### PR TITLE
Mark the delivery thread daemonic.

### PR DESCRIPTION
**Pull request by benjaminp**
@veblush

### CODE REVIEW

**Comment by gnossen** [comment]
@benjaminp Interesting. What sort of problems were you seeing?

**Comment by benjaminp** [comment]
These delivery threads are implicated in interpreter shutdown hangs.

**Comment by benjaminp** [comment]
(Already most of the threads created by `_channel.py` do `setDaemon(True)`. Is there a rationale or daemon vs. non-daemon?)

**Comment by gnossen** [comment]
@benjaminp Thank you for the contribution!

**Comment by benjaminp** [comment]
Thank you for the reviews.

**Pull request merged**
