### PR TITLE
Correctly count port indices and siblings.

### PR DESCRIPTION
**Pull request by daniel-j-born**
In the old code, the check for "port_index != 0" and "--port_index" is a bug: we want to advance to the next non-sibling grpc_tcp_listener\* to get the batch for port_index, rather than just the next grpc_tcp_listener*. get_port_index() is the correct way.

This was easier to test in PR#7047, because it created many listeners at the same port. The current test coverage isn't great, because the test creates no siblings, but tcp_server_posix_test.c has some coverage.

### CODE REVIEW

**Comment by y-zeng** [comment]
Please resolve merge conflicts.

**Comment by daniel-j-born** [comment]
I did the merge, but tests fail when I try to run them locally:

$ tools/run_tests/run_tests.py  -lc

make: *** No rule to make target `include/grpc/impl/codegen/time.h', needed by `/usr/local/google/home/dborn/github/daniel-j-born/grpc/objs/opt/test/core/util/test_config.o'.  Stop.
FAILED: make [ret=2, pid=3342]
FAILED: Some tests failed

**Comment by ctiller** [comment]
make clean?

**Comment by daniel-j-born** [comment]
Local make clean && run_tests.py -lc success.

**Comment by y-zeng** [comment]
Clang format isn't happy.

**Comment by daniel-j-born** [comment]
clang-reformatted.

**Comment by y-zeng** [comment]
Test failures seem unrelated.

**Pull request merged**
