### PR TITLE
Update xcode version for macOS Obj-C tests to 9.2

### LINKED ISSUE #15072: objc tests on macOS broken by Kokoro migration
Seems broken by migration to kokoro distrib. master (perhaps the MacOS images are different?).

Broken both on dbg and opt
https://source.cloud.google.com/results/invocations/4f1f0cdb-9c3c-4e7f-a41a-c20bd3e34137/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests
https://source.cloud.google.com/results/invocations/c21ae9e2-106e-4502-9aa9-bc5b5e74a09f/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests
https://source.cloud.google.com/results/invocations/e5455b10-d6fd-4fcc-8ec5-a63c6525fe5a/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests

```
dyld: Symbol not found: _OBJC_CLASS_$_FBSDisplay
  Referenced from: /Applications/Xcode_8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/IBCocoaTouchToolFoundation.framework/IBCocoaTouchToolFoundation
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 in /Applications/Xcode_8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/IBCocoaTouchToolFoundation.framework/IBCocoaTouchToolFoundation
2018-04-16 02:12:01.046 ibtoold[89961:1144383] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEInterfaceBuilder/IDEInterfaceBuilder-11762/InterfaceBuilderKit/Utilities/IBAbstractInterfaceBuilderPlatformToolManager.m:254
Details:  Failed to attach to Interface Builder Cocoa Touch Tool with error: Error Domain=com.apple.InterfaceBuilder Code=-1 "Encountered an error communicating with Interface Builder Cocoa Touch Tool." UserInfo={NSUnderlyingError=0x7f8e6e131aa0 {Error Domain=com.apple.InterfaceBuilder Code=-1 "Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn" UserInfo={NSLocalizedDescription=Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn, NSUnderlyingError=0x7f8e6e131c90 {Error Domain=com.apple.InterfaceBuilder Code=-1 "Failed to handshake with platform tool" UserInfo={NSUnderlyingError=0x7f8e6e10d2a0 {Error Domain=com.apple.InterfaceBuilder Code=-1 "" UserInfo=0x7f8e6e1398e0 (not displayed)}, NSLocalizedFailureReason=Failed to open connection over FIFOs with platform tool, NSLocalizedDescription=Failed to handshake with platform tool}}}}, NSLocalizedDescription=Encountered an error communicating with Interface Builder Cocoa Touch Tool., NSLocalizedRecoverySuggestion=Please check Console.app for crash reports for "Interface Builder Cocoa Touch Tool" for further information., NSLocalizedFailureReason=Interface Builder Cocoa Touch Tool (91446) failed to launch and exited with status 6}
Object:   <IBCocoaTouchToolManager>
Method:   +_THREADSAFE_launchNewToolWithLaunchContext:executionContext:toolProxyClass:failureContext:requestingMethod:error:forReason:
Thread:   <NSThread: 0x7f8e6cd18710>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2018-04-16 02:12:01.047 ibtoold[89961:1144383] [MT] IBPlatformTool: *** Failed to launch tool with description <IBCocoaTouchPlatformToolDescription: 0x7f8e6e25f550> System content 2x for IBCocoaTouchFramework-NineOneAndLater w/ default fidelity: Encountered an error communicating with Interface Builder Cocoa Touch Tool. (Failure reason: Interface Builder Cocoa Touch Tool (91446) failed to launch and exited with status 6): Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn: Failed to handshake with platform tool (Failure reason: Failed to open connection over FIFOs with platform tool): : Failed to open FIFOs for handshaking with platform tool (Failure reason: Interface Builder Cocoa Touch Tool exited before we could handshake)
2018-04-16 02:12:02.066 ibtoold[89961:1144383] [MT] IBPlatformTool: Wrote failed marshalling request diagnostics to path: /var/folders/yh/crtc3sq52n34tstm39cljbcr0000gn/T/IB-agent-diagnostics_2018-04-16_02-12-02_057000
/* com.apple.ibtool.errors */
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/examples/objective-c/auth_sample/Misc/Base.lproj/Main.storyboard: error: Internal error. Please file a bug at bugreport.apple.com and attach "/var/folders/yh/crtc3sq52n34tstm39cljbcr0000gn/T/IB-agent-diagnostics_2018-04-16_02-12-02_057000".
    Recovery Suggestion: Please check Console.app for crash reports for "Interface Builder Cocoa Touch Tool" for further information.
    Underlying Errors:
        Description: Encountered an error communicating with Interface Builder Cocoa Touch Tool.
        Failure Reason: Interface Builder Cocoa Touch Tool (91446) failed to launch and exited with status 6
        Recovery Suggestion: Please check Console.app for crash reports for "Interface Builder Cocoa Touch Tool" for further information.
        Underlying Errors:
            Description: Failed to launch Interface Builder Cocoa Touch Tool via CoreSimulator spawn
            Underlying Errors:
                Description: Failed to handshake with platform tool
                Failure Reason: Failed to open connection over FIFOs with platform tool
                Underlying Errors:
                    Description:
                    Recovery Suggestion: Try restarting your computer
                    Underlying Errors:
                        Description: Failed to open FIFOs for handshaking with platform tool
                        Failure Reason: Interface Builder Cocoa Touch Tool exited before we could handshake
CompileAssetCatalog /Users/kbuilder/Library/Developer/Xcode/DerivedData/AuthSample-avhbvfsdaqcxnlhjheomlltvzteo/Build/Products/Debug-iphonesimulator/AuthSample.app Misc/Images.xcassets
    /Applications/Xcode_8.2.1.app/Contents/Developer/usr/bin/actool --output-format human-readable-text --notices --warnings --export-dependency-info /Users/kbuilder/Library/Developer/Xcode/DerivedData/AuthSample-avhbvfsdaqcxnlhjheomlltvzteo/Build/Intermediates/AuthSample.build/Debug-iphonesimulator/AuthSample.build/assetcatalog_dependencies --output-partial-info-plist /Users/kbuilder/Library/Developer/Xcode/DerivedData/AuthSample-avhbvfsdaqcxnlhjheomlltvzteo/Build/Intermediates/AuthSample.build/Debug-iphonesimulator/AuthSample.build/assetcatalog_generated_info.plist --app-icon AppIcon --compress-pngs --enable-on-demand-resources YES --filter-for-device-model iPhone7,2 --filter-for-device-os-version 11.1 --sticker-pack-identifier-prefix .sticker-pack. --target-device iphone --target-device ipad --minimum-deployment-target 8.3 --platform iphonesimulator --product-type com.apple.product-type.application --compile /Users/kbuilder/Library/Developer/Xcode/DerivedData/AuthSample-avhbvfsdaqcxnlhjheomlltvzteo/Build/Products/Debug-iphonesimulator/AuthSample.app /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/examples/objective-c/auth_sample/Misc/Images.xcassets
```

### PR DESCRIPTION
**Pull request by matt-kwong**
This is the latest xcode version available on Kokoro macOS Sierra workers. 

Fixes #15072

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Looks like ObjC passed. The failure is in C#.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by matt-kwong** [comment]
macOS C# failures: #15103
Interop: #14969

**Pull request merged**
