### PR TITLE
Add long_description with setup.cfg for grpcio_tools

### PR DESCRIPTION
**Pull request by yanqd0**
This is an update for grpc/grpc#16457 .

### CODE REVIEW

**Comment by yanqd0** [comment]
This is not necessary. There is not conflict.

**Comment by yanqd0** [comment]
This is reopened to update a better solution with `setup.cfg`.

**Comment by yanqd0** [comment]
There are 3 cases in Windows failed. I can not understand why, even after I checked logs.

This PR changes the packaging procedure of grpcio_tools, which should be no side effect.

**Comment by gnossen** [comment]
Closing and reopening to retrigger the CLA bot.

**Comment by yanqd0** [comment]
Thanks.

The master seems unstable. I will try it later.

**Comment by gnossen** [comment]
@yanqd0 No need to close and reopen again. That was due to a one-time failure in the CLA bot, which is now passing.

**Pull request closed without merging**
