### PR TITLE
Added verbose option to run_interop_test to ease tracing the commands…

### PR DESCRIPTION
**Pull request by yongni**
… invoked

Sample output

yongni@canaan:~/github/grpc/tools/run_tests$ ./run_interop_tests.py -l java --use_docker -v --cloud_to_prod --manual_run
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
**Jobs to run: 
build_docker_java: TTY_FLAG=-t INTEROP_IMAGE=grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b BASE_NAME=grpc_interop_java tools/run_tests/dockerize/build_interop_image.sh**

PASSED: build_docker_java [time=37.3sec; retries=0:0]
SUCCESS: All docker images built successfully.
All tests will skipped --manual_run option is active.
**Jobs to run: 
cloud_to_prod:default:java:large_unary:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_84ee44de-8c4d-4d85-97f6-f0cc28862134 grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=large_unary
cloud_to_prod:default:java:empty_unary:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_64244d49-b815-4977-9134-c18aa5464369 grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=empty_unary
cloud_to_prod:default:java:ping_pong:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_806df682-d426-4c48-bcc9-874b9e3e74dd grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=ping_pong
cloud_to_prod:default:java:empty_stream:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_803f4db4-fb90-4286-86e8-676bb40b3629 grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=empty_stream
cloud_to_prod:default:java:client_streaming:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_62800952-f465-4f4f-8208-cfb74bbbf3c6 grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=client_streaming
cloud_to_prod:default:java:server_streaming:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_6ae44bf2-7363-40aa-a558-aa7e92df45b6 grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=server_streaming
cloud_to_prod:default:java:cancel_after_begin:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_4019fa09-85ad-4f06-bcd1-940b124e62ce grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=cancel_after_begin
cloud_to_prod:default:java:cancel_after_first_response:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_9bfac72c-e29f-46f0-b555-357dde29e34d grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=cancel_after_first_response
cloud_to_prod:default:java:timeout_on_sleeping_server:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_150d2b41-6c20-4d0b-8af3-f98233c702be grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com --server_port=443 --use_tls=true --test_case=timeout_on_sleeping_server**

SKIPPED: cloud_to_prod:default:java:large_unary
SKIPPED: cloud_to_prod:default:java:empty_unary
SKIPPED: cloud_to_prod:default:java:ping_pong
SKIPPED: cloud_to_prod:default:java:empty_stream
SKIPPED: cloud_to_prod:default:java:client_streaming
SKIPPED: cloud_to_prod:default:java:server_streaming
SKIPPED: cloud_to_prod:default:java:cancel_after_begin
SKIPPED: cloud_to_prod:default:java:cancel_after_first_response
SKIPPED: cloud_to_prod:default:java:timeout_on_sleeping_server
SUCCESS: All tests passed
Command log written to file interop_client_cmds.sh
Preserving docker image: grpc_interop_java:c902c076-12fa-46ce-9032-f045e584045b

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by jtattermusch** [comment]
test this please

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by yongni** [comment]
The -v show the env and native commands for docker build.

Tested with and without -v
yongni@canaan:~/github/grpc/tools/run_tests$ ./run_interop_tests.py -l java --use_docker -v --cloud_to_prod
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
Jobs to run: 
build_docker_java: TTY_FLAG=-t INTEROP_IMAGE=grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 BASE_NAME=grpc_interop_java tools/run_tests/dockerize/build_interop_ima
ge.sh

PASSED: build_docker_java [time=50.8sec; retries=0:0]
SUCCESS: All docker images built successfully.
Jobs to run: 
cloud_to_prod:default:java:large_unary:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_3f73bb45-2a58-4bd4-a113-518807b5
4450 grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.c
om --server_port=443 --use_tls=true --test_case=large_unary
cloud_to_prod:default:java:empty_unary:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_9e5e39f3-53ec-4b3c-ab07-aa38293a
77d0 grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.c
om --server_port=443 --use_tls=true --test_case=empty_unary
cloud_to_prod:default:java:ping_pong:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_589f8f6a-664a-4bb2-97ed-efbad2b22e
f2 grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.com
 --server_port=443 --use_tls=true --test_case=ping_pong
cloud_to_prod:default:java:empty_stream:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_911b0a6c-97a8-4c8f-b0ff-81a31bc
c5048 grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googleapis.
com --server_port=443 --use_tls=true --test_case=empty_stream
cloud_to_prod:default:java:client_streaming:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_40cfd2e9-6d7e-4419-81b4-117
c2c13bd81 grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googlea
pis.com --server_port=443 --use_tls=true --test_case=client_streaming
cloud_to_prod:default:java:server_streaming:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_413075ef-445a-4737-9d05-b83
27d786f4c grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googlea
pis.com --server_port=443 --use_tls=true --test_case=server_streaming
cloud_to_prod:default:java:cancel_after_begin:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_27402a41-ddf5-4d4a-a6d3-4
95b6843af8d grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandbox.googl
eapis.com --server_port=443 --use_tls=true --test_case=cancel_after_begin
cloud_to_prod:default:java:cancel_after_first_response:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_77d7f92d-e408-42
6b-8915-073485cd0504 grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sand
box.googleapis.com --server_port=443 --use_tls=true --test_case=cancel_after_first_response
cloud_to_prod:default:java:timeout_on_sleeping_server:  docker run -i --rm=true -w /var/local/git/grpc/../grpc-java --net=host --name=interop_client_java_ddf5a2ff-f6b6-498
a-bd92-d3b009aa5059 grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126 bash -c ./run-test-client.sh --server_host=216.239.32.254 --server_host_override=grpc-test.sandb
ox.googleapis.com --server_port=443 --use_tls=true --test_case=timeout_on_sleeping_server

PASSED: cloud_to_prod:default:java:large_unary [time=10.5sec; retries=0:0]
PASSED: cloud_to_prod:default:java:timeout_on_sleeping_server [time=11.1sec; retries=0:0]
PASSED: cloud_to_prod:default:java:cancel_after_begin [time=12.1sec; retries=0:0]
PASSED: cloud_to_prod:default:java:empty_unary [time=12.7sec; retries=0:0]
PASSED: cloud_to_prod:default:java:ping_pong [time=13.7sec; retries=0:0]
PASSED: cloud_to_prod:default:java:server_streaming [time=14.2sec; retries=0:0]
PASSED: cloud_to_prod:default:java:client_streaming [time=14.8sec; retries=0:0]
PASSED: cloud_to_prod:default:java:empty_stream [time=15.2sec; retries=0:0]
PASSED: cloud_to_prod:default:java:cancel_after_first_response [time=15.4sec; retries=0:0]
SUCCESS: All tests passed
Removing docker image grpc_interop_java:bbe2a827-aa3a-4f58-9865-f8597ea79126



yongni@canaan:~/github/grpc/tools/run_tests$ ./run_interop_tests.py -l java --use_docker --cloud_to_prod                                                                   
Seen --use_docker flag, will run interop tests under docker.

IMPORTANT: The changes you are testing need to be locally committed
because only the committed changes in the current branch will be
copied to the docker environment.
START: Building interop docker images.
PASSED: build_docker_java [time=36.0sec; retries=0:0]
SUCCESS: All docker images built successfully.
PASSED: cloud_to_prod:default:java:empty_stream [time=9.4sec; retries=0:0]
PASSED: cloud_to_prod:default:java:server_streaming [time=10.1sec; retries=0:0]
PASSED: cloud_to_prod:default:java:ping_pong [time=10.6sec; retries=0:0]
PASSED: cloud_to_prod:default:java:cancel_after_begin [time=11.5sec; retries=0:0]
PASSED: cloud_to_prod:default:java:empty_unary [time=12.1sec; retries=0:0]
PASSED: cloud_to_prod:default:java:timeout_on_sleeping_server [time=12.6sec; retries=0:0]
PASSED: cloud_to_prod:default:java:cancel_after_first_response [time=13.0sec; retries=0:0]
PASSED: cloud_to_prod:default:java:large_unary [time=13.4sec; retries=0:0]
PASSED: cloud_to_prod:default:java:client_streaming [time=13.5sec; retries=0:0]
SUCCESS: All tests passed
Removing docker image grpc_interop_java:1d6458ee-8ed2-425e-85e6-6492a5723cb8
yongni@canaan:~/github/grpc/tools/run_tests$

**Comment by yongni** [comment]
issues: #10836

**Pull request merged**
