### PR TITLE
Update debian source instruction

### PR DESCRIPTION
**Pull request by stanley-cheung**
Change unstable to testing.

Previously #2990

### CODE REVIEW

**Comment by tbetbetbe** [comment]
Have you any idea why the jenkins build here is red?

**Comment by stanley-cheung** [comment]
Things just timed out, during simply the checkout from git step - it's happening quite frequently on Jenkins recently. This PR only touches text files so it should not have broken the build.

**Comment by stanley-cheung** [comment]
Rebuilt, mostly green now. I find that it's much easier off office-hours.

**Comment by tbetbetbe** [comment]
Updates instructions to reflect latest status on #662

**Pull request merged**
