### PR TITLE
Fix error messages.

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
I think the project files need to be re-generated after a merge... Sorry ^^

**Comment by yang-g** [comment]
Green enough?

**Comment by ctiller** [comment]
Needs a merge. Can you follow this up by hitting the channel args in chttp2_transport.c?

You may need to borrow some code from the connectivity_state.c end2end test to get the channel connected.

**Comment by yang-g** [comment]
Merged. That could be in another PR?

**Pull request merged**
