### PR TITLE
Fix pypa link

### PR DESCRIPTION
**Pull request by gnossen**
```
+ curl https://bootstrap.pypa.io/2.7/get-pip.py
+ /t/src/github/grpc/workspace_python_windows_opt_asyncio/py38_asyncio/Scripts/python.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100   936  100   936    0     0    312      0  0:00:03  0:00:03 --:--:--   261

Hi there!

The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:

    https://bootstrap.pypa.io/pip/2.7/get-pip.py
```

Generated with:

```
grep -rl "bootstrap.pypa.io/2.7/get-pip.py" | xargs sed -i 's|bootstrap.pypa.io/2.7/get-pip.py|bootstrap.pypa.io/pip/2.7/get-pip.py|g
```

### CODE REVIEW

**Comment by veblush** [comment]
@gnossen Thanks for the quick fix! You might need to update the docker images.

**Review by lidizheng — APPROVED** [review]
LGTM if the tests are green.

**Comment by lidizheng** [comment]
@gnossen Can you also create a backport PR to branch `v1.36.x`? If this is breaking HEAD, then it will break the interop image generation as well.

**Comment by gnossen** [comment]
Failures:
 - https://github.com/grpc/grpc/issues/25652
 - https://github.com/grpc/grpc/issues/25124

**Pull request merged**
