### PR TITLE
Try fixing macos build breakage: upgrade google-api-python-client

### PR DESCRIPTION
**Pull request by jtattermusch**
attempt to fix https://github.com/grpc/grpc/issues/15600

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
doesn't seem to help,  https://github.com/grpc/grpc/pull/15602 might be better.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
