### PR TITLE
Use prebuilt ruby artifact docker image from dockerhub

### PR DESCRIPTION
**Pull request by apolcyn**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
artifact build based off of this branch was successful: https://grpc-testing.appspot.com/job/gRPC_build_artifacts/1097/platform=linux/artifact/artifacts/

**Comment by apolcyn** [comment]
portability tests failed with infrastructure failure:
* `ssh_exchange_identification: Connection closed by remote host`

* asan c++: https://github.com/grpc/grpc/issues/12313
* c++ linux dbg: https://github.com/grpc/grpc/issues/12510
* c++ opt linux: https://github.com/grpc/grpc/issues/12313
* mac tests didn't run in opt: `Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)`
* node failures: https://github.com/grpc/grpc/issues/13073
* windows: https://github.com/grpc/grpc/issues/12858
* kokoro cloud-to-cloud/prod interop failed with kokoro infarstructure failure (I believe this is an issue with this branch not being master): `com.google.devtools.kokoro.config.ConfigException`

**Pull request merged**
