### PR TITLE
Flagging unlikely branches.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Again, trying out microbenchmarks until we have hotspot info.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.0%     -18 [None]                                                                                  -538  -0.0%
  -0.4%     -46 src/core/ext/transport/chttp2/transport/hpack_parser.cc                                  -46  -0.4%
      [DEL]    -292 take_string(grpc_chttp2_hpack_parser*, grpc_chttp2_hpack_parser_string*, bool) [clon    -292  [DEL]
      -7.5%     -28 [Unmapped]                                                                               -28  -7.5%
      -2.0%     -14 grpc_chttp2_header_parser_parse                                                          -14  -2.0%
      -3.5%      -9 parse_value5up                                                                            -9  -3.5%
      -4.1%      -8 finish_max_tbl_size                                                                       -8  -4.1%
      -1.8%      -8 finish_lithdr_notidx                                                                      -8  -1.8%
      -1.8%      -8 finish_lithdr_nvridx                                                                      -8  -1.8%
      -2.4%      -8 finish_lithdr_notidx_v                                                                    -8  -2.4%
      -2.4%      -8 finish_lithdr_nvridx_v                                                                    -8  -2.4%
      -3.6%      -6 huff_nibble                                                                               -6  -3.6%
      -2.8%      -3 add_huff_bytes                                                                            -3  -2.8%

  -0.0%     -64 TOTAL                                                                                   -584  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
This did not have any noticeable performance impact

**Pull request closed without merging**
