### PR TITLE
Improve Python installation story

### PR DESCRIPTION
**Pull request by soltanmm**
Enables binary distribution submission to PyPI et al., warns on the non-existence of Python protobuf (instead of failing), and adds hooks for handling different C compiler versions by checking the compiler Python is about to use instead of guessing from the operating system.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Change content looks good; test results continue to look crazy. :-( Poke when green or green enough?

**Comment by ctiller** [comment]
Let's get the sanity tests to pass (will minimally need #4686 merged)

**Comment by soltanmm** [comment]
Python green. Sanity is broken on copyright headers, but frankly given how long it takes for Jenkins to finish tests in recent days, I'm against fixing them in this PR unless we can all agree that we won't wait for the tests to run again for just that change.

**Comment by ctiller** [comment]
Jenkins is fast now.

**Comment by ctiller** [comment]
This looks green enough to me

**Pull request merged**
