### PR TITLE
Update Channel.cs

### PR DESCRIPTION
**Pull request by AdamLeMmon01**
Simple spelling or wording fixes to make comments read more cleanly

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @AdamLeMmon01 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by AdamLeMmon01** [comment]
I have completed the CLA form

**Comment by jtattermusch** [comment]
@AdamLeMmon01  the CLA check is still failing.

**Comment by AdamLeMmon01** [comment]
I signed it

**Comment by AdamLeMmon01** [comment]
I am uncertain why the two remaining checks are unsuccessful. Can I get some help getting this to build and pass checks?

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/18477

**Pull request merged**
