### PR TITLE
Fix handling of call context in health check call batch payload.

### PR DESCRIPTION
**Pull request by markdroth**
This fixes an internal test failure.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                         FILE SIZE
 ++++++++++++++ GROWING                                                           ++++++++++++++
  +0.2%     +16 src/core/ext/filters/client_channel/health/health_check_client.cc     +16  +0.2%
      +4.0%      +8 [Unmapped]                                                             +8  +4.0%
      +0.5%      +8 grpc_core::HealthCheckClient::CallState::StartCall                     +8  +0.5%

 -+-+-+-+-+-+-+ MIXED                                                             +-+-+-+-+-+-+-
  +0.0%     +16 [None]                                                                -16  -0.0%

  +0.0%     +32 TOTAL                                                                   0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,303      Total (=)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,480      Total (<)     11,115,484

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                         FILE SIZE
 ++++++++++++++ GROWING                                                           ++++++++++++++
  +0.0%     +24 [None]                                                               +112  +0.0%
  +0.6%     +48 src/core/ext/filters/client_channel/health/health_check_client.cc     +48  +0.6%
      +9.6%     +24 grpc_core::HealthCheckClient::CallState::~CallState                   +24  +9.6%
      +8.1%     +16 [Unmapped]                                                            +16  +8.1%
      +0.5%      +8 grpc_core::HealthCheckClient::CallState::StartCall                     +8  +0.5%

  +0.0%     +72 TOTAL                                                                +160  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,383      Total (>)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,473      Total (<)     11,115,477

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
@AspirinSJL, please take another look, since I've added another fix (for a memory leak) and changed our tests to catch these problems.  Thanks!

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                         FILE SIZE
 ++++++++++++++ GROWING                                                           ++++++++++++++
  +0.0%     +24 [None]                                                               +112  +0.0%
  +0.6%     +48 src/core/ext/filters/client_channel/health/health_check_client.cc     +48  +0.6%
      +9.6%     +24 grpc_core::HealthCheckClient::CallState::~CallState                   +24  +9.6%
      +8.1%     +16 [Unmapped]                                                            +16  +8.1%
      +0.5%      +8 grpc_core::HealthCheckClient::CallState::StartCall                     +8  +0.5%

  +0.0%     +72 TOTAL                                                                +160  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.6%    +270 src/cpp/server/server_cc.cc                                                             +270  +0.6%
      +143%    +254 grpc::internal::CallOpSet<grpc::internal::CallOpRecvMessage<grpc::ByteBuffer>, grpc:    +254  +143%
      [NEW]     +51 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>::Deserialize                    +51  [NEW]
      [NEW]     +51 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>::Deserialize                     +51  [NEW]

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  +0.0%     +42 [None]                                                                                   -62  -0.0%

  +0.1%    +312 TOTAL                                                                                   +208  +0.0%



```

**Comment by AspirinSJL** [comment]
These changes look good to me!

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                         FILE SIZE
 ++++++++++++++ GROWING                                                           ++++++++++++++
  +0.0%     +24 [None]                                                               +112  +0.0%
  +0.6%     +48 src/core/ext/filters/client_channel/health/health_check_client.cc     +48  +0.6%
      +9.6%     +24 grpc_core::HealthCheckClient::CallState::~CallState                   +24  +9.6%
      +8.1%     +16 [Unmapped]                                                            +16  +8.1%
      +0.5%      +8 grpc_core::HealthCheckClient::CallState::StartCall                     +8  +0.5%

  +0.0%     +72 TOTAL                                                                +160  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,383      Total (>)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,474      Total (<)     11,115,478

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,383      Total (>)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,476      Total (<)     11,115,480

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
The test failures all look like infrastructure issues.

**Pull request merged**
