### PR TITLE
Delete unused TIMEOUT enum in end2end tests

### PR DESCRIPTION
**Pull request by rjshade**

### CODE REVIEW

**Comment by rjshade** [comment]
@yang-g can you take a look at this?

**Comment by yang-g** [comment]
LGTM

**Comment by yang-g** [comment]
test this please

**Comment by rjshade** [comment]
@yang-g ping?

**Comment by yang-g** [comment]
It seems clang-format is not happy, could you fix that? Thanks.

**Comment by rjshade** [comment]
Done.

**Pull request merged**
