### PR TITLE
Fix typo in Python test harness

### PR DESCRIPTION
**Pull request by soltanmm**
Embarrassing.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Should this change have been made against the `release-0_12` branch?

**Comment by soltanmm** [comment]
Eep, didn't that already get cut?

**Comment by nathanielmanistaatgoogle** [comment]
It did - do we want this fix there too?

**Comment by soltanmm** [comment]
Yes. I'll make another PR.

**Pull request merged**
