### PR TITLE
Update Node interop test invocation to use new fixtures

### PR DESCRIPTION
**Pull request by murgatroid99**
Fixes grpc/grpc-node#89.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by murgatroid99** [comment]
The interop cloud-to-cloud failure is a Node server failing because of #12932. But most of the tests against that server passed, which implies that this fix for the invocation of that server is working properly.

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_unary_ping_pong.BM_UnaryPingPong_InProcessCHTTP2_NoOpMutator_Server_AddInitialMetadata_RandomAsciiMetadata_10__1___0_0.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by murgatroid99** [comment]
Known failures: #13270, #13381, #12932, #13404, #13178, #13122.

The portability tests are failing due to a known issue. @nicolasnoble can you merge this as an admin?

**Comment by jtattermusch** [comment]
I re-ran the portability linux test suite, it's possible to merge now. Merging.

**Pull request merged**
