### PR TITLE
Fix building ruby artifact

### PR DESCRIPTION
**Pull request by jtattermusch**
Partial fix for #8318

### CODE REVIEW

**Comment by dgquintas** [comment]
I'm curious, which compiler is complaining about this? It used to be windows giving trouble with `%zu`, but not gcc. The `%zu` syntax is C99

**Comment by jtattermusch** [comment]
It's ruby crosscompilation for windows, so I thinks it's mingw targetting windows (that's why %z is not allowed).

https://github.com/grpc/grpc/blob/master/tools/run_tests/build_artifact_ruby.sh

**Comment by dgquintas** [comment]
Oh well...

**Comment by jtattermusch** [comment]
Checked the test failures and they seem unrelated.

**Pull request merged**
