### PR TITLE
Upmerge v1.4.x to master

### PR DESCRIPTION
**Pull request by murgatroid99**
The only substantial manual merge was in the file `src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.c`.

### CODE REVIEW

**Comment by murgatroid99** [comment]
Done.

**Comment by markdroth** [comment]
@dgquintas, shouldn't the changes to `round_robin.c` be reverted in favor of your #11604?

**Comment by dgquintas** [comment]
@markdroth ah, yes! Thank you for catching that.

**Comment by murgatroid99** [comment]
OK, I redid the merge with no changes to `round_robin.c`.

**Comment by murgatroid99** [comment]
The Mac failures are #11223. The Windows failure is #11383. And the interop failure should be fixed by grpc/grpc-java/#3188.

**Pull request merged**
