### PR TITLE
Bump python protobuf dependency to 3.0.0

### PR DESCRIPTION
**Pull request by kpayson64**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Thanks!

Your commit log message should make clear why `requirements.txt`, `src/python/grpcio_health_checking/setup.py`, and `src/python/grpcio_tests/setup.py` are left out of this change. Also the " (GA)" isn't quite working for me, since as much as _we've_ used the term to refer to _our_ 1.0.0 release, I don't think I've ever heard them use the term to refer to their 3.0.0 release.

**Comment by kpayson64** [comment]
I've updated the dependency in ```requirements.txt``` and ```src/python/grpcio_tests/setup.py```.  ```grpcio_health_checking``` did not have a direct dependency on protobuf.

**Comment by nathanielmanistaatgoogle** [comment]
I think `grpcio_health_checking` should be given a direct dependency on protobuf; its code imports at least one `_pb2` module and we know that that module will import from `google.protobuf`.

**Comment by kpayson64** [comment]
Added explicit protobuf dependency to grpcio_health_checking

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum and thank you.

**Pull request merged**
