### PR TITLE
CMake: Enable building of test targets

### PR DESCRIPTION
**Pull request by jtattermusch**
Based on https://github.com/grpc/grpc/pull/9361

Expose gRPC_BUILD_TESTS cmake option (default is OFF).
When ON, cmake builds targets of type 'test' as well.

Selection of interesting targets that can now be built with cmake (on linux):
interop_server, interop_client, qps_worker, grpc_cli, ...

### CODE REVIEW

**Comment by jtattermusch** [comment]
I added a few fixes for CMake on windows. Things seem to work but there is a couple unrelated build errors in interop_server, interop_client, qps_worker, .. I'll try to address them separately.

**Comment by matt-kwong** [comment]
It looks like the sanity test failures are related to your fork being behind gRPC master. After rebasing your branch and regenerating, it should look good.

**Comment by jtattermusch** [comment]
@matt-kwong  rebased and regenerated. The sanity test should be now passing.

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/9398
https://github.com/grpc/grpc/issues/9399

**Pull request merged**
