### PR TITLE
Updated travis to use Xcode 7.2 and SDK 9.2

### PR DESCRIPTION
**Pull request by makdharma**
Updated travis to use Xcode 7.2 and SDK 9.2

### CODE REVIEW

**Comment by jcanizales** [comment]
So the interop tests fail now, for something most probably unrelated to this change:
`subchannel_index.c:59] assertion failed: gpr_tls_get(&subchannel_index_exec_ctx) == 0`

**Comment by pgrosu** [comment]
Hi Jorge,

There is a major change going to 7.2 - we've gone through some of this troubleshooting previously at the following issue in [protobuf](https://github.com/google/protobuf/issues/1253):

https://github.com/google/protobuf/issues/1253

Maybe running the build via `sudo` might help to bypass the security checks in 10.11.

Hope it helps,
Paul

**Comment by jcanizales** [comment]
Thanks for the heads-up, Paul. Vasilis is finding the same assert error when running ObjC examples locally (#5367), so it looks to me like this needs a fix in the C library. I'm creating an issue for it.

**Comment by jcanizales** [comment]
PR #5390 fixed it, so I'll rerun Travis and hopefully merge now :)

**Comment by jcanizales** [comment]
:rocket:

**Comment by pgrosu** [comment]
Sure thing Jorge, keeping my fingers crossed :)

**Pull request merged**
