### PR TITLE
Add comment to keep Dockerfile up to date against oss-fuzz

### PR DESCRIPTION
**Pull request by yang-g**
Ref: https://github.com/google/oss-fuzz/pull/2096

### CODE REVIEW

**Comment by jtattermusch** [comment]
Sanity test failing (looks like the docker file template needs to be updated too).

**Comment by yang-g** [comment]
Yes, thanks. I did not know that... Updated and let's see how it goes.

**Comment by yang-g** [comment]
Now it seems unable to find the docker image because the file's sha1sum has changed. Specifically it is failing here: https://github.com/grpc/grpc/blob/e4f1bb165e87ff6f679e02ba945a3871839b1df7/tools/run_tests/dockerize/build_and_run_docker.sh#L45 for `Error response from daemon: pull access denied for grpctesting/bazel_455f565930c239c21ade5c14455737bd38fe6f38, repository does not exist or may require 'docker login'`

Do I need to do something else to build/publish a new image or something?

**Comment by yang-g** [comment]
With the help from Nicolas, I built and pushed a new image. I just triggered a re-build of the bazel test.

**Comment by yang-g** [comment]
Test failure is: #17779

**Pull request merged**
