### PR TITLE
Create binder transport folder

### PR DESCRIPTION
**Pull request by sifmelcara**
Hi! I'm mingcl@, as mentioned in today's meeting with @nicolasnoble , this is the first commit to create the folders for the project.

More documentations and tests will be added in sub-directories later

### CODE REVIEW

**Comment by sifmelcara** [comment]
Tests: Ran `tools/run_tests/run_tests.py` locally and worked as expected

**Comment by sifmelcara** [comment]
cc @ctiller @markdroth @napathome @waynetu @LittleCVR @Rokya

**Comment by ctiller** [comment]
This seems fine to me, but would like someone more familiar with our build system as it stands today to take a look.

**Comment by sifmelcara** [comment]
(rebased on latest master)

**Review by grpc-google-owners — APPROVED** [review]

**Pull request merged**
