### PR TITLE
Prefer using https_proxy for secure channels and http_proxy for insec…

### LINKED ISSUE #9561: CONNECT: use `HTTPS_PROXY` instead of `http_proxy`
Today it [seems the code is using `http_proxy`](https://github.com/grpc/grpc/blob/d58a985/src/core/ext/client_channel/http_proxy.c). That is a commonly used environment variable for enabling a forward proxy, but it is generally for _http_ (no s) connections. The distinction is because http forward proxying does not use CONNECT whereas https does.

Note that we would get to choose which case of the environment variable to use. For example, curl uses upper case whereas wget uses lower. I don't know which convention is more widely used.

### PR DESCRIPTION
**Pull request by yashykt**
Prefer using https_proxy over http_proxy.
If https_proxy is missing but http_proxy is provided instead, fallback on http_proxy so as to not to break existing usecases.

Fixes #9561

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/15698)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +2.8%     +48 src/core/ext/filters/client_channel/http_proxy.cc     +48  +2.8%
      +3.8%     +62 proxy_mapper_map_name                                 +62  +3.8%

 -+-+-+-+-+-+-+ MIXED                                             +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                            +2.55Ki  +0.0%

  +0.0%     +32 TOTAL                                             +2.59Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +2.8%     +48 src/core/ext/filters/client_channel/http_proxy.cc     +48  +2.8%
      +3.8%     +62 proxy_mapper_map_name                                 +62  +3.8%

 -+-+-+-+-+-+-+ MIXED                                             +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                            +2.55Ki  +0.0%

  +0.0%     +32 TOTAL                                             +2.59Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +0.0%     +16 [None]                                            +2.55Ki  +0.0%
  +2.8%     +48 src/core/ext/filters/client_channel/http_proxy.cc     +48  +2.8%
      +3.8%     +62 proxy_mapper_map_name                                 +62  +3.8%

  +0.0%     +64 TOTAL                                             +2.59Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  [ = ]       0 [None]                                            +2.58Ki  +0.0%
  +3.7%     +64 src/core/ext/filters/client_channel/http_proxy.cc     +64  +3.7%
      +4.7%     +78 proxy_mapper_map_name                                 +78  +4.7%

  +0.0%     +64 TOTAL                                             +2.64Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  [ = ]       0 [None]                                            +2.58Ki  +0.0%
  +3.7%     +64 src/core/ext/filters/client_channel/http_proxy.cc     +64  +3.7%
      +4.7%     +78 proxy_mapper_map_name                                 +78  +4.7%

  +0.0%     +64 TOTAL                                             +2.64Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
This looks reasonable, but I am concerned about the dependency on the security code.

---

Reviewed 4 of 13 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 6 of 6 files at r4.
Review status: all files reviewed, 4 unresolved discussions (waiting on @yashykt, @dgquintas, and @AspirinSJL)

---

*[BUILD, line 1071 at r4](https://reviewable.io/reviews/grpc/grpc/15698#-LEu-ntQAa_FbW0QaGG7:-LEu-ntQAa_FbW0QaGG8:b-ouvjcf) ([raw file](https://github.com/grpc/grpc/blob/2a8e2ec4a787247e95bc7cfcd52aa4f7f6a4a086/BUILD#L1071)):*
> ```Python
>         "src/core/ext/filters/client_channel/subchannel_index.h",
>         "src/core/ext/filters/client_channel/uri_parser.h",
>         "src/core/lib/security/credentials/credentials.h",
> ```

I don't think this is okay.  We can't depend on any of the security stuff in an insecure build of grpc, and the client channel code is used in insecure builds.

Also, why don't we have a similar change in build.yaml?

---

*[src/core/ext/filters/client_channel/http_proxy.cc, line 51 at r4](https://reviewable.io/reviews/grpc/grpc/15698#-LEu06I42rUlp-9CC_uN:-LEu06I42rUlp-9CC_uO:b-i4ungn) ([raw file](https://github.com/grpc/grpc/blob/2a8e2ec4a787247e95bc7cfcd52aa4f7f6a4a086/src/core/ext/filters/client_channel/http_proxy.cc#L51)):*
> ```cpp
>   GPR_ASSERT(user_cred != nullptr);
>   char* uri_str = nullptr;
>   /* Prefer using 'https_proxy' for secure channels and 'http_proxy' for
> ```

To avoid the dependency on the security code, how about we just unconditionally use `https_proxy` and then fall back to using `http_proxy`?

---

*[test/core/end2end/gen_build_yaml.py, line 60 at r4](https://reviewable.io/reviews/grpc/grpc/15698#-LEu1JuT-_EeW8DXThDV:-LEu1JuT-_EeW8DXThDW:b-4suuif) ([raw file](https://github.com/grpc/grpc/blob/2a8e2ec4a787247e95bc7cfcd52aa4f7f6a4a086/test/core/end2end/gen_build_yaml.py#L60)):*
> ```Python
>     'h2_http_proxy': default_unsecure_fixture_options._replace(
>         ci_mac=False, exclude_iomgrs=['uv'], supports_proxy_auth=True),
>     'h2_https_proxy': default_secure_fixture_options._replace(
> ```

It seems a bit wasteful to duplicate the entire test fixture here, since the thing we're trying to test (the use of the different environment variable for secure vs. insecure) does not differ for any of the individual tests.  It might be better to instead add a single standalone test (not part of the end2end framework, although you can certainly reuse parts of the HTTP proxy fixture) that tests this.

Of course, this issue is moot if we change the code to do the same thing for secure and insecure channels.

---

*[test/core/end2end/fixtures/h2_https_proxy.cc, line 19 at r4](https://reviewable.io/reviews/grpc/grpc/15698#-LEu13i69k1adxIbxtSy:-LEu13i69k1adxIbxtSz:b-w2hp8j) ([raw file](https://github.com/grpc/grpc/blob/2a8e2ec4a787247e95bc7cfcd52aa4f7f6a4a086/test/core/end2end/fixtures/h2_https_proxy.cc#L19)):*
> ```cpp
>  */
> 
> /* This fixture runs end to end tests over a SSL connection with an http proxy.
> ```

The code we're testing doesn't actually care about SSL; it just cares that the channel is secure.  So we could use the fake security credentials here instead of SSL, which might be simpler.

Of course, this issue is moot if we change the code to do the same thing for secure and insecure channels.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15698#-:-LEu1vOS8B6W0GwEdRVk:bl4254y)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +0.0%     +32 [None]                                            +2.30Ki  +0.0%
  +3.5%     +64 src/core/ext/filters/client_channel/http_proxy.cc     +64  +3.5%
      +3.7%     +64 proxy_mapper_map_name                                 +64  +3.7%

  +0.0%     +96 TOTAL                                             +2.36Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by yashykt** [comment]
*[BUILD, line 1071 at r4](https://reviewable.io/reviews/grpc/grpc/15698#-LEu-ntQAa_FbW0QaGG7:-LEv86bQAkOQOYj4ctlG:b3px6fn) ([raw file](https://github.com/grpc/grpc/blob/2a8e2ec4a787247e95bc7cfcd52aa4f7f6a4a086/BUILD#L1071)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this is okay.  We can't depend on any of the security stuff in an insecure build of grpc, and the client channel code is used in insecure builds.

Also, why don't we have a similar change in build.yaml?
</blockquote></details>

Removed. build.yaml maybe already had those dependencies so it didn't need those changes.. anyway doesn't matter anymore

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15698)*

**Comment by yashykt** [comment]
Review status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @markdroth, @yashykt, @dgquintas, and @AspirinSJL)

---

*[test/core/end2end/gen_build_yaml.py, line 60 at r4](https://reviewable.io/reviews/grpc/grpc/15698#-LEu1JuT-_EeW8DXThDV:-LEv8eVa37g6y-izH9XU:bss4a1y) ([raw file](https://github.com/grpc/grpc/blob/2a8e2ec4a787247e95bc7cfcd52aa4f7f6a4a086/test/core/end2end/gen_build_yaml.py#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It seems a bit wasteful to duplicate the entire test fixture here, since the thing we're trying to test (the use of the different environment variable for secure vs. insecure) does not differ for any of the individual tests.  It might be better to instead add a single standalone test (not part of the end2end framework, although you can certainly reuse parts of the HTTP proxy fixture) that tests this.

Of course, this issue is moot if we change the code to do the same thing for secure and insecure channels.
</blockquote></details>

Removed!

---

*[test/core/end2end/fixtures/h2_https_proxy.cc, line 19 at r4](https://reviewable.io/reviews/grpc/grpc/15698#-LEu13i69k1adxIbxtSy:-LEv8j3OACMYLWuBeWeU:bss4a1y) ([raw file](https://github.com/grpc/grpc/blob/2a8e2ec4a787247e95bc7cfcd52aa4f7f6a4a086/test/core/end2end/fixtures/h2_https_proxy.cc#L19)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The code we're testing doesn't actually care about SSL; it just cares that the channel is secure.  So we could use the fake security credentials here instead of SSL, which might be simpler.

Of course, this issue is moot if we change the code to do the same thing for secure and insecure channels.
</blockquote></details>

Removed!

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15698)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +0.0%     +32 [None]                                               +424  +0.0%
  +3.5%     +64 src/core/ext/filters/client_channel/http_proxy.cc     +64  +3.5%
      +3.7%     +64 proxy_mapper_map_name                                 +64  +3.7%

  +0.0%     +96 TOTAL                                                +488  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +0.0%     +48 [None]                                               +152  +0.0%
  +2.7%     +48 src/core/ext/filters/client_channel/http_proxy.cc     +48  +2.7%
      +2.8%     +48 proxy_mapper_map_name                                 +48  +2.8%

  +0.0%     +96 TOTAL                                                +200  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
failing test is unrelated . Created #15766 to track the error
Thanks for reviewing Mark!

**Pull request merged**
