### PR TITLE
Don't set ANDROID_NDK_HOME for all linux jobs

### PR DESCRIPTION
**Pull request by jtattermusch**
Followup for https://github.com/grpc/grpc/pull/28683.

Just try which jobs break

### CODE REVIEW

**Review by gnossen — APPROVED** [review]

**Comment by jtattermusch** [comment]
@gnossen  Interesting, looks like this doesn't break any tests?

This might make sense since:
-  "Bazel BinderTransport APK building/testing" runs under docker so this change wouldn't have any effect anyway
- grpc_android uses cmake (and not bazel): https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/grpc_android.sh

**Comment by jtattermusch** [comment]
since it looks like this PR doesn't do any harm, I'll try to merge. We can rollback if any problems appear.

**Comment by gnossen** [comment]
It doesn't do any harm because none of the PR presubmits run Bazel 5.0. I expect that this will re-break the Bazel latest distribtest.

**Comment by jtattermusch** [comment]
> It doesn't do any harm because none of the PR presubmits run Bazel 5.0. I expect that this will re-break the Bazel latest distribtest.

Turns out it won't re-break grpc_bazel_distribtest_latest since that test runs under docker (so the ANDROID_NDK_HOME variable set in tools/internal_ci/helper_scripts/prepare_build_linux_rc isn't visible to it either.

https://github.com/grpc/grpc/blob/a32c22f2a98f148b8b8be9f7aa8e26ec5fe9aaab/tools/internal_ci/linux/grpc_bazel_distribtest_latest.sh#L26

So IIUC the ANDROID_NDK_HOME was set unnecessarily by the original PR? Removing it doesn't seem to affect any jobs.

**Pull request merged**
