### PR TITLE
Use grpc_build_system.bzl in other projects

### PR DESCRIPTION
**Pull request by makdharma**
Added //external to grpc deps in case where grpc_build_system.bzl is
imported in a project that is using grpc as a dependency.

### CODE REVIEW

**Comment by makdharma** [comment]
test this please

**Comment by makdharma** [comment]
Failing tests - None of them are relevant to the change in .bzl file.

aggregate_tests.run_tests_c++_linux_asan_native
objc_macos_dbg_native.objc-tests
objc_macos_opt_native.objc-tests
aggregate_tests.run_tests_objc_macos_dbg_native
aggregate_tests.run_tests_objc_macos_opt_native
aggregate_tests.run_tests_c_windows_opt_native
c_windows_opt_native.vsprojects/Release/h2_http_proxy_nosec_test.exe keepalive_timeout
aggregate_tests.run_tests_c_linux_msan_native
c_linux_msan_native.bins/msan/h2_proxy_nosec_test no_logging GRPC_POLL_STRATEGY=epoll
c_linux_msan_native.bins/msan/h2_ssl_proxy_test no_logging GRPC_POLL_STRATEGY=epoll
c_linux_msan_native.bins/msan/h2_proxy_test no_logging GRPC_POLL_STRATEGY=epoll
aggregate_tests.run_tests_c++_linux_dbg_native_default_cmake
c_linux_tsan_native.bins/tsan/h2_proxy_test no_logging GRPC_POLL_STRATEGY=epoll
c_linux_tsan_native.bins/tsan/h2_proxy_nosec_test no_logging GRPC_POLL_STRATEGY=epoll
c_linux_tsan_native.bins/tsan/h2_ssl_proxy_test no_logging GRPC_POLL_STRATEGY=epoll
tests.cloud_to_cloud:php7:java_server:custom_metadata
tests.cloud_to_cloud:php:java_server:custom_metadata
tests.cloud_to_cloud:java:node_server:large_unary
tests.cloud_to_cloud:java:csharp_server:client_streaming
tests.cloud_to_cloud:java:csharpcoreclr_server:client_streaming
tests.cloud_to_cloud:java:csharp_server:custom_metadata
tests.cloud_to_cloud:java:csharpcoreclr_server:custom_metadata
benchmarks.qps_json_driver.cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota

**Comment by dgquintas** [comment]
jenkins test this please

**Comment by makdharma** [comment]
I think the failures are flaky. The (inactive) change in bazel file can at worst cause a build failure, not the kind of failures seen in these tests:
aggregate_tests.run_tests_c_linux_opt_native
c_linux_opt_native.bins/opt/h2_ssl_proxy_test no_logging GRPC_POLL_STRATEGY=epoll
c_macos_opt_native.bins/opt/endpoint_pair_test
objc_macos_dbg_native.objc-tests
objc_macos_opt_native.objc-tests
aggregate_tests.run_tests_c_macos_opt_native
aggregate_tests.run_tests_objc_macos_dbg_native
aggregate_tests.run_tests_objc_macos_opt_native
c_linux_tsan_native.bins/tsan/h2_ssl_proxy_test no_logging GRPC_POLL_STRATEGY=epoll

@nicolasnoble can you make a call on whether to merge this PR?

**Comment by nicolasnoble** [comment]
Save it for `c_macos_opt_native.bins/opt/endpoint_pair_test`, everything looks fine.

**Comment by dgquintas** [comment]
Yes, it's fine. We have ongoing issues with accept4 errors @yang-g is looking into (all the no_logging failures, you can write them all under https://github.com/grpc/grpc/issues/9976). 

the endpoint one: https://github.com/grpc/grpc/issues/9980

**Comment by dgquintas** [comment]
Plus a new one: https://github.com/grpc/grpc/issues/9993

**Comment by dgquintas** [comment]
@makdharma please, in the future, summarize the failures pointing to issue numbers (creating them if they don't exist), not just the name of the failing tests. Yes, it's super annoying. That's the idea, so that we all strive to fix them to minimize the annoyance.

**Comment by makdharma** [comment]
Will do.. sorry I thought that between your comment and @nicolasnoble all issues were covered.

I filed a new one  for "Basic Tests Mac" since I didn't see a bug: #9994

**Comment by dgquintas** [comment]
Thank you! No worries :)

**Pull request merged**
