### PR TITLE
Update rules_apple and apple_support

### PR DESCRIPTION
**Pull request by meteorcloudy**
Based on: https://github.com/grpc/grpc/pull/26211

@jtattermusch @gnossen

### CODE REVIEW

**Comment by meteorcloudy** [comment]
/cc @veblush @drfloob 

It looks like grpc is still using Bazel 3.7.1 on Kokoro, but this PR requires Bazel 4.0+. Is there a plan to upgrade Bazel on Kokoro?

This is important for making grpc build with Bazel@HEAD so that we can catch Bazel breaking changes (bug or incompatible changes) earlier in future.

**Comment by veblush** [comment]
@meteorcloudy We don't have a plan to upgrade it but it seems that it needs a discussion to do it. 

@jtattermusch @nicolasnoble PTAL for another bazel upgrade.

**Comment by meteorcloudy** [comment]
@jtattermusch Bazel 4.x is our first LTS release which will be supported for a long time. See https://blog.bazel.build/2020/11/10/long-term-support-release.html

I think it makes more sense to support 4.x than maintaining compatibility with older versions as most Bazel projects are going to upgrade to this version and grpc is a fundamental dependency for many of them.

**Comment by jtattermusch** [comment]
> @jtattermusch Bazel 4.x is our first LTS release which will be supported for a long time. See https://blog.bazel.build/2020/11/10/long-term-support-release.html
> 
> I think it makes more sense to support 4.x than maintaining compatibility with older versions as most Bazel projects are going to upgrade to this version and grpc is a fundamental dependency for many of them.

Fair point, but I'll let @gnossen evaluate the situation around what bazel versions we need to support (as he's the one working on the distribtests). The problem might be that by upgrading to 4.x we might be forcing all project using grpc as a dependency to also upgrade to bazel 4.x  which is problematic (and can result in an avalanche of projects being stuck with need to upgrade, but being unable to do so for various reasons).

Also, it seems that bumping version to 4.x is still blocked until we figure out how to make our UBSAN RBE test suite work well with never toolchain versions (the problem I pointed out in my previous comment).

**Comment by jtattermusch** [comment]
I'm closing this as superseded by #27410. (which updates rules_apple and apple_support and also upgrades to bazel 4)

**Pull request closed without merging**
