### PR TITLE
Upmerge from v1.7

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @vosst isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* User @chrisdunelm isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by nicolasnoble** [comment]
*sigh* that'll be painful.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                 FILE SIZE
 ++++++++++++++ GROWING                                   ++++++++++++++
  +0.6% +3.14Ki [None]                                    +29.7Ki  +0.5%
      +0.6% +2.89Ki [Unmapped]                                +29.6Ki  +0.5%
      +8.3%     +92 [None]                                          0  [ = ]
      [NEW]     +56 grpc_fork_support_init()::truthy              +56  [NEW]
      [NEW]     +48 g_cv                                            0  [ = ]
       +25%     +40 g_mu                                            0  [ = ]
      +100%      +4 g_thread_count                                  0  [ = ]
      [NEW]      +4 g_awaiting_threads                              0  [ = ]
      [NEW]      +4 fork_support_enabled                            0  [ = ]
      [NEW]      +4 override_fork_support_enabled                  +4  [NEW]
  [NEW]    +550 src/core/lib/iomgr/fork_posix.cc             +550  [NEW]
      [NEW]    +279 grpc_prefork                                 +279  [NEW]
      [NEW]    +110 grpc_postfork_child() [clone .part.1]        +110  [NEW]
      [NEW]     +54 grpc_fork_handlers_auto_register              +54  [NEW]
      [NEW]     +41 [Unmapped]                                    +41  [NEW]
      [NEW]     +33 grpc_postfork_child                           +33  [NEW]
      [NEW]     +33 grpc_postfork_parent                          +33  [NEW]
   +62%    +341 src/core/lib/support/thd_posix.cc            +341   +62%
      [NEW]    +108 gpr_await_threads                            +108  [NEW]
      [NEW]     +92 dec_thd_count() [clone .part.0]               +92  [NEW]
       +11%     +55 gpr_thd_new                                   +55   +11%
      [NEW]     +53 gpr_thd_init                                  +53  [NEW]
       +73%     +19 [Unmapped]                                    +19   +73%
       +44%     +14 thread_body                                   +14   +44%
  [NEW]    +151 src/core/lib/support/fork.cc                 +151  [NEW]
      [NEW]    +128 grpc_fork_support_init                       +128  [NEW]
      [NEW]      +9 [Unmapped]                                     +9  [NEW]
      [NEW]      +7 grpc_enable_fork_support                       +7  [NEW]
      [NEW]      +7 grpc_fork_support_enabled                      +7  [NEW]
  [NEW]     +31 pthread_atfork.c                              +31  [NEW]
      [NEW]     +31 __pthread_atfork                              +31  [NEW]
  +1.4%     +16 src/core/lib/surface/init.cc                  +16  +1.4%
       +20%      +9 do_basic_init                                  +9   +20%
       +50%      +7 [Unmapped]                                     +7   +50%

  +0.4% +4.20Ki TOTAL                                     +30.7Ki  +0.5%


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++

 -------------- SHRINKING                    --------------
  -8.0%      -7 src/cpp/common/version_cc.cc      -7  -8.0%
     -17.1%      -7 grpc::Version[abi:cxx11]          -7 -17.1%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  +0.0%      +7 [None]                           -89  -0.0%

  [ = ]       0 TOTAL                            -96  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_InProcessCHTTP2_NoOpMutator_NoOpMutator__1_1.opt.old: 1


[microbenchmarks] No significant performance differences
```

**Comment by kpayson64** [comment]
@nicolasnoble 
Looks like this just needs a clang format then should be all set.

**Comment by jtattermusch** [comment]
Shouldn't all the upmerges from 1.7 be also included in 1.8? (if they already are, then I'm sorry, just checking).

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                 FILE SIZE
 ++++++++++++++ GROWING                                   ++++++++++++++
  +0.6% +3.14Ki [None]                                    +29.7Ki  +0.5%
      +0.6% +2.89Ki [Unmapped]                                +29.6Ki  +0.5%
      +8.3%     +92 [None]                                          0  [ = ]
      [NEW]     +56 grpc_fork_support_init()::truthy              +56  [NEW]
      [NEW]     +48 g_cv                                            0  [ = ]
       +25%     +40 g_mu                                            0  [ = ]
      +100%      +4 g_thread_count                                  0  [ = ]
      [NEW]      +4 g_awaiting_threads                              0  [ = ]
      [NEW]      +4 fork_support_enabled                            0  [ = ]
      [NEW]      +4 override_fork_support_enabled                  +4  [NEW]
  [NEW]    +550 src/core/lib/iomgr/fork_posix.cc             +550  [NEW]
      [NEW]    +279 grpc_prefork                                 +279  [NEW]
      [NEW]    +110 grpc_postfork_child() [clone .part.1]        +110  [NEW]
      [NEW]     +54 grpc_fork_handlers_auto_register              +54  [NEW]
      [NEW]     +41 [Unmapped]                                    +41  [NEW]
      [NEW]     +33 grpc_postfork_child                           +33  [NEW]
      [NEW]     +33 grpc_postfork_parent                          +33  [NEW]
   +62%    +341 src/core/lib/support/thd_posix.cc            +341   +62%
      [NEW]    +108 gpr_await_threads                            +108  [NEW]
      [NEW]     +92 dec_thd_count() [clone .part.0]               +92  [NEW]
       +11%     +55 gpr_thd_new                                   +55   +11%
      [NEW]     +53 gpr_thd_init                                  +53  [NEW]
       +73%     +19 [Unmapped]                                    +19   +73%
       +44%     +14 thread_body                                   +14   +44%
  [NEW]    +151 src/core/lib/support/fork.cc                 +151  [NEW]
      [NEW]    +128 grpc_fork_support_init                       +128  [NEW]
      [NEW]      +9 [Unmapped]                                     +9  [NEW]
      [NEW]      +7 grpc_enable_fork_support                       +7  [NEW]
      [NEW]      +7 grpc_fork_support_enabled                      +7  [NEW]
  [NEW]     +31 pthread_atfork.c                              +31  [NEW]
      [NEW]     +31 __pthread_atfork                              +31  [NEW]
  +1.4%     +16 src/core/lib/surface/init.cc                  +16  +1.4%
       +20%      +9 do_basic_init                                  +9   +20%
       +50%      +7 [Unmapped]                                     +7   +50%

  +0.4% +4.20Ki TOTAL                                     +30.7Ki  +0.5%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                 FILE SIZE
 ++++++++++++++ GROWING                                   ++++++++++++++
  +0.6% +3.14Ki [None]                                    +29.7Ki  +0.5%
      +0.6% +2.89Ki [Unmapped]                                +29.6Ki  +0.5%
      +8.3%     +92 [None]                                          0  [ = ]
      [NEW]     +56 grpc_fork_support_init()::truthy              +56  [NEW]
      [NEW]     +48 g_cv                                            0  [ = ]
       +25%     +40 g_mu                                            0  [ = ]
      +100%      +4 g_thread_count                                  0  [ = ]
      [NEW]      +4 g_awaiting_threads                              0  [ = ]
      [NEW]      +4 fork_support_enabled                            0  [ = ]
      [NEW]      +4 override_fork_support_enabled                  +4  [NEW]
  [NEW]    +550 src/core/lib/iomgr/fork_posix.cc             +550  [NEW]
      [NEW]    +279 grpc_prefork                                 +279  [NEW]
      [NEW]    +110 grpc_postfork_child() [clone .part.1]        +110  [NEW]
      [NEW]     +54 grpc_fork_handlers_auto_register              +54  [NEW]
      [NEW]     +41 [Unmapped]                                    +41  [NEW]
      [NEW]     +33 grpc_postfork_child                           +33  [NEW]
      [NEW]     +33 grpc_postfork_parent                          +33  [NEW]
   +62%    +341 src/core/lib/support/thd_posix.cc            +341   +62%
      [NEW]    +108 gpr_await_threads                            +108  [NEW]
      [NEW]     +92 dec_thd_count() [clone .part.0]               +92  [NEW]
       +11%     +55 gpr_thd_new                                   +55   +11%
      [NEW]     +53 gpr_thd_init                                  +53  [NEW]
       +73%     +19 [Unmapped]                                    +19   +73%
       +44%     +14 thread_body                                   +14   +44%
  [NEW]    +151 src/core/lib/support/fork.cc                 +151  [NEW]
      [NEW]    +128 grpc_fork_support_init                       +128  [NEW]
      [NEW]      +9 [Unmapped]                                     +9  [NEW]
      [NEW]      +7 grpc_enable_fork_support                       +7  [NEW]
      [NEW]      +7 grpc_fork_support_enabled                      +7  [NEW]
  [NEW]     +31 pthread_atfork.c                              +31  [NEW]
      [NEW]     +31 __pthread_atfork                              +31  [NEW]
  +1.4%     +16 src/core/lib/surface/init.cc                  +16  +1.4%
       +20%      +9 do_basic_init                                  +9   +20%
       +50%      +7 [Unmapped]                                     +7   +50%

  +0.4% +4.20Ki TOTAL                                     +30.7Ki  +0.5%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                 FILE SIZE
 ++++++++++++++ GROWING                                   ++++++++++++++
  +0.6% +3.14Ki [None]                                    +29.7Ki  +0.5%
      +0.6% +2.89Ki [Unmapped]                                +29.6Ki  +0.5%
      +8.3%     +92 [None]                                          0  [ = ]
      [NEW]     +56 grpc_fork_support_init()::truthy              +56  [NEW]
      [NEW]     +48 g_cv                                            0  [ = ]
       +25%     +40 g_mu                                            0  [ = ]
      +100%      +4 g_thread_count                                  0  [ = ]
      [NEW]      +4 g_awaiting_threads                              0  [ = ]
      [NEW]      +4 fork_support_enabled                            0  [ = ]
      [NEW]      +4 override_fork_support_enabled                  +4  [NEW]
  [NEW]    +550 src/core/lib/iomgr/fork_posix.cc             +550  [NEW]
      [NEW]    +279 grpc_prefork                                 +279  [NEW]
      [NEW]    +110 grpc_postfork_child() [clone .part.1]        +110  [NEW]
      [NEW]     +54 grpc_fork_handlers_auto_register              +54  [NEW]
      [NEW]     +41 [Unmapped]                                    +41  [NEW]
      [NEW]     +33 grpc_postfork_child                           +33  [NEW]
      [NEW]     +33 grpc_postfork_parent                          +33  [NEW]
   +62%    +341 src/core/lib/support/thd_posix.cc            +341   +62%
      [NEW]    +108 gpr_await_threads                            +108  [NEW]
      [NEW]     +92 dec_thd_count() [clone .part.0]               +92  [NEW]
       +11%     +55 gpr_thd_new                                   +55   +11%
      [NEW]     +53 gpr_thd_init                                  +53  [NEW]
       +73%     +19 [Unmapped]                                    +19   +73%
       +44%     +14 thread_body                                   +14   +44%
  [NEW]    +151 src/core/lib/support/fork.cc                 +151  [NEW]
      [NEW]    +128 grpc_fork_support_init                       +128  [NEW]
      [NEW]      +9 [Unmapped]                                     +9  [NEW]
      [NEW]      +7 grpc_enable_fork_support                       +7  [NEW]
      [NEW]      +7 grpc_fork_support_enabled                      +7  [NEW]
  [NEW]     +31 pthread_atfork.c                              +31  [NEW]
      [NEW]     +31 __pthread_atfork                              +31  [NEW]
  +1.4%     +16 src/core/lib/surface/init.cc                  +16  +1.4%
       +20%      +9 do_basic_init                                  +9   +20%
       +50%      +7 [Unmapped]                                     +7   +50%

  +0.4% +4.20Ki TOTAL                                     +30.7Ki  +0.5%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                  cpu_time    real_time
-------------------------  ----------  -----------
BM_MetadataRefUnrefStatic  +6%         +6%
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
Known failures: #12913 https://github.com/grpc/grpc/issues/13122

**Pull request merged**
