### PR TITLE
Monkey-patch distutils.ccompiler.spawn to elide -std=c++11 from non-C…

### PR DESCRIPTION
**Pull request by mingwandroid**
…++ code

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @mingwandroid isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @mingwandroid isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by komar** [comment]
Hi @mingwandroid, 
are there any plans for updating this PR with CLA?

**Comment by ericgribkoff** [comment]
It's not clear how the problem this PR tries to solve would be encountered on Mac, as to work-around this we already skip distutils for building the core dependencies on Mac and use make in a subprocess. We also don't want to (further) monkey-patch distutils to work-around this, and unfortunately there's no exposed API in distutils to accomplish this properly.

Closing this for now; if the original author is able to provides more context (as well as signing the CLA) we can re-open.

**Pull request closed without merging**
