### PR TITLE
Add a core tracer for DNS requests

### PR DESCRIPTION
**Pull request by murgatroid99**

### CODE REVIEW

**Comment by ctiller** [comment]
Please update doc/environment_variables.md

**Comment by markdroth** [comment]
@y-zeng This is probably something we'll want to continue to support when we're using c-ares for DNS, as per #7771.

**Comment by nicolasnoble** [comment]
Please clang-format.

**Comment by ctiller** [comment]
This will need some updating to the latest tracing api...

**Comment by markdroth** [comment]
It probably also needs to include the c-ares resolver.

**Comment by jtattermusch** [comment]
Are there any plans to proceed with this?  I'm currently debugging issues with https://github.com/grpc/grpc/blob/082ddc563ea71a6b7a700070ec60095bfb65d88f/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L379 and it would be useful to be able to use `GRPC_TRACE=dns`
@y-zeng

**Comment by murgatroid99** [comment]
It would probably be easier to redo this from scratch than to make this work

**Pull request closed without merging**
