### PR TITLE
Temporary workaround to re-enable single-channel throughput tests

### PR DESCRIPTION
**Pull request by vjpai**
Make BIG smaller until we figure out big message issues

### CODE REVIEW

**Comment by vjpai** [comment]
FWIW, I think that this temporary workaround will not need to last long. I think that #6412 is a guide for what to do next.

**Comment by jtattermusch** [comment]
is this still needed?

**Comment by vjpai** [comment]
Not sure. Let me determine if it is.

**Comment by jtattermusch** [comment]
After changing scenario_config.py significantly, this change needs to be basically rewritten. Unassigning myself for now.

**Pull request closed without merging**
