### PR TITLE
Sync java options in example protos

### PR DESCRIPTION
**Pull request by ejona86**
This makes the protos identical between this repository and the java
repository.

Fixes grpc/grpc-java#1381

### CODE REVIEW

**Comment by dsymonds** [comment]
FYI, the copyright year shouldn't be bumped just because the file is changed. It's meant to be when the file was first created.

**Comment by ejona86** [comment]
@dsymonds, that [disagrees with check_copyright.py](https://grpc-testing.appspot.com/job/gRPC_pull_requests/5873/config=opt,language=sanity,platform=linux/testReport/junit/(root)/tests/tools_distrib_check_copyright_py/):
> examples/protos/helloworld.proto modified 2016 but copyright only extends to 2015
> examples/protos/route_guide.proto modified 2016 but copyright only extends to 2015

I don't know who made that check, I'm just trying to follow the rules.

**Comment by dsymonds** [comment]
Maybe it's trying to tell you to write `2015-2016` instead?

But the check is broken. You can read go/copyright (internally) or http://www.copyright.gov/eco/help-publication.html.

**Comment by ejona86** [comment]
@dsymonds, updated to 2015-2016. Reading the script it appears to support the year range and I see multiple other usages of that in the codebase. Is 2015-2016 correct in your mind?

Based on the link you provided, it seems that 2016 would be correct:
> For a revised version, the publication date should be the date the revised version was first published, not the date the original version first appeared online.

and:
> Give the year in which creation of this work was completed. Also, this should be the year this particular version was completed. Do NOT refer to earlier or later versions.

If the check is still broken in your mind, would you mind filing an issue? I would, but I don't think I'm knowledgeable enough to do so.

**Comment by dsymonds** [comment]
Yes, `2015-2016` would be fine, though IMO leaving it as `2015` would have been fine too.

The relevant phrase is `Give the year in which creation of this work was completed.`, and it was completed last year. You're just making a change to what was previously considered completed; it wasn't "incomplete" last year.

Happy to file an issue, but I don't know where. Who owns check_copyright.py?

@dberlin might have words to say.

**Comment by ejona86** [comment]
@dsymonds, an issue in this repo looks good. At the very least that'll help track down where it came from. But it seems it might have been created by @ctiller. We can discuss in an issue once we have one.

**Comment by dsymonds** [comment]
Sure. Filed #5051.

**Comment by dberlin** [comment]
You shouldn't bother updating dates. It's pointless, and if we are still
using this in 80 years, we should all feel bad :)

**Pull request merged**
