### PR TITLE
Update to nan 2.0

### LINKED ISSUE #2906: Update Node to the new version of nan
Version 3.0 of nan was recently released, and it has a completely different namespace structure than the previous version. It also looks like it has some useful additions.

### PR DESCRIPTION
**Pull request by murgatroid99**
This adds compatibility for io.js 3.x and Node 4.0. Fixes #2906.

### CODE REVIEW

**Comment by Zerqkboo** [comment]
Hi, will this fix be released in 0.11.1 ?

**Comment by murgatroid99** [comment]
That's the plan.

**Comment by nicolasnoble** [comment]
@tbetbetbe any chance of getting that reviewed ?

**Comment by tbetbetbe** [comment]
FYI: the test failures were not related to this change.

**Comment by Andyccs** [comment]
@murgatroid99 @tbetbetbe So is grpc compatible with Node 4.0 now?

**Comment by murgatroid99** [comment]
Yes, as long as you are willing to build from the git repo. This change will be in the 0.11.1 version of the npm package whenever that gets published.

**Pull request merged**
