### PR TITLE
RouteGuide example now works with moving between tabs. Fixes issue 6404.

### LINKED ISSUE #6404: ObjC route_guide app doesn't send request the second time you click on a tab.
the route_guide app works like this: When you click on the bottom tabs ("Get Feature", "List Features", "Record Route", "Route Chat"), it does the right thing. But only the first time. The second time you click on a tab it does nothing. The RPC call is made in the viewDidLoad() callback, which only gets called once per tab.

### PR DESCRIPTION
**Pull request by makdharma**
Fixes #6404

### CODE REVIEW

**Comment by makdharma** [comment]
The test failures seem unrelated. @jcanizales  - OK to merge?

**Comment by jcanizales** [comment]
Please create issues to get those flakes fixed, or ping and cross-reference them to this PR if they already exist.

**Comment by makdharma** [comment]
@nicolasnoble or @jtattermusch - Could you opine on the test failures? To me they seem unrelated to the change. If there's a known issue could you please link it here?

**Comment by jcanizales** [comment]
To be clear - they are unrelated to this change for sure.

**Comment by jtattermusch** [comment]
failures are unrelated, restarted the tests.

**Comment by makdharma** [comment]
@jcanizales - does route guide example get tested in the CI system? If not,
what more needs to be done for this PR?

**Comment by jcanizales** [comment]
Merging. There's an open issue already for building the samples in CI.

**Pull request merged**
