### PR TITLE
Revert "Merge pull request #13710 from ctiller/fix17it1"

### PR DESCRIPTION
**Pull request by mehrdada**
This reverts commit 78335ac3769b27ccb7c76f034293619ee76cd36d, reversing
changes made to 92b6e9909acea0594160ed0dce7fb87932790ece.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
This might or might not be necessary as the existing import was fixed and submitted cleanly--the next import may need to revert this again. But let's defer this for now and revert only if the next import fails. Closing for now and giving it some time.

**Pull request closed without merging**
