### PR TITLE
fix typo in document

### PR DESCRIPTION
**Pull request by tanjunchen**
@nicolasnoble

### CODE REVIEW

**Comment by markdroth** [comment]
Looks good to me.  Let's see if tests pass.

**Comment by tanjunchen** [comment]
@markdroth should i can do ? run something command?

**Comment by AspirinSJL** [comment]
@tanjunchen The tests can only be started by adding "kokoro:run" label, which is only available to repo maintainers.

**Comment by tanjunchen** [comment]
@AspirinSJL   thank  you

**Comment by markdroth** [comment]
The test failures are all known issues.

**Comment by gnossen** [comment]
LGTM

**Pull request merged**
