### PR TITLE
increase parallelism in selected artifact and distribtest jobs

### PR DESCRIPTION
**Pull request by jtattermusch**
Followup for internal cl/413151606 (switched selected jobs to 32 core workers).

### CODE REVIEW

**Review by lidizheng — APPROVED** [review]
LGTM. This PR along with the CL improves build time as mentioned.

The mapping from 12 jobs to 32 cores may need more thoughts. In the worst case, each Python build could spawn 32 threads?

**Comment by jtattermusch** [comment]
> LGTM. This PR along with the CL improves build time as mentioned.
> 
> The mapping from 12 jobs to 32 cores may need more thoughts. In the worst case, each Python build could spawn 32 threads?

I think for that we'd have to set the number of parallel compiler jobs very high and I don't think we're doing that:
https://github.com/grpc/grpc/blob/74d0e3905e9d5a94f592813cb1f137fb60a907b8/tools/run_tests/artifacts/build_artifact_python.sh#L42
(IIRC we're only setting GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS to 2 or 4 or something relatively low). 

Oh ok, maybe here, but that's not for artifact build?
https://github.com/grpc/grpc/blob/25f5399b412382b29ba8d814ab5d64c9ae32f81e/tools/run_tests/helper_scripts/build_python.sh#L125
(I think using nproc parallel jobs is an overkill and I'd be surprised if it lead to actual improvement in build time)

**Comment by lidizheng** [comment]
`nproc` is good for debugging, while fixed parallelism number is good for CI planning. I agree that the latter seems better for our use case.

**Comment by jtattermusch** [comment]
Timing improvements:
grpc_build_artifacts
BEFORE ~3h AFTER 1h50min

grpc_distribtests_python
BEFORE 130min AFTER 75min.

**Comment by jtattermusch** [comment]
Known failures: 
- https://github.com/grpc/grpc-dotnet/issues/1511

**Pull request merged**
