### PR TITLE
Grpc args doxygen

### LINKED ISSUE #7458: Document useful grpc_channel_args
/cc @nathanielmanistaatgoogle @ctiller 

We need a simple document discussing channel args and potentially useful one for advance cases. Wrapped languages pass these args to core but they are currently not documented. 

Either a markdown or doxygen comments that can be referenced would be a good starting point. 

Ref: http://www.grpc.io/grpc/core/structgrpc__channel__args.html

### PR DESCRIPTION
**Pull request by dgquintas**
Fixes #7458

### CODE REVIEW

**Comment by hsaliak** [comment]
LGTM

**Comment by hsaliak** [comment]
Fyi @nicolasnoble this needs to go into the v1.0.x branch so that the generated API references contain this grouping.

**Comment by ctiller** [comment]
Please don't commit doc/ref to the repository

**Comment by dgquintas** [comment]
@ctiller Yes, it's been fixed (you may need to reload).

**Comment by dgquintas** [comment]
@hsaliak the PR against the v1.0.x branch is at #7470

**Pull request merged**
