### PR TITLE
Revert "Revert "Renamed google_benchmark submodule to benchmark""

### PR DESCRIPTION
**Pull request by markdroth**
Reverts grpc/grpc#8950.  Re-do of #8851.  Won't merge until after fixit.

### CODE REVIEW

**Comment by ctiller** [comment]
Test this please

**Comment by ctiller** [comment]
Looks like this breaks Jenkins

**Comment by markdroth** [comment]
@dgquintas, you're the original author of this change.  Can you fix the jenkins problems?  Thanks!

**Comment by dgquintas** [comment]
yes, on it.

**Comment by dgquintas** [comment]
The original PR had some issues. I've created a brand new PR, https://github.com/grpc/grpc/pull/8986 This one can be closed.

**Pull request closed without merging**
