### PR TITLE
Add "--log_metadata_and_status" interop client flag (and a test)

### PR DESCRIPTION
**Pull request by jtattermusch**
See internal bug b/203714502

### CODE REVIEW

**Comment by jtattermusch** [comment]
This is ready for initial review now. See internal bug b/203714502 for context.

**Review by yashykt — APPROVED** [review]

**Comment by jtattermusch** [comment]
@gnossen, before we merge this, can you please do an internal cherry-pick of this PR to double check everything is fine?
I ran a cherry-pick before and it seemed that they're might be and ODR violation between the internal version of interop_client and the updates from this PR.

FTR my cherry-pick is cl/410486644 and the failure is sponge/1cacc4d3-14ed-4c05-8868-12d725339af1

(I'm currently OOO).

**Comment by gnossen** [comment]
I have resolved the ODR violation in a CITC client. After the last couple of OSS tests here finish, I will cherry-pick this in.

**Comment by srini100** [comment]
@gnossen, fyi, lately the ObjC iOS test has been getting stuck.

**Comment by gnossen** [comment]
Yes. At any rate, after some digging, it looks like there shouldn't be any dependency relationship between this PR and the ObjC iOS basic tests, so going ahead and merging now.

**Pull request merged**
