### PR TITLE
Add Python 3.8 test

### PR DESCRIPTION
**Pull request by gnossen**
This PR adds a compatibility test with Python 3.8. No CI job has been added for it yet and it has not been added as a default test configuration. This should be changed after the final release in October. For the moment, the test image pulls the most recent cpython 3.8 pre-release version and compiles from source. It is expected that this test be run manually. Python 3.8 support has also not yet been added to the wheel metadata.

Related: https://github.com/grpc/grpc/issues/19243

### CODE REVIEW

**Comment by gnossen** [comment]
@lidizheng It wouldn't be a bad idea, but I see one hard problem. When should we rebuild the image? Currently, our docker build system assumes that a new instance of an image should be built only when the hash of the dockerfile changes. It doesn't even incorporate files `COPY`'d into the image into the hash. Ideally, we'd rebuild *this* image every time a new version of cpython released. If we were working with microrepos rather than a monorepo, I'd create a separate repo hosting just the build for this image. It would be triggered on a cron job and check for a new version of `cpython`. If a new one had been released, it would compile it and publish it to the `latest` tag. Then, in the `grpc/grpc` repo, we'd simply use that image in `run_tests.py`. We'd have to pay down a *bunch* of tech debt to make that happen, so I'm not fully convinced that it's worth it.

**Comment by gnossen** [comment]
https://hub.docker.com/_/python could offer an alternative. But I don't seen a tag equivalent to `3.8.+`.

**Comment by lidizheng** [comment]
@gnossen Good idea! Using the Python stretch image. How about the `rc_stretch` tag?

**Comment by gnossen** [comment]
I was able to confirm that [these images are being updated the way we'd like](https://github.com/docker-library/official-images/commit/81ed93836b2c1a9fc0788dc65193d10db75bdc3a#diff-051bb6df61b6c6e7f8c1868985011b07). Going with `3.8-rc-slim-stretch`.

**Comment by gnossen** [comment]
**Known Failures**:
 - [Basic Tests C/C++ MacOS](https://github.com/grpc/grpc/issues/18416)

Filed https://github.com/grpc/grpc/issues/19340 to track turning this into an automated test of the next minor revision of CPython.

Going ahead and merging this as an interim solution as discussed offline with @lidizheng

**Pull request merged**
