### PR TITLE
Remove unreachable code in RR

### PR DESCRIPTION
**Pull request by AspirinSJL**
As mentioned in #13654, we will never receive a notification for a subcahnnel going back to IDLE state.

I've run 3000+ tests locally, no failures.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%     +48 [None]    +256  +0.0%

  +0.0%     +48 TOTAL     +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
- Basic Tests Multi-language Linux (internal CI) : #13272
- Tsan C++ (internal CI): #13148

**Pull request merged**
