### PR TITLE
Revert "Add Type Checking On Channel Args"

### PR DESCRIPTION
**Pull request by ncteisen**
Looks like the original change caused #15753

Reverts grpc/grpc#15678

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
   +16%    +672 src/core/ext/filters/http/client/http_client_filter.cc                                  +672   +16%
       +79%    +676 init_channel_elem                                                                       +676   +79%
   +11%    +224 src/core/lib/security/credentials/credentials.cc                                        +224   +11%
      [NEW]     +98 grpc_server_credentials_from_arg                                                         +98  [NEW]
      [NEW]     +98 grpc_channel_credentials_from_arg                                                        +98  [NEW]
       +14%     +28 [Unmapped]                                                                               +28   +14%
  +3.5%    +176 src/core/lib/iomgr/tcp_server_posix.cc                                                  +176  +3.5%
       +52%    +191 tcp_server_create                                                                       +191   +52%
  +4.1%    +160 src/core/lib/iomgr/tcp_server_custom.cc                                                 +160  +4.1%
       +71%    +159 tcp_server_create                                                                       +159   +71%
      +1.2%      +1 [Unmapped]                                                                                +1  +1.2%
  +0.5%    +156 src/core/ext/filters/client_channel/client_channel.cc                                   +156  +0.5%
       +14%    +167 cc_init_channel_elem                                                                    +167   +14%
      +2.2%      +9 [Unmapped]                                                                                +9  +2.2%
  +3.6%    +112 src/core/lib/security/context/security_context.cc                                       +112  +3.6%
      [NEW]     +98 grpc_auth_context_from_arg                                                               +98  [NEW]
      +9.0%     +14 [Unmapped]                                                                               +14  +9.0%
  +1.2%    +112 src/core/lib/security/security_connector/security_connector.cc                          +112  +1.2%
      [NEW]     +98 grpc_security_connector_from_arg                                                         +98  [NEW]
      +2.6%     +14 [Unmapped]                                                                               +14  +2.6%
  +1.1%     +80 src/core/lib/iomgr/resource_quota.cc                                                     +80  +1.1%
       +72%     +68 grpc_resource_quota_from_channel_args                                                    +68   +72%
      +4.5%     +12 [Unmapped]                                                                               +12  +4.5%
  +3.4%     +64 src/core/lib/iomgr/tcp_server_utils_posix_common.cc                                      +64  +3.4%
      +7.4%     +62 grpc_tcp_server_prepare_socket                                                           +62  +7.4%
      +9.1%      +2 [Unmapped]                                                                                +2  +9.1%
  +1.5%     +48 src/core/lib/iomgr/tcp_client_posix.cc                                                   +48  +1.5%
      +8.4%     +52 grpc_tcp_client_prepare_fd                                                               +52  +8.4%
  +0.8%     +32 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             +32  +0.8%
      +7.3%     +40 grpc_core::(anonymous namespace)::AresDnsResolverFactory::CreateResolver(grpc_core::     +40  +7.3%
  +0.6%     +32 src/core/lib/iomgr/udp_server.cc                                                         +32  +0.6%
       +10%     +21 grpc_udp_server_create                                                                   +21   +10%
      +6.7%     +11 [Unmapped]                                                                               +11  +6.7%
  +0.1%     +16 src/core/ext/transport/inproc/inproc_transport.cc                                        +16  +0.1%
      +1.4%      +9 grpc_inproc_channel_create                                                                +9  +1.4%
      +3.4%      +7 [Unmapped]                                                                                +7  +3.4%
  +0.3%      +5 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_channel_secure.cc             +5  +0.3%
      +0.6%      +5 grpc_lb_policy_grpclb_modify_lb_channel_args                                              +5  +0.6%

 -------------- SHRINKING                                                                            --------------
  -1.5%    -160 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  -160  -1.5%
      -4.7%    -158 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               -158  -4.7%
      -0.8%      -2 [Unmapped]                                                                                -2  -0.8%
  -0.6%     -96 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           -96  -0.6%
      -5.1%     -55 grpc_core::(anonymous namespace)::GrpcLbFactory::CreateLoadBalancingPolicy(grpc_core     -55  -5.1%
      -2.5%     -29 grpc_core::(anonymous namespace)::GrpcLb::ProcessChannelArgsLocked                       -29  -2.5%
      -2.9%     -12 [Unmapped]                                                                               -12  -2.9%
  -3.7%     -96 src/core/lib/security/credentials/ssl/ssl_credentials.cc                                 -96  -3.7%
     -23.0%     -96 ssl_create_security_connector                                                            -96 -23.0%
  -3.2%     -64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       -64  -3.2%
     -43.5%     -40 grpc_core::FakeResolverResponseGenerator::GetFromArgs                                    -40 -43.5%
     -52.6%     -40 grpc_core::FakeResolverResponseGenerator::MakeChannelArg                                 -40 -52.6%
  -2.9%     -40 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 -40  -2.9%
     -43.5%     -40 grpc_lb_addresses_find_channel_arg                                                       -40 -43.5%
  -0.3%     -32 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 -32  -0.3%
      -1.3%     -35 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                               -35  -1.3%
  -0.1%     -16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                              -16  -0.1%
      -0.3%     -12 grpc_create_chttp2_transport                                                             -12  -0.3%
      -0.6%      -4 [Unmapped]                                                                                -4  -0.6%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  +0.2% +1.38Ki [None]                                                                               -11.3Ki  -0.1%

  +0.2% +2.73Ki TOTAL                                                                                -9.92Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +40  +0.0%

  [ = ]       0 TOTAL      +40  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Somehow, the original change caused a gevent failure... we should rollback while I investigate

**Comment by kpayson64** [comment]
That is very odd... I don't see any changes to files that are gevent-specific.  Rollback LGTM though.

**Comment by ncteisen** [comment]
Fixes #15753

**Pull request merged**
