### PR TITLE
Reintroduce "Remove ccache from all docker images"

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Introducing this would break grpc-node tests again - @nicolasnoble   what would be the proper fix?

**Comment by murgatroid99** [comment]
Are the docker images that are impacted by this change saved anywhere, or are they rebuilt whenever the tests are run?

**Comment by jtattermusch** [comment]
they are saved in dockerhub (and they are differentiated based on sha1 of the `Dockerfile`)
https://hub.docker.com/u/grpctesting/

by computing sha1 of the Dockerfile before and after you can get to the exact images used by kokoro.

**Comment by murgatroid99** [comment]
OK, I think I know what the problem is. It's not related to ccache, but rather to the fact that the docker image is getting rebuilt. I think this should be fixed by #15491.

**Comment by murgatroid99** [comment]
I have merged #15491. I think you will have to merge master into your branch and republish the docker images, but then the tests should pass.

**Comment by jtattermusch** [comment]
@murgatroid99, thanks for the update!  Testing now.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
