### PR TITLE
Add virtual destructor to satisfy a requirement of some compilers

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
You make it sound like we're doing a bad thing. How about changing "avoid a warning with some compilers" to "satisfy requirements of some compilers"?

**Comment by vjpai** [comment]
Done.

**Comment by nathanielmanistaatgoogle** [comment]
In your commit too?

**Comment by vjpai** [comment]
git commit --amend and git push --force
I too like to live dangerously
Done

**Comment by nathanielmanistaatgoogle** [comment]
Wait, what? What's going on that another commit is required?

**Comment by vjpai** [comment]
I amended a commit post-push, so it wouldn't let me push the change from my local client unless I used --force . Then Github said that my branch was out of date with master, so I merged master. It's all done now and ready to review

**Comment by nathanielmanistaatgoogle** [comment]
To avoid having the merge commit in the future, always bring your client up-to-date before drafting an easy one-off change like this? Remember that GitHub, by its nature of things, will add _another_ merge commit to project history due to the way it works.

LGTM with snobbery. :-\ :-P

**Comment by vjpai** [comment]
It was up to date before I started; it went out-of-date when I did the push
--force. Not sure if that's a causal relationship, though, as I know that
Nico merged something else in the meanwhile.

**Pull request merged**
