### PR TITLE
Add comment to NewInstance override in the generated code

### LINKED ISSUE #8249: C# generator doesn't include XML doc comment for NewInstance
The protected NewInstance method in the generated client code should include an XML doc comment to avoid warnings when being built in a context that generates a documentation file.

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes #8249

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @jskeet

**Comment by jtattermusch** [comment]
Needed to re-run tests, so rebased this on #8352 to get better xml reports.

**Comment by jtattermusch** [comment]
I checked all the test failures and they are unrelated.

**Comment by jskeet** [comment]
Am I right in saying this didn't make it into 1.0.1? Are we expecting it to be in the next release?

**Comment by jtattermusch** [comment]
@jskeet  yes, you're right. I will be in 1.1.  Do you need this backported?

**Comment by jskeet** [comment]
I'll be pleased to see my "No XML comment for publicly visible member X" warnings go as soon as possible, but it's not critical. If 1.1 isn't scheduled to go out until 2018 or something, then backporting would be nice - but I suspect it'll be out earlier than that :)

**Comment by jtattermusch** [comment]
My hope is to get 1.1 out the door before end of 2016, as it has some
highly desirable features (such as a 10x C# throughput boost).

**Comment by jskeet** [comment]
SGTM - thanks Jan.

**Pull request merged**
