### PR TITLE
First draft at addressing #1799 for grpc_security.

### PR DESCRIPTION
**Pull request by jboeuf**
- Will make all the changes everywhere once we reach consensus.

### CODE REVIEW

**Comment by jboeuf** [comment]
ctiller@ please have a look as well.

**Comment by ctiller** [comment]
LGTM so far.

**Comment by jboeuf** [comment]
OK, I will add the implementation part then.

**Comment by jboeuf** [comment]
PTAL. msan and tsan error look unrelated.

**Pull request merged**
