### PR TITLE
Avoid stall

### LINKED ISSUE #13918: Roll Forward #13665 on Master
https://github.com/grpc/grpc/pull/13665 got rolled back on master due to an issue with the quota_server test:
https://sponge.corp.google.com/invocation?id=080130e9-fc00-4cca-bf13-885dd553f344&searchFor
https://sponge.corp.google.com/target?id=080130e9-fc00-4cca-bf13-885dd553f344&target=github/grpc/c_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

### PR DESCRIPTION
**Pull request by kpayson64**
Fixes #13918

Only the last commit is relevant (New for the roll-forward)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++
  +0.0%      +8 [None]                                                +136  +0.0%
  +0.9%    +112 src/core/lib/iomgr/ev_poll_posix.cc                   +112  +0.9%
      +2.2%     +64 pollset_work                                           +64  +2.2%
      +9.6%     +32 fd_orphan                                              +32  +9.6%
      +4.6%     +11 fd_create                                              +11  +4.6%
      +1.6%      +5 [Unmapped]                                              +5  +1.6%
  +0.3%     +16 src/core/ext/transport/chttp2/transport/writing.cc     +16  +0.3%
       +59%     +10 [Unmapped]                                             +10   +59%
      +5.4%      +6 report_stall                                            +6  +5.4%

  +0.0%    +136 TOTAL                                                 +264  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++
  +0.0%      +8 [None]                                                +136  +0.0%
  +0.9%    +112 src/core/lib/iomgr/ev_poll_posix.cc                   +112  +0.9%
      +2.2%     +64 pollset_work                                           +64  +2.2%
      +9.6%     +32 fd_orphan                                              +32  +9.6%
      +4.6%     +11 fd_create                                              +11  +4.6%
      +1.6%      +5 [Unmapped]                                              +5  +1.6%
  +0.3%     +16 src/core/ext/transport/chttp2/transport/writing.cc     +16  +0.3%
       +59%     +10 [Unmapped]                                             +10   +59%
      +5.4%      +6 report_stall                                            +6  +5.4%

  +0.0%    +136 TOTAL                                                 +264  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++
  +0.0%      +8 [None]                                                +128  +0.0%
  +0.9%    +112 src/core/lib/iomgr/ev_poll_posix.cc                   +112  +0.9%
      +2.2%     +64 pollset_work                                           +64  +2.2%
      +9.6%     +32 fd_orphan                                              +32  +9.6%
      +4.6%     +11 fd_create                                              +11  +4.6%
      +3.1%     +10 [Unmapped]                                             +10  +3.1%
  +0.3%     +16 src/core/ext/transport/chttp2/transport/writing.cc     +16  +0.3%
       +59%     +10 [Unmapped]                                             +10   +59%
      +5.4%      +6 report_stall                                            +6  +5.4%

  +0.0%    +136 TOTAL                                                 +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_unary_ping_pong.BM_UnaryPingPong_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__0_8.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by kpayson64** [comment]
#13945

**Pull request merged**
