### PR TITLE
Revert "Revert "Config migration""

### PR DESCRIPTION
**Pull request by veblush**
This is a roll-forward of "Config migration" which was recently rollbacked. 
- Original PR (#18931)
- Rollback PR (#19027)

Google internal test is being in-progress with cl/249077900

### CODE REVIEW

**Comment by veblush** [comment]
First test run.

### Bazel RBE Debug C/C++
- /test/core/end2end:h2_http_proxy_nosec_test@disappearing_server@poller=epoll1
  https://source.cloud.google.com/results/invocations/157db96e-6630-4572-9b34-704f975bc8a8/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_http_proxy_nosec_test@disappearing_server@poller%3Depoll1/log
-> Not reproducible locally

### Basic Tests ObjC MacOS [dbg]
- grpc/core/pull_request/macos/grpc_basictests_objc_dbg
  Test Case '-[InteropTestsRemote testResponsesOver4MBAreAcceptedIfOptedIn]' started.
  <unknown>:0: error: -[InteropTestsRemote testResponsesOver4MBAreAcceptedIfOptedIn] : Asynchronous wait failed: Exceeded timeout of 32 seconds, with unfulfilled expectations: "HigherResponseSizeLimit".
  Test Case '-[InteropTestsRemote testResponsesOver4MBAreAcceptedIfOptedIn]' failed (32.172 seconds).
-> ?

### Interop Cloud-to-Cloud Tests (internal CI)
- grpc/core/pull_request/linux/grpc_interop_tocloud
  https://source.cloud.google.com/results/invocations/90c488a3-e527-41a7-90b9-43657b0669e2/targets;collapsed=/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log
  2019-05-20 08:29:01,917 (node:194) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
  2019-05-20 08:29:01,917 FAILED: cloud_to_cloud:nodepurejs:java_server:server_streaming:tls [ret=1, pid=5092, time=1.8sec]
-> ?

### Interop Cloud-to-Prod Tests (internal CI)
- grpc/core/pull_request/linux/grpc_interop_toprod
  https://source.cloud.google.com/results/invocations/a9e80fd7-b814-4696-a057-a82688e29af9/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log
  2019-05-20 08:29:17,211 (node:195) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
  2019-05-20 08:29:17,211 FAILED: cloud_to_prod:nodepurejs:default:server_streaming:tls [ret=1, pid=6864, time=2.1sec]
-> ?

**Comment by veblush** [comment]
None of test failures above doesn't seem relevant to this PR although this might be affecting them indirectly. Second run of test is in progress to see if failures are consistently reproducible.

**Comment by markdroth** [comment]
Are there any new changes here since the original PR, or is this just a pure revert of the revert?

If there are new changes, can you please separate the new changes into a separate commit from the revert commit, so that I can see what changed?  Thanks!

**Comment by veblush** [comment]
There is no change at this moment. I'll do make a separate CL if something should be fixed.

**Comment by veblush** [comment]
This the result of second test run.

### Bazel RBE Debug C/C++
Failure is gone. Seems flaky.

### Basic Tests ObjC MacOS [dbg]
Same failure.

### Interop Cloud-to-Cloud Tests (internal CI)
- grpc/core/pull_request/linux/grpc_interop_tocloud
  https://source.cloud.google.com/results/invocations/e6029207-9219-44bf-af39-e2dc33765c72/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log
   2019-05-20 10:32:38,710 FAILED: cloud_to_cloud:nodepurejs:java_server:server_streaming:tls [ret=1, pid=28710, time=1.8sec]
  113 failed
-> Lots of failures are newly added.

### Interop Cloud-to-Prod Tests (internal CI)
- grpc/core/pull_request/linux/grpc_interop_toprod
  https://source.cloud.google.com/results/invocations/43bd30c6-9e0e-4fb8-94a3-c3444226f67c/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log
   2019-05-20 10:30:48,116 FAILED: cloud_to_prod:nodepurejs:default:server_streaming:tls [ret=1, pid=8059, time=1.9sec]
   2019-05-20 10:31:25,567 FAILED: cloud_to_prod:nodepurejs:gateway_v4:server_streaming:tls [ret=1, pid=8410, time=2.0sec]
  2 failed
-> 1 additional failure is found.

### Failed tests because of git failure.
These failed because "subprocess.CalledProcessError: Command '['git', 'merge-base', 'origin/null', 'HEAD']' returned non-zero exit status 128"

- Basic Tests C# MacOS
- Basic Tests C/C++ MacOS
- Basic Tests ObjC MacOS [opt]
- Basic Tests Python MacOS
- iOS Binary Size Diff (internal CI)

**Comment by veblush** [comment]
Test doesn't show anything special and Google3 internal test is done without any special test failure related with this.

**Pull request merged**
