### PR TITLE
Fix implicit declaration error in zlib + macOS

### PR DESCRIPTION
**Pull request by qnighy**
Fixes https://github.com/grpc/grpc/issues/24881. Based on https://github.com/madler/zlib/pull/300#issuecomment-328266399.

@nicolasnoble

### CODE REVIEW

**Comment by qnighy** [comment]
@apolcyn could you take a look at this too? This is similar to https://github.com/grpc/grpc/pull/24962 but the approach is different.

**Comment by apolcyn** [comment]
This seems reasonable, since we are basically assuming that [zlib's probe for whether unistd.h exists](https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/configure#L568) will always be successful. But we are already assuming that `unistd.h` is available since grpc sources themselves won't compile without it.

But if I understand correctly, this isn't just an OSX issue but an issue whenever `-Wimplicit-function-declaration`. So, should we apply define `HAVE_UNISTD_H` for all zlib sources in the Makefile build, not just for OSX?

Also, "sanity checks" failed here because the `Makefile` is actually auto-generated from `templates/Makefile.template`. What you'll need to do is to hand edit `templates/Makefile.template` and then run `tools/buildgen/generate_projects.sh` (ping this PR if you need help to do that).

Adding @nicolasnoble for a second googler's review

**Comment by qnighy** [comment]
Thanks! Removed `ifeq ($(SYSTEM),Darwin)` and it allowed me to move the configuration into `build_handwritten.yaml`.

**Comment by apolcyn** [comment]
basic tests python windows: https://github.com/grpc/grpc/issues/25124

**Review by apolcyn — APPROVED** [review]

**Review by nicolasnoble — APPROVED** [review]

**Pull request merged**
