### PR TITLE
Earworm avoidance PR

### PR DESCRIPTION
**Pull request by vjpai**
gRPC has a serious naming problem. In particular, one cannot see the repeated references to "Bidi" without immediately imagining disco beats and the introduction "Naa ghilaaaaaaf , Naa lihaaaaaf...."  Before long the work environment becomes a nonstop gyrating party atmosphere as team members climb on their desks exclaiming "Beedi jalaile jigar se piya, jigar maa badi aag hai". It will be total chaos.

To avoid the possibility of earworming, I have replaced all references to Bidi with Twodi, pronounced as in "gRPC is to die for".

This should be a quick and easy LGTM. I don't think it needs much discussion.

Cc: @hsaliak  @zinuga for programmatic guidance

### CODE REVIEW

**Comment by hsaliak** [comment]
I actually think bidi is a better name than twodi, since bidi, due to convention is a more common way to express streams going both ways simultaneously. Perhaps ```duplex``` is a better name if we want to avoid inadvertent gyrations?  

twodi to be honest sounds a lot like toddy, which is no better than bidi: https://en.wikipedia.org/wiki/Palm_wine

**Comment by hsaliak** [comment]
There are also a few API Changes there eg: BidiStreamingHandler -> TwodiStreamingHandler that I think are not worth it, no one listens to such an old song anyway.

**Comment by vjpai** [comment]
Do you really want people pouring Hint all over themselves in the middle of the day? Because this is how you get people pouring Hint all over themselves.

**Comment by vjpai** [comment]
Which language do you mean? TwodiStreamingHandler sits below the API level; it's only seen by people writing their own code generator.

**Pull request closed without merging**
