### PR TITLE
Properly detect C++ exception for MSVC

### PR DESCRIPTION
**Pull request by rongjiecomputer**
Inspired from protobuf

https://github.com/protocolbuffers/protobuf/blob/77f03d932a35e8aa0a98c0c728ad3f5aacfe30ce/src/google/protobuf/stubs/common.h#L50

### CODE REVIEW

**Comment by rongjiecomputer** [comment]
Ping @vjpai @nicolasnoble. Two CI failures should have nothing to do with this change.

**Comment by rongjiecomputer** [comment]
Ping after 2 weeks @vjpai @nicolasnoble

**Comment by rongjiecomputer** [comment]
Ping after 24 days @vjpai @nicolasnoble

**Comment by vjpai** [comment]
Do we have a reference compiler version that works versus doesn't work with exceptions on Windows so that we have some justification for disabling it as specified here

**Comment by vjpai** [comment]
Or compiler options for that matter

**Comment by rongjiecomputer** [comment]
> Do we have a reference compiler version that works versus doesn't work with exceptions on Windows so that we have some justification for disabling it as specified here

You mean which MSVC version that does not have `_CPPUNWIND` macro? As far as I know, MSVC has been using  this macro at least as far back as VS2013. This is the standard way to detect exception on MSVC: https://cs.chromium.org/search/?q=_CPPUNWIND&sq=package:chromium&type=cs

If you are asking why we should do this for MSVC, I would say why not since GCC style compiler already has it? I have been using this patch for awhile now, it saves some binary size when you don't need exception.

**Comment by rongjiecomputer** [comment]
Ping @vjpai

**Comment by rongjiecomputer** [comment]
Ping @vjpai

Can I know what I need to do on my side to move this forward? This PR has been lying around for 2 months.

**Comment by brightest-dazes** [comment]
What do you mean?

**Comment by AspirinSJL** [comment]
Raising priority because of the latency.

**Comment by vjpai** [comment]
Needs CLA.

**Comment by vjpai** [comment]
@AspirinSJL can you also provide a review

**Comment by brightest-dazes** [comment]
What's the PR been lying about?

**Pull request merged**
