### PR TITLE
Removed 3rd party dep on thrift

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by dgquintas** [comment]
Merging without waiting for tests in order to fix said tests.

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by ejona86** [comment]
@vjpai, that would be fine with me, and would simplify things a bit for us. Will the repo be grpc-ecosystem/grift?

**Comment by vjpai** [comment]
We should probably do it like that. I will look into setting up the repo next week. I'll create a new issue here for now.

**Comment by muxi** [comment]
I suspect the following two test failures are due to this change:
```
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/5076/testReport/junit/(root)/sanity_linux_dbg_native/tools_run_tests_sanity_check_sources_and_headers_py/
```
```
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/5076/testReport/junit/(root)/sanity_linux_dbg_native/tools_run_tests_sanity_check_submodules_sh/
```
Could you confirm/disconfirm?

**Pull request merged**
