### PR TITLE
dont use mktemp on aix as it does not exist

### PR DESCRIPTION
**Pull request by amandeepgautam**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @amandeepgautam isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by vjpai** [comment]
So, the Makefile is generated code; the actual file that should be edited is `templates/Makefile.template` and then you need to tun `tools/buildgen/generate_projects.sh` for your PR to be testable.

**Comment by amandeepgautam** [comment]
@vjpai I modified `templates/Makefile.template` file and running `tools/buildgen/generate_projects.sh` modifies a lot of files. Should those modified files also part of commit? How can I verify those changes? Any tests that I should run locally?

**Comment by vjpai** [comment]
Yes, all those modified files need to be committed as well.

As for tests, I think the best is to start with `make -k buildtests` since your expected effect is in make itself and not some other test.

**Comment by vjpai** [comment]
Ping @amandeepgautam can you commit the needed files?

**Comment by amandeepgautam** [comment]
@vjpai  I made another commit: https://github.com/amandeepgautam/grpc/commit/8ce6e44179b062a677dd5c799921e42082bd55c9

But I am afraid that removes all files related to boring ssl is not there on AIX. Can you look once and see if it is even worth trying to get this to merge.

**Pull request closed without merging**
