### PR TITLE
Revert "Revert "Allow encoding arbitrary channel args on a per-address basis.""

### PR DESCRIPTION
**Pull request by markdroth**
Reverts grpc/grpc#17450

I won't merge this until the internal change is ready.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
   +56% +3.34Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc         +3.34Ki   +56%
      +189% +1.65Ki on_hostbyname_done_locked                                                            +1.65Ki  +189%
      [NEW] +1.43Ki grpc_cares_wrapper_address_sorting_sort                                              +1.43Ki  [NEW]
      [NEW] +1.30Ki grpc_dns_lookup_ares_locked_impl                                                     +1.30Ki  [NEW]
      [NEW]    +250 log_address_sorting_list                                                                +250  [NEW]
       +28%    +128 on_dns_lookup_done_locked                                                               +128   +28%
      +9.1%     +18 grpc_resolve_address_ares_impl                                                           +18  +9.1%
       +18%     +13 [Unmapped]                                                                               +13   +18%
   +11% +1.77Ki src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                       +1.77Ki   +11%
      [NEW] +1.76Ki grpc_core::(anonymous namespace)::GrpcLb::CreateRoundRobinPolicyArgsLocked           +1.76Ki  [NEW]
      [NEW] +1.09Ki grpc_core::(anonymous namespace)::GrpcLb::CreateOrUpdateRoundRobinPolicyLocked() [cl +1.09Ki  [NEW]
       +83%    +956 grpc_core::(anonymous namespace)::GrpcLb::ProcessChannelArgsLocked                      +956   +83%
       +25%     +96 grpc_core::(anonymous namespace)::GrpcLb::~GrpcLb                                        +96   +25%
      +5.7%     +80 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::OnBalancerMessageReceiv     +80  +5.7%
      +2.4%      +9 [Unmapped]                                                                                +9  +2.4%
      +2.5%      +8 grpc_core::(anonymous namespace)::GrpcLb::PickLocked                                      +8  +2.5%
      +3.1%      +8 grpc_core::(anonymous namespace)::GrpcLb::PendingPickSetMetadataAndContext                +8  +3.1%
       +29%      +5 grpc_core::(anonymous namespace)::lb_token_cmp                                            +5   +29%
      +0.1%      +1 grpc_core::(anonymous namespace)::GrpcLbFactory::CreateLoadBalancingPolicy(grpc_core      +1  +0.1%
  [NEW] +1.30Ki src/core/ext/filters/client_channel/server_address.cc                                +1.30Ki  [NEW]
      [NEW]    +635 grpc_core::(anonymous namespace)::ServerAddressListCopy                                 +635  [NEW]
      [NEW]    +136 grpc_core::(anonymous namespace)::ServerAddressListCompare                              +136  [NEW]
      [NEW]    +114 grpc_core::(anonymous namespace)::ServerAddressListDestroy                              +114  [NEW]
      [NEW]    +102 grpc_core::ServerAddress::Cmp(grpc_core::ServerAddress const&) const                    +102  [NEW]
      [NEW]     +90 grpc_core::ServerAddress::ServerAddress                                                  +90  [NEW]
      [NEW]     +76 grpc_core::CreateServerAddressListChannelArg                                             +76  [NEW]
      [NEW]     +66 [Unmapped]                                                                               +66  [NEW]
      [NEW]     +47 grpc_core::FindServerAddressListChannelArg                                               +47  [NEW]
      [NEW]     +37 grpc_core::ServerAddress::IsBalancer() const                                             +37  [NEW]
      [NEW]     +24 grpc_core::ServerAddress::ServerAddress                                                  +24  [NEW]
  +7.4% +1.11Ki src/core/ext/filters/client_channel/lb_policy/xds/xds.cc                             +1.11Ki  +7.5%
      [NEW] +1.94Ki grpc_core::(anonymous namespace)::XdsLb::CreateOrUpdateChildPolicyLocked() [clone .p +1.94Ki  [NEW]
      +116% +1.30Ki grpc_core::(anonymous namespace)::XdsLb::ProcessChannelArgsLocked                    +1.30Ki  +116%
      [NEW]    +115 grpc_core::(anonymous namespace)::XdsLb::PendingPickCleanup                             +115  [NEW]
       +25%     +96 grpc_core::(anonymous namespace)::XdsLb::~XdsLb                                          +96   +25%
      +5.7%     +83 grpc_core::(anonymous namespace)::XdsLb::BalancerCallState::OnBalancerMessageReceive     +83  +5.7%
      +2.5%      +8 grpc_core::(anonymous namespace)::XdsLb::PickLocked                                       +8  +2.5%
   +46%    +832 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc              +832   +46%
      +114%    +722 grpc_core::(anonymous namespace)::CreateSockaddrResolver                                +722  +114%
      +263%    +108 grpc_core::(anonymous namespace)::SockaddrResolver::~SockaddrResolver                   +108  +263%
      +1.1%      +2 [Unmapped]                                                                                +2  +1.1%
  +6.2%    +800 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +800  +6.2%
       +25%    +780 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               +780   +25%
      [NEW]    +219 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc    +219  [NEW]
      +3.4%     +16 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +16  +3.4%
      +1.6%      +4 [Unmapped]                                                                                +4  +1.6%
   +21%    +560 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                 +560   +21%
       +73%    +554 grpc_core::(anonymous namespace)::NativeDnsResolver::OnResolvedLocked                   +554   +73%
      [NEW]     +65 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeFinishNextLocked() [clone      +65  [NEW]
      +5.5%      +6 [Unmapped]                                                                                +6  +5.5%
  +3.0%    +416 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                +416  +3.0%
       +24%    +644 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                              +644   +24%
      [NEW]    +592 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelList::StartWatchin    +592  [NEW]
      [NEW]    +219 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu    +219  [NEW]
      +4.7%     +11 [Unmapped]                                                                               +11  +4.7%
  +4.5%    +192 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc            +192  +4.5%
      +112%    +117 grpc_core::(anonymous namespace)::AresDnsResolver::~AresDnsResolver                     +117  +112%
      [NEW]    +111 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeFinishNextLocked() [clone .p    +111  [NEW]
      +5.6%     +88 grpc_core::(anonymous namespace)::AresDnsResolver::OnResolvedLocked                      +88  +5.6%
      +2.2%      +3 [Unmapped]                                                                                +3  +2.2%
  +0.5%     +48 src/core/ext/filters/client_channel/subchannel.cc                                        +48  +0.5%
      [NEW]     +76 grpc_core::ConnectedSubchannel::ConnectedSubchannel                                      +76  [NEW]
       +25%     +16 grpc_core::ConnectedSubchannel::~ConnectedSubchannel                                     +16   +25%
      +0.3%      +1 [Unmapped]                                                                                +1  +0.3%
  +0.5%     +32 src/core/ext/filters/client_channel/resolver_result_parsing.cc                           +32  +0.5%
      [NEW]    +260 grpc_core::internal::(anonymous namespace)::ParseDuration(grpc_json*, long*) [clone     +260  [NEW]
      [NEW]    +111 void grpc_core::ServiceConfig::ParseGlobalParams<grpc_core::internal::ProcessedResol    +111  [NEW]
      +7.9%     +31 grpc_core::internal::ProcessedResolverResult::ProcessLbPolicyName                        +31  +7.9%
      +1.8%      +1 [Unmapped]                                                                                +1  +1.8%
  +0.0%     +16 src/core/ext/filters/client_channel/client_channel.cc                                    +16  +0.0%
      [NEW] +3.51Ki on_resolver_result_changed_locked(void*, grpc_error*) [clone .part.83]               +3.51Ki  [NEW]
      [NEW]    +391 add_closure_for_subchannel_batch(grpc_call_element*, grpc_transport_stream_op_batch*    +391  [NEW]
      [NEW]    +192 add_retriable_send_message_op(grpc_call_element*, (anonymous namespace)::subchannel_    +192  [NEW]
      +4.5%     +16 [Unmapped]                                                                               +16  +4.5%
      +4.0%     +16 invoke_recv_message_callback                                                             +16  +4.0%
      +0.6%     +12 run_closures_for_completed_call                                                          +12  +0.6%
      +2.1%      +8 invoke_recv_initial_metadata_callback                                                     +8  +2.1%
  +0.7%     +16 src/core/lib/iomgr/sockaddr_utils.cc                                                     +16  +0.7%
      +7.1%     +16 grpc_sockaddr_to_uri                                                                     +16  +7.1%

 -------------- SHRINKING                                                                            --------------
  [DEL] -1.35Ki src/core/ext/filters/client_channel/lb_policy_factory.cc                             -1.35Ki  [DEL]
      [DEL]    -383 grpc_lb_addresses_cmp                                                                   -383  [DEL]
      [DEL]    -211 grpc_lb_addresses_set_address                                                           -211  [DEL]
      [DEL]    -164 grpc_lb_addresses_copy                                                                  -164  [DEL]
      [DEL]    -158 grpc_lb_addresses_set_address_from_uri                                                  -158  [DEL]
      [DEL]    -109 grpc_lb_addresses_destroy                                                               -109  [DEL]
      [DEL]     -91 grpc_lb_addresses_contains_balancer_address                                              -91  [DEL]
      [DEL]     -76 grpc_lb_addresses_create_channel_arg                                                     -76  [DEL]
      [DEL]     -72 [Unmapped]                                                                               -72  [DEL]
      [DEL]     -61 grpc_lb_addresses_create                                                                 -61  [DEL]
      [DEL]     -47 grpc_lb_addresses_find_channel_arg                                                       -47  [DEL]
      [DEL]      -5 lb_addresses_cmp                                                                          -5  [DEL]
      [DEL]      -5 lb_addresses_copy                                                                         -5  [DEL]
      [DEL]      -5 lb_addresses_destroy                                                                      -5  [DEL]
  -2.3%     -33 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_channel_secure.cc            -33  -2.3%
      -2.7%     -33 grpc_lb_policy_grpclb_modify_lb_channel_args                                             -33  -2.7%
  -2.6%     -33 src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_secure.cc                  -33  -2.6%
      -2.7%     -33 grpc_lb_policy_xds_modify_lb_channel_args                                                -33  -2.7%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.1% -1.00Ki [None]                                                                                +118Ki  +1.1%
      [NEW]     +96 grpc_core::(anonymous namespace)::BuildBalancerChannelArgs(grpc_core::InlinedVector<     +96  [NEW]
      [NEW]     +24 grpc_core::(anonymous namespace)::lb_token_arg_vtable                                    +24  [NEW]
      [NEW]     +24 grpc_core::(anonymous namespace)::server_addresses_arg_vtable                            +24  [NEW]
      [NEW]     +24 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +24  [NEW]
      [NEW]     +24 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +24  [NEW]
      [NEW]      +8 grpc_core::(anonymous namespace)::ExtractBalancerAddresses(grpc_core::InlinedVector<      +8  [NEW]
      [DEL]     -96 grpc_core::(anonymous namespace)::BuildBalancerChannelArgs(grpc_lb_addresses const*,     -96  [DEL]
      [DEL]     -48 grpc_core::(anonymous namespace)::lb_token_vtable                                        -48  [DEL]
      [DEL]     -24 lb_addresses_arg_vtable                                                                  -24  [DEL]
      [DEL]     -24 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -24  [DEL]
      [DEL]     -24 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     -24  [DEL]
     -16.7%      -8 vtable for grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData         -8 -16.7%
     -16.7%      -8 vtable for grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData           -8 -16.7%
     -16.7%      -8 vtable for grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::R      -8 -16.7%
     -16.7%      -8 vtable for grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::Pi      -8 -16.7%

  +0.5% +7.94Ki TOTAL                                                                                 +127Ki  +1.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   731,780       Core (>)        730,594

 2,020,870      Total (>)      2,019,548

***************FRAMEWORKS****************
  New size                      Old size
 3,970,386       Core (>)      3,949,210

11,177,119      Total (>)     11,155,944


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] Performance differences noted:
Benchmark                                     cpu_time    real_time
--------------------------------------------  ----------  -----------
BM_ClosureRunOnExecCtx                        +6%         +6%
BM_ErrorGetStatus<ErrorWithGrpcStatus>        +14%        +14%
BM_ErrorGetStatus<ErrorWithNestedGrpcStatus>  +11%        +11%
BM_ErrorGetStatusCode<ErrorNone>              +4%         +4%
BM_ErrorHttpError<ErrorNone>                  +4%         +4%
BM_ErrorHttpError<ErrorWithNestedGrpcStatus>  +8%         +8%
```

**Comment by markdroth** [comment]
Known failures: #17462 #17463

The "Basic Tests Windows [opt] (internal CI) " test is having infrastructure problems.

**Pull request merged**
