### PR TITLE
Manually Upmerge changes from 0.14 release branch into master

### PR DESCRIPTION
**Pull request by jtattermusch**
(getting ready for 0.15 release)

### CODE REVIEW

**Comment by jtattermusch** [comment]
@jcanizales   upmerging 0.14 changes was a bit tricky, can you please check for correctness?

@stanley-cheung  please check the PHP changes.

**Comment by jtattermusch** [comment]
CC @makdharma

**Comment by jtattermusch** [comment]
objC test have failed. 
https://grpc-testing.appspot.com/job/gRPC_pull_requests/9820/config=dbg,language=objc,platform=macos/console
@jcanizales  / @makdharma  can you please help?

**Comment by stanley-cheung** [comment]
PHP `package.xml` change LGTM

**Comment by jcanizales** [comment]
The Jenkins failure is because the Mac slave needs to be updated to Cocoapods 1.0. Travis did not run?

**Comment by jcanizales** [comment]
Obj-C-related changes LGTM, pending a tests run.

**Comment by jtattermusch** [comment]
@jcanizales  that means we would need to update all our mac workers to cocoapods 1.0 (doable, but it's nontrivial). Is there sufficient value in using 1.0 which will outweight the costs?

**Comment by jcanizales** [comment]
> Is there sufficient value in using 1.0 which will outweight the costs?

You mean beyond tests passing? :D Of the benefits, the biggest will be the ability to use Protobuf, which won't support pre-release versions of Cocoapods.

Travis did not run? It's already set up to use 1.0.

**Comment by jtattermusch** [comment]
@jcanizales  (after confirming with @makdharma  we turned off travis last week because the tests are not running on jenkins).

**Comment by jcanizales** [comment]
Then our two options are to turn it on again until we have time to update our Jenkins machines, or do that update.

**Comment by jtattermusch** [comment]
@jcanizales  I've updated the workers with the newest version of cocoapods, I'll restart the tests now and I really hope it helps.

**Comment by jtattermusch** [comment]
downgraded cocoapods on all mac workers to 1.0.0

**Comment by jtattermusch** [comment]
ObjC tests still failing. Now I saw this message in the log
```
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8 
```

**Comment by jtattermusch** [comment]
Tried fix from here: http://stackoverflow.com/questions/26990057/cocoapods-commands-fail-due-to-no-such-file-or-directory-dir-initialize-us  (thanks @makdharma)

And still seeing the same error:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/9905/config=dbg,language=objc,platform=macos/console

**Comment by jcanizales** [comment]
The warning shouldn't be a problem. The error is still `ArgumentError - invalid byte sequence in US-ASCII`

**Comment by jtattermusch** [comment]
this time we got further:

https://grpc-testing.appspot.com/job/gRPC_pull_requests/9908/config=dbg,language=objc,platform=macos/console

**Comment by jtattermusch** [comment]
@jcanizales  the warning warns about a problem with encoding which later results in ArgumentError. I set export LANG=en_US.UTF-8 as suggested and it got us further.

**Comment by jtattermusch** [comment]
@jcanizales  @makdharma , please help with resolving:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/9908/config=dbg,language=objc,platform=macos/console
(now the tests are building, but some of them are failing)

**Comment by jcanizales** [comment]
Pasting the error:
```
2016-06-14 16:43:17.342 xcodebuild[63264:199539695] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f93cc15bda0>
```
I have no idea what that is, but it sounds similar to when the simulator refuses to launch, or to behave.

Why don't we keep Travis enabled for comparison until we get these things nailed down?

**Comment by jtattermusch** [comment]
I re-enabled travis and merged with upstream/master to get a new test run.

**Comment by jtattermusch** [comment]
I re-enabled travis because running objC on jenkins is still problematic (and objC tests are failing on Jenkins on master anyway).

@nicolasnoble  Travis is green, let's merge this?

**Pull request merged**
