### PR TITLE
[PSM Interop] Fix the issue with URL Map test suite not cleaning up failed test client

### PR DESCRIPTION
**Pull request by larry-safran**
`tearDownClass` is not executed when `setUpClass` failed. In URL Map test suite, this leads to a test client that failed to start not being cleaned up.
This PR change the URL Map test suite to register a custom `addClassCleanup` callback, instead of relying on the `tearDownClass`. Unlike `tearDownClass`, cleanup callbacks are executed when the `setUpClass` failed.

ref b/276761453

### CODE REVIEW

**Review by sergiitk — COMMENTED** [review]
The style check is failing, please run `./bin/yapf.sh` as documented here: https://github.com/grpc/grpc/tree/master/tools/run_tests/xds_k8s_test_driver#making-changes-to-the-driver

**Comment by larry-safran** [comment]
Fixed the indent, but now get random test failures in the bazel builds.  Can't set the labels to force a rerun.

**Comment by sergiitk** [comment]
Restarted the failed TSAN job (surprised it's not excluded), and started adhoc PSM Interop URL Map:
- [grpc/core/v1.54.x/branch/linux/grpc_xds_url_map](https://source.cloud.google.com/results/invocations/a22f8d96-7ae3-414f-b568-d523e7ab57b1)

**Review by sergiitk — APPROVED** [review]
Test passed. Thank you so much for the contribution!

**Pull request merged**
