### PR TITLE
fix flakey race in ruby tests

### PR DESCRIPTION
**Pull request by apolcyn**
cc @muxi, this should fix the flake seen earlier

### CODE REVIEW

**Comment by apolcyn** [comment]
cc @murgatroid99 actually there is one more change I'd like to make before this is ready

**Comment by apolcyn** [comment]
actually sorry, I was looking for a way to avoid the `sleep 5` but I don't see any way to do this.

I think this is ready for review

**Comment by muxi** [comment]
Thanks for the fix Alex.

**Comment by apolcyn** [comment]
tests are green

**Pull request merged**
