### PR TITLE
Remove unused import

### PR DESCRIPTION
**Pull request by eundoosong**
- Remove unused import
  - collections are not used.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @eundoosong isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by eundoosong** [comment]
I think CLA is done.

**Comment by jtattermusch** [comment]
@mehrdada  please accept/close

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,588      Total (=)      1,964,588

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,886,953      Total (>)     10,886,951

 No significant differences in binary sizes


```

**Pull request merged**
