### PR TITLE
Add v1.50-1.52 releases of grpc-go to interop matrix

### PR DESCRIPTION
**Pull request by dfawley**

### CODE REVIEW

**Comment by dfawley** [comment]
(manual interop run started)

**Comment by dfawley** [comment]
The interop tests are failing, but the invocation log is empty so I'm not sure how to proceed.

**Comment by jtattermusch** [comment]
> Details

The job failed very early, so only the internal sponge invocation has some useful logs: 
http://sponge2.corp.google.com/a3e42ebd-34b9-4d44-aadd-000dd09fd0ca

I'll try look into what's wrong.

**Comment by jtattermusch** [comment]
I started the adhoc interop matrix run again: sponge/7b6dccad-8b7c-4674-aa9f-a9d158703234

**Comment by jtattermusch** [comment]
@dfawley  ok, it looks like the problem was caused by grpc_interop_matrix_adhoc.cfg being removed by mistake. https://github.com/grpc/grpc/pull/31709 adds it back, so that should fix your adhoc run.

**Pull request merged**
