### PR TITLE
Upgrade Node dependency on Protobuf.js to version 6

### PR DESCRIPTION
**Pull request by murgatroid99**
This is based on the work in #9004 by @paralin, but mostly rewritten to include some relevant refactoring and to ensure full backwards compatibility. `grpc.loadObject` now can load both Protobuf.js 5 and ProtoBuf.js 6 objects. ~~In order to load objects from ProtoBuf.js 6, and additional option `protobufjs_version` must be passed with the value `6`.~~

Code that needs to be present for compatibility with each version of ProtoBuf.js has been moved into `protobuf_js_[56]_common.js`. Some code that depends on the version of ProtoBuf.js, such as in `grpc.load`, has remained there, because that only needs to support one version of ProtoBuf.js at a time.

The Server method `addProtoService` is now deprecated, and `addService` should be used instead. `grpc.load` and `grpc.loadObject` now return objects that can be passed directly to `addService`.

The specific structure of some child objects in the output of `grpc.load` and `grpc.loadObject` have been modified, but those objects can still be used with the relevant `grpc` APIs as before.

All changes to tests are changes to the use of non-gRPC APIs and changes to stop using the deprecated function `addProtoService` (though that function is still tested).

### CODE REVIEW

**Comment by paralin** [comment]
> In order to load objects from ProtoBuf.js 6, and additional option protobufjs_version must be passed with the value 6

You can't just detect that? There are very clear differences between the structure in 5 and 6.

**Comment by paralin** [comment]
Nice, much better. LGTM.

**Comment by murgatroid99** [comment]
Note: due to dcodeIO/protobuf.js#710, this change is currently API breaking. Hopefully, that will be fixed soon.

**Comment by nicolasnoble** [comment]
Well, so, regarding the presence of the `protobufjs_version` option, we may or we may not be able to continue doing this in the future - aka, with an hypothetical version 7.

The setting might not be something we could skip later on, and the combinatorial detection might become an interesting problem.

I'd rather keep the option, but the values of the option could be something along the lines of:
```
protobufjs_version_5,
protobufjs_version_6,
protobufs_detect_version // best effort, may break in the future, you've been warned.
```

**Comment by paralin** [comment]
Remember that we are working in concert with the author of ProtobufJS and as such, we will have early warning to what the next version might look like. I don't think the reflection structure should change too much, 6 was a complete rewrite from scratch. 4->5 for example didn't require an update to grpc-node, afaik

**Comment by nicolasnoble** [comment]
So, two things.

First, my thought is to be more cautious than anything else. At that point, I'd rather have a method to override the autodetection now, instead of being stuck later on with a corner-case bug that would require adding that option in a bug-fix patch. If for any reason the autodetection wouldn't work for a given user - and with the way the autodetection is done right now, I can think of a couple of ways where that code would break - I'd rather like to be in a position where we can tell said user to just specify the option for his scenario, instead of having to require us to push a bugfix.

Second, I would be very very cautious about basing an API collaboration with other projects. Not that I have any beef against @dcodeIO, quite the contrary in fact, I enjoy ProtobufJS a lot. But in general, when creating an API, I prefer to be cautiously pessimistic if it deals with external projects.

**Comment by paralin** [comment]
What's stopping you from putting a peerDependency in place?

**Comment by murgatroid99** [comment]
If we use a peerDependency to force our users to upgrade their dependency on ProtoBuf.js, that's a breaking change, as much as if we just dropped support for ProtoBuf.js 5 in the code. If you're suggesting that we limit users to versions of ProtoBuf.js that we currently support, then that would not break anyone, but that is still an unreasonable way of resolving API compatibility issues.

**Comment by paralin** [comment]
Is it? To my understanding that's the entire point of peerDependency. If I upgrade to protobufjs 6 and keep the current version of grpc-node, there's no failure or warning at the npm install stage, only at runtime. This seems wrong, no? As it currently stands the default versions of both packages are incompatible with each other in a way that is not immediately apparent to users.

**Comment by murgatroid99** [comment]
But the goal here is to make gRPC compatible with ProtoBuf.js 6, not to prevent users from using ProtoBuf.js 6 (or 5 or 7 or whatever). Currently you can use gRPC and ProtoBuf.js 6 in the same program, they just won't interact well.

**Comment by dcodeIO** [comment]
Regarding protobuf.js version detection: A good marker is the presence of the `protobuf.Reflect` namespace. This is used in v5 (super unlikely to change), but no longer in v6 which uses a flat structure instead.

Another thing: Would it help if there'd be some sort of converter from v5 to v6 definitions (JSON)? So grpc could just use v6 under the hood, while it would keep working with v5 definitions?

**Comment by murgatroid99** [comment]
I'm not sure what you mean by "the presence of `protobuf.Reflect`. The situation we're trying to handle, essentially, is one where we have ProtoBuf.js 6 loaded within gRPC, and the user provides us with an object created using ProtoBuf.js 5. In that case, we don't have access to the entire ProtoBuf.js 5 module, just the one object.

What would help more than a simple converter is a function that takes old or current reflection objects and converts them to current relfection objects, plus a guarantee that that function will be in all versions of ProtoBuf.js going forward. The goal here is to ensure that if a user can currently load an object from a particular version of ProtoBuf.js, then they can continue to do so in the future, so that that API doesn't break.

**Comment by murgatroid99** [comment]
I have added a couple of tests that are currently failing due to dcodeIO/protobuf.js#710. Until they pass, this PR should not be merged.

**Comment by murgatroid99** [comment]
Note: this will also finally fix #4045

**Comment by murgatroid99** [comment]
The latest commit is a fix for #8595 and #8726.

**Comment by Arun-KumarH** [comment]
Any updates about this merge or when the new build would be available ?

**Comment by murgatroid99** [comment]
We are now waiting on dcodeIO/protobuf.js#748.

**Comment by murgatroid99** [comment]
It turns out that dcodeIO/protobuf.js#748 was actually caused by my own misunderstanding of their API.

**Pull request merged**
