### PR TITLE
[xds] Do not crash when XdsLocalityName is null

### PR DESCRIPTION
**Pull request by eugeneo**

### CODE REVIEW

**Review by yashykt — APPROVED** [review]

**Comment by markdroth** [comment]
In what circumstance is the locality name null here?

**Comment by eugeneo** [comment]
Not clear... Happens rarely in PSM Interop testing.

**Comment by markdroth** [comment]
I don't think it should ever happen.  If it is, then there's probably some deeper bug here, and this PR is just working around the symptom without solving the underlying problem.

**Comment by eugeneo** [comment]
I assumed it was fine since the rest of the code could survive the null. I will reopen the PSM bug but lower its priority.

**Pull request closed without merging**
