### PR TITLE
Correction link error: 404

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

@sheenaqotj

### CODE REVIEW

**Comment by yuxiaobo96** [comment]
I don't understand how to add this labels.
Please help me.

**Comment by tanjunchen** [comment]
ref:https://github.com/grpc/grpc/issues/21236
@sheenaqotj  review this? Maybe some urls need not to be fixed because of old docs.

**Pull request closed without merging**
