### PR TITLE
Upgrade protobufs to latest version that has C# support.

### PR DESCRIPTION
**Pull request by jtattermusch**
Upgrading to version of protobufs that already contains 
https://github.com/google/protobuf/pull/351

Also Fixes #1455

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Unfortunately, that still won't work :-) Protobuf needs to be republished with that commit backported in alpha-2 for everything to work fine.

**Comment by jcanizales** [comment]
@nicolasnoble Are they aware of that?

**Comment by nicolasnoble** [comment]
Yes.

**Comment by nicolasnoble** [comment]
I think @haberman is planning on doing it.

**Comment by jtattermusch** [comment]
Updated this pull request to use the new python protobuf package.

**Comment by nicolasnoble** [comment]
Your change still seems to fail on Python. However, my change here which has a few more tweaks does seem to work: nicolasnoble/grpc@342a2b69c6f743c9122249b13869496309ee692f

https://travis-ci.org/grpc/grpc/jobs/63107313

#1455 has been updated with it.

**Comment by nathanielmanistaatgoogle** [comment]
Closing; this has been superseded by #1654.

**Pull request closed without merging**
