### PR TITLE
Switches sample app to remote specs

### PR DESCRIPTION
**Pull request by jcanizales**
To help review: Only the 1st and 5th commit are manual; the other 3 are autogenerated by Cocoapods as a consequence of the 1st.

### CODE REVIEW

**Comment by tbetbetbe** [comment]
Why does the  PR report that 823 files have changed?

**Comment by jcanizales** [comment]
Cocoapods downloads and copies the dependencies into the Pods/ subdirectory of the app. This includes the source code for C gRPC, and the copied files are automatically transformed to have string.h -> grpc_string.h and time.h -> grpc_time.h

What I'm worried about is the failed C test, which says that it's using an OpenSSL version below what's required?

**Comment by jcanizales** [comment]
Ah, it's probably that third_party/openssl change in the first commit. I'm not sure what it is; definitely not intentional. Something to do with submodules apparently.

**Comment by nicolasnoble** [comment]
That commit is indeed reverting the OpenSSL submodule. You need to fix that.

But the ~823 added files are definitely too much, and it looks quite bad:
* it effectively duplicates all of the grpc header files and source code - src/objective-c/examples/Sample/Pods/gRPC/ is a full copy
* it includes pre-compiled libraries - src/objective-c/examples/Sample/Pods/OpenSSL/lib
* it includes files that we can't have in there for licensing reason, namely the OpenSSL header files in src/objective-c/examples/Sample/Pods/OpenSSL/opensslIncludes/openssl

Does the example /have/ to live in there ? Can't it go in grpc-common like all the other examples ? Distribution of the whole duplication of the source code nonwithstanding, that is. Or isn't there a way to acquire / generate these Cocoapods dependencies, akin to a `pip install` or a `gem install` ? Something that the endusers would run in order to generate that themselves.

**Comment by jcanizales** [comment]
End users *can* generate the dependencies by running `pod install`. Even so, the recommended practice (and what I'd prefer) is to check in source control the generated files, because:

* It makes builds possible even if/when some dependency's server, or the Cocoapods specs repo, becomes inaccessible.
* It makes builds hermetic and hence always reproducible.
* The (relatively fast) evolution of the cocoapods binary could otherwise break the build for users cloning this.
* It's much better experience for users if a sample app works as is when cloned. Without the generated code checked in, the app doesn't build. If after that the user is still interested, he might Google the problem, and find on StackOverflow that (as our documentation tells) he needs to install Cocoapods before and run some command.
* Not everybody will want to install Cocoapods.

The example can go on grpc-common, it doesn't need to be here. *Some* app will need to be here for development and tests, though, so the problem won't go away with that.

The generated files aren't a perfect copy of the sources of the dependencies. For the C library, it modifies occurrences of `time.h` and `string.h` with `grpc_time.h` and `grpc_string.h` so the library can build. For OpenSSL, the generated files are the headers and precompiled binaries (which a lot of people put into source control because compiling it takes ages).

What specifically prevents us from including the OpenSSL headers in this repo? Among the generated files is a copy of their license, FWIW.

**Comment by nicolasnoble** [comment]
While I can definitely appreciate the desire to create something that works out of the box - that's the reason we're having the generated Makefile in here for example - I do believe this one is taking it a notch slightly too far. I can't condone what I've described before: the duplicating of our own code (grpc core and objective-c), in such a way it'll deviate with time, and will need to be re-generated almost all the time, the duplicating of OpenSSL, which is already a third party submodule, and the checking in of pre-compiled libraries. There has to be a better way to do all of this.

**Comment by nicolasnoble** [comment]
So as a first step towards integrating this PR how about this: you basically rollback these changes to only contain the necessary modifications to the project without the actual pod installations, and you provide some documentation in a README.md file that explains how to do that for the end users. That should provide the same functionality with the extra pod installation step. From there, we can start discussing and evaluating how to proceed.

**Comment by jcanizales** [comment]
I'm not convinced a midway solution would help more than hinder. I also want to understand what we are trying to *prevent* by not checking in these generated files. So far we have:

1. The automatically modified (not duplicated) gRPC core would deviate over time and would need to be regenerated constantly.
2. X number of auto-generated files are too many.
3. Checking in precompiled binaries is bad.
4. OpenSSL's license doesn't let us copy its headers here.

The first one is fine with me, and the others I don't understand yet:

1. They are regenerated if necessary when I do `pod install` to test changes in the Objective-C code, which already is constantly.
2. What's this limit?
3. Not only it's common practice to have a precompiled OpenSSL checked in, we want to distribute the whole Objective-C library as a framework for people that don't use Cocoapods. A framework is just a specially-organized folder with the headers and precompiled binaries (including dependencies) inside. What's the reason *not* to check in a precompiled binary? Repo size?
4. Obviously IANAL, but I would expect us to be able to distribute it along with its license.

When we agree to the downsides of checking the files in, then we can balance them with the downsides of not checking them in:

1. Building this would depend on the OpenSSL and RubyGems servers being always reachable, making tests unnecessarily flaky.
2. Builds wouldn't be hermetic, but I don't think this will be a problem for the moment.
3. Recompiling the same OpenSSL unnecessarily adds XX minutes to start working on each new branch, and would add them to each run of Travis tests. It kills the development workflow (for me and anyone who would want to contribute).
4. It presents users with an app that's broken. But we can add big red warnings that point users to an example in grpc-common that has the generated files checked in, and that point developers to instructions to install and run Cocoapods.

We can decide to live with 1 and 2. I don't think we can afford 4 until we have more than zero users. And 3 is why this might hinder more than help.

**Comment by jcanizales** [comment]
Alternatives I can think of:
- I'm looking around at artifact repositories and the like, to see if there's something we could integrate with Cocoapods.
- Have a separate repo for Objective-C. This has upsides and downsides.
- Switch development to Bazel, and have Travis check that Cocoapods keeps working. This doesn't sound like it solves problem 3, though.

**Comment by nicolasnoble** [comment]
1. The main difference between the currently generated files, and the one you are proposing, is that we only have to regenerate the project files when people add or remove files to the project. We don't need to regenerate them for every single change in the project. Regenerating the examples on every commit to keep everything in sync would be excessive, and the alternative is to allow drifting, which is unacceptable. See #1124 by the way, which aims at adding a test against drifting for the currently generated files.

2. We don't have an actual number for the limit we're imposing. The only limit we have is "reasonable" - meaning that we'll only accept a reasonable amount of generated files in there. Every single file of grpc C core being duplicated is not a reasonable amount in my opinion.

3. I really, really don't want to have OpenSSL embedded in the project. I don't really care about what other projects are doing on that matter, but this won't be acceptable here. Several reasons:
* This is a security maintenance and responsibility burden. We don't want that burden.
* This would mean gRPC becomes a project that explicitly contains cryptography code. Under US laws, that isn't exportable outside US to certain countries, and we have to put a legal disclaimer for that. We don't want that.
* The OpenSSL license means if we distribute it, we have to change our own license to include the disclaimer that we are shipping with OpenSSL. 

That said, we are currently building OpenSSL regularly when doing our own tests. In fact, Travis currently does build OpenSSL 8 times for doing the tests, for every pull request, and every commit we're merging. We're also giving a batch script for the Windows users to build their own OpenSSL easily out of the third_party folder. But we still don't distribute OpenSSL ourselves.


All of that being said, I have absolutely no objection in switching to Bazel - in fact, I would be in favor of that.

**Comment by jcanizales** [comment]
Ok, that makes a lot of sense. I'll strip these pull requests of the generated files (and the bogus submodule change), and try to figure out if the "collaborate using Cocoapods" scenario can be saved.

**Comment by nicolasnoble** [comment]
I do believe that the cocoapods solution is a good one - which may be kept in parallel to what we'd offer here. Note that I just added a stub for Bazel support in my recent PR #1155 so maybe we can start working our way from here towards an acceptable solution.

**Comment by jcanizales** [comment]
Ok I already have a somewhat-clumsy way to work with the generated files there and send PRs without them, and these changes have already been merged without the generated files. So I'm closing this PR.

**Pull request closed without merging**
