### PR TITLE
guard multiprocessing code with main

### PR DESCRIPTION
**Pull request by Clement-Jean**
When trying to generate the documentation (`tools/buildgen/generate_projects.sh`) for issue #31986 I got the following error:

```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
``` 

And after searching a little bit, I found that on Windows and Mac, we need to guard multiprocessing code in the ` if __name__ == '__main__':` construct. I also tried to stay consistent with other python script that I found in the tools directory by adding a main function and then calling it inside the __main__.

### CODE REVIEW

**Comment by drfloob** [comment]
Did the script complete successfully for you on Windows after making this change? I believe you'll find that adding `freeze_support()` is not sufficient to get the `generate_projects.sh` script working on Windows, though I have not tried under WSL.

**Comment by Clement-Jean** [comment]
I only tried on Mac, I will give it a try on windows

**Comment by drfloob** [comment]
There's a broader issue that our build and distribution scripts do not support Windows. I do agree that adding `freeze_support` and removing code from the global scope is the right thing to do, but this effort should probably take a pass at making the build scripts work on Windows altogether. Otherwise, changes like this can't really be confirmed to be working / meaningful. 

I'll label this as "help wanted", in case you or anyone else wants to take up that challenge.

**Comment by drfloob** [comment]
Actually, @Clement-Jean , if you don't want to take on the broader project, it would probably be better to close this PR and open a tracking issue for the feature request.

**Comment by Clement-Jean** [comment]
I'm happy to help, but I thought we could go step by step. This would already help people being on Mac.

**Comment by drfloob** [comment]
> I'm happy to help, but I thought we could go step by step. This would already help people being on Mac.

Thanks. `generate_projects.sh` runs as is on mac with Python 3.9, a team member just confirmed. What version if Python + Mac OS are you having trouble with? Since `freeze_support` is [only meaningful on Windows](https://docs.python.org/3/library/multiprocessing.html#multiprocessing-programming:~:text=Calling%20freeze_support()%20has%20no%20effect%20when%20invoked%20on%20any%20operating%20system%20other%20than%20Windows), I'm not sure this PR actually fixes anything. Please correct me if I'm wrong.

In general, I'm fine to land an improvement, which this is. I just want to be clear about what it accomplishes for the sake of posterity.

**Comment by Clement-Jean** [comment]
Mac M1 Ventura 13.0.1
Python 3.9.9

Here are some links that showed other people with the problem:

- [Multiprocessing is not running on M1 MacBook Air - Big Sur 11.2](https://github.com/RI-imaging/ODTbrain/issues/15)
- [Multiprocessing with `Pool` throws error on M1 Macbook](https://stackoverflow.com/questions/67999589/multiprocessing-with-pool-throws-error-on-m1-macbook)

On my main branch (fork), I definitely can't run the script. But on this branch works just fine. Let me know how I can further help

**Comment by drfloob** [comment]
I see, this may be a change related to the Python implementation on Apple M1s. In that case, let's get this merged regardless. There are some file conflicts that will need to be resolved, please ping me when you've done so.

**Comment by Clement-Jean** [comment]
@drfloob That should be done

**Comment by drfloob** [comment]
@Clement-Jean the missing newline in the file is breaking the sanity checks.

**Comment by drfloob** [comment]
@Clement-Jean Sanity checks are again failing. It looks like you need to merge the latest master, and run `generate_projects.sh`.

**Comment by drfloob** [comment]
I took the liberty of trying to fix the build for you, and pushed a few commits to your branch. Somehow, XDS changes got picked up in your PR, and the execution bit was removed from `fix_build_deps`. You'll need to pull latest changes from github if you want to hack on the branch further. Hopefully this was enough to move this PR forward.

**Review by drfloob — APPROVED** [review]

**Review by yashykt — APPROVED** [review]

**Review by eugeneo — APPROVED** [review]

**Pull request merged**
