### PR TITLE
Allow conditional builds of grpc_csharp_ext for vcpkg manager

### PR DESCRIPTION
**Pull request by jozefizso**
When building grpc using `vcpkg` it is desired to disable compilation of `grpc_csharp_ext` library.

This PR adds new option `gRPC_BUILD_CSHARP_EXT` that controls build of `grpc_csharp_ext`.

For reference, see vcpkg portfile for grpc: https://github.com/Microsoft/vcpkg/blob/14708a09a9ade27dce3329ee8453a8a2724f94b6/ports/grpc/portfile.cmake

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @jozefizso isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jozefizso** [comment]
I've signed the CLA.

**Comment by jtattermusch** [comment]
@jozefizso   you also need to run `tools/buildgen/generate_projects.sh` to regenerate CMakeLists.txt  (see sanity test failure).

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jozefizso** [comment]
@jtattermusch I've rebased the pull request on to current master and regenerated the CMakeLists.txt file

**Comment by jtattermusch** [comment]
Known failures:
#15027
#15500
#13379

**Pull request merged**
