### PR TITLE
[ObjC] CF Stream Event Engine Client

### PR DESCRIPTION
**Pull request by HannahShiSFB**
bazel build --config=macos --genrule_strategy=local --copt="-DGRPC_CFSTREAM=1" //test/cpp/end2end:cfstream_test
succeeds

Fixing failure described here: https://github.com/grpc/grpc/pull/32882#issuecomment-1512210309

### CODE REVIEW

**Comment by sampajano** [comment]
@HannahShiSFB Thanks so much for fixing the test failures, Hannah!! Could you help highlight what is different from this PR the the original PR (https://github.com/grpc/grpc/pull/32077), for ease of review? Maybe in the form of making it a separate commit? Thanks!! 😃

**Comment by HannahShiSFB** [comment]
> @HannahShiSFB Thanks so much for fixing the test failures, Hannah!! Could you help highlight what is different from this PR the the original PR (#32077), for ease of review? Maybe in the form of making it a separate commit? Thanks!! 😃

Yes, the difference is a separate commit. [add cf event engine to macos build](https://github.com/grpc/grpc/pull/32924/commits/9be677fcc57ece44ee2dd147be445f4236199bd0)

**Comment by sampajano** [comment]
> > @HannahShiSFB Thanks so much for fixing the test failures, Hannah!! Could you help highlight what is different from this PR the the original PR (#32077), for ease of review? Maybe in the form of making it a separate commit? Thanks!! 😃
> 
> Yes, the difference is a separate commit. [add cf event engine to macos build](https://github.com/grpc/grpc/pull/32924/commits/9be677fcc57ece44ee2dd147be445f4236199bd0)

Oh ok!!! Thanks for clarifying!! Looks great!! 😃

**Review by sampajano — APPROVED** [review]
Thanks so much for fixing this, Hannah!! 😃

**Comment by HannahShiSFB** [comment]
bazel build --config=macos --genrule_strategy=local --copt="-DGRPC_CFSTREAM=1" //test/cpp/end2end:cfstream_test
succeeds. This internal CI should pass now. ready to merge. @sampajano 

Could you provide the script and log, if has any further failures please @drfloob

**Comment by drfloob** [comment]
> Could you provide the script and log, if has any further failures please @drfloob

I leave it to @sampajano to identify why our PR-specific CI jobs do not exercise the cfstream tests, while our master CI jobs do. I'm guessing it's a resource overhead or execution-time issue, but I do not know the history. I don't have the setup to reproduce iOS tests locally. 

Eryu, do you want to work on PR CI jobs before this is landed? The risk of course is having to roll it back again if the master tests fail.

**Comment by sampajano** [comment]
> > Could you provide the script and log, if has any further failures please @drfloob
> 
> I leave it to @sampajano to identify why our PR-specific CI jobs do not exercise the cfstream tests, while our master CI jobs do. I'm guessing it's a resource overhead or execution-time issue, but I do not know the history. I don't have the setup to reproduce iOS tests locally.
> 
> Eryu, do you want to work on PR CI jobs before this is landed? The risk of course is having to roll it back again if the master tests fail.

@drfloob Thanks for the considerations! Since Hannah has fixed the previous failure seen on master CI, i think we can attempt merging it (it should at least fix the original failure but yes theres's a risk of other failures but i think rollback would be fine if that happens).

I will work with @mikefan1991 to understand this discrepancy between PR CI and master CI.

---

@mikefan1991 Yingwei - Could you help take a look into why the following test is NOT ran as part of Github CI but is run as part of gRPC master CI? (See [this comment](https://github.com/grpc/grpc/pull/32882#issuecomment-1512210309) on master CI failure)

```
bazel build --config=macos --genrule_strategy=local --test_output=all --copt=-DGRPC_CFSTREAM=1 //test/cpp/end2end:cfstream_test
```

Thanks!!

**Pull request merged**
