### PR TITLE
Switch to C++14 if fully supported for our test platforms

### PR DESCRIPTION
**Pull request by vjpai**
Note that this is called c++1y on some compilers

c++17 (c++1z) is not an option if we continue to use the Debian Jessie default platform as our baseline supported platform since gcc-4.9 is the default compiler there and it doesn't support c++17 features.

### CODE REVIEW

**Comment by vjpai** [comment]
All the artifact builds passed, implying that this is ok for the build system used in Python and other wrapped languages. The benefits of switching to C++14 that we're likely to use are:

1. Allows assignment captures in lambdas (used in this PR itself)
1. Defines behavior of std::result_of when applied to arbitrary arguments (used in #18856)

**Comment by jtattermusch** [comment]
qq: what do we gain from this?

**Comment by mehrdada** [comment]
MOAR `constexpr`

**Comment by vjpai** [comment]
What @mehrdada said, plus assignment captures, return type deduction, and generically-parameterized lambdas. C++17 has more stuff but isn't supported under the default compiler for Jessie

**Comment by mehrdada** [comment]
@vjpai Please note that some Python end-users rely on build-from-source-package when they do `pip install`, and if they don't have a proper compiler installed they will fail, so this might have moar negative impact than may be obvious.

**Comment by nicolasnoble** [comment]
The goal is to do this for the C++ API only, not for the core.

**Comment by mehrdada** [comment]
@nicolasnoble if it does not affect the Core, why would Python care at all?

**Comment by nicolasnoble** [comment]
Right, so - if we CAN flip the flag globally, then good. If not, we'll have to modify our build infrastructure to distinguish between "code source code" and "C++ API source code" to only enable it there.

And if it CAN work in core, then maybe we can also introduce some of these concepts there.

**Comment by vjpai** [comment]
@mehrdada : I'll look into it. But gcc-4.9+ or clang-3.4+ is sufficient for what we need here; hopefully they'd have one of those?

**Comment by mehrdada** [comment]
@vjpai we have source distribtests that verify Alpine (not sure they run on every PR, but they do run on daily builds). You should be able to catch them if they break. I think you need to update setup.py though to pass C++14 flag.

**Pull request closed without merging**
