### PR TITLE
Initialize variables in surface/call.c

### PR DESCRIPTION
**Pull request by dgquintas**
Thanks to mbennett@

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM

**Comment by jboeuf** [comment]
LGTM. Maybe we should change the style guide to mandate that we always initialize pointers.

**Comment by dgquintas** [comment]
+1 @ctiller , what do you think. I can make the change in a jiffy.

**Comment by nicolasnoble** [comment]
@dgquintas: you can make another PR to the style guide change :-)

**Comment by dgquintas** [comment]
Yes, will do.

**Comment by dgquintas** [comment]
Done: https://github.com/grpc/grpc/pull/7243

**Pull request merged**
