### PR TITLE
PHP: attempt to fix mem leaks

### LINKED ISSUE #8074: PHP memory leaks
when I run the PHP example both `route_guide_client.php` and `greeter_client.php` have an memory leaks like this:

``` zsh
➜  php php greeter_client.php
Hello world
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/timeval.c(235) :  Freeing 0x7F5345863690 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/timeval.c(74) :  Freeing 0x7F53458636C0 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/call.c(246) :  Freeing 0x7F53458637E0 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/call.c(242) :  Freeing 0x7F5345863AB0 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/call.c(89) :  Freeing 0x7F5345863AE0 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/byte_buffer.c(71) :  Freeing 0x7F5345863B70 (14 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
/media/psf/code/src/php-7.0.10/Zend/zend_alloc.c(2518) : Actual location (location was relayed)
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/media/psf/code/src/php-7.0.10/Zend/zend_API.c(1061) :  Freeing 0x7F53458B2000 (56 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/media/psf/code/src/php-7.0.10/Zend/zend_objects.c(162) :  Freeing 0x7F53458C0A00 (40 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
=== Total 13 memory leaks detected ===
```

here is part of my PHP-ini

``` zsh
➜  php php -v
PHP 7.0.10 (cli) (built: Sep  6 2016 15:16:56) ( NTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
➜  php php --ri grpc

grpc

grpc support => enabled
```

### PR DESCRIPTION
**Pull request by thinkerou**
Attempt to fix #8074 memory leak.

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Sorry for the delay. Is there a simple reproducible test case? Can the PR be simplified so that it doesn't have 8 commits and 17 files changed? It's quite hard to review which part actually fixes the memleak.

**Comment by thinkerou** [comment]
@stanley-cheung I have removed eighth commits, if it still review hard, I will rewrite it tonight. Thanks.

**Comment by stanley-cheung** [comment]
ok to test

**Comment by stanley-cheung** [comment]
Thanks. The size of the PR is more manageable now. Can you still squash the 7 commits though? Thanks. I will do more testing tomorrow.

**Comment by thinkerou** [comment]
OK, done.

2017-01-10 12:54 GMT+08:00 Stanley Cheung <notifications@github.com>:

**Comment by stanley-cheung** [comment]
I did some manual testing on PHP 5.5/5.6/7.0 ubuntu14/debian8/ubuntu16 and all PHP tests passed

**Comment by thinkerou** [comment]
OK, thanks.

**Pull request merged**
