### PR TITLE
Migrate from dep.proto. to dep[ProtoInfo] provider

### PR DESCRIPTION
**Pull request by hlopko**
This PR updates grpc to be forward compatible for Bazel incompatible change https://github.com/bazelbuild/bazel/issues/7152. `ProtoInfo` provider was added in Bazel 0.22, therefore with this change grpc won't build with older Bazel.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @hlopko isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by hlopko** [comment]
I've signed the CLA.

**Comment by hlopko** [comment]
Test failures seemed like they were not caused by this PR, so I tried syncing. Is it expected that tests didn't finish running overnight?

**Comment by jtattermusch** [comment]
@hlopko  because you're not in the "grpc" github organization, you're changes need to be whitelisted before our CI runs the tests (it's a security measure), that's why the tests didn't finish overnight.

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/16580

**Comment by hlopko** [comment]
Thank you so much!

**Pull request merged**
