### PR TITLE
Add C++ streaming QPS test, fix bug in async C++ tests

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by ctiller** [comment]
Awesome!

**Comment by vjpai** [comment]
Looks like this branch has been sitting around for a while and merge conflicts have swept in (undoubtedly some caused by me related to range-based fors). I'm going to get this back in gear.

**Comment by yang-g** [comment]
Is it ready for review?

**Comment by vjpai** [comment]
Yes, sorry for not saying so earlier. Please review if you can.

**Comment by yang-g** [comment]
Will do.

**Pull request merged**
