### PR TITLE
Rename a flag in c-ares driver, add a test for cancelled queries

### PR DESCRIPTION
**Pull request by apolcyn**
Bringing this out of https://github.com/grpc/grpc/pull/15179

This changes the c-ares fd shutdown/destroy logic to use ref counts rather than `shutdown` and `readable/writeable_registered` flags, which makes it simpler to convert to C++ (which in turn simplifies porting to windows). Also adds a test for DNS queries that are cancelled.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/15420)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%     +88 [None]                                                                              +928  +0.0%
  +3.6%     +96 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posi     +96  +3.6%
      [NEW]    +275 grpc_ares_fd_node_unref                                                             +275  [NEW]
      [NEW]    +162 fd_node_shutdown                                                                    +162  [NEW]
       +22%     +64 grpc_ares_ev_driver_create                                                           +64   +22%
      [NEW]     +60 grpc_ares_fd_node_ref                                                                +60  [NEW]
       +19%     +16 [Unmapped]                                                                           +16   +19%

  +0.0%    +184 TOTAL                                                                              +1024  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%     +88 [None]                                                                              +928  +0.0%
  +3.6%     +96 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posi     +96  +3.6%
      [NEW]    +275 grpc_ares_fd_node_unref                                                             +275  [NEW]
      [NEW]    +162 fd_node_shutdown                                                                    +162  [NEW]
       +22%     +64 grpc_ares_ev_driver_create                                                           +64   +22%
      [NEW]     +60 grpc_ares_fd_node_ref                                                                +60  [NEW]
       +19%     +16 [Unmapped]                                                                           +16   +19%

  +0.0%    +184 TOTAL                                                                              +1024  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%     +88 [None]                                                                              +928  +0.0%
  +3.6%     +96 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posi     +96  +3.6%
      [NEW]    +275 grpc_ares_fd_node_unref                                                             +275  [NEW]
      [NEW]    +162 fd_node_shutdown                                                                    +162  [NEW]
       +22%     +64 grpc_ares_ev_driver_create                                                           +64   +22%
      [NEW]     +60 grpc_ares_fd_node_ref                                                                +60  [NEW]
       +19%     +16 [Unmapped]                                                                           +16   +19%

  +0.0%    +184 TOTAL                                                                              +1024  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
It's not clear to me that this PR moves us in the right direction.  The PR description says that this will make it easier to convert this code to C++, but I don't see how that's actually true, and it seems like it actually makes us behave more sloppily about cleaning up unused resources.  Let's chat in person about what you're trying to do here.

---

Reviewed 6 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 61 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCilrHFDc3Ghdswc9_K:-LCilrHFDc3Ghdswc9_L:b-i8ya3l) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L61)):*
> ```cpp
>   /** has this fd node been shutdown yet */
>   bool already_shutdown;
>   /** refcount of the fd node*/
> ```

Why is it useful to refcount the fd node?  It looks like we are always holding the EV driver lock when we manipulate the fd nodes, so why is refcounting beneficial?

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 139 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCijWXS63LzdHdnxRVc:-LCijWXS63LzdHdnxRVd:bkewuc7) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L139)):*
> ```cpp
>   ares_options opts;
>   memset(&opts, 0, sizeof(opts));
>   // Pass ARES_FLAGS_STAYOPEN: defer closing of fd's that were
> ```

This seems messy.  Why is this necessary?  Shouldn't this be handled by the call to `grpc_fd_orphan()` on line 100 above?

Actually, reading further, it seems like this is actually part of the main change in this PR, which is to defer cleanly shutting down the fd node until all requests are done.  But it's not clear to me why we want to do this.  What's the value in this change?  Why would we not want to clean up the fds as soon as we know that they're no longer needed?

---

*[test/cpp/naming/cancel_ares_query_test.cc, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCim8J4ER1sbQK3FaKB:-LCim8J4ER1sbQK3FaKC:b-oy72dp) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/test/cpp/naming/cancel_ares_query_test.cc#L86)):*
> ```cpp
>   }
>   ~FakeNonResponsiveDNSServer() { close(socket_); }
>   int socket_;
> ```

Data members should be private.

---

*[test/cpp/naming/cancel_ares_query_test.cc, line 89 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCimXrH-0VWQP_ZRZna:-LCimXrH-0VWQP_ZRZnb:b-hbki1f) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/test/cpp/naming/cancel_ares_query_test.cc#L89)):*
> ```cpp
> };
> 
> class CallWithNonResponsiveDNSServer {
> ```

It's not clear to me that this needs to be a class; it could just be a simple test function.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15420#-:-LCimgwiD1RUlbxviCUb:bvat52c)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +32  +0.0%

  [ = ]       0 TOTAL      +32  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by apolcyn** [comment]
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/cpp/naming/cancel_ares_query_test.cc, line 86 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCim8J4ER1sbQK3FaKB:-LCm3z9iBSEDD1fHi5MF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/test/cpp/naming/cancel_ares_query_test.cc#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Data members should be private.
</blockquote></details>

Done.

---

*[test/cpp/naming/cancel_ares_query_test.cc, line 89 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCimXrH-0VWQP_ZRZna:-LCm3zUz8qxirU815h7Q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/test/cpp/naming/cancel_ares_query_test.cc#L89)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not clear to me that this needs to be a class; it could just be a simple test function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15420)*

**Comment by apolcyn** [comment]
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/grpc/grpc/15420#-LCm4AefE5KMMeq8ua_n:-LCm4Aeg8o6uebzV7NZ5:bijhazn) (no related file):*
I've reverted the refcounting changes to the driver code and just renamed the fd node `shutting_down` variable, which does what I was trying to do.

I could carry on with this PR as is now, or another option is to add it to a later PR that does more of the actual driver C++-izing and Windows porting.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15420)*

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/grpc/grpc/15420#-LCm4AefE5KMMeq8ua_n:-LCni8Gr41ZqYPWsOmRT:b-4dzsnf) (no related file):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I've reverted the refcounting changes to the driver code and just renamed the fd node `shutting_down` variable, which does what I was trying to do.

I could carry on with this PR as is now, or another option is to add it to a later PR that does more of the actual driver C++-izing and Windows porting.
</blockquote></details>

I think this PR is fine as a stand-alone, or in combination with #15435.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 61 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCilrHFDc3Ghdswc9_K:-LCnf2zXAvFkgHIj3Vn6:b-5qf0wb) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L61)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I felt this simplified the code by making it easier to reason about exactly when an fd node will be destroyed: the driver holds a list of FD's, and that FD is destroyed once its removed from that list for lack of c-ares interest and after all of its pending callbacks are done. Also when converted to C++, we can then remove a few lines by having the driver just hold a list of `RefCountedPtr<FdNode>`'s that c-ares it interested in, and pass `Ref()`'s of those to the readable/writeable callback signups.
</blockquote></details>

Thanks for reverting this.  In general, the Google style guide says to avoid refcounting objects whenever possible.  There are some cases where it's appropriate, and we happen to have quite a few of those use-cases in gRPC (much more than in most Google projects), but we should always try to use single ownership instead of refcounting whenever feasible.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 139 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCijWXS63LzdHdnxRVc:-LCnfkOSBhqmIsrXTFO7:b-gw80dd) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L139)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Biggest reason for this was I thought this simplified things by allowing us to unconditionally call `grcp_fd_shutdown` for each fd node before destroying it (and to guarantee that happens).
</blockquote></details>

In light of the fact that we need to make this change anyway (as per #15435), I spent a while this morning reading through this code, and I now have a much clearer understanding of how this works than I did when we talked yesterday.  In retrospect, I think your original approach here was actually better.  Let's go back to doing it that way, minus the refcounting of the fd_node objects.  (Instead, I think you can have `grpc_ares_notify_on_event_locked()` free the node if it's not registered for either reads or writes.)

Sorry for steering you wrong on this!

---

*[test/cpp/naming/cancel_ares_query_test.cc, line 180 at r3](https://reviewable.io/reviews/grpc/grpc/15420#-LCnhqO_AVgw5GGGOfuR:-LCnhqO_AVgw5GGGOfuS:b1pktp2) ([raw file](https://github.com/grpc/grpc/blob/d03e4a71cfc1fcab6387e99fcd9dfc5e824a61ab/test/cpp/naming/cancel_ares_query_test.cc#L180)):*
> ```cpp
>   // including the teardown time (the teardown
>   // part of the test involves cancelling the DNS query,
>   // which is the main point of interest for this test).
> ```

Hmm...  This seems a bit of a roundabout way of testing this.  Would it make more sense to just manually instantiate the c-ares resolver and test its behavior directly?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15420)*

**Comment by apolcyn** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/grpc/grpc/15420#-LCm4AefE5KMMeq8ua_n:-LCo_BeR-b5cnCg6kIfV:b-8l3i9f) (no related file):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this PR is fine as a stand-alone, or in combination with #15435.
</blockquote></details>

When responding to comments, I'm finding that this is PR is very overlapped with #15435, so I'll add these changes into that one and closing out this one.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 61 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCilrHFDc3Ghdswc9_K:-LCo_Ufy0lq7Xa4ZDBVG:b-yn0rqf) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L61)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Thanks for reverting this.  In general, the Google style guide says to avoid refcounting objects whenever possible.  There are some cases where it's appropriate, and we happen to have quite a few of those use-cases in gRPC (much more than in most Google projects), but we should always try to use single ownership instead of refcounting whenever feasible.
</blockquote></details>


Thanks for explanation, sounds good.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 139 at r2](https://reviewable.io/reviews/grpc/grpc/15420#-LCijWXS63LzdHdnxRVc:-LCo_bEm3JERIxPc4jBp:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/07e9a74ec9567cab9d6eeaf43963c8f7cd2eae89/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L139)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In light of the fact that we need to make this change anyway (as per #15435), I spent a while this morning reading through this code, and I now have a much clearer understanding of how this works than I did when we talked yesterday.  In retrospect, I think your original approach here was actually better.  Let's go back to doing it that way, minus the refcounting of the fd_node objects.  (Instead, I think you can have `grpc_ares_notify_on_event_locked()` free the node if it's not registered for either reads or writes.)

Sorry for steering you wrong on this!
</blockquote></details>

Done.

---

*[test/cpp/naming/cancel_ares_query_test.cc, line 180 at r3](https://reviewable.io/reviews/grpc/grpc/15420#-LCnhqO_AVgw5GGGOfuR:-LCo_cF50INsnqT3u-cl:boe37zf) ([raw file](https://github.com/grpc/grpc/blob/d03e4a71cfc1fcab6387e99fcd9dfc5e824a61ab/test/cpp/naming/cancel_ares_query_test.cc#L180)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hmm...  This seems a bit of a roundabout way of testing this.  Would it make more sense to just manually instantiate the c-ares resolver and test its behavior directly?
</blockquote></details>

I could perhaps put this into something along the lines of the existing `resolver_component_test.cc`, but my main hesitation is I think the test code will probably be a little more complicated, and I think the current one is a way to be sure to cover the realistic resolver cancellation code path (i.e., it seems like a good sanity check that we don't hang, crash, or leak in this sort of scenario).

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15420)*

**Comment by apolcyn** [comment]
Since there's turning out to be a lot of overlap between this and https://github.com/grpc/grpc/pull/15435, I've merged the changes in this PR into https://github.com/grpc/grpc/pull/15435, and I'll close this one.

**Comment by apolcyn** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/cpp/naming/cancel_ares_query_test.cc, line 180 at r3](https://reviewable.io/reviews/grpc/grpc/15420#-LCnhqO_AVgw5GGGOfuR:-LD2qlN7Ad5j2kREi0hW:b-bh5q86) ([raw file](https://github.com/grpc/grpc/blob/d03e4a71cfc1fcab6387e99fcd9dfc5e824a61ab/test/cpp/naming/cancel_ares_query_test.cc#L180)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

I could perhaps put this into something along the lines of the existing `resolver_component_test.cc`, but my main hesitation is I think the test code will probably be a little more complicated, and I think the current one is a way to be sure to cover the realistic resolver cancellation code path (i.e., it seems like a good sanity check that we don't hang, crash, or leak in this sort of scenario).
</blockquote></details>

I've updated https://github.com/grpc/grpc/pull/15435 to use a more focused version of this test that does involve instantiating a resolver directly.
The test now has both the "client to server" end2end and this more focused one. I'm not really sure if we want to choose one over the other, open to ideas.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15420)*

**Pull request closed without merging**
