### PR TITLE
PHP: use php7_wrapper to reduce duplicated codes on v1.0.x branch(second part)

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Thanks for the contribution. Looks like by doing this, we cut down the number of occurance of `if PHP_MAJOR_VERSION < 7` from 55 to 45. Nice work!

**Comment by stanley-cheung** [comment]
@thinkerou Can you rebase your branch on the latest of `v1.0.x`? It will pick up the latest change that will test this PR properly on Jenkins. Thanks.

**Comment by thinkerou** [comment]
We need to support `>= PHP4.5` ?

I commit the PR to `v1.0.x` branch before, I have run the command `git fetch upstream`, `git merge upstream/v1.0.x` and `git push origin wrap_php7_on_v1_branch_second`.

`Basic tests` on PHP7 errors, this is because code merge error?

**Comment by stanley-cheung** [comment]
Can you try doing what you did again?

**Comment by stanley-cheung** [comment]
Please try doing these again. `git fetch upstream`, `git merge upstream/v1.0.x` and `git push origin wrap_php7_on_v1_branch_second`. It should pick up some latest change on the `v1.0.x` branch so that Jenkins can test this PR properly. Thanks,

**Comment by stanley-cheung** [comment]
Oh, nevermind. The change I was thinking wasn't on the `v1.0.x` branch.

**Comment by stanley-cheung** [comment]
LGTM. This is ready to merge.

**Comment by thinkerou** [comment]
OK

**Pull request merged**
