### PR TITLE
Dotnet CLI distrib tests and associated cleanup.

### PR DESCRIPTION
**Pull request by jtattermusch**
-- cleanup of project.json files (get rid of runtimes declaration thanks to importing Microsoft.NETCore.App with "type": "platform")
-- fixes in run_tests.py to run tests build by dotnet cli correctly
-- add a distribtest that tests `dotnet build` and `dotnet publish` for both `net45` and `netcoreapp1.0`
-- (hopefully) fix `dotnet publish` on `netcoreapp1.0` by adding a search path for the native extension.
-- enable building all nugets on linux (under docker) and zip them.
-- in distribtests, update nuget to 2.12 so that Grpc.sln can be restored.

Note: By default, the distribtests still run for the old way of building nuget packages (that will be changed in a followup PR if things go well).

Tentative fix for https://github.com/grpc/grpc/issues/8012.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Based on my grabbing the packages build by jenkins and running distribtests manually with them, it seems that the all the tested scenarios with dotnetcli now work.

the distribtest csharp_nuget_linux_x64_centos7 doesn't pass, but actually before this PR all the distribtests seemd to be broken (because of the nuget update -self)

**Comment by jtattermusch** [comment]
Tests seem green.

**Comment by apolcyn** [comment]
Sorry I'm just re-checking the non-passing centos distrib test, as I did see distrib tests passing earlier (when they were updated to System.Interactive.Async dependency, ran the nuget update -self and saw them pass in https://github.com/grpc/grpc/pull/7729).

Re-ran a build on v1.0.x just to check distrib tests, at https://grpc-testing.appspot.com/job/gRPC_build_artifacts/1712/

**Comment by jtattermusch** [comment]
+1 to double checking stuff (but if the distrib tests pass, I'd be very surprised).

**Comment by apolcyn** [comment]
LGTM

**Pull request merged**
