### PR TITLE
Removed const-ness from Reporter interface methods

### PR DESCRIPTION
**Pull request by dgquintas**
I shot myself in the foot when I made them so. It limits implementing classes too much.

### CODE REVIEW

**Comment by dgquintas** [comment]
Green (Travis-wise)

**Comment by vjpai** [comment]
LGTM, but  I want a heads up from @nicolasnoble before merging since I don't exactly know the rules in the Jenkins world.

**Comment by dgquintas** [comment]
Jenkin's green now too :)

**Comment by vjpai** [comment]
So there's still a red line for "unstable & flaky tests" - what to do about that?

**Comment by ctiller** [comment]
Ignore it. Nico is working on making it not red.

**Pull request merged**
