### PR TITLE
[bazel] fix python detection on windows

### PR DESCRIPTION
**Pull request by acxz**
This adds a patch that has been used internally for our project (https://github.com/ray-project/ray) for some time. Thought, I'd upstream it so that others can enjoy windows support.

@gnossen

### CODE REVIEW

**Review by gnossen — APPROVED** [review]
Thanks for the contribution!

**Comment by acxz** [comment]
@gnossen is there anything holding this PR up?

**Comment by acxz** [comment]
@gnossen friendly ping

**Comment by acxz** [comment]
@gnossen can you provide closure to this PR?

**Comment by gnossen** [comment]
@acxz Sorry for the hold-up. This looks good to go.

**Pull request merged**
