### PR TITLE
Allow to specify user provided audience in google default credentials and JWT credentials

### PR DESCRIPTION
**Pull request by yihuazhang**
This PR implements https://github.com/grpc/proposal/pull/241.

F.Y.I. @jiangtaoli2016

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/26392)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks good overall!  Comments are all relatively minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392#-:-Mb7VEyn3Tvx0ZxI3DiH:b-al50jm)* status: all files reviewed, 10 unresolved discussions (waiting on @yihuazhang)

___
*[include/grpc/grpc_security.h, line 164 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7PkYCE-P6lBxYelOX:-Mb7PkYCE-P6lBxYelOY:b-mvd6c1) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/include/grpc/grpc_security.h#L164)):*
> ```objc
> 
>    user_provided_audience is an optional field for user to override the
>    audience in the JWT token if used. If user_provided_audience is empty,
> ```

This should use null instead of empty string.
___
*[include/grpc/grpc_security.h, line 338 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7PSPcCooNrELDvjPH:-Mb7PSPcCooNrELDvjPI:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/include/grpc/grpc_security.h#L338)):*
> ```objc
>      will be cropped to this value.
>    - user_provided_audience is an optional field for user to override the
>      auidence in the JWT token. If user_provided_audience is empty, the
> ```

Same here.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7Pe-PBDtbfxCQjH9i:-Mb7Pe-PBDtbfxCQjH9j:bn95ioa) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/ext/xds/xds_bootstrap.cc#L62)):*
> ```cpp
>                                           const Json& /*config*/) {
>   if (creds_type == "google_default") {
>     return grpc_google_default_credentials_create(nullptr, "");
> ```

This should pass nullptr instead of an empty string.
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7RfvcAD-q0oHjMLBL:-Mb7RfvcAD-q0oHjMLBM:bozw4pa) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L62)):*
> ```cpp
>   gpr_timespec refresh_threshold = gpr_time_from_seconds(
>       GRPC_SECURE_TOKEN_REFRESH_THRESHOLD_SECS, GPR_TIMESPAN);
>   std::string audience = user_provided_audience_.empty()
> ```

Please change the type of this to `absl::string_view` to avoid making an unnecessary copy.
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 142 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7Qzd8481enTl1xoyQ:-Mb7Qzd8481enTl1xoyR:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L142)):*
> ```cpp
>   }
>   return grpc_core::MakeRefCounted<grpc_service_account_jwt_access_credentials>(
>       key, token_lifetime, user_provided_audience);
> ```

`std::move()`
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 175 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7Qdm79SakAuV31-iB:-Mb7Qdm79SakAuV31-iC:b-ay4g04) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L175)):*
> ```cpp
>   grpc_core::ApplicationCallbackExecCtx callback_exec_ctx;
>   grpc_core::ExecCtx exec_ctx;
>   return grpc_service_account_jwt_access_credentials_create_from_auth_json_key(
> ```

Before this line, please add:

```
if (user_provided_audience == nullptr) user_provided_audience = "";
```
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 177 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7QQgb3dZINEoLCbHy:-Mb7QQgb3dZINEoLCbHz:b-hixlg3) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L177)):*
> ```cpp
>   return grpc_service_account_jwt_access_credentials_create_from_auth_json_key(
>              grpc_auth_json_key_create_from_string(json_key), token_lifetime,
>              std::string(user_provided_audience))
> ```

No need to explicitly convert to `std::string` here; that will happen automatically, since `std::string` is constructible from `const char*`.
___
*[src/cpp/client/secure_credentials.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7SfdD7kSIxHOatwC6:-Mb7SfdD7kSIxHOatwC7:b-k6icz2) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/cpp/client/secure_credentials.cc#L111)):*
> ```cpp
>   return internal::WrapChannelCredentials(
>       grpc_google_default_credentials_create(nullptr,
>                                              user_provided_audience.c_str()));
> ```

Please use the following here:

```
user_provided_audience.empty() ? nullptr : user_provided_audience.c_str()
```
___
*[src/cpp/client/secure_credentials.cc, line 336 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7T1PU0hEFLxd9077q:-Mb7T1PU0hEFLxd9077r:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/cpp/client/secure_credentials.cc#L336)):*
> ```cpp
>       gpr_time_from_seconds(token_lifetime_seconds, GPR_TIMESPAN);
>   return WrapCallCredentials(grpc_service_account_jwt_access_credentials_create(
>       json_key.c_str(), lifetime, user_provided_audience.c_str()));
> ```

Same here.
___
*[src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi, line 437 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7T4Xm3RCveNxoah8u:-Mb7T4Xm3RCveNxoah8v:bfex0ux) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi#L437)):*
> ```Cython
> 
>   cdef grpc_channel_credentials *c(self) except *:
>     self._c_creds = grpc_google_default_credentials_create(self._call_creds, '')
> ```

This should pass null instead of empty string.

**Review by yihuazhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392)* status: all files reviewed, 10 unresolved discussions (waiting on @markdroth)

___
*[include/grpc/grpc_security.h, line 164 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7PkYCE-P6lBxYelOX:-MbBWlfFBrcNsGv2AJqJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/include/grpc/grpc_security.h#L164)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use null instead of empty string.
</blockquote></details>

Done.
___
*[include/grpc/grpc_security.h, line 338 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7PSPcCooNrELDvjPH:-MbBWvsU5vJi7duhtZMF:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/include/grpc/grpc_security.h#L338)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7Pe-PBDtbfxCQjH9i:-MbBWyRk81JAPMLXQyBi:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/ext/xds/xds_bootstrap.cc#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should pass nullptr instead of an empty string.
</blockquote></details>

Done
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7RfvcAD-q0oHjMLBL:-MbBX2GTCscn8ajMQXhJ:bz2n0e2) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please change the type of this to `absl::string_view` to avoid making an unnecessary copy.
</blockquote></details>

After changing it to `absl::string_view`, the check `cached_.audience == audience` below fails which I am pretty confused about. I thought we can do a comparison between string and string_view with ==. Did I miss something? 
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 142 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7Qzd8481enTl1xoyQ:-MbBY4Yc2T-AU_jJ2T5t:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L142)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 175 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7Qdm79SakAuV31-iB:-MbBY5VL2P-YTLgxdJa7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L175)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Before this line, please add:

```
if (user_provided_audience == nullptr) user_provided_audience = "";
```
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 177 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7QQgb3dZINEoLCbHy:-MbBY6a650UMt84JqzO_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L177)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to explicitly convert to `std::string` here; that will happen automatically, since `std::string` is constructible from `const char*`.
</blockquote></details>

Done.
___
*[src/cpp/client/secure_credentials.cc, line 111 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7SfdD7kSIxHOatwC6:-MbBYBMT4rS33yjwgqxV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/cpp/client/secure_credentials.cc#L111)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use the following here:

```
user_provided_audience.empty() ? nullptr : user_provided_audience.c_str()
```
</blockquote></details>

Done.
___
*[src/cpp/client/secure_credentials.cc, line 336 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7T1PU0hEFLxd9077q:-MbBYMiJ9XxE9oqA3hyN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/cpp/client/secure_credentials.cc#L336)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi, line 437 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7T4Xm3RCveNxoah8u:-MbBYO2m--N07qXxxvcZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi#L437)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should pass null instead of empty string.
</blockquote></details>

Done.

**Comment by jiangtaoli2016** [comment]
Thank you Yihua for the change!

**Review by markdroth — CHANGES_REQUESTED** [review]
Just a few minor nits remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392#-:-MbCvPbE4zNxWs_ZsvCZ:b-w24zng)* status: all files reviewed, 3 unresolved discussions (waiting on @yihuazhang)

___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7RfvcAD-q0oHjMLBL:-MbCuBA-2LnP2iYGAC7S:bqw1xu5) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L62)):*
<details><summary><i>Previously, yihuazhang (yihuaz) wrote…</i></summary><blockquote>

After changing it to `absl::string_view`, the check `cached_.audience == audience` below fails which I am pretty confused about. I thought we can do a comparison between string and string_view with ==. Did I miss something? 
</blockquote></details>

You can, but you need to change the order of the operands.  Try changing it to `audience == cached_.audience`.
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 69 at r3](https://reviewable.io/reviews/grpc/grpc/26392#-MbCuKPt8qR57HaJqpzd:-MbCuKPt8qR57HaJqpze:bws18iu) ([raw file](https://github.com/grpc/grpc/blob/ae23dadbf9b42d1b3a9457a83fbcbc9eafece9a5/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L69)):*
> ```cpp
>   {
>     gpr_mu_lock(&cache_mu_);
> ```

Please remove unnecessary blank lines within functions.
___
*[src/cpp/client/secure_credentials.cc, line 109 at r3](https://reviewable.io/reviews/grpc/grpc/26392#-MbCv9wNEnD4-zm7D6Gb:-MbCv9wNEnD4-zm7D6Gc:bh1w4w3) ([raw file](https://github.com/grpc/grpc/blob/ae23dadbf9b42d1b3a9457a83fbcbc9eafece9a5/src/cpp/client/secure_credentials.cc#L109)):*
> ```cpp
>     const grpc::string& user_provided_audience) {
>   grpc::GrpcLibraryCodegen init;  // To call grpc_init().
> ```

Please remove blank line.

**Review by yihuazhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7RfvcAD-q0oHjMLBL:-MbD12Zr5Wi7eOyiGVvC:b5pr48o) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You can, but you need to change the order of the operands.  Try changing it to `audience == cached_.audience`.
</blockquote></details>

Ugh... the test still fails the check after changing the order.
___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 69 at r3](https://reviewable.io/reviews/grpc/grpc/26392#-MbCuKPt8qR57HaJqpzd:-MbD10uPE5SUBbTxnNZN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ae23dadbf9b42d1b3a9457a83fbcbc9eafece9a5/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L69)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove unnecessary blank lines within functions.
</blockquote></details>

Done.
___
*[src/cpp/client/secure_credentials.cc, line 109 at r3](https://reviewable.io/reviews/grpc/grpc/26392#-MbCv9wNEnD4-zm7D6Gb:-MbD11ky3sMMioxGo3Ev:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ae23dadbf9b42d1b3a9457a83fbcbc9eafece9a5/src/cpp/client/secure_credentials.cc#L109)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.

**Review by markdroth — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392)* status: all files reviewed, 1 unresolved discussion (waiting on @yihuazhang)

___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7RfvcAD-q0oHjMLBL:-MbHuiwVDmPYasvf2TRv:b-hewbf2) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L62)):*
<details><summary><i>Previously, yihuazhang (yihuaz) wrote…</i></summary><blockquote>

Ugh... the test still fails the check after changing the order.
</blockquote></details>

It looks like I was wrong; I thought `absl::string_view` provided an overload of the `operator==()` method for `std::string`, but it doesn't.

Try saying `absl::string_view(cached_.audience) == audience`.

**Comment by yihuazhang** [comment]
> > Reviewed 1 of 7 files at r2, 2 of 2 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392)_ status: all files reviewed, 1 unresolved discussion (waiting on @yihuazhang)
> 
> _[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7RfvcAD-q0oHjMLBL:-MbHuiwVDmPYasvf2TRv:b-hewbf2) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L62)):_
> 
> Previously, yihuazhang (yihuaz) wrote…
> It looks like I was wrong; I thought `absl::string_view` provided an overload of the `operator==()` method for `std::string`, but it doesn't.
> 
> Try saying `absl::string_view(cached_.audience) == audience`.

Using `absl::string_view(cached_.audience) == audience` still fails. I got it work by explicitly constructing a `string_view` object (by passing in a start pointer and length).

**Review by markdroth — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392)* status: all files reviewed, 1 unresolved discussion (waiting on @yihuazhang)

___
*[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7RfvcAD-q0oHjMLBL:-MbI0P2B5DOk_9mwbPMC:b-iybdxt) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L62)):*
<details><summary><i>Previously, yihuazhang (yihuaz) wrote…</i></summary><blockquote>

Using `absl::string_view(cached_.audience) == audience` still fails. I got it work by explicitly constructing a `string_view` object (by passing in a start pointer and length).  
</blockquote></details>

Oh!  So the problem here was not the `==` operation below, it was the way that you were constructing the `string_view` here.

I don't think you need to explicitly call `strlen()` here.  You can just say `absl::string_view(context.service_url)`.

**Comment by yihuazhang** [comment]
> > Reviewed 1 of 1 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392)_ status: all files reviewed, 1 unresolved discussion (waiting on @yihuazhang)
> 
> _[src/core/lib/security/credentials/jwt/jwt_credentials.cc, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/26392#-Mb7RfvcAD-q0oHjMLBL:-MbI0P2B5DOk_9mwbPMC:b-iybdxt) ([raw file](https://github.com/grpc/grpc/blob/b3d288b7c3ec388e522fd4a1bc9651b483e4f437/src/core/lib/security/credentials/jwt/jwt_credentials.cc#L62)):_
> 
> Previously, yihuazhang (yihuaz) wrote…
> Oh! So the problem here was not the `==` operation below, it was the way that you were constructing the `string_view` here.
> 
> I don't think you need to explicitly call `strlen()` here. You can just say `absl::string_view(context.service_url)`.

Done.

**Review by markdroth — APPROVED** [review]
Looks great!

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26392#-:-MbI8hSaCO7gnSpuERyX:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yihuazhang)

**Comment by yihuazhang** [comment]
Thanks much for the review, Mark!

**Comment by markdroth** [comment]
@yashykt Once grpc/proposal#241 is merged, we'll need to release a new patch for 1.38 that includes this change.  It's needed for C++ only, not wrapped languages.

**Comment by lidizheng** [comment]
@yihuazhang This PR broke gRPC-Swift: https://fusion2.corp.google.com/invocations;query=label:tap%20label:postsubmit%20cl:377715297%20target:%2F%2Fgooglemac%2FGoogleMobile:GoogleEarlGreyTestRig.apple_binary

**Comment by yihuazhang** [comment]
@ZhenLian Do you mind taking a look at the gRPC-swift breakage? It might be as simple as the API call site change. I am currently on vacation, and would not be able to get on to it by June 13th.

**Comment by ZhenLian** [comment]
Yeah, the breakage seems easy-to-fix, but it appears that the roll back has already been done...It seems a cherry-pick would be needed. 
Yihua, do you want me to re-import all the changes and apply the patch?

**Pull request merged**
