### PR TITLE
 Upmerge v1.15.x to master

### PR DESCRIPTION
**Pull request by AspirinSJL**
For https://github.com/grpc/grpc/pull/16521.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,026      Total (=)      1,955,026

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,757      Total (>)     10,843,755

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Failures:
https://github.com/grpc/grpc/issues/16471
https://github.com/grpc/grpc/issues/15599

**Pull request merged**
