### PR TITLE
Add a simple export tool for JSON performance scenarios

### PR DESCRIPTION
**Pull request by jtattermusch**
This tool  consumes scenario_config.py  and dump selected (by category and regex) scenarios as json files.
This seems useful as a building block for the OSS benchmarks.

### CODE REVIEW

**Review by codeblooded — APPROVED** [review]
LGTM @jtattermusch -- Thanks for the script to help us along. /cc @grpc/test-infra

**Review by paulosjca — APPROVED** [review]

**Comment by jtattermusch** [comment]
I just found out that the json files aren't directly usable for the configMaps in OSS benchmarks.

The example json scenarios you're using are wrapped in an additional `{ "scenarios": [ THE_SCENARIO ] }` at the top level.
E.g. https://github.com/grpc/test-infra/blob/a51aa917bafa7f0747735fb5f390522e18f0c837/config/samples/java_example_scenario.json#L2
(which is also a format that's accepted directly  by the qps_json_driver)

Which scenario format we want to use in the long run is TBD.

**Comment by codeblooded** [comment]
Yes, I'm sorry I missed that. It's funny you mention the fact that the driver accepts multiple, because we had a discussion about this yesterday in the chat. 

Fundamentally this allows a user to run multiple scenarios in a single load test. By default, I think we should use examples with only 1 to show it's a best practice. But, perhaps there are instances where multiple could be useful. For instance, if I run a Java scenario and then notice an extreme degradation in performance running another one, this may indicate some sort of leak.

I was thinking of this like a hidden nob that could be used by devs who need it, but the 99% would use 1 scenario/test for hermetic purposes. As you said, it's TBD. Maybe we can discuss it on Tuesday.

**Comment by paulosjca** [comment]
> I just found out that the json files aren't directly usable for the configMaps in OSS benchmarks.

I would not worry about that right now. We are in the process of designing how the scenarios are going to be combined with a LoadTest configuration for continuous integration. We can use your script as a baseline and change it to support the process as we settle on it.

**Comment by jtattermusch** [comment]
I updated the script to always generate `{ "scenarios" : [] }` as the top level element to match the format required by ScenariosJSON.

**Comment by jtattermusch** [comment]
Python failure is an unrelated flake: https://source.cloud.google.com/results/invocations/323df08c-f79f-4210-b5ef-ebcf61b34316/targets

**Pull request merged**
