### PR TITLE
Add clang3.4 and 3.6 support to run_tests.py

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Seems green enough.

**Comment by jtattermusch** [comment]
friendly ping.

**Comment by jtattermusch** [comment]
This should make portability tests on master more green, so it can be considered part of the fixit.

**Comment by jtattermusch** [comment]
@ctiller , we can either merge this and then fix  clang3.4 and 3.6 (shouldn't be hard I hope) or we could disable clang3.4 and 3.6 tests on master (currently red). I prefer the first but leaving up to you.

**Comment by ctiller** [comment]
I'd lean towards holding this back until all present bugs are fixed and
seeing if we have time.

**Comment by jtattermusch** [comment]
@ctiller , can I have an LGTM for this one?  (so we can eventually merge as part of "keeping it green")?

**Comment by ctiller** [comment]
Lgtm

**Pull request merged**
