### PR TITLE
[Backport] Reduce the workload of presubmit artifact builds and distribtests

### PR DESCRIPTION
**Pull request by lidizheng**
Backports #28228

### CODE REVIEW

**Review by jtattermusch — APPROVED** [review]
Fair enough, but I'd be more in favor of backporting just the duplication of the `master/*.cfg` files to `pull_request/*.cfg`.
There is no reason to introduce extra complexity to an already-cut branch (and increase the risk of breaking stuff on release branch where we should do as few changes as possible). And you might need to backport to older release branches at some point as well, at which point backporting the entire PR or nontrivial complexity might be problematic.

Leaving the final resolution up to you.

**Comment by jtattermusch** [comment]
Let's merge https://github.com/grpc/grpc/pull/28298 instead.

**Review by jtattermusch — CHANGES_REQUESTED** [review]
Undo LGTM.

**Comment by lidizheng** [comment]
Thanks for creating a thiner version of this PR. It's nice to be cautious. Closing this PR https://github.com/grpc/grpc/pull/28298.

**Pull request closed without merging**
