### PR TITLE
Revert unneeded change in qps worker

### PR DESCRIPTION
**Pull request by vjpai**
I believe that this change was unneeded and actually
may hurt matters by holding a lock for too long.

Partially undoes #5444 , particularly commit e7042b5

### CODE REVIEW

**Comment by vjpai** [comment]
@ctiller : I went back to the code that you originally wrote but that I mucked around with. But I can assign it elsewhere if you are overloaded.

**Comment by ctiller** [comment]
LGTM

**Comment by vjpai** [comment]
Remaining failures in basic tests are unrelated
Re-running portability test

**Comment by vjpai** [comment]
Remaining failures in basic tests are unrelated
Portability test passes

**Pull request merged**
