### PR TITLE
Stop supporting non-C++11 conformant compilers - DO NOT MERGE INTO V1.0.X

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by vjpai** [comment]
Mark, you will have to give many more approvals down the road as we get the rest of the code looking good.

**Comment by vjpai** [comment]
Cc: @matt-kwong @ctiller @yang-g @y-zeng @dgquintas

**Comment by vjpai** [comment]
This PR depends on the merging of PR #8600 since it's not testable until that point.

**Comment by vjpai** [comment]
There are no longer any references to macros that start with GRPC_CXX

TODO:

1. Switch uses of gpr_sleep_until with std::this_thread::sleep_for . This exists only in test/cpp
2. Eliminate uses of grpc::thread, grpc::condition_variable, etc and then delete include/grpc/impl/thd.h and include/grpc/impl/sync.h

**Comment by dgquintas** [comment]
Much glorious, very joy.

**Comment by vjpai** [comment]
I think this covers all the mechanical changes and gets everything running in true C++11; I would suggest that the remaining changes are stylistic (lambdas, ranges, etc) and should be done in the future. PTAL.

**Comment by markdroth** [comment]
Still LGTM.

**Comment by vjpai** [comment]
I have re-merged master now that #8600 is merged: that should allow the portability tests to actually pass.

**Comment by vjpai** [comment]
Remaining issues are known flakes.

**Pull request merged**
