### PR TITLE
Change c++_codegen_lib from build: protoc to build: all

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by dgquintas** [comment]
this is a "backport" right?

**Comment by dgquintas** [comment]
LGTM

**Comment by jtattermusch** [comment]
Btw, why exactly do we need this?

**Comment by jtattermusch** [comment]
Got explanation offline.

**Comment by jtattermusch** [comment]
@vjpai , @dgquintas  turns out explanations made offline are a bad idea because now I don't remember why we needed this and this causes #6011.   I'm tempted to revert, what would be the consequences?

**Comment by ctiller** [comment]
Next import would fail.

I think I know how to fix this forever... By removing the need to create
the codegen stuff as libs. Going to amend #6092 to set the stage (and also
fix the bug you referred to)

**Pull request merged**
