### PR TITLE
Optimizing Ring Hash creation.

### PR DESCRIPTION
**Pull request by donnadionne**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/26420)

### CODE REVIEW

**Comment by donnadionne** [comment]
Using this code review to discuss the optimization solution.

1. I am now only calling ring hash creation only once, however a ring of size 100,000 it could still take as long as 4 seconds, which means the 1st RPC will deadline exceed with in the default 1 second timeout; this is noticiably much better than before where the first few RPC may fail.  However this does mean in our test we still need a slightly longer timeout.
2. Since picker has a ref to the parent (ringhash), I added the a vector of ring entries directly in ringhash, let me know if this is ok
3. I try to call subchannel()->CheckConnectivityState as little as possible, but in Pick() I may need to call it twice, let me know what you think
4. For some reason, I now have a new flake 
 E0603 08:40:53.462985791      21 client_channel.cc:3038]     assertion failed: connected_subchannel_ != nullptr
Which makes me think some lock may be missing or something like that.  Any suggestions?

Thanks for the review

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks like a good start!

Answering your questions here:

> I am now only calling ring hash creation only once, however a ring of size 100,000 it could still take as long as 4 seconds, which means the 1st RPC will deadline exceed with in the default 1 second timeout; this is noticiably much better than before where the first few RPC may fail.  However this does mean in our test we still need a slightly longer timeout.

When you say that constructing the ring takes 4 seconds, is that in msan or asan, or is that in an opt or dbg build?  If it happens only in the *san runs, maybe we can just special-case those builds.

I think it may also be worthwhile to look at how much time is being taken by each step of ring creation.  Maybe there's a way we can optimize it.

> Since picker has a ref to the parent (ringhash), I added the a vector of ring entries directly in ringhash, let me know if this is ok

This won't work.  See my comment in the code.

> I try to call subchannel()->CheckConnectivityState as little as possible, but in Pick() I may need to call it twice, let me know what you think

You're calling it once per subchannel that we're looking at.  That's fine.

> For some reason, I now have a new flake
> E0603 08:40:53.462985791      21 client_channel.cc:3038]     assertion failed: connected_subchannel_ != nullptr
> Which makes me think some lock may be missing or something like that.  Any suggestions?

Ugh... This may be a problem.  The channel is currently assuming that its view of the subchannel states is effectively synchronized from within the data plane mutex: at the moment at which the LB policy returns a new picker, we store refs to the ConnectedSubchannels for all READY subchannels in state guarded by the data plane mutex, and we store the new picker at the same time, so the two are expected to always be in sync, thus making it impossible for the picker to return a subchannel for which the channel doesn't have a ConnectedSubchannel.  But now that we are directly using the underlying state of the subchannel instead of the state seen by the LB policy, the two are getting out of sync.  So we've probably got a case where a subchannel has just become READY but the channel has not yet stored its ConnectedSubchannel in the stage guarded by the data plane mutex.

For now, try changing this line:

https://github.com/grpc/grpc/blob/57dd2eb02e916d05d09a3691a6d3b24db87e274e/src/core/ext/filters/client_channel/client_channel.cc#L3038

To this:

```
if (connected_subchannel_ == nullptr) {
  MaybeAddCallToLbQueuedCallsLocked();
  return false;
}
```

That will basically queue the call and try again when the picker gets updated, which should happen as soon as the LB policy sees the subchannel state update.  Let me know if that fixes the problem.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26420#-:-MbIIoK16L28MGZ3bXSl:b-u1uugv)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 205 at r1](https://reviewable.io/reviews/grpc/grpc/26420#-MbIEydSEg9VV0j-zmdF:-MbIEydT7kb73eo-UubE:b-r04wnj) ([raw file](https://github.com/grpc/grpc/blob/7010ff1ad024431380a7611fb3e4f3da93a04586/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L205)):*
> ```cpp
>   class Picker : public SubchannelPicker {
>    public:
>     Picker(RefCountedPtr<RingHash> parent,
> ```

This ctor should no longer be needed.  The code for constructing the ring should instead be moved to the ctor for the ring object.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 208 at r1](https://reviewable.io/reviews/grpc/grpc/26420#-MbIF-tR4_GFCwcDvmKw:-MbIF-tR4_GFCwcDvmKx:b-m8idom) ([raw file](https://github.com/grpc/grpc/blob/7010ff1ad024431380a7611fb3e4f3da93a04586/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L208)):*
> ```cpp
>            RingHashSubchannelList* subchannel_list);
> 
>     Picker(RefCountedPtr<RingHash> parent) : parent_(std::move(parent)){};
> ```

This needs to take a ref to the ring in addition to a ref to the LB policy.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 270 at r1](https://reviewable.io/reviews/grpc/grpc/26420#-MbIF3xq4ScYfbQDl8q0:-MbIF3xq4ScYfbQDl8q1:b8plaw6) ([raw file](https://github.com/grpc/grpc/blob/7010ff1ad024431380a7611fb3e4f3da93a04586/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L270)):*
> ```cpp
>     RefCountedPtr<SubchannelInterface> subchannel;
>   };
>   std::vector<RingEntry> ring_;
> ```

It's not okay to put this directly in the LB policy, because we may need more than one at a time.  If we get a resolver update and construct a new picker, the old picker will still need to keep using the old ring until we return the new picker to the channel and the channel swaps out the picker and deletes the old one.

What we need here is a separate ref-counted object for the ring.  Every picker instance will take ownership of a ref to a ring.  We need to hold a ref to the current ring here in the LB policy.  When a subchannel connectivity state update occurs, we will create a new picker by taking a new ref to the current ring from the LB policy, without actually constructing a new ring.  When we get an update from the resolver, then we will construct a new ring, save it in the LB policy, and then create a picker with a ref to that new ring.  The old ring won't actually be deleted until the picker is swapped out.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 332 at r1](https://reviewable.io/reviews/grpc/grpc/26420#-MbIHFeN0b7XqLeQOtTR:-MbIHFeN0b7XqLeQOtTS:b-axpd64) ([raw file](https://github.com/grpc/grpc/blob/7010ff1ad024431380a7611fb3e4f3da93a04586/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L332)):*
> ```cpp
>   const uint64_t ring_size = std::ceil(scale);
>   gpr_log(GPR_INFO, "donna create just once");
>   parent_->ring_.clear();
> ```

We can't clear the existing ring while it's still in use by the existing picker.

**Review by donnadionne — COMMENTED** [review]
I have modified the timeout to be in sync with the config we are running and ran all the problem tests in msan 1000X and no issues

I have made the suggested changes in client_channel.cc to retry instead of ASSERT, I need one more change for moving the clearing of the pending_update and everything seems to be working

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26420#-:-MbZmS2r4FEPmcyTjOTX:b-wxrfg9)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1659 at r2](https://reviewable.io/reviews/grpc/grpc/26420#-MbZmsPD3wPEfCOP2mMk:-MbZmsPD3wPEfCOP2mMl:b-qbe4oc) ([raw file](https://github.com/grpc/grpc/blob/f5eb0ce7858f5a6fde892c8638ff7458b28cb74a/src/core/ext/filters/client_channel/client_channel.cc#L1659)):*
> ```cpp
>     // Need to do this here because the next Picker may add to this update which
>     // we do not wish to clear.
>     pending_subchannel_updates_.clear();
> ```

have to move this into the mutex now, because PickSubchannelLocked now calls CheckConnectivityState and calls MaybeUpdateConnectedSubchannel which can add to pending_subchannel_updates_ and those should not be cleared
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 205 at r1](https://reviewable.io/reviews/grpc/grpc/26420#-MbIEydSEg9VV0j-zmdF:-MbZmKhEBD3ymGTy6s6h:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7010ff1ad024431380a7611fb3e4f3da93a04586/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L205)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This ctor should no longer be needed.  The code for constructing the ring should instead be moved to the ctor for the ring object.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 208 at r1](https://reviewable.io/reviews/grpc/grpc/26420#-MbIF-tR4_GFCwcDvmKw:-MbZmLG41wJJ5J0QR2QW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7010ff1ad024431380a7611fb3e4f3da93a04586/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L208)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This needs to take a ref to the ring in addition to a ref to the LB policy.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 270 at r1](https://reviewable.io/reviews/grpc/grpc/26420#-MbIF3xq4ScYfbQDl8q0:-MbZmMLt49QnbCL8McUG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7010ff1ad024431380a7611fb3e4f3da93a04586/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L270)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It's not okay to put this directly in the LB policy, because we may need more than one at a time.  If we get a resolver update and construct a new picker, the old picker will still need to keep using the old ring until we return the new picker to the channel and the channel swaps out the picker and deletes the old one.

What we need here is a separate ref-counted object for the ring.  Every picker instance will take ownership of a ref to a ring.  We need to hold a ref to the current ring here in the LB policy.  When a subchannel connectivity state update occurs, we will create a new picker by taking a new ref to the current ring from the LB policy, without actually constructing a new ring.  When we get an update from the resolver, then we will construct a new ring, save it in the LB policy, and then create a picker with a ref to that new ring.  The old ring won't actually be deleted until the picker is swapped out.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 332 at r1](https://reviewable.io/reviews/grpc/grpc/26420#-MbIHFeN0b7XqLeQOtTR:-MbZmMyB1fvI0rVSC0zQ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/7010ff1ad024431380a7611fb3e4f3da93a04586/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L332)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We can't clear the existing ring while it's still in use by the existing picker.
</blockquote></details>

Done.

**Review by donnadionne — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26420)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 727 at r3](https://reviewable.io/reviews/grpc/grpc/26420#-MbZosVUEoHBlGxZHheT:-MbZosVUEoHBlGxZHheU:b-68x4gu) ([raw file](https://github.com/grpc/grpc/blob/09243be9c7c05683685b493e17cee2c9abce04a4/src/core/ext/filters/client_channel/client_channel.cc#L727)):*
> ```cpp
>     if (disconnect_error != GRPC_ERROR_NONE) return;
>     // Not shutting down, so do the update.
>     if (connected_subchannel_ != connected_subchannel) {
> ```

I have a data race here:

line 727 is called by 
#1 grpc_core::ClientChannel::SubchannelWrapper::MaybeUpdateConnectedSubchannel(grpc_core::RefCountedPtr<grpc_core::ConnectedSubchannel>) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:727:31 (liblibgrpc_Uclient_Uchannel.so+0x153811)
#2 grpc_core::ClientChannel::SubchannelWrapper::CheckConnectivityState() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:500:5 (liblibgrpc_Uclient_Uchannel.so+0x170608)
    #3 grpc_core::(anonymous namespace)::RingHash::Picker::Pick(grpc_core::LoadBalancingPolicy::PickArgs) /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc:450:53 (liblibgrpc_Ulb_Upolicy_Uring_Uhash.so+0x2b146)

line 727 is called by
#2 grpc_core::ClientChannel::SubchannelWrapper::MaybeUpdateConnectedSubchannel(grpc_core::RefCountedPtr<grpc_core::ConnectedSubchannel>) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:728:29 (liblibgrpc_Uclient_Uchannel.so+0x15383e)
    #3 grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::ApplyUpdateInControlPlaneWorkSerializer() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:701:18 (liblibgrpc_Uclient_Uchannel.so+0x1533a2)
    #4 grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange()::'lambda'()::operator()() const /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:637:17 (liblibgrpc_Uclient_Uchannel.so+0x152be2)
    #5 std::_Function_handler<void (), grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange()::'lambda'()>::_M_invoke(std::_Any_data const&) /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:1871:2 (liblibgrpc_Uclient_Uchannel.so+0x15299a)
    #6 std::function<void ()>::operator()() const /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:2267:14 (xds_end2end_test+0x98a1e6)
    #7 grpc_core::WorkSerializer::WorkSerializerImpl::Run(std::function<void ()>, grpc_core::DebugLocation const&) /proc/self/cwd/src/core/lib/iomgr/work_serializer.cc:67:5 (liblibgrpc_Ubase_Uc.so+0x1c6c61)
    #8 grpc_core::WorkSerializer::Run(std::function<void ()>, grpc_core::DebugLocation const&) /proc/self/cwd/src/core/lib/iomgr/work_serializer.cc:152:10 (liblibgrpc_Ubase_Uc.so+0x1c731a)
    #9 grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:634:42 (liblibgrpc_Uclient_Uchannel.so+0x14ff6d)


This is flakily happening, any idea how to fix? Thanks

**Review by markdroth — CHANGES_REQUESTED** [review]
The client channel changes needed here look like they're going to be trickier than I thought.  I'll probably have to work on them separately.  But let's see if we can get this working with what I have so far.

If we get blocked on this, then we can set this aside for now and then come back to it later when I've got all of the client channel changes merged.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26420#-:-MbbcPvz62mdbziAJhIw:b-pb8ebc)* status: all files reviewed, 6 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/client_channel.cc, line 1659 at r2](https://reviewable.io/reviews/grpc/grpc/26420#-MbZmsPD3wPEfCOP2mMk:-MbauOKFAgprPRbRaodC:bol04rk) ([raw file](https://github.com/grpc/grpc/blob/f5eb0ce7858f5a6fde892c8638ff7458b28cb74a/src/core/ext/filters/client_channel/client_channel.cc#L1659)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

have to move this into the mutex now, because PickSubchannelLocked now calls CheckConnectivityState and calls MaybeUpdateConnectedSubchannel which can add to pending_subchannel_updates_ and those should not be cleared
</blockquote></details>

This is a symptom of the problem I mentioned above.  `CheckConnectivityState()` is intended to be called in the work serializer, not while holding the data plane mutex.  The two should be separate, so this isn't the right fix.  But #26428 eliminates this problem anyway.
___
*[src/core/ext/filters/client_channel/client_channel.cc, line 727 at r3](https://reviewable.io/reviews/grpc/grpc/26420#-MbZosVUEoHBlGxZHheT:-Mbat_xrBT1vA0fn4O_g:b-i8o6w5) ([raw file](https://github.com/grpc/grpc/blob/09243be9c7c05683685b493e17cee2c9abce04a4/src/core/ext/filters/client_channel/client_channel.cc#L727)):*
<details><summary><i>Previously, donnadionne wrote…</i></summary><blockquote>

I have a data race here:

line 727 is called by 
#1 grpc_core::ClientChannel::SubchannelWrapper::MaybeUpdateConnectedSubchannel(grpc_core::RefCountedPtr<grpc_core::ConnectedSubchannel>) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:727:31 (liblibgrpc_Uclient_Uchannel.so+0x153811)
#2 grpc_core::ClientChannel::SubchannelWrapper::CheckConnectivityState() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:500:5 (liblibgrpc_Uclient_Uchannel.so+0x170608)
    #3 grpc_core::(anonymous namespace)::RingHash::Picker::Pick(grpc_core::LoadBalancingPolicy::PickArgs) /proc/self/cwd/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc:450:53 (liblibgrpc_Ulb_Upolicy_Uring_Uhash.so+0x2b146)

line 727 is called by
#2 grpc_core::ClientChannel::SubchannelWrapper::MaybeUpdateConnectedSubchannel(grpc_core::RefCountedPtr<grpc_core::ConnectedSubchannel>) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:728:29 (liblibgrpc_Uclient_Uchannel.so+0x15383e)
    #3 grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::ApplyUpdateInControlPlaneWorkSerializer() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:701:18 (liblibgrpc_Uclient_Uchannel.so+0x1533a2)
    #4 grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange()::'lambda'()::operator()() const /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:637:17 (liblibgrpc_Uclient_Uchannel.so+0x152be2)
    #5 std::_Function_handler<void (), grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange()::'lambda'()>::_M_invoke(std::_Any_data const&) /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:1871:2 (liblibgrpc_Uclient_Uchannel.so+0x15299a)
    #6 std::function<void ()>::operator()() const /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:2267:14 (xds_end2end_test+0x98a1e6)
    #7 grpc_core::WorkSerializer::WorkSerializerImpl::Run(std::function<void ()>, grpc_core::DebugLocation const&) /proc/self/cwd/src/core/lib/iomgr/work_serializer.cc:67:5 (liblibgrpc_Ubase_Uc.so+0x1c6c61)
    #8 grpc_core::WorkSerializer::Run(std::function<void ()>, grpc_core::DebugLocation const&) /proc/self/cwd/src/core/lib/iomgr/work_serializer.cc:152:10 (liblibgrpc_Ubase_Uc.so+0x1c731a)
    #9 grpc_core::ClientChannel::SubchannelWrapper::WatcherWrapper::OnConnectivityStateChange() /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:634:42 (liblibgrpc_Uclient_Uchannel.so+0x14ff6d)


This is flakily happening, any idea how to fix? Thanks



</blockquote></details>

Ugh.  I forgot that calling CheckConnectivityState() was expected to be called only from inside the WorkSerializer, which it needs to (a) update the cached ref to the connected subchannel and (b) access the health check service name.

Instead of the changes you've made here to client_channel.cc, try patching in #26428 and see if that fixes the problem.  That PR is not quite ready to merge (there's a test failure that I'm getting Alex's help to resolve), and it doesn't solve the health check service name problem (although that won't be an issue for the ring_hash tests, and I am working on a fix for that in #26441), but it may be good enough to solve the specific problem you're seeing here.  Please give it a try and see if it works.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 213 at r3](https://reviewable.io/reviews/grpc/grpc/26420#-MbapOAI5GEqxrPmMPmi:-MbapOAI5GEqxrPmMPmj:bzg54gt) ([raw file](https://github.com/grpc/grpc/blob/09243be9c7c05683685b493e17cee2c9abce04a4/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L213)):*
> ```cpp
>     };
> 
>     const std::vector<RingEntry>& GetRing() { return ring_; }
> ```

This should be called `ring()`, since it's a simple accessor method.

Also, the method should be `const`.
___
*[src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc, line 216 at r3](https://reviewable.io/reviews/grpc/grpc/26420#-MbapWqvAH2xWWgF6zVI:-MbapWqvAH2xWWgF6zVJ:b-8ddl7k) ([raw file](https://github.com/grpc/grpc/blob/09243be9c7c05683685b493e17cee2c9abce04a4/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L216)):*
> ```cpp
> 
>    private:
>     RefCountedPtr<RingHash> parent_;
> ```

This data member is not necessary.  The ring itself has no need to hold a ref to the LB policy; the picker does that.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 157 at r3](https://reviewable.io/reviews/grpc/grpc/26420#-Mbaqt4_6EpU6rfCcC5c:-Mbaqt4_6EpU6rfCcC5d:b-kzhvtj) ([raw file](https://github.com/grpc/grpc/blob/09243be9c7c05683685b493e17cee2c9abce04a4/test/cpp/end2end/xds_end2end_test.cc#L157)):*
> ```cpp
> constexpr int kDefaultLocalityWeight = 3;
> constexpr int kDefaultLocalityPriority = 0;
> constexpr int kDefaultRpcTimeoutMs = 1000;
> ```

I don't think this is needed.  As per my comment below, this should be used only in the `RpcOptions` struct, so there's no need to define a constant for it.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 7230 at r3](https://reviewable.io/reviews/grpc/grpc/26420#-MbaqOsQ2_hBOSJI3S7j:-MbaqOsQ2_hBOSJI3S7k:b-yasnqb) ([raw file](https://github.com/grpc/grpc/blob/09243be9c7c05683685b493e17cee2c9abce04a4/test/cpp/end2end/xds_end2end_test.cc#L7230)):*
> ```cpp
>   const double kErrorTolerance = 0.05;
>   const uint32_t kRpcTimeoutMs =
>       kDefaultRpcTimeoutMs * grpc_test_slowdown_factor();
> ```

Multiplying by the test slowdown factor isn't necessary here, because that already happens in `grpc_timeout_milliseconds_to_deadline()`, which is called from `RpcOptions::SetupRpc()`.  I think you can just use the default timeout here without overriding it in each test.

Same thing for all of the tests modified here.

**Comment by markdroth** [comment]
I've finally gotten #26428 merged, so we should be able to move forward with this now.

**Comment by markdroth** [comment]
This is now superceded by #28338.

**Pull request closed without merging**
