### PR TITLE
Test ObjC Kokoro failure with partial revert - 1

### PR DESCRIPTION
**Pull request by muxi**
**DO NOT MERGE**
No review required. This PR is only intended for troubleshooting ObjC internal CI failure.

### CODE REVIEW

**Comment by muxi** [comment]
No review required. This PR is only intended for troubleshooting ObjC internal CI failure.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.1%    +503 [None]                                                             +11.3Ki  +0.2%
      +0.1%    +471 [Unmapped]                                                         +11.3Ki  +0.2%
      +2.6%     +31 [None]                                                                   0  [ = ]
      [NEW]      +1 grpc_trace_alarm_refcount                                                0  [ = ]
  [NEW] +1.04Ki src/core/lib/surface/alarm.cc                                      +1.04Ki  [NEW]
      [NEW]    +346 grpc_alarm_set                                                        +346  [NEW]
      [NEW]    +242 alarm_unref(grpc_alarm*) [clone .part.3]                              +242  [NEW]
      [NEW]    +209 grpc_alarm_cancel                                                     +209  [NEW]
      [NEW]     +81 grpc_alarm_create                                                      +81  [NEW]
      [NEW]     +62 [Unmapped]                                                             +62  [NEW]
      [NEW]     +59 alarm_cb                                                               +59  [NEW]
      [NEW]     +41 grpc_alarm_destroy                                                     +41  [NEW]
      [NEW]     +25 alarm_end_completion                                                   +25  [NEW]

 -------------- SHRINKING                                                          --------------
 -21.0%    -320 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    -320 -21.0%
      [DEL]    -150 grpc_fake_resolver_response_generator_set_response_upon_error         -150  [DEL]
      [DEL]    -117 set_response_closure_locked                                           -117  [DEL]
     -28.9%     -56 grpc_fake_resolver_response_generator_set_response                     -56 -28.9%
     -47.4%     -46 fake_resolver_channel_saw_error_locked                                 -46 -47.4%
     -12.8%     -32 [Unmapped]                                                             -32 -12.8%
     -18.4%      -9 fake_resolver_destroy                                                   -9 -18.4%

  +0.1% +1.22Ki TOTAL                                                              +12.1Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +1.8%    +112 src/cpp/common/channel_arguments.cc                                                     +112  +1.8%
      [NEW]     +56 grpc_core::ExecCtx::~ExecCtx                                                             +56  [NEW]
      [NEW]     +53 grpc_core::ExecCtx::~ExecCtx                                                             +53  [NEW]
      [NEW]      +3 grpc_core::ExecCtx::CheckReadyToFinish                                                    +3  [NEW]

 -------------- SHRINKING                                                                            --------------
  -2.0% -4.48Ki [None]                                                                               -63.6Ki  -1.3%
      -2.1% -4.31Ki [Unmapped]                                                                           -63.4Ki  -1.3%
      [DEL]     -40 typeinfo for grpc::Alarm                                                                 -40  [DEL]
      [DEL]     -40 vtable for grpc::internal::AlarmImpl                                                     -40  [DEL]
      [DEL]     -32 vtable for grpc::Alarm                                                                   -32  [DEL]
      [DEL]     -27 typeinfo name for grpc::internal::AlarmImpl                                              -27  [DEL]
      [DEL]     -24 typeinfo for grpc::internal::AlarmImpl                                                   -24  [DEL]
      [DEL]     -14 typeinfo name for grpc::Alarm                                                            -14  [DEL]
     -12.5%      -8 grpc::internal::g_core_codegen                                                            -8 -12.5%
     -12.5%      -8 grpc::internal::g_gli                                                                     -8 -12.5%
      -3.4%      -1 std::__ioinit                                                                              0  [ = ]
  [DEL] -2.89Ki src/cpp/common/alarm.cc                                                              -2.89Ki  [DEL]
      [DEL]    -671 grpc::Alarm::~Alarm                                                                     -671  [DEL]
      [DEL]    -422 grpc::Alarm::SetInternal                                                                -422  [DEL]
      [DEL]    -361 grpc::Alarm::Alarm                                                                      -361  [DEL]
      [DEL]    -335 grpc::internal::AlarmImpl::FinalizeResult                                               -335  [DEL]
      [DEL]    -286 grpc::Alarm::Cancel                                                                     -286  [DEL]
      [DEL]    -257 grpc::internal::AlarmImpl::~AlarmImpl                                                   -257  [DEL]
      [DEL]    -248 grpc::internal::AlarmImpl::~AlarmImpl                                                   -248  [DEL]
      [DEL]     -97 _GLOBAL__sub_I_alarm.cc                                                                  -97  [DEL]
      [DEL]     -59 grpc::internal::AlarmImpl::AlarmImpl()::{lambda(void*, grpc_error*)#1}::operator()(v     -59  [DEL]
      [DEL]     -59 grpc::internal::AlarmImpl::AlarmImpl()::{lambda(void*, grpc_error*)#1}::_FUN             -59  [DEL]
      [DEL]     -56 grpc_core::ExecCtx::~ExecCtx                                                             -56  [DEL]
      [DEL]     -53 grpc_core::ExecCtx::~ExecCtx                                                             -53  [DEL]
      [DEL]     -32 [Unmapped]                                                                               -32  [DEL]
      [DEL]     -18 grpc::Alarm::~Alarm                                                                      -18  [DEL]
      [DEL]      -3 grpc_core::ExecCtx::CheckReadyToFinish                                                    -3  [DEL]
      [DEL]      -2 grpc::internal::AlarmImpl::AlarmImpl()::{lambda(void*, grpc_error*)#1}::operator()(v      -2  [DEL]
      [DEL]      -2 grpc::internal::AlarmImpl::AlarmImpl()::{lambda(void*, grpc_error*)#1}::operator()(v      -2  [DEL]

  -2.1% -7.26Ki TOTAL                                                                                -66.4Ki  -1.3%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
