### PR TITLE
Add v1.38.0 release of grpc-go to interop matrix

### PR DESCRIPTION
**Pull request by easwars**

### CODE REVIEW

**Comment by easwars** [comment]
@jtattermusch

**Comment by jtattermusch** [comment]
FYI We recently added a note in the docs that asks you to run the ad-hoc run of interop matrix tests: https://github.com/grpc/grpc/commit/912515384e069c8e99ebe7be5eda3105b080bf11#diff-e0017bd09f3b6b6a979072f4da276e4d58bbb81d62514d96329207e48fd2001b

I just started them.
LGTM once they are green.

**Review by jtattermusch — APPROVED** [review]

**Comment by easwars** [comment]
> FYI We recently added a note in the docs that asks you to run the ad-hoc run of interop matrix tests: [9125153#diff-e0017bd09f3b6b6a979072f4da276e4d58bbb81d62514d96329207e48fd2001b](https://github.com/grpc/grpc/commit/912515384e069c8e99ebe7be5eda3105b080bf11#diff-e0017bd09f3b6b6a979072f4da276e4d58bbb81d62514d96329207e48fd2001b)
> 
> I just started them.
> LGTM once they are green.

Thanks Jan.
I will update our internal release instructions to add this step.

**Comment by jtattermusch** [comment]
adhoc interop matrix tests run is green, merging.

**Pull request merged**
