### PR TITLE
Explicitly delete copy constructor of ::grpc::Service class.

### PR DESCRIPTION
**Pull request by bassofil**
Solve #15653

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @bassofil isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by bassofil** [comment]
I signed it

**Comment by fedemengo** [comment]
Will this PR ever be merged?

**Comment by vjpai** [comment]
Since the purpose is DLLs, I will reassign the review more appropriately.

**Comment by fedemengo** [comment]
> 
> 
> Since the purpose is DLLs, I will reassign the review more appropriately.

Just FYI this solved a compilation problem for me on Linux

**Comment by fraeu** [comment]
Hi @nicolasnoble 
Any progress on this?

**Pull request closed without merging**
