### PR TITLE
interop_matrix: Bump 9 Java versions

### PR DESCRIPTION
**Pull request by ejona86**
Java did 10 releases in a batch; update them almost all together. One version has already been handled in 63104ed.

CC @sergiitk, @temawi, @YifeiZhuang

### CODE REVIEW

**Review by sergiitk — APPROVED** [review]
LGTM for my releases.

**Comment by ejona86** [comment]
Adhoc run: https://fusion2.corp.google.com/invocations/8f9fb06d-b55c-4fc6-8b51-248c3f530ecf/targets

**Review by temawi — APPROVED** [review]
LGTM, but check out the C++ and ObjC failures.

**Comment by ejona86** [comment]
@temawi, the changes here can't impact the iOS tests.

**Pull request merged**
