### PR TITLE
Revert "Revert "Adding xxhash as a subtree""

### PR DESCRIPTION
**Pull request by donnadionne**
Adding xxhash as a subtree

Attempting to submit the same code after taking care of import issues.

### CODE REVIEW

**Comment by jtattermusch** [comment]
there's a bunch of failures and you'll also need a passing adhoc artifacts - packages - distribtest (distribtests were broken the last time) run before this can go in (see bullet point 2 here: https://github.com/grpc/grpc/tree/master/third_party#checklist-for-adding-a-new-third-party-dependency)

**Comment by donnadionne** [comment]
> there's a bunch of failures and you'll also need a passing adhoc artifacts - packages - distribtest (distribtests were broken the last time) run before this can go in (see bullet point 2 here: https://github.com/grpc/grpc/tree/master/third_party#checklist-for-adding-a-new-third-party-dependency)

started: https://fusion2.corp.google.com/invocations/8e76a837-d153-4677-987e-2a373e9df5ea/targets

**Comment by jtattermusch** [comment]
> > there's a bunch of failures and you'll also need a passing adhoc artifacts - packages - distribtest (distribtests were broken the last time) run before this can go in (see bullet point 2 here: https://github.com/grpc/grpc/tree/master/third_party#checklist-for-adding-a-new-third-party-dependency)
> 
> started: https://fusion2.corp.google.com/invocations/8e76a837-d153-4677-987e-2a373e9df5ea/targets

That build seemed stuck for some reason, so I started another one https://sponge2.corp.google.com/e5a04e01-2ed9-4776-976f-528021b103ae

**Comment by donnadionne** [comment]
Tools failures from previous ad-hoc runs; triggered another one after synching:
c7125420-2691-483b-97fe-1586d3578a4a

**Comment by donnadionne** [comment]
Known issues: #25660 (interop test failures)

**Comment by donnadionne** [comment]
kokoro failure: due to unable to access the commitsha that is not yet submitted

**Comment by donnadionne** [comment]
All Required tests pass; failed test have explainations.

This is really the same change as last week; just now it's ready to be imported.  

PTAL thank you!

**Comment by jtattermusch** [comment]
> https://fusion2.corp.google.com/invocations/0046ece3-ddd0-4e84-ba7a-93836099cbb2/targets

Following through the chained jobs, the python-dev  distribtests are failing:
https://fusion2.corp.google.com/invocations/8378f432-3d21-4b82-889c-fd7cae48eefa/targets/github%2Fgrpc;config=default/tests

**Comment by jtattermusch** [comment]
FTR, as discussed I think the issue with python-dev distribtests is that the python "sdist" archive is missing the newly added xxhash.h header:

https://pantheon.corp.google.com/storage/browser/_details/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/linux/grpc_build_artifacts/16172/20210309-131926/github/grpc/artifacts/python_manylinux2010_x86_cp38-cp38/grpcio-1.37.0.dev0.tar.gz (and indeed, if you open the archive you'll see that third_party/xxhash/xxhash.h is not there).

**Comment by donnadionne** [comment]
Updated PYTHON-MANIFEST.in which fixed the grpc/core/experimental/grpc_distribtests_multiplatform: grpc/core/master/linux/grpc_distribtests:
https://source.cloud.google.com/results/invocations/dcd3d928-cf65-4fed-9cf0-d075eacaaed8/targets

**Comment by donnadionne** [comment]
Known issues: #25660 (interop test failures)

Ruby Failue is just a timeout, and this test has passed in previous runs before the 1 line change for Python.

**Review by jtattermusch — APPROVED** [review]
LGTM (assuming you've tried the cherrypick into google3 and it worked fine).

**Pull request merged**
