### PR TITLE
Add test for CPU functions. 

### LINKED ISSUE #3534: gpr_cpu_current_cpu is untested

### PR DESCRIPTION
**Pull request by a-veitch**
Fixes #3534

### CODE REVIEW

**Comment by a-veitch** [comment]
Works fine on my mac and Linux workstation. Linux sees 100% of cores "used", Mac-OS is more variable  (between 4-8 on my laptop). In any case, I think this provides a basic sanity test.

**Comment by a-veitch** [comment]
Oh, should I 'git add vsprojects/vcxproj/test/gpr_cpu_test/'?

**Comment by ctiller** [comment]
Yeah you should add the vsprojects.

**Comment by a-veitch** [comment]
Added vsprojects, merged to head. Waiting for tests to run...

**Comment by a-veitch** [comment]
AFAICT, everything about this test is green. PTAL.

**Pull request merged**
