### PR TITLE
Using protobuf GA branch and tag.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by murgatroid99** [comment]
It looks like something in the codegen changed, because the `check_generated_pb_files` sanity test failed.

**Comment by nicolasnoble** [comment]
Also, objective C is sad, because we're missing the packages being published.

**Comment by nicolasnoble** [comment]
@makdharma and @jcanizales, what's the status of the newer protobuf packages ? Do you know ?

**Comment by jcanizales** [comment]
https://github.com/grpc/grpc/pull/7475 :)

**Pull request closed without merging**
