### PR TITLE
Add BUILD file for stats_test.cc

### LINKED ISSUE #16849: missing bazel BUILD file: test/core/debug/stats_test.cc
https://github.com/grpc/grpc/blob/8ae3285323e126938bf46401ad09b9a17d3f1852/build.yaml#L5433

no BUILD file here:
https://github.com/grpc/grpc/tree/master/test/core/debug

### PR DESCRIPTION
**Pull request by yashykt**
Add BUILD file for stats_test.cc

Fixes #16849

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,616      Total (=)      2,020,616

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,180,935      Total (<)     11,180,941

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
All green! Thanks for reviewing!

**Pull request merged**
