### PR TITLE
cmake: fix cares configuration

### PR DESCRIPTION
**Pull request by BusyJay**
`set` will be ignored if not cache. And if shared library is not disable, static library target will be `c-ares_static` instead of `c-ares`.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
CMakeLists.txt is actually generated from templates/CMakeLists.txt.template - you need to change the template and then regenerate otherwise the sanity tests will fails.

Also, on what platform are you seeing a problem - our continuous test actually indicate that things build just fine (linux and windows).

**Comment by BusyJay** [comment]
> ...you need to change the template and then regenerate...

Done.

> ..on what platform are you seeing a problem...

I build it on Fedora release 25 (Twenty Five) without c-ares package installed.

**Comment by BusyJay** [comment]
I might have mislead the problem. We maintain [a rust grpc library](https://github.com/pingcap/grpc-rs) that base on grpc c core, which will link to c-ares statically and explicitly. After switching the grpc submodule to master, it fails to compile because c-ares static library is missing.

**Comment by jtattermusch** [comment]
jenkins: test this please

**Pull request merged**
