### PR TITLE
[Python][macOS] explicitly differentiate arch while compiling wheels

### PR DESCRIPTION
**Pull request by lidizheng**
Fixes https://github.com/grpc/grpc/issues/28387

This is an issue for 3.10 users.

### CODE REVIEW

**Comment by lidizheng** [comment]
To be sure, ad-hoc [prod:grpc/core/experimental/linux/grpc_interop_matrix_adhoc](https://fusion2.corp.google.com/invocations/80b75e16-30a1-4822-83c7-e39cd2083cf8) (still running).

**Comment by lidizheng** [comment]
Last run, CI flake killed the job... let's run [prod:grpc/core/master/linux/grpc_build_artifacts](https://fusion2.corp.google.com/invocations/c8dc812a-036f-4454-a84d-9bff35327436/targets) this time.

**Review by gnossen — APPROVED** [review]

**Comment by lidizheng** [comment]
I triggered the wrong artifact build job last time 😮‍💨 . The "linux" build is not an umbrella for all platforms, just Linux. New build: [prod:grpc/core/master/macos/grpc_build_artifacts](https://fusion2.corp.google.com/invocations/9fb1cbde-c978-43a4-82a5-60fa95c5558f/targets)

**Comment by lidizheng** [comment]
Nope, this PR is not working.
```
[15:35:02] Copied /tmp/workspace/workspace/grpc/core/master/macos/grpc_build_artifacts/artifacts/github/grpc/artifacts/python_macos_x64_python3.10/grpcio-1.45.0.dev0-cp310-cp310-macosx_10_10_universal2.whl to /placer/prod/scratch/home/kokoro-dedicated/build_artifacts/prod/grpc/core/master/macos/grpc_build_artifacts/19218/20220204-135200/github/grpc/artifacts/python_macos_x64_python3.10/grpcio-1.45.0.dev0-cp310-cp310-macosx_10_10_universal2.whl
...
grpcio-1.45.0.dev0-cp310-cp310-macosx_10_10_universal2.whl
```

**Pull request closed without merging**
