### PR TITLE
Backport CoreCLR support to v1.0.x

### PR DESCRIPTION
**Pull request by jtattermusch**
Doesn't add any new APIs, only adds supported platforms, therefore safe to add to v1.0.x.

This backports pull requests #7986, #8039, #8047, #8048, #8075, #8076.

First commit is just a run of `tools/buildgen/generate_projects.sh` to fix sanity tests.

### CODE REVIEW

**Comment by jtattermusch** [comment]
FYI @nicolasnoble

**Comment by apolcyn** [comment]
the c# tests here seem fine. 

I believe the python timeout failure here is a flake, cc @kpayson64

**Comment by jtattermusch** [comment]
@nicolasnoble  all required statuses are passing but the "merge pull request" button is still disabled.

**Comment by jtattermusch** [comment]
Tests seem green, merging.

**Pull request merged**
