### PR TITLE
[bazel] Auto-generate .pyi files in py_proto_library rule

### PR DESCRIPTION
**Pull request by ferstlf**
With some delay, this is a PR for https://github.com/grpc/grpc/issues/32564 (and previously https://github.com/grpc/grpc/pull/31791). 

I looked into adding a regular `py_test` for this change [as suggested](https://github.com/grpc/grpc/pull/31791#issuecomment-1423245116) but I am not aware of any effect that the presence of a .pyi stub file would have at runtime and where some sort of type-checking in a .py script would be affected. Stub files are only for use by type checkers & IDE's. I mean, something like this would work:

```
import helloworld_pb2
py_file = helloworld_pb2.__file__ 
pyi_file = py_file + 'i’
self.assertTrue(os.path.exists(pyi_file))
```

But that seems really hacky to me. Instead I created a simple rule test for `py_proto_library` with Bazel Skylib which tests the declared outputs for an example `py_proto_library`  target. Indirectly, this also tests that the declared output files are actually generated. Please let me know if this is sufficient.

### CODE REVIEW

**Comment by ferstlf** [comment]
Friendly bump!

**Comment by gnossen** [comment]
Unfortunately, it looks like adding a dependency on Bazel Skylib introduces a thorny issue:

```
(venv) rbellevi@rbellevi:~/dev/grpc/test/distrib/bazel/python$ tools/bazel test -c dbg //:py_proto_library_provider_contents_test
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 6.1.2 will be used instead of system-wide bazel installation.
ERROR: /usr/local/google/home/rbellevi/.cache/bazel/_bazel_rbellevi/6b245ae2ccca35fac920f4dfd855cf78/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /usr/local/google/home/rbellevi/.cache/bazel/_bazel_rbellevi/6b245ae2ccca35fac920f4dfd855cf78/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed
ERROR: /usr/local/google/home/rbellevi/dev/grpc/test/distrib/bazel/python/BUILD:160:24: While resolving toolchains for target //:py_proto_library_provider_contents_test: invalid registered toolchain '@bazel_skylib//toolchains/unittest:cmd_toolchain': 
ERROR: Analysis of target '//:py_proto_library_provider_contents_test' failed; build aborted: 
INFO: Elapsed time: 0.355s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 2 targets configured)
ERROR: Couldn't start the build. Unable to run tests
```

[This only happens on Bazel 6+](https://github.com/bazelbuild/bazel/issues/8622), but we need to run these tests against all supported Bazel versions, including 6+. We don't use platform constraints ourself, but several of our dependencies do:

```
(venv) rbellevi@rbellevi:~/dev/grpc$ grep -rn "bazel_tools//platforms"
third_party/bloaty/third_party/protobuf/third_party/googletest/BUILD.bazel:41:    constraint_values = ["@bazel_tools//platforms:windows"],
third_party/bloaty/third_party/googletest/BUILD.bazel:41:    constraint_values = ["@bazel_tools//platforms:windows"],
third_party/bloaty/third_party/abseil-cpp/absl/BUILD.bazel:47:        "@bazel_tools//platforms:osx",
third_party/bloaty/third_party/abseil-cpp/absl/BUILD.bazel:54:        "@bazel_tools//platforms:ios",
third_party/bloaty/third_party/abseil-cpp/absl/time/internal/cctz/BUILD.bazel:29:        "@bazel_tools//platforms:osx",
third_party/bloaty/third_party/abseil-cpp/absl/time/internal/cctz/BUILD.bazel:36:        "@bazel_tools//platforms:ios",
```

So fixing _that_ issue would become a big yak shaving exercise.

Instead of using Bazel Skylib, could we do something more end-to-end? How are these `.pyi` files going to be consumed by you under Bazel builds? Presumably you also have a type checker like `pytype` or `mypy` integrated with your Bazel build? Could we just have a smoke check that a simple proto passes type check with this change?

**Comment by ferstlf** [comment]
Thanks for the reply, I can reproduce this problem. I was using Bazel 5.4.0 when creating this PR.

Currently we don't consume the .pyi files with Bazel (or a type checker integrated with Bazel) but with Pylance/VS Code to get import resolution and auto-completion. There is a bit more to our setup, but in a nut-shell we add Bazel's output paths such as `bazel-bin/external/com_github_grpc_grpc/src/python/grpcio` to the analysis paths for Pylance and then, of course, Pylance understands seeing `foo.py` next to `foo.pyi`.

I haven't worked with type checkers in Bazel but I could give it a shot. But before I do: would it be an option to simply update to a newer version of Skylib? It seems like Skylib migrated their use of platform constraints in [this commit](https://github.com/bazelbuild/bazel-skylib/commit/327d61b5eaa15c11a868a1f7f3f97cdf07d31c58). All we'd need is Skylib version 1.0.3 instead of 1.0.2 in [grpc_deps()](https://github.com/grpc/grpc/blob/a90239f381e9c95b51aa8b33728923f71b971120/bazel/grpc_deps.bzl#L361-L369). I tentatively updated this PR with the newer skylib version - just so you can try it out (if bumping the version is in fact an option). Tested successfully with Bazel 5.4.0 and 6.1.2.

**Comment by gnossen** [comment]
> would it be an option to simply update to a newer version of Skylib

Sure! As long as it works with all of our versions of Bazel. I just triggered CI so we can find out.

**Comment by ferstlf** [comment]
AFAICT the newer Skylib version seems to have solved the issue?!

**Review by gnossen — APPROVED** [review]

**Pull request merged**
