### PR TITLE
Add route_guide_db.json to Ruby examples

### PR DESCRIPTION
**Pull request by aquinofb**
Just add the file route_guide_db.json to `exampes/ruby/route_guide/`

### CODE REVIEW

**Comment by aquinofb** [comment]
I signed it!

**Comment by apolcyn** [comment]
thanks, I think this is under the python directory though, not a big deal but I'd like to refer to that one just since the existing example guides refer to that one

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @aquinofb isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jtattermusch** [comment]
@apolcyn  please resolve or close.

**Pull request closed without merging**
