### PR TITLE
remove all unused-parameter warnings in C++

### PR DESCRIPTION
**Pull request by chrisse74**
As described in #16542
"C++ code generated for streaming methods contains functions with unused arguments that trip up compilation with -Wunused-parameter (part of -Wextra)."

According to the Google C++ Style Guide ( section: Function_Declarations_and_Definitions ) this should be adressed by commenting out the unused parameter names.

This pull request handles all unused-parameter warnings, that I could find.

@sheenaqotj @hcaseyal : Sorry for the mess in PR #19681 .

### CODE REVIEW

**Comment by chrisse74** [comment]
@hcaseyal i hopefully found all test errors:
- tools/distrib/clang_format_code.sh has been executed
- test/cpp/codegen/compiler_test_golden is now recreated

**Comment by chrisse74** [comment]
@sheenaqotj Removed whitespace between 'Service *' as suggested.

**Comment by chrisse74** [comment]
@hcaseyal @sheenaqotj Thanks for the approves. What do i have to do, to get this merged? Is there a merge-strategy i have to follow? :)

**Comment by hcaseyal** [comment]
The CLA bot is stuck so I need to close and re-open this PR

**Comment by hcaseyal** [comment]
MacOS node tests known failure: https://github.com/grpc/grpc/issues/19422

**Comment by hcaseyal** [comment]
@chrisse74 At this point, I am just checking the output of failed tests. If all is well, I will merge this; else, I will ping you

**Pull request merged**
