### PR TITLE
replace uses of iteritems with six.iteritems

### PR DESCRIPTION
**Pull request by leifurhauks**
re #5648 , #282 

replace `dict_instance.iteritems()` with `six.iteritems(dict_instance)` to be python 2/3 compatible.

### CODE REVIEW

**Comment by leifurhauks** [comment]
I just rebased to resolve a conflict, but it doesn't seem to be queued on Jenkins

**Comment by nathanielmanistaatgoogle** [comment]
This is OK to test.

**Comment by jtattermusch** [comment]
tests havent finished, removing the label.

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: LGTM

**Pull request merged**
