### PR TITLE
Add a test for grpc/grpc#6522

### PR DESCRIPTION
**Pull request by soltanmm**
Related to #6547. Turnaround on #6522.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum; kicked off another test execution.

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_pull_requests/9723/config=dbg,language=python,platform=linux/testReport/(root)/tests/py_test__crust_over_core_over_links_face_interface_test_GenericInvokerBlockingInvocationInlineServiceTest/ has timed out.

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: good thing thing that test is not long for this world. We can either ignore it because it's not a possible effect of this change, ignore it because it no longer tests production code, or wait for the re-run to pass?

**Comment by jtattermusch** [comment]
Python tests look fine now, merging. (and yeah, I'm just trying to do the right thing and make sure we are not introducing flakes/test breakages).

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: I appreciate your diligence. 👍

**Pull request merged**
