### PR TITLE
Updating the server1 cert so that it can be used with Go.

### LINKED ISSUE #4086: Update Certificates for testing
The Test CA for interop testing here: https://github.com/grpc/grpc/blob/master/src/core/tsi/test_creds/ca.pem has  an ASN.1 representation for its Subject field that encodes slightly differently for the Server certificates used in grpc core as well as in the Grpc Go language. (e.g. https://github.com/grpc/grpc-go/blob/master/interop/server/testdata/server1.pem )  This is okay per the ASN.1 normalization rules, but currently the Go TLS package uses exact encoding match to verify the certificate authority chain.  

It would likely be easier to either regenerate the server certs with the test CA, or generate a test CA that would match the certs to allow for interop testing.   OpenSSL does not exhibit this issue, which is why it hasn't been discovered up until now.

### PR DESCRIPTION
**Pull request by jboeuf**
The encoding of the issuer field in this cert is now a PRINTABLESTRING
as opposed to UTF8STRING in the previous server1.pem which was causing
the Go issue.

Fixes #4086.

### CODE REVIEW

**Comment by jboeuf** [comment]
@carl-mastrangelo The go interop tests are failing. Is that expected?

**Comment by jtattermusch** [comment]
The change itself looks alright, but we need to resolve the interop test failure before merging this.

**Comment by carl-mastrangelo** [comment]
@jboeuf You probably also need to update the grpc-go certs to before this will pass.  (though, I don't have anything against submitting it).

They should be https://github.com/grpc/grpc-go/tree/master/interop/server/testdata and https://github.com/grpc/grpc-go/tree/master/interop/client/testdata

**Comment by jtattermusch** [comment]
I am definitely against committing anything that will introduce new breakages. If you update the go cert first, will we prevent breaking the interop tests by this PR? If so, we should do that.

Please note that it is possible to change both changes (to this repo and to the go repo) at the same time by running the interop tests locally.

**Comment by carl-mastrangelo** [comment]
@jtattermusch the two certs between repos are mutually incompatible (this is why grpc-go uses its own root CA).  Making the change in both repos and running the test seems fine.  That said, it still seems like there will be a brief window O(~seconds) where the test would fail if rerun from a new PR.

**Comment by jtattermusch** [comment]
that sounds alright. Just wanted to point out we need to coordinate both
pull requests appropriately to make the transition as short as possible

**Pull request merged**
