### PR TITLE
Build native MacOS arm64 artifacts (universal2)

### LINKED ISSUE #29262: A solution to build Apple Silicon (M1) Python binary wheels
Currently, the `grpcio` Python package does not distribute functioning binary wheels for the Apple Silicon (M1 processor family) architecture.

This has been a major blocker for me and other colleagues working with Google Cloud, as `grpcio` is a fundamental building block of many Google Cloud client libraries, and compiling grpcio from source on Macs is far from straightforward, as the comments on [this issue](https://github.com/grpc/grpc/issues/25082) prove.

Besides, a broken Mac "universal" wheel [was uploaded](https://github.com/grpc/grpc/issues/28387) on PyPI, preventing Apple Silicon users on Python 3.10 to even install `grpcio` from source without passing specific configuration options to `pip`. Those using `poetry` are out of luck, as there is no way to force a source installation.

I understand there are significant technical difficulties in providing a working binary wheel for Apple Silicon.
Here is **a simple solution to get working binary wheels for Apple Silicon, on Python 3.8, 3.9, 3.10**.

The idea is to use a commercially available [CircleCI Mac machine executor](https://circleci.com/docs/2.0/executor-types/#using-macos) (on Intel) and cross-compile `grpcio` for Apple Silicon using the [cibuildwheel](https://github.com/pypa/cibuildwheel) tool.
As you see, there's no need for specialised Apple Silicon machines, which most CI providers don't offer.

Here is the stripped-down version of the CircleCI pipeline that we are using internally.
It builds the wheel in parallel for Python 3.8, 3.9, and 3.10. The resulting `.whl` files are saved into the CircleCI artifacts of the job, but they can also easily be uploaded to PyPI using a tool such as `twine`.

I'm sharing this in the sincere hope you can provide official working Apple Silicon wheels soon. ☮️ 

```yaml
version: 2.1

jobs:
  build-grpcio-apple-silicon-wheel:
    working_directory: ~/grpcio-wheels
    macos:
      xcode: << parameters.xcode_version >>

    parameters:
      python_build_version:
        type: string
        description: The Python version to build the wheel for
      xcode_version:
        type: string
        description: The Xcode version for the CircleCI executor
        default: 13.3.0

    environment:
      CIBW_ARCHS_MACOS: "arm64"
      CIBW_TEST_SKIP: "*_arm64"
      CIBW_BUILD: "<< parameters.python_build_version >>-macosx_arm64"
      CIBW_BUILD_FRONTEND: pip
      CIBW_ENVIRONMENT_MACOS: "GRPC_PYTHON_BUILD_WITH_CYTHON=1"
      CIBW_BEFORE_BUILD: "pip install -r requirements.txt"
    steps:
      - run:
          name: Install cibuildwheel
          command: |
              python3 -m venv venv
              source venv/bin/activate
              python -m pip install -U pip wheel cibuildwheel==2.3.1
      - run:
          name: Build grpcio
          command: |
            source venv/bin/activate
            pip download --no-binary grpcio grpcio
            tar xf *.tar.gz
            cd grpcio-*/
            
            cibuildwheel --output-dir ../wheelhouse
      - store_artifacts:
          path: wheelhouse/

workflows:
  version: 2
  build:
    jobs:
      - build-grpcio-apple-silicon-wheel:
          matrix:
            parameters:
              python_build_version: [ "cp38", "cp39", "cp310" ]

```

### PR DESCRIPTION
**Pull request by gnossen**
This PR builds all MacOS artifacts as [`universal2`](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary) artifacts by default. This builds the `.whl` with a shared object library supporting both the `x86_64` and `arm64` platforms:

```
rbellevi-macbookpro:tmp.u9QVKZQH rbellevi$ file ./grpc/_cython/cygrpc.cpython-311-darwin.so
./grpc/_cython/cygrpc.cpython-311-darwin.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64Mach-O 64-bit bundle x86_64] [arm64]
./grpc/_cython/cygrpc.cpython-311-darwin.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
./grpc/_cython/cygrpc.cpython-311-darwin.so (for architecture arm64):	Mach-O 64-bit bundle arm64
```

This also removes the hack introduced by https://github.com/grpc/grpc/pull/29857 since we are now truly building universal artifacts. Fixes #29262

### CODE REVIEW

**Comment by gnossen** [comment]
Whoops. Looks like in the most recent build, only 3.11 artifacts ended up as universal. I guess this need some more work.

**Comment by gnossen** [comment]
Yet another issue:

```
(venv) rbellevi-macbookpro:tmp.u9QVKZQH rbellevi$ file  grpc/_cython/cygrpc.cpython-310-darwin.so
grpc/_cython/cygrpc.cpython-310-darwin.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64Mach-O 64-bit bundle x86_64] [arm64]
grpc/_cython/cygrpc.cpython-310-darwin.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
grpc/_cython/cygrpc.cpython-310-darwin.so (for architecture arm64):	Mach-O 64-bit bundle arm64
(venv) rbellevi-macbookpro:tmp.u9QVKZQH rbellevi$ arch
arm64
(venv) rbellevi-macbookpro:tmp.u9QVKZQH rbellevi$ python
Python 3.10.7 (main, Nov 29 2022, 11:11:58) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/var/folders/p1/18dr8yp97cs7mq__92r5fwfr00krr5/T/tmp.u9QVKZQH/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/private/var/folders/p1/18dr8yp97cs7mq__92r5fwfr00krr5/T/tmp.u9QVKZQH/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/private/var/folders/p1/18dr8yp97cs7mq__92r5fwfr00krr5/T/tmp.u9QVKZQH/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_ChaCha20_ctr32)
```

It looks like a symbol from boringssl is missing. It seems that this function is written in assembly and expected to be linked in separately. As far as I can tell, there is no arm64 implementation. We'll probably have to turn off boringssl assembly optimizations. Hopefully, we can do it just for the arm64 version and not the x86 version, but I'm not sure yet if that's possible.

**Comment by gnossen** [comment]
It looks like selectively disabling ASM optimizations for just arm64 would be difficult. We'd likely have to compile to object files then link them together into a fat archive using (e.g.) `lipo`. For the moment, I think it's reasonable to just disable the assembly optimizations for our prebuilt MacOS artifacts. This will allow M1 users to start using things right away.

**Review by XuanWang-Amos — APPROVED** [review]

**Comment by gnossen** [comment]
This should make it into 1.52.0, which is currently scheduled for release December 27th, but may slip by a week or so due to the holidays.

**Pull request merged**
