### PR TITLE
Update run tests instructions

### PR DESCRIPTION
**Pull request by hcaseyal**
When first installing grpc and trying to run tests, I've encountered python import errors multiple times. It may not be clear to some users what they need to do to resolve the errors.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by hcaseyal** [comment]
Going to create a branch on my fork instead of master

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +4.4%     +16 src/core/lib/security/credentials/alts/grpc_alts_credentials_client_options.cc           +16  +4.4%
      [NEW]    +110 grpc_alts_credentials_client_options_add_target_service_account                         +110  [NEW]
      [NEW]     +29 grpc_alts_credentials_client_options_create                                              +29  [NEW]
       +12%      +1 [Unmapped]                                                                                +1   +12%

 -------------- SHRINKING                                                                            --------------
  -0.2% -1.52Ki [None]                                                                               -7.21Ki  -0.1%
      -0.2% -1.43Ki [Unmapped]                                                                           -7.18Ki  -0.1%
      -3.3%     -40 [None]                                                                                     0  [ = ]
      [DEL]     -24 grpc_handshaker_trace                                                                      0  [ = ]
     -25.0%      -8 fail_handshaker_vtable                                                                    -8 -25.0%
     -25.0%      -8 security_handshaker_vtable                                                                -8 -25.0%
     -25.0%      -8 http_connect_handshaker_vtable                                                            -8 -25.0%
 -24.7%    -560 src/core/lib/channel/handshaker.cc                                                      -560 -24.7%
     -67.2%    -415 call_next_handshaker_locked                                                             -415 -67.2%
     -38.6%     -83 grpc_handshake_manager_add                                                               -83 -38.6%
      [DEL]     -48 _GLOBAL__sub_I_handshaker.cc                                                             -48  [DEL]
      [DEL]      -8 grpc_handshaker_name                                                                      -8  [DEL]
      -4.9%      -6 [Unmapped]                                                                                -6  -4.9%
  -1.3%    -400 src/core/ext/filters/client_channel/client_channel.cc                                   -400  -1.3%
      [DEL]    -460 execute_closures_in_call_combiner(grpc_call_element*, char const*, closure_to_execut    -460  [DEL]
      [DEL]    -181 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    -181  [DEL]
      [DEL]    -163 add_closure_for_subchannel_batch(client_channel_call_data*, grpc_transport_stream_op    -163  [DEL]
      [DEL]    -107 free_cached_send_message                                                                -107  [DEL]
      [DEL]     -64 free_cached_send_initial_metadata                                                        -64  [DEL]
      [DEL]     -64 free_cached_send_trailing_metadata                                                       -64  [DEL]
     -10.6%     -19 start_internal_recv_trailing_metadata                                                    -19 -10.6%
  -8.0%    -326 src/core/lib/channel/channel_args.cc                                                    -326  -8.0%
      [DEL]    -316 grpc_channel_args_string                                                                -316  [DEL]
      -5.4%     -10 [Unmapped]                                                                               -10  -5.4%
  -0.9%    -288 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             -288  -0.9%
     -52.3%    -291 init_keepalive_ping_locked                                                              -291 -52.3%
  -0.3%     -16 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc             -16  -0.3%
      -7.5%      -8 [Unmapped]                                                                                -8  -7.5%
      -7.0%      -8 grpc_ares_request_unref                                                                   -8  -7.0%
  -1.0%     -16 third_party/address_sorting/address_sorting.c                                            -16  -1.0%
     -37.2%     -16 address_sorting_shutdown                                                                 -16 -37.2%

  -0.2% -3.07Ki TOTAL                                                                                -8.76Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.5% -1.12Ki [None]                                                                               -13.5Ki  -0.3%
      -0.5% -1.11Ki [Unmapped]                                                                           -13.5Ki  -0.3%
     -12.3%     -16 [None]                                                                                     0  [ = ]
  -3.6%    -336 src/cpp/client/secure_credentials.cc                                                    -336  -3.6%
      [DEL]    -335 grpc::experimental::AltsCredentials                                                     -335  [DEL]
      [DEL]    -194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    -194  [DEL]
      -0.7%      -1 [Unmapped]                                                                                -1  -0.7%
  -3.6%    -192 src/cpp/server/secure_server_credentials.cc                                             -192  -3.6%
      [DEL]    -184 grpc::experimental::AltsServerCredentials                                               -184  [DEL]
     -17.8%      -8 [Unmapped]                                                                                -8 -17.8%

  -0.5% -1.64Ki TOTAL                                                                                -14.0Ki  -0.3%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
