### PR TITLE
Actually build CensusContext

### PR DESCRIPTION
**Pull request by gnossen**
Re-add accidentally reverted `_channel.py`

(related to #17460)

### CODE REVIEW

**Comment by lidizheng** [comment]
Related PR #17460

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,870      Total (=)      2,020,870

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,114      Total (<)     11,177,122

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,870      Total (=)      2,020,870

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,122      Total (>)     11,177,121

 No significant differences in binary sizes


```

**Comment by lidizheng** [comment]
Do you think we should add a minimal test in GitHub?

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,870      Total (=)      2,020,870

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,125      Total (>)     11,177,117

 No significant differences in binary sizes


```

**Pull request merged**
