### PR TITLE
Update bazel_support.md

### PR DESCRIPTION
**Pull request by Clement-Jean**
Typo where 'k' should be a comma. We can now copy paste the code as is.

### CODE REVIEW

**Comment by yijiem** [comment]
Not really familiar with this, but I believe this file is generated from the template here: [bazel_support.md.template](../blob/136055b043dcf2b15f69f535f659e4090cf25b9f/templates/doc/bazel_support.md.template)

Can you change that template and run `tools/buildgen/generate_projects.sh` to see if it works? You can find more info here: https://github.com/grpc/grpc/tree/master/templates#regenerating-project-files

**Review by jtattermusch — APPROVED** [review]
Good catch, looks like the typo was introduced by https://github.com/grpc/grpc/pull/29191.

**Comment by jtattermusch** [comment]
I'll merge once the tests are green.

**Comment by jtattermusch** [comment]
The bazel distribtest failure is also happening on master so it is unrelated. Other tests are green.

**Pull request merged**
