### PR TITLE
Reorder the compression algorithm by level

### PR DESCRIPTION
**Pull request by AspirinSJL**
As titled.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                 FILE SIZE
 ++++++++++++++ GROWING                                   ++++++++++++++
  +0.6%      +8 src/core/lib/compression/compression.cc        +8  +0.6%
       +19%      +9 [Unmapped]                                     +9   +19%
      +9.8%      +8 grpc_compression_encoding_mdelem               +8  +9.8%

 -------------- SHRINKING                                 --------------
  -0.0%      -8 [None]                                        -64  -0.0%

  [ = ]       0 TOTAL                                         -56  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by muxi** [comment]
Needs a bit of tweak [here](https://github.com/grpc/grpc/blob/master/src/core/lib/compression/compression.cc#L32) too.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,866      Total (<)      2,020,870

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,126      Total (<)     11,177,129

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++
  +0.6%      +8 src/core/lib/compression/compression.cc      +8  +0.6%
      +9.8%      +8 grpc_compression_encoding_mdelem             +8  +9.8%

 -------------- SHRINKING                               --------------
  -0.0%      -8 [None]                                       -8  -0.0%

  [ = ]       0 TOTAL                                         0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                    FILE SIZE
 ++++++++++++++ GROWING                                      ++++++++++++++
  +0.6%      +8 src/core/lib/compression/compression.cc           +8  +0.6%
      +9.8%      +8 grpc_compression_encoding_mdelem                  +8  +9.8%
  +0.1%      +3 src/core/lib/compression/message_compress.cc      +3  +0.1%
       +13%      +5 [Unmapped]                                        +5   +13%
      +2.8%      +3 grpc_msg_decompress                               +3  +2.8%

 -------------- SHRINKING                                    --------------
  -0.0%     -11 [None]                                           -19  -0.0%

  [ = ]       0 TOTAL                                             -8  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
@muxi Please take another look. Thanks!

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                    FILE SIZE
 ++++++++++++++ GROWING                                      ++++++++++++++
  +0.6%      +8 src/core/lib/compression/compression.cc           +8  +0.6%
      +9.8%      +8 grpc_compression_encoding_mdelem                  +8  +9.8%
  +0.1%      +3 src/core/lib/compression/message_compress.cc      +3  +0.1%
       +13%      +5 [Unmapped]                                        +5   +13%
      +2.8%      +3 grpc_msg_decompress                               +3  +2.8%

 -------------- SHRINKING                                    --------------
  -0.0%     -11 [None]                                           -19  -0.0%

  [ = ]       0 TOTAL                                             -8  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by vjpai** [comment]
Actually, I changed my mind. Enum ordering is not an API guarantee, it's a Hyrum's Law thing, and we should definitely reorder the enums as many times as we want as long as their names don't change.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                    FILE SIZE
 ++++++++++++++ GROWING                                      ++++++++++++++
  +0.6%      +8 src/core/lib/compression/compression.cc           +8  +0.6%
      +9.8%      +8 grpc_compression_encoding_mdelem                  +8  +9.8%
  +0.1%      +3 src/core/lib/compression/message_compress.cc      +3  +0.1%
       +13%      +5 [Unmapped]                                        +5   +13%
      +2.8%      +3 grpc_msg_decompress                               +3  +2.8%

 -------------- SHRINKING                                    --------------
  -0.0%     -11 [None]                                           -19  -0.0%

  [ = ]       0 TOTAL                                             -8  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by vjpai** [comment]
I'm requesting that we hold off on merging this change until we get some external guidance about what enum stability implies.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
The advice that I'm seeing and to which @AspirinSJL is also on the list is that enum reordering is an API breaker unless we've explicitly declared otherwise. So I'd suggest not doing this unless it is truly unavoidable.

**Comment by muxi** [comment]
Any reference?

**Comment by vjpai** [comment]
@muxi : I'll send you a link

**Comment by AspirinSJL** [comment]
Good to know!

Closing this PR.

**Pull request closed without merging**
