### PR TITLE
Renamed load_reporting.{c,h} to load_reporting_plugin.{c,h}

### PR DESCRIPTION
**Pull request by dgquintas**
The previous name was ambiguous and confusing.

### CODE REVIEW

**Comment by dgquintas** [comment]
ping

**Comment by yang-g** [comment]
update include guard? :)

**Comment by markdroth** [comment]
As long as you're renaming this, how about calling it `server_load_reporting_plugin`, to disambiguate with client-side load reporting?

**Comment by dgquintas** [comment]
Issues: #12394

**Pull request merged**
