### PR TITLE
[php] fix SEGFAULT on buffer destroy

### PR DESCRIPTION
**Pull request by shmel1k**
Hello!
I figured out that if I firewall the gRPC host(e.g. `iptables -I INPUT -s some_ip_addr -j DROP`, where I do requests, my PHP-fpms get SEGFAULT errors.
Something like
```
#0  malloc_printerr (ar_ptr=0x75e8c7894800001e, ptr=<optimized out>, str=0x7f843f0ebcaf "free(): invalid pointer", action=3) at malloc.c:4993
No locals.
#1  _int_free (av=0x75e8c7894800001e, p=<optimized out>, have_lock=0) at malloc.c:3867
        size = <optimized out>
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = <optimized out>
        locked = <optimized out>
#2  0x00007f843efe253c in __GI___libc_free (mem=mem@entry=0x55c178017cc6 <ap_php_snprintf+166>) at malloc.c:2968
        ar_ptr = <optimized out>
        p = 0x55c178017cb6 <ap_php_snprintf+150>
        hook = <optimized out>
#3  0x00007f84308346f5 in gpr_free (p=p@entry=0x55c178017cc6 <ap_php_snprintf+166>) at src/core/lib/gpr/alloc.cc:52
No locals.
#4  0x00007f84308056e0 in grpc_byte_buffer_destroy (bb=0x55c178017cc6 <ap_php_snprintf+166>) at src/core/lib/surface/byte_buffer.cc:83
        exec_ctx = {_vptr.ExecCtx = 0x7f8430cd4170 <vtable for grpc_core::ExecCtx+16>, closure_list_ = {head = 0x0, tail = 0x0}, combiner_data_ = {active_combiner = 0x0, last_combiner = 0x0}, flags_ = 1, starting_cpu_ = 4294967295, now_is_valid_ = false, now_ = 0,
          static exec_ctx_ = 140721568857952, last_exec_ctx_ = 0x0}
#5  0x00007f8430cf94b9 in zim_Call_startBatch (execute_data=<optimized out>, return_value=<optimized out>) at /home/a.petrukhin/grpc/src/php/ext/grpc/call.c:531
        i = <optimized out>
        result = 0x7f843be63630
        index = <optimized out>
        recv_status = <optimized out>
        value = <optimized out>
        inner_value = <optimized out>
        message_value = <optimized out>
        message_flags = <optimized out>
        ops = {{op = GRPC_OP_RECV_MESSAGE, flags = 0, reserved = 0x0, data = {reserved = {reserved = {0x7ffc4b1fc088, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}, send_initial_metadata = {count = 140721568858248, metadata = 0x0, maybe_compression_level = {is_set = 0 '\000',
                  level = GRPC_COMPRESS_LEVEL_NONE}}, send_message = {send_message = 0x7ffc4b1fc088}, send_status_from_server = {trailing_metadata_count = 140721568858248, trailing_metadata = 0x0, status = GRPC_STATUS_OK, status_details = 0x0}, recv_initial_metadata = {
                recv_initial_metadata = 0x7ffc4b1fc088}, recv_message = {recv_message = 0x7ffc4b1fc088}, recv_status_on_client = {trailing_metadata = 0x7ffc4b1fc088, status = 0x0, status_details = 0x0, error_string = 0x0}, recv_close_on_server = {cancelled = 0x7ffc4b1fc088}}}, {
            op = GRPC_OP_RECV_STATUS_ON_CLIENT, flags = 0, reserved = 0x0, data = {reserved = {reserved = {0x7ffc4b1fc100, 0x7ffc4b1fc078, 0x7ffc4b1fc120, 0x0, 0x0, 0x0, 0x0, 0x0}}, send_initial_metadata = {count = 140721568858368, metadata = 0x7ffc4b1fc078,
                maybe_compression_level = {is_set = 32 ' ', level = 32764}}, send_message = {send_message = 0x7ffc4b1fc100}, send_status_from_server = {trailing_metadata_count = 140721568858368, trailing_metadata = 0x7ffc4b1fc078, status = 1260372256, status_details = 0x0},
              recv_initial_metadata = {recv_initial_metadata = 0x7ffc4b1fc100}, recv_message = {recv_message = 0x7ffc4b1fc100}, recv_status_on_client = {trailing_metadata = 0x7ffc4b1fc100, status = 0x7ffc4b1fc078, status_details = 0x7ffc4b1fc120, error_string = 0x0},
              recv_close_on_server = {cancelled = 0x7ffc4b1fc100}}}, {op = GRPC_OP_SEND_INITIAL_METADATA, flags = 0, reserved = 0x0, data = {reserved = {reserved = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}, send_initial_metadata = {count = 0, metadata = 0x0,
                maybe_compression_level = {is_set = 0 '\000', level = GRPC_COMPRESS_LEVEL_NONE}}, send_message = {send_message = 0x0}, send_status_from_server = {trailing_metadata_count = 0, trailing_metadata = 0x0, status = GRPC_STATUS_OK, status_details = 0x0},
              recv_initial_metadata = {recv_initial_metadata = 0x0}, recv_message = {recv_message = 0x0}, recv_status_on_client = {trailing_metadata = 0x0, status = 0x0, status_details = 0x0, error_string = 0x0}, recv_close_on_server = {cancelled = 0x0}}}, {
            op = GRPC_OP_SEND_INITIAL_METADATA, flags = 0, reserved = 0x0, data = {reserved = {reserved = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}, send_initial_metadata = {count = 0, metadata = 0x0, maybe_compression_level = {is_set = 0 '\000',
                  level = GRPC_COMPRESS_LEVEL_NONE}}, send_message = {send_message = 0x0}, send_status_from_server = {trailing_metadata_count = 0, trailing_metadata = 0x0, status = GRPC_STATUS_OK, status_details = 0x0}, recv_initial_metadata = {recv_initial_metadata = 0x0},
              recv_message = {recv_message = 0x0}, recv_status_on_client = {trailing_metadata = 0x0, status = 0x0, status_details = 0x0, error_string = 0x0}, recv_close_on_server = {cancelled = 0x0}}}, {op = GRPC_OP_SEND_INITIAL_METADATA, flags = 0, reserved = 0x0, data = {
              reserved = {reserved = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}, send_initial_metadata = {count = 0, metadata = 0x0, maybe_compression_level = {is_set = 0 '\000', level = GRPC_COMPRESS_LEVEL_NONE}}, send_message = {send_message = 0x0}, send_status_from_server = {
                trailing_metadata_count = 0, trailing_metadata = 0x0, status = GRPC_STATUS_OK, status_details = 0x0}, recv_initial_metadata = {recv_initial_metadata = 0x0}, recv_message = {recv_message = 0x0}, recv_status_on_client = {trailing_metadata = 0x0, status = 0x0,
                status_details = 0x0, error_string = 0x0}, recv_close_on_server = {cancelled = 0x0}}}, {op = GRPC_OP_SEND_INITIAL_METADATA, flags = 0, reserved = 0x0, data = {reserved = {reserved = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}, send_initial_metadata = {count = 0,
                metadata = 0x0, maybe_compression_level = {is_set = 0 '\000', level = GRPC_COMPRESS_LEVEL_NONE}}, send_message = {send_message = 0x0}, send_status_from_server = {trailing_metadata_count = 0, trailing_metadata = 0x0, status = GRPC_STATUS_OK, status_details = 0x0},
              recv_initial_metadata = {recv_initial_metadata = 0x0}, recv_message = {recv_message = 0x0}, recv_status_on_client = {trailing_metadata = 0x0, status = 0x0, status_details = 0x0, error_string = 0x0}, recv_close_on_server = {cancelled = 0x0}}}, {
            op = GRPC_OP_SEND_INITIAL_METADATA, flags = 0, reserved = 0x0, data = {reserved = {reserved = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}, send_initial_metadata = {count = 0, metadata = 0x0, maybe_compression_level = {is_set = 0 '\000',
                  level = GRPC_COMPRESS_LEVEL_NONE}}, send_message = {send_message = 0x0}, send_status_from_server = {trailing_metadata_count = 0, trailing_metadata = 0x0, status = GRPC_STATUS_OK, status_details = 0x0}, recv_initial_metadata = {recv_initial_metadata = 0x0},
              recv_message = {recv_message = 0x0}, recv_status_on_client = {trailing_metadata = 0x0, status = 0x0, status_details = 0x0, error_string = 0x0}, recv_close_on_server = {cancelled = 0x0}}}, {op = GRPC_OP_SEND_INITIAL_METADATA, flags = 0, reserved = 0x0, data = {
              reserved = {reserved = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}, send_initial_metadata = {count = 0, metadata = 0x0, maybe_compression_level = {is_set = 0 '\000', level = GRPC_COMPRESS_LEVEL_NONE}}, send_message = {send_message = 0x0}, send_status_from_server = {
                trailing_metadata_count = 0, trailing_metadata = 0x0, status = GRPC_STATUS_OK, status_details = 0x0}, recv_initial_metadata = {recv_initial_metadata = 0x0}, recv_message = {recv_message = 0x0}, recv_status_on_client = {trailing_metadata = 0x0, status = 0x0,
                status_details = 0x0, error_string = 0x0}, recv_close_on_server = {cancelled = 0x0}}}}
        op_num = 2
        array = 0x7f843be1be60
        array_hash = <optimized out>
        status_hash = <optimized out>
        message_hash = <optimized out>
        metadata = {count = 0, capacity = 0, metadata = 0x0}
        trailing_metadata = {count = 0, capacity = 0, metadata = 0x0}
        recv_metadata = {count = 0, capacity = 0, metadata = 0x0}
        recv_trailing_metadata = {count = 0, capacity = 0, metadata = 0x0}
        status = 778233600
```

After further investigation I found that I get crashes if I get call_status != GRPC_STATUS_OK. Looks like then buffer is tried to be deallocated, but I do not really know, what is inside this buffer. The string is "sprintf"ed, possibly, there is some static buffer which can not be freed.

How I tested, that this code works: just firewalled the remote host and gave some RPS, waiting for PHP memory leaks. I have not found them.

Thanks in advance!
If I am wrong, can you tell me investigation direction, so I can fix it and send other PR? :)

@markdroth

### CODE REVIEW

**Comment by stanley-cheung** [comment]
@shmel1k Thanks for this PR. This looks interesting. We'd certainly like to look into this more. Is there some way we can reproduce this? Ideally, we can base this on some pre-built PHP docker image like `FROM php:7.3-fpm`. Give us a sample `php-fpm.conf` file and we can try to hit it with many requests to try to reproduce that crash? Do you think you will be able to help us reproduce it that way?

**Comment by shmel1k** [comment]
@stanley-cheung, thanks for your answer
My current PHP version is `7.2.33-1+ubuntu16.04.1+deb.sury.org+1`

My php-fpm.conf is pretty default
```
pid = /var/run/php/php7.2-fpm.pid
error_log = /var/log/php-fpm/error.log
syslog.facility = daemon
syslog.ident = php-fpm
log_level = notice
emergency_restart_threshold = 0
rlimit_core = unlimited
include=/etc/php/7.2/fpm/pool.d/*.conf
```


My  conf.d/20-grpc.ini is also quite empty
```
extension=grpc.so
```

Which configuration we have:
php-fpm -> nginx with gRPC module -> some external gRPC service. When I firewall nginx, php-fpm begin to SEGFAULT.

**Comment by shmel1k** [comment]
@stanley-cheung, is there any info about the bug? 
We deployed this fix and everything looks fine(at least I hope so :))

**Comment by stanley-cheung** [comment]
@shmel1k Thanks for the update. Unfortunately, it will take us some time to properly reproduce this and work this into our testing as we lack this use case for now. And with the holidays coming up, I can't guarantee we can get to this quickly. But rest assured that we will look into this when possible. And given that this fix works for you, it is likely that we will accept this in some form or shape. We just have to work through the testing aspects of things. Hope you understand!

**Comment by shmel1k** [comment]
It is okay!
What should I do? Write some tests for my functionality that reproduces the problem and proves, that my fix works?

**Comment by stanley-cheung** [comment]
Yes - basically what we need is some very precise steps to reproduce this, ideally in the form of a docker image. Like, if you can set up a very simple git repo with a base dockerfile. And let us know - build this docker image this way, launch it this way, hit it this way. No errors. Then kill the Nginx image (to simulate upstream host going away). And hit php-fpm again and see the errors. Stuff like that would be tremendously helpful to us.

**Comment by pparshin** [comment]
Hi, @stanley-cheung 

I investigated this problem along with @shmel1k and found out that the problem occurs when we try to reuse existing UnaryCall in retries. I wrote a simple test which produces a coredump:

```php
    public function testReuseCall()
    {
        $div_arg = new Math\DivArgs();
        $div_arg->setDividend(7);
        $div_arg->setDivisor(4);
        $call = self::$client->Div($div_arg, [], ['timeout' => 1000000]);

        for ($i = 1; $i <= 2; $i++) {
            list($response, $status) = $call->wait();
            $this->assertSame(\Grpc\STATUS_OK, $status->code);
        }
    }
```

Suppose that better to handle such cases and throw an exception because I really hadn't seen any reason to create a new instance of the UnaryCall in retries or just clarify this moment in the documentation.

**Comment by stanley-cheung** [comment]
@pparshin this is good to know. Thanks for the short and concise test case. We will definitely look into this.

**Comment by stanley-cheung** [comment]
@shmel1k @pparshin After doing more research, we have come up with an alternate, slightly more simpler solution to this problem. Can you have a look at #25245? This should fix the crash when the call object is being re-used after the call is finished. (It should throw an error instead of crashing). That PR has cleared our testing so we would appreciate if you can confirm if that will solve your issue as well. Thanks!

**Comment by stanley-cheung** [comment]
Superceded by #25245.

**Pull request closed without merging**
