### PR TITLE
Swallow content-type at the client.

### LINKED ISSUE #3368: Swallow Content-Type when sent from server --> client
Currently we hand this up to the application, but since it's really "protocol stuff" it should be consumed in the core library.

### PR DESCRIPTION
**Pull request by dgquintas**
Fixes #3368

### CODE REVIEW

**Comment by ctiller** [comment]
This should be in http_client_filter.c

**Comment by dgquintas** [comment]
Ack, sending revert+new changes in a separate PR referencing this one in a bit.

**Comment by ctiller** [comment]
Also: thank-you :)

**Comment by nicolasnoble** [comment]
Sorry, I needed that a bit urgently :-)

**Comment by dgquintas** [comment]
modifying http_client_filter would prevent the client from sending the content-type, but isn't when the client is receiving from a server (ie, as part of recv_metadata, as in the present PR) when we should swallow it?

**Pull request merged**
