### PR TITLE
Fix issue #9602

### LINKED ISSUE #9602: CMake build system: important include not exported (not being installed)
The following file:
```
include/grpc++/impl/codegen/proto_utils.h
```

is required when compiling against gRPC.  One finds it in the headers generated by the protobuf grpc++ plugin. Unfortunately, the file is not being installed. Well, at least not when gRPC_BUILD_TESTS is FALSE ;-)

### PR DESCRIPTION
**Pull request by ppietrasa**
Fixes #9602.

This is achieved by putting `grpc++_codegegen_proto` on the `filegroup` of `grpc++`.

### CODE REVIEW

**Comment by jtattermusch** [comment]
you need to run tools/buildgen/generate_projects.sh to regenerate the file generated from build.yaml.

**Comment by ppietrasa** [comment]
@jtattermusch I know. I did run it locally. The CMakeListst.txt was successfully generated and I tested that it works. 

I intentionally did not include the re-generated file in the pull request to minimize the risk that it conflicts with changes coming from other pull requests. I thought you might want to regenerate the file yourself after you go over and approve the pull requests.  Note, I myself authored another request (#9599) which impacts the generated CMakeLists.txt.

**Comment by jtattermusch** [comment]
@ppietrasa  please just add the generated CMakeLists.txt to this PR, because without it I can't really run the CI tests (which is what I'd like to check first).

**Comment by ppietrasa** [comment]
@jtattermusch done

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
Sanity test is failing: https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2638/testReport/junit/(root)/aggregate_tests/run_tests_sanity_linux_opt/

perhaps you didn't include all the files that got generated from build.yaml change?

**Comment by jtattermusch** [comment]
I checked with @nicolasnoble  and the change itself makes sense - thanks for noticing that. There are a few more things needed:
 - adding all the files that have been modified by tools/buildgen/generate_projects.sh  
 - we also need to update the bazel BUILD file with the dependency (right now we temporarily have two sources of truth for the project structure - BUILD file and build.yaml).

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
Known failures:
- https://github.com/grpc/grpc/issues/9669
- https://github.com/grpc/grpc/issues/9399
- https://github.com/grpc/grpc/issues/9674

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @ppietrasa isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request merged**
