### PR TITLE
Move a census file from src/cpp to src/core since core depends on it

### PR DESCRIPTION
**Pull request by vjpai**
This was the only file in `src/cpp` that was depended on by something in `src/core`. This in turn was screwing up source distributions for wrapped languages. Also added a sanity check to avoid reintroducing this problem.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                   FILE SIZE
 ++++++++++++++ GROWING                                     ++++++++++++++
  [NEW]    +193 src/core/ext/filters/census/grpc_context.cc    +193  [NEW]
      [NEW]    +113 grpc_census_call_set_context                   +113  [NEW]
      [NEW]     +65 grpc_census_call_get_context                    +65  [NEW]
      [NEW]     +15 [Unmapped]                                      +15  [NEW]

 -------------- SHRINKING                                   --------------
  [DEL]    -193 src/cpp/ext/filters/census/grpc_context.cc     -193  [DEL]
      [DEL]    -113 grpc_census_call_set_context                   -113  [DEL]
      [DEL]     -65 grpc_census_call_get_context                    -65  [DEL]
      [DEL]     -15 [Unmapped]                                      -15  [DEL]
  [ = ]       0 [None]                                         -104  -0.0%

  [ = ]       0 TOTAL                                          -104  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                   FILE SIZE
 ++++++++++++++ GROWING                                     ++++++++++++++
  [NEW]    +193 src/core/ext/filters/census/grpc_context.cc    +193  [NEW]
      [NEW]    +113 grpc_census_call_set_context                   +113  [NEW]
      [NEW]     +65 grpc_census_call_get_context                    +65  [NEW]
      [NEW]     +15 [Unmapped]                                      +15  [NEW]

 -------------- SHRINKING                                   --------------
  [DEL]    -193 src/cpp/ext/filters/census/grpc_context.cc     -193  [DEL]
      [DEL]    -113 grpc_census_call_set_context                   -113  [DEL]
      [DEL]     -65 grpc_census_call_get_context                    -65  [DEL]
      [DEL]     -15 [Unmapped]                                      -15  [DEL]
  [ = ]       0 [None]                                         -104  -0.0%

  [ = ]       0 TOTAL                                          -104  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                   FILE SIZE
 ++++++++++++++ GROWING                                     ++++++++++++++
  [NEW]    +193 src/core/ext/filters/census/grpc_context.cc    +193  [NEW]
      [NEW]    +113 grpc_census_call_set_context                   +113  [NEW]
      [NEW]     +65 grpc_census_call_get_context                    +65  [NEW]
      [NEW]     +15 [Unmapped]                                      +15  [NEW]

 -------------- SHRINKING                                   --------------
  [DEL]    -193 src/cpp/ext/filters/census/grpc_context.cc     -193  [DEL]
      [DEL]    -113 grpc_census_call_set_context                   -113  [DEL]
      [DEL]     -65 grpc_census_call_get_context                    -65  [DEL]
      [DEL]     -15 [Unmapped]                                      -15  [DEL]
  [ = ]       0 [None]                                         -104  -0.0%

  [ = ]       0 TOTAL                                          -104  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,730      Total (=)      1,952,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,663,749      Total (>)     10,663,743

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,730      Total (=)      1,952,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,663,751      Total (>)     10,663,747

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,730      Total (=)      1,952,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,663,752      Total (=)     10,663,752

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Hi @Vizerai and @g-easy , I'm going to merge this to avoid causing problems with our distributions, but please revert it if it does indeed cause any problems for census.

**Pull request merged**
