### PR TITLE
Revert "Revert "Add back C# distribtests for Grpc.Tools""

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#31412.

Second attempt to add https://github.com/grpc/grpc/pull/31399.
The original PR was reverted because the packages from testcodegen.proto clashed with some internal .proto files. Changing the package should help.

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @tonydnewell

**Review by apolcyn — APPROVED** [review]

**Comment by jtattermusch** [comment]
FTR: https://source.cloud.google.com/results/invocations/08298adc-8586-494c-8488-836f3b505cef/targets;collapsed=/github%2Fgrpc%2Fdistribtests/tests;passed=true

**Comment by jtattermusch** [comment]
This PR should be ready to merge once the revert from https://github.com/grpc/grpc/pull/31464 gets merged.

**Comment by jtattermusch** [comment]
The windows basictests C# failure is a known problem and unrelated to this PR: https://source.cloud.google.com/results/invocations/ff159488-0667-44b2-9c53-38f23fa2b661/log

**Comment by tonydnewell** [comment]
@jtattermusch I've managed to reproduce the issue and I'm investigating

**Comment by CaptainCplus** [comment]
It Might Of Not Worked Because To Many Hashtags?
To Be Honest That's The Only Reason I Know.
Cheers!
CaptainCplus.

**Comment by CaptainCplus** [comment]
@jtattermusch i will look into this problem and figure this out.

**Comment by CaptainCplus** [comment]
@jtattermusch Sadly I cannot simply do it, I am sorry, there is no available research on that Web page, Reply if you want to talk, or send me a issue (for example) a issue on Babel, or anything on github.
Cheers!
CaptainCplus

**Pull request merged**
