### PR TITLE
Fixing a reported ruby crash when using ruby_vm_at_exit.

### PR DESCRIPTION
**Pull request by nicolasnoble**
@blowmage for the confirmation this actually fixes the problems.

### CODE REVIEW

**Comment by blowmage** [comment]
I can confirm this change resolves the segfault for me on ruby versions 2.3.0, 2.2.3, and 2.2.0.

| version | before | after |
| ----- | ----- | ----- |
| 2.0.0 | pass | pass |
| 2.1.0 | pass | pass |
| 2.2.0 | **segfault** | pass |
| 2.2.3 | **segfault** | pass |
| 2.3.0 | **segfault** | pass |

@nicolasnoble thank you so much for identifying this!

**Comment by nicolasnoble** [comment]
Unfortunately, this seems to be creating a crash condition elsewhere.

**Comment by nicolasnoble** [comment]
Worked around it with another technique.

**Comment by blowmage** [comment]
@nicolasnoble Do you want me to retest on my setup?

**Comment by nicolasnoble** [comment]
@blowmage  If you wouldn't mind, yes, please :)

**Comment by nicolasnoble** [comment]
And the problem with the initial attempt is that this is invoked by Ruby's garbage collection, which means we don't have control over the order in which things gets destroyed, which is a problem in our case.

**Comment by blowmage** [comment]
K, it will be a few hours until I'm able to retest. I'll let you know.

**Comment by nicolasnoble** [comment]
Entered a Ruby bug for that one, as it really seems to be a bug in the Ruby's VM, involving the garbage collector: https://bugs.ruby-lang.org/issues/12095

**Comment by blowmage** [comment]
Have applied this patch and recompiled on ruby versions 2.0.0, 2.1.0, 2.2.0, 2.2.3, and 2.3.0 and all worked properly. No more segfaults!

**Comment by blowmage** [comment]
@nicolasnoble Any word on when this fix will be released? We continue to see segfaults on our CI builds. We'd like to have this fix out before adding the dependency to our gem.

**Comment by evanphx** [comment]
The ruby bug in question has been identify and the patch is written and waiting to be applied. I'll work to get it ported backwards to all maintained ruby versions (2.0+).

**Comment by evanphx** [comment]
@nicolasnoble Would it be possible to release 0.13.1 with your fix?

**Comment by blowmage** [comment]
Or a 0.14.0 release that includes this _and_ the GC/call credentials fix? :)

**Pull request merged**
