### PR TITLE
Upgrade re2 to 2024-04-01 (Latest CMake Build Fix)

### PR DESCRIPTION
**Pull request by xanather**
Fixes https://github.com/grpc/grpc/issues/36358#issuecomment-2099157513

### CODE REVIEW

**Comment by xanather** [comment]
Anything I can do to get this merged?

**Comment by xanather** [comment]
This is such a simple commit that'll fix my build pipeline. I can't choose what version of CMake I am using on GitHub hosted runners so can this please be merged?

**Review by yashykt — APPROVED** [review]

**Comment by BusyJay** [comment]
Can we get this landed on 1.64.1? This should also fix the issue that re2.pc is missing when build and install grpc and its dependencies using cmake.

**Comment by veblush** [comment]
There are many test failures. You need to resolve them to get this merged.

**Comment by xanather** [comment]
Half the tests I don't even have permission to view.

Anyway, it seems RE2 isn't properly picking up ABSL targets anymore.

**Comment by xanather** [comment]
I might spend some time trying to fix this if I get permissions to view and run the GCP tests myself so I can sort it in one sitting otherwise its not my problem.

**Comment by xanather** [comment]
OK so this is caused by RE2 now depending on abseil in the latest version, that wasn't the case 2 years ago.

I have stopped using git submodules and started pulling down latest sources from each repo to build gRPC and it works fine on Windows. Mac and Linux.

I am going to close this PR since this will involve more work for the other platforms, but I'll leave the associated issue open.

**Pull request closed without merging**
