### PR TITLE
Simplify grpclb update handling

### PR DESCRIPTION
**Pull request by markdroth**
This is one of the changes I suggested in #12587.  I'm not entirely sure this won't break anything, so let's see how the tests look.

### CODE REVIEW

**Comment by markdroth** [comment]
Fixes #12727.

**Comment by AspirinSJL** [comment]
BTW, I just merged the fallback PR (finally!). So you may want to rebase this PR now.

**Comment by markdroth** [comment]
Merged changes from master.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                      FILE SIZE
 ++++++++++++++ GROWING                                                        ++++++++++++++

 -------------- SHRINKING                                                      --------------
  -1.9%    -272 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc    -272  -1.9%
     -18.9%    -175 glb_update_locked                                                 -175 -18.9%
     -13.9%     -61 glb_lb_channel_on_connectivity_changed_cb                          -61 -13.9%
     -13.0%     -36 glb_destroy                                                        -36 -13.0%
  -0.0%     -48 [None]                                                            -216  -0.0%

  -0.0%    -320 TOTAL                                                             -488  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.old: 1


[microbenchmarks] Performance differences noted:
Benchmark                                                          cpu_time    real_time
-----------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/256k                        +7%         +7%
BM_PumpStreamClientToServer<InProcess>/32k                         +4%         +4%
BM_PumpStreamClientToServer<InProcessCHTTP2>/32k                   +4%         +4%
BM_PumpStreamServerToClient<InProcess>/256k                        +13%        +13%
BM_PumpStreamServerToClient<InProcess>/32k                         +6%         +6%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32k  -7%         -7%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/256k       +4%         +4%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/256k/0       +5%         +5%
```

**Comment by markdroth** [comment]
Known failures: #11055 #12510 #12952 #12957 #12958 #12959 #12960 #12931 #12961 #12932 #12886 #12918 #12963 #12964 

The above line makes me incredibly sad.

**Pull request merged**
