### PR TITLE
Resolve a circular dependence in build

### PR DESCRIPTION
**Pull request by vjpai**
between create_test_channel.o and libgrpc++_test_util.a .

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Does this need to be adjusted in the BUILD file too ?

**Comment by vjpai** [comment]
The two sources that need to be manually edited are BUILD and build.yaml, correct? But BUILD doesn't have anything about test/cpp . Am I missing something?

**Comment by nicolasnoble** [comment]
Sorry, I meant, whichever BUILD file somewhere down the source tree that covers the same thing ? Or maybe we don't and then that's fine.

**Comment by vjpai** [comment]
Ok, I get it, thanks. Let me check.

**Comment by vjpai** [comment]
We're clear here because the issue was on test/cpp/interop (stress_test), which isn't yet covered by BUILD.

**Comment by vjpai** [comment]
Test failures: infrastructure on interop, and #9993

**Pull request merged**
