### PR TITLE
Making c-ares work under Windows.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Please note I have https://github.com/grpc/grpc/pull/12305 in review.

**Comment by nicolasnoble** [comment]
Yeah, that's independant. This PR is to actually hook event processing in so that cares is pumping bytes using gRPC's notifications.

**Comment by nicolasnoble** [comment]
Alright, all the relevant tests for this PR are passing at the moment, so I think this is reviewable now.

**Comment by y-zeng** [comment]
Thanks for adding the windows event driver! It looks great! I think we can enable this test https://github.com/grpc/grpc/blob/master/tools/run_tests/run_tests_matrix.py#L251 in this PR.

**Comment by nicolasnoble** [comment]
Good point, thanks, I'll mutate that script.

**Comment by markdroth** [comment]
Thanks for doing this!

---

Reviewed 18 of 20 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.c, line 37 at r3](https://reviewable.io:443/reviews/grpc/grpc/12416#-Ktr77CtE6JJzKtdnIH4:-Ktr77CtE6JJzKtdnIH5:b-5dicaw) ([raw file](https://github.com/grpc/grpc/blob/f060abc3aed658168e344cc641cad84afaf28309/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.c#L37)):*
> ```C
> #include "src/core/lib/support/string.h"
> 
> typedef struct fd_node {
> ```

General comment on this file: Although there is certainly some Windows-specific code here, there is also a lot of overlap with the existing posix driver.  Would it make sense to refactor somehow to avoid so much duplication?

Feel free to push back on this; I'm honestly not sure whether or not this makes sense.  I guess I'm just worried about the possibility of fixing a bug in one of the two files and then forgetting to update the other one.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.c, line 243 at r3](https://reviewable.io:443/reviews/grpc/grpc/12416#-Ktr6CGNuk_6BcDDuztP:-Ktr6CGNuk_6BcDDuztQ:b-6ej45s) ([raw file](https://github.com/grpc/grpc/blob/f060abc3aed658168e344cc641cad84afaf28309/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.c#L243)):*
> ```C
>           char *fd_name;
>           gpr_asprintf(&fd_name, "ares_ev_driver-%" PRIuPTR, i);
>           fdn = gpr_malloc(sizeof(fd_node));
> ```

Need a cast here due to impending C++ build.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.c, line 244 at r3](https://reviewable.io:443/reviews/grpc/grpc/12416#-Ktr6Mcd1rWaHftkfFTn:-Ktr6Mcd1rWaHftkfFTo:b-fk9e0s) ([raw file](https://github.com/grpc/grpc/blob/f060abc3aed658168e344cc641cad84afaf28309/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.c#L244)):*
> ```C
>           gpr_asprintf(&fd_name, "ares_ev_driver-%" PRIuPTR, i);
>           fdn = gpr_malloc(sizeof(fd_node));
>           gpr_log(GPR_DEBUG, "new socket: 0x%" PRIxPTR, (uintptr_t)socks[i]);
> ```

Does `%p` not work on Windows?

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.c, line 259 at r3](https://reviewable.io:443/reviews/grpc/grpc/12416#-Ktr6deE02FCUaG85e-s:-Ktr6deE02FCUaG85e-t:b-9zteo3) ([raw file](https://github.com/grpc/grpc/blob/f060abc3aed658168e344cc641cad84afaf28309/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.c#L259)):*
> ```C
>         new_list = fdn;
>         gpr_mu_lock(&fdn->mu);
>         // There's not a lot of good ways to poll sockets using the IOCP loop.
> ```

Maybe preface this comment with `TODO(nnoble):`, so that people know who the "I" in the comment refers to? :)

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.c, line 239 at r3](https://reviewable.io:443/reviews/grpc/grpc/12416#-Ktr3huwcvq89Jg6YND8:-Ktr3huwcvq89Jg6YND9:b-k8genu) ([raw file](https://github.com/grpc/grpc/blob/451b92a754900a800a7728a3d63462058026ac2c/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.c#L239)):*
> ```C
>       for (struct ares_srv_reply *srv_it = reply; srv_it != NULL;
>            srv_it = srv_it->next) {
>         if (grpc_ipv6_loopback_available()) {
> ```

Hmm... The extra lookups for the IPv6 records do add latency, so it probably does make sense to avoid them if we know that we don't have an IPv6 loopback address.  Is there a reasonable way to do that, maybe by implementing a dummy version of `grpc_ipv6_loopback_available()` on Windows?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/12416#-:-Ktr7_22O2ztC6Wovcwl:bxgavm9)*

**Comment by markdroth** [comment]
Might need to incorporate similar changes to the ones from #12631.

**Comment by dunkymole** [comment]
I am also keen for an update. I asked a couple of times on Gitter but I think it got lost in the noise. I have been setting expectations that it would be early Q1 of this year based on the last estimate. Its a blocker to going live for us.

**Comment by nicolasnoble** [comment]
Sorry for the delay, I'll look at landing this one shortly.

**Comment by PiRXlv** [comment]
Investigating using c-ares dns functionality on windows environment. Would be good if you could give at least rough idea of timelines here, please.

**Comment by dunkymole** [comment]
Hi guys. Any update on 'shortly'? Are we talking 1-3 months or 3-6? Sorry, I know I am being a bit 'chasey'

**Comment by dunkymole** [comment]
Hey. Seeing a bit of activity here which is encouraging. Is this still the correct PR to follow?

**Comment by dunkymole** [comment]
Hi. Bumping this thread. I am still super keen to know when this will land.

**Comment by Falco20019** [comment]
V1.15 was released yesterday and according to the release notes this should be part of it :)

**Comment by apolcyn** [comment]
@Falco20019 you are referring to https://github.com/grpc/grpc/pull/16163?

@dunkymole https://github.com/grpc/grpc/pull/15914 and https://github.com/grpc/grpc/pull/16420 make the c-ares resolver useable on Windows. Those PR's are merged but haven't made it into a release (they should be available in the [nightlies](https://packages.grpc.io/) though).

**Comment by dunkymole** [comment]
Exciting news @apolcyn. Thanks for the update!! :-)

**Comment by apolcyn** [comment]
@Falco20019 https://github.com/grpc/grpc/pull/15914 made c-ares usable on Windows back in August, and a follow-up localhost resolution fixed was merged not long after in #16420 (I looked through the release notes from back then and these PR's do seem to be missing from the release notes; sorry if that's confusing). So, you should be able to use c-ares on Windows starting from the 1.16.0 release, by running your binary under environment variable setting `GRPC_DNS_RESOLVER=ares`.... is this not currently working for you?

**Comment by Falco20019** [comment]
@apolcyn Thanks for the update. I watched this issue and it sounded like it’s just the first step and not already fully usable. Will try it with the environment variable then :)

**Comment by apolcyn** [comment]
@Falco20019 I should note that we are planning to use the c-ares DNS resolver by default in the upcoming 1.19 release. That is, the behavior of running under environment variable setting `GRPC_DNS_RESOLVER=ares` would become the default behavior - see the description of https://github.com/grpc/grpc/pull/17723#issue-244927932 for more details (also note from the description, the upcoming 1.19 release will contain a per-channel setting to enable SRV queries that defaults to off).

**Comment by jtattermusch** [comment]
Should this PR be closed?

**Pull request closed without merging**
