### PR TITLE
C# qps worker updates

### LINKED ISSUE #4992: C# performance benchmarks should ignore host field
PR #4960 removed the host option from the ServerConfig proto, and this should be reflected in the C# performance benchmarks.

### PR DESCRIPTION
**Pull request by jtattermusch**
-- regenerate C# .protos
-- Fixes #4992
-- implement CoreCount and QuitWorker rpcs.

### CODE REVIEW

**Comment by vjpai** [comment]
Overall, the new RPCs and related changes look good, but I do have a question. This applies to the pre-existing setup as well. Is there anything in place to prevent a worker from servicing more than 1 of its important RPC classes simultaneously? For example, in the C++ code there is a lock protecting each of the methods in WorkerServiceImpl so that you can only do 1 of RunClient, RunServer, or QuitWorker at any time (CoreCount can be done without the lock). I didn't see anything equivalent in the C# but maybe I'm wrong? It would be helpful to make sure that we don't accidentally fire off 2 sets of work at the same worker, or quit while it's still trying to operate.

**Comment by jtattermusch** [comment]
@vjpai  no, C# currently doesn't support such feature and I am not even sure if I like such feature to be introduced. There is so many more things that can go wrong with the performance testing that hardcoding such feature doesn't seem very useful.

**Comment by jtattermusch** [comment]
Fine to merge?

**Comment by vjpai** [comment]
What do you mean by "hardcoding" ? Can you think of a situation where you would want a single WorkerService to be simultaneously doing more than one of the above? Maybe there's an issue that I'm not seeing. Additionally, one of the intentions here is to make sure that quitting is sane.

**Pull request merged**
