### PR TITLE
Stream removal errors return UNAVAILABLE

### LINKED ISSUE #13800: Stream Removal Errors Should Return UNAVAILABLE
Allows for retries

### PR DESCRIPTION
**Pull request by ncteisen**
Fixes #13800

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +24  +0.0%

  [ = ]       0 TOTAL      +24  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by vjpai** [comment]
Tested?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%     +16 [None]                                                                               +56  +0.0%
  +0.0%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                          +16  +0.0%
      +5.5%     +16 removal_error(grpc_error*, grpc_chttp2_stream*, char const*) [clone .isra.2]         +16  +5.5%

  +0.0%     +32 TOTAL                                                                                +72  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                             cpu_time    real_time
--------------------------------------------------------------------  ----------  -----------
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/262144  +8%         +8%
```

**Pull request closed without merging**
