### PR TITLE
Move h2_ssl_cert_tests out of fixtures and shard them

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by vjpai** [comment]
This was terrible, actually. I should redo this and also pay attention to Bazel.

**Comment by ctiller** [comment]
If you convert the test to gtest (all tests ultimately will be converted to
gtest), then we can keep it one binary and have Bazel shard the testing
across machines. (This is a shift from what we've been doing because we
have a slightly fancier toolkit now)

**Comment by ctiller** [comment]
Talk to Nico for details

**Comment by vjpai** [comment]
After talking to @nicolasnoble, I think I need to go ahead with this change for now since the automatic sharding/etc won't be available for some time on all platforms. I'll rework this to be less ugly.

**Comment by ctiller** [comment]
We get automatic sharding with run_tests, and we'll get automatic sharding with whatever we switch to.

**Comment by jtattermusch** [comment]
CC @jtattermusch

**Comment by vjpai** [comment]
Yes, I am going to kill this and recreate it with gtest so that we get automatic sharding.

**Comment by vjpai** [comment]
Done properly in #12950

**Pull request closed without merging**
