### PR TITLE
Polymorphic delete support

### PR DESCRIPTION
**Pull request by nicolasnoble**
Enabling RTTI, and doing proper polymorphic deletion.

### CODE REVIEW

**Comment by markdroth** [comment]
Would this allow us to revert the work-around I added in #14888?

**Comment by nicolasnoble** [comment]
Maybe? I'd need to check exactly what you were after.

**Comment by markdroth** [comment]
Can you try reverting that change as part of this PR?  If all the tests pass, then it's probably no longer necessary.

**Comment by nicolasnoble** [comment]
So reverting #14888 isn't clean, as code changed around it in the meantime, which probably means we'd want a second PR to try and revert it.

I'd say let's get this one in, and we can work on seeing to revert #14888.

**Pull request merged**
