### PR TITLE
Refactor resolver result callback

### PR DESCRIPTION
**Pull request by markdroth**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/15896)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +264 [None]                                                                               +4.83Ki  +0.1%
  +7.5%     +99 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 +99  +7.5%
      [NEW]     +87 grpc_lb_addresses_contains_balancer_address                                              +87  [NEW]
       +14%     +12 [Unmapped]                                                                               +12   +14%

 -------------- SHRINKING                                                                            --------------
  -0.4%    -155 src/core/ext/filters/client_channel/client_channel.cc                                   -155  -0.4%
      [DEL]    -367 add_closure_for_subchannel_batch(grpc_call_element*, grpc_transport_stream_op_batch*    -367  [DEL]
      [DEL]    -197 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    -197  [DEL]
      -4.5%    -171 on_resolver_result_changed_locked                                                       -171  -4.5%
     -13.7%     -16 cc_get_channel_info                                                                      -16 -13.7%

  +0.0%    +208 TOTAL                                                                                +4.77Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +258 [None]                                                                               +5.06Ki  +0.1%
  +7.5%     +99 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 +99  +7.5%
      [NEW]     +87 grpc_lb_addresses_contains_balancer_address                                              +87  [NEW]
       +14%     +12 [Unmapped]                                                                               +12   +14%

 -------------- SHRINKING                                                                            --------------
  -0.3%    -117 src/core/ext/filters/client_channel/client_channel.cc                                   -117  -0.3%
      [DEL]    -367 add_closure_for_subchannel_batch(grpc_call_element*, grpc_transport_stream_op_batch*    -367  [DEL]
      [DEL]    -197 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    -197  [DEL]
      -3.5%    -133 on_resolver_result_changed_locked                                                       -133  -3.5%
     -13.7%     -16 cc_get_channel_info                                                                      -16 -13.7%

  +0.0%    +240 TOTAL                                                                                +5.05Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by AspirinSJL** [comment]
It looks much cleaner now! Thanks!

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 9 unresolved discussions (waiting on @markdroth and @dgquintas)

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 305 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGBX6Kv95fo_qx-27ZK:-LGBX6Kw2R_flxiLPdd_:bqelcpe) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L305)):*
> ```cpp
>   if (chand->resolver != nullptr) {
>     if (grpc_client_channel_trace.enabled()) {
>       gpr_log(GPR_INFO, "chand=%p: shutting down resolver", chand);
> ```

Maybe print `%p` of the resolver like we did when shutting down the LB policy.

But maybe we don't need this block at all. Since there are multiple "shutdown" steps (1. the dtor orphans the resolver/the disconnection op resets the resolver, 2. the resolver shuts itself down by cancelling the closure and unreffing itself, 3. the client channel optionally resets the resolver in the callback), the function name `on_resolver_shutdown_locked()` with this shutting down log is kind of confusing regarding the shutdown status. 

I think we can move the resetting of the resolver from here into `shutdown_resolver_locked()` to replace the `Orphan()` there. Then, resolver has started shutting down <=> `resolver == nullptr` => the callback can invoke `on_resolver_shutdown_locked()` to clean up the LB policy and its resolver-related closures (so step 3 is removed). The error of the closure is not important because it's always set after we reset the resolver. 

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 312 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGBYc9R6Q7GVTlFUi7V:-LGBYc9R6Q7GVTlFUi7W:byr6src) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L312)):*
> ```cpp
>       chand, GRPC_CHANNEL_SHUTDOWN,
>       GRPC_ERROR_CREATE_REFERENCING_FROM_STATIC_STRING(
>           "Got resolver result after disconnection", &error, 1),
> ```

We can reach here in two cases: one is after the channel data dtor, which causes the closure to be scheduled with an error; the other one is after the `disconnect_with_error` op, which resets the resolver (most likely also cancel the closure in time) and also sets the connectivity to `SHUTDOWN`. 

In the former case, the error message is inaccurate. We are just cancelling the closure. No resolver result has arrived, nor did we disconnect (at least not disconnect via `op->disconnect_with_error`).

In the latter case, it's possible that a race happens where the closure is scheduled with no error but we reset the resolver before the closure runs. But even that happens, do we want to set the channel connectivity to `SHUTDOWN` again with a new error message? I think we shouldn't, because the cause of the shutdown is `op->disconnect_with_error`, not that we still got a resolver result even after disconnection. A debug log should be enough.

It makes more sense to me to remove this connectivity update, and update the connectivity to `SHUTDOWN` in dtor instead, if that still matters.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 378 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGEJAf_7rBaRRYTb5yq:-LGEJAf_7rBaRRYTb5yr:b-51odi6) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L378)):*
> ```
> unset
> ```

"unchanged" might be more accurate.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 390 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGEPvyX1gXau0u94jHm:-LGEPvyX1gXau0u94jHn:b9otx9y) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L390)):*
> ```cpp
>       grpc_core::LoadBalancingPolicyRegistry::CreateLoadBalancingPolicy(
>           lb_policy_name, lb_policy_args);
>   if (GPR_UNLIKELY(new_lb_policy == nullptr)) {
> ```

If `chand->lb_policy != nullptr`, we should set `connectivity_state` and `connectivity_error` to some other reasonable value.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 439 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGD9KO1-EnBwH4nZTQG:-LGD9KO1-EnBwH4nZTQH:b2sfgx9) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L439)):*
> ```cpp
>   const grpc_arg* channel_arg =
>       grpc_channel_args_find(chand->resolver_result, GRPC_ARG_SERVICE_CONFIG);
>   char* service_config_json = grpc_channel_arg_get_string(channel_arg);
> ```

Can be `const char*`.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 477 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGE4JOm-6MPIGYvwHgc:-LGE4JOm-6MPIGYvwHgd:bxqw4m4) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L477)):*
> ```cpp
>   if (grpc_client_channel_trace.enabled()) {
>     gpr_log(GPR_INFO,
>             "chand=%p: got resolver result: resolver_result=%p error=%s", chand,
> ```

If there is an error, this log might be confusing, even though the error is printed. We'd better differentiate the causes of the invocation of this callback to be clear.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 481 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGE3U3FBBnc30IYX68M:-LGE3U3FBBnc30IYX68N:b308cdl) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L481)):*
> ```cpp
>   }
>   // Handle shutdown.
>   if (error != GRPC_ERROR_NONE || chand->resolver == nullptr) {
> ```

If we change line 305 to move the resetting of the resolver, `error != GRPC_ERROR_NONE` => `chand->resolver == nullptr` for the current code base. Although we might still want to check the error value to be safe.  

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 491 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGE6QgRB4yzdYFcQ0y_:-LGE6Pu_C6zrh3_tkm-Q:b-ii88dl) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L491)):*
> ```cpp
>       GRPC_ERROR_CREATE_FROM_STATIC_STRING("No load balancing policy");
>   // chand->resolver_result will be null in the case of a transient
>   // resolution error.  In that case, we don't have any new result to
> ```

Nit: duplicate space.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 492 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGE9JYx6fIDEdXMb0r_:-LGE9JYx6fIDEdXMb0ra:b-7zpzrz) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L492)):*
> ```cpp
>   // chand->resolver_result will be null in the case of a transient
>   // resolution error.  In that case, we don't have any new result to
>   // process, which means that we keep using the previous result (if any).
> ```

I don't see any place where the LB policies are watching the connectivity of the client channel. Is the connectivity watching generally in a bottom-up style. If so, is that related to that the shutdown control signal is passed top-down?

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 493 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGEKT6R7_M1BhH9dSod:-LGEKT6R7_M1BhH9dSoe:blh31dy) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L493)):*
> ```cpp
>   // resolution error.  In that case, we don't have any new result to
>   // process, which means that we keep using the previous result (if any).
>   if (chand->resolver_result == nullptr) {
> ```

If we don't receive any resolver result due to a resolver transient failure, but still have an LB policy in use, I don't think we need to set the connectivity to `GRPC_CHANNEL_TRANSIENT_FAILURE`. At least, the error shouldn't be "No load balancing policy".

Similar problem happens if we fail to create a new LB policy but there is an existing one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15896#-:-LGERN5572Nx4AKvq-u7:b8ep738)*

**Comment by markdroth** [comment]
Review status: all files reviewed, 9 unresolved discussions (waiting on @AspirinSJL, @markdroth, and @dgquintas)

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 305 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGBX6Kv95fo_qx-27ZK:-LGS6YJu36QmNc71hutB:bypp4e) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L305)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

Maybe print `%p` of the resolver like we did when shutting down the LB policy.

But maybe we don't need this block at all. Since there are multiple "shutdown" steps (1. the dtor orphans the resolver/the disconnection op resets the resolver, 2. the resolver shuts itself down by cancelling the closure and unreffing itself, 3. the client channel optionally resets the resolver in the callback), the function name `on_resolver_shutdown_locked()` with this shutting down log is kind of confusing regarding the shutdown status. 

I think we can move the resetting of the resolver from here into `shutdown_resolver_locked()` to replace the `Orphan()` there. Then, resolver has started shutting down <=> `resolver == nullptr` => the callback can invoke `on_resolver_shutdown_locked()` to clean up the LB policy and its resolver-related closures (so step 3 is removed). The error of the closure is not important because it's always set after we reset the resolver. 
</blockquote></details>

I've changed this to print the address of the resolver, although that's less important for the resolver than for the LB policy, since a given client channel will only ever have one resolver instance, whereas it may switch LB policy instances.

Note that there are actually two code paths for resolver shutdown.  In the code-path that you're referring to, the filter's `destroy_channel_elem()` method will only be called when the channel stack's refcount goes to zero, and we hold a ref to the channel stack whenever there is a pending resolver callback.  So the only way that `chand->resolver` can be non-null in `destroy_channel_elem()` is if the channel is destroyed without ever having started resolving, in which case the callback will never be invoked, and this function will never be called.  (Also, note that once `destroy_channel_elem()` returns, the channel data is freed, so no subsequent callback may access its fields; this is why we pass the resolver into `shutdown_resolver_locked()` and call `Orphan()` directly, because we can't access `chand->resolver` anymore at that point.)  I've added a comment about this in `destroy_channel_elem()`.

The other code path for resolver shutdown is the one in which this function will be used.  That is when the surface sends down a disconnect transport op (see handling of `op->disconnect_with_error` in `start_transport_op_locked()`, around like 579).  In that case, we reset `chand->resolver`, which invokes the resolver's `Orphan()` method, which shuts it down.  This causes the pending resolver callback to be invoked with an error, which is what triggers this code.  This code unrefs the channel stack (line 318 below), which will eventually cause `destroy_channel_elem()` to be called, but `chand->resolver` will already be null when it is.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 312 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGBYc9R6Q7GVTlFUi7V:-LGSAS_f4nYLOkAMkBgd:bb30cc3) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L312)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

We can reach here in two cases: one is after the channel data dtor, which causes the closure to be scheduled with an error; the other one is after the `disconnect_with_error` op, which resets the resolver (most likely also cancel the closure in time) and also sets the connectivity to `SHUTDOWN`. 

In the former case, the error message is inaccurate. We are just cancelling the closure. No resolver result has arrived, nor did we disconnect (at least not disconnect via `op->disconnect_with_error`).

In the latter case, it's possible that a race happens where the closure is scheduled with no error but we reset the resolver before the closure runs. But even that happens, do we want to set the channel connectivity to `SHUTDOWN` again with a new error message? I think we shouldn't, because the cause of the shutdown is `op->disconnect_with_error`, not that we still got a resolver result even after disconnection. A debug log should be enough.

It makes more sense to me to remove this connectivity update, and update the connectivity to `SHUTDOWN` in dtor instead, if that still matters.
</blockquote></details>

As mentioned above, we cannot actually reach this code after `destroy_channel_elem()` is called, so the only case here is the one triggered by the `disconnect_with_error` op.

I think you're right that it should not be necessary to reset the channel's connectivity state here.  I think it also should not ever be possible for `chand->resolver` to not be null here, because the resolver should never shut down until and unless we orphan it.  But I think it's better to leave that check in, just to be defensive against a bad resolver implementation.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 378 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGEJAf_7rBaRRYTb5yq:-LGVV-jL6jOy3BM-6O78:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L378)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

> ```
> unset
> ```

"unchanged" might be more accurate.
</blockquote></details>

Done.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 390 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGEPvyX1gXau0u94jHm:-LGS2uAzBHNwzV176dty:b-dna4no) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L390)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

If `chand->lb_policy != nullptr`, we should set `connectivity_state` and `connectivity_error` to some other reasonable value.
</blockquote></details>

See discussion below.  I deliberately kept the pre-existing behavior in this PR, but we can discuss whether this is the right thing to do.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 439 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGD9KO1-EnBwH4nZTQG:-LGVVDaJ9rr2FS63Efdl:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L439)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

Can be `const char*`.
</blockquote></details>

Done.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 477 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGE4JOm-6MPIGYvwHgc:-LGVWD4ACKSY34uFIzAO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L477)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

If there is an error, this log might be confusing, even though the error is printed. We'd better differentiate the causes of the invocation of this callback to be clear.
</blockquote></details>

Done.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 481 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGE3U3FBBnc30IYX68M:-LGVWIvs4zTYjzA3iaFh:bmg7qsd) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L481)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

If we change line 305 to move the resetting of the resolver, `error != GRPC_ERROR_NONE` => `chand->resolver == nullptr` for the current code base. Although we might still want to check the error value to be safe.  
</blockquote></details>

See above -- that change is not feasible, so we need this check to cover the race condition where the callback has been scheduled but not yet run when the resolver is shut down.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 491 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGE6QgRB4yzdYFcQ0y_:-LGVWU089iZjPDp0zB3O:bed271y) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L491)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

Nit: duplicate space.
</blockquote></details>

Sorry, I'm firmly in the two-space-after-period camp. :)

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 492 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGE9JYx6fIDEdXMb0r_:-LGVWbkE8xxFnurhfaMH:b-u1gab1) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L492)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

I don't see any place where the LB policies are watching the connectivity of the client channel. Is the connectivity watching generally in a bottom-up style. If so, is that related to that the shutdown control signal is passed top-down?
</blockquote></details>

I don't quite understand the question.

Connectivity state notifications always flow up the stack.  The LB policies watch the connectivity state of the subchannels and report an aggregated state to the client channel, which propagates it up to the surface.

The shutdown process does run top-down, though.  When that happens, we set the client channel's connectivity state to SHUTDOWN directly, without waiting for an update from the LB policy.  Any subsequent notifications from the LB policy should just wind up resetting it to the same thing.

---

*[src/core/ext/filters/client_channel/client_channel.cc, line 493 at r2](https://reviewable.io/reviews/grpc/grpc/15896#-LGEKT6R7_M1BhH9dSod:-LGVXjnx3CHY4p_fKdNH:b38ial1) ([raw file](https://github.com/grpc/grpc/blob/6a8afa43bfc30089f3096de9fa42d101e8095a13/src/core/ext/filters/client_channel/client_channel.cc#L493)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

If we don't receive any resolver result due to a resolver transient failure, but still have an LB policy in use, I don't think we need to set the connectivity to `GRPC_CHANNEL_TRANSIENT_FAILURE`. At least, the error shouldn't be "No load balancing policy".

Similar problem happens if we fail to create a new LB policy but there is an existing one.
</blockquote></details>

I noticed this when working on this PR, and I agree that this behavior seems questionable.  However, this was the behavior of the existing code, and I was reluctant to change it, since I don't know what might break.  Also, it does seem like we should do *something* to indicate that there's a problem, because these are situations where the client would actually fail if it gets restarted and does not have a pre-existing LB policy to use.  But perhaps this calls for a bit of discussion.

@ejona86 and @dfawley, what do Java and Go do in these situations?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15896)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +274 [None]                                                                               +5.28Ki  +0.1%
  +7.5%     +99 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 +99  +7.5%
      [NEW]     +87 grpc_lb_addresses_contains_balancer_address                                              +87  [NEW]
       +14%     +12 [Unmapped]                                                                               +12   +14%

 -------------- SHRINKING                                                                            --------------
  -0.2%     -69 src/core/ext/filters/client_channel/client_channel.cc                                    -69  -0.2%
      [DEL]    -367 add_closure_for_subchannel_batch(grpc_call_element*, grpc_transport_stream_op_batch*    -367  [DEL]
      [DEL]    -197 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    -197  [DEL]
      -2.2%     -85 on_resolver_result_changed_locked                                                        -85  -2.2%
     -13.7%     -16 cc_get_channel_info                                                                      -16 -13.7%

  +0.0%    +304 TOTAL                                                                                +5.30Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ejona86** [comment]
Avoiding reviewable because I don't want to give it permissions to all my repositories to respond with a comment.

> @ejona86 and @dfawley, what do Java and Go do in these situations?

Java propagates any failures to the LB policy, and lets it decide what to do. Pick First appears to start failing all RPCs with the NR's failure. Round Robin continues using the old subchannels until they are all in TRANSIENT_FAILURE, at which time it propagates the NR's failure. gRPCLB appears to generally ignore the failure, but will use it if it has no channels _at that precise moment_.

I think our Round Robin is doing close to the right thing here, but it would be nice to expose the failures a bit more prominently.

**Comment by markdroth** [comment]
Interesting.  Is it really the right thing to do to let the LB policy decide how to handle the error, given that the resolver result might have caused us to switch to a new LB policy?  This is particularly relevant in the second case we're talking about here, which is when we get a valid resolver result but fail to create the new LB policy for some reason.

**Comment by ejona86** [comment]
> which is when we get a valid resolver result but fail to create the new LB policy for some reason.

... like what sort of reason? Generally, for us failing to create a LB policy is a "very bad thing" and we go into a "we are very broken; kill RPCs, forever" state.

Do you mean the service config chose a non-existent LB policy? That would have to happen before the discussed failure, in Java, as the resolver can only return a service config on success.

**Comment by dfawley** [comment]
> This is particularly relevant in the second case we're talking about
here, which is when we get a valid resolver result but fail to create the
new LB policy for some reason

Instantiating the balancer is a distinct step from getting a result from
the resolver, in Go at least.

Go has a problem, currently, where the resolver can't return an error back
to grpc.  Once it does, we will plumb that through to the balancer (we
already have a place in the balancer API for it), and then we'll be the
same as Java (dependent on balancer behavior).

**Comment by markdroth** [comment]
> > which is when we get a valid resolver result but fail to create the new LB policy for some reason.
> 
> ... like what sort of reason? Generally, for us failing to create a LB policy is a "very bad thing" and we go into a "we are very broken; kill RPCs, forever" state.
> 
> Do you mean the service config chose a non-existent LB policy? That would have to happen before the discussed failure, in Java, as the resolver can only return a service config on success.

So it's the resolver's job to check that the specified LB policy actually exists, and if it doesn't, then you have the resolver return a failure?  It seems weird to push that responsibility into the resolver.

Currently, in C-core, the resolver just returns the specified LB policy name to the client channel, and the client channel tries to instantiate the named policy.  If that fails, either because the named policy doesn't exist or because the policy's factory returned null (e.g., if the grpclb policy is selected but there are no balancer addresses), then we need to figure out how to handle it.

In any case, regardless of how the code is laid out, it sounds like you're saying that if the resolver gets a service config with a non-existent LB policy name, you will have the resolver return an error and send that error to the currently existing LB policy?  Doesn't that seem weird, given that it's not really the current LB policy that had anything to do with that error?

**Comment by ejona86** [comment]
>> Do you mean the service config chose a non-existent LB policy? That would have to happen before the discussed failure, in Java, as the resolver can only return a service config on success.
>
> So it's the resolver's job to check that the specified LB policy actually exists, and if it doesn't, then you have the resolver return a failure? It seems weird to push that responsibility into the resolver.

No. The resolver returns (in the service config) which LB policy to select. But it can only return that on a successful resolution. If the LB policy doesn't exist, then we deal with it in one way or another (fallback to a default, use "always-fail" LB policy, etc).

The point is that if we subsequently get a name resolution failure, we would already have an LB policy in place.

**Comment by markdroth** [comment]
> No. The resolver returns (in the service config) which LB policy to select. But it can only return that on a successful resolution. If the LB policy doesn't exist, then we deal with it in one way or another (fallback to a default, use "always-fail" LB policy, etc).

That "one way or another" is one of the things I'm asking about.  What exactly do you do if the resolver returns an LB policy name that does not exist?  Do you stick with the existing LB policy if you have one?  Or do you switch to an "always fail" policy?  Or something else?  And do you change the channel's connectivity state at all?

> The point is that if we subsequently get a name resolution failure, we would already have an LB policy in place.

Okay.  This still seems a bit odd to me, though, since the name resolution failure doesn't really have anything to do with the LB policy.  What's the motivation for pushing this into the LB policy vs. handling it directly in the client channel?

In your RR implementation, where it keeps using the existing subchannels, does it change the channel's connectivity state to reflect that there was a name resolution error?  Or is the error effectively invisible to the application?

**Comment by ejona86** [comment]
> The only two reasonable ideas to me are to: use a "always fail" policy or use a "default" fallback policy.

Actually, thinking about this more, "always fail" is not acceptable as it prevents safely enabling new LB policies. It seems the two should be: consider the service config broken and use a default fallback policy (it seems pick first), or consider the service config broken and fallback to the old service config (and if there isn't an older one, we'd choose the default, pick first).

Falling back to an old service config is, IIRC, the behavior we are trying to use elsewhere. But this may be a pretty "late" verification step since it is a dynamic check. But this goes back to service config validation and error handling.

**Comment by markdroth** [comment]
Yeah, I was just going to make the same comment about the service config.  It seems like sticking with the old LB policy would actually be consistent with our plan for handling invalid service configs.

I'd still like a reply to the questions I asked above about how Java handles transient resolver failures.  In particular, what was the motivation for moving the error handling of those cases into the LB policy?  And does your RR implementation change the channel's connectivity state to reflect the error, or is the error basically invisible to the application?

**Comment by ejona86** [comment]
> In particular, what was the motivation for moving the error handling of those cases into the LB policy?

If we don't send it to the LB policy, and previously there was a successful resolution, it would be going to /dev/null. Not sending it to /dev/null seemed a good idea. The LB is in a position to use the information in cases where it determines things look bad (like all its connections have died). Although I considered this still an open problem, because it may be a _long_ time before the client is notified things have deteriorated.

> And does your RR implementation change the channel's connectivity state to reflect the error, or is the error basically invisible to the application?

It changes the connectivity state. Changing the connectivity state is part of updating to produce new pick decisions.

**Comment by markdroth** [comment]
Okay, here's what I think you're saying:

- When a transient resolver error occurs, RR will stash the error internally for later use, but it will not immediately change the connectivity state or change pick decisions if it still has existing reachable subchannels.

- Once all of its subchannels go bad, it will set the channel's connectivity state to TRANSIENT_FAILURE and return the previously stashed error from the resolver for all picks.

This implies that if there is a long period of time between those two events, the failure mode is invisible to the application.

Do I have that right?

**Comment by markdroth** [comment]
@AspirinSJL, I think we'll need to have further discussions about what the right behavior is in these cases.  However, this PR does not change the existing behavior for these cases, so let's not block this PR on that discussion.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +234 [None]                                                                               +4.56Ki  +0.1%
  +7.5%     +99 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 +99  +7.5%
      [NEW]     +87 grpc_lb_addresses_contains_balancer_address                                              +87  [NEW]
       +14%     +12 [Unmapped]                                                                               +12   +14%

 -------------- SHRINKING                                                                            --------------
  -0.4%    -149 src/core/ext/filters/client_channel/client_channel.cc                                   -149  -0.4%
      [DEL]    -367 add_closure_for_subchannel_batch(grpc_call_element*, grpc_transport_stream_op_batch*    -367  [DEL]
      [DEL]    -197 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    -197  [DEL]
      [DEL]    -106 shutdown_resolver_locked                                                                -106  [DEL]
      -2.2%     -85 on_resolver_result_changed_locked                                                        -85  -2.2%
     -13.7%     -16 cc_get_channel_info                                                                      -16 -13.7%
      -1.6%      -6 [Unmapped]                                                                                -6  -1.6%

  +0.0%    +184 TOTAL                                                                                +4.52Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +234 [None]                                                                               +4.56Ki  +0.1%
  +7.5%     +99 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 +99  +7.5%
      [NEW]     +87 grpc_lb_addresses_contains_balancer_address                                              +87  [NEW]
       +14%     +12 [Unmapped]                                                                               +12   +14%

 -------------- SHRINKING                                                                            --------------
  -0.4%    -149 src/core/ext/filters/client_channel/client_channel.cc                                   -149  -0.4%
      [DEL]    -367 add_closure_for_subchannel_batch(grpc_call_element*, grpc_transport_stream_op_batch*    -367  [DEL]
      [DEL]    -197 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    -197  [DEL]
      [DEL]    -106 shutdown_resolver_locked                                                                -106  [DEL]
      -2.2%     -85 on_resolver_result_changed_locked                                                        -85  -2.2%
     -13.7%     -16 cc_get_channel_info                                                                      -16 -13.7%
      -1.6%      -6 [Unmapped]                                                                                -6  -1.6%

  +0.0%    +184 TOTAL                                                                                +4.52Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: #14268 #16003 #16004

**Pull request merged**
