### PR TITLE
Revert "Enable C++ standard library"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#19918

- size increase in artifacts that needs to be investigated
- broken distribtests

### CODE REVIEW

**Comment by veblush** [comment]
Can I fix the problem without having rollback because it only affect the distribtests? If I cannot fix the problem today, I will rollback it.

**Comment by veblush** [comment]
PHP Fix is in progress: #20169

**Comment by veblush** [comment]
PHP Fix is merged: #20169
iOS size increase is not caused by the PR.

**Comment by veblush** [comment]
I think this can be closed since php fix is merged and iOS size is not relevant.

**Comment by jtattermusch** [comment]
How about the C# nuget size decrease that I reported in the first place? Doubling the size of an already big nuget is not acceptable.

**Comment by jtattermusch** [comment]
Ah, I didn't see the note about https://github.com/grpc/grpc/pull/20113 causing the size increase of nugets. Thanks for rootcausing the issue.

**Pull request closed without merging**
