### PR TITLE
DO NOT REVIEW - copy of https://github.com/grpc/grpc/pull/17110

### PR DESCRIPTION
**Pull request by nlopezgi**
attn: @billfeng327 

DO NOT REVIEW
this is a copy of https://github.com/grpc/grpc/pull/17110 to help @billfeng327 debug the current issues with multipool config.

Sample passing run:
https://source.cloud.google.com/results/invocations/1162dee4-c602-424c-9327-d562371f4865

toolchain / Platform flags I used:
```
--crosstool_top=@com_github_bazelbuild_bazeltoolchains//configs/debian8_clang/0.4.0/bazel_0.16.1/default:toolchain
--extra_execution_platforms=//third_party/toolchains:rbe_ubuntu1604,//third_party/toolchains:rbe_ubuntu1604_large 
--host_platform=//third_party/toolchains:rbe_ubuntu1604 
--platforms=//third_party/toolchains:rbe_ubuntu1604,//third_party/toolchains:rbe_ubuntu1604_large 
--extra_toolchains=@com_github_bazelbuild_bazeltoolchains//configs/ubuntu16_04_clang/1.1/bazel_0.16.1/cpp:cc-toolchain-clang-x86_64-default
```

I honestly don't know what is wrong in your PR, or how you are running this as the only difference I can see now is in the extra properties (which I cannot have as I don't have pools with those properties set) and the fact that I'm using bazel 0.19.0 (you might be using an older version?)

### CODE REVIEW

**Comment by jtattermusch** [comment]
@nlopezgi   someone from gRPC team needs to add "kokoro:run" label to get a test run. I did so just now, @billfeng327  can do that for next runs you'll need.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
