### PR TITLE
Make native nuget packages VS2015 ready 

### PR DESCRIPTION
**Pull request by jtattermusch**
-- upgrades openssl nuget package to 1.0.2d
-- make openssl, zlib, and csharp.native.ext packages VS2015 ready
-- include 64bit builds of openssl and zlib in the native packages

-- when native nuget packages are used in a managed C# project, improve the autodetection of what version of .dll gets copied to the output directory (autodetect VS version and try to detect Debug/Release configuration).

As of now, tests for this PR will fail because the new nuget packages for openssl and zlib haven't been uploaded yet (i'll upload them once I get preliminary LGTM for this PR).

The commit "regenerate project files" contains tons of autogenerated .vsxproj files, so I recommend reviewing this PR commit-by-commit.

### CODE REVIEW

**Comment by ctiller** [comment]
These are autogenerated files. Please update the template.

**Comment by jtattermusch** [comment]
@ctiller , not sure I follow.  Generated files changed as a result of updating openssl and zlib version in build.yaml.

**Comment by ctiller** [comment]
Oh... I read your commit message as visual studio had done that thing where
it rewrites a bunch of projects for you.

**Comment by ctiller** [comment]
IOW: never mind me

**Comment by jtattermusch** [comment]
Ok, as expected, mergin this PR probably breaks everything on windows as the new nuget packages haven't been uploaded yet (I was waiting for the feedback from review so I have chance to adjust things).

So I will try to upload the packages ASAP today.

**Comment by jtattermusch** [comment]
Just uploaded new version of grpc.dependencies.openssl.* and grpc.dependencies.zlib.* packages, so things should be fine now.

**Comment by nicolasnoble** [comment]
Ah, sorry.

**Pull request merged**
