### PR TITLE
Remove g-stands-for from user agent string

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/16630 and ends a long debate.

The main argument is that sending useless bytes around is wasteful.

### CODE REVIEW

**Comment by vjpai** [comment]
Sorry for the delayed review. LGTM.

**Comment by vjpai** [comment]
Any conclusion on this? It still isn't merged.

**Comment by jtattermusch** [comment]
Looks like I'll have to fix some of the tests and I still haven't gotten to it. I'll re-run the tests and see what I can do.

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/22650

**Comment by jtattermusch** [comment]
after a bit of digging, I found this error message (objC test logs are very difficult to read).
https://source.cloud.google.com/results/invocations/e1a622b7-c876-45d0-b99e-16fda6b31d60/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fmac-test-basictests/tests

```
Tue Apr 14 04:33:01 PDT 2020 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/objective-c/tests/UnitTests/APIv2Tests.m:244: error: -[CallAPIv2Tests testUserAgentPrefix] : ((userAgent) equal to (expectedUserAgent)) failed: ("Foo grpc-objc/1.29.0-dev grpc-c/10.0.0 (osx; chttp2)") is not equal to ("Foo grpc-objc/1.29.0-dev grpc-c/10.0.0 (osx; chttp2; gringotts)")
Tue Apr 14 04:33:01 PDT 2020 - Test Case '-[CallAPIv2Tests testUserAgentPrefix]' failed (0.009 seconds).
```

**Comment by jtattermusch** [comment]
@muxi  I had to update some of ObjC's tests - can you please check that what I've done is correct?
I've also ran into this comment:
```
// Change in format of user-agent field in a direction that does not match the regex will
// likely cause problem for certain gRPC users. For details, refer to internal doc
// https://goo.gl/c2diBc
```
so I'd like to doublecheck my change is fine (I checked the regex and it should be, but I don't have much background here).

**Comment by jtattermusch** [comment]
@muxi can you please check with YT and post a comment here once PR once is safe to merge?
(btw, grpc-java and grpc-go already produce user agent string without the g_stands_for string and the regex in the objc test works both for the new and old version of the user agent string produced by C-core - I am not sure if that's sufficient for YT's needs).

**Comment by muxi** [comment]
Did that. I'll merge it when I got an update

**Comment by muxi** [comment]
YT side is cleared. 

Test failure is known: #22691

Merging.

**Pull request merged**
