### PR TITLE
Python bindings changes for server SSL credentials reload

### PR DESCRIPTION
**Pull request by cauthu**
NOT READY for merge

this depends on @justinburke 's https://github.com/grpc/grpc/pull/12644

the python test is actually not part of this PR; will create a separate PR for it.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by cauthu** [comment]
@justinburke do you think we can ask folks who own the python bindings to take a quick look at the overall approach of this PR and give feedback? with the understanding that this is still slightly in flux because your PR #12644  might still change.

**Comment by justinburke** [comment]
Hi @nathanielmanistaatgoogle mind checking out this PR?

**Comment by nathanielmanistaatgoogle** [comment]
@justinburke will try to look at it in the next few days.

**Comment by nathanielmanistaatgoogle** [comment]
In the meantime: we prefer tests to be included in the same pull request as added features (not necessarily the same commit, but that's fine too) and in the gRPC Python subcodebase we maintain [this standard](https://chris.beams.io/posts/git-commit/#seven-rules) for commit log messages.

**Comment by cauthu** [comment]
> we prefer tests to be included in the same pull request as added features

sounds good. Justin and i had thought maybe including the test would make the PR slightly harder to review. i will include the test here and close #12691

**Comment by cauthu** [comment]
i've updated the commit messages and added the test in this PR. thanks!

**Comment by cauthu** [comment]
@nathanielmanistaatgoogle #12644 is likely going to go through non-trivial changes that will affect this PR, so please don't look at this PR yet

**Comment by nathanielmanistaatgoogle** [comment]
@cauthu: I sort of suspected that it would and have been keeping my relationship with this pull request pretty casual for the time being.

**Comment by cauthu** [comment]
@nathanielmanistaatgoogle curious: once PR #12644 merges (i think it's almost there), how soon will you have time to work on python support? if it's a week or two, then i'd probably just leave it to you.... if it's three or more, then i probably want to take a stab and create a PR for you to review :)

also, another question, say, once the python changes merge, how soon afterwards can we push out a pypi update :)?

thanks!

**Comment by nathanielmanistaatgoogle** [comment]
@cauthu: this... is a pull request? It's already one that you created, that I am under the impression I will review after the merge of [pull request 12644](https://github.com/grpc/grpc/pull/12644)?

**Comment by cauthu** [comment]
yea, was just thinking maybe you guys desired to add this feature, too, then you would also want to implement it :)
i guess i will have to do it then, since i want it the sooner the better :)

**Comment by cauthu** [comment]
created new PR #13140 which should be cleaner. closing this one.

**Pull request closed without merging**
