### PR TITLE
Revert "Use the RECV_STATUS op in ALTS handshake RPCs"

### PR DESCRIPTION
**Pull request by hcaseyal**
Reverts grpc/grpc#20929 and is a workaround for https://github.com/grpc/grpc/issues/21142

### CODE REVIEW

**Comment by hcaseyal** [comment]
I misread the issue about this being a probable root cause and not a definite root cause. After the tests finish running, we should see if this revert fixes the failures

**Comment by apolcyn** [comment]
The test that's failing is a test that was added in #21142 itself, so it's a definite root cause. I can reproduce the failure locally (oddly, reproduces with the `make` build, but not bazel RBE), but it will take some more time to root cause.

**Comment by apolcyn** [comment]
added more details in https://github.com/grpc/grpc/issues/21142

This revert is still good to unbreak master before the fix

**Comment by hcaseyal** [comment]
Merged the fix forward in https://github.com/grpc/grpc/pull/21193, so closing this PR

**Pull request closed without merging**
