### PR TITLE
Revert "Revert "grpc_cli json support""

### PR DESCRIPTION
**Pull request by yang-g**
Reverts grpc/grpc#16902

### CODE REVIEW

**Comment by dgquintas** [comment]
Is there a commit adding something to the revert?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by yang-g** [comment]
No. This should be a clean revert.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,966,317      Total (=)      1,966,317

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,771      Total (=)     10,909,771

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
@dgquintas ping~

**Comment by dgquintas** [comment]
If this is a clean revert, how is it going to prevent the issues I faced during the import?

**Comment by yang-g** [comment]
Because I fixed it internally :), see 217759704

**Comment by dgquintas** [comment]
ah, sneaky...

**Pull request merged**
