### PR TITLE
Fix uninitialized variable in workaround_cronet_compression_filter

### PR DESCRIPTION
**Pull request by muxi**
Fixes warning generated on Mac Sierra.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                FILE SIZE
 ++++++++++++++ GROWING                                                                  ++++++++++++++
  +0.0%     +16 [None]                                                                      +376  +0.0%
  +9.1%     +80 src/core/ext/filters/workarounds/workaround_cronet_compression_filter.cc     +80  +9.1%
       +16%     +73 parse_user_agent                                                             +73   +16%
       +11%      +7 [Unmapped]                                                                    +7   +11%

  +0.0%     +96 TOTAL                                                                       +456  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                      cpu_time    real_time
---------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/262144  -5%         -5%
BM_PumpStreamClientToServer<InProcess>/32768   -5%         -5%
```

**Comment by muxi** [comment]
Failures are known errors.

**Pull request merged**
