### PR TITLE
Cleanup configuration of bazel RBE jobs

### PR DESCRIPTION
**Pull request by jtattermusch**
Followup for https://github.com/grpc/grpc/pull/29353

- cleanup and simplify .cfg and .sh files for linux bazel RBE jobs (make use of env variables instead of helper .sh scripts)
- enable uploading of XML report artifacts for selected bazel jobs (the idea is to enable the bazel_report_helper.py reports to show up in resultstore/sponge).
- use "respawn in moved src tree" for linux bazel RBE jobs (to speed up job finalization).

### CODE REVIEW

**Comment by jtattermusch** [comment]
Bazel C++ iOS bazel report: https://source.cloud.google.com/results/invocations/303bc042-6e79-4ea4-9d3f-233aac2995f0/targets (from adhoc test run).

**Comment by jtattermusch** [comment]
@lidizheng  this is now ready for review.

**Review by lidizheng — APPROVED** [review]
LGTM to the script structure changes. Can you also ask a C++ team member to review? So they will be aware of the change.

**Comment by jtattermusch** [comment]
> LGTM to the script structure changes. Can you also ask a C++ team member to review? So they will be aware of the change.

CC @veblush  for visibility. 
I feel like this change is pretty noncontroversial (it's just moving config args around), so I don't think we need extra pair of eyes to formally review.
As a side effect, this change also fixes the problem introduced by https://github.com/grpc/grpc/pull/29353 (thus superseding https://github.com/grpc/grpc/pull/29387),
and since this change is already approved, I think I'm going to merge once I doublecheck that it actually fixes the broken tests on master.

**Comment by jtattermusch** [comment]
Adhoc run of grpc/core/master/linux/bazel_rbe/grpc_bazel_rbe_opt job (to see if this PR fixes the breakage currently on master): https://source.cloud.google.com/results/invocations/fdb3c227-6f80-4cfb-8d44-0438c4291329

**Comment by jtattermusch** [comment]
Merging to fix b/229025694

**Pull request merged**
