### PR TITLE
PHP: use php7_wrapper to reduce duplicated codes on v1.0.x branch(final part)

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Please merge in changes from `v1.0.x` branch. That will enable PHP7 tests to be run on Jenkins (which I will enable later)

**Comment by stanley-cheung** [comment]
LGTM. This PR looks good. All relevant tests including PHP7 ones passed. But I'd like to see what's going on with `master` before merging this. 

Is there anything else you want to do on this? I'd like to lock down the `v1.0.x` branch soon. Any new change should only go onto `master` after this. OK?

**Comment by stanley-cheung** [comment]
There's compilation error:
```
/var/local/git/grpc/src/php/ext/grpc/call.c: In function 'create_metadata_array':
/var/local/git/grpc/src/php/ext/grpc/call.c:153:9: error: variable 'key' set but not used [-Werror=unused-but-set-variable]
   char *key = NULL;
         ^
/var/local/git/grpc/src/php/ext/grpc/call.c: In function 'zim_Call_startBatch':
/var/local/git/grpc/src/php/ext/grpc/call.c:299:9: error: variable 'key' set but not used [-Werror=unused-but-set-variable]
   char *key = NULL;
         ^
cc1: all warnings being treated as errors
make: *** [call.lo] Error 1
Makefile:196: recipe for target 'call.lo' failed
```

**Comment by thinkerou** [comment]
I change `char *key = NULL` to `char *key`, the problem can solve? Because it run right on local.

**Comment by stanley-cheung** [comment]
I can reproduce the error when I run `make` on linux

**Comment by stanley-cheung** [comment]
I see what the problems are. But it seems trickly to solve...

**Comment by stanley-cheung** [comment]
Ok, I added a couple of `efree(key)` statement at the end of their functions and it got rid of the compilation error. But then unit tests failed with
```
Starting test 'CallCredentials2Test::testCreateFromPlugin'.
F
Starting test 'CallCredentials3Test::testCreateFromPlugin'.
F
Starting test 'CallCredentialsTest::testCreateFromPlugin'.
E0727 20:58:14.117990636   18224 hpack_encoder.c:374]        assertion failed: GPR_SLICE_LENGTH(elem->key->slice) > 0
./bin/run_tests.sh: line 41: 18224 Aborted                 php $extension_dir -d max_execution_time=300 $(which phpunit) -v --debug ../tests/unit_tests
```

**Comment by stanley-cheung** [comment]
You will need the `fix unused var` commit in this branch as well

**Comment by thinkerou** [comment]
Yes, done.

**Comment by thinkerou** [comment]
Hi @stanley-cheung now you should review the PR again and merge it, I will not commit code in the PR commits. Thanks.

**Comment by stanley-cheung** [comment]
LGTM. All relevant tests passed. I will fix the nits in a separate PR. I have a few other minor things I want to fix.

**Pull request merged**
