### PR TITLE
Backport merge.

### PR DESCRIPTION
**Pull request by nicolasnoble**
As discussed, if we want to ease the publication of 0.13.1 later on.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
This is basically git merge master done in the 0.13 branch. No conflict whatsoever. Only thing changed from master is the version.

**Comment by nicolasnoble** [comment]
@soltanmm: this is the scorched earth method for your issue.

**Comment by jtattermusch** [comment]
LGTM

**Comment by nicolasnoble** [comment]
@ctiller:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (log.o) in output file used for input files: /jenkins/workspace/gRPC_pull_requests/config/dbg/language/c/platform/macos/objs/dbg/src/core/census/log.o and: /jenkins/workspace/gRPC_pull_requests/config/dbg/language/c/platform/macos/objs/dbg/src/core/support/log.o (due to use of basename, truncation, blank padding or duplicate input files)
```

**Comment by nicolasnoble** [comment]
Pushed various fixes for MacOS on master, and merged here. Let's see.

**Comment by nicolasnoble** [comment]
Things are looking good.

**Comment by nicolasnoble** [comment]
`Slave went offline during the build`. Seriously ? https://grpc-testing.appspot.com/computer/grpc-mac-node2/log

**Comment by nicolasnoble** [comment]
Started a replacement build at #6394.

**Comment by nicolasnoble** [comment]
Alright, that was almost green, minus a test timeout. Merging.

**Pull request merged**
