### PR TITLE
Revert "Add owners file for tools/run_tests/"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#14355

### CODE REVIEW

**Comment by jtattermusch** [comment]
Feel free to merge as soon as the tests pass.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
