### PR TITLE
move grpc_assert_never_ok out of extern C block

### PR DESCRIPTION
**Pull request by yashykt**
move grpc_assert_never_ok out of extern C block

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%     +32 [None]     +88  +0.0%

  +0.0%     +32 TOTAL      +88  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
This should not be required any longer. clossing the PR

**Pull request closed without merging**
