### PR TITLE
Revert "Revert "Transport channel arg""

### PR DESCRIPTION
**Pull request by ctiller**
Reverts grpc/grpc#28818

Will cherry pick across this time!

### CODE REVIEW

**Review by markdroth — APPROVED** [review]

**Comment by markdroth** [comment]
I don't understand that last commit.  It looks like there are now some unrelated changes here?

**Comment by ctiller** [comment]
Symptom of how I merged with head... no actual changes

**Comment by ctiller** [comment]
(due to this being a pr on grpc/grpc, not ctiller/grpc)

**Comment by ctiller** [comment]
Used a bigger hammer, should be clean now.

**Comment by markdroth** [comment]
Looks good.  Thanks!

**Pull request merged**
