### PR TITLE
Upload test results to BQ in batches

### PR DESCRIPTION
**Pull request by jtattermusch**
- Uploading generates huge amount of logs:  the `URL being requested: ...` line is logged for each row uploaded.
- Uploading row by row is not very efficient (upload itself can take ~3mins).

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Known flakes: https://github.com/grpc/grpc/issues/15599

**Comment by jtattermusch** [comment]
After merging, I will double check that the test results are being uploaded correctly.

**Pull request merged**
