### PR TITLE
Remove channelz from LB policy API.

### PR DESCRIPTION
**Pull request by markdroth**
This also significantly simplifies the channelz node creation code.  And it addresses the lock-inversion failure that is preventing #18496 from being merged.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/19066)

### CODE REVIEW

**Comment by markdroth** [comment]
This is now ready for review.

**Comment by markdroth** [comment]
This is now based on #19202.

**Comment by markdroth** [comment]
It looks like I've accidentally introduced a deadlock in the channelz code.  I've run out of steam for today, but I'll work on this more on Monday.

**Comment by markdroth** [comment]
This is now based on #19244 instead of #19202.

I think this is once again ready for review.

**Comment by markdroth** [comment]
The dependent PR has been merged, so the only changes here are now the ones from this PR itself.

**Comment by AspirinSJL** [comment]
I will review this PR today.

**Comment by markdroth** [comment]
Thanks!

**Comment by markdroth** [comment]
@veblush, you may want to review the changes to the channelz API here.

**Comment by markdroth** [comment]
Known issues: #18416 #17007

**Pull request merged**
