### PR TITLE
Used the proper GRPC_TRACE value in run_tests.py

### PR DESCRIPTION
**Pull request by murgatroid99**

### CODE REVIEW

**Comment by ctiller** [comment]
Please give this a few runs through Jenkins to catch any flakiness introduced by additional logging.

**Comment by soltanmm** [comment]
@ctiller A'ight.

As far as the change is concerned, LGTM.

**Comment by murgatroid99** [comment]
It looks like this caused the C# tests and possibly the Python dbg test to time out.

**Comment by soltanmm** [comment]
The Python timeout might just be related to #3577/#3585... Still need to get to those.

**Comment by murgatroid99** [comment]
That C# timeout looks very consistent, and the Python timeout happens about half the time.

**Comment by murgatroid99** [comment]
Jenkins is now green.

**Pull request merged**
