### PR TITLE
Clean up a core test

### LINKED ISSUE #5746: Cleanup related to few outstanding comments on PR #5731
PR #5731 should be allowed to be merged since it is solving a critical race. Code review only turned up a few very minor glitches, and those should be resolved after the merge. You can assign me as a reviewer in processing those.

### PR DESCRIPTION
**Pull request by soltanmm**
Depends on #5731 

Fixes #5746

### CODE REVIEW

**Comment by vjpai** [comment]
Now that #5731 is merged, please remerge master...

**Comment by soltanmm** [comment]
Addressed.

**Comment by vjpai** [comment]
LGTM.

**Comment by vjpai** [comment]
Please clang_format

**Comment by soltanmm** [comment]
@vjpai Woops, forgot to ping you. Updated.

**Comment by vjpai** [comment]
LGTM.
The qps test tsan failure is related to an infrastructure issue that we are resolving separately.

**Comment by soltanmm** [comment]
Python flakes are well known and probably fixed by #5786.

**Pull request merged**
