### PR TITLE
fixed code style for php_grpc.c

### PR DESCRIPTION
**Pull request by feilengcui**

### CODE REVIEW

**Comment by tbetbetbe** [comment]
Hi @feilengcui, thanks for this contribution.  Can you make sure you have accepted the Contributor License Agreement please ?

**Comment by feilengcui** [comment]
yeah,I've signed the Contributor License Agreement with the email feilengcui008@gmail.com account,its different from my commit email,does that matter?

**Comment by murgatroid99** [comment]
Thank you for your contribution.

However, I am hesitant to merge this. All of the C and C++ code in the repository is formatted with `clang-format-3.5`, and I'm not sure I want to change the code to conflict with that formatting.

**Comment by feilengcui** [comment]
ok,I just thought it's weird for a php extension^_^

**Pull request closed without merging**
