### PR TITLE
Channelz++ Part 5: GetServerSockets Support

### PR DESCRIPTION
**Pull request by ncteisen**
~Build on #16758 and #16760~

Tracking: #15988

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.2% +1.42Ki [None]                                                      +22.6Ki  +0.2%
      +0.2% +1.32Ki [Unmapped]                                                  +22.6Ki  +0.2%
      +3.1%     +32 [None]                                                            0  [ = ]
     +10.0%      +8 inproc_vtable                                                    +8 +10.0%
      +0.6%      +8 vtable                                                           +8  +0.6%
       +20%      +8 vtable for grpc_core::channelz::ServerNode                       +8   +20%
       +20%      +8 vtable for grpc_core::channelz::SocketNode                       +8   +20%
       +14%      +8 vtable for grpc_core::channelz::ChannelNode                      +8   +14%
       +20%      +8 vtable for grpc_core::channelz::SubchannelNode                   +8   +20%
       +14%      +8 vtable for grpc_core::channelz::ClientChannelNode                +8   +14%
       +20%      +8 vtable for grpc_core::channelz::BaseNode                         +8   +20%
   +29%    +735 src/core/lib/channel/channelz.cc                               +735   +29%
      [NEW]    +384 grpc_core::channelz::ServerNode::RenderServerSockets           +384  [NEW]
      +201%    +299 grpc_core::channelz::ServerNode::RenderJson                    +299  +201%
      [NEW]     +66 grpc_core::channelz::ServerNode::ServerNode                     +66  [NEW]
      [NEW]     +47 grpc_core::channelz::BaseNode::RenderServerSockets              +47  [NEW]
      +1.3%      +2 [Unmapped]                                                       +2  +1.3%
  +2.5%    +368 src/core/lib/surface/server.cc                                 +368  +2.5%
      [NEW]    +354 grpc_server_populate_listen_sockets                            +354  [NEW]
      +1.1%      +8 grpc_server_create                                               +8  +1.1%
      +1.6%      +6 [Unmapped]                                                       +6  +1.6%
  +3.1%     +80 src/core/lib/channel/channelz_registry.cc                       +80  +3.1%
      [NEW]     +69 grpc_channelz_get_server_sockets                                +69  [NEW]
      +7.2%     +11 [Unmapped]                                                      +11  +7.2%
  +3.4%     +48 src/core/lib/channel/connected_channel.cc                       +48  +3.4%
       +17%     +24 bind_transport                                                  +24   +17%
       +18%     +15 [Unmapped]                                                      +15   +18%
      [NEW]      +9 grpc_connected_channel_get_socket_uuid                           +9  [NEW]
  +0.1%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +16  +0.1%
      +1.6%     +11 [Unmapped]                                                      +11  +1.6%
      [NEW]      +5 get_socket_uuid                                                  +5  [NEW]
  +0.1%     +16 src/core/ext/transport/inproc/inproc_transport.cc               +16  +0.1%
      +5.6%     +13 [Unmapped]                                                      +13  +5.6%
      [NEW]      +3 get_socket_uuid                                                  +3  [NEW]
  +0.8%     +16 src/core/lib/transport/transport.cc                             +16  +0.8%
      +6.4%     +10 [Unmapped]                                                      +10  +6.4%
      [NEW]      +6 grpc_transport_get_socket_uuid                                   +6  [NEW]

  +0.2% +2.66Ki TOTAL                                                       +23.9Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -48  -0.0%

  [ = ]       0 TOTAL      -48  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,948      Total (>)      1,964,792

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,683,570       Core (>)      3,681,546

10,889,084      Total (>)     10,887,059


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                FILE SIZE
 ++++++++++++++ GROWING                                                  ++++++++++++++
  +0.2% +1.15Ki [None]                                                   +20.8Ki  +0.2%
      +0.2% +1.07Ki [Unmapped]                                               +20.7Ki  +0.2%
      +3.1%     +32 [None]                                                         0  [ = ]
       +20%      +8 vtable for grpc_core::channelz::ServerNode                    +8   +20%
       +20%      +8 vtable for grpc_core::channelz::SocketNode                    +8   +20%
       +14%      +8 vtable for grpc_core::channelz::ChannelNode                   +8   +14%
       +20%      +8 vtable for grpc_core::channelz::SubchannelNode                +8   +20%
       +14%      +8 vtable for grpc_core::channelz::ClientChannelNode             +8   +14%
       +20%      +8 vtable for grpc_core::channelz::BaseNode                      +8   +20%
   +17%    +447 src/core/lib/channel/channelz.cc                            +447   +17%
      [NEW]    +384 grpc_core::channelz::ServerNode::RenderServerSockets        +384  [NEW]
      [NEW]     +66 grpc_core::channelz::ServerNode::ServerNode                  +66  [NEW]
      [NEW]     +47 grpc_core::channelz::BaseNode::RenderServerSockets           +47  [NEW]
      +8.6%     +13 [Unmapped]                                                   +13  +8.6%
  +2.4%    +352 src/core/lib/surface/server.cc                              +352  +2.4%
      [NEW] +1.13Ki grpc_server_setup_transport_with_socket_uuid             +1.13Ki  [NEW]
      [NEW]    +334 grpc_server_populate_server_sockets                         +334  [NEW]
      +1.1%      +8 grpc_server_create                                            +8  +1.1%
      +0.5%      +2 [Unmapped]                                                    +2  +0.5%
  +3.1%     +80 src/core/lib/channel/channelz_registry.cc                    +80  +3.1%
      [NEW]     +69 grpc_channelz_get_server_sockets                             +69  [NEW]
      +7.2%     +11 [Unmapped]                                                   +11  +7.2%
  +0.6%     +16 src/core/ext/transport/chttp2/server/chttp2_server.cc        +16  +0.6%
      +3.4%     +16 on_handshake_done                                            +16  +3.4%

  +0.1% +2.02Ki TOTAL                                                    +21.7Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%



```

**Comment by markdroth** [comment]
The new code here (just the last commit) looks good.  I'll wait for the dependent PRs to be merged before approving.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,988      Total (>)      1,964,892

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,683,754       Core (>)      3,682,198

10,889,276      Total (>)     10,887,721


```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,012      Total (>)      1,964,916

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,685,586       Core (>)      3,682,198

10,891,099      Total (>)     10,887,716


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                         cpu_time    real_time
------------------------------------------------  ----------  -----------
BM_HasClearGrpcStatus<ErrorWithHttpError>         +16%        +16%
BM_HasClearGrpcStatus<ErrorWithNestedGrpcStatus>  +5%         +5%
BM_MetadataRefUnrefExternal                       +12%        +12%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                    FILE SIZE
 ++++++++++++++ GROWING                                                      ++++++++++++++
  +0.3% +2.08Ki [None]                                                       +34.2Ki  +0.4%
      +0.3% +1.95Ki [Unmapped]                                                   +34.1Ki  +0.4%
      [NEW]     +48 vtable for grpc_core::channelz::ListenSocketNode                 +48  [NEW]
      +3.1%     +32 [None]                                                             0  [ = ]
       +20%      +8 vtable for grpc_core::channelz::ServerNode                        +8   +20%
       +20%      +8 vtable for grpc_core::channelz::SocketNode                        +8   +20%
       +14%      +8 vtable for grpc_core::channelz::ChannelNode                       +8   +14%
       +20%      +8 vtable for grpc_core::channelz::SubchannelNode                    +8   +20%
       +14%      +8 vtable for grpc_core::channelz::ClientChannelNode                 +8   +14%
       +20%      +8 vtable for grpc_core::channelz::BaseNode                          +8   +20%
   +34%    +884 src/core/lib/channel/channelz.cc                                +884   +34%
      [NEW]    +384 grpc_core::channelz::ServerNode::RenderServerSockets            +384  [NEW]
      +190%    +283 grpc_core::channelz::ServerNode::RenderJson                     +283  +190%
      [NEW]     +75 grpc_core::channelz::ListenSocketNode::RenderJson                +75  [NEW]
      [NEW]     +66 grpc_core::channelz::ServerNode::ServerNode                      +66  [NEW]
      [NEW]     +47 grpc_core::channelz::BaseNode::RenderServerSockets               +47  [NEW]
      [NEW]     +30 grpc_core::channelz::ListenSocketNode::ListenSocketNode          +30  [NEW]
      [NEW]     +28 grpc_core::channelz::ListenSocketNode::~ListenSocketNode         +28  [NEW]
      [NEW]     +19 grpc_core::channelz::ListenSocketNode::~ListenSocketNode         +19  [NEW]
      +9.9%     +15 [Unmapped]                                                       +15  +9.9%
  +4.1%    +608 src/core/lib/surface/server.cc                                  +608  +4.1%
      [NEW] +1.13Ki grpc_server_setup_transport                                  +1.13Ki  [NEW]
      [NEW]    +334 grpc_server_populate_server_sockets                             +334  [NEW]
      [NEW]    +272 grpc_server_populate_listen_sockets                             +272  [NEW]
      [NEW]     +75 grpc_server_add_listener                                         +75  [NEW]
      +1.1%      +8 grpc_server_create                                                +8  +1.1%
  +8.5%    +205 src/core/ext/transport/chttp2/server/chttp2_server.cc           +205  +8.5%
       +13%    +125 grpc_chttp2_server_add_port                                     +125   +13%
       +32%     +72 tcp_server_shutdown_complete                                     +72   +32%
      +3.4%     +16 on_handshake_done                                                +16  +3.4%
  +3.1%     +80 src/core/lib/channel/channelz_registry.cc                        +80  +3.1%
      [NEW]     +69 grpc_channelz_get_server_sockets                                 +69  [NEW]
      +7.2%     +11 [Unmapped]                                                       +11  +7.2%

  +0.3% +3.81Ki TOTAL                                                        +36.0Ki  +0.4%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,912      Total (>)      1,964,816

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,684,926       Core (>)      3,681,546

10,890,448      Total (>)     10,887,064


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                  cpu_time    real_time
-----------------------------------------  ----------  -----------
BM_ErrorGetMissingInt                      +12%        +12%
BM_ErrorGetStatusCode<SimpleError>         +6%         +6%
BM_HasClearGrpcStatus<ErrorWithHttpError>  +16%        +16%
BM_MetadataRefUnrefExternal                +25%        +25%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                    FILE SIZE
 ++++++++++++++ GROWING                                                      ++++++++++++++
  +0.2% +1.72Ki [None]                                                       +32.8Ki  +0.4%
      +0.3% +1.71Ki [Unmapped]                                                   +32.8Ki  +0.4%
      [NEW]     +40 vtable for grpc_core::channelz::ListenSocketNode                 +40  [NEW]
   +29%    +837 src/core/lib/channel/channelz.cc                                +837   +29%
      [NEW]    +384 grpc_core::channelz::ServerNode::RenderServerSockets            +384  [NEW]
      +190%    +283 grpc_core::channelz::ServerNode::RenderJson                     +283  +190%
      [NEW]     +75 grpc_core::channelz::ListenSocketNode::RenderJson                +75  [NEW]
      [NEW]     +66 grpc_core::channelz::ServerNode::ServerNode                      +66  [NEW]
      [NEW]     +30 grpc_core::channelz::ListenSocketNode::ListenSocketNode          +30  [NEW]
      [NEW]     +28 grpc_core::channelz::ListenSocketNode::~ListenSocketNode         +28  [NEW]
      [NEW]     +19 grpc_core::channelz::ListenSocketNode::~ListenSocketNode         +19  [NEW]
     +10.0%     +15 [Unmapped]                                                       +15 +10.0%
  +4.1%    +608 src/core/lib/surface/server.cc                                  +608  +4.1%
      [NEW] +1.13Ki grpc_server_setup_transport                                  +1.13Ki  [NEW]
      [NEW]    +334 grpc_server_populate_server_sockets                             +334  [NEW]
      [NEW]    +272 grpc_server_populate_listen_sockets                             +272  [NEW]
      [NEW]     +75 grpc_server_add_listener                                         +75  [NEW]
  +8.5%    +205 src/core/ext/transport/chttp2/server/chttp2_server.cc           +205  +8.5%
       +13%    +125 grpc_chttp2_server_add_port                                     +125   +13%
       +32%     +72 tcp_server_shutdown_complete                                     +72   +32%
      +3.4%     +16 on_handshake_done                                                +16  +3.4%
  +3.1%     +80 src/core/lib/channel/channelz_registry.cc                        +80  +3.1%
      [NEW]     +65 grpc_channelz_get_server_sockets                                 +65  [NEW]
      +9.9%     +15 [Unmapped]                                                       +15  +9.9%

  +0.2% +3.41Ki TOTAL                                                        +34.5Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -16  -0.0%

  [ = ]       0 TOTAL      -16  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,331      Total (<)      1,965,335

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,685,906       Core (>)      3,682,710

10,891,423      Total (>)     10,888,236


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                    cpu_time    real_time
---------------------------  ----------  -----------
BM_ErrorGetMissingInt        +6%         +6%
BM_MetadataRefUnrefExternal  +27%        +27%
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,914      Total (=)      1,965,914

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,686,418       Core (>)      3,684,154

10,891,942      Total (>)     10,889,673


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                    FILE SIZE
 ++++++++++++++ GROWING                                                      ++++++++++++++
  +0.1% +1.10Ki [None]                                                       +13.9Ki  +0.1%
      +0.2% +1.06Ki [Unmapped]                                                   +13.9Ki  +0.1%
      [NEW]     +40 vtable for grpc_core::channelz::ListenSocketNode                 +40  [NEW]
   +13%    +437 src/core/lib/channel/channelz.cc                                +437   +13%
      +190%    +283 grpc_core::channelz::ServerNode::RenderJson                     +283  +190%
      [NEW]     +75 grpc_core::channelz::ListenSocketNode::RenderJson                +75  [NEW]
      [NEW]     +30 grpc_core::channelz::ListenSocketNode::ListenSocketNode          +30  [NEW]
      [NEW]     +28 grpc_core::channelz::ListenSocketNode::~ListenSocketNode         +28  [NEW]
      [NEW]     +19 grpc_core::channelz::ListenSocketNode::~ListenSocketNode         +19  [NEW]
      +1.2%      +2 [Unmapped]                                                        +2  +1.2%
  +1.8%    +272 src/core/lib/surface/server.cc                                  +272  +1.8%
      [NEW]    +272 grpc_server_populate_listen_sockets                             +272  [NEW]
      [NEW]     +75 grpc_server_add_listener                                         +75  [NEW]
  +7.8%    +189 src/core/ext/transport/chttp2/server/chttp2_server.cc           +189  +7.8%
       +13%    +125 grpc_chttp2_server_add_port                                     +125   +13%
       +32%     +72 tcp_server_shutdown_complete                                     +72   +32%

  +0.1% +1.98Ki TOTAL                                                        +14.8Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                    cpu_time    real_time
---------------------------  ----------  -----------
BM_ErrorGetIntFromNoError    -4%         -4%
BM_MetadataRefUnrefExternal  -4%         -4%
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,914      Total (=)      1,965,914

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,686,418       Core (>)      3,684,154

10,891,935      Total (>)     10,889,675


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                         cpu_time    real_time
------------------------------------------------  ----------  -----------
BM_ErrorGetIntFromNoError                         -7%         -7%
BM_ErrorGetStatusCode<ErrorWithHttpError>         +8%         +8%
BM_ErrorGetStatusCode<ErrorWithNestedGrpcStatus>  +7%         +7%
BM_MetadataRefUnrefExternal                       -16%        -16%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,914      Total (=)      1,965,914

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,891,936      Total (<)     10,891,942

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
