### PR TITLE
More upb targets on googleapis

### PR DESCRIPTION
**Pull request by veblush**
- Migrated `google/api/*` upb targets to regular upb targets
- Updated `gen_upb_api_from_bazel_xml.py` script to support a transitive proto dependency

### CODE REVIEW

**Comment by veblush** [comment]
[grpc_build_artifacts_multiplatform](https://fusion2.corp.google.com/invocations/ae874cbc-64b1-4992-a7a8-36086338380a): running

**Review by markdroth — APPROVED** [review]
This is fine with me, but please also have @jtattermusch review, since he knows the build scripts much better than I do.

**Comment by veblush** [comment]
internal cherry-pick cl/411070220

**Review by jtattermusch — APPROVED** [review]
LGTM.

**Pull request merged**
