### PR TITLE
Cap deadline to 99999999 seconds on wire

### PR DESCRIPTION
**Pull request by yang-g**
- cap deadline to 99,999,999 seconds on the wire
- when time out is over the limit, send "99999999S" on the wire.
- takes only 3 significant digits when timeout is larger than 1000 seconds.
- reduce the timeout encoding buffer size to 10.

This is to conform to the standard that grpc-timeout value should have at most 8 digits. While we can set separate limits for hours, minutes and seconds, 1157 days seems to be a long enough timeout cap for rpcs.

### CODE REVIEW

**Comment by markdroth** [comment]
It seems a bit odd to enforce this cap in the transport API layer, rather than in chttp2, since the spec that restricts this to 8 digits is the spec for the HTTP/2 wire protocol.  There could be other transports that don't need this restriction in the future, couldn't there?

**Comment by yang-g** [comment]
This is http2 transport API. Note the function is called `grpc_http2_encode_timeout` and I do not think other transport would use this.

**Comment by yang-g** [comment]
Thanks. I will do a cherrypick and a TGP to make sure there is no potential issues (I would not assume there is any).

**Comment by yang-g** [comment]
Test failures: #18126 #18616

**Pull request merged**
