### PR TITLE
Add buildifier sanity check

### PR DESCRIPTION
**Pull request by lidizheng**
This is a two step change.
1. Make sure the `buildifier` is working properly with Kokoro;
2. Format all existing BUILD files with the `buildifier`, and checked in atomically.

### CODE REVIEW

**Comment by gnossen** [comment]
This is a really nice change! One major concern though. Do we have any guarantee that the style enforced by buildifier externally will also be the style enforced *internally*?

**Comment by jtattermusch** [comment]
Makes sense to me overall, but you need to also add the test to https://github.com/grpc/grpc/blob/master/tools/run_tests/sanity/sanity_tests.yaml (and doublecheck sanity results to make sure it's actually being run).

**Comment by lidizheng** [comment]
@gnossen I also concerned about this question, and I think there are two parts in it:

Does the external `buildifier` has the same "rule" as the internal one?
I tried to format every Bazel/Blaze related in gRPC folder in google3 using the external binary, it didn't change anything. I would say it is safe to assume they have the same "rule" now.

Will the external `buildifier` always have the same "rule" as the internal one?
I pined the binary to `0.29.0`, so it might diverge from internal rules in distant future. But due to Bazel's instability in the past year, I would prefer to pin the version to make our sanity test deterministic.

**Comment by jtattermusch** [comment]
> @gnossen I also concerned about this question, and I think there are two parts in it:
> 
> Does the external `buildifier` has the same "rule" as the internal one?
> I tried to format every Bazel/Blaze related in gRPC folder in google3 using the external binary, it didn't change anything. I would say it is safe to assume they have the same "rule" now.
> 
> Will the external `buildifier` always have the same "rule" as the internal one?
> I pined the binary to `0.29.0`, so it might diverge from internal rules in distant future. But due to Bazel's instability in the past year, I would prefer to pin the version to make our sanity test deterministic.

+1 to pinning.

**Comment by lidizheng** [comment]
@jtattermusch The `buildifier` check failed in the expected way 👍 (because our Bazel files are not formatted just yet).
https://source.cloud.google.com/results/invocations/8bca8b89-aa53-4bfd-986e-b2748e6f3d45/targets/github%2Fgrpc%2Frun_tests%2Fsanity_linux_dbg_native%2Ftools%2Frun_tests%2Fsanity%2Fcheck_buildifier.sh/tests

**Comment by lidizheng** [comment]
Included in #20885

**Pull request closed without merging**
