### PR TITLE
Make _channel_test threads not hold the test harness hostage

### PR DESCRIPTION
**Pull request by soltanmm**
Bail out early on test timeout and don't let other threads keep the test from finishing.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
I get why we would want to hack up this test this way in the course of an investigation, but are we sure we want to commit this change to the codebase? As in, this is the way the test should look going forward?

**Comment by soltanmm** [comment]
Honestly I feel like all of our tests ought to behave *like* this; it provides more information w.r.t. where hangs are or are not coming from by differentiating among threads that are or are not behaving the way we expect them to be.

Arguably this kind of thing should be made into a cross-test utility, but then I'd want to integrate it into `LoggingPool` as a sort of 'debug mode' (along with all the other bells and whistles a debug mode ought to provide).

**Comment by nathanielmanistaatgoogle** [comment]
No hard feelings, but I'd like to sit on this until we see what happens in #5731. Poke me if that gets in your way?

**Comment by soltanmm** [comment]
Sitting *is* a time-honored tradition of the human species...

**Comment by soltanmm** [comment]
This is no longer necessary, but I do still believe we should revisit some sort of debug mode on thread pools and the like.

**Pull request closed without merging**
