### PR TITLE
Set allow_flakes to true for cloud_to_prod tests

### PR DESCRIPTION
**Pull request by adelez**
#12518 and #11219

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by adelez** [comment]
Portability Tests Linux: #12871 
Basic Tests C++ Linux: #12510, #12873
Basic Tests MacOS: #5424
Interop Cloud-to-Cloud Tests and Interop Cloud-to-Prod Tests #12875

**Pull request merged**
