### PR TITLE
Upmerge #14973 to the master

### PR DESCRIPTION
**Pull request by ZhouyihaiDing**
Testing to see if this works for #14960

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ZhouyihaiDing** [comment]
Known issue:
Interop Cloud-to-Cloud Tests (internal CI) 
Interop Cloud-to-Prod Tests (internal CI) - #14969

**Pull request merged**
