### PR TITLE
Need to include functional to use std::bind

### PR DESCRIPTION
**Pull request by vjpai**
gcc7 complains otherwise

### CODE REVIEW

**Comment by ncteisen** [comment]
was this compiling before?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by vjpai** [comment]
It was compiling fine because we don't have gcc7 in our test suite.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
