### PR TITLE
Load Reporting Filter

### PR DESCRIPTION
**Pull request by dgquintas**
WIP implementation of the LR filter. The final LR design is still in flux, but changes introduced in this PR (`grpc_call_final_info`) are needed by census. Large parts of the code is also valid regardless of the final form of the LR filter.

### CODE REVIEW

**Comment by dgquintas** [comment]
@summerxyt FYI

**Comment by ctiller** [comment]
no objections to this

**Comment by dgquintas** [comment]
@sreecha Requesting a quick review so that this can go in to make @bogdandrutu happy. Note @ctiller 's previous comment, which to me sounds similar to an LGTM :)

I've made some minor changes since to remove code that we now know won't be used (due to LR filter's redesign in progress).

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
