### PR TITLE
Add a GrpcEnvironment.NativeLibrary property as an escape hatch for unusual deployment scenarios

### PR DESCRIPTION
**Pull request by jskeet**
Basically this is for cases where the auto-detection would fail.
This API is marked as being experimental.

(The PR has been split off from #7282.)

### CODE REVIEW

**Comment by jtattermusch** [comment]
Jon, do you want to follow up on this one or shall we close it?

**Comment by jskeet** [comment]
I still think it would be a good idea, but we could certainly punt on it for now.

**Comment by zaneclaes** [comment]
@jskeet @jtattermusch could this be revisited? The `TODO` in `LoadUnmanagedLibrary` has been sitting in the code for a long time, and I find the lack of configurability to be a major annoyance in working with GRPC. I'd be happy with just a one-line change to add an optional environment variable override for the path.

**Comment by jskeet** [comment]
Definitely up to @jtattermusch - it feels reasonable to me too, but I don't have nearly as much experience as Jan on this.

**Comment by jtattermusch** [comment]
@zaneclaes  I can try to revive this PR (I expect to run into some merge conflicts some of which might be interesting to solve) but not sure when I'll get to it. Feel free to recreate the PR yourself if this is a feature you need.

**Comment by jtattermusch** [comment]
@zaneclaes  do you have particular loading scenarios/platforms in mind?   The way the loading of native library works has actually recently become more complicated as we added Unity and Xamarin support. 
The new mobile platforms actually rely purely on [DllImport] annotated methods and they don't use the logic for explicit loading of the library from a disk file: https://github.com/grpc/grpc/blob/60069baa6a430f744338941ee91953f6bd9403ef/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L108

So, after re-thinking, setting the native library path would only work on some platforms (~ the "desktop" ones) while on others I can't think of a way how to implement this new setting.

**Pull request closed without merging**
