### PR TITLE
Make cross-compiling great again

### LINKED ISSUE #11475: When cross-compiling gRPC should not use the same CPPFLAGS for the target and the host
### What version of gRPC and what language are you using?
1.3.0 but the issue exists in master as well 
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu Trusty
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 ARM cross-compiler:

```
Chromium OS 5.0_pre300080-r7 clang version 5.0.0
Target: armv7a-cros-linux-gnueabi
Thread model: posix
 ```
Host compiler:

```
x86_64-pc-linux-gnu-g++.real (4.9.2_cos_gg_4.9.2-r155-32c89c19b042a12b5a1bf0153299154ea5435c03_4.9.2-r155) 4.9.x 20150123 (prerelease)
```

### What did you do?

```
make -j56 V=1 \
    prefix=/usr \
    PKG_CONFIG=/build/kevin/build/bin/pkg-config \
    'AR=armv7a-cros-linux-gnueabi-ar rcs' \
    CC=armv7a-cros-linux-gnueabi-clang \
    CXX=armv7a-cros-linux-gnueabi-clang++ \
    LD=armv7a-cros-linux-gnueabi-clang \
    LDXX=armv7a-cros-linux-gnueabi-clang++ \
    HOST_CC=x86_64-pc-linux-gnu-gcc \
    HOST_CXX=x86_64-pc-linux-gnu-g++ \
    HOST_LD=x86_64-pc-linux-gnu-gcc \
    HOST_LDXX=x86_64-pc-linux-gnu-g++
```
 
### What did you expect to see?
 
The build completes successfully.
 
### What did you see instead?
 
```
x86_64-pc-linux-gnu-g++ -O2 -O2 -O2 -pipe -march=armv8-a+crc -mtune=cortex-a57.cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -g -fno-exceptions -fno-unwind-tables   -fno-asynchronous-unwind-tables  -clang-syntax -std=c++11   -pthread  -Ithird_party/googletest/googletest/include  -g -Wall -Wextra -Werror -Wno-
long-long -Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -O2 -fPIC -I. -Iinclude -I/build/kevin/tmp/portage/dev-libs/grpc-1.3.0/work/grpc-1.3.0/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr\"     -DTSI_OPENSSL_ALPN_SUPPORT=0 -MMD -MF /build/kevin/tmp/portage/dev-libs/grpc-1.3.0/work/grpc-1.3.0/objs/opt/src/compiler/ruby_gener
ator.dep -c -o /build/kevin/tmp/portage/dev-libs/grpc-1.3.0/work/grpc-1.3.0/objs/opt/src/compiler/ruby_generator.o src/compiler/ruby_generator.cc
x86_64-pc-linux-gnu-g++.real: error: unrecognized command line option '-mfpu=crypto-neon-fp-armv8'
x86_64-pc-linux-gnu-g++.real: error: unrecognized command line option '-mfloat-abi=hard'
x86_64-pc-linux-gnu-g++.real: error: unrecognized command line option '-clang-syntax'
```

There are a couple of things here:

* I did not set GRPC_CROSS_COMPILE to true because chrome os has cross-compile aware wrappers around pkg-config, which prefix paths appropriately when cross-compiling for different devices.  Unfortunately, it looks like the Makefile makes assumptions in some places that if we are cross-compiling then pkg-config does not exist and doesn't bother to consult it. 

* The flags that host compiler is complaining about are set through the CXXFLAGS environment variable by the chrome os build system.  As you can see, these flags are ARM-specific.  However it looks like the Makefile simply uses the same C{,XX,PP}FLAGS for both the target and the host.  In almost no case is this a good idea.  Additionally, I can't just workaround the problem by setting my own HOST_C{,PP,XX}FLAGS because there are some non architecture-specific includes and defines that are needed when compiling the plugins on the host.

The host flags should only include those things that are actually needed to compile the plugins.  For example, right now the Makefile tries to link against openssl and c-ares when building the plugins.  I don't think those should be necessary for a compiler plugin...

If nothing else, there should be a toggle to disable building the plugins and to just use the ones that are already installed.
 
### Anything else we should know about your project / environment?

I'm attempting to build gRPC for an ARM chromebook.  There are several CLs currently pending so reproducing this problem may be a bit more difficult.

### PR DESCRIPTION
**Pull request by jynnantonix**
Fixes #11475

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by nicolasnoble** [comment]
This is okay to test.

**Comment by nicolasnoble** [comment]
Several comments. First you would need to update the template file so it regenerates properly when someone changes the list of files in the project. 

Second, most of the change isn't actually really needed. I can get behind the `AR` one, but for the rest, you can actually override these values from make's command line. At best you should use ?= instead of = so they become overridable from the environment variables too.

**Comment by jynnantonix** [comment]
> Second, most of the change isn't actually really needed. I can get behind the AR one, but for the rest, you can actually override these values from make's command line. At best you should use ?= instead of = so they become overridable from the environment variables too.

That was my first approach (setting them on the make command line so that they cannot get set by the Makefile) but it doesn't really work because there are some non arch-specific includes and defines that are necessary to actually compile the plugins which don't get added.

Ideally there would be some way to just turn off building the plugins and use the ones already installed on the build machine.  Then you wouldn't have to treat cross-compiling in any special way at all.

**Comment by nicolasnoble** [comment]
About the includes and defines not being properly mangled, that's the real
issue to try solving then. I wasn't aware of the problem. Usually ?= used
with environment variables does the trick nicky.

However I am confused about the rest of the comment. Are you suggesting
using the system's plug-ins to build the tests? Because aside from tests, I
am not aware of the reason you'd need the plug-ins to build anything.

**Comment by jynnantonix** [comment]
> However I am confused about the rest of the comment. Are you suggesting
using the system's plug-ins to build the tests? Because aside from tests, I
am not aware of the reason you'd need the plug-ins to build anything.

Even if I remove `plugins` from the `all` target, something still attempts to use them.  Look for `$(PROTOC_PLUGINS)` starting from [here](https://github.com/grpc/grpc/blob/master/Makefile#L2244).  I don't think I'm building any tests since the way I invoke the build is to just run `make` with no target.

It appears that `PROTOC_PLUGINS` automatically gets set to the ones from the grpc tree if `$(HAS_SYSTEM_PROTOBUF)` is true (see [here](https://github.com/grpc/grpc/blob/master/Makefile#L794)).  This also seems like a bug.  I would think that if `$(HAS_SYSTEM_PROTOBUF)` is true, then we should check to see if the protoc plugins are also installed and use those instead of building them out of the tree.

So to clarify my comment what I'd like is for the Makefile to not attempt to handle multiple toolchains at all and instead use the same toolchain to build everything while providing knobs to turn off parts of the build (like the plugins).  I guess I'm a bit frustrated because it's clear that cross-compiling isn't something that gets tested on every commit (otherwise the AR/HOST_AR issue would have been caught earlier) so it seems better to just drop the support rather than let it bit-rot until someone finds a problem.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by nicolasnoble** [comment]
Aah, the health checking now uses the plugins, indeed. Okay, that's a good reason to have a cause for concern when doing cross compilation. Originally, one could ask to only build the library and no host target would've been touch, that's not the case anymore, which indeed increases the complexity.

However, I'm a bit weary of the "using the plugin from the system" part, because this isn't something that's supposed to be stable and backward-compatible. The code generated by the plugin isn't subject to semantic versioning, and there has been cases in the past where code generated by a previous version of the plugin wouldn't be compatible anymore with the latest version of the library, from a pure compilation perspective. So I'm not sure doing what you're suggesting is a good idea, since it would become impossible to upgrade grpc with a simple overwrite. Basically you'd need to uninstall the former version before even compiling, which seems odd.

On another subject, testing cross compilation on every commit isn't something we're really able to do at the moment for two big reasons:

1) There are _lots_ of potential cross compilation targets. Be it ARM on GNU Linux, Android, ChromeOS, WebOS, ... or even Intel Alpine Linux. We'd need to find a narrow list of targets we're willing to support first, then expand.
2) The maintenance cost for this isn't trivial. Actually going in and say we're actively going to fully support cross compilation for all times now and forever isn't a decision we should take on lightly.

Alternatively, finding interested active maintainers for some items in 1) would alleviate 2).

**Comment by jynnantonix** [comment]
Re: cross-compile being a huge commitment.  I fully understand, cross-compiling is a hairy beast.  I guess what is was trying to get at is that (from a chrome os perspective) cross-compiling should either be fully-supported or not supported at all.  The reason is that we have a lot of tools (like the previously mentioned cross-compile aware wrappers around pkg-config) to deal with packages that don't support cross-compiling.  It's the packages that provide halfway (or best-effort) support that cause the most headaches for us because they don't integrate nicely with any of our existing infrastructure.

Re: building the plugins.  What I'm suggesting is to provide the following instructions for cross-compiling:

* Build and install grpc natively for the build machine and then
* Use the plugins from the previous step when cross-compiling

Rather than making it a default, maybe we can gate it behind the GRPC_CROSS_COMPILE option so that nothing changes for the average user.  If you're still worried about backwards compatibility then I won't try to make this change and I'll just stick to cleaning up the host flags and applying those changes to the template.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @jynnantonix isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
