### PR TITLE
[bazel] Upgrade repo to bazel 6.1.1

### PR DESCRIPTION
**Pull request by jtattermusch**
Upgrade the preferred version of bazel to 6.1.1 (repo wide).
- migrates us to the lastest stable version of bazel
- tentative fix for b/275035917
- prerequisite for dropping bazel 4

Let's see what the tests say.

For comparison, the upgrade to bazel 5.3 looked like this: https://github.com/grpc/grpc/pull/30844/files

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @ctiller  since this likely is the solution for b/275035917

**Comment by jtattermusch** [comment]
objC build failure: 
https://source.cloud.google.com/results/invocations/6c449be0-294b-4135-9d77-e0170e04e9db/log

```
ERROR: /private/var/tmp/_bazel_kbuilder/56f0bf568ea4b00a9aa3000e432900f1/external/CronetFramework/BUILD.bazel:154:15: in _gen_module_map rule @CronetFramework//:CronetFramework_module_map:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_kbuilder/56f0bf568ea4b00a9aa3000e432900f1/external/rules_pods/BazelExtensions/extensions.bzl", line 197, column 55, in _module_map_impl
		objc_provider = apple_common.new_objc_provider(
Error in new_objc_provider: Argument header not a recognized key, 'strict_include', or 'providers'.
ERROR: /private/var/tmp/_bazel_kbuilder/56f0bf568ea4b00a9aa3000e432900f1/external/CronetFramework/BUILD.bazel:154:15: Analysis of target '@CronetFramework//:CronetFramework_module_map' failed
ERROR: Analysis of target '//src/objective-c/tests:CppCronetTests' failed; build aborted:
INFO: Elapsed time: 5.702s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded, 12258 targets configured)
ERROR: Couldn't start the build. Unable to run tests
```

@HannahShiSFB  @sampajano  can you please take a look?

**Comment by HannahShiSFB** [comment]
Can we drop the support of Cronet?
It doesn't have arm builds so cannot run on M1/M2 mac or iOS anyways.

**Comment by sampajano** [comment]
> Can we drop the support of Cronet? It doesn't have arm builds so cannot run on M1/M2 mac or iOS anyways.

Let's disable Cronet tests whenever necessary.

Cronet support is going away soon, but they're still used by some major clients and hence we cannot simply remove the code.

I believe Cronet worked on iPhones and that's why some are still using it (sometimes through C++ APIs). Is it not the case?

**Comment by HannahShiSFB** [comment]
[Cronet](https://storage.googleapis.com/grpc-precompiled-binaries/cronet/Cronet.framework-v0.0.5.zip) only provides x86 (32 and 64 bit) binaries, so can't be working on iPhones.

```
% file Cronet.framework/Cronet
Cronet.framework/Cronet: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386]
Cronet.framework/Cronet (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Cronet.framework/Cronet (for architecture i386):	Mach-O dynamically linked shared library i386
```

**Comment by sampajano** [comment]
> [Cronet](https://storage.googleapis.com/grpc-precompiled-binaries/cronet/Cronet.framework-v0.0.5.zip) only provides x86 (32 and 64 bit) binaries, so can't be working on iPhones.
> 
> ```
> % file Cronet.framework/Cronet
> Cronet.framework/Cronet: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386]
> Cronet.framework/Cronet (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
> Cronet.framework/Cronet (for architecture i386):	Mach-O dynamically linked shared library i386
> ```

@HannahShiSFB Aha. Interesting information! Could you give further information on how these Cronet binaries you pointed to are distributed? (e.g. website, etc.)

From traffic log we gathered, there are clients using Cronet on Android/iOS, but is maybe only doing so via the C++ API (instead of ObjC API).

**Comment by veblush** [comment]
FYI, I didn't know about this PR and Bazel 6 upgrade was complete by https://github.com/grpc/grpc/pull/32910. All Cronet tests ended up being disabled.

**Comment by jtattermusch** [comment]
Superseded by https://github.com/grpc/grpc/pull/32910

**Pull request closed without merging**
