### PR TITLE
Fix AuthSample crash on startup

### PR DESCRIPTION
**Pull request by jcanizales**
Downloaded plist with new keys needed by Firebase SDK

### CODE REVIEW

**Comment by jcanizales** [comment]
I've cancelled the Travis run because this change doesn't affect compiling, which is all Travis does with the example apps.

**Comment by jcanizales** [comment]
Ping

**Comment by jcanizales** [comment]
Ping :)

**Comment by muxi** [comment]
I tried to install AuthSample within this branch and got the following error:

```
[!] Unable to satisfy the following requirements:

- `!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1)` required by `AuthTestService (0.0.1)`

None of your spec sources contain a spec satisfying the dependency: `!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1)`.
```

**Comment by jcanizales** [comment]
Please run `pod repo update` for Cocoapods to refresh its knowledge of the pods that exist :) Not sure why they stopped doing it automatically. I wasted hours to figure out what was wrong the first time it happened to me.

**Comment by muxi** [comment]
LGTM

**Comment by jcanizales** [comment]
@makdharma for his supermerge powers.

**Pull request merged**
