### PR TITLE
Add a header to override grpc::string when needed

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by yang-g** [comment]
@gwvo is this going to be a problem for flatbuffer?

**Comment by gwvo** [comment]
Yes, that's a problem since config.h pulls in a whole bunch of other grpc headers. cpp_generator.h is meant to be self-contained so it can be compiled into `flatc` without needing grpc.

**Comment by yang-g** [comment]
@gwvo Could you somehow override the config.h or remove that line when making the copy? The cpp_generator.h uses grpc::string and it would be hard for me to override it without the header. Thanks.

**Comment by yang-g** [comment]
test this please

**Comment by gwvo** [comment]
I guess easiest if in FlatBuffers we just provide an empty config.h, right?

**Comment by yang-g** [comment]
@gwvo That is what I had in mind :) and it is the reason I did not remove the section about the custom string.

**Comment by yang-g** [comment]
@nicolasnoble ping~

**Pull request merged**
