### PR TITLE
fixed a bug in json_run_localhost scenario generation

### PR DESCRIPTION
**Pull request by billfeng327**
The current scenario_gen.py for json_run_localhost was using the same scenarios as qps_json_driver, this is to fix the bug

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,026      Total (=)      1,955,026

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,748      Total (<)     10,843,756

 No significant differences in binary sizes


```

**Comment by jtattermusch** [comment]
@billfeng327  please apply the "release notes: yes" or "release notes: no" (probably the right choice for this PR) label to make the "Mergeable" check pass.

**Pull request merged**
