### PR TITLE
PHP: Delete dup-header files included

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by thinkerou** [comment]
PHP5 failed on Linux and PHP7 is successful, but I can not see the error log.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by thinkerou** [comment]
Because difficultly squash and close the pr via #12360

**Pull request closed without merging**
