### PR TITLE
Add cloud_gateway as prod server in Jenkins tests.

### PR DESCRIPTION
**Pull request by adelez**
@ejona86

### CODE REVIEW

**Comment by jtattermusch** [comment]
Setting up the cloud_gateway tests is good work, thanks!

Nevertheless, it seems that the  go and java tests are failing against cloud_gateway (and there's one PHP test failure I'm unsure about). We can't really merge this until we figure this out.

See the report:
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/1962/HTML_Report/

**Comment by jtattermusch** [comment]
Also please fix the copyright:
`tools/jenkins/run_interop.sh modified 2016 but copyright only extends to 2015`

**Comment by adelez** [comment]
@ejona86 and @iamqizhao, can you please take a look at the java and go test failures? They were the same interop tests against the canary CFEs.

**Comment by adelez** [comment]
Fixed copyright.

**Comment by ejona86** [comment]
I tracked down the Java failure. Java has broken SNI when using OpenSSL. The cloud gateway uses the same IP for google.com and googleapis.com whereas the normal gateway uses separate IPs. This means that the cloud gateway requires SNI while the normal gateway does not.

It's already been [fixed upstream](https://github.com/netty/netty/commit/e220c568232fe9b479e3ac7a5b66f5a97dcc2c39). We'll need to update to netty-4.1.0.CR2 to pick up the fix. Filed grpc/grpc-java#1398 for tracking upgrade.

**Comment by adelez** [comment]
This is replaced by #5453

**Pull request closed without merging**
