### PR TITLE
Added unit testing support.

### PR DESCRIPTION
**Pull request by MakMukhi**
- Auto-generate GMOCK code for client stubs.
- Updated mock_test.cpp to use the new way.
- Added parameter to cpp_plugin for generating GMOCK code. 

Design doc: https://docs.google.com/a/google.com/document/d/1SdkAkgMckeCGfcpS7i9BThARCgtcIleE0SJrrtd_78I/edit?usp=sharing

### CODE REVIEW

**Comment by ctiller** [comment]
Please add a golden file test for this, to make this review and future
changes easier.

**Comment by yang-g** [comment]
Please run tools/buildgen/generate_projects.sh to re-generate projects.

**Comment by MakMukhi** [comment]
test this please

**Comment by MakMukhi** [comment]
ping

**Comment by ncteisen** [comment]
This looks to have broken the cmake tests:

`/var/local/git/grpc/test/cpp/end2end/mock_test.cc:37:25: fatal error: gmock/gmock.h: No such file or directory
 #include <gmock/gmock.h>`

**Pull request merged**
