### PR TITLE
fix print format for python3

### PR DESCRIPTION
**Pull request by OceanOfWest**
add brackets of print in run_tests/start_port_server.py

### CODE REVIEW

**Comment by gnossen** [comment]
Is it possible to remove the shebang at the top of the file as well to make this fully Python version agnostic?
Related: https://github.com/grpc/grpc/issues/19083

**Comment by OceanOfWest** [comment]
ah~ yes it is, thanks for your correction, i make another commit of this.
notice that you are optimize this part, that's great.～^_^

**Comment by gnossen** [comment]
`python` also [explicitly refers to Python 2](https://www.python.org/dev/peps/pep-0394/). It's probably best to just leave the shebang off if possible and modify all of the call sites that invoke it as an executable.

**Comment by OceanOfWest** [comment]
ok, my mistake, thanks again. seems this PR is duplication of the work you are doing, how should i oprate, close now or close when you are done for all?

**Comment by gnossen** [comment]
I'm actually not actively working on upgrading the `tools/` directory code at the moment. I'm investigating a Python 3-only future for the gRPC Python package. I've just documented technical debt in the tooling code where I've found it. So this PR is not duplicated. It's greatly appreciated.

**Comment by OceanOfWest** [comment]
ok, thanks for your advanced and helpful advice, but original intention of this PR is just modify the python 'print' format, matching both of python2 and python3.
I suggest modification of the shebang of python files and the calling sites to be done by another PR,
I can work for that if needed.

**Comment by gnossen** [comment]
Known failures:
 - Basic Tests C/C++ MacOS: https://github.com/grpc/grpc/issues/18416
 - Interop Tests: https://github.com/grpc/grpc/issues/18967

**Pull request merged**
