### PR TITLE
Strip manylinux1 binary wheels

### PR DESCRIPTION
**Pull request by mehrdada**
Fixes https://github.com/grpc/grpc/issues/14970

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
Python distribtests ran manually and seem to pass. Will keep an eye on master as well.

**Comment by ericgribkoff** [comment]
Reverted by https://github.com/grpc/grpc/pull/17412 due to https://github.com/grpc/grpc/issues/17409

**Comment by mehrdada** [comment]
@ericgribkoff Interesting... Our distribtests verify `pip install`; if you want to ensure `pex` installation is supported down the road, it is a good idea to add a distribtest for that to catch things like this.

**Comment by nicolasnoble** [comment]
Or maybe simply try and strip the files before the hash is generated? Or have a hash regeneration script?

**Comment by ericgribkoff** [comment]
The issue was not specifically about `pex` compatibility but that we shouldn't be distributing malformed wheels. `pip` is currently not checking the hash codes, but this will likely change (@lidizheng found https://github.com/pypa/pip/issues/3513). More fundamentally, we should just rely on setup.py to do its work and produce a valid wheel; as long as we refrain from unzipping it and adhoc modifying its after it is created, we should be fine.

The correct approach to stripping the binaries seems to be doing this as part of the build process, when the wheel is created. However, there are pros and cons to stripping debug symbols and we will have to evaluate how easily users can give us useful backtraces if the distributed binaries are stripped versus in their current form before deciding to modify our wheel creation.

**Comment by mehrdada** [comment]
@nicolasnoble @ericgribkoff yep, if there's a right way to strip it we should do that (I had no idea that wheels are more than a simple archive, personally), but having distribtests for `pex` seems like a good way to make sure wheels are valid. Pinging @ejona86 as he was there when the stripping decision was made.

**Comment by lidizheng** [comment]
Package `wheel` provides `unpack` and `repack` commands. It can be the intended way of stripping binary then put it back. The checksum in RECORD will be regenerated by `repack`.
https://wheel.readthedocs.io/en/stable/reference/wheel_pack.html

**Pull request merged**
