### PR TITLE
Building grpc++ as dynamic library (DLL) with exported symbols for windows using bazel

### PR DESCRIPTION
**Pull request by ikishchenko**
### Problem
Unable to use one instance of grpc library between different windows dynamic libraries in one application.

### Example
Some application (client.exe) uses two dynamic libraries (a.dll and b.dll). Both dynamic libraries (a.dll and b.dll) contain different implementations of different grpc clients (generated by protoc.exe). Every dynamic library compiled with static grpc library (grpc++.lib) inside, and as result - every dynamic library (a.dll and b.dll) contain the same implementation of grpc++ static libraries. This is a problem, because the application after this contains duplicated implementation of grpc++ and fails with error in runtime.

Compilation grpc++ as dynamic library (DLL) resolves this problem because application loaded only once instance of grpc++ library.

### About changes
 - Add rule for bazel 'grpc++_shared' to build grpc as a dynamic library with exported symbols.
 - Hide public static fields inside implementation and make accessors for that, because bazel can't export symbols of static fields (this fields are used in public headers and as result when we link grpc++.dll to other project we got 'unresolved external symbol' error. Accessors exported normally and fix this)

### How to use
```
$ bazel build grpc++_shared.dll
```

### CODE REVIEW

**Comment by nicolasnoble** [comment]
So, the thing I am really worried with this kind of features is that [memory management for Windows DLLs](https://blogs.msdn.microsoft.com/oldnewthing/20161209-00/?p=94905) is fairly complicated. Crossing DLL boundaries for objects and other memory allocations is usually a bad idea, and the our C++ surface API doesn't attempt to guard in any way against such pattern - quite the contrary.

**Comment by ikishchenko** [comment]
We understand that memory allocation across DLL boundaries in Windows is tricky business.
I expect Windows/C++ developers know this is a problem - and adopt sane discipline - if you allocate in a DLL, free in the same DLL.

The problem with the current situation is that it makes it simply impossible to use GRPC under Windows in C++ -- since pretty much all large-scale applications (especially client side) end up using DLLs.

Our modification includes 2 aspects:
- Protecting access to static variables by wrapping them in getters/setters
- The bazel build modifications to produce the Windows DLL

What I would like to ask is to at least merge the first aspect - this static var wrapping would not hurt anyone.
This way you make it easy for anyone to decide with which rope to hang themselves - we still can produce DLLs if we foolishly believe we can work with DLLs under Windows by just triggering the compilation option for this - but at least the codebase allows for it, without damage to anyone else who is not interested in running C++/DLLs.

I also would like to note this moment. The compilation of several static libraries (gpr, grpc, grpc++) occurs into one DLL (grpc++), so we always allocate and free memory inside one dynamic library.

**Comment by nicolasnoble** [comment]
I agree with you about the bundling together of the three libraries, but surely the surface API does delegate objects to the application, right? @vjpai

**Comment by ikishchenko** [comment]
As we agree, we excluded from the pool request changes on bazel part for compilation of dlles.
Please, check and accept proposed change of encapsulation members to Getter/Setter methods.

**Comment by Maxpeng92** [comment]
Hi! @nicolasnoble & @ikishchenko , Do you have any follow ups on consuming grpc as dlls on windows? And could someone has similar requests as me point me to the right place to discuss this issue?

**Comment by ikishchenko** [comment]
> Hi! @nicolasnoble & @ikishchenko , Do you have any follow ups on consuming grpc as dlls on windows? And could someone has similar requests as me point me to the right place to discuss this issue?

We have been using GRPC as DLL for more than a year in production. No problems were detected.

**Comment by bjayanth** [comment]
@ikishchenko Is the fork that you use in production open source? Is it the `master-winbuild` on your fork of grpc or some other branch?
I am trying to do the same, build grpc as a dll, but it looks like I have to use bazel to build the dll (I saw the changes in one of your commits in this pull request). Is there also a CMakeLists with the same changes?

**Comment by ikishchenko** [comment]
> @ikishchenko Is the fork that you use in production open source? Is it the `master-winbuild` on your fork of grpc or some other branch?

I remove fork from my github account, but you can make [patch](https://patch-diff.githubusercontent.com/raw/grpc/grpc/pull/17137.patch) from this pull request and apply it to actual version of GRPC. In production we use old grpc 1.14.x

> I am trying to do the same, build grpc as a dll, but it looks like I have to use bazel to build the dll (I saw the changes in one of your commits in this pull request). Is there also a CMakeLists with the same changes?
For CMake: https://github.com/grpc/grpc/pull/14558

**Pull request closed without merging**
