### PR TITLE
Add conversion method for absl::Status to grpc_error*

### PR DESCRIPTION
**Pull request by drfloob**
While the conversion from grpc_error to absl::Status already existed, there were no tests for it, and the reverse conversion was not implemented. Converting in the reverse - from absl::Status to grpc_error - is needed for the EventEngine's iomgr implementation.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25896)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
Thanks for doing this!

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896#-:-MXcXD4i4EnrCRRjE6Wb:b-pevjuw)* status: all files reviewed, 6 unresolved discussions (waiting on @drfloob and @veblush)

___
*[src/core/lib/transport/error_utils.cc, line 145 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUJBj0SRFD_mFb19T:-MXcUJBj0SRFD_mFb19U:b-gu7en9) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L145)):*
> ```cpp
>   }
>   if (absl::IsCancelled(status)) {
>     return GRPC_ERROR_CANCELLED;
> ```

This conversion would lose any information that might be present in the message in `status`.

It might be better to not have this special-case at all.  Instead, we can just convert this to a real `grpc_error` (i.e., not `GRPC_ERROR_CANCELLED`), just like we're doing in the default case below.
___
*[src/core/lib/transport/error_utils.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcVqYT1_BVcf9FZqyU:-MXcVqYT1_BVcf9FZqyV:b-35bc3q) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L149)):*
> ```cpp
>   if (absl::IsResourceExhausted(status) &&
>       status.message() == "Out of memory") {
>     return GRPC_ERROR_OOM;
> ```

Same thing here.

I see that in this case, we're actually checking that `status.message()` is the same [message that we use for `GRPC_ERROR_OOM`](https://github.com/grpc/grpc/blob/c3e852b06fc502f7e94c3b905a843048e03c7698/src/core/lib/iomgr/error.cc#L462), so that we only return `GRPC_ERROR_OOM` if that would not lose the different message in `status`.  While that is technically correct, I'm not sure it's actually necessary; it seems like it would also be fine to just remove the special case for `GRPC_ERROR_OOM` and return a real `grpc_error` object here, regardless of the content of the message.
___
*[src/core/lib/transport/error_utils.cc, line 152 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUONo1hukNgg18Uze:-MXcUONo1hukNgg18Uzf:b813wg3) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L152)):*
> ```cpp
>   }
>   return grpc_error_set_int(
>       GRPC_ERROR_CREATE_FROM_COPIED_STRING(status.message().data()),
> ```

Is `message()` guaranteed to be nul-terminated?  I suspect not, since it's a `string_view`.

I think this has come up a few times now.  It might be a good idea to introduce a `GRPC_ERROR_CREATE_FROM_STRING_VIEW()` macro.
___
*[test/core/transport/error_utils_test.cc, line 27 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcWovkCGTBA-Msib-q:-MXcWovkCGTBA-Msib-r:bcmmchs) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/test/core/transport/error_utils_test.cc#L27)):*
> ```cpp
> namespace {
> 
> // ---- Ok Status ----
> ```

I see tests for all of the special cases here, but I don't see tests for a completely different status (e.g., `UNAVAILABLE`).
___
*[test/core/transport/error_utils_test.cc, line 37 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUU1EDbLKYqbkF6sl:-MXcUU1EDbLKYqbkF6sm:b8dc4fg) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/test/core/transport/error_utils_test.cc#L37)):*
> ```cpp
>   grpc_slice message;
>   ASSERT_TRUE(grpc_error_get_str(error, GRPC_ERROR_STR_GRPC_MESSAGE, &message));
>   char* cstr = grpc_slice_to_c_string(message);
> ```

Suggest using [`grpc_core::StringViewFromSlice()`](https://github.com/grpc/grpc/blob/c3e852b06fc502f7e94c3b905a843048e03c7698/src/core/lib/slice/slice_utils.h#L192) here.  That will make the code simpler to read (and incidentally avoid making two copies of the string).

Same thing throughout.
___
*[test/core/transport/error_utils_test.cc, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcVHaN5nok6FjoTPj9:-MXcVHaN5nok6FjoTPjA:b-ah0ak7) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/test/core/transport/error_utils_test.cc#L41)):*
> ```cpp
>   // Special error equivalent check
>   ASSERT_EQ(error, GRPC_ERROR_NONE);
> ```

Please remove blank lines within functions.

Same thing throughout.

**Review by drfloob — COMMENTED** [review]
Of course. Thanks for the review. I've made most of the changes, and replied to two suggestions that needed discussion.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896#-:-MXcnZeW8LXugzq52uoj:b-15ees8)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @markdroth and @veblush)

___
*[src/core/lib/transport/error_utils.cc, line 145 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUJBj0SRFD_mFb19T:-MXcdLWZ-0lJGSk_3ujl:bvgbhj2) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L145)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This conversion would lose any information that might be present in the message in `status`.

It might be better to not have this special-case at all.  Instead, we can just convert this to a real `grpc_error` (i.e., not `GRPC_ERROR_CANCELLED`), just like we're doing in the default case below.
</blockquote></details>

True, we would lose information. However, that suggestion would result in an incompatibility between `absl::CancelledError()` and `GRPC_ERROR_CANCELLED`. See [timer.h](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/timer.h#L65), where callbacks are to specifically check for GRPC_ERROR_CANCELLED. For the EventEngine-based iomgr's callbacks, if we use this conversion method, the conversion would likely go from GRPC_ERROR_CANCELLED -> absl::CancelledError -> [something]. If that [something] is not a GRPC_ERROR_CANCELLED as you suggest, I think we'll have issues. I'd recommend we try to maintain compatibility for now to ease the transition, and revisit the idea to break that compatibility (or replace grpc_error) at a later time.
___
*[src/core/lib/transport/error_utils.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcVqYT1_BVcf9FZqyU:-MXcgCes7BL9QtegVpri:b-34vmyd) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same thing here.

I see that in this case, we're actually checking that `status.message()` is the same [message that we use for `GRPC_ERROR_OOM`](https://github.com/grpc/grpc/blob/c3e852b06fc502f7e94c3b905a843048e03c7698/src/core/lib/iomgr/error.cc#L462), so that we only return `GRPC_ERROR_OOM` if that would not lose the different message in `status`.  While that is technically correct, I'm not sure it's actually necessary; it seems like it would also be fine to just remove the special case for `GRPC_ERROR_OOM` and return a real `grpc_error` object here, regardless of the content of the message.
</blockquote></details>

See above
___
*[src/core/lib/transport/error_utils.cc, line 152 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUONo1hukNgg18Uze:-MXcnCJs2DcLSrcHYCCJ:bp7lpy9) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L152)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is `message()` guaranteed to be nul-terminated?  I suspect not, since it's a `string_view`.

I think this has come up a few times now.  It might be a good idea to introduce a `GRPC_ERROR_CREATE_FROM_STRING_VIEW()` macro.
</blockquote></details>

Great catch! Done. I implemented it in terms of `grpc_slice_from_copied_buffer`.
___
*[test/core/transport/error_utils_test.cc, line 27 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcWovkCGTBA-Msib-q:-MXccQ3r5Xhbk_WDE65y:b8wb40c) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/test/core/transport/error_utils_test.cc#L27)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I see tests for all of the special cases here, but I don't see tests for a completely different status (e.g., `UNAVAILABLE`).
</blockquote></details>

The `AbslNonOOMResourceExhaustedToGrpcErrorIsNotSpecial` test is an example that exercises that code path, but I've added another for UNAVAILABLE.
___
*[test/core/transport/error_utils_test.cc, line 37 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUU1EDbLKYqbkF6sl:-MXccczW7krHpeBjETU_:boyexb3) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/test/core/transport/error_utils_test.cc#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest using [`grpc_core::StringViewFromSlice()`](https://github.com/grpc/grpc/blob/c3e852b06fc502f7e94c3b905a843048e03c7698/src/core/lib/slice/slice_utils.h#L192) here.  That will make the code simpler to read (and incidentally avoid making two copies of the string).

Same thing throughout.
</blockquote></details>

Done. Thanks!
___
*[test/core/transport/error_utils_test.cc, line 41 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcVHaN5nok6FjoTPj9:-MXcdB1S3quHqLgCL028:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/test/core/transport/error_utils_test.cc#L41)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank lines within functions.

Same thing throughout.
</blockquote></details>

Done.

**Review by drfloob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896)* status: 6 of 9 files reviewed, 6 unresolved discussions (waiting on @markdroth and @veblush)

___
*[src/core/lib/transport/error_utils.cc, line 145 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUJBj0SRFD_mFb19T:-MXcp5Sl-chwRiI7o3aL:btvlla7) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L145)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

True, we would lose information. However, that suggestion would result in an incompatibility between `absl::CancelledError()` and `GRPC_ERROR_CANCELLED`. See [timer.h](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/timer.h#L65), where callbacks are to specifically check for GRPC_ERROR_CANCELLED. For the EventEngine-based iomgr's callbacks, if we use this conversion method, the conversion would likely go from GRPC_ERROR_CANCELLED -> absl::CancelledError -> <something>. If that <something> is not a GRPC_ERROR_CANCELLED as you suggest, I think we'll have issues. I'd recommend we try to maintain compatibility for now to ease the transition, and revisit the idea to break that compatibility (or replace grpc_error) at a later time.
</blockquote></details>

Looks like Markdown bit me here. A couple of edits around the iomgr discussion, revised:

For the EventEngine-based iomgr's callbacks, if we use this conversion method, the conversion would likely go from GRPC_ERROR_CANCELLED -> absl::CancelledError -> **[some kind of grpc_error]** . If that **[some kind of grpc_error]** is not a GRPC_ERROR_CANCELLED as you suggest, I think we'll have issues. I'd recommend we try to maintain compatibility for now to ease the transition, and revisit the idea to break that compatibility (or replace grpc_error) at a later time.

**Review by veblush — APPROVED** [review]
It looks good assuming that this conversion function isn't expected to be complete so that it's okay to miss some data (e.g. payloads). Since I'm working to replace grpc_error with absl::Status, if it's worked out, this function will be able to be removed.

**Review by markdroth — CHANGES_REQUESTED** [review]
The changes all look good, just the two open discussion items (really a single issue) remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896#-:-MXcuoVm4Rk9afGPupoB:b7is6qi)* status: all files reviewed, 2 unresolved discussions (waiting on @drfloob and @veblush)

___
*[src/core/lib/transport/error_utils.cc, line 145 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUJBj0SRFD_mFb19T:-MXcsUX3CicdIvX1clbD:b1dy9fw) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L145)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Looks like Markdown bit me here. A couple of edits around the iomgr discussion, revised:

For the EventEngine-based iomgr's callbacks, if we use this conversion method, the conversion would likely go from GRPC_ERROR_CANCELLED -> absl::CancelledError -> **[some kind of grpc_error]** . If that **[some kind of grpc_error]** is not a GRPC_ERROR_CANCELLED as you suggest, I think we'll have issues. I'd recommend we try to maintain compatibility for now to ease the transition, and revisit the idea to break that compatibility (or replace grpc_error) at a later time.
</blockquote></details>

It might be a good idea to audit the codebase for uses of `GRPC_ERROR_CANCELLED` to see how frequently it actually gets used.  The timer case is the only one I know of offhand where that value is special-cased.  If it's the only case, then I think we can handle it as a one-off, which would be preferable to encoding that special case for all errors in this general-purpose conversion code.  I think that most engineers will be surprised that a general-purpose function like this would have a special case like this that strips off potentially useful information.

For the timer case, we can handle it by either (a) having the EE-based iomgr impl explicitly special-case `absl::IsCancelled()` in its timer code, or (b) changing the existing `grpc_timer` API to remove this special case.  (The latter might not be that hard, since most timer callbacks in practice check whether the error is `GRPC_ERROR_NONE` rather than checking whether it is `GRPC_ERROR_CANCELLED`.  This is because the error might actually be something different in the case of timer system shutdown.)
___
*[src/core/lib/transport/error_utils.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcVqYT1_BVcf9FZqyU:-MXcu9efBCkl2xeSs-D5:bu86b1c) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L149)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

See above
</blockquote></details>

I suspect that `GRPC_ERROR_OOM` is used in even fewer places than `GRPC_ERROR_CANCELLED`.  In fact, I can't recall a single place where I've actually used it in the entire time I've been working on gRPC.

**Review by drfloob — COMMENTED** [review]
Thanks, both. I've removed the special case handling so we retain the messages/payload, with one final followup question.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896#-:-MXdWIsm9JOm-DPCASgm:b-9a167f)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/transport/error_utils.cc, line 142 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXdW-s68-R6jzIepZgW:-MXdW-s68-R6jzIepZgX:buhczco) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L142)):*
> ```cpp
>   // Special error checks
>   if (status.ok()) {
>     return GRPC_ERROR_NONE;
> ```

@markdroth are you still ok with returning the special type here? absl::OkStatus() likely won't have messages we need to parse, but we'll lose them nonetheless.
___
*[src/core/lib/transport/error_utils.cc, line 145 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcUJBj0SRFD_mFb19T:-MXdVQcP3DM4NiKQ0CUE:b166ypg) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L145)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It might be a good idea to audit the codebase for uses of `GRPC_ERROR_CANCELLED` to see how frequently it actually gets used.  The timer case is the only one I know of offhand where that value is special-cased.  If it's the only case, then I think we can handle it as a one-off, which would be preferable to encoding that special case for all errors in this general-purpose conversion code.  I think that most engineers will be surprised that a general-purpose function like this would have a special case like this that strips off potentially useful information.

For the timer case, we can handle it by either (a) having the EE-based iomgr impl explicitly special-case `absl::IsCancelled()` in its timer code, or (b) changing the existing `grpc_timer` API to remove this special case.  (The latter might not be that hard, since most timer callbacks in practice check whether the error is `GRPC_ERROR_NONE` rather than checking whether it is `GRPC_ERROR_CANCELLED`.  This is because the error might actually be something different in the case of timer system shutdown.)
</blockquote></details>

Thanks for helping out with this. I've removed the special handling for `GRPC_ERROR_CANCELLED`, and I'll look into the EventEngine-based iomgr's timer code to handle this case.
___
*[src/core/lib/transport/error_utils.cc, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXcVqYT1_BVcf9FZqyU:-MXdVMaU3-G6h5v_Pu8a:b-5wuqyn) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L149)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I suspect that `GRPC_ERROR_OOM` is used in even fewer places than `GRPC_ERROR_CANCELLED`.  In fact, I can't recall a single place where I've actually used it in the entire time I've been working on gRPC.
</blockquote></details>

SGTM, I've removed special handling for that error.

**Review by markdroth — CHANGES_REQUESTED** [review]
The code looks great!  I think a bunch of the tests can be removed now.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896#-:-MXgmJ8KAIK5uYZUSEFm:b-cnh4aw)* status: all files reviewed, 7 unresolved discussions (waiting on @drfloob)

___
*[src/core/lib/transport/error_utils.cc, line 142 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXdW-s68-R6jzIepZgW:-MXgjYKRDnH3xckxhb64:bjn03l9) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L142)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

@markdroth are you still ok with returning the special type here? absl::OkStatus() likely won't have messages we need to parse, but we'll lose them nonetheless.
</blockquote></details>

Yes, this is fine.  Basically no one ever passes a message with OK status, and code mostly ignores it in that case anyway.
___
*[test/core/transport/error_utils_test.cc, line 30 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXgkWyqA4qBlKzvbpnN:-MXgkWyqA4qBlKzvbpnO:bcbbz5r) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L30)):*
> ```cpp
> TEST(ErrorUtilsTest, AbslOkToGrpcError) {
>   grpc_error* error = absl_status_to_grpc_error(absl::OkStatus());
>   // Status code checks
> ```

This case doesn't actually need to check the status code or error; it just need to check that the result is `GRPC_ERROR_NONE`.  The entire test can be one line:

```
EXPECT_EQ(GRPC_ERROR_NONE, absl_status_to_grpc_error(absl::OkStatus()));
```

Once we've checked that, the remaining code is basically just testing the behavior of `GRPC_ERROR_NONE` itself, which is not the responsibility of these tests.  I haven't looked, but this should be covered by tests of `grpc_error` elsewhere.
___
*[test/core/transport/error_utils_test.cc, line 52 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXgjoig0ExSwNdlKZH9:-MXgjoig0ExSwNdlKZHA:b18asct) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L52)):*
> ```cpp
> 
> // Loosely equivalent to GRPC_ERROR_NONE
> TEST(ErrorUtilsTest, GrpcOrdinaryErrorOkToAbslStatus) {
> ```

This test probably isn't useful, since we'll basically never see this case in reality.  No one is ever going to use anything other than `GRPC_ERROR_NONE` for OK status.

Also, even if they did, this test basically covers the exact same behavior as the `GrpcErrorUnavailableToAbslStatus` test below.
___
*[test/core/transport/error_utils_test.cc, line 62 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXgksICEW_q36Tc8oWN:-MXgksICEW_q36Tc8oWO:b-5cv1vr) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L62)):*
> ```cpp
> 
> // ---- Cancelled Status ----
> TEST(ErrorUtilsTest, AbslCancelledToGrpcError) {
> ```

Since there's no longer any special handling for `GRPC_ERROR_CANCELLED`, I don't think we need this test.  The `AbslUnavailableToGrpcError` test below covers the same thing.

I don't think we need to explicitly test that the result is *not* `GRPC_ERROR_CANCELLED`, since we don't have a special case for that in the code.
___
*[test/core/transport/error_utils_test.cc, line 86 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXglAh0B3sm_0uL2d8M:-MXglAh0B3sm_0uL2d8N:bsjbjxf) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L86)):*
> ```cpp
> }
> 
> TEST(ErrorUtilsTest, GrpcOrdinaryErrorCancelledToAbslStatus) {
> ```

This test is not useful; it covers exactly the same code as the `GrpcErrorUnavailableToAbslStatus` test below.
___
*[test/core/transport/error_utils_test.cc, line 96 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXglMCB-moWS0uaW41L:-MXglMCB-moWS0uaW41M:b-r2ay7s) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L96)):*
> ```cpp
> 
> // ---- OOM Status ----
> TEST(ErrorUtilsTest, AbslOOMToGrpcError) {
> ```

There's no more special case for `GRPC_ERROR_OOM`, so I don't think we need this test or the next one.
___
*[test/core/transport/error_utils_test.cc, line 140 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXglSgoAK0ngs0N_o65:-MXglSgoAK0ngs0N_o66:bsjbjxf) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L140)):*
> ```cpp
> }
> 
> TEST(ErrorUtilsTest, GrpcOrdinaryErrorOOMToAbslStatus) {
> ```

This test is not useful; it covers exactly the same code as the `GrpcErrorUnavailableToAbslStatus` test below.

**Review by drfloob — COMMENTED** [review]
Thanks Mark. There's less code to maintain now. Please take a look again.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896#-:-MXh8mOQ3pKTeQ48CQev:bomam0y)* status: all files reviewed, 7 unresolved discussions (waiting on @drfloob and @markdroth)

___
*[src/core/lib/transport/error_utils.cc, line 142 at r1](https://reviewable.io/reviews/grpc/grpc/25896#-MXdW-s68-R6jzIepZgW:-MXh8SZ68uhajxI2pMML:b-6mhywn) ([raw file](https://github.com/grpc/grpc/blob/ad8cb41df4f21945ab813f44e59837d9426e51d4/src/core/lib/transport/error_utils.cc#L142)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Yes, this is fine.  Basically no one ever passes a message with OK status, and code mostly ignores it in that case anyway.
</blockquote></details>

Great, thanks.
___
*[test/core/transport/error_utils_test.cc, line 30 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXgkWyqA4qBlKzvbpnN:-MXh5Zg63GqrS6HAXpZG:bn7w1l2) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This case doesn't actually need to check the status code or error; it just need to check that the result is `GRPC_ERROR_NONE`.  The entire test can be one line:

```
EXPECT_EQ(GRPC_ERROR_NONE, absl_status_to_grpc_error(absl::OkStatus()));
```

Once we've checked that, the remaining code is basically just testing the behavior of `GRPC_ERROR_NONE` itself, which is not the responsibility of these tests.  I haven't looked, but this should be covered by tests of `grpc_error` elsewhere.
</blockquote></details>

Good point. I've removed most of the test, and left the `GRPC_ERROR_UNREF(error);` part as documentation for proper grpc_error ownership transfer.
___
*[test/core/transport/error_utils_test.cc, line 52 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXgjoig0ExSwNdlKZH9:-MXh5wzM4IO3cWhVUpRb:bss4a2b) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L52)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This test probably isn't useful, since we'll basically never see this case in reality.  No one is ever going to use anything other than `GRPC_ERROR_NONE` for OK status.

Also, even if they did, this test basically covers the exact same behavior as the `GrpcErrorUnavailableToAbslStatus` test below.
</blockquote></details>

Removed.
___
*[test/core/transport/error_utils_test.cc, line 62 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXgksICEW_q36Tc8oWN:-MXh6BrtDDLYd4ETCKbr:b-3qwoil) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since there's no longer any special handling for `GRPC_ERROR_CANCELLED`, I don't think we need this test.  The `AbslUnavailableToGrpcError` test below covers the same thing.

I don't think we need to explicitly test that the result is *not* `GRPC_ERROR_CANCELLED`, since we don't have a special case for that in the code.
</blockquote></details>

This test serves as *executable documentation* of the asymmetric behavior of conversions, which I think may be surprising. To your point though, I removed everything except that ASSERT_NE check since that's all redundant, and I removed the other tests that effectively assert the same thing.
___
*[test/core/transport/error_utils_test.cc, line 86 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXglAh0B3sm_0uL2d8M:-MXh7Ofa0ztXCMao_u_b:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This test is not useful; it covers exactly the same code as the `GrpcErrorUnavailableToAbslStatus` test below.
</blockquote></details>

Removed
___
*[test/core/transport/error_utils_test.cc, line 96 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXglMCB-moWS0uaW41L:-MXh7ahm-RdWCNKhem3Q:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L96)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no more special case for `GRPC_ERROR_OOM`, so I don't think we need this test or the next one.
</blockquote></details>

Removed
___
*[test/core/transport/error_utils_test.cc, line 140 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXglSgoAK0ngs0N_o65:-MXh8cTqE3szkZWxdhdq:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L140)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This test is not useful; it covers exactly the same code as the `GrpcErrorUnavailableToAbslStatus` test below.
</blockquote></details>

Removed

**Review by markdroth — APPROVED** [review]
Just one remaining nit.  Feel free to merge after addressing.

Thanks for doing this!

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896#-:-MXheqXa81SrJYXID_p6:bu1la8t)* status: all files reviewed, 2 unresolved discussions (waiting on @drfloob)

___
*[test/core/transport/error_utils_test.cc, line 134 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXheX9-BAk8KV_L-NtQ:-MXheX9-BAk8KV_L-NtR:b8gb17j) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L134)):*
> ```cpp
> }
> 
> TEST(ErrorUtilsTest, GrpcSpecialErrorOOMToAbslStatus) {
> ```

This test we should keep, since we do need to convert `GRPC_ERROR_OOM` to the equivalent `Status`.

**Review by drfloob — COMMENTED** [review]
Thanks, will do.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25896#-:-MXhf_LyCPvlFu9NMh99:bvr1eqf)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[test/core/transport/error_utils_test.cc, line 134 at r4](https://reviewable.io/reviews/grpc/grpc/25896#-MXheX9-BAk8KV_L-NtQ:-MXhfNQu2IbWeEhPPnJv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/85f8160dbc0d9f8faa5febde0e0c87ba753d7812/test/core/transport/error_utils_test.cc#L134)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This test we should keep, since we do need to convert `GRPC_ERROR_OOM` to the equivalent `Status`.
</blockquote></details>

Done.

**Pull request merged**
