### PR TITLE
.proto and BUILD files can now in differnt dirs

### PR DESCRIPTION
**Pull request by makdharma**

### CODE REVIEW

**Comment by makdharma** [comment]
test this please

**Comment by makdharma** [comment]
test this please

**Comment by makdharma** [comment]
test this please

**Comment by makdharma** [comment]
test this please

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by makdharma** [comment]
Known failures:
gRPC_interop_pull_requests - #10839 
Tsan C - #10810 
Portability Tests Linux - #10880 
Bazel Full Build & Tests - Ignored
Basic Tests Windows - #9153 
Basic Tests Mac - Flake - fatal: unable to access 'https://github.com/madler/zlib/': Server aborted the SSL handshake
Basic Tests Linux - #10894

**Pull request merged**
