### PR TITLE
Update win RBE docker image to VS2019

### PR DESCRIPTION
**Pull request by jtattermusch**
- update the RBE docker image (to contain VS2019 instead of VS2015)
- regenerate RBE toolchain configuration (to use VS2019)

Basically followed steps from go/rbe-windows-user-guide

I also tried to upgrade the docker image to use VS2017 (= the version we're currently using for our cmake build on windows) but I wasn't able to make that work. IMHO the setup where we use VS2017 for our cmake build (which takes care of checking the compatibility with VS2017) and we use newer VS2019 for RBE builds actually makes sense.

### CODE REVIEW

**Comment by jtattermusch** [comment]
```
ERROR: T:/_bazel_output/pjdymepj/external/com_google_absl/absl/time/BUILD.bazel:28:11: Compiling absl/time/clock.cc failed: (Exit 1): cl.exe failed: error executing command
  cd T:/_bazel_output/pjdymepj/execroot/com_github_grpc_grpc
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows Kits\8.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\winrt;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Windows\Microsoft.NET\Framework64\;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\ContainerAdministrator\AppData\Local\Temp
    SET TMP=C:\Users\ContainerAdministrator\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/com_google_absl /Ibazel-out/x64_windows-opt-exec-5A65A9B/bin/external/com_google_absl /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /W3 /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_ENABLE_EXTENDED_ALIGNED_STORAGE /bigobj /wd4005 /wd4068 /wd4180 /wd4244 /wd4267 /wd4503 /wd4800 /Fobazel-out/x64_windows-opt-exec-5A65A9B/bin/external/com_google_absl/absl/time/_objs/time/clock.obj /c external/com_google_absl/absl/time/clock.cc
Execution platform: //third_party/toolchains:rbe_windows_2019
INFO: Elapsed time: 706.069s, Critical Path: 620.42s
INFO: 490 processes: 490 internal.
FAILED: Build did NOT complete successfully
```

**Comment by jtattermusch** [comment]
Looks like I also need to refresh the win toolchain configuration.

**Comment by jtattermusch** [comment]
CC @veblush - these are my experiments so far

**Comment by jtattermusch** [comment]
TODOs:
- lots of `cl : Command line warning D9002 : ignoring unknown option '-std=c++14'` warnings
-cannot find bash: `bash.exe failed: error executing command`

**Review by veblush — APPROVED** [review]
Thank you for doing this!

**Comment by jtattermusch** [comment]
I checked the test results and they are all unrelated to this change (python, C++ and ruby test flakiness, all of them outside of windows RBE).

**Pull request merged**
