### PR TITLE
Added the client and server configurations to the bench results proto.

### PR DESCRIPTION
**Pull request by dgquintas**
The added configurations also include the host of both parties. This is useful for reporting.

### CODE REVIEW

**Comment by vjpai** [comment]
LGTM.

**Comment by vjpai** [comment]
Please note that this pull request has compile-time errors.

**Comment by dgquintas** [comment]
Yes, I'm looking into those, which are strange... On the one hand, what doesn't work now (the return of ScenarioResult) shouldn't have worked in the past either (Histogram can't be copied). I can't reproduce locally. I'm forcing the compiler to be 4.6 to see if that makes any difference (Travis' version).

**Comment by ctiller** [comment]
Suspect something in the protos are forcing the RVO off in that compiler.
We were skirting the edges of the standard there anyway. Maybe we make
Histogram copyable?

**Comment by dgquintas** [comment]
Yes, I confirm: 4.6 tries to copy (and the failure is consistent with Travis'). 4.8 is smarter and moves the instance as Craig mentions. In fact, there's a *move* constructor but no *copy* one (public anyway).

Does anybody know why the operator= and copy ctor are private?

**Comment by dgquintas** [comment]
For the time being, I'll just change RunScenario to return a unique_ptr

**Comment by ctiller** [comment]
I think they're private because I didn't get time to implement them that
day (and didn't need to).

**Comment by ctiller** [comment]
unique_ptr SGTM.

**Comment by vjpai** [comment]
unique_ptr SGTM also

**Comment by dgquintas** [comment]
PTAL. Failures expected while issue #1688 is in the works.

**Comment by dgquintas** [comment]
Green

**Pull request merged**
