### PR TITLE
[logging] Add tests for cases where we don't send any metadata and improve debuggability

### PR DESCRIPTION
**Pull request by yashykt**

### CODE REVIEW

**Comment by ctiller** [comment]
This isn't passing tests, and also the error message is near useless to figure out what's going on:

image

**Comment by yashykt** [comment]
Ah I forgot to fix this test.

The trick to debugging these is to look at the matchers and see which one didn't match, and then compare what the expectation was and what was actually sent.

**Comment by yashykt** [comment]
Fixed it, and improving the error message as well.

**Review by ctiller — APPROVED** [review]
Approving with reservations: I think we're leaning on testing frameworks too heavily here, and we'd have a better test of we wrote some of these expectations directly.

Imagine:
EXPECT_EQ(entries.size(), 12);
auto* client_header_from_client = GetEntry(entries, kClientHeader, Logger::kClient);
EXPECT_EQ(client_header_from_client->authority, server_address_);
// etc...

the main test would be about as long (possibly shorter!), and the output would be crystal clear as to what the problem we're seeing is.

**Comment by yashykt** [comment]
> Approving with reservations: I think we're leaning on testing frameworks too heavily here, and we'd have a better test of we wrote some of these expectations directly.

Yeah, I think you are right. I'll switch these over.

**Pull request merged**
