### PR TITLE
Makefile: override AR when it has not the default value.

### PR DESCRIPTION
**Pull request by pedr000000**
Append to the AR make's variable the required options when the default
value os not used, namely when $(origin) does NOT return "default"

### CODE REVIEW

**Comment by pedr000000** [comment]
I signed it!

**Comment by nicolasnoble** [comment]
Sometimes, the AR command can be something that isn't going to accept "rcs", such as Mac's tools. I'm not sure this is a good change. I'd rather see people using `AR="ar rcs" make`.

**Comment by pedr000000** [comment]
Mumble mumble,  what about using  ARFLAGS?
Il 19/set/2016 19:07, "Nicolas Noble" <notifications@github.com> ha scritto:

**Comment by nicolasnoble** [comment]
I could get behind such a change.

**Pull request closed without merging**
