### PR TITLE
Add CMake Project

### PR DESCRIPTION
**Pull request by podsvirov**
Hey guys!

You are doing a good deal!

Community CMake of the  C++ world too will appreciate it!

I want a little help.

The work has only just begun and not all questions solved, but the technology is already working.

Please look like I build "Hello World" example:

https://github.com/podsvirov/grpc/wiki/grpc-cpp-helloworld-daddy

If the PR is applyed, I will continue to work on this topic.
I'm interested.

### CODE REVIEW

**Comment by ctiller** [comment]
This is ok to test.

**Comment by ctiller** [comment]
I think we're better off creating a templates/CMakeLists.txt.template file and driving this off the build file templating system that the rest of the build files use.

That way, it's easier to keep this up to date with changes in the build.yaml format, and a bit easier for us to maintain and test.

**Comment by podsvirov** [comment]
Generate code for code generator - sounds strange and sad to CMake.�The format of the build.yaml is fairly simple and straightforward. CMake cope with its analysis and work is already showing results.Necessary for CMake template files I have created in the folder for templates.�I don't know how well you are familiar with the CMake system, but it's not just a building - it is a complete project management from development to distribution and updates.�05.10.2015, 18:47, "Craig Tiller" <notifications@github.com>:> I think we're better off creating a templates/CMakeLists.txt.template file and driving this off the build file templating system that the rest of the build files use.>> That way, it's easier to keep this up to date with changes in the build.yaml format, and a bit easier for us to maintain and test.�I do not exclude the specified approach, but I think that functionality changes in build.yaml will also generate and change the associated template.�I still adhere to the approach laid me.�Regards,Konstantin Podsvirov�

**Comment by podsvirov** [comment]
I also spoke on this subject with Nicolas Noble in group:
https://groups.google.com/forum/#!topic/grpc-io/fbz7VmJPMmU

It would be interesting to hear his opinion.
Anyway, to come to a common denominator.

This code has worked for me on the Windows. Earlier I pointed out the description of the building of examples:
https://github.com/podsvirov/grpc/wiki/grpc-cpp-helloworld-daddy

There is a link to the project with binary packages:
http://dad.podsvirov.pro

**Comment by ctiller** [comment]
This needs to be generated by build.yaml as part of our normal build file generation process to be accepted.

**Comment by podsvirov** [comment]
Hello @ctiller,
i realized my mistakes and resurrecting the old ideas in #7553.

**Pull request closed without merging**
