### PR TITLE
Use more normal API for client channel connectivity watches from internal code

### PR DESCRIPTION
**Pull request by markdroth**
Built on #20405.  Only the last commit is new.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/20406)

### CODE REVIEW

**Comment by markdroth** [comment]
This depends on the changes in #20255, but I'm having to revert that PR in #20407 due to internal breakage, so this will have to be on hold until that can be rolled forward again.

**Comment by markdroth** [comment]
This is now built on #20408.

**Comment by AspirinSJL** [comment]
Sorry, I'm having some difficulty figuring out the pure diff for this PR. Could you please rebase? Or maybe there is some easy way to find the diff on reviewable.io but I don't know.

**Comment by markdroth** [comment]
Both of the PRs this was based on have now been merged, and I've merged in the changes from master and squashed my commits, so the diff should now show only the changes from this PR.

**Comment by markdroth** [comment]
Known issues: #20421 #20445 #20437

**Pull request merged**
