### PR TITLE
Added per-test XML reports for Node tests on Jenkins

### PR DESCRIPTION
**Pull request by murgatroid99**
This is based on #3878, so that should be merged first.

### CODE REVIEW

**Comment by murgatroid99** [comment]
This doesn't seem to work yet. It looks like Jenkins doesn't notice the XML file.

**Comment by nicolasnoble** [comment]
Sorry, I lied. The filename has to be `report.xml`, not `reports.xml`

**Comment by murgatroid99** [comment]
I don't think that worked.

**Comment by nicolasnoble** [comment]
Well... I am looking at the workspace for the node debug build that finished, and I don't see src/node/report.xml in there.

**Comment by nicolasnoble** [comment]
Still not it. image

**Comment by murgatroid99** [comment]
Well, I have no idea why it's not working. It works on my machine.

**Comment by nicolasnoble** [comment]
I'll let you toy with it a bit. You can add some debugging information to the PR to see why it's not generating the file properly, or so. It's easier by amending constantly a commit to see new debugging logs on Jenkins for example.

**Comment by murgatroid99** [comment]
Well, I know why this is happening. The Jenkins tests use the `--use_docker` flag. This runs `tools/jenkins/build_docker_and_run_tests.sh`, which only copies out `report.xml` in the root directory. I am not sure how to fix this.

**Comment by nicolasnoble** [comment]
How about something like this:

`find . -name report.xml -exec zip reports.zip`

at the end of `tools/jenkins/docker_run_tests.sh`, and removing the copy of that one `report.xml` in `build_docker_and_run_tests.sh`. That way, everything is done through that zip file for all of the reporting.

**Comment by murgatroid99** [comment]
It works now.

**Comment by murgatroid99** [comment]
All of the build failures were caused by #3889.

**Comment by nicolasnoble** [comment]
Can we rebuild that PR btw ?

**Pull request closed without merging**
