### PR TITLE
Add static method to generated code to return fully qualified protobuf service name

### PR DESCRIPTION
**Pull request by jeady**

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by yang-g** [comment]
jenkins: this is ok to test

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by jeady** [comment]
I'm not sure how my PR could cause these failures. Are these tests flaky?

**Comment by yang-g** [comment]
Known test failures: #10839 #9088 #9037 #5450 #10894

**Comment by jeady** [comment]
Thanks Yang!

**Pull request merged**
