### PR TITLE
Initial support for Haiku

### PR DESCRIPTION
**Pull request by korli**
This provides the baseline needed to build gRPC on Haiku systems.

At least one project has started using on gRPC as a dependency.

@drfloob

### CODE REVIEW

**Comment by drfloob** [comment]
Adding code for an unsupported platform is a complicated decision. I don't think we have a rule book for it (pinging @nicolasnoble in case we do). I don't have experience with Haiku ... evidently it's still in Beta, but has been so since ~2018.

Since we don't have the infrastructure for continuous integration on Haiku, or on any of the other community-supported platforms listed in the [supported platforms doc](https://github.com/grpc/grpc/tree/34fdb542b5dafcd84dcb0ce2137bb0ee2049aaaa/src/cpp#supported-platforms), gRPC may break on those platforms at any time, and the team likely won't have the resources to help out.

This looks like a pretty lightweight change, not much to maintain at this point. Are any/all of the tests passing on Haiku when you enable these macros?

**Comment by drfloob** [comment]
@korli friendly reping. The python3 migration has landed, your port_server issue should have cleared up. For community-supported platform ownership, please add something like the following to port_platform:

```
...
#elif defined(__HAIKU__)
// Haiku is a community-supported platform. Please contact Person <person@example.com> for support.
...
```

**Comment by Begasus** [comment]
> At least one project has started using on gRPC as a dependency.

@korli could you point me to it, looking into bumping our version at haikuports atm, but couldn't find anything there so far?

**Comment by Tevo45** [comment]
Hello; I apologize for asking, but is there any update on this? My Haiku Bazel port depends on this, but the PR seems to be stalled.

**Comment by korli** [comment]
@drfloob I fixed conflicts which  were pending. Which action is now required from me?

**Comment by drfloob** [comment]
@korli I started the CI for this change. If all goes well, I'll merge this in today.

**Comment by drfloob** [comment]
@korli Sanity checks were failing due to word wrap issues, so I fixed them and pushed to your branch. CI is running again.

**Review by drfloob — APPROVED** [review]

**Comment by drfloob** [comment]
The test failures are unrelated, LGTM. Thanks for the contribution @korli.

**Pull request merged**
