### PR TITLE
Made Fork.support_enabled_ atomic

### PR DESCRIPTION
**Pull request by veblush**

### CODE REVIEW

**Comment by gnossen** [comment]
@veblush Can you please do a cherrypick of this PR and verify that it fixes things?

**Comment by veblush** [comment]
I tested it and it showed it fixed the problem!

**Comment by gnossen** [comment]
Looks like we're seeing infrastructure flakes. Perhaps hitting our github requests/hour limit?

**Comment by veblush** [comment]
Yeah kokoro became flaky recently. So let's ignore irrelevant error.

**Pull request merged**
