### PR TITLE
Add code and message to base.NoSuchMethodError

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
This is part of support for applications being able to respond to RPCs
with unrecognized names with specific codes and messages.

### CODE REVIEW

**Comment by soltanmm** [comment]
Needs a rebase.

**Comment by nathanielmanistaatgoogle** [comment]
Rebased as needed.

**Comment by soltanmm** [comment]
Any particular reason only NoSuchMethodError is getting this treatment? I'd have thought other errors also have status codes/details as well.

Is the status in this case the low-level status of gRPC core or something entirely different? In either case, mind documenting the types involved?

**Comment by nathanielmanistaatgoogle** [comment]
NoSuchMethodError is getting treated alone in this commit because it stands apart from the other exceptions for the way it is raised by applications rather than by RPC Framework itself. The other exceptions will probably get initial_metadata, terminal_metadata, code, and details attributes in another commit sometime tomorrow.

The code in this case is "whatever the application passes to the NoSuchMethodError constructor", but yes, in practice, "the application" will be a gRPC-specific object that will pass a gRPC status code as the code value.

I would love to document the types involved but they're entirely parametric and Python doesn't really like that. What I wouldn't give for [first-class documentation support for type parameters...](http://docs.oracle.com/javase/1.5.0/docs/tooldocs/windows/javadoc.html#@param)

**Pull request merged**
