### PR TITLE
Break qps services into seperate protos

### PR DESCRIPTION
**Pull request by kpayson64**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Is this just refactoring or is there any rationale why this is important?

**Comment by kpayson64** [comment]
This is needed for a new experimental stack internally (bamm2).

We have a separate codegen for the bamm2 stack, but we want to be able to only generate the bamm2 code for the benchmark service, and use standard codgen for the service that talks to qps_json_driver.

**Comment by kpayson64** [comment]
#15119
#15120
#14969

**Pull request merged**
