### PR TITLE
Raise the exception while credential initialization

### PR DESCRIPTION
**Pull request by lidizheng**
Blocking issue https://github.com/grpc/grpc/pull/16971
Fixing issue https://github.com/grpc/grpc/issues/16718

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,021,646      Total (=)      2,021,646

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,934      Total (=)     11,177,934

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,021,646      Total (=)      2,021,646

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,934      Total (<)     11,177,935

 No significant differences in binary sizes


```

**Comment by lidizheng** [comment]
@mehrdada Thanks for pointing out. I have updated the code.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,021,324      Total (=)      2,021,324

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,663      Total (>)     11,177,654

 No significant differences in binary sizes


```

**Comment by mehrdada** [comment]
This probably should be in release notes, as a user-facing behavioral change?

**Comment by lidizheng** [comment]
@mehrdada Label updated.

**Pull request merged**
