### PR TITLE
Fix Python 3.7 Docker Environment

### PR DESCRIPTION
**Pull request by lidizheng**
Issue #16900
In short, an old version OpenSSL library dependency somehow sneaked into the build. I still attempt to locate the problem along the building procedure, but I found a not-elegant fix for the Python 3.7 Docker environment in `docker_run_tests.sh`.
* It doesn't copy files from the host into the container
* It use the volume directory to build the artifacts (key difference)
* So it may remain compiling files at the host's folder

More detail about the remaining files
* Most of it contained in `py37_native` folder
* It doesn't affect next build; you can repeat the `run_tests.py` without clean those files
* There is a dedicated `reports`
* To clean them with one command `git clean -xdf`

Also, without setting in `~/.bashrc`, `pyenv` won't switch Python version properly, and people who run this Docker image against `--compiler=python3.6` or `--compiler=python3.7` will encounter a command not found.

Key questions for @nicolasnoble 
1. Do you think this change is valid?
1. Is there other files need to be kept?
1. Is there any reason we can't clean the folder?

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by mehrdada** [comment]
cc @jtattermusch as he might have some perspective to add here as well

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,990,553      Total (=)      1,990,553

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,020,810      Total (>)     11,020,804

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by lidizheng** [comment]
@mehrdada I was wrong about changing the run script. It breaks tests. You
are right about that changing the Dockerfile is the easy way here. I will
close this pr.

**Pull request closed without merging**
