### PR TITLE
Removed redundant include paths from podspec

### LINKED ISSUE #2093: Don't use Cocoapods' implementation details in the podspec
See: https://github.com/grpc/grpc/blob/master/gRPC.podspec#L34

One way around it is, during installation (`prepare_command`), move all headers under `include/grpc/...` into `grpc/...` (i.e., remove the `include` element from their path).

### PR DESCRIPTION
**Pull request by murgatroid99**
This fixes #2093

### CODE REVIEW

**Comment by murgatroid99** [comment]
For the record, I used a clean clone of this repo just to make sure my tests were not affected by previous invocations of `pod install`

**Comment by nicolasnoble** [comment]
Unrelated to the core of that change, but pertinent to that last comment, we still need to work on testing the creation of the various packages.

**Comment by murgatroid99** [comment]
In this particular case, that comment would also not be necessary if we had automated testing of the Objective C library.

**Comment by jcanizales** [comment]
Is the same setting down in GRPCClient still necessary?

**Comment by murgatroid99** [comment]
I don't know what setting in GRPCClient you are talking about.

**Comment by jcanizales** [comment]
This one: https://github.com/grpc/grpc/blob/master/gRPC.podspec#L116

**Comment by murgatroid99** [comment]
It looks like that is still necessary. I can't compile without it.

**Comment by jcanizales** [comment]
Then we don't fix #2093 :(

One possible fix is as the TODO suggests: tell Cocoapods to move, on `pod install`, `/include/grpc/*` up as `/grpc/*`. Because the root of the repo is in the header search path (due to `header_mappings_dir` of the core subspec), `#include <grpc/...>` will work as well as `#include <src/core/...>`. It's still a workaround to https://github.com/CocoaPods/CocoaPods/issues/1437 (if we could specify the search paths explicitly we'd be set), but at least it's a supported one, unlike referencing the directories under `$(PODS_ROOT)`.

**Comment by murgatroid99** [comment]
OK, I've done that (moving the directory). It seems to work fine

**Comment by jcanizales** [comment]
Nice! :D

**Pull request merged**
