### PR TITLE
[xds_end2end_test] Remove wait_for_ready

### PR DESCRIPTION
**Pull request by yashykt**
Reduces the test runtime from ~2 minutes to ~36 seconds

### CODE REVIEW

**Comment by markdroth** [comment]
Doesn't removing wait_for_ready here just turn this into a busy loop?  Without wait_for_ready, the RPC will fail, and we'll just immediately try again, creating a whole new channel instead of waiting for the backoff in the channel we created for the past iteration.  Seems like this would significantly increase CPU usage.

**Comment by yashykt** [comment]
good point, not sure why I had the channel creation inside the loop.

**Comment by yashykt** [comment]
I see. The channel recreation was helping with the busy loop.

**Comment by markdroth** [comment]
I think wait_for_ready avoids the busy loop, not recreating the channel.  If we use wait_for_ready, then we avoid the busy loop, regardless of whether we recreate the channel for each attempt.  If we don't use wait_for_ready, then we have a busy loop, regardless of whether we recreate the channel for each attempt.

I don't think it's helpful to recreate the channel on each attempt, and I do think we should change it to avoid doing that, because it's adding unnecessary work in the test for no benefit.  But I think that change is orthogonal to the point of this PR, because it shouldn't affect the behavior either way.

**Comment by yashykt** [comment]
ok, yeah, you are right. Let me try to reduce the time taken in a smarter way.

**Pull request closed without merging**
