### PR TITLE
Don't send kwargs to unintended rule.

### PR DESCRIPTION
**Pull request by daicoden**
_generate_pb2_src has no other arguments to be configured by end users.
As documented, kwargs should be passed through to the py_library.

@veblush

### CODE REVIEW

**Comment by daicoden** [comment]
Thanks @gnosson - that would have hit me next.

**Comment by gnossen** [comment]
Optional: It would be nice if we had a test covering this in https://github.com/grpc/grpc/blob/master/bazel/test/python_test_repo/BUILD.

**Comment by daicoden** [comment]
@gnossen unfortunately the python_test_repo doesn't build on mac. 10.15.3.

Issue very similar to https://github.com/grpc/grpc/issues/13856.

Tried with both checked in bazel 1.0 , and 2.2.

**Comment by gnossen** [comment]
@daicoden I wasn't aware of the failure on MacOS. I was able to reproduce. Yes, this definitely looks like something that needs to be looked into.

**Comment by daicoden** [comment]
@gnossen I'm still fumbling around with bazel a bit, so if there's a better way let me know. I know it doesn't work on windows... but I couldn't figure out a way to actually assert the kwargs made it to the underlying rule.

i was reading starlark's unit testing guide... but I couldn't figure out how to test a rule received an argument. I guess I could use imports, and then assert PiInfo has the import.

**Comment by gnossen** [comment]
This is a pretty whitebox approach. For the moment, I think it's fine, but a more blackbox approach would be something like:
 - Specify `imports` in `py_proto_library` rule.
 - Create `py_test` with a dependency on said `py_proto_library`
 - Use test to verify that import ended up on `sys.path`

**Comment by daicoden** [comment]
@gnossen still want to merge this one?

**Pull request closed without merging**
