### PR TITLE
Fix fuzzer tests for Bazel

### PR DESCRIPTION
**Pull request by adelez**
Also piggyback a minor change to the build file for bad_ssl.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by adelez** [comment]
The fuzzer tests pass but Bazel Build Basic test is failing because of 
ERROR: /var/local/git/grpc/test/core/nanopb/BUILD:23:1: Traceback (most recent call last):
	File "/var/local/git/grpc/test/core/nanopb/BUILD", line 23
		grpc_fuzzer(name = "fuzzer_response", srcs = [..."], <3 more arguments>)
	File "/var/local/git/grpc/test/core/util/grpc_fuzzer.bzl", line 18, in grpc_fuzzer
		grpc_cc_test(name = name, srcs = srcs, deps = dep..."], <4 more arguments>)
	File "/var/local/git/grpc/test/core/util/grpc_fuzzer.bzl", line 26, in grpc_cc_test
		native.package_name()
struct has no method 'package_name'.

I'm looking.

**Comment by adelez** [comment]
The same test passed on Foundry with canary bazel.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by adelez** [comment]
Upgrading bazel to 0.9.0 worked.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
