### PR TITLE
Transforming gRPC.podspec to use build.json instead of globbing.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Are trainling commas supported ?

### CODE REVIEW

**Comment by murgatroid99** [comment]
This seems to have added all of the C++ headers and source files to the list. I don't think that's a good idea.

**Comment by nicolasnoble** [comment]
Right.

**Comment by murgatroid99** [comment]
By the way, the trailing comma is in fact valid.

**Comment by murgatroid99** [comment]
For the record, this won't work yet due to CocoaPods/CocoaPods#1437, as referenced in the existing podspec.

**Comment by jcanizales** [comment]
Ah right, we need to list `grpc_time.h` and `grpc_string.h` instead of `time.h` and `string.h`.

**Comment by nicolasnoble** [comment]
Yep, let's hold off until that is fixed upstream. There's no need to come
up with convoluted fixes in the template when this will eventually get
fixed.

**Comment by murgatroid99** [comment]
I'm sure the ruby failure is unrelated, so I'm merging

**Pull request merged**
