### PR TITLE
Upgrade protobuf dependency to 3.12.4.

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Any particular reason to move to `3.12.4`? There seems to be not much added since `3.12.2`, which we are currently at. See https://github.com/protocolbuffers/protobuf/commits/3.12.x. There seems to be just one Objective-C fix since `3.12.2`.

Protobuf team did just release `3.13.0` today (which was earlier called `4.0.0-rc`). There seems to be a lot more changes there. If we are to update the protobuf dependency, should we consider moving directly to `3.13.0`?

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc/pull/23485 is waiting on 3.13.0

**Comment by jtattermusch** [comment]
I created a PR for upgrade to 3.13.0 #23855.

**Comment by markdroth** [comment]
I was just doing this as part of the normal preparations for the next gRPC release.  When I looked at the protobuf repo, 3.12.4 was the latest version.  I'm fine with upgrading to 3.13 instead, as long as there are no problems with it.

**Pull request closed without merging**
