### PR TITLE
Fix leak credentials_test.cc

### PR DESCRIPTION
**Pull request by soheilhy**
Sorry that I introduced it in #19493

### CODE REVIEW

**Comment by jboeuf** [comment]
I don't understand what happened here. I had to change this code before merging my PR because gpr_split_host_port had been replaced by another function that took string_views. I checked master and it looks like we're back on the old code...

Anyway LGTM.

**Comment by soheilhy** [comment]
@jboeuf Thank you for the review. It's because of a rollback and this PR is my fault.

1) Problem started with me introducing a PR to add StringView to gRPC which changed the API.
2) You submitted your PR applying those API changes.
3) I rolledback the PR in (1).
4) Since rollback in (3) didn't rollback the API change in (2), I sent #19493.
5)  In #19493, I forgot to do `gpr_free`.

**Comment by soheilhy** [comment]
I'd need an official LGTM to merge this.

**Comment by soheilhy** [comment]
Actually I'm rolling forward. So, please hold off. Thanks

**Comment by jboeuf** [comment]
Checking in on this. Do you still need my LGTM or do you want to close the PR?

**Comment by soheilhy** [comment]
Oh sorry forgot to close this one.

**Pull request closed without merging**
