### PR TITLE
Updated python qps tests to use GA server API

### PR DESCRIPTION
**Pull request by kpayson64**
This should have been included as part of
45c0f2b3051bf1642337e109df57e8031cb654c8

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Change content looks great, but are you sure you mean 45c0f2b3051bf1642337e109df57e8031cb654c8 and not a6b2a5a090ff057f77976b22d854ff375883c1b9?

**Comment by kpayson64** [comment]
I think a6b2a5a090ff057f77976b22d854ff375883c1b9 got merged in first, so I'll own this one (I knew the server change was coming anyways).

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum.

**Comment by nicolasnoble** [comment]
GA polish or GA ?

**Comment by kpayson64** [comment]
I'd say GA, all the Python QPS data is missing ATM. 
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5760820306771968

**Comment by kpayson64** [comment]
@nicolasnoble 
This is a pretty safe 1 line change if you want to override and merge into master if your cutting the GA branch now.

**Pull request merged**
