### PR TITLE
Inline slice_add_indexed

### PR DESCRIPTION
**Pull request by ncteisen**
Testing

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
   +14%    +624 src/core/lib/slice/slice_buffer.cc                                                      +624   +14%
      +106%    +446 grpc_slice_buffer_trim_end                                                              +446  +106%
      [NEW]    +203 grpc_slice_embiggen                                                                     +203  [NEW]
       +29%    +192 grpc_slice_buffer_add                                                                   +192   +29%
       +21%    +170 slice_buffer_move_first_maybe_ref                                                       +170   +21%
       +29%     +36 grpc_slice_buffer_tiny_add                                                               +36   +29%
   +35%    +512 src/core/lib/slice/slice_string_helpers.cc                                              +512   +35%
       +41%    +524 grpc_slice_split_inner                                                                  +524   +41%
   +17%    +368 src/core/lib/compression/message_compress.cc                                            +368   +17%
      [NEW] +1.22Ki zlib_body(z_stream_s*, grpc_slice_buffer*, grpc_slice_buffer*, int (*)(z_stream_s*,  +1.22Ki  [NEW]
      [NEW]    +166 copy(grpc_slice_buffer*, grpc_slice_buffer*) [clone .isra.0]                            +166  [NEW]
       +24%      +7 [Unmapped]                                                                                +7   +24%
  +1.0%    +336 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +336  +1.0%
       +42%    +208 init_stream                                                                             +208   +42%
      +3.7%    +128 grpc_create_chttp2_transport                                                            +128  +3.7%
  +1.9%    +160 src/core/ext/transport/chttp2/transport/hpack_encoder.cc                                +160  +1.9%
      +144%    +157 begin_frame                                                                             +157  +144%
      +2.4%      +3 [Unmapped]                                                                                +3  +2.4%
  +7.5%    +122 src/core/tsi/alts/zero_copy_frame_protector/alts_zero_copy_grpc_protector.cc            +122  +7.5%
       +26%    +122 alts_zero_copy_grpc_protector_create                                                    +122   +26%
  +3.0%    +116 src/core/lib/security/transport/secure_endpoint.cc                                      +116  +3.0%
       +26%    +116 grpc_secure_endpoint_create                                                             +116   +26%
  +0.4%    +112 [Other]                                                                                 +112  +0.4%
  +1.4%     +96 src/core/lib/iomgr/resource_quota.cc                                                     +96  +1.4%
       +31%     +88 ru_allocated_slices                                                                      +88   +31%
      +3.0%      +8 [Unmapped]                                                                                +8  +3.0%
  +2.9%     +80 src/core/lib/http/httpcli.cc                                                             +80  +2.9%
       +14%     +80 internal_request_begin                                                                   +80   +14%
  +2.6%     +64 src/core/ext/filters/client_channel/http_connect_handshaker.cc                           +64  +2.6%
       +15%     +33 handshaker_factory_add_handshakers                                                       +33   +15%
      +4.3%     +32 on_read_done                                                                             +32  +4.3%
  +0.5%     +64 src/core/ext/transport/inproc/inproc_transport.cc                                        +64  +0.5%
       +12%     +72 message_transfer_locked                                                                  +72   +12%
  +8.6%     +64 src/core/lib/surface/byte_buffer.cc                                                      +64  +8.6%
       +15%     +24 grpc_raw_byte_buffer_from_reader                                                         +24   +15%
       +13%     +24 grpc_raw_compressed_byte_buffer_create                                                   +24   +13%
       +94%     +16 [Unmapped]                                                                               +16   +94%
  +2.6%     +48 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc               +48  +2.6%
      +7.2%     +48 grpc_core::(anonymous namespace)::CreateSockaddrResolver                                 +48  +7.2%
  +1.5%     +48 src/core/ext/filters/http/message_compress/message_compress_filter.cc                    +48  +1.5%
      +4.4%     +32 finish_send_message                                                                      +32  +4.4%
       +18%     +27 init_call_elem                                                                           +27   +18%
  +1.2%     +48 src/core/ext/filters/http/server/http_server_filter.cc                                   +48  +1.2%
      +1.8%     +48 server_filter_incoming_metadata(grpc_call_element*, grpc_metadata_batch*) [clone .is     +48  +1.8%
  +1.4%     +48 src/core/lib/iomgr/tcp_custom.cc                                                         +48  +1.4%
       +12%     +50 custom_read_callback                                                                     +50   +12%
  +1.2%     +48 src/core/lib/security/transport/security_handshaker.cc                                   +48  +1.2%
       +18%     +48 grpc_security_handshaker_create                                                          +48   +18%
  +1.0%     +48 src/core/tsi/fake_transport_security.cc                                                  +48  +1.0%
       +47%     +48 tsi_create_fake_zero_copy_grpc_protector                                                 +48   +47%
  +2.8%     +40 src/core/tsi/alts/zero_copy_frame_protector/alts_grpc_integrity_only_record_protocol     +40  +2.8%
       +18%     +40 alts_grpc_integrity_only_record_protocol_create                                          +40   +18%
  +1.4%     +32 src/core/lib/channel/handshaker.cc                                                       +32  +1.4%
      +7.2%     +32 grpc_handshake_manager_do_handshake                                                      +32  +7.2%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.1%    -486 [None]                                                                               +11.3Ki  +0.1%

  +0.2% +2.53Ki TOTAL                                                                                +14.3Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -80  -0.0%

  [ = ]       0 TOTAL      -80  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +2.3% +2.09Ki [Other]                                                                              +2.09Ki  +2.3%
  +5.3% +1.73Ki src/core/ext/transport/chttp2/transport/chttp2_transport.cc                          +1.73Ki  +5.3%
      [NEW] +2.02Ki close_from_api                                                                       +2.02Ki  [NEW]
       +47%    +412 destroy_stream_locked                                                                   +412   +47%
       +32%    +352 grpc_chttp2_maybe_complete_recv_message                                                 +352   +32%
       +47%    +282 grpc_chttp2_maybe_complete_recv_trailing_metadata                                       +282   +47%
       +45%    +267 grpc_chttp2_unref_transport                                                             +267   +45%
       +17%    +160 read_action_locked                                                                      +160   +17%
       +98%    +149 grpc_chttp2_maybe_complete_recv_initial_metadata                                        +149   +98%
       +22%    +106 grpc_chttp2_fake_status                                                                 +106   +22%
       +29%     +56 send_goaway                                                                              +56   +29%
      [NEW]     +46 post_destructive_reclaimer(grpc_chttp2_transport*) [clone .part.29]                      +46  [NEW]
      [NEW]     +43 post_benign_reclaimer(grpc_chttp2_transport*) [clone .part.28]                           +43  [NEW]
   +22%    +960 src/core/lib/slice/slice_buffer.cc                                                      +960   +22%
       +56%    +369 grpc_slice_buffer_add                                                                   +369   +56%
      +344%    +347 grpc_slice_buffer_add_indexed                                                           +347  +344%
      +184%    +230 grpc_slice_buffer_tiny_add                                                              +230  +184%
       +71%    +168 grpc_slice_buffer_destroy                                                               +168   +71%
       +54%    +127 grpc_slice_buffer_reset_and_unref                                                       +127   +54%
       +15%     +64 grpc_slice_buffer_move_first_into_buffer                                                 +64   +15%
       +84%     +61 grpc_slice_buffer_undo_take_first                                                        +61   +84%
   +11%    +928 src/core/ext/transport/chttp2/transport/hpack_encoder.cc                                +928   +11%
      +296%    +323 begin_frame                                                                             +323  +296%
       +40%    +288 add_key_with_index                                                                      +288   +40%
       +62%    +213 get_wire_value                                                                          +213   +62%
      +8.9%     +64 emit_lithdr_noidx_v                                                                      +64  +8.9%
      +8.9%     +64 emit_lithdr_incidx_v                                                                     +64  +8.9%
      [NEW]     +31 add_wire_value(framer_state*, wire_value) [clone .isra.8]                                +31  [NEW]
   +11%    +808 src/core/lib/iomgr/tcp_posix.cc                                                         +808   +11%
       +18%    +173 tcp_flush                                                                               +173   +18%
       +92%    +140 tcp_read_allocation_done                                                                +140   +92%
       +12%    +125 tcp_do_read                                                                             +125   +12%
       +14%     +91 tcp_handle_read                                                                          +91   +14%
       +91%     +89 tcp_unref                                                                                +89   +91%
      +259%     +70 tcp_destroy                                                                              +70  +259%
       +49%     +56 grpc_tcp_destroy_and_release_fd                                                          +56   +49%
       +31%     +56 tcp_read                                                                                 +56   +31%
      +4.5%      +8 [Unmapped]                                                                                +8  +4.5%
   +18%    +674 src/core/lib/security/transport/secure_endpoint.cc                                      +674   +18%
      +169%    +255 destroy                                                                                 +255  +169%
       +14%    +165 on_read                                                                                 +165   +14%
       +12%    +144 endpoint_write                                                                          +144   +12%
       +48%     +75 endpoint_read                                                                            +75   +48%
      +7.7%     +34 grpc_secure_endpoint_create                                                              +34  +7.7%
      +1.0%      +1 [Unmapped]                                                                                +1  +1.0%
  +2.6%    +416 src/core/lib/surface/call.cc                                                            +416  +2.6%
      [NEW]    +594 set_encodings_accepted_by_peer(grpc_call*, grpc_mdelem, unsigned int*, bool) [clone     +594  [NEW]
      +8.8%    +170 grpc_call_create                                                                        +170  +8.8%
      +5.0%     +62 finish_batch_step                                                                        +62  +5.0%
       +22%     +52 get_final_status_from                                                                    +52   +22%
      +1.5%     +48 call_start_batch                                                                         +48  +1.5%
   +25%    +400 src/core/tsi/alts/zero_copy_frame_protector/alts_zero_copy_grpc_protector.cc            +400   +25%
      +368%    +272 alts_zero_copy_grpc_protector_destroy                                                   +272  +368%
      [NEW]    +266 create_alts_grpc_record_protocol(unsigned char const*, unsigned long, bool, bool, bo    +266  [NEW]
       +22%    +133 alts_zero_copy_grpc_protector_unprotect                                                 +133   +22%
   +18%    +338 src/core/lib/slice/percent_encoding.cc                                                  +338   +18%
       +19%    +119 grpc_strict_percent_decode_slice                                                        +119   +19%
       +22%    +106 grpc_percent_encode_slice                                                               +106   +22%
       +15%     +98 grpc_permissive_percent_decode_slice                                                     +98   +15%
       +52%     +15 [Unmapped]                                                                               +15   +52%
   +14%    +336 src/core/ext/filters/client_channel/http_connect_handshaker.cc                          +336   +14%
      +156%    +175 http_connect_handshaker_unref                                                           +175  +156%
       +22%    +161 on_read_done                                                                            +161   +22%
      +150%      +3 http_connect_handshaker_destroy                                                           +3  +150%
   +23%    +336 src/core/tsi/alts/zero_copy_frame_protector/alts_grpc_integrity_only_record_protocol    +336   +23%
       +34%    +228 alts_grpc_integrity_only_unprotect                                                      +228   +34%
      +248%    +104 alts_grpc_integrity_only_destruct                                                       +104  +248%
       +18%      +4 [Unmapped]                                                                                +4   +18%
  +9.0%    +304 src/core/lib/iomgr/tcp_custom.cc                                                        +304  +9.0%
       +35%    +148 custom_read_callback                                                                    +148   +35%
       +32%     +82 tcp_read_allocation_done                                                                 +82   +32%
       +67%     +72 endpoint_read                                                                            +72   +67%
      +1.2%      +2 [Unmapped]                                                                                +2  +1.2%
  +7.3%    +304 src/core/lib/security/transport/security_handshaker.cc                                  +304  +7.3%
      +131%    +186 security_handshaker_unref                                                               +186  +131%
       +13%     +72 on_handshake_next_done_locked                                                            +72   +13%
      +6.9%     +27 move_read_buffer_into_handshake_buffer                                                   +27  +6.9%
       +12%     +19 [Unmapped]                                                                               +19   +12%
  +5.7%    +304 src/core/lib/surface/channel.cc                                                         +304  +5.7%
       +27%    +160 grpc_channel_create_call                                                                +160   +27%
       +41%    +144 grpc_channel_create_pollset_set_call                                                    +144   +41%
   +20%    +304 src/core/lib/transport/byte_stream.cc                                                   +304   +20%
       +39%    +187 grpc_core::ByteStreamCache::CachingByteStream::Pull                                     +187   +39%
      +178%     +89 grpc_core::ByteStreamCache::Destroy                                                      +89  +178%
       +16%     +40 grpc_core::SliceBufferByteStream::Pull                                                   +40   +16%
   +22%    +256 src/core/tsi/alts/zero_copy_frame_protector/alts_grpc_privacy_integrity_record_proto    +256   +22%
       +36%    +191 alts_grpc_privacy_integrity_unprotect                                                   +191   +36%
       +16%     +64 alts_grpc_privacy_integrity_protect                                                      +64   +16%
      +6.2%      +1 [Unmapped]                                                                                +1  +6.2%
  +7.8%    +245 src/core/ext/filters/http/message_compress/message_compress_filter.cc                   +245  +7.8%
      +357%    +107 destroy_call_elem                                                                       +107  +357%
       +81%     +70 send_message_on_complete                                                                 +70   +81%
      +7.2%     +53 finish_send_message                                                                      +53  +7.2%
       +15%     +15 [Unmapped]                                                                               +15   +15%
  +4.8%    +224 src/core/tsi/fake_transport_security.cc                                                 +224  +4.8%
      +352%    +176 fake_zero_copy_grpc_protector_destroy                                                   +176  +352%
      +9.4%     +50 fake_zero_copy_grpc_protector_unprotect                                                  +50  +9.4%
  +9.0%    +208 src/core/lib/transport/metadata_batch.cc                                                +208  +9.0%
       +76%    +133 grpc_attach_md_to_error                                                                 +133   +76%
       +49%     +68 grpc_metadata_batch_set_value                                                            +68   +49%
      +4.6%      +7 [Unmapped]                                                                                +7  +4.6%
  +6.3%    +176 src/core/lib/http/httpcli.cc                                                            +176  +6.3%
       +78%    +184 finish                                                                                  +184   +78%
      +9.1%      +8 [Unmapped]                                                                                +8  +9.1%
  +5.2%    +176 src/core/lib/transport/metadata.cc                                                      +176  +5.2%
       +17%    +235 grpc_mdelem_create                                                                      +235   +17%

 -------------- SHRINKING                                                                            --------------
  -2.9%    -192 src/core/lib/iomgr/error.cc                                                             -192  -2.9%
     -25.3%     -87 internal_set_str                                                                         -87 -25.3%
     -20.4%     -85 grpc_error_unref                                                                         -85 -20.4%
      -3.4%     -24 copy_error_and_unref                                                                     -24  -3.4%
 -10.3%    -144 src/core/ext/transport/chttp2/transport/frame_goaway.cc                                 -144 -10.3%
     -31.0%    -144 grpc_chttp2_goaway_append                                                               -144 -31.0%
 -10.3%     -96 src/core/ext/transport/chttp2/transport/frame_ping.cc                                    -96 -10.3%
     -40.7%     -87 grpc_chttp2_ping_create                                                                  -87 -40.7%
     -42.9%      -9 [Unmapped]                                                                                -9 -42.9%
 -11.5%     -96 src/core/ext/transport/chttp2/transport/frame_rst_stream.cc                              -96 -11.5%
     -50.0%     -94 grpc_chttp2_rst_stream_create                                                            -94 -50.0%
     -25.0%      -2 [Unmapped]                                                                                -2 -25.0%
  -8.3%     -80 src/core/ext/transport/chttp2/transport/frame_window_update.cc                           -80  -8.3%
     -37.1%     -89 grpc_chttp2_window_update_create                                                         -89 -37.1%
  -2.0%     -67 src/core/ext/transport/chttp2/transport/frame_data.cc                                    -67  -2.0%
     -18.0%     -83 grpc_chttp2_data_parser_parse                                                            -83 -18.0%
     -11.8%     -34 grpc_chttp2_encode_data                                                                  -34 -11.8%
  -0.7%     -32 src/core/ext/filters/message_size/message_size_filter.cc                                 -32  -0.7%
      -9.1%     -15 grpc_core::SliceHashTable<grpc_core::RefCountedPtr<grpc_core::(anonymous namespace):     -15  -9.1%
      -1.8%      -9 init_call_elem                                                                            -9  -1.8%
      -6.0%      -8 [Unmapped]                                                                                -8  -6.0%
  -1.5%     -32 src/core/ext/transport/chttp2/client/secure/secure_channel_create.cc                     -32  -1.5%
      -2.4%     -33 client_channel_factory_create_subchannel                                                 -33  -2.4%
  -1.5%     -32 src/core/lib/compression/stream_compression_gzip.cc                                      -32  -1.5%
      -1.8%     -29 gzip_flate                                                                               -29  -1.8%
      -8.3%      -3 [Unmapped]                                                                                -3  -8.3%
  -0.4%     -32 src/core/lib/security/credentials/jwt/jwt_verifier.cc                                    -32  -0.4%
     -10.3%     -12 verifier_cb_ctx_destroy                                                                  -12 -10.3%
      -3.2%      -8 [Unmapped]                                                                                -8  -3.2%
     -14.0%      -6 grpc_jwt_claims_destroy                                                                   -6 -14.0%
     -17.6%      -6 jose_header_destroy                                                                       -6 -17.6%
  -0.1%     -18 src/core/ext/filters/client_channel/client_channel.cc                                    -18  -0.1%
      [DEL]    -181 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    -181  [DEL]
     -10.3%     -24 grpc_core::SliceHashTable<grpc_core::RefCountedPtr<grpc_core::internal::ClientChanne     -24 -10.3%
      -2.8%     -16 cc_destroy_call_elem                                                                     -16  -2.8%
      -2.5%     -16 grpc_core::RefCountedPtr<grpc_core::SliceHashTable<grpc_core::RefCountedPtr<grpc_cor     -16  -2.5%
      -3.5%     -10 grpc_core::RefCountedPtr<grpc_core::internal::ClientChannelMethodParams> grpc_core::     -10  -3.5%
  -0.1%     -16 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           -16  -0.1%
      [DEL] -1.98Ki grpc_core::(anonymous namespace)::GrpcLb::CreateOrUpdateRoundRobinPolicyLocked() [cl -1.98Ki  [DEL]
      -7.3%     -16 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::~BalancerCallState          -16  -7.3%
      -1.0%     -16 grpc_core::(anonymous namespace)::GrpcLb::StartBalancerCallLocked                        -16  -1.0%
      -1.4%      -5 [Unmapped]                                                                                -5  -1.4%
  -1.0%     -16 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_channel_secure.cc            -16  -1.0%
     -10.8%     -16 grpc_core::SliceHashTable<std::unique_ptr<char, grpc_core::DefaultDelete<char> > >::     -16 -10.8%
  -0.6%     -16 src/core/ext/filters/client_channel/uri_parser.cc                                        -16  -0.6%
     -11.0%     -24 decode_and_copy_component                                                                -24 -11.0%
  -0.8%     -16 src/core/lib/slice/b64.cc                                                                -16  -0.8%
      -1.6%      -9 grpc_base64_decode_with_len                                                               -9  -1.6%
     -14.6%      -7 [Unmapped]                                                                                -7 -14.6%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.5% -3.22Ki [None]                                                                               +43.7Ki  +0.5%

  +0.5% +7.26Ki TOTAL                                                                                +54.1Ki  +0.6%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                        cpu_time    real_time
-----------------------------------------------  ----------  -----------
BM_HpackEncoderEncodeHeader<EmptyBatch>/1/16384  -11%        -11%
```

**Comment by ncteisen** [comment]
I agree. I will post data as soon as I can get to my desk this week

**Comment by ncteisen** [comment]
Looks like this greatly reduced the time spent on GRPC_SLICE_MALLOC (and thus begin_frame has fallen from 1st to under 10th). But slice_buffer_add_indexed is still doing an extra copy on the line:
```
sb->slices[out] = s;
```

Before:
before

After:
after

**Comment by nicolasnoble** [comment]
Is `grpc_slice_buffer_add_indexed_internal` inlined ?

Also, it's looking like we've pushed a lot of the time to this one function. Which is good in the sense we now have a heavy weight function to look at for optimization.

**Comment by ncteisen** [comment]
No impact

**Pull request closed without merging**
