### PR TITLE
Revert "added grpclb support to sockaddr resolver"

### PR DESCRIPTION
**Pull request by ctiller**
Reverts grpc/grpc#5933

### CODE REVIEW

**Comment by ctiller** [comment]
This PR broke the build: it conflicts with another change that removed a variable this change depends on.

**Comment by jtattermusch** [comment]
You were 30 seconds faster than I was in finding the root cause :-).

**Comment by ctiller** [comment]
When restoring, please move URI parsing to the URI parser.

**Comment by jtattermusch** [comment]
I'll wait for some tests to become green and then I'll merge.

**Comment by ctiller** [comment]
(IOW: query parts should be part of grpc_uri, instead of having a different potentially incompatible parser in each resolver).

**Comment by jtattermusch** [comment]
@dgquintas  FYI

**Pull request merged**
