### PR TITLE
[core] fix compilation with clang-16 and libc++/libstdc++

### PR DESCRIPTION
**Pull request by dpronin**
```
[  7%] Building CXX object CMakeFiles/grpc_unsecure.dir/src/core/ext/filters/channel_idle/idle_filter_state.cc.o
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/ext/filters/census/grpc_context.cc:26:
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/debug/trace.h:34:
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/gprpp/global_config.h:91:
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/gprpp/global_config_env.h:27:
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/gprpp/memory.h:24:
In file included from /usr/include/c++/v1/memory:898:
In file included from /usr/include/c++/v1/__memory/shared_ptr.h:31:
/usr/include/c++/v1/__memory/unique_ptr.h:63:19: error: invalid application of 'sizeof' to an incomplete type 'grpc_server_config_fetcher'
    static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
                  ^~~~~~~~~~~
/usr/include/c++/v1/__memory/unique_ptr.h:297:7: note: in instantiation of member function 'std::default_delete<grpc_server_config_fetcher>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/usr/include/c++/v1/__memory/unique_ptr.h:231:5: note: in instantiation of member function 'std::unique_ptr<grpc_server_config_fetcher>::reset' requested here
    reset(__u.release());
    ^
/home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/surface/server.h:145:21: note: in instantiation of member function 'std::unique_ptr<grpc_server_config_fetcher>::operator=' requested here
    config_fetcher_ = std::move(config_fetcher);
                    ^
/home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/include/grpc/grpc.h:458:16: note: forward declaration of 'grpc_server_config_fetcher'
typedef struct grpc_server_config_fetcher grpc_server_config_fetcher;
               ^
[  7%] Built target grpc_python_plugin
```

src/core/lib/surface/server.h: Server::set_config_fetcher() function  must be defined below the definition of the type
'struct grpc_server_config_fetcher' because std::unique_ptr must know how type looks like at the place where the smart pointer calls a deleter

### CODE REVIEW

**Comment by dpronin** [comment]
```
[  7%] Building CXX object CMakeFiles/grpc_unsecure.dir/src/core/ext/filters/channel_idle/idle_filter_state.cc.o
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/ext/filters/census/grpc_context.cc:26:
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/debug/trace.h:34:
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/gprpp/global_config.h:91:
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/gprpp/global_config_env.h:27:
In file included from /home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/gprpp/memory.h:24:
In file included from /usr/include/c++/v1/memory:898:
In file included from /usr/include/c++/v1/__memory/shared_ptr.h:31:
/usr/include/c++/v1/__memory/unique_ptr.h:63:19: error: invalid application of 'sizeof' to an incomplete type 'grpc_server_config_fetcher'
    static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
                  ^~~~~~~~~~~
/usr/include/c++/v1/__memory/unique_ptr.h:297:7: note: in instantiation of member function 'std::default_delete<grpc_server_config_fetcher>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/usr/include/c++/v1/__memory/unique_ptr.h:231:5: note: in instantiation of member function 'std::unique_ptr<grpc_server_config_fetcher>::reset' requested here
    reset(__u.release());
    ^
/home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/src/core/lib/surface/server.h:145:21: note: in instantiation of member function 'std::unique_ptr<grpc_server_config_fetcher>::operator=' requested here
    config_fetcher_ = std::move(config_fetcher);
                    ^
/home/dpronin/.conan2/p/t/grpc7af12e0c3f76b/b/src/include/grpc/grpc.h:458:16: note: forward declaration of 'grpc_server_config_fetcher'
typedef struct grpc_server_config_fetcher grpc_server_config_fetcher;
               ^
[  7%] Built target grpc_python_plugin
```

**Comment by dpronin** [comment]
@yashykt may you check the PR? Thanks in advance

**Comment by dpronin** [comment]
@timburks @beccasaurus @hassox may someone assist me in this PR?

**Comment by dpronin** [comment]
@yashykt @grpc-kokoro @hassox @beccasaurus how do we proceed?

**Review by yashykt — APPROVED** [review]

**Comment by yashykt** [comment]
Thanks for the contribution!

**Review by drfloob — APPROVED** [review]

**Comment by dpronin** [comment]
@yashykt @drfloob what should be done from me to finally merge it in?

**Comment by dpronin** [comment]
@yashykt @hassox @drfloob ping

**Comment by dpronin** [comment]
@yashykt @drfloob @grpc-kokoro @hassox ping

**Comment by yashykt** [comment]
Sorry for the delay

**Comment by dpronin** [comment]
> Sorry for the delay

Nevermind. So, what are we waiting for?

**Comment by yashykt** [comment]
ah, iwyu is failing. You need to run `tools/distrib/iwyu.sh`. I'll maybe it run it myself and push the commit

**Comment by dpronin** [comment]
@yashykt I ran it myself and see that the issue has not been related to my changes, at least I don't see the root cause that might be the case

```
+ tools/distrib/gen_compilation_database.py --include_headers --ignore_system_headers --dedup_targets '//:*' //src/core/... //src/cpp/ext/gsm/... //src/cpp/ext/otel/... //src/compiler/... //test/core/... //test/cpp/... //fuzztest/... //test/cpp/common:time_jump_test //test/cpp/common:time_jump_test@poller=epoll1 //test/cpp/common:time_jump_test@poller=poll //test/cpp/end2end:cfstream_test //test/cpp/end2end:cfstream_test@poller=epoll1 //test/cpp/end2end:cfstream_test@poller=poll //test/cpp/end2end:flaky_network_test //test/cpp/end2end:flaky_network_test@poller=epoll1 //test/cpp/end2end:flaky_network_test@poller=poll //test/cpp/microbenchmarks:bm_basic_work_queue //test/cpp/microbenchmarks:bm_callback_streaming_ping_pong //test/cpp/microbenchmarks:bm_callback_streaming_ping_pong@poller=epoll1 //test/cpp/microbenchmarks:bm_callback_streaming_ping_pong@poller=poll //test/cpp/microbenchmarks:bm_callback_unary_ping_pong //test/cpp/microbenchmarks:bm_callback_unary_ping_pong@poller=epoll1 //test/cpp/microbenchmarks:bm_callback_unary_ping_pong@poller=poll
ERROR: Traceback (most recent call last):
	File "/home/dpronin/.cache/bazel/_bazel_dpronin/4fc932cbe6e70591698d99c563e32441/external/rules_cc/cc/private/rules_impl/compiler_flag.bzl", line 17, column 76, in <toplevel>
		load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain", "use_cpp_toolchain")
Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)
```

**Comment by yashykt** [comment]
It's probably a setup issue on your end. Just ran sanity and uploaded the commit

**Comment by dpronin** [comment]
@yashykt @drfloob @mehrdada again, guys, who is aware of what is going on in your CI? From my side there have been made a PR with cosmetic changes those cannot have been merged in for almost a month

**Comment by dpronin** [comment]
@yashykt ping

**Comment by dpronin** [comment]
@yashykt ping

**Comment by yashykt** [comment]
ah, need to run the tests again

**Comment by yashykt** [comment]
> again, guys, who is aware of what is going on in your CI? From my side there have been made a PR with cosmetic changes those cannot have been merged in for almost a month

Setting up the dev environment for grpc/grpc admittedly takes some time, but once you have set it up, running `tools/distrib/sanitize.sh` fixes most of the issues that you are seeing.

**Comment by yashykt** [comment]
Please don't revert my changes, IWYU is complaining again.

**Pull request merged**
