### PR TITLE
Added system roots feature to load roots from OS trust store

### PR DESCRIPTION
**Pull request by tdbhacks**
Added a flag-guarded feature that allows gRPC to load TLS/SSL
roots from the OS trust store. This is the Linux-specific
implementation of such feature.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/16083)

### CODE REVIEW

**Comment by jiangtaoli2016** [comment]
Thanks @tdbhacks for this PR.
@yihuazhang Could you please take the first pass?
@markdroth Could you please check grpc coding standards?
I will be out of office next week.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   668,635       Core (>)        666,642

 1,978,398      Total (>)      1,976,225

***************FRAMEWORKS****************
  New size                      Old size
 3,612,130       Core (>)      3,609,774

10,772,783      Total (>)     10,770,427


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                      FILE SIZE
 ++++++++++++++ GROWING                                                        ++++++++++++++
  +0.4% +2.64Ki [None]                                                         +12.4Ki  +0.1%
      +0.4% +2.59Ki [Unmapped]                                                     +12.4Ki  +0.1%
      +6.0%     +60 [None]                                                               0  [ = ]
      [NEW]     +16 CSWTCH.93                                                          +16  [NEW]
   +18% +1.74Ki src/core/lib/security/security_connector/security_connector.cc +1.73Ki   +18%
      [NEW]    +487 grpc_core::DefaultSslRootStore::CreateRootCertsBundle             +487  [NEW]
       +85%    +373 grpc_core::DefaultSslRootStore::ComputePemRootCerts               +373   +85%
      [NEW]    +328 grpc_core::DefaultSslRootStore::GetDirectoryTotalSize             +328  [NEW]
      [NEW]    +207 grpc_core::DefaultSslRootStore::GetAbsoluteFilePath               +207  [NEW]
      [NEW]    +172 grpc_core::DefaultSslRootStore::GetSystemRootCerts                +172  [NEW]
      [NEW]     +87 grpc_core::DefaultSslRootStore::GetValidCertsDirectory             +87  [NEW]
      [NEW]     +40 grpc_core::DefaultSslRootStore::linux_cert_files_                  +40  [NEW]
      [NEW]     +40 grpc_core::DefaultSslRootStore::linux_cert_directories_            +40  [NEW]
      +5.0%     +28 [Unmapped]                                                         +28  +5.0%
      [NEW]     +14 grpc_core::DefaultSslRootStore::DetectPlatform                     +14  [NEW]
      [NEW]      +4 grpc_core::DefaultSslRootStore::platform_                            0  [ = ]

  +0.3% +4.38Ki TOTAL                                                          +14.1Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   668,693       Core (>)        666,642

 1,978,456      Total (>)      1,976,225

***************FRAMEWORKS****************
  New size                      Old size
 3,612,130       Core (>)      3,609,774

10,772,781      Total (>)     10,770,426


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                      FILE SIZE
 ++++++++++++++ GROWING                                                        ++++++++++++++
  +0.4% +2.77Ki [None]                                                         +13.3Ki  +0.1%
      +0.4% +2.74Ki [Unmapped]                                                     +13.3Ki  +0.1%
      +2.8%     +28 [None]                                                               0  [ = ]
      [NEW]     +16 CSWTCH.95                                                          +16  [NEW]
   +19% +1.91Ki src/core/lib/security/security_connector/security_connector.cc +1.91Ki   +19%
      [NEW]    +577 grpc_core::DefaultSslRootStore::CreateRootCertsBundle             +577  [NEW]
      [NEW]    +416 grpc_core::DefaultSslRootStore::GetDirectoryTotalSize             +416  [NEW]
       +85%    +373 grpc_core::DefaultSslRootStore::ComputePemRootCerts               +373   +85%
      [NEW]    +207 grpc_core::DefaultSslRootStore::GetAbsoluteFilePath               +207  [NEW]
      [NEW]    +172 grpc_core::DefaultSslRootStore::GetSystemRootCerts                +172  [NEW]
      [NEW]     +87 grpc_core::DefaultSslRootStore::GetValidCertsDirectory             +87  [NEW]
      [NEW]     +40 grpc_core::DefaultSslRootStore::linux_cert_files_                  +40  [NEW]
      [NEW]     +40 grpc_core::DefaultSslRootStore::linux_cert_directories_            +40  [NEW]
      +4.7%     +26 [Unmapped]                                                         +26  +4.7%
      [NEW]     +14 grpc_core::DefaultSslRootStore::DetectPlatform                     +14  [NEW]
      [NEW]      +4 grpc_core::DefaultSslRootStore::platform_                            0  [ = ]

  +0.3% +4.68Ki TOTAL                                                          +15.2Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   668,765       Core (>)        666,642

 1,978,560      Total (>)      1,976,225

***************FRAMEWORKS****************
  New size                      Old size
 3,612,178       Core (>)      3,609,774

10,772,828      Total (>)     10,770,425


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yihuazhang** [comment]
@tdbhacks, here is another example (i.e., check gcp environment) of a single-interface with multiple platform-specific implementations that Mark pointed out. 

Interface: `grpc_alts_is_running_on_gcp() ` https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/alts/check_gcp_environment.h#L55
Linux-specific implementation: https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/alts/check_gcp_environment_linux.cc
Windows-specific implementation: https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/alts/check_gcp_environment_linux.cc
no-op implementation: https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/alts/check_gcp_environment_linux.cc

You could also use `GPR_LINUX`, `GPR_WINDOWS`, and `GPR_APPLE` macros to identify a corresponding platform.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9% +6.41Ki [None]                                                                               +18.2Ki  +0.2%
      +0.4% +2.38Ki [Unmapped]                                                                           +18.2Ki  +0.2%
      [NEW] +4.00Ki grpc_core::SystemRootCerts::GetAbsoluteFilePath(char const*, char const*)::absolute_       0  [ = ]
      +3.2%     +32 [None]                                                                                     0  [ = ]
      [NEW]     +16 CSWTCH.83                                                                                +16  [NEW]
  [NEW] +1.35Ki src/core/lib/security/security_connector/load_system_roots_linux.cc                  +1.35Ki  [NEW]
      [NEW]    +417 grpc_core::SystemRootCerts::CreateRootCertsBundle                                       +417  [NEW]
      [NEW]    +237 grpc_core::SystemRootCerts::GetDirectoryTotalSize                                       +237  [NEW]
      [NEW]    +171 grpc_core::SystemRootCerts::GetValidCertsDirectory                                      +171  [NEW]
      [NEW]    +170 grpc_core::SystemRootCerts::GetSystemRootCerts                                          +170  [NEW]
      [NEW]    +164 grpc_core::LoadSystemRootCerts                                                          +164  [NEW]
      [NEW]     +99 grpc_core::SystemRootCerts::GetAbsoluteFilePath                                          +99  [NEW]
      [NEW]     +42 [Unmapped]                                                                               +42  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_directories_                                      +40  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc                          +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                                     +168   +38%

  +0.6% +7.91Ki TOTAL                                                                                +19.7Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9% +6.41Ki [None]                                                                               +18.3Ki  +0.2%
      +0.4% +2.41Ki [Unmapped]                                                                           +18.3Ki  +0.2%
      [NEW] +4.00Ki grpc_core::SystemRootCerts::GetAbsoluteFilePath(char const*, char const*)::absolute_       0  [ = ]
      [NEW]     +16 CSWTCH.83                                                                                +16  [NEW]
  [NEW] +1.35Ki src/core/lib/security/security_connector/load_system_roots_linux.cc                  +1.35Ki  [NEW]
      [NEW]    +417 grpc_core::SystemRootCerts::CreateRootCertsBundle                                       +417  [NEW]
      [NEW]    +237 grpc_core::SystemRootCerts::GetDirectoryTotalSize                                       +237  [NEW]
      [NEW]    +171 grpc_core::SystemRootCerts::GetValidCertsDirectory                                      +171  [NEW]
      [NEW]    +170 grpc_core::SystemRootCerts::GetSystemRootCerts                                          +170  [NEW]
      [NEW]    +164 grpc_core::LoadSystemRootCerts                                                          +164  [NEW]
      [NEW]     +99 grpc_core::SystemRootCerts::GetAbsoluteFilePath                                          +99  [NEW]
      [NEW]     +42 [Unmapped]                                                                               +42  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_directories_                                      +40  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc                          +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                                     +168   +38%

  +0.6% +7.91Ki TOTAL                                                                                +19.8Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,582      Total (>)      1,976,356

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,770,904      Total (>)     10,770,411

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9% +6.38Ki [None]                                                                               +17.3Ki  +0.2%
      +0.4% +2.41Ki [Unmapped]                                                                           +17.3Ki  +0.2%
      [NEW] +4.00Ki grpc_core::SystemRootCerts::GetAbsoluteFilePath(char const*, char const*)::absolute_       0  [ = ]
      [NEW]     +16 CSWTCH.83                                                                                +16  [NEW]
  [NEW] +1.35Ki src/core/lib/security/security_connector/load_system_roots_linux.cc                  +1.35Ki  [NEW]
      [NEW]    +425 grpc_core::SystemRootCerts::CreateRootCertsBundle                                       +425  [NEW]
      [NEW]    +237 grpc_core::SystemRootCerts::GetDirectoryTotalSize                                       +237  [NEW]
      [NEW]    +171 grpc_core::SystemRootCerts::GetValidCertsDirectory                                      +171  [NEW]
      [NEW]    +170 grpc_core::SystemRootCerts::GetSystemRootCerts                                          +170  [NEW]
      [NEW]    +164 grpc_core::LoadSystemRootCerts                                                          +164  [NEW]
      [NEW]     +99 grpc_core::SystemRootCerts::GetAbsoluteFilePath                                          +99  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_directories_                                      +40  [NEW]
      [NEW]     +34 [Unmapped]                                                                               +34  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc                          +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                                     +168   +38%

  +0.5% +7.88Ki TOTAL                                                                                +18.8Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,848      Total (>)      1,976,610

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,772,004      Total (>)     10,771,525

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9% +6.38Ki [None]                                                                               +17.3Ki  +0.2%
      +0.4% +2.41Ki [Unmapped]                                                                           +17.3Ki  +0.2%
      [NEW] +4.00Ki grpc_core::SystemRootCerts::GetAbsoluteFilePath(char const*, char const*)::absolute_       0  [ = ]
      [NEW]     +16 CSWTCH.83                                                                                +16  [NEW]
  [NEW] +1.35Ki src/core/lib/security/security_connector/load_system_roots_linux.cc                  +1.35Ki  [NEW]
      [NEW]    +425 grpc_core::SystemRootCerts::CreateRootCertsBundle                                       +425  [NEW]
      [NEW]    +237 grpc_core::SystemRootCerts::GetDirectoryTotalSize                                       +237  [NEW]
      [NEW]    +171 grpc_core::SystemRootCerts::GetValidCertsDirectory                                      +171  [NEW]
      [NEW]    +170 grpc_core::SystemRootCerts::GetSystemRootCerts                                          +170  [NEW]
      [NEW]    +164 grpc_core::LoadSystemRootCerts                                                          +164  [NEW]
      [NEW]     +99 grpc_core::SystemRootCerts::GetAbsoluteFilePath                                          +99  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_directories_                                      +40  [NEW]
      [NEW]     +34 [Unmapped]                                                                               +34  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc                          +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                                     +168   +38%

  +0.5% +7.88Ki TOTAL                                                                                +18.8Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,848      Total (>)      1,976,610

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,772,007      Total (>)     10,771,522

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9% +6.35Ki [None]                                                                               +17.3Ki  +0.2%
      +0.4% +2.38Ki [Unmapped]                                                                           +17.3Ki  +0.2%
      [NEW] +4.00Ki grpc_core::SystemRootCerts::GetAbsoluteFilePath(char const*, char const*)::absolute_       0  [ = ]
      [NEW]     +16 CSWTCH.83                                                                                +16  [NEW]
  [NEW] +1.38Ki src/core/lib/security/security_connector/load_system_roots_linux.cc                  +1.38Ki  [NEW]
      [NEW]    +433 grpc_core::SystemRootCerts::CreateRootCertsBundle                                       +433  [NEW]
      [NEW]    +250 grpc_core::SystemRootCerts::GetDirectoryTotalSize                                       +250  [NEW]
      [NEW]    +171 grpc_core::SystemRootCerts::GetValidCertsDirectory                                      +171  [NEW]
      [NEW]    +170 grpc_core::SystemRootCerts::GetSystemRootCerts                                          +170  [NEW]
      [NEW]    +164 grpc_core::LoadSystemRootCerts                                                          +164  [NEW]
      [NEW]     +99 grpc_core::SystemRootCerts::GetAbsoluteFilePath                                          +99  [NEW]
      [NEW]     +45 [Unmapped]                                                                               +45  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_directories_                                      +40  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc                          +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                                     +168   +38%

  +0.5% +7.88Ki TOTAL                                                                                +18.8Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,892      Total (>)      1,976,654

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,776,224      Total (>)     10,775,730

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9% +6.36Ki [None]                                                                               +17.4Ki  +0.2%
      +0.4% +2.39Ki [Unmapped]                                                                           +17.4Ki  +0.2%
      [NEW] +4.00Ki grpc_core::SystemRootCerts::GetAbsoluteFilePath(char const*, char const*)::absolute_       0  [ = ]
      [NEW]     +16 CSWTCH.83                                                                                +16  [NEW]
  [NEW] +1.39Ki src/core/lib/security/security_connector/load_system_roots_linux.cc                  +1.39Ki  [NEW]
      [NEW]    +453 grpc_core::SystemRootCerts::CreateRootCertsBundle                                       +453  [NEW]
      [NEW]    +250 grpc_core::SystemRootCerts::GetDirectoryTotalSize                                       +250  [NEW]
      [NEW]    +171 grpc_core::SystemRootCerts::GetValidCertsDirectory                                      +171  [NEW]
      [NEW]    +170 grpc_core::SystemRootCerts::GetSystemRootCerts                                          +170  [NEW]
      [NEW]    +164 grpc_core::LoadSystemRootCerts                                                          +164  [NEW]
      [NEW]     +99 grpc_core::SystemRootCerts::GetAbsoluteFilePath                                          +99  [NEW]
      [NEW]     +41 [Unmapped]                                                                               +41  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::SystemRootCerts::linux_cert_directories_                                      +40  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc                          +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                                     +168   +38%

  +0.6% +7.91Ki TOTAL                                                                                +18.9Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,892      Total (>)      1,976,654

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,776,229      Total (>)     10,775,734

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.3% +1.86Ki [None]                                                              +27.5Ki  +0.3%
      +0.3% +1.89Ki [Unmapped]                                                          +27.5Ki  +0.3%
      [NEW]     +16 CSWTCH.83                                                               +16  [NEW]
  [NEW] +1.31Ki src/core/lib/security/security_connector/load_system_roots_linux.cc +1.31Ki  [NEW]
      [NEW]    +773 grpc_core::CreateRootCertsBundle                                       +773  [NEW]
      [NEW]    +225 grpc_core::LoadSystemRootCerts                                         +225  [NEW]
      [NEW]    +170 grpc_core::GetSystemRootCerts                                          +170  [NEW]
      [NEW]     +68 grpc_core::GetAbsoluteFilePath                                          +68  [NEW]
      [NEW]     +40 grpc_core::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::linux_cert_directories_                                      +40  [NEW]
      [NEW]     +29 [Unmapped]                                                              +29  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc         +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                    +168   +38%

  +0.2% +3.33Ki TOTAL                                                               +29.0Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,980,921      Total (>)      1,980,683

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,812,258      Total (>)     10,811,768

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.3% +1.91Ki [None]                                                              +27.8Ki  +0.3%
      +0.3% +1.94Ki [Unmapped]                                                          +27.8Ki  +0.3%
      [NEW]     +16 CSWTCH.83                                                               +16  [NEW]
  [NEW] +1.33Ki src/core/lib/security/security_connector/load_system_roots_linux.cc +1.33Ki  [NEW]
      [NEW]    +757 grpc_core::CreateRootCertsBundle                                       +757  [NEW]
      [NEW]    +225 grpc_core::LoadSystemRootCerts                                         +225  [NEW]
      [NEW]    +170 grpc_core::GetSystemRootCerts                                          +170  [NEW]
      [NEW]     +97 grpc_core::GetAbsoluteFilePath                                          +97  [NEW]
      [NEW]     +40 grpc_core::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::linux_cert_directories_                                      +40  [NEW]
      [NEW]     +32 [Unmapped]                                                              +32  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc         +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                    +168   +38%

  +0.2% +3.40Ki TOTAL                                                               +29.3Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,980,921      Total (>)      1,980,683

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,812,251      Total (>)     10,811,767

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.2% +1.70Ki [None]                                                              +28.1Ki  +0.3%
      +0.2% +1.62Ki [Unmapped]                                                          +28.1Ki  +0.3%
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertFiles                       +40  [NEW]
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertDirectories                 +40  [NEW]
      [NEW]     +16 CSWTCH.83                                                               +16  [NEW]
  [NEW] +1.35Ki src/core/lib/security/security_connector/load_system_roots_linux.cc +1.35Ki  [NEW]
      [NEW]    +838 grpc_core::CreateRootCertsBundle                                       +838  [NEW]
      [NEW]    +426 grpc_core::LoadSystemRootCerts                                         +426  [NEW]
      [NEW]    +105 grpc_core::GetAbsoluteFilePath                                         +105  [NEW]
      [NEW]     +17 [Unmapped]                                                              +17  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc         +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                    +168   +38%

  +0.2% +3.21Ki TOTAL                                                               +29.6Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,981,968      Total (>)      1,981,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,814,504      Total (>)     10,814,011

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,981,968      Total (>)      1,981,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,814,511      Total (>)     10,814,016

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.2% +1.79Ki [None]                                                              +27.4Ki  +0.3%
      +0.3% +1.71Ki [Unmapped]                                                          +27.3Ki  +0.3%
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertFiles                       +40  [NEW]
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertDirectories                 +40  [NEW]
      [NEW]     +16 CSWTCH.83                                                               +16  [NEW]
  [NEW] +1.40Ki src/core/lib/security/security_connector/load_system_roots_linux.cc +1.40Ki  [NEW]
      [NEW]    +884 grpc_core::CreateRootCertsBundle                                       +884  [NEW]
      [NEW]    +426 grpc_core::LoadSystemRootCerts                                         +426  [NEW]
      [NEW]    +105 grpc_core::GetAbsoluteFilePath                                         +105  [NEW]
      [NEW]     +19 [Unmapped]                                                              +19  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc         +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                    +168   +38%

  +0.2% +3.34Ki TOTAL                                                               +29.0Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jiangtaoli2016** [comment]
Thanks @markdroth  for your help on review.
The code looks good to me. Thanks much for implementation.
@tdbhacks @maliksaafir Could you pls squash all commit into one commit, and run tests again.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.2% +1.79Ki [None]                                                              +27.4Ki  +0.3%
      +0.3% +1.71Ki [Unmapped]                                                          +27.3Ki  +0.3%
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertFiles                       +40  [NEW]
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertDirectories                 +40  [NEW]
      [NEW]     +16 CSWTCH.83                                                               +16  [NEW]
  [NEW] +1.40Ki src/core/lib/security/security_connector/load_system_roots_linux.cc +1.40Ki  [NEW]
      [NEW]    +884 grpc_core::CreateRootCertsBundle                                       +884  [NEW]
      [NEW]    +426 grpc_core::LoadSystemRootCerts                                         +426  [NEW]
      [NEW]    +105 grpc_core::GetAbsoluteFilePath                                         +105  [NEW]
      [NEW]     +19 [Unmapped]                                                              +19  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc         +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                    +168   +38%

  +0.2% +3.34Ki TOTAL                                                               +28.9Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,950,932      Total (>)      1,950,694

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,669,327      Total (>)     10,668,838

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jiangtaoli2016** [comment]
Test failures are known failures. Merging.

**Pull request merged**
