### PR TITLE
Support Unbalanced Per-Method Codegen Generic on Server Side

### PR DESCRIPTION
**Pull request by ncteisen**
Built atop #15771.

Working towards #15764.

This supports async server side handlers in which one of req/resp is to be proto, and the other is to be generic. This fulfills the first concrete use case that incentivized the change.

TensorFlow worker servers want to receive RecvTensorRequest as a proto, but then return a ::grpc::ByteBuffer response ([1]), so that they may efficiently encode a Tensor object directly into the ByteBuffer ([2]).

This change allows them to continue using this optimization without having to dig into gRPC internal class.

[1]: https://github.com/tensorflow/tensorflow/blob/ced4fddc0400fedce8ba15fb9a3e6e765ddda757/tensorflow/core/distributed_runtime/rpc/grpc_worker_service.cc#L291-L292

[2]: https://github.com/tensorflow/tensorflow/blob/ced4fddc0400fedce8ba15fb9a3e6e765ddda757/tensorflow/core/distributed_runtime/rpc/grpc_tensor_coding.cc#L136

### CODE REVIEW

**Comment by ncteisen** [comment]
Wanted to put this out for an early look. I still need to expand test coverage

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +304  +0.0%

  [ = ]       0 TOTAL     +304  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                                             ++++++++++++++
  +0.0%     +16 [None]                                                                              +1.26Ki  +0.0%
  +0.1%     +16 src/cpp/server/health/default_health_check_service.cc                                   +16  +0.1%
      +2.9%     +16 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::HealthCheckServiceImpl         +16  +2.9%

  +0.0%     +32 TOTAL                                                                               +1.27Ki  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +296  +0.0%

  [ = ]       0 TOTAL     +296  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                                             ++++++++++++++
  +0.1%     +16 src/cpp/server/health/default_health_check_service.cc                                   +16  +0.1%
      +2.9%     +16 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::HealthCheckServiceImpl         +16  +2.9%

 -+-+-+-+-+-+-+ MIXED                                                                               +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                                                              +1.26Ki  +0.0%

  [ = ]       0 TOTAL                                                                               +1.27Ki  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +304  +0.0%

  [ = ]       0 TOTAL     +304  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                                             ++++++++++++++
  +0.1%     +16 src/cpp/server/health/default_health_check_service.cc                                   +16  +0.1%
      +2.9%     +16 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::HealthCheckServiceImpl         +16  +2.9%

 -+-+-+-+-+-+-+ MIXED                                                                               +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                                                              +1.26Ki  +0.0%

  [ = ]       0 TOTAL                                                                               +1.27Ki  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
This is done now too. There is a lot of boilerplate code in the tests, which I am not happy about, but it tests all of the new APIs

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +304  +0.0%

  [ = ]       0 TOTAL     +304  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                                             ++++++++++++++
  +0.1%     +16 src/cpp/server/health/default_health_check_service.cc                                   +16  +0.1%
      +2.9%     +16 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::HealthCheckServiceImpl         +16  +2.9%

 -+-+-+-+-+-+-+ MIXED                                                                               +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                                                              +1.43Ki  +0.0%

  [ = ]       0 TOTAL                                                                               +1.45Ki  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +304  +0.0%

  [ = ]       0 TOTAL     +304  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                                             ++++++++++++++
  +0.1%     +16 src/cpp/server/health/default_health_check_service.cc                                   +16  +0.1%
      +2.9%     +16 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::HealthCheckServiceImpl         +16  +2.9%

 -+-+-+-+-+-+-+ MIXED                                                                               +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                                                              +1.43Ki  +0.0%

  [ = ]       0 TOTAL                                                                               +1.45Ki  +0.0%



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                 cpu_time    real_time
----------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/32768                                              +4%         +4%
BM_PumpStreamServerToClient<InProcess>/262144                                             +5%         +5%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/1                     -6%         -6%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/262144                      -5%         -5%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                       -7%         -7%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/262144                   -5%         -5%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/0     -6%         -6%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/1/0  -6%         -6%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/2/1  -6%         -6%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/262144                       -4%         -4%
```

**Pull request closed without merging**
