### PR TITLE
Switch .py shebang to python3

### PR DESCRIPTION
**Pull request by jtattermusch**
Followup for python3 migration.

### CODE REVIEW

**Review by gnossen — APPROVED** [review]

**Comment by jtattermusch** [comment]
My guess is that the Python MacOS failure (https://source.cloud.google.com/results/invocations/0349f858-b297-4b22-b1f8-c23ef6cf2cf8/log)  is the same as in https://github.com/grpc/grpc/pull/28125#issuecomment-972815291.

@gnossen  is there any progress with debugging that problem?

**Comment by gnossen** [comment]
Quick update. I was able to reproduce this locally and will continue debugging it today.

**Comment by gnossen** [comment]
It turns out my local error was not a reproduction. And it looks like I'm unable to SSH to the Mac workers, so I've been forced to [repeatedly commit, push, and wait](https://github.com/grpc/grpc/pull/29061). I don't have a complete fix yet, but I do know a lot more. It looks like this is related to [an implementation detail of CPython on Mac OS](https://stackoverflow.com/questions/26323852/whats-the-meaning-of-pyvenv-launcher-environment-variable). The `__PYVENV_LAUNCHER__` environment variable points at 3.7 and every time Python spins up a subprocess, this seems to be the executable used, regardless of the Python version of the parent process.

I was able to get the build step to pass by unsetting this env var in the build step. But then all of the gRPC Python tests that spin up subprocesses started failing, saying that they couldn't find the `grpc` module. This likely means that _those_ subprocesses were instantiated with 3.7 again, somehow. I'm not sure where the environment variable is getting reinjected. My most recent fix attempt was to set put the 3.8 installation (which seems to be a better behaved CPython) at the Kokoro entrypoint, but I'm still seeing issues with the tests that involve subprocesses.

**Comment by jtattermusch** [comment]
Looks like the prepare_build_macos_rc change I added to this PR is fixing the problem with __PYVENV_LAUNCHER__: https://source.cloud.google.com/results/invocations/1a32ef1f-1963-4775-bdaa-17c9089348fa

**Comment by jtattermusch** [comment]
the fix from this PR should also unblock https://github.com/grpc/grpc/pull/28125

**Comment by jtattermusch** [comment]
As the fix in this PR seems to be working correctly, I'm going to merge (I'm happy to address additional comments as a followup).

Known failures:
- node interop test build is failing on also master.

**Comment by jtattermusch** [comment]
CC @lidizheng

**Pull request merged**
