### PR TITLE
Always build the grpc library when building the ruby extension.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Ping :D

**Comment by murgatroid99** [comment]
How do I make it run the tests again?

**Comment by nicolasnoble** [comment]
This was done because we realized that if there's an older, stale libgrpc.a into libs/opt, the script won't try to build it.

**Comment by murgatroid99** [comment]
I understand why we did it. I just want Jenkins to rerun the tests to make sure that the change is correct.

**Comment by nicolasnoble** [comment]
Ah, sorry. There's some magic words.

**Comment by nicolasnoble** [comment]
test this please

**Comment by nicolasnoble** [comment]
There you go - that was the magic words.

**Comment by murgatroid99** [comment]
LGTM, but it looks like the interop tests are failing because it's failing to use the grpc-go repo.

**Comment by murgatroid99** [comment]
I don't think merging master was a good idea.

**Comment by nicolasnoble** [comment]
Bah.

**Comment by nicolasnoble** [comment]
Supersed by #6396.

**Pull request closed without merging**
