### PR TITLE
Specify min windows version as Vista for Python

### PR DESCRIPTION
**Pull request by kpayson64**
This should fix the C++ build issue.  It can be changed separately.

### CODE REVIEW

**Comment by yashykt** [comment]
Awesome! Thanks for looking into this!

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by kpayson64** [comment]
Issues
#12747 
#12428

**Pull request merged**
