### PR TITLE
Add version_cc.cc and thread_manager.cc into grpc++_base bazel rule

### PR DESCRIPTION
**Pull request by mzhaom**
Add version_cc.cc and thread_manager.cc into grpc++_base bazel rule to deal with link error when building a grpc application with bazel.

### CODE REVIEW

**Comment by ctiller** [comment]
Jenkins: this is ok to test

**Comment by yang-g** [comment]
This is covered as part of #9303 :)

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @mzhaom isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jtattermusch** [comment]
@nicolasnoble   is this PR still useful? Let's accept/close.

**Pull request closed without merging**
