### PR TITLE
Add Census log and tests

### PR DESCRIPTION
**Pull request by a-veitch**

### CODE REVIEW

**Comment by a-veitch** [comment]
Fixes #1775

**Comment by a-veitch** [comment]
Tests seem to be failing on windows; how can I reproduce/debug?

**Comment by ctiller** [comment]
Open vsprojects/buildtests_c.sln under visual studio 2013, and set the
appropriate test as the startup project.

**Comment by a-veitch** [comment]
> Open vsprojects/buildtests_c.sln under visual studio 2013

That implies having access to a system with VS...

**Comment by ctiller** [comment]
It's amazing what can be written without using words, especially when your
audience is smart.

**Comment by ctiller** [comment]
target census_log_test (test/core/census/log_tests.c) does not name header src/core/census/log.h as a dependency
target census_log_test (test/core/census/log_tests.c) does not name header test/core/util/test_config.h as a dependency

Looks like some headers need to be added to build.yaml?

**Comment by ctiller** [comment]
Ping?

**Comment by ctiller** [comment]
Ping

**Comment by a-veitch** [comment]
Still trying to get the windows version of this built. Lower priority than some other census PR's.

**Comment by a-veitch** [comment]
Two options: (1) review the PR, with the understanding that things may change once I understand why windows doesn't like it. (2) I can unassign you, and reassign when things are working.

**Comment by ctiller** [comment]
I'm fine with where it is currently.

**Comment by a-veitch** [comment]
I'm going to close this PR, and open a new one with updated code once I solve the Windows issue (actively debugging now).

**Pull request closed without merging**
