### PR TITLE
Add ruby client utility for extracting Google::Rpc::Status from GRPC::Status

### PR DESCRIPTION
**Pull request by apolcyn**
cc @geigerj @qingling128

Looking for feedback on this right now.

### CODE REVIEW

**Comment by qingling128** [comment]
Thanks for the heads up, @apolcyn !

**Comment by apolcyn** [comment]
PTAL

There seems to be some differences between rubocop on these tests and my dev environment which I'm not sure is the exact cause yet, but is causing some delayed rubocop errors. Assuming those are now fixed, I think this should be ready for a look.

IMO the most tricky part of this was the added dependency on `googleapis-common-protos-types` and the loading of the `google-protobuf` message in the new utility file. But since we already have the `google-protobuf` dependency in the gemspec, and because there is no runtime loading of those protobuf messages unless the new utility used, this should not break any current usage.

**Comment by geigerj** [comment]
FYI @qingling128 

Any update on this PR, which is blocking the fix for https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1438?

**Comment by qingling128** [comment]
Thanks for checking @geigerj !
Hmm, seems there are some failed tests and it has not been reviewed yet.

**Comment by apolcyn** [comment]
squashing commits down before mering

**Comment by apolcyn** [comment]
mac tests saw pre-existing #12538, but sanity tests failed to build the docker image, so re-running sanity

**Comment by apolcyn** [comment]
interop tests passed but the test failed because of

```
ERROR: [GitHub Commit Status Setter] - {"message":"No commit found for SHA: eb464d3e6ba4b7dd04eb1058edddd7822e46618b","documentation_url":"https://developer.github.com/v3/repos/statuses/"}, setting build result to FAILURE
```

mac tests on failed with known kokoro/mac/ruby issue: https://github.com/grpc/grpc/issues/12538

**Pull request merged**
