### PR TITLE
Remove redundant work serializer usage in c-ares windows code

### PR DESCRIPTION
**Pull request by apolcyn**
This is extracted from the changes to c-ares windows code in https://github.com/grpc/grpc/pull/27858/files.

I'm not 100% sure why we were explicitly scheduling these methods on the work serializer when we were already running under it.

I think it's because these methods were originally added back in https://github.com/grpc/grpc/commit/03797e0ec36e76f08ecb51c74ebec0531d24fac4#, which was before the change to use `WorkSerializer`s in https://github.com/grpc/grpc/commit/e05417db32266a18c8c611054a8c452c96eca49d#diff-22089b08a43cdad7a2fcf577721907568fe29a57024bf600d137c69996fed567. In the former PR, the `pending_continue_register_for_on_{readable,writable}_locked_` fields were pointers to closures, and code would schedule their underlying closures on the combiner, even if we were already running under the combiner. The change to use work serializer also changed these fields from pointers to booleans, and also changed code to explicitly schedule their methods on the work serializer in the case these flags were set. But, explicitly scheduling on the work serializer remained redundant.

### CODE REVIEW

**Review by markdroth — APPROVED** [review]

**Comment by apolcyn** [comment]
portability tests windows: https://github.com/grpc/grpc/issues/28025

basic tests objc: https://github.com/grpc/grpc/issues/21858

**Comment by apolcyn** [comment]
Easy CLA is holding this up. Trying to re-kick it.

**Comment by apolcyn** [comment]
I signed it

**Pull request merged**
