### PR TITLE
PHP: Fix make error when get sources from pecl

### LINKED ISSUE #7922: PHP: make error from pecl download source
step1: download source from `pecl`, the version is `1.0.0`
step2: `phpize`, `./configure`, `make`

when I run `make`, it will error:

    In file included from /Users/thinkerou/Downloads/grpc/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.c:46:
    In file included from ./src/core/lib/security/credentials/jwt/jwt_credentials.h:38:
    ./src/core/lib/security/credentials/jwt/json_token.h:38:10: fatal error: 'openssl/rsa.h' file not found
    #include <openssl/rsa.h>
                   ^
    1 error generated.
    make: *** [src/core/lib/security/credentials/google_default/google_default_credentials.lo] Error 1

### PR DESCRIPTION
**Pull request by thinkerou**
Fixed #7922

### CODE REVIEW

**Comment by stanley-cheung** [comment]
I tried your fix, but I got this error, in Debian 8:

```
running: make
/bin/bash /tmp/pear/temp/pear-build-rootgzMcio/grpc-1.0.1RC1/libtool --mode=compile cc -Wall -Werror     -Wno-parentheses-equality -Wno-unused-value -std=c11     -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN     -D_HAS_EXCEPTIONS=0 -DNOMINMAX -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootgzMcio/grpc-1.0.1RC1/include -I/tmp/pear/temp/pear-build-rootgzMcio/grpc-1.0.1RC1/main -I/tmp/pear/temp/grpc -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/tmp/pear/temp/pear-build-rootgzMcio/grpc-1.0.1RC1/include -I/grpc -I/include  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/grpc/src/php/ext/grpc/byte_buffer.c -o src/php/ext/grpc/byte_buffer.lo
libtool: compile:  cc -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootgzMcio/grpc-1.0.1RC1/include -I/tmp/pear/temp/pear-build-rootgzMcio/grpc-1.0.1RC1/main -I/tmp/pear/temp/grpc -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/tmp/pear/temp/pear-build-rootgzMcio/grpc-1.0.1RC1/include -I/grpc -I/include -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/grpc/src/php/ext/grpc/byte_buffer.c  -fPIC -DPIC -o src/php/ext/grpc/.libs/byte_buffer.o
In file included from /tmp/pear/temp/grpc/src/php/ext/grpc/byte_buffer.c:42:0:
/tmp/pear/temp/grpc/src/php/ext/grpc/php_grpc.h:62:23: fatal error: grpc/grpc.h: No such file or directory
 #include "grpc/grpc.h"
                       ^
compilation terminated.
Makefile:180: recipe for target 'src/php/ext/grpc/byte_buffer.lo' failed
make: *** [src/php/ext/grpc/byte_buffer.lo] Error 1
ERROR: `make' failed
```

**Comment by stanley-cheung** [comment]
Got the same error on Mac. Something else could be the culprit.

Can you tell me what exactly did you do to reproduce this? And for what platform / OS version?

**Comment by thinkerou** [comment]
Mac OS 10.11

**Comment by stanley-cheung** [comment]
I cannot reproduce this on Mac 10.11. Can you give me the detail steps?

**Comment by thinkerou** [comment]
If only change the line: `PHP_ADD_INCLUDE(../../grpc/third_party/boringssl/include)`, it can make right, but I think that my system have `grpc` header files on `/usr/local/include/grpc`.
When I run `./configure`, it outputs the follow  info(part):

	checking if awk is broken... no
	checking whether to enable grpc support... yes, shared
	./configure: line 4143: cd: ../../grpc/src/php/ext: No such file or directory
	checking for ld used by cc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld

**Comment by stanley-cheung** [comment]
I guess I don't understand why you need to run `./configure`. If you are trying to compile from source, you shouldn't be using the pecl package. The pecl package is only intended to be used when installed via `sudo pecl install grpc` or `sudo pecl install grpc-1.0.0.tgz` as a whole.

If you need to compile from source, you will need to do it from the `src/php/ext/grpc` directory.

**Comment by thinkerou** [comment]
Oh...I understand what you mean. Because I receive email which he use the method to compile, and I use the same method reproduced, so I commit the PR.
All in all, I think that He and I should not use the method to compile, right?

**Comment by stanley-cheung** [comment]
Yes correct. If you need to compile from source, you need to do it from the `src/php/ext/grpc` directory.

**Comment by thinkerou** [comment]
But the `src/php/ext/grpc` directory have not `config.m4`, if I copy, it will also the error.
So I think that we only can get the source from `github` which can compile correctly.

**Comment by stanley-cheung** [comment]
Correct. The pecl package is not intended to be the source. If you want to compile from source, you need our github repo, which contains the source code.

**Comment by thinkerou** [comment]
OK, thanks cheung.

**Comment by thinkerou** [comment]
Not bug.

**Pull request closed without merging**
