### PR TITLE
Install Node 8 in artifact linux Dockerfiles

### PR DESCRIPTION
**Pull request by murgatroid99**
This should fix the Node artifact failures on Linux. This should have been part of the change made in #11627.

### CODE REVIEW

**Comment by murgatroid99** [comment]
A test artifact build for this branch is at https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/435/

**Comment by jtattermusch** [comment]
Also needs running https://github.com/grpc/grpc/blob/master/tools/dockerfile/push_testing_images.sh  to avoid breaking artifact build on kokoro.

**Comment by murgatroid99** [comment]
I tried running that script but it failed building the `grpc_interop_android_java` image at step 22: `grpc_interop_android_java`.

**Comment by murgatroid99** [comment]
I've made a change to try to avoid the failure in the last test build. The new test build is here: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/444/

**Comment by murgatroid99** [comment]
Now the build is running properly; it's just timing out.

**Comment by murgatroid99** [comment]
With these changes, the build succeeded: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/446/

**Comment by murgatroid99** [comment]
@jtattermusch Can you take another look at this? I made a fairly significant change to the Dockerfiles.

**Comment by murgatroid99** [comment]
I did push the images to dockerhub.

Known failures: #11676, #10686

**Pull request merged**
