### PR TITLE
Fix C# codegen for empty service

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/15574.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
@adelez   I rewrote the PR, PTAL

A few remarks:
- I've added a patch that enables building the C# v1.0.1 interop images.
- I realized that the `create_matrix_images.py` and  `tools/interop_matrix/run_interop_matrix_tests.py`  are not intuitive to use and also would really need some refactoring (the code is way to complex for what it's doing) - I made a few changes and also added comments to places in the code where refactoring would be useful.
- I've rebuilt and uploaded C# v1.0.1 images.

Currently, both csharp and csharpcoreclr v1.0.1 tests are passing reliably if I use `--server_host grpc-test.sandbox.googleapis.com`, but I'm getting some errors when running with `--server_host 74.125.206.210`
(which is the default setting) - can you please retest and advise what to do next? There's really nothing more I can do on the C# side to make these pass I believe.

this one passes reliably:
`tools/interop_matrix/run_interop_matrix_tests.py -l csharp --release v1.0.1 --server_host grpc-test.sandbox.googleapis.com`

this one shows some errors:
`tools/interop_matrix/run_interop_matrix_tests.py -l csharp --release v1.0.1`

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
