### PR TITLE
Remove support for ipv4: and ipv6: URI prefixes.

### PR DESCRIPTION
**Pull request by markdroth**
I think we no longer need these resolvers, since the DNS and fake resolvers can be used instead.  But let's see what breaks before we decide whether we should go ahead with this.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/15324)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  [NEW]    +962 src/core/ext/filters/client_channel/resolver/unix/unix_resolver.cc                      +962  [NEW]
      [NEW]    +248 grpc_core::(anonymous namespace)::UnixResolverFactory::CreateResolver(grpc_core::Res    +248  [NEW]
      [NEW]    +175 grpc_core::(anonymous namespace)::UnixResolver::ShutdownLocked                          +175  [NEW]
      [NEW]    +142 grpc_core::(anonymous namespace)::UnixResolver::MaybeFinishNextLocked() [clone .part    +142  [NEW]
      [NEW]    +111 grpc_resolver_unix_init                                                                 +111  [NEW]
      [NEW]     +87 grpc_core::(anonymous namespace)::UnixResolver::NextLocked                               +87  [NEW]
      [NEW]     +81 [Unmapped]                                                                               +81  [NEW]
      [NEW]     +41 grpc_core::(anonymous namespace)::UnixResolver::~UnixResolver                            +41  [NEW]
      [NEW]     +24 grpc_core::(anonymous namespace)::UnixResolverFactory::GetDefaultAuthority(grpc_uri*     +24  [NEW]
      [NEW]     +18 grpc_core::(anonymous namespace)::UnixResolver::RequestReresolutionLocked                +18  [NEW]
      [NEW]     +14 grpc_core::(anonymous namespace)::UnixResolver::~UnixResolver                            +14  [NEW]
      [NEW]      +9 grpc_core::(anonymous namespace)::UnixResolverFactory::~UnixResolverFactory               +9  [NEW]
      [NEW]      +8 grpc_core::(anonymous namespace)::UnixResolverFactory::scheme() const                     +8  [NEW]
      [NEW]      +2 grpc_resolver_unix_shutdown                                                               +2  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::UnixResolverFactory::~UnixResolverFactory               +2  [NEW]

 -------------- SHRINKING                                                                            --------------
  -0.1%    -856 [None]                                                                               -9.54Ki  -0.1%
      -0.1%    -744 [Unmapped]                                                                           -9.43Ki  -0.1%
      [DEL]     -64 vtable for grpc_core::(anonymous namespace)::SockaddrResolver                            -64  [DEL]
      [DEL]     -56 vtable for grpc_core::(anonymous namespace)::IPv4ResolverFactory                         -56  [DEL]
      [DEL]     -56 vtable for grpc_core::(anonymous namespace)::IPv6ResolverFactory                         -56  [DEL]
  [DEL] -1.83Ki src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc           -1.83Ki  [DEL]
      [DEL]    -668 grpc_core::(anonymous namespace)::CreateSockaddrResolver                                -668  [DEL]
      [DEL]    -242 grpc_resolver_sockaddr_init                                                             -242  [DEL]
      [DEL]    -195 [Unmapped]                                                                              -195  [DEL]
      [DEL]    -175 grpc_core::(anonymous namespace)::SockaddrResolver::ShutdownLocked                      -175  [DEL]
      [DEL]    -142 grpc_core::(anonymous namespace)::SockaddrResolver::MaybeFinishNextLocked() [clone .    -142  [DEL]
      [DEL]     -87 grpc_core::(anonymous namespace)::SockaddrResolver::NextLocked                           -87  [DEL]
      [DEL]     -69 grpc_core::(anonymous namespace)::IPv4ResolverFactory::CreateResolver(grpc_core::Res     -69  [DEL]
      [DEL]     -69 grpc_core::(anonymous namespace)::IPv6ResolverFactory::CreateResolver(grpc_core::Res     -69  [DEL]
      [DEL]     -69 grpc_core::(anonymous namespace)::UnixResolverFactory::CreateResolver(grpc_core::Res     -69  [DEL]
      [DEL]     -41 grpc_core::(anonymous namespace)::SockaddrResolver::~SockaddrResolver                    -41  [DEL]
      [DEL]     -24 grpc_core::(anonymous namespace)::UnixResolverFactory::GetDefaultAuthority(grpc_uri*     -24  [DEL]
      [DEL]     -18 grpc_core::(anonymous namespace)::SockaddrResolver::RequestReresolutionLocked            -18  [DEL]
      [DEL]     -14 grpc_core::(anonymous namespace)::SockaddrResolver::~SockaddrResolver                    -14  [DEL]
      [DEL]      -9 grpc_core::(anonymous namespace)::IPv4ResolverFactory::~IPv4ResolverFactory               -9  [DEL]
      [DEL]      -9 grpc_core::(anonymous namespace)::IPv6ResolverFactory::~IPv6ResolverFactory               -9  [DEL]
      [DEL]      -9 grpc_core::(anonymous namespace)::UnixResolverFactory::~UnixResolverFactory               -9  [DEL]
      [DEL]      -8 [Other]                                                                                   -8  [DEL]
      [DEL]      -8 grpc_core::(anonymous namespace)::IPv4ResolverFactory::scheme() const                     -8  [DEL]
      [DEL]      -8 grpc_core::(anonymous namespace)::IPv6ResolverFactory::scheme() const                     -8  [DEL]
      [DEL]      -8 grpc_core::(anonymous namespace)::UnixResolverFactory::scheme() const                     -8  [DEL]
      [DEL]      -2 grpc_resolver_sockaddr_shutdown                                                           -2  [DEL]

  -0.1% -1.73Ki TOTAL                                                                                -10.4Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
General question: why did we introduce the IPV4 and IPV6 resolvers? We should have already had DNS resolver at that time, I guess?

---

Reviewed 29 of 31 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[doc/naming.md, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/15324#-LCGrAPGC7FJ1G9L7j_S:-LCGrAPGC7FJ1G9L7j_T:b-pfdj5d) ([raw file](https://github.com/grpc/grpc/blob/c7574a126471459f9fbb3fe3f9cbe2909d6777f5/doc/naming.md#L28)):*
> ```Markdown
> 
> - `dns:[//authority/]host[:port]` -- DNS (default)
>   - `host` is the host to resolve via DNS.
> ```

Does this mean the URI "path" is `host` without `port`?

---

*[doc/naming.md, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/15324#-LCGrHo50yW1rwWvUU9f:-LCGrHo50yW1rwWvUU9g:bn1d8fb) ([raw file](https://github.com/grpc/grpc/blob/c7574a126471459f9fbb3fe3f9cbe2909d6777f5/doc/naming.md#L29)):*
> ```Markdown
> - `dns:[//authority/]host[:port]` -- DNS (default)
>   - `host` is the host to resolve via DNS.
>   - `port` is the port to return for each address.  If not specified,
> ```

If the returned value is either what we input or the default (443), why do we need this component? Does this component affect how the host is resolved? If not, can we defer attaching the port until when we receive the resolved IPs?

Or do we just want to hand off this per-address work to the resolver so that it's easier on our side?

---

*[test/core/end2end/dualstack_socket_test.cc, line 130 at r1](https://reviewable.io/reviews/grpc/grpc/15324#-LCGvX6rAL1eARiAhZvp:-LCGvX6s3jsfGx20LEUb:bh791a6) ([raw file](https://github.com/grpc/grpc/blob/c7574a126471459f9fbb3fe3f9cbe2909d6777f5/test/core/end2end/dualstack_socket_test.cc#L130)):*
> ```
> response_generator
> ```

What will be broken if this is moved into the scope of `if (client_host[0] == 'i')`?

---

*[test/cpp/end2end/round_robin_end2end_test.cc, line 1 at r1](https://reviewable.io/reviews/grpc/grpc/15324#-LCGkOmw6EBf_XluDTuv:-LCGkOmw6EBf_XluDTuw:b-m4jp6x) ([raw file](https://github.com/grpc/grpc/blob/47537f51acad4aa1e6d5ce75441680f66b500ea7/test/cpp/end2end/round_robin_end2end_test.cc#L1)):*
> ```cpp
> /*
> ```

Why is this file deleted? It seems unrelated to the rest of the PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15324#-:-LCGuYxeAOSKMytC91eL:b-k2whxu)*

**Comment by dgquintas** [comment]
Is this PR abandoned?

**Comment by markdroth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[doc/naming.md, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/15324#-LCGrAPGC7FJ1G9L7j_S:-LDxN4EIAnICTIa9aVpY:bk630ys) ([raw file](https://github.com/grpc/grpc/blob/c7574a126471459f9fbb3fe3f9cbe2909d6777f5/doc/naming.md#L28)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

Does this mean the URI "path" is `host` without `port`?
</blockquote></details>

No.  As per RFC-3986, the path is actually everything after the authority (i.e., technically, it includes the `/` before `host`).  But the syntax here is not showing how to break it up into components of the URI; it's showing the logical pieces relative to this specific scheme.

---

*[doc/naming.md, line 29 at r1](https://reviewable.io/reviews/grpc/grpc/15324#-LCGrHo50yW1rwWvUU9f:-LDxNKYk4bEdHeU3tl31:b-vmba75) ([raw file](https://github.com/grpc/grpc/blob/c7574a126471459f9fbb3fe3f9cbe2909d6777f5/doc/naming.md#L29)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

If the returned value is either what we input or the default (443), why do we need this component? Does this component affect how the host is resolved? If not, can we defer attaching the port until when we receive the resolved IPs?

Or do we just want to hand off this per-address work to the resolver so that it's easier on our side?
</blockquote></details>

It's true that the DNS resolver does not return port information, but there are other resolvers that do.  In order to support both of those models, our design is that the resolver API is responsible for returning the port information.  In cases like the DNS resolver, it returns the value specified by the user, or assumes a default if nothing is specified.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15324)*

**Comment by markdroth** [comment]
I know of at least one case where a user is using the IP resolvers (see #12569), so I guess we'll have to keep them.

**Pull request closed without merging**
