### PR TITLE
PHP stress client in stress test framework

### PR DESCRIPTION
**Pull request by sreecha**
Integrate PHP stress client to the stress test framework.

I reused almost all of the interop docker image templates 
- `src/php/bin/stress_client.sh`   was copied from `src/php/bin/interop_client.sh`
- `templates/tools/dockerfile/stress_test/grpc_interop_stress_php/Dockerfile.template` was copied from `templates/tools/dockerfile/interoptest/grpc_interop_php/Dockerfile.template` and I just added one line to install `gcp_api_libraries.include`
- `tools/dockerfile/stress_test/grpc_interop_stress_php/Dockerfile` is autogenerated by `generate_projects.sh` script based on the template
- `tools/dockerfile/stress_test/grpc_interop_stress_php/build_interop_stress.sh` is copied from `tools/dockerfile/interoptest/grpc_interop_php/build_interop.sh`
- `tools/run_tests/stress_test/configs/php-cxx.json` is newly added file. Please verify that the client and server commands I am using are correct. i.e `stressClientCmd`, `metricsClientCmd` and their parameters `clientArgs` and `metricsArgs` fields in the file. Rest of it is standard boiler-plate

### CODE REVIEW

**Comment by jtattermusch** [comment]
LGTM.

**Comment by stanley-cheung** [comment]
LGTM

**Comment by sreecha** [comment]
@stanley-cheung , 
There is a typo in PHP stress test client and it wasn't correctly honoring the `metrics_port` arg because of that.  (Thanks to @nicolasnoble and @murgatroid99 for the help in finding this)

can you PTAL at the file `src/php/tests/interop/stress_client.php`  ?

**Comment by stanley-cheung** [comment]
Ah, good catch. Thanks.

**Comment by jtattermusch** [comment]
Let me know once this is ready to go.

**Comment by sreecha** [comment]
The failures are unrelated and this is good to to. @stanley-cheung I am assuming you are okay with this ..

**Comment by stanley-cheung** [comment]
Yea it's good to go

**Pull request merged**
