### PR TITLE
Fix cmake windows C++ distrib test

### PR DESCRIPTION
**Pull request by jtattermusch**
- the variables defined by find_package turn out to be pretty tricky. Fixing stuff and adding explanatory comments.
- fixing a few nits

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Failures:
https://github.com/grpc/grpc/issues/13477

**Pull request merged**
