### PR TITLE
Add Node v1.11.2 to interop matrix

### PR DESCRIPTION
**Pull request by murgatroid99**
I don't think we've changed anything with the interop tests in the Node repo, so this should just work.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ejona86** [comment]
It looks like a v1.11.3 release for node was added to the interop matrix, so this appears obsolete. Closing.

**Pull request closed without merging**
