### PR TITLE
Fix MacOS breakage

### PR DESCRIPTION
**Pull request by a-veitch**
#5098 broke MacOS builds due to adding a file (src/core/census/log.c) that conflicted with src/core/support/log.c when libtool was building libgrpc.a. This PR removes the linkage of LIBGPR_OBJS into libgrpc.a, which eliminates this conflict (see changes to Makefile.template). Only one binary (bin_encoder_test) relied on this, added explicit dependency on gpr there (build.yaml).

Also added the -no_warning_for_no_symbols option to libtool and ranlib, which eliminates a number of warnings.

### CODE REVIEW

**Comment by ctiller** [comment]
This is almost certainly the wrong thing to do for the distribution story
where we need to rely on lumping everything together. I'd also prefer not
having to teach our users about gpr if possible. Could we simply rename one
of the files?

**Comment by nicolasnoble** [comment]
Indeed. Please rename the files. Some build systems will be dumb enough to
still mix all the .o files in a single folder, and that would still trigger
a collision.

**Comment by a-veitch** [comment]
OK, I'll rename. I'll point out that you still have a potential problem here at least, since the gpr files will end up in multiple libraries (gpr and grpc).

**Comment by a-veitch** [comment]
#5352 as alternative. Do you want me to delete this, or just keep the -no_warning_for_no_symbols part (which at least cleans up some of the spurious warnings).

**Comment by jcanizales** [comment]
I'd like very much the spurious warnings out of my builds.

**Comment by nicolasnoble** [comment]
#5353.

**Comment by ctiller** [comment]
The -no_warning_for_no_symbols part seems worth keeping.
We'll have a sanity check that validates 'the rules' we need to live with
shortly... (fixing up the rest of the problem cases now).

**Comment by a-veitch** [comment]
Didn't notice #5353 . Reclosing.

**Pull request closed without merging**
