### PR TITLE
CDS policy setting the correct child policy for aggregated clusters.

### PR DESCRIPTION
**Pull request by donnadionne**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/28853)

### CODE REVIEW

**Review by donnadionne — COMMENTED** [review]
This is response to https://b.corp.google.com/issues/218398904, where cds seems to be setting its child policy to round robin as oppose to ring hash.

This is the scenario where we have an aggregated cluster, and inside the aggregate, one cluster is ring hash (the first one in the vector) and the second one is round robin.

Currently an update on the second cluster will cause the generated xds_cluster_resolver_experimental policy to set child policy to round_robin.

I think the right thing to do is always follow the policy of the first cluster in the prioritized_cluster_names?

This does open the question what happens if we have to fail over when the first cluster is down?

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28853#-:-Mvb_loEBtfRz7_EQD8v:b-ueggwm)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @markdroth)

**Review by donnadionne — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28853)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 6397 at r1](https://reviewable.io/reviews/grpc/grpc/28853#-Mvbae9a34Ua1YLDgemz:-Mvbae9bASQp-aWcvUxI:b-yxre5j) ([raw file](https://github.com/grpc/grpc/blob/8d36caeeca3a2d5c2e648056bc760fc1a8bbe408/test/cpp/end2end/xds/xds_end2end_test.cc#L6397)):*
> ```cpp
> }
> 
> TEST_P(CdsTest, AggregateClusterFirstPriorityRingHash) {
> ```

This test is not totally right yet.  I do see that we are setting the correct policy type according to the code changes I made, but i am verifying that by looking at the debug log.  Once we confirm what we should do with down endpoints I'll fix this test better.

**Comment by markdroth** [comment]
The LB policy for an aggregate cluster is determined by the aggregate cluster itself, not by any of the underlying clusters that the aggregate cluster points to.  The LB policy setting in the underlying clusters is ignored completely in this case.

**Comment by markdroth** [comment]
To be clear, if the problem is being triggered by an update of an underlying cluster whose LB policy is something *other* than RING_HASH, that implies that the bug is that the CDS policy is looking at the LB policy of the underlying clusters instead of just the one for the aggregate cluster.

For example, consider the following Cluster resources:

- cluster A:
  - type: aggregate
  - LB policy: RING_HASH
  - underlying cluster list: [B, C]
- cluster B:
  - type: EDS
  - LB policy: ROUND_ROBIN
- cluster C:
  - type: LOGICAL_DNS
  - LB policy: ROUND_ROBIN

In this case, the LB policy for the aggregate cluster should be RING_HASH.  The fact that the underlying clusters use ROUND_ROBIN is irrelevant, since those policies should not actually get used.

**Pull request closed without merging**
