### PR TITLE
Document purpose and validity of interception API

### PR DESCRIPTION
**Pull request by vjpai**
Add comments to all relevant types and methods

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +520  +0.0%

  [ = ]       0 TOTAL     +520  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Yeah, I'd prefer not to make any commitments right now about the combinations of hook points that can come together since that could change in the future.

**Pull request merged**
