### PR TITLE
Fix bug in system time and user time calculation

### PR DESCRIPTION
**Pull request by nanahpang**
The calculation here was wrong before.
SystemTime + UserTime is the total cpu time usage(in second) for all the threads in benchmark tests. And WallTime is the real world time elapse in benchmark tests. No matter how many clients or servers are in the test, the real world time should not be summed. 

And based on how qps and qps_per_cpu is calculated here, we should use average(WallTime) to make these three metrics interconvertible.

This post processing function needs to be refactored and add more information in the comment. Will do it later.

### CODE REVIEW

**Comment by jtattermusch** [comment]
For context, the original PR is this https://github.com/grpc/grpc/pull/6192/files

**Comment by jtattermusch** [comment]
You're right saying that ClientStats.user_time + system time is total CPU time across all threads.
https://github.com/grpc/grpc/blob/729a0a9e5bf85f81bd4a6a3dc22c6fb984749761/src/proto/grpc/testing/stats.proto#L21

I'm still not convinced there's anything wrong.
I might be missing something but it seems that it all really depends on what's the definition of "client_user_time" and "client_system_time" from control.proto.  The only description I found is here:
https://github.com/grpc/grpc/blob/729a0a9e5bf85f81bd4a6a3dc22c6fb984749761/src/proto/grpc/testing/control.proto#L232
Do your realize that doing sum() / sum() is actually the same as doing avg() / avg() (which might actually be the purpose here?)

**Comment by jtattermusch** [comment]
So I also the looked at the benchmark results dataset (the `grpc-testing:performance_test.performance_experiment` dataset) and here's my findings:

1. on server, the results we currently have are just fine (regardless of the way we compute), because we only have one server in all our benchmarks, and for one server  avg = sum. That's good news because even if we change the computation, our old data will still be valid.

2. on client, the current semantics of the "client_system_time" value is the avg  cpu cores spent it kernel per one client VM   (so for 30s benchmark, if one client VM measures system time 45s and the other one 60s, the client_system_time will be   (45 + 60)/(30 + 30), so each VM will burn approx 1.75 cpu cores in kernel.

3. the way qps per CPU second is calculated seems to be correct and doesn't depend on how client_system_time or server_system_time is calculated.
https://github.com/jtattermusch/grpc/blob/d62f7285f9c55cdfdef0e68b24e1cfe3683a7d9b/test/cpp/qps/driver.cc#L179 (at least that seems to be the case for the opensource benchmarks).

Due to 2.) the argument becomes whether client_system_time should be the avg cores over all client VMs  or if it should be a sum of all cores over all client VMs. I don't see why one way would be correct then the other (I'm happy to be explained otherwise), but I have a preference of not changing the semantics of our results suddenly, unless we have a very good reason to do so.

One thing we really should do it to improve the comments in .proto files to make sure the meaning of the measurements and statistics is unambiguous.

**Comment by nanahpang** [comment]
Close this PR because the objective has changed and would open a new PR to correct the metric calculation and add comments in proto files.

**Pull request closed without merging**
