### PR TITLE
Adding a python_wrapper.sh script to call in an appropriate python2 interpreter

### LINKED ISSUE #5454: httpcli and httpscli failure on gcc4.4 portability test
https://grpc-testing.appspot.com/job/gRPC_portability_master/481/language=c,scenario=linux_x64_gcc4.4/testReport/junit/(root)/tests/bins_dbg_httpcli_test/ and https://grpc-testing.appspot.com/job/gRPC_portability_master/481/language=c,scenario=linux_x64_gcc4.4/testReport/junit/(root)/tests/bins_dbg_httpscli_test/

```
D0226 22:01:27.240215380   17660 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
D0226 22:01:27.240381929   17660 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
E0226 22:01:27.240932752   17660 tcp_client_posix.c:173]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
/usr/bin/env: python2.7: No such file or directory
D0226 22:01:32.242924042   17660 test_config.c:159]          test slowdown: machine=1.000000 build=1.000000 total=1.000000
D0226 22:01:32.243027323   17660 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
I0226 22:01:32.243043037   17660 httpscli_test.c:79]         test_get
I0226 22:01:32.243051205   17660 httpscli_test.c:82]         requesting from localhost:1105
E0226 22:01:32.244421395   17719 tcp_client_posix.c:173]     failed to connect to 'ipv6:[::1]:1105': socket error: connection refused
E0226 22:01:32.244550439   17719 tcp_client_posix.c:173]     failed to connect to 'ipv4:127.0.0.1:1105': socket error: connection refused
E0226 22:01:32.244590640   17719 httpscli_test.c:63]         assertion failed: response

*******************************
Caught signal 6
bins/dbg/httpscli_test[0x579235]
/lib/libpthread.so.0(+0xeff0)[0x7f8cb2cb9ff0]
/lib/libc.so.6(gsignal+0x35)[0x7f8cb2970f15]
/lib/libc.so.6(abort+0x180)[0x7f8cb2973d20]
bins/dbg/httpscli_test[0x4043ca]
bins/dbg/httpscli_test[0x406202]
bins/dbg/httpscli_test[0x406731]
bins/dbg/httpscli_test[0x406687]
bins/dbg/httpscli_test[0x407ad0]
bins/dbg/httpscli_test[0x499104]
bins/dbg/httpscli_test[0x423e44]
/lib/libpthread.so.0(+0x68ca)[0x7f8cb2cb18ca]
/lib/libc.so.6(clone+0x6d)[0x7f8cb2a17abd]
```

### PR DESCRIPTION
**Pull request by nicolasnoble**
Fixes #5454.

The gcc4.4 portability test image is so old that it doesn't have python2.7, only python2.6. And there's no viable python2.7 rpm package for it.

### CODE REVIEW

**Comment by ctiller** [comment]
Looks like it breaks us on the normal docker platform :(

(also copyright)

**Comment by nicolasnoble** [comment]
And MacOS. Nevermind, I have a more nuclear option, I think. Maybe.

**Comment by nicolasnoble** [comment]
Actually, screw it, let's just use "python". I don't know of any distribution yet which aliases that to python 3 instead of 2.

**Comment by ctiller** [comment]
Arch and gentoo.

**Comment by ctiller** [comment]
I'm thinking a better approach might be just to not run these if python2.7
is in the path.

**Comment by ctiller** [comment]
If python2.7 is not in the path.

**Comment by nicolasnoble** [comment]
So my nuclear option I was thinking about would be a python_wrapper script that bootstraps running python scripts during tests by probing for the proper interpreter and forking over.

**Comment by ctiller** [comment]
We have something like that, in the dockerfile for the Python distribtest
on some very old distro

**Comment by ctiller** [comment]
(Or similar)

**Comment by ctiller** [comment]
... If this is from run_tests.py... The Python interpreter will tell you
what binary the Python interpreter is

**Comment by nicolasnoble** [comment]
I started noodling a lot about this... Here's the main points of my thinking.

- We can't rely on run_tests, as #5573 and #4878 are proving that people are willing to run the tests using `make tests`. I'd even argue that tests are better off being self-enclosed, and not rely on external things (python interpreter, python script, altered root certificates via environment variable)
- Right now, https?cli_test are the only two tests that require an external python interpreter to properly run.
- We could theoretically make `make test` run `run_tests -lc,c++ -c$CONFIG`, but we'd push more and more towards rendering python necessary - and making the tests not self-enclosed (think Windows, probably ?)
- We originally migrated from using google.com to a python server to alleviate the possible redirect issues. Did we care about network connectivity ? I'm not sure.

How about we change our nginx configuration for grpc-testing.appspot.com to add a static hello world to a known test url, so that we can use https?://grpc-testing.appspot.com/httpcli_test as an actual testing target.

Pros:
- No longer require an external python script (which sometime won't go down if an assert fails btw, hence leaking a bit)
- Reduces the dependency burden for people willing to run our C-core tests on their machines (aka, the canonical `make test`).
- No longer require bogus root certificates, which would've avoided #4878, and would prevent further issues related to using a side-loaded external file into a test.
- Test can then run on all platforms, not just Linux.

Cons:
- Require an actual internet connection.
- If GCP goes down, the test fails.

**Comment by ctiller** [comment]
Let's not do that: The tests would no longer be hermetic and require reasoning about a bunch of infrastructure to fix any bug. The result will be some flaky tests that nobody ever does anything about, stalling development at random times, or encouraging people to ignore any other failures. 

We've been there, it was bad, let's not do it again.

I'd rather remove 'make tests' entirely than deal with adding more infrastructure that this team needs to support: we're overburdened there as it is.

If needing python for a test feels overburdensome, the following remedies could work:
- check for the presence (or absence) of the necessary Python interpreter, and if it doesn't exist, print a bunch of lines of warning and exit with success
- rewrite the servers in C (much easier once #5383 goes in)

**Comment by nicolasnoble** [comment]
I am okay with both alternatives. In fact, doing the first one was what I had in mind originally, and can be done quickly, and the second one might be the proper thing to do in the long run, since that's also a good way to test #5383.

**Comment by nicolasnoble** [comment]
Updated the PR with a wrapper. Will conflict with #5573.

**Comment by ctiller** [comment]
Looks like this introduces an allocation bug

**Comment by nicolasnoble** [comment]
All green now.

**Comment by ctiller** [comment]
Lgtm

**Comment by jtattermusch** [comment]
Merging as this fixed httpcli and httpscli failures on gcc4.4

**Pull request merged**
