### PR TITLE
Properly shutdown endpoints in h2_http_proxy

### PR DESCRIPTION
**Pull request by sreecha**
Shutdown the endpoint only if both read and write failures are observed on that endpoint.

Addresses the issue: https://github.com/grpc/grpc/issues/13124

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/13579)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
This looks pretty good.  My comments are fairly minor.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 165 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I2rHXgzlCAuL_tTKz:-L-I2rHXgzlCAuL_tTL-:by6uzm9) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L165)):*
> ```cpp
>   if (ep_state != new_ep_state) {
>     conn->ep_state = new_ep_state;
> ```

Nit: Please remove unnecessary blank lines within functions.

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 249 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I3jXJ2hmr-etndZVh:-L-I3jXJ2hmr-etndZVi:bbvvtq6) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L249)):*
> ```cpp
>   proxy_connection* conn = (proxy_connection*)arg;
>   if (error != GRPC_ERROR_NONE) {
>     // Report a read failure on the client endpoint. If there is no pending
> ```

It seems a bit messy to handle this here, because we're basically lying to `proxy_connection_failed()` by telling it that there was a server endpoint failure when there really wasn't any.  Instead, how about having `proxy_connection_failed()` directly check `server_is_writing` to decide whether or not to shut down the server endpoint when it sees a client endpoint failure?

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 287 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I47oYeKLPtRmzb95z:-L-I47oYeKLPtRmzb96-:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L287)):*
> ```cpp
>   proxy_connection* conn = (proxy_connection*)arg;
>   if (error != GRPC_ERROR_NONE) {
>     // Report a read failure on the server end point. If there is no pending
> ```

Same here.

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 494 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I2M5FCJS99J-4b6zA:-L-I2M5FCJS99J-4b6zB:b-v1ob2f) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L494)):*
> ```cpp
>   conn->proxy = proxy;
>   gpr_ref_init(&conn->refcount, 1);
>   conn->ep_state = 0;
> ```

Not necessary, since we allocate the struct via `gpr_zalloc()` a few lines above this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/13579#-:-L-I5Csk8Jvgl6kaFaI-:b-lj2cuk)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by sreecha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 165 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I2rHXgzlCAuL_tTKz:-L-IFel14x4o10vV8fp0:bs7wumx) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L165)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Nit: Please remove unnecessary blank lines within functions.
</blockquote></details>

Done. 

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 249 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I3jXJ2hmr-etndZVh:-L-IG9Wl4m9AspOn_yvM:b-bxxqqd) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L249)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It seems a bit messy to handle this here, because we're basically lying to `proxy_connection_failed()` by telling it that there was a server endpoint failure when there really wasn't any.  Instead, how about having `proxy_connection_failed()` directly check `server_is_writing` to decide whether or not to shut down the server endpoint when it sees a client endpoint failure?
</blockquote></details>

Actually this is messy no matter where we do it. I felt it is better to keep `proxy_connection_failed` to be dumb. The callers just "report" client/server read/write endpoint failures to it.  If it notices both read and write failures in a particular endpoint, it shuts it down. 

Also, `proxy_connection_failed` is also called by the other callbacks used during initial connection establishments - and any failure during that time must be considered a failure in both endpoints. So that requires another special-case in `proxy_connection_failed`.

Considering this, it felt like its  a (relatively) cleaner way to keep `proxy_connection_failed`'s logic simple

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 287 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I47oYeKLPtRmzb95z:-L-IHRU_h1rrQEsgQ8TD:bpw9hr7) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L287)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

(See previous comment)

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 494 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I2M5FCJS99J-4b6zA:-L-IG7zAb8Awqhjzv5o7:bb6un1j) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L494)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Not necessary, since we allocate the struct via `gpr_zalloc()` a few lines above this.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/13579)*

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by sreecha** [comment]
Failures are known:

Asan C++ (internal CI) : https://github.com/grpc/grpc/issues/13122
Basic Tests C++ Linux [dbg] (internal CI): https://github.com/grpc/grpc/issues/13330
Tsan C++ (internal CI): https://github.com/grpc/grpc/issues/13122

**Comment by markdroth** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 249 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I3jXJ2hmr-etndZVh:-L-IPZESJqIsOSocVSp7:byyazxo) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L249)):*
<details><summary><i>Previously, sreecha (Sree Kuchibhotla) wrote…</i></summary><blockquote>

Actually this is messy no matter where we do it. I felt it is better to keep `proxy_connection_failed` to be dumb. The callers just "report" client/server read/write endpoint failures to it.  If it notices both read and write failures in a particular endpoint, it shuts it down. 

Also, `proxy_connection_failed` is also called by the other callbacks used during initial connection establishments - and any failure during that time must be considered a failure in both endpoints. So that requires another special-case in `proxy_connection_failed`.

Considering this, it felt like its  a (relatively) cleaner way to keep `proxy_connection_failed`'s logic simple
</blockquote></details>

I can deal with this being messy, as long as the messiness is hidden behind an API with clear semantics.  Right now, we don't have a clean API for `proxy_connection_failed()`: the function says that the caller should tell it the types of failure has occurred, but what we are actually giving it is a separate set of flags that tells it what to actually do, and the state controlling that decision is split between `proxy_connection_failed()` and its callers rather than being centralized in one place.

Please see the following PR for my suggested approach:

https://github.com/sreecha/grpc/pull/10

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/13579)*

**Comment by sreecha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/core/end2end/fixtures/http_proxy_fixture.cc, line 249 at r3](https://reviewable.io:443/reviews/grpc/grpc/13579#-L-I3jXJ2hmr-etndZVh:-L-JAKn349cUrkjzLaj-:bchy0ct) ([raw file](https://github.com/grpc/grpc/blob/445c5664e0572daa7b07fdde0e4959f0deeb803f/test/core/end2end/fixtures/http_proxy_fixture.cc#L249)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I can deal with this being messy, as long as the messiness is hidden behind an API with clear semantics.  Right now, we don't have a clean API for `proxy_connection_failed()`: the function says that the caller should tell it the types of failure has occurred, but what we are actually giving it is a separate set of flags that tells it what to actually do, and the state controlling that decision is split between `proxy_connection_failed()` and its callers rather than being centralized in one place.

Please see the following PR for my suggested approach:

https://github.com/sreecha/grpc/pull/10
</blockquote></details>

Thanks for the PR. I see your point. I merged your commit and send the updated PR with your changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/13579)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by markdroth** [comment]
Thanks for fixing this!

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/13579#-:-L-JFIcaWJfuNc_dw1gG:b-whxd1j)*

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by sreecha** [comment]
`ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires` failed. Known issue (
https://github.com/grpc/grpc/issues/11008 and https://github.com/grpc/grpc/issues/12917)

**Pull request merged**
