### PR TITLE
etcd name resolver

### PR DESCRIPTION
**Pull request by hongweiwang**
Add etcd name resolver to gRPC. Etcd names in gRPC are represented as a URI.
etcd://host:port/name
Where host:port is etcd server address. name is etcd path of the service. An example would be etcd://127.0.0.1:2379/storage/mysql.

Services are registered in etcd server in hierarchical format service/instance, similar to Apache Curator. Each service is an etcd node, and each instance is a child node of the service. Each instance node stores its address (host and port) in JSON format.

### CODE REVIEW

**Comment by hongweiwang** [comment]
@dgquintas Can you please review this pull request and start jenkins? Thanks!

**Comment by hongweiwang** [comment]
ping?

**Comment by dgquintas** [comment]
pong! Sorry, I'll do a first pass today. Thanks for pinging!

**Comment by hongweiwang** [comment]
And please start jenkins as well.

**Comment by dgquintas** [comment]
This is ok to test.

**Comment by hongweiwang** [comment]
I forgot one issue. The etcd server on grpc-jenkins-master was not properly configured for the test. @dgquintas can you do me a favor since I don't have the permission now. Here are the steps:

1. Log on `grpc-jenkins-master` and go to the `etcd` directory under `jenkins_home`.
2. Kill the original etcd server if running. You can use `ps -ef | grep etcd` to find the etcd process and then kill it.
3. Restart etcd server:
`./etcd --listen-client-urls 'http://grpc-jenkins-master:2379' --advertise-client-urls 'http://grpc-jenkins-master:2379'`

**Comment by dgquintas** [comment]
Done. However, the process seems to say in the background, which is to say, the moment I close my SSH window the server will go away.

**Comment by dgquintas** [comment]
Actually, the way tests should work is by bringing up any external process they may need (like, in this case, a server) as part of their setup and then bring those external processed down as part of their teardown. In other words, tests should be self-contained and not rely on their environment.

We can take care of setting up the infrastructure for all this in about a week's time, as we are all quite busy right now.

I'm shutting down the etcd server in jenkins-master based on what I described above and also because the jenkins master shouldn't be running any additional software that may interfere with it.

**Comment by hongweiwang** [comment]
Sure, we can solve the etcd test one week later. Ping me when you are free to do it.

Basically, it is the same process with zookeeper test. @nicolasnoble suggested me running zookeeper server in grpc-jenkins-master to avoid downloading zookeeper since zookeeper is an optional plugin in gRPC. We need to discuss with him on etcd test to decide whether we should follow the same logic as zookeeper or have a separate process to handle the etcd server (we need to download the package, uncompress it and run the etcd server). 

By the way, one solution to solve the above problem that the server is killed when ssh is closed is to run the command in a "screen".

**Comment by dgquintas** [comment]
Yeah, @nicolasnoble will be back next well.

Sure, one could use screen or tmux (or even "nohup") but those are very hacky solutions indeed :)

**Comment by hongweiwang** [comment]
@nicolasnoble @dgquintas Any suggestions on the etcd test?

**Comment by ctiller** [comment]
Closing due to lack of progress on the test.

Please re-open if there's a change.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @hongweiwang isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
