### PR TITLE
Fix typo in python_configure.bzl

### PR DESCRIPTION
**Pull request by gallmerci**
See #20773 for details.

@gnossen

### CODE REVIEW

**Comment by gallmerci** [comment]
Do I need to do anything besides signing the CLA? I signed it few days ago but no update here yet.

**Comment by gnossen** [comment]
The CLA bot doesn't seem to be retriggering. Trying again.

**Comment by gnossen** [comment]
@gallmerci Could you please close and reopen the PR. The CLA bot needs to be retriggered.

**Comment by gallmerci** [comment]
@gnossen Sure, seems that it works now :)

**Comment by gnossen** [comment]
Unrelated failures:
 - https://github.com/grpc/grpc/issues/20694
 - https://github.com/grpc/grpc/issues/20890

**Comment by gnossen** [comment]
@gallmerci Thank you for the fix!

**Pull request merged**
