### PR TITLE
Dynamic-sized thread pool

### PR DESCRIPTION
**Pull request by vjpai**
This is a dynamic sized thread pool. The constructor specifies the number of threads to hold in reserve (possibly 0 if so desired), but the thread pool will grow any time that a new callback finds no thread waiting to process it, and the thread pool will shrink whenever there are more idle threads than the initial reserve. More complex adaptive allocation policies are possible, but this is the most straightforward way to capture basic dynamic requirements.

### CODE REVIEW

**Comment by vjpai** [comment]
Fixes #2423

**Comment by vjpai** [comment]
Yang, would you consider this green enough? I know that there is a TSAN failure on thread_stress_test but it's not related; it is most probably caused by another existing bug (double-push) and is being separately tracked in issue #2653 . Any unstable C MacOS builds are unrelated because the changes here were only on the C++ side.

**Comment by yang-g** [comment]
I think for those test we may not need to create a thread pool explicitly any more. But this looks fine as is.

**Comment by yyh-graphsql** [comment]
@vjpai  Can I ask a question, If there is some settings to set the upper worker limits of a thread pool? In my program, there is a bug in server side, which made the RPC not return. And the thread count increased to 20000+.

**Pull request merged**
