### PR TITLE
fix assertion error in php debug build

### PR DESCRIPTION
**Pull request by fujimoto**
directly deleting hash elements (in Grpc\Channel::__construct()) causes assertion error in debug build of php (built with --enable-debug configure option):

```sh
php: /path/to/build/php-7.3.4-debug/Zend/zend_hash.c:1345: zend_hash_str_del: Assertion `(zend_gc_refcount(&(ht)->gc) == 1) || ((ht)->u.flags & (1<<6))' failed.
zsh: abort (core dumped)  php grpc_client.php
```
(can reproduce, just running ```$client = new Helloworld\GreeterClient('localhost:50051', ['credentials' => Grpc\ChannelCredentials::createInsecure()]);``` with php (7.x) debug build)

this patch simply copies passed arrays to fix this.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @fujimoto isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by fujimoto** [comment]
> After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.
> 
> * User @fujimoto isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

done:)

**Comment by fujimoto** [comment]
> Tests fail. Please fix, thanks!

oops, I will take a look with in a few days.

**Comment by fujimoto** [comment]
fixed php5 builds, by adding some more zend_hash wrappers in php7_wrapper.h. please let me know if this is not a comfortable way in some other aspects.

**Comment by ZhouyihaiDing** [comment]
Thanks for the update.
Sorry it seems a lot of tests failed.
```

There were 6 failures:
1) ChannelTest::testPersistentChannelSameHost
Failed asserting that false is true.
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:171
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:209
2) ChannelTest::testPersistentChannelSameArgs
Failed asserting that false is true.
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:171
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:259
3) ChannelTest::testPersistentChannelSameChannelCredentials
Failed asserting that false is true.
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:171
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:304
4) ChannelTest::testPersistentChannelSameChannelCredentialsRootCerts
Failed asserting that false is true.
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:171
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:357
5) ChannelTest::testPersistentChannelSharedMoreThanTwo
Failed asserting that false is true.
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:171
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:459
6) ChannelTest::testPersistentChannelForceNewOldChannelIdle2
Failed asserting that false is true.
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:183
/var/local/git/grpc/src/php/tests/unit_tests/ChannelTest.php:609
```

**Comment by fujimoto** [comment]
ah, sorry for bothering (I've just checked out tests under ext/grpc). should be fixed soon.

**Comment by fujimoto** [comment]
@ZhouyihaiDing:
sorry to be (very ) late, I've fixed the test errors (confirmed on ubuntu 14.x, and ubuntu 16.x).

(anyways run_tests.sh fails on ubuntu 18.x, or, phpunit version >=6, I will create the issue later)

**Comment by stanley-cheung** [comment]
This is superceded by #20249. It's a slightly different way of fixing the segfault in `--enable-debug` build. I have tested that PR extensively across various environments (with or without debug) and tests are passing at the moment. @fujimoto Thanks for your contribution. Please take a look at that PR and let us know if you see any issue. Thanks.

**Pull request closed without merging**
