### PR TITLE
grpc_cli json support

### PR DESCRIPTION
**Pull request by gfecher**
Adding json support to grpc_cli would allow us to use the tooling already available for json (e.g. jq) to run more extensive integration tests.
I have introduced two new parameters to the relevant commands
`--json_input`
`--json_output`
and a new command `tojson` that converts binary messages to json.
The behaviour of these closely follows the behaviour of the default text format.

Let me know what you think.

### CODE REVIEW

**Comment by yashykt** [comment]
@yang-g Would you be able to take a look at this?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,922      Total (=)      1,965,922

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,002      Total (<)     10,909,004

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
There are also some format errors but those should be easy to fix.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,206      Total (=)      1,965,206

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,022      Total (=)     10,909,022

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
@gfecher Could you run clang-format or tools/dockerfile/grpc_clang_format/clang_format_all_the_things.sh to format the code? I have a diff in the test log if you prefer, though it is long..

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,242      Total (=)      1,965,242

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,029      Total (>)     10,909,022

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
Thanks for the updates!

**Comment by yang-g** [comment]
@gfecher I think the current release was cut on Oct 8 and the next release should be cut around late Nov and release early Dec.

**Comment by dgquintas** [comment]
This change is causing trouble internally, specifically due to [this line](https://github.com/grpc/grpc/pull/16766/files#diff-db3b353bb94bfa912c20313a57ae6f66R44). @yang-g can you take a look? Otherwise we'll need to roll it back.

**Comment by gfecher** [comment]
Oh no! Is there anything I can help with?

**Comment by connesc** [comment]
Very nice addition, thanks @gfecher! Can't wait to see this released :smile: 
For symmetry with text conversions, JSON support should probably added to `tobinary` as well.

**Comment by yang-g** [comment]
@gfecher *I think* I have fixed the internal issue... will try to roll this forward soon.

**Comment by gfecher** [comment]
Thanks a lot @yang-g !
@connesc - I have just tried this and specifying --json_input on the command line for `tobinary` works, like this:
```
grpc_cli tobinary --json_input examples/protos/route_guide.proto routeguide.Rectangle '{"lo": {"latitude": 407838351, "longitude": -746143763}, "hi": {"latitude": 408122808, "longitude": -743999179} }'
```
Having said that I have found bigger issues with `tobinary`, namely it doesn't produce valid binary messages at all due to the newline added by `SimplePrint` in `grpc_cli.cc`, I will open a new issue for that.

**Pull request merged**
