### PR TITLE
Remove generated pb files

### PR DESCRIPTION
**Pull request by y-zeng**
- Removed reflection.grpc.pb.h, reflection.grpc.pb.cc, reflection.pb.h, reflection.pb.cc
- Removed the script for generating those files
- Removed the sanity test for checking the generated files
- Server reflection proto files will be generated during gRPC compilation

### CODE REVIEW

**Comment by nicolasnoble** [comment]
LGTM - let's see the result of the tests.

**Comment by vjpai** [comment]
If you are getting rid of these, why not also get rid of golden_file_test , which is essentially another case of the same thing?

**Comment by y-zeng** [comment]
The purpose of this PR is to avoid using generated files as public headers. I'm not sure if golden_file_test is still needed. @yang-g Could you please take a look?

**Comment by y-zeng** [comment]
@nicolasnoble Test failures seem unrelated.

**Comment by yang-g** [comment]
I am not sure golden_file_test is related to this change. Whether we need that test is a separate question I think.

**Comment by vjpai** [comment]
I agree that golden_file_test is not directly in the same category as this PR, but it also has a similar issue with it - we need to actually commit generated code into our repository. Agreed, that is not as bad as installing generated code into public headers, so I'll raise it as a separate issue and won't stand in the way here.

**Comment by vjpai** [comment]
Ok, I have created a separate issue #8428 to discuss my issue with generated code in the repo.

**Pull request merged**
