### PR TITLE
fixed multiple initialization of globals

### PR DESCRIPTION
**Pull request by dgquintas**
related to https://github.com/grpc/grpc/pull/5809 

@vjpai

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM

**Comment by ctiller** [comment]
@jtattermusch this ought to let us merge #5809 which will fix the TSAN stability issues

**Comment by vjpai** [comment]
Great, I like the code too.

**Comment by jtattermusch** [comment]
h2_full_test_connectivity has failed.

https://grpc-testing.appspot.com/job/gRPC_pull_requests/7140/config=opt,language=c,platform=macos/testReport/junit/(root)/tests/bins_opt_h2_full_test_connectivity/

**Comment by ctiller** [comment]
Definitely not related.

**Comment by vjpai** [comment]
Agreed that it's unrelated as this PR is only C++ and that test is in core.

**Comment by jtattermusch** [comment]
Fine to merge once performance tests & travis finish.

**Pull request merged**
