### PR TITLE
Upmerge 1.1.x into master

### PR DESCRIPTION
**Pull request by murgatroid99**
The merge conflicts were:

 - `src/node/ext/slice.cc` was added to the Node extension on master, and `src/node/ext/server_{uv,generic}.cc` were added on v1.1.x

 - Part of `src/node/ext/server.cc` was modified on master and moved to `src/node/ext/server_uv.cc` on v1.1.x

 - Part of `test/core/surface/completion_queue_test.c` was modified on master and moved to `test/core/surface/completion_queue_threading_test.c` on v1.1.x

### CODE REVIEW

**Comment by jtattermusch** [comment]
Do you need this commit too? https://github.com/grpc/grpc/pull/9453/commits/da83b376ebb03818221c823c6b53162b79d0b389

**Comment by jtattermusch** [comment]
Please close https://github.com/grpc/grpc/pull/9453 if this PR supersedes it.

**Comment by murgatroid99** [comment]
#9453 was actually superseded by #9694.

**Comment by murgatroid99** [comment]
Interop failures are all #9762.

**Pull request merged**
