### PR TITLE
Fixes build problem in the ObjC sample client and adds local tests

### PR DESCRIPTION
**Pull request by jcanizales**
The local tests pass for a locally-running RouteGuide gRPC server (as in the Java sample).

### CODE REVIEW

**Comment by jcanizales** [comment]
In order to add only 1 file to the root of the repo, instead of 2, I can move RxLibrary.podspec into gRPC.podspec (as a subspec).

**Comment by jcanizales** [comment]
@tbetbetbe this is the PR that adds the podspecs to the root of the main repo. Currently it'd add 2 podspec files; I can change that to 1 easily if it's an easier sell.

**Comment by jcanizales** [comment]
Merged the two podspecs into one, as agreed with @a11r . This is ready now.

**Comment by murgatroid99** [comment]
I will merge without waiting for Travis because we do not yet have Travis tests for this library.

**Pull request merged**
