### PR TITLE
Demonstrate issue where we get too many timer wakeups

### PR DESCRIPTION
**Pull request by rmstar**
The test creates a timer that fires in 1.5 seconds, then sleeps for 5 seconds.

 I would expect 6 grpc timer wakeups: 1 wakeup/second when there are no timers (this is based on my testing, not sure if it's intended behavior) + 1 wakeup for the timer that fires after 1.5 seconds.
What we actually see is 11 wakeups. 

If you create more timers, you'll notice that the issue gets worse - there are even more seemingly unnecessary timer wakeups.

I think the problem is in the [deadline calculation](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/timer_generic.cc#L503).

```
$  bazel-bin/test/cpp/common/timer_test
D0731 17:10:51.917567000 4554032576 test_config.cc:384]                test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TimerTest
[ RUN      ] TimerTest.TimerExpiry
E0731 17:10:51.919765000 4554032576 timer_test.cc:37]                  sleeping for 5 seconds
E0731 17:10:51.919802000 123145472860160 timer_manager.cc:185]         sleep for a 541 milliseconds
E0731 17:10:52.464437000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:52.464512000 123145472860160 timer_manager.cc:185]         sleep for a 457 milliseconds
E0731 17:10:52.922711000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:52.922780000 123145472860160 timer_manager.cc:185]         sleep for a 153 milliseconds
E0731 17:10:53.076916000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:53.076953000 123145472860160 timer_manager.cc:185]         sleep for a 342 milliseconds
E0731 17:10:53.422647000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:53.422903000 123145472860160 timer_test.cc:36]             Timer fired
E0731 17:10:53.422928000 123145472860160 timer_manager.cc:185]         sleep for a 357 milliseconds
E0731 17:10:53.782250000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:53.782305000 123145472860160 timer_manager.cc:185]         sleep for a 142 milliseconds
E0731 17:10:53.928712000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:53.928783000 123145472860160 timer_manager.cc:185]         sleep for a 651 milliseconds
E0731 17:10:54.581226000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:54.581282000 123145472860160 timer_manager.cc:185]         sleep for a 348 milliseconds
E0731 17:10:54.932272000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:54.932307000 123145472860160 timer_manager.cc:185]         sleep for a 526 milliseconds
E0731 17:10:55.462168000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:55.462226000 123145472860160 timer_manager.cc:185]         sleep for a 470 milliseconds
E0731 17:10:55.936669000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:55.936737000 123145472860160 timer_manager.cc:185]         sleep for a 456 milliseconds
E0731 17:10:56.395491000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
E0731 17:10:56.395548000 123145472860160 timer_manager.cc:185]         sleep for a 543 milliseconds
E0731 17:10:56.923576000 4554032576 timer_test.cc:39]                  sleep done
[       OK ] TimerTest.TimerExpiry (5005 ms)
[----------] 1 test from TimerTest (5005 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (5005 ms total)
[  PASSED  ] 1 test.
E0731 17:10:56.923973000 123145473396736 timer_manager.cc:201]         wait ended: was_timed:0 kicked:0
E0731 17:10:56.924058000 123145472860160 timer_manager.cc:201]         wait ended: was_timed:1 kicked:0
```

### CODE REVIEW

**Comment by rmstar** [comment]
I found a much more serious issue on Mac OS. In `TimerTest.TimeJumpsBackwards`, I simulate time jumping backwards by 3 seconds. This results in > 600k wakeups in 5 seconds! 
On Mac OS, the `pthread_cond_timedwait` deadline uses realtime clock, which is affected by changes in wallclock time. We use monotonic clock on linux, so this is not a problem on linux. 

https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/sync_posix.cc#L132-L138

```c++
#if GPR_LINUX
    abs_deadline = gpr_convert_clock_type_debug(
        abs_deadline, GPR_CLOCK_MONOTONIC, now1, now2, add_result, sub_result);
#else
    abs_deadline = gpr_convert_clock_type_debug(
        abs_deadline, GPR_CLOCK_REALTIME, now1, now2, add_result, sub_result);
#endif  // GPR_LINUX
```
This logic was added in https://github.com/grpc/grpc/pull/13137.

@iancoolidge @sreecha  do you remember why we only use monotonic clock on linux?

**Comment by iancoolidge** [comment]
My understanding was that Linux only supports the monotonic domain.

See
https://linux.die.net/man/3/clock_gettime

**Comment by rmstar** [comment]
> My understanding was that Linux only supports the monotonic domain. See https://linux.die.net/man/3/clock_gettime

Thanks Ian. I should rephrase my question - using monotonic clock seems like the correct thing to do. Why are we only using monotonic clock on linux, but not on other platforms?

Digging a bit more, I think I found the answer. `pthread_condattr_setclock` is not implemented on Mac OS. See https://github.com/nanomsg/nanomsg/issues/10 for example.
Not sure about `pthread_condattr_setclock` support on other platforms.

**Comment by AspirinSJL** [comment]
I can reproduce https://github.com/grpc/grpc/pull/19808#issue-303171580 on Linux with almost the same log. We need to understand the code logic behind this first.

**Comment by iancoolidge** [comment]
Sorry ---
my phrasing was horrible. LOL.
Linux only supports the monotonic domain.
should read
ONLY Linux supports the monotonic domain.
this is consistent with the lack of support for pthread_condattr_setclock.

**Comment by rmstar** [comment]
Here are the results of some tests on my Macbook Pro. When time goes back >= 1 second, the number of wakeups/sec is around 110k.

|Time offset |     CPU%  |     Wakeups/sec|
|-----------|----------|----------------|
| 0 | 0| 1|
|-10ms|0.8|1k|
|-100ms|7|11k|
|-500ms|37|64k|
|-750ms|43|75k|
|-1s|66|110k|
|-10s|65|110k|
|-100s|65|110k|
|-1 hour|65|110k|

**Comment by rmstar** [comment]
Sorry for the false alarm, `TimerTest.TimeJumpsBackwards` is incorrect. The test is changing the implementation of `gpr_now`, which affects time seen by grpc, but it doesn't change the OS's view of time. `pthread_cond_timedwait` sees the correct system clock, while grpc code sees the fake time that was injected by the test. 

However, the issue mentioned in https://github.com/grpc/grpc/pull/19808#issue-303171580 is still valid. We need to understand why we get multiple wakeups when a timer is created.

**Pull request closed without merging**
