### PR TITLE
Add scripts for creating performance worker VMs

### PR DESCRIPTION
**Pull request by jtattermusch**
Will be useful for creating more worker VMs.

### CODE REVIEW

**Comment by vjpai** [comment]
So, I know that we're not running these in docker for the time being, but would it be possible to get the same version of clang that we use in the C++ standard tests, in case there are optimizations in there that aren't present in the older apt-get version?

**Comment by vjpai** [comment]
Otherwise, LGTM

**Comment by jtattermusch** [comment]
Sure, why not. But currently we are running all the performance tests compiled by gcc, so clang version doesn't really bother us. Let's make *actually running* the tests the priority and figure out relative details later.

**Comment by vjpai** [comment]
Sounds good.
LGTM

**Pull request merged**
