### PR TITLE
Incorporate feedback from API review: Use IAsyncEnumerator to represent async read stream

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by jtattermusch** [comment]
C# tests are green, not sure what's wrong with python and ruby.

**Comment by tbetbetbe** [comment]
C# fails on travis, PTAL

Errors:
/home/travis/build/grpc/grpc/src/csharp/Grpc.sln (default targets) ->
(Build target) ->
/home/travis/build/grpc/grpc/src/csharp/Grpc.Examples.Tests/Grpc.Examples.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
	MathClientServerTests.cs(119,44): error CS0012: The type `System.Collections.Generic.IAsyncEnumerator`1<TResponse>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
	 4 Warning(s)
	 1 Error(s)
Time Elapsed 00:00:02.8333170
FAILED: tools/run_tests/build_csharp.sh [ret=1]
FAILED: Some tests failed

**Comment by tbetbetbe** [comment]
C# build failed on travis, PTAL

Build FAILED.
Warnings:
/home/travis/build/grpc/grpc/src/csharp/Grpc.sln (default targets) ->
(Build target) ->
/home/travis/build/grpc/grpc/src/csharp/Grpc.Core/Grpc.Core.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
	Internal/AsyncCallBase.cs(65,24): warning CS0649: Field `Grpc.Core.Internal.AsyncCallBase<TWrite,TRead>.errorOccured' is never assigned to, and will always have its default value `false'
/home/travis/build/grpc/grpc/src/csharp/Grpc.sln (default targets) ->
(Build target) ->
/home/travis/build/grpc/grpc/src/csharp/Grpc.Examples/Grpc.Examples.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
	MathServiceImpl.cs(73,47): warning CS1998: Async block lacks `await' operator and will run synchronously
/home/travis/build/grpc/grpc/src/csharp/Grpc.sln (default targets) ->
(Build target) ->
/home/travis/build/grpc/grpc/src/csharp/Grpc.Core.Tests/Grpc.Core.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
	ClientServerTest.cs(223,43): warning CS1998: Async block lacks `await' operator and will run synchronously
	ClientServerTest.cs(235,41): warning CS1998: Async block lacks `await' operator and will run synchronously
Errors:
/home/travis/build/grpc/grpc/src/csharp/Grpc.sln (default targets) ->
(Build target) ->
/home/travis/build/grpc/grpc/src/csharp/Grpc.Examples.Tests/Grpc.Examples.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
	MathClientServerTests.cs(119,44): error CS0012: The type `System.Collections.Generic.IAsyncEnumerator`1<TResponse>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
	 4 Warning(s)
	 1 Error(s)

**Comment by jtattermusch** [comment]
The last commit should be fixes the failure you have posted.

**Comment by nathanielmanistaatgoogle** [comment]
How bad a colleague would I be if I asked for commit squashing?

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle  I've squashed the commits and I am really hoping you appreciate that, because it's obviously gonna cost me half a day of waiting for travis to finish the build :-)

**Comment by jtattermusch** [comment]
Green!

**Pull request merged**
