### PR TITLE
Protect Spammy Log with Tracer

### PR DESCRIPTION
**Pull request by ncteisen**
NO_BUG=logs

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,938      Total (>)      1,965,922

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,000      Total (<)     10,909,004

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Repro instructions:

```
LAPTOP ~/Desktop/grpc [master] (0) $ uname
Darwin
LAPTOP ~/Desktop/grpc [master] (0) $ export GRPC_VERBOSITY=debug
LAPTOP ~/Desktop/grpc [master] (0) $ bins/opt/h2_full_test simple_request
D1016 08:02:33.708854000 140735808258944 test_config.cc:391]           test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D1016 08:02:33.710309000 140735808258944 ev_posix.cc:169]              Using polling engine: poll
D1016 08:02:33.710400000 140735808258944 dns_resolver.cc:338]          Using native dns resolver
I1016 08:02:33.710446000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.712873000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.713142000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.720287000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.720388000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.720478000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:2768
D1016 08:02:33.720494000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.721383000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.721672000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa60602260 for subchannel 0x7faa60701220
D1016 08:02:33.721942000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58918
D1016 08:02:33.721954000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:2768
I1016 08:02:33.722248000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.723082000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.723204000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.724688000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.724757000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.724837000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:29871
D1016 08:02:33.724848000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.725733000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.725991000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa60703870 for subchannel 0x7faa62001840
D1016 08:02:33.726176000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58921
D1016 08:02:33.726186000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:29871
I1016 08:02:33.726411000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.727263000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.727388000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.742574000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.742625000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.742724000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:23685
D1016 08:02:33.742736000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.743612000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.743859000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa62002520 for subchannel 0x7faa60501730
D1016 08:02:33.744032000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58924
D1016 08:02:33.744043000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:23685
I1016 08:02:33.744258000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.744886000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.744999000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.746308000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.746354000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.746422000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:2279
D1016 08:02:33.746432000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.747142000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.747348000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa62000e60 for subchannel 0x7faa60604ba0
D1016 08:02:33.747489000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58927
D1016 08:02:33.747500000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:2279
I1016 08:02:33.747718000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.748351000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.748474000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.749976000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.750028000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.750102000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:17129
D1016 08:02:33.750129000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.750960000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.751282000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa605020a0 for subchannel 0x7faa62000b90
D1016 08:02:33.751520000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58930
D1016 08:02:33.751534000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:17129
I1016 08:02:33.751798000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.753473000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.753658000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.755617000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.755667000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.755738000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:6968
D1016 08:02:33.755755000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.756571000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.756850000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa60503320 for subchannel 0x7faa60702720
D1016 08:02:33.757120000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58933
D1016 08:02:33.757137000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:6968
I1016 08:02:33.757413000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.758112000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.758239000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.759475000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.759521000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.759584000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:15106
D1016 08:02:33.759598000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.760250000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.760401000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa62004bc0 for subchannel 0x7faa62001c60
D1016 08:02:33.760598000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58936
D1016 08:02:33.760610000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:15106
I1016 08:02:33.760859000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.761507000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.761635000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.762862000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.762908000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.762960000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:25800
D1016 08:02:33.762971000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.763635000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.763924000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa60703260 for subchannel 0x7faa60501650
D1016 08:02:33.764120000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58939
D1016 08:02:33.764132000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:25800
I1016 08:02:33.764395000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.765050000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.765178000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.766369000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.766414000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.766465000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:14902
D1016 08:02:33.766475000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.767118000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.767313000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa60705600 for subchannel 0x7faa607003c0
D1016 08:02:33.767452000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58942
D1016 08:02:33.767464000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:14902
I1016 08:02:33.767693000 140735808258944 simple_request.cc:40]         Running test: test_invoke_simple_request/chttp2/fullstack
I1016 08:02:33.768323000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.768453000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.769618000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.769664000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.769716000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:23676
D1016 08:02:33.769726000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.770358000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.770545000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa607021b0 for subchannel 0x7faa62003390
D1016 08:02:33.770700000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58945
D1016 08:02:33.770712000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:23676
I1016 08:02:33.770925000 140735808258944 simple_request.cc:40]         Running test: test_invoke_10_simple_requests/chttp2/fullstack
I1016 08:02:33.771613000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.771719000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.772810000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.772854000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
D1016 08:02:33.772903000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.772913000 140735808258944 dns_resolver.cc:279]          Start resolving.
I1016 08:02:33.773577000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.773755000 140735808258944 subchannel.cc:663]            New connected subchannel at 0x7faa62300ec0 for subchannel 0x7faa60605300
D1016 08:02:33.774009000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.774021000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.774133000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 0
D1016 08:02:33.774147000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.774219000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.774229000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.774332000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 1
D1016 08:02:33.774351000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.774416000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.774426000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.774508000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 2
D1016 08:02:33.774522000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.774587000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.774619000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.774722000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 3
D1016 08:02:33.774736000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.774823000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.774833000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.774911000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 4
D1016 08:02:33.774925000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.774983000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.774993000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.775086000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 5
D1016 08:02:33.775102000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.775167000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.775177000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.775288000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 6
D1016 08:02:33.775304000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.775367000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.775377000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.775450000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 7
D1016 08:02:33.775463000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.775517000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.775526000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.775596000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 8
D1016 08:02:33.775608000 140735808258944 simple_request.cc:123]        client_peer_before_call=localhost:1283
D1016 08:02:33.775661000 140735808258944 simple_request.cc:168]        server_peer=ipv6:[::1]:58948
D1016 08:02:33.775670000 140735808258944 simple_request.cc:172]        client_peer=ipv6:[::1]:1283
I1016 08:02:33.775736000 140735808258944 simple_request.cc:268]        Running test: Passed simple request 9
D1016 08:02:33.776141000 140735808258944 ev_posix.cc:169]              Using polling engine: poll
D1016 08:02:33.776159000 140735808258944 dns_resolver.cc:338]          Using native dns resolver
I1016 08:02:33.776967000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.777075000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.778362000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.778484000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.779762000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.779865000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.781037000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.781144000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.782298000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.782407000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.783528000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.783657000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.785561000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.785681000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.786900000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.786999000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.788264000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.788369000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.789648000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.789762000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.791373000 123145420038144 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
I1016 08:02:33.791514000 140735808258944 socket_utils_common_posix.cc:310] TCP_USER_TIMEOUT not supported for this platform
```

**Comment by ncteisen** [comment]
In future, would be happy with removing the tracer check as long as it only happens once per process or something

**Pull request merged**
