### PR TITLE
codegen: Correct indentation

### PR DESCRIPTION
**Pull request by VPeruS**
Added single space to align 'private:' with 'public:'(generated on line 1350).

@markdroth

### CODE REVIEW

**Comment by markdroth** [comment]
It looks like this PR is causing test failures because of a golden file that checks the output.  If you update the file to match the new output, it should pass.

**Comment by VPeruS** [comment]
Fixed golden file.

**Comment by markdroth** [comment]
I've re-triggered the tests.  Let's see if they're happy now.

**Comment by markdroth** [comment]
Known issues: #26595 

The "Basic Tests PHP MacOS" failure is an infrastructure timeout.

**Review by markdroth — APPROVED** [review]

**Pull request merged**
