### PR TITLE
Delete BUILD.gn

### PR DESCRIPTION
**Pull request by tamird**
This was erroneously added in https://github.com/grpc/grpc/pull/27193
via bad merge conflict resolution.

The presence of this file makes it impossible for Fuchsia to update
grpc.

@veblush

### CODE REVIEW

**Comment by drfloob** [comment]
@tamird Thanks for contributing. Is this a critical bug at all? We generally only do patch releases when they are absolutely essential, it's an onerous process that takes a few days of testing and requires a half dozen people participate. This backport PR is fine to land, but it would not be actionable unless having `BUILD.gn` in the build is a significant problem.

**Comment by tamird** [comment]
As mentioned in the commit message and PR description, the presence of this file in any released version makes that version *unusable* in Fuchsia's build system.

**Comment by drfloob** [comment]
Understood. BUILD.gn existed in the v1.44.0 release as well, which has been out since February. Maybe nobody in the Fuchsia community has attempted to upgrade? The v1.46.0 release will be coming out in a week or two, might it be possible to skip v1.45, or do you need v1.45 for some specific reason?

**Comment by tamird** [comment]
Yes, nobody has attempted to update for some time. We're ok with skipping 1.45.

**Comment by drfloob** [comment]
@tamird Let's make that the plan, then. The tests will not pass due to CI changes that have happened since this release, and we'd need an admin to force-merge it.

**Comment by nicolasnoble** [comment]
Someone called?

**Pull request closed without merging**
