### PR TITLE
Upgrading protobuf

### PR DESCRIPTION
**Pull request by jtattermusch**
Closes #1455 and #1628.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Everything's fine in terms of CLA, @nicolasnoble is Googler.

**Comment by nathanielmanistaatgoogle** [comment]
Commit message should say *to what version* of protobuf this change migrates the code.

**Comment by jtattermusch** [comment]
Updated the commit message.

**Comment by nathanielmanistaatgoogle** [comment]
Merging now and killing the Travis build. #1455 shows passing tests against exactly the same diff.

**Comment by ctiller** [comment]
Looks like this has introduced a great deal of flakiness.

Perhaps just canceling Travis and ignoring failures without reporting them wasn't a great idea?

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller: help me understand the error in my judgement? #1455 showed a history of this content-change passing. When @jtattermusch reconstituted this change as a new pull request, he likely did so against a different master point, but with the same diff. I didn't think that the risk of the same diff against a different head was worth the resource consumption of a new test execution - better that execution to have gone into testing as-yet-untested content, I thought. Was that the wrong decision?

**Comment by ctiller** [comment]
I see two Travis runs for that change here:
https://travis-ci.org/grpc/grpc/pull_requests (although I can't see what
code was included in them)
The first failed: https://travis-ci.org/grpc/grpc/builds/63203085
The second succeeded: https://travis-ci.org/grpc/grpc/builds/63217461

The first was an error that hadn't been seen for some time.
It was ignored, and (I assume) a flattened version was pushed.
The new version was then submitted.

Whether you saw the initial Travis failure or not, I don't know. If not, no
harm. I would be surprised if no-one did though.

The flakiness was wholly anticipated by Nico, and we know how to fix it.
It's now a scramble to get things organized versus something that could be
planned, however.

**Pull request merged**
