### PR TITLE
Add method for creating insecure channel from FD with custom arguments using C++ API.

### PR DESCRIPTION
**Pull request by gislan**
This was already supported in C API.

### CODE REVIEW

**Comment by gislan** [comment]
@ctiller would you mind taking a look at this?

**Comment by gislan** [comment]
What's the next step here? Someone with admin powers needs to tell Jenkins to run test?

**Comment by ctiller** [comment]
Jenkins: test this please

**Comment by gislan** [comment]
Hmm...none of those failures seem related to my change. One of them is:
/bin/bash: rvm: command not found
The command '/bin/sh -c /bin/bash -l -c "rvm install ruby-2.1"' returned a non-zero code: 127
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1126, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tools/run_tests/dockerize/build_docker_and_run_tests.sh']' returned non-zero exit status 127

Another one is some kind of benchmark that doesn't even call the method I'm adding here.

Is it possible these tests are just flaky?

**Comment by gislan** [comment]
@ctiller @yang-g Do you agree that the failures are flakes / unrelated? How do I proceed?

**Comment by yang-g** [comment]
The tests look like flaky to me.

**Pull request merged**
