### PR TITLE
[PSM Interop] Delete PSM interop source per new repo migration

### PR DESCRIPTION
**Pull request by sergiitk**
New source of truth: https://github.com/grpc/psm-interop.

This PR removes PSM Interop framework source code from `tools/run_tests/xds_k8s_test_driver`, and all references to it.

### CODE REVIEW

**Comment by sergiitk** [comment]
Note to the reviewers: the first commit just removes the source, no need to review. See the other two for actual changes.

**Review by XuanWang-Amos — APPROVED** [review]
This calls for a celebration! 🥳

**Comment by sergiitk** [comment]
Looks like we need to merge https://github.com/grpc/grpc/pull/35507 first.

**Comment by sergiitk** [comment]
Rebased against master so that `.github/workflows/psm-interop.yaml` is not a part of this PR anymore.

**Pull request closed without merging**
