### PR TITLE
Revert "Allow to specify user provided audience in google default credentials and JWT credentials"

### PR DESCRIPTION
**Pull request by lidizheng**
Reverts grpc/grpc#26392

This API change broke: https://fusion2.corp.google.com/invocations;query=label:tap%20label:postsubmit%20cl:377715297%20target:%2F%2Fgooglemac%2FGoogleMobile:GoogleEarlGreyTestRig.apple_binary

See build log:
https://fusion2.corp.google.com/invocations;query=label:tap%20label:postsubmit%20cl:377715297%20target:%2F%2Fgooglemac%2FGoogleMobile:GoogleEarlGreyTestRig.apple_binary/8a15f678-e5d5-4baa-afc8-b3c1910ae8d5/log

gRPC-Swift is depending on the `grpc_google_default_credentials_create` API.

### CODE REVIEW

**Comment by markdroth** [comment]
We don't promise backward compatibility for the C-core API.  I think the right answer for this is to change the grpc-swift code to use the new API.

**Review by veblush — APPROVED** [review]

**Comment by markdroth** [comment]
If @yihuazhang can fix this for grpc-swift and we want to roll back just long enough to allow him to do that, then I'm fine with that.  I just don't want to allow this breakage to completely prevent us from making this change, since this isn't something that we guarantee not to break.

**Comment by lidizheng** [comment]
@markdroth Sounds good. Let's wait for @yihuazhang to decide.

**Comment by lidizheng** [comment]
@markdroth I just found out that @yihuazhang will be OOO till next week. Can we merge this rollback first to unblock the import?

**Comment by markdroth** [comment]
Yes, if this is blocking the import, let's go ahead and merge it.

**Pull request merged**
