### PR TITLE
Update Cds response parsing for tls

### PR DESCRIPTION
**Pull request by yashykt**
I wish we didn't need to add logic like this and could directly add the proto messages.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24285)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks good, only a few minor comments.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24285#-:-MIWDzXABhUFFSMMK4Nn:b-l8d1pn)* status: all files reviewed, 4 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 173 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWBAxj19XL2YeJ0fSG:-MIWBAxk5QdzdjcnN0IS:byr74qh) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.h#L173)):*
> ```objc
> 
>   struct CommonTlsContext {
>     struct CertificateProviderInstance {
> ```

I don't think we need this struct.  We can just directly use a `std::string` for the instance name.
___
*[src/core/ext/xds/xds_api.cc, line 1806 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWC0K7CR39-TxmsTmN:-MIWC0K7CR39-TxmsTmO:btz760n) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1806)):*
> ```cpp
>     XdsApi::CommonTlsContext::CertificateProviderInstance*
>         certificate_provider_instance) GRPC_MUST_USE_RESULT;
> grpc_error* CertificateProviderInstanceParse(
> ```

There's no reason to have this return an error, since it always returns `GRPC_ERROR_NONE`.

Actually, given that the entire function is just one statement, it's probably not needed at all.  I suggest just removing it and inlining the code in the couple of places where it's used.
___
*[src/core/ext/xds/xds_api.cc, line 1825 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWCWp7AFK5eypxBr4h:-MIWCWp7AFK5eypxBr4i:b-643edg) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1825)):*
> ```cpp
>         common_tls_context_proto,
>     XdsApi::CommonTlsContext* common_tls_context) {
>   if (envoy_extensions_transport_sockets_tls_v3_CommonTlsContext_has_combined_validation_context(
> ```

In general, instead of this:

```
if (type_has_foo(msg)) {
  foo* f = type_foo(msg);
  ...
}
```

you can just say:

```
foo* f = type_foo(msg);
if (f != nullptr) {
  ...
}
```

Given the long upb function names here, this will reduce some redundancy and make the code a lot more readable.
___
*[src/core/ext/xds/xds_api.cc, line 1987 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWDaHX-xrxCiKyCmZR:-MIWDaHX-xrxCiKyCmZS:b-3vf2it) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1987)):*
> ```cpp
>       auto* transport_socket =
>           envoy_config_cluster_v3_Cluster_transport_socket(cluster);
>       upb_strview name =
> ```

This would be clearer if written as:

```
absl::string_view name = UpbStringToAbsl(
    envoy_config_core_v3_TransportSocket_name(transport_socket));
if (name == "tls") {
```

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24285)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 173 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWBAxj19XL2YeJ0fSG:-MIWG4Pq7dLHgvYJFMCm:b-29kbcv) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.h#L173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need this struct.  We can just directly use a `std::string` for the instance name.
</blockquote></details>

I wanted to make it future-proof for example if in the future, we end up using the field - certificate_name or if we add another field here
___
*[src/core/ext/xds/xds_api.cc, line 1806 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWC0K7CR39-TxmsTmN:-MIWGGSYCzsLASLmJbaF:bk9dndr) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1806)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no reason to have this return an error, since it always returns `GRPC_ERROR_NONE`.

Actually, given that the entire function is just one statement, it's probably not needed at all.  I suggest just removing it and inlining the code in the couple of places where it's used.
</blockquote></details>

I can probably remove the grpc_error return. It is a separate function mainly because this parsing happens twice.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24285)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 1825 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWCWp7AFK5eypxBr4h:-MIWGsvADF7cGcf2ETKb:bub7xcs) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1825)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In general, instead of this:

```
if (type_has_foo(msg)) {
  foo* f = type_foo(msg);
  ...
}
```

you can just say:

```
foo* f = type_foo(msg);
if (f != nullptr) {
  ...
}
```

Given the long upb function names here, this will reduce some redundancy and make the code a lot more readable.
</blockquote></details>

Is this guaranteed to work?

**Review by markdroth — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24285)* status: all files reviewed, 4 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 173 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWBAxj19XL2YeJ0fSG:-MIWIjoQ8uBqa0QuU1Us:b54etl5) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.h#L173)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I wanted to make it future-proof for example if in the future, we end up using the field - certificate_name or if we add another field here
</blockquote></details>

This isn't an externally visible API, so there's no need to future-proof it.  Let's keep it as simple as it needs to be for now, and we can make it more complicated if we need additional fields later.
___
*[src/core/ext/xds/xds_api.cc, line 1806 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWC0K7CR39-TxmsTmN:-MIWIsOc5CvbRruPkmq2:b-l5z4r2) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1806)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I can probably remove the grpc_error return. It is a separate function mainly because this parsing happens twice.
</blockquote></details>

Right, but the call to this function is almost as long as the code contained in the function, so I'm not sure there's much benefit.
___
*[src/core/ext/xds/xds_api.cc, line 1825 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWCWp7AFK5eypxBr4h:-MIWIy0U0Pes1t72B60m:bqaj5bp) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1825)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Is this guaranteed to work?
</blockquote></details>

I believe so.  We're depending on it elsewhere in this parser code.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24285)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 173 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWBAxj19XL2YeJ0fSG:-MIWLVt-Cqt2fBprz2M6:brpmqbq) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.h#L173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't an externally visible API, so there's no need to future-proof it.  Let's keep it as simple as it needs to be for now, and we can make it more complicated if we need additional fields later.
</blockquote></details>

removed!
___
*[src/core/ext/xds/xds_api.cc, line 1806 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWC0K7CR39-TxmsTmN:-MIWLXWX38dnPoffRq0F:bss4a1y) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1806)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Right, but the call to this function is almost as long as the code contained in the function, so I'm not sure there's much benefit.
</blockquote></details>

Removed!
___
*[src/core/ext/xds/xds_api.cc, line 1825 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWCWp7AFK5eypxBr4h:-MIWLiInCjc1VMbz0SJe:b-896fja) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1825)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I believe so.  We're depending on it elsewhere in this parser code.
</blockquote></details>

Done!
___
*[src/core/ext/xds/xds_api.cc, line 1987 at r1](https://reviewable.io/reviews/grpc/grpc/24285#-MIWDaHX-xrxCiKyCmZR:-MIWLkJA6TFTHScfmmWV:b-896fja) ([raw file](https://github.com/grpc/grpc/blob/7bc5c082dd8cb71513e0d549eaad508dbfc21846/src/core/ext/xds/xds_api.cc#L1987)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This would be clearer if written as:

```
absl::string_view name = UpbStringToAbsl(
    envoy_config_core_v3_TransportSocket_name(transport_socket));
if (name == "tls") {
```
</blockquote></details>

Done!

**Review by markdroth — APPROVED** [review]
Just one more minor nit.  Feel free to merge after addressing.  Thanks!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24285#-:-MIWNHow16wdgJuopyvK:b-3bn4dv)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 1821 at r2](https://reviewable.io/reviews/grpc/grpc/24285#-MIWN-Zs2olzmvEcs_Y8:-MIWN-Zs2olzmvEcs_Y9:b-k9ir2v) ([raw file](https://github.com/grpc/grpc/blob/c8f2e55012625a0d2fdf97c0e30c4cc28d8dbad4/src/core/ext/xds/xds_api.cc#L1821)):*
> ```cpp
>           envoy_extensions_transport_sockets_tls_v3_CertificateValidationContext_match_subject_alt_names(
>               default_validation_context, &len);
>       if (subject_alt_names_matchers != nullptr) {
> ```

This check is not needed, because if it's null, `len`  will be 0, so the loop below will never be entered in the first place.

**Comment by yashykt** [comment]
Thanks for reviewing!

**Comment by yashykt** [comment]
___
*[src/core/ext/xds/xds_api.cc, line 1821 at r2](https://reviewable.io/reviews/grpc/grpc/24285#-MIWN-Zs2olzmvEcs_Y8:-MI_q9XJ9a2bzO4E6L8z:ba3dfob) ([raw file](https://github.com/grpc/grpc/blob/c8f2e55012625a0d2fdf97c0e30c4cc28d8dbad4/src/core/ext/xds/xds_api.cc#L1821)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check is not needed, because if it's null, `len`  will be 0, so the loop below will never be entered in the first place.
</blockquote></details>

Removed

**Pull request merged**
