### PR TITLE
Show actual thread id in windows logs

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
No, sorry, we can't do that, because then the API would be inconsistent as to what a `gpr_thd_id` represents and how it can be manipulated.

**Comment by jtattermusch** [comment]
I see. I will try to come up with something less intrusive. Btw, reporting the thread id what is basically a pointer doesn't really make much sense in logs. At least on windows, seeing the actual thread ids is pretty useful for debugging.

**Comment by nicolasnoble** [comment]
Well, when looking at logs, you can follow thread jumps at least. Personally I usually debug at looking "what has the same thread id number".

Also note that if you're actively in a debugger, you can do a watch that'll resolve our threadid into the real one, by going into the structure and plucking it out.

**Comment by ctiller** [comment]
You can't though.  We only capture a pointer for threads created by GPR.
Actually in preference of using the windows id for gpr_thd_id and having a
lookup table for gpr_thd_join.

**Comment by nicolasnoble** [comment]
Right, that wouldn't work in the case a system thread tries to do gpr_log. It'll display 0 instead.

**Pull request closed without merging**
