### PR TITLE
Add python3 to list of acceptable pythons in python wrapper

### PR DESCRIPTION
**Pull request by apolcyn**
This is an attempt to fix fix httpcli portability tests which have been failing continuously since what appears to be https://github.com/grpc/grpc/pull/28010/files, with example log: https://source.cloud.google.com/results/invocations/34f2174c-5660-4f37-9414-a7b0b75c43e1/targets/github%2Fgrpc%2Frun_tests%2Fc_linux_dbg_native_x64_gcc11/tests

b/209014236

### CODE REVIEW

**Review by jtattermusch — APPROVED** [review]
LGTM.

**Comment by apolcyn** [comment]
The fake python server used in these tests doesn't seem to be python3 compatible.

Test now failing:

```
  File "test/core/../../test/core/http/test_server.py", line 30
    print _PEM
```

**Comment by apolcyn** [comment]
After that, the script is now failing with:

```
Traceback (most recent call last):
  File "/Volumes/BuildData/tmpfs/tmp/bazel/sandbox/darwin-sandbox/7009/execroot/com_github_grpc_grpc/bazel-out/darwin-dbg/bin/test/core/http/httpcli_test.runfiles/com_github_grpc_grpc/test/core/../../test/core/http/test_server.py", line 22, in <module>
    import BaseHTTPServer
ModuleNotFoundError: No module named 'BaseHTTPServer'
```

**Comment by apolcyn** [comment]
Test now fails with:

```
Traceback (most recent call last):
  File "test/core/../../test/core/http/test_server.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by jtattermusch** [comment]
Superseded by https://github.com/grpc/grpc/pull/28284.

**Pull request closed without merging**
