### PR TITLE
Make public header files in include/grpcpp/test installed with 'make install'

### LINKED ISSUE #20208: include/grpcpp/test/mock_stream.h is not installed by `make install`
# What version of gRPC and what language are you using?
v1.20.1 & c++

### What operating system (Linux, Windows,...) and version?
Ubuntu 16.04.6 LTS

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 5.4.0

### What did you do?
`cd /tmp && git clone -q --single-branch --depth 1 --branch v1.20.1 https://github.com/grpc/grpc.git && cd grpc && git submodule update --init && make CFLAGS='-Wimplicit-fallthrough=0' CXXFLAGS='-Wimplicit-fallthrough=0' > /dev/null && make install STRIP=/bin/true`

### What did you expect to see?
Expect following header file to be present:
`/usr/local/include/grpcpp/test/mock_stream.h`

### What did you see instead?
All other include files/directories are available except the `/usr/local/include/grpcpp/test` directory.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
I need `mock_stream.h` to be able to write mock tests for my grpc service.

### PR DESCRIPTION
**Pull request by nanahpang**
fix #20208 

@nicolasnoble

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @jtattermusch

**Comment by nanahpang** [comment]
Good question, I haven't ask the user to try it yet, but I tries "make install" on my local machine, and it installed the include/grpcpp/test public headers. I will ask the user to test it first.

**Comment by nanahpang** [comment]
Since the user is idle for a while, I am going to merge this PR first, and then go back to close the issue once he response.

**Comment by jtattermusch** [comment]
I created a revert PR. It seems that this PR has broken a large number of tests.
Some of these failures are apparent from the PR test results (which seems to have been ignored):
https://source.cloud.google.com/results/invocations/49fa74a2-aa1e-4635-b313-2644b151e623
https://source.cloud.google.com/results/invocations/96045046-7c3f-4c9b-afd6-41603e62602c
https://source.cloud.google.com/results/invocations/6f60cd8e-5fad-46d6-a333-0b7ad42c7031

Please double-check the test failures on the PR next time (and mark known failures according to our process).

**Comment by nicolasnoble** [comment]
So the error is "No SOURCES given to target: grpc++_test". @vjpai I remember you found a cmake operand to declare a header-only library. Do you remember what it was? @jtattermusch we'd need to fix the cmake template to use @vjpai's operand for libraries when there's no source, in order to support header-only libraries in the cmakefile.

**Comment by vjpai** [comment]
I found this page about cmake header-only libraries: http://mariobadr.com/creating-a-header-only-library-with-cmake.html  . The magic incantation seems to be `INTERFACE`

**Pull request merged**
