### PR TITLE
Add protobuf_deps to WORKSPACE

### PR DESCRIPTION
**Pull request by rafi-kamal**
See https://github.com/grpc/grpc/pull/20224#issuecomment-531355209

### CODE REVIEW

**Comment by rafi-kamal** [comment]
@gnossen

**Comment by gnossen** [comment]
As I said in my original comment, this change is going to have to be made by all of our downstreams as well, so you'll have to modify [this Bazel test](https://github.com/grpc/grpc/blob/master/bazel/test/python_test_repo/WORKSPACE) as well.

**Comment by rafi-kamal** [comment]
Thanks, added it.

**Comment by gnossen** [comment]
Cross-reference: https://github.com/bazelbuild/bazel/issues/1943

**Comment by rafi-kamal** [comment]
Friendly ping :)

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/20095
the PHP interop errors are due to a transient `"https://packagist.org/p/provider-2019-04%246e9d3eb372b3e43a14ff5ba6e6cb037890da61f8f3288e468ac3a1a1bbbf27c1.json" file could not be downloaded (HTTP/1.1 404 Not Found)` error.

**Pull request merged**
