### PR TITLE
Decrease parallelism in interop tests

### PR DESCRIPTION
**Pull request by jtattermusch**
To see if this helps with https://github.com/grpc/grpc/issues/15540.

Basically we are running 12 parallel builds of all the languages currently.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by matt-kwong** [comment]
We'd also need to change the flags used for pull requests:
https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/pull_request/grpc_interop_tocloud.cfg
https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/pull_request/grpc_interop_toprod.cfg

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
