### PR TITLE
objective-c: Add a GRPCCall extension for the ability to set a hostname override.

### PR DESCRIPTION
**Pull request by wuurrd**

### CODE REVIEW

**Comment by wuurrd** [comment]
I signed it!

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by wuurrd** [comment]
Any chance I can get a review here?

**Comment by muxi** [comment]
@wuurrd - we just started working on this issue too. Could you let me know what is your use cases on this feature? That helps us make a decision of what the design will look like. Thanks!

**Comment by muxi** [comment]
Feature implemented in another PR (#11606). Closing.

**Pull request closed without merging**
