### PR TITLE
EXPERIMENT: Use arena allocation for client-side callback API

### PR DESCRIPTION
**Pull request by vjpai**
Builds on #16492 : the new commit is 9eec9b0
Not yet ready for review
If tests look good on this, I will cherry-pick 9eec9b0 into #16492

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                FILE SIZE
 ++++++++++++++ GROWING                                  ++++++++++++++
  +0.0%     +16 [None]                                      +120  +0.0%
  +0.2%     +16 src/core/lib/surface/completion_queue.cc     +16  +0.2%
       +22%     +20 cq_shutdown_callback                         +20   +22%

  +0.0%     +32 TOTAL                                       +136  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +4.7% +10.5Ki [None]                                                                                +152Ki  +3.0%
      +4.6% +9.54Ki [Unmapped]                                                                            +151Ki  +3.0%
      [NEW]    +216 typeinfo name for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadat    +216  [NEW]
      [NEW]    +136 typeinfo for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, gr    +136  [NEW]
       +16%     +89 [Other]                                                                                  +88   +17%
      [NEW]     +57 typeinfo name for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl         +57  [NEW]
      [NEW]     +56 typeinfo name for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl          +56  [NEW]
      [NEW]     +56 vtable for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc     +56  [NEW]
      [NEW]     +41 typeinfo name for grpc::(anonymous namespace)::ShutdownCallback                          +41  [NEW]
      [NEW]     +40 vtable for grpc::(anonymous namespace)::ShutdownCallback                                 +40  [NEW]
      [NEW]     +40 vtable for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl                 +40  [NEW]
      [NEW]     +40 vtable for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl                +40  [NEW]
      [NEW]     +34 typeinfo name for grpc_core::CQCallbackInterface                                         +34  [NEW]
      [NEW]     +24 typeinfo for grpc::(anonymous namespace)::ShutdownCallback                               +24  [NEW]
      [NEW]     +24 typeinfo for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl               +24  [NEW]
      [NEW]     +24 typeinfo for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl              +24  [NEW]
      [NEW]     +16 typeinfo for grpc_core::CQCallbackInterface                                              +16  [NEW]
       +17%      +8 vtable for grpc::ServerContext::CompletionOp                                              +8   +17%
     +10.0%      +8 vtable for grpc::ChannelInterface                                                         +8 +10.0%
       +17%      +8 vtable for grpc::Server::UnimplementedAsyncResponse                                       +8   +17%
      +5.3%      +8 vtable for grpc::Channel                                                                  +8  +5.3%
      +6.1%      +7 [None]                                                                                     0  [ = ]
   +29% +4.07Ki src/cpp/client/generic_stub.cc                                                       +4.07Ki   +29%
      [NEW] +2.14Ki grpc::GenericStub::experimental_type::UnaryCall                                      +2.14Ki  [NEW]
      [NEW] +1.04Ki grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal: +1.04Ki  [NEW]
      [NEW]    +471 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:    +471  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
      [NEW]     +93 std::function<void (grpc::Status)>::function                                             +93  [NEW]
      [NEW]     +83 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:     +83  [NEW]
      [NEW]     +82 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:     +82  [NEW]
      [NEW]     +50 grpc::Status::~Status                                                                    +50  [NEW]
      +2.0%     +29 grpc::GenericStub::Call                                                                  +29  +2.0%
      +5.4%     +28 grpc::GenericStub::PrepareCall                                                           +28  +5.4%
       +61%     +17 [Unmapped]                                                                               +17   +61%
      +1.0%      +8 grpc::GenericStub::PrepareUnaryCall                                                       +8  +1.0%
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvMessage<grpc::ByteBuffer>, grpc:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +5  [NEW]
      +1.6%      +3 grpc::internal::CallOpSet<grpc::internal::CallOpRecvMessage<grpc::ByteBuffer>, grpc:      +3  +1.6%
  [NEW] +2.32Ki src/cpp/common/callback_common.cc                                                    +2.32Ki  [NEW]
      [NEW]    +445 grpc::internal::CallbackWithStatusTag::CallbackWithStatusTag                            +445  [NEW]
      [NEW]    +400 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::Run                      +400  [NEW]
      [NEW]    +370 grpc::internal::CallbackWithSuccessTag::CallbackWithSuccessTag                          +370  [NEW]
      [NEW]    +326 grpc::internal::CallbackWithStatusTag::force_run                                        +326  [NEW]
      [NEW]    +245 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::Run                     +245  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
      [NEW]     +85 [Unmapped]                                                                               +85  [NEW]
      [NEW]     +82 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::~CallbackWithStatusIm     +82  [NEW]
      [NEW]     +82 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::~CallbackWithStatusIm     +82  [NEW]
      [NEW]     +46 _GLOBAL__sub_I_callback_common.cc                                                        +46  [NEW]
      [NEW]     +42 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::~CallbackWithSuccess     +42  [NEW]
      [NEW]     +42 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::~CallbackWithSuccess     +42  [NEW]
      [NEW]     +13 grpc::internal::CallbackWithSuccessTag::force_run                                        +13  [NEW]
   +15%    +691 src/cpp/client/channel_cc.cc                                                            +691   +15%
      [NEW]    +537 grpc::Channel::CallbackCQ                                                               +537  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
       +19%     +64 grpc::Channel::Channel                                                                   +64   +19%
      [NEW]     +28 grpc::(anonymous namespace)::ShutdownCallback::Run                                       +28  [NEW]
       +12%     +24 [Unmapped]                                                                               +24   +12%
      +6.2%     +16 grpc::Channel::~Channel                                                                  +16  +6.2%
      [NEW]      +9 grpc::(anonymous namespace)::ShutdownCallback::~ShutdownCallback                          +9  [NEW]
      +4.3%      +8 grpc::Channel::PerformOpsOnCall                                                           +8  +4.3%
      [NEW]      +3 grpc::ChannelInterface::CallbackCQ                                                        +3  [NEW]
      [NEW]      +2 grpc::(anonymous namespace)::ShutdownCallback::~ShutdownCallback                          +2  [NEW]
  +0.5%     +25 src/cpp/server/server_context.cc                                                         +25  +0.5%
      +7.2%      +9 [Unmapped]                                                                                +9  +7.2%
      +2.0%      +7 grpc::ServerContext::ServerContext                                                        +7  +2.0%
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +4 grpc::ServerContext::CompletionOp::cq_tag                                                 +4  [NEW]
  +0.2%     +24 src/cpp/server/health/default_health_check_service.cc                                    +24  +0.2%
      +0.4%     +16 grpc::internal::RpcMethodHandler<grpc::DefaultHealthCheckService::HealthCheckService     +16  +0.4%
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]

 -------------- SHRINKING                                                                            --------------
  -0.1%     -24 src/cpp/server/server_cc.cc                                                              -24  -0.1%
      [DEL]     -50 grpc::Status::~Status                                                                    -50  [DEL]
      -1.1%     -31 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>::RunHandler                     -31  -1.1%
      -1.1%     -31 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>::RunHandler                      -31  -1.1%
      -0.3%      -1 [Unmapped]                                                                                -1  -0.3%

  +4.9% +17.5Ki TOTAL                                                                                 +159Ki  +3.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,030      Total (>)      1,955,026

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,756      Total (>)     10,843,754

 No significant differences in binary sizes


```

**Comment by vjpai** [comment]
Needs a little work. The `std::function` in the tags isn't POD, so it doesn't fit nicely in the arena without a proper deletion of some kind.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                FILE SIZE
 ++++++++++++++ GROWING                                  ++++++++++++++
  +0.0%     +16 [None]                                      +120  +0.0%
  +0.2%     +16 src/core/lib/surface/completion_queue.cc     +16  +0.2%
       +22%     +20 cq_shutdown_callback                         +20   +22%

  +0.0%     +32 TOTAL                                       +136  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +4.7% +10.5Ki [None]                                                                                +152Ki  +3.0%
      +4.6% +9.58Ki [Unmapped]                                                                            +151Ki  +3.0%
      [NEW]    +216 typeinfo name for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadat    +216  [NEW]
      [NEW]    +136 typeinfo for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, gr    +136  [NEW]
       +16%     +89 [Other]                                                                                  +88   +17%
      [NEW]     +57 typeinfo name for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl         +57  [NEW]
      [NEW]     +56 typeinfo name for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl          +56  [NEW]
      [NEW]     +56 vtable for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc     +56  [NEW]
      [NEW]     +41 typeinfo name for grpc::(anonymous namespace)::ShutdownCallback                          +41  [NEW]
      [NEW]     +40 vtable for grpc::(anonymous namespace)::ShutdownCallback                                 +40  [NEW]
      [NEW]     +40 vtable for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl                 +40  [NEW]
      [NEW]     +40 vtable for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl                +40  [NEW]
      [NEW]     +34 typeinfo name for grpc_core::CQCallbackInterface                                         +34  [NEW]
      [NEW]     +24 typeinfo for grpc::(anonymous namespace)::ShutdownCallback                               +24  [NEW]
      [NEW]     +24 typeinfo for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl               +24  [NEW]
      [NEW]     +24 typeinfo for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl              +24  [NEW]
      [NEW]     +16 typeinfo for grpc_core::CQCallbackInterface                                              +16  [NEW]
       +17%      +8 vtable for grpc::ServerContext::CompletionOp                                              +8   +17%
     +10.0%      +8 vtable for grpc::ChannelInterface                                                         +8 +10.0%
       +17%      +8 vtable for grpc::Server::UnimplementedAsyncResponse                                       +8   +17%
      +5.3%      +8 vtable for grpc::Channel                                                                  +8  +5.3%
      +6.1%      +7 [None]                                                                                     0  [ = ]
   +29% +4.07Ki src/cpp/client/generic_stub.cc                                                       +4.07Ki   +29%
      [NEW] +2.14Ki grpc::GenericStub::experimental_type::UnaryCall                                      +2.14Ki  [NEW]
      [NEW] +1.04Ki grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal: +1.04Ki  [NEW]
      [NEW]    +471 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:    +471  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
      [NEW]     +93 std::function<void (grpc::Status)>::function                                             +93  [NEW]
      [NEW]     +83 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:     +83  [NEW]
      [NEW]     +82 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:     +82  [NEW]
      [NEW]     +50 grpc::Status::~Status                                                                    +50  [NEW]
      +2.0%     +29 grpc::GenericStub::Call                                                                  +29  +2.0%
      +5.4%     +28 grpc::GenericStub::PrepareCall                                                           +28  +5.4%
       +61%     +17 [Unmapped]                                                                               +17   +61%
      +1.0%      +8 grpc::GenericStub::PrepareUnaryCall                                                       +8  +1.0%
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvMessage<grpc::ByteBuffer>, grpc:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +5  [NEW]
      +1.6%      +3 grpc::internal::CallOpSet<grpc::internal::CallOpRecvMessage<grpc::ByteBuffer>, grpc:      +3  +1.6%
  [NEW] +2.41Ki src/cpp/common/callback_common.cc                                                    +2.41Ki  [NEW]
      [NEW]    +445 grpc::internal::CallbackWithStatusTag::CallbackWithStatusTag                            +445  [NEW]
      [NEW]    +440 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::Run                      +440  [NEW]
      [NEW]    +370 grpc::internal::CallbackWithSuccessTag::CallbackWithSuccessTag                          +370  [NEW]
      [NEW]    +326 grpc::internal::CallbackWithStatusTag::force_run                                        +326  [NEW]
      [NEW]    +293 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::Run                     +293  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
      [NEW]     +93 [Unmapped]                                                                               +93  [NEW]
      [NEW]     +82 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::~CallbackWithStatusIm     +82  [NEW]
      [NEW]     +82 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::~CallbackWithStatusIm     +82  [NEW]
      [NEW]     +46 _GLOBAL__sub_I_callback_common.cc                                                        +46  [NEW]
      [NEW]     +42 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::~CallbackWithSuccess     +42  [NEW]
      [NEW]     +42 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::~CallbackWithSuccess     +42  [NEW]
      [NEW]     +13 grpc::internal::CallbackWithSuccessTag::force_run                                        +13  [NEW]
   +15%    +691 src/cpp/client/channel_cc.cc                                                            +691   +15%
      [NEW]    +537 grpc::Channel::CallbackCQ                                                               +537  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
       +19%     +64 grpc::Channel::Channel                                                                   +64   +19%
      [NEW]     +28 grpc::(anonymous namespace)::ShutdownCallback::Run                                       +28  [NEW]
       +12%     +24 [Unmapped]                                                                               +24   +12%
      +6.2%     +16 grpc::Channel::~Channel                                                                  +16  +6.2%
      [NEW]      +9 grpc::(anonymous namespace)::ShutdownCallback::~ShutdownCallback                          +9  [NEW]
      +4.3%      +8 grpc::Channel::PerformOpsOnCall                                                           +8  +4.3%
      [NEW]      +3 grpc::ChannelInterface::CallbackCQ                                                        +3  [NEW]
      [NEW]      +2 grpc::(anonymous namespace)::ShutdownCallback::~ShutdownCallback                          +2  [NEW]
  +0.5%     +25 src/cpp/server/server_context.cc                                                         +25  +0.5%
      +7.2%      +9 [Unmapped]                                                                                +9  +7.2%
      +2.0%      +7 grpc::ServerContext::ServerContext                                                        +7  +2.0%
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +4 grpc::ServerContext::CompletionOp::cq_tag                                                 +4  [NEW]
  +0.2%     +24 src/cpp/server/health/default_health_check_service.cc                                    +24  +0.2%
      +0.4%     +16 grpc::internal::RpcMethodHandler<grpc::DefaultHealthCheckService::HealthCheckService     +16  +0.4%
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]

 -------------- SHRINKING                                                                            --------------
  -0.1%     -24 src/cpp/server/server_cc.cc                                                              -24  -0.1%
      [DEL]     -50 grpc::Status::~Status                                                                    -50  [DEL]
      -1.1%     -31 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>::RunHandler                     -31  -1.1%
      -1.1%     -31 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>::RunHandler                      -31  -1.1%
      -0.3%      -1 [Unmapped]                                                                                -1  -0.3%

  +4.9% +17.7Ki TOTAL                                                                                 +159Ki  +3.1%



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                FILE SIZE
 ++++++++++++++ GROWING                                  ++++++++++++++
  +0.0%     +16 [None]                                      +120  +0.0%
  +0.2%     +16 src/core/lib/surface/completion_queue.cc     +16  +0.2%
       +22%     +20 cq_shutdown_callback                         +20   +22%

  +0.0%     +32 TOTAL                                       +136  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +4.7% +10.5Ki [None]                                                                                +152Ki  +3.0%
      +4.6% +9.56Ki [Unmapped]                                                                            +151Ki  +3.0%
      [NEW]    +216 typeinfo name for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadat    +216  [NEW]
      [NEW]    +136 typeinfo for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, gr    +136  [NEW]
       +16%     +89 [Other]                                                                                  +88   +17%
      [NEW]     +57 typeinfo name for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl         +57  [NEW]
      [NEW]     +56 typeinfo name for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl          +56  [NEW]
      [NEW]     +56 vtable for grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc     +56  [NEW]
      [NEW]     +41 typeinfo name for grpc::(anonymous namespace)::ShutdownCallback                          +41  [NEW]
      [NEW]     +40 vtable for grpc::(anonymous namespace)::ShutdownCallback                                 +40  [NEW]
      [NEW]     +40 vtable for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl                 +40  [NEW]
      [NEW]     +40 vtable for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl                +40  [NEW]
      [NEW]     +34 typeinfo name for grpc_core::CQCallbackInterface                                         +34  [NEW]
      [NEW]     +24 typeinfo for grpc::(anonymous namespace)::ShutdownCallback                               +24  [NEW]
      [NEW]     +24 typeinfo for grpc::internal::(anonymous namespace)::CallbackWithStatusImpl               +24  [NEW]
      [NEW]     +24 typeinfo for grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl              +24  [NEW]
      [NEW]     +16 typeinfo for grpc_core::CQCallbackInterface                                              +16  [NEW]
       +17%      +8 vtable for grpc::ServerContext::CompletionOp                                              +8   +17%
     +10.0%      +8 vtable for grpc::ChannelInterface                                                         +8 +10.0%
       +17%      +8 vtable for grpc::Server::UnimplementedAsyncResponse                                       +8   +17%
      +5.3%      +8 vtable for grpc::Channel                                                                  +8  +5.3%
      +6.1%      +7 [None]                                                                                     0  [ = ]
   +29% +4.07Ki src/cpp/client/generic_stub.cc                                                       +4.07Ki   +29%
      [NEW] +2.14Ki grpc::GenericStub::experimental_type::UnaryCall                                      +2.14Ki  [NEW]
      [NEW] +1.04Ki grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal: +1.04Ki  [NEW]
      [NEW]    +471 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:    +471  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
      [NEW]     +93 std::function<void (grpc::Status)>::function                                             +93  [NEW]
      [NEW]     +83 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:     +83  [NEW]
      [NEW]     +82 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:     +82  [NEW]
      [NEW]     +50 grpc::Status::~Status                                                                    +50  [NEW]
      +2.0%     +29 grpc::GenericStub::Call                                                                  +29  +2.0%
      +5.4%     +28 grpc::GenericStub::PrepareCall                                                           +28  +5.4%
       +61%     +17 [Unmapped]                                                                               +17   +61%
      +1.0%      +8 grpc::GenericStub::PrepareUnaryCall                                                       +8  +1.0%
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvMessage<grpc::ByteBuffer>, grpc:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +5  [NEW]
      +1.6%      +3 grpc::internal::CallOpSet<grpc::internal::CallOpRecvMessage<grpc::ByteBuffer>, grpc:      +3  +1.6%
  [NEW] +2.36Ki src/cpp/common/callback_common.cc                                                    +2.36Ki  [NEW]
      [NEW]    +440 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::Run                      +440  [NEW]
      [NEW]    +419 grpc::internal::CallbackWithStatusTag::CallbackWithStatusTag                            +419  [NEW]
      [NEW]    +344 grpc::internal::CallbackWithSuccessTag::CallbackWithSuccessTag                          +344  [NEW]
      [NEW]    +326 grpc::internal::CallbackWithStatusTag::force_run                                        +326  [NEW]
      [NEW]    +293 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::Run                     +293  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
      [NEW]     +97 [Unmapped]                                                                               +97  [NEW]
      [NEW]     +82 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::~CallbackWithStatusIm     +82  [NEW]
      [NEW]     +82 grpc::internal::(anonymous namespace)::CallbackWithStatusImpl::~CallbackWithStatusIm     +82  [NEW]
      [NEW]     +46 _GLOBAL__sub_I_callback_common.cc                                                        +46  [NEW]
      [NEW]     +42 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::~CallbackWithSuccess     +42  [NEW]
      [NEW]     +42 grpc::internal::(anonymous namespace)::CallbackWithSuccessImpl::~CallbackWithSuccess     +42  [NEW]
      [NEW]     +13 grpc::internal::CallbackWithSuccessTag::force_run                                        +13  [NEW]
   +15%    +691 src/cpp/client/channel_cc.cc                                                            +691   +15%
      [NEW]    +537 grpc::Channel::CallbackCQ                                                               +537  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
       +19%     +64 grpc::Channel::Channel                                                                   +64   +19%
      [NEW]     +28 grpc::(anonymous namespace)::ShutdownCallback::Run                                       +28  [NEW]
       +12%     +24 [Unmapped]                                                                               +24   +12%
      +6.2%     +16 grpc::Channel::~Channel                                                                  +16  +6.2%
      [NEW]      +9 grpc::(anonymous namespace)::ShutdownCallback::~ShutdownCallback                          +9  [NEW]
      +4.3%      +8 grpc::Channel::PerformOpsOnCall                                                           +8  +4.3%
      [NEW]      +3 grpc::ChannelInterface::CallbackCQ                                                        +3  [NEW]
      [NEW]      +2 grpc::(anonymous namespace)::ShutdownCallback::~ShutdownCallback                          +2  [NEW]
  +0.5%     +25 src/cpp/server/server_context.cc                                                         +25  +0.5%
      +7.2%      +9 [Unmapped]                                                                                +9  +7.2%
      +2.0%      +7 grpc::ServerContext::ServerContext                                                        +7  +2.0%
      [NEW]      +5 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +5  [NEW]
      [NEW]      +4 grpc::ServerContext::CompletionOp::cq_tag                                                 +4  [NEW]
  +0.2%     +24 src/cpp/server/health/default_health_check_service.cc                                    +24  +0.2%
      +0.4%     +16 grpc::internal::RpcMethodHandler<grpc::DefaultHealthCheckService::HealthCheckService     +16  +0.4%
      [NEW]      +8 grpc::internal::CallOpSet<grpc::internal::CallOpSendInitialMetadata, grpc::internal:      +8  [NEW]

 -------------- SHRINKING                                                                            --------------
  -0.1%     -24 src/cpp/server/server_cc.cc                                                              -24  -0.1%
      [DEL]     -50 grpc::Status::~Status                                                                    -50  [DEL]
      -1.1%     -31 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>::RunHandler                     -31  -1.1%
      -1.1%     -31 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>::RunHandler                      -31  -1.1%
      -0.3%      -1 [Unmapped]                                                                                -1  -0.3%

  +4.9% +17.6Ki TOTAL                                                                                 +160Ki  +3.1%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,030      Total (>)      1,955,026

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,750      Total (>)     10,843,746

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
This branch didn't cause any new problems once I made some fixes, so I cherry-picked it into #16492

**Pull request closed without merging**
