### PR TITLE
[alts] Fix memory leak in `atls_frame_protector.cc::alts_create_frame_protector()`

### PR DESCRIPTION
**Pull request by yijiem**
Fix https://github.com/grpc/grpc/issues/37727.

A better idea might be to set up Fuzzing for these APIs to find those sort of things. Maybe that can be a next step if we want to further hardening things.

### CODE REVIEW

**Comment by ctiller** [comment]
We want further hardening

**Review by matthewstevenson88 — APPROVED** [review]
Thanks for the fix @yijiem! Agreed with @ctiller that further hardening and better testing/fuzzing of the ALTS stack is needed, but I don't want to block this PR on those improvements.

**Comment by yijiem** [comment]
> Thanks for the fix @yijiem! Agreed with @ctiller that further hardening and better testing/fuzzing of the ALTS stack is needed, but I don't want to block this PR on those improvements.

Thanks Matthew! I took a stab and add a fuzz test for `alts_frame_protector` in https://github.com/grpc/grpc/pull/37763. PTAL. Thanks!

**Comment by matthewstevenson88** [comment]
> > Thanks for the fix @yijiem! Agreed with @ctiller that further hardening and better testing/fuzzing of the ALTS stack is needed, but I don't want to block this PR on those improvements.
> 
> Thanks Matthew! I took a stab and add a fuzz test for `alts_frame_protector` in #37763. PTAL. Thanks!

Thank you!

**Pull request closed without merging**
