### PR TITLE
Don't run xds_end2end_test on iOS

### LINKED ISSUE #20755: grpc/core/master/macos/grpc_bazel_cpp_ios_tests is broken on master
It started failing with this build
https://source.cloud.google.com/results/invocations/fb6a1d5b-aaa0-45b6-a97b-6b15913c853a/log

```
[1,255 / 1,256] Testing //test/cpp/end2end:xds_end2end_test_on_ios; 8s darwin-sandbox
FAIL: //test/cpp/end2end:xds_end2end_test_on_ios (see /Volumes/BuildData/tmpfs/tmp/bazel/a002d9727939acebf422134be2d181ab/execroot/com_github_grpc_grpc/bazel-out/darwin-fastbuild/testlogs/test/cpp/end2end/xds_end2end_test_on_ios/test.log)
INFO: From Testing //test/cpp/end2end:xds_end2end_test_on_ios:
==================== Test output for //test/cpp/end2end:xds_end2end_test_on_ios:
2019-10-16 20:50:52,119 Will consider the test as test type logic_test to run.
2019-10-16 20:50:53,924 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:53,934 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:53,946 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:53,956 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:53,963 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:53,969 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:53,975 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:53,987 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:53,995 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,003 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,009 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,016 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,022 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,031 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,037 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,044 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,050 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,057 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:54,068 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:55,626 Failed to import biplist module. Will use tool /usr/libexec/PlistBuddy to handle the binary format plist.
2019-10-16 20:50:55,633 Creating a new simulator:
Name: New-iPhone Xʀ-12.1
OS: iOS 12.1
Type: iPhone Xʀ
2019-10-16 20:50:56,165 Created new simulator 1A2C0E7E-A5F3-4EE4-8FC9-FB94EA79D1A5.
Test Suite 'All tests' started at 2019-10-16 13:50:59.100
Test Suite 'xds_end2end_test_on_ios.xctest' started at 2019-10-16 13:50:59.101
Test Suite 'GTMGoogleTestRunner' started at 2019-10-16 13:50:59.101
Test Suite 'XdsResolverTest' started at 2019-10-16 13:50:59.101
Test Case '-[GTMGoogleTestRunner XdsResolverTest::XdsResolverIsUsed]' started.
E1016 13:50:59.108517000 4368274304 xds.cc:748]                        assertion failed: error == GRPC_ERROR_NONE
Child process terminated with signal 6: Abort trap
2019-10-16 20:50:59,111 Deleting simulator 1A2C0E7E-A5F3-4EE4-8FC9-FB94EA79D1A5 asynchronously.
2019-10-16 20:50:59,117 Done.
================================================================================
Target //test/cpp/end2end:xds_end2end_test_on_ios up-to-date:
  bazel-bin/test/cpp/end2end/xds_end2end_test_on_ios
  bazel-bin/test/cpp/end2end/xds_end2end_test_on_ios.zip
INFO: Elapsed time: 228.282s, Critical Path: 46.43s
INFO: 1225 processes: 1222 darwin-sandbox, 3 local.
INFO: Build completed, 1 test FAILED, 1256 total actions
//test/cpp/end2end:xds_end2end_test_on_ios                               FAILED in 8.5s
    ERROR   .test/cpp/end2end/xds_end2end_test_on_ios (0.0s)
```

This is right after https://github.com/grpc/grpc/pull/20606 (which I think introduces a test that's not compatible with the grpc_bazel_cpp_ios_tests?)

### PR DESCRIPTION
**Pull request by rmstar**
Fixes #20755

### CODE REVIEW

**Comment by markdroth** [comment]
This PR should not have been necessary.  The problem should have been fixed by #20701.

**Comment by rmstar** [comment]
@markdroth xds_end2end_test_on_ios segfaults with the latest code. We can revert this PR once the test issues have been fixed.

**Comment by markdroth** [comment]
The description of this PR says that it fixes #20755, which should actually be fixed by #20701.  If there's a separate segfault problem, can you please file a separate bug about that?

**Comment by rmstar** [comment]
I think there were multiple issues with xds_end2end_test_on_ios. 

 #20775. Test fails with `Failed to import biplist module`. 
The  'Failed to import biplist module' error seems to have been fixed in the latest code (by #20701 ?)

But now, I see a new failure:
```
Test Case '-[GTMGoogleTestRunner UsesXdsResolver/BasicTest::Vanilla/0]' started.
Child process terminated with signal 11: Segmentation fault
```
I have filed #20788 to track this new failure.

**Pull request merged**
