### PR TITLE
Roll-forward: "Do not interpolate variables in leading comments"

### PR DESCRIPTION
**Pull request by vjpai**
Reverts grpc/grpc#13510
Roll-forward of grpc/grpc#12938

Cc @gkelly

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by vjpai** [comment]
Note that this is a pure roll-forward; the fix was internal-only.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by vjpai** [comment]
Doing a fast merge since this is a pure roll-forward of already-accepted code that didn't break anything in OSS.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
