### PR TITLE
Revert "Merge pull request #15797 from apolcyn/windows_compile_and_sort"

### PR DESCRIPTION
**Pull request by apolcyn**
This reverts commit ae8d3efc3a360b289f0b33e1c53c8c73960cb31f, reversing
changes made to e41215e181564a61320b9b69ae5feb7f7c3625fe.

internal breakage

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++

 -------------- SHRINKING                                                                        --------------
  -0.0%    -269 [None]                                                                           -16.8Ki  -0.2%
  -1.9%     -32 third_party/address_sorting/address_sorting.c                                        -32  -1.9%
      [DEL]     -24 address_sorting_get_source_addr_for_testing                                          -24  [DEL]
      -8.8%      -8 [Unmapped]                                                                            -8  -8.8%
  [DEL]     -19 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_posix.     -19  [DEL]
      [DEL]     -19 grpc_ares_query_ipv6                                                                 -19  [DEL]

  -0.0%    -320 TOTAL                                                                            -16.9Ki  -0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,356      Total (=)      1,976,356

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,770,413      Total (>)     10,770,404

 No significant differences in binary sizes


```

**Comment by apolcyn** [comment]
macos tests: #16156
windows c tests: https://github.com/grpc/grpc/issues/15616
interop ALTS tests: https://github.com/grpc/grpc/issues/15434

**Pull request merged**
