### PR TITLE
don't print multiple imports to protobuf modules

### PR DESCRIPTION
**Pull request by bblancha**
Fixes https://github.com/grpc/grpc/issues/9058

### CODE REVIEW

**Comment by soltanmm-google** [comment]
Jenkins invocation: this is ok to test

Thanks for the PR!

**Comment by soltanmm-google** [comment]
@bblancha You probably need to run `$REPO/tools/distrib/clang_format_code.sh` and commit whatever formatting changes are made by that script to pass some of the sanity tests.

**Comment by nathanielmanistaatgoogle** [comment]
Please squash commits with each round of code review back-and-forth.

**Comment by nathanielmanistaatgoogle** [comment]
I'm satisfied; @soltanmm-google will also review and will approve and merge.

**Comment by bblancha** [comment]
@soltanmm-google Will keep that in mind for future PRs.

Thanks!

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @bblancha isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request merged**
