### PR TITLE
Upgrading to OpenSSL 1.0.2a - https://www.openssl.org/news/secadv_20150319.txt

### PR DESCRIPTION
**Pull request by nicolasnoble**
We'll have to be extra careful when reviewing future pull requests that people aren't reverting that one by accident. It's going to be a common issue.

### CODE REVIEW

**Comment by jboeuf** [comment]
Thanks much for doing this. Will merge as soon as travis is green.

**Comment by jboeuf** [comment]
SHA checked against https://github.com/openssl/openssl/tree/OpenSSL_1_0_2a.

**Comment by nicolasnoble** [comment]
All that shiny green.

**Comment by ctiller** [comment]
Time for a test to avoid accidents?

**Comment by jboeuf** [comment]
Good idea. See #1111.

**Pull request merged**
