### PR TITLE
Refactoring the core security code.

### PR DESCRIPTION
**Pull request by jboeuf**
As opposed to a flat directory, we now have the following structure:

- security
  - context
  - credentials
    - composite
    - fake
    - google_default
    - iam
    - jwt
    - oauth2
    - plugin
    - ssl
  - transport
  - util

We have not refactored the test code yet but this PR is already large
enough...

### CODE REVIEW

**Comment by ctiller** [comment]
Structure looks good.

Looks like it needs:
tools/distrib/check_include_guards.py --fix && tools/distrib/clang_format_code.sh

**Comment by jboeuf** [comment]
Looks like jenkins is green enough except maybe for this issue:
https://github.com/grpc/grpc/issues/6523

**Comment by jboeuf** [comment]
Looks greenish again. PTAL.

**Comment by ctiller** [comment]
LGTM. Flakes look unrelated.

**Pull request merged**
