### PR TITLE
Upgrade third_party/protobuf to v3.13.0

### PR DESCRIPTION
**Pull request by jtattermusch**
protobuf v3.13.0 is already out.
Supersedes https://github.com/grpc/grpc/pull/23841.

### CODE REVIEW

**Comment by jtattermusch** [comment]
I see a bunch of ODR violations:
https://source.cloud.google.com/results/invocations/536680df-1ae5-4def-9159-efc209eaef30/targets/%2F%2Ftest%2Fcore%2Fchannel:channel_trace_test@poller%3Depoll1/log
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/core/channel:channel_trace_test@poller=epoll1
-----------------------------------------------------------------------------
+ export GRPC_POLL_STRATEGY=epoll1
+ shift
+ test/core/channel/channel_trace_test
=================================================================
==17==ERROR: AddressSanitizer: odr-violation (0x7fcea56df400):
  [1] size=32 'google::protobuf::_DoubleValue_default_instance_' bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/wrappers_proto/google/protobuf/wrappers.pb.cc:21:3
  [2] size=32 'google::protobuf::_DoubleValue_default_instance_' external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:21:3
These globals were registered at these points:
  [1]:
    #0 0x44380d in __asan_register_globals /tmp/clang-build/src/compiler-rt/lib/asan/asan_globals.cpp:362:3
    #1 0x7fcea56c601b in asan.module_ctor (/b/f/w/bazel-out/k8-fastbuild/bin/test/core/channel/channel_trace_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/core/channel/../../../_solib_k8/libexternal_Scom_Ugoogle_Uprotobuf_Slibwrappers_Uproto.so+0x2a01b)

  [2]:
    #0 0x44380d in __asan_register_globals /tmp/clang-build/src/compiler-rt/lib/asan/asan_globals.cpp:362:3
    #1 0x7fcea54dfceb in asan.module_ctor (/b/f/w/bazel-out/k8-fastbuild/bin/test/core/channel/channel_trace_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/core/channel/../../../_solib_k8/libexternal_Scom_Ugoogle_Uprotobuf_Slibprotobuf.so+0xa0cceb)

==17==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'google::protobuf::_DoubleValue_default_instance_' at bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/wrappers_proto/google/protobuf/wrappers.pb.cc:21:3
==17==ABORTING
```

and 
https://source.cloud.google.com/results/invocations/4656d0ec-4817-4478-a0e3-2d5eb1049b12/targets/%2F%2Ftest%2Fcpp%2Fgrpclb:grpclb_api_test/log
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/cpp/grpclb:grpclb_api_test
-----------------------------------------------------------------------------
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:644] File already exists in database: google/protobuf/any.proto
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1371] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
external/bazel_tools/tools/test/test-setup.sh: line 310: 88296 Abort trap: 6           "${TEST_PATH}" "$@" 2>&1
```

CC @acozzette

**Comment by jtattermusch** [comment]
Looks like the ODR violation  is due to doubly included well known protos, and that's due to this change in protobuf's BUILD https://github.com/protocolbuffers/protobuf/pull/7065/files

Note: this change was then followed by https://github.com/protocolbuffers/protobuf/pull/7652 (also on the release branch 3.13.x, but not released yet)

CC @rafi-kamal  @acozzette @Yannic   looks like https://github.com/protocolbuffers/protobuf/pull/7065 prevents grpc from upgrading to protobuf 3.13.0

**Comment by jtattermusch** [comment]
I also tested against (unreleased) head of protobuf's 3.13.x  at commit 93d8e89374947aa6c05c290b08efd211c6703087 and the ODR violations are still there (which means the unreleased protocolbuffers/protobuf#7652  is also not helping us)

**Comment by jtattermusch** [comment]
CC @gnossen  as our local bazel guru

**Comment by Yannic** [comment]
I feel like I've seen (and fixed) this before (https://github.com/bazelbuild/bazel/issues/10484). Which version of Bazel are you testing against?

**Comment by jtattermusch** [comment]
> I feel like I've seen (and fixed) this before ([bazelbuild/bazel#10484](https://github.com/bazelbuild/bazel/issues/10484)). Which version of Bazel are you testing against?

We are using bazel 1.0.0 (we do that on purpose to make sure grpc still works with older bazel versions)

**Comment by Yannic** [comment]
The new way of skipping WKPs was broken until ~Bazel 2.2.0. Starting with Bazel 4.0, the old way (that Protobuf was using before protocolbuffers/protobuf#7652) won't be supportet anymore. Can you try against Bazel 2.2, and, assuming that passes all tests, consider dropping support for Bazel 1.x (Bazel 2.2 doesn't contain incompatible changes w.r.t. Bazel 2.0)?

**Comment by jtattermusch** [comment]
Ok, this is where we originally saw the ODR violation problem with well known types:
https://github.com/grpc/grpc/pull/21590#issuecomment-574585757  in that PR, it seems to have been solved by 

https://github.com/protocolbuffers/protobuf/pull/7096
(which doesn't seem to be available on the 3.13.x branch?)

**Comment by Yannic** [comment]
> (which doesn't seem to be available on the 3.13.x branch?)

protocolbuffers/protobuf#7652 is essentially a revert of protocolbuffers/protobuf#7096 to become compatible with the unrelease Bazel 4.0 (https://github.com/bazelbuild/bazel/issues/11694) (and 3.13.x is the first release to include the change).

**Comment by jtattermusch** [comment]
@Yannic  so there is no way how to make this work with bazel 1.x?

**Comment by Yannic** [comment]
> @Yannic so there is no way how to make this work with bazel 1.x?

Unfortunately, no 😞

**Comment by jtattermusch** [comment]
> > @Yannic so there is no way how to make this work with bazel 1.x?
> 
> Unfortunately, no 😞

Can you elaborate that a bit? We'd really like to integrate latest protobuf for our next release (coming soon) but currently this change prevents that. It has worked before so it's hard to believe that that there is no way of making this backward compatible with bazel 1.0 (also bazel 4.0 wasn't released yet so while making things future-proof makes sense in general, I'm not 100% sure it makes sense to proactively break what currently works because of that).

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/23028

**Comment by jtattermusch** [comment]
I upgraded our bazel version to 2.2 in https://github.com/grpc/grpc/pull/23902 so this PR is good to go.

**Pull request merged**
