### PR TITLE
update to use new nuget client in tests

### PR DESCRIPTION
**Pull request by apolcyn**
Attempt to migrate the tests over to the new nuget client, which doesn't support solution package restores anymore.

### CODE REVIEW

**Comment by apolcyn** [comment]
test this please

**Comment by apolcyn** [comment]
The main changes here are to the loading of the nuget dependencies in the tests, when the "tools/run_tests/pre_build_csharp.sh" and "tools/run_tests/pre_build_csharp.bat" are ran. This also gets rid of the solution level dependencies and added them as dependencies of the Grpc.Core.Tests project, since nuget 3.4 no longer supports solution dependencies, and it adds some empty packages.config files just so that nuget 2.8 won't complain about them missing. 

Tested that these scripts work with the latest 3.4.x nuget client on OS X, linux, and windows. The nuget clients on the jenkins workers right now are at 2.8.x, so this should let the nuget packages get restored with the old and new nuget clients.

**Comment by murgatroid99** [comment]
It looks like that project.json file is a generated from a template, so you have to change the template too.

**Comment by murgatroid99** [comment]
LGTM

**Comment by apolcyn** [comment]
Moved this to the v1.0.x branch with this PR: https://github.com/grpc/grpc/pull/7568

**Pull request closed without merging**
