### PR TITLE
gRPC Core API to create Xds channel credentials

### PR DESCRIPTION
**Pull request by yashykt**
Mostly just the type - not fleshed out since security connector would depend on pending tls connector changes.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24312)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
Only minor comments -- otherwise, looks good.

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24312#-:-MIuAP5r1cE59SNLeoev:b-6avchh)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne, @veblush, and @yashykt)

___
*[BUILD, line 1773 at r1](https://reviewable.io/reviews/grpc/grpc/24312#-MIu8fIU4xg-UDiggY--:-MIu8fIU4xg-UDiggY-0:bok2h8d) ([raw file](https://github.com/grpc/grpc/blob/658145c24d7892767b6d76f63ffa894f9afadb7a/BUILD#L1773)):*
> ```Starlark
>         "src/core/lib/security/credentials/tls/grpc_tls_credentials_options.cc",
>         "src/core/lib/security/credentials/tls/tls_credentials.cc",
>         "src/core/lib/security/credentials/xds/xds_credentials.cc",
> ```

We should probably include these in the build only if xDS is included.  Maybe make them their own build target and include the target in the conditional on line 326?
___
*[src/core/lib/security/credentials/xds/xds_credentials.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/24312#-MIu9Q7n1ysF7xBWnY9S:-MIu9Q7n1ysF7xBWnY9T:b7wa9v1) ([raw file](https://github.com/grpc/grpc/blob/658145c24d7892767b6d76f63ffa894f9afadb7a/src/core/lib/security/credentials/xds/xds_credentials.h#L30)):*
> ```objc
> namespace grpc_core {
> 
> class XdsCredentials final : public grpc_channel_credentials {
> ```

Does anything need this definition outside of the .cc file?
___
*[src/core/lib/security/credentials/xds/xds_credentials.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24312#-MIu9TfPBaxbASrWTRTC:-MIu9TfPBaxbASrWTRTD:blg54pf) ([raw file](https://github.com/grpc/grpc/blob/658145c24d7892767b6d76f63ffa894f9afadb7a/src/core/lib/security/credentials/xds/xds_credentials.h#L32)):*
> ```objc
> class XdsCredentials final : public grpc_channel_credentials {
>  public:
>   static constexpr const char kCredentialsTypeXds[] = "Xds";
> ```

I don't think `const` is needed if you're already saying `constexpr`.
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/24312#-MIu9mQ1EmpuJWsveuH5:-MIu9mQ1EmpuJWsveuH6:bv0zj8c) ([raw file](https://github.com/grpc/grpc/blob/658145c24d7892767b6d76f63ffa894f9afadb7a/src/core/lib/security/credentials/xds/xds_credentials.cc#L25)):*
> ```cpp
> namespace grpc_core {
> 
> constexpr const char XdsCredentials::kCredentialsTypeXds[];
> ```

I think the `const` is not needed with `constexpr`.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24312)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne, @markdroth, @veblush, and @yashykt)

___
*[src/core/lib/security/credentials/xds/xds_credentials.h, line 30 at r1](https://reviewable.io/reviews/grpc/grpc/24312#-MIu9Q7n1ysF7xBWnY9S:-MIuDfZrBNSslIQPcRgj:bq64kkq) ([raw file](https://github.com/grpc/grpc/blob/658145c24d7892767b6d76f63ffa894f9afadb7a/src/core/lib/security/credentials/xds/xds_credentials.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Does anything need this definition outside of the .cc file?
</blockquote></details>

I think I just need kCredentialsTypeXds for credentials type checking

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24312)* status: 19 of 22 files reviewed, 4 unresolved discussions (waiting on @donnadionne, @markdroth, and @veblush)

___
*[BUILD, line 1773 at r1](https://reviewable.io/reviews/grpc/grpc/24312#-MIu8fIU4xg-UDiggY--:-MIuEIeF8E0dVn1oYQkW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/658145c24d7892767b6d76f63ffa894f9afadb7a/BUILD#L1773)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should probably include these in the build only if xDS is included.  Maybe make them their own build target and include the target in the conditional on line 326?
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/xds/xds_credentials.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/24312#-MIu9TfPBaxbASrWTRTC:-MIuELJu-9t-9HxeHjAx:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/658145c24d7892767b6d76f63ffa894f9afadb7a/src/core/lib/security/credentials/xds/xds_credentials.h#L32)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think `const` is needed if you're already saying `constexpr`.
</blockquote></details>

removed
___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/24312#-MIu9mQ1EmpuJWsveuH5:-MIuEN60DvcncrwPP7GL:b-hfpv0l) ([raw file](https://github.com/grpc/grpc/blob/658145c24d7892767b6d76f63ffa894f9afadb7a/src/core/lib/security/credentials/xds/xds_credentials.cc#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think the `const` is not needed with `constexpr`.
</blockquote></details>

removed

**Review by markdroth — APPROVED** [review]
Looks great!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24312#-:-MIuFX174ntoBFKCa8qb:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne and @veblush)

**Comment by yashykt** [comment]
@markdroth Looks like VisualStudio does not like 
`static constexpr char[]`.

This seems to be a known bug.

**Review by markdroth — APPROVED** [review]
Weird.  Okay, that's fine.

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24312#-:-MIulfGG8pSYHD4jSj-N:b-5mjmh7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne and @veblush)

**Review by donnadionne — APPROVED** [review]

**Comment by yashykt** [comment]
Artfact build macos - #19898 
Thanks for reviewing!

**Pull request merged**
