### PR TITLE
internal_ci: rename grpc_xds_k8s to psm-security as part of tech-debt cleanup and name clarity (backport 1.40.x)(#28034)

### PR DESCRIPTION
**Pull request by sanjaypujare**

### CODE REVIEW

**Review by sergiitk — APPROVED** [review]

**Comment by sanjaypujare** [comment]
This one is stuck in 
```
Portability Tests Windows [Build Only] (internal CI) Expected — Waiting for status to be reported
```

Any clues? Should I force a rerun?

**Comment by sergiitk** [comment]
Hm, that's strange. I'd say let it finish running everything else, maybe by then `Portability Tests Windows [Build Only]` will start too.

**Comment by sergiitk** [comment]
Oh. This is stuck in in other branches too.

**Pull request merged**
