### PR TITLE
Revert "Change grpc_udp_server interface"

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
Incompatible with Google's internal codebase.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.0%     -48 [None]                                                                                  -496  -0.0%
  -1.0%     -48 src/core/lib/iomgr/udp_server.cc                                                         -48  -1.0%
      [DEL]    -856 grpc_udp_server_add_port                                                                -856  [DEL]
      [DEL]    -415 add_socket_to_server(grpc_udp_server*, int, grpc_resolved_address const*, void (*)(g    -415  [DEL]
     -13.4%     -48 grpc_udp_server_start                                                                    -48 -13.4%

  -0.0%     -96 TOTAL                                                                                   -544  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by nicolasnoble** [comment]
More specifically, the change to the read callback is weird and would require deeper changes, if at all possible. Could you argument on that change which seems outside the scope of the original PR ?

**Comment by nathanielmanistaatgoogle** [comment]
@nicolasnoble: who is "you" in [your request](https://github.com/grpc/grpc/pull/13878#issuecomment-354163172)?

**Comment by nicolasnoble** [comment]
Ah, sorry, I was theoretically speaking to the author of the original PR, @danzh2010 - for some reason I thought you CC them in here for awareness.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by danzh2010** [comment]
Spoke with nathanielmanistaatgoogle off line, the original PR doesn't need import. And please do NOT merge this rollback. It would break next import.

**Comment by nathanielmanistaatgoogle** [comment]
Closing; a change of circumstances has obviated this.

**Pull request closed without merging**
