### PR TITLE
Enabling python artifact building for Windows.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Proof: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/225/architecture=x64,language=python,platform=windows/

**Comment by nicolasnoble** [comment]
Actually, I forgot the DLL part.

**Comment by nicolasnoble** [comment]
DLL should now be getting built. Proof: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/237/architecture=x64,language=python,platform=windows/

**Comment by soltanmm** [comment]
Something is profoundly broken when I install; somehow the *only* thing that ends up installed is the extension (all the Python files are missing). This is really, really weird.

Investigating...

**Comment by nicolasnoble** [comment]
32 bits support added.

**Comment by soltanmm** [comment]
Both installations work; the only gotcha during installation was that `pip` had to be upgraded to understand that the wheel is compatibly named.

**Pull request merged**
