### PR TITLE
Add a dummy reference to prevent unused variable warning if there is …

### PR DESCRIPTION
**Pull request by yang-g**
…no rpc method defined.

### CODE REVIEW

**Comment by vjpai** [comment]
Do we have a test that covers this case?

**Comment by yang-g** [comment]
Currently we do not have unit tests for code generation. See #1225 for discussions.

**Comment by vjpai** [comment]
Oh no, I wasn't asking for a unit test. That's it's own beast (and I also don't like the golden-file testing approach). I was asking if any of our existing protos in open-source actually exhibit this behavior (no rpc method defined). I think the answer is no, and it would be nice to have coverage of that case to make sure that nobody strips out this reference in the future thinking, "Hmm, useless void ref" . I'm fine with an issue filed even if the proto isn't filled in now.

**Comment by vjpai** [comment]
All C++ tests pass, so I declare this PR mergeworthy.

**Pull request merged**
