### PR TITLE
Regenerating project files and massaging VS project files.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Replaces #2709.

### CODE REVIEW

**Comment by larsonmpdx** [comment]
I just rebuilt using this - the base libs built fine, they are all static (/MTd) now which is good for what I'm doing.  had to rebuild libprotobuf as static, that will require a note in the windows readme somewhere.  still sorting out my dependent project to line up.

**Comment by jtattermusch** [comment]
Renaming the configurations would break https://github.com/grpc/grpc/blob/master/vsprojects/nuget_package/buildall.bat (at least)

**Comment by nicolasnoble** [comment]
Alright, changing these too. I can see vsprojects/nuget_package/grpc.native.csharp_ext.nuspec and vsprojects/nuget_package/grpc.native.csharp_ext.targets that references that too.

**Comment by nicolasnoble** [comment]
Ping ?

**Pull request merged**
