### PR TITLE
Release resources more eagerly on ruby server

### PR DESCRIPTION
**Pull request by apolcyn**
Fixes the server socket leak mentioned in https://github.com/grpc/grpc/issues/11015#issuecomment-314308630.

The issue appears to not be a <i>leak</i>, but instead due to relying on the garbage collector to destroy finished server-side `grpc_call`'s.

If we start the example server, run the example against it e.g. 10 times, and then check open fds on the server process with `lsof`, 10 open sockets will stay open for some time (and the server-side-call garbage collection callbacks don't appeared to be called). But if we then run e.g., 1000 RPC's (to try to trigger garbage collection), then GC callbacks can be seen to run and some server-side sockets can get closed.

Tested this change manually (with `lsof`) to see that server-side sockets close immediately after call completion on all rpc types.

PTAL, I think this should be ready now.

### CODE REVIEW

**Comment by rafaelsales** [comment]
@apolcyn not sure if it helps, but I noticed the leak or GC laziness does not happen in 1.0.1 but it happens on the next ruby version (1.1.2).

@apolcyn let me take the opportunity to ask a question: because this issue doesn't happen when you make calls on the same stub, does that mean grpc assume clients are supposed to always reuse client stubs?

**Comment by apolcyn** [comment]
the latest few commits here make the "call context objects" more robust after the underlying call has finished, and add some tests for cases of "use after call finished". (most significant tweaks were needed for handling of `peer` and `peer_cert` attributes of server-side "call contexts") 

These also fix a few misc. things, including a broken `status` accessor on call `operation views`, and missing `peer` and `peer_cert` accessors on client-streaming/bidi RPC types.

PTAL

**Comment by apolcyn** [comment]
fixed broken new copyright, waiting for tests to re-run

jenkins: test this please

**Comment by apolcyn** [comment]
just made one more nit fix in `src/ruby/spec/generic/rpc_server_spec.rb`:

changed 

`fail 'shouldnt reuse service' unless @call.nil?` 

to

`fail 'shouldnt reuse service' unless @server_side_call.nil?`

**Comment by apolcyn** [comment]
tests are green

**Comment by rafaelsales** [comment]
This is great. You guys have an idea on when this would be released? Thanks!

**Comment by apolcyn** [comment]
@rafaelsales, personally I'd guess that this could get in to the 1.5 release in the next few weeks.

**Comment by apolcyn** [comment]
@rafaelsales this change was just released in the 1.4.5 version

**Comment by rafaelsales** [comment]
@apolcyn Thanks for the reminder! Will leave some staging servers running this version over the weekend and likely have it in prod by Monday :)

**Comment by rafaelsales** [comment]
@apolcyn I was running GRPC 1.3.4 for Ruby on a nginx+passenger process and it worked fine. As soon as I upgraded to 1.4.5, I started having this segmentation fault when grpc calls are made from within this nginx/passenger process:

Here's the seg fault that was logged by passenger:
https://gist.github.com/rafaelsales/1cbe03f94910f20b5a2f3f9ae0b9bbb3

Just downgrading back to 1.3.4 fixes the issue.

Since I didn't find any breaking changes on the between 1.3.4, this is the only thing that I changed when upgrading:

```
33422f33a 2017-08-11 23:18:37 -0300 Rafael Sales | grpc 1.4.5
diff --git a/Gemfile b/Gemfile
index 8a06cf1bb..1010d1eba 100644
--- a/Gemfile
+++ b/Gemfile
@@ -70,7 +70,7 @@ 
...
-gem 'grpc', '1.3.4'
+gem 'grpc', '1.4.5'
...
diff --git a/Gemfile.lock b/Gemfile.lock
index 5d7aa124a..bcc88a25b 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -404,7 +404,7 @@ GEM
...
-    grpc (1.3.4)
+    grpc (1.4.5)
...
@@ -789,7 +789,7 @@ DEPENDENCIES
...
-  grpc (= 1.3.4)
+  grpc (= 1.4.5)
...
```

**Comment by apolcyn** [comment]
@rafaelsales are you able tell if this error happens on the GRPC 1.4.1?

It looks like the segfault posted here is happening during client-side "unary/request-response" RPCs (most of the changes between 1.4.5 and 1.4.1 only affect server-side calls,  but the diff between 1.4.1 and 1.3.4 is a lot bigger).

Taking a look, but are you able to share more details about the call (e.g., details about the message sent and received, metadata used, etc.), or possibly code that triggers this?

**Comment by rafaelsales** [comment]
@apolcyn since I don't use nginx/passenger for development, I could only reproduce this on staging/prod servers, but I'll try to setup and reproduce locally so I can test with different grpc versions. Thanks

**Comment by jacobvosmaer** [comment]
When we upgraded to 1.4.5 some of our Ruby client code broke. For some reason, before 1.4.5 we were able to do this on a response stream:

```ruby
first_msg = response.first
# Do stuff with first_msg

response.each do |msg|
  # Do stuff with the rest
end
```

We were able to work around that by rewriting the calling code to use just one loop.

```ruby
first_msg = nil
response.each do |msg|
  if first_msg = nil
    first_msg = msg
    # Do stuff with first message
    next
 end

  # Do stuff with the rest
end
```

Our guess is that it is because of this MR. Sharing here in case it helps someone else. Actual change can be seen in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/13597/diffs.

**Comment by apolcyn** [comment]
@jacobvosmaer indeed the breakage posted here is definitely due to this change.

As a different workaround, `response.next` should work well as a repacement to `response.first`, leaving everything else the same.

The problem appears to be that certain `Enumerable` methods, like `#first`, will cause the generator's wrapping `ensure` block to run even though it has yet finished (with this PR, the `ensure` block expects to run only after enumeration has finished).

I think this can be fixed within ruby-grpc

**Comment by apolcyn** [comment]
On second thought, I'm actually a little reluctant to support the now-broken usage that's posted above.

The problem is that something like `#first` will fully enter and "run the ensure" of the "fiber/generator method" every time it's called.

Also note that using something like `#first` followed by `#next` or `#each` will give different results if used on other types `Enumerables`.

I.e., supporting that behavior makes the grpc "response stream enumerable" inconsistent with something like this:

```
class Trial
  def each
    [1, 2, 3, 4].each do |i|
        yield i
    end
  end
end

def main
  enum = Trial.new.enum_for(:each)
  p enum.first # => 1
  p enum.next # => 1
  enum.each do |r| # => 1, 2, 3, 4
    p r
  end
end


if __FILE__ == $0
  main()
end
```

That said, supporting that can be done if we'd like to - is this important?

**Comment by jacobvosmaer** [comment]
Thanks @apolcyn ! In case this wasn't clear from what I wrote above: I only posted here to help others whose code might have broken in the same way.

I am OK with the new behavior of the response enumerators.

**Pull request merged**
