### PR TITLE
Remove duplicate code for grpc encoding, and extra class.

### PR DESCRIPTION
**Pull request by g-easy**
Originally from #18359 by @bogdandrutu.

This PR replaces class TraceContextEncoding with equivalent encoding/decoding
code that was added into the OpenCensus library. The latter is optimized, tested,
and fuzzed as part of OpenCensus.

### CODE REVIEW

**Comment by g-easy** [comment]
cc @AspirinSJL @yang-g

**Comment by g-easy** [comment]
Could someone please review this? :)

**Comment by g-easy** [comment]
Windows CI is broken due to
```
Unspecified (no such package '@com_github_grpc_grpc//bazel': Could not create symlink to repository "." (absolute path: "T:/src/github/grpc"): Cannot create junction (name=C:\users\builder\_bazel_kbuilder\lndsuir7\external\com_github_grpc_grpc, target=T:\src\github\grpc): ERROR: src/main/native/windows/file-jni.cc(99): nativeCreateJunction(\\?\C:\users\builder\_bazel_kbuilder\lndsuir7\external\com_github_grpc_grpc, \\?\T:\src\github\grpc): ERROR: src/main/native/windows/file.cc(252): CreateFileW(\\?\C:\users\builder\_bazel_kbuilder\lndsuir7\external\com_github_grpc_grpc): Access is denied.
)
```
Which I don't think is affected by my change.

**Comment by jtattermusch** [comment]
@veblush  who is the best person to review?

**Comment by vjpai** [comment]
I can review the C++ components, anyone else can review the BUILD/bzl stuff.

**Comment by vjpai** [comment]
Also, can you run `tools/distrib/clang_format_code.sh` and commit the result?

**Comment by g-easy** [comment]
PR desc: done.
Format: done.

Please have another look. :)

**Comment by g-easy** [comment]
Friendly ping. :)

**Comment by g-easy** [comment]
>GrpcTraceContext is now understood to be redundant with SpanContext, but what (if anything) enabled that?

Work in OpenCensus to add de/serialization code there.

This PR is still current, please take a look.

**Comment by g-easy** [comment]
Friendly ping. :)

**Review by veblush — APPROVED** [review]
LGTM for the build part.

**Comment by g-easy** [comment]
Thanks @veblush. Who can merge this?

**Comment by veblush** [comment]
@g-easy It needs Vijay's approval since he left some review here.

**Comment by jtattermusch** [comment]
@vjpai  PTAL and approve/request more changes.

**Review by vjpai — APPROVED** [review]

**Comment by jtattermusch** [comment]
Merging to finally be done with this PR. ;-)

**Pull request merged**
