### PR TITLE
Change retry default to 'disabled' in objc

### PR DESCRIPTION
**Pull request by muxi**
Change retry default in objc and provide more info in the comments

### CODE REVIEW

**Comment by markdroth** [comment]
Is there a way to have the iOS layer use whatever default core uses instead of defining its own?  It seems wrong to have to maintain this default in two places.

**Comment by muxi** [comment]
Use cases for iOS and other wrappers are different, so I think it makes sense to have iOS's own default.

**Comment by markdroth** [comment]
In what way are they different?

**Comment by muxi** [comment]
Network disruption is much more frequently on iOS devices.

**Comment by markdroth** [comment]
And how does that relate to the assertion that iOS should have its own default here?

**Comment by muxi** [comment]
So that default change of core does not get pushed directly into iOS without prior notice. If the change is ok, making a follow-up iOS default change is acceptable overhead.

**Comment by markdroth** [comment]
If core starts enabling retries by default, how is delaying that change to iOS going to help iOS?

**Pull request closed without merging**
