### PR TITLE
RefCountedPtr: Explicit constructor

### PR DESCRIPTION
**Pull request by yashykt**
Rationale: An implicit construction of RefCountedPtr can cause cause refcounting bugs.

For example -
```
class A : public RefCounted<A> {
public:
  class B {
  public:
    explicit B(RefCountedPtr<A> parent) : parent_(std::move(parent)) {}
  private:
    RefCountedPtr<A> parent_;
  }

  void func() {
    //...
    B b(this); // !! Refcounting bug!!
    //...
  }
}

```

### CODE REVIEW

**Comment by markdroth** [comment]
As an alternative solution, how about using `std::enable_if<>` to allow the implicit constructor to be used only if the passed-in type is a subclass of `T`?

**Comment by yashykt** [comment]
@markdroth No, that would not catch the kind of error shown in the example.

**Comment by yashykt** [comment]
@markdroth That doesn't work for the case described in the example.

**Comment by markdroth** [comment]
Oh, sorry, I didn't read carefully -- I thought the problem was that it was the wrong type, not that you were creating a `RefCountedPtr<>` without actually giving it a new ref.

This seems like a reasonable change, and it appears consistent with how STL types like `std::unique_ptr<>` and `std::shared_ptr<>` work, so let's do it.

Please also make the same change for `WeakRefCountedPtr<>`.

**Review by markdroth — APPROVED** [review]

**Comment by yashykt** [comment]
Issues: #28232, #26886 and the interop failure is being looked at.

**Comment by yashykt** [comment]
Thanks for reviewing!

**Pull request merged**
