### PR TITLE
The language of all upb generated code rules should be "c".

### PR DESCRIPTION
**Pull request by benjaminp**
@nicolasnoble

### CODE REVIEW

**Comment by veblush** [comment]
@benjaminp Thanks for the PR but do you have a specific issue with having C++ language type for upb targets? I know `C` would be the right one but I want to know what's difference there.

**Comment by benjaminp** [comment]
The language affects whether `-std=c99` is passed or not, which may be needed to make older compilers understand all the features the upb `.c` files use.

**Comment by veblush** [comment]
@benjaminp Do you have a concrete case (e.g. compiler version with some warnings or errors because of not having `-std=c99`) as a future reference?

**Comment by benjaminp** [comment]
For instance, GCC 4.x uses c89 as its default standards version.

**Comment by veblush** [comment]
Since we started using proper upb targets instead of generating them in advance, this isn't relevant any more.

**Pull request closed without merging**
