### PR TITLE
Rename GTS to ALTS for TSI plugin

### PR DESCRIPTION
**Pull request by yihuazhang**
Rename GTS to ALTS (Application Layer Transport Security) for the TSI plugin. There are no functional changes in this PR.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++
  [NEW]    +117 src/core/tsi/alts_transport_security.cc    +117  [NEW]
      [NEW]     +69 grpc_tsi_alts_shutdown                      +69  [NEW]
      [NEW]     +32 grpc_tsi_alts_init                          +32  [NEW]
      [NEW]      +8 [Unmapped]                                   +8  [NEW]
      [NEW]      +8 alts_get_shared_resource                     +8  [NEW]
  [ = ]       0 [None]                                      +16  +0.0%
      [NEW]     +64 g_alts_resource                               0  [ = ]
      [ = ]       0 [Unmapped]                                  +16  +0.0%

 -------------- SHRINKING                               --------------
  [DEL]    -117 src/core/tsi/gts_transport_security.cc     -117  [DEL]
      [DEL]     -69 grpc_tsi_gts_shutdown                       -69  [DEL]
      [DEL]     -32 grpc_tsi_gts_init                           -32  [DEL]
      [DEL]      -8 [Unmapped]                                   -8  [DEL]
      [DEL]      -8 gts_get_shared_resource                      -8  [DEL]

  [ = ]       0 TOTAL                                       +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++
  [NEW]    +117 src/core/tsi/alts_transport_security.cc    +117  [NEW]
      [NEW]     +69 grpc_tsi_alts_shutdown                      +69  [NEW]
      [NEW]     +32 grpc_tsi_alts_init                          +32  [NEW]
      [NEW]      +8 [Unmapped]                                   +8  [NEW]
      [NEW]      +8 alts_get_shared_resource                     +8  [NEW]
  [ = ]       0 [None]                                      +16  +0.0%
      [NEW]     +64 g_alts_resource                               0  [ = ]
      [ = ]       0 [Unmapped]                                  +16  +0.0%

 -------------- SHRINKING                               --------------
  [DEL]    -117 src/core/tsi/gts_transport_security.cc     -117  [DEL]
      [DEL]     -69 grpc_tsi_gts_shutdown                       -69  [DEL]
      [DEL]     -32 grpc_tsi_gts_init                           -32  [DEL]
      [DEL]      -8 [Unmapped]                                   -8  [DEL]
      [DEL]      -8 gts_get_shared_resource                      -8  [DEL]

  [ = ]       0 TOTAL                                       +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++
  [NEW]    +117 src/core/tsi/alts_transport_security.cc    +117  [NEW]
      [NEW]     +69 grpc_tsi_alts_shutdown                      +69  [NEW]
      [NEW]     +32 grpc_tsi_alts_init                          +32  [NEW]
      [NEW]      +8 [Unmapped]                                   +8  [NEW]
      [NEW]      +8 alts_get_shared_resource                     +8  [NEW]
  [ = ]       0 [None]                                      +16  +0.0%
      [NEW]     +64 g_alts_resource                               0  [ = ]
      [ = ]       0 [Unmapped]                                  +16  +0.0%

 -------------- SHRINKING                               --------------
  [DEL]    -117 src/core/tsi/gts_transport_security.cc     -117  [DEL]
      [DEL]     -69 grpc_tsi_gts_shutdown                       -69  [DEL]
      [DEL]     -32 grpc_tsi_gts_init                           -32  [DEL]
      [DEL]      -8 [Unmapped]                                   -8  [DEL]
      [DEL]      -8 gts_get_shared_resource                      -8  [DEL]

  [ = ]       0 TOTAL                                       +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_unary_ping_pong.BM_UnaryPingPong_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__0_16777216.counters.old: 1


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yihuazhang** [comment]
Hi Mark, 

Is there anything else I need to do to get the PR merged to upstream? 

Best, 
Yihua

**Comment by markdroth** [comment]
Sorry for the delay on this; I've been swamped lately.

Please merge with master and squash your commits, and I'll take a look at the tests and try to get this merged.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++
  [NEW]    +117 src/core/tsi/alts_transport_security.cc    +117  [NEW]
      [NEW]     +69 grpc_tsi_alts_shutdown                      +69  [NEW]
      [NEW]     +32 grpc_tsi_alts_init                          +32  [NEW]
      [NEW]      +8 [Unmapped]                                   +8  [NEW]
      [NEW]      +8 alts_get_shared_resource                     +8  [NEW]
  [ = ]       0 [None]                                      +16  +0.0%
      [NEW]     +64 g_alts_resource                               0  [ = ]
      [ = ]       0 [Unmapped]                                  +16  +0.0%

 -------------- SHRINKING                               --------------
  [DEL]    -117 src/core/tsi/gts_transport_security.cc     -117  [DEL]
      [DEL]     -69 grpc_tsi_gts_shutdown                       -69  [DEL]
      [DEL]     -32 grpc_tsi_gts_init                           -32  [DEL]
      [DEL]      -8 [Unmapped]                                   -8  [DEL]
      [DEL]      -8 gts_get_shared_resource                      -8  [DEL]

  [ = ]       0 TOTAL                                       +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known failures: #13149 #13429

**Pull request merged**
