### PR TITLE
Enable C++ in ALTS interop tests

### PR DESCRIPTION
**Pull request by yihuazhang**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                              FILE SIZE
 ++++++++++++++ GROWING                                                ++++++++++++++
  +0.0%      +8 [None]                                                    +184  +0.0%
  +2.8%    +112 src/core/lib/security/transport/security_handshaker.cc    +112  +2.8%
       +26%    +114 on_handshake_next_done_locked                             +114   +26%

  +0.0%    +120 TOTAL                                                     +296  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                              FILE SIZE
 ++++++++++++++ GROWING                                                ++++++++++++++
  +0.0%     +24 [None]                                                    +208  +0.0%
  +2.4%     +96 src/core/lib/security/transport/security_handshaker.cc     +96  +2.4%
       +22%     +98 on_handshake_next_done_locked                              +98   +22%

  +0.0%    +120 TOTAL                                                     +304  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by yihuazhang** [comment]
Will merge now. PR passed all internal tests.

**Comment by adelez** [comment]
This merge breaks our bazel build: https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fremote_bazel_tests_dbg

**Pull request merged**
