### PR TITLE
Update interop test service url to grpc-test.sandbox.googleapis.com.

### PR DESCRIPTION
**Pull request by adelez**
FYI to @jtattermusch, @ctiller, @nicolasnoble

### CODE REVIEW

**Comment by yang-g** [comment]
LGTM

**Comment by yang-g** [comment]
I will wait a bit for the test before merging.

**Comment by adelez** [comment]
The test won't work until the update on GFE configs go live. I'll try locally when it does and post the result here. For now, please check if I miss anything.

**Comment by yang-g** [comment]
I think all the occurrences I can find are fixed.

**Comment by jtattermusch** [comment]
Please be careful with running interop tests suite on this pull request. As the  grpc-test.sandbox.googleapis.com service is not working yet, the test run can take extremely long time because of retrying all the cloud to prod tests several time (and sometimes timing out). Such long test run can prevent interop tests runs for other pull requests from being processed.

**Comment by yang-g** [comment]
I am planning to merge this now. Any objections?

**Comment by jtattermusch** [comment]
Just verified that grpc-test.sandbox.googleapis.com works.

**Pull request merged**
