### PR TITLE
Fix windows RBE results uploading to bigquery

### PR DESCRIPTION
**Pull request by jtattermusch**
b/210820484

### CODE REVIEW

**Comment by jtattermusch** [comment]
Adhoc run of the master RBE job: http://sponge/a932ecb1-bddf-45ce-a782-3e4ca8d8ad2e

**Comment by jtattermusch** [comment]
Still needs work:
```
timeout.exe /t 60 /nobreak  


  


 python ./tools/run_tests/python_utils/upload_rbe_results.py 


) 


timeout: invalid time interval '/t'

Try 'timeout --help' for more information.

Traceback (most recent call last):


  File "./tools/run_tests/python_utils/upload_rbe_results.py", line 22, in <module>


    import urllib.error


ImportError: No module named error
```

**Comment by jtattermusch** [comment]
Another adhoc run: http://sponge/d0f46198-6939-4d4c-85a8-bbbf347400c9

**Comment by jtattermusch** [comment]
http://sponge/42e537b7-4263-4598-b937-5cbf614adbe3

**Comment by jtattermusch** [comment]
http://sponge/70e1b3fd-812b-480b-9e8f-bea7bebc9392

**Comment by jtattermusch** [comment]
@gnossen  With the last attempt, it looks like the RBE result uploading works again. This is ready for review and merging.

http://sponge/70e1b3fd-812b-480b-9e8f-bea7bebc9392

**Review by gnossen — APPROVED** [review]

**Comment by jtattermusch** [comment]
Known failures: b/209603283

**Pull request merged**
