### PR TITLE
Remove pip install six where it should not be necessary

### PR DESCRIPTION
**Pull request by jtattermusch**
Followup for https://github.com/grpc/grpc/pull/5167.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Distributions tests are still passing.
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/65/architecture=x64,language=python,platform=linux/console
Fedora21 problem is unrelated.

**Comment by jtattermusch** [comment]
Actually, no. It's breaking the distrib tests:

`pkg_resources.VersionConflict: (six 1.9.0 (/usr/lib/python2.7/site-packages), Requirement.parse('six>=1.10'))`

https://grpc-testing.appspot.com/job/gRPC_distribtest/66/architecture=x64,language=python,platform=linux/console

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_distribtest/66/architecture=x64,language=python,platform=linux/console

**Comment by jtattermusch** [comment]
for some reason, if you don't manually do `pip install --upgrade six` before installing, the distribtests fail (despite six>=1.10 being mentioned in requirements.txt).

**Comment by jtattermusch** [comment]
friendly ping, any opinions on this?

**Comment by soltanmm** [comment]
Maybe `six` is already installed and without the `--upgrade` flag the python distribution gets confused because it's owned by the system (although then that'd mean `--ignore-installed` would be required? except I'm not sure if that's required or not for certain versions of `pip`?)?

My basic diagnosis is that `six` is not owned by `pip`, so `pip` can't upgrade it. I just don't understand why it was then working with the `--upgrade` flag as opposed to the `--ignore-installed` flag.

**Pull request closed without merging**
