### PR TITLE
Add option to priority policy to ignore reresolution requests from a given child.

### PR DESCRIPTION
**Pull request by donnadionne**
Add option to priority policy to ignore reresolution requests from a given child.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24674)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks good overall!  I have just one noteworthy comment, which is about retaining the value when the child is removed from the config.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24674#-:-MLOgjdOBznNXOcIPwg4:b-5gq1dl)* status: all files reviewed, 3 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/24674#-MLOdLgK8bcbLhX-jBax:-MLOdLgK8bcbLhX-jBay:b-4p5cjv) ([raw file](https://github.com/grpc/grpc/blob/0a1e25f3d3d951f38fa86890611b265bcc1646d5/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L56)):*
> ```cpp
> constexpr int kDefaultChildFailoverTimeoutMs = 10000;
> 
> struct PriorityLbChild {
> ```

This can be inside of `PriorityLbConfig`.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 737 at r1](https://reviewable.io/reviews/grpc/grpc/24674#-MLOeXrj8OmKKgV0mgoE:-MLOeXrj8OmKKgV0mgoF:b-9xwz2k) ([raw file](https://github.com/grpc/grpc/blob/0a1e25f3d3d951f38fa86890611b265bcc1646d5/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L737)):*
> ```cpp
>   auto child_config =
>       priority_->priority_policy_->config_->children().find(priority_->name());
>   if (child_config != priority_->priority_policy_->config_->children().end() &&
> ```

When a child is removed from the config, it is deactivated, but it won't actually be removed for another 15 minutes.  However, if it was configured to ignore re-resolution requests, then it should continue to ignore re-resolution requests even after it's removed from the config.

In order to do this, I think you'll need to store the `ignore_reresolution_requests` value from the config in the `ChildPriority` object, so that it can still be accessed even after the child is removed from the config.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 846 at r1](https://reviewable.io/reviews/grpc/grpc/24674#-MLOgTT0-ngNCOwJEH3A:-MLOgTT0-ngNCOwJEH3B:b-hs6kkm) ([raw file](https://github.com/grpc/grpc/blob/0a1e25f3d3d951f38fa86890611b265bcc1646d5/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L846)):*
> ```cpp
>                       &parse_error, 1));
>               GRPC_ERROR_UNREF(parse_error);
>             } else if (error_list.empty()) {
> ```

The `else` isn't necessary, because whatever values we return here won't actually be used if the error list is non-empty.

**Review by donnadionne — COMMENTED** [review]
PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24674#-:-MLks_WL5tL57ak7mnwB:bxtaph9)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/24674#-MLOdLgK8bcbLhX-jBax:-MLksWNDDiLGTCfIDAxw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0a1e25f3d3d951f38fa86890611b265bcc1646d5/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be inside of `PriorityLbConfig`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 737 at r1](https://reviewable.io/reviews/grpc/grpc/24674#-MLOeXrj8OmKKgV0mgoE:-MLksXlSE1hsZEL3dvan:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0a1e25f3d3d951f38fa86890611b265bcc1646d5/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L737)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

When a child is removed from the config, it is deactivated, but it won't actually be removed for another 15 minutes.  However, if it was configured to ignore re-resolution requests, then it should continue to ignore re-resolution requests even after it's removed from the config.

In order to do this, I think you'll need to store the `ignore_reresolution_requests` value from the config in the `ChildPriority` object, so that it can still be accessed even after the child is removed from the config.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 846 at r1](https://reviewable.io/reviews/grpc/grpc/24674#-MLOgTT0-ngNCOwJEH3A:-MLksYIX4sEBf2Ru5Umk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0a1e25f3d3d951f38fa86890611b265bcc1646d5/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L846)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The `else` isn't necessary, because whatever values we return here won't actually be used if the error list is non-empty.
</blockquote></details>

Done.

**Review by markdroth — CHANGES_REQUESTED** [review]
This is looking pretty good!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24674#-:-MLn5xUsDtgDOZtcm7tG:b-lm5h1l)* status: all files reviewed, 5 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 96 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn3csL7cT7On-eWK5K:-MLn3csL7cT7On-eWK5L:bal6bhe) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L96)):*
> ```cpp
>    public:
>     ChildPriority(RefCountedPtr<PriorityLb> priority_policy, std::string name,
>                   bool ignore_reresolution_requests);
> ```

I think we need to add this parameter to `UpdateLocked()` instead of adding it to the ctor, because we will need to update it whenever we get an update from our parent.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn3lIv4QUBOXxsEPWT:-MLn3lIv4QUBOXxsEPWU:bd9tfei) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L103)):*
> ```cpp
> 
>     const std::string& name() const { return name_; }
>     const bool ignore_reresolution_requests() const {
> ```

I don't think this accessor method is necessary, because the only place it's used is inside the helper, which is already nested inside of `ChildPriority`, so it can directly access the data member.

Also, for a method that returns by value, there's no point in having the return value be `const`.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 320 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn4iJO2K6L_8H2Qu1U:-MLn4iJO2K6L_8H2Qu1V:b-y23acc) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L320)):*
> ```cpp
>     } else {
>       // Existing child found in new config.  Update it.
>       child->UpdateLocked(config_it->second.config);
> ```

Here we also need to pass in `config_it->second.ignore_reresolution_requests`, in case the value changed since the last update.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 421 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn3ISp8OYyxYiiNjk5:-MLn3ISp8OYyxYiiNjk6:b-cdnk1z) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L421)):*
> ```cpp
>     // If the child for the priority does not exist yet, create it.
>     const std::string& child_name = config_->priorities()[priority];
>     auto child_config = config_->children().find(child_name);
> ```

These two lines can move down to line 437, so that we're not actually doing this lookup unless we need to create the child.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 746 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn5PXx4Bq2wlFhnF3_:-MLn5PXx4Bq2wlFhnF3a:b-kof9g8) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L746)):*
> ```cpp
> void PriorityLb::ChildPriority::Helper::RequestReresolution() {
>   if (priority_->priority_policy_->shutting_down_) return;
>   auto child = priority_->priority_policy_->children_.find(priority_->name());
> ```

There's no need to do this lookup.  We already have a pointer to the child object in `priority_`, so we can just use `priority_->ignore_reresolution_requests_` here.

**Review by donnadionne — COMMENTED** [review]
PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24674#-:-MLnWkxaBE0OcJGB74VZ:bxtaph9)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 96 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn3csL7cT7On-eWK5K:-MLnWr875axjZT2bMit4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L96)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we need to add this parameter to `UpdateLocked()` instead of adding it to the ctor, because we will need to update it whenever we get an update from our parent.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 103 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn3lIv4QUBOXxsEPWT:-MLnWrlA9D4FkyTJGM92:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L103)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this accessor method is necessary, because the only place it's used is inside the helper, which is already nested inside of `ChildPriority`, so it can directly access the data member.

Also, for a method that returns by value, there's no point in having the return value be `const`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 320 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn4iJO2K6L_8H2Qu1U:-MLnWt681kf8CWyBOh_4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L320)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Here we also need to pass in `config_it->second.ignore_reresolution_requests`, in case the value changed since the last update.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 421 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn3ISp8OYyxYiiNjk5:-MLnWuHu3CFbWHPj-ChE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L421)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two lines can move down to line 437, so that we're not actually doing this lookup unless we need to create the child.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/priority/priority.cc, line 746 at r2](https://reviewable.io/reviews/grpc/grpc/24674#-MLn5PXx4Bq2wlFhnF3_:-MLnWvmz6IN2mWyyDg53:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d0b127539c47e06f0fa7334f629272ae87718cf4/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc#L746)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

There's no need to do this lookup.  We already have a pointer to the child object in `priority_`, so we can just use `priority_->ignore_reresolution_requests_` here.
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
This looks great!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24674#-:-MLnYoWE-Ras0yWtuQcY:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
