### PR TITLE
Backport "Make legacy artifact -> packages -> distribtest jobs a noop" to v1.49.x

### PR DESCRIPTION
**Pull request by apolcyn**
Attempt to build packages successfully on v1.49.x

Currently, the macos artifact build job is failing to install dependencies.

### CODE REVIEW

**Review by gnossen — APPROVED** [review]

**Comment by jtattermusch** [comment]
@apolcyn  I suspect this might not be what you want. If you provided the link to the failed build, I'd know more.

If you're actually trying to build the artifacts / packages on 1.49.x (rather than just trying to silence an error), this PR is likely not going to help you.  I suspect the macos artifact build might be failing because of the recent MacOS monterey migration?

You might want to backport e.g. this instead: https://github.com/grpc/grpc/pull/31125

**Comment by apolcyn** [comment]
@jtattermusch there were Ruby and Python setup failures in the macos artifact build job.

The ruby failure was here: https://fusion2.corp.google.com/invocations/e4fd00c9-d2ae-40e1-915a-36150d86eb44/targets/grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_build_artifacts/log. This PR would stop trying to use macos entirely, for the ruby artifact build.

I can't find the link to the Python failure, but it was happening on [this command](https://github.com/grpc/grpc/blob/07411bcfd30e0f5dba3d9e609b73af8d60328d86/tools/internal_ci/macos/grpc_build_artifacts.sh#L32), I believe because it couldn't find `python2.7`. This PR would stop using that script entirely.

**Comment by jtattermusch** [comment]
From your log:
```
++ rvm get stable
Archives path '/Users/kbuilder/.rvm/archives' not writable, aborting.
``` 
would be addressed by https://github.com/grpc/grpc/pull/31125.

**Comment by jtattermusch** [comment]
I created https://github.com/grpc/grpc/pull/31697.

The python issue would IMHO be addressed by backporting https://github.com/grpc/grpc/pull/31126/.

A PHP fix is here: https://github.com/grpc/grpc/pull/31567 (also backport if that's what you need).

**Comment by jtattermusch** [comment]
Looks like this was superseded. I'm going to close, feel free to reopen if still needed.

**Pull request closed without merging**
