### PR TITLE
Ruby 2.4.0 support.

### PR DESCRIPTION
**Pull request by nicolasnoble**
This is a port of #9291 and effectively replaces it.

### CODE REVIEW

**Comment by dazuma** [comment]
@nicolasnoble @apolcyn Is this going to get into master as well?

**Comment by apolcyn** [comment]
I think this will go into master on an upmerge.

Is this needed on master now? The changes here were used to add 2.4 support to the released 1.1.2 gem (built from the 1.1.1 branch here).

**Comment by dazuma** [comment]
No, it's not immediately needed. I was curious because #9291 was set up as a master merge.

**Comment by nicolasnoble** [comment]
As a matter of fact, #9694 is taking care of the upmerge from the release branch.

**Pull request merged**
