### PR TITLE
Compression Cookbook

### PR DESCRIPTION
**Pull request by dgquintas**
@nathanielmanistaatgoogle as requested in your comments :)

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
[Rendered](https://github.com/dgquintas/grpc/blob/276c72e259c6f9eeee4586c02051e08b7f71b0fd/doc/compression_cookbook.md).

Luhguhtum.

**Comment by kpayson64** [comment]
test this please

**Comment by nicolasnoble** [comment]
*sigh* why...

**Comment by nicolasnoble** [comment]
(Jenkins that is)

**Comment by nicolasnoble** [comment]
test this please

**Comment by dgquintas** [comment]
these requests need more swearing and cussing, that's why.

**Comment by ctiller** [comment]
We have a variety of languages in which to curse.

Let's try all of them.

**Comment by nicolasnoble** [comment]
Projects files need regeneration, apparently, according to Jenkins.

**Comment by kpayson64** [comment]
@nicolasnoble 
The php templates needed updating, I fixed that here #7312

**Pull request merged**
