### PR TITLE
Fix markdown

### PR DESCRIPTION
**Pull request by kerneltime**
Github is not formatting the markdown correctly. Fix the markdown to comply with GitHub's renderer.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Same as https://github.com/grpc/grpc/pull/10264.

**Comment by jtattermusch** [comment]
Actually #10264 seems to be subset of this PR.

**Comment by jtattermusch** [comment]
test this please

**Comment by kerneltime** [comment]
@jtattermusch tests seem flaky unless markdown is being validated..

**Pull request merged**
