### PR TITLE
Enable bitcode for ios native libraries

### LINKED ISSUE #16839: Unity C#: Xcode reports libgrpc_csharp_ext.a does not contain bitcode
### What version of gRPC and what language are you using?
I am using the experimental plugin for Unity  in C#. I followed the instruction [here](https://github.com/grpc/grpc/tree/master/src/csharp/experimental)

After exporting my Unity project to Xcode and compiling the exported project I am getting this error:

`
/../Libraries/Plugins/Grpc.Core/runtimes/ios/libgrpc_csharp_ext.a(grpc_csharp_ext.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
`
 
I am using Xcode 10, and deployment target: 11.2

### PR DESCRIPTION
**Pull request by koshelevpavel**
Fixes #16839 

@jtattermusch

### CODE REVIEW

**Comment by jtattermusch** [comment]
Thanks for the contribution! I'll get that tested.

**Comment by jtattermusch** [comment]
Started an adhoc run of package build: https://sponge.corp.google.com/invocation?id=bdb704c2-0123-4793-ad21-c3edf9169836&searchFor=

**Comment by jtattermusch** [comment]
The adhoc build of unity package with grpc_csharp_ext bitcode embedded is here: https://storage.googleapis.com/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/windows/grpc_build_packages/8035/20190829-061342/github/grpc/artifacts/grpc_unity_package.2.24.0-dev.zip

@koshelevpavel  can you test if that works for you?

**Comment by koshelevpavel** [comment]
> The adhoc build of unity package with grpc_csharp_ext bitcode embedded is here: https://storage.googleapis.com/grpc-testing-kokoro-prod/test_result_public/prod/grpc/core/master/windows/grpc_build_packages/8035/20190829-061342/github/grpc/artifacts/grpc_unity_package.2.24.0-dev.zip
> 
> @koshelevpavel can you test if that works for you?

Yes! It works for me. Thank you so much.

**Pull request merged**
