### PR TITLE
xDS changes for server listener resource name template

### PR DESCRIPTION
**Pull request by yashykt**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24965)

### CODE REVIEW

**Comment by yashykt** [comment]
@markdroth This PR has been updated with the changes to `server_listener_resource_name_template` as per the most recent discussions. Please take a look :)

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks really good!  All comments are minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24965#-:-MVOPZrVAnNKoXiiviz5:b-u4euqn)* status: all files reviewed, 7 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 1915 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOM_0-Ep5Q_mAd6RVD:-MVOM_0-Ep5Q_mAd6RVE:b-12edfd) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_api.cc#L1915)):*
> ```cpp
>     return GRPC_ERROR_CREATE_FROM_STATIC_STRING("Invalid port");
>   }
>   *address = absl::StrFormat(
> ```

Suggest using `JoinHostPort()` here.
___
*[src/core/ext/xds/xds_api.cc, line 1926 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOMzQG4uNET1cd4ymq:-MVOMzQHEiJ5OTo8FxDe:b90oeui) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_api.cc#L1926)):*
> ```cpp
>     const EncodingContext& context,
>     const envoy_config_listener_v3_Listener* listener,
>     const envoy_config_core_v3_Address* address,
> ```

It seems confusing to pass this in as a parameter, because someone might think that they can pass in a different address than the one in the listener proto.  It's probably better to just extract the address field again inside of this function.
___
*[src/core/ext/xds/xds_api.cc, line 1930 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOMv1t3dKwHCrMlUdV:-MVOMv1t3dKwHCrMlUdW:bedayr3) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_api.cc#L1930)):*
> ```cpp
>   lds_update->type = XdsApi::LdsUpdate::ListenerType::kTcpListener;
>   grpc_error* error = GRPC_ERROR_NONE;
>   error = AddressParse(address, &lds_update->address);
> ```

This can be combined with the previous line.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 124 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVONDl6E8wnSXs6UipJ:-MVONDl737VCumz0W02Q:b45f6mi) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_bootstrap.cc#L124)):*
> ```cpp
>   if (!bootstrap.server_listener_resource_name_template().empty()) {
>     parts.push_back(
>         absl::StrFormat("server_listener_resource_name_template_=\"%s\",\n",
> ```

We shouldn't have a trailing underscore here.
___
*[src/core/ext/xds/xds_client.h, line 91 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOOX3T2tpioIM-c6Oy:-MVONafO-_BSo3DtLT7g:bwiytsb) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_client.h#L91)):*
> ```objc
>   ~XdsClient() override;
> 
>   const XdsBootstrap* bootstrap() const { return bootstrap_.get(); }
> ```

Can this ever return null?  If not, maybe make it a reference instead of a pointer.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOO5bVEBVDnYXcBo2r:-MVOO5bVEBVDnYXcBo2s:b1tc224) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_server_config_fetcher.cc#L112)):*
> ```cpp
>       }
>       if (listener.address != listening_address_) {
>         OnFatalError(absl::Status(
> ```

Can just use `absl::FailedPreconditionError(...)` here.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 191 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOOE1L9PL_jx3gNtCO:-MVOOE1L9PL_jx3gNtCP:b409a9t) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_server_config_fetcher.cc#L191)):*
> ```cpp
> 
>     void OnResourceDoesNotExist() override {
>       OnFatalError(absl::Status(absl::StatusCode::kNotFound,
> ```

`absl::NotFoundError(...)`

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24965)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 1915 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOM_0-Ep5Q_mAd6RVD:-MVSj-Px4s7QgqM1DStR:ba0h43s) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_api.cc#L1915)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest using `JoinHostPort()` here.
</blockquote></details>

Oh right, this would be a bug otherwise. IPv6 needed to be surrounded by `[]`.  (Luckily, we've got an ipV6 only test infra to catch stuff like this)
___
*[src/core/ext/xds/xds_api.cc, line 1926 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOMzQG4uNET1cd4ymq:-MVSjOWXCOG868cg_6ST:b-8ztyin) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_api.cc#L1926)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It seems confusing to pass this in as a parameter, because someone might think that they can pass in a different address than the one in the listener proto.  It's probably better to just extract the address field again inside of this function.
</blockquote></details>

Done. Such stuff always confuses me as to what to prefer.
___
*[src/core/ext/xds/xds_api.cc, line 1930 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOMv1t3dKwHCrMlUdV:-MVSj_IF07m09sTOQajN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_api.cc#L1930)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be combined with the previous line.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_bootstrap.cc, line 124 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVONDl6E8wnSXs6UipJ:-MVSjdOoAhLSzQdllFr7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_bootstrap.cc#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We shouldn't have a trailing underscore here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.h, line 91 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOOX3T2tpioIM-c6Oy:-MVShZW21eZGNjAbSOQB:b-8t0bac) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_client.h#L91)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can this ever return null?  If not, maybe make it a reference instead of a pointer.
</blockquote></details>

it can if there's an issue with the bootstrap parsing
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 112 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOO5bVEBVDnYXcBo2r:-MVSjgjQ-0XrkE0YQwvK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_server_config_fetcher.cc#L112)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can just use `absl::FailedPreconditionError(...)` here.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_server_config_fetcher.cc, line 191 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOOE1L9PL_jx3gNtCO:-MVSjh8ECdH0fxOxuNMs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_server_config_fetcher.cc#L191)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`absl::NotFoundError(...)`
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
Just one remaning nit.  I'll approve so that you can merge after addressing.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24965#-:-MVTUb2W9oLVlMniP5jN:b-cepmj3)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/ext/xds/xds_client.h, line 91 at r1](https://reviewable.io/reviews/grpc/grpc/24965#-MVOOX3T2tpioIM-c6Oy:-MVTTxiT6pso6HJ4ezK5:b-aupbx7) ([raw file](https://github.com/grpc/grpc/blob/2138f2d02b1f7402317e2f034d0123044f027068/src/core/ext/xds/xds_client.h#L91)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

it can if there's an issue with the bootstrap parsing
</blockquote></details>

Sure, but in that case, `XdsClient` creation fails, so the object can't actually be used for anything anyway.  So I think we can safely change this to a reference.

If you want to be extra safe here, you can also change `XdsClient::GetOrCreate()` to return null if `*error != GRPC_ERROR_NONE` after instantiating the `XdsClient`.

**Pull request merged**
