### PR TITLE
Enforce shellcheck on scripts under /test/

### PR DESCRIPTION
**Pull request by mehrdada**
Progress on #11601

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
LGTM so far, but can we do an artifact build to sanity check that there are no new failing distrib tests?

**Comment by mehrdada** [comment]
@apolcyn I think distribtests are run automatically here, aren't they? I see them passed in the list on this page.

**Comment by apolcyn** [comment]
cc @matt-kwong for reference but I believe the distrib tests ran per-PR are a smaller subset of all of the distrib tests (I believe these ones focus on c++).

**Comment by matt-kwong** [comment]
@apolcyn is right. I triggered a build here: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/1851/

**Comment by apolcyn** [comment]
unfortunately it looks like the [artifact build on jenkins for python is failing right now, on master](https://grpc-testing.appspot.com/job/gRPC_build_artifacts/1874/#showFailuresLink), which looks to be blocking the distrib tests FYI

**Comment by mehrdada** [comment]
Yes. I don't think that's caused by anything in this PR. This is actually a fairly trivial change compared to the previous shellcheck PRs.

**Comment by apolcyn** [comment]
yes, it looks like most of the distrib tests, whose previous builds were ok, passed anyways: https://grpc-testing.appspot.com/job/gRPC_distribtest/1860/#showFailuresLink

**Pull request merged**
