### PR TITLE
Attempt to fix #11011.

### LINKED ISSUE #11011: TSI_INTERNAL_ERROR after upgrade to grpc 1.3.0
After upgrade to server python to grpcio 1.3.0 (and after regenerating proto files)
I have this:
`
E0505 20:13:50.851834103   32645 ssl_transport_security.c:429] SSL_read returned 0 unexpectedly.
`
`
E0505 20:13:50.851868188   32645 secure_endpoint.c:185]      Decryption error: TSI_INTERNAL_ERROR
`

and often

`
E0505 20:13:33.406171300   32645 chttp2_server.c:83]         Handshaking failed: {"created":"@1494015213.406134120","description":"Handshake read failed","file":"src/core/lib/security/transport/security_handshaker.c","file_line":239,"referenced_errors":[{"created":"@1494015213.406130326","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":456,"referenced_errors":[{"created":"@1494015213.406108664","description":"Handshake timed out","file":"src/core/lib/channel/handshaker.c","file_line":241}]}]}
`

The client code is Java (1.2.0 or 1.3.0). The certificate is generate by letsencrypt.

### PR DESCRIPTION
**Pull request by jboeuf**
The new code complies with the documentation:
https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#SSL_read

At the very least, that should give us better debugging info of the problem.

### CODE REVIEW

**Comment by jboeuf** [comment]
@nicolasnoble ping?

**Comment by jboeuf** [comment]
ping? ping?

**Comment by nicolasnoble** [comment]
Looks like code formatting isn't happy.

**Comment by jboeuf** [comment]
Thanks for having a look. It should be now.

**Comment by jboeuf** [comment]
@matt-kwong are you the one merging approved PRs or do you want me to do it? Thanks!

**Comment by matt-kwong** [comment]
You're free to merge pull requests as soon as they're approved and you check if failing tests are unrelated to your change.

**Comment by jboeuf** [comment]
Thanks Matt!

**Pull request merged**
