### PR TITLE
Python: update the version of six and delete repeated six string

### PR DESCRIPTION
**Pull request by thinkerou**
The same as #7404, but this commit for v1.0.x branch.

### CODE REVIEW

**Comment by kpayson64** [comment]
What is the motivation for this?

We recently lowered the six dependency (#7130) because some Ubuntu distributions come with six=1.5.2, and consider six to be a "owned by OS" so it can't be upgraded.  This prevents grpcio from being installed on such systems because the six=1.10.0 dependency can't be met:

```
Downloading/unpacking six from https://pypi.python.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl#md5=3ab558cf5d4f7a72611d59a81a315dc8
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed six
Cleaning up...
```

**Comment by soltanmm** [comment]
I'm in favor of not doing the version upgrade, but killing the extra `six` sounds good.

**Comment by kpayson64** [comment]
The extra six was a hack to get the Sphinx dependencies satisfied.  If I remember correctly, only removing the six in setup_requires will cause setup.py to fail.

**Comment by thinkerou** [comment]
Ohh, my fault, you arch right @kpayson64 , I will close the commit.

**Pull request closed without merging**
