### PR TITLE
Avoid identifiers reserved by Ruby

### PR DESCRIPTION
**Pull request by yugui**
> "prefix `rb` shows that it belongs to `ruby`".
[RHG]

`rb_` is a prefix to prevent exported symbols in libruby from
conflicting with symbols in other libraries, in particular,
dynamically loaded Ruby extension libraries.
So the prefix is reserved by Ruby by convention.

For gRPC, simply "grpc_" would be a better prefix.

# References
* [RHG]: Minero Aoki. "The Ruby Hacking Guide" (2002), chapter 4

### CODE REVIEW

**Comment by tbetbetbe** [comment]
@yugui: Thanks for this! Could you make the prefix  grpc_rb_ instead of grpc_ ?
This is 
- to minimize the risk of clashes with names in the C core
- make it easier to identify ruby extension symbols when debugging

**Comment by yugui** [comment]
@tbetbetbe
Sure.  I'll replace the prefixes as you said.

Also may I ask a question? I wonder if we need to export some symbols, e.g. `grpc_rb_cEvent`.

These variables need to be exported only if:
* you need to refer the variable in another compilation unit in your extension library; or
* you want other extension libraries to directly access to your implementation details for some reasons, e.g. performance.

I guess this is not the case for these symbols in this extension.  If so, you can keep them in static storage and I'm happy to write another pull request.
What do you think?

**Comment by yugui** [comment]
Replaced the prefix with "grpc_rb_". Please take another look.

**Comment by tbetbetbe** [comment]
Thanks, LGTM
> I guess this is not the case for these symbols in this extension. If so, you can keep them in static storage and I'm happy to write another pull request.
> What do you think?

This would be a great improvement - thanks for offering, I will look forward to the next pull request.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @yugui isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request merged**
