### PR TITLE
First upmerge from v1.1.x to master.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Ping, can we proceed with this one? Changes in 1.1.x are piling up.

**Comment by dgquintas** [comment]
Changes were approved a while ago. @nicolasnoble ?

**Comment by jtattermusch** [comment]
There's a conflict that must be resolved.

**Comment by murgatroid99** [comment]
Superseded by #9694.

**Pull request closed without merging**
