### PR TITLE
Change default for SETTINGS_MAX_HEADER_LIST_SIZE from 16KiB to 8KiB.

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by ncteisen** [comment]
What's the motivation for this change?

**Comment by ncteisen** [comment]
Ahh nevermind, I see this is cited as the default value in the HTTP/2 spec

**Comment by ncteisen** [comment]
What's the motivation for this change?

The HTTP/2 spec cites that this defaults to an infinite value:

> For any given request, a lower limit than what is advertised MAY
> be enforced.  The initial value of this setting is unlimited.

**Comment by markdroth** [comment]
We're trying to use the same defaults across all languages.  Java currently uses 8KiB, and @a11r decided that we should standardize on that value.  (Go does not yet support this setting at all, but they'll be adding it in the future.)

**Comment by a11r** [comment]
The 8KB default is used in production by many proxies that do not wish to
OOM by arbitrarily large headers.

I will not comment on the wisdom of the HTTP/2 spec authors making this
default to infinite.

**Comment by markdroth** [comment]
Jenkins: retest this please.

**Comment by markdroth** [comment]
Known failures: #11223

**Comment by ncteisen** [comment]
This caused large_metadata_bad_client_test to start failing consistently on MacOS. The failure was masked by #11223, but if you look at Jenkins, large_metadata_bad_client_test starts failing after this and it wasn't before.

The first run that shows this failure is https://grpc-testing.appspot.com/job/gRPC_master_macos/2892/#showFailuresLink

**Comment by markdroth** [comment]
Thanks for the heads up, @ncteisen.  I think that should be addressed by commit 1c537d8 in #11719, but we'll see once the tests run.

**Comment by markdroth** [comment]
Looks like #11719 didn't fully fix it, although it may have converted it from a consistent failure to a flake.  Interestingly, this time I saw the failure on Windows, not Mac.

I've created #11745 to track this problem.

**Pull request merged**
