### PR TITLE
Speed up sanity's check_sources_and_headers.py

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/13699
- precompute transitive closure of headers provided by each target in advance
- a bit of python style fixing

It now takes seconds to run (instead of 10 mins at 100% cpu). 
I also tried including a bad header and the script correctly reported it.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/12917
https://github.com/grpc/grpc/issues/13441

**Pull request merged**
