### PR TITLE
avoid c-ares dependency on libnsl (for v1.16.x)

### PR DESCRIPTION
**Pull request by jtattermusch**
Backport of fix for https://github.com/grpc/grpc/issues/17255

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,967,222      Total (=)      1,967,222

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,889,385      Total (<)     10,889,388

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
Will this go into master as well?

**Comment by jtattermusch** [comment]
@apolcyn  yes, i'll upmerge https://github.com/grpc/grpc/pull/17271

**Comment by jtattermusch** [comment]
@apolcyn a  bit more explanation why this change should be safe:
- the only place where we enable gRPC_BACKWARDS_COMPATIBILITY_MODE is when building the C# artifact (and the "hack" from this PR only gets activated when backward compatibility mode is enabled, it's off by default), so this change really shouldn't influence anyone's build. https://github.com/grpc/grpc/blob/e0d9692fa30cf3a7a8410a722693d5d3d68fb0fd/tools/run_tests/artifacts/build_artifact_csharp.sh#L24
- no other wrapped languages are using cmake to build the C-core extension.
- in Makefile, this change is not applicable as the reason why libnsl dependency gets added is the c-ares' own CMakeLists.txt. When building using Makefile, we are basically replicating c-ares build by pulling the list of source files (and we are not doing any special handling for libnsl).

**Comment by jtattermusch** [comment]
Merging to backport https://github.com/grpc/grpc/pull/17271.

**Comment by jtattermusch** [comment]
@nicolasnoble  please merge.

**Pull request merged**
