### PR TITLE
Make Python testing predictable again

### LINKED ISSUE #3902: Some Python tests never run
In our eternal quest to figure out how the heck to properly organize and test our code so our tools don't misbehave, we discover that *some of our tests are not running*.

All tests collectable from `grpcio_test/grpc_test/framework/_crust_over_core_face_interface_test.py` are inexplicably missing in the records. Other `load_tests` tests may also be missing. This is really strange given that some `load_tests` tests run and there's nothing immediately special about them versus these missing ones.

### PR DESCRIPTION
**Pull request by soltanmm**
This reorganizes the Python code, scraps the current testing
infrastructure, and implements a simple test discovery and run script
based on the standard Python unittest library so we can trust that our
tests are running.

It still needs some clean-up (and a way to capture stdout/stderr that works with the C extension); for now this is just to see how Jenkins feels about the `report.xml`.

fixes #3902 (and adds coverage for Cython, which for whatever reason I could never get to work with py.test)

EDIT: I'll also need to update the docker images, methinks...

### CODE REVIEW

**Comment by soltanmm** [comment]
And for some reason Jenkins appears to be running an older version of the run_python.sh script than the one in this PR. Hmm.

**Comment by soltanmm** [comment]
Clearly I need to do the output capturing so we don't always get timed-out on Jenkins from the sheer amount of output that happens when `GRPC_TRACE=api` is set... Also maybe add a grace period to `jobset.py`'s `JobSpec` such that processes are sent a SIGINT first then a SIGTERM a little after (giving scripts a chance to print out what's still in flight).

**Comment by soltanmm** [comment]
Latest commit is just me looking for Jenkins finishing the run without timing out; it runs all the cases in forked processes with duplicated FDs to force the output somewhere else. It doesn't keep track of failures at the moment; again, just looking for Jenkins not timing out.

**Comment by nathanielmanistaatgoogle** [comment]
(Reassign back to me when you would like this reviewed.)

**Comment by soltanmm** [comment]
Still need to edit (refactor?) [this function](https://github.com/soltanmm/grpc/blob/fffffuuuuu/tools/run_tests/run_interop_tests.py#L326) in `run_interop_tests.py` to respect the internal composition of command line flags per language...

**Comment by soltanmm** [comment]
cc @jtattermusch for changes in `run_interop_tests.py`.

**Comment by soltanmm** [comment]
This PR is going to be a sad panda after #4228 goes through and the release-0_12 branch is merged back into master.

**Comment by soltanmm** [comment]
Due to the merging of #4269 onto `release-0_12`, this PR is utterly poisonous (due to commit 0518f83) until it can be rebased against an `release-0_12`-upmerged master.

**Comment by soltanmm** [comment]
Closing in favor of working against `release-0_12`.

**Pull request closed without merging**
