### PR TITLE
updated version of abseil for enabling windows bazel build

### PR DESCRIPTION
**Pull request by billfeng327**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by jtattermusch** [comment]
nit: a link/description to the error this fixes would be useful once you send this for review.

**Comment by nicolasnoble** [comment]
Basically, this is to remove the "warnings are errors" flag for Windows.

**Comment by billfeng327** [comment]
> nit: a link/description to the error this fixes would be useful once you send this for review.

it's an internal bug, there's no github issue associated with it

**Comment by nicolasnoble** [comment]
The closest we have is https://github.com/bazelbuild/bazel/issues/5750 - Bazel triggers warnings on MSVC builds, so if we enable warnings as errors under Windows, we can't build. Absl used to have that enabled, and they removed it.

**Comment by jtattermusch** [comment]
> > nit: a link/description to the error this fixes would be useful once you send this for review.
> 
> it's an internal bug, there's no github issue associated with it

Got it, but at least copying the text of the error (or a link to a logs of a failing build) is something that would be helpful. Like this, whoever sees this PR, they'll have no idea what the original problem was or what was the change in the abseil repo that fixed the problem (there are 160 commits in the diff of original abseil version and the new one https://github.com/abseil/abseil-cpp/compare/cd95e71df6eaf8f2a282b1da556c2cf1c9b09207...308ce31528a7edfa39f5f6d36142278a0ae1bf45).

**Pull request merged**
