### PR TITLE
Revert "Revert "Fix shutdown of closed fd when c-ares opens a second fd""

### PR DESCRIPTION
**Pull request by apolcyn**
This reverts https://github.com/grpc/grpc/pull/15685

The issue with the original PR was that the socket stress loop wasn't setting `SO_REUSEADDR` on its newly opened sockets. In each of the failed tests in the [sponge log](https://sponge.corp.google.com/invocation?tab=Build+Log&id=38d7328f-130d-484a-a799-3994e3117385&searchFor=) of the previous failures, the sockets stress loop fails to bind to it's socket due to `errno: 98`.

Presumably this started happening on continuous Kokoro runs pretty quickly because of the business of those tests.

The error could be reliably reproduced locally by:

1) Hack the sockets stress loop to use some static port, rather than picking one from the port server (e.g., port 12000).
2) Start up some TCP server on your machine that listens on port 12000.
3) Set up some connection to that server and send something.
4) Bring down the server abruptly, while the client is still connected
5) Run `bins/dbg/resolver_component_tests_runner_invoker --test_bin_name=resolver_component_test`, and watch the sockets stress loop fail to bind to its port with `errno: 98`

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.0%      +8 [None]                                                                                +968  +0.0%
  +0.6%     +64 src/core/lib/iomgr/ev_epollex_linux.cc                                                 +64  +0.6%
       +89%     +73 fd_shutdown                                                                            +73   +89%
  +0.6%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.     +16  +0.6%
       +21%    +213 grpc_ares_notify_on_event_locked                                                      +213   +21%
      [NEW]    +116 fd_node_shutdown_locked(fd_node*, char const*) [clone .isra.1] [clone .part.2]        +116  [NEW]
       +22%     +64 grpc_ares_ev_driver_create                                                             +64   +22%

  +0.0%     +88 TOTAL                                                                              +1.02Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                 cpu_time    real_time
----------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/32768                                              +4%         +4%
BM_PumpStreamClientToServer<InProcessCHTTP2>/32768                                        +8%         +8%
BM_PumpStreamServerToClient<InProcess>/32768                                              +5%         +5%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                       -4%         -4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32768                    -6%         -6%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/2/0  -5%         -5%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/262144                       +5%         +5%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/2097152                        +7%         +7%
```

**Comment by apolcyn** [comment]
This one is ready for a look

**Comment by apolcyn** [comment]
test failures:
* linux: https://github.com/grpc/grpc/issues/15693
* windows: https://github.com/grpc/grpc/issues/15693
* mac: https://github.com/grpc/grpc/issues/15693, <objc issue>

**Pull request merged**
