### PR TITLE
Assert we get a valid creds.

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by dgquintas** [comment]
LGTM.

Do we know anything about that failing Python test?

**Comment by yang-g** [comment]
Seems like #5779.

**Comment by adelez** [comment]
Sorry I missed this PR. LGTM.

**Comment by dgquintas** [comment]
Ah yes. I tried looking for the issue but it seems github issue search doesn't work very well with partial substrings... anyhow, labelling for merge!

**Pull request merged**
