### PR TITLE
Dynamically allocate compression filter data

### PR DESCRIPTION
**Pull request by kpayson64**
Reduces about 500 bytes/call in non-compressed case

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                             cpu_time    real_time
----------------------------------------------------  ----------  -----------
BM_IsolatedFilter<CompressFilter, NoOp>               -20%        -20%
BM_IsolatedFilter<CompressFilter, SendEmptyMetadata>  -7%         -7%
```

**Comment by kpayson64** [comment]
0.831 Meta Score

**Comment by markdroth** [comment]
This looks good -- all comments are minor.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/core/ext/filters/http/message_compress/message_compress_filter.c, line 51 at r1](https://reviewable.io:443/reviews/grpc/grpc/12773#-KwBtoCltX2d69dtDnrr:-KwBtoCltX2d69dtDnrs:b-b8u72v) ([raw file](https://github.com/grpc/grpc/blob/b4c580053db71e601ae00aa2ecad433d63f8a5fa/src/core/ext/filters/http/message_compress/message_compress_filter.c#L51)):*
> ```C
> 
> #define NO_COMPRESSION (compression_data *)NULL
> #define UNKNOWN_COMPRESSION (compression_data *)0x1
> ```

Please call this `INITIAL_METADATA_UNSEEN`, since that more clearly expresses what it's used for.

---

*[src/core/ext/filters/http/message_compress/message_compress_filter.c, line 57 at r1](https://reviewable.io:443/reviews/grpc/grpc/12773#-KwBs0bBQq7zMEdKK7Tf:-KwBs0bBQq7zMEdKK7Tg:b-z1cdhr) ([raw file](https://github.com/grpc/grpc/blob/b4c580053db71e601ae00aa2ecad433d63f8a5fa/src/core/ext/filters/http/message_compress/message_compress_filter.c#L57)):*
>   grpc_call_combiner *call_combiner;
>   gpr_arena *arena;

Nit: Please put these two fields at the top of the struct, since they're constants set at initialization time.

---

*[src/core/ext/filters/http/message_compress/message_compress_filter.c, line 80 at r1](https://reviewable.io:443/reviews/grpc/grpc/12773#-KwBtXRA-qg7UzU41Zch:-KwBtXRA-qg7UzU41Zci:b8xvtly) ([raw file](https://github.com/grpc/grpc/blob/b4c580053db71e601ae00aa2ecad433d63f8a5fa/src/core/ext/filters/http/message_compress/message_compress_filter.c#L80)):*
> ```C
> } channel_data;
> 
> static void compression_data_init(
> ```

Suggest moving the definition of this function up to here so there's no need for the forward declaration.

---

*[src/core/ext/filters/http/message_compress/message_compress_filter.c, line 94 at r1](https://reviewable.io:443/reviews/grpc/grpc/12773#-KwBvNUXndgjjs9plVya:-KwBvNUXndgjjs9plVyb:bss9rap) ([raw file](https://github.com/grpc/grpc/blob/b4c580053db71e601ae00aa2ecad433d63f8a5fa/src/core/ext/filters/http/message_compress/message_compress_filter.c#L94)):*
> ```C
> }
> 
> /** Filter initial metadata */
> ```

Suggest extending this comment to indicate that this function also sets `calld->compression_data`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/12773#-:-KwBvbYykemAQ2k3HD3N:b-gn7ttg)*

**Pull request closed without merging**
