### PR TITLE
interop: Enable Go modules support

### PR DESCRIPTION
**Pull request by easwars**
@donnadionne

### CODE REVIEW

**Comment by jtattermusch** [comment]
The build is now succeeding, but a large number of go interop tests is now failing: 
https://source.cloud.google.com/results/invocations/4fbaddf0-0796-40a8-88e6-06e5420fa8c3/targets/github%2Fgrpc%2Finterop_test/tests

Perhaps not enough has been reverted in https://github.com/grpc/grpc-go/pull/4060 (previously the go build worked just fine and now it's broken -> there is definitely a go change which can be reverted to make things work again).

**Comment by jtattermusch** [comment]
https://source.cloud.google.com/results/invocations/47c358e3-9558-4908-a854-90cf66ed2051/targets/github%2Fgrpc%2Finterop_test/tests

**Comment by easwars** [comment]
Based on my local testing with the following `Dockerfile`:

```
FROM golang:1.11

RUN git clone --recursive https://github.com/grpc/grpc-go.git src/google.golang.org/grpc
RUN cd src/google.golang.org/grpc
RUN cd src/google.golang.org/grpc/interop/client && GO111MODULE=on go install
RUN cd src/google.golang.org/grpc/interop/server && GO111MODULE=on go install

CMD ["bash"]
```

I think we should go ahead with this change which enables module support by exporting `GO111MODULE=on`, and does not call `make deps` or `make testdeps`. Instead `go install` will pull in whatever it needs.

**Comment by easwars** [comment]
This is now getting past the docker build stage, but the tests are failing. I'm guessing this has something to do with the fact that `GO111MODULE=on` has to set in other scripts.

**Comment by easwars** [comment]
It does look like interop tests with Go are now passing, but there are some other failures which seem unrelated to Go.

This one though I'm not sure what is going on: https://source.cloud.google.com/results/invocations/8f617b63-e1cf-4290-b824-523ad23ed5f0/targets/github%2Fgrpc%2Frun_tests%2Fsanity_linux_dbg_native%2Ftools%2Fbuildgen%2Fgenerate_projects.sh/tests

**Comment by jtattermusch** [comment]
> It does look like interop tests with Go are now passing, but there are some other failures which seem unrelated to Go.

I think the remaining interop flakes are due to b/174126929

> 
> This one though I'm not sure what is going on: https://source.cloud.google.com/results/invocations/8f617b63-e1cf-4290-b824-523ad23ed5f0/targets/github%2Fgrpc%2Frun_tests%2Fsanity_linux_dbg_native%2Ftools%2Fbuildgen%2Fgenerate_projects.sh/tests

The sanity test failure basically complains that you've updated tools/dockerfile/interoptest/grpc_interop_go/build_interop.sh (which is generated from a template) but you haven't updates the corresponding build_interop.sh.template file. I already pointed that out in https://github.com/grpc/grpc/pull/24822#issuecomment-732770219

**Comment by jtattermusch** [comment]
I've pushed a few fixes to this branch 
- fix the sanity test error by also updating the build_interop.sh.template 
- performed a bit of cleanup of the older go docker images

Known failures:
- windows failures are due to `powershell -File src\csharp\install_dotnet_sdk.ps1` failure (unrelated to this PR)
- remaining interop test failures are due to b/174126929

**Review by jtattermusch — APPROVED** [review]
LGTM (after I applied a few fixes).

**Comment by jtattermusch** [comment]
@yulin-liang  this should probably be backported into v1.34.x branch so that the interop tests on that branch can pass.

**Comment by dfawley** [comment]
@jtattermusch thank you for the fixes!

Can you confirm my understanding that the interop tests no longer depend on `grpc-go/master@HEAD`'s `Makefile` at all anymore, and we can delete it?

**Comment by jtattermusch** [comment]
> @jtattermusch thank you for the fixes!
> 
> Can you confirm my understanding that the interop tests no longer depend on `grpc-go/master@HEAD`'s `Makefile` at all anymore, and we can delete it?

I can manually test the change for you if you point me to a PR.
(basically it's done by having grpc and grpc-go checkouts side-by-side locally and running `tools/run_tests/run_interop_tests.py -l go --cloud_to_prod --use_docker` - which will test the local working copy of grpc-go)

**Pull request merged**
