### PR TITLE
Allow custom prefixes for generated Python modules.

### PR DESCRIPTION
**Pull request by DPJacques**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
This is ok to test

**Comment by DPJacques** [comment]
Hmm, any guidance on these failed tests would be welcome.  Some of the output is not super helpful.  Some of them read like server errors?

**Comment by nicolasnoble** [comment]
We have some flaky tests. CC @dgquintas.

**Comment by dgquintas** [comment]
Known issues: #10002 #9980 #9804 #9976 #9956 #9609 

This list should be shorter very soon :/ 

But as far as this PR goes, consider testing to be OK.

**Comment by nathanielmanistaatgoogle** [comment]
Closing as superseded by [pull request 10141](https://github.com/grpc/grpc/pull/10141).

**Pull request closed without merging**
