### PR TITLE
Fix CMake installation issues

### LINKED ISSUE #10759: cmake installation doesn't generate targets file
Originally post:
http://stackoverflow.com/questions/43349916/grpc-cmake-installation-doesnt-generate-targets-file

I've been trying to build and install gRPC with cmake. Building the project went relatively smoothly with ninja after some confusion related to acquiring nuget packages and updating the git submodules.

I am having trouble installing gRPC though. After reading the cmake file I discovered that you need to manually set the gRPC_INSTALL cache variable to ON in order for cmake to generate an install target. After doing this I can invoke the install target and the libraries and headers and cmake config files are emplaced. But the cmake targets file is missing, and it isn't even being generated. The config file is simple, all it does is call the targets file:

```
include(${CMAKE_CURRENT_LIST_DIR}/gRPCTargets.cmake)
```
But it doesn't look like the CMakeLists file in gRPC is even attempting to generate this file, unless I am missing something? You can't even build the example cpp project in the gRPC repo with cmake because when it tries to find the gRPC package, the config file fails to find gRPCTargets.cmake. So what is the proper way to build, install, and link to gRPC with cmake? I am on Windows but that shouldn't matter with cmake.

### PR DESCRIPTION
**Pull request by randomguy3**
Fixes #10759 and #11006.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by randomguy3** [comment]
The method of deciding whether to enable gRPC_INSTALL may not be the best: turning it off can't be overridden.

NB: it still installs gflags when that is in module mode, and will until gflags/gflags#216 is merged. gflags should be statically linked into the binaries and not needed for the libraries, so nothing from it should need to be installed at all (I think).

It also still installs benchmark when that is in module mode - that needs to be fixed in the benchmark repository.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
Known issues:
https://github.com/grpc/grpc/issues/11383
https://github.com/grpc/grpc/issues/5450
https://github.com/grpc/grpc/issues/11116
https://github.com/grpc/grpc/issues/10686
https://github.com/grpc/grpc/issues/10455

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by ax3l** [comment]
@jtattermusch @muxi hi, is there a reason this 1-month-ago merged fix is in `master` but not yet in the 10-day-old `1.4.2` release? :) Will it make it into `1.4.3`? :)

**Comment by jtattermusch** [comment]
@ax3l  we just didn't think it was critical to backport this fix to v1.4.x (and no one had asked for backporting either). v1.5.0 will should be released soon, and it's going to have this fix.

**Comment by ax3l** [comment]
@jtattermusch thanks! the upcoming release will be sufficient, too - I will still need my PR in #11903 to build successfully with an external c-ares :)

**Pull request merged**
