### PR TITLE
Ruby distribtests on Linux

### PR DESCRIPTION
**Pull request by jtattermusch**
-- currently not passing because it tries to install protobuf (needs to be compiled and we don't install the tools in our images)
-- add gem install bundler for images that we'll get working the soonest.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Green enough.

**Comment by jtattermusch** [comment]
The distribtests are now passing with several linux distributions. What's not working are some of the older distros (mostly complaining about too old ruby installed or missing some dependencies in the Dockerfiles)

**Comment by jtattermusch** [comment]
```
PASSED: distribtest.ruby_linux_x64_jessie [time=35.6sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_centos7 [time=39.5sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_ubuntu1504 [time=32.5sec; retries=0:0]
PASSED: distribtest.ruby_linux_x86_jessie [time=40.7sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_fedora23 [time=41.1sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_ubuntu1510 [time=25.7sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_ubuntu1604 [time=24.8sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_fedora22 [time=47.4sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_fedora21 [time=47.9sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_fedora20 [time=58.7sec; retries=0:0]
```

**Comment by nicolasnoble** [comment]
So grpc-ruby requires Ruby 2.0.0+, that's a hard requirement.

**Comment by jtattermusch** [comment]
```
START: Building targets.
PASSED: distribtest.ruby_linux_x64_fedora22 [time=19.6sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_centos7 [time=19.9sec; retries=0:0]
PASSED: distribtest.ruby_linux_x86_jessie [time=31.1sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_fedora21 [time=33.4sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_fedora23 [time=33.8sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_wheezy [time=34.2sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_ubuntu1404 [time=34.4sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_centos6 [time=34.6sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_fedora20 [time=36.4sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_ubuntu1204 [time=36.5sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_jessie [time=37.5sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_ubuntu1504 [time=19.0sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_ubuntu1510 [time=19.2sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_opensuse [time=41.9sec; retries=0:0]
PASSED: distribtest.ruby_linux_x64_ubuntu1604 [time=18.0sec; retries=0:0]
SUCCESS: All targets built successfully.
```

**Comment by jtattermusch** [comment]
All linux distribtests are passing now!

**Pull request merged**
