### PR TITLE
Remove argue.js to improve performance by almost 40%

### PR DESCRIPTION
**Pull request by kprakasam**
I was evaluating the QPS performance on GRPC on Java/Node.js for an internals project, when I was surprised by low QPS numbers for Node.js dug in I found that big chunk of time was spent in argue.js call to fill in default and optional function parameters (see below for number and flame graph of profile output) so I have modified the code to fill in the default and optional parameters.  Results for Node.js QPS benchmark can be reproduced using this[ benchmark driver](https://github.com/kprakasam/grpc-node-benchmark-driver).

Machine Configuration
-----------------------
12GB RAM, 4 VCPU
Hardened Ubuntu  14.04
JDK 1.8 JVM / Node.JS v6.10
Canned Request  (1K) / Response (4K)

Java QPS
----------
Channels: 1
Outstanding RPCs per Channel: 10
Server Payload Size: 4096
Client Payload Size: 1024
50%ile Latency (in micros): 915
90%ile Latency (in micros): 1607
95%ile Latency (in micros): 1719
99%ile Latency (in micros): 1879
99.9%ile Latency (in micros): 4223
Maximum Latency (in micros): 24191
QPS: 9715

Node.JS QPS with Argue.js
---------------------------
Channels: 1
Outstanding RPCs per Channel: 10
Server Payload Size: 4096
Client Payload Size: 1024
50%ile Latency (in micros): 2883
90%ile Latency (in micros): 3611
95%ile Latency (in micros): 3815
99%ile Latency (in micros): 10783
99.9%ile Latency (in micros): 13231
Maximum Latency (in micros): 32303
Request Count: 1986074
QPS: 3310
User Time: 560.490193
System Time: 39.202487
Elapsed Time: 600.001344083

Node.JS QPS with out Argue.js
-------------------------------
Channels: 1
Outstanding RPCs per Channel: 10
Server Payload Size: 4096
Client Payload Size: 1024
50%ile Latency (in micros): 2032
90%ile Latency (in micros): 2621
95%ile Latency (in micros): 2851
99%ile Latency (in micros): 3583
99.9%ile Latency (in micros): 17887
Maximum Latency (in micros): 28463
Request Count: 2712765
QPS: 4521.272519230517
User Time: 547.966842
System Time: 53.169124
Elapsed Time: 600.000329213

Flame Graphs
--------------
no-arguejs

with-arguejs

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by kprakasam** [comment]
I signed it!

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by nicolasnoble** [comment]
This is ok to test.

**Comment by nicolasnoble** [comment]
I think you mean "without" in the second series of benchmark ?

**Comment by nicolasnoble** [comment]
Also we're kind of unlikely to release another 1.3 package at that point; do you think you could do that change either against master or the 1.4 release branch ?

**Comment by nicolasnoble** [comment]
1.4.x is fine with me if you manage to get it there. Master would be the default if you can't.

**Comment by murgatroid99** [comment]
Ping @kprakasam. Can you recreate this change against v1.4.x or master?

**Comment by kprakasam** [comment]
I am testing against 1.4.x, I'll send the PR today or tomorrow latest

**Comment by kprakasam** [comment]
I sent a new pull request for v1.4.x branch.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by murgatroid99** [comment]
Thank you. I'll close this one and use the new one instead.

**Pull request closed without merging**
