### PR TITLE
Add OpenCensus measures and views for retries

### PR DESCRIPTION
**Pull request by yashykt**
This is in preparation for #26739 for collecting metrics which uses the new stats API merged in #26673

Posting my understanding of the OpenCensus views as used by the gRPC C++ OpenCensus filter - 
From what I understand, for any particular view found in the spec, we implement three views. For example, if we want to implement `grpc.io/client/retries_per_call` with `distribution` as the aggregation, we actually define three views - `grpc.io/client/retries_per_call/cumulative`, `grpc.io/client/retries_per_call/minute` and `grpc.io/client/retries_per_call/hour`. These three views differ in their aggregation window. (AggregationWindow defines the time range over which recorded data is aggregated for each view.) 'Cumulative' is the default aggregation window, and based on the comment -
```
// You probably do not need this: ViewDescriptor has a Cumulative aggregation
// window by default, and that is what most exporters expect. Interval
// aggregation is mainly useful for on-task purposes, such as server status
// displays.
```
we don't really need the minute and hour aggregation windows, but that is what the already implemented views do, and so I've replicated that effort.

For each of these individual views, we also specify the `name` of the view, the `measure` to be used, the `aggregation` type (distribution, sum, count, last value) and `tags` if any (we use the client method as the tag).

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/26751)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
Thanks for doing this!

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26751#-:-MfE_MtC3N_0AXQbDBFU:bxgavm9)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[src/cpp/ext/filters/census/views.cc, line 133 at r1](https://reviewable.io/reviews/grpc/grpc/26751#-MfEZlz76LvjHP2E2_UO:-MfEZlz85Hvol5BADz1J:b3zv5qk) ([raw file](https://github.com/grpc/grpc/blob/23deec27277ea85e598e5aa5cfec70c1f67e584d/src/cpp/ext/filters/census/views.cc#L133)):*
> ```cpp
>   const static ViewDescriptor descriptor =
>       ViewDescriptor()
>           .set_name("grpc.io/client/completed_rpcs/cumulative")
> ```

We also need to add something similar to `completed_rpcs` (although without the status tag) for `retries` and `transparent_retries`, as per the retry stats spec.

(I would have used `started_rpcs` as an example instead of `completed_rpcs`, since the former does not have the status tag.  However, it looks like we're not defining that view at all, even though it's in the OpenCensus spec.  We're definitely going to need to audit all of this and standardize it as part of the new stats design.)
___
*[src/cpp/ext/filters/census/views.cc, line 338 at r1](https://reviewable.io/reviews/grpc/grpc/26751#-MfEZFb90ZzQaYk2_1Nd:-MfEZFb90ZzQaYk2_1Ne:b-8epmra) ([raw file](https://github.com/grpc/grpc/blob/23deec27277ea85e598e5aa5cfec70c1f67e584d/src/cpp/ext/filters/census/views.cc#L338)):*
> ```cpp
>   const static ViewDescriptor descriptor =
>       MinuteDescriptor()
>           .set_name("grpc.io/client/retry_delay_per_call/minute")
> ```

I see `retry_delay_per_call` for minute and hour, but not cummulative.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26751)* status: all files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/cpp/ext/filters/census/views.cc, line 133 at r1](https://reviewable.io/reviews/grpc/grpc/26751#-MfEZlz76LvjHP2E2_UO:-MfEfM1_B4D1-AnMP03F:btytq42) ([raw file](https://github.com/grpc/grpc/blob/23deec27277ea85e598e5aa5cfec70c1f67e584d/src/cpp/ext/filters/census/views.cc#L133)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We also need to add something similar to `completed_rpcs` (although without the status tag) for `retries` and `transparent_retries`, as per the retry stats spec.

(I would have used `started_rpcs` as an example instead of `completed_rpcs`, since the former does not have the status tag.  However, it looks like we're not defining that view at all, even though it's in the OpenCensus spec.  We're definitely going to need to audit all of this and standardize it as part of the new stats design.)
</blockquote></details>

Is there a different document? I'm referring to the currently internal spec at (go/grpc-retry-stats)
___
*[src/cpp/ext/filters/census/views.cc, line 338 at r1](https://reviewable.io/reviews/grpc/grpc/26751#-MfEZFb90ZzQaYk2_1Nd:-MfEfjZn7DCcnjwafEC6:b-35k64w) ([raw file](https://github.com/grpc/grpc/blob/23deec27277ea85e598e5aa5cfec70c1f67e584d/src/cpp/ext/filters/census/views.cc#L338)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I see `retry_delay_per_call` for minute and hour, but not cummulative.
</blockquote></details>

Based this on the internal doc at go/grpc-retry-stats

**Comment by yashykt** [comment]
@markdroth PTALA. I've made changes based on what we discussed on chat.

**Review by markdroth — APPROVED** [review]
Looks like the view names don't exactly match the OpenCensus spec (which doesn't include separate views for cumulative/hour/minute), but they're consistent with what we've already got here, so I think this is good for now.  We can audit the views and try to standardize on something as part of the broader stats effort.

Thanks for doing this!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26751#-:-MfFFZr65-qcvIrfQo-m:bt6c2ax)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)

**Comment by yashykt** [comment]
Known issues: #26652

**Comment by yashykt** [comment]
Thanks for reviewing!

**Pull request merged**
