### PR TITLE
Python Beta documentation

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
@soltanmm and @LisaFC, would you both please review this? It should be easy and I don't anticipate any surprises.

### CODE REVIEW

**Comment by soltanmm** [comment]
Did you remove the execution flags on `route_guide_client.py` on purpose?

**Comment by nathanielmanistaatgoogle** [comment]
I didn't, but now that you point out that it happened, it's the right thing (because the file lacks a shebang line, so it's not directly runnable anyway) and I've gone and done it to route_guide_server.py as well.

Unless you think the files *should* be directly executable? I'd rather they weren't; I think the example is more n00b-friendly if a failure-to-find-an-executable-python-on-the-system happens with the command "python route_guide_server.py" rather than "./route_guide_server.py". In the latter case, I think the user might be able to misconstrue the failure as happening "inside" the sample code, whereas in the former case it would be more clear that the sample code is just an input file.

**Comment by LisaFC** [comment]
The updated tutorial text looks good, but could you make the updates to the route guide doc in grpc.io  - if you don't have edit rights, let me know/ask Jayant? Ditto can you update https://github.com/grpc/grpc.github.io/blob/master/docs/index.md with any helloworld newness? (note the rendered version of this in Github looks a bit weird because it hasn't got the multi-language Javascript tab thing from the site version: http://www.grpc.io/docs/)

We're planning on removing the duplicate route guide and other tutorials from the code repo and replacing them with simple READMEs w/ links to the grpc.io versions, because at the moment the magical process for keeping them in sync is me manually copying the content across every time anyone updates them. :(

**Comment by nathanielmanistaatgoogle** [comment]
Well it looks like I shouldn't replicate a helloworld change in grpc.io because you're removing all those files in https://github.com/grpc/grpc.github.io/pull/70, yes?

**Comment by LisaFC** [comment]
I'm moving all the current Quickstart/gRPC in 3 minutes/whatever docs, but the helloworld stuff in all languages is also covered in the Overview, which is very much staying.

**Comment by nathanielmanistaatgoogle** [comment]
https://github.com/grpc/grpc.github.io/pull/71 is the replication of the doc changes here in the https://github.com/grpc/grpc.github.io repository. :-)

**Pull request merged**
