### PR TITLE
Remove unused idle_jobs

### PR DESCRIPTION
**Pull request by kpayson64**
idle_jobs is only ever checked for work, but never has anything added to it.

It looks like dead code.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++

 -------------- SHRINKING                                                  --------------
  -0.0%    -120 [None]                                                     -1.55Ki  -0.0%
  -3.7%    -480 src/core/lib/iomgr/ev_poll_posix.cc                           -480  -3.7%
      -9.2%    -268 pollset_work                                                  -268  -9.2%
      [DEL]    -169 init_result(poll_args*) [clone .constprop.19]                 -169  [DEL]
      [DEL]    -124 unref_by(grpc_fd*, int) [clone .constprop.21]                 -124  [DEL]
      [DEL]    -106 pollset_kick_locked(grpc_fd_watcher*) [clone .isra.12]        -106  [DEL]
     -39.9%     -81 pollset_shutdown                                               -81 -39.9%
     -31.6%     -62 pollset_destroy                                                -62 -31.6%
     -33.6%     -51 finish_shutdown                                                -51 -33.6%
     -17.6%     -22 pollset_init                                                   -22 -17.6%
      -5.0%      -9 pollset_add_fd                                                  -9  -5.0%

  -0.0%    -600 TOTAL                                                      -2.02Ki  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by kpayson64** [comment]
#13945 
#14362

**Pull request merged**
