### PR TITLE
Add abseil thread annotations to grpcpp/sync

### PR DESCRIPTION
**Pull request by veblush**
Adding clang thread annotations to grpcpp/sync/mutex so that it can benefit from clang thread analysis. This is a follow-up of https://github.com/grpc/grpc/pull/25325 which did the same thing for core/sync/mutex.
 
This PR does two things;
- Updating the existing grpcpp mutex to have annotation and abseil-compatibility.
- Updating the existing tests to support abseil dependency in the public headers of gRPC C++.

### CODE REVIEW

**Comment by veblush** [comment]
Failed test:
- distribtest.cpp_linux_x64_stretch_cmake_module_install_pkgconfig
- distribtest.cpp_linux_x64_stretch_cmake_module_install
- distribtest.cpp_linux_x64_stretch_raspberry_pi
- 
All tests other than cpp_linux_x64_stretch_raspberry_pi should work with this PR

**Review by vjpai — CHANGES_REQUESTED** [review]
Can I suggest you also add in some use of thread annotations (e.g., go ahead and steal the code in #25571) to show that it works as desired? Otherwise this looks great.

**Comment by veblush** [comment]
@vjpai I verified this with `client_lb_end2end_test`.

**Review by vjpai — APPROVED** [review]

**Comment by veblush** [comment]
[grpc_build_artifacts_multiplatform](https://fusion2.corp.google.com/invocations/5ad3f263-994c-42c6-b1de-3ae98b926463): running

**Comment by veblush** [comment]
Portability build failed ([log](https://source.cloud.google.com/results/invocations/82621d06-85cd-47c2-a79d-ca4f468f3283/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_c%2B%2B_linux_dbg_native_x64_gcc_musl_buildonly/tests))

```
/var/local/git/grpc/cmake/build/gens/test/core/tsi/alts/fake_handshaker/transport_security_common.pb.h:221:35: error: expected unqualified-id before 'unsigned'
   ::PROTOBUF_NAMESPACE_ID::uint32 major() const;
                                   ^~~~~
/var/local/git/grpc/cmake/build/gens/test/core/tsi/alts/fake_handshaker/transport_security_common.pb.h:221:35: error: expected ')' before 'unsigned'
/var/local/git/grpc/cmake/build/gens/test/core/tsi/alts/fake_handshaker/transport_security_common.pb.h:221:35: error: expected ')' before 'unsigned'
/var/local/git/grpc/cmake/build/gens/test/core/tsi/alts/fake_handshaker/transport_security_common.pb.h:230:35: error: expected unqualified-id before 'unsigned'
   ::PROTOBUF_NAMESPACE_ID::uint32 minor() const;
                                   ^~~~~
/var/local/git/grpc/cmake/build/gens/test/core/tsi/alts/fake_handshaker/transport_security_common.pb.h:230:35: error: expected ')' before 'unsigned'
/var/local/git/grpc/cmake/build/gens/test/core/tsi/alts/fake_handshaker/transport_security_common.pb.h:230:35: error: expected ')' before 'unsigned'
/var/local/git/grpc/cmake/build/gens/test/core/tsi/alts/fake_handshaker/transport_security_common.pb.h:435:69: error: expected unqualified-id before '(' token
 inline ::PROTOBUF_NAMESPACE_ID::uint32 RpcProtocolVersions_Version::major() const {
                                                                     ^~~~~
/var/local/git/grpc/cmake/build/gens/test/core/tsi/alts/fake_handshaker/transport_security_common.pb.h:455:69: error: expected unqualified-id before '(' token
 inline ::PROTOBUF_NAMESPACE_ID::uint32 RpcProtocolVersions_Version::minor() const {
                                                                     ^~~~~
```

This might be related to [this](https://sourceware.org/bugzilla/show_bug.cgi?id=19239). So this can be fixed by either upgrading alpine linux to the latest or changing major and minor fields in the proto file which is a bit harder because other languages also depend on.

**Comment by veblush** [comment]
Yeah, upgrading alpine linux to 3.11 appears to solve the compilation issue.

**Pull request merged**
