### PR TITLE
Add more counters to debug the timer crash on iOS

### PR DESCRIPTION
**Pull request by muxi**
Previous counters found that the crash was caused by nanosecond component of [`abs_deadline`](https://github.com/grpc/grpc/blob/60f2d379fec3364ff59f4f0d463b16275525863d/src/core/lib/gpr/sync_posix.cc#L106) being either negative or greater than `1e9` (more than 1 second). We were not able to find a breach in the code. Adding more counters to pinpoint where the corruption occurs.

cc: @srini100

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,548      Total (=)      2,019,548

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,155,951      Total (>)     11,155,950

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,548      Total (=)      2,019,548

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,155,955      Total (>)     11,155,948

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by promiseofcake** [comment]
@muxi, I believe we are seeing a crash related to `gpr_cv_wait` in sync_posix.cc in production at scale, would it be helpful to collaborate with our team on this and see what we can dig up?

**Comment by muxi** [comment]
@promiseofcake - we are still interested in what you found in your product :)

**Pull request merged**
