### PR TITLE
Delete qps_driver and dependent scripts, add quit to qps_json_driver

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Sanity fails:
```
--- /local-code/test/cpp/qps/qps_json_driver.cc	2016-04-20 20:11:14.007725150 +0000
+++ /tmp/tmp.dtgi1DLBqX	2016-04-20 20:13:51.090268921 +0000
@@ -59,10 +59,10 @@
   bool scfile = (FLAGS_scenarios_file != "");
   bool scjson = (FLAGS_scenarios_json != "");
   if ((!scfile && !scjson && !FLAGS_quit) ||
-      (scfile && (scjson || FLAGS_quit)) ||
-      (scjson && FLAGS_quit)) {
-    gpr_log(GPR_ERROR, "Exactly one of --scenarios_file, --scenarios_json, "
-	    "or --quit must be set");
+      (scfile && (scjson || FLAGS_quit)) || (scjson && FLAGS_quit)) {
+    gpr_log(GPR_ERROR,
+            "Exactly one of --scenarios_file, --scenarios_json, "
+            "or --quit must be set");
     abort();
   }
```

**Comment by jtattermusch** [comment]
LGTM once code formatting is fixed.

**Comment by vjpai** [comment]
Fixes #6193

**Comment by jtattermusch** [comment]
Travis tests seen to be unhappy and it actually might be related to this change.

**Comment by jtattermusch** [comment]
Travis seems happy now, merging.

**Pull request merged**
