### PR TITLE
Move functions for individual args out of channel_args.{h,cc}.

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by markdroth** [comment]
Ping?

**Comment by muxi** [comment]
Sorry, missed this. I'll get the review done later today.

**Comment by markdroth** [comment]
Thanks!

**Comment by markdroth** [comment]
I'm not sure why the commits being squashed would hide anything in the diff.

In any case, the only other change here is to remove the unused `grpc_channel_args_set_socket_mutator()` function.

**Comment by markdroth** [comment]
Known issues: #18637 #18511

**Comment by muxi** [comment]
All right

**Pull request merged**
