### PR TITLE
re-generate ruby protos and add a test case

### PR DESCRIPTION
**Pull request by yang-g**
The proto generation script does not seem to work properly and will be fixed in a later try.
A compression test case is added to test compression path. The test case passed.

#6745

### CODE REVIEW

**Comment by yang-g** [comment]
For reference, tested locally with commands:
server:
bins/opt/interop_server --port=50051 --use_tls=true
client:
ruby src/ruby/pb/test/client.rb --server_host_override foo.test.google.fr --use_tls true --use_test_ca true --test_case client_compressed_unary --server_host 127.0.0.1 --server_port 50051

**Comment by murgatroid99** [comment]
I am glad to have an implementation of this interop test, but this doesn't actually resolve that issue. The point of that issue is to verify that Ruby code behaves correctly when *receiving* compressed messages, and that test just involves the ruby code *sending* compressed messages.

**Comment by yang-g** [comment]
Added another case with receive. Is there any way we can check the incoming message is compressed?

**Comment by murgatroid99** [comment]
Unfortunately, we can't make that check. The way I originally imagined writing this test was as a unit test with a Ruby client *and* server sending compressed messages to each other.

**Comment by yang-g** [comment]
The last commit was reverted as a unit test is added in #7073.
I will leave this PR to you to see whether you want to close it or not.

**Comment by murgatroid99** [comment]
Thank you for your help, but I think I will close this one. I think it would be better to implement that interop test once we have a complete implementation of compression in Ruby.

**Pull request closed without merging**
