### PR TITLE
Update port_platform.h

### PR DESCRIPTION
**Pull request by IronsDu**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
What it this pull request trying to achieve?

**Comment by jtattermusch** [comment]
The PR seems abandoned and it's not clear what it is good for. Please provide a description and we can reopen it.

**Pull request closed without merging**
