### PR TITLE
[bazel RBE] add direct link to Fusion UI in bazel rbe invocations

### PR DESCRIPTION
**Pull request by jtattermusch**
Currently the bazel invocations provide a link back to the original kokoro jobs for resultstore and sponge UIs.
This adds another back link to Fusion UI, which has the advantage of 
- being able to navigate to the kokoro job overview
- there is a button to trigger a new build (in case the job needs to be re-run).

image

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @drfloob

**Comment by jtattermusch** [comment]
Result: 
linux, windows (and mac) bazel RBE invocations now have the fusion url link on them:
- https://source.cloud.google.com/results/invocations/d581975c-682f-4813-a94c-5bd9417ad95e/details
- https://source.cloud.google.com/results/invocations/59cccc7b-7af7-4bf6-ad93-06a4c270e1f7/details
- https://source.cloud.google.com/results/invocations/b2092bdf-0478-4b16-96f5-e3575e5fe1c4/details

**Review by veblush — APPROVED** [review]

**Review by drfloob — APPROVED** [review]
Very nice! This will save me 2 clicks per failing CI job. Previously: (failing job link) -> Invocation details -> Kokoro Sponge URL -> Invocation details -> Fusion URL.

Do you know how we might add the link to the "Build Context" in the top right of some CI jobs? That would save even more clicks. For example: https://source.cloud.google.com/results/invocations/999944dd-3c4a-45ed-8d28-bc00dad0d5d9/targets
image

**Comment by jtattermusch** [comment]
> Very nice! This will save me 2 clicks per failing CI job. Previously: (failing job link) -> Invocation details -> Kokoro Sponge URL -> Invocation details -> Fusion URL.
> 
> Do you know how we might add the link to the "Build Context" in the top right of some CI jobs? That would save even more clicks. For example: https://source.cloud.google.com/results/invocations/999944dd-3c4a-45ed-8d28-bc00dad0d5d9/targets image



> Very nice! This will save me 2 clicks per failing CI job. Previously: (failing job link) -> Invocation details -> Kokoro Sponge URL -> Invocation details -> Fusion URL.
> 
> Do you know how we might add the link to the "Build Context" in the top right of some CI jobs? That would save even more clicks. For example: https://source.cloud.google.com/results/invocations/999944dd-3c4a-45ed-8d28-bc00dad0d5d9/targets image

I don't think we can add that ourselves, since the "build context" is implemented by kokoro for the kokoro jobs. The results store links that correspond to a bazel invocation and not a kokoro job don't have the "build context" set and I don't know of a way to set it.

**Pull request merged**
