### PR TITLE
Modification of #20862 to Work in Blaze

### PR DESCRIPTION
**Pull request by gnossen**
This PR modifies and supercedes https://github.com/grpc/grpc/pull/20862 in order to make it compatible with Blaze as the build system.

This PR shouldn't necessarily require a cherrypick for submission, but I would like to test it out in google3 before merge.

@eytankidron Please take a look.

### CODE REVIEW

**Comment by eytankidron** [comment]
LGTM.

Would there need to be a google3 equivalent of bazel/grpc_build_system.bzl that defines LARGE_MACHINE in a different way?

**Comment by gnossen** [comment]
It's actually already there, courtesy of @jtattermusch

**Comment by gnossen** [comment]
Known failures:
 - https://github.com/grpc/grpc/issues/20817

**Comment by gnossen** [comment]
After my last commit, this *will* require a cherrypick.

**Comment by gnossen** [comment]
Failures:
 - https://github.com/grpc/grpc/issues/20436
 - https://github.com/grpc/grpc/issues/20817

**Pull request merged**
