### PR TITLE
Revert "Remove ccache from all docker images"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#15466

This was merged around the time https://github.com/grpc/grpc/issues/15470 started happening, so trying if reverting would help.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
Based on the test results, this actually seem to be solving the problem, but i have no idea why - the ccache change shouldn't really affect node in any way. It might be some other cached stuff in the newly uploaded docker image that breaks node.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
merging to fix the breakage.

**Pull request merged**
