### PR TITLE
Update function signature in grpc_security

### PR DESCRIPTION
**Pull request by muxi**
Users were getting warning (which is treated as error) when building this since they are `extern C` functions.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,961,099      Total (=)      1,961,099

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,883,609      Total (>)     10,883,607

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by nicolasnoble** [comment]
By the way, as a very minor nit: the function signatures didn't change, only their declaration. Saying that the signature changes is automatically an API change, and is more scary :-)

**Comment by vjpai** [comment]
@nicolasnoble : do you know why this passed our compiler warnings? Muxi and I were looking at this yesterday, and it seems like old-style declarations should be caught by `-Wextra`, which we use.

**Pull request merged**
