### PR TITLE
Fix new memory corruption in QPS test

### LINKED ISSUE #16899: Corrupt Memory Bug in qps_json_driver
Issue is reproduced in #16889

### PR DESCRIPTION
**Pull request by vjpai**
Maybe it was never really legit to use the assignment operator on a ServerResponseWriter (etc) class but the issue got exposed because of the cq_tag change.

Supercedes #16889 
Fixes #16899

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,996,269      Total (=)      1,996,269

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,020,631      Total (>)     11,020,628

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,996,269      Total (=)      1,996,269

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,020,630      Total (>)     11,020,629

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
As we discussed, I think we can make this better by redefining the assignment operator for CallOpSet to handle cq_tag. But let's try this clean version First and hope that it doesn't cause any regression.

**Comment by vjpai** [comment]
actually, thinking about it, I should fix the assignment operator. It is fundamental to the API since we haven't deleted it. I will respin this pull request.

**Comment by vjpai** [comment]
Closing this one in favor of #16950

**Pull request closed without merging**
