### PR TITLE
Backport #14691 (Kokoro package build and distrib test config) to v1.10.x

### PR DESCRIPTION
**Pull request by mehrdada**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
The build worked this time I triggered it without merging this.  I will close it for now unmerged.

**Comment by jtattermusch** [comment]
I think you actually do need this PR.
the grpc_build_artifacts might succeed, but the grpc_build_packages fails with

`Build config /tmp/workspace/workspace/grpc/core/master/windows/grpc_build_packages/src/github/grpc/tools/internal_ci/windows/grpc_build_packages.cfg does not exist`

**Comment by mehrdada** [comment]
Ok, merged, I'll trigger a package rebuild now.

**Pull request merged**
