### PR TITLE
C++ default health checking service.

### PR DESCRIPTION
**Pull request by yang-g**
WIP

### CODE REVIEW

**Comment by yang-g** [comment]
All async parts are removed per offline discussion in light of https://github.com/grpc/proposal/pull/6

**Comment by yang-g** [comment]
ping~

**Comment by ctiller** [comment]
Much cleaner, thanks!

**Comment by yang-g** [comment]
jenkins: test this please

**Comment by yang-g** [comment]
Test flakes: #9504 #9088 #9399 #9762 
Also bazel build fails with gflags.h not found error which I assume will be fixed by submodule update.

**Pull request merged**
