### PR TITLE
Increase client load reporting interval to avoid test flake.

### LINKED ISSUE #14724: bins/tsan/grpclb_end2end_test SingleBalancerWithClientLoadReportingTest.Vanilla is flaky under tsan and poll-cv
This showed up today as a new flake, but turns out to be a very old one, as far back as I can easily go: even at 5b48dc737151464c1d863df6e4318ff3d766ddbc from Jan 20th the test is flaky under tsan and poll-cv:

```
$ git checkout 5b48dc7371
$ git submodule update --init && make clean && ./tools/run_tests/run_tests.py -l c++ -c tsan -S -n inf -r 'ReportingTest.Vanilla' -a 10 --force_use_pollers=poll-cv
...
PASSED: make [time=171.1sec, retries=0:0]2018-03-15 18:21:03,592 detected port server running version 20
2018-03-15 18:21:03,652 my port server is version 20

D0315 18:29:29.424103529   40306 ev_posix.cc:128]            Using polling engine: poll-cv
D0315 18:29:29.424366008   40306 dns_resolver.cc:294]        Using native dns resolver
D0315 18:29:29.443516168   40306 test_config.cc:388]         test slowdown factor: sanitizer=5, fixture=1, poller=5, total=25
Note: Google Test filter = SingleBalancerWithClientLoadReportingTest.Vanilla
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SingleBalancerWithClientLoadReportingTest
[ RUN      ] SingleBalancerWithClientLoadReportingTest.Vanilla
I0315 18:29:29.481200295   40306 grpclb_end2end_test.cc:529] starting backend server on port 26323
I0315 18:29:29.496242421   40324 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0315 18:29:29.527923000   40306 grpclb_end2end_test.cc:534] backend server startup complete
I0315 18:29:29.588540246   40306 grpclb_end2end_test.cc:529] starting backend server on port 28141
I0315 18:29:29.600381560   40347 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0315 18:29:29.611996305   40306 grpclb_end2end_test.cc:534] backend server startup complete
I0315 18:29:29.668559045   40306 grpclb_end2end_test.cc:529] starting backend server on port 7427
I0315 18:29:29.672035762   40369 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0315 18:29:29.699853061   40306 grpclb_end2end_test.cc:534] backend server startup complete
I0315 18:29:29.728743518   40306 grpclb_end2end_test.cc:529] starting backend server on port 2142
I0315 18:29:29.735999136   40393 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0315 18:29:29.743560371   40306 grpclb_end2end_test.cc:534] backend server startup complete
I0315 18:29:29.756341191   40306 grpclb_end2end_test.cc:529] starting balancer server on port 25731
I0315 18:29:29.771045371   40410 server_builder.cc:269]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0315 18:29:29.795893440   40306 grpclb_end2end_test.cc:534] balancer server startup complete
I0315 18:29:29.827537862   40306 subchannel.cc:603]          New connected subchannel at 0x7d080000d3a0 for subchannel 0x7d540000f500
I0315 18:29:29.857780218   40414 grpclb_end2end_test.cc:187] LB[0x7d480000bb80]: BalanceLoad
I0315 18:29:29.859436819   40414 grpclb_end2end_test.cc:191] LB[0x7d480000bb80]: recv msg 'initial_request {
  name: "servername_not_used"
}
'
I0315 18:29:29.859857303   40414 grpclb_end2end_test.cc:303] LB[0x7d480000bb80]: sleeping for 0 ms...
I0315 18:29:29.860012373   40414 grpclb_end2end_test.cc:309] LB[0x7d480000bb80]: Woke up! Sending response 'server_list {
  servers {
    ip_address: "\177\000\000\001"
    port: 26323
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 28141
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 7427
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 2142
  }
}
'
I0315 18:29:29.860747339   40306 grpclb.cc:489]              Missing LB token for backend address 'ipv4:127.0.0.1:26323'. The empty token will be used instead
I0315 18:29:29.860786948   40306 grpclb.cc:489]              Missing LB token for backend address 'ipv4:127.0.0.1:28141'. The empty token will be used instead
I0315 18:29:29.860808731   40306 grpclb.cc:489]              Missing LB token for backend address 'ipv4:127.0.0.1:7427'. The empty token will be used instead
I0315 18:29:29.860828187   40306 grpclb.cc:489]              Missing LB token for backend address 'ipv4:127.0.0.1:2142'. The empty token will be used instead
I0315 18:29:29.886504077   40421 subchannel.cc:603]          New connected subchannel at 0x7d0800001b20 for subchannel 0x7d540000eb00
I0315 18:29:29.886717477   40421 subchannel.cc:603]          New connected subchannel at 0x7d080000dba0 for subchannel 0x7d540000e880
I0315 18:29:29.886892102   40421 subchannel.cc:603]          New connected subchannel at 0x7d080000dda0 for subchannel 0x7d540000e600
I0315 18:29:29.887074329   40421 subchannel.cc:603]          New connected subchannel at 0x7d08000197e0 for subchannel 0x7d540000e380
I0315 18:29:30.082489267   40306 grpclb_end2end_test.cc:435] Performed 4 warm up requests (a multiple of 1) against the backends. 4 succeeded, 0 failed, 0 dropped.
I0315 18:29:31.902085556   40414 grpclb_end2end_test.cc:224] LB[0x7d480000bb80]: recv client load report msg: 'client_stats {
  timestamp {
    seconds: 1521163771
    nanos: 859972472
  }
  num_calls_started: 400
  num_calls_finished: 399
  num_calls_finished_known_received: 399
}
'
I0315 18:29:31.902147196   40414 grpclb_end2end_test.cc:249] LB[0x7d480000bb80]: done
test/cpp/end2end/grpclb_end2end_test.cc:1201: Failure
      Expected: kNumRpcsPerAddress * num_backends_ + num_ok
      Which is: 404
To be equal to: client_stats.num_calls_started
      Which is: 400
test/cpp/end2end/grpclb_end2end_test.cc:1203: Failure
      Expected: kNumRpcsPerAddress * num_backends_ + num_ok
      Which is: 404
To be equal to: client_stats.num_calls_finished
      Which is: 399
test/cpp/end2end/grpclb_end2end_test.cc:1206: Failure
      Expected: kNumRpcsPerAddress * num_backends_ + (num_ok + num_drops)
      Which is: 404
To be equal to: client_stats.num_calls_finished_known_received
      Which is: 399
I0315 18:29:31.904212093   40306 grpclb_end2end_test.cc:140] Backend: shut down
I0315 18:29:31.904249498   40306 grpclb_end2end_test.cc:553] backend about to shutdown
I0315 18:29:31.907577804   40314 subchannel.cc:641]          Connect failed: {"created":"@1521163771.907325738","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":198,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:26323"}
I0315 18:29:31.907643749   40314 subchannel.cc:466]          Subchannel 0x7d540000eb00: Retry in 999 milliseconds
I0315 18:29:31.907797003   40306 grpclb_end2end_test.cc:556] backend shutdown completed
I0315 18:29:31.907829717   40306 grpclb_end2end_test.cc:140] Backend: shut down
I0315 18:29:31.907992901   40306 grpclb_end2end_test.cc:553] backend about to shutdown
I0315 18:29:31.919010714   40306 grpclb_end2end_test.cc:556] backend shutdown completed
I0315 18:29:31.919061318   40306 grpclb_end2end_test.cc:140] Backend: shut down
I0315 18:29:31.919082851   40306 grpclb_end2end_test.cc:553] backend about to shutdown
I0315 18:29:31.920077557   40314 subchannel.cc:641]          Connect failed: {"created":"@1521163771.919867532","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":198,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:28141"}
I0315 18:29:31.920131052   40314 subchannel.cc:466]          Subchannel 0x7d540000e880: Retry in 998 milliseconds
I0315 18:29:31.922376797   40314 subchannel.cc:641]          Connect failed: {"created":"@1521163771.922182628","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":198,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:7427"}
I0315 18:29:31.922427070   40314 subchannel.cc:466]          Subchannel 0x7d540000e600: Retry in 999 milliseconds
I0315 18:29:31.923479868   40306 grpclb_end2end_test.cc:556] backend shutdown completed
I0315 18:29:31.923510127   40306 grpclb_end2end_test.cc:140] Backend: shut down
I0315 18:29:31.923528769   40306 grpclb_end2end_test.cc:553] backend about to shutdown
I0315 18:29:31.928708864   40306 grpclb_end2end_test.cc:556] backend shutdown completed
I0315 18:29:31.928880189   40306 grpclb_end2end_test.cc:264] LB[0x7d480000bb80]: shut down
I0315 18:29:31.928905258   40306 grpclb_end2end_test.cc:553] balancer about to shutdown
I0315 18:29:31.933102756   40421 subchannel.cc:641]          Connect failed: {"created":"@1521163771.932871026","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":198,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:2142"}
I0315 18:29:31.933296878   40421 subchannel.cc:466]          Subchannel 0x7d540000e380: Retry in 998 milliseconds
I0315 18:29:31.937959930   40306 grpclb_end2end_test.cc:556] balancer shutdown completed
[  FAILED  ] SingleBalancerWithClientLoadReportingTest.Vanilla (2504 ms)
[----------] 1 test from SingleBalancerWithClientLoadReportingTest (2504 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2505 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SingleBalancerWithClientLoadReportingTest.Vanilla

 1 FAILED TEST
D0315 18:29:32.955675510   40306 ev_posix.cc:128]            Using polling engine: poll-cv
D0315 18:29:32.955764221   40306 dns_resolver.cc:294]        Using native dns resolver
FAILED: bins/tsan/grpclb_end2end_test --gtest_filter=SingleBalancerWithClientLoadReportingTest.Vanilla  GRPC_POLL_STRATEGY=poll-cv [ret=1, pid=40306, time=4.8sec]
FLAKE: bins/tsan/grpclb_end2end_test --gtest_filter=SingleBalancerWithClientLoadReportingTest.Vanilla  GRPC_POLL_STRATEGY=poll-cv [1/1291 runs flaked]
```
Note that it may take a while. In the previous example, it took 1291 runs and about 11 minutes.

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #14724.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: #15610 #15672

**Pull request merged**
