### PR TITLE
Fix a bug in synchronous streaming QPS test

### PR DESCRIPTION
**Pull request by vjpai**
This test was not properly configured to support multiple streams.

### CODE REVIEW

**Comment by ctiller** [comment]
Should this still be considered DNM?

**Comment by vjpai** [comment]
Yes. There is a deadlock that is getting triggered right now. It might be
that the deadlock was always there and is just now being exposed, but it's
certainly there. It deadlocks pretty soon after start, I think on the mu_
lock of Client::Thread, and I don't understand why it is happening.

**Comment by vjpai** [comment]
I have removed the DNM. PTAL. Thanks!

**Comment by vjpai** [comment]
Just waiting on Ruby fix now.

**Comment by ctiller** [comment]
Re-merge?

**Comment by vjpai** [comment]
Remerged. Waiting on Travis.

**Comment by vjpai** [comment]
Green!

**Pull request merged**
