### PR TITLE
Add a script to run interop tests against all versions of prod servers.

### PR DESCRIPTION
**Pull request by adelez**
Replacing #5124 to run additional interop tests on an experiment project.

### CODE REVIEW

**Comment by adelez** [comment]
@yang-g

**Comment by adelez** [comment]
Ping?

**Comment by jtattermusch** [comment]
LGTM, but can't merge because of the fixit this week.

**Comment by jtattermusch** [comment]
Please rebase and push, I can't merge without tests being green.

**Comment by adelez** [comment]
Done.

**Pull request merged**
