### PR TITLE
Revert "Revert arena size fix"

### PR DESCRIPTION
**Pull request by AspirinSJL**
Reverts grpc/grpc#15524

Rolling forward after #15536.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++
  +0.0%    +144 [None]                                     +224  +0.0%
  +0.1%     +16 src/core/lib/surface/call.cc                +16  +0.1%
      +2.7%     +10 [Unmapped]                                  +10  +2.7%
      [NEW]      +6 grpc_call_get_initial_size_estimate          +6  [NEW]

  +0.0%    +160 TOTAL                                      +240  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                    atm_cas_per_iteration
-------------------------------------------------------------------------------------------  -----------------------
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/134217728/1/1     -4%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/134217728/1/1  -4%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/134217728/134217728                    -4%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/134217728/134217728                 -4%
```

**Comment by AspirinSJL** [comment]
@jtattermusch Yes, I've did that verification.

**Comment by AspirinSJL** [comment]
Asan C++ (internal CI): #15526
Basic Tests MacOS [opt] (internal CI): #15550
Interop ALTS Tests (internal CI): #15434

**Comment by AspirinSJL** [comment]
Merging again!

**Pull request merged**
