### PR TITLE
F# example

### PR DESCRIPTION
**Pull request by haf**
Tested on macOS 10.12 w/ mono and .net core 2.0.

Wishlist for using gRPC with F#:

 - `fsharp` folder in examples
 - `fsharp` kept up to date with new versions of gRPC
 - F#-native codegen, e.g. with Froto (see referenced issue in Froto)
 - Hopac jobs and Concurrent ML programming style rather than the ogres that are hot/push Tasks aka Futures.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by haf** [comment]
Hey @grpc-jenkins and @grpc-jenkins bots – I got it, thank you!

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by haf** [comment]
Ping

**Comment by jtattermusch** [comment]
@haf   I looks like this PR has slipped through the cracks, sorry about that!  Looking at the PR again,
given that F# support is not something we are actively working on, I think it might make sense to put the F# example to different repository (your own one would be the simplest, or perhaps add under the https://github.com/grpc-ecosystem/ organization. There's also https://github.com/grpc-ecosystem/awesome-grpc repository where we could add a link to the F# example).

Would you be interested in publishing a blog about how to setup gRPC C# with F# projects?

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @haf isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
