### PR TITLE
Fix the namespace detection pattern.

### PR DESCRIPTION
**Pull request by jmuk**
As I tried with protobufjs 6.7.3, message types (Type) also has
'nested' field, but the value is undefined. It should check
this pattern too, otherwise non-namespace ones become an empty
object. That causes the failure of googleapis/gax-nodejs#135

### CODE REVIEW

**Comment by jmuk** [comment]
@murgatroid99 ?

**Comment by murgatroid99** [comment]
I don't think those tests are going to work. The dependency is still on Protobuf.js 5, so I wouldn't expect `protobuf_js_6_common.loadObject(messages_proto)` to work at all.

Also, though I don't object to this change, I would strongly recommend against using the message types that are output there.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jmuk** [comment]
Current package.json file specifies as `'^6.7.0'`, am I missing something?
Anyways, added the logic to skip the test if protobufjs doesn't look like 6.

> I would strongly recommend against using the message types that are output there.
I'm not sure I get this. Here are my understandings, correct me where I'm wrong.

With protobufjs 5.x, `loadObject()` works like:
- if namespace, returns an object with the child nodes
- if service, returns a wrapped class of the service
- if message, returns the message class (by calling `build()`)

My change is doing the same thing in protobufjs 6.x.
The current protobuf_js_6_common.js misunderstands message as namespace because message types also have `nested` property, so it returns an empty object. I think it should return the message class. And it looks like unnecessary to call `build()`, the `value` is already the message class.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
@murgatroid99  this PR seems abandoned. Closing, feel free to revive if still useful.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @jmuk isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
