### PR TITLE
Slice small malloc inline

### PR DESCRIPTION
**Pull request by ncteisen**
Build upon #15302

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                FILE SIZE
 ++++++++++++++ GROWING                                                  ++++++++++++++
  +0.0%    +184 [None]                                                      +592  +0.0%
      +0.0%    +152 [Unmapped]                                                  +592  +0.0%
      +2.9%     +32 [None]                                                         0  [ = ]
  +4.0%    +176 src/core/lib/slice/slice_buffer.cc                          +176  +4.0%
      [NEW]    +176 grpc_slice_buffer_malloc_indexed                            +176  [NEW]

 -------------- SHRINKING                                                --------------
  -0.4%     -32 src/core/ext/transport/chttp2/transport/hpack_encoder.cc     -32  -0.4%
      [DEL]    -109 begin_frame                                                 -109  [DEL]

  +0.0%    +328 TOTAL                                                       +736  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]      -8  -0.0%

  [ = ]       0 TOTAL       -8  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                FILE SIZE
 ++++++++++++++ GROWING                                                  ++++++++++++++
  +0.0%    +184 [None]                                                      +592  +0.0%
      +0.0%    +152 [Unmapped]                                                  +592  +0.0%
      +2.9%     +32 [None]                                                         0  [ = ]
  +4.0%    +176 src/core/lib/slice/slice_buffer.cc                          +176  +4.0%
      [NEW]    +176 grpc_slice_buffer_malloc_indexed                            +176  [NEW]

 -------------- SHRINKING                                                --------------
  -0.4%     -32 src/core/ext/transport/chttp2/transport/hpack_encoder.cc     -32  -0.4%
      [DEL]    -109 begin_frame                                                 -109  [DEL]

  +0.0%    +328 TOTAL                                                       +736  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]      -8  -0.0%

  [ = ]       0 TOTAL       -8  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                  cpu_time    real_time
-------------------------  ----------  -----------
BM_MetadataRefUnrefStatic  +20%        +20%
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                  cpu_time    real_time
-------------------------  ----------  -----------
BM_MetadataRefUnrefStatic  +5%         +5%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                FILE SIZE
 ++++++++++++++ GROWING                                                  ++++++++++++++
  +0.0%    +184 [None]                                                      +584  +0.0%
      +0.0%    +152 [Unmapped]                                                  +584  +0.0%
      +2.9%     +32 [None]                                                         0  [ = ]
  +4.0%    +176 src/core/lib/slice/slice_buffer.cc                          +176  +4.0%
      [NEW]    +176 grpc_slice_buffer_malloc_indexed                            +176  [NEW]

 -------------- SHRINKING                                                --------------
  -0.4%     -32 src/core/ext/transport/chttp2/transport/hpack_encoder.cc     -32  -0.4%
      [DEL]    -109 begin_frame                                                 -109  [DEL]

  +0.0%    +328 TOTAL                                                       +728  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -16  -0.0%

  [ = ]       0 TOTAL      -16  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                              cpu_time    real_time
-------------------------------------  ----------  -----------
BM_HasClearGrpcStatus<ErrorCancelled>  -15%        -15%
```

**Comment by ncteisen** [comment]
No impact

**Pull request closed without merging**
