### PR TITLE
Fixing Linux Portability Build

### PR DESCRIPTION
**Pull request by yashykt**
explicit type conversion for timeout_encoding_test

### CODE REVIEW

**Comment by matt-kwong** [comment]
Please add #12882 to this PR. I don't think Linux portability will pass w/o one of them.

**Comment by yashykt** [comment]
Done

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  [ = ]       0 [None]                                                     +200  +0.0%
  +1.4%     +32 src/core/ext/transport/chttp2/transport/flow_control.cc     +32  +1.4%
      +2.4%     +32 grpc_chttp2_flowctl_get_action                              +32  +2.4%

  +0.0%     +32 TOTAL                                                      +232  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  [ = ]       0 [None]                                                     +200  +0.0%
  +1.4%     +32 src/core/ext/transport/chttp2/transport/flow_control.cc     +32  +1.4%
      +2.4%     +32 grpc_chttp2_flowctl_get_action                              +32  +2.4%

  +0.0%     +32 TOTAL                                                      +232  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  [ = ]       0 [None]                                                     +200  +0.0%
  +1.4%     +32 src/core/ext/transport/chttp2/transport/flow_control.cc     +32  +1.4%
      +2.4%     +32 grpc_chttp2_flowctl_get_action                              +32  +2.4%

  +0.0%     +32 TOTAL                                                      +232  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by matt-kwong** [comment]
There's a bit of a queue for Kokoro since there were a lot of active PRs today, you can test this locally with `./tools/run_tests/run_tests_matrix.py --build_only -f c uv linux`

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  [ = ]       0 [None]                                                     +200  +0.0%
  +1.4%     +32 src/core/ext/transport/chttp2/transport/flow_control.cc     +32  +1.4%
      +2.4%     +32 grpc_chttp2_flowctl_get_action                              +32  +2.4%

  +0.0%     +32 TOTAL                                                      +232  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  [ = ]       0 [None]                                                     +200  +0.0%
  +1.4%     +32 src/core/ext/transport/chttp2/transport/flow_control.cc     +32  +1.4%
      +2.4%     +32 grpc_chttp2_flowctl_get_action                              +32  +2.4%

  +0.0%     +32 TOTAL                                                      +232  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  [ = ]       0 [None]                                                     +200  +0.0%
  +1.4%     +32 src/core/ext/transport/chttp2/transport/flow_control.cc     +32  +1.4%
      +2.4%     +32 grpc_chttp2_flowctl_get_action                              +32  +2.4%

  +0.0%     +32 TOTAL                                                      +232  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.old: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.old: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.new: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.old: 1


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  [ = ]       0 [None]                                                     +200  +0.0%
  +1.4%     +32 src/core/ext/transport/chttp2/transport/flow_control.cc     +32  +1.4%
      +2.4%     +32 grpc_chttp2_flowctl_get_action                              +32  +2.4%

  +0.0%     +32 TOTAL                                                      +232  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  [ = ]       0 [None]                                                     +200  +0.0%
  +1.4%     +32 src/core/ext/transport/chttp2/transport/flow_control.cc     +32  +1.4%
      +2.4%     +32 grpc_chttp2_flowctl_get_action                              +32  +2.4%

  +0.0%     +32 TOTAL                                                      +232  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by yashykt** [comment]
Linux Portability passes

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.new: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_2_0.opt.old: 1


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Pull request merged**
