### PR TITLE
Revert "Revert "Cleanup run docker machinery in run_tests.py, task_runner.py and elsewhere (#28704)" (#28741)"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reintroduce #28704.

(fedora34 seems to have no "find" command? `/var/local/jenkins/grpc/tools/run_tests/dockerize/docker_run.sh: line 54: find: command not found`)

### CODE REVIEW

**Comment by jtattermusch** [comment]
Adhoc run of full python distribtests: 
https://fusion2.corp.google.com/invocations/6cc87bb8-eaf7-48fc-86a0-f526b9540fbc/log

**Review by lidizheng — APPROVED** [review]
The ad-hoc run passed. LGTM.

**Comment by nicolasnoble** [comment]
This seems to have broken a few jobs on the test fusion dashboard...

**Comment by jtattermusch** [comment]
> This seems to have broken a few jobs on the test fusion dashboard...

Which ones?

**Pull request merged**
