### PR TITLE
Node interop custom_metadata

### PR DESCRIPTION
**Pull request by murgatroid99**
This adds the custom_metadata interop test and corresponding server functionality to Node. This is **not** a beta requirement. The primary purpose is to provide something to test the Objective C client's metadata handling against. This should only be merged after #3012.

### CODE REVIEW

**Comment by tbetbetbe** [comment]
can you resolve this branch and re-push to remove commits that already submitted

**Comment by murgatroid99** [comment]
Can we merge this now?

**Comment by jtattermusch** [comment]
```
 Interop tests should pass custom_metadata:
     Uncaught Error: keys that end with '-bin' must have Buffer values
      at validate (/var/local/git/grpc/src/node/src/metadata.js:62:13)
      at Metadata.set (/var/local/git/grpc/src/node/src/metadata.js:85:3)
      at getEchoTrailer (/var/local/git/grpc/src/node/interop/interop_server.js:79:22)
      at Object.handleUnary [as unaryCall] (/var/local/git/grpc/src/node/interop/interop_server.js:112:12)
      at Object.wrapper [as func] (/var/local/git/grpc/src/node/node_modules/lodash/index.js:3095:19)
      at /var/local/git/grpc/src/node/src/server.js:478:13

  2) Other conditions Call propagation Cancellation With a server stream call:
     Error: timeout of 8000ms exceeded
      at null.<anonymous> (/var/local/git/grpc/src/node/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by murgatroid99** [comment]
OK, I fixed that problem.

**Pull request merged**
