### PR TITLE
V1.6.x

### PR DESCRIPTION
**Pull request by c252496**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @vosst isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* User @andremedeiros isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* User @apolcyn isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* User @kpayson64 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* User @muxi isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @vosst isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* User @andremedeiros isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @vosst isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* User @andremedeiros isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by andremedeiros** [comment]
Signed the CLA.

**Pull request closed without merging**
