### PR TITLE
Remove duplicate check for shutting_down

### PR DESCRIPTION
**Pull request by AspirinSJL**
Already checked at line 1826.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]      -8  -0.0%

  [ = ]       0 TOTAL       -8  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
- Asan C++ (internal CI): #13443
Basic Tests C++ Linux [dbg] (internal CI): #13477

**Pull request merged**
