### PR TITLE
Server creds auth md processor

### PR DESCRIPTION
**Pull request by jboeuf**
Plug-in server-side auth metadata processing.
This is PR supersedes #2492 as it has a better API.

### CODE REVIEW

**Comment by ctiller** [comment]
Can we find 30 minutes today to convince me that the API's the right one?

**Comment by jboeuf** [comment]
Sure. I'm open to suggestions as well.

On Wednesday, August 5, 2015, Craig Tiller <notifications@github.com> wrote:

> Can we find 30 minutes today to convince me that the API's the right one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc/pull/2777#issuecomment-128046424>.
>


-- 
Julien.

**Comment by ctiller** [comment]
I'm waiting for an update, right?

**Comment by jboeuf** [comment]
Correct. This afternoon. Thanks much.

**Comment by jboeuf** [comment]
Fixed. PTAL.

**Comment by jboeuf** [comment]
Jenkins is greenish...

**Pull request merged**
