### PR TITLE
Changed census static metadata keys for tracing and tag propagation

### PR DESCRIPTION
**Pull request by dgquintas**
On behalf of @bogdandrutu

### CODE REVIEW

**Comment by pgrosu** [comment]
Unless I'm mistaken, isn't @bogdandrutu also doing a similar thing via #6877?

**Comment by dgquintas** [comment]
Apparently. I did this with @bogdandrutu right by my side (ie, on his behalf), so I'll let him comment on the duplication.

**Comment by bogdandrutu** [comment]
I marked that as a DO NOT SUBMIT and throw it away.

**Comment by pgrosu** [comment]
Well that simplifies things :)  Thanks Bogdan and David.

**Pull request merged**
