### PR TITLE
Cleaned up installation/test requirement fetching

### PR DESCRIPTION
**Pull request by makdharma**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Not ready to merge at all. All the tests are failing and no LGTM.

**Comment by soltanmm** [comment]
@jtattermusch I was under the impression that one was supposed to pass that onto a committee decision due to the nature of the failures (known, unrelated flakes) and that my attachment of the label was my acknowledgment?

In any case, I rebooted the tests, and: LGTM.

Remaining basic test failures are unrelated (e.g. #5509). Feel free to remove the label again if the consensus is that we're blocking on unrelated flakes.

**Comment by jtattermusch** [comment]
qps_test failure is a known flake and  CLA is fine as @makdharma  is a googler.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
