### PR TITLE
Fix #12114 missing TSRMLS for zts BUILD

### LINKED ISSUE #12114: [PHP 5.x / ZTS] failed build
```
/usr/include/php-zts/php/Zend/../TSRM/TSRM.h:164:57: error: 'tsrm_ls' undeclared (first use in this function)
 #define TSRMG(id, type, element) (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                         ^
/usr/include/php-zts/php/Zend/zend_hash.h:110:28: note: in definition of macro 'zend_hash_update'
   _zend_hash_add_or_update(ht, arKey, nKeyLength, pData, nDataSize, pDest, HASH_UPDATE ZEND_FILE_LINE_CC)
                            ^~
/builddir/build/BUILD/php-pecl-grpc-1.4.3/ZTS/src/php/ext/grpc/channel.c:188:3: note: in expansion of macro 'PHP_GRPC_PERSISTENT_LIST_UPDATE'
   PHP_GRPC_PERSISTENT_LIST_UPDATE(&EG(persistent_list), key, key_len,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/php-zts/php/Zend/zend_globals_macros.h:45:16: note: in expansion of macro 'TSRMG'
 # define EG(v) TSRMG(executor_globals_id, zend_executor_globals *, v)
                ^~~~~
/builddir/build/BUILD/php-pecl-grpc-1.4.3/ZTS/src/php/ext/grpc/channel.c:188:36: note: in expansion of macro 'EG'
   PHP_GRPC_PERSISTENT_LIST_UPDATE(&EG(persistent_list), key, key_len,
                                    ^~
/usr/include/php-zts/php/Zend/../TSRM/TSRM.h:164:57: note: each undeclared identifier is reported only once for each function it appears in
 #define TSRMG(id, type, element) (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                         ^
/usr/include/php-zts/php/Zend/zend_hash.h:110:28: note: in definition of macro 'zend_hash_update'
   _zend_hash_add_or_update(ht, arKey, nKeyLength, pData, nDataSize, pDest, HASH_UPDATE ZEND_FILE_LINE_CC)
                            ^~
/builddir/build/BUILD/php-pecl-grpc-1.4.3/ZTS/src/php/ext/grpc/channel.c:188:3: note: in expansion of macro 'PHP_GRPC_PERSISTENT_LIST_UPDATE'
   PHP_GRPC_PERSISTENT_LIST_UPDATE(&EG(persistent_list), key, key_len,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/php-zts/php/Zend/zend_globals_macros.h:45:16: note: in expansion of macro 'TSRMG'
 # define EG(v) TSRMG(executor_globals_id, zend_executor_globals *, v)
                ^~~~~
/builddir/build/BUILD/php-pecl-grpc-1.4.3/ZTS/src/php/ext/grpc/channel.c:188:36: note: in expansion of macro 'EG'
   PHP_GRPC_PERSISTENT_LIST_UPDATE(&EG(persistent_list), key, key_len,
                                    ^~
/builddir/build/BUILD/php-pecl-grpc-1.4.3/ZTS/src/php/ext/grpc/channel.c: At top level:
cc1: error: unrecognized command line option '-Wno-parentheses-equality' [-Werror]
cc1: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by remicollet**
see bug #12114

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by remicollet** [comment]
Sorry, but I don't remember about your CLA, don't care about it, this is a trivial fix. so merge this of fix it yourself.

**Comment by remicollet** [comment]
BTW pr #12108 also includes this fix.

**Pull request closed without merging**
