### PR TITLE
Mark pre-generated Visual Studio projects as deprecated, recommend cmake

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by jtattermusch** [comment]
What are the use cases where VS projects generated by cmake are not
sufficient? They are the same in almost all respects, except they are
correct in terms of including dependencies.

**Comment by varshanbp** [comment]
@jtattermusch  Let VS Projects also be there. There won't be any problem if VS projects are there. There is no benefits of deprecation.

**Comment by jtattermusch** [comment]
@varshanbp, the benefits of deprecation (unless there's a compelling reason for keeping them, and you haven't provided one):
- Maintaining another build solution costs time and effort (a nontrivial amount of it). We'd much invest our time into making one build solution great rather than supporting two build systems that "kind of" work.
- Visual Studio projects need to be continuously tested. Such testing solution needs to be maintained and it also costs resources to run those tests.
- Giving people the choice to use pre-generated VS projects might actually be harmful to them. As described in the PR, the pregen VS projects have limitations and are known to be partially broken and incomplete.

**Comment by jtattermusch** [comment]
Docs only change, merging.

**Pull request merged**
