### PR TITLE
PHP: windows config.w32 file

### PR DESCRIPTION
**Pull request by stanley-cheung**
Introduce the `config.w32` file so that PECL can build the gRPC PHP package on Windows.

~~Currently there is some compilation error when trying to compile this on Windows.~~

### CODE REVIEW

**Comment by rcoenen** [comment]
Is this still being worked on?

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by stanley-cheung** [comment]
I have managed to compile the gRPC PHP extension on Windows using the current state of the `config.w32` file in this PR. There are still lots of work to be done but I believe this is a big step towards providing Windows support for gRPC PHP.

**Comment by rcoenen** [comment]
Nice work!

**Comment by stanley-cheung** [comment]
@murgatroid99 @jtattermusch This is ready for review. 

So as it stands, this PR will only add a `config.w32` file to the repo. I haven't got a chance to add any testing yet - that will come at a subsequent PR. 

The reason I want to merge this in first, is to have a dry-run of the release process. With the `config.w32` file in the repo, PECL will attempt to build the .dll when I upload a release. I want to see how / if things go wrong in that process. Can't do that without this file being in the package.

This PR does not mean that we have Windows support for PHP officially yet, but a big step.

**Comment by stanley-cheung** [comment]
Mac failure is #11116 
Windows failure is #11216

**Pull request merged**
