### PR TITLE
Reintroduce a lambda capture as part of C++11-izing code

### PR DESCRIPTION
**Pull request by vjpai**
This is a partial undo of #2428 . In particular, this brings back a lambda capture and removes an internal namespace that was being used. This may also actually improve performance since newer stdlibc++ no longer require an additional allocation for small capture sizes (such as this, which only captures a pointer).

### CODE REVIEW

**Comment by vjpai** [comment]
Moral question: is this an API breakage? I believe the answer is technically yes (since this was actually a public class, not just an internal class, to deal with limitations in certain old compilers), but in practice this is not a breakage since there is not a reference to this class in any existing code guide, and it is hard to conceive of a situation where anyone would actually use this class. So I'm going to leave off the API breakage tag.

**Comment by yang-g** [comment]
I think this is ok.

**Comment by vjpai** [comment]
Rebased master to avoid a test breakage; diff is still the same

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by vjpai** [comment]
Rebasing master, diff unchanged

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by vjpai** [comment]
Test failures: infrastructural on interop and mac

**Pull request merged**
