### PR TITLE
V1.16.x fix logging

### PR DESCRIPTION
**Pull request by gnossen**
Cherry pick https://github.com/grpc/grpc/pull/17064 onto the `v1.16.x` branch in anticipation of cutting a patch.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,967,222      Total (=)      1,967,222

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,889,383      Total (<)     10,889,391

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,967,222      Total (=)      1,967,222

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,889,392      Total (>)     10,889,389

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by gnossen** [comment]
Looks like the objective C tests failed [due to a config file that is not present on this branch](https://sponge.corp.google.com/target?id=8fdf0fe8-22ea-4634-8e3d-7bd02a5e6e18&target=grpc/core/pull_request/macos/grpc_basictests_objc_dbg&searchFor):

```
com.google.devtools.kokoro.config.ConfigException: Build config /tmp/workspace/workspace/grpc/core/pull_request/macos/grpc_basictests_objc_dbg/src/github/grpc/tools/internal_ci/macos/pull_request/grpc_basictests_objc_dbg.cfg does not exist
```

I conferred with @srini100 and we agreed to ignore these failures for now as they should only affect objective C releases. Any further `1.16` releases of objective C will have to address this issue.

**Comment by gnossen** [comment]
Looks like we hit a transient error:

```
W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/Release.gpg  Unable to connect to ftp.debian.org:http:
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,967,222      Total (=)      1,967,222

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,889,384      Total (=)     10,889,384

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by gnossen** [comment]
```
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/objective-c/tests/InteropTests.m:416: error: -[InteropTestsLocalCleartext testCancelAfterBeginRPC] : ((call.state) equal to (GRXWriterStateFinished)) failed: ("1") is not equal to ("3")
```

Looks like we hit https://github.com/grpc/grpc/issues/16497 again.

**Pull request merged**
