### PR TITLE
Fixing make_grpcio_tools.py

### PR DESCRIPTION
**Pull request by jtattermusch**
- make_grpcio_tools.py currently doesn't work if it falls back to using bazel from a dockerimage (= if bazel is not installed locally). See https://github.com/grpc/grpc/pull/15492#issuecomment-390758571.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
This was progress towards https://github.com/grpc/grpc/issues/14862

**Pull request merged**
