### PR TITLE
Remove ChannelInterface and replace it with Channel

### LINKED ISSUE #2824: Clean up channel interface in C++
- delete ChannelInterface, expose only Channel - a concrete class
- make RegisterMethod, CreateCall and PerformOpsOnCall implementation private and accessible only to stubs

### PR DESCRIPTION
**Pull request by yang-g**
Fixes #2824.

### CODE REVIEW

**Comment by yang-g** [comment]
Should the Channel ctor be hidden in private as well?

**Comment by ctiller** [comment]
It probably should be private.

It'd be worth spending a little time figuring if we can make RegisterMethod private also, since this is strictly implementation detail.

**Comment by yang-g** [comment]
Done. PTAL

**Comment by yang-g** [comment]
Fixes #2824.

**Comment by ctiller** [comment]
LGTM on condition of mergability and good enough tests.

Switching to @dgquintas to pull the trigger once he's ready for this.

**Comment by dgquintas** [comment]
Ready as of 11:44am today. Merge is a go once mergeable.

**Comment by dgquintas** [comment]
Waiting for Jenkins now.

**Comment by yang-g** [comment]
Seems green enough.

**Pull request merged**
