### PR TITLE
Remove expected results in server interceptor test

### PR DESCRIPTION
**Pull request by vjpai**
Potential stopgap test change. Will also try to prepare an alternative fix.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by vjpai** [comment]
Better fix coming.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,388      Total (=)      2,019,388

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,185      Total (<)     11,154,189

 No significant differences in binary sizes


```

**Pull request closed without merging**
