### PR TITLE
Remove private headers from "source_files" in gRPC-Core.podspec

### PR DESCRIPTION
**Pull request by MrMage**
As it turns out, CocoaPods copies the headers listed in "source_files" verbatim into the output framework. This is undesirable for two reasons:

1. Only public headers should be shipped with the framework; private ones should be discarded.
2. The 'header_mappings_dir' trickery in the Podspec has the effect of copying the headers mentioned above straight into the "Versions" directory of the framework. In that directory, essentially only a directory called "A" is expected, with headers in "A/Headers". The presence of other files in that directory leads to invalid code signatures; see https://github.com/jmcnamara/libxlsxwriter/pull/94 for more information.

### CODE REVIEW

**Comment by MrMage** [comment]
CCing @muxi @jcanizales, who should be qualified to review this. Feedback is much appreciated — I'm not 100% sure that this has no unintended side effects.

Also note that I have not done the same process for the other podspecs (e.g. for `gRPC-C++`), as those templates appeared to be more complex.

**Comment by muxi** [comment]
Will need some sort of verification other than CI for this. I'll do it manually.

**Comment by muxi** [comment]
Actually I think these header files need to be at least referenced somewhere (maybe [private_header_files](https://guides.cocoapods.org/syntax/podspec.html#private_header_files)?). Otherwise they are before builds and the compiler will complain. That seems to be what the CI error is about.

**Comment by MrMage** [comment]
Hmm, I’ll see if moving these headers to `private_header_files` instead works then 😊

**Comment by MrMage** [comment]
Please take another look — I hope that all files (including private headers) are now in the expected lists.

**Comment by muxi** [comment]
Sorry for late reply; was OOO for a few days.

In this commit, the style seems to be working with gRPC-Core, but failing with BoringSSL. BoringSSL has the inclusion style of `#include "../internal.h"`, which is only possible when these headers are also present in source files (see https://github.com/CocoaPods/CocoaPods/issues/1259) when built as static library.

**Comment by muxi** [comment]
Sorry about the delay. I can take a look at this. But I need a bit help understanding the issue. For 1) in your first post, I tried to build the pod `gRPC-Core` as framework (with the HelloWorld example in `example/objective-c/helloworld`) and I found no private header in the generated framework ([screenshot](https://drive.google.com/open?id=1ssXyNsEnfNP1OvcNbaaroFaR_BOBcyAL)). For 2), I was a bit confused about what is `A` and what is `Versions` directory. I do not see a `Versions` directory in the framework or any directory called `A`. Do you have any sample project that has that code signature failure?

**Comment by MrMage** [comment]
Thanks for getting back on this! The screenshot looks like an iOS framework to me. macOS frameworks have a different structure; only they are affected.

**Comment by muxi** [comment]
Ahh that is the reason. I have not tried a macOS framework before (since grpc not officially supporting it). Let me try that.

**Comment by muxi** [comment]
You are right. When I build it as macos framework, I do see the private headers in the framework. I agree that it will be good to remove private headers from the framework, but if that breaks something I am fine with leaving them too.

On the other hand I am more worried about the second issue. I tried that myself but I was not able to reproduce (maybe I messed up signing since I haven't done that on mac projects...). I would really like to avoid duplicating the pod into static/dynamic. Is there any reason Cocoapods copies the `src` directory to the framework? If only directory `A` is supposed to be there, that sounds like a bug to be.

**Comment by MrMage** [comment]
I've filed https://github.com/CocoaPods/CocoaPods/issues/7788 for this now.

**Comment by vjpai** [comment]
Hi there, is this still relevant?

**Comment by MrMage** [comment]
This is still affecting me, but I do have a private workaround (deleting the headers in a later build step) for now.

**Pull request closed without merging**
