### PR TITLE
Fix Python protoc plugin test workflow

### PR DESCRIPTION
**Pull request by soltanmm**
@nathanielmanistaatgoogle Please review (and merge? I might want to split the commits apart and even split the first commit into two).

### CODE REVIEW

**Comment by soltanmm** [comment]
That's certainly what I'd like to do (sooner rather than later). I just want to see the protoc plugin test run on Travis successfully for now.

**Comment by nathanielmanistaatgoogle** [comment]
LGTM. Bump this comment thread when you've decided in what way you want to split the commits.

**Comment by soltanmm** [comment]
Actually, on further thought, I think the commit history on this one is fine.

**Comment by soltanmm** [comment]
cc #866

**Pull request merged**
