### PR TITLE
Update docker files to use clang 3.9

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by dgquintas** [comment]
It seems to have worked. At least tests are running and it can be seen that it downloads the release39 branch of clang.

**Comment by dgquintas** [comment]
I think https://grpc-testing.appspot.com/job/gRPC_pull_requests_asan_cpp/497/consoleText shows that the new version is being checked out and compiled.

**Comment by nicolasnoble** [comment]
We might actually try to use https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile instead (oss-fuzz/base-builder). That'd save us a lot of trouble.

**Comment by dgquintas** [comment]
@matt-kwong you have a better/different PR taking care of this right? Can I drop this one?

**Comment by matt-kwong** [comment]
Yeah, you can drop this PR. We're looking at the possibility of replacing our Jenkins fuzzer tests with google/oss-fuzz.

**Pull request closed without merging**
