### PR TITLE
Add mako to multilang dockerimage

### PR DESCRIPTION
**Pull request by jtattermusch**
to fix node build in coverage suite

https://source.cloud.google.com/results/invocations/707c0572-1a9c-495e-aabe-81a92504fd21/targets/github%2Fgrpc/tests

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
@matt-kwong  we reverted the PR requiring gsutil, so why would we need to add `gsutil` to the image?

If that's fine, let's merge this PR to get things fixed and address the rest as followup.

**Pull request merged**
