### PR TITLE
Yapf tools/

### PR DESCRIPTION
**Pull request by ncteisen**
Fixes: #11437

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
One note -  if we really want the code to stay yapf compliant, we would need to enforce the format with a sanity test - but it's fine to to the initial formatting now and introduce followup changes later.  The PR is fine as is.

**Comment by ncteisen** [comment]
C++: #9462 
Tsan: #13178 
MacOS: infra

**Comment by ncteisen** [comment]
@jtattermusch, we actually do sanity this. All the checking happens in [this](https://github.com/grpc/grpc/blob/master/tools/distrib/yapf_code.sh#L51) code block if the TEST env var is set. And run_tests sets this [here](https://github.com/grpc/grpc/blob/master/tools/run_tests/run_tests.py#L989)

**Pull request merged**
