### PR TITLE
enable_ssl to use_tls

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by yang-g** [comment]
Fixes #3357

**Comment by jtattermusch** [comment]
interop tests are unhappy:

START: build
WAITING: 1 jobs running, 0 complete, 0 failed
PASSED: build [time=917.0sec]
START: large_unary
START: empty_unary
START: ping_pong
START: client_streaming
START: server_streaming
WAITING: 5 jobs running, 0 complete, 0 failed
ERROR: unknown command line flag 'use_tls'

**Comment by jtattermusch** [comment]
I imagine it might be picking up some old docker image at some point, which is why we are working on revamping the interop tests.

**Comment by jcanizales** [comment]
Please update https://github.com/grpc/grpc/blob/master/src/objective-c/tests/run_tests.sh#L40 too.

**Comment by jtattermusch** [comment]
Now that #3373  has been merged, can you pls try to rebase -i upstream/master and update the run_interop_tests.py script accordingly? After that the unknown command line flag problem should be gone.

**Comment by jtattermusch** [comment]
Btw, the spec explicitly requires supporting --use_tls=true (and not just --use_tls), does that work for C++?

**Comment by yang-g** [comment]
Tests seems to pass locally.

**Pull request merged**
