### PR TITLE
Fix alarm test flake on windows

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/13693.
It looks like that shutting down cq on the same thread doesn't guarantee to return shutdown event immediatelly if deadline is infinite future, but overall I didn't notice anything that would really be broken (passing inf_past seems like a rather exotic case).

I was able to reproduce initially (0.3% approx) and with this change I didn't get a single failure in >5000 runs.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by ctiller** [comment]
I'd rather fix the test here: inf_past is the only way we have to reliably
indicate a polling next.

If this is truly the right thing to do then a description of why we
shouldn't test polling next along with an amended title (since this is not
a fix but a test definition change).

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
@ctiller, ok, I'll try to investigate further.

One of the reasons why I thought it's fine to make this change is that it's a change of the test cleanup procedure rather than the actual test body (and I didn't see a reason why the test cleanup should insist on polling behavior for cq_next()).

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
An analysis of what's happening in the test is here: https://github.com/grpc/grpc/issues/13693#issuecomment-357746436

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by jtattermusch** [comment]
I added a comment why changing the deadline is the right thing to do (after consulting the problem with @sreecha). I didn't change the test title because this only updates the shutdown procedure after the actual tests have successfully finished. 
PTAL.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
