### PR TITLE
Use WorkSerializer in XdsClient to propagate updates in a synchronized manner

### PR DESCRIPTION
**Pull request by yashykt**
XdsClient watcher notifications callbacks are currently invoked inline while still holding onto the XdsClient mutex. These callbacks often require to invoke an API on `XdsClient`. To do this in a way that avoids deadlocks, the callbacks schedule themselves on ExecCtx. The issue with this is that the callbacks can be pushed on `ExecCtx`s of different threads which can mess up the ordering of these notifications.

Using `WorkSerializer::Schedule` and `WorkSerializer::DrainQueue`, we always invoke the callbacks outside the `XdsClient::mu_` so that the callbacks do not need to delay the callbacks. We additionally get the advantage of being able to execute code outside the critical region which should be a performance win (though it's probably not so critical).

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/27975)

### CODE REVIEW

**Comment by yashykt** [comment]
Mark is OOO, so adding @donnadionne for review. I probably won't merge this till I get Mark's eyes on this but it'll be good to have an additional set of eyes.

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks good overall!  Comments are mostly optimizations, particularly around not taking unnecessary refs or making unnecessary copies.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27975#-:-Mo9kuSg8QSD2I-DkTHO:b-xjcfdc)* status: all files reviewed, 15 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 75 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9fNVc-3OlxoioUedf:-Mo9fNVc-3OlxoioUedg:b7kdq1a) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L75)):*
> ```cpp
> 
>     void OnClusterChanged(XdsApi::CdsUpdate cluster_data) override {
>       RefCountedPtr<CdsLb> cds_lb = parent_;
> ```

This can be a const reference, since we don't need to take a new ref here.  The new ref will happen with the copy for the lambda capture.

Actually, since the watcher itself is now ref-counted, we can avoid copying `name_` if we take a ref to the watcher instead of taking a ref to the CDS LB policy:

```
Ref().release();  // Ref held by callback.
parent_->work_serializer()->Run(
    // TODO(roth): When we move to C++14, capture cluster_data with std::move().
    [this, cluster_data]() mutable {
      parent_->OnClusterChanged(name_, std::move(cluster_data));
      Unref();
    },
    DEBUG_LOCATION);
```

Same for all three callbacks.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 78 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9i25P0B9PVQeh2maK:-Mo9i25P0B9PVQeh2maL:b-il96ch) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L78)):*
> ```cpp
>       std::string name = name_;
>       parent_->work_serializer()->Run(
>           [cds_lb, name, cluster_data]() mutable {
> ```

Please add a TODO about capturing `cluster_data` via `std::move()` once we can use C++14.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 148 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9iTel-VjYXtLeocK0:-Mo9gn2hB0Cwdy42gSXj:b-7i2ktj) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L148)):*
> ```cpp
>     }
> 
>     // parent() and index() could have been protected methods but a bug in msvc
> ```

If possible, I'd prefer to keep these methods `protected` and use `friend` statements to work around this bug, like we were doing before.  If MSVC doesn't understand the lambdas, then maybe we can move the code from the lambdas to private methods of `EndpointWatcher`.  For example:

```
class EndpointWatcher : public XdsClient::EndpointWatcherInterface {
 public:
  void OnEndpointChanged(XdsApi::EdsUpdate update) override {
    Ref().release();  // Ref held by callback.
    discovery_mechanism_->parent()->work_serializer()->Run(
        [this, update]() mutable {
          OnEndpointChangedHelper(std::move(update));
          Unref();
        },
        DEBUG_LOCATION);
  }

 private:
  // Code accessing protected methods of `DiscoveryMechanism` need to be
  // in methods of this class rather than in lambdas to work around an MSVC bug.
  void OnEndpointChangedHelper(XdsApi::EdsUpdate update) {
    discovery_mechanism_->parent()->OnEndpointChanged(
        discovery_mechanism_->index(), std::move(update));
  }
};
```
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 181 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9h43L5jJ3Vsavh_By:-Mo9h43M9i0OkNST5kLf:bh9tvo0) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L181)):*
> ```cpp
>       }
>       void OnEndpointChanged(XdsApi::EdsUpdate update) override {
>         RefCountedPtr<EdsDiscoveryMechanism> discovery_mechanism =
> ```

This can be a const reference, so that we don't take an unnecessary ref.  We are already taking a ref in the lambda capture.

Same thing for all three callbacks.

(This becomes irrelevant if you take my suggestion above about taking a new ref to the watcher instead of taking a ref to the discovery mechanism to avoid the MSVC bug.)
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 184 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9hfsy94BblugCe-9a:-Mo9hfsy94BblugCe-9b:b-ipqrs7) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L184)):*
> ```cpp
>             discovery_mechanism_;
>         discovery_mechanism->parent()->work_serializer()->Run(
>             [discovery_mechanism, update]() mutable {
> ```

Please add a TODO about capturing `update` via `std::move()` once we can use C++14.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 899 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9j8dc3nasXzd52UJt:-Mo9j8dc3nasXzd52UJu:bnkghmz) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L899)):*
> ```cpp
> void XdsResolver::NotifyLdsUpdate(XdsApi::LdsUpdate update,
>                                   const DebugLocation& location) {
>   RefCountedPtr<XdsResolver> resolver = Ref();
> ```

This is taking two refs, one here and another in the lambda capture, but we only need one.

I think it makes sense to keep this code in the watcher implementations rather than moving it into these helper functions, because then we can avoid the extra ref by taking the same approach as elsewhere (i.e., take a ref to the watcher), or we can declare a const reference to the existing `RefCountedPtr<XdsResolver>` data member.

Same thing for all three callbacks.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 901 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9khSN4FhRFBBfKuZK:-Mo9khSN4FhRFBBfKuZL:b-mf3o6v) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L901)):*
> ```cpp
>   RefCountedPtr<XdsResolver> resolver = Ref();
>   work_serializer_->Run(
>       [resolver, update]() mutable {
> ```

Please add a TODO about using `std::move()` to capture `update` when we move to C++14.

Same for the RDS update.
___
*[src/core/ext/xds/xds_client.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9YiOh0h61aMIxllQo:-Mo9YiOi2X2lNKZ2NEsM:bbri6bp) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.h#L49)):*
> ```objc
>   class ListenerWatcherInterface : public RefCounted<ListenerWatcherInterface> {
>    public:
>     // TODO(review_note): Tried adding ABSL_EXCLUSIVE_LOCKS_REQUIRED but that
> ```

What was the error you got when trying this?

Note that when using lock annotations with a `WorkSerializer`, you need to add `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` annotations to the lambdas that you run in the `WorkSerializer`.  You can see how we did this in the client channel code in #25983.
___
*[src/core/ext/xds/xds_client.cc, line 183 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9_7Xh4rVc3yWfjdOV:-Mo9_7Xh4rVc3yWfjdOW:b2wwr9p) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L183)):*
> ```cpp
>   class ResourceState : public InternallyRefCounted<ResourceState> {
>    public:
>     // TODO(): Check if passing XdsClient as a raw ptr is safe
> ```

I don't think we need to pass this in at all.  Instead, you can change `OnTimer()` to access it via `self->ads_calld_->xds_client()`.
___
*[src/core/ext/xds/xds_client.cc, line 226 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9ZeUs6CXYq1u28JOb:-Mo9ZeUs6CXYq1u28JOc:byk4du3) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L226)):*
> ```cpp
>         self->OnTimerLocked(GRPC_ERROR_REF(error));
>       }
>       // TODO(): Can we avoid draining the queue on a timer thread?
> ```

I think this is fine.  We were already doing this work in the timer thread before this change.
___
*[src/core/ext/xds/xds_client.cc, line 2162 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9bfbD22SoqoveV-Zx:-Mo9bfbD22SoqoveV-Zy:bcb4xfw) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2162)):*
> ```cpp
>         "Unable to parse resource name for listener %s", listener_name));
>     work_serializer_.Run(
>         [watcher, error]() {
> ```

Please add a TODO that once we can use C++14, we can capture `watcher` using `std::move()`.

Same thing for all resource types.
___
*[src/core/ext/xds/xds_client.cc, line 2163 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9aPsfArW3G8gMDtwa:-Mo9aPsfArW3G8gMDtwb:b-fpgliw) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2163)):*
> ```cpp
>     work_serializer_.Run(
>         [watcher, error]() {
>           // review_note: this should fix a leak
> ```

Good catch!

Please remove these `review_note:` comments before merging.
___
*[src/core/ext/xds/xds_client.cc, line 2184 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9c8nv-3piWUcjmFLY:-Mo9c8nv-3piWUcjmFLZ:bhy47nc) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2184)):*
> ```cpp
>       auto& value = listener_state.update.value();
>       work_serializer_.Schedule(
>           [watcher, value]() { watcher->OnListenerChanged(value); },
> ```

Same C++14 TODO here.

Same thing for all resource types.
___
*[src/core/ext/xds/xds_client.cc, line 2589 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9clPG4vQp3K94lccz:-Mo9clPG4vQp3K94lcd-:bb8tr4e) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2589)):*
> ```cpp
>   // being captured by value
>   work_serializer_.Schedule(
>       [authority_state_map, error]() ABSL_NO_THREAD_SAFETY_ANALYSIS {
> ```

I don't think we want to capture the whole authority_state_map here, since that includes a lot of data we don't actually need.  It will take an unnecessary ref to the `ChannelState` object, and it will unnecessarily copy all of the cached resource data.

Instead, I suggest something like this:

```
std::set<RefCountedPtr<ListenerWatcher>> listener_watchers;
std::set<RefCountedPtr<RouteConfigWatcher>> route_config_watchers;
std::set<RefCountedPtr<ClusterWatcher>> cluster_watchers;
std::set<RefCountedPtr<EndpointWatcher>> endpoint_watchers;
for (const auto& a : authority_state_map_) {
  for (const auto& p : a.second.listener_map) {
    const ListenerState& listener_state = p.second;
    for (const auto& q : listener_state.watchers) {
      listener_watchers.insert(q.second);
    }
  }
  // ...same for other resource types...
}
work_serializer_.Schedule(
    [listener_watchers, route_config_watchers, cluster_watchers, endpoint_watchers, error]()
        ABSL_EXCLUSIVE_LOCKS_REQUIRED(&work_serializer_) {
      for (const auto& watcher : listener_watchers) {
        watcher->OnError(GRPC_ERROR_REF(error);
      }
      // ...same for other resource types...
      GRPC_ERROR_UNREF(error);
    },
    DEBUG_LOCATION);
```
___
*[src/core/ext/xds/xds_client.cc, line 2589 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9d6C24fh_pTyRDMeb:-Mo9d6C24fh_pTyRDMec:bgk35tj) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2589)):*
> ```cpp
>   // being captured by value
>   work_serializer_.Schedule(
>       [authority_state_map, error]() ABSL_NO_THREAD_SAFETY_ANALYSIS {
> ```

This should use `ABSL_EXCLUSIVE_LOCKS_REQUIRED(&work_serializer_)` instead of `ABSL_NO_THREAD_SAFETY_ANALYSIS`.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27975)* status: 1 of 6 files reviewed, 15 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 75 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9fNVc-3OlxoioUedf:-MoAY__A6G1ufJHdIzq-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L75)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be a const reference, since we don't need to take a new ref here.  The new ref will happen with the copy for the lambda capture.

Actually, since the watcher itself is now ref-counted, we can avoid copying `name_` if we take a ref to the watcher instead of taking a ref to the CDS LB policy:

```
Ref().release();  // Ref held by callback.
parent_->work_serializer()->Run(
    // TODO(roth): When we move to C++14, capture cluster_data with std::move().
    [this, cluster_data]() mutable {
      parent_->OnClusterChanged(name_, std::move(cluster_data));
      Unref();
    },
    DEBUG_LOCATION);
```

Same for all three callbacks.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/cds.cc, line 78 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9i25P0B9PVQeh2maK:-MoAYa5AAY5qdwo0DNmi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/cds.cc#L78)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO about capturing `cluster_data` via `std::move()` once we can use C++14.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 148 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9iTel-VjYXtLeocK0:-MoAYbNICE3W7uJlfRMS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L148)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If possible, I'd prefer to keep these methods `protected` and use `friend` statements to work around this bug, like we were doing before.  If MSVC doesn't understand the lambdas, then maybe we can move the code from the lambdas to private methods of `EndpointWatcher`.  For example:

```
class EndpointWatcher : public XdsClient::EndpointWatcherInterface {
 public:
  void OnEndpointChanged(XdsApi::EdsUpdate update) override {
    Ref().release();  // Ref held by callback.
    discovery_mechanism_->parent()->work_serializer()->Run(
        [this, update]() mutable {
          OnEndpointChangedHelper(std::move(update));
          Unref();
        },
        DEBUG_LOCATION);
  }

 private:
  // Code accessing protected methods of `DiscoveryMechanism` need to be
  // in methods of this class rather than in lambdas to work around an MSVC bug.
  void OnEndpointChangedHelper(XdsApi::EdsUpdate update) {
    discovery_mechanism_->parent()->OnEndpointChanged(
        discovery_mechanism_->index(), std::move(update));
  }
};
```
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 181 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9h43L5jJ3Vsavh_By:-MoAYcnnAm9END9FIE3-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L181)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be a const reference, so that we don't take an unnecessary ref.  We are already taking a ref in the lambda capture.

Same thing for all three callbacks.

(This becomes irrelevant if you take my suggestion above about taking a new ref to the watcher instead of taking a ref to the discovery mechanism to avoid the MSVC bug.)
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 184 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9hfsy94BblugCe-9a:-MoAYdKFDPjY_woCNNFe:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L184)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO about capturing `update` via `std::move()` once we can use C++14.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 899 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9j8dc3nasXzd52UJt:-MoAYqjsBj_NsS0XWKZI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L899)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is taking two refs, one here and another in the lambda capture, but we only need one.

I think it makes sense to keep this code in the watcher implementations rather than moving it into these helper functions, because then we can avoid the extra ref by taking the same approach as elsewhere (i.e., take a ref to the watcher), or we can declare a const reference to the existing `RefCountedPtr<XdsResolver>` data member.

Same thing for all three callbacks.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 901 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9khSN4FhRFBBfKuZK:-MoAYfZ8Em3R83c9wqIS:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L901)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO about using `std::move()` to capture `update` when we move to C++14.

Same for the RDS update.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9YiOh0h61aMIxllQo:-MoAYhmE7fKfvElCsyxd:b-49d2sq) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.h#L49)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What was the error you got when trying this?

Note that when using lock annotations with a `WorkSerializer`, you need to add `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` annotations to the lambdas that you run in the `WorkSerializer`.  You can see how we did this in the client channel code in #25983.
</blockquote></details>

Adding in what I tried.
___
*[src/core/ext/xds/xds_client.cc, line 183 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9_7Xh4rVc3yWfjdOV:-MoAYoCS426eBX7FXhpi:bb4d2d3) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L183)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we need to pass this in at all.  Instead, you can change `OnTimer()` to access it via `self->ads_calld_->xds_client()`.
</blockquote></details>

Ah, you are right. Thanks!
___
*[src/core/ext/xds/xds_client.cc, line 226 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9ZeUs6CXYq1u28JOb:-MoAY-iz7Zxeb-k3A6t9:bb6sh2i) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L226)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think this is fine.  We were already doing this work in the timer thread before this change.
</blockquote></details>

Ack.
___
*[src/core/ext/xds/xds_client.cc, line 2162 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9bfbD22SoqoveV-Zx:-MoAY2bEAgFC8KP6cnu2:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2162)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO that once we can use C++14, we can capture `watcher` using `std::move()`.

Same thing for all resource types.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2163 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9aPsfArW3G8gMDtwa:-MoAY3Ds92rYNb6Bg5Wm:b2nhb2c) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2163)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Good catch!

Please remove these `review_note:` comments before merging.
</blockquote></details>

Ack
___
*[src/core/ext/xds/xds_client.cc, line 2184 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9c8nv-3piWUcjmFLY:-MoAY6UU7SxJpEFga3_b:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2184)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same C++14 TODO here.

Same thing for all resource types.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2589 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9clPG4vQp3K94lccz:-MoAYVpVCNgOMEglxfmT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2589)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think we want to capture the whole authority_state_map here, since that includes a lot of data we don't actually need.  It will take an unnecessary ref to the `ChannelState` object, and it will unnecessarily copy all of the cached resource data.

Instead, I suggest something like this:

```
std::set<RefCountedPtr<ListenerWatcher>> listener_watchers;
std::set<RefCountedPtr<RouteConfigWatcher>> route_config_watchers;
std::set<RefCountedPtr<ClusterWatcher>> cluster_watchers;
std::set<RefCountedPtr<EndpointWatcher>> endpoint_watchers;
for (const auto& a : authority_state_map_) {
  for (const auto& p : a.second.listener_map) {
    const ListenerState& listener_state = p.second;
    for (const auto& q : listener_state.watchers) {
      listener_watchers.insert(q.second);
    }
  }
  // ...same for other resource types...
}
work_serializer_.Schedule(
    [listener_watchers, route_config_watchers, cluster_watchers, endpoint_watchers, error]()
        ABSL_EXCLUSIVE_LOCKS_REQUIRED(&work_serializer_) {
      for (const auto& watcher : listener_watchers) {
        watcher->OnError(GRPC_ERROR_REF(error);
      }
      // ...same for other resource types...
      GRPC_ERROR_UNREF(error);
    },
    DEBUG_LOCATION);
```
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 2589 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9d6C24fh_pTyRDMeb:-MoAYWB0Ak26N2XBH2pV:bfj1qdn) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2589)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should use `ABSL_EXCLUSIVE_LOCKS_REQUIRED(&work_serializer_)` instead of `ABSL_NO_THREAD_SAFETY_ANALYSIS`.
</blockquote></details>

Tried but doesn't seem to be working

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27975)* status: 1 of 6 files reviewed, 15 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/xds/xds_client.h, line 49 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9YiOh0h61aMIxllQo:-MoBOLXu70vzw1L-Pmyd:bikuj9x) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.h#L49)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Adding in what I tried.
</blockquote></details>

got it to work :)
___
*[src/core/ext/xds/xds_client.cc, line 2589 at r2](https://reviewable.io/reviews/grpc/grpc/27975#-Mo9d6C24fh_pTyRDMeb:-MoBORo33uj0fs-K6fDl:bikuj9x) ([raw file](https://github.com/grpc/grpc/blob/3b817204609c65310de98fdebdc0f7d539717aec/src/core/ext/xds/xds_client.cc#L2589)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Tried but doesn't seem to be working
</blockquote></details>

got it to work :)

**Review by markdroth — APPROVED** [review]
This looks great!  Feel free to merge after addressing the remaining couple of minor comments.

> Reviewed 2 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27975#-:-MoFYK5DAtetHnrlAbm7:bypt5md)* status: all files reviewed, 2 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 91 at r5](https://reviewable.io/reviews/grpc/grpc/27975#-MoFXpr4-CPe_PEpmiPK:-MoFXpr4-CPe_PEpmiPL:b-fo6dpc) ([raw file](https://github.com/grpc/grpc/blob/2a0ed4e20d2eb1a33e818869ecd786c4ab1e41f2/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L91)):*
> ```cpp
>           // std::move
>           [this, listener]() mutable {
>             if (resolver_->xds_client_ != nullptr) {
> ```

We can probably move the check for `xds_client_` being null into `XdsResolver::OnListenerUpdate()`, `XdsResolver::OnRouteConfigUpdate()`, `XdsResolver::OnError()`, and `XdsResolver::OnResourceDoesNotExist()`, so that they don't need to be duplicated in all of the lambdas.
___
*[src/core/ext/xds/xds_client.cc, line 2625 at r5](https://reviewable.io/reviews/grpc/grpc/27975#-MoFSoCf7s_8E7tiRo6f:-MoFSoCf7s_8E7tiRo6g:b-dwlutx) ([raw file](https://github.com/grpc/grpc/blob/2a0ed4e20d2eb1a33e818869ecd786c4ab1e41f2/src/core/ext/xds/xds_client.cc#L2625)):*
> ```cpp
>   }
>   work_serializer_.Schedule(
>       [listener_watchers, route_config_watchers, cluster_watchers,
> ```

Please add the same TODO here about capturing with `std::move()` when we can use C++14.

**Comment by yashykt** [comment]
@caniszczyk Can you help with getting the EasyCLA check to get unstuck?

**Comment by dealako** [comment]
Odd, EasyCLA logs show the PR successfully passed the check and we posted an update back to GitHub:

> cla: EasyCLA App checks pass for PR: 27975 with authors: [('f5fabdbc7a7e216150a035330e352dcdd4c1e596', 'Yash Tibrewal'), ('0cfdad83b6d54add6177ed239a03abb1e9df9c67', 'Yash Tibrewal'), ('7ce03fae7dbe1cc137656b5ae4ae69d2d630bd77', 'Yash Tibrewal'), ('0c5f6f9afe6a70af6cd31dd1314e714253cc57d8', 'Yash Tibrewal'), ('abed7a0cb12f55365bbfeb000fe394c4bbf851df', 'Yash Tibrewal'), ('3b817204609c65310de98fdebdc0f7d539717aec', 'Yash Tibrewal'), ('03edbdd4c9f75fe15645b44454059f0f356b7d28', 'Yash Tibrewal'), ('00090182dd5cdcb6055d6fd5224afa9b23946363', 'Yash Tibrewal'), ('df04a85776e7d80c7017643215de1d41294156a7', 'Yash Tibrewal'), ('2a0ed4e20d2eb1a33e818869ecd786c4ab1e41f2', 'Yash Tibrewal'), ('ff0d8f884372a8541d045bc9de14cb135ee6180b', 'Yash Tibrewal')]
> cla: Successfully posted status success on PR 27975: Commit f5fabdbc7a7e216150a035330e352dcdd4c1e596

**Comment by dealako** [comment]
Somehow the EasyCLA bot is unable to update the status. May need to close and re-open this ticket to re-trigger all the status checks.

**Comment by dealako** [comment]
We're pushing an update to EasyCLA which resolves this issue. Sorry for the inconvenience!  The issue was related to EasyCLA calculating/determining the latest (most recent) git commit SHA when more than 1 commit is associated with a given PR.  When updating the status, we need to provide the latest git commit SHA as input - not the other SHAs.  This should be resolved now with our latest update. Once we have this fix deployed, I'll add the '/easycla' commit to trigger a re-check - which should pass.

Again, sorry for the inconvenience.

**Comment by yashykt** [comment]
Issues: #28025, #26886

**Comment by yashykt** [comment]
Thanks @dealako !

**Pull request merged**
