### PR TITLE
Update client_matrix.py after 1.16 release

### PR DESCRIPTION
**Pull request by stanley-cheung**
I ran the `tools/interop_matrix/create_matrix_images.py` script and verified that the images are updated to the gcp project

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,997,274      Total (=)      1,997,274

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,021,702      Total (>)     11,021,701

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by stanley-cheung** [comment]
Yes, following the process, and also similar to what we did in v1.15

**Pull request merged**
