### PR TITLE
Upmerge Split off pre_1.11 Python interop script

### PR DESCRIPTION
**Pull request by mehrdada**
#15159  Upmerge

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
Interop matrix running at https://fusion.corp.google.com/invocation/f7b56525-f3ae-4985-adda-a928f40984f9

**Pull request merged**
