### PR TITLE
DO NOT MERGE: Updated protobuf version to 4.0.0-rc1

### PR DESCRIPTION
**Pull request by acozzette**

### CODE REVIEW

**Comment by acozzette** [comment]
This pull request probably should not be merged, but I would just like to run the CI tests to verify that the upcoming protobuf 4.0.0 release doesn't break anything.

**Comment by stanley-cheung** [comment]
@acozzette Hi, we had a draft PR #23482 with the same idea. There we are running into issues where the Cocoapods packages for Obj-C version `4.0.0-rc1` wasn't uploaded yet. Any idea when that will be uploaded?

**Comment by acozzette** [comment]
@stanley-cheung Uploading the Cocoapods package looks easy to do but I realized I can't do it myself since I don't have a Mac. On Monday I'll ask if one of my teammates can do it.

**Comment by acozzette** [comment]
@TeBoring Could you upload the cocoapod for rc1 when you have a chance?

**Comment by TeBoring** [comment]
Sure

**Comment by stanley-cheung** [comment]
Thanks. Updated #23482 and running a new round of tests.

**Pull request closed without merging**
