### PR TITLE
Advance versions from 0.14 -> 1.0.0-pre1

### PR DESCRIPTION
**Pull request by jcanizales**
Pending after this:

- [x] Test by pointing BoringSSL.podspec to latest commit of its repo.
- [x] Tag that commit of the BoringSSL repo.
- [ ] Tag gRPC repo.
- [ ] Build the plugin, zip it, and add it to the release.
- [ ] Push Cocoapods to trunk.

### CODE REVIEW

**Comment by jcanizales** [comment]
Argh, of course this fails until we tag the BoringSSL repo...

**Comment by muxi** [comment]
templates/gRPC-Core.podspec.template may need to be updated too

**Comment by jcanizales** [comment]
Good catch!

**Comment by jcanizales** [comment]
Note that the 3 Travis failures are expected, as the apps under `/examples` use the released pods, and 1.0 isn't released yet. The apps under `/src/objective-c/examples` compile everything from sources, same as the tests, so they pass.

**Comment by makdharma** [comment]
Since all the changes are about obj-c, and the tests are expected to fail because cocoapods doesn't know about 1.0.0-pre1, I'm merging by force.

**Pull request merged**
