### PR TITLE
global replace health check proto v1alpha to v1

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by yang-g** [comment]
@jtattermusch @murgatroid99 @soltanmm Please take a look at csharp ruby/node python. Thanks.

**Comment by murgatroid99** [comment]
Node changes LGTM, and the tests still pass.

**Comment by jtattermusch** [comment]
C# LGTM.

**Comment by soltanmm** [comment]
Python LGTM.

**Comment by yang-g** [comment]
@murgatroid99 Could you take a look at ruby as well? Thanks

**Comment by murgatroid99** [comment]
I don't see any problems with the Ruby changes. The tests passed, so it's probably correct.

**Comment by yang-g** [comment]
I will merge this once I see green.

**Pull request merged**
