### PR TITLE
Fix the shared library build for :grpc++_unsecure

### PR DESCRIPTION
**Pull request by jhseu**

### CODE REVIEW

**Comment by jhseu** [comment]
@vjpai

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by vjpai** [comment]
Jenkins, this is ok to test

**Comment by vjpai** [comment]
Can you describe the issue that these changes resolve? AFAIK, none of the changes being made _require_ security and that should be the only difference between grpc and grpc_unsecure. Maybe we need a new more trimmed target for your purposes?

**Comment by jhseu** [comment]
Probably the main issue is that these aren't being linked into the grpc++_unsecure rule, but should be. They're missing dependencies.

**Comment by vjpai** [comment]
@nicolasnoble : what's the path forward on combining #11933 and #11944 ?

**Comment by vjpai** [comment]
Superceded by #11978

**Pull request closed without merging**
