### PR TITLE
Fix unused parameter warning in cpp codegen

### LINKED ISSUE #6518: Cannot turn warnings into errors because of unused "options" param
Hi there.

I'd like to use -Werror on a codebase that depends on gRPC. I get a warning for unused "options" parameter in this stub:

```
std::unique_ptr< MyService::Stub> MyService::NewStub(const std::shared_ptr<::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
    std::unique_ptr< MyService::Stub> stub(new MyService::Stub(channel));
    return stub;
 }
```

Regards.

### PR DESCRIPTION
**Pull request by kpayson64**
Credit to @dholm for this fix #13104, It just never got merged due to a CLA issue.

Fixes #6518

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by kpayson64** [comment]
#12510

**Pull request merged**
