### PR TITLE
Pin version of RSA package to avoid bad releases

### PR DESCRIPTION
**Pull request by lidizheng**
Fix https://github.com/grpc/grpc/issues/23190 #23188

The cause: https://github.com/sybrenstuvel/python-rsa/issues/152

The `rsa` release 4.1.1 and 4.2 dropped Python 2 support, which is a legit move. However, they didn't update the corresponding classifier in their `setup.py`. So, the PyPI offers py2-incompatible packages to Python 2 users and caused the breakage.

We don't directly depend on `rsa`. The `google-auth` library incurs dependency on `rsa`, which unfortunately was needed for our tests.

### CODE REVIEW

**Comment by veblush** [comment]
It seems that they've just released pypi [4.3](https://pypi.org/project/rsa/4.3/) supporting Python 2.7 and [4.4](https://pypi.org/project/rsa/4.4/) dropping Python 2.7 to fix the problem. How about waiting for their fix if this is not urgent?

**Comment by sybrenstuvel** [comment]
I hope it's fixed now! If there are still issues, please let me know.

**Comment by lidizheng** [comment]
@sybrenstuvel Thanks for the quick update. From my local experiments, `python2 -m pip install -U rsa` installs `rsa==4.4`, which is still Python 2 incompatible. I think there might be another classifier issue in version 4.4, you might want to "yank" that version, or release a newer Python 2 compatible version.

**Comment by busunkim96** [comment]
FYI, we just released google-auth 1.17.2 with a more restricted pin https://github.com/googleapis/google-auth-library-python/blob/b74168b710da38c0cf06cdf8685c49af4748e3a0/setup.py#L25-L26

**Comment by stanley-cheung** [comment]
@lidizheng I wonder whether we need to backport this fix to the `1.30.x` branch? Right now there's not a lot of traffic on the `1.30.x` branch, but when we do, I suppose PR would fail these tests in the same way?

**Comment by lidizheng** [comment]
@stanley-cheung We won't need to backport this. The breakage is only impacting our test infrastructure. The bad release comes from `rsa` which is dependency of `google-auth` which only affect our unit tests.

This PR is a more or less a bandage, long term solution is https://github.com/grpc/grpc/pull/23200.

**Pull request merged**
