### PR TITLE
Add common oauth ultilities for 3pi support

### PR DESCRIPTION
**Pull request by renkelvin**
1. Add common structs: client auth, token exchange requests and responses
2. Add token exchange helper methods to generate grpc_httpcli_request and request body

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/23961)

### CODE REVIEW

**Comment by renkelvin** [comment]
@markdroth @jiangtaoli2016 @ZhenLian 
Please take a look at this PR which adds common oauth utilities for 3p identity support.

It seems I don't have write access so I can't add the proper labels. Can someone help add them? Thanks!

**Comment by markdroth** [comment]
Using C++ style for this new code does not depend on the style of any existing code.  As I said, we are in the process of migration, so there is a bunch of existing code that has not yet been migrated.  But I do not want to make that process harder by adding more code using the wrong style that will have to be migrated later.

It's fine to create a class whose name is in C++ style and that inherits from another class whose name is not yet in C++ style.  It's also fine to use C-style names if you are implementing an interface whose API has not yet been converted to C++ style naming (e.g. `grpc_call_credentials`).  Those are uses of existing code that you can't avoid.  But for anything that does not need to use C style in order to make those kinds of interactions work, it should be done in C++ style.

I'm not sure why it's useful for you to see docs about our migration to C++, but you're certainly welcome to view them.  Here are the relevant docs:

- [gRFC L6: Allow C++ in gRPC Core Library](https://github.com/grpc/proposal/blob/master/L6-core-allow-cpp.md)
- [gRFC L59: Allow C++ standard library in gRPC Core Library](https://github.com/grpc/proposal/blob/master/L59-core-allow-cppstdlib.md)
- [Moving gRPC core to C++](https://github.com/grpc/grpc/blob/master/doc/core/moving-to-c%2B%2B.md)

In the particular case of `grpc_oauth2_token_fetcher_credentials` and of the method names in the `grpc_call_credentials` API, they should have been converted to C++ style names when the code was coverted to C++.  @soheilhy, you did that conversion in #17291, which was merged in Dec. 2018.  You told me at that time that you were going to update the names to C++ style in a subsequent PR, but you never did.  Are you still going to do it, and if so when?  If not, I will try to find time to do it myself.

**Comment by renkelvin** [comment]
I was worried about the mix of C++11 and C styles so I was thinking converting the style at the same time may be better. But what you said makes sense. I'll update this PR in C++ styles.

I was wondering if there is migrated code(instead of docs) I can refer to, so I can learn more about the C++11 style and adhere that. The docs and project board helps though.

I'll update this PR later. Thanks!

**Comment by markdroth** [comment]
You can look at pretty much any of the completed code in https://github.com/grpc/grpc/projects/9 for examples.

See also https://github.com/grpc/grpc/blob/master/doc/cpp-style-guide.md, which basically just points to Google's OSS C++ style guide.

**Comment by soheilhy** [comment]
> @soheilhy, you did that conversion in #17291, which was merged in Dec. 2018. You told me at that time that you were going to update the names to C++ style in a subsequent PR, but you never did. Are you still going to do it, and if so when? If not, I will try to find time to do it myself.

My apologists, I probably wouldn't have the cycles to do so.  IIRC, I had a patch ready but there were complication regarding Asylo imports and namings, and I had to give on that patch due to copybara headaches and conflicts.

**Comment by renkelvin** [comment]
According to the discussion @markdroth , the OAuth related methods should be encapsulated in the base credentials class. Please see the changes in https://github.com/grpc/grpc/pull/24208 and I'm going to close this issue.

**Pull request closed without merging**
