### PR TITLE
Fix dependency issue if not using embedded zlib

### PR DESCRIPTION
**Pull request by bc-lee**

### CODE REVIEW

**Comment by bc-lee** [comment]
I signed it!

**Comment by jtattermusch** [comment]
Hi, thanks for the PR. Makefile is generated, you need to change the template under templates/ and run tools/buildgen/generate_projects.sh to regenerate.

Also, there's a merge conflict in Makefile, please resolve.

**Comment by jtattermusch** [comment]
Can you also please add an explanation of what gets fixed by this PR?

**Comment by jtattermusch** [comment]
Hi, because of the merge conflict and missing explanation, I'm going to close this PR. Please reopen once this is ready for review.

**Pull request closed without merging**
