### PR TITLE
Respond with UNIMPLEMENTED when a requested method is not found

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
This depends on #3150 and partially addresses #2634.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Is this okay to merge ? Otherwise this will need to be re-done on the beta branch. Also, please don't assign your pull requests to yourself ?

**Comment by nathanielmanistaatgoogle** [comment]
This is not okay to merge. It's assigned to myself because I found an issue with it that I need to correct. I can live with having to redo it against the beta branch.

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller - huh?

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller ahh I see how this works now. Nevermind; sorry for the noise.

**Pull request merged**
