### PR TITLE
Automatic v1.0.x -> master upmerge

### PR DESCRIPTION
**Pull request by nicolasnoble**
The more people are committing to v1.0.x, the more this PR will evolve. We can merge it anytime to keep master in sync, and recreate it right after.

### CODE REVIEW

**Comment by jcanizales** [comment]
Let's merge it ASAP to fix the broken ObjC tests in master.

**Comment by jcanizales** [comment]
Oh, because this isn't from your fork it doesn't get Travis. Should we re-enable?

**Comment by nicolasnoble** [comment]
Go for it.

**Comment by jcanizales** [comment]
Enabled. You might need to do a dummy push into v1.0.x for it to trigger though.

**Comment by jcanizales** [comment]
@nicolasnoble are you fine if I merge and recreate?

**Comment by nicolasnoble** [comment]
I'm fine with that, yes.

**Pull request merged**
