### PR TITLE
Fixes gRPC ObjC plugin's upper camel conversion

### PR DESCRIPTION
**Pull request by muxi**
`grpc_objective_c_plugin`'s output file name was not correct when dash (`-`) was included in the source proto file's filename. This PR uses Protocol Buffer's native upper camel conversion function instead of a custom one to resolve this problem.

Manually tested OK. With a proto file named `test-test-test.proto`, current version of `grpc_objective_c_plugin` generates `Test-test-test.pbrpc.{m,h}`. After the patch, `TestTestTest.pbrpc.{m,h}` was generated.

### CODE REVIEW

**Comment by makdharma** [comment]
We need to figure out how to handle breaking change to existing code.

**Comment by muxi** [comment]
I think one day they will be broken anyway. The best that I can think of for now is to generate two styles at the same time. But it would be confusing to new users though. Probably write warning comments at the beginning of the old style file that they should use the new style file?

**Comment by jcanizales** [comment]
One way to make it non-breaking is to enable this with a protoc plugin flag: protoc has a syntax to let pass flags to a plugin. We could have the Blaze rule always pass such a flag.

Alternatively, if few people use filenames with dashes, we can have the plugin flag there to _disable_ the new behavior, and document the breaking change and the way to disable.

This change is mostly aesthetic, though, so I would keep the default backwards-compatible.

**Comment by muxi** [comment]
Basic Tests Mac - #11116 
Basic Tests Windows - #11383

**Pull request merged**
