### PR TITLE
Remove THREAD_SANITIZER define as it triggers #17175

### PR DESCRIPTION
**Pull request by jtattermusch**
Hopefully less invasive fix for #17175 than https://github.com/grpc/grpc/pull/17211.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
Manual RBE run confirms that this fixes the problem
`bazel --bazelrc=tools/remote_build/manual.bazelrc test --config=tsan --runs_per_test=5 //test/cpp/ext/filters/census:grpc_opencensus_plugin_test@poller=epoll1`

**Comment by jtattermusch** [comment]
@vjpai  nope, THREAD_SANITIZER is absl-specific. Our codebase used GRPC_TSAN AFAIK. It was added here https://github.com/grpc/grpc/pull/17165/files#diff-4c3a4e61471476647ad1c0987a744414R37 (with the intent to fix an MSAN issue, the TSAN define was only added for consistency)

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,964      Total (=)      2,019,964

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,183,089      Total (>)     11,183,084

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/17218

**Pull request merged**
