### PR TITLE
Change LB policy API to always return results via the closure.

### PR DESCRIPTION
**Pull request by markdroth**
There are no functional changes here, but this simplifies the LB policy API and eliminates a lot of duplicate code that we had due to supporting two different code-paths.

The only concern I have about this is whether there are performance implications, but I think this shouldn't be a big deal now that everything is running under the same combiner.  But let's see what bm_diff has to say about it.

### CODE REVIEW

**Comment by ctiller** [comment]
It's probably worth merging this and re-running tests.

**Comment by markdroth** [comment]
This is now built on top of #11352.

**Comment by markdroth** [comment]
I think I've just discovered something about where the additional lock contention in this PR is coming from.  I had originally assumed that it was coming from the additional callback being invoked on the combiner.  However, while working on #11352, I made a change that caused us to call grpc_polling_entity_add_to_pollset_set() and grpc_polling_entity_del_from_pollset_set() even in the synchronous case, and it resulted in almost exactly the same amount of increased lock contention being reported for this PR.  I have reverted that change from the other PR, but I now suspect that the additional lock contention in this PR is actually due to the pollset_set modification, not to invoking a new callback on the combiner.

Craig, any thoughts on how we might address this?

**Comment by dgquintas** [comment]
@sreecha may also have ideas.

**Comment by dgquintas** [comment]
Is this PR still ongoing?

**Comment by markdroth** [comment]
I've put it on the back burner for now.  I'll come back to it at some point in the future.

**Comment by markdroth** [comment]
This PR is now sufficiently out of date that if I do ever decide to pick this up again, I will wind up starting over anyway, so I'm going to close it.

**Pull request closed without merging**
