### PR TITLE
Fix a number of issues on Windows.

### PR DESCRIPTION
**Pull request by TassoKarkanisADSK**

### CODE REVIEW

**Comment by TassoKarkanisADSK** [comment]
I signed it!


On Apr 21, 2015, at 11:35 AM, googlebot <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your pull request. It looks like this may be your first contribution to a Google open source project, in which case you'll need to sign a Contributor License Agreement (CLA).

[:memo:] Please visit https://cla.developers.google.com/ to sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

________________________________

  *   If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data<https://cla.developers.google.com/clas> and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.
  *   If you signed the CLA as a corporation, please let us know the company's name.

**Comment by nicolasnoble** [comment]
Thanks for the pull request. However it looks like there's a few things that won't work with it at the moment.

More specifically, why are you adding an include on <winsock2.h> ? This is causing the build to fail this way:

```
 call_op_string.c
C:\Program Files (x86)\Windows Kits\8.1\Include\shared\ws2def.h(100): warning C4005: 'AF_IPX' : macro redefinition [C:\Program Files (x86)\Jenkins\jobs\grpc - Visual Studio 2013\workspace\vsprojects\grpc\grpc.vcxproj]
          C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock.h(452) : see previous definition of 'AF_IPX'
```


I assume you are trying to get gRPC working under 64 bits ?

**Comment by TassoKarkanisADSK** [comment]
Thanks for your quick response.  Yes, I'm trying to compile for WIN64.  I'm including <winsock2.h> because this header uses types defined there, and it failed to build for me.  I have to admit at this point that I'm not using your DevStudio project files (we have our own build system).  I will track down the source of this problem and get back to you.

**Comment by nicolasnoble** [comment]
Note that this is a small extract of the failure log. I can provide the full list if you need.

**Comment by wkubiak** [comment]
The fix done in 9ffe6e59380d6217f37c8624b5804af005747905 has actually already made it to the master branch 00b658530d94c5fd827bec793e3448838a6221f1.

What is your Windows build environment @TassoKarkanisADSK ?

**Comment by ctiller** [comment]
Closing stale PR.

**Pull request closed without merging**
