### PR TITLE
Fine tune cmake find_package usage

### PR DESCRIPTION
**Pull request by jtattermusch**
Just a bit of cleanup and providing explanatory comments.

### CODE REVIEW

**Comment by jtattermusch** [comment]
@nicolasnoble  for OWNERS approval.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__8.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
@matt-kwong, I need owner approval, can you please approve?

**Comment by jtattermusch** [comment]
@mehrdada, this is ready to merge, I just need owners approval (I'm owner myself, but github). Please consider including in v1.10.0 (if not cut yet).

**Pull request merged**
