### PR TITLE
Fix ping policy

### PR DESCRIPTION
**Pull request by y-zeng**
Will be merged to #11072 to after being tested.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                                                                                    allocs_per_iteration    atm_add_per_iteration    atm_cas_per_iteration    cpu_time    locks_per_iteration    real_time    writes_per_iteration
-----------------------------------------------------------------------------------------------------------  ----------------------  -----------------------  -----------------------  ----------  ---------------------  -----------  ----------------------
BM_PumpStreamClientToServer<InProcessCHTTP2>/0                                                               +123%                   +62%                     +67%                     +28%        +138%                  +28%         +184%
BM_PumpStreamClientToServer<InProcessCHTTP2>/1                                                               +124%                   +58%                     +60%                     +24%        +139%                  +24%         +186%
BM_PumpStreamClientToServer<InProcessCHTTP2>/16M                                                                                                                                                   +10%
BM_PumpStreamClientToServer<InProcessCHTTP2>/2M                                                                                                                                                    +15%                                +15%
BM_PumpStreamClientToServer<InProcessCHTTP2>/32k                                                             +4%                                                                                   +5%
BM_PumpStreamClientToServer<InProcessCHTTP2>/4k                                                              +69%                    +44%                     +53%                                 +116%                               +143%
BM_PumpStreamClientToServer<InProcessCHTTP2>/512                                                             +78%                    +51%                     +62%                     +22%        +144%                  +22%         +191%
BM_PumpStreamClientToServer<InProcessCHTTP2>/64                                                              +79%                    +51%                     +63%                     +21%        +147%                  +21%         +196%
BM_PumpStreamClientToServer<InProcessCHTTP2>/8                                                               +127%                   +60%                     +61%                     +25%        +143%                  +25%         +191%
BM_PumpStreamClientToServer<MinInProcessCHTTP2>/0                                                            +122%                   +62%                     +66%                     +36%        +138%                  +36%         +184%
BM_PumpStreamClientToServer<SockPair>/128M                                                                   +7%
BM_PumpStreamClientToServer<SockPair>/256k                                                                   +6%
BM_PumpStreamClientToServer<UDS>/256k                                                                        +4%
BM_PumpStreamServerToClient<InProcessCHTTP2>/0                                                               +133%                   +60%                     +59%                     +16%        +99%                   +16%         +199%
BM_PumpStreamServerToClient<InProcessCHTTP2>/1                                                               +133%                   +49%                     +40%                     +11%        +99%                   +11%         +199%
BM_PumpStreamServerToClient<InProcessCHTTP2>/2M                                                                                                                                                    +10%                                +13%
BM_PumpStreamServerToClient<InProcessCHTTP2>/32k                                                             +5%                                                                                   +5%
BM_PumpStreamServerToClient<InProcessCHTTP2>/4k                                                              +69%                    +34%                     +32%                                 +79%                                +143%
BM_PumpStreamServerToClient<InProcessCHTTP2>/512                                                             +78%                    +39%                     +39%                     +6%         +96%                   +6%          +191%
BM_PumpStreamServerToClient<InProcessCHTTP2>/64                                                              +79%                    +40%                     +40%                     +16%        +99%                   +16%         +198%
BM_PumpStreamServerToClient<InProcessCHTTP2>/8                                                               +133%                   +49%                     +40%                     +11%        +99%                   +11%         +199%
BM_PumpStreamServerToClient<MinInProcessCHTTP2>/0                                                            +133%                   +60%                     +59%                     +39%        +99%                   +39%         +199%
BM_PumpStreamServerToClient<SockPair>/128M                                                                   +6%
BM_PumpStreamServerToClient<SockPair>/16M                                                                    +7%
BM_PumpStreamServerToClient<SockPair>/256k                                                                   +6%
BM_PumpStreamServerToClient<UDS>/256k                                                                        +5%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomAsciiMetadata<100>, 1>, NoOpMutator>/0/0          +53%                    +23%                     +28%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomAsciiMetadata<10>, 1>, NoOpMutator>/0/0           +61%                    +23%                     +28%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomAsciiMetadata<31>, 1>, NoOpMutator>/0/0           +53%                    +23%                     +27%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomBinaryMetadata<100>, 1>, NoOpMutator>/0/0         +53%                    +23%                     +28%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomBinaryMetadata<100>, 2>, NoOpMutator>/0/0         +44%                    +22%                     +26%                                 +46%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomBinaryMetadata<10>, 1>, NoOpMutator>/0/0          +61%                    +23%                     +28%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomBinaryMetadata<10>, 2>, NoOpMutator>/0/0          +57%                    +22%                     +28%                                 +46%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomBinaryMetadata<31>, 1>, NoOpMutator>/0/0          +53%                    +23%                     +27%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, Client_AddMetadata<RandomBinaryMetadata<31>, 2>, NoOpMutator>/0/0          +44%                    +22%                     +27%                                 +46%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0                                              +79%                    +24%                     +29%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/1                                              +79%                    +24%                     +28%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/128M                                                                   -14%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/16M                                            -42%                    -51%                                                                                              -13%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/256k                                           +81%                    +25%                     +29%                                 +71%                                +58%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/2M                                                                                                                                   +49%                                +35%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/32k                                            +29%                    +11%                     +13%                                 +36%                                +38%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/4k                                             +58%                    +20%                     +25%                                 +55%                                +85%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/512                                            +65%                    +22%                     +28%                                 +59%                                +97%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/64                                             +66%                    +22%                     +29%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/0/8                                              +79%                    +24%                     +29%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/1/0                                              +79%                    +24%                     +28%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/1/1                                              +79%                    +24%                     +29%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/128M/128M                                                                                                                              +45%                                +36%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/16M/0                                                                                                                                  +6%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/16M/16M                                          -14%                    -27%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/256k/0                                           +23%                    +5%                                                           +6%                                 +12%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/256k/256k                                        +43%                    +14%                     +13%                                 +41%                                +35%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2M/0                                             +11%                                                                                  +13%                                +22%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/2M/2M                                            +7%                                                                                   +39%                                +33%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/32k/0                                            +27%                    +9%                      +10%                                 +16%                                +34%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/4k/0                                             +58%                    +20%                     +25%                                 +50%                                +85%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/4k/4k                                            +44%                    +17%                     +21%                                 +46%                                +72%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/512/0                                            +65%                    +22%                     +28%                                 +58%                                +97%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/512/512                                          +55%                    +21%                     +28%                                 +58%                                +95%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/64/0                                             +66%                    +22%                     +28%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/64/64                                            +56%                    +21%                     +29%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/8/0                                              +79%                    +24%                     +29%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, NoOpMutator>/8/8                                              +79%                    +24%                     +29%                                 +59%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, Server_AddInitialMetadata<RandomAsciiMetadata<100>, 1>>/0/0   +49%                    +23%                     +27%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, Server_AddInitialMetadata<RandomAsciiMetadata<10>, 100>>/0/0  +7%                     +6%                      +18%                                 +5%                                 +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, Server_AddInitialMetadata<RandomAsciiMetadata<10>, 1>>/0/0    +57%                    +23%                     +28%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, Server_AddInitialMetadata<RandomAsciiMetadata<31>, 1>>/0/0    +49%                    +23%                     +27%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, Server_AddInitialMetadata<RandomBinaryMetadata<100>, 1>>/0/0  +49%                    +23%                     +28%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, Server_AddInitialMetadata<RandomBinaryMetadata<10>, 1>>/0/0   +57%                    +23%                     +28%                                 +49%                                +99%
BM_UnaryPingPong<InProcessCHTTP2, NoOpMutator, Server_AddInitialMetadata<RandomBinaryMetadata<31>, 1>>/0/0   +49%                    +23%                     +28%                                 +49%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/0                                           +79%                    +24%                     +33%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/1                                           +79%                    +24%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/128M                                                                -6%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/16M                                         -41%                    -51%                                                                                              -15%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/256k                                        +79%                    +23%                     +32%                                 +67%                                +52%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/2M                                          +25%                    +9%                                                           +65%                                +55%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/32k                                         +27%                    +11%                     +13%                                 +34%                                +36%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/4k                                          +58%                    +20%                     +29%                                 +55%                                +85%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/512                                         +65%                    +22%                     +32%                                 +59%                                +97%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/64                                          +66%                    +23%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/0/8                                           +79%                    +24%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/1/0                                           +79%                    +24%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/1/1                                           +79%                    +24%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/128M/128M                                                                                                                           +46%                                +35%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/16M/16M                                       -9%                     -23%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/256k/0                                        +22%                    +5%                                                           +6%                                 +13%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/256k/256k                                     +40%                    +13%                     +4%                                  +40%                                +35%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2M/0                                          +17%                    +6%                                                           +16%                                +27%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/2M/2M                                         +12%                                                                                  +40%                                +36%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/32k/0                                         +28%                    +9%                      +13%                                 +17%                                +35%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/4k/0                                          +58%                    +20%                     +28%                                 +50%                                +85%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/4k/4k                                         +44%                    +17%                     +25%                                 +46%                                +73%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/512/0                                         +65%                    +22%                     +32%                                 +58%                                +97%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/512/512                                       +55%                    +21%                     +30%                                 +58%                                +96%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/64/0                                          +66%                    +23%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/64/64                                         +56%                    +21%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/8/0                                           +79%                    +24%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/8/8                                           +79%                    +24%                     +32%                                 +59%                                +99%
BM_UnaryPingPong<MinSockPair, NoOpMutator, NoOpMutator>/0/0                                                  +22%                    +9%                      +7%                                  +8%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/0                                                       +19%                    +8%                      +5%                                  +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/1                                                       +20%                    +8%                      +6%                                  +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/256k                                                    +7%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/32k                                                     +8%                                                                                   +5%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/4k                                                      +16%                    +6%                      +5%                                  +5%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/512                                                     +18%                    +7%                      +5%                                  +5%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/64                                                      +18%                    +7%                      +6%                                  +5%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/8                                                       +19%                    +7%                      +6%                                  +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/0                                                       +20%                    +8%                      +6%                                  +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/1                                                       +20%                    +8%                      +6%                                  +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/0                                                    +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/0                                                     +7%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/0                                                      +16%                    +6%                      +4%                                  +5%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/4k                                                     +13%                    +5%                      +4%                                  +4%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/0                                                     +18%                    +7%                      +6%                                  +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/512                                                   +17%                    +7%                      +7%                                  +5%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/0                                                      +18%                    +7%                      +5%                                  +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/64                                                     +16%                    +6%                      +6%                                  +5%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/0                                                       +20%                    +8%                      +6%                                  +6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/8                                                       +20%                    +8%                      +5%                                  +6%
BM_UnaryPingPong<MinUDS, NoOpMutator, NoOpMutator>/0/0                                                       +20%                    +8%                      +7%                                  +7%
BM_UnaryPingPong<SockPair, NoOpMutator, NoOpMutator>/0/0                                                     +22%                    +9%                      +5%                                  +8%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/0                                                          +20%                    +8%                      +5%                                  +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/1                                                          +20%                    +8%                      +5%                                  +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/256k                                                       +8%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/32k                                                        +7%                                                                                   +5%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/4k                                                         +16%                    +6%                      +5%                                  +5%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/512                                                        +18%                    +7%                      +5%                                  +5%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/64                                                         +18%                    +7%                      +5%                                  +5%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/8                                                          +19%                    +7%                      +5%                                  +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/1/0                                                          +20%                    +8%                      +5%                                  +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/1/1                                                          +20%                    +8%                      +6%                                  +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/256k/0                                                       +7%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/32k/0                                                        +7%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/4k/0                                                         +16%                    +6%                      +5%                                  +5%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/4k/4k                                                        +13%                    +5%                      +4%                                  +4%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/512/0                                                        +18%                    +7%                      +5%                                  +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/512/512                                                      +17%                    +7%                      +5%                                  +5%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/64/0                                                         +18%                    +7%                      +5%                                  +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/64/64                                                        +16%                    +6%                      +4%                                  +5%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/8/0                                                          +20%                    +8%                      +5%                                  +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/8/8                                                          +20%                    +8%                      +5%                                  +6%
BM_UnaryPingPong<UDS, NoOpMutator, NoOpMutator>/0/0                                                          +20%                    +8%                      +5%                                  +7%
```

**Comment by ncteisen** [comment]
I still need to tune the QPS performance bot, but I took a manual look at the data and it looks like this PR shows a 4% regression for 'multi-channel-64-KiB'

`Master = [46153.2, 47297.1, 45783.8, 47959.6]`
`This PR = [45271.7, 44583.4, 44758.7, 44784.3] `

**Comment by y-zeng** [comment]
Thanks, @ncteisen! The data is very useful. I'm still working on the performance issue in the PR. It touched the bandwidth prober in chttp2_transport, which might be the cause of the regression.

**Comment by y-zeng** [comment]
Merged in #11587

**Pull request closed without merging**
