### PR TITLE
Attempt to drop support for Python 3.4

### PR DESCRIPTION
**Pull request by lidizheng**
In `1.24` gRPC starts releasing 3.8 wheels and `manylinux2010` wheels. Since Python 3.4 is not officially supported (https://www.python.org/dev/peps/pep-0429/), we might want to also remove Python 3.4 support to reduce complexity and build time.

Thanks to @veblush , here is the download statistics across different versions. The usage of 3.4 is 0.1%.
> Python version distribution on 1.24.3 (by Query 1)
> 
> Row python download_count
> 1   3.6     28060
> 2   2.7     26214
> 3   3.7      7104
> 4   3.5      4890
> 5   null     3187
> 6   3.8       251
> 7   3.4        70

Let's see if our infra is happy with my change first :)

### CODE REVIEW

**Comment by jtattermusch** [comment]
Sounds like a good idea, let's see if the tests pass (let's make sure to run the artifacts - packages - distribtests flow at some point).

**Comment by lidizheng** [comment]
[prod:grpc/core/experimental/grpc_build_artifacts_multiplatform](http://sponge/07269185-bbfe-43b6-9bbb-7b1d0b7b92c5)

**Comment by lidizheng** [comment]
@gnossen @jtattermusch PTAL. I think both the Fusion job, and the CI tests are indicating this PR is safe.

**Comment by lidizheng** [comment]
@jtattermusch PTAL. Known failures: https://github.com/grpc/grpc/issues/20923 https://github.com/grpc/grpc/issues/20921

**Pull request merged**
