### PR TITLE
Fix false positive in grpc_is_epollexclusive_available on ESXi

### LINKED ISSUE #22182: false positive in grpc_is_epollexclusive_available()
### What version of gRPC and what language are you using?
1.27.3, C++

### What operating system (Linux, Windows,...) and version?
VMware ESXi 6.7

`grpc_is_epollexclusive_available()` checks that the invalid EPOLLEXCLUSIVE | EPOLLONESHOT flag combination fails with EINVAL and declares success, but not that any other valid combination that has EPOLLEXCLUSIVE succeeds.

VMware's VMkernel supports epoll, but not EPOLLEXCLUSIVE. it returns EINVAL just because it sees the unsupported flag and `grpc_is_epollexclusive_available()` returns true.

the end of the function should be changed to also do a positive check, for example:

```C++
  // Now check that EPOLLEXCLUSIVE is supported at all.
  ev.events =
      static_cast<uint32_t>(EPOLLET | EPOLLIN | EPOLLEXCLUSIVE);
  if (epoll_ctl(fd, EPOLL_CTL_ADD, evfd, &ev) != 0) {
    if (!logged_why_not) {
      gpr_log(GPR_DEBUG,
              "epoll_ctl with EPOLLEXCLUSIVE failed with error: "
              "%d. Not using epollex polling engine.",
              errno);
      logged_why_not = true;
    }
    close(fd);
    close(evfd);
    return false;
  }

  close(evfd);
  close(fd);
  return true;
}
```

also it will be good the file descriptors to be closed by RAII.

### PR DESCRIPTION
**Pull request by tpetkov-VMW**
Hey, this the change @tbuyukliev proposed in the form of a pull request.

Fixes #22182.

### CODE REVIEW

**Comment by tpetkov-VMW** [comment]
This is for issue #22182

**Comment by yashykt** [comment]
Hi, please run 
tools/distrib/clang_format_code.sh to format the code

**Comment by yashykt** [comment]
There are still failures, I'm going to rerun the tests

**Comment by tpetkov-VMW** [comment]
There are some build failures that cannot be from this change, along with some that don't have an obvious connection to the change. Is there some way to deal with those? Would rebasing help?

Example:
https://source.cloud.google.com/results/invocations/fbb99cbe-26fb-4e27-bbe5-4a19fec3ee94/targets/github%2Fgrpc%2Finterop_docker_build/tests

package github.com/envoyproxy/go-control-plane/envoy/api/v2/core: cannot find package "github.com/envoyproxy/go-control-plane/envoy/api/v2/core" in any of:

**Comment by yashykt** [comment]
Other pull requests seem to be getting all green. It is most likely an infrastructure issue. Rerunning once more

**Comment by tpetkov-VMW** [comment]
All checks have passed, is there anything else needed?

**Pull request merged**
