### PR TITLE
Instantiate application callback exec ctx's in a few places where needed

### PR DESCRIPTION
**Pull request by vjpai**
This is needed to resolve an internally-visible bug blocking #17957 . It made more sense to keep this a separate PR since it's a dependency of #17957, not a part of it.

### CODE REVIEW

**Comment by markdroth** [comment]
I need more context on this.

What is `ApplicationCallbackExecCtx`, and when is it needed?  There are no comments in exec_ctx.h that tell me anything about what it is, how it is expected to be used, etc.

Why does it need to be used in this particular case?  This is not the only place where we have a callback that goes out to application code, so why this case and not others?

**Comment by vjpai** [comment]
Failures: #17911

**Comment by vjpai** [comment]
Ok, the comment is in #17984. As for why this is needed here right now, the reason is that all the other known ExecCtx's that can trigger application-level work have already been covered. This particular spot only popped up now because #17957 increases the scope of our internal testing to cover cases that we hadn't previously tested.

**Comment by markdroth** [comment]
I still don't understand why this particular spot needs this.  The place you've added it is where the auth metadata processor plugin on the server returns control to C-core.  Do we have auth metadata processor plugins that do gRPC work?  Or is the concern here simply that when a plugin invokes the async callback into core, the entry into core might result in us needing to schedule other application callbacks?  Does that imply that we need this on every single entry point into core?  To ask that another way, in what situations would we need an ExecCtx but *not* an ApplicationExecCtx?

There are several other places where we get callbacks from application plugins back into core.  Some examples:

- plugin credentials on the client side: https://github.com/grpc/grpc/blob/master/src/core/lib/security/credentials/plugin/plugin_credentials.cc#L117
- the callbacks added in the new TLS credentials surface API in #17549
- the external resolver API being added in #16617

These are just the ones I can think of offhand; there are probably others as well.

**Comment by vjpai** [comment]
Great; it looks like we don't have C++ test coverage for some of those other cases so we probably haven't observed them. It is safe to go ahead and add them though so I can expand this PR. Many ExecCtx's need an ApplicationCallbackExecCtx before them, but many don't. For example, the ExecCtx for things like slice_buffer_unref won't trigger any application work no matter what, so it doesn't need ApplicationCallbackExecCtx coverage. The timer thread and executor thread use long-lived ExecCtx's (that live the full duration of the thread) but empty it in each iteration of their main loop, so we wouldn't want the ApplicationCallbackExecCtx to outlive the ExecCtx in that case (but we would want one in their main loops).

In this particular case, the on_md_processing_done causes a new server RPC to be published, which triggers a method handler for that RPC.

**Comment by vjpai** [comment]
I take back one of my comments. We do provide the facility to invoke a user-provided destruction function in slice unreffing; as a result, we could consider pushing this to the ApplicationCallbackExecCtx (it currently doesn't even run on the ExecCtx but rather just executes inline)

**Comment by vjpai** [comment]
I went through all instantiations of ExecCtx in src/core and added ApplicationCallbackExecCtx for any that _might_ be a trigger for core callback API usage (essentially, anything that I couldn't rule out).

**Comment by markdroth** [comment]
It looks like we're still not covering the callbacks added in the new TLS credentials surface API in #17549.  Do we need it there?

More generally, it seems a little redundant that we need an `ApplicationExecCtx` in almost all of the places where we need a normal `ExecCtx`.  Instead of having a separate object for this, have you considered simply storing a list of application callbacks in the `ExecCtx` to be invoked after the internal callbacks?

**Comment by vjpai** [comment]
So I guess I should clarify that ApplicationCallbackExecCtx is meant for resolving repeated core re-entrances that trigger callbacks from the callback API. In the case of #17549, the callbacks are not part of the callback API (similar to the callbacks in the Slice API). So #17549 doesn't introduce any of the callbacks that that ExecCtx format targets. We may want to expand ApplicationCallbackExecCtx to cover other application callbacks (such as the Slice API above) but that's beyond the scope of the current project or testing. I'm specifically looking for scenarios where a core entrance can cause a cq_end_op to get triggered.

**Comment by vjpai** [comment]
And to address the 2nd comment: the reason that this is currently separate from ExecCtx is that ExecCtx is still stackable, and that'll cause a problem for direct use with application callbacks (stack crashes like we had been seeing before). It may be possible to unify them in many of the use cases but the end result will be a hybrid structure that is part stackable and part pass-through. It is also not directly possible to unify them in the cases of the timer thread and executor thread ExecCtx that need to outlive the ApplicationCallbackExecCtx but get flushed.

**Comment by markdroth** [comment]
> It is also not directly possible to unify them in the cases of the timer thread and executor thread ExecCtx that need to outlive the ApplicationCallbackExecCtx but get flushed (I can take it as an AI to see if this is possible with refactoring though)

I assume those threads will go away as we move to EventManager-based polling.  Or will we just wind up having the same problem in EventManager threads?

**Comment by vjpai** [comment]
I think you're definitely right for timing and the offload-features of executor but I know a lot less about how the EM affects the executor as it is used for resolving.

**Pull request merged**
