### PR TITLE
xds failover locality handling

### PR DESCRIPTION
**Pull request by AspirinSJL**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/19981)

### CODE REVIEW

**Comment by AspirinSJL** [comment]
I need to add more tests, clean the added tests, and clean the code more. But overall this is ready for review. Thanks!

**Comment by guantaol** [comment]
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds.cc, line 2549 at r10](https://reviewable.io/reviews/grpc/grpc/19981#-LoaBMUl7VDatKKsv8Qc:-Low8Nmh64rlx0WWLGuN:bwrv9ot) ([raw file](https://github.com/grpc/grpc/blob/88a05b6ed61a4e99c5c9b501d6c30e2e6bc1d70f/src/core/ext/filters/client_channel/lb_policy/xds/xds.cc#L2549)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

@guantaol, if we have a single thread set two timers for exact same time, do we have a guarantee that the callbacks for those timers will run in the order in which the timers were scheduled?  Note that I am asking about what guarantee the C-core timer API provides, regardless of the underlying platform or implementation.
</blockquote></details>

Juanli is the owner of C-core timers, so she may be more authoritative to confirm this.

In my check, we have no such guarantee on the execution order in the timer API.

**Comment by veblush** [comment]
The reason "Bazel RBE UBSAN C/C++" fails is related with this [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66017) and because this is a bug of libstdc++, solution might be either i) upgrading version of gcc for this to 5.2 or later with the fix or ii) disabling ubsan test on this.

**Comment by AspirinSJL** [comment]
@veblush Thanks! I disabled UBSAN on this test as a workaround.

**Comment by AspirinSJL** [comment]
Interop ALTS Tests (internal CI): https://github.com/grpc/grpc/issues/20384
Interop Cloud-to-Prod Tests (internal CI): https://github.com/grpc/grpc/issues/20395

**Pull request merged**
