### PR TITLE
remove redudant optional keyword in proto3

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by murgatroid99** [comment]
There is an existing pull request (#1579) to change the PHP proto to `syntax = "proto2";`, so you probably shouldn't change that one.

**Comment by yang-g** [comment]
Thanks for the headsup. reverted.

**Comment by yang-g** [comment]
green

**Comment by tbetbetbe** [comment]
LGTM; This PR has a ruby label, just curious as to why that is?

**Comment by tbetbetbe** [comment]
ah - it will be because it's the proto file in the ruby folder :+1: )

**Pull request merged**
