### PR TITLE
Global channel args mutator when creating a client channel

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by markdroth** [comment]
This looks like a good API.  Can you please add a test for it?

**Comment by yang-g** [comment]
Done. PTAL. Thanks @markdroth

**Comment by yang-g** [comment]
Test failure: #20355

**Comment by yihuazhang** [comment]
@yang-g The global channel arg mutator will also take effect on subchannels since the global args set on `grpc_channel` will get propagated to its subchannel's. Is it correct?

**Comment by yang-g** [comment]
Right. It is set on client channels and then propagated to the subchannels so that it can be applied to fds.

**Pull request merged**
