### PR TITLE
Backport #14956 and #14987

### PR DESCRIPTION
**Pull request by matt-kwong**
This backports fixes for Python testing on macOS. See #14956 and #14987 for more context.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by mehrdada** [comment]
@matt-kwong there seems to be a docker failure in portability tests :(

**Comment by matt-kwong** [comment]
@mehrdada I just uploaded the new Dockerimages. I guess there are some other Dockerfile changes that haven't landed in `v1.11.x` yet.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by matt-kwong** [comment]
Failures:
Interop:  #14969
Windows: #14471 (fixed not merged into v1.11.x?)

**Comment by mehrdada** [comment]
@matt-kwong The fix is merged in v1.11.x--just confirmed. Looks like the fix wasn't perfect.

**Pull request merged**
