### PR TITLE
Counter for number of trylocks (successes/failures) and transient pop-failures in cq

### PR DESCRIPTION
**Pull request by sreecha**
Added three counters
- Number of trylock successes
- Number of trylock failures
- Number of transient pop faiilures

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by sreecha** [comment]
@ctiller - I added a couple of more counters. PTAL

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                              atm_add_per_iteration    cpu_time    real_time
---------------------------------------------------------------------  -----------------------  ----------  -----------
BM_ClosureReschedOnExecCtx                                                                      -7%         -7%
BM_EmptyCore                                                           +49%
BM_ErrorGetStatus<ErrorWithGrpcStatus>                                                          +7%         +7%
BM_ErrorGetStatus<ErrorWithHttpError>                                                           +5%         +5%
BM_ErrorGetStatusCode<ErrorWithNestedGrpcStatus>                                                +4%         +4%
BM_ErrorGetStatusCode<SimpleError>                                                              +5%         +5%
BM_ErrorHttpError<SimpleError>                                                                  +5%         +5%
BM_HasClearGrpcStatus<ErrorWithHttpError>                                                       +5%         +5%
BM_HasClearGrpcStatus<ErrorWithNestedGrpcStatus>                                                +5%         +5%
BM_HpackEncoderInitDestroy                                                                      +6%         +6%
BM_IsolatedCall_StreamingSend                                          +7%                      +4%         +4%
BM_MetadataRefUnrefStatic                                                                       -16%        -16%
BM_Pass1Core                                                           +12%
BM_Pass1Cpp                                                            +12%                     +4%         +4%
BM_PumpStreamClientToServer<InProcess>/0                               +5%
BM_PumpStreamClientToServer<InProcess>/1                               +5%
BM_PumpStreamClientToServer<InProcess>/256k                            +4%
BM_PumpStreamClientToServer<InProcess>/32k                             +4%
BM_PumpStreamClientToServer<InProcess>/4k                              +4%
BM_PumpStreamClientToServer<InProcess>/512                             +4%
BM_PumpStreamClientToServer<InProcess>/64                              +4%
BM_PumpStreamClientToServer<InProcess>/8                               +5%
BM_PumpStreamClientToServer<MinInProcess>/0                            +5%
BM_PumpStreamServerToClient<InProcess>/0                               +5%
BM_PumpStreamServerToClient<InProcess>/1                               +5%
BM_PumpStreamServerToClient<InProcess>/256k                            +4%
BM_PumpStreamServerToClient<InProcess>/32k                             +4%
BM_PumpStreamServerToClient<InProcess>/4k                              +4%
BM_PumpStreamServerToClient<InProcess>/512                             +4%
BM_PumpStreamServerToClient<InProcess>/64                              +4%
BM_PumpStreamServerToClient<InProcess>/8                               +5%
BM_PumpStreamServerToClient<MinInProcess>/0                            +5%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/0/2          +4%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/1/2          +4%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/8/2          +4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/2       +4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/1/2       +4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/8/2       +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/0        +5%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/1        +5%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/256k     +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32k      +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/4k       +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/512      +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/64       +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/8        +5%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/0     +5%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/1     +5%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/256k  +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32k   +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/4k    +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/512   +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/64    +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/8     +5%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                FILE SIZE
 ++++++++++++++ GROWING                                  ++++++++++++++
  +0.1%    +616 [None]                                      +584  +0.0%
      +0.1%    +600 [Unmapped]                                  +536  +0.0%
      +3.4%     +24 grpc_stats_counter_doc                       +24  +3.4%
      +3.4%     +24 grpc_stats_counter_name                      +24  +3.4%
  +3.1%    +208 src/core/lib/surface/completion_queue.cc    +208  +3.1%
      +181%    +197 cq_event_queue_pop                          +197  +181%
      +3.6%     +11 [Unmapped]                                   +11  +3.6%

  +0.1%    +824 TOTAL                                       +792  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_TCP_NoOpMutator_NoOpMutator__16M_2.counters.old: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.old: 1


[microbenchmarks] Performance differences noted:
Benchmark                                                              atm_add_per_iteration    cpu_time    real_time
---------------------------------------------------------------------  -----------------------  ----------  -----------
BM_EmptyCore                                                           +49%
BM_IsolatedCall_StreamingSend                                          +7%
BM_Pass1Core                                                           +12%                     +10%        +10%
BM_Pass1Cpp                                                            +12%                     +6%         +6%
BM_PumpStreamClientToServer<InProcess>/0                               +5%
BM_PumpStreamClientToServer<InProcess>/1                               +5%
BM_PumpStreamClientToServer<InProcess>/256k                            +4%
BM_PumpStreamClientToServer<InProcess>/32k                             +4%
BM_PumpStreamClientToServer<InProcess>/4k                              +4%
BM_PumpStreamClientToServer<InProcess>/512                             +4%
BM_PumpStreamClientToServer<InProcess>/64                              +4%
BM_PumpStreamClientToServer<InProcess>/8                               +5%
BM_PumpStreamClientToServer<MinInProcess>/0                            +5%
BM_PumpStreamServerToClient<InProcess>/0                               +5%
BM_PumpStreamServerToClient<InProcess>/1                               +5%
BM_PumpStreamServerToClient<InProcess>/256k                            +4%
BM_PumpStreamServerToClient<InProcess>/32k                             +4%
BM_PumpStreamServerToClient<InProcess>/4k                              +4%
BM_PumpStreamServerToClient<InProcess>/512                             +4%
BM_PumpStreamServerToClient<InProcess>/64                              +4%
BM_PumpStreamServerToClient<InProcess>/8                               +5%
BM_PumpStreamServerToClient<MinInProcess>/0                            +5%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/0/2          +4%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/1/2          +4%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/8/2          +4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/2       +4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/1/2       +4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/8/2       +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/0        +5%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/1        +5%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/256k     +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32k      +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/4k       +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/512      +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/64       +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/8        +5%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/0     +5%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/1     +5%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/256k  +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32k   +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/4k    +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/512   +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/64    +4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/8     +5%
```

**Comment by y-zeng** [comment]
Shall we merge this PR?

**Pull request merged**
