### PR TITLE
Allow suffixing interop matrix image tags with the git commit they were built at

### PR DESCRIPTION
**Pull request by apolcyn**
Background: I'm running a set of tests that use the docker images produced by the backwards compatibility interop matrix for testing in a different environment. We often need to use clients built from master instead of a release tag because of a bug fix, etc. When doing this, however, tests need to be configured to pull images from the uri of `gcr.io/grpc-testing/<language>:master` . . . . which is scary, because someone on the team can easily re-build the master tag at a new master commit and cause this external test suite to mysteriously break.

This PR adds an option to suffix the image tags in GCR with `_at_commit_<commit hash built it>` so that we can pull a stable client.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,802      Total (=)      1,964,802

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,887,468      Total (>)     10,887,464

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
@apolcyn, I'm not sure I fully understand this: 

> We often need to use clients built from master instead of a release tag because of a bug fix, etc. When doing this, however, tests need to be configured to pull images from the uri of gcr.io/grpc-testing/<language>:master

I thought that the client for interop matrix should always be built from given version with patches applied (see https://github.com/grpc/grpc/tree/master/tools/interop_matrix/patches), I don't think we should ever build from master.
I agree that what you're describing sound scary, but I think the right way is to always apply patches so that the tag becomes buildable, not adding new command line arguments - but perhaps I'm out of context here, so please correct me if needed.

Btw I think the whole process for interop_matrix is pretty cumbersome and would need some simplification.

**Comment by apolcyn** [comment]
> I thought that the client for interop matrix should always be built from given version with patches applied (see https://github.com/grpc/grpc/tree/master/tools/interop_matrix/patches), I don't think we should ever build from master.

I think the patches thing is really best suited for the case in which we want to test a certain release branch `1.x` of a certain language in the interop tests, but where there is something wrong specifically with the interop client on that branch preventing it from building and running suitably in the interop test suite. For example, the ruby client on the 1.0.x branch (the original motivation for that patches feature) works fine on its latest point release of that branch, but there is a bug in its version of protobuf that prevents the protobuf library from loading on ruby versions with more than two digits in its minor  version (which the interop client docker image happens to use); so the ruby patch on that branch changes the interop client docker image's ruby version. I tend to think that for cases in which the client has a legitimate bug that prevents it from being testable, there should probably be an actual source code patch and subsequent release of that language on that branch (with a new updated tag).

The cases where I'm using the `master` tag builds of these images is to pick up e.g. new gRPC feature additions that haven't made it into a release yet... like, for example, grpc-go's addition of the "google default credentials" API that was [merged one week ago](https://github.com/grpc/grpc-go/pull/2315).

I'm actually not sure if/who there is anyone else using the `master` tag builds... I personally would be ok getting rid of the extra command arg and having this new behavior be the default for `master` tag builds, as an alternative.

WDYT?

**Comment by jtattermusch** [comment]
I never understood what the `master` tag builds were useful for besides being confusing. :-)
Isn't the regular interop tests (from run_interop_tests.py) what should be used for testing on master?

**Comment by apolcyn** [comment]
> Isn't the regular interop tests (from run_interop_tests.py) what should be used for testing on master?

FWIW actually, the only real reasons I'm using the interop client docker images built from the interop matrix right now are:
  1) Having the client pre-built in a docker image cuts down test time a lot by skipping the build step
  2) It simplifies test environment setup: tests on new VM's just need to install docker, pull an image, run
  3) `docker pull` from GCR is (from my observations) a lot less flak than `git clone` or debian package downloads

I'm using the interop clients in these environment in ways which `run_interop_tests.py` isn't suited for, and so there is basically another `run_interop_tests` python script for this environment, which happens to use imagess built by this script. All in all I'd actually like to move away from this since it's a sort of unintended use case . . . but it's also convenient.

**Comment by apolcyn** [comment]
I'm not using the mentioned thing anymore so I have no need for this myself

**Pull request closed without merging**
