### PR TITLE
WIP: Deflaking gRPC Python's unit test `_server_ssl_cert_config_test`

### PR DESCRIPTION
**Pull request by lidizheng**
Issue #17138

Two failed unit tests:
* ServerSSLCertReloadTest**With**ClientAuth
* ServerSSLCertReloadTest**Without**ClientAuth

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,390      Total (=)      2,019,390

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,180,032      Total (<)     11,180,039

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,390      Total (=)      2,019,390

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,180,038      Total (>)     11,180,037

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,390      Total (=)      2,019,390

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,180,035      Total (<)     11,180,040

 No significant differences in binary sizes


```

**Comment by lidizheng** [comment]
Invalid

**Pull request closed without merging**
