### PR TITLE
[CMake] Link with librt only when platform toolchain has it

### PR DESCRIPTION
**Pull request by Roman-Byshliaha-Bose**
Not all POSIX platforms have rt as a separate library. QNX has rt as part of libc (same as pthreads).
Add condition to check if the library can be found and link with it only in positive scenario.

A solution for: https://github.com/grpc/grpc/issues/34254

### CODE REVIEW

**Comment by Roman-Byshliaha-Bose** [comment]
@yashykt thanks for the hint!
Done and pushed.

P.S.: sorry for late feedback.

**Comment by Roman-Byshliaha-Bose** [comment]
@yashykt anything else is required from my side?

**Comment by Roman-Byshliaha-Bose** [comment]
@yashykt @eugeneo hello folks.
Is there anything else I can do to merge this PR into main branch?
Looks like it's left without attention and I want to make sure you have everything from my side what you need.

I didn't mean to push, but what's the approximate time to merge this type of changes?

And what are the chances for it to appear in the release in the nearest future?

**Comment by Roman-Byshliaha-Bose** [comment]
@yashykt can you please take a look?

**Comment by yashykt** [comment]
Sorry for the delay, taking a look

**Review by veblush — APPROVED** [review]

**Comment by yashykt** [comment]
Thanks for the PR!

**Pull request merged**
