### PR TITLE
Fix protobuf_generate_grpc_cpp when package is not located in usr/local

### PR DESCRIPTION
**Pull request by lebdron**
Compilation fails with the following CMake arguments: `-DgRPC_PROTOBUF_PACKAGE_TYPE=CONFIG -DProtobuf_DIR=/path/to/custom/build/lib/cmake/protobuf` with errors related to not finding required `.proto` files. This happens due to `PROTOBUF_WELLKNOWN_IMPORT_DIR` set to `/usr/local/include` instead of custom source directory.
This PR fixes the issue by querying `protobuf::libprotoc` target for include directories, or using `PROTOBUF_INCLUDE_DIRS` variable directly, depending on whether protobuf targets are set.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @lebdron isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jtattermusch** [comment]
Thanks for the PR. I think you're right and this needs fixing, but there are problems with the PR:
- CMakeLists.txt is generated from template/CMakeLists.txt.template and so the sanity tests are failing.

Meanwhile, I'm working on a bigger revamp of CMakeLists.txt here https://github.com/grpc/grpc/pull/13904 (but the change is not ready yet).

**Comment by jtattermusch** [comment]
The problem was fixed by #14028.

**Comment by lebdron** [comment]
Thanks a lot, @jtattermusch !

**Pull request closed without merging**
