### PR TITLE
[C-API] server

### PR DESCRIPTION
**Pull request by tengyifei**
This PR contains all of the client additions, and serves as a starting point for async server API in C.

This PR implements all blocking APIs and a async unary call and server support for unary async. It has tests for the basic API wrapping layer and for generated code. It supersedes https://github.com/grpc/grpc/pull/7386.

To reviewers:
- `include/grpc_c` contains the public headers that the final user could see.
- `include/grpc_c/codgen` contains the private headers that must be visible to generated code, but shall not be referenced directly in user code.
- `src/c` contains the implementations of those methods defined in `include`.
- `src/compiler/c_generator.cpp` contains the bulk of `grpc_c_plugin` code generator.
- `test/c/end2end` contains end-to-end tests for the APIs.
- `examples/c` contains the `helloworld` and `routeguide` example ported to C demonstrating the usage of the API.

The tests are written in C++, since it depends on a server implementation which the C runtime does not provide yet. As a result they are subsumed under C++ tests and can be run by specifying `-l c++` in the test script.

Since this is a huge PR, I hope to split it into different functional components and have multiple reviewers each going over a section:
- Unary blocking call: `src/c/unary_blocking_call.c`
- Client streaming block call: `src/c/client_streaming_blocking_call.c`
- Server streaming block call: `src/c/server_streaming_blocking_call.c`
- Bidi streaming block call: `src/c/bidi_streaming_blocking_call.c`
- Unary async call: `src/c/unary_async_call.c`

Some useful files:
- `src/c/completion_queue.c` handles unwrapping of tags. A `call_op_set` is always used as tag during async operations. The user tag is stored in the set and is what `completion_queue_next` returns.
- `src/c/call_ops.c` handles filling a `grpc_op` array using operations specified in `call_op_set`. The library can declaratively indicate the actions to be performed in a `call_start_batch`, much like C++.

### CODE REVIEW

**Comment by tengyifei** [comment]
Additional test suite: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests_c_and_core/

All C tests for core layer have been migrated to core. The C language now denotes the C wrapper layer, much like the C++ language.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
no action here for >1 year. Closing as code is probably way out of date.

CC @vjpai @srini100

**Pull request closed without merging**
