### PR TITLE
Update debian/sid with changes from release 0_11

### PR DESCRIPTION
**Pull request by tbetbetbe**

### CODE REVIEW

**Comment by tbetbetbe** [comment]
@andrewpollock - this the right target now :)

**Comment by andrewpollock** [comment]
Are you going to do a build test, or do you just want to merge this? It should be okay to merge as it's already known code, right?

**Comment by tbetbetbe** [comment]
sorry, was offline for a bit.  I did a build test of the branch earlier.

**Comment by tbetbetbe** [comment]
Part of #3283

**Comment by jtattermusch** [comment]
@tbetbetbe, I think you should have merged only changes from the https://github.com/grpc/grpc/commits/release-0_11_0  tag, not the latest state of the 0_11 branch  - otherwise the contents of debian packages in not 100% the same as what is in our release tag (e.g. PR #3280 is in debian/sid branch now, but it's not in the release tag).

**Pull request merged**
