### PR TITLE
New C# auth API

### PR DESCRIPTION
**Pull request by jtattermusch**
-- wrap metadata credentials plugin logic from C core (introduced MetadataCredentials type)
-- wrap C core CompositeCredentials
-- modified helpers in Grpc.Auth to be able to wrap credentials objects from Google.Apis.Auth as MetadataCredentials object
-- added Credentials to call options to allow per-rpc-creds with the new API
-- HeaderInterceptor is not recommended to use for auth and authUri has been removed from it.
-- refactor interop client a bit to use the new API

### CODE REVIEW

**Comment by jtattermusch** [comment]
@tbetbetbe  FYI

**Comment by murgatroid99** [comment]
The C# tests failed to build under Linux.

**Comment by jtattermusch** [comment]
Yes, I see. Will fix, thanks for pointing that out.

**Comment by jtattermusch** [comment]
I fixed the compilation error on linux.

**Comment by jtattermusch** [comment]
I introduced the new split-type credentials api. This should be ready for review. In parallel, I also plan to update the overview doc with the new API.

**Comment by jtattermusch** [comment]
Fixed the compilation error on linux once again.

**Pull request merged**
