### PR TITLE
Android C++ Interop App

### PR DESCRIPTION
**Pull request by ericgribkoff**
gRPC C++ Android interop client. Initial focus is on instrumentation (on-device) automated testing. These can be run on an emulator or physical device with the following parameters:

```
./gradlew connectedAndroidTest \
  -Pandroid.testInstrumentationRunnerArguments.server_host=10.0.2.2 \
  -Pandroid.testInstrumentationRunnerArguments.server_port=8080 \
  -Pandroid.testInstrumentationRunnerArguments.use_tls=false
```
```
./gradlew connectedAndroidTest \
-Pandroid.testInstrumentationRunnerArguments.server_host=grpc-test.sandbox.googleapis.com \
  -Pandroid.testInstrumentationRunnerArguments.server_port=443 \
  -Pandroid.testInstrumentationRunnerArguments.use_tls=true
```

Alongside the instrumentation tests, this includes a very barebones app interface that (right now) supports only the ping-pong test. The remaining test cases from `run_interop_tests.py` to follow. The tests here reuse the interop_client.cc file for the C++ interop client, which calls `abort()` when tests fail, which kills the app entirely. Slightly poor user experience, and it makes viewing the actual error logs more difficult during instrumentation test runs. I think it'd be better to modify the behavior of the interop_client.cc code to not `abort()` on failure (or only conditionally do so, to allow different behavior on Android), but that can be considered separately from this PR.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ericgribkoff** [comment]
Thanks for the reviews.

@matt-kwong We discussed this a little offline, but wanted to get your review on the Android Kokoro build changes - it seems worth it to just run the emulator tests on PRs and on master, but does this seem like it will cause any problems? The entire Android build here took ~25 minutes, with ~7 minutes for the Firebase emulator tests.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
