### PR TITLE
Tentative fix for "error: can't start new thread" in Python tests

### LINKED ISSUE #1037: Python-tests-on-Travis sometimes fail with "error: can't start new thread"
The problem seems probabilistic and reattempting the test is usually enough to get a green result but it's annoying, time-consuming, probably something to do with how Travis constrains the tests run within it, and something that should be fixed at some point.

### PR DESCRIPTION
**Pull request by soltanmm**
Fixes #1037 (tentatively)

Is a PR to run on Travis. I'll be restarting the Python test jobs several times over the next day or two and keeping track of what happens.

Related to #1192; if this works and is merged, both PRs will be closed.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Out of curiosity, how many times did you run this locally?

**Comment by soltanmm** [comment]
At the time of this comment, once (it passed). Will run it a few more times locally.

The job is failing on Travis with a strange, strange error about 'abandonment'...

**Comment by ctiller** [comment]
Seen again.

**Comment by nathanielmanistaatgoogle** [comment]
When I look at the current Travis attempt associate with this pull request, I see "error: can't start new thread" in the failing log (thirty-five times between lines 1028 and 1889).

Starting to look into what causes the Python interpreter to be unable to start new threads...

**Comment by soltanmm** [comment]
Given the progress we're making with @ctiller's branch, closing.

**Pull request closed without merging**
