### PR TITLE
Add utf8 encoding line to generated python code

### PR DESCRIPTION
**Pull request by timonwong**

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the contribution! This is probably a good idea.

In most things related to code generation we follow the example set by [Protocol Buffers](https://github.com/google/protobuf) and I'd like to continue doing so here. When they generate `_pb2.py` files, do they include a UTF-8 encoding line? Why or why not?

@anandolee, @xfxyjwf, @acozzette, @haberman: any insight, comments, or reactions to this proposed change in the gRPC Python code generator?

**Pull request closed without merging**
