### PR TITLE
Fix ClangTidy

### PR DESCRIPTION
**Pull request by ncteisen**
Internal ClangTidy balked about this during an import

### CODE REVIEW

**Comment by ncteisen** [comment]
This error specifically: http://clang.llvm.org/extra/clang-tidy/checks/readability-inconsistent-declaration-parameter-name.html

I wonder why our clang fmt sanity did not catch this. I guess internal ClangTidy is stricter?

**Comment by ncteisen** [comment]
The param was named status in the .h and status_code in the .cc and it did not like that

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
