### PR TITLE
Some debian package manager tweaks

### PR DESCRIPTION
**Pull request by Rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

results in smaller image size.

@veblush

### CODE REVIEW

**Comment by Rajpratik71** [comment]
@jtattermusch can you trigger CI Build

**Comment by Rajpratik71** [comment]
@jtattermusch @hassox @timburks  any suggestion or fix on failing CI build , almost in every failing build got 

"Error response from daemon: pull access denied for grpctesting/"respective image", repository does not exist or may require 'docker login'.

**Comment by Rajpratik71** [comment]
> @jtattermusch @hassox @timburks any suggestion or fix on failing CI build , almost in every failing build got
> 
> "Error response from daemon: pull access denied for grpctesting/"respective image", repository does not exist or may require 'docker login'.

is there any update or suggestion on this.

**Comment by Rajpratik71** [comment]
@jtattermusch can you trigger CI Build

**Comment by jtattermusch** [comment]
While the idea of making some of the images smaller is nice in general, I don't think it's worth adding the `--no-install-recommends` flag all over the place and thus increasing the complexity. 
Also this would need re-building all the testing docker images which takes a lot of time and IMHO it's simply not worth the for for a change like this.
Also from the PR description it's not clear how much the size would decrease.

I'd be open a to more targeted approach in reducing size of some of the images (where it makes sense).
Note that some of the files are code-generated.
Also we definitely do not want to update the .md documentation.

**Pull request closed without merging**
