### PR TITLE
 Install Python 3.7 in pyenv Dockerfile

### PR DESCRIPTION
**Pull request by mehrdada**
Bump pyenv Dockerfile to Debian stretch that provides
OpenSSL 1.0.2+ which is required to build Python 3.7
and get Python 3.7 installed in the test docker
image.

Progress toward https://github.com/grpc/grpc/issues/15191

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
Failures: interop java docker & bazel

**Pull request merged**
