### PR TITLE
Introduce run_full_performance.sh and support 32core scenarios

### PR DESCRIPTION
**Pull request by jtattermusch**
-- scenarios marked as scalable  will run with 32core setup as well and results will be stored to a separate bigquery table to prevent data confusion

### CODE REVIEW

**Comment by jtattermusch** [comment]
Once this one is in, I can setup https://grpc-testing.appspot.com/job/gRPC_performance_experiment to run run_full_performance.sh.

**Comment by vjpai** [comment]
LGTM

**Comment by jtattermusch** [comment]
Before commit 75381c5  the tests were green. https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/9120/

I'll merge.

**Comment by vjpai** [comment]
LGTM.

**Pull request merged**
