### PR TITLE
Add sanity check preventing "DO NOT SUBMIT"s from submitting

### PR DESCRIPTION
**Pull request by drfloob**

### CODE REVIEW

**Comment by ctiller** [comment]
This should fail sanity tests right?

**Comment by ctiller** [comment]
Oh no... I see the file exclusion.

**Comment by drfloob** [comment]
Yes. It's currently failing only when "DO NOT SUBMIT"s are missing :-). An appropriate `exit` status coming in the next commit.

**Comment by drfloob** [comment]
> This should fail sanity tests right?
The script should cause sanity tests to fail, yes, but not for this file, or anything in `.git` or `third_party`.

I think the script now exits appropriately if grep finds anything. PTAL.

**Review by ctiller — APPROVED** [review]

**Pull request merged**
