### PR TITLE
Makes @class forward decls unconditional in generated pbrpc.h files.

### PR DESCRIPTION
**Pull request by nallohki**
Rationale:

When using GPB_GRPC_PROTOCOL_ONLY there is no guarantee that the user will actually whitelist all the interface-defined protobuf request/responses.

Unfortunately, since currently we have an Xor(forward decls, class imports) based on GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO, any user #importing the .pbrpc.h will need to manually declare these forward decls from their own import site or get a compilation error.

However, there is no danger in allowing these forward decls to exist even when using a #import, and solves this problem, so I propose this fix as a solution.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by muxi** [comment]
Basic Tests MacOS failures are already failing in master. Merging

**Pull request merged**
