### PR TITLE
Add config files for linux_extra artifacts

### PR DESCRIPTION
**Pull request by jtattermusch**
(migrating https://grpc-testing.appspot.com/job/gRPC_build_artifacts_ARM job from Jenkins to Kokoro)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Both test failures seem like infrastructure failures. The change shouldn't really affect them, so merging.

**Pull request merged**
