### PR TITLE
[Bazel] Enable grpcio-reflection to be used via Bazel

### LINKED ISSUE #31011: Fail to build grpcio_reflection when using grpc as bazel external dependence
### What version of gRPC and what language are you using?
 gRPC 1.48.0
Python

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.10
gcc 9.4.0

### What did you do?
A minimal demonstration.
```
# WORKSPACE file
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

_RULES_PYTHON_VERSION = "0.8.0"
http_archive(
    name = "rules_python",
    sha256 = "9fcf91dbcc31fde6d1edb15f117246d912c33c36f44cf681976bd886538deba6",
    strip_prefix = "rules_python-%s" % _RULES_PYTHON_VERSION,
    urls = [
        "https://github.com/bazelbuild/rules_python/archive/refs/tags/%s.tar.gz" % _RULES_PYTHON_VERSION,
    ],
)

GRPC_VERSION = "1.48.0"
http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "9b1f348b15a7637f5191e4e673194549384f2eccf01fcef7cc1515864d71b424",
    strip_prefix = "grpc-%s" % GRPC_VERSION,
    urls = [
        "https://bwh.qingtiantruck.com/externalcache/grpc/grpc/archive/v%s.tar.gz" % GRPC_VERSION,
        "https://github.com/grpc/grpc/archive/v%s.tar.gz" % GRPC_VERSION,
    ],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "grpc_python_dependencies",
    requirements = "@com_github_grpc_grpc//:requirements.bazel.txt",
)
```

running 
```
bazel build -s @com_github_grpc_grpc//src/python/grpcio_reflection/grpc_reflection/v1alpha:reflection_py_pb2_grpc
```
shows
```
ERROR: /home/user/.cache/bazel/_bazel_user/d6d247163069c06dffeeec49a63cc20f/external/com_github_grpc_grpc/src/python/grpcio_reflection/grpc_reflection/v1alpha/BUILD.bazel:24:16: output 'external/com_github_grpc_grpc/src/python/grpcio_reflection/grpc_reflection/v1alpha/reflection_pb2_grpc.py' was not created
ERROR: /home/user/.cache/bazel/_bazel_user/d6d247163069c06dffeeec49a63cc20f/external/com_github_grpc_grpc/src/python/grpcio_reflection/grpc_reflection/v1alpha/BUILD.bazel:24:16: ProtocInvocation external/com_github_grpc_grpc/src/python/grpcio_reflection/grpc_reflection/v1alpha/reflection_pb2_grpc.py failed: not all outputs were created or valid
Target @com_github_grpc_grpc//src/python/grpcio_reflection/grpc_reflection/v1alpha:reflection_py_pb2_grpc failed to build
```

### What did you expect to see?
I'm trying to use grpc_reflection on a bazel project with grpc as external dependency, which should depend on `"@com_github_grpc_grpc//src/python/grpcio_reflection/grpc_reflection/v1alpha:grpc_reflection"`. Such python library will fail to build due to  the above issue.

### PR DESCRIPTION
**Pull request by CareF**
The current `py_grpc_library` results in the wrong grpc proto python code path when grpc is a third-party source code in a Bazel project. This PR should fix it. 

fixes #31011

### CODE REVIEW

**Comment by gnossen** [comment]
Can you please add a test case [to this directory](https://github.com/grpc/grpc/tree/master/test/distrib/bazel/python)?

**Comment by CareF** [comment]
> Can you please add a test case [to this directory](https://github.com/grpc/grpc/tree/master/test/distrib/bazel/python)?

Thanks for the remainder. I realize that there are more problems with this issue than what I have already done. 
This PR fixes the pb2_grpc.py file path but yet still (with or without this PR), the generated pb2.py file tries to import beyond top-level package: 

Under `test/distrib/bazel/python/`, the generated `./bazel-bin/external/com_github_grpc_grpc/src/python/grpcio_reflection/grpc_reflection/v1alpha/reflection_pb2.py` file is 
```python
from ...com_github_grpc_grpc.src.proto.grpc.reflection.v1alpha.reflection_pb2 import *
```

with or with out this PR. This will trigger error `ValueError: attempted relative import beyond top-level package`
```
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_lm/ce2d8b67d17f2cc0fd23ca117ea353ce/execroot/python_test_repo/bazel-out/k8-fastbuild/bin/import_from_grpcio_reflection_test.runfiles/python_test_repo/import_from_grpcio_reflection.py", line 17, in <module>
    from grpc_reflection.v1alpha import reflection
  File "/home/user/.cache/bazel/_bazel_lm/ce2d8b67d17f2cc0fd23ca117ea353ce/execroot/python_test_repo/bazel-out/k8-fastbuild/bin/import_from_grpcio_reflection_test.runfiles/com_github_grpc_grpc/src/python/grpcio_reflection/grpc_reflection/v1alpha/reflection.py", line 19, in <module>
    from grpc_reflection.v1alpha import reflection_pb2 as _reflection_pb2
  File "/home/user/.cache/bazel/_bazel_lm/ce2d8b67d17f2cc0fd23ca117ea353ce/execroot/python_test_repo/bazel-out/k8-fastbuild/bin/import_from_grpcio_reflection_test.runfiles/com_github_grpc_grpc/src/python/grpcio_reflection/grpc_reflection/v1alpha/reflection_pb2.py", line 1, in <module>
    from ...com_github_grpc_grpc.src.proto.grpc.reflection.v1alpha.reflection_pb2 import *
ValueError: attempted relative import beyond top-level package
```

**Comment by CareF** [comment]
@gnossen PTAL

**Comment by CareF** [comment]
```
[1331/1338] Linking CXX executable test_core_iomgr_timer_list_test.exe

FAILED: test_core_iomgr_timer_list_test.exe

cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\test_core_iomgr_timer_list_test.dir --manifests  -- C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx86\x86\link.exe /nologo @CMakeFiles/test_core_iomgr_timer_list_test.rsp  /out:test_core_iomgr_timer_list_test.exe /implib:test_core_iomgr_timer_list_test.lib /pdb:test_core_iomgr_timer_list_test.pdb /version:0.0  /machine:X86 /debug /INCREMENTAL /subsystem:console  && cd ."

FINAL LINK: command "C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx86\x86\link.exe /nologo @CMakeFiles/test_core_iomgr_timer_list_test.rsp /out:test_core_iomgr_timer_list_test.exe /implib:test_core_iomgr_timer_list_test.lib /pdb:test_core_iomgr_timer_list_test.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console /MANIFEST /MANIFESTFILE:CMakeFiles\test_core_iomgr_timer_list_test.dir/intermediate.manifest CMakeFiles\test_core_iomgr_timer_list_test.dir/manifest.res" failed (exit code 1) with the following output:
LINK : the 32-bit linker (C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx86\x86\link.exe) failed to do memory mapped file I/O on `grpc.lib' and is going to restart linking with a 64-bit linker for better throughput

LINK : restarting link with 64-bit linker `C:\tools\msys64\usr\bin\link.exe'

link: unknown option -- i
Try '/c/PROGRA~2/MIB055~1/2017/COMMUN~1/VC/Tools/MSVC/1414~1.264/bin/Hostx86/x86/link --help' for more information.
```
seems to be completely irreverent to this PR

**Comment by CareF** [comment]
@gnossen Anything else I need to do?

**Comment by aschleck** [comment]
@gnossen is it possible to get this submitted? It's blocking our usage of grpcio-reflection so it'd be great to have this bug fixed.

**Comment by CareF** [comment]
I've been using this commit as a patch in my private projects for a while and didn't see any issues.

**Review by gnossen — APPROVED** [review]
Thanks for the contribution! Sorry for the delay.

**Comment by mering** [comment]
@CareF @gnossen The change in `bazel/python_rules.bzl` breaks us when trying to upgrade with the message:
```
output 'external/MODULE~override/path/to/MYPROTO_pb2_grpc.py' was not created
```

When reverting this change and always using `out_dir.path` compilation works fine in your code base.

Any suggestion on how to move forward?

**Pull request merged**
