### PR TITLE
[core] Add an assertion to catch the environment variable emptiness issue.

### PR DESCRIPTION
**Pull request by mikefan1991**

### CODE REVIEW

**Comment by ctiller** [comment]
We can't use the assert functions defined in log.h here because they use configuration loaded using this mechanism.

That said this seems ill advised... Isn't this a normal situation we're turning into a crash? Albeit a debug only crash, but I thing the problem we saw was a release build?

**Comment by mikefan1991** [comment]
What should be a better way to catch this instead of using assert? I would like to catch it under debug mode.

**Comment by mikefan1991** [comment]
Although we saw the issue in release build, my change here is to prevent it from going into the release build. It can catch emptiness during development.

**Comment by ctiller** [comment]
I think an assert this broad (every config var we have) is destined to be problematic - experiments and trace for example have default empty, and most often have their values empty too.

An assert is fine, but you need to narrow the scope down to just the property that you need (this specific config var is not empty?) - you also need to get the code compiling so that you can test this and demonstrate that it's doing the thing you think it is.

**Comment by mikefan1991** [comment]
> I think an assert this broad (every config var we have) is destined to be problematic - experiments and trace for example have default empty, and most often have their values empty too.
> 
> An assert is fine, but you need to narrow the scope down to just the property that you need (this specific config var is not empty?) - you also need to get the code compiling so that you can test this and demonstrate that it's doing the thing you think it is.

For this specific function, I don't see the reason of passing in two empty strings. It will clearly return nothing if both parameters are empty. So for this scenario, I think this function should not be called at the first place. WDYT?

**Comment by mikefan1991** [comment]
Hi @ctiller, can you review the PR so that I can proceed with the process. Thank you!

**Review by ctiller — COMMENTED** [review]
This looks fine so far... please address the failing tests (especially look at the sanity tests) - looks like we need to regenerate projects (`tools/buildgen/generate_projects.sh`)

**Comment by mikefan1991** [comment]
The projects are updated after running tools/buildgen/generate_projects.sh. And the only two failing tests are not related to my change. Please take a look again. Thanks!

**Review by ctiller — APPROVED** [review]

**Review by ctiller — APPROVED** [review]

**Review by ctiller — APPROVED** [review]

**Pull request merged**
