### PR TITLE
Backport #11606: Expose :authority pseudo-header to Obj-C API

### PR DESCRIPTION
**Pull request by muxi**
Backports #11606 to v1.4.x for the next release.

### CODE REVIEW

**Comment by muxi** [comment]
@thassss Hi Tommy, in this PR I am trying to cherry-pick your PR into our v1.4.x release branch for the next version of release. Per CLA requirement, could you please confirm here that you are ok about this PR? Thanks!

**Comment by thassss** [comment]
@muxi Yes, that's OK with me. Thanks!

**Comment by muxi** [comment]
Thanks!

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @thassss isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request merged**
