### PR TITLE
[PSM Interop] Enable xDS affinity test for Node

### PR DESCRIPTION
**Pull request by murgatroid99**
Similar to #34146, this will only run on master for now. This will work after grpc/grpc-node#2568 is merged.

### CODE REVIEW

**Comment by murgatroid99** [comment]
- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/faf9c782-fa05-4889-ba0c-36954ee9c80b/targets)

**Comment by sergiitk** [comment]
framework.helpers.retryers.RetryError: Retry error calling framework.test_app.client_app.XdsTestClient.find_server_channel_with_state: timeout 0:05:00 (h:mm:ss) exceeded. Last exception: ChannelNotFound: [psm-grpc-client-6cf9cc7d9c-t9sdv] Client has no READY channel with server xds:///psm-grpc-server:59164

Reason: The client couldn't connect to the server.

**Comment by murgatroid99** [comment]
Attempt 2:

- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/7b6f7876-673a-4495-9ca1-a1beebe49a18/targets)

**Comment by murgatroid99** [comment]
Attempt 3:

- [ ] [grpc/node/master/xds_k8s_lb](https://source.cloud.google.com/results/invocations/43f87149-edea-4f8b-a607-d093596da1b4/targets)

**Comment by murgatroid99** [comment]
The test passed, and I merged the implementation PR.

**Review by sergiitk — APPROVED** [review]

**Pull request merged**
