### PR TITLE
Add v1.23.0 to interop matrix

### PR DESCRIPTION
**Pull request by karthikravis**

### CODE REVIEW

**Comment by srini100** [comment]
@karthikravis, can you please confirm if the local tests are passing?

**Comment by karthikravis** [comment]
tools/interop_matrix/run_interop_matrix_tests.py -l all --release v1.23.0 --> all tests pass. Is this what you mean by local tests?

**Comment by srini100** [comment]
Yes. Wait for adhoc interop matrix test to pass before merging.

**Comment by karthikravis** [comment]
Basic Tests C/C++ MacOS: #19819
Basic Tests Node MacOS: #19422
Basic Tests ObjC iOS: #20020
Interop Cloud-to-Cloud Tests (internal CI): #19176
Interop Cloud-to-Prod Tests (internal CI): #19176

**Pull request merged**
