### PR TITLE
Upmerge 1.9.x to master

### PR DESCRIPTION
**Pull request by mehrdada**
@nicolasnoble FYI, I have left out the "Revert  #13932" out of this upmerge

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                       FILE SIZE
 ++++++++++++++ GROWING                                                                         ++++++++++++++
   +17%    +448 src/core/ext/filters/max_age/max_age_filter.cc                                     +448   +17%
      [NEW]    +388 max_idle_timer_cb                                                                  +388  [NEW]
      +195%    +160 decrease_call_count                                                                +160  +195%
      +286%    +103 increase_call_count                                                                +103  +286%
      +2.1%     +16 init_channel_elem                                                                   +16  +2.1%
      +2.1%      +3 [Unmapped]                                                                           +3  +2.1%
  +0.1%     +16 src/core/ext/filters/client_channel/client_channel.cc                               +16  +0.1%
       +13%     +11 pick_callback_done_locked                                                           +11   +13%
      +1.8%      +5 [Unmapped]                                                                           +5  +1.8%
  +0.1%     +16 src/core/lib/surface/call.cc                                                        +16  +0.1%
      +6.8%     +16 publish_app_metadata(grpc_call*, grpc_metadata_batch*, int) [clone .isra.5]         +16  +6.8%

 -+-+-+-+-+-+-+ MIXED                                                                           +-+-+-+-+-+-+-
  -0.0%     -24 [None]                                                                          +1.17Ki  +0.0%

  +0.0%    +456 TOTAL                                                                           +1.64Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
https://github.com/grpc/grpc/issues/14354

**Pull request merged**
