### PR TITLE
Re-add deprecated channel arg key to python API for backward-compatibility.

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
I don't have enough context here - the commit message says "re-add" but can you point me to a revision of records.pyx.pxi in which there ever was such a key?

Also for Python changes consider adhering to [these guidelines](http://chris.beams.io/posts/git-commit/#seven-rules).

**Comment by markdroth** [comment]
@nathanielmanistaatgoogle, see #8168 for my initial change.  See also the internal email thread from David about the breakage that prompted this PR.

**Comment by nathanielmanistaatgoogle** [comment]
That'll teach me to start the day with email in reverse-chronological order...

**Comment by nathanielmanistaatgoogle** [comment]
In the commit log message of the commit that reintroduces the field please add additional text along the lines of "this field was recently removed in 0123456789abcdef".

Also I don't yet agree that this warrants the overhead of keeping it until the next API breaking point. In the gRPC Python API so far, all channel argument keys and values are "unspecified power-user features" with no compatibility guarantees.

**Comment by markdroth** [comment]
Closing this as per internal discussion.

**Pull request closed without merging**
