### PR TITLE
Clang Tidy Codebase Part1

### PR DESCRIPTION
**Pull request by ncteisen**
Actually check all header files.

Also adds some google clang-tidy checks we happen to already follow.

Working towards #14085

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_unary_ping_pong.BM_UnaryPingPong_InProcessCHTTP2_NoOpMutator_NoOpMutator__16777216_0.counters.old: 1


[microbenchmarks] No significant performance differences
```

**Comment by matt-kwong** [comment]
From sanity:
```
2018-01-19 15:39:22,699 WAITING: ETA 2.7 sec; 107 queued, 16 jobs running, 934 complete, 0 failed (load 16.00) next: test/cpp/end2end/hybrid_end2end_test.cc @ 1.00 cpu
2018-01-19 15:39:22,761 Error while trying to load a compilation database:
Could not auto-detect compilation database for file "test/cpp/qps/driver.cc"
No compilation database found in /var/local/git/grpc/test/cpp/qps or any parent directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
165 warnings and 1 error generated.
Error while processing /var/local/git/grpc/test/cpp/qps/driver.cc.
/var/local/git/grpc/test/cpp/qps/driver.cc:36:10: error: 'src/proto/grpc/testing/services.grpc.pb.h' file not found [clang-diagnostic-error]
#include "src/proto/grpc/testing/services.grpc.pb.h"
         ^
/var/local/git/grpc/test/cpp/qps/driver.cc:552:2: error: namespace 'testing' ends with a comment that refers to a wrong namespace 'grpc' [google-readability-namespace-comments,-warnings-as-errors]
}  // namespace grpc
 ^~~~~~~~~~~~~~~~~~~
   // namespace testing
/var/local/git/grpc/test/cpp/qps/driver.cc:53:11: note: namespace 'testing' starts here
namespace testing {
          ^
Suppressed 164 warnings (164 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
1 warning treated as error

2018-01-19 15:39:22,761 FAILED: test/cpp/qps/driver.cc [ret=1, pid=10266, time=1.7sec]
```
Can you look into this failure?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by ncteisen** [comment]
Hmm very interesting... It passes locally, plus manualy looking at that file shows that the comments match up. Will keep digging

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +0.0%    +104 [None]                                               +224  +0.0%
  +0.3%     +16 src/core/ext/filters/client_channel/subchannel.cc     +16  +0.3%
      +5.5%     +19 maybe_start_connecting_locked                         +19  +5.5%
      +7.2%     +19 on_alarm                                              +19  +7.2%

  +0.0%    +120 TOTAL                                                +240  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++

 -------------- SHRINKING                    --------------
  -5.4%      -5 src/cpp/common/version_cc.cc      -5  -5.4%
     -10.9%      -5 grpc::Version[abi:cxx11]          -5 -10.9%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  +0.0%      +5 [None]                          -123  -0.0%

  [ = ]       0 TOTAL                           -128  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by matt-kwong** [comment]
I see a merge conflict for `test/cpp/qps/driver.cc`. Could that be the reason the file being picked up as an older version?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
That did work, things are green now. Hmm so if a merge is not possible, kokoro can pick up stale code? Interesting

**Comment by ncteisen** [comment]
This is good to be reviewe

**Comment by matt-kwong** [comment]
From my experience with merge conflicts, all builds should usually fail because the commit reference to test can't be created from the merge conflict. Not entirely sure if it's changed, but it seems alright now.

**Pull request merged**
