### PR TITLE
mark unreachable code with a macro

### LINKED ISSUE #2128: Remove unreachable code in C core
The C core has several instances of unreachable code, most of which are `abort();` and/or `gpr_log(GPR_ERROR, "should never reach here");`. These should be removed.

This is part of fixing #2102

### PR DESCRIPTION
**Pull request by yang-g**
Fixes #2128.

@murgatroid99 Maybe cross check with the list of xcode warnings.

### CODE REVIEW

**Comment by ctiller** [comment]
Needs merge

**Comment by yang-g** [comment]
Done.

**Comment by ctiller** [comment]
Mac build failure:

src/core/surface/call.c:438:1: error: control may reach end of
non-void function [-Werror,-Wreturn-type]

**Comment by yang-g** [comment]
Fixed. PTAL

**Pull request merged**
