### PR TITLE
Remove deprecated variant of JoinHostPort().

### PR DESCRIPTION
**Pull request by markdroth**
Also change `grpc_sockaddr_to_string()` to return `std::string`.

### CODE REVIEW

**Comment by markdroth** [comment]
The tests all look happy now.  This is ready to be reviewed.

**Comment by markdroth** [comment]
Known issues: #22760

**Comment by markdroth** [comment]
Known issue: #20703

**Comment by nicolasnoble** [comment]
We technically can't make this change without breaking Asylo too: https://github.com/google/asylo/blob/master/asylo/grpc/auth/test/h2_enclave_security_test.cc#L86-L87

**Pull request merged**
