### PR TITLE
set server/client core limits to 1 in go ping pong to lower gomaxprocs

### PR DESCRIPTION
**Pull request by apolcyn**
this would follow the findings under discussion in https://github.com/grpc/grpc-go/issues/1014

### CODE REVIEW

**Comment by xiang90** [comment]
Why do we set this to 1, not 2, not 3 or 4?

**Comment by vjpai** [comment]
Experimentally, @apolcyn has seen that the value of 1 works. Rationally speaking, the justification for using 1 is that this is a single channel, single RPC outstanding test and has no internal concurrency; the benefit of using a greater number of cores in this test would be to have greater aggregate cache capacity, but without concurrency those benefits are likely to be overwhelmed by the increased latency of cache-to-cache transfers.

**Comment by xiang90** [comment]
> Experimentally, @apolcyn has seen that the value of 1 works. 

@vjpai What do you mean by it works? I did not see the result of 2, 3, 4 anywhere. Do you mind to share it?

**Comment by apolcyn** [comment]
not planning to use this now, closing

**Pull request closed without merging**
