### PR TITLE
Bump version to v1.16.1-pre1

### PR DESCRIPTION
**Pull request by srini100**
Bump version to v1.16.1-pre1

### CODE REVIEW

**Comment by srini100** [comment]
@stanley-cheung, this is 1.16.1-pre1 targeted for Python only.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++
  +0.0%     +21 [None]                          +109  +0.0%
   +13%     +11 src/cpp/common/version_cc.cc     +11   +13%
       +28%     +11 grpc::Version[abi:cxx11]         +11   +28%

  +0.0%     +32 TOTAL                           +120  +0.0%



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,967,227      Total (>)      1,967,222

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,889,391      Total (>)     10,889,390

 No significant differences in binary sizes


```

**Comment by srini100** [comment]
objective C tests failed due to a config file on master not present on this branch.

**Pull request merged**
