### PR TITLE
Revert "Wrap strerror into a thread-safe implementation"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#25140

Creating a revert to test the theory that the PR has caused https://github.com/grpc/grpc/issues/25174

### CODE REVIEW

**Comment by jtattermusch** [comment]
Adhoc artifacts - packages - distribtest run:
https://fusion2.corp.google.com/invocations/ee109ee5-2344-41f4-91ff-d37bb2adc3bf

If it ends up being green, it proves that #25174 was caused by this PR.

**Comment by stanley-cheung** [comment]
Looks like tests are green all across!

**Comment by jtattermusch** [comment]
Yes, looks like reverting the PR would fix the distribtests again:
https://source.cloud.google.com/results/invocations/7ef620c1-5fa2-4943-aa76-9f1b8a61e762/targets/github%2Fgrpc/tests;group=tasks;test=distribtest.csharp_linux_x64_alpine_dotnetcli;row=6

**Comment by jtattermusch** [comment]
I commented on b/177904713 with some theories about what could be wrong. 

@yang-g  should we proceed with the revert? (otherwise we'll need a quick fix).

**Review by yang-g — APPROVED** [review]

**Pull request merged**
