### PR TITLE
Only cleanup the listeners when shutdown is set

### PR DESCRIPTION
**Pull request by yang-g**
For #10002

### CODE REVIEW

**Comment by dgquintas** [comment]
Please retarget this branch against https://github.com/grpc/grpc/tree/v1.2.x

**Comment by yang-g** [comment]
Test failures: #10096 #10138 #10092

**Comment by rjshade** [comment]
Should this fix be duplicated in udp_server? The code structure is very similar, including the same "if (!s->shutdown)" check:

https://github.com/grpc/grpc/blob/3cafec2f55f66e3df61569579c8259b2e5b5ee00/src/core/lib/iomgr/udp_server.c#L165

**Comment by yang-g** [comment]
@rjshade I have sent out https://github.com/grpc/grpc/pull/10292.

**Pull request merged**
