### PR TITLE
Fix data races between cq-shutdown and cq-begin-op for a pluckable cq

### PR DESCRIPTION
**Pull request by sreecha**
Also some misc cleanup.

### CODE REVIEW

**Comment by sreecha** [comment]
We saw a tsan error in one of the internal tests Yuchen ran (the race was on GPR_ASSERT(cqd->shutdown_called) line that I removed now). 

Btw, since pluck is very heavily used in sync api, I will run the sync benchmarks before merging this.

**Comment by yang-g** [comment]
Thanks.

**Comment by sreecha** [comment]
Before this change:
```
Benchmark              Time           CPU Iterations
----------------------------------------------------
BM_Pluck1Core        203 ns        202 ns    3445716 locks/iter:2 atm_cas/iter:0 atm_add/iter:5 nows/iter:0 allocs/iter:2.90215e-07
```

After this change:
```
Benchmark              Time           CPU Iterations
----------------------------------------------------
BM_Pluck1Core        205 ns        205 ns    3416548 locks/iter:2 atm_cas/iter:1 atm_add/iter:4 nows/iter:0 allocs/iter:2.92693e-07
```

One atm_add is converted to atm_cas

**Comment by sreecha** [comment]
Ran the `cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure` benchmark on my machine with and without this change and there is no visible difference in the QPS

QPS: 153184.7  (without this change)
QPS: 150421.4  (with this change)

**Pull request merged**
