### PR TITLE
[Ruby] disable BACKWARDS_COMPATIBILITY_MODE in ruby arm32 extension

### LINKED ISSUE #33921: error building grpc for armv7 - 'SYS_clock_gettime' was not declared in this scope; did you mean 'SYS_clock_gettime32' ?
### What version of gRPC and what language are you using?

1.56.2 with Ruby

### What operating system (Linux, Windows,...) and version?

I am building a docker image for armv7 (to run on a raspberry Pi)

```
FROM ruby:3.2.2-alpine3.16
```

From my macbook M2 with macOS Ventura 13.4.1 (22F82). Docker desktop 4.21.1 (114176)

for armv7 using

```
docker buildx build --push \
--file docker/Dockerfile \
--platform linux/arm/v7 \
.
```

### What runtime / compiler are you using (e.g. python version or version of gcc)

Not really sure what is expected here...?  

Ruby MRI 3.2.2 and compilers from docker image `ruby:3.2.2-alpine3.16`
gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

How I generated this bug

Clone and checkout the chatwoot repo on a branch (I produced the bug from tag v2.18.0) : https://github.com/chatwoot/chatwoot/tree/v2.18.0

(optional) To make things faster, edit the docker/Dockerfile to only install grpc (https://github.com/chatwoot/chatwoot/blob/v2.18.0/docker/Dockerfile). You can replace that file with the code below

```
# pre-build stage
FROM ruby:3.2.2-alpine3.16 AS pre-builder

# ARG default to production settings
# For development docker-compose file overrides ARGS
ARG BUNDLE_WITHOUT="development:test"
ENV BUNDLE_WITHOUT ${BUNDLE_WITHOUT}
ENV BUNDLER_VERSION=2.1.2

ARG RAILS_SERVE_STATIC_FILES=true
ENV RAILS_SERVE_STATIC_FILES ${RAILS_SERVE_STATIC_FILES}

ARG RAILS_ENV=production
ENV RAILS_ENV ${RAILS_ENV}

ENV BUNDLE_PATH="/gems"

RUN apk update && apk add --no-cache \
    openssl \
    tar \
    build-base \
    tzdata \
    postgresql-dev \
    postgresql-client \
    nodejs \
    yarn \
    git \
  && mkdir -p /var/app \
  && gem install bundler

WORKDIR /app

COPY Gemfile Gemfile.lock ./

# natively compile grpc and protobuf to support alpine musl (dialogflow-docker workflow)
# https://github.com/googleapis/google-cloud-ruby/issues/13306
# adding xz as nokogiri was failing to build libxml
# https://github.com/chatwoot/chatwoot/issues/4045
RUN apk update && apk add --no-cache build-base musl ruby-full ruby-dev gcc make musl-dev openssl openssl-dev g++ linux-headers xz vips
RUN bundle config set --local force_ruby_platform true

# fix grpc install bug
RUN gem install grpc
```

Build the docker image for armv7

```
docker buildx build --push \
--file docker/Dockerfile \
--platform linux/arm/v7 \
.
```

### What did you expect to see?

Successfull installation of grpc

### What did you see instead?

```
1321.7 [CXX]     Compiling src/core/lib/gpr/string.cc
1321.7 mkdir -p `dirname /usr/local/bundle/gems/grpc-1.56.2/src/ruby/ext/grpc/objs/opt/src/core/lib/gpr/string.o`
1321.7 g++ -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares/cares/include -Ithird_party/cares -Ithird_party/cares/cares    -DGPR_BACKWARDS_COMPATIBILITY_MODE -DGRPC_XDS_USER_AGENT_NAME_SUFFIX="\"RUBY\"" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="\"1.56.2\"" -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/utf8_range -Ithird_party/xxhash -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/usr/local/bundle/gems/grpc-1.56.2/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\"   -Ithird_party/zlib   -std=c++14   -fno-exceptions -MMD -MF /usr/local/bundle/gems/grpc-1.56.2/src/ruby/ext/grpc/objs/opt/src/core/lib/gpr/string.dep -c -o /usr/local/bundle/gems/grpc-1.56.2/src/ruby/ext/grpc/objs/opt/src/core/lib/gpr/string.o src/core/lib/gpr/string.cc
1321.7 src/core/lib/gpr/posix/time.cc: In function 'gpr_timespec now_impl(gpr_clock_type)':
1321.7 src/core/lib/gpr/posix/time.cc:79:13: error: 'SYS_clock_gettime' was not declared in this scope; did you mean 'SYS_clock_gettime32'?
1321.7    79 |     syscall(SYS_clock_gettime, clockid_for_gpr_clock[clock_type], &now);
1321.7       |             ^~~~~~~~~~~~~~~~~
1321.7       |             SYS_clock_gettime32
1321.7 make: *** [Makefile:758: /usr/local/bundle/gems/grpc-1.56.2/src/ruby/ext/grpc/objs/opt/src/core/lib/gpr/posix/time.o] Error 1
1321.7 make: *** Waiting for unfinished jobs....
1321.7 make: Leaving directory '/usr/local/bundle/gems/grpc-1.56.2'
1321.7 *** extconf.rb failed ***
1321.7 Could not create Makefile due to some reason, probably lack of necessary
1321.7 libraries and/or headers.  Check the mkmf.log file for more details.  You may
1321.7 need configuration options.
1321.7
1321.7 Provided configuration options:
1321.7 	--with-opt-dir
1321.7 	--without-opt-dir
1321.7 	--with-opt-include
1321.7 	--without-opt-include=${opt-dir}/include
1321.7 	--with-opt-lib
1321.7 	--without-opt-lib=${opt-dir}/lib
1321.7 	--with-make-prog
1321.7 	--without-make-prog
1321.7 	--srcdir=.
1321.7 	--curdir
1321.7 	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
1321.7
1321.7 extconf failed, exit code 1
1321.7
1321.7 Gem files will remain installed in /usr/local/bundle/gems/grpc-1.56.2 for inspection.
1321.7 Results logged to /usr/local/bundle/extensions/arm-linux-musleabihf/3.2.0/grpc-1.56.2/gem_make.out
```

### Anything else we should know about your project / environment?

It seems like the dockerfile already had some problems with grpc, see the docker file + this issue referenced inside : https://github.com/googleapis/google-cloud-ruby/issues/13306

### PR DESCRIPTION
**Pull request by alto-ruby**
#4998 added the compatibility mode (7 years ago) which invoking syscalls directly for clock_gettime, however it didn't mention what exact ABI issues it was fixing.

armv7 build fails with 'SYS_clock_gettime' was not declared. Disable GPR_BACKWARDS_COMPATIBILITY_MODE fix the build armv7 build. Other environments are also built without issues.

fixes #33921

### CODE REVIEW

**Comment by apolcyn** [comment]
We need `GPR_BACKWARDS_COMPATIBILITY_MODE` in order to not depend on recent kernel or libc APIs. That way, we can continue to support older libc's even while compiling on a newer distro (this is needed for portability of our precompiled packages).

Can we come up with a more narrow solution: e.g. only affect armv7, and not other builds? Or a workaround for this specific clock gettime issue on armv7?

**Comment by alto-ruby** [comment]
ping @apolcyn

**Comment by sampajano** [comment]
@alto-ruby Hihi, there's a merge conflict now, could you resolve it? Then we can merge it :)

**Comment by alto-ruby** [comment]
BACKWARDS_COMPATIBILITY_MODE is completely removed in #35602 after all, this PR is not needed.

**Pull request closed without merging**
