### PR TITLE
add ruby subclasses of bad status for each GPRC status code

### PR DESCRIPTION
**Pull request by apolcyn**
fixes https://github.com/grpc/grpc/issues/7253

### CODE REVIEW

**Comment by murgatroid99** [comment]
You should also change the client code to actually use these status subclasses. I would recommend adding a static factory function to `BadStatus` that creates the correct subclass based on the code.

**Comment by apolcyn** [comment]
test this please

**Comment by apolcyn** [comment]
test failures on:
- linux PR: https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1200/
- tsan c++ PR: https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/538/
- interop PR: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/9866/
- performance PR https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/7769/ (error on report upload)

I believe these tests were last ran before the fix-it was done though, re-running the tests

**Comment by apolcyn** [comment]
jenkins: test this please

**Comment by apolcyn** [comment]
failures on the following the new and known tests:

* performance PR: known issue in https://github.com/grpc/grpc/issues/9047
* interop PR: known issue in https://github.com/grpc/grpc/issues/9092
* tsan c++ PR: known issue in https://github.com/grpc/grpc/issues/9046
* tsan c++ PR: new issue https://github.com/grpc/grpc/issues/9117
* linux PR: new issue https://github.com/grpc/grpc/issues/9116

**Pull request merged**
