### PR TITLE
Fix CMake (and probably other build systems) build of grpc++

### PR DESCRIPTION
**Pull request by per-gron**
Here comes a very very small PR (except for generated code, the relevant changes are in `build.yaml`) with a very very long description. I'm sorry about the wordiness, but I don't know how to briefly explain this given that I am not familiar with this code base and don't know the person who will review this. For a brief description, refer to the commit messages.

As far as I can tell, the `CMakeFiles.txt` (and probably `Makefile` and VS solution) files generated by the `build.yaml` processing are broken in the following way: The build files are syntactically correct, and they describe a build that can be built, but the resulting C++ libraries (`grpc++`, `grpc++_cronet`) are unusable.

One way to see that something fishy is going on is to look at the current `CMakeLists.txt` file and observe that many files, for example `src/core/lib/channel/channel_args.c` are listed as part of several libraries. More precisely, all files in the `grpc_base` "filegroup" are listed several times.

The libraries that contain `src/core/lib/channel/channel_args.c` are: `grpc`, `grpc_cronet`, `grpc_test_util`, `grpc_unsecure`, `grpc++`, `grpc++_cronet` and `grpc++_unsecure`.

Listing implementation files in more than one CMake target is not really normal, but it is in itself not really an issue. However, there are also CMake statements like this:

    target_link_libraries(grpc++
      ...
      grpc
      ...
    )

There are similar ones for the other C++ libraries.

What this does is that it tells CMake that whenever someone who actually wants to use `grpc++` and does so with `target_link_libraries(my_awesome_app grpc++)`, it should link not only against `libgrpc++.a` but also against `libgrpc.a` (and its dependencies).

But `libgrpc++.a` and `libgrpc.a` are both linked with `channel_args.o`, so when `my_awesome_app` is linked it will fail with a duplicate symbol error.

Now, this is not only a problem with that CMake links two things that aren't actually intended to be linked at the same time: Even if the settings are changed so that `my_awesome_app` is linked only with `libgrpc++.a`, the build will fail because `my_awesome_app` depends on symbols from `src/core/lib/surface/init.c`, but that actually is not present in the `grpc++` target.

So: When gRPC is built with the provided `CMakeLists.txt`, it will create `libgrpc++.a` and `libgrpc.a`. Some symbols are in both of them, some symbols (stuff from `init.c`) are only in `libgrpc.a` and the C++ stuff is only in `libgrpc++.a`. Short of some serious messing around with these static libraries there is nothing I can do to use them, they are just wrong.

---

I've looked at `build.yaml` and the associated Python code, and at the `BUILD` file (which does not seem autogenerated) and tried to understand the situation. What I have found is:

* The `build.yaml` file has a "filegroup" concept that is a little bit like a library in that it is a group of files with dependencies, but it does not correspond to an actual build target.
* The `BUILD` file does not have "filegroups"; most of the `build.yaml` filegroups are declared as `grpc_cc_library()`s.
* It seems like the intention is that programs using C++ gRPC should need to link against SSL, Protobuf and `gpr` separately.
* I can't tell if the intention is that programs using C++ gRPC should need to link against both `libgrpc++.a` and `libgrpc.a` or only `libgrpc++.a`

Based on this, I have concluded that I believe that it is not against what the authors of this system intended to make it so that programs using C++ gRPC should need to link against both `libgrpc++.a` and `libgrpc.a`.

Given that belief, I think the line in `build.yaml` that states that the `grpc++_base` filegroup should use (aka include) `grpc_base` is wrong. It is sufficient that the lib entries in that file say that the things that have the `grpc++_base` filegroup depend (as in `target_link_libraries` in CMake) on `grpc`.

Removing that one line from `build.yaml` makes the generated `CMakeLists.txt` file have far fewer duplicates, and (more importantly) makes it possible for my CMake based application to use gRPC.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
test this please

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by per-gron** [comment]
@jtattermusch The build seems to be red partly because this PR is broken and partly due to flaky tests. I am about to upload a fix for the PR brokenness. Here is my understanding of how it's broken and an appropriate way to fix it:

This PR currently breaks the `tools/run_tests/sanity/check_sources_and_headers.py` check: The `grpc++_base` filegroup (or target, as this script calls it in its error output) has files that `#include` stuff from the `grpc_base` filegroup.

I tried to fix this by just adding a `deps` dependency from the `grpc++_base` filegroup to the `grpc` lib. This works for the `libgrpc++.a` target, but that pulls in ssl stuff into the `grpc++_unsecure` target and breaks it with duplicate symbols.

I tried to fix that by changing the added `deps` dependency from `grpc` to `grpc_base`, but that is not valid because `grpc_base` is not a `lib`.

---

So: The `check_sources_and_headers.py` script requires that `grpc++_base` has a `uses` or a `deps` dependency to `grpc_base`. Because of the reasons outlined in the initial PR comment, it can't be a `uses` dependency. Because `grpc_base` is a filegroup and not a lib, it can't be a `deps` dependency either. A `deps` dependency could point to `grpc` instead, which makes the `grpc++` target work but it breaks the `grpc++_unsecure` target.

I think a good way to fix this is to make `grpc_base` a lib instead of a filegroup. That way, both secure and `*_unsecure` targets can depend on it, and the `grpc++`/`grpc++_unsecure` targets can depend on it without pulling in all the `gprc_base` .o files in their static library outputs, which causes duplicate symbol errors. Furthermore, this change makes the build more similar to how the Bazel `BUILD` file is structured, where everything is a lib.

---

Another note: The `grpc++_cronet` target is in master broken too, because of essentially the same reasons as `grpc++`. The new commits that I'm just pushing fixes `grpc++_cronet` too.

**Comment by jtattermusch** [comment]
Thanks for the PR. See my responses inline.

On Thu, May 11, 2017 at 11:24 PM, Per Grön <notifications@github.com> wrote:

> Here comes a very very small PR (except for generated code, the relevant
> changes are in build.yaml) with a very very long description. I'm sorry
> about the wordiness, but I don't know how to briefly explain this given
> that I am not familiar with this code base and don't know the person who
> will review this. For a brief description, refer to the commit messages.
>
> As far as I can tell, the CMakeFiles.txt (and probably Makefile and VS
> solution) files generated by the build.yaml processing are broken in the
> following way: The build files are syntactically correct, and they describe
> a build that can be built, but the resulting C++ libraries (grpc++,
> grpc++_cronet) are unusable.
>
> One way to see that something fishy is going on is to look at the current
> CMakeLists.txt file and observe that many files, for example
> src/core/lib/channel/channel_args.c are listed as part of several
> libraries. More precisely, all files in the grpc_base "filegroup" are
> listed several times.
>
> The libraries that contain src/core/lib/channel/channel_args.c are: grpc,
> grpc_cronet, grpc_test_util, grpc_unsecure, grpc++, grpc++_cronet and
> grpc++_unsecure.
>
In case of grpc, grpc_cronet and grpc_unsecure this is intended. These
libraries are basically different flavors or the gRPC C core library.

I agree that for others (specifically the C++ libraries) this is
questionable. For the grpc_test_utils it probably doesn't matter because
it's not a public library, it only there to make it easier to build tests.


> Listing implementation files in more than one CMake target is not really
> normal, but it is in itself not really an issue. However, there are also
> CMake statements like this:
>
> target_link_libraries(grpc++
>   ...
>   grpc
>   ...
> )
>
> There are similar ones for the other C++ libraries.
>
> What this does is that it tells CMake that whenever someone who actually
> wants to use grpc++ and does so with target_link_libraries(my_awesome_app
> grpc++), it should link not only against libgrpc++.a but also against
> libgrpc.a (and its dependencies).
>
> But libgrpc++.a and libgrpc.a are both linked with channel_args.o, so
> when my_awesome_app is linked it will fail with a duplicate symbol error.
>
> Now, this is not only a problem with that CMake links two things that
> aren't actually intended to be linked at the same time: Even if the
> settings are changed so that my_awesome_app is linked only with
> libgrpc++.a, the build will fail because my_awesome_app depends on
> symbols from src/core/lib/surface/init.c, but that actually is not
> present in the grpc++ target.
>
> So: When gRPC is built with the provided CMakeLists.txt, it will create
> libgrpc++.a and libgrpc.a. Some symbols are in both of them, some symbols
> (stuff from init.c) are only in libgrpc.a and the C++ stuff is only in
> libgrpc++.a. Short of some serious messing around with these static
> libraries there is nothing I can do to use them, they are just wrong.
> ------------------------------
>
> I've looked at build.yaml and the associated Python code, and at the BUILD
> file (which does not seem autogenerated) and tried to understand the
> situation. What I have found is:
>
>    - The build.yaml file has a "filegroup" concept that is a little bit
>    like a library in that it is a group of files with dependencies, but it
>    does not correspond to an actual build target.
>    - The BUILD file does not have "filegroups"; most of the build.yaml
>    filegroups are declared as grpc_cc_library()s.
>    - It seems like the intention is that programs using C++ gRPC should
>    need to link against SSL, Protobuf and gpr separately.
>    - I can't tell if the intention is that programs using C++ gRPC should
>    need to link against both libgrpc++.a and libgrpc.a or only libgrpc++.a
>
> I think programs that are using gRPC C++ should link against both
libgrpc++ and libgrpc.


>
> Based on this, I have concluded that I believe that it is not against what
> the authors of this system intended to make it so that programs using C++
> gRPC should need to link against both libgrpc++.a and libgrpc.a.
>
> Given that belief, I think the line in build.yaml that states that the
> grpc++_base filegroup should use (aka include) grpc_base is wrong. It is
> sufficient that the lib entries in that file say that the things that have
> the grpc++_base filegroup depend (as in target_link_libraries in CMake)
> on grpc.
>
> Removing that one line from build.yaml makes the generated CMakeLists.txt
> file have far fewer duplicates, and (more importantly) makes it possible
> for my CMake based application to use gRPC.
>

I think you are right in terms of removing grpc_base from shouldn't be part
of grpc++_base - so removing the 'uses' is correct. I am less convinced
about other changes being done in this PR (what does it fix to change
grpc_base from a filegroup to a library?) AFAIK, grpc_base is defined as a
filegroup to avoid having grpc_base library generated by the makefile.

**Comment by jtattermusch** [comment]
Also, can you please rebase -i upstream/master and regenerate the files again? There are merge conflicts.

**Comment by jtattermusch** [comment]
test this please

**Comment by per-gron** [comment]
@jtattermusch Thanks a bunch for the review!

For my purposes, the ["uses" change](https://github.com/grpc/grpc/pull/11097/commits/627d2973f75500a818ef294bf842a0d3728c1f3e) itself is enough.

As you say, this PR changes the makefiles to generate a `libgrpc_base.a` static library (which applications must link against). For my purposes, since CMake keeps track of these dependencies, it doesn't matter but I totally understand if you don't want it.

The reason I did the additional changes is that the `tools/run_tests/sanity/check_sources_and_headers.py` script, which is run as part of your CI tests, breaks if only the `uses` line is removed, because the `grpc++_base` filegroup has dependencies to files in `grpc_base` and without the `uses` line, they become undeclared dependencies, which that script prohibits.

Making `grpc_base` a library was the way I could come up with that silences that error. Do you have any other suggestions for how this can be fixed?

Idea: I could make a `grpc_base_headers` filegroup, and add it to `uses` of grpc_base and `grpc++_base`. I think that could silence the errors. What do you think?

I'll rebase once I know what to do.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
Actually, the problem with "uses" and symbol duplication was already fixed properly here: https://github.com/grpc/grpc/pull/11247/files

Thanks for the PR anyway!

**Pull request closed without merging**
