### PR TITLE
Upgrade to bazel 1.0.1

### PR DESCRIPTION
**Pull request by eytankidron**
This pull request is based off of https://github.com/grpc/grpc/pull/20558 with the following additions:
* Remove the toolchains //third_party/toolchains:local and //third_party/toolchains:local_large.
* Remove the platforms :rbe_ubuntu1604, :rbe_ubuntu1604_large, :local and :local_large.
* No longer inherit from @rbe_default//config:platform but instead use it directly. It is now the *only* non-windows platform.
* When creating @rbe_default//config:platform directly with rbe_autoconfig, set dockerAddCapabilities and dockerPrivileged directly in the exec_properties field. No need to set dockerNetwork to "off" and dockerSiblingContainers to false since these are the defaults.
* Also set gceMachineType = "n1-highmem-2" on the default platform. This value can be overridden by specific targets that want to use LARGE_MACHINE. 
* Use create_exec_properties_dict where appropriate.
* Use custom_exec_properties to define LARGE_MACHINE.

Note that these changes do not address (at least not intentionally) the reasons because of which https://github.com/grpc/grpc/pull/20558 was rolled back in https://github.com/grpc/grpc/pull/20611.

Also, I wasn't able to test thoroughly that this PR does not break any existing targets. I was not able to run anything on windows/mac and I also don't have access to gRPC's RBE setup.

### CODE REVIEW

**Comment by jtattermusch** [comment]
@eytankidron  I'm trying to get https://github.com/grpc/grpc/pull/20732 in first - it's mostly done but I'm facing a problem with std::regex bug in RBE docker image (I think).

**Comment by eytankidron** [comment]
> @eytankidron I'm trying to get #20732 in first - it's mostly done but I'm facing a problem with std::regex bug in RBE docker image (I think).

Sounds good. When that PR is merged, the next step could be to implement these platform/toolchain simplifications.

**Comment by jtattermusch** [comment]
@eytankidron  #20732 has been merged, can you please rebase?

**Comment by eytankidron** [comment]
> @eytankidron #20732 has been merged, can you please rebase?

I am going to create a new pull request which only has the platform/constraints changes and does not attempt to migrate from Bazel 1.0.0 to Bazel 1.0.1 because that just adds noise.

Stay tuned.

**Comment by jtattermusch** [comment]
Superseded by https://github.com/grpc/grpc/pull/20862

**Pull request closed without merging**
