### PR TITLE
Fix spinlock bug in poll engine

### PR DESCRIPTION
**Pull request by kpayson64**
When a socket gets shutdown, polling it will always return SIGHUP, but we never remove it from the pollset.

This causes poll based servers to enter spinlock as soon as a client disconnects.

### CODE REVIEW

**Comment by kpayson64** [comment]
Fixes #9688

**Comment by sreecha** [comment]
@kpayson64 - Is there a reason why `fd_orphan` was not called on that fd ? (because calling `fd_orphan` would ensure that the fd is removed from the pollset)

**Comment by kpayson64** [comment]
@sreecha 
I'm not sure where fd_orphan should be called.  AFAICT, in order to actually do the pollset removal, we would need to pass in a closure that does that work, and I didn't see any functions capable of removing an fd from a pollset.

**Comment by sreecha** [comment]
@kpayson64: 
I am also not very clear when `grpc_fd_orphan` should be called. I always thought it should be called whenever the user of that fd wants to "close" the fd (currently if you look at the code, tcp server / client call this).. I don't know when we expect the caller to call `grpc_fd_shutdown` versus `grpc_fd_orphan` (I am clear what they do..I just don't know what expectation the polling engine has from its callers). This is a @ctiller question!

However, when this is called, the FD is removed from the pollset:
Calling `grpc_fd_orphan` marks the fd as orphaned (on the `grpc_fd` struct) and in the `pollset_work()` function, when constructing the list of fds to poll, we do check if an fd is orphaned and NOT add it to the pollset (see below)

``` C

      fd_count = 0;
      pfd_count = 2;
      pfds[0].fd = GRPC_WAKEUP_FD_GET_READ_FD(&global_wakeup_fd);
      pfds[0].events = POLLIN;
      pfds[0].revents = 0;
      pfds[1].fd = GRPC_WAKEUP_FD_GET_READ_FD(&worker.wakeup_fd->fd);
      pfds[1].events = POLLIN;
      pfds[1].revents = 0;
      for (i = 0; i < pollset->fd_count; i++) {
        if (fd_is_orphaned(pollset->fds[i])) { // <<<Sree:  Skip adding orphaned fds
          GRPC_FD_UNREF(pollset->fds[i], "multipoller");
        } else {
          pollset->fds[fd_count++] = pollset->fds[i];
          watchers[pfd_count].fd = pollset->fds[i];
          GRPC_FD_REF(watchers[pfd_count].fd, "multipoller_start");
          pfds[pfd_count].fd = pollset->fds[i]->fd;
          pfds[pfd_count].revents = 0;
          pfd_count++;
        }
      }
      pollset->fd_count = fd_count;   // <<<Sree: Updating the fd_count 
      gpr_mu_unlock(&pollset->mu);
...
```

**Comment by kpayson64** [comment]
Summarizing the outcome here:

The real cause of the error was calling ```grpc_completion_queue_next()``` after a ```grpc_call``` had completed, but not been destroyed.  The call's fd will only be removed from the pollset after destruction.

This restriction only applies to the poll() engine.

**Comment by sreecha** [comment]
Thanks @kpayson64. 

To summarize the other open question we had regarding `fd_orphan` versus `fd_shutdown`:
- The layers using the polling engine MUST call `grpc_fd_orphan` when they are done with the fd. Once `grpc_fd_orphan` is called, the fd MUST not be used anymore.  

- `grpc_fd_shutdown` MAY be called on the fd if the layers using the polling engine want to cancel any pending read/write closures on the fd (i.e the closures would be called with a failure) AND to prevent any new read/write closures from being added to the fd.

**Pull request closed without merging**
