### PR TITLE
Added GRPC_ERROR_IS_ABSEIL_STATUS

### PR DESCRIPTION
**Pull request by veblush**
Main changes
- Added `GRPC_ERROR_IS_ABSEIL_STATUS` flag to set `grpc_error_handle` as the alias of `absl::Status`
- Added `grpc_error` compatible functions such as `grpc_error_set_int` for `absl::Status` to error.h so that the existing code can work with both `grpc_error` and `absl::Status`.

Extra changes
- Used C++ standard style for the field names of `StatusIntProperty` and `StatusStrProperty`
- Added low-level status functions such as `StatusAllocPtr` only for migration purpose.

Although all required functions are implemented in this PR, gRPC isn't able to build with `GRPC_ERROR_IS_ABSEIL_STATUS` enabled since there are a couple of cases where grpc_error_handle should be `grpc_error*` so those are addressed by separate PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/26078)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks good!  Only a few minor comments.

Please let me know if you have any questions.  Thanks!

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26078#-:-MZKBNx-036mrXgq5kNJ:b-as20iy)* status: all files reviewed, 4 unresolved discussions (waiting on @veblush)

___
*[src/core/lib/gprpp/status_helper.h, line 144 at r1](https://reviewable.io/reviews/grpc/grpc/26078#-MZKAP658xXACK_s6job:-MZKAP658xXACK_s6joc:b-glas0y) ([raw file](https://github.com/grpc/grpc/blob/25e4d5c97f9ea430761dcda928529dfa78427b06/src/core/lib/gprpp/status_helper.h#L144)):*
> ```objc
> 
> /// The same value of grpc_core::internal::StatusAllocPtr(absl::OkStatus())
> static constexpr uintptr_t OK_STATUS_PTR = 0;
> ```

This should be named `kOkStatusPointer`.
___
*[src/core/lib/gprpp/status_helper.h, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/26078#-MZKAXtf9AXLIlN42G_R:-MZKAXtf9AXLIlN42G_S:b-1c9ojh) ([raw file](https://github.com/grpc/grpc/blob/25e4d5c97f9ea430761dcda928529dfa78427b06/src/core/lib/gprpp/status_helper.h#L149)):*
> ```objc
> /// This ptr can be used to get Status later and should be freed by
> /// StatusFreePtr. This shouldn't be used except migration purpose.
> uintptr_t StatusAllocPtr(absl::Status s);
> ```

I assume these functions are intended to address the lame filter use-case?
___
*[src/core/lib/iomgr/error.cc, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/26078#-MZK9_fZ2HoVCm8Khm8i:-MZK9_fZ2HoVCm8Khm8j:b-nbx65z) ([raw file](https://github.com/grpc/grpc/blob/25e4d5c97f9ea430761dcda928529dfa78427b06/src/core/lib/iomgr/error.cc#L60)):*
> ```cpp
>                                 size_t children_count, absl::Status* children) {
>   absl::Status s = StatusCreate(code, msg, location, {});
>   for (size_t i = 0; i < children_count; ++i) {
> ```

Why don't we just pass this list to `StatusCreate()`?
___
*[src/core/lib/iomgr/error.cc, line 98 at r1](https://reviewable.io/reviews/grpc/grpc/26078#-MZK9rjD5XqQ6Nscasq_:-MZK9rjD5XqQ6Nscasqa:byxrs3n) ([raw file](https://github.com/grpc/grpc/blob/25e4d5c97f9ea430761dcda928529dfa78427b06/src/core/lib/iomgr/error.cc#L98)):*
> ```cpp
>                                      grpc_error_ints which, intptr_t value) {
>   grpc_core::StatusSetInt(
>       &src, static_cast<grpc_core::StatusIntProperty>(which), value);
> ```

We probably need a set of `static_assert()` statements that ensures that the two sets of enum values match up.  Otherwise, someone could change one of them without changing the other.

**Review by veblush — COMMENTED** [review]
Thank you for the quick review!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26078#-:-MZKOTM83SxKU_XKwNpC:b-u8jprg)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/gprpp/status_helper.h, line 144 at r1](https://reviewable.io/reviews/grpc/grpc/26078#-MZKAP658xXACK_s6job:-MZKOVs_Aoi7st97bp1T:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/25e4d5c97f9ea430761dcda928529dfa78427b06/src/core/lib/gprpp/status_helper.h#L144)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be named `kOkStatusPointer`.
</blockquote></details>

Done.
___
*[src/core/lib/gprpp/status_helper.h, line 149 at r1](https://reviewable.io/reviews/grpc/grpc/26078#-MZKAXtf9AXLIlN42G_R:-MZKLSYn02-FX5NemTBe:bm37txj) ([raw file](https://github.com/grpc/grpc/blob/25e4d5c97f9ea430761dcda928529dfa78427b06/src/core/lib/gprpp/status_helper.h#L149)):*
> ```
>  OK_STATUS_PTR 
> ```

Yes, this could be a solution for those edge cases. But this will be a last resort if there are no viable solutions.
___
*[src/core/lib/iomgr/error.cc, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/26078#-MZK9_fZ2HoVCm8Khm8i:-MZKJz479BUStgfIl_9f:b-iyup2n) ([raw file](https://github.com/grpc/grpc/blob/25e4d5c97f9ea430761dcda928529dfa78427b06/src/core/lib/iomgr/error.cc#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why don't we just pass this list to `StatusCreate()`?
</blockquote></details>

There is no standard way to create a std::initialzer_list from a C list. If I really want to use it, we might have to create a vector or something from a C list first but it introduces an additional heap allocation, though.
___
*[src/core/lib/iomgr/error.cc, line 98 at r1](https://reviewable.io/reviews/grpc/grpc/26078#-MZK9rjD5XqQ6Nscasq_:-MZKOK4D1wdXol4kkiQu:b-2lnfrf) ([raw file](https://github.com/grpc/grpc/blob/25e4d5c97f9ea430761dcda928529dfa78427b06/src/core/lib/iomgr/error.cc#L98)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We probably need a set of `static_assert()` statements that ensures that the two sets of enum values match up.  Otherwise, someone could change one of them without changing the other.
</blockquote></details>

I rather changed the error enum to use status enum so that they have identical values.

**Review by markdroth — APPROVED** [review]
Looks great!

> Reviewed 1 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26078#-:-MZOqH2sDy0wszoYVLWn:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @veblush)

**Comment by yashykt** [comment]
@veblush I believe this has caused a CBF on Android

**Pull request merged**
