### PR TITLE
Adding util to get a NULL terminated string from a slice.

### PR DESCRIPTION
**Pull request by jboeuf**

### CODE REVIEW

**Comment by ctiller** [comment]
What's the use case?

**Comment by jboeuf** [comment]
A bunch of test code where I have to print the contents of a slice.

**Comment by ctiller** [comment]
No chance gpr_hexdump does the trick?

I worry about us missing some bad problem due to embedded nulls.

**Comment by jboeuf** [comment]
mmmm. Not really, I'd like this data to be readable by a human being...
For the embedded nulls, it's kind of the same with C++
std::string::c_str(), isn't it? There may be some in the middle but at
least you know that you have one at the end.

**Comment by ctiller** [comment]
So hexdump can produce both a hex string and an ASCII dump (with dots at
relavent string positions for non printables).

I'm being cautious because I've seen this go horribly wrong.

**Comment by jboeuf** [comment]
That will look pretty bad... If you add a flag that does not produce the
hex, I could go for it (even though that would look weird hexdump(PLAINTEXT
& NO_HEX))... I'm not sure I really understand the concern here though...
Embedded nulls are a well-known issue. I can add some comments to warn that
this may be the case explicitly if that makes you feel better :).

**Comment by ctiller** [comment]
So, a decade ago I watched an engineer* corrupt thousands of files and stop
a team of about a hundred working for a day by not noticing that a null
terminator was being written into a file - because the debug tools we had
exhibited exactly this limitation.

It was a very bad day, and I'm keen to not repeat it.

Could you make your function crash if there's a NULL within the slice?


* not I, but as it turns out they're now another fine Googler

**Comment by jboeuf** [comment]
I certainly could but do you want to prohibit the use of c_str() as well in
C++? I frankly don't see the difference here. Enlighten me!

**Comment by ctiller** [comment]
c_str being broken isn't an excuse for repeating mistakes

**Comment by ctiller** [comment]
Also, ```std::string```'s primary purpose isn't carrying binary data.

**Comment by nicolasnoble** [comment]
Since this is for debugging, how about having a c_str() equivalent that
actually does a strdup() like ?

Basically:

char *gpr_string_from_slice(const gpr_slice *slice) {
  char *ret = gpr_malloc(GPR_SLICE_SIZE(slice) + 1);
  memcpy(ret, GPR_SLICE_PTR(slice), GPR_SLICE_SIZE(slice));
  ret[GPR_SLICE_SIZE(slice)] = 0;
  return ret;
}

**Comment by nicolasnoble** [comment]
Actually, that's what this is doing :-D

**Comment by nicolasnoble** [comment]
So, after discussing a bit with @ctiller, here's my stance on that:

* `gpr_hexdump` should be renamed to `gpr_dump` or `gpr_dump_slice`.
* `gpr_dump_slice` should get an enum parameter that specifies the format: `HEX` or `PLAINTEXT`.

**Comment by jboeuf** [comment]
That sounds reasonable to me.

Another thing I could do is to have a gpr_cstring_from_slice in the
non-public src/core/support/string.h and keep gpr_hexdump as is. This way
it is not in the public slice.h and hopefully that should alleviate Craig's
concerns about people abusing this function.

Let me know... Craig?

**Comment by ctiller** [comment]
I think a general gpr_dump_{buffer,slice} taking some options flags sounds like a really fantastic thing actually.

**Comment by soltanmm** [comment]
Maybe while y'all are at it, address #2111?

**Comment by ctiller** [comment]
@soltanmm - I think that's a different topic.

**Comment by jboeuf** [comment]
SGTM. I will amend the PR them.

**Comment by jboeuf** [comment]
How do you like it now?

**Comment by nicolasnoble** [comment]
```
src/core/transport/chttp2_transport.c: In function 'grpc_chttp2_add_incoming_goaway':
src/core/transport/chttp2_transport.c:555:3: error: implicit declaration of function 'gpr_hexdump' [-Werror=implicit-function-declaration]
   char *msg = gpr_hexdump((char*)GPR_SLICE_START_PTR(goaway_text), GPR_SLICE_LENGTH(goaway_text), GPR_HEXDUMP_PLAINTEXT);
   ^
src/core/transport/chttp2_transport.c:555:99: error: 'GPR_HEXDUMP_PLAINTEXT' undeclared (first use in this function)
   char *msg = gpr_hexdump((char*)GPR_SLICE_START_PTR(goaway_text), GPR_SLICE_LENGTH(goaway_text), GPR_HEXDUMP_PLAINTEXT);
                                                                                                   ^
```

**Comment by jboeuf** [comment]
Merged and fixed.

**Comment by jboeuf** [comment]
Anyone wants to merge this?

**Pull request merged**
