### PR TITLE
Frame sizing by BDP

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by vjpai** [comment]
This depends on #10641 that fixes a frame-resizing bug

**Comment by ctiller** [comment]
Checking the new bm_diff

Jenkins test this please

**Comment by ctiller** [comment]
Jenkins test this please

**Comment by vjpai** [comment]
Ok, since this is a definite win, I'll log the flakes and test failures and make sure that this is mergeable as is.

**Comment by vjpai** [comment]
Test failures #10760 #9804 #9542 and interop

**Comment by vjpai** [comment]
This partially addresses #10289

**Pull request merged**
