### PR TITLE
Fix race between send message and send initial metadata

### PR DESCRIPTION
**Pull request by jtattermusch**
thanks @ctiller (who actually made the change)!

Creating the pull request to run tests on jenkins, still in the process of running tests locally, but it looks promising.

### CODE REVIEW

**Comment by ctiller** [comment]
Python is the fix.

**Comment by jtattermusch** [comment]
If this works I'll merge it into all branches I'll ever see. :-)

**Comment by jtattermusch** [comment]
I think this fixes #5564, so far it has passed 1000 runs of BetaFeaturesTest

**Comment by nicolasnoble** [comment]
```
FAILED: py.test._face_interface_test.GenericInvokerBlockingInvocationInlineServiceTest
```

**Comment by ctiller** [comment]
Might just be a fix for #5564, not Python in general.
I was hopeful.

**Comment by jtattermusch** [comment]
Ran all python tests with -n 100 and only got these 8 failures. All of them we've seen before. 

```
TIMEOUT: py.test._crust_over_core_face_interface_test.GenericInvokerEventInvocationSynchronousEventServiceTest
TIMEOUT: py.test._crust_over_core_face_interface_test.DynamicInvokerEventInvocationSynchronousEventServiceTest
FAILED: py.test.cygrpc_test.SecureServerSecureClient
TIMEOUT: py.test._crust_over_core_face_interface_test.MultiCallableInvokerEventInvocationSynchronousEventServiceTest
TIMEOUT: py.test._crust_over_core_face_interface_test.MultiCallableInvokerEventInvocationSynchronousEventServiceTest
TIMEOUT: py.test._channel_test.ChannelTest
TIMEOUT: py.test._crust_over_core_over_links_face_interface_test.MultiCallableInvokerEventInvocationSynchronousEventServiceTest
TIMEOUT: py.test._face_interface_test.GenericInvokerEventInvocationSynchronousEventServiceTest
```

**Comment by jtattermusch** [comment]
cc @soltanmm  and @nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment]
`<Keanu>Whoa.</Keanu>`

**Comment by nicolasnoble** [comment]
Alright, it seems to generally improve the state of python, not worsen it, so I'm merging it.

**Pull request merged**
