### PR TITLE
Updates to TLS credentials, version 2

### PR DESCRIPTION
**Pull request by matthewstevenson88**
This PR attempts to fix the flaky test `LoadTlsServerCredentials` that was introduced in PR #21766 and rolled back in PR #21778.

### CODE REVIEW

**Comment by matthewstevenson88** [comment]
First test run: 2 failing tests.

1. Bazel C/C++ Dbg MacOS: failing because of `test/core/end2end/tests/retry_recv_message.cc`.
2. Bazel RBE MSAN C/C++: failing because of `test/cpp/qps:qps_json_driver_test_cpp_protobuf_sync_streaming_qps_unconstrained_10mps_insecure`, more precisely because of the scenario `cpp_protobuf_sync_streaming_qps_unconstrained_10mps_insecure`.

**Comment by matthewstevenson88** [comment]
Second test run: 5 failing tests.

1. Basic Tests ObjC iOS: failed because of a timeout with `run_tests_objc_macos_opt_native`. In the log, it mentions the files modified by this PR in the following way:

"_Looking for irrelevant tests to skip..._
_Finding file differences between gRPC origin/master branch and pull request..._

  _include/grpcpp/security/tls_credentials_options.h_
  _src/cpp/common/tls_credentials_options.cc_
  _test/cpp/client/credentials_test.cc_

_No tests will be skipped._"

This does not seem to indicate any problem with these files or with `credentials_test.cc`, but I have saved the logs just in case.
2. Bazel C/C++ Dbg MacOS: failed to build target `//test/core/end2end:h2_local_uds_test@stream_compression_compressed_payload` because of error loading package `@local_config_cc//`. Note that this failure is for a different reason than in the first test run.
3. Bazel RBE MSAN C/C++: failed because of `//test/cpp/end2end:grpclb_end2end_test`.
4. Bazel RBE TSAN C/C++: failed because of `//test/core/channel:channelz_test`.
5. Interop Cloud-to-Cloud Tests (internal CI): failed because of `build_docker_javaokhttp`.

**Comment by matthewstevenson88** [comment]
Third test run: 1 failing test.

1. Basic Tests ObjC iOS: 3 targets here were failing, namely `grpc_basictests_objc_ios`, `run_tests_objc_macos_opt_native` (same as in second test run), and `ios-test-interoptests`. Again, I saved the logs just in case.

**Comment by matthewstevenson88** [comment]
Fourth test run: 2 failing tests.

1. Bazel C/C++ Dbg MacOs: failing because of `//test/core/end2end:h2_ssl_cred_reload_test@call_creds` and `//test/core/end2end:h2_tls_test@retry_throttled`.
2. Interop Cloud-to-Cloud Tests (internal CI): this is failing due to `cloud_to_cloud:dart:aspnetcore_server:timeout_on_sleeping_server:tls`. While this mentions TLS, I would guess it is a flake since it involves a timeout.

**Comment by matthewstevenson88** [comment]
Below is an accounting of the known errors that have occurred in the 4 test runs.

- In the first test run, the Bazel RBE MSAN C/C++ failure is Issue #20444. The Bazel C/C++ Dbg MacOS is not in the known list but seems unrelated (indeed, it is a C-core e2e test).
- In the second test run, the Bazel RBE MSAN C/C++ failure is Issue #13328, the Bazel RBE TSAN C/C++ failure is Issue #19660, and Interop Cloud-to-Cloud Tests (internal CI) failure is Issue #21675. The Basic Tests ObjC iOS and Bazel C/C++ Dbg MacOS failures don't seem to have issues, but do seem unrelated to the TLS credentials.
- In the third test run, the Basic Tests ObjC iOS failure is Issue #19866 and Issue #21381.
- In the fourth test run, one of the Bazel C/C++ Dbg MacOS failures is similar to Issue #19303, and the other is a C-core TLS test failure. The Interop Cloud-to-Cloud Tests (internal CI) failure is Issue #19834.

**Comment by matthewstevenson88** [comment]
@yihuazhang @ZhenLian This PR is a second attempt to submit the updates to the TLS credentials from PR #21766. The only difference between this PR and the previous one is the last line of the `LoadTlsChannelCredentials` and `LoadTlsServerCredentials` unit tests, where I added `.get()`.

With this change, the flake found in [Issue #21776](https://github.com/grpc/grpc/issues/21776) is not reproducible after 4 rounds of Kokoro testing. Earlier comments in this PR detail any failing tests during these test runs.

**Comment by yihuazhang** [comment]
@matthewstevenson88 Do you know why removing '.get()' will resolve the error - `assertion failed: 0 == pthread_setspecific(tls->key, (void*)value)`?

**Comment by matthewstevenson88** [comment]
Note: the root cause of the failure in [Issue #21776](https://github.com/grpc/grpc/issues/21776) was really [Issue #20311](https://github.com/grpc/grpc/issues/20311), and not the TLS credentials PR.

**Comment by matthewstevenson88** [comment]
Thanks @yihuazhang! :)

**Pull request merged**
