### PR TITLE
DocFixit: Add instructions to install protobuf3 in python readme files

### PR DESCRIPTION
**Pull request by royalharsh**
https://github.com/grpc/grpc/issues/5815
Adds instruction to install protobuf3 in python readme file

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
This is OK to test.

**Comment by soltanmm** [comment]
Thanks for the contribution! Would you mind instead placing the `protobuf>=3.0.0a3` line in `requirements.txt`?

**Comment by royalharsh** [comment]
I did think of doing that initially :smile:

**Comment by soltanmm** [comment]
lgtm

**Comment by soltanmm** [comment]
Oops. Please squash commits.

**Comment by nathanielmanistaatgoogle** [comment]
Squash commits - there are currently four commits in this pull request; there should be only one.

Is seven the right number of dependencies at which to sort them alphabetically?

**Comment by royalharsh** [comment]
Squashed and sorted!

**Comment by nathanielmanistaatgoogle** [comment]
Edit your commit log message - I'm [currently](https://github.com/grpc/grpc/pull/5959/commits/4bca5494ea1f0f9d5de7f21794e08d100509635e) seeing nearly the same sentence repeated five times. :-P

**Comment by royalharsh** [comment]
looks good now?

**Comment by nathanielmanistaatgoogle** [comment]
Looks better, but still has more improvement to come.

Take a look at [these guidelines](http://chris.beams.io/posts/git-commit/#seven-rules) for how to write a commit log message in general.

In this specific case:
(1) If you were reading just the commit log message, before looking at the code, could you identify _that to which_ protobuf3 had been added?
(2) There are some spelling mistakes in the current commit log message.
(3) Drop "and squashing commits" - it's generally not appropriate to explain in a commit log message the drafting and code review history of how the commit came to be formed.

**Comment by royalharsh** [comment]
Thanks for the article! I will remember these guidelines while writing my future commit messages.

**Comment by nathanielmanistaatgoogle** [comment]
This looks great to me; @soltanmm will also review and will merge.

**Comment by vjpai** [comment]
Friendly ping; what is the status of this PR?

**Comment by vjpai** [comment]
Is it confirmed that this fixes #5815 ?

**Comment by royalharsh** [comment]
@soltanmm will review

**Comment by soltanmm** [comment]
lgtm

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @hvardhanx isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request merged**
