### PR TITLE
Fix TSAN race in client channel's retry_state

### LINKED ISSUE #16896: Bazel TSAN failing: race in client_channel
Seeing elevated flakiness rate in last 5 builds: 
Examples:
https://source.cloud.google.com/results/invocations/b60e2847-ee02-40fc-80c4-94274a83077f/targets/%2F%2Ftest%2Fcpp%2Fend2end:client_lb_end2end_test@poller%3Dpoll-cv/log
https://source.cloud.google.com/results/invocations/f941831a-a8e2-4109-ad49-0f942d54be77/targets/%2F%2Ftest%2Fcpp%2Fend2end:client_lb_end2end_test@poller%3Depollex/log
https://source.cloud.google.com/results/invocations/6bef59ef-fe72-43c7-9b83-611b70a4376b/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_http_proxy_test@retry_server_pushback_delay@poller%3Depoll1/log
https://source.cloud.google.com/results/invocations/6ccd79f2-763e-4662-9ef7-bab5e64cb161/targets/%2F%2Ftest%2Fcore%2Fend2end:h2_http_proxy_test@retry@poller%3Depoll1/log

E.g.
```
WARNING: ThreadSanitizer: data race (pid=18)
  Write of size 2 at 0x7b9000011f00 by thread T3:
    #0 on_complete(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:2090 (h2_http_proxy_test+0x6c90bc)
    #1 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40 (h2_http_proxy_test+0xa3ef8b)
    #2 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:134 (h2_http_proxy_test+0xa3ecd3)
    #3 run_some_timers() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:131 (h2_http_proxy_test+0xa20493)
    #4 timer_main_loop() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:232 (h2_http_proxy_test+0xa200d9)
    #5 timer_thread(void*) /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:279 (h2_http_proxy_test+0xa1ffcc)
    #6 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:100 (h2_http_proxy_test+0xabe003)
    #7 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:74 (h2_http_proxy_test+0xabde38)
  Previous write of size 2 at 0x7b9000011f00 by thread T4:
    #0 do_retry(grpc_call_element*, subchannel_call_retry_state*, long) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:1421 (h2_http_proxy_test+0x6ce476)
    #1 maybe_retry(grpc_call_element*, subchannel_batch_data*, grpc_status_code, grpc_mdelem*) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:1531 (h2_http_proxy_test+0x6cdaa1)
    #2 recv_trailing_metadata_ready(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:1977 (h2_http_proxy_test+0x6ccda7)
    #3 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40 (h2_http_proxy_test+0xa3ef8b)
    #4 grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /proc/self/cwd/./src/core/lib/iomgr/closure.h:258 (h2_http_proxy_test+0x5d07b2)
    #5 recv_trailing_metadata_ready(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:784 (h2_http_proxy_test+0x6bfa93)
    #6 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40 (h2_http_proxy_test+0xa3ef8b)
    #7 grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /proc/self/cwd/./src/core/lib/iomgr/closure.h:258 (h2_http_proxy_test+0x5d07b2)
    #8 recv_trailing_metadata_ready(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/message_size/message_size_filter.cc:185 (h2_http_proxy_test+0x61b462)
    #9 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40 (h2_http_proxy_test+0xa3ef8b)
    #10 grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /proc/self/cwd/./src/core/lib/iomgr/closure.h:258 (h2_http_proxy_test+0x5d07b2)
    #11 recv_trailing_metadata_ready(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/http/client/http_client_filter.cc:191 (h2_http_proxy_test+0x9b9351)
    #12 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40 (h2_http_proxy_test+0xa3ef8b)
    #13 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:134 (h2_http_proxy_test+0xa3ecd3)
    #14 end_worker(grpc_pollset*, grpc_pollset_worker*, grpc_pollset_worker**) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:974 (h2_http_proxy_test+0xa68e05)
    #15 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_epoll1_linux.cc:1043 (h2_http_proxy_test+0xa64748)
    #16 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_posix.cc:317 (h2_http_proxy_test+0xa3d568)
    #17 grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/pollset.cc:48 (h2_http_proxy_test+0xa4f622)
    #18 thread_main(void*) /proc/self/cwd/test/core/end2end/fixtures/http_proxy_fixture.cc:520 (h2_http_proxy_test+0x5fdd11)
    #19 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:100 (h2_http_proxy_test+0xabe003)
    #20 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:74 (h2_http_proxy_test+0xabde38)
  Location is heap block of size 8007 at 0x7b9000010000 allocated by thread T1:
    #0 malloc /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:664 (h2_http_proxy_test+0x4df657)
    #1 gpr_malloc /proc/self/cwd/src/core/lib/gpr/alloc.cc:57 (h2_http_proxy_test+0xabc890)
    #2 gpr_malloc_aligned /proc/self/cwd/src/core/lib/gpr/alloc.cc:93 (h2_http_proxy_test+0xabcbad)
    #3 zalloc_aligned(unsigned long) /proc/self/cwd/src/core/lib/gpr/arena.cc:94 (h2_http_proxy_test+0xabce2f)
    #4 gpr_arena_alloc(gpr_arena*, unsigned long) /proc/self/cwd/src/core/lib/gpr/arena.cc:136 (h2_http_proxy_test+0xabd067)
    #5 grpc_core::ConnectedSubchannel::CreateCall(grpc_core::ConnectedSubchannel::CallArgs const&, grpc_subchannel_call**) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:937 (h2_http_proxy_test+0x6be403)
    #6 create_subchannel_call(grpc_call_element*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:2594 (h2_http_proxy_test+0x6d046d)
    #7 pick_done(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:2651 (h2_http_proxy_test+0x6d01c1)
    #8 exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40 (h2_http_proxy_test+0xa3ef8b)
    #9 grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:134 (h2_http_proxy_test+0xa3ecd3)
    #10 GrpcExecutor::RunClosures(char const*, grpc_closure_list) /proc/self/cwd/src/core/lib/iomgr/executor.cc:79 (h2_http_proxy_test+0xa402e9)
    #11 GrpcExecutor::ThreadMain(void*) /proc/self/cwd/src/core/lib/iomgr/executor.cc:191 (h2_http_proxy_test+0xa40b44)
    #12 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:100 (h2_http_proxy_test+0xabe003)
    #13 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:74 (h2_http_proxy_test+0xabde38)
  Thread T3 'grpc_global_tim' (tid=22, running) created by main thread at:
    #0 pthread_create /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:965 (h2_http_proxy_test+0x4e0b45)
    #1 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:73 (h2_http_proxy_test+0xabdaa9)
    #2 grpc_core::(anonymous namespace)::ThreadInternalsPosix* grpc_core::New<grpc_core::(anonymous namespace)::ThreadInternalsPosix, char const*&, void (*&)(void*), void*&, bool*>(char const*&, void (*&)(void*), void*&, bool*&&) /proc/self/cwd/./src/core/lib/gprpp/memory.h:52 (h2_http_proxy_test+0xabd69a)
    #3 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:142 (h2_http_proxy_test+0xabd467)
    #4 start_timer_thread_and_unlock() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:97 (h2_http_proxy_test+0xa1fefc)
    #5 start_threads() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:288 (h2_http_proxy_test+0xa1f972)
    #6 grpc_timer_manager_init() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:311 (h2_http_proxy_test+0xa1f8ee)
    #7 grpc_iomgr_start() /proc/self/cwd/src/core/lib/iomgr/iomgr.cc:62 (h2_http_proxy_test+0xa429a5)
    #8 grpc_init /proc/self/cwd/src/core/lib/surface/init.cc:149 (h2_http_proxy_test+0x600ff0)
    #9 main /proc/self/cwd/test/core/end2end/fixtures/h2_http_proxy.cc:125 (h2_http_proxy_test+0x549cb2)
  Thread T4 'grpc_http_proxy' (tid=23, running) created by main thread at:
    #0 pthread_create /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:965 (h2_http_proxy_test+0x4e0b45)
    #1 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:73 (h2_http_proxy_test+0xabdaa9)
    #2 grpc_core::(anonymous namespace)::ThreadInternalsPosix* grpc_core::New<grpc_core::(anonymous namespace)::ThreadInternalsPosix, char const*&, void (*&)(void*), void*&, bool*>(char const*&, void (*&)(void*), void*&, bool*&&) /proc/self/cwd/./src/core/lib/gprpp/memory.h:52 (h2_http_proxy_test+0xabd69a)
    #3 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:142 (h2_http_proxy_test+0xabd467)
    #4 grpc_end2end_http_proxy_create(grpc_channel_args*) /proc/self/cwd/test/core/end2end/fixtures/http_proxy_fixture.cc:559 (h2_http_proxy_test+0x5fd102)
    #5 chttp2_create_fixture_fullstack(grpc_channel_args*, grpc_channel_args*) /proc/self/cwd/test/core/end2end/fixtures/h2_http_proxy.cc:56 (h2_http_proxy_test+0x549e35)
    #6 begin_test(grpc_end2end_test_config, char const*, grpc_channel_args*, grpc_channel_args*) /proc/self/cwd/test/core/end2end/tests/retry_too_many_attempts.cc:48 (h2_http_proxy_test+0x575645)
    #7 test_retry_too_many_attempts(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/retry_too_many_attempts.cc:143 (h2_http_proxy_test+0x573cd7)
    #8 retry_too_many_attempts(grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/tests/retry_too_many_attempts.cc:292 (h2_http_proxy_test+0x573b0a)
    #9 grpc_end2end_tests(int, char**, grpc_end2end_test_config) /proc/self/cwd/test/core/end2end/end2end_tests.cc:612 (h2_http_proxy_test+0x54f431)
    #10 main /proc/self/cwd/test/core/end2end/fixtures/h2_http_proxy.cc:128 (h2_http_proxy_test+0x549d30)
  Thread T1 'default-executo' (tid=20, running) created by main thread at:
    #0 pthread_create /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:965 (h2_http_proxy_test+0x4e0b45)
    #1 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:73 (h2_http_proxy_test+0xabdaa9)
    #2 grpc_core::(anonymous namespace)::ThreadInternalsPosix* grpc_core::New<grpc_core::(anonymous namespace)::ThreadInternalsPosix, char const*&, void (*&)(void*), void*&, bool*>(char const*&, void (*&)(void*), void*&, bool*&&) /proc/self/cwd/./src/core/lib/gprpp/memory.h:52 (h2_http_proxy_test+0xabd69a)
    #3 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:142 (h2_http_proxy_test+0xabd467)
    #4 GrpcExecutor::SetThreading(bool) /proc/self/cwd/src/core/lib/iomgr/executor.cc:115 (h2_http_proxy_test+0xa3f9ff)
    #5 GrpcExecutor::Init() /proc/self/cwd/src/core/lib/iomgr/executor.cc:58 (h2_http_proxy_test+0xa3f47d)
    #6 grpc_executor_init() /proc/self/cwd/src/core/lib/iomgr/executor.cc:372 (h2_http_proxy_test+0xa41b81)
    #7 grpc_iomgr_init() /proc/self/cwd/src/core/lib/iomgr/iomgr.cc:54 (h2_http_proxy_test+0xa428b8)
    #8 grpc_init /proc/self/cwd/src/core/lib/surface/init.cc:133 (h2_http_proxy_test+0x600eef)
    #9 main /proc/self/cwd/test/core/end2end/fixtures/h2_http_proxy.cc:125 (h2_http_proxy_test+0x549cb2)
SUMMARY: ThreadSanitizer: data race /proc/self/cwd/src/core/ext/filters/client_channel/client_channel.cc:2090 in on_complete(void*, grpc_error*)
```

### PR DESCRIPTION
**Pull request by soheilhy**
There is a real race between `do_retry` and `on_complete`, and TSAN is
correctly complaining about the check and stores.

I presume having parallel `do_retry` and `on_complete` is intended.
can you please verify?

Fixes #16896

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                             FILE SIZE
 ++++++++++++++ GROWING                                               ++++++++++++++
  +0.0%     +16 [None]                                                +9.06Ki  +0.1%
  +0.8%    +272 src/core/ext/filters/client_channel/client_channel.cc    +272  +0.8%
       +15%    +272 on_complete                                              +272   +15%
      +2.1%      +8 recv_message_ready                                         +8  +2.1%

  +0.0%    +288 TOTAL                                                 +9.33Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by yashykt** [comment]
That is probably the case. Would relaxed memory order be sufficient?

**Comment by soheilhy** [comment]
Yes, TSAN would be happy as long as explicitly load with any ordering. :-)

**Comment by yashykt** [comment]
I meant whether it would be logically correct. @markdroth ?

**Comment by soheilhy** [comment]
Yes, that's was my original question in the PR message. The way it's implement right now is "relaxed", so I chose relaxed for that reason.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,358      Total (<)      2,020,378

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,174,076      Total (<)     11,174,081

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] Performance differences noted:
Benchmark           cpu_time    real_time
------------------  ----------  -----------
BM_SliceFromStatic  -8%         -8%
```

**Comment by soheilhy** [comment]
Yes, thank you @markdroth ! This definitely needs a deeper look at least confirm it's as intended. I'm very troubled with the check in `on_complete` based on `retry_state`. That's racy: We can enter the if branch in `on_complete` while we are inside `do_retry`.

**Comment by markdroth** [comment]
This can probably be closed in favor of #17367.

**Comment by soheilhy** [comment]
Thank you your for the note. This is closed in favor of #17368 and #17367.

**Pull request closed without merging**
