### PR TITLE
fixes for cross-compilation from Windows to Android

### PR DESCRIPTION
**Pull request by Slonegg**
I'm working on GRPC for Android. Here are changes to build gRPC with CMake for Android. Instructions (MSVS + Ninja), related to [this PR](https://github.com/google/protobuf/pull/2980). Note that @podsvirov is working on more elegant solution for cross-compiling protobuf.

Instructions (MSVS + Ninja):
1. Install Android SDK
2. Install Android NDK. Generally only NDK is necessary, SDK just may be useful for other purposes.
3. Set environment variable ANDROID_NDK
4. Install Ninja. Just drop ninja.exe somewhere where it can be accessed from command line, for example, alongside cmake binaries.
5. Build gRPC for host, because we will need protoc and grpc executables that we can run on host:
```
    mkdir _host_build
    cd _host_build
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
    cmake .. -G Ninja
    cmake --build .
```
6. Build gRPC for android:
```
    mkdir _android_build
    cd _android_build
    cmake .. -G Ninja -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_STL_TYPE=gnustl_static -Dprotobuf_BUILD_TESTS=OFF -DgRPC_ZLIB_PROVIDER=package -DRUN_HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0 -DRUN_HAVE_STEADY_CLOCK=0 -Dprotobuf_IMPORT_EXECUTABLES=../_host_build/protobuf_ImportExecutables.cmake -DgRPC_IMPORT_EXECUTABLES=../_host_build/gRPC_ImportExecutables.cmake
    cmake --build .
```

Partially resolves https://github.com/grpc/grpc/issues/8398

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
Looks like this PR fell through the cracks.  The code now seems fairly out of date. Nevertheless, https://github.com/grpc/grpc/issues/8398 seems to have been resolved. Closing.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @Slonegg isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
