### PR TITLE
Bump version to 1.44.0 (on v1.44.x branch)

### PR DESCRIPTION
**Pull request by jtattermusch**
As per the release process.

### CODE REVIEW

**Review by veblush — APPROVED** [review]

**Comment by jtattermusch** [comment]
C# distribtest failure is a bug with building single-platform nugets, but it doesn't affect correctness of nugets build by the multiplatform nugets / distribtests.

https://source.cloud.google.com/results/invocations/dc324217-4104-4606-8c03-b647d9cd5ec9/targets/github%2Fgrpc%2Fbuild_packages/tests


There also seems to be a bunch of failures of `//test/core/tsi:crl_ssl_transport_security_test`, which seems suspicious.

https://source.cloud.google.com/results/invocations/49fffe11-7d3b-4407-9e05-3857a2de152b/targets
https://source.cloud.google.com/results/invocations/7b981be9-42ae-4d78-bd8e-3c6d8593b3a1/targets/%2F%2Ftest%2Fcore%2Ftsi:crl_ssl_transport_security_test/log

**Comment by jtattermusch** [comment]
Ad //test/core/tsi:crl_ssl_transport_security_test failures:

A similar problem happened on master and I think the solution is to backport https://github.com/grpc/grpc/pull/28794 to the release branch.

**Comment by jtattermusch** [comment]
this PHP failure doesn't affect correctness of this PR, but we might wanna check whether this is something than needs to be fixed before publishing the stable release:
https://source.cloud.google.com/results/invocations/569b98c4-16d6-4cf2-918a-5f8b3db59a6e/targets/github%2Fgrpc%2Frun_tests%2Fphp7_linux_dbg_native%2Fsrc%2Fphp%2Fbin%2Frun_tests.sh/tests

**Comment by jtattermusch** [comment]
> Basic Tests PHP Linux

I ran a few more adhoc runs and they passed, so the failure seems to be a random fluke.

**Pull request merged**
