### PR TITLE
Update xDS interop test proto

### PR DESCRIPTION
**Pull request by voidzcy**
Updates the xDS interop test proto to support more advanced tests.

- Change the response of accumulated stats to group stats in RPC method.
  - This can be useful to distinguish RPCs routed to different backend services (by configuring different path matchers). So it would be convenient for verifying per backend service configurations.
  - E.g., we can use two backend services with one setting circuit breakers max_request = 500 and the other 1000. Then we apply path matchers to route different RPC methods to separate backend services. We can observe circuit breakers are effective per backend service.

### CODE REVIEW

**Review by donnadionne — APPROVED** [review]
ok i'll update my client code

**Comment by voidzcy** [comment]
> ok i'll update my client code

Thank you! Sorry for the change.

**Review by ericgribkoff — APPROVED** [review]
LGTM. At some point can you also add this test spec to the doc at https://github.com/grpc/grpc/blob/master/doc/xds-test-descriptions.md?

**Comment by voidzcy** [comment]
> LGTM. At some point can you also add this test spec to the doc at https://github.com/grpc/grpc/blob/master/doc/xds-test-descriptions.md?

Yeah, that's part of #24704, you can take a look there and let me know if you think more details needed.

**Pull request merged**
