### PR TITLE
Created Visual Studio 2010 project files.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by jtattermusch** [comment]
I suspect we actually don't need project for grpc_shared and gpr_shared. I introduced these a while ago, but then I made grpc_csharp_ext depend on static versions of grpc and gpr. So grpc.dll and gpr.dll are unused (and the way they are generated for VS 2013 is kind of hackish)

Also, I was wondering if we should use cmake to generate VS solutions in the future. It seems that it should be able to generate project files for multiple versions of VS as well as nmake makefiles.

**Comment by nicolasnoble** [comment]
So maybe we should remove the dll part for both vs2013 and vs2010 in the same time ? I don't mind doing that here.

As for the cmake argument, as I said in other threads, I don't mind at all generating a CMakefile for gRPC - the same way we're now generating a Bazel BUILD file. But I only want this to be an option for people, not the obligatory one-way passage to get to be able to build the code. Having the Makefile and Visual Studio projects inside the repository allows end users to checkout the code, and use it straight without needing any additional tool other than what they would already have on their machine. Having cmake under Windows isn't a natural state of things.

Beside, controlling ourselves the project files allows us to have a finer grained solution. For example, we can create a custom protoc rule that'll run our codegen plugin. AFAIK, you can't do that at the moment with cmake.

**Comment by jtattermusch** [comment]
On Thu, Apr 2, 2015 at 10:54 AM, Nicolas Noble <notifications@github.com>
wrote:

> So maybe we should remove the dll part for both vs2013 and vs2010 in the
> same time ? I don't mind doing that here.
>
SG, please remove them. I only need the project for grpc_csharp_ext.dll.

> As for the cmake argument, as I said in other threads, I don't mind at all
> generating a CMakefile for gRPC - the same way we're now generating a Bazel
> BUILD file. But I only want this to be an option for people, not the
> obligatory one-way passage to get to be able to build the code. Having the
> Makefile and Visual Studio projects inside the repository allows end users
> to checkout the code, and use it straight without needing any additional
> tool other than what they would already have on their machine. Having cmake
> under Windows isn't a natural state of things.
>
> Beside, controlling ourselves the project files allows us to have a finer
> grained solution. For example, we can create a custom protoc rule that'll
> run our codegen plugin. AFAIK, you can't do that at the moment with cmake.
>
ACK

**Comment by nicolasnoble** [comment]
Updated.

**Pull request merged**
