### PR TITLE
Bump to version 1.3.2

### PR DESCRIPTION
**Pull request by stanley-cheung**

### CODE REVIEW

**Comment by murgatroid99** [comment]
you should also change BUILD

**Comment by stanley-cheung** [comment]
Artifact build looks good: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/3411/

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                        cpu_time    real_time
-----------------------------  ----------  -----------
BM_ErrorCreateAndSetIntAndStr     +118.00      +118.00
BM_ErrorCreateAndSetStatus        +117.00      +117.00
BM_ErrorCreateFromCopied          +111.00      +111.00
BM_ErrorCreateFromStatic          +100.50      +100.50
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Pull request merged**
