### PR TITLE
Calling python to spawn a python subprocess.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by ctiller** [comment]
Needs a merge

**Comment by ctiller** [comment]
Dead?

**Comment by ctiller** [comment]
Ping?

**Comment by ctiller** [comment]
Unassigned myself until this is revived

**Comment by nicolasnoble** [comment]
Bah. Managed to skip the notifications until now.

**Comment by nicolasnoble** [comment]
And mergeable now :-P

**Comment by ctiller** [comment]
Sanity is failing (Jenkins, not mine)

**Pull request merged**
