### PR TITLE
Authority supported test flag now DOES_NOT_SUPPORT

### PR DESCRIPTION
**Pull request by rjshade**
Renames FEATURE_MASK_SUPPORTS_AUTHORITY_HEADER to FEATURE_MASK_DOES_NOT_SUPPORT_AUTHORITY_HEADER. This simplifies the vast majority of fixtures as they no longer need to mention this flag: the only fixture that doesn't support authority header is the Cronet fixture.

Inspired by comments in https://github.com/grpc/grpc/pull/10090

### CODE REVIEW

**Comment by yang-g** [comment]
I think there are missing fixes. See test failures.

**Comment by rjshade** [comment]
Yep, updated test/core/end2end/end2end_test_utils.c

**Comment by markdroth** [comment]
Cleaning up old PRs.  If this is still something you want to pursue, please re-open.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @rjshade isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
