### PR TITLE
grpc-cli: add install-grpc-cli target to Makefile

### PR DESCRIPTION
**Pull request by toanju**
ease the installation of grpc-cli using the Makefile

### CODE REVIEW

**Comment by ncteisen** [comment]
The makefile is created with a template, please edit templates/Makefile.template

**Comment by ncteisen** [comment]
(then run `tools/buildgen/generate_projects.sh`)

**Comment by toanju** [comment]
oh, right I forgot to update this branch. Thanks!

**Comment by toanju** [comment]
updated and rebased to master

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
