### PR TITLE
Support grpc++ compilation as windows dynamic library (DLL) using cmake.

### PR DESCRIPTION
**Pull request by ivan-kishchenko**
# Support grpc++ compilation as windows dynamic library (DLL) using cmake.

#### Description
Using one instance of grpc library between other windows dynamic libraries in application.

#### Example
My application (*client.exe*) use two my dynamic libraries (*a.dll* and *b.dll*). Both dynamic libraries (*a.dll* and *b.dll*) contain different implementation of different grpc clients (generated by *protoc.exe*). Every my dynamic library compiled with static grpc library (*grpc++.lib*), and as result - every dynamic library (*a.dll* and *b.dll*) contain implementation of *grpc++* static library. This is an issue for me, because my application after this contains duplicated implementation of *grpc++* static library.

Compilation GRPC as dynamic library (*DLL*) resolves this problem and in application loaded only once instance of *grpc++* library.

## About changes
Added new option *gRPC_BUILD_SHARED* (OFF by default) to CMakeLists.txt.
Added *dllexport* and *dllimport* directives to grpc++ code for export symbols and compile *grpc++* project as windows dynamic library (Only for windows and if gRPC_BUILD_SHARED=ON)

## How it works
- Configure and build project using *cmake* with *gRPC_BUILD_SHARED* option:
```
cd <grpc root directory>
md .build
cd .build
cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DgRPC_BUILD_SHARED=ON
cmake --build .
```

- Copy *grpc++.dll*, *grpc++.lib* and *libprotobuf.dll*, *libprotobuf.lib* to your project. grpc++ already contains grpc and gpr implementation inside.
- Add ```GRPC_USE_DLLS``` and ```PROTOBUF_USE_DLLS``` preprocessor definitions to your project.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @ivan-kishchenko isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Very interesting. I definitely want to look at this in more detail.
However, I need to stress something very important here. If a new
consequence of this pull request is that all public apis have to have that
new export symbol tag on them, we also have to have a matching sanity check
for it. We certainly can't accept a change that requires new constraints on
our existing or new files unless there is a sanity check to make sure that
those constraints don't get violated in the future. Another less critical
obstacle to accepting this is about testing. We certainly test for Windows
and using cmake, but we need a detailed testing story here and a
justification for why this is needed.

Thanks for your contribution, and I look forward to looking over the code.

**Comment by ivan-kishchenko** [comment]
All public APIs of grpc++ marked with export preprocessor directive where its possible. For platforms where export not needed/not supported (linux as example), the export preprocessor directive defined as empty.

Thanks for response, and I look forward to reviewing the code from you.

**Pull request closed without merging**
