### PR TITLE
Make Python testing predictable again

### PR DESCRIPTION
**Pull request by soltanmm**
Also simplifies `(build|run)_python` by using `tox` and generates coverage reports. Because why not.

### CODE REVIEW

**Comment by soltanmm** [comment]
#4228 should probably go in first so that extension code coverage Just Works™.

**Comment by nathanielmanistaatgoogle** [comment]
What's to be made of
```
Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    bool(BUILD_WITH_CYTHON))
  File "setup.py", line 118, in cython_extensions
    import Cython.Build
ImportError: No module named Cython.Build
```
in the failed test run of this?

**Comment by nathanielmanistaatgoogle** [comment]
Looks good content-wise.

**Comment by soltanmm** [comment]
The error on Jenkins was from a silly oversight on my part - fixed.

**Comment by soltanmm** [comment]
The *other* error which was *also* an oversight during fixing of the previous oversight has also been fixed.

**Comment by ctiller** [comment]
... trained to mix concrete and sign complicated insurance forms by ...

**Pull request merged**
