### PR TITLE
Add a Shutdown call to HealthCheckServiceInterface

### PR DESCRIPTION
**Pull request by yang-g**
The test service is moved to its own library so that I can reuse it in other tests.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/17435)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%     +48 src/cpp/server/health/default_health_check_service.cc                                    +48  +0.1%
      [NEW]    +219 grpc::DefaultHealthCheckService::Shutdown                                               +219  [NEW]
       +13%    +104 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCallHandler::OnCallRec    +104   +13%
      +7.3%     +16 grpc::DefaultHealthCheckService::SetServingStatus                                        +16  +7.3%
      +2.1%     +16 grpc::DefaultHealthCheckService::DefaultHealthCheckService                               +16  +2.1%
      +2.9%      +7 [Unmapped]                                                                                +7  +2.9%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  +0.1%    +196 [None]                                                                               -1.23Ki  -0.0%
       +17%      +8 vtable for grpc::DefaultHealthCheckService                                                +8   +17%

  +0.0%    +244 TOTAL                                                                                -1.18Ki  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,676      Total (=)      2,019,676

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,186      Total (<)     11,154,190

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.2%     +80 src/cpp/server/health/default_health_check_service.cc                                    +80  +0.2%
      [NEW]    +219 grpc::DefaultHealthCheckService::Shutdown                                               +219  [NEW]
      +4.9%     +24 grpc::DefaultHealthCheckService::SetServingStatus                                        +24  +4.9%
      +7.3%     +16 grpc::DefaultHealthCheckService::SetServingStatus                                        +16  +7.3%
      +2.1%     +16 grpc::DefaultHealthCheckService::DefaultHealthCheckService                               +16  +2.1%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  +0.1%    +192 [None]                                                                                  -184  -0.0%
       +17%      +8 vtable for grpc::DefaultHealthCheckService                                                +8   +17%

  +0.0%    +272 TOTAL                                                                                   -104  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,676      Total (=)      2,019,676

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,184      Total (>)     11,154,183

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
Test flake: #17399

**Pull request merged**
