### PR TITLE
implement timeout_on_sleeping_server interop test

### LINKED ISSUE #2822: C# implement timeout_on_sleeping_server interop test

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes #2822

### CODE REVIEW

**Comment by murgatroid99** [comment]
LGTM. Waiting for tests

**Comment by murgatroid99** [comment]
It looks like the C# tests failed.

**Comment by jtattermusch** [comment]
No, the tests were failing for that one and I haven't addressed that yet.

**Comment by jtattermusch** [comment]
Reverted the change.

**Comment by murgatroid99** [comment]
Oops. I think I got confused for a second about which PR I was looking at. I think you'll have to send this change to me again once the tests pass.

**Pull request merged**
