### PR TITLE
Upgrade third_party/protobuf to v3.17.3

### PR DESCRIPTION
**Pull request by donnadionne**

### CODE REVIEW

**Review by jtattermusch — APPROVED** [review]
I'd prefer if the handwritten changes were in separate commits from the generated changes, but I went through all the changes and it's looking alright.

LGTM once all the tests pass and once the adhoc artifacts - packages - distribtest flow also passes.

**Comment by jtattermusch** [comment]
Sanity tests failing `2021-09-02 06:35:55,980 FAILED: tools/distrib/check_upb_output.sh [ret=1, pid=361, time=102.2sec]`

**Comment by jtattermusch** [comment]
Adhoc artifacts / packages / distribtests run: https://fusion2.corp.google.com/invocations/89c1a33d-29e3-41a5-9f82-8c835dad4104/targets

**Comment by donnadionne** [comment]
> Sanity tests failing `2021-09-02 06:35:55,980 FAILED: tools/distrib/check_upb_output.sh [ret=1, pid=361, time=102.2sec]`

This is fix by regen upb

**Comment by donnadionne** [comment]
> Adhoc artifacts / packages / distribtests run: https://fusion2.corp.google.com/invocations/89c1a33d-29e3-41a5-9f82-8c835dad4104/targets

linux failure seems to like a timeout

window failure also seems like a timeout:
T:\src>choco install nasm -y --limit-output 

Installing the following packages:

nasm

By installing you accept licenses for the packages.

nasm not installed. An error occurred during installation:

 The operation has timed out

nasm package files install completed. Performing other installation steps.

The install of nasm was NOT successful.

nasm not installed. An error occurred during installation:

 The operation has timed out



Chocolatey installed 0/1 packages. 1 packages failed.

 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).



Failures

 - nasm (exited 1) - nasm not installed. An error occurred during installation:

 The operation has timed out


Re-running both with new commit after sanity test fix

**Comment by donnadionne** [comment]
> > Adhoc artifacts / packages / distribtests run: https://fusion2.corp.google.com/invocations/89c1a33d-29e3-41a5-9f82-8c835dad4104/targets
> 
> linux failure seems to like a timeout
> 
> window failure also seems like a timeout:
> T:\src>choco install nasm -y --limit-output
> 
> Installing the following packages:
> 
> nasm
> 
> By installing you accept licenses for the packages.
> 
> nasm not installed. An error occurred during installation:
> 
> The operation has timed out
> 
> nasm package files install completed. Performing other installation steps.
> 
> The install of nasm was NOT successful.
> 
> nasm not installed. An error occurred during installation:
> 
> The operation has timed out
> 
> Chocolatey installed 0/1 packages. 1 packages failed.
> 
> See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
> 
> * nasm (exited 1) - nasm not installed. An error occurred during installation:
> 
> The operation has timed out
> 
> Re-running both with new commit after sanity test fix

Newest run: linux passes!  but mac fails with timeout.


https://source.cloud.google.com/results/invocations/e59f884b-4e8a-4684-b0e1-41072f0434cd/targets/grpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform/log

**Comment by donnadionne** [comment]
Finally all passed after rerunning: https://source.cloud.google.com/results/invocations/80ff5392-cf42-48e8-8a08-1f8714edc1e9/targets/grpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform/log

Build #1455 0038657139b64c1e545f0b089949fdb74fd83b85

**Comment by donnadionne** [comment]
> > > Adhoc artifacts / packages / distribtests run: https://fusion2.corp.google.com/invocations/89c1a33d-29e3-41a5-9f82-8c835dad4104/targets
> > 
> > 
> > linux failure seems to like a timeout
> > window failure also seems like a timeout:
> > T:\src>choco install nasm -y --limit-output
> > Installing the following packages:
> > nasm
> > By installing you accept licenses for the packages.
> > nasm not installed. An error occurred during installation:
> > The operation has timed out
> > nasm package files install completed. Performing other installation steps.
> > The install of nasm was NOT successful.
> > nasm not installed. An error occurred during installation:
> > The operation has timed out
> > Chocolatey installed 0/1 packages. 1 packages failed.
> > See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> > Failures
> > 
> > * nasm (exited 1) - nasm not installed. An error occurred during installation:
> > 
> > The operation has timed out
> > Re-running both with new commit after sanity test fix
> 
> Newest run: linux passes! but mac fails with timeout.
> 
> https://source.cloud.google.com/results/invocations/e59f884b-4e8a-4684-b0e1-41072f0434cd/targets/grpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform/log

Finally all passed after rerunning: https://source.cloud.google.com/results/invocations/80ff5392-cf42-48e8-8a08-1f8714edc1e9/targets/grpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform/log

Build #1455 0038657

**Pull request merged**
