### PR TITLE
Client auth filter error handling

### LINKED ISSUE #2484: Fix error codes in client_auth_filter.c

### PR DESCRIPTION
**Pull request by jboeuf**
Fixes #2484.

### CODE REVIEW

**Comment by jcanizales** [comment]
Let's clarify here the details of these error cases so that (1) we make sure the choice of status code and message is appropriate, and (2) we can later incorporate it into our documentation. I'm guessing, so please edit anything that's wrong or incomplete:

* [Unauthenticated: "Credentials failed to get metadata"](https://github.com/jboeuf/grpc/blob/client_auth_filter_error_handling/src/core/security/client_auth_filter.c#L97)
  * **Cause:** This call used a credentials object that needs to add some headers, but the object wasn't able to produce them.
  * **Is it a client bug?** No, this can happen e.g. if there's a network error when trying to refresh an OAuth2 access token. _Can a client bug cause this when using the types of credentials we're shipping?_
  * **How should the client handle it?** Retry the call with exponential back-off.
* [Invalid Argument: "Incompatible credentials set on channel and call."](https://github.com/jboeuf/grpc/blob/client_auth_filter_error_handling/src/core/security/client_auth_filter.c#L158)
  * **Cause:** The channel was created with a set of credentials (via `grpc_secure_channel_create`); the call, with an additional set of credentials (via `grpc_call_set_credentials`). At least one of those sets needs to be "headers-only", and it wasn't the case. _But then, why do we allow users to attach credentials that aren't headers-only to a call? And what happens if e.g. I attach SSL credentials to a call that was created from a cleartext channel?_
  * **Is it a client bug?** Yes.
  * **How should the client prevent it?** _(Depends on the clarification of the above.)_
* [Failed Precondition: "Invalid host set in :authority metadata"](https://github.com/jboeuf/grpc/blob/client_auth_filter_error_handling/src/core/security/client_auth_filter.c#L186)
  * **Cause:** The server refuses call with the passed `:authority` value. _Can this still happen if one follows the preventive steps below?_ 
  * **Is it a client bug?** Yes.
  * **How should the client prevent it?** Pass `NULL` as `host` to `grpc_channel_create_call` or `grpc_channel_register_call`. If you're connecting to a test server, be sure to use as `:authority` the SSL name override expected by the server (e.g. by setting it as the default `:authority` for the channel). _Otherwise?_
* [Failed Precondition: "Invalid host set in :authority metadata"](https://github.com/jboeuf/grpc/blob/client_auth_filter_error_handling/src/core/security/client_auth_filter.c#L256)
  * _Same situation as above? If so, should the source code be deduplicated into a same function?_

**Comment by jboeuf** [comment]
Sorry for the delay and thanks much for the very thorough feedback: doc looks great. Here are a few points of clarification.

* *Unauthenticated*: This also can happen if the refresh token is expired or just parses ok but is actually not valid anymore (has been revoked). Same thing for service accounts credentials where the key to sign the JWT has been revoked as well. Maybe I could try to have a better credentials status to map it to a more specific grpc status.

* *Invalid argument*: 
  * We do not allow users to attach credentials that are not header-only to a call: `grpc_call_set_credentials` would return an error in this case.

* *Failed Precondition*: The 2 code paths are actually the same error handling: one for the sync version of the call to `grpc_channel_security_connector_check_call_host` and one from the async version. I could probably simplify this function and just have an async version.

**Comment by jcanizales** [comment]
CC: @tbetbetbe @ejona86

**Comment by jcanizales** [comment]
Let's double-check I understood correctly:

1. [Unauthenticated: "Credentials failed to get metadata"](https://github.com/jboeuf/grpc/blob/client_auth_filter_error_handling/src/core/security/client_auth_filter.c#L97)
  * **Cause:** This call used a credentials object that needs to add some headers, but the object wasn't able to produce them. Either because the auth server couldn't be reached, or because the stored credentials aren't valid anymore.
  * **Is it a client bug?** No.
  * **How should the client handle it?** Reauthenticate.
2. [Invalid Argument: "Incompatible credentials set on channel and call."](https://github.com/jboeuf/grpc/blob/client_auth_filter_error_handling/src/core/security/client_auth_filter.c#L158)
  * **Cause:** The channel was created with a set of credentials (via `grpc_secure_channel_create`); the call, with an additional set of credentials (via `grpc_call_set_credentials`). Both sets will try to set the same header.
  * **Is it a client bug?** Yes.
  * **How should the client prevent it?** Each credential type will document which other types it is incompatible with.
3. [Invalid Argument: "Invalid host set in :authority metadata"](https://github.com/jboeuf/grpc/blob/client_auth_filter_error_handling/src/core/security/client_auth_filter.c#L186) ([also here](https://github.com/jboeuf/grpc/blob/client_auth_filter_error_handling/src/core/security/client_auth_filter.c#L256))
  * **Cause:** The server doesn't have a certificate for the the passed `:authority` value.
  * **Is it a client bug?** Yes.
  * **How should the client prevent it?** Pass `NULL` as `host` to `grpc_channel_create_call` or `grpc_channel_register_call`. If you're connecting to a test server, be sure to use as `:authority` the SSL name override expected by the server (e.g. by setting it as the default `:authority` for the channel).


For (1.) we'll open an issue to let the credentials object pass us a status that we'll propagate (ideally with an error message too). So that we'll be able to distinguish `unavailable` (the client should retry the request) from `unauthenticated` (do the necessary auth dance).

For (2.): Does it mean that if I add OAuth2 credentials to the channel, I can't later override those per-call with different OAuth2 credentials? Because instead of the call credentials overriding the channel credentials, they'll just collide and produce this error.

**Comment by jboeuf** [comment]
Thanks for the summary. Everything looks good. Note that the headers/metadata check for 2. is not currently preformed by the code (but we will need to have it at some point).

**Comment by jcanizales** [comment]
The change LGTM, but apparently it broke all Jenkins tests? :)

**Comment by jboeuf** [comment]
Jenkins doesn't work well. Let me restart a build manually...

**Comment by jcanizales** [comment]
All reds are git failures to checkout stuff. Merging.

**Pull request merged**
