### PR TITLE
Override default certificats directly from httpscli_test.

### LINKED ISSUE #4878: make test failed with core dump
When run 'make test', get following error with core dump.

```
D0126 06:15:33.010985875   49112 test_config.c:159]          test slowdown: machine=1.000000 build=1.000000 total=1.000000
E0126 06:15:33.011358531   49112 init.c:123]                 Could not initialize census.
I0126 06:15:33.011376734   49112 httpscli_test.c:78]         test_get
I0126 06:15:33.011384146   49112 httpscli_test.c:81]         requesting from localhost:43576
E0126 06:15:33.012602723   49112 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:43576': socket error: connection refused
E0126 06:15:33.025234955   49112 ssl_transport_security.c:190] ssl_info_callback: error occured.

E0126 06:15:33.025260279   49112 ssl_transport_security.c:877] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0126 06:15:33.025264788   49112 handshake.c:236]            Handshake failed with error TSI_PROTOCOL_FAILURE
E0126 06:15:33.025269445   49112 httpcli_security_connector.c:156] Secure transport setup failed with error 1.
E0126 06:15:33.025273951   49112 httpscli_test.c:62]         assertion failed: response



*******************************
Caught signal 6
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test[0x4d84a3]
/lib64/libpthread.so.0(+0xf130)[0x7fcca6568130]
/lib64/libc.so.6(gsignal+0x37)[0x7fcca5db55d7]
/lib64/libc.so.6(abort+0x148)[0x7fcca5db6cc8]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test[0x40f49b]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test[0x410564]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test[0x410bfd]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test[0x47be85]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test[0x47c31f]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test[0x41ed8e]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test(grpc_exec_ctx_flush+0x5a)[0x4102aa]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test(grpc_pollset_work+0x1c5)[0x414815]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test(main+0x2d8)[0x40ef88]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fcca5da1af5]
/home/gpadmin/workspace/grpc/bins/opt/httpscli_test[0x40f27d]
/bin/sh: line 1: 49112 Aborted                 (core dumped) /home/gpadmin/workspace/grpc/bins/opt/httpscli_test
test httpscli_test failed
make: *** [test_c] Error 1
```

### PR DESCRIPTION
**Pull request by nicolasnoble**
Fixes #4878.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
"Green enough". Some python MacOS tests timed out.

**Comment by nicolasnoble** [comment]
Ping ?

**Comment by ctiller** [comment]
I was going to hold til post fixit based on it not affecting any fixit related work.

**Comment by nicolasnoble** [comment]
Fair enough, it's still a "fix", but not a green checkbox-related fix :P

**Comment by ctiller** [comment]
Right. We're getting close. I start to get paranoid about follow-on
breakage.

**Comment by ctiller** [comment]
Closing antiquity.

**Pull request closed without merging**
