### PR TITLE
Add check for input parameter being null.

### LINKED ISSUE #20175: Possible dereference of null pointer
This was found with CppCheck
lb_policy_registry.cc contains ParseLoadBalancingConfigHelper() function which goes like this:

      if (lb_config_array == nullptr || lb_config_array->type != GRPC_JSON_ARRAY) {
    gpr_asprintf(&error_msg, "field:%s error:type should be array",
                 lb_config_array->key);

In case `lb_config_array` is null control enters the `if` and then attempt to compute `lb_config_array->key` causes dereferencing of null pointer and undefined behavior.

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #20175.

### CODE REVIEW

**Comment by vjpai** [comment]
If this is never going to happen in practice, it should be a DEBUG_ASSERT rather than an error (imo); the master version itself was apparently just adding in a useless check for nullptr.

**Comment by markdroth** [comment]
I agree that it should never happen, but in general, we have been trying to limit the asserts in our code.  This code isn't something that gets called in the fastpath, so I don't mind the overhead of the extra error handling.

**Comment by vjpai** [comment]
If an assert is the problem, then so is the if check. Why not just delete the check altogether?

**Comment by markdroth** [comment]
Null is a common sentinel value.  There's not much we can do to protect against other invalid values (e.g., arbitrary memory corruption), but I think it's not unreasonable to check for null.

**Comment by markdroth** [comment]
Known issues: #20095 #20198

The objc ios test failure is an infrastructure timeout.

**Pull request merged**
