### PR TITLE
[Second attempt] Add Type Checking On Channel Args

### PR DESCRIPTION
**Pull request by ncteisen**
NOT READY FOR REVIEW

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +1.5%    +160 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +160  +1.5%
      +4.9%    +158 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               +158  +4.9%
      +0.8%      +2 [Unmapped]                                                                                +2  +0.8%
  +0.6%     +96 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           +96  +0.6%
      +5.4%     +55 grpc_core::(anonymous namespace)::GrpcLbFactory::CreateLoadBalancingPolicy(grpc_core     +55  +5.4%
      +2.6%     +29 grpc_core::(anonymous namespace)::GrpcLb::ProcessChannelArgsLocked                       +29  +2.6%
      +3.0%     +12 [Unmapped]                                                                               +12  +3.0%
  +3.8%     +96 src/core/lib/security/credentials/ssl/ssl_credentials.cc                                 +96  +3.8%
       +30%     +96 ssl_create_security_connector                                                            +96   +30%
  +3.3%     +64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       +64  +3.3%
       +77%     +40 grpc_core::FakeResolverResponseGenerator::GetFromArgs                                    +40   +77%
      +111%     +40 grpc_core::FakeResolverResponseGenerator::MakeChannelArg                                 +40  +111%
  +3.0%     +40 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 +40  +3.0%
       +77%     +40 grpc_lb_addresses_find_channel_arg                                                       +40   +77%
  +0.3%     +32 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +32  +0.3%
      +1.3%     +35 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                               +35  +1.3%
  +0.1%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                              +16  +0.1%
      +0.4%     +12 grpc_create_chttp2_transport                                                             +12  +0.4%
      +0.6%      +4 [Unmapped]                                                                                +4  +0.6%

 -------------- SHRINKING                                                                            --------------
 -13.7%    -672 src/core/ext/filters/http/client/http_client_filter.cc                                  -672 -13.7%
     -44.0%    -676 init_channel_elem                                                                       -676 -44.0%
  -9.7%    -224 src/core/lib/security/credentials/credentials.cc                                        -224  -9.7%
      [DEL]     -98 grpc_server_credentials_from_arg                                                         -98  [DEL]
      [DEL]     -98 grpc_channel_credentials_from_arg                                                        -98  [DEL]
     -12.4%     -28 [Unmapped]                                                                               -28 -12.4%
  -3.3%    -176 src/core/lib/iomgr/tcp_server_posix.cc                                                  -176  -3.3%
     -34.1%    -191 tcp_server_create                                                                       -191 -34.1%
  -3.9%    -160 src/core/lib/iomgr/tcp_server_custom.cc                                                 -160  -3.9%
     -41.6%    -159 tcp_server_create                                                                       -159 -41.6%
      -1.1%      -1 [Unmapped]                                                                                -1  -1.1%
  -0.5%    -156 src/core/ext/filters/client_channel/client_channel.cc                                   -156  -0.5%
     -12.4%    -167 cc_init_channel_elem                                                                    -167 -12.4%
      -2.1%      -9 [Unmapped]                                                                                -9  -2.1%
  -3.5%    -112 src/core/lib/security/context/security_context.cc                                       -112  -3.5%
      [DEL]     -98 grpc_auth_context_from_arg                                                               -98  [DEL]
      -8.3%     -14 [Unmapped]                                                                               -14  -8.3%
  -1.1%    -112 src/core/lib/security/security_connector/security_connector.cc                          -112  -1.2%
      [DEL]     -98 grpc_security_connector_from_arg                                                         -98  [DEL]
      -2.5%     -14 [Unmapped]                                                                               -14  -2.5%
  -1.1%     -80 src/core/lib/iomgr/resource_quota.cc                                                     -80  -1.1%
     -42.0%     -68 grpc_resource_quota_from_channel_args                                                    -68 -42.0%
      -4.3%     -12 [Unmapped]                                                                               -12  -4.3%
  -3.3%     -64 src/core/lib/iomgr/tcp_server_utils_posix_common.cc                                      -64  -3.3%
      -6.9%     -62 grpc_tcp_server_prepare_socket                                                           -62  -6.9%
      -8.3%      -2 [Unmapped]                                                                                -2  -8.3%
  -1.5%     -48 src/core/lib/iomgr/tcp_client_posix.cc                                                   -48  -1.5%
      -7.8%     -52 grpc_tcp_client_prepare_fd                                                               -52  -7.8%
  -0.8%     -32 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -32  -0.8%
      -6.8%     -40 grpc_core::(anonymous namespace)::AresDnsResolverFactory::CreateResolver(grpc_core::     -40  -6.8%
  -0.6%     -32 src/core/lib/iomgr/udp_server.cc                                                         -32  -0.6%
      -9.3%     -21 grpc_udp_server_create                                                                   -21  -9.3%
      -6.2%     -11 [Unmapped]                                                                               -11  -6.2%
  -0.1%     -16 src/core/ext/transport/inproc/inproc_transport.cc                                        -16  -0.1%
      -1.4%      -9 grpc_inproc_channel_create                                                                -9  -1.4%
      -3.3%      -7 [Unmapped]                                                                                -7  -3.3%
  -0.3%      -5 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_channel_secure.cc             -5  -0.3%
      -0.6%      -5 grpc_lb_policy_grpclb_modify_lb_channel_args                                              -5  -0.6%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.2% -1.38Ki [None]                                                                               +11.3Ki  +0.1%

  -0.2% -2.73Ki TOTAL                                                                                +9.92Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -40  -0.0%

  [ = ]       0 TOTAL      -40  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                              cpu_time    real_time
---------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/32768                           -4%         -4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/2  -4%         -4%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +1.5%    +160 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +160  +1.5%
      +4.9%    +158 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               +158  +4.9%
      +0.8%      +2 [Unmapped]                                                                                +2  +0.8%
  +0.6%     +96 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           +96  +0.6%
      +5.4%     +55 grpc_core::(anonymous namespace)::GrpcLbFactory::CreateLoadBalancingPolicy(grpc_core     +55  +5.4%
      +2.6%     +29 grpc_core::(anonymous namespace)::GrpcLb::ProcessChannelArgsLocked                       +29  +2.6%
      +3.0%     +12 [Unmapped]                                                                               +12  +3.0%
  +3.7%     +96 src/core/lib/security/credentials/ssl/ssl_credentials.cc                                 +96  +3.7%
       +30%     +96 ssl_create_security_connector                                                            +96   +30%
  +3.3%     +64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       +64  +3.3%
       +77%     +40 grpc_core::FakeResolverResponseGenerator::GetFromArgs                                    +40   +77%
      +111%     +40 grpc_core::FakeResolverResponseGenerator::MakeChannelArg                                 +40  +111%
  +3.0%     +40 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 +40  +3.0%
       +77%     +40 grpc_lb_addresses_find_channel_arg                                                       +40   +77%
  +0.3%     +32 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +32  +0.3%
      +1.3%     +35 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                               +35  +1.3%
  +0.1%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                              +16  +0.1%
      +0.4%     +12 grpc_create_chttp2_transport                                                             +12  +0.4%
      +0.6%      +4 [Unmapped]                                                                                +4  +0.6%

 -------------- SHRINKING                                                                            --------------
 -13.7%    -672 src/core/ext/filters/http/client/http_client_filter.cc                                  -672 -13.7%
     -44.0%    -676 init_channel_elem                                                                       -676 -44.0%
  -9.5%    -224 src/core/lib/security/credentials/credentials.cc                                        -224  -9.5%
      [DEL]     -98 grpc_server_credentials_from_arg                                                         -98  [DEL]
      [DEL]     -98 grpc_channel_credentials_from_arg                                                        -98  [DEL]
     -11.1%     -28 [Unmapped]                                                                               -28 -11.1%
  -3.3%    -176 src/core/lib/iomgr/tcp_server_posix.cc                                                  -176  -3.3%
     -34.1%    -191 tcp_server_create                                                                       -191 -34.1%
  -3.9%    -160 src/core/lib/iomgr/tcp_server_custom.cc                                                 -160  -3.9%
     -41.6%    -159 tcp_server_create                                                                       -159 -41.6%
      -1.4%      -1 [Unmapped]                                                                                -1  -1.4%
  -0.4%    -156 src/core/ext/filters/client_channel/client_channel.cc                                   -156  -0.4%
     -12.4%    -167 cc_init_channel_elem                                                                    -167 -12.4%
      -2.4%      -9 [Unmapped]                                                                                -9  -2.4%
  -3.5%    -112 src/core/lib/security/context/security_context.cc                                       -112  -3.5%
      [DEL]     -98 grpc_auth_context_from_arg                                                               -98  [DEL]
      -7.9%     -14 [Unmapped]                                                                               -14  -7.9%
  -1.1%    -112 src/core/lib/security/security_connector/security_connector.cc                          -112  -1.1%
      [DEL]     -98 grpc_security_connector_from_arg                                                         -98  [DEL]
      -2.5%     -14 [Unmapped]                                                                               -14  -2.5%
  -1.1%     -80 src/core/lib/iomgr/resource_quota.cc                                                     -80  -1.1%
     -42.0%     -68 grpc_resource_quota_from_channel_args                                                    -68 -42.0%
      -4.2%     -12 [Unmapped]                                                                               -12  -4.2%
  -3.3%     -64 src/core/lib/iomgr/tcp_server_utils_posix_common.cc                                      -64  -3.3%
      -6.9%     -62 grpc_tcp_server_prepare_socket                                                           -62  -6.9%
      -8.3%      -2 [Unmapped]                                                                                -2  -8.3%
  -1.5%     -48 src/core/lib/iomgr/tcp_client_posix.cc                                                   -48  -1.5%
      -7.8%     -52 grpc_tcp_client_prepare_fd                                                               -52  -7.8%
  -0.8%     -32 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -32  -0.8%
      -6.8%     -40 grpc_core::(anonymous namespace)::AresDnsResolverFactory::CreateResolver(grpc_core::     -40  -6.8%
  -0.6%     -32 src/core/lib/iomgr/udp_server.cc                                                         -32  -0.6%
      -9.3%     -21 grpc_udp_server_create                                                                   -21  -9.3%
      -6.2%     -11 [Unmapped]                                                                               -11  -6.2%
  -0.1%     -16 src/core/ext/transport/inproc/inproc_transport.cc                                        -16  -0.1%
      -1.4%      -9 grpc_inproc_channel_create                                                                -9  -1.4%
      -3.0%      -7 [Unmapped]                                                                                -7  -3.0%
  -0.3%      -5 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_channel_secure.cc             -5  -0.3%
      -0.6%      -5 grpc_lb_policy_grpclb_modify_lb_channel_args                                              -5  -0.6%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.2% -1.41Ki [None]                                                                               +15.5Ki  +0.2%

  -0.2% -2.77Ki TOTAL                                                                                +14.2Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +1.5%    +160 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +160  +1.5%
      +4.9%    +158 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               +158  +4.9%
      +0.8%      +2 [Unmapped]                                                                                +2  +0.8%
  +0.6%     +96 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           +96  +0.6%
      +5.4%     +55 grpc_core::(anonymous namespace)::GrpcLbFactory::CreateLoadBalancingPolicy(grpc_core     +55  +5.4%
      +2.6%     +29 grpc_core::(anonymous namespace)::GrpcLb::ProcessChannelArgsLocked                       +29  +2.6%
      +3.0%     +12 [Unmapped]                                                                               +12  +3.0%
  +3.7%     +96 src/core/lib/security/credentials/ssl/ssl_credentials.cc                                 +96  +3.7%
       +30%     +96 ssl_create_security_connector                                                            +96   +30%
  +3.3%     +64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       +64  +3.3%
       +77%     +40 grpc_core::FakeResolverResponseGenerator::GetFromArgs                                    +40   +77%
      +111%     +40 grpc_core::FakeResolverResponseGenerator::MakeChannelArg                                 +40  +111%
  +3.0%     +40 src/core/ext/filters/client_channel/lb_policy_factory.cc                                 +40  +3.0%
       +77%     +40 grpc_lb_addresses_find_channel_arg                                                       +40   +77%
  +0.3%     +32 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +32  +0.3%
      +1.3%     +35 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                               +35  +1.3%
  +0.1%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                              +16  +0.1%
      +0.4%     +12 grpc_create_chttp2_transport                                                             +12  +0.4%
      +0.6%      +4 [Unmapped]                                                                                +4  +0.6%

 -------------- SHRINKING                                                                            --------------
 -13.7%    -672 src/core/ext/filters/http/client/http_client_filter.cc                                  -672 -13.7%
     -44.0%    -676 init_channel_elem                                                                       -676 -44.0%
  -9.5%    -224 src/core/lib/security/credentials/credentials.cc                                        -224  -9.5%
      [DEL]     -98 grpc_server_credentials_from_arg                                                         -98  [DEL]
      [DEL]     -98 grpc_channel_credentials_from_arg                                                        -98  [DEL]
     -11.1%     -28 [Unmapped]                                                                               -28 -11.1%
  -3.3%    -176 src/core/lib/iomgr/tcp_server_posix.cc                                                  -176  -3.3%
     -34.1%    -191 tcp_server_create                                                                       -191 -34.1%
  -3.9%    -160 src/core/lib/iomgr/tcp_server_custom.cc                                                 -160  -3.9%
     -41.6%    -159 tcp_server_create                                                                       -159 -41.6%
      -1.4%      -1 [Unmapped]                                                                                -1  -1.4%
  -0.4%    -156 src/core/ext/filters/client_channel/client_channel.cc                                   -156  -0.4%
     -12.4%    -167 cc_init_channel_elem                                                                    -167 -12.4%
      -2.4%      -9 [Unmapped]                                                                                -9  -2.4%
  -3.5%    -112 src/core/lib/security/context/security_context.cc                                       -112  -3.5%
      [DEL]     -98 grpc_auth_context_from_arg                                                               -98  [DEL]
      -7.9%     -14 [Unmapped]                                                                               -14  -7.9%
  -1.1%    -112 src/core/lib/security/security_connector/security_connector.cc                          -112  -1.1%
      [DEL]     -98 grpc_security_connector_from_arg                                                         -98  [DEL]
      -2.5%     -14 [Unmapped]                                                                               -14  -2.5%
  -1.1%     -80 src/core/lib/iomgr/resource_quota.cc                                                     -80  -1.1%
     -42.0%     -68 grpc_resource_quota_from_channel_args                                                    -68 -42.0%
      -4.2%     -12 [Unmapped]                                                                               -12  -4.2%
  -3.3%     -64 src/core/lib/iomgr/tcp_server_utils_posix_common.cc                                      -64  -3.3%
      -6.9%     -62 grpc_tcp_server_prepare_socket                                                           -62  -6.9%
      -8.3%      -2 [Unmapped]                                                                                -2  -8.3%
  -1.5%     -48 src/core/lib/iomgr/tcp_client_posix.cc                                                   -48  -1.5%
      -7.8%     -52 grpc_tcp_client_prepare_fd                                                               -52  -7.8%
  -0.8%     -32 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -32  -0.8%
      -6.8%     -40 grpc_core::(anonymous namespace)::AresDnsResolverFactory::CreateResolver(grpc_core::     -40  -6.8%
  -0.6%     -32 src/core/lib/iomgr/udp_server.cc                                                         -32  -0.6%
      -9.3%     -21 grpc_udp_server_create                                                                   -21  -9.3%
      -6.2%     -11 [Unmapped]                                                                               -11  -6.2%
  -0.1%     -16 src/core/ext/transport/inproc/inproc_transport.cc                                        -16  -0.1%
      -1.4%      -9 grpc_inproc_channel_create                                                                -9  -1.4%
      -3.0%      -7 [Unmapped]                                                                                -7  -3.0%
  -0.3%      -5 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_channel_secure.cc             -5  -0.3%
      -0.6%      -5 grpc_lb_policy_grpclb_modify_lb_channel_args                                              -5  -0.6%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.2% -1.41Ki [None]                                                                               +15.5Ki  +0.2%

  -0.2% -2.77Ki TOTAL                                                                                +14.2Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                    cpu_time    real_time
---------------------------  ----------  -----------
BM_MetadataRefUnrefExternal  -5%         -5%
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                   cpu_time    real_time
------------------------------------------  ----------  -----------
BM_HasClearGrpcStatus<ErrorCancelled>       -5%         -5%
BM_HasClearGrpcStatus<ErrorWithGrpcStatus>  -5%         -5%
BM_MetadataRefUnrefStatic                   -5%         -5%
```

**Comment by markdroth** [comment]
Out of curiosity, what's holding up this PR?  It's not blocking anything, but it would be nice to have.

**Comment by ncteisen** [comment]
There were some python  failures IIRC. I can try to revive this this week

**Pull request closed without merging**
