### PR TITLE
No Error Creation on RPC Hotpath

### LINKED ISSUE #7687: Add a test verifying that no grpc_error instances are created during a typical request
Use the same approach as in #246.

### PR DESCRIPTION
**Pull request by ncteisen**
Fixes #7687

Ensures that once we are warmed up with one RPC, subsequent successful RPCs never create anything other than a special case error (GRPC_ERROR_OK, etc etc).

This is similar to our test that ensures no logging in the RPC hotpath

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                       FILE SIZE
 ++++++++++++++ GROWING                         ++++++++++++++
  +0.0%    +192 [None]                             +336  +0.0%
  +0.5%     +32 src/core/lib/iomgr/error.cc         +32  +0.5%
       +19%     +28 [Unmapped]                          +28   +19%
      [NEW]      +2 grpc_enable_error_creation           +2  [NEW]
      [NEW]      +2 grpc_disable_error_creation          +2  [NEW]

  +0.0%    +224 TOTAL                              +368  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +40  +0.0%

  [ = ]       0 TOTAL      +40  +0.0%



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                       FILE SIZE
 ++++++++++++++ GROWING                         ++++++++++++++
  +0.0%    +160 [None]                             +328  +0.0%
  +0.5%     +32 src/core/lib/iomgr/error.cc         +32  +0.5%
       +19%     +28 [Unmapped]                          +28   +19%
      [NEW]      +2 grpc_enable_error_creation           +2  [NEW]
      [NEW]      +2 grpc_disable_error_creation          +2  [NEW]

  +0.0%    +192 TOTAL                              +360  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +40  +0.0%

  [ = ]       0 TOTAL      +40  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Bazel #15610

**Pull request merged**
