### PR TITLE
Don't ignore empty serverlists from the grpclb balancer.

### PR DESCRIPTION
**Pull request by markdroth**
Fixes grpc/grpc-go#2347.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.3%     -48 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           -48  -0.3%
      -4.9%     -72 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::OnBalancerMessageReceiv     -72  -4.9%
      -0.1%      -2 grpc_core::(anonymous namespace)::GrpcLb::CreateOrUpdateRoundRobinPolicyLocked() [cl      -2  -0.1%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -24 [None]                                                                                  +160  +0.0%

  -0.0%     -72 TOTAL                                                                                   +112  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.3%     -48 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           -48  -0.3%
      -4.9%     -72 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::OnBalancerMessageReceiv     -72  -4.9%
      -0.1%      -2 grpc_core::(anonymous namespace)::GrpcLb::CreateOrUpdateRoundRobinPolicyLocked() [cl      -2  -0.1%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -56 [None]                                                                                  +184  +0.0%

  -0.0%    -104 TOTAL                                                                                   +136  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: #17338

**Pull request merged**
