### PR TITLE
Allow Bazel to build gRPC as a third-party dependency without git submodules

### PR DESCRIPTION
**Pull request by jwpowell055**
Update Bazel WORKSPACE file and third_party/cares BUILD files so that Bazel can build gRPC as a dependency.

The WORKSPACE file now pulls third_party dependencies directly instead of requiring a git submodule init and update. The git hashes pulled by Bazel are exactly the same as the git submodules checked into third_party.

A tiny bit of complexity comes from the c-ares project's use of ares_config.h.cmake and ares_build.h.cmake. The current solution to this problem is to check in a valid ares_config.h and a few valid ares_config.h files. This is the same general approach used still, but ares_config.h and ares_build.h are supplied to cares.BUILD from the only remaining local_repository, which serves only to export these two header files.

### CODE REVIEW

**Comment by jwpowell055** [comment]
I have attempted to fix this at go/patching

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by nicolasnoble** [comment]
So, reading more closely this PR, what I don't necessarily like about it, is the loose coupling between the actual submodules and the WORKSPACE links. I'd rather have something that makes sure that if the submodule gets updated, some sort of test indicates that the WORKSPACE file has to be updated as well.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by ctiller** [comment]
So to rephrase: we'd be looking for a linter that runs during run_sanity
that succeeds when the workspace matches our submodules and fails when it
does not, similar in spirit to the current check_submodules.sh script.

As an implementation hint: The WORKSPACE file is SkyLark and is
sufficiently syntactically similar to Python that we ought to be able to
read() then eval() it to verify these properties.

**Comment by jwpowell055** [comment]
Just picking this back up. Sorry for the delay. Would you want this linter to be a part of check_submodules.sh?

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @jwpowell055 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by ctiller** [comment]
I think make it a separate script... iirc there's a json document in that
directory listing the scripts to run.

**Comment by jwpowell055** [comment]
I've added a Python script that does impose some checks. It may require some updates if you'd like the sanity check to be performed in a slightly different way but it's a start to iterate on. Is there a formatter that was used on the other Python scripts in this directory? It's apparently not YAPF.

Also, the Linux Foundation CLA requirement must've been added some I opened this PR. Is that right?

**Comment by jwpowell055** [comment]
ping (to prompt a reassessment of the Linux Foundation CLA)

I will look at the conflict with the c-ares BUILD file tonight.

**Comment by jwpowell055** [comment]
I have resolved the conflict with third_party/cares/cares.BUILD.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by nicolasnoble** [comment]
Your new file, grpc/tools/run_tests/sanity/check_bazel_workspace.py needs the exec bit on, I think.

**Comment by jwpowell055** [comment]
Thanks for the suggestion. Done.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
