### PR TITLE
Properly using our build.yaml source of truth to generate our list of public APIs.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Leftover from our Ruby rush. Also will unblock #6214 for @makdharma.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Yes, that change surprisingly ends up being a no-up for generated files.

**Comment by ctiller** [comment]
LGTM

**Comment by makdharma** [comment]
all C windows builds are failing.

**Comment by nicolasnoble** [comment]
Git checkout sneezed.

**Comment by makdharma** [comment]
The test failures below sound like flakes. @nicolasnoble  - OK to merge?
tests.csharp.Grpc.Core.Tests.MarshallingErrorsTest
tests.bins/msan/fling_stream_test
tests.vsprojects/Release/concurrent_connectivity_test.exe
tests.bins/tsan/h2_sockpair_1byte_nosec_test invoke_large_request

**Comment by nicolasnoble** [comment]
Yep.

**Pull request merged**
