### PR TITLE
Experimental API for xDS server credentials

### PR DESCRIPTION
**Pull request by yashykt**
This is the server equivalent of #24313

List of changes -
**Insecure Server Credentials**
- Add experimental API for `grpc_insecure_server_credentials_create()` similar to `grpc_insecure_credentials_create()`.
This is needed to be able to provide `InsecureServerCredentials()` as fallback credentials to `XdsServerCredentials()`.
_Rationale_ - In its current form `InsecureServerCredentials()` are not implemented as `grpc_server_credentials`, instead it uses a separate API altogether to add ports to the server `grpc_server_add_insecure_http2_port()`. This would not work for `XdsServerCredentials()` since the fallback credentials also need to be of the form `grpc_server_credentials`. 
- Modified insecure security connector's `MakeAuthContext()` to _NOT_ add peer identity since that results in `auth_context->IsPeerAuthenticated()` returning true instead of false
- Added a Core end2end test fixture which uses these new insecure credentials types.
- Modified and fixed Core end2end test call_creds.cc to test whether the call credentials are propagated or not based on the channel's security level. (Insecure and Fake credentials should only support call credentials that do not require any security.)

**Xds Server Credentials**

- Added experimental API for `XdsServerCredentials()`. 
To deal with `InsecureServerCredentials()` not being based on `SecureServerCredentials()`, hacks similar to those of `ChannelCredentials` have been introduced. These should go away once we can remove insecure builds from gRPC.
- Added end2end tests for `XdsServerCredentials()` for testing that fallback credentials work as expected.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24843)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks pretty good!  My only significant comment is about why we're no longer setting properties of the insecure auth context.  Other than that, I'd just like @yihuazhang to verify that this looks right to him.

Please let me know if you have any questions.  Thanks!

> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24843#-:-MNPW2zf2osLPVDeXqkA:btcdhkc)* status: all files reviewed, 5 unresolved discussions (waiting on @yashykt and @yihuazhang)

___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 123 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPP2oj0gzc0cXDIxmo:-MNPP2oj0gzc0cXDIxmp:b-q3i9l8) ([raw file](https://github.com/grpc/grpc/blob/d385d47d02f3724a42417a7144de44f09d8837c8/src/core/lib/security/credentials/xds/xds_credentials.cc#L123)):*
> ```cpp
> grpc_server_credentials* grpc_xds_server_credentials_create(
>     grpc_server_credentials* fallback_credentials) {
>   return new grpc_core::XdsServerCredentials(fallback_credentials->Ref());
> ```

Please add:

```
GPR_ASSERT(fallback_credentials != nullptr);
```
___
*[src/core/lib/security/security_connector/insecure/insecure_security_connector.cc, line 76 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPQKqlAxsuedwqocQo:-MNPQKqlAxsuedwqocQp:b-ko8086) ([raw file](https://github.com/grpc/grpc/blob/bad99c5772774e92690559fedb13b2b46a5f883d/src/core/lib/security/security_connector/insecure/insecure_security_connector.cc#L76)):*
> ```cpp
> InsecureChannelSecurityConnector::MakeAuthContext() {
>   auto ctx = MakeRefCounted<grpc_auth_context>(nullptr);
>   grpc_auth_context_add_cstring_property(
> ```

Looks like we're no longer setting `GRPC_TRANSPORT_SECURITY_TYPE_PROPERTY_NAME` or calling `grpc_auth_context_set_peer_identity_property_name()`.  Is that intentional?  Why is this not needed?

@yihuazhang, please verify that this change is okay.
___
*[src/cpp/server/secure_server_credentials.h, line 72 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPRErGEq4O_43tJgtk:-MNPRErGEq4O_43tJgtl:bgkuur6) ([raw file](https://github.com/grpc/grpc/blob/d385d47d02f3724a42417a7144de44f09d8837c8/src/cpp/server/secure_server_credentials.h#L72)):*
> ```objc
>       const std::shared_ptr<grpc::AuthMetadataProcessor>& processor) override;
> 
>   grpc_server_credentials* GetRawCredentials() { return creds_; }
> ```

Suggest calling this method `c_creds()`.
___
*[test/core/end2end/tests/call_creds.cc, line 526 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPVyP9B25ccEA9ywya:-MNPVyP9B25ccEA9ywyb:b-3vlmz5) ([raw file](https://github.com/grpc/grpc/blob/d385d47d02f3724a42417a7144de44f09d8837c8/test/core/end2end/tests/call_creds.cc#L526)):*
> ```cpp
> }
> 
> void call_creds(grpc_end2end_test_config config) {
> ```

The changes here look right to me, but given the security sensitivity, I'd like @yihuazhang to also confirm that it looks right to him.
___
*[test/core/security/insecure_security_connector_test.cc, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPV4j15mdHIhFCzLIy:-MNPV4j15mdHIhFCzLIz:bblgjx1) ([raw file](https://github.com/grpc/grpc/blob/bad99c5772774e92690559fedb13b2b46a5f883d/test/core/security/insecure_security_connector_test.cc#L39)):*
> ```cpp
>   const grpc_auth_property* prop = grpc_auth_property_iterator_next(&it);
>   ASSERT_NE(prop, nullptr);
>   EXPECT_STREQ(prop->name, GRPC_TRANSPORT_SECURITY_TYPE_PROPERTY_NAME);
> ```

Similar to my comment elsewhere, I'm not sure why we're removing this property.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24843)* status: all files reviewed, 5 unresolved discussions (waiting on @markdroth, @yashykt, and @yihuazhang)

___
*[src/core/lib/security/security_connector/insecure/insecure_security_connector.cc, line 76 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPQKqlAxsuedwqocQo:-MNQ-QHN1Lf-EW7LCAfn:b-wi9acs) ([raw file](https://github.com/grpc/grpc/blob/bad99c5772774e92690559fedb13b2b46a5f883d/src/core/lib/security/security_connector/insecure/insecure_security_connector.cc#L76)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Looks like we're no longer setting `GRPC_TRANSPORT_SECURITY_TYPE_PROPERTY_NAME` or calling `grpc_auth_context_set_peer_identity_property_name()`.  Is that intentional?  Why is this not needed?

@yihuazhang, please verify that this change is okay.
</blockquote></details>

(I missed adding this in the CL description.) The reason for not setting `grpc_auth_context_set_peer_identity_property_name()` is that this is used to denote whether the peer was authenticated or not. (`auth_context()->IsPeerAuthenticated()`). It makes sense for insecure connections to have this return false and hence the change.
___
*[test/core/security/insecure_security_connector_test.cc, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPV4j15mdHIhFCzLIy:-MNQ00KT0hilovIA8-Ni:b-5otlrc) ([raw file](https://github.com/grpc/grpc/blob/bad99c5772774e92690559fedb13b2b46a5f883d/test/core/security/insecure_security_connector_test.cc#L39)):*
> (I missed adding this in the CL description.) The reason for not setting `grpc_auth_context_set_peer_identity_property_name()` is that this is used to denote whether the peer was authenticated or not. (`auth_context()->IsPeerAuthenticated()`). It makes sense for insecure connections to have this return false and hence the change.

**Review by yashykt — COMMENTED** [review]
Updated the PR description with the reason for removing peer identity property from the auth context.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24843#-:-MNQ1V0O89bs3SKE1cCh:b-4xkhtf)* status: 27 of 30 files reviewed, 5 unresolved discussions (waiting on @markdroth, @yashykt, and @yihuazhang)

___
*[src/core/lib/security/credentials/xds/xds_credentials.cc, line 123 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPP2oj0gzc0cXDIxmo:-MNQ1RSX7ndRY-gFJFbr:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d385d47d02f3724a42417a7144de44f09d8837c8/src/core/lib/security/credentials/xds/xds_credentials.cc#L123)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add:

```
GPR_ASSERT(fallback_credentials != nullptr);
```
</blockquote></details>

Done.
___
*[src/cpp/server/secure_server_credentials.h, line 72 at r1](https://reviewable.io/reviews/grpc/grpc/24843#-MNPRErGEq4O_43tJgtk:-MNQ1TSy0EoFY3VL2LFI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d385d47d02f3724a42417a7144de44f09d8837c8/src/cpp/server/secure_server_credentials.h#L72)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this method `c_creds()`.
</blockquote></details>

Done.

**Review by markdroth — COMMENTED** [review]
This looks good to me, but I'll hold off on approving to make sure Yihua is okay with the changes.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24843#-:-MNQZfugEQkLfxK42OAZ:b-k3x9hn)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth, @yashykt, and @yihuazhang)

**Comment by yihuazhang** [comment]
Thanks for the PR. The changes to insecure server credentials LGTM overall, except for the following two issues:

- `GRPC_TRANSPORT_SECURITY_TYPE_PROPERTY_NAME` peer property is orthogonal to `grpc_auth_context_set_peer_identity_property_name()`. So I agree that we should not call `grpc_auth_context_set_peer_identity_property_name()` (sorry, I should have pointed it out in the previous PR) but `GRPC_TRANSPORT_SECURITY_TYPE_PROPERTY_NAME` needs to be added for keeping consistency with other credentials.

- Regarding the changes in`call_creds.cc`, I think the only change we need is the ability of generating/sending test call credentials (i.e., created by `grpc_md_only_test_credentials_create()`) which is controlled by `FEATURE_MASK_SUPPORTS_PER_CALL_CREDENTIALS_LEVEL_INSECURE` mask. For the case when sending secure credentials over the channels created with insecure or fake credentials, you can re-use the mask `      FEATURE_MASK_DOES_NOT_SUPPORT_SEND_CALL_CREDENTIALS)`, which basically validates that call credential sending fails if channel security level is insufficient.

PLMK if you have any further questions.

**Review by yashykt — COMMENTED** [review]
Thanks for the review @yihuazhang 
> GRPC_TRANSPORT_SECURITY_TYPE_PROPERTY_NAME peer property is orthogonal to grpc_auth_context_set_peer_identity_property_name(). So I agree that we should not call grpc_auth_context_set_peer_identity_property_name() (sorry, I should have pointed it out in the previous PR) but GRPC_TRANSPORT_SECURITY_TYPE_PROPERTY_NAME needs to be added for keeping consistency with other credentials.

Added this property back

> Regarding the changes incall_creds.cc, I think the only change we need is the ability of generating/sending test call credentials (i.e., created by grpc_md_only_test_credentials_create()) which is controlled by FEATURE_MASK_SUPPORTS_PER_CALL_CREDENTIALS_LEVEL_INSECURE mask. For the case when sending secure credentials over the channels created with insecure or fake credentials, you can re-use the mask FEATURE_MASK_DOES_NOT_SUPPORT_SEND_CALL_CREDENTIALS, which basically validates that call credential sending fails if channel security level is insufficient.

The feature mask `FEATURE_MASK_DOES_NOT_SUPPORT_SEND_CALL_CREDENTIALS` is not really needed anymore with `FEATURE_MASK_SUPPORTS_PER_CALL_CREDENTIALS_LEVEL_INSECURE`. (`FEATURE_MASK_SUPPORTS_PER_CALL_CREDENTIALS_LEVEL_INSECURE` implies `FEATURE_MASK_DOES_NOT_SUPPORT_SEND_CALL_CREDENTIALS`). Also, this mask was not really being properly tested earlier since the mode `FAIL` did not do anything different from `DESTROY`. I believe in the current state, we properly each case that we care about.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24843#-:-MNRDGTn0LDzMTQSZGag:bn954jb)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth, @yashykt, and @yihuazhang)

**Comment by yihuazhang** [comment]
Thanks for the explanation. I agree that we do not need `FEATURE_MASK_DOES_NOT_SUPPORT_SEND_CALL_CREDENTIALS` once we have `FEATURE_MASK_SUPPORTS_PER_CALL_CREDENTIALS_LEVEL_INSECURE`. However, I do not understand why cannot reuse `test_request_with_server_rejecting_client_creds()` to validate the failure of sending secure call creds over insecure channels. With it, you do not need a special handling of fail mode (e.g., [here](https://github.com/grpc/grpc/pull/24843/files#diff-d69cd53d17f2800b1a2355395866b8c1e5e9eacc3cca66bff2875b072c5e3329R246-R251)) in `request_response_with_payload_and_call_creds`, and change will be much simpler.

**Comment by yashykt** [comment]
@yihuazhang `test_request_with_server_rejecting_client_creds()` tests a very different thing. What it does is, it configures the server to reject the call creds received from the client by adding a `grpc_auth_metadata_processor` that fails the call. So, we get a failure even if we use test creds with a secure channel.

**Comment by yihuazhang** [comment]
Chatted with @yashykt offline. It was my mistake that I got confused about `status` of `GRPC_OP_RECV_STATUS_ON_CLIENT` op that is checked against `GRPC_STATUS_UNAUTHENTICATED` in `test_request_with_server_rejecting_client_creds()` and in `request_response_with_payload_and_call_creds`. The latter is the one returned from `client_auth_filter.cc` while the former is the one returned from the server. We definitely need the check in `request_response_with_payload_and_call_creds` to validate a grpc call is rejected because of insufficient security level, by pairing it with default (success)`grpc_auth_metadata_processor`.

**Review by yihuazhang — APPROVED** [review]

**Review by markdroth — APPROVED** [review]
Looks great!

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24843#-:-MNV-koH596ebBDnmI30:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by yashykt** [comment]
Thanks for reviewing! The interop to-prod tests have been had an infra issue (b/174073491)

**Pull request merged**
