### PR TITLE
Add integration test case descriptions

### LINKED ISSUE #1205: Migrate interop test specifications to open source
We have a document specifying how our interoperability tests are required to work, but it's imprecise, unversioned, and not yet part of the project's open source content. As our interoperability tests become more and more the metric by which we measure this library's development, the fact that they conform to an invisible specification becomes proportionately more an area of poor communication on our part.

We should migrate that document's content to this repository and flesh it out so that it's a complete specification of all of our interoperability tests. It should be possible for those implementing gRPC in strange languages (Ante, Befunge, and Standard ML of New Jersey) to write their own interoperability test code without having to reverse-engineer the extant implementations in this library, as they would have to do today.

### PR DESCRIPTION
**Pull request by ejona86**
It is a partially manual port from Google Docs to Markdown. The content
was not changed.

@nathanielmanistaatgoogle

Resolves #1205.

I discussed the location of the document with @nicolasnoble, and this is where we thought it made the most sense.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
I'm uncomfortable with the way we're calling them "Cross Language", "Integration", and "Interop[erability]" tests - I think it's slightly confusing to English readers and a flat-out obstacle to those who don't read English well to not be using one single name. I don't want to ask for changes to the doc content in this simple content-migration change, but can I ask you to change "integration" to "interoperability" in the content's filename and in your commit log message?

**Comment by ejona86** [comment]
@nathanielmanistaatgoogle, PTAL. I just changed the title, file name, and commit message (which required modifying the previous commit).

**Comment by nathanielmanistaatgoogle** [comment]
LGTM; thanks for the tweak. Anything else before merge?

**Comment by ejona86** [comment]
@nathanielmanistaatgoogle, I don't think so. It is "good enough" and can be improved from here. I'll update the existing doc to point to this new location once it is merged.

**Comment by ejona86** [comment]
Oh, @nathanielmanistaatgoogle, and if you make improvements, know that I don't watch the grpc repo, but would be happy to review if you @mention me.

**Pull request merged**
