### PR TITLE
Fixing Logical DNS case:

### PR DESCRIPTION
**Pull request by donnadionne**
- override child policy with pick_first
- set ignore_reresolution to false

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25298)

### CODE REVIEW

**Comment by donnadionne** [comment]
Wanted to confirm this is what we should do for the logical dns case.

The logical dns test is passing with this case; but the mixed type case is not.  Using this code review as a base to discuss and debug.

**Review by markdroth — CHANGES_REQUESTED** [review]
Thanks for doing this!

The code change looks functionally correct to me (my comments are all cosmetic), so I'm not sure why the test is failing.  You'll have to debug it.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25298#-:-MSFSwgr0hs_oM1dEhFE:brv47p9)* status: all files reviewed, 5 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 133 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFO0VCBqaigFYcGKOD:-MSFO0VD8jlCe1EoH-nF:b-kjbx0r) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L133)):*
> ```cpp
>     DiscoveryMechanism(
>         RefCountedPtr<XdsClusterResolverLb> xds_cluster_resolver_lb,
>         size_t index, bool override_child_policy, bool reresolution)
> ```

We don't need to store these values in the base class.  Let's just make the methods pure virtual and have the subclasses implement them.  That way, they can return constants, so we don't have to store the values in each discovery mechanism instance.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 140 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFOCHm2AK-eWPFzuic:-MSFOCHm2AK-eWPFzuid:b-76f6pj) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L140)):*
> ```cpp
>     virtual void Start() = 0;
>     void Orphan() override = 0;
>     bool override_child_policy() const { return override_child_policy_; }
> ```

If we're overridding the child policy, then this needs to return what child policy to use, probably as a `Json::Array` object.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 141 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFOTGwAJV6HiPqccEl:-MSFOTGwAJV6HiPqccEm:b-36t1kv) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L141)):*
> ```cpp
>     void Orphan() override = 0;
>     bool override_child_policy() const { return override_child_policy_; }
>     bool reresolution() const { return reresolution_; }
> ```

Let's call this `disable_reresolution`, since we're only going to populate the field in the priority policy's config if this is true.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 866 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFQfyR02TxDTcWpA53:-MSFQfyR02TxDTcWpA54:bu96f24) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L866)):*
> ```cpp
>     if (discovery_mechanisms_[discovery_index]
>             .discovery_mechanism->override_child_policy()) {
>       child_policy = Json::Array{
> ```

As mentioned above, this object should be returned by the discovery mechanism.  Otherwise, the "override child policy" bool is really a "force use of pick_first" bool, and I think we want this to be a little more general-purpose.  That way, if we need to force use of some other child policy in the future for a new discovery mechanism, we can do that.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 942 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFSD0f5WkUZ354x2Uk:-MSFSD0gDLhvPSp6PeP-:b4ngvyg) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L942)):*
> ```cpp
>     priority_children[child_name] = Json::Object{
>         {"config", std::move(locality_picking_policy)},
>         {"ignore_reresolution_requests",
> ```

If we're not setting this to true, then we don't need to add it to the config at all, because it's off by default in the priority policy.

**Review by donnadionne — COMMENTED** [review]
I fixed the code review suggestions.

I found 1 reason why we could not failover from logical dns to EDS: when the backend for logical DNS was shutdown, pick_first saw the failure but translated it to IDLE, this IDLE state was propagated all the way up to CDs.

I made a quick change (you will see in pick_first.cc) to report TRANSIENT_FAILURE instead of IDLE, this allowed the failover from logical dns to EDS work; in fact all tests passed.

But I don't think this is the right fix as the translation from TRANSIENT_FAILURE to IDLE was for a reason.

Furthermore, I tested bringing backup the backend for logical DNS and expecting us to fall back to use that backend; but it seems that the TRANSIENT_FAILURE will lead pick_first to "[pick_first 0x7f121c00ee90] Destroying subchannel_list 0x7f121c00bb60" and priority police will skip over the logical DNS even after the backend is up.

Let's discuss how best to fix all of this?

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25298#-:-MSRNEOS0rI2ejPzUdvT:bwkqyky)* status: all files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 133 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFO0VCBqaigFYcGKOD:-MSRN7tY7Sar7t-qTyvk:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L133)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We don't need to store these values in the base class.  Let's just make the methods pure virtual and have the subclasses implement them.  That way, they can return constants, so we don't have to store the values in each discovery mechanism instance.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 140 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFOCHm2AK-eWPFzuic:-MSRN9B2Dphkl7C-0Ji8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L140)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're overridding the child policy, then this needs to return what child policy to use, probably as a `Json::Array` object.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 141 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFOTGwAJV6HiPqccEl:-MSRN9kl4MGGpG44VMHm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L141)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Let's call this `disable_reresolution`, since we're only going to populate the field in the priority policy's config if this is true.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 866 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFQfyR02TxDTcWpA53:-MSRNBfPD1lcCSBViHgf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L866)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As mentioned above, this object should be returned by the discovery mechanism.  Otherwise, the "override child policy" bool is really a "force use of pick_first" bool, and I think we want this to be a little more general-purpose.  That way, if we need to force use of some other child policy in the future for a new discovery mechanism, we can do that.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 942 at r1](https://reviewable.io/reviews/grpc/grpc/25298#-MSFSD0f5WkUZ354x2Uk:-MSRNCyfA71tJW3ttqs_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/70cd963374aa812676af34414301557d33b494be/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L942)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're not setting this to true, then we don't need to add it to the config at all, because it's off by default in the priority policy.
</blockquote></details>

Done.

**Review by markdroth — CHANGES_REQUESTED** [review]
The changes to xds_cluster_resolver look good.

The pick_first change is definitely incorrect; pick_first *should* report IDLE in that case.  But you're right that this poses a problem for failing over from a LOGICAL_DNS cluster to another cluster at a lower priority.  I'll have to chat with Eric and Doug about this.

That having been said, I think we should not be running into this in our existing tests.  The case we actually expect to see is where the aggregate cluster points first to an EDS cluster and then to a LOGICAL_DNS cluster -- i.e., the LOGICAL_DNS cluster should be second in the list, not first.  It looks like the `AggregateClusterMixedType` test is covering the wrong case.

For now, let's do the following:
- Make a copy of the `AggregateClusterMixedType` test called `AggregateClusterEdsToLogicalDns` that puts the EDS cluster first.
- Rename the current `AggregateClusterMixedType` test to `DISABLED_AggregateClusterLogicalDnsToEds`, and add a TODO about re-enabling it once we figure out how to address the pick_first IDLE problem.
- Just to be safe, let's also modify all three of the aggregate cluster tests to also check that when the backend from the first underlying cluster comes back up, traffic automatically moves back to that backend.

I'll follow up with Eric and Doug about how to handle the pick_first problem.

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25298#-:-MSTEFPQEpHT9vmZRy3u:b-h7wuv6)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1003 at r2](https://reviewable.io/reviews/grpc/grpc/25298#-MSTE4ED4YzbGFFwIrK7:-MSTE4ED4YzbGFFwIrK8:bwlfauq) ([raw file](https://github.com/grpc/grpc/blob/dab0fffa502e24bd0f4ab187fbfd0e43ff5e1898/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1003)):*
> ```cpp
>   }
>   return config;
> }  // namespace
> ```

This comment is incorrect.  This is actually the end of a function.

**Review by donnadionne — COMMENTED** [review]
Made the test changes.

EDS->Logical DNS test is working
logical DNS->EDS is disabled for now
added the moving back check

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25298#-:-MSTstoO8Jlm6DeKq-e1:brrlw9c)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 1003 at r2](https://reviewable.io/reviews/grpc/grpc/25298#-MSTE4ED4YzbGFFwIrK7:-MSTt8K20nzw5RnD_Oo5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/dab0fffa502e24bd0f4ab187fbfd0e43ff5e1898/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L1003)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This comment is incorrect.  This is actually the end of a function.
</blockquote></details>

Done.

**Review by markdroth — CHANGES_REQUESTED** [review]
I think I would actually like to dig into why the Logical DNS -> EDS test is failing.  Thinking about this further, it doesn't really make sense to me.

Other than that, this looks great!

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25298#-:-MSTzukb7nRDCSb99qg8:b-mamb2b)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5469 at r3](https://reviewable.io/reviews/grpc/grpc/25298#-MSTxbWC5Bd8A0YZL2Xn:-MSTxbWC5Bd8A0YZL2Xo:b-5g8q7b) ([raw file](https://github.com/grpc/grpc/blob/9eca72a8d7ea7e951706f816e240c4f8d287c37e/test/cpp/end2end/xds_end2end_test.cc#L5469)):*
> ```cpp
> 
> TEST_P(CdsTest, DISABLED_AggregateClusterLogicalDnsToEds) {
>   // TODO(donnadionne): re-enable after pick_first policy works around
> ```

So, thinking about this further, I'm not actually sure why this test is failing.  I think this should actually work without any changes to pick_first or the priority policy.

Here's what I think should be happening:
1. Traffic initially goes to backend 1 via pick_first child policy for priority 0.
2. We shut down backend 1, which sends a GOAWAY, which causes pick_first to report IDLE.  The priority policy does *not* fail over at this point, because it treats IDLE the same as READY.
3. The next RPC that gets sent should cause pick_first to try to reconnect to backend 1, so it reports CONNECTING.  However, the connection attempt should immediately fail, at which point pick_first should report TRANSIENT_FAILURE.  At this point, the priority policy should create the child for priority 1 (the EDS policy), and it will report CONNECTING.

You said this test was failing, but you didn't say what the failure was.  Can you enable this test (remove the `DISABLED_` prefix from the name) and then point me at the log for a failing instance, with the usual tracers enabled?  Thanks!

**Review by donnadionne — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25298)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 5469 at r3](https://reviewable.io/reviews/grpc/grpc/25298#-MSTxbWC5Bd8A0YZL2Xn:-MSV8fsK7CDwWYOpM1IS:bdu8a78) ([raw file](https://github.com/grpc/grpc/blob/9eca72a8d7ea7e951706f816e240c4f8d287c37e/test/cpp/end2end/xds_end2end_test.cc#L5469)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

So, thinking about this further, I'm not actually sure why this test is failing.  I think this should actually work without any changes to pick_first or the priority policy.

Here's what I think should be happening:
1. Traffic initially goes to backend 1 via pick_first child policy for priority 0.
2. We shut down backend 1, which sends a GOAWAY, which causes pick_first to report IDLE.  The priority policy does *not* fail over at this point, because it treats IDLE the same as READY.
3. The next RPC that gets sent should cause pick_first to try to reconnect to backend 1, so it reports CONNECTING.  However, the connection attempt should immediately fail, at which point pick_first should report TRANSIENT_FAILURE.  At this point, the priority policy should create the child for priority 1 (the EDS policy), and it will report CONNECTING.

You said this test was failing, but you didn't say what the failure was.  Can you enable this test (remove the `DISABLED_` prefix from the name) and then point me at the log for a failing instance, with the usual tracers enabled?  Thanks!
</blockquote></details>

Found the cause: ExitIdleLocked is not being called; reason: cds and xds_cluster_resolver both did not implement it so we were not calling all the way down to pick_first.

**Review by markdroth — APPROVED** [review]
Thanks for digging into that!  This looks great!

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25298#-:-MSYL_m01LsqQkwsFj61:bkzyobg)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by donnadionne** [comment]
known issue #25236

**Pull request merged**
