### PR TITLE
Python: delete duplicted imports in the example of python

### LINKED ISSUE #6923: Example Python contains lots of duplicated 'import' calls
You can see this directly in the ["route_guide" example](https://github.com/grpc/grpc/blob/release-0_14/examples/python/route_guide/route_guide_pb2.py#L362), where it includes the `route_guide_pb2` module (even though it *is* the `route_guide_pb2` module) eight times in each function that includes it.

I'm seeing it four times in each service I'm generating.

### PR DESCRIPTION
**Pull request by thinkerou**
Attempt to fix #6923.
The two files is regenerated using `sh run_codegen.sh` command not edited by hand.

### CODE REVIEW

**Comment by murgatroid99** [comment]
Did you just regenerate those files from the route_guide.proto file, or did you edit them by hand?

And please clean up all of the extra commits in this PR.

**Comment by thinkerou** [comment]
@murgatroid99 I regenerated with `sh run_codegen.sh` command, OK, I will clean up extra commits, thx!

**Comment by nathanielmanistaatgoogle** [comment]
Code looks good and thank you for including just one commit.

Please follow [these guidelines](http://chris.beams.io/posts/git-commit/#seven-rules) in your commit message - in particular, the fact that the content of your commit was generated by a script rather than hand-authored by you is an important thing to record in your commit message.

Thank you for the contribution!

**Comment by thinkerou** [comment]
@nathanielmanistaatgoogle I have attempted to update commit-comment, thanks.

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
Can we rebase to give jenkins a kick and get a fresh test run?

**Comment by thinkerou** [comment]
@jtattermusch I have fetched upstream and rebase, but jenkins not run automatically.

**Comment by nathanielmanistaatgoogle** [comment]
test this please

**Comment by nathanielmanistaatgoogle** [comment]
(@thinkerou: when we say "test this please", that's us instructing Jenkins to run the tests, not you.)

**Comment by jtattermusch** [comment]
this is ok to test

**Comment by jtattermusch** [comment]
Jenkins is refusing to run tests on this PR for some reason.

**Comment by thinkerou** [comment]
@nathanielmanistaatgoogle @jtattermusch I regenerate *_pb2.py by script for lacking import-grpc before.

**Comment by nathanielmanistaatgoogle** [comment]
test this please

**Comment by thinkerou** [comment]
@nathanielmanistaatgoogle the commit need to commit v1.0.x branch?

**Comment by nathanielmanistaatgoogle** [comment]
I've drafted [pull request 7419](https://github.com/grpc/grpc/pull/7419) (which I suspect will supersede this pull request) against the `v1.0.x` branch.

**Comment by nathanielmanistaatgoogle** [comment]
Obviated by [pull request 7419](https://github.com/grpc/grpc/pull/7419); closing.

**Pull request closed without merging**
