### PR TITLE
Upgrade third_party/protobuf to 3.2.0 and update C# nugets.

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Currently, there's a problem building python, because of missing  `well_known_types_embed.cc` (that file is generated when building protobuf, but grpcio_tools basically replicates protobuf's build and fails to generate it.
```
gcc: error: third_party/protobuf/src/google/protobuf/compiler/js/well_known_types_embed.cc: No such file or directory
```
https://github.com/google/protobuf/blob/17174b54ddd040a326dec6db75d1bfb5e5b3caa9/BUILD#L243

**Comment by jtattermusch** [comment]
@kpayson64, do you any suggestion what we should do with the grpcio_tools build?

**Comment by kpayson64** [comment]
@jtattermusch, @mehrdada Is working on addressing this

**Comment by mehrdada** [comment]
I have drafted a patch on this pull request that embeds the generated code, and substitutes the code generator and the generated code .cc files in the setup.py for grpcio-tools package with the embedded file. On my machine, python tests are passing. Please pull from my branch to get the patch.

**Comment by jtattermusch** [comment]
@mehrdada, thanks for the patch! A few remarks:
- on github, you can actually create a pull request against someone else's pull request. (in case you didn't know). That's what we usually use for situations like this, as it allows to comment/pushback on the suggested changes.
- I think I am fine with the hack you came up with for now, but we should really file an issue to track this, so we can eventually resolve it in a cleaner way.

**Comment by jtattermusch** [comment]
There seems to be an issue with building python plugin on Windows:
https://grpc-testing.appspot.com/job/gRPC_pr_win/3005/testReport/junit/(root)/aggregate_tests/run_tests_python_windows_dbg_native/

The likely cause it that the windows build happens with Visual C++ 2008, which is an ancient version.
This can be either: 1. because of change we've made to our plugin code  2. changes made in protobuf 3.2.0 (harder to fix because it's not our code).

**Comment by mehrdada** [comment]
I agree—we debated the way to move forward at length and most people agree that the Python build system is hackish and instead of treating protobuf as a black-box dependency, it has adopted its source code. However, it is unclear what the right move is to keep surprises for grpcio-tools package users minimal (prebuilt binaries will break "pip install" for unsupported architectures and rewriting the python extension to wrap a subprocess instead of the current approach may cause unanticipated side effects), so I went with the conservative change at this point, considering my [lack of] expertise in the code base and python runtime.

The Windows compilation issue seems unrelated to our plugin code—looks like protobuf itself has build issues with the Windows compiler. A header file included from "python_generator.cc" is not building, which is not modified by us at all. (Of course, it might be the effect of our Python build system circumventing the protobuf autoconf/automake and hackishly setting some compiler flags.)

Is it a common problem in previous updates of protobuf library?

**Comment by mehrdada** [comment]
Actually, upon further investigation, GRPC also has a file with the identical name "python_generator.cc" in its code base. I now think that might be the cause.

**Comment by jtattermusch** [comment]
@mehrdada  I think I might have a windows fix, let's see what the tests say. PTAL.

@dgquintas  tentatively, it would be good to bump protobuf to 3.2 before creating 1.2.x branch, but it's fine to skip if there are issues with this PR.

**Comment by jtattermusch** [comment]
Known failures:
- https://github.com/grpc/grpc/issues/9186
- https://github.com/grpc/grpc/issues/9804
- https://github.com/grpc/grpc/issues/9980
- https://github.com/grpc/grpc/issues/9903
- https://github.com/grpc/grpc/issues/9956
- https://github.com/grpc/grpc/issues/9399

**Comment by jtattermusch** [comment]
Tests (except known flakes) look good, this can be merged right after approving.

**Pull request merged**
