### PR TITLE
Fix TSAN issue in backup poller

### PR DESCRIPTION
**Pull request by sreecha**
This fixes one of the tsan failures in https://github.com/grpc/grpc/issues/13125
There are about four more that needs to be fixed.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%      +8 [None]     +80  +0.0%

  +0.0%      +8 TOTAL      +80  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%      +8 [None]     +80  +0.0%

  +0.0%      +8 TOTAL      +80  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%      +8 [None]     +80  +0.0%

  +0.0%      +8 TOTAL      +80  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%      +8 [None]     +80  +0.0%

  +0.0%      +8 TOTAL      +80  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%      +8 [None]     +80  +0.0%

  +0.0%      +8 TOTAL      +80  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by sreecha** [comment]
Asan C++ (internal CI) — Internal CI build failed: https://github.com/grpc/grpc/issues/13247
Basic Tests MacOS [dbg] (internal CI) — Internal CI build failed: https://github.com/grpc/grpc/issues/13148
Basic Tests MacOS [opt] (internal CI) — Internal CI build failed: https://github.com/grpc/grpc/issues/13148
Basic Tests Multi-language Linux (internal CI) — Internal CI build failed: https://github.com/grpc/grpc-node/pull/86
Basic Tests Windows [dbg] (internal CI) — Internal CI build failed: https://github.com/grpc/grpc/issues/13149
Interop Cloud-to-Cloud Tests (internal CI) — Internal CI build failed: https://github.com/grpc/grpc/issues/13253
Tsan C++ (internal CI) — Internal CI build failed: https://github.com/grpc/grpc/issues/13178
Basic Tests C++ Linux [opt] (internal CI) — Internal CI build failed: ??

**Pull request merged**
