### PR TITLE
Add v1.12.0 release of grpc-java

### PR DESCRIPTION
**Pull request by zpencer**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by zpencer** [comment]
@jtattermusch PTAL

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by zpencer** [comment]
@jtattermusch can you also do the merge, I don't think I have access.

**Comment by zpencer** [comment]
@jtattermusch ping

**Pull request merged**
