### PR TITLE
[PSM Interop] Simplify PSM Interop Kokoro buildscripts

### PR DESCRIPTION
**Pull request by sergiitk**
Integrates the new features of the the Kokoro PSM Interop install library introduced in grpc/psm-interop#73.

Nearly all common functionality was moved from per-language/per-branch PSM Interop build scripts to [psm_interop_kokoro_lib.sh](https://github.com/grpc/psm-interop/blob/main/.kokoro/psm_interop_kokoro_lib.sh):
1. The list of tests in the each test suite 
2. Per-test-suite flag customization
3. `run_test` methods
4. `build_docker_images_if_needed` methods
5. Generic `build_test_app_docker_images` methods (simple docker build + docker push + docker tag). grpc-java is one exception, as it doesn't run docker directly, but a cloudbuild flow.

Now all PSM Interop jobs share the same buildscripts by all test suites:
1.  buildscript that invokes the test: `psm-interop-test-{language}.sh` (configured as `build_file` in the build cfg)
2. buildscript that builds the xDS test client/server and publishes them as a Docker image: `psm-interop-build-{language}.sh` (conventional name called from `psm_interop_kokoro_lib.sh`)

`psm-interop-test-{language}.sh`:
1. Sets `GRPC_LANGUAGE`, `BUILD_SCRIPT_DIR` environment variables.
2. Downloads the shared `psm_interop_kokoro_lib.sh` from the main branch of the psm-interop repo.
3. Sources `psm-interop-build-{language}.sh`
4. Calls `psm::run "${PSM_TEST_SUITE}"` (`PSM_TEST_SUITE` configured in the cfg file).

`psm-interop-build-{language}.sh`:
1. Defines `psm::lang::build_docker_images` which is called from `psm_interop_kokoro_lib.sh`.
2. Invokes any repo-specific logic.
3. May use `psm::build::docker_images_generic` for generic Docker build, tag, push, or provide implement its own build/publish method.

References:
- b/288578634
- See the full list of the new features at grpc/psm-interop#73.
- Additional fixes to the shared lib: grpc/psm-interop#78, grpc/psm-interop#79

### CODE REVIEW

**Comment by sergiitk** [comment]
Using grpc/psm-interop#73 / grpc/psm-interop@7186db2:

- [ ] [grpc/core/master/linux/grpc_xds_url_map](https://source.cloud.google.com/results/invocations/ef94871d-1ab4-4d55-9a47-80513110ea40)

**Comment by sergiitk** [comment]
Full LB suite run 
- [ ] [grpc/core/master/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/860fd40c-5ebb-49ae-8f30-0050d3b71f97)

URL Map py:
- [ ] [grpc/core/master/linux/grpc_xds_url_map_python](https://source.cloud.google.com/results/invocations/f3231074-f70a-4872-8939-2a0741d779ad)

**Comment by sergiitk** [comment]
@yashykt  please review, but don't merge it yet. I'd like to wait until I got approvals on the same change from the rest of the repos. So we don't have to do another set of backports if anything comes up.

**Comment by sergiitk** [comment]
The last check using the install script from `main` (to be updated).

CPP:
- [ ] [grpc/core/master/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/d348cca1-3710-489b-914b-f19b13ced501)

Python:
- [ ] [grpc/core/master/linux/grpc_xds_k8s_lb_python](https://source.cloud.google.com/results/invocations/700914da-45f3-4faa-aae5-a3b95013d750)

**Comment by sergiitk** [comment]
Using grpc/psm-interop@2cbdfd02 (main) [to be updated].

CPP:
- [ ] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/eb5acdea-fd8b-4a4d-a2bc-e9c4365932b5)

Python:
- [ ] [grpc/core/master/linux/psm-csm-python](https://source.cloud.google.com/results/invocations/74c8c078-76ff-403c-95ce-fd3ef2785d9d)

**Review by yashykt — APPROVED** [review]

**Pull request closed without merging**
