### PR TITLE
[v1.30.x] Backport #23335 (Added missing `deps_linkage` property)

### PR DESCRIPTION
**Pull request by veblush**
This is required for Ruby Windows. 

Fixes: #23423

### CODE REVIEW

**Comment by veblush** [comment]
[grpc_build_artifacts_multiplatform](https://sponge.corp.google.com/invocation?id=ad2bb845-f534-497a-b35e-cac78cc712fb&searchFor=): running

**Comment by srini100** [comment]
Is a patch required? If yes, let's wait until @markdroth merges the upb changes for xDS logging.

**Comment by veblush** [comment]
@srini100 Yes, this is required for Ruby *only*. Without this, Ruby artifacts don't work on Windows.

**Comment by markdroth** [comment]
The upb changes are merged, but they seem to have caused some test failures for things that run on master but not on individual PRs.  @nicolasnoble is looking at those issues, but I don't think we should back-port the upb changes to 1.30 until those problems get resolved.

**Comment by srini100** [comment]
@veblush, is this PR still needed?

**Comment by veblush** [comment]
@srini100 Yes, this is required to fix #23423. The latest version of gRPC Ruby (1.30.1) is not working now on Windows.

**Pull request merged**
