### PR TITLE
Fix port server in internal CI

### PR DESCRIPTION
**Pull request by jtattermusch**
- force enable ipv6 (see https://github.com/moby/moby/issues/32924)
- also cleanup the rc scripts

Supersedes https://github.com/grpc/grpc/pull/11081

### CODE REVIEW

**Comment by matt-kwong** [comment]
Jenkins, test this please

**Comment by jtattermusch** [comment]
Jenkins workers seem fine based on test results in https://github.com/grpc/grpc/pull/11081.

**Comment by jtattermusch** [comment]
Merging to get the internal_ci ball rolling.

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Pull request merged**
