### PR TITLE
Extend bazel BUILD file to build all the C/C++ libraries as well as protobuf plugins.

### PR DESCRIPTION
**Pull request by mzhaom**

### CODE REVIEW

**Comment by murgatroid99** [comment]
Please do not modify the BUILD file directly. Instead, you should modify `templates/BUILD.template` and run `tools/buildgen/generate_projects.sh` to regenerate the BUILD file.

**Comment by nicolasnoble** [comment]
More specifically, your tools/buildgen/generate_bazel_build.py is pretty close to what you'd need to do in templates/BUILD.template

**Comment by mzhaom** [comment]
Please take another look. Thanks.

**Comment by nicolasnoble** [comment]
Yep, looks great. Thanks!

**Pull request merged**
