### PR TITLE
Revert "Added absl::Status support to grpc_closure.error"

### PR DESCRIPTION
**Pull request by ctiller**
Reverts grpc/grpc#27308

Let's not do this before a long weekend.

### CODE REVIEW

**Review by drfloob — APPROVED** [review]
LGTM, the reverted commit was merged an hour ago, seems safe that nothing is relying on this code yet. Pinging @veblush for next steps.

**Comment by veblush** [comment]
@ctiller Is this just in case? or do we have an actual breakage by this? I'm fine with either, though.

**Comment by ctiller** [comment]
This is just in case - we've got actual fixes that need to go in, and this seems risky to import at the same time.

**Comment by ctiller** [comment]
Suggest relanding this after the first import on Monday.
@apolcyn can coordinate.

**Pull request merged**
