### PR TITLE
Merge 1.8.x into master

### PR DESCRIPTION
**Pull request by apolcyn**
merges #13917 and #13921

cc @murgatroid99, this takes the changes from #13917 into master.

For #13921, this is a no-op (we want only what's on master already)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
I think it'd be better to merge at the point AFTER the version bump, and manually resolve the inevitable version number conflict, so that the future bugfixes on 1.8.x are easily upmerge-able and not cause an accidental version overwrite (but it is fine since future commits on 1.8.x are hopefully going to be small if any).

**Comment by apolcyn** [comment]
test failures: 

* c++ linux dbg - https://github.com/grpc/grpc/issues/13148
* c++ linux opt - https://github.com/grpc/grpc/issues/10092
* basic tests c windows - https://github.com/grpc/grpc/issues/12748
* tsan c++ - https://github.com/grpc/grpc/issues/13148

**Comment by apolcyn** [comment]
as chatted offline, lets upmerge https://github.com/grpc/grpc/pull/13934 separately from this PR

**Pull request merged**
