### PR TITLE
Fix Objective-C Mojave related issues

### PR DESCRIPTION
**Pull request by muxi**
Fix Objective-C Mojave related issues. Tested with adhoc experimental tests.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Created cl/283933462 . If we are confident that this will work, we can just submit both the changes at ~ the same time.

**Comment by muxi** [comment]
Note this PR only fixes ObjC issues. [Tool failures](https://sponge.corp.google.com/target?id=40fa9044-35a2-4532-8056-e1473d6f208d&target=grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp&searchFor=) and C# still need fixing before the cl can be submitted.

**Comment by jtattermusch** [comment]
> Note this PR only fixes ObjC issues. [Tool failures](https://sponge.corp.google.com/target?id=40fa9044-35a2-4532-8056-e1473d6f208d&target=grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp&searchFor=) and C# still need fixing before the cl can be submitted.

That means all the changes need to go in at the same time.

**Comment by muxi** [comment]
Doesn't sound very attractive

**Comment by dennycd** [comment]
closing as patch no longer valid

**Pull request closed without merging**
