### PR TITLE
Enable prod outlier detection interop tests for C++ and Python

### PR DESCRIPTION
**Pull request by murgatroid99**
The Node test has confirmed that this feature is working on prod, so we can enable the test in other languages.

### CODE REVIEW

**Review by markdroth — APPROVED** [review]

**Comment by ctiller** [comment]
can this wait until post fixit?

**Comment by markdroth** [comment]
It can wait if you prefer, yeah.  I don't think it would actually be a problem for it to go in now, though, since it doesn't touch anything that affects the fixit either way.  The fixit doesn't include the xDS interop tests.

**Comment by murgatroid99** [comment]
Manual Python test job run with the new test passing: https://source.cloud.google.com/results/invocations/a0a46de7-0df0-4cd1-ad1b-8e73842b155c/targets

**Comment by murgatroid99** [comment]
Can I merge this now? If not, when can I merge it?

**Comment by markdroth** [comment]
@ctiller will take care of merging this later today.

**Pull request merged**
