### PR TITLE
xds: Change ADS parsing to not stop at the first error

### PR DESCRIPTION
**Pull request by markdroth**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25329)

### CODE REVIEW

**Review by lidizheng — CHANGES_REQUESTED** [review]
Thanks for helping out on this change! It would take much much longer for me to ramp up, and I wouldn't able to get the validation errors as well.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25329#-:-MS_dZw38S8nwSKH67cD:b-hnv2kj)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 378 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_aIitBo70reXiwpO_:-MS_aIitBo70reXiwpOa:b-j5gf91) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.h#L378)):*
> ```objc
>   // If there is any other type of validation error, the parse_error
>   // field will be set and the resource_names_failed field will be
>   // populated.
> ```

Though obvious, but we could also mention the parse_error will not be GRPC_ERROR_NONE.
___
*[src/core/ext/xds/xds_api.h, line 390 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_b6bgCwTC6gMZmqfQ:-MS_b6bgCwTC6gMZmqfR:ba954sg) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.h#L390)):*
> ```objc
>     CdsUpdateMap cds_update_map;
>     EdsUpdateMap eds_update_map;
>     std::set<std::string> resource_names_failed;
> ```

Thanks. This data structure will be very handy to craft CSDS response. So whether under SotW or incremental ADS, the `parse_error` above will be mapped to all resource with names here.
___
*[src/core/ext/xds/xds_api.cc, line 1483 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_VdnOEMFG9mKWxd7z:-MS_VdnPEh_Ch-tH4V_2:b65b4r9) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.cc#L1483)):*
> ```cpp
>     if (!IsLds(type_url)) {
>       errors.push_back(GRPC_ERROR_CREATE_FROM_COPIED_STRING(
>           absl::StrCat("index ", i, ": Resource is not LDS.").c_str()));
> ```

```
error parsing "EDS" response: resource "endpoints-0": EDS response contains a locality without ID, locality: lb_endpoints:{endpoint:{address:{socket_address:{address:"0.0.0.0" port_value:123}}}}resource "endpoints-1": EDS response contains a locality without ID, locality: lb_endpoints:{endpoint:{address:{socket_address:{address:"1.1.1.1" port_value:456}}}}
```

Optional: this is a pure stylish discussion. From the first pass, I wasn't sure what does index mean, could it means the index number of the error or the index of the resource in the update list. I think the output from Golang is slightly more readable. I know their resource name could be "endpoints-0" and "endpoints-1". When listener name is not yet available, could we use something like `<resource-type> <index>:`?
___
*[src/core/ext/xds/xds_api.cc, line 1548 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_cXmH4zR9UL8Jtx7V:-MS_assY0okk7qyabV1c:b-ie5zcw) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.cc#L1548)):*
> ```cpp
>           error));
>       resource_names_failed->insert(listener_name);
>     }
> ```

It looks like we also added validation errors in this PR. Just a note, in case people reading this PR in future.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3012 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_d03o0rH_5tJNBbBZ:-MS_d03o0rH_5tJNBbB_:bt53qjr) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/test/cpp/end2end/xds_end2end_test.cc#L3012)):*
> ```cpp
>   EXPECT_THAT(
>       response_state.error_message,
>       ::testing::HasSubstr("Listener has neither address nor ApiListener"));
> ```

Do we need to add one test case that ensures multiple error messages can be produced by `ParseAdsResponse` (or four each covers a type of xDS)? Also, a test to check if the `resource_names_failed` field is populated properly?

**Review by markdroth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25329)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @lidizheng)

___
*[src/core/ext/xds/xds_api.h, line 378 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_aIitBo70reXiwpO_:-MScjJmG4yy3heTtWi0z:bll4mdj) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.h#L378)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Though obvious, but we could also mention the parse_error will not be GRPC_ERROR_NONE.
</blockquote></details>

That's basically what "will be set" means in this context.  But I've clarified the wording.
___
*[src/core/ext/xds/xds_api.h, line 390 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_b6bgCwTC6gMZmqfQ:-MScjPHp8Tbhseqx8He6:btmiaps) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.h#L390)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Thanks. This data structure will be very handy to craft CSDS response. So whether under SotW or incremental ADS, the `parse_error` above will be mapped to all resource with names here.
</blockquote></details>

Yup, that was exactly the reason I added it.
___
*[src/core/ext/xds/xds_api.cc, line 1483 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_VdnOEMFG9mKWxd7z:-MScjTo80545EpzWHcc9:bwh32e7) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.cc#L1483)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

```
error parsing "EDS" response: resource "endpoints-0": EDS response contains a locality without ID, locality: lb_endpoints:{endpoint:{address:{socket_address:{address:"0.0.0.0" port_value:123}}}}resource "endpoints-1": EDS response contains a locality without ID, locality: lb_endpoints:{endpoint:{address:{socket_address:{address:"1.1.1.1" port_value:456}}}}
```

Optional: this is a pure stylish discussion. From the first pass, I wasn't sure what does index mean, could it means the index number of the error or the index of the resource in the update list. I think the output from Golang is slightly more readable. I know their resource name could be "endpoints-0" and "endpoints-1". When listener name is not yet available, could we use something like `<resource-type> <index>:`?
</blockquote></details>

I think it's misleading to say something like "endpoints-0", since that implies that's the actual name string, not an index.  I've added the word "resource" before "index".  Hopefully that clarifies it.

In general, I don't want to hold up this PR too much for word-smithing.  I do see several places in the code where the details of the error message could be better, but for this PR, I think the important thing is to report the errors and associate them with resources as best we can.  We can improve the contents of the messages later.
___
*[src/core/ext/xds/xds_api.cc, line 1548 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_cXmH4zR9UL8Jtx7V:-MSckkNREqVDZoGWmXJ_:b7iipit) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.cc#L1548)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

It looks like we also added validation errors in this PR. Just a note, in case people reading this PR in future.
</blockquote></details>

I'm not sure what you mean by that.  This PR does not add any new error cases.  The code here is just wrapping the error returned from `LdsResponseParseClient()` or `LdsResponseParseServer()` with another error that indicates the resource name.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 3012 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_d03o0rH_5tJNBbBZ:-MSd-UDA7h80e7doTkPP:bxjszif) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/test/cpp/end2end/xds_end2end_test.cc#L3012)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Do we need to add one test case that ensures multiple error messages can be produced by `ParseAdsResponse` (or four each covers a type of xDS)? Also, a test to check if the `resource_names_failed` field is populated properly?
</blockquote></details>

I've added tests for multiple bad resources for LDS and CDS.  It's non-trivial to add this test for RDS and EDS, because the xDS server is not obligated to send both resources in the same response.

The presence of `resource_names_failed` isn't visible to the end2end test right now, so there's no way to test that.  I think you can add tests as part of the CSDS PR that cover this, though.

**Review by lidizheng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25329)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 1548 at r1](https://reviewable.io/reviews/grpc/grpc/25329#-MS_cXmH4zR9UL8Jtx7V:-MSdJt2QBnJFSP4Hs0V4:b-4d9jsq) ([raw file](https://github.com/grpc/grpc/blob/7a443a4e3f7d5e41b682c6a2df5ad7749eae5f56/src/core/ext/xds/xds_api.cc#L1548)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'm not sure what you mean by that.  This PR does not add any new error cases.  The code here is just wrapping the error returned from `LdsResponseParseClient()` or `LdsResponseParseServer()` with another error that indicates the resource name.
</blockquote></details>

My bad. I thought these lines added a new type of error, but it 's adding tracking info to the error.

**Comment by markdroth** [comment]
Known issues: #23822

The "Bazel C/C++ Dbg MacOS" failure is an infrastructure issue.

**Pull request merged**
