### PR TITLE
grpclb drop support

### PR DESCRIPTION
**Pull request by markdroth**
This is built on #10821, so it may be easier to review once that's been merged.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by markdroth** [comment]
As per internal discussions, closing this in favor of #11026.

**Pull request closed without merging**
