### PR TITLE
Update node protobuf dependency to 3.0.0 where applicable. Also update example dependency to grpc 1.0.0

### PR DESCRIPTION
**Pull request by murgatroid99**
This also makes the health-check package dependency match the version of gRPC that it's published along with.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Has the node protobuf package pushed yet ?

**Comment by murgatroid99** [comment]
Yes, it has.

**Comment by nicolasnoble** [comment]
Jenkins / node seems to disagree :-)

**Comment by murgatroid99** [comment]
npmjs.org definitely says version 3.0.0 is there. It's probably just a caching problem.

**Comment by murgatroid99** [comment]
test this please

**Comment by nicolasnoble** [comment]
That'd be a weird cache, given it's inside fresh docker containers that are getting purged after each run... :-)

**Comment by murgatroid99** [comment]
A while ago, I set up an NPM cache that mounts a directory from outside the docker file.

**Comment by nicolasnoble** [comment]
Ah, right.

**Comment by murgatroid99** [comment]
test this please

**Comment by nicolasnoble** [comment]
Sanity is sad.

**Comment by murgatroid99** [comment]
Should be fixed now

**Comment by nicolasnoble** [comment]
For Jenkins: test this please

**Comment by murgatroid99** [comment]
Node is all green

**Pull request merged**
