### PR TITLE
Backport PR #12721 to 1.6.x

### PR DESCRIPTION
**Pull request by apolcyn**

### CODE REVIEW

**Comment by apolcyn** [comment]
re-running tests after correcting the base to be 1.6.x instead of master.

jenkins: test this please

**Comment by apolcyn** [comment]
I signed it!

**Comment by kpayson64** [comment]
Looks like there is a Rubucop failure:
```
Running RuboCop...
Inspecting 52 files
............C.......................................

Offenses:

src/ruby/lib/grpc/google_rpc_status_utils.rb:32:81: C: Line is too long. [82/80]
      Google::Rpc::Status.decode(status.metadata[grpc_status_details_bin_trailer])
```
                                                                                ^^

**Comment by apolcyn** [comment]
good catch, thanks. looks like rubocop was upgraded on master and slightly differs from style requirements on this branch

**Comment by apolcyn** [comment]
test failures:
* ruby mac dbg/opt kokoro: https://github.com/grpc/grpc/issues/12538
* windows kokoro: https://github.com/grpc/grpc/issues/10643 (`h2_sockpair_nosec_test.exe max_concurrent_streams`)
* interop cloud to prod: https://github.com/grpc/grpc/issues/10763

kokoro portability tests failed with what looks like a kokoro ssh failure:
```
[ID: 9568121] Retrying SSH due to network disconnect:
python /tmpfs/kokoro_log_reader.py /tmpfs/kokoro_build.log /tmpfs/kokoro_build_exit_code /tmpfs/kokoro_build.pid /tmpfs/kokoro_log_reader.pid --start_byte 8583

E0929 15:03:15.026963  132223 transport.py:1575] Exception: Error reading SSH protocol banner
E0929 15:03:15.028149  132223 transport.py:1573] Traceback (most recent call last):
E0929 15:03:15.028200  132223 transport.py:1573]   File "/export/hda3/borglet/local_ram_fs_dirs/0.kokoro-slave-gcp_ubuntu-dynamic-grpc-prod-375715706.jenkins_slave.kokoro-dedicated.1055787751.c8564a224093156f/alloc/builder/kokoro_builder.par/google3/third_party/py/paramiko/transport.py", line 1740, in run
E0929 15:03:15.028233  132223 transport.py:1573]     self._check_banner()
E0929 15:03:15.028270  132223 transport.py:1573]   File "/export/hda3/borglet/local_ram_fs_dirs/0.kokoro-slave-gcp_ubuntu-dynamic-grpc-prod-375715706.jenkins_slave.kokoro-dedicated.1055787751.c8564a224093156f/alloc/builder/kokoro_builder.par/google3/third_party/py/paramiko/transport.py", line 1888, in _check_banner
E0929 15:03:15.028307  132223 transport.py:1573]     raise SSHException('Error reading SSH protocol banner' + str(e))
E0929 15:03:15.028344  132223 transport.py:1573] SSHException: Error reading SSH protocol banner
E0929 15:03:15.028378  132223 transport.py:1573] 
I0929 15:03:30.056122   56464 util.py:337] 

```

**Pull request merged**
