### PR TITLE
Revert "Add grpcio-status extension package"

### PR DESCRIPTION
**Pull request by AspirinSJL**
Reverts grpc/grpc#17490

Due to internal build failure.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,026,842      Total (=)      2,026,842

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,324,729      Total (<)     11,324,734

 No significant differences in binary sizes


```

**Comment by AspirinSJL** [comment]
@lidizheng Sure. Please stop me from reverting the PR whenever you think it can be fixed trivially.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
Fixing forward.

**Pull request closed without merging**
