### PR TITLE
[ObjC] remove grpc_bazel_cpp_ios_event_engine_experiment_tests

### PR DESCRIPTION
**Pull request by HannahShiSFB**
zero cases ran according to CI logs:
e.g.:
```
Executing tests from //test/core/event_engine/cf:cf_engine_test_on_ios
-----------------------------------------------------------------------------
2023-12-09 21:28:59,623 Creating a new simulator:
Name: New-iPhone X-16.1
OS: iOS 16.1
Type: iPhone X
2023-12-09 21:29:00,377 Created new simulator 9958E216-2526-4A95-A70F-8E006D6DB512.
2023-12-09 21:29:01,105 Will consider the test as test type logic_test to run.
Test Suite 'All tests' started at 2023-12-09 13:29:01.708
Test Suite 'All tests' passed at 2023-12-09 13:29:01.709.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
2023-12-09 21:29:01,715 Deleting simulator 9958E216-2526-4A95-A70F-8E006D6DB512 asynchronously.
2023-12-09 21:29:01,720 Done.
```

All logs in:
https://source.cloud.google.com/results/invocations/f77ffe5d-d5c8-4aea-a54d-80e02c7d54fd/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_bazel_cpp_ios_event_engine_experiment_tests/log
https://source.cloud.google.com/results/invocations/2a12c3be-1f7c-48af-8a2d-26982a72c04b/targets
https://source.cloud.google.com/results/invocations/2a12c3be-1f7c-48af-8a2d-26982a72c04b/targets/%2F%2Ftest%2Fcore%2Fevent_engine%2Fcf:cf_engine_test_on_ios/log

-----
PS: although no tests were executed, we are seeing random timeouts in the internal CI most likely due to the environment issue as tests are still being build and emulators are being lunched.

### CODE REVIEW

**Comment by drfloob** [comment]
@sampajano Do you need a separate set of CI tests for the EventEngine client on iOS? Whenever you make the switch, these will become irrelevant. Until then, it seems wrong that no tests are running.

**Comment by sampajano** [comment]
> @sampajano Do you need a separate set of CI tests for the EventEngine client on iOS? Whenever you make the switch, these will become irrelevant. Until then, it seems wrong that no tests are running.

Yeah i totally agree that it seems wrong that no tests are running. Or is there other test coverage that's outside of this flag?

@HannahShiSFB Do you know the reason why this flag isn't working as intended to provide test coverage? And whether there is other tests properly providing this coverage?

Thanks!!

**Comment by HannahShiSFB** [comment]
ios tests need a obj-c wrapper and use grpc_objc_ios_unit_test target, we already have them (https://github.com/grpc/grpc/blob/master/src/objective-c/tests/BUILD) run in a separate job (https://source.cloud.google.com/results/invocations/89f979bc-cffb-4e78-af5a-4a2a88ca9c3c/targets).


--
For the targets attempted to run in the job being removed in this PR:
https://source.cloud.google.com/results/invocations/2a12c3be-1f7c-48af-8a2d-26982a72c04b/targets
most of them are either not relevant (e.g. //test/core/event_engine/posix:event_poller_posix_test_on_ios) or platform agnostic (//test/cpp/util:byte_buffer_test_on_ios) or e2e tests which ios has its own. 

--
It looks like those jobs need to be removed from internal CI, not just by removing the config files.
The other one we want to remove is `tools/internal_ci/macos/grpc_bazel_cpp_ios_tests.cfg` which is in the same state that runs 0 cases.

**Comment by sampajano** [comment]
Ok that sounds good to me!

@drfloob Do you think that's fair?

**Review by sampajano — APPROVED** [review]
Could you also mention this is an attempt to address the timeout issue? Thanks!

**Pull request closed without merging**
