### PR TITLE
Proposing several upcoming 'g's

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by murgatroid99** [comment]
I think the "greight" pun is a little too subtle. At first look, it's hard to tell whether it should be pronounced like "eight" or like "height" or even "freight".

**Comment by dgquintas** [comment]
Yeah, I don't get it... <spoiler>Is it because it's the eighth and it's great?</spoiler>

**Comment by vjpai** [comment]
Don't blame me, that one comes from @ejona86

**Comment by ctiller** [comment]
In the future I'd suggest making people send their suggestions as their own
PR's for proper attribution of such... ideas.

**Comment by vjpai** [comment]
Good idea, I'm removing 1.8

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by nathanielmanistaatgoogle** [comment]
Please squash commits.

**Comment by vjpai** [comment]
Closing a troll PR since it's been superceded

**Pull request closed without merging**
