### PR TITLE
Remove Python background poller thread

### PR DESCRIPTION
**Pull request by kpayson64**
This thread is apparently no longer required because a background polling thread gets created in c-core.

_reconnect_test.py still passes with its removal.

### CODE REVIEW

**Comment by mehrdada** [comment]
Can you please remove the additional sleep inbetween requests in `_reconnect_test` in this PR and see if it passes over say 10000 iterations?

**Comment by kpayson64** [comment]
Hmm, this test fails deterministically internally and on mac after this change... Need to investigate further.

**Comment by srini100** [comment]
[This PR](https://github.com/grpc/grpc/pull/12732) makes the python poller thread obsolete. If this goes well, other wrapped languages need to do the same.

**Comment by kpayson64** [comment]
It appears the background poller only solves this issue for ```epoll1```.
```
(py27)kpayson@kpayson0:~/grpc$ GRPC_POLL_STRATEGY=epoll1 python src/python/grpcio_tests/tests/unit/_reconnect_test.py
test_reconnect (__main__.ReconnectTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
(py27)kpayson@kpayson0:~/grpc$ GRPC_POLL_STRATEGY=epollsig python src/python/grpcio_tests/tests/unit/_reconnect_test.py
test_reconnect (__main__.ReconnectTest) ... ERROR

======================================================================
ERROR: test_reconnect (__main__.ReconnectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/python/grpcio_tests/tests/unit/_reconnect_test.py", line 94, in test_reconnect
    self.assertEqual(_RESPONSE, multi_callable(_REQUEST))
  File "/usr/local/google/home/kpayson/grpc2/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 487, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/google/home/kpayson/grpc2/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 437, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Socket closed)>

----------------------------------------------------------------------
Ran 1 test in 0.011s

FAILED (errors=1)
(py27)kpayson@kpayson0:~/grpc$ GRPC_POLL_STRATEGY=poll python src/python/grpcio_tests/tests/unit/_reconnect_test.py
test_reconnect (__main__.ReconnectTest) ... ERROR

======================================================================
ERROR: test_reconnect (__main__.ReconnectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/python/grpcio_tests/tests/unit/_reconnect_test.py", line 94, in test_reconnect
    self.assertEqual(_RESPONSE, multi_callable(_REQUEST))
  File "/usr/local/google/home/kpayson/grpc2/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 487, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/google/home/kpayson/grpc2/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 437, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Socket closed)>

----------------------------------------------------------------------
Ran 1 test in 0.009s

FAILED (errors=1)
```
(I also tried epollex internally and it failed)

@sreecha Do you have any ideas why this might be?

**Comment by sreecha** [comment]
Can you try setting `GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS` env variable to something smaller like '100'   (or smaller if your test expects it sooner)

**Comment by kpayson64** [comment]
```GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS``` worked perfectly!  We will just need to add to the release notes for Python something about this change because it will be a slight behavior change.

**Comment by mehrdada** [comment]
So there will still be a potential race condition in the timeframe specified by `GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS`?

**Comment by kpayson64** [comment]
@mehrdada That's right.

Also, it looks like there is still an issue with the ```poll``` engine.  I'll investigate.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                           FILE SIZE
 ++++++++++++++ GROWING                             ++++++++++++++
  +0.0%     +16 [None]                                  +80  +0.0%
  +0.1%     +16 src/core/lib/iomgr/ev_poll_posix.cc     +16  +0.1%
      +0.3%      +9 pollset_work                             +9  +0.3%
      +2.1%      +7 [Unmapped]                               +7  +2.1%

  +0.0%     +32 TOTAL                                   +96  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                              cpu_time    real_time
-------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcessCHTTP2>/262144                                    -4%         -4%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/1  +4%         +4%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/262144                      -9%         -9%
```

**Comment by kpayson64** [comment]
#13727
#14631
#14445

+ A whole bunch of bazel test failures, but I'm assuming those are still a WIP.

**Pull request merged**
