### PR TITLE
Change pick_first to not unref unselected subchannels.

### PR DESCRIPTION
**Pull request by markdroth**
Based on #16306.

This eliminates the requirement for resolvers to immediately return a result when `RequestReresolutionLocked()` is called.

@AspirinSJL and @dgquintas, please scrutinize this carefully.  All the tests pass, but I'd like to get both of your pairs of knowledgable eyes on this to make sure I haven't missed anything.  Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/16342)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%     +28 [None]                                                                                  +732  +0.0%
  +2.0%    +256 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +256  +2.0%
      [NEW]    +713 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +713  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::CheckConnectiv    +200  [NEW]
       +10%     +29 [Unmapped]                                                                               +29   +10%
  +0.2%     +66 src/core/ext/filters/client_channel/client_channel.cc                                    +66  +0.2%
      +2.2%     +32 start_transport_op_locked                                                                +32  +2.2%
       +16%     +32 request_reresolution_locked                                                              +32   +16%
      [NEW]      +2 grpc_core::Resolver::RequestReresolutionLocked                                            +2  [NEW]
  +0.1%     +16 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +16  +0.1%
      +2.6%     +16 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +16  +2.6%

 -------------- SHRINKING                                                                            --------------
 -20.8%     -78 src/core/ext/filters/client_channel/resolver.cc                                          -78 -20.8%
      [DEL]     -78 grpc_core::Resolver::RequestReresolutionLocked                                           -78  [DEL]
  -3.3%     -64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       -64  -3.3%
     -53.3%     -57 grpc_core::FakeResolver::RequestReresolutionLocked                                       -57 -53.3%
     -28.2%     -22 grpc_core::FakeResolverResponseGenerator::SetResponseLocked                              -22 -28.2%
     -14.3%      -9 grpc_core::FakeResolver::~FakeResolver                                                    -9 -14.3%
      -6.4%      -8 grpc_core::FakeResolver::FakeResolver                                                     -8  -6.4%
  -1.7%     -32 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc               -32  -1.7%
      [DEL]    -142 grpc_core::(anonymous namespace)::SockaddrResolver::MaybeFinishNextLocked() [clone .    -142  [DEL]
     -11.9%     -23 [Unmapped]                                                                               -23 -11.9%
      [DEL]     -18 grpc_core::(anonymous namespace)::SockaddrResolver::RequestReresolutionLocked            -18  [DEL]
  -0.4%     -16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -16  -0.4%
      [DEL]    -220 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked            -220  [DEL]
  -0.6%     -16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  -16  -0.6%
      [DEL]    -217 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked          -217  [DEL]
      -0.7%      -1 [Unmapped]                                                                                -1  -0.7%

  +0.0%    +160 TOTAL                                                                                   +864  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,950,963      Total (<)      1,951,081

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,661,771      Total (>)     10,661,413

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,950,979      Total (<)      1,951,097

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,661,766      Total (>)     10,661,409

 No significant differences in binary sizes


```

**Comment by dgquintas** [comment]
Tests don't look happy.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%     +28 [None]                                                                                  +684  +0.0%
  +2.0%    +256 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +256  +2.0%
      [NEW]    +713 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +713  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::CheckConnectiv    +200  [NEW]
       +10%     +29 [Unmapped]                                                                               +29   +10%
  +0.2%     +66 src/core/ext/filters/client_channel/client_channel.cc                                    +66  +0.2%
      +2.2%     +32 start_transport_op_locked                                                                +32  +2.2%
       +16%     +32 request_reresolution_locked                                                              +32   +16%
      [NEW]      +2 grpc_core::Resolver::RequestReresolutionLocked                                            +2  [NEW]
  +0.1%     +16 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +16  +0.1%
      +2.6%     +16 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +16  +2.6%

 -------------- SHRINKING                                                                            --------------
 -20.8%     -78 src/core/ext/filters/client_channel/resolver.cc                                          -78 -20.8%
      [DEL]     -78 grpc_core::Resolver::RequestReresolutionLocked                                           -78  [DEL]
  -3.3%     -64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       -64  -3.3%
     -53.3%     -57 grpc_core::FakeResolver::RequestReresolutionLocked                                       -57 -53.3%
     -28.2%     -22 grpc_core::FakeResolverResponseGenerator::SetResponseLocked                              -22 -28.2%
     -14.3%      -9 grpc_core::FakeResolver::~FakeResolver                                                    -9 -14.3%
      -6.4%      -8 grpc_core::FakeResolver::FakeResolver                                                     -8  -6.4%
  -1.7%     -32 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc               -32  -1.7%
      [DEL]    -142 grpc_core::(anonymous namespace)::SockaddrResolver::MaybeFinishNextLocked() [clone .    -142  [DEL]
     -11.9%     -23 [Unmapped]                                                                               -23 -11.9%
      [DEL]     -18 grpc_core::(anonymous namespace)::SockaddrResolver::RequestReresolutionLocked            -18  [DEL]
  -0.4%     -16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -16  -0.4%
      [DEL]    -220 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked            -220  [DEL]
  -0.6%     -16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  -16  -0.6%
      [DEL]    -217 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked          -217  [DEL]
      -0.7%      -1 [Unmapped]                                                                                -1  -0.7%

  +0.0%    +160 TOTAL                                                                                   +816  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,616      Total (<)      1,952,734

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,663,941      Total (>)     10,663,578

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
Just pushed a new commit to fix a test failure in #16306.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +1.1%    +144 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +144  +1.1%
      [NEW]    +628 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +628  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::CheckConnectiv    +200  [NEW]
       +12%     +34 [Unmapped]                                                                               +34   +12%
  +0.2%     +66 src/core/ext/filters/client_channel/client_channel.cc                                    +66  +0.2%
      +2.2%     +32 start_transport_op_locked                                                                +32  +2.2%
       +16%     +32 request_reresolution_locked                                                              +32   +16%
      [NEW]      +2 grpc_core::Resolver::RequestReresolutionLocked                                            +2  [NEW]
  +0.1%     +16 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +16  +0.1%
      +2.6%     +16 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +16  +2.6%

 -------------- SHRINKING                                                                            --------------
 -20.8%     -78 src/core/ext/filters/client_channel/resolver.cc                                          -78 -20.8%
      [DEL]     -78 grpc_core::Resolver::RequestReresolutionLocked                                           -78  [DEL]
  -3.3%     -64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       -64  -3.3%
     -53.3%     -57 grpc_core::FakeResolver::RequestReresolutionLocked                                       -57 -53.3%
     -28.2%     -22 grpc_core::FakeResolverResponseGenerator::SetResponseLocked                              -22 -28.2%
     -14.3%      -9 grpc_core::FakeResolver::~FakeResolver                                                    -9 -14.3%
      -6.4%      -8 grpc_core::FakeResolver::FakeResolver                                                     -8  -6.4%
  -1.7%     -32 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc               -32  -1.7%
      [DEL]    -142 grpc_core::(anonymous namespace)::SockaddrResolver::MaybeFinishNextLocked() [clone .    -142  [DEL]
     -11.9%     -23 [Unmapped]                                                                               -23 -11.9%
      [DEL]     -18 grpc_core::(anonymous namespace)::SockaddrResolver::RequestReresolutionLocked            -18  [DEL]
  -0.4%     -16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -16  -0.4%
      [DEL]    -220 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked            -220  [DEL]
  -0.6%     -16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  -16  -0.6%
      [DEL]    -217 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked          -217  [DEL]
      -0.7%      -1 [Unmapped]                                                                                -1  -0.7%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -60 [None]                                                                                  +868  +0.0%

  -0.0%     -40 TOTAL                                                                                   +888  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,393      Total (<)      1,952,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,664,102      Total (>)     10,663,749

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.2%     +66 src/core/ext/filters/client_channel/client_channel.cc                                    +66  +0.2%
      +2.2%     +32 start_transport_op_locked                                                                +32  +2.2%
       +16%     +32 request_reresolution_locked                                                              +32   +16%
      [NEW]      +2 grpc_core::Resolver::RequestReresolutionLocked                                            +2  [NEW]
  +0.1%     +16 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +16  +0.1%
      +2.6%     +16 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +16  +2.6%

 -------------- SHRINKING                                                                            --------------
  -0.0%    -180 [None]                                                                               -4.04Ki  -0.0%
  -1.6%    -208 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  -208  -1.6%
      [DEL]    -122 grpc_core::(anonymous namespace)::PickFirst::DestroyUnselectedSubchannelsLocked         -122  [DEL]
      -4.6%     -54 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnect     -54  -4.6%
     -35.6%     -32 grpc_core::(anonymous namespace)::PickFirst::StartPickingLocked                          -32 -35.6%
      -0.2%      -8 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                                 -8  -0.2%
      -1.3%      -8 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec      -8  -1.3%
 -20.8%     -78 src/core/ext/filters/client_channel/resolver.cc                                          -78 -20.8%
      [DEL]     -78 grpc_core::Resolver::RequestReresolutionLocked                                           -78  [DEL]
  -3.3%     -64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       -64  -3.3%
     -53.3%     -57 grpc_core::FakeResolver::RequestReresolutionLocked                                       -57 -53.3%
     -28.2%     -22 grpc_core::FakeResolverResponseGenerator::SetResponseLocked                              -22 -28.2%
     -14.3%      -9 grpc_core::FakeResolver::~FakeResolver                                                    -9 -14.3%
      -6.4%      -8 grpc_core::FakeResolver::FakeResolver                                                     -8  -6.4%
  -1.7%     -32 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc               -32  -1.7%
      [DEL]    -142 grpc_core::(anonymous namespace)::SockaddrResolver::MaybeFinishNextLocked() [clone .    -142  [DEL]
     -11.9%     -23 [Unmapped]                                                                               -23 -11.9%
      [DEL]     -18 grpc_core::(anonymous namespace)::SockaddrResolver::RequestReresolutionLocked            -18  [DEL]
  -0.4%     -16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -16  -0.4%
      [DEL]    -220 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked            -220  [DEL]
  -0.6%     -16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  -16  -0.6%
      [DEL]    -217 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked          -217  [DEL]
      -0.7%      -1 [Unmapped]                                                                                -1  -0.7%

  -0.0%    -512 TOTAL                                                                                -4.36Ki  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,393      Total (<)      1,952,998

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,664,106      Total (<)     10,664,798

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,393      Total (<)      1,952,998

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,664,110      Total (<)     10,664,800

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.2%     +66 src/core/ext/filters/client_channel/client_channel.cc                                    +66  +0.2%
      +2.2%     +32 start_transport_op_locked                                                                +32  +2.2%
       +16%     +32 request_reresolution_locked                                                              +32   +16%
      [NEW]      +2 grpc_core::Resolver::RequestReresolutionLocked                                            +2  [NEW]
  +0.1%     +16 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +16  +0.1%
      +2.6%     +16 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +16  +2.6%

 -------------- SHRINKING                                                                            --------------
  -0.0%    -180 [None]                                                                               -4.02Ki  -0.0%
  -1.6%    -208 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  -208  -1.6%
      [DEL]    -122 grpc_core::(anonymous namespace)::PickFirst::DestroyUnselectedSubchannelsLocked         -122  [DEL]
      -4.6%     -54 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnect     -54  -4.6%
     -35.6%     -32 grpc_core::(anonymous namespace)::PickFirst::StartPickingLocked                          -32 -35.6%
      -0.2%      -8 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                                 -8  -0.2%
      -1.3%      -8 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec      -8  -1.3%
 -20.8%     -78 src/core/ext/filters/client_channel/resolver.cc                                          -78 -20.8%
      [DEL]     -78 grpc_core::Resolver::RequestReresolutionLocked                                           -78  [DEL]
  -3.3%     -64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       -64  -3.3%
     -53.3%     -57 grpc_core::FakeResolver::RequestReresolutionLocked                                       -57 -53.3%
     -28.2%     -22 grpc_core::FakeResolverResponseGenerator::SetResponseLocked                              -22 -28.2%
     -14.3%      -9 grpc_core::FakeResolver::~FakeResolver                                                    -9 -14.3%
      -6.4%      -8 grpc_core::FakeResolver::FakeResolver                                                     -8  -6.4%
  -1.7%     -32 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc               -32  -1.7%
      [DEL]    -142 grpc_core::(anonymous namespace)::SockaddrResolver::MaybeFinishNextLocked() [clone .    -142  [DEL]
     -11.9%     -23 [Unmapped]                                                                               -23 -11.9%
      [DEL]     -18 grpc_core::(anonymous namespace)::SockaddrResolver::RequestReresolutionLocked            -18  [DEL]
  -0.4%     -16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -16  -0.4%
      [DEL]    -220 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked            -220  [DEL]
  -0.6%     -16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  -16  -0.6%
      [DEL]    -217 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked          -217  [DEL]
      -0.7%      -1 [Unmapped]                                                                                -1  -0.7%

  -0.0%    -512 TOTAL                                                                                -4.34Ki  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,357      Total (<)      1,952,962

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,664,113      Total (<)     10,664,801

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark              cpu_time    real_time
---------------------  ----------  -----------
BM_ErrorGetMissingInt  +9%         +9%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.2%     +66 src/core/ext/filters/client_channel/client_channel.cc                                    +66  +0.2%
      +2.2%     +32 start_transport_op_locked                                                                +32  +2.2%
       +16%     +32 request_reresolution_locked                                                              +32   +16%
      [NEW]      +2 grpc_core::Resolver::RequestReresolutionLocked                                            +2  [NEW]
  +0.1%     +16 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +16  +0.1%
      +2.6%     +16 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +16  +2.6%

 -------------- SHRINKING                                                                            --------------
  -0.0%    -180 [None]                                                                               -4.05Ki  -0.0%
  -1.6%    -208 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  -208  -1.6%
      [DEL]    -122 grpc_core::(anonymous namespace)::PickFirst::DestroyUnselectedSubchannelsLocked         -122  [DEL]
      -4.6%     -54 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnect     -54  -4.6%
     -35.6%     -32 grpc_core::(anonymous namespace)::PickFirst::StartPickingLocked                          -32 -35.6%
      -0.2%      -8 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                                 -8  -0.2%
      -1.3%      -8 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec      -8  -1.3%
 -20.8%     -78 src/core/ext/filters/client_channel/resolver.cc                                          -78 -20.8%
      [DEL]     -78 grpc_core::Resolver::RequestReresolutionLocked                                           -78  [DEL]
  -3.3%     -64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       -64  -3.3%
     -53.3%     -57 grpc_core::FakeResolver::RequestReresolutionLocked                                       -57 -53.3%
     -28.2%     -22 grpc_core::FakeResolverResponseGenerator::SetResponseLocked                              -22 -28.2%
     -14.3%      -9 grpc_core::FakeResolver::~FakeResolver                                                    -9 -14.3%
      -6.4%      -8 grpc_core::FakeResolver::FakeResolver                                                     -8  -6.4%
  -1.7%     -32 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc               -32  -1.7%
      [DEL]    -142 grpc_core::(anonymous namespace)::SockaddrResolver::MaybeFinishNextLocked() [clone .    -142  [DEL]
     -11.9%     -23 [Unmapped]                                                                               -23 -11.9%
      [DEL]     -18 grpc_core::(anonymous namespace)::SockaddrResolver::RequestReresolutionLocked            -18  [DEL]
  -0.4%     -16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -16  -0.4%
      [DEL]    -220 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked            -220  [DEL]
  -0.6%     -16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  -16  -0.6%
      [DEL]    -217 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked          -217  [DEL]
      -0.7%      -1 [Unmapped]                                                                                -1  -0.7%

  -0.0%    -512 TOTAL                                                                                -4.38Ki  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by markdroth** [comment]
@AspirinSJL, did you want to look at this again?  You marked it as "changes requested".

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,365      Total (<)      1,952,970

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,664,363      Total (<)     10,665,042

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                         cpu_time    real_time
--------------------------------  ----------  -----------
BM_HasClearGrpcStatus<ErrorNone>  +8%         +8%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.2%     +66 src/core/ext/filters/client_channel/client_channel.cc                                    +66  +0.2%
      +2.2%     +32 start_transport_op_locked                                                                +32  +2.2%
       +16%     +32 request_reresolution_locked                                                              +32   +16%
      [NEW]      +2 grpc_core::Resolver::RequestReresolutionLocked                                            +2  [NEW]
  +0.1%     +16 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +16  +0.1%
      +2.6%     +16 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +16  +2.6%

 -------------- SHRINKING                                                                            --------------
  -1.6%    -208 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  -208  -1.6%
      [DEL]    -122 grpc_core::(anonymous namespace)::PickFirst::DestroyUnselectedSubchannelsLocked         -122  [DEL]
      -4.6%     -54 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnect     -54  -4.6%
     -35.6%     -32 grpc_core::(anonymous namespace)::PickFirst::StartPickingLocked                          -32 -35.6%
      -0.2%      -8 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                                 -8  -0.2%
      -1.3%      -8 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec      -8  -1.3%
  -0.0%    -180 [None]                                                                                   -44  -0.0%
 -20.8%     -78 src/core/ext/filters/client_channel/resolver.cc                                          -78 -20.8%
      [DEL]     -78 grpc_core::Resolver::RequestReresolutionLocked                                           -78  [DEL]
  -3.3%     -64 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc                       -64  -3.3%
     -53.3%     -57 grpc_core::FakeResolver::RequestReresolutionLocked                                       -57 -53.3%
     -28.2%     -22 grpc_core::FakeResolverResponseGenerator::SetResponseLocked                              -22 -28.2%
     -14.3%      -9 grpc_core::FakeResolver::~FakeResolver                                                    -9 -14.3%
      -6.4%      -8 grpc_core::FakeResolver::FakeResolver                                                     -8  -6.4%
  -1.7%     -32 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc               -32  -1.7%
      [DEL]    -142 grpc_core::(anonymous namespace)::SockaddrResolver::MaybeFinishNextLocked() [clone .    -142  [DEL]
     -11.9%     -23 [Unmapped]                                                                               -23 -11.9%
      [DEL]     -18 grpc_core::(anonymous namespace)::SockaddrResolver::RequestReresolutionLocked            -18  [DEL]
  -0.4%     -16 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -16  -0.4%
      [DEL]    -220 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeStartResolvingLocked            -220  [DEL]
  -0.6%     -16 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  -16  -0.6%
      [DEL]    -217 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeStartResolvingLocked          -217  [DEL]
      -0.7%      -1 [Unmapped]                                                                                -1  -0.7%

  -0.0%    -512 TOTAL                                                                                   -376  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,951,979      Total (<)      1,952,584

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,665,015      Total (<)     10,665,706

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                              cpu_time    real_time
-------------------------------------  ----------  -----------
BM_ErrorGetMissingInt                  +20%        +20%
BM_HasClearGrpcStatus<ErrorCancelled>  +11%        +11%
BM_HasClearGrpcStatus<ErrorNone>       +16%        +16%
```

**Comment by markdroth** [comment]
Known failures: #16042 #16465 #15410

**Pull request merged**
