### PR TITLE
Use '//' for JSON comments.

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by vjpai** [comment]
Comments in any form aren't technically real JSON, so does it really matter? JSON only semantically accepts key-value pairs.

**Comment by markdroth** [comment]
@ejona86 tells me that it's a common extension to support comments in JSON using `//`.

**Comment by vjpai** [comment]
[Google JSON style guide](https://google.github.io/styleguide/jsoncstyleguide.xml#Comments) doesn't accept comments in real JSON in any form, though it does use comments in the document to explain things, which was, I think the purpose here as well, correct?

**Comment by markdroth** [comment]
Yes, the purpose of these comments is to explain things.

**Comment by vjpai** [comment]
Right, which was already achieved. Switching from `#` to `//` seems to be like using Vulcan rather than Klingon - neither is really appropriate anyway, so why the need?

**Comment by markdroth** [comment]
The common convention for comments in JSON is to use `//`.  That's what we use in our other docs, and we should do the same here for consistency.

**Comment by vjpai** [comment]
Alright, consistency justifies Vulcan over Klingon. LGTM.

**Comment by markdroth** [comment]
Since this is a doc-only change, I'm not going to bother noting the test failures, since they're clearly unrelated.

**Pull request merged**
