### PR TITLE
1.4.0 to master upmerge

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by murgatroid99** [comment]
Did you have to fix any merge conflicts other than version numbers?

**Comment by dgquintas** [comment]
No. Still, it seems there are differences in the generated projects output.
eg
https://github.com/grpc/grpc/pull/11455/files#diff-38ce68e55e10fc655a0123717db8498d

**Comment by jtattermusch** [comment]
This will need a fresh tests run after rebasing. There's too much noise in the test results because recent breakages in upstream/master (some of them are not fixed).

**Comment by murgatroid99** [comment]
With this many test failures, including sanity failures, I'm not comfortable with merging this.

**Comment by murgatroid99** [comment]
Closing: superseded by #11516.

**Pull request closed without merging**
