### PR TITLE
Make grpc_tcp_listener private.

### PR DESCRIPTION
**Pull request by daniel-j-born**
grpc_tcp_listener is now completely private to the implementation. It seems its
only use was to return the port, so add_port() now returns this instead.

Made the port_index stable: adding more ports doesn't affect the indices of
existing ports. (Previously, every add_port() would should shift them all by
one.)

grpc_tcp_server is now refcounted.

grpc_tcp_server_cb passes a pointer to the server and gives the callee a ref. It
also gives the indices of the accepting server fd.

I wasn't able to test (or even compile) any of the windows code. It looks like
some combination of docker, run_tests.py, and Jenkins would do this, but I was
wondering if there is a recommended way for a Linux user.

Based on discussion in #4555

### CODE REVIEW

**Comment by ctiller** [comment]
The Windows code needs a Windows machine, unfortunately (as does some of the Mac code).

Build results are here:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/5080/config=dbg,language=c,platform=windows/console

---

Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/core/iomgr/tcp_server.h, line 44 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qKr7_zDsmugydyyKv:-K7qKr7aqTE9uRPpm2zf:-2032470272) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server.h#L44)):*
If you have six arguments you probably missed one.

Let's bundle from_server, port_index, fd_index into a struct perhaps?

---

*[src/core/iomgr/tcp_server.h, line 73 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qMGM0Uod1ScK1g4Ml:-K7qMGM1u0ZenOUvxXMq:1900761098) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server.h#L73)):*
grpc_tcp_server_port_fd_count

---

*[src/core/iomgr/tcp_server.h, line 79 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qMKVISMUr3HEZ8qUi:-K7qMKVISMUr3HEZ8qUj:-24993926) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server.h#L79)):*
grpc_tcp_server_port_fd

---

*[src/core/iomgr/tcp_server.h, line 86 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qMdrlf6doylSrIDvL:-K7qMdrlf6doylSrIDvM:-1390322947) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server.h#L86)):*
I'd prefer to see the shutdown complete closure be a set-once thing.

Either it's always passed into the construction function, or it's always passed into the shutdown function.

The previous API would work if grpc_tcp_server_destroy were renamed grpc_tcp_server_shutdown and released an implicit ref to the server.

---

*[src/core/iomgr/tcp_server_posix.c, line 215 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qLVPHRjlFGZM0P_zb:-K7qLVPHRjlFGZM0P_zc:1482722423) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server_posix.c#L215)):*
Style guide: static functions are not prefixed with grpc_

https://github.com/grpc/grpc/blob/master/doc/c-style-guide.md

---

*[src/core/iomgr/tcp_server_posix.c, line 366 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qLpZV2DmfCX8Tt7Yd:-K7qLpZV2DmfCX8Tt7Ye:-149149574) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server_posix.c#L366)):*
Prefer passing a borrowed reference here and letting receivers ref if they need to keep the pointer.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grpc/grpc/4680#-:-K7qNTOodIOiEBVhwsHX:-1995114300)*

**Comment by daniel-j-born** [comment]
It looks like my best option to is check those Jenkins logs after I push.

---

Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/core/iomgr/tcp_server.h, line 44 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qKr7_zDsmugydyyKv:-K7szSE1q-8ljyoNZNHQ:-499146009) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server.h#L44)):*
Done.

---

*[src/core/iomgr/tcp_server.h, line 73 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qMGM0Uod1ScK1g4Ml:-K7sv88g_8Kfyxm3ThGs:-499146009) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server.h#L73)):*
Done.

---

*[src/core/iomgr/tcp_server.h, line 79 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qMKVISMUr3HEZ8qUi:-K7sv7t1EvLOsMkSHvn4:-499146009) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server.h#L79)):*
Done.

---

*[src/core/iomgr/tcp_server.h, line 86 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qMdrlf6doylSrIDvL:-K7riqlzKGG1T4t8W1D4:-186908470) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server.h#L86)):*
The problem with a grpc_tcp_server_shutdown(shutdown_cb) is that the caller never knows which shutdown call drops the refcount to zero, so every call must pass the shutdown_cb. Basically, every call to unref (or anything that effectively unrefs) would have to pass the shutdown_cb. I want to avoid this.

I made it so it can only be passed to create().

---

*[src/core/iomgr/tcp_server_posix.c, line 215 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qLVPHRjlFGZM0P_zb:-K7szugD1Crp0_wSJJ8v:-499146009) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server_posix.c#L215)):*
Done.

---

*[src/core/iomgr/tcp_server_posix.c, line 366 \[r1\]](https://reviewable.io:443/reviews/grpc/grpc/4680#-K7qLpZV2DmfCX8Tt7Yd:-K7szl7PEwEpUeFL9P3B:-739405827) ([raw file](https://github.com/grpc/grpc/blob/fa6b606898b18c22cdcbaa006338fe1d57d8f93f/src/core/iomgr/tcp_server_posix.c#L366)):*
This is fine as long as on_accept_cb is called synchronously. It currently is, so I made this change.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grpc/grpc/4680#-:-K7szW_P-DRC9wDx54Ok:-551403164)*

**Comment by daniel-j-born** [comment]
The only thing left that might be a test failure is tests.bins/asan/generic_async_streaming_ping_pong_test, but this is unlikely to be related to my code. It looks like a pre-existing test failure.

**Comment by daniel-j-born** [comment]
There were some conflicts with master, so I did the merge. Craig, want to take a look at this and #4745 ?

**Comment by daniel-j-born** [comment]
I merged #4745 into this. It was just one extra commit (9c12bc2) to add the shutdown_starting callbacks.

**Comment by jboeuf** [comment]
@ctiller, is there something this PR or should we merge it? Thanks!

**Comment by ctiller** [comment]
Hey - we've had some testing infrastructure madness the past week. Let me
take a peek this morning.

**Comment by jboeuf** [comment]
Awesome. thanks!

**Pull request merged**
