### PR TITLE
 Bump v1.10.x to 1.10.1-pre1

### PR DESCRIPTION
**Pull request by mehrdada**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++
  +0.0%     +21 [None]                          +109  +0.0%
   +13%     +11 src/cpp/common/version_cc.cc     +11   +13%
       +28%     +11 grpc::Version[abi:cxx11]         +11   +28%

  +0.0%     +32 TOTAL                           +120  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                               cpu_time    real_time
----------------------------------------------------------------------  ----------  -----------
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/262144  -6%         -6%
```

**Comment by mehrdada** [comment]
Failures: bazel infra, removed beta_interface tests for Python, TLS error on Python, Java docker image download infra failure

**Pull request merged**
