### PR TITLE
Add UDP server to gRPC.

### PR DESCRIPTION
**Pull request by rjshade**
(Trying this again, with correct email associated with commits.)

Preparation for experimentation with QUIC as a transport.

ctiller: This is the result of our discussion over email. Structure is very similar to the existing tcp_server code.

This pull request isn't quite ready for review: the test_receive test hangs at the destroy_pollset call. I'd appreciate it if you could take a look at how I've wired things up, and see if you can spot what's going on.

I'm also unclear if the read callback/write methods in udp_server.h look sensible, PTAL.

Thanks!

### CODE REVIEW

**Comment by rjshade** [comment]
Before this goes any further: is it required that this pull request be coming from my @google.com account, rather than personal address? The googlebot's comment suggests it might not be complaining if this was the case. Let me know, and I can create a new pull request with the right address (I don't think I can modify this one).

**Comment by ctiller** [comment]
You can send from your personal request... but you'll need to sign the CLA
(which should mostly be a click through)

**Comment by rjshade** [comment]
ctiller: Can you take a look, and advise on how I should be triggering reads from the UDP socket? The udp_server_test goes into an infinite loop calling grpc_pollset_work, as I believe this never triggers a read. It's not clear to me how the new UDP server code should interact with pollsets.

$ make udp_server_test && ./bins/opt/udp_server_test

**Comment by yang-g** [comment]
I just started to look at this today. It seems in the test your client socket is connecting to an empty addr. You may want to expose get_fd from udp_server.h and copy the part about svrfd from tcp_server_posix_test to make the connect() work.

With that change a test_receive(10) can pass but there are future events polluting the later test cases. I am still looking to understand why.

**Comment by yang-g** [comment]
Another problem is in on_read, the case where success == 0 is not handled. With that fixed, all test cases pass. You can take a look at commit https://github.com/grpc/grpc/commit/fabefe10e31a635430365e703d6aa2eb14b91721 for a minimal fix.

What is still lacking is the actual reading part in udp_server.c on_read.

**Comment by rjshade** [comment]
Thanks for the comments, tests now passing, branch is now up to date.

Your comment about implementing reading in udp_server.c on_read: this calls the server port's read_cb which is where I intended to actually do the reads. See the example in udp_server_test.c. Does that seem sensible?

**Comment by nicolasnoble** [comment]
This is ok to test.

**Comment by yang-g** [comment]
It seems it has not picked up some recent api change and is not building.

**Pull request merged**
