### PR TITLE
Backport: fix resolver crash when DNS server unreachable to v1.11.x

### PR DESCRIPTION
**Pull request by jtattermusch**
Backports https://github.com/grpc/grpc/pull/15134.

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @mehrdada

**Comment by jtattermusch** [comment]
Wrong target branch, please ignore this PR.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                    FILE SIZE
 ++++++++++++++ GROWING                                                                      ++++++++++++++
  +0.0%     +16 [None]                                                                           +72  +0.0%
  +0.3%     +16 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc     +16  +0.3%
      +8.2%      +8 [Unmapped]                                                                        +8  +8.2%
      +7.5%      +8 grpc_ares_request_unref                                                           +8  +7.5%

  +0.0%     +32 TOTAL                                                                            +88  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
