### PR TITLE
Connection backoff interop test client and server

### PR DESCRIPTION
**Pull request by yang-g**
This is based on #2590 which is based on #2477. They need to be merged first.

### CODE REVIEW

**Comment by vjpai** [comment]
Yang, can you tell me which commits are unique? Then I can just review those before the others get reviewed...

**Comment by vjpai** [comment]
Never mind; I'll just figure it out by authorship..

**Comment by yang-g** [comment]
Sorry I did not make it clear, just the last commit for this PR. I squashed all commits into one. The other two are from #2590

**Comment by yang-g** [comment]
The parameters are from https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md except kTransmissionDelay which is chosen to cover network delay between the test client and server. It was chosen generously and might be too large.

**Comment by vjpai** [comment]
Ok, I understand. In an ideal world, that 100 ms would be too large for sure on localhost, but in the real world where we might encounter the occasional context switch, I'm afraid that we're stuck with it. So, LGTM on this commit. Let me know when the other PRs get merged.

**Comment by vjpai** [comment]
Status update: I'll wait for a minor code change on CV usage and then can merge if you're ready. The CV usage issue will be explored at a later date under issue #2714 .

**Comment by yang-g** [comment]
Fixed, thanks for the discussion. Would you like to take the parent PR as well? #2590

**Comment by vjpai** [comment]
Conflicts!

**Comment by yang-g** [comment]
Gone!

**Comment by yang-g** [comment]
Green enough?

**Pull request merged**
