### PR TITLE
Add cc-specific args to cc_grpc_library rule

### PR DESCRIPTION
**Pull request by kgreenek**
In the cc_grpc_library macro, **kwargs is forwarded to both the protobuf
genrule target, as well as the native cc_library that is created. As a
result, it was not possible to pass some args to the underlying
cc_library because they did not exist in the proto genrule.

This commit adds strip_inlude_prefix and include_prefix args.

@yashykt

### CODE REVIEW

**Comment by gnossen** [comment]
Doesn't the `kwargs` parameter already cover this functionality?

**Comment by gnossen** [comment]
It seems like a losing battle to specify individual parameters like this. Why not split things out into `cc_args` and `proto_args`? We'd need to think about backwards compatibility here. The docstrings are scant as is. @nicolasnoble Thoughts?

**Comment by kgreenek** [comment]
That is a very valid point. Especially with backwards compatibility.

How about keeping the logic as-is, where **kwargs is forwarded to both the proto and cc_library targets. But also add cc_args and proto_args, which are only forwarded to the respective targets.

**Comment by gnossen** [comment]
@kgreenek Sounds like a plan to me. Just want to get @nicolasnoble 's opinion first.

**Comment by kgreenek** [comment]
PTAL
I updated the macro to have the following 4 args:

* proto_args (dict): Args which are forwarded only to the generated proto_library target.
* cc_proto_args (dict): Args which are forwarded only to the generated cc_proto_library target.
* grpc_args (dict): Args which are forwarded only to the underlying grpc genrule.
* cc_args (dict): Args which are forwarded only to the generated cc_library target.

**Comment by nicolasnoble** [comment]
So, the general defectiveness of just blindly passing down arguments like that is that one could start doing things like `my_abstraction_wrapper(cc_args = ["-some-gcc-option"])`. This obviously breaks the abstraction layer we need to keep for being able to build on msvc for instance.

In other words, doing so creates a leaky abstraction, which I am not happy about.

**Comment by kgreenek** [comment]
It already kinda-sorta breaks the abstraction by passing kwargs down to the underlying rules. But I understand your point.

What I am really looking for is a way to strip the include prefix and set a different one. Our mono-repo was originally set up with a top-level directory called `//src` with all the code under it. We're in the process of renaming it so our python packages and c++ include statements don't all have "src" in them. Having the ability to override the include prefix for individual grpc targets will enable me to update imports / includes across our codebase in a piece-meal way, before finally moving all the files out of src. At least that's my current best idea.

**Comment by nicolasnoble** [comment]
So that's mainly the reason we have the abstraction layer here. We have things defined at the lowest common denominator, and then specific abstraction layers to expand them accordingly.

For instance, we have `externaldeps = ["zlib"]`, and then we have different scripts depending on where the code is to expand this into the proper deps argument. In github this will expand to "//external:zlib", whereas in the Google's mono repo this will expand to the absolute path to the zlib library.

Very specifically, this script: https://github.com/grpc/grpc/blob/master/bazel/grpc_build_system.bzl only exists in this form in github, and is radically different in Google's mono repo, to account for all the mutations in path. Everything else is the same.

**Comment by kgreenek** [comment]
Makes sense. Thanks for sharing that context.

I could undo the last commit in this PR, so it explicitly has args for strip_include_prefix and include_prefix. Or other alternatives. What do you think is the best way for me to achive what I'm trying to do?

**Comment by gnossen** [comment]
Reviving this PR.

@nicolasnoble If that's the case, would it be reasonable to just forward `strip_include_prefix` and `include_prefix` instead? Those options should make sense on all supported platforms.

**Pull request closed without merging**
