### PR TITLE
Add envoy and its dependent repos as submodules in third_party

### PR DESCRIPTION
**Pull request by vishalpowar**
The basic criteria is to have protoc generate code for envoy api's and
this change achieves that.

e.g.
protoc -I=$PWD -I=$PWD/third_party/envoy/api -I=$PWD/third_party/googleapis -I=$PWD/third_party/protobuf -I=$PWD/third_party/protoc-gen-validate third_party/envoy/api/envoy/api/v2/eds.proto

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,244      Total (=)      2,019,244

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,179,118      Total (<)     11,179,122

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
I'm confused as to why we're trying to use protoc here.  I thought our goal was to use upb instead.

**Comment by vishalpowar** [comment]
upb needs protoc generated output, the current steps to generate upb code are as follows 

Step 1: Use protoc to generate code and redirect it to a temp file
protoc envoy/api/v2/discovery.proto --include_imports -o /tmp/descriptor.pb

Step 2: Use protoc output to generate upb code
../upb/bazel-bin/upbc /tmp/descriptor.pb

From what I know josh plans to have upb as a protoc plugin (like nanopb). So the steps above are going to change.

**Comment by haberman** [comment]
I have a normal protoc plugin for upb in PR here, hopefully should be in soon: https://github.com/google/upb/pull/134

**Comment by nicolasnoble** [comment]
You need to tweak some sanity checks when adding submodules to make sure we have everything in sync.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
I feel like the number of git submodules we have is getting out of hand. Are we adding 3 new submodules just to generate code for eds.proto? It looks like the envoy repository isn't exactly small and we are only using a few .proto files from it. Isn't there at least an envoy repo that only contains the API definitions (as opposed to the whole thing).

**Comment by jtattermusch** [comment]
I don't have much context here so I might be off topic, but how do we plan to use the generated code for eds.proto? Depending on the use we might need to update also our Makefile and CMakeLists.txt.
Also, if we are planning to use protoc-generated code in C-core, doesn't that mean that we will start depending on libc++ (I always thought the plan was to avoid that because of binary compatibility problems).

**Comment by vishalpowar** [comment]
There is a READ_ONLY_MIRROR for the api alone 

https://github.com/envoyproxy/data-plane-api

I will check with harvey if we can use it.

**Comment by vishalpowar** [comment]
Regarding the protoc question.
We are going to use upb generated code for C-core XDS plugin. So no dependency on libc++for C-core.

I will be making the changes in Makefile in subsequent PRs when I get upb added to grpc

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,964      Total (=)      2,019,964

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,183,090      Total (>)     11,183,087

 No significant differences in binary sizes


```

**Comment by jtattermusch** [comment]
@vishalpowar  so you are going to check-in the generated code or generate on the fly while building?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by vishalpowar** [comment]
@jtattermusch form what I understand for C-core, we have to commit the generated code to grpc.
Where it goes and how it gets built will be part of the next PR.

for Java and Go we probably need to work with generating code on the fly. I dont plan to tackle it right now.

**Comment by vishalpowar** [comment]
@nicolasnoble do you think these submodules should be part of the list here
test/distrib/cpp/run_distrib_test_cmake_as_externalproject.sh

**Comment by jtattermusch** [comment]
@vishalpowar  in case we are just checking-in the generated code, I'd try to avoid including the submodule in any of our build files (CMakeLists.txt and Makefile), because it needs to be done with care and has nontrivial consequence. The only place where you need access to that file is when regenerating the generated code and in sanity check (to check that the generated code is up-to-date). 
Ideally, regenerating would be done via bazel, because that would let you declare the dependencies in the bazel file easily (and bazel would only download the deps when needed), without needing to introduce new submodules that aren't really build-time dependencies.
Also, you can check out how regenerating is done for nanopb files - it seems it's very similar to what you're trying to achieve https://github.com/grpc/grpc/blob/master/tools/codegen/core/gen_nano_proto.sh (it doesn't use bazel though).

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,964      Total (=)      2,019,964

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,183,086      Total (>)     11,183,085

 No significant differences in binary sizes


```

**Comment by vishalpowar** [comment]
@jtattermusch
> Ideally, regenerating would be done via bazel, because that would let you declare the dependencies
> in the bazel file easily (and bazel would only download the deps when needed), without needing to
> introduce new submodules that aren't really build-time dependencies.

I explored this with @nicolasnoble, bazel did not seem the right approach (envoy uses bazel too). So going ahead with submodule.

Yes, I am trying to make this similar to grpclb for C-core. For other languages, I would defer to @nicolasnoble.

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by nicolasnoble** [comment]
So, the idea is that these submodules are needed to simply have the proto files being imported into the repository. The long story short here is that this is for grpclb, which is going to be included into the core, and exposed to the wrapped languages, so yes, we'll be using pre-generated files committed into the repository. But having the submodules here means that there'll be a script to re-generated these files based on whichever version the submodules are pointing to.

It's one of these "if only we had a proto registry" issue.

**Pull request merged**
