### PR TITLE
Add comments for AsyncGenericService

### LINKED ISSUE #11022: gRPC C++ doxygen audit suggestions/change requests
- `grpc::Server.Wait` says blocks till “all work” is complete. Please consider being more explicit with what is “all work”? pending RPCs? Under what circumstances should the user need to call it?
- `ServerBuilder::SyncServerOption` and `SetSyncServerOption` lacks documentation
- `ServerBuilder::AddCompletionQueue` talks at length about why `is_frequently_polled` should not be set to false, but does not mention an example valid use case for that scenario.
- `CreateChannel`: clarify what a “lame” cannel is.
- `security/auth_metadata_processor.h`: add class description comment
- Comments in `async_generic_service`
- Add documentation for `impl/codegen/{call.h,service.h,rpc_method.h}` even though they are under `impl`?

### PR DESCRIPTION
**Pull request by yang-g**
fixes #11022

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
Test failures: #13477 #12510

**Pull request merged**
