### PR TITLE
Change Python Windows tests to 3.5

### PR DESCRIPTION
**Pull request by kpayson64**

### CODE REVIEW

**Comment by jtattermusch** [comment]
I tested a slight modification of this PR with `python35_config` on Kokoro (it doesn't have python3.6, but it has python3.5) and it has passed.
https://sponge.corp.google.com/invocation?id=6dc5fa71-87c4-400a-b446-29e2575d3cbe&searchFor=

To get tests passing on Kokoro, can we use python3.5 as the default compiler whenever we are running on Kokoro? (if env variable KOKORO_JOB_NAME is set, it's a good indication we are)?

**Comment by kpayson64** [comment]
I'm fine keeping it consistent for now with 3.5, and we can move to 3.6 once that is supported.

**Comment by jtattermusch** [comment]
@kpayson64  nice, I didn't know we had Python35 on our Jenkins workers.

**Comment by kpayson64** [comment]
#11386

**Comment by matt-kwong** [comment]
This breaks sanity - the Dockerfile needed to be updated in the template file.

**Comment by kpayson64** [comment]
Oops, fixed in https://github.com/grpc/grpc/pull/11395

**Pull request merged**
