### PR TITLE
enable grpc-dotnet client compression interop tests

### PR DESCRIPTION
**Pull request by jtattermusch**
Supersedes https://github.com/grpc/grpc/pull/19694/files (and doesn't touch auth interop test blacklist).

### CODE REVIEW

**Comment by jtattermusch** [comment]
@JunTaoLuo @JamesNK

**Comment by jtattermusch** [comment]
@JamesNK  looks like the `server_compressed_streaming` and `server_compressed_unary` scenarios are not passing against the C++ server. We can't merge before this is resolved.

https://source.cloud.google.com/results/invocations/26d210c3-a760-4edd-9187-e59ce3a31356/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_cloud:aspnetcore:c%2B%2B_server:server_compressed_streaming:tls;row=1

**Comment by JamesNK** [comment]
I'm not sure why it is failing. For some reason the deflate compressed content from the C++ server can't be decompressed in C#.

**Comment by JamesNK** [comment]
Can retest after https://github.com/grpc/grpc-dotnet/pull/480 is merged

**Comment by JamesNK** [comment]
Merged

@jtattermusch Ready to retest

**Comment by JamesNK** [comment]
@jtattermusch Once https://github.com/grpc/grpc-dotnet/pull/481 is approved and merged then we can enable the server compression tests for aspnetcore as well.

Could do that here or a new PR.

**Comment by JamesNK** [comment]
Should be able to enable server compression tests now

**Comment by jtattermusch** [comment]
known failures:
https://github.com/grpc/grpc/issues/19338

**Pull request merged**
