### PR TITLE
More flexible default google creds.

### PR DESCRIPTION
**Pull request by jboeuf**
- We now accept the GOOGLE_APPLICATION_CREDENTIALS to point to a refresh
  token as opposed to just a json key.
- Tested with grpc_print_google_default_creds_token.

### CODE REVIEW

**Comment by jboeuf** [comment]
I'd like to modify the code based on my discussion with @anthmgoogle and add some tests as well.

**Comment by jboeuf** [comment]
It looks like the tests are flaky...

**Comment by yang-g** [comment]
LGTM I thought I merged it... Please merge with head~

**Comment by jboeuf** [comment]
Done merging. I looked at the jenkins and travis errors and they are unrelated to this PR.

**Pull request merged**
