### PR TITLE
DO NOT MERGE: print pthread_mutex_log errorcode

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                      FILE SIZE
 ++++++++++++++ GROWING                        ++++++++++++++
  [ = ]       0 [None]                            +104  +0.0%
  +1.3%     +16 src/core/lib/gpr/sync_posix.cc     +16  +1.3%
       +42%     +28 gpr_mu_lock                        +28   +42%

  +0.0%     +16 TOTAL                             +120  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                      FILE SIZE
 ++++++++++++++ GROWING                        ++++++++++++++
  +0.0%     +16 [None]                         +4.73Ki  +0.1%
   +61%    +736 src/core/lib/gpr/sync_posix.cc    +736   +61%
     +11e2%    +738 gpr_mu_lock                       +738 +11e2%

  +0.1%    +752 TOTAL                          +5.45Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
ignore this comment, testing CI.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,981,254      Total (>)      1,980,683

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,811,765      Total (<)     10,811,766

 No significant differences in binary sizes


```

**Pull request closed without merging**
