### PR TITLE
Don't pass -pthread and -std=c99 on Windows.

### PR DESCRIPTION
**Pull request by sgreenstein**
These flags are ignored by the MSVC linker, but cause lots of spam in
the build logs. Add a config_setting in BUILD to enable windows-specific
configuration.

### CODE REVIEW

**Comment by sgreenstein** [comment]
Friendly ping, this is a simple change with no effect on non-Windows platforms

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits was unable to be associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by sgreenstein** [comment]
Comment to re-verify GitHub user email

**Comment by sgreenstein** [comment]
Comment to re-verify CLA

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by sgreenstein** [comment]
#13963 did the same thing and got merged instead

**Pull request closed without merging**
