### PR TITLE
Handle partial transmits in WSASend (Compatibility with WINE).

### PR DESCRIPTION
**Pull request by Schramp**
Handle partial transmits in WSASend (Compatibility with WINE).

#28472 

Associated implementation doesn't stall anymore in WINE. 
I tested a significant data transfer: No stalls and works as expected.

The code doesn't handle the fact that the Buffer is on the stack yet which seems in violation with the API of WSASend. In the blocking scenario, this buffer would get out of scope before WSASend is completed.
I  think the buffer could be corrupted before all bytes are asynchronously send. Also the WSAOVERLAPPED information on the stack doesn't seem to influence later use of that buffer by the kernel.

I didn't detect a buffer/stack corruption which I assume would lead to exceptions (reading invalid length and pointers from the stack).

N.B. This PR is not intended to be merged right away.

@ctiller

### CODE REVIEW

**Review by EastyWeasty — APPROVED** [review]

**Comment by nicolasnoble** [comment]
Duplicate of #28432 really.

**Review by EastyWeasty — APPROVED** [review]

**Review by EastyWeasty — APPROVED** [review]

**Comment by ctiller** [comment]
@drfloob probably your call on where this goes

**Comment by Schramp** [comment]
> Duplicate of #28432 really.

I think this is the same problem, judging the patch and description.

**Comment by Schramp** [comment]
#28524

**Comment by drfloob** [comment]
Thanks @Schramp , sorry I didn't catch the duplication. Let's use the other PR to collaborate on this.

**Pull request closed without merging**
