### PR TITLE
PHP: ran php-cs-fixer to comply with php coding standard

### LINKED ISSUE #851: PHP code style
I noticed a quite unique style in the PHP language wrapper.

For ease of external contribution, testing (formatting), and consistency with other projects, I recommend switching the PHP wrapper to comply to the [PSR-2 style guide](http://www.php-fig.org/psr/psr-2/).

You can then (initially or eventually) implement [a format checker](https://github.com/squizlabs/PHP_CodeSniffer) in the tests/CI to make sure that contributions comply with the standard.

I'd be happy to make a pull-request with the changes, if the idea is accepted.

### PR DESCRIPTION
**Pull request by stanley-cheung**
Ran [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to comply with [PHP coding standard](http://www.php-fig.org/psr/psr-2/)

Fixes #851

Added a script to run this regularly

```
~/grpc/src/php$ ./bin/run_php_cs_fixer.sh 
Fixed all files in 1.428 seconds, 7.750 MB memory used
Fixed all files in 1.223 seconds, 8.000 MB memory used
Fixed all files in 1.341 seconds, 9.500 MB memory used
Fixed all files in 2.037 seconds, 8.000 MB memory used
```

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Missed the `tests` directory. More commits coming

**Comment by Rican7** [comment]
While this works, this ties the style to [the proprietary **Symfony** project's ruleset][symfony]. It may be better to run `php-cs-fixer` with the `--level=psr2` argument, as it defaults to `--level=symfony`.

Alternatively, you could use the [`phpcs`/`phpcbf`][phpcs] tools, like this:

- Check: `phpcs --standard=PSR2 --encoding=utf-8 -p /path/to/code`
- Fix: `phpcbf --standard=PSR2 --encoding=utf-8 /path/to/code`



[symfony]: https://github.com/symfony/symfony
[phpcs]: https://github.com/squizlabs/PHP_CodeSniffer

**Comment by stanley-cheung** [comment]
The version of `php-cs-fixer` I was running seems to run `--level=psr2` by default? I run `php-cs-fixer fix lib/Grpc --level=psr2` just now and it doesn't report anymore violations.

Here's the help section I see if I run `php-cs-fixer help fix`

```
The fix command tries to fix as much coding standards
 problems as possible on a given file or directory:
 
     php /usr/local/bin/php-cs-fixer fix /path/to/dir
     php /usr/local/bin/php-cs-fixer fix /path/to/file
 
 The --verbose option show applied fixers. When using ``txt`` format (default one) it will also displays progress notification.
 
 The --level option limits the fixers to apply on the
 project:
 
     php /usr/local/bin/php-cs-fixer fix /path/to/project --level=psr0
     php /usr/local/bin/php-cs-fixer fix /path/to/project --level=psr1
     php /usr/local/bin/php-cs-fixer fix /path/to/project --level=psr2
     php /usr/local/bin/php-cs-fixer fix /path/to/project --level=symfony
 
 By default, all PSR-2 fixers and some additional ones are run. The "contrib
 level" fixers cannot be enabled via this option; you should instead set them
 manually by their name via the --fixers option.
```

**Comment by Rican7** [comment]
Yea, I believe the **Symfony** code style spec is an extension to **PSR-2**, so technically anything that satisfies **Symfony**'s will also satisfy **PSR-2**. In which case, this should be good. I just noticed some uncommon spacing in method parameter definitions and realized `php-cs-fixer` may have been run with the **Symfony** specific standard in mind.

Sorry to have bothered! :smile:

**Pull request merged**
