### PR TITLE
Fix issue #14717. Piggyback keepalive ping onto pings inflight

### PR DESCRIPTION
**Pull request by yashykt**
Fix issue #14717 where we do not send the keepalive ping if there is already another ping in progress which means we also do not start the keepalive watchdog. This can lead to a hung state.

This PR fixes that behavior by considering the ping in progress as a keepalive ping too and starts the keepalive ping.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by srini100** [comment]
Is this sufficient to fix #14717? You mentioned that keepalive timer is not reset based on reads or writes. Is it sufficient to depend on BDP pings. Also, what about conforming to keepalive timer values?

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                             cpu_time    real_time
------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/262144                                         +4%         +4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/32768/2                  +6%         +6%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32768                +5%         +5%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/32768/1/1  +5%         +5%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/32768/2/1  +4%         +4%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/32768/32768                  +4%         +4%
```

**Comment by yashykt** [comment]
I have verified that it certainly fixes #14717

It might be a different kind of ping not just a BDP ping. This fix only handles the kind of racy condition where we lose connection when a ping is already in progess. In the normal case, where no other ping is in flight, it would send a ping and start the keepalive watchdog timer.

We are also conforming to the keepalive timer values in the normal case. As for the case that we are fixing, it does mean that the ping has more time to complete since it was started earlier but it does not harm the spirit of the keepalive ping.

Also, when I said that the keepalive timer is not reset based on reads or writes, I did not mean that it is not rearmed when it fires or is cancelled. The keepalive timer is rearmed once the keepalive ping finishes and it is also fired if it is cancelled for some reason.

**Comment by srini100** [comment]
I am fine with this fix for this particular issue. Deferring code review to @yang-g.  Will open a separate issue to enhance keepalive to look at reads too. That'll make it more reliable and efficient.

**Comment by yashykt** [comment]
Known issues : #14815, #14969, #13617

**Pull request merged**
