### PR TITLE
Pyformat Python code

### LINKED ISSUE #262: Run pyformat over Python code.
As long as the C family is using (or intends to use) clang-format, pyformat should be used on the Python parts of the codebase.

### PR DESCRIPTION
**Pull request by soltanmm**
First commit is the tooling change, second commit runs the tooling change over the code.

... This breaks from the Google style guide for Python. Do we care?

Fixes #262.

cc @jtattermusch

### CODE REVIEW

**Comment by soltanmm** [comment]
It also doesn't appear to format Cython code... Do we care?

**Comment by nathanielmanistaatgoogle** [comment]
[Whoa](https://www.google.com/search?q=keanu+whoa&tbm=isch). Thank you much!

Yes, we do care about breaking with the [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html). Please describe the differences in your commit message? Alternatively, is there such a thing as a "`.pyformatrc`" that we could use to maintain compliance with the style guide and/or put us more in control of exactly what differences we maintain?

**Comment by nathanielmanistaatgoogle** [comment]
We do care about formatting Cython code - I guess my reason for that would be "we have enough of it". If it can't be done today in this change, open a fresh issue for it?

**Comment by soltanmm** [comment]
*LE GASP*. Google's internal Python style guide is different from the external style guide! I'll have to go back and check over its agreement with [PEP8](https://www.python.org/dev/peps/pep-0008/).

**Comment by soltanmm** [comment]
They appear compatible.

**Comment by nathanielmanistaatgoogle** [comment]
This currently needs conflict resolution - hold off on rebasing until after [6609](https://github.com/grpc/grpc/pull/6609) and [6602](https://github.com/grpc/grpc/pull/6602) are integrated? Then let's cross our fingers and attempt integration of this?

**Comment by soltanmm** [comment]
rebased

**Comment by nathanielmanistaatgoogle** [comment]
How about we come back to this after [pull request 7338](https://github.com/grpc/grpc/pull/7338)?

**Comment by soltanmm** [comment]
Rebased.

**Comment by soltanmm** [comment]
I'd actually like to hold off on doing this before GA. Would rather not inadvertently force rebases for upmerges from v1.0.x.

**Comment by soltanmm** [comment]
Or, rather, I guess I'd prefer having this get simultaneously cherry-picked onto the v1.0.x branch just before 1.0.1.

**Comment by nathanielmanistaatgoogle** [comment]
I also fear that this will bring pain to anything that follows it and that has to be done on more than one branch. When is the next time that we'll be at a point in our development cycle with only one branch under active development and all other branches are stable/closed? More than a few days, less than a few weeks?

**Comment by soltanmm** [comment]
Maybe just before 1.1 is cut? Maybe.

**Comment by pgrosu** [comment]
The majority of the changes are just transforming each space to two spaces, where the usual 2-space indent becomes a 4-space indent.  The code is hard enough to go through with some the files being quite long, so maybe keeping it as a 2-space indent for now would be better for troubleshooting purposes.  Yes, the PEP8 style helps but things are changing every day that it might be nice to have it formatted after things stabilize for some time.

**Comment by soltanmm-google** [comment]
outmoded

**Pull request closed without merging**
