### PR TITLE
Fix namespace package usage

### PR DESCRIPTION
**Pull request by soltanmm**
Potential fix for #6892. Build-to-watch and trace through to distrib tests: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/1023/ .

### CODE REVIEW

**Comment by soltanmm** [comment]
Fixes the [distrib test](https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/958/). For some reason the Windows build is broken, though (AFAICT due to an unrelated issue).

**Comment by kpayson64** [comment]
Just want to verify this doesn't break grpc-tools: Is grpcio-tools still allowed to share the grpc. namespace if grpcio is not a namespace package?

**Comment by jtattermusch** [comment]
Friendly ping, can we get this in ASAP?

**Comment by kpayson64** [comment]
Tested locally, it seems this does not interfere with the grpc.tools package as I suspected.  LGTM.

**Pull request merged**
