### PR TITLE
Foundry: Align msan kokoro and manual configurations

### PR DESCRIPTION
**Pull request by jtattermusch**
- last piece of kokoro foundry scripts cleanup (all rbe kokoro runs now rely on bazelrc files).
- After this, bazer_wrapper.py usage has been completely eliminated.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,303      Total (=)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,276      Total (>)     11,115,270

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Adhoc msan run with this change:
https://source.cloud.google.com/results/invocations/f9c94c1f-e6a2-4bb0-9161-2f25d0ad52c6/targets (1523 failures)

And msan run on master (without this PR):
https://source.cloud.google.com/results/invocations/d2eb1816-a7ca-44d8-a0f7-28b6fac7caeb/targets (1521 failures)

that seems to be good enough in terms of not making test results worse while cleaning up the configuration.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,303      Total (=)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,275      Total (=)     11,115,275

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Pull request merged**
