### PR TITLE
Change transport connectivity watch API to not be lossy.

### PR DESCRIPTION
**Pull request by murgatroid99**
Backport #20255 to version 1.24.x so that I can pick it up in the Node library to fix grpc/grpc-node#1503.

### CODE REVIEW

**Comment by markdroth** [comment]
Note that #20255 was reverted in #20407 and then rolled forward with some additional fixes in #20408.  You should probably make sure you have those additional fixes here.

**Comment by markdroth** [comment]
Other than the above comment, this looks okay to me, but the code has changed a lot since then, so it's possible that I'm missing something.  I'd say you should rely more on the tests than on my review to ensure correctness.

**Comment by murgatroid99** [comment]
The artifact builds are failing because of Python dependency issues. I think the C# failure is #18126. The Objective C failure appears to be #9538 by way of #22214. The Bazel failures have no details; I'm guessing that they're not set up on this branch. The interop suites are all failing because of Go and Java docker build errors; I assume that the Dockerfiles in this branch are not compatible with the HEAD of those repositories. The sanity checks job is failing on pylint because of what looks like a dependency incompatibility problem.

With the C/C++ tests passing, I am mostly confident in this change.

**Comment by murgatroid99** [comment]
I am not authorized to merge this PR to this branch. I think I am as confident as I can get that this PR is in a good state, so I would like to merge it when possible.

**Pull request closed without merging**
