### PR TITLE
Use GRPC_CLOSURE_RUN instead of directly invoking callbacks in filters

### PR DESCRIPTION
**Pull request by hcaseyal**
Minor cleanup for some filters. Needed for my filter microbenchmarks PR #15630

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.0%     +40 [None]                                                                 +784  +0.0%
  +5.0%     +48 src/core/ext/filters/load_reporting/server_load_reporting_filter.cc     +48  +5.0%
       +12%     +48 on_initial_md_ready                                                     +48   +12%
  +1.6%     +32 src/core/ext/filters/deadline/deadline_filter.cc                        +32  +1.6%
       +62%     +36 recv_initial_metadata_ready                                             +36   +62%

  +0.0%    +120 TOTAL                                                                  +864  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by hcaseyal** [comment]
Known issues: #15710 and #15610

**Pull request merged**
