### PR TITLE
Fix breakage from moving gpr_strdup

### PR DESCRIPTION
**Pull request by jcanizales**
Broken by #1898

### CODE REVIEW

**Comment by ctiller** [comment]
@a-veitch - should this code be removed at this point?

**Comment by a-veitch** [comment]
@ctiller asked "should this code be removed at this point?"

It could be removed, but we are shortly going to refactor/move/delete many of the files in the statistics directory into census. Not removing them now will make that series of changes cleaner, if you can live with the work-in-progress inconsistencies with having them in the code base and not in the build.

**Comment by ctiller** [comment]
I'm fine with that Alistair.

**Comment by jcanizales** [comment]
Merge this meanwhile, then?

**Comment by ctiller** [comment]
Why not fix your build system instead of bandaiding?

**Comment by jcanizales** [comment]
Doing that (#2064) is blocked on a Cocoapods issue.

**Comment by ctiller** [comment]
Closable?

**Comment by jcanizales** [comment]
Yes, closing.
Made obsolete by https://github.com/nicolasnoble/grpc/pull/4.

**Pull request closed without merging**
