### PR TITLE
Return response object to server interceptors in request/response calls

### PR DESCRIPTION
**Pull request by tmattia**
Attempt to fix https://github.com/grpc/grpc/issues/15966

I didn't have enough time to invest into understand the test suite as of right now, but there didn't seem to be an automated test covering this part of the code specifically.

I would probably suggest writing a simple functional test covering this scenario (from the interceptors proposal), but I would appreciate any guidance on what would be the best way to automate it on this project.

### CODE REVIEW

**Comment by tmattia** [comment]
@apolcyn is there anything I can do to help move this PR forward?

**Comment by apolcyn** [comment]
Sorry for the wait on this. As you've described the server-side interceptors indeed do not appear to follow the examples in the [initial proposal](As you've described the server-side interceptors indeed do not appear to follow the guidelin). But with another look, I think that the one problem with the server-side interceptor API that you're pointing out here is slightly beyond request/response calls? If fixing request/response calls to have access to the "response", it would also make sense to fix the three other types of RPC handlers: "client streaming", "server streaming", and "bidi streaming". 

Out of curiosity, what's your intended use of being able to access the "response" in server interceptors? Note that the response is not mutable at that point, because after an interceptor yields, the call has been effectively finished and terminated, complete with a status having already been sent (looks like another problem with the gRFC examples is that those examples appear to make the response object look mutable).

**Comment by ganmacs** [comment]
> Out of curiosity, what's your intended use of being able to access the "response" in server interceptors?

I want to log the response data as [go-grpc-middleware](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/498ae206fc3cfe81cd82e48c1d4354026fa5f9ec/logging/logrus/payload_interceptors.go#L33) does.

**Comment by shidel-dev** [comment]
I am also running into this issue. My use case is to be able to record status codes in the logs of my service.

**Pull request closed without merging**
