### PR TITLE
Add gcov php coverage report

### PR DESCRIPTION
**Pull request by stanley-cheung**
For #3772

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Ready for review

Link to a lcov code coverage report for PHP in Jenkins: https://grpc-testing.appspot.com/job/gRPC_pull_requests/5153/config=gcov,language=php,platform=linux/HTML_Report/

**Comment by murgatroid99** [comment]
Please update the copyright dates in `build_php.sh` and `post_tests_php.sh`.

**Comment by stanley-cheung** [comment]
Fixed the copyright dates.

**Comment by stanley-cheung** [comment]
Ping?

**Comment by stanley-cheung** [comment]
Thanks!

**Pull request merged**
