### PR TITLE
add java options to empty.proto

### PR DESCRIPTION
**Pull request by jyane**
Add java options to empty.proto for consistency.
In grpc-java, empty.proto has some java options. https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/proto/io/grpc/testing/integration/empty.proto

ref:
https://github.com/grpc/grpc-java/issues/4241
https://github.com/grpc/grpc-java/commit/156cc44c5f6ad64ff9b6706e4b03f24abadb4c99

cc: @ejona86

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ejona86** [comment]
@nathanielmanistaatgoogle, I don't know the merge process for this repo.

**Comment by jtattermusch** [comment]
@carl-mastrangelo  is this PR still useful? I think you've mentioned that you've updated the .protos in our repo recently. Let's resolve/close.

**Comment by carl-mastrangelo** [comment]
It is not.

**Pull request closed without merging**
