### PR TITLE
Simplify the platform and constraints settings for remote execution

### PR DESCRIPTION
**Pull request by eytankidron**
* Remove the toolchains //third_party/toolchains:local and //third_party/toolchains:local_large.
* Remove the platforms :rbe_ubuntu1604, :rbe_ubuntu1604_large, :local and :local_large.
* No longer inherit from @rbe_default//config:platform but instead use it directly. It is now the only non-windows platform.
* When creating @rbe_default//config:platform directly with rbe_autoconfig, set dockerAddCapabilities and dockerPrivileged directly in the exec_properties field. No need to set dockerNetwork to "off" and dockerSiblingContainers to false since these are the defaults.
* Also set gceMachineType = "n1-highmem-2" on the default platform. This value can be overridden by specific targets that want to use LARGE_MACHINE.
* Use create_exec_properties_dict where appropriate.
* Use custom_exec_properties to define LARGE_MACHINE.

I wasn't able to test thoroughly that this PR does not break any existing targets. I was not able to run anything on windows/mac and I also don't have access to gRPC's RBE setup.

@jtattermusch

### CODE REVIEW

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/20639
https://github.com/grpc/grpc/issues/20468

**Comment by jtattermusch** [comment]
@gnossen ready to merge?

**Comment by gnossen** [comment]
So I just attempted to cherrypick this PR and see how presubmit went. Unfortunately, this isn't going to work as is. All of the C++ `BUILD` files are also being run under Blaze, so they need to work in both environments. So these lines are problematic.

```
load("@grpc_custom_exec_properties//:constants.bzl", "LARGE_MACHINE")
```

From Blaze's perspective, there's no such thing as a `grpc_custom_exec_properties` workspace.

gRPC has dealt with similar problems in the past. Check out [how we pull in external dependencies](https://github.com/grpc/grpc/blob/05d6f9f2b1655e9f9771351a2625de766304ab10/src/core/ext/transport/cronet/BUILD#L41) [in `grpc_cc_library`](https://github.com/grpc/grpc/blob/892d5d724e24a7c7af1d48d960e23e0389bce453/bazel/grpc_build_system.bzl#L51). There's an alternative definition of this function in google3 that is able to translate, e.g. `twisted` to `//third_party/py/twisted`.

I think we need some sort of wrapper here as well in order to make all of the `BUILD` files agnostic to which build system they're running under. I'm looking into the best way to make this happen.

**Comment by gnossen** [comment]
I believe https://github.com/grpc/grpc/pull/20926 will resolve these issues.

**Comment by jtattermusch** [comment]
Thanks for doing this!

**Comment by eytankidron** [comment]
Thank you Richard and Jan for doing this!
I didn't realize the google3 integration would be so tricky.

**Pull request merged**
