### PR TITLE
Create a shared_from_this analog, remove direct Ref/Unref calls

### LINKED ISSUE #14152: Add shared_from_this analog to RefCountedPtr
### Should this be an issue in the gRPC issue tracker?
 
Yes

### What version of gRPC and what language are you using?
 
Core
 
### What operating system (Linux, Windows, …) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
N/A
 
### What did you do?

Needed a way to count a new reference to an object already owned by a RefCountedPtr from that object's member function
 
### What did you expect to see?
 
Something like shared_from_this 

### What did you see instead?
 
Have to directly invoke Ref() and Unref() on the object

### Anything else we should know about your project / environment?

We can do this without multiple inheritance or combinatorial explosion of types by adding an additional template parameter to `RefCounted` and partially specializing to include the needed extra fields.

### PR DESCRIPTION
**Pull request by vjpai**
Fixes #14152

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +0.0%      +8 [None]                                            +1.69Ki  +0.0%
  +0.4%     +24 src/core/ext/filters/client_channel/subchannel.cc     +24  +0.4%
       +17%     +56 grpc_core::ConnectedSubchannel::CreateCall            +56   +17%
      +3.4%      +9 [Unmapped]                                             +9  +3.4%

  +0.0%     +32 TOTAL                                             +1.71Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +0.0%      +8 [None]                                            +1.69Ki  +0.0%
  +0.4%     +24 src/core/ext/filters/client_channel/subchannel.cc     +24  +0.4%
       +17%     +56 grpc_core::ConnectedSubchannel::CreateCall            +56   +17%
      +3.4%      +9 [Unmapped]                                             +9  +3.4%

  +0.0%     +32 TOTAL                                             +1.71Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by vjpai** [comment]
grpc_subchannel_call should probably be a class since it's not just POD anymore, and we need to give it an ersatz destructor since it's arena-allocated.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                 cpu_time    real_time
----------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/262144                                             +7%         +7%
BM_PumpStreamServerToClient<InProcess>/262144                                             +10%        +10%
BM_PumpStreamServerToClient<InProcess>/32768                                              +7%         +7%
BM_PumpStreamServerToClient<InProcessCHTTP2>/32768                                        +4%         +4%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/1                        +6%         +6%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/2                        +10%        +10%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/32768/1                         +5%         +5%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/2                     +6%         +6%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/32768/1                      +4%         +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/262144                      +9%         +9%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                       +8%         +8%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/262144                   +6%         +6%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32768                    +7%         +7%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/0     +12%        +12%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/1     +7%         +7%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/32768/1/1      +5%         +5%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/32768/2/0      +4%         +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/2/0  +5%         +5%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/2/1  +11%        +11%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/32768/1/0   +4%         +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/32768/2/1   +4%         +4%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/32768/0                             -4%         -4%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/32768/32768                         -4%         -4%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/262144                         -4%         -4%
```

**Comment by markdroth** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/core/ext/filters/client_channel/subchannel.cc, line 137 at r2](https://reviewable.io:443/reviews/grpc/grpc/14179#-L3jjss_xmHxjym-kNXF:-L3jjss_xmHxjym-kNXG:b1isb23) ([raw file](https://github.com/grpc/grpc/blob/cffb434e11ed37c725eb42d9d59b6f4540b8ab1d/src/core/ext/filters/client_channel/subchannel.cc#L137)):*
> ```cpp
> 
> struct grpc_subchannel_call {
>   grpc_core::RefCountedPtr<grpc_core::ConnectedSubchannel> connection;
> ```

This is a C struct that hasn't yet been converted to C++, so we will need to explicitly call `reset()` on this field before the struct is destroyed.

---

*[src/core/ext/filters/client_channel/subchannel.cc, line 779 at r2](https://reviewable.io:443/reviews/grpc/grpc/14179#-L3jkNTDfMSJGcVWBL0H:-L3jkNTDfMSJGcVWBL0I:b-kjx625) ([raw file](https://github.com/grpc/grpc/blob/cffb434e11ed37c725eb42d9d59b6f4540b8ab1d/src/core/ext/filters/client_channel/subchannel.cc#L779)):*
> ```cpp
>   grpc_call_stack* callstk = SUBCHANNEL_CALL_TO_CALL_STACK(*call);
>   
>   (*call)->connection = RefCountedFromThis();
> ```

This doesn't seem like a good use of `RefCountedFromThis()`, since the ref is being held by a different object, not internally by the object itself.  For this use-case, we could just use CRTP to change the existing `RefCounted` class to return this from the `Ref()` method, rather than needing a whole other class.  It seems to me that the new class is only useful for internal refs, where we don't already have access to the `RefCountedPtr` to copy.  Or is there something I'm missing here?

---

*[src/core/lib/gprpp/ref_counted_ptr.h, line 120 at r2](https://reviewable.io:443/reviews/grpc/grpc/14179#-L3jiwd_NJ13rx89xVCh:-L3jiwd_NJ13rx89xVCi:byq83w5) ([raw file](https://github.com/grpc/grpc/blob/cffb434e11ed37c725eb42d9d59b6f4540b8ab1d/src/core/lib/gprpp/ref_counted_ptr.h#L120)):*
> ```objc
>   // implementation because the underlying object is inherited from the
>   // RefCounted class. We can static_cast back to the derived class.
>   RefCountedPtr<This> RefCountedFromThis() {
> ```

Should this method be protected, since the intended use-case is for internal refs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14179)*

**Comment by vjpai** [comment]
Closed in favor of #14221

**Pull request closed without merging**
