### PR TITLE
refactor extra-copy integrity-only protector

### PR DESCRIPTION
**Pull request by jiangtaoli2016**
This is internal refactoring and optimization to make extra-copy version of frame protector more efficient. In current implementation, we will allocate at least 3 slices on protected slices buffer. In this new version, a single slice is allocated.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
   +17%    +272 src/core/tsi/alts/zero_copy_frame_protector/alts_grpc_integrity_only_record_prot    +272   +17%
       +43%    +266 alts_grpc_integrity_only_protect                                                    +266   +43%
       +30%      +6 [Unmapped]                                                                            +6   +30%

 -+-+-+-+-+-+-+ MIXED                                                                            +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                                                           +1.27Ki  +0.0%

  +0.0%    +256 TOTAL                                                                            +1.54Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
This shows about a 1% improvement for both CPU and Wall time

**Comment by jiangtaoli2016** [comment]
@ncteisen This is a awesome!
@yihuazhang Do you mind take a quick look?

**Comment by jiangtaoli2016** [comment]
Thanks all for quick review!

**Pull request merged**
