### PR TITLE
core: fix duplicated definition

### PR DESCRIPTION
**Pull request by kuscsik**
Refactor remove() function name to avoid
duplicated function definition when building
on latest AOSP. stdio in Bionic also defines
remove().

### CODE REVIEW

**Comment by vjpai** [comment]
I'm unclear why this is an issue; it's a static function in a ".c" file, not publicly-visible or in a header file. The compiler should just resolve this reference to the corresponding reference in the same linkage unit. Are you not able to build in your environment, or are you getting shadow warnings or some other issue?

**Comment by kuscsik** [comment]
I'm building grpc as part of the AOSP framework. When building against bionic libc the
header file has a dependency on stdio.h which also defines a remove() function causing the build to fail. 
bionic headers:

https://android.googlesource.com/platform/bionic/+/master/libc/include/stdio.h#144

**Comment by vjpai** [comment]
Ok, I see. Thanks for your contribution. I'll make review comments and I'm asking for another reviewer on this as well.

**Comment by kuscsik** [comment]
Thanks for the review @vjpai. I updated the pull request with the requested change.

**Comment by kuscsik** [comment]
@vjpai ping.

**Comment by kuscsik** [comment]
Hi @y-zeng, could you please look at this? There is no reviewer activity for some time.
Thanks,

Zoltan

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by vjpai** [comment]
Oops! The current code is not mergeable because of formatting. Can you run
`tools/distrib/clang_format_code.sh` ? You may need to do this with sudo depending on how your docker is configured.

**Comment by kuscsik** [comment]
Formatting applied. It should be good now.

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by vjpai** [comment]
Thanks, @kuscsik , we'll merge it soon.

**Comment by vjpai** [comment]
Test failures: #9542 and issue being addressed in #10848

**Pull request merged**
