### PR TITLE
Watch subchannel that's reffed

### PR DESCRIPTION
**Pull request by AspirinSJL**
Fix https://github.com/grpc/grpc/issues/15514. (The new test fails on master.)

But when I was adding the test comments according to what I saw in the log, I see some problems... Maybe we should fix the issue shown in https://github.com/grpc/grpc/pull/16175 first. Depending on the decision of that issue, this PR will be updated.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/16176)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%    +696 [None]                                                                               +3.64Ki  +0.0%
      +0.1%    +664 [Unmapped]                                                                           +3.61Ki  +0.0%
       +20%      +8 vtable for grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelList         +8   +20%
       +20%      +8 vtable for grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList           +8   +20%
       +20%      +8 vtable for grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::R      +8   +20%
       +20%      +8 vtable for grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::Pi      +8   +20%
  +2.9%    +368 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +368  +2.9%
      [NEW]    +243 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc    +243  [NEW]
      [NEW]    +166 grpc_core::(anonymous namespace)::PickFirst::ShutdownUnselectedSubchannelsLocked        +166  [NEW]
      [NEW]    +127 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc    +127  [NEW]
      [NEW]     +92 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +92  [NEW]
      +3.6%     +61 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnect     +61  +3.6%
      +0.9%     +31 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                                +31  +0.9%
       +11%     +29 [Unmapped]                                                                               +29   +11%
  +2.1%    +288 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                +288  +2.1%
      [NEW]    +250 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu    +250  [NEW]
      [NEW]     +92 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +92  [NEW]
      +7.6%     +23 [Unmapped]                                                                               +23  +7.6%
      [NEW]     +18 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelList::StartWatchin     +18  [NEW]

 -------------- SHRINKING                                                                            --------------
  -0.5%     -32 src/core/ext/filters/client_channel/subchannel.cc                                        -32  -0.5%
      [DEL]    -393 maybe_start_connecting_locked                                                           -393  [DEL]
      -7.7%     -24 grpc_subchannel_notify_on_state_change                                                   -24  -7.7%
      -3.0%      -8 [Unmapped]                                                                                -8  -3.0%

  +0.1% +1.29Ki TOTAL                                                                                +4.25Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,977,509      Total (>)      1,976,654

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,614,978       Core (>)      3,612,762

10,777,950      Total (>)     10,775,736


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%    +512 [None]                                                                                  +408  +0.0%
  +1.8%    +224 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +224  +1.8%
      [NEW] +1.57Ki grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnect +1.57Ki  [NEW]
      [NEW]    +274 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList::ProcessInitial    +274  [NEW]
      +7.2%    +238 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               +238  +7.2%
      [NEW]    +181 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList::MaybeTryNextLo    +181  [NEW]
      [NEW]    +181 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc    +181  [NEW]
      [NEW]    +166 grpc_core::(anonymous namespace)::PickFirst::ShutdownUnselectedSubchannelsLocked        +166  [NEW]
      [NEW]     +84 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +84  [NEW]
      [NEW]     +78 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +78  [NEW]
       +14%     +39 [Unmapped]                                                                               +39   +14%
      +178%     +32 grpc_core::(anonymous namespace)::PickFirst::ExitIdleLocked                              +32  +178%
      +5.6%     +16 grpc_core::(anonymous namespace)::PickFirst::PickLocked                                  +16  +5.6%
      +1.6%     +16 grpc_core::(anonymous namespace)::PickFirst::UpdateChildRefsLocked                       +16  +1.6%
       +11%      +8 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc      +8   +11%

 -------------- SHRINKING                                                                            --------------
  -0.7%     -96 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 -96  -0.7%
      [DEL]    -580 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelList::StartWatchin    -580  [DEL]
     -47.6%    -496 grpc_core::(anonymous namespace)::RoundRobin::DoPickLocked                              -496 -47.6%
      [DEL]    -196 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData::ProcessConne    -196  [DEL]
     -12.9%     -80 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -80 -12.9%
      [DEL]     -78 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -78  [DEL]
     -29.9%     -73 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -73 -29.9%
     -10.9%     -66 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -66 -10.9%
     -18.8%     -44 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -44 -18.8%
     -13.4%     -43 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -43 -13.4%
      -3.3%     -33 grpc_core::(anonymous namespace)::RoundRobin::UpdateChildRefsLocked                      -33  -3.3%
      -5.1%     -32 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData::UpdateConnec     -32  -5.1%
     -22.2%     -10 grpc_core::(anonymous namespace)::RoundRobin::ExitIdleLocked                             -10 -22.2%
      -0.3%      -1 grpc_core::(anonymous namespace)::RoundRobin::PickLocked                                  -1  -0.3%
  -1.0%     -64 src/core/ext/filters/client_channel/subchannel.cc                                        -64  -1.0%
      [DEL]    -393 maybe_start_connecting_locked                                                           -393  [DEL]
      -7.7%     -24 grpc_subchannel_notify_on_state_change                                                   -24  -7.7%
      -1.9%     -16 on_subchannel_connected                                                                  -16  -1.9%
      -3.7%     -10 [Unmapped]                                                                               -10  -3.7%
  -0.9%     -16 src/core/lib/transport/connectivity_state.cc                                             -16  -0.9%
      [DEL]      -9 grpc_connectivity_state_has_watchers                                                      -9  [DEL]
     -15.6%      -7 [Unmapped]                                                                                -7 -15.6%

  +0.0%    +560 TOTAL                                                                                   +456  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   667,413       Core (>)        666,360

 1,981,532      Total (>)      1,980,479

***************FRAMEWORKS****************
  New size                      Old size
10,810,874      Total (>)     10,810,798

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%    +496 [None]                                                                                  +384  +0.0%
  +1.8%    +224 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +224  +1.8%
      [NEW] +1.57Ki grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnect +1.57Ki  [NEW]
      [NEW]    +274 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList::ProcessInitial    +274  [NEW]
      +7.2%    +238 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               +238  +7.2%
      [NEW]    +181 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList::MaybeTryNextLo    +181  [NEW]
      [NEW]    +181 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc    +181  [NEW]
      [NEW]    +166 grpc_core::(anonymous namespace)::PickFirst::ShutdownUnselectedSubchannelsLocked        +166  [NEW]
      [NEW]     +84 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +84  [NEW]
      [NEW]     +78 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +78  [NEW]
       +14%     +39 [Unmapped]                                                                               +39   +14%
      +178%     +32 grpc_core::(anonymous namespace)::PickFirst::ExitIdleLocked                              +32  +178%
      +5.6%     +16 grpc_core::(anonymous namespace)::PickFirst::PickLocked                                  +16  +5.6%
      +1.6%     +16 grpc_core::(anonymous namespace)::PickFirst::UpdateChildRefsLocked                       +16  +1.6%
       +11%      +8 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc      +8   +11%

 -------------- SHRINKING                                                                            --------------
  -0.7%     -96 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 -96  -0.7%
      [DEL]    -580 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelList::StartWatchin    -580  [DEL]
     -47.6%    -496 grpc_core::(anonymous namespace)::RoundRobin::DoPickLocked                              -496 -47.6%
      [DEL]    -196 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData::ProcessConne    -196  [DEL]
     -12.9%     -80 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -80 -12.9%
      [DEL]     -78 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -78  [DEL]
     -29.9%     -73 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -73 -29.9%
     -10.9%     -66 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -66 -10.9%
     -18.8%     -44 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -44 -18.8%
     -13.4%     -43 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -43 -13.4%
      -3.3%     -33 grpc_core::(anonymous namespace)::RoundRobin::UpdateChildRefsLocked                      -33  -3.3%
      -5.1%     -32 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData::UpdateConnec     -32  -5.1%
     -22.2%     -10 grpc_core::(anonymous namespace)::RoundRobin::ExitIdleLocked                             -10 -22.2%
      -0.3%      -1 grpc_core::(anonymous namespace)::RoundRobin::PickLocked                                  -1  -0.3%
  -0.5%     -32 src/core/ext/filters/client_channel/subchannel.cc                                        -32  -0.5%
      [DEL]    -393 maybe_start_connecting_locked                                                           -393  [DEL]
      -7.7%     -24 grpc_subchannel_notify_on_state_change                                                   -24  -7.7%
      -1.9%     -16 on_subchannel_connected                                                                  -16  -1.9%
      -4.4%     -12 [Unmapped]                                                                               -12  -4.4%
  -0.9%     -16 src/core/lib/transport/connectivity_state.cc                                             -16  -0.9%
      [DEL]      -9 grpc_connectivity_state_has_watchers                                                      -9  [DEL]
     -15.6%      -7 [Unmapped]                                                                                -7 -15.6%

  +0.0%    +576 TOTAL                                                                                   +464  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   667,401       Core (>)        666,360

 1,981,520      Total (>)      1,980,479

***************FRAMEWORKS****************
  New size                      Old size
10,810,884      Total (>)     10,810,798

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.6%     +80 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                   +80  +0.6%
      [NEW] +1.57Ki grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnect +1.57Ki  [NEW]
      [NEW]    +274 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList::ProcessInitial    +274  [NEW]
      +7.2%    +238 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               +238  +7.2%
      [NEW]    +181 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList::MaybeTryNextLo    +181  [NEW]
      [NEW]    +181 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc    +181  [NEW]
      [NEW]    +166 grpc_core::(anonymous namespace)::PickFirst::ShutdownUnselectedSubchannelsLocked        +166  [NEW]
      [NEW]     +84 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +84  [NEW]
      [NEW]     +78 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +78  [NEW]
      +178%     +32 grpc_core::(anonymous namespace)::PickFirst::ExitIdleLocked                              +32  +178%
      +7.3%     +21 [Unmapped]                                                                               +21  +7.3%
      +5.6%     +16 grpc_core::(anonymous namespace)::PickFirst::PickLocked                                  +16  +5.6%
      +1.6%     +16 grpc_core::(anonymous namespace)::PickFirst::UpdateChildRefsLocked                       +16  +1.6%
       +11%      +8 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc      +8   +11%

 -------------- SHRINKING                                                                            --------------
  -0.1%    -840 [None]                                                                               -10.7Ki  -0.1%
      -0.1%    -768 [Unmapped]                                                                           -10.6Ki  -0.1%
     -11.1%      -8 vtable for grpc_core::FakeResolver                                                        -8 -11.1%
      -6.2%      -8 vtable for grpc_core::(anonymous namespace)::RoundRobin                                   -8  -6.2%
     -11.1%      -8 vtable for grpc_core::(anonymous namespace)::AresDnsResolver                              -8 -11.1%
     -11.1%      -8 vtable for grpc_core::(anonymous namespace)::SockaddrResolver                             -8 -11.1%
     -11.1%      -8 vtable for grpc_core::(anonymous namespace)::NativeDnsResolver                            -8 -11.1%
      -6.2%      -8 vtable for grpc_core::(anonymous namespace)::GrpcLb                                       -8  -6.2%
      -6.2%      -8 vtable for grpc_core::(anonymous namespace)::PickFirst                                    -8  -6.2%
      -6.2%      -8 vtable for grpc_core::LoadBalancingPolicy                                                 -8  -6.2%
     -11.1%      -8 vtable for grpc_core::Resolver                                                            -8 -11.1%
  -5.3%    -320 src/core/lib/surface/channel.cc                                                         -320  -5.3%
      [DEL]    -318 grpc_channel_reset_connect_backoff                                                      -318  [DEL]
      -1.5%      -2 [Unmapped]                                                                                -2  -1.5%
  -1.8%    -240 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                -240  -1.8%
      [DEL]    -580 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelList::StartWatchin    -580  [DEL]
     -47.6%    -496 grpc_core::(anonymous namespace)::RoundRobin::DoPickLocked                              -496 -47.6%
      [DEL]    -196 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData::ProcessConne    -196  [DEL]
      [DEL]     -92 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -92  [DEL]
     -12.9%     -80 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -80 -12.9%
      [DEL]     -78 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -78  [DEL]
     -29.9%     -73 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -73 -29.9%
     -10.9%     -66 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -66 -10.9%
     -18.8%     -44 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -44 -18.8%
     -13.4%     -43 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -43 -13.4%
      [DEL]     -34 grpc_core::(anonymous namespace)::RoundRobin::ResetBackoffLocked                         -34  [DEL]
      -3.3%     -33 grpc_core::(anonymous namespace)::RoundRobin::UpdateChildRefsLocked                      -33  -3.3%
      -5.1%     -32 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData::UpdateConnec     -32  -5.1%
     -22.2%     -10 grpc_core::(anonymous namespace)::RoundRobin::ExitIdleLocked                             -10 -22.2%
      -0.3%      -1 grpc_core::(anonymous namespace)::RoundRobin::PickLocked                                  -1  -0.3%
  -3.2%    -208 src/core/ext/filters/client_channel/subchannel.cc                                       -208  -3.2%
      [DEL]    -393 maybe_start_connecting_locked                                                           -393  [DEL]
      [DEL]    -113 grpc_subchannel_reset_backoff                                                           -113  [DEL]
     -14.8%     -46 on_alarm                                                                                 -46 -14.8%
     -10.1%     -29 [Unmapped]                                                                               -29 -10.1%
      -7.7%     -24 grpc_subchannel_notify_on_state_change                                                   -24  -7.7%
      -1.9%     -16 on_subchannel_connected                                                                  -16  -1.9%
  -0.2%     -82 src/core/ext/filters/client_channel/client_channel.cc                                    -82  -0.2%
      -6.1%     -88 start_transport_op_locked                                                                -88  -6.1%
      [DEL]      -2 grpc_core::Resolver::ResetBackoffLocked                                                   -2  [DEL]
  -5.7%     -78 src/core/ext/filters/client_channel/lb_policy.cc                                         -78  -5.7%
      [DEL]     -78 grpc_core::LoadBalancingPolicy::ResetBackoffLocked                                       -78  [DEL]
  -0.4%     -64 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           -64  -0.4%
      [DEL]     -50 grpc_core::(anonymous namespace)::GrpcLb::ResetBackoffLocked                             -50  [DEL]
      -3.3%     -14 [Unmapped]                                                                               -14  -3.3%
  -1.1%     -48 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc             -48  -1.1%
      [DEL]     -38 grpc_core::(anonymous namespace)::AresDnsResolver::ResetBackoffLocked                    -38  [DEL]
      -6.7%     -10 [Unmapped]                                                                               -10  -6.7%
  -1.8%     -48 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                  -48  -1.8%
      [DEL]     -38 grpc_core::(anonymous namespace)::NativeDnsResolver::ResetBackoffLocked                  -38  [DEL]
      -7.4%     -10 [Unmapped]                                                                               -10  -7.4%
  -0.9%     -16 src/core/lib/transport/connectivity_state.cc                                             -16  -0.9%
      [DEL]      -9 grpc_connectivity_state_has_watchers                                                      -9  [DEL]
     -15.6%      -7 [Unmapped]                                                                                -7 -15.6%

  -0.1% -1.82Ki TOTAL                                                                                -11.7Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE                                                             FILE SIZE
 ++++++++++++++ GROWING                                               ++++++++++++++

 -------------- SHRINKING                                             --------------
  -0.1%    -240 [None]                                                   -536  -0.0%
  -0.4%     -16 src/cpp/client/channel_cc.cc                              -16  -0.4%
      [DEL]      -9 grpc::experimental::ChannelResetConnectionBackoff          -9  [DEL]
      -3.5%      -7 [Unmapped]                                                 -7  -3.5%

  -0.1%    -256 TOTAL                                                    -552  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                 cpu_time    real_time
----------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamServerToClient<InProcess>/262144                                             +6%         +6%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/2/0  +4%         +4%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/262144                            +4%         +4%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/262144                    +5%         +5%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/32768/32768                      +6%         +6%
```

**Comment by markdroth** [comment]
Is this PR still needed for anything?

**Pull request closed without merging**
