### PR TITLE
Fix macos interop_toprod tests

### PR DESCRIPTION
**Pull request by jtattermusch**
Followup for #23703.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Testing with an adhoc run: sponge/1acd48d6-ba64-484a-aa47-d776ff4da174

**Comment by jtattermusch** [comment]
Another adhoc run: sponge/014864b0-b7e7-4ae4-9891-6ae3bb387467

**Comment by jtattermusch** [comment]
Adhoc test passed: sponge/c2a8e733-b222-403f-9109-335ca774b13a

That gives me confidence that the fix is valid and that we can merge this fix (instead of reverting).

**Comment by jtattermusch** [comment]
This is safe to merge as soon as the tests pass and it should supersede the revert PR https://github.com/grpc/grpc/pull/23729.

**Comment by nanahpang** [comment]
There are three tests required but not proceeding in a long time.

**Comment by jtattermusch** [comment]
Restarted the tests to be able to merge.

**Pull request merged**
