### PR TITLE
Fix no_proxy_str memory leak

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/14119.

### CODE REVIEW

**Comment by markdroth** [comment]
Yash is the new owner of this code, so he should review.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +2.9%     +48 src/core/ext/filters/client_channel/http_proxy.cc     +48  +2.9%
      +2.9%     +46 proxy_mapper_map_name                                 +46  +2.9%
      +5.0%      +2 [Unmapped]                                             +2  +5.0%

 -+-+-+-+-+-+-+ MIXED                                             +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                               +136  +0.0%

  +0.0%     +32 TOTAL                                                +184  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
@yashykt   can you give this a quick look?

**Comment by jtattermusch** [comment]
Known failures:
#13429

**Pull request merged**
