### PR TITLE
Fix #3803

### LINKED ISSUE #3803: Metadata plugins do not propagate the error_details to the status
I have a test with a metadata plugin that sets a non-OK status and sets `error_details` in the callback. The call correctly ends with a non-OK status and the expected status code, but it gets empty status details instead of the specified details string.

### PR DESCRIPTION
**Pull request by jboeuf**
Error details are now being propagated. Better late than never...
Fixes #3803

### CODE REVIEW

**Comment by jboeuf** [comment]
Adding @ctiller for the double-free fix of optional_message.

**Comment by murgatroid99** [comment]
I guess LGTM, but I don't know much about the code that's being modified here.

**Comment by jboeuf** [comment]
Thanks, can you test that it does what you want in node for example and
re-assign the PR to @ctiller?

**Comment by murgatroid99** [comment]
I have confirmed that this change makes the relevant tests pass in Node.

**Comment by jboeuf** [comment]
Thanks! @ctiller, can you have a look?

**Comment by hsaliak** [comment]
@ctiller could you please take a look at this PR?

**Comment by ctiller** [comment]
LGTM

**Comment by jtattermusch** [comment]
test this please

**Pull request merged**
