### PR TITLE
Add cpp macros to append wrapped language info to xDS user agent

### PR DESCRIPTION
**Pull request by markdroth**
@nicolasnoble, can you please advise as to the best way to set this macro in the build system for C++?  I assume that we'll need to add it for both bazel and cmake?  Thanks!

CC @srini100 @yashykt

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Quick comment first:

> all identifiers regardless of use that begin with either two underscores or an underscore followed by a capital letter are reserved names

so technically, `_GRPC_XDS_USER_AGENT_VERSION_SUFFIX` is reserved.

**Comment by nicolasnoble** [comment]
In general, for Bazel and cmake, you'll want to add defines in the corresponding library target. Since the change you're doing does not need to propagate to the users of the library, the change is luckily less problematic than if it was to pollute the whole environment.

For bazel you want to use the [`local_defines`](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary.local_defines) attribute for the build target.

For cmake, that'd be [`add_definitions`](https://cmake.org/cmake/help/latest/command/add_definitions.html) used [like so](https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/examples/cpp/cmake/common.cmake#L24-L26). I don't think we could make it easy to only target the one library, but at the same time, I don't think it matters that much here.

**Review by nicolasnoble — APPROVED** [review]

**Comment by markdroth** [comment]
As per today's discussion, we'll leave these macros unset for C++, setting them only for wrapped languages when we know that we're building for those languages.  This means that we'll be lumping in cases where we build python with bazel in with the C++ stats, but that's probably okay for now.  We can always try to find a new way to optimize that later if we need more detail.

**Comment by markdroth** [comment]
Known issues: #26019

**Pull request merged**
