### PR TITLE
Test this repo against grpc/grpc-node#1239

### PR DESCRIPTION
**Pull request by murgatroid99**
Background: The Node test jobs in this repo's PRs run [this script](https://github.com/grpc/grpc-node/blob/master/test-grpc-submodule.sh) in the node repository, passing a commit reference for the commit in the PR. That script is missing a `set -e` line and recently the command to check out the submodule commit has been failing because of some changes made to the `third_party/upb`. As a result of that combination of problems, the script has been silently testing the current state of the grpc-node repository, instead of the state corresponding to updating the submodule with the contents of the PR.

This PR runs the Node test job against grpc/grpc-node#1239, which fixes those problems. There are other known integration problems, so the Node test job for this PR will fail initially.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
So, @veblush, the node test was broken here reporting no problem (see https://github.com/grpc/grpc-node/pull/1239 - the upb submodule change broke it), which means a few build issues cropped since this happened. One of them being this:

```
static library binding.gyp:absl__strings__strings#target has several files with the same basename:
  escaping: deps/grpc/third_party/abseil-cpp/absl/strings/escaping.cc deps/grpc/third_party/abseil-cpp/absl/strings/internal/escaping.cc
```

This probably is something we want to double-file with abseil. The gist is that if you try to create a static library under macos using XCode with the same filename twice, one will get ignored or overridden by the other one, even if they come from different sub directories.

I am guessing this issue with `escaping.cc` isn't biting us right now because we're currently not using features from these files, but nodejs' build system is more pedantic to make sure this doesn't spread. #21639 has more details on what's going on.

**Comment by nicolasnoble** [comment]
Hopefully we can get abseil/abseil-cpp#605 in, to fix the next breakage on this PR.

**Comment by veblush** [comment]
Thank you for the report. This is interesting but I think it could be a bit out-dated warning. The warning was needed before with msvc2008 and mac make with libtool on mac and it has been considered to remove this check as no one is actively using those. Is it possible to use `--no-duplicate-basename-check` ?

Reference:
- [--no-duplicate-basename-check](https://codereview.chromium.org/344573002)
- [gyp: Duplicate basenames in sources section](https://forums.livecode.com/viewtopic.php?t=26114)
- [Internal: GYP duplicate basename check](http://g/googlemac-gyp/Kf_fN0rvwTQ)

**Comment by nicolasnoble** [comment]
@veblush: if this was working, sure: nodejs/node-gyp#2026

**Pull request closed without merging**
