### PR TITLE
[C++] Fix Directory Walker on NetBSD.

### PR DESCRIPTION
**Pull request by 0-wiz-0**
Use the POSIX code like FreeBSD does.

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
Can someone please explain what a label is and how I can add it? I don't see the magic keyword 'release' in the git log, so it's not something in the commit message, is it?

**Comment by 0-wiz-0** [comment]
Let's try summoning @drfloob  because of their help last time :-)

**Comment by yashykt** [comment]
Sorry for the delay here

**Comment by drfloob** [comment]
> Let's try summoning @drfloob because of their help last time :-)

Apologies, the Github UI is terrible for this sort of summoning. 

> Can someone please explain what a label is and how I can add it?

Only maintainers can add labels. We use them for categorization and automation around that. Generally, PRs and Issues are auto-assigned to maintainers, and we triage them (and add labels) at least weekly. This one slipped through the cracks.

**Comment by yashykt** [comment]
@0-wiz-0 the tests failed probably because of conflicts. Can you merge master please?

**Comment by 0-wiz-0** [comment]
I've reapplied the change. It's really simple, please merge it.

**Review by yashykt — APPROVED** [review]

**Review by ctiller — APPROVED** [review]

**Pull request closed without merging**
