### PR TITLE
Move grpcio_tools to src/python

### PR DESCRIPTION
**Pull request by soltanmm**
This is #9413, but against `v1.1.x`.

@nathanielmanistaatgoogle @kpayson64 n.b. I can't start the artifacts build anymore, although I'll note that the previous builds passed modulo #9355.

### CODE REVIEW

**Comment by soltanmm** [comment]
@googlebot ehhh? It is now signed with my non-Google hat.

**Comment by soltanmm** [comment]
Uhhh... just for the record: I confirm that my past self that had the Google hat on is okay with me (the person without my Google hat on) pull-requesting my Google-hatted commits.

**Comment by nathanielmanistaatgoogle** [comment]
Uggh, the most brainless of all conflicts. Please resolve; my apologies.

Commit content looks fine.

**Comment by soltanmm** [comment]
Well. That rebase got screwed up. Will revisit.

**Comment by nathanielmanistaatgoogle** [comment]
Understood; looking forward to the unscrewupping.

**Comment by soltanmm** [comment]
Like a jar of peanut butter at a picnic.

**Comment by nathanielmanistaatgoogle** [comment]
test this please

**Comment by nathanielmanistaatgoogle** [comment]
Is the change to `tools/dockerfile/bazel/Dockerfile` an intended part of your commit?

**Comment by soltanmm** [comment]
re Dockerfile: https://github.com/grpc/grpc/pull/9413#discussion_r97166711

**Comment by nathanielmanistaatgoogle** [comment]
What's going on with the CLA label flapping? Anything we can do to placate @googlebot?

What do you make of [the sanity test failure](https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2792/testReport/junit/(root)/sanity_linux_dbg/tools_distrib_python_check_grpcio_tools_py/)?

**Comment by soltanmm** [comment]
Sanity test needs a change in `check_grpcio_tools.py`, while @googlebot will likely need some email address finagling on the commit. Will get back to those.

**Comment by soltanmm** [comment]
(`this is ok to test`, pl0x; alt criticize the sanity optimism in the face of cthulhu-esque horrorrs)

**Comment by nathanielmanistaatgoogle** [comment]
Conflicts? Oh come on!

... sigh. Please resolve?

Even though it's just a simple(!) move I'm very much looking forward to having this.

**Comment by soltanmm** [comment]
D-:

**Comment by nathanielmanistaatgoogle** [comment]
Good news: gRPC is now doing regular time-based releases like a healthy project.

Bad news: the right place for this is now `master`, which is [where it was originally going to be](https://github.com/grpc/grpc/pull/9413) until [I asked for it to be on `v1.1.x`](https://github.com/grpc/grpc/pull/9413#issuecomment-274877367).

Let me know if I'm being an awful person asking, but... I've retargeted this to `master`; please resolve conflicts one last time and let's get it in.

I apologize for the runaround.

**Comment by soltanmm** [comment]
Woah, that's possible on GitHub? How'd you retarget it?

**Comment by nathanielmanistaatgoogle** [comment]
It has _become_ possible, as of a few weeks ago. The "Edit" button right up there at the top of the page.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
I think this PR would be nice to have, but it needs to be rebased against upstream/master first (there's been some changes in artifact building in the meantime).

Let's do it or close this PR.

**Comment by mehrdada** [comment]
Closing this as it is more sensible to do a PR from scratch due to conflicts and such...

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @soltanmm isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Pull request closed without merging**
