### PR TITLE
php return the right classes

### LINKED ISSUE #12898: \Grpc\SimpleSurfaceActiveCall php no longer exists
### What version of gRPC and what language are you using?
`grpc 1.6`
 
### What operating system (Linux, Windows, …) and version?
 `Linux`
 
### What did you do?
When using grpc library in PHP, running `Phan is a static analyzer for PHP` there should be no undefined classes in the php library.
 
### What did you expect to see?
No errors.
 
### What did you see instead?
```
PhanUndeclaredClassMethod Call to method wait from undeclared class \Grpc\SimpleSurfaceActiveCall
``` 
 
### Where is the problem?
I believe the problems is here:
https://github.com/grpc/grpc/blob/master/src/php/lib/Grpc/BaseStub.php#L221

### PR DESCRIPTION
**Pull request by ghophp**
fixes #12898

### CODE REVIEW

**Comment by ghophp** [comment]
I signed it!

**Comment by stanley-cheung** [comment]
OK to test

**Comment by ghophp** [comment]
any idea why the failure? should I rebase and push again or the errors are related to the changes indeed?

**Comment by stanley-cheung** [comment]
Thanks for the contribution!

**Pull request merged**
