### PR TITLE
php: fix scenario_config command

### PR DESCRIPTION
**Pull request by pongad**
The flag "-c" should be in an argument.

### CODE REVIEW

**Comment by ZhouyihaiDing** [comment]
The checks didn't run maybe because of the conflict. Can you please rebase this PR?
Thanks!

**Comment by pongad** [comment]
@ZhouyihaiDing Thank you for letting me know. I merged master, PTAL.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by ZhouyihaiDing** [comment]
Tested on adhoc and works well. LGTM.
I was wondering why the sanity check still hangs after rebase but now it starts. How to trigger the checks start running?

**Comment by stanley-cheung** [comment]
I applied the `kokoro:run` label to trigger the tests

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by pongad** [comment]
@stanley-cheung Do the failures look like flakes to you? I'm not super familiar with gRPC code base but I really don't see how this could fail a C++ test.

**Pull request merged**
