### PR TITLE
Use requirements.txt when installing dependencies

### PR DESCRIPTION
**Pull request by soltanmm**
Associated with #1564.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Curiosity about what's in this pull request took me to https://caremad.io/2013/07/setup-vs-requirement/; what do you think of what's there?

**Comment by soltanmm** [comment]
I think it's valid to a point. Right now we have extension code that compiles with modified `CFLAGS` and `LD_LIBRARY_PATH` when `pip install`ing for our tests. If we use the form of `requirements.txt` offered by the article:

```
--index-url https://pypi.python.org/simple/
-e .
```

Then there are three counters I can immediately think of:

1. Wherever we are trying to `pip install` for our tests, if we wish to use the `requirements.txt` file (and I believe this is a desirable and 'right' use-case), we will be forced to modify our environment variables for both `grpcio` _and_ all of its dependencies. That has a small but non-zero chance of becoming a major problem not under our control in the future.
2. We will never treat `grpcio` as an 'application', so we will never have concrete dependencies in our `requirements.txt` file.
3. There exist two models of 'inheritance'. One can imagine 'inheritance' of concrete requirements from abstract requirements as that of a tightening or as a widening. In the case of a tightening, yes, as written this PR has a dissonance with common thought. In the case of a widening, from concrete to abstract, one can imagine that the way in which `requirements.txt` is parsed can be akin to a 'stripping down' or a 'forgetting' of concrete behaviors. This behavior isn't necessarily implemented, but it wouldn't necessarily be difficult to add onto what's here if we, for whatever reason, decided to treat `grpcio` as an 'application'.

**Comment by soltanmm** [comment]
It appears that there're some nontrivial version issues with respect to `pip.req.parse_requirements`.

**Comment by ctiller** [comment]
Is this dead?

**Comment by nathanielmanistaatgoogle** [comment]
Merely pining for the fjords! We know we want to list our dependencies in exactly one place; I think we're still working through where and how to do it.

**Comment by soltanmm** [comment]
The impotent manifestation of our wants in this particular PR are effectively dead.

**Pull request closed without merging**
