### PR TITLE
Ruby: Update gemspec homepage org from google to grpc

### PR DESCRIPTION
**Pull request by euglena1215**
`grpc.gemspec` and `grpc-tools.gemspec` homepage link is outdated (was google org).
So, I fixed it.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @euglena1215 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by euglena1215** [comment]
Signed CLA.

**Comment by euglena1215** [comment]
I signed it

**Comment by euglena1215** [comment]
I signed it

**Comment by mishina2228** [comment]
Why was this PR not merged?
`homepage` links are still outdated.

https://github.com/grpc/grpc/blob/1630efd8ab3d2ff4b006f1288fde1be5c29dc651/grpc.gemspec#L11
https://github.com/grpc/grpc/blob/1630efd8ab3d2ff4b006f1288fde1be5c29dc651/src/ruby/tools/grpc-tools.gemspec#L9

This change reduces unnecessary redirection when someone visits this gem's homepage
via https://rubygems.org/gems/grpc and https://rubygems.org/gems/grpc-tools,
or some tools or APIs that use the gem's metadata.

Would you consider merging this PR? Thanks!

**Comment by mishina2228** [comment]
@apolcyn Sorry for direct pin, could you please consider merging this PR?

**Pull request closed without merging**
