### PR TITLE
PHP: replace jessie to stretch

### PR DESCRIPTION
**Pull request by HannahShiSFB**
This PR is part of deprecate php5. fix of #24306 

@veblush @stanley-cheung

### CODE REVIEW

**Comment by veblush** [comment]
Thank you for the quick fix-forward. 

[grpc_build_artifacts_multiplatform](https://g3c.corp.google.com/results/invocations/b8235786-1415-4a0b-aadb-4cbe5b5b93e9): running

**Comment by stanley-cheung** [comment]
I kicked off another [grpc_build_artifacts_multiplatform](https://g3c.corp.google.com/results/invocations/dc4a07e3-e0a7-4a6f-b965-f0c9fd8a6006/targets) run. The first one failed because I didn't run the `./tools/dockerfile/push_testing_images.sh` script yet.

**Comment by veblush** [comment]
@stanley-cheung Thanks! I'm approving this so that you can get two approvals. You can get this merged after it passes the build_artifacts test.

**Review by veblush — APPROVED** [review]
Thank you for the quick-fix!

**Comment by stanley-cheung** [comment]
```
libtool: compile:  g++ -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserLtUI9v/grpc-1.33.0dev/include -I/tmp/pear/temp/pear-build-defaultuserLtUI9v/grpc-1.33.0dev/main -I/tmp/pear/temp/grpc -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb -DHAVE_CONFIG_H -std=c++11
 -fno-exceptions -fno-rtti -g -O2 -c /tmp/pear/temp/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc  -fPIC -DPIC -o src/core/ext/transport/chttp2/server/.libs/chttp2_server.o
In file included from /tmp/pear/temp/grpc/src/core/ext/transport/chttp2/transport/internal.h:40:0,
                 from /tmp/pear/temp/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc:39:
/tmp/pear/temp/grpc/src/core/lib/compression/stream_compression.h:27:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
Makefile:348: recipe for target 'src/core/ext/transport/chttp2/server/chttp2_server.lo' failed
make: *** [src/core/ext/transport/chttp2/server/chttp2_server.lo] Error 1
ERROR: `make' failed
```

@HannahShiSFB we probably need to add `zlib1g-dev` to the `apt-get install` prereqs list here: https://github.com/grpc/grpc/pull/24311/files#diff-2dde7c4d21168f570e0ac439097545c5R17

**Comment by HannahShiSFB** [comment]
> ```
> libtool: compile:  g++ -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -I. -I/tmp/pear/temp/grpc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserLtUI9v/grpc-1.33.0dev/include -I/tmp/pear/temp/pear-build-defaultuserLtUI9v/grpc-1.33.0dev/main -I/tmp/pear/temp/grpc -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb -DHAVE_CONFIG_H -std=c++11
>  -fno-exceptions -fno-rtti -g -O2 -c /tmp/pear/temp/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc  -fPIC -DPIC -o src/core/ext/transport/chttp2/server/.libs/chttp2_server.o
> In file included from /tmp/pear/temp/grpc/src/core/ext/transport/chttp2/transport/internal.h:40:0,
>                  from /tmp/pear/temp/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc:39:
> /tmp/pear/temp/grpc/src/core/lib/compression/stream_compression.h:27:18: fatal error: zlib.h: No such file or directory
>  #include <zlib.h>
>                   ^
> compilation terminated.
> Makefile:348: recipe for target 'src/core/ext/transport/chttp2/server/chttp2_server.lo' failed
> make: *** [src/core/ext/transport/chttp2/server/chttp2_server.lo] Error 1
> ERROR: `make' failed
> ```
> 
> @HannahShiSFB we probably need to add `zlib1g-dev` to the `apt-get install` prereqs list here: https://github.com/grpc/grpc/pull/24311/files#diff-2dde7c4d21168f570e0ac439097545c5R17

added. thank you for the comment

**Comment by stanley-cheung** [comment]
Kicked off another [grpc_build_artifacts_multiplatform](https://g3c.corp.google.com/results/invocations/c5bed12f-a7fd-44bc-a054-5926bb7e60b9/targets) run. Thanks for the quick fix.

**Comment by stanley-cheung** [comment]
[another run](https://g3c.corp.google.com/results/invocations/d7bfab1d-57a4-4da1-9737-f4408d9dcb71/targets)

**Comment by stanley-cheung** [comment]
> [another run](https://g3c.corp.google.com/results/invocations/d7bfab1d-57a4-4da1-9737-f4408d9dcb71/targets)

This last one is finally completely passing in all 3 stages.

**Review by stanley-cheung — APPROVED** [review]
LGTM

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/issues/24333

**Pull request merged**
