### PR TITLE
Fix forward of sanitized non-polling (#12953)

### PR DESCRIPTION
**Pull request by vjpai**
This is the right way to enable non-polling since some tests (fuzzers) are declared non-polling but actually have 0-timeout polls.

### CODE REVIEW

**Comment by vjpai** [comment]
Tests on the rollback (#12956) are taking so long that I decided to send in the fix forward as well.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                   FILE SIZE
 ++++++++++++++ GROWING                                     ++++++++++++++
  +0.0%     +48 [None]                                         +552  +0.0%
      +0.0%     +48 [Unmapped]                                     +552  +0.0%
      [NEW]      +8 real_poll_function                                0  [ = ]
  +3.6%     +48 src/core/lib/iomgr/ev_posix.cc                  +48  +3.6%
      [NEW]     +91 dummy_poll                                      +91  [NEW]
       +91%     +32 (anonymous namespace)::init_non_polling         +32   +91%
      +1.6%      +3 [Unmapped]                                       +3  +1.6%

  +0.0%     +96 TOTAL                                          +600  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by ctiller** [comment]
I've merged this into #12789 in order to progress... So please don't squash or rebase going forward :)

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.new: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_2_0.counters.new: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_2_0.counters.old: 1


[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Test failures: #11737

**Pull request merged**
