### PR TITLE
Fix all build warnings reported by gcc-9.

### PR DESCRIPTION
**Pull request by alokpr**
Fixes grpc/grpc#29417

@yashykt

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Hi - thank you for the pull request, but we'd need you to sign the CLA to accept it first.

**Comment by alokpr** [comment]
> 

I have tried signing the CLA several times. In fact I have even received the confirmation email saying "The CLA has now been signed". But for some reason, the records are not being updated here.

**Comment by nicolasnoble** [comment]
@alokpr let me bring in the appropriate people to look at the CLA issues then :)

**Comment by alokpr** [comment]
> /easycla

Figured out the CLA issue. The commits did not have the right author. Looks good now.

**Comment by alokpr** [comment]
@nicolasnoble Is there anything else you need from me?

**Comment by nicolasnoble** [comment]
Ah, sorry, didn't see your update. here. Let's see about this PR now.

**Comment by alokpr** [comment]
> 

Hmm... this is strange because the change proposed in the patch is the correct syntax for union: `union attr class-head-name { member-specification }`
https://en.cppreference.com/w/cpp/language/union

I have tested this patch with both gcc-9 and gcc-11. Which compiler are you testing it with?

**Comment by nicolasnoble** [comment]
This is definitely using clang.

**Comment by drfloob** [comment]
Closing this as stale, but please reopen if you wish to try to resolve the issues with the broader set of compilers and versions that gRPC supports.

**Pull request closed without merging**
