### PR TITLE
Separate out the posix part of the c-ares driver

### PR DESCRIPTION
**Pull request by apolcyn**
c-ares on Windows can make use the same overall structure of the existing posix driver, but it needs to  
 first abstract out the use of posix-specific grpc iomgr API's, which this PR does.

This PR mostly just a simple move from `grpc_ares_ev_driver_posix.cc` to `grpc_ares_ev_driver.cc`, but with a couple of changes to abstract posix:
* use the newly added `GrpcPolledFd` objects instead of using posix iomgr APIs directly.
* use the portable `ares_socket_t` type instead of `int`, for underlying c-ares fd's.

I'll try to follow this up shortly with the windows-specific piece shortly, in case we want to wait on review of this until that part can be seen.

Note that my plan for windows is to have the `GrpcPolledFd` use the [ares_set_socket_functions](https://github.com/c-ares/c-ares/blob/1abf13ed309b001868bc9c90507ab73939f6b9da/ares.h#L379) API, to use the grpc windows poller by using our own buffers.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/15780)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.9% +6.23Ki [None]                                                                             +33.2Ki  +0.4%
      +1.0% +6.12Ki [Unmapped]                                                                         +33.1Ki  +0.4%
      [NEW]     +80 vtable for grpc_core::GrpcPolledFdPosix                                                +80  [NEW]
      +3.0%     +32 [None]                                                                                   0  [ = ]
  [NEW] +2.19Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc     +2.19Ki  [NEW]
      [NEW] +1.02Ki grpc_ares_notify_on_event_locked                                                   +1.02Ki  [NEW]
      [NEW]    +368 grpc_ares_ev_driver_create_locked                                                     +368  [NEW]
      [NEW]    +171 grpc_ares_ev_driver_unref                                                             +171  [NEW]
      [NEW]    +159 on_readable_locked                                                                    +159  [NEW]
      [NEW]    +139 on_writable_locked                                                                    +139  [NEW]
      [NEW]    +128 fd_node_shutdown_locked(fd_node*, char const*) [clone .isra.1] [clone .part.2]        +128  [NEW]
      [NEW]     +79 grpc_ares_ev_driver_shutdown_locked                                                    +79  [NEW]
      [NEW]     +61 [Unmapped]                                                                             +61  [NEW]
      [NEW]     +49 grpc_ares_ev_driver_ref                                                                +49  [NEW]
      [NEW]     +25 grpc_ares_ev_driver_start_locked                                                       +25  [NEW]
      [NEW]      +9 grpc_ares_ev_driver_destroy_locked                                                      +9  [NEW]
      [NEW]      +5 grpc_core::GrpcPolledFd::~GrpcPolledFd                                                  +5  [NEW]
      [NEW]      +4 grpc_ares_ev_driver_get_channel_locked                                                  +4  [NEW]
      [NEW]      +2 grpc_core::GrpcPolledFd::~GrpcPolledFd                                                  +2  [NEW]

 -------------- SHRINKING                                                                          --------------
 -79.7% -1.81Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix. -1.81Ki -79.7%
      [DEL] -1.05Ki grpc_ares_notify_on_event_locked                                                   -1.05Ki  [DEL]
      [DEL]    -368 grpc_ares_ev_driver_create_locked                                                     -368  [DEL]
      [DEL]    -210 on_readable_locked                                                                    -210  [DEL]
      [DEL]    -171 grpc_ares_ev_driver_unref                                                             -171  [DEL]
      [DEL]    -131 on_writable_locked                                                                    -131  [DEL]
      [DEL]    -116 fd_node_shutdown_locked(fd_node*, char const*) [clone .isra.1] [clone .part.2]        -116  [DEL]
     -93.5%     -86 [Unmapped]                                                                             -86 -93.5%
      [DEL]     -79 grpc_ares_ev_driver_shutdown_locked                                                    -79  [DEL]
      [DEL]     -49 grpc_ares_ev_driver_ref                                                                -49  [DEL]
      [DEL]     -25 grpc_ares_ev_driver_start_locked                                                       -25  [DEL]
      [DEL]      -9 grpc_ares_ev_driver_destroy_locked                                                      -9  [DEL]
      [DEL]      -4 grpc_ares_ev_driver_get_channel_locked                                                  -4  [DEL]

  +0.5% +6.60Ki TOTAL                                                                              +33.6Ki  +0.4%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.9% +6.15Ki [None]                                                                             +32.7Ki  +0.4%
      +0.9% +6.04Ki [Unmapped]                                                                         +32.6Ki  +0.4%
      [NEW]     +80 vtable for grpc_core::GrpcPolledFdPosix                                                +80  [NEW]
      +3.0%     +32 [None]                                                                                   0  [ = ]
  [NEW] +2.19Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc     +2.19Ki  [NEW]
      [NEW] +1.03Ki grpc_ares_notify_on_event_locked                                                   +1.03Ki  [NEW]
      [NEW]    +368 grpc_ares_ev_driver_create_locked                                                     +368  [NEW]
      [NEW]    +171 grpc_ares_ev_driver_unref                                                             +171  [NEW]
      [NEW]    +159 on_readable_locked                                                                    +159  [NEW]
      [NEW]    +139 on_writable_locked                                                                    +139  [NEW]
      [NEW]    +128 fd_node_shutdown_locked(fd_node*, char const*) [clone .isra.1] [clone .part.2]        +128  [NEW]
      [NEW]     +79 grpc_ares_ev_driver_shutdown_locked                                                    +79  [NEW]
      [NEW]     +49 [Unmapped]                                                                             +49  [NEW]
      [NEW]     +49 grpc_ares_ev_driver_ref                                                                +49  [NEW]
      [NEW]     +25 grpc_ares_ev_driver_start_locked                                                       +25  [NEW]
      [NEW]      +9 grpc_ares_ev_driver_destroy_locked                                                      +9  [NEW]
      [NEW]      +9 grpc_core::GrpcPolledFd::~GrpcPolledFd                                                  +9  [NEW]
      [NEW]      +4 grpc_ares_ev_driver_get_channel_locked                                                  +4  [NEW]
      [NEW]      +2 grpc_core::GrpcPolledFd::~GrpcPolledFd                                                  +2  [NEW]

 -------------- SHRINKING                                                                          --------------
 -84.7% -1.93Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix. -1.93Ki -84.7%
      [DEL] -1.05Ki grpc_ares_notify_on_event_locked                                                   -1.05Ki  [DEL]
      [DEL]    -368 grpc_ares_ev_driver_create_locked                                                     -368  [DEL]
      [DEL]    -210 on_readable_locked                                                                    -210  [DEL]
      [DEL]    -171 grpc_ares_ev_driver_unref                                                             -171  [DEL]
      [DEL]    -131 on_writable_locked                                                                    -131  [DEL]
      [DEL]    -116 fd_node_shutdown_locked(fd_node*, char const*) [clone .isra.1] [clone .part.2]        -116  [DEL]
     -87.0%     -80 [Unmapped]                                                                             -80 -87.0%
      [DEL]     -79 grpc_ares_ev_driver_shutdown_locked                                                    -79  [DEL]
      [DEL]     -49 grpc_ares_ev_driver_ref                                                                -49  [DEL]
      [DEL]     -25 grpc_ares_ev_driver_start_locked                                                       -25  [DEL]
      [DEL]      -9 grpc_ares_ev_driver_destroy_locked                                                      -9  [DEL]
      [DEL]      -4 grpc_ares_ev_driver_get_channel_locked                                                  -4  [DEL]

  +0.5% +6.41Ki TOTAL                                                                              +33.0Ki  +0.4%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by apolcyn** [comment]
Review status: 13 of 16 files reviewed, 5 unresolved discussions (waiting on @markdroth, @apolcyn, @dgquintas, and @AspirinSJL)

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 26 at r1](https://reviewable.io/reviews/grpc/grpc/15780#-LF2umhlAbxtXODoQlUj:-LF3Y_TJ55DxfQsCvc32:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1679f959125f0f88c70f81b6f2743e132546350d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L26)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like these three includes are actually needed.
</blockquote></details>

Done.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 83 at r1](https://reviewable.io/reviews/grpc/grpc/15780#-LF2uWWP0OWq8S88abWe:-LF3YaXgESSoKwk-lEdM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1679f959125f0f88c70f81b6f2743e132546350d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since there will be only one implementation of these functions built on any given platform, I don't think we need `ForCurrentPlatform` as part of their names.
</blockquote></details>

Done.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 43 at r1](https://reviewable.io/reviews/grpc/grpc/15780#-LF2uuQM4MR8bJd9z79P:-LF3YbgV-MsJMcUoITcu:balicwg) ([raw file](https://github.com/grpc/grpc/blob/1679f959125f0f88c70f81b6f2743e132546350d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L43)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of passing in the read and write closures and requiring that the caller use the same ones each time, how about instead just having the caller pass the closure to `RegisterForOnReadableLocked()` and `RegisterForOnWriteableLocked()`?
</blockquote></details>

Done. Yeah, I originally did this because on Windows, the read and write closures won't be simply passed through and will need to be saved somewhere for later, but I think it makes sense to accommodate that only on Windows, where it's needed.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/15780#-LF2sr-FEzfyvWhD4dmb:-LF3Z8LO-k2N0e4gS0Bc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1679f959125f0f88c70f81b6f2743e132546350d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

For the fields that we're initializing via simple assignments, we can do that via an initializer list instead of doing it in the body.
</blockquote></details>

Done.

---

*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc, line 78 at r1](https://reviewable.io/reviews/grpc/grpc/15780#-LF2vDEZCuaEh0kwQJsO:-LF3Z9AY6inCee3Cg5qT:b-wau7w9) ([raw file](https://github.com/grpc/grpc/blob/1679f959125f0f88c70f81b6f2743e132546350d/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix.cc#L78)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't we still want to check that we have not previously been shut down, like the current implementation does?
</blockquote></details>

The check is still there in `grpc_ares_ev_driver.cc` (within the `fd_node_shutdown_locked` function).

I tried to make this "called once and only once" invariant a part of `GrpcPolledFd::ShutdownLocked` API, but on the other hand this PR does add some indirection around this.... what do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15780)*

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
squashing down

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                                            ++++++++++++++
  +0.9% +6.15Ki [None]                                                                             +32.7Ki  +0.4%
      +0.9% +6.04Ki [Unmapped]                                                                         +32.6Ki  +0.4%
      [NEW]     +80 vtable for grpc_core::GrpcPolledFdPosix                                                +80  [NEW]
      +3.0%     +32 [None]                                                                                   0  [ = ]
  [NEW] +2.19Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc     +2.19Ki  [NEW]
      [NEW] +1.03Ki grpc_ares_notify_on_event_locked                                                   +1.03Ki  [NEW]
      [NEW]    +368 grpc_ares_ev_driver_create_locked                                                     +368  [NEW]
      [NEW]    +171 grpc_ares_ev_driver_unref                                                             +171  [NEW]
      [NEW]    +159 on_readable_locked                                                                    +159  [NEW]
      [NEW]    +139 on_writable_locked                                                                    +139  [NEW]
      [NEW]    +128 fd_node_shutdown_locked(fd_node*, char const*) [clone .isra.1] [clone .part.2]        +128  [NEW]
      [NEW]     +79 grpc_ares_ev_driver_shutdown_locked                                                    +79  [NEW]
      [NEW]     +49 [Unmapped]                                                                             +49  [NEW]
      [NEW]     +49 grpc_ares_ev_driver_ref                                                                +49  [NEW]
      [NEW]     +25 grpc_ares_ev_driver_start_locked                                                       +25  [NEW]
      [NEW]      +9 grpc_ares_ev_driver_destroy_locked                                                      +9  [NEW]
      [NEW]      +9 grpc_core::GrpcPolledFd::~GrpcPolledFd                                                  +9  [NEW]
      [NEW]      +4 grpc_ares_ev_driver_get_channel_locked                                                  +4  [NEW]
      [NEW]      +2 grpc_core::GrpcPolledFd::~GrpcPolledFd                                                  +2  [NEW]

 -------------- SHRINKING                                                                          --------------
 -84.7% -1.93Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posix. -1.93Ki -84.7%
      [DEL] -1.05Ki grpc_ares_notify_on_event_locked                                                   -1.05Ki  [DEL]
      [DEL]    -368 grpc_ares_ev_driver_create_locked                                                     -368  [DEL]
      [DEL]    -210 on_readable_locked                                                                    -210  [DEL]
      [DEL]    -171 grpc_ares_ev_driver_unref                                                             -171  [DEL]
      [DEL]    -131 on_writable_locked                                                                    -131  [DEL]
      [DEL]    -116 fd_node_shutdown_locked(fd_node*, char const*) [clone .isra.1] [clone .part.2]        -116  [DEL]
     -87.0%     -80 [Unmapped]                                                                             -80 -87.0%
      [DEL]     -79 grpc_ares_ev_driver_shutdown_locked                                                    -79  [DEL]
      [DEL]     -49 grpc_ares_ev_driver_ref                                                                -49  [DEL]
      [DEL]     -25 grpc_ares_ev_driver_start_locked                                                       -25  [DEL]
      [DEL]      -9 grpc_ares_ev_driver_destroy_locked                                                      -9  [DEL]
      [DEL]      -4 grpc_ares_ev_driver_get_channel_locked                                                  -4  [DEL]

  +0.5% +6.41Ki TOTAL                                                                              +33.0Ki  +0.4%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
