### PR TITLE
Pass repo manager duty to nicolasnoble.

### PR DESCRIPTION
**Pull request by markdroth**
I won't merge this until Monday.

### CODE REVIEW

**Comment by JScon01** [comment]
Please stop sending me these Emails!

Jeffrey H. Conz

**Comment by markdroth** [comment]
@JScon01 You probably accidentally subscribed to notifications for the grpc repo on github.  You should be able to use the github UI to unsubscribe yourself.

**Comment by JScon01** [comment]
I’ve unsubscribed, but I did not subscribe to this programming ring.

Jeffrey H. Conz

**Comment by markdroth** [comment]
@JScon01 I didn't do anything to subscribe you, so I'm not sure how that happened.  But hopefully you've found a way to fix it.

**Comment by JScon01** [comment]
I’ve unsubscribed, what else do I need to do?

Jeffrey H. Conz

**Review by nicolasnoble — APPROVED** [review]

**Pull request merged**
