### PR TITLE
Fix crashing server_builder_test

### PR DESCRIPTION
**Pull request by ara-ayvazyan**
In the [server_builder_test.cc](https://github.com/ara-ayvazyan/grpc/blob/master/test/cpp/server/server_builder_test.cc) there is an initialization ordering issue between `GetPort()` that relies on `g_alloc_functions` which is also initialized globally.

### CODE REVIEW

**Comment by ara-ayvazyan** [comment]
The issue is in the following line: `grpc::string g_port = MakePort();`

The `MakePort()` function indirectly uses `g_alloc_functions` in order to allocate memory. Since the `g_alloc_functions` and `g_port` both are global objects in different translation units, the order in which they are initialized is undefined. The result is a memory access violation inside `MakePort` when it tries to calling to malloc function pointer which is nullptr (not yet initialized).

**Comment by sreecha** [comment]
Thank you!

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Sanity check fails because of bad formatting:
```
++ dirname tools/distrib/clang_format_code.sh
+ cd tools/distrib/../..
++ pwd
+ REPO_ROOT=/var/local/git/grpc
+ '[' true == '' ']'
+ CLANG_FORMAT_ROOT=/var/local/git/grpc
+ tools/dockerfile/grpc_clang_format/clang_format_all_the_things.sh
--- /var/local/git/grpc/test/cpp/server/server_builder_test.cc	2018-04-03 09:38:36.700233232 +0000
+++ /tmp/tmp.CV59b86sBY	2018-04-03 09:39:58.120233232 +0000
@@ -40,8 +40,8 @@
 }
 
 const grpc::string& GetPort() {
-    static grpc::string g_port = MakePort();
-    return g_port;
+  static grpc::string g_port = MakePort();
+  return g_port;
 }
 
 TEST(ServerBuilderTest, NoOp) { ServerBuilder b; }
```

**Pull request merged**
