### PR TITLE
Change trace logging to use GPR_INFO instead of GPR_DEBUG.

### PR DESCRIPTION
**Pull request by markdroth**
This will allow us to enable tracers internally in non-debug builds.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%      +9 [None]                                                                               +2.78Ki  +0.0%
  +0.9%    +296 src/core/ext/filters/client_channel/client_channel.cc                                   +296  +0.9%
       +13%     +50 [Unmapped]                                                                               +50   +13%
      +1.8%     +48 on_complete                                                                              +48  +1.8%
      +1.8%     +28 maybe_retry                                                                              +28  +1.8%
      +2.1%     +28 cc_start_transport_stream_op_batch                                                       +28  +2.1%
       +11%     +24 retry_commit                                                                             +24   +11%
      +1.1%     +18 [Other]                                                                                  +18  +1.1%
      +1.7%     +16 pick_callback_start_locked                                                               +16  +1.7%
      +3.2%     +11 recv_message_ready                                                                       +11  +3.2%
      +2.4%     +11 execute_closures_in_call_combiner(grpc_call_element*, char const*, closure_to_execut     +11  +2.4%
      +1.4%     +11 pick_after_resolver_result_done_locked                                                   +11  +1.4%
      +1.4%      +8 pending_batches_fail                                                                      +8  +1.4%
      +4.1%      +8 request_reresolution_locked                                                               +8  +4.1%
      +0.2%      +8 on_resolver_result_changed_locked                                                         +8  +0.2%
      +0.2%      +6 start_retriable_subchannel_batches                                                        +6  +0.2%
      +2.1%      +3 start_resolving_locked                                                                    +3  +2.1%
      +2.8%      +3 free_cached_send_message                                                                  +3  +2.8%
      +1.4%      +3 maybe_clear_pending_batch(grpc_call_element*, pending_batch*) [clone .isra.4]             +3  +1.4%
      +3.1%      +3 pick_callback_done_locked                                                                 +3  +3.1%
      +1.9%      +3 pick_callback_cancel_locked                                                               +3  +1.9%
      +0.9%      +3 recv_initial_metadata_ready                                                               +3  +0.9%
      +0.8%      +3 invoke_recv_message_callback                                                              +3  +0.8%
  +0.3%    +142 [Other]                                                                                 +142  +0.3%
  +0.9%    +112 src/core/ext/transport/inproc/inproc_transport.cc                                       +112  +0.9%
      +1.4%     +41 op_state_machine                                                                         +41  +1.4%
      +2.1%     +19 init_stream                                                                              +19  +2.1%
      +0.9%     +19 perform_stream_op                                                                        +19  +0.9%
      +0.6%      +8 fail_helper_locked                                                                        +8  +0.6%
      +1.3%      +8 message_transfer_locked                                                                   +8  +1.3%
      +0.5%      +3 grpc_inproc_channel_create                                                                +3  +0.5%
      +4.7%      +3 ref_stream                                                                                +3  +4.7%
      +4.7%      +3 unref_stream                                                                              +3  +4.7%
      +5.2%      +3 ref_transport                                                                             +3  +5.2%
      +1.6%      +3 unref_transport                                                                           +3  +1.6%
      +3.3%      +3 destroy_transport                                                                         +3  +3.3%
      +1.3%      +3 perform_transport_op                                                                      +3  +1.3%
      +0.9%      +3 close_transport_locked                                                                    +3  +0.9%
  +1.0%    +112 src/core/lib/iomgr/ev_epollex_linux.cc                                                  +112  +1.0%
      +1.1%     +22 pollset_work                                                                             +22  +1.1%
      +6.1%     +19 [Unmapped]                                                                               +19  +6.1%
      +1.9%     +16 pollset_set_add_pollset                                                                  +16  +1.9%
      +1.4%     +11 pollset_set_add_pollset_set                                                              +11  +1.4%
      +2.8%      +8 pollable_add_fd                                                                           +8  +2.8%
      +1.2%      +8 pollable_process_events                                                                   +8  +1.2%
      +6.2%      +8 pollset_maybe_finish_shutdown                                                             +8  +6.2%
      +2.7%      +8 pollset_transition_pollable_from_fd_to_multi_locked                                       +8  +2.7%
      +0.7%      +3 pollset_kick                                                                              +3  +0.7%
      +0.5%      +3 kick_one_worker                                                                           +3  +0.5%
      +1.2%      +3 pollset_set_del_fd                                                                        +3  +1.2%
      +1.1%      +3 pollset_set_del_pollset                                                                   +3  +1.1%
  +1.3%     +96 src/core/lib/iomgr/tcp_posix.cc                                                          +96  +1.3%
      +4.6%     +25 notify_on_write                                                                          +25  +4.6%
      +5.2%     +19 tcp_drop_uncovered_then_handle_write                                                     +19  +5.2%
      +2.5%     +16 tcp_handle_read                                                                          +16  +2.5%
      +2.0%     +11 run_poller                                                                               +11  +2.0%
      +1.0%      +6 tcp_write                                                                                 +6  +1.0%
      +2.3%      +4 [Unmapped]                                                                                +4  +2.3%
      +4.5%      +3 done_poller                                                                               +3  +4.5%
      +0.8%      +3 call_read_cb                                                                              +3  +0.8%
      +2.2%      +3 drop_uncovered((anonymous namespace)::grpc_tcp*) [clone .isra.4]                          +3  +2.2%
      +2.9%      +3 notify_on_read                                                                            +3  +2.9%
      +2.0%      +3 tcp_read_allocation_done                                                                  +3  +2.0%
  +0.8%     +80 src/core/lib/iomgr/ev_epoll1_linux.cc                                                    +80  +0.8%
      +1.7%     +40 pollset_kick                                                                             +40  +1.7%
      +1.1%     +38 pollset_work                                                                             +38  +1.1%
      +0.7%      +2 [Unmapped]                                                                                +2  +0.7%
  +2.9%     +51 src/core/lib/iomgr/call_combiner.cc                                                      +51  +2.9%
      +5.5%     +27 grpc_call_combiner_stop                                                                  +27  +5.5%
       +29%     +12 [Unmapped]                                                                               +12   +29%
      +2.2%      +9 grpc_call_combiner_set_notify_on_cancel                                                   +9  +2.2%
      +1.0%      +3 grpc_call_combiner_cancel                                                                 +3  +1.0%
  +1.5%     +51 src/core/lib/iomgr/tcp_custom.cc                                                         +51  +1.5%
       +10%     +24 tcp_read_allocation_done                                                                 +24   +10%
      +6.5%     +10 [Unmapped]                                                                               +10  +6.5%
      +2.3%      +8 custom_write_callback                                                                     +8  +2.3%
      +0.7%      +3 custom_tcp_endpoint_create                                                                +3  +0.7%
      +0.8%      +3 call_read_cb                                                                              +3  +0.8%
      +2.3%      +3 endpoint_shutdown                                                                         +3  +2.3%
  +0.7%     +48 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +48  +0.7%
      +1.1%     +24 grpc_core::(anonymous namespace)::RoundRobin::OnConnectivityChangedLocked                +24  +1.1%
      +4.7%     +19 grpc_core::(anonymous namespace)::RoundRobin::PickLocked                                 +19  +4.7%
      +1.7%      +8 grpc_core::(anonymous namespace)::RoundRobin::GetNextReadySubchannelIndexLocked           +8  +1.7%
      +5.8%      +8 grpc_core::(anonymous namespace)::RoundRobin::UpdateLastReadySubchannelIndexLocked        +8  +5.8%
      +0.4%      +3 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                                +3  +0.4%
      +0.7%      +3 grpc_core::(anonymous namespace)::RoundRobin::ShutdownLocked                              +3  +0.7%
  +0.1%     +48 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                              +48  +0.1%
      +4.3%     +11 start_bdp_ping_locked                                                                    +11  +4.3%
      +1.3%      +9 [Unmapped]                                                                                +9  +1.3%
      +2.4%      +8 perform_stream_op                                                                         +8  +2.4%
      +1.2%      +8 maybe_start_some_streams                                                                  +8  +1.2%
      +3.2%      +3 connectivity_state_set                                                                    +3  +3.2%
      +0.8%      +3 benign_reclaimer_locked                                                                   +3  +0.8%
      +1.6%      +3 schedule_bdp_ping_locked                                                                  +3  +1.6%
      +0.9%      +3 destructive_reclaimer_locked                                                              +3  +0.9%
  +1.8%     +48 src/core/lib/iomgr/combiner.cc                                                           +48  +1.8%
      +1.6%     +16 grpc_combiner_continue_exec_ctx                                                          +16  +1.6%
      +9.4%     +16 queue_offload                                                                            +16  +9.4%
      +7.6%      +7 [Unmapped]                                                                                +7  +7.6%
      +2.6%      +3 grpc_combiner_unref                                                                       +3  +2.6%
      +1.7%      +3 grpc_combiner_create                                                                      +3  +1.7%
      +2.3%      +3 really_destroy                                                                            +3  +2.3%
  +2.3%     +40 src/core/lib/transport/connectivity_state.cc                                             +40  +2.3%
      +4.5%     +24 grpc_connectivity_state_set                                                              +24  +4.5%
      +1.6%      +8 grpc_connectivity_state_notify_on_state_change                                            +8  +1.6%
      +2.8%      +3 grpc_connectivity_state_get                                                               +3  +2.8%
      +3.6%      +3 grpc_connectivity_state_check                                                             +3  +3.6%
      +4.7%      +2 [Unmapped]                                                                                +2  +4.7%
  +0.9%     +32 src/core/lib/iomgr/executor.cc                                                           +32  +0.9%
      +3.9%     +27 executor_thread                                                                          +27  +3.9%
      +1.8%      +3 run_closures(grpc_closure_list) [clone .isra.4]                                           +3  +1.8%
      +0.2%      +3 executor_push                                                                             +3  +0.2%
  +0.5%     +32 src/core/lib/iomgr/resource_quota.cc                                                     +32  +0.5%
      +2.4%     +30 rq_step                                                                                  +30  +2.4%
      +1.4%      +3 grpc_resource_user_free                                                                   +3  +1.4%
  +0.7%     +32 src/core/lib/iomgr/timer_generic.cc                                                      +32  +0.7%
      +1.6%     +21 run_some_expired_timers(long, long*, grpc_error*) [clone .part.3]                        +21  +1.6%
      +2.2%     +16 timer_check                                                                              +16  +2.2%
      +0.8%      +8 timer_init                                                                                +8  +0.8%
  +0.9%     +19 src/core/ext/filters/client_channel/lb_policy/subchannel_list.cc                         +19  +0.9%
      +1.2%     +11 grpc_lb_subchannel_list_create                                                           +11  +1.2%
      +3.2%      +8 grpc_lb_subchannel_list_unref                                                             +8  +3.2%
      +3.4%      +3 grpc_lb_subchannel_list_ref                                                               +3  +3.4%
      +0.8%      +3 grpc_lb_subchannel_list_shutdown_and_unref                                                +3  +0.8%
      +2.0%      +3 grpc_lb_subchannel_data_stop_connectivity_watch                                           +3  +2.0%
      +2.1%      +3 grpc_lb_subchannel_data_start_connectivity_watch                                          +3  +2.1%
  +0.5%     +16 src/core/ext/filters/http/message_compress/message_compress_filter.cc                    +16  +0.5%
      +2.2%     +16 finish_send_message                                                                      +16  +2.2%
  +0.7%     +16 src/core/ext/transport/chttp2/transport/frame_settings.cc                                +16  +0.7%
      +1.3%     +16 grpc_chttp2_settings_parser_parse                                                        +16  +1.3%
  +0.2%     +16 src/core/ext/transport/chttp2/transport/hpack_encoder.cc                                 +16  +0.2%
      +6.9%      +8 [Unmapped]                                                                                +8  +6.9%
      +4.0%      +8 grpc_chttp2_hpack_compressor_set_max_table_size                                           +8  +4.0%
  +0.7%     +16 src/core/ext/transport/chttp2/transport/hpack_table.cc                                   +16  +0.7%
      +2.3%      +8 grpc_chttp2_hptbl_set_current_table_size                                                  +8  +2.3%
      +9.4%      +5 [Unmapped]                                                                                +5  +9.4%
      +3.1%      +3 grpc_chttp2_hptbl_set_max_bytes                                                           +3  +3.1%

  +0.1% +1.28Ki TOTAL                                                                                +4.05Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%      +9 [None]                                                                               +2.78Ki  +0.0%
  +0.9%    +296 src/core/ext/filters/client_channel/client_channel.cc                                   +296  +0.9%
       +13%     +50 [Unmapped]                                                                               +50   +13%
      +1.8%     +48 on_complete                                                                              +48  +1.8%
      +1.8%     +28 maybe_retry                                                                              +28  +1.8%
      +2.1%     +28 cc_start_transport_stream_op_batch                                                       +28  +2.1%
       +11%     +24 retry_commit                                                                             +24   +11%
      +1.1%     +18 [Other]                                                                                  +18  +1.1%
      +1.7%     +16 pick_callback_start_locked                                                               +16  +1.7%
      +3.2%     +11 recv_message_ready                                                                       +11  +3.2%
      +2.4%     +11 execute_closures_in_call_combiner(grpc_call_element*, char const*, closure_to_execut     +11  +2.4%
      +1.4%     +11 pick_after_resolver_result_done_locked                                                   +11  +1.4%
      +1.4%      +8 pending_batches_fail                                                                      +8  +1.4%
      +4.1%      +8 request_reresolution_locked                                                               +8  +4.1%
      +0.2%      +8 on_resolver_result_changed_locked                                                         +8  +0.2%
      +0.2%      +6 start_retriable_subchannel_batches                                                        +6  +0.2%
      +2.1%      +3 start_resolving_locked                                                                    +3  +2.1%
      +2.8%      +3 free_cached_send_message                                                                  +3  +2.8%
      +1.4%      +3 maybe_clear_pending_batch(grpc_call_element*, pending_batch*) [clone .isra.4]             +3  +1.4%
      +3.1%      +3 pick_callback_done_locked                                                                 +3  +3.1%
      +1.9%      +3 pick_callback_cancel_locked                                                               +3  +1.9%
      +0.9%      +3 recv_initial_metadata_ready                                                               +3  +0.9%
      +0.8%      +3 invoke_recv_message_callback                                                              +3  +0.8%
  +0.3%    +142 [Other]                                                                                 +142  +0.3%
  +0.9%    +112 src/core/ext/transport/inproc/inproc_transport.cc                                       +112  +0.9%
      +1.4%     +41 op_state_machine                                                                         +41  +1.4%
      +2.1%     +19 init_stream                                                                              +19  +2.1%
      +0.9%     +19 perform_stream_op                                                                        +19  +0.9%
      +0.6%      +8 fail_helper_locked                                                                        +8  +0.6%
      +1.3%      +8 message_transfer_locked                                                                   +8  +1.3%
      +0.5%      +3 grpc_inproc_channel_create                                                                +3  +0.5%
      +4.7%      +3 ref_stream                                                                                +3  +4.7%
      +4.7%      +3 unref_stream                                                                              +3  +4.7%
      +5.2%      +3 ref_transport                                                                             +3  +5.2%
      +1.6%      +3 unref_transport                                                                           +3  +1.6%
      +3.3%      +3 destroy_transport                                                                         +3  +3.3%
      +1.3%      +3 perform_transport_op                                                                      +3  +1.3%
      +0.9%      +3 close_transport_locked                                                                    +3  +0.9%
  +1.0%    +112 src/core/lib/iomgr/ev_epollex_linux.cc                                                  +112  +1.0%
      +1.1%     +22 pollset_work                                                                             +22  +1.1%
      +6.1%     +19 [Unmapped]                                                                               +19  +6.1%
      +1.9%     +16 pollset_set_add_pollset                                                                  +16  +1.9%
      +1.4%     +11 pollset_set_add_pollset_set                                                              +11  +1.4%
      +2.8%      +8 pollable_add_fd                                                                           +8  +2.8%
      +1.2%      +8 pollable_process_events                                                                   +8  +1.2%
      +6.2%      +8 pollset_maybe_finish_shutdown                                                             +8  +6.2%
      +2.7%      +8 pollset_transition_pollable_from_fd_to_multi_locked                                       +8  +2.7%
      +0.7%      +3 pollset_kick                                                                              +3  +0.7%
      +0.5%      +3 kick_one_worker                                                                           +3  +0.5%
      +1.2%      +3 pollset_set_del_fd                                                                        +3  +1.2%
      +1.1%      +3 pollset_set_del_pollset                                                                   +3  +1.1%
  +1.3%     +96 src/core/lib/iomgr/tcp_posix.cc                                                          +96  +1.3%
      +4.6%     +25 notify_on_write                                                                          +25  +4.6%
      +5.2%     +19 tcp_drop_uncovered_then_handle_write                                                     +19  +5.2%
      +2.5%     +16 tcp_handle_read                                                                          +16  +2.5%
      +2.0%     +11 run_poller                                                                               +11  +2.0%
      +1.0%      +6 tcp_write                                                                                 +6  +1.0%
      +2.3%      +4 [Unmapped]                                                                                +4  +2.3%
      +4.5%      +3 done_poller                                                                               +3  +4.5%
      +0.8%      +3 call_read_cb                                                                              +3  +0.8%
      +2.2%      +3 drop_uncovered((anonymous namespace)::grpc_tcp*) [clone .isra.4]                          +3  +2.2%
      +2.9%      +3 notify_on_read                                                                            +3  +2.9%
      +2.0%      +3 tcp_read_allocation_done                                                                  +3  +2.0%
  +0.8%     +80 src/core/lib/iomgr/ev_epoll1_linux.cc                                                    +80  +0.8%
      +1.7%     +40 pollset_kick                                                                             +40  +1.7%
      +1.1%     +38 pollset_work                                                                             +38  +1.1%
      +0.7%      +2 [Unmapped]                                                                                +2  +0.7%
  +2.9%     +51 src/core/lib/iomgr/call_combiner.cc                                                      +51  +2.9%
      +5.5%     +27 grpc_call_combiner_stop                                                                  +27  +5.5%
       +29%     +12 [Unmapped]                                                                               +12   +29%
      +2.2%      +9 grpc_call_combiner_set_notify_on_cancel                                                   +9  +2.2%
      +1.0%      +3 grpc_call_combiner_cancel                                                                 +3  +1.0%
  +1.5%     +51 src/core/lib/iomgr/tcp_custom.cc                                                         +51  +1.5%
       +10%     +24 tcp_read_allocation_done                                                                 +24   +10%
      +6.5%     +10 [Unmapped]                                                                               +10  +6.5%
      +2.3%      +8 custom_write_callback                                                                     +8  +2.3%
      +0.7%      +3 custom_tcp_endpoint_create                                                                +3  +0.7%
      +0.8%      +3 call_read_cb                                                                              +3  +0.8%
      +2.3%      +3 endpoint_shutdown                                                                         +3  +2.3%
  +0.7%     +48 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 +48  +0.7%
      +1.1%     +24 grpc_core::(anonymous namespace)::RoundRobin::OnConnectivityChangedLocked                +24  +1.1%
      +4.7%     +19 grpc_core::(anonymous namespace)::RoundRobin::PickLocked                                 +19  +4.7%
      +1.7%      +8 grpc_core::(anonymous namespace)::RoundRobin::GetNextReadySubchannelIndexLocked           +8  +1.7%
      +5.8%      +8 grpc_core::(anonymous namespace)::RoundRobin::UpdateLastReadySubchannelIndexLocked        +8  +5.8%
      +0.4%      +3 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                                +3  +0.4%
      +0.7%      +3 grpc_core::(anonymous namespace)::RoundRobin::ShutdownLocked                              +3  +0.7%
  +0.1%     +48 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                              +48  +0.1%
      +4.3%     +11 start_bdp_ping_locked                                                                    +11  +4.3%
      +1.3%      +9 [Unmapped]                                                                                +9  +1.3%
      +2.4%      +8 perform_stream_op                                                                         +8  +2.4%
      +1.2%      +8 maybe_start_some_streams                                                                  +8  +1.2%
      +3.2%      +3 connectivity_state_set                                                                    +3  +3.2%
      +0.8%      +3 benign_reclaimer_locked                                                                   +3  +0.8%
      +1.6%      +3 schedule_bdp_ping_locked                                                                  +3  +1.6%
      +0.9%      +3 destructive_reclaimer_locked                                                              +3  +0.9%
  +1.8%     +48 src/core/lib/iomgr/combiner.cc                                                           +48  +1.8%
      +1.6%     +16 grpc_combiner_continue_exec_ctx                                                          +16  +1.6%
      +9.4%     +16 queue_offload                                                                            +16  +9.4%
      +7.6%      +7 [Unmapped]                                                                                +7  +7.6%
      +2.6%      +3 grpc_combiner_unref                                                                       +3  +2.6%
      +1.7%      +3 grpc_combiner_create                                                                      +3  +1.7%
      +2.3%      +3 really_destroy                                                                            +3  +2.3%
  +2.3%     +40 src/core/lib/transport/connectivity_state.cc                                             +40  +2.3%
      +4.5%     +24 grpc_connectivity_state_set                                                              +24  +4.5%
      +1.6%      +8 grpc_connectivity_state_notify_on_state_change                                            +8  +1.6%
      +2.8%      +3 grpc_connectivity_state_get                                                               +3  +2.8%
      +3.6%      +3 grpc_connectivity_state_check                                                             +3  +3.6%
      +4.7%      +2 [Unmapped]                                                                                +2  +4.7%
  +0.9%     +32 src/core/lib/iomgr/executor.cc                                                           +32  +0.9%
      +3.9%     +27 executor_thread                                                                          +27  +3.9%
      +1.8%      +3 run_closures(grpc_closure_list) [clone .isra.4]                                           +3  +1.8%
      +0.2%      +3 executor_push                                                                             +3  +0.2%
  +0.5%     +32 src/core/lib/iomgr/resource_quota.cc                                                     +32  +0.5%
      +2.4%     +30 rq_step                                                                                  +30  +2.4%
      +1.4%      +3 grpc_resource_user_free                                                                   +3  +1.4%
  +0.7%     +32 src/core/lib/iomgr/timer_generic.cc                                                      +32  +0.7%
      +1.6%     +21 run_some_expired_timers(long, long*, grpc_error*) [clone .part.3]                        +21  +1.6%
      +2.2%     +16 timer_check                                                                              +16  +2.2%
      +0.8%      +8 timer_init                                                                                +8  +0.8%
  +0.9%     +19 src/core/ext/filters/client_channel/lb_policy/subchannel_list.cc                         +19  +0.9%
      +1.2%     +11 grpc_lb_subchannel_list_create                                                           +11  +1.2%
      +3.2%      +8 grpc_lb_subchannel_list_unref                                                             +8  +3.2%
      +3.4%      +3 grpc_lb_subchannel_list_ref                                                               +3  +3.4%
      +0.8%      +3 grpc_lb_subchannel_list_shutdown_and_unref                                                +3  +0.8%
      +2.0%      +3 grpc_lb_subchannel_data_stop_connectivity_watch                                           +3  +2.0%
      +2.1%      +3 grpc_lb_subchannel_data_start_connectivity_watch                                          +3  +2.1%
  +0.5%     +16 src/core/ext/filters/http/message_compress/message_compress_filter.cc                    +16  +0.5%
      +2.2%     +16 finish_send_message                                                                      +16  +2.2%
  +0.7%     +16 src/core/ext/transport/chttp2/transport/frame_settings.cc                                +16  +0.7%
      +1.3%     +16 grpc_chttp2_settings_parser_parse                                                        +16  +1.3%
  +0.2%     +16 src/core/ext/transport/chttp2/transport/hpack_encoder.cc                                 +16  +0.2%
      +6.9%      +8 [Unmapped]                                                                                +8  +6.9%
      +4.0%      +8 grpc_chttp2_hpack_compressor_set_max_table_size                                           +8  +4.0%
  +0.7%     +16 src/core/ext/transport/chttp2/transport/hpack_table.cc                                   +16  +0.7%
      +2.3%      +8 grpc_chttp2_hptbl_set_current_table_size                                                  +8  +2.3%
      +9.4%      +5 [Unmapped]                                                                                +5  +9.4%
      +3.1%      +3 grpc_chttp2_hptbl_set_max_bytes                                                           +3  +3.1%

  +0.1% +1.28Ki TOTAL                                                                                +4.05Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                    cpu_time    real_time
---------------------------  ----------  -----------
BM_MetadataRefUnrefExternal  -33%        -33%
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: #15199 #14240 #15029

**Pull request merged**
