### PR TITLE
Revert "Introduce C++ wrappers for gpr_mu and gpr_cv."

### PR DESCRIPTION
**Pull request by apolcyn**
This reverts commit a26c09dd258a0d4dc3023e874b13f92e29174a43.

### CODE REVIEW

**Comment by apolcyn** [comment]
Should I shelf this PR? Not completely sure about the status of the fix forward

**Comment by soheilhy** [comment]
@apolcyn yes, please go ahead. 

Verdict is that the root cause is not this PR, but it's the first time we are using `gpr_mu` in gprpp codegen it's surfacing a latent build issue that causes a serious stackoverflow. Until we get that fixed, we shouldn't proceed with rolling this forward.

**Comment by apolcyn** [comment]
SG. will merge then

**Comment by apolcyn** [comment]
windows: https://github.com/grpc/grpc/issues/18637, https://github.com/grpc/grpc/issues/18126
interop: https://github.com/grpc/grpc/issues/18431

**Pull request merged**
