### PR TITLE
Implement AppNet GrpcRoute -> Router References and Scope in Interop Test

### PR DESCRIPTION
**Pull request by gnossen**
[Tested](http://sponge2/15e8b5f2-cc0c-4367-92e1-95c6bc472080)

This PR is dependent on [this bootstrap generator PR](https://github.com/GoogleCloudPlatform/traffic-director-grpc-bootstrap/pull/22).

### CODE REVIEW

**Review by sergiitk — APPROVED** [review]
This looks great!

I'm approving it, but, unfortunately, we have no CI to confirm other intop tests work fine, yet.
May I ask you to manually run PSM Security, and URL Map tests?

**Comment by gnossen** [comment]
Manual test runs (in progress):
 - https://fusion2.corp.google.com/invocations/c3dcf22c-9f10-40c4-8ed2-76926bd659ba (Security)
 - https://fusion2.corp.google.com/invocations/6a82a7b4-818b-4f55-811d-f6a3cd8c8174 (URL Map)

**Comment by gnossen** [comment]
Superceded by https://github.com/grpc/grpc/pull/27378

**Comment by sergiitk** [comment]
I think you meant  https://github.com/grpc/grpc/pull/27874.

**Comment by gnossen** [comment]
Indeed. Fixed.

**Pull request closed without merging**
