### PR TITLE
Upmerge "fix cares resolution with default authority" to master

### PR DESCRIPTION
**Pull request by jtattermusch**
Upmerge https://github.com/grpc/grpc/pull/15073 from v1.11.x

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by mehrdada** [comment]
Actually, let's close this and upmerge the entire 1.11.x branch. I'll make an upmerge PR.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
