### PR TITLE
clang-format the examples/cpp directory

### PR DESCRIPTION
**Pull request by vjpai**
Add the examples/cpp directory to the clang-format consistency check to make sure that the code looks right. Realized that this looks odd when I was working on some examples.

### CODE REVIEW

**Review by jtattermusch — APPROVED** [review]
Approving to grant OWNERS approval. 

I think @veblush  is the best person to review the actual changes since he dealt with lots of c++ cleanup recently.

**Comment by vjpai** [comment]
@jtattermusch Thanks for the review! Yes, I've assigned @veblush as the code reviewer for that reason.

**Review by veblush — APPROVED** [review]
LGTM! Thank you for the clean-up!

**Comment by tonysongzheng** [comment]
GPR_ASSERT(ok);  ok is false when called quickly. why?

**Pull request merged**
