### PR TITLE
Fix saving results to BigQuery from Kokoro in OSS benchmarks.

### PR DESCRIPTION
**Pull request by paulosjca**

### CODE REVIEW

**Review by jtattermusch — APPROVED** [review]
LGTM.

**Comment by jtattermusch** [comment]
Test failures are unrelated to this PR.

**Comment by jtattermusch** [comment]
I looked at the results of one of the loadtest's driver pods (`kubectl logs kokoro-test-11a06a5a-ba14-58a8-adb6-12c74695bbf7-driver-549b38ae-3c1e-422d-9d93-80972fe58ba9` and it showed "Completed" without showing any failure trying to upload to bigquery.

Can please you confirm these:
- the error didn't show up since the `spec.results.bigQueryTable` was originally misplaced and thus no attempt was made to upload the test results (and that's why I can't see any upload attempt in the driver's kubectl logs).
- if `spec.results.bigQueryTable` was actually set to point to a malformed dataset/table name, that would have triggered and error when trying to upload to bigquery (and it would have shown up in the driver's logs).

If the answer is yes to both of the above, I think that's a fair behavior.

**Comment by paulosjca** [comment]
Yes to both.

**Pull request merged**
