### PR TITLE
remove confusing generating code section

### PR DESCRIPTION
**Pull request by LisaFC**
Fixes https://github.com/grpc/grpc/issues/5559

### CODE REVIEW

**Comment by stanley-cheung** [comment]
@LisaFC did you get a chance to sign that CLA?

**Comment by LisaFC** [comment]
I shouldn't have to as a Googler as per the Open Source docs as I'm covered by the company CLA - I think the problem is that I managed to set my email address to private in my Github settings and because I made this change in the browser it went in as: From: LisaFC <LisaFC@users.noreply.github.com>

I've unset the email privacy, so should I just abandon this change and do it again?

**Comment by stanley-cheung** [comment]
Yea I have seen this before. Usually the solution is to make sure you use that email address when you make the git commit (make sure you run that `git config --global user.email <email>` command before you make commit. And then make the PR again.

**Comment by LisaFC** [comment]
Done! Also annoyingly, I think I accidentally branched this in the main repo rather than my own fork so I can't delete it - can you delete the LisaFC-fixREADME branch? Thanks.

**Comment by LisaFC** [comment]
Turns out I can, in fact, delete it. :)

**Pull request closed without merging**
