### PR TITLE
Fix math client

### PR DESCRIPTION
**Pull request by ganmacs**
I fixed some points because src/ruby/bin/math_client.rb does not work.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @ganmacs isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by ganmacs** [comment]
CLA signed.

**Comment by apolcyn** [comment]
LGTM, and thanks. But can you please squash these four commits down into one before merging?

**Comment by ganmacs** [comment]
Thanks 😄

**Pull request merged**
