### PR TITLE
Adding support to enable tracing in tsi.

### PR DESCRIPTION
**Pull request by jboeuf**

### CODE REVIEW

**Comment by ctiller** [comment]
I want to get Travis sorted out completely before merging this.

**Comment by nicolasnoble** [comment]
I think Travis is now sorted out enough so we should be able to merge this - if @jboeuf would be kind enough to pull from master in order to update this PR.

**Comment by ctiller** [comment]
I'd actually put Ruby being up as the threshold for things being
operational enough to start taking C core changes.

**Comment by ctiller** [comment]
(I realize the likelyhood of this change breaking things is low, but I want
to be consistent here)

**Comment by nicolasnoble** [comment]
Hm, fair enough.

**Comment by jboeuf** [comment]
I pulled from master and travis is happy now...

**Comment by ctiller** [comment]
Can you merge head once more and push: tests are to where I'm happy with them now.

**Comment by jboeuf** [comment]
Done.

**Pull request merged**
