### PR TITLE
Update protobuf to 3.17.3

### PR DESCRIPTION
**Pull request by apolcyn**
For the 3.19 release

### CODE REVIEW

**Review by stanley-cheung — APPROVED** [review]

**Review by jtattermusch — APPROVED** [review]
The C# changes LGTM.

**Comment by jtattermusch** [comment]
Looks like python win artifacts are broken by the upgrade?
https://source.cloud.google.com/results/invocations/919ec9af-9845-42c1-bdd0-66dbc6f23c5a/targets/github%2Fgrpc/tests

there might also be other issues, let's doublecheck the test failures.

**Comment by apolcyn** [comment]
The ruby macos and artifact build macos failures are known issue: https://github.com/grpc/grpc/issues/26522

The objc ios failures looks like pre-existing issue: https://github.com/grpc/grpc/issues/26528

And indeed the python windows artifacts build looks broken: 

```
third_party\protobuf\src/google/protobuf/stubs/mutex.h: In constructor 'constexpr google::protobuf::internal::WrappedMutex::WrappedMutex()':


third_party\protobuf\src/google/protobuf/stubs/mutex.h:122:29: error: temporary of non-literal type 'google::protobuf::internal::CallOnceInitializedMutex<std::mutex>' in a constant expression


   constexpr WrappedMutex() {}


                             ^


third_party\protobuf\src/google/protobuf/stubs/mutex.h:96:7: note: 'google::protobuf::internal::CallOnceInitializedMutex<std::mutex>' is not literal because:


 class CallOnceInitializedMutex {


       ^~~~~~~~~~~~~~~~~~~~~~~~


third_party\protobuf\src/google/protobuf/stubs/mutex.h:96:7: note:   'google::protobuf::internal::CallOnceInitializedMutex<std::mutex>' has a non-trivial destructor


In file included from third_party\protobuf\src/google/protobuf/descriptor.h:65:0,


                 from third_party\protobuf\src/google/protobuf/compiler/java/java_doc_comment.h:38,


                 from third_party\protobuf\src\google\protobuf\compiler\java\java_message_field.cc:39:


third_party\protobuf\src/google/protobuf/stubs/mutex.h: In constructor 'constexpr google::protobuf::internal::WrappedMutex::WrappedMutex()':
```

**Comment by jtattermusch** [comment]
Superseded by https://github.com/grpc/grpc/pull/27227.

**Pull request closed without merging**
