### PR TITLE
Remove duplicate message member in test

### PR DESCRIPTION
**Pull request by AspirinSJL**
`kMessage_` is basically equal to `kRequestMessage_`.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by AspirinSJL** [comment]
- Asan C++ (internal CI) — Internal CI build failed: #13122
- Basic Tests C++ Linux [dbg] (internal CI) — Internal CI build failed: #13080
- Basic Tests C++ Linux [opt] (internal CI) — Internal CI build failed: #13133, #13122, #13080
- Microbenchmarks Diff (internal CI) — Internal CI build failed: #13126
- Tsan C++ (internal CI) — Internal CI build failed: #13122

**Pull request merged**
