### PR TITLE
Use macro for GRPC max value instead of using GPR_ATM_MAX

### PR DESCRIPTION
**Pull request by mhaidrygoog**
Fix for Issue #16417. The issue was caused because timer_list_shutdown was passing GPR_ATM_MAX as the max value of GRPC timers. However GPR_ATM_MAX is the max value of gpr_atm an intptr and not grpc_millics which is an int64.  So tests relying on this value would fail for 32-bit systems and pass for 64-bit systems. Replaced the macro value with GRPC_MILLIS_INF_FUTURE which basically maps to INT64_MAX and is the max value for grpc_millis.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by mhaidrygoog** [comment]
https://github.com/grpc/grpc/pull/15813 already solves what this PR is trying to fix

**Comment by mhaidrygoog** [comment]
Closing this request as merging #15813  will solve this

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,025      Total (=)      1,955,025

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,754      Total (>)     10,843,752

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
