### PR TITLE
Fix C# test access violation exception on Windows

### LINKED ISSUE #1940: Labeling iomgr objects makes C# tests crash
#1856 seems to make C# tests crash
tools/run_tests/run_tests.py -l csharp

This commit has C# tests already broken
https://github.com/grpc/grpc/commit/19fdb33da268b4ded64c64bd7bde7b75714ab0a0

With its parent, C# tests pass
https://github.com/grpc/grpc/commit/206e6e844140a3a477d65767d4a92e19d9893e56

Unfortunately, this is also part of the 0.9.1 release. I haven't released the NuGet packages yet though - I was testing manually that everything works and that's how I discovered this one.
Because all of C# alpha users are using NuGet, I don't think we've broken anyone.

### PR DESCRIPTION
**Pull request by jtattermusch**
fix wrong ordering of free and iomgr_unregister_object
Fixes #1940 

@nicolasnoble FYI

### CODE REVIEW

**Comment by jtattermusch** [comment]
Look at the wonderful blue dot this merge has added to the csharp-windows cell on Jenkins.
http://grpc-testing.appspot.com/job/gRPC/27/  (it was red before)

**Comment by ctiller** [comment]
I like http://green.bikeshed.org better than http://blue.bikeshed.org.

**Comment by jtattermusch** [comment]
Better now?

**Comment by ctiller** [comment]
\o/

**Pull request merged**
