### PR TITLE
Remove an unneccessary dependency from grpc++_base

### PR DESCRIPTION
**Pull request by tberghammer**
Previously grpc++_base was depending on grpc what caused a transitive
dependency on ssl for grpc++_unsecure. Removing the grpc dependency
shouldn't cause any issue as grpc++_base is a filegroup and all library
using it already depends on grpc directly.

This fixes https://github.com/grpc/grpc/issues/6784

### CODE REVIEW

**Comment by ctiller** [comment]
This is ok to test.

**Comment by ctiller** [comment]
Good catch - LGTM. I'm going to let Jenkins chew on it and we'll get it merged.

**Comment by jtattermusch** [comment]
For some reason jenkins refuses running tests on this PR. Please rebase and push, perhaps that will help. Without green tests, I cannot merge.

**Comment by ctiller** [comment]
Jenkins - This is ok to test.

**Comment by ctiller** [comment]
Jenkins - test this please.

**Pull request merged**
