### PR TITLE
Add CompositeCallCredentials

### PR DESCRIPTION
**Pull request by yang-g**
#12556

### CODE REVIEW

**Comment by jboeuf** [comment]
Thanks much. Maybe a little test? You could add something in end2end_test.cc if it proves difficult to unit-test this one.

**Comment by yang-g** [comment]
Sorry for the delay. PTAL
Thanks!

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
Test failures: #12428 #12510

**Pull request merged**
