### PR TITLE
replaced protobuf tag

### PR DESCRIPTION
**Pull request by jronak**
Replaced protobuf to avoid confusion when used with flatbuffers

### CODE REVIEW

**Comment by vjpai** [comment]
This will currently not pass the tests, unfortunately, as there are several golden-file tests that check the contents of generated files. Those may be removed by #8380 , so I would suggest holding off on this PR until that one goes through.

**Comment by JRonak** [comment]
Alright, Thanks!

**Comment by JRonak** [comment]
@vjpai looks like #8380 has been merged

**Comment by soltanmm-google** [comment]
Magical Jenkins invocation: this is ok to test

Though, the generator code is currently protobuf specific; this arguably is not needed quite yet (unless someone has already repurposed this code for flatbuffers somewhere downstream?).

**Comment by JRonak** [comment]
https://github.com/google/flatbuffers/tree/master/grpc
Flatbuffers shares the copy of generators from here

**Comment by soltanmm-google** [comment]
Ah, thanks. I stand corrected.

**Comment by yang-g** [comment]
Thanks.
Please also update https://github.com/grpc/grpc/blob/master/test/cpp/codegen/compiler_test_golden accordingly.

**Comment by JRonak** [comment]
@yang-g  Done

**Comment by yang-g** [comment]
jenkins: test this please

**Comment by yang-g** [comment]
jenkins: test this please

**Pull request merged**
