### PR TITLE
Reintroduce #28396 (Cleanup of windows CI .bat scripts)

### PR DESCRIPTION
**Pull request by jtattermusch**
Reintroduce https://github.com/grpc/grpc/pull/28396 (with a fixup)

### CODE REVIEW

**Comment by jtattermusch** [comment]
Adhoc run of windows bazel RBE opt: https://source.cloud.google.com/results/invocations/b7f5b5b2-2a65-4f4f-8599-6b13baaff4ba (green).

**Review by lidizheng — APPROVED** [review]

**Comment by jtattermusch** [comment]
The macos failures are b/212422399

**Comment by lidizheng** [comment]
THe `Bazel RBE Windows Opt C/C++` job is also passed in the original PR, do you know why our presubmit checks didn't catch it in the first time?

**Comment by jtattermusch** [comment]
> THe `Bazel RBE Windows Opt C/C++` job is also passed in the original PR, do you know why our presubmit checks didn't catch it in the first time?

Because the PR version of that test doesn't upload results to bigquery (which is why it passed). I made sure to run the master version of the test as adhoc (which does upload to bigquery).

**Comment by lidizheng** [comment]
Thanks. That makes sense.

**Pull request merged**
