### PR TITLE
Improve nodejs example

### PR DESCRIPTION
**Pull request by RinatMullayanov**
Hi, I'm a little improved nodejs example.

### CODE REVIEW

**Comment by RinatMullayanov** [comment]
I signed it!

**Comment by murgatroid99** [comment]
Most of these changes are ECMASCRIPT6-specific, and that would make the examples only run on io.js and Node 4.x+. I'm not sure that adding that restriction is a good idea.

**Comment by RinatMullayanov** [comment]
@murgatroid99 And you need to support Node 0.12.x and higher?

**Comment by murgatroid99** [comment]
The library itself currently supports 0.12.x and above. I would prefer to have the same version support in the example, at least until we have a good reason to change it.

**Comment by RinatMullayanov** [comment]
@murgatroid99 Ok, I understood, then I close this pull request?

**Comment by RinatMullayanov** [comment]
@murgatroid99 By the way if you need support for ECMAScript 5 is why you do not use [Babel](https://github.com/babel/babel)?

**Comment by murgatroid99** [comment]
I don't use Babel because I see no substantial benefit to writing ES6 compatible code and compiling it to ES5 code, as opposed to simply writing ES5 code.

I am going to close this PR for now. In the future, if we change what versions we support, this may become useful again.

**Pull request closed without merging**
