### PR TITLE
reland: cpu_linux: Don't spam sched_getcpu failures on qemu

### PR DESCRIPTION
**Pull request by iancoolidge**
__NR_getcpu isn't implemented on qemu, and for some reason
sysconf(_SC_NPROCESSORS_ONLN) returns the number of processers
of the host system, giving a false indication that there is more
than one cpu for the qemu case.

Expand the init_num_cpus sequence to also run sched_getcpu once,
if GPR_MUSL_LIBC_COMPAT isn't defined.
If that call isn't supported, initialize 'ncpus' to 1.

Later, in gpr_cpu_current_cpu, use gpr_cpu_num_cores to avoid
the system call in cases where we know it isn't supported, or
if the ncpus is otherwise 1.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @iancoolidge isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by iancoolidge** [comment]
Ok, I think I got the CLA thing done.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                         FILE SIZE
 ++++++++++++++ GROWING                           ++++++++++++++
   +48%     +96 src/core/lib/support/cpu_linux.cc     +96   +48%
      +103%     +80 init_num_cpus                         +80  +103%
       +22%     +16 gpr_cpu_current_cpu                   +16   +22%
  +0.0%      +8 [None]                                +24  +0.0%

  +0.0%    +104 TOTAL                                +120  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
