### PR TITLE
gRPC.podspec shouldn't be a template anymore.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Restoring the podspec changes from 0.14.

This is for 0.15. The best is to do the 0.15->1.0->master crawl.

### CODE REVIEW

**Comment by jcanizales** [comment]
Why this change specifically, out of the many in 0.14?

**Comment by makdharma** [comment]
LGTM. All other changes from 0.14 already made it to 0.15 in the PR https://github.com/grpc/grpc/pull/7321

**Comment by nicolasnoble** [comment]
Yep, for some reasons, git merges "forgot" or ignored that gRPC.podspec.template was deleted in 0.14. So only that should need to be reverted. Hopefully.

**Comment by makdharma** [comment]
Seems like Travis is failing https://travis-ci.org/grpc/grpc/jobs/144224434 because 
[!] Unable to satisfy the following requirements:
- `Protobuf (from `../../../third_party/protobuf`)` required by `Podfile`

**Comment by jcanizales** [comment]
I guess the merge nuked the submodule upgrade too.

**Comment by nicolasnoble** [comment]
Let's see. From the history, there was two submodule upgrades - one in 0.14, one in 0.15. Git decided that the one in 0.15 took precedence.

**Comment by jcanizales** [comment]
Yeah automatic merges can only be so smart about what they're merging.

**Comment by nicolasnoble** [comment]
Well, that's why propagating the changes correctly in the first place would've been the right thing to do.

Now, looking back at it, in 0.14, the protobuf submodule didn't get set up properly, and sanity was always failing there because of it. But right now it's set on protobuf beta 3.1. Release 0.15 is on protobuf beta 3.2 - probably with good reasons. The v1.0.x branch is on 3.3.

It seems that git did The Right Thing by merging up - the thing that needs to change, potentially, is that the podspec needs the 3.2 reference instead of 3.1. Reverting down to 3.1 doesn't seem the logical choice here.

**Comment by jcanizales** [comment]
The problem is the beta-3.2 tag of protobuf isn't a successor of beta-3.1. Beta-3.1 has changes needed by Obj-C; beta-3.2 has changes needed by JavaScript apparently. So I merged both in https://github.com/google/protobuf/pull/1737 and the merge got assigned the beta-3.3 tag.

**Comment by nicolasnoble** [comment]
Whee. Okay. So 0.15 needs to go to beta-3.3. Got it.

**Comment by nicolasnoble** [comment]
Done in 65464515f77dbe1460fae312281d42eed459561c - let's see.

**Comment by jcanizales** [comment]
Can Travis be enabled/disabled on a per-branch basis?

What I'm currently doing myself is have it enabled for pushes to my fork.

**Comment by nicolasnoble** [comment]
Not that I know, no.

**Comment by jcanizales** [comment]
For reference, the Travis run is https://travis-ci.org/nicolasnoble/grpc/builds/144270930

**Comment by pgrosu** [comment]
@jcanizales https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches

**Comment by nicolasnoble** [comment]
https://travis-ci.org/nicolasnoble/grpc/builds/144279244 now.

**Comment by jcanizales** [comment]
Travis tests fail because of https://github.com/grpc/grpc/issues/6118 being treated as an error. Which is weird because it suggests 0.15 got the stricter check from https://github.com/grpc/grpc/pull/6922 but not the corresponding silencing of those warnings.

Because it's pressing to get 1.0 and master fixed, and it's fine for 0.15 to have broken ObjC tests (as there's not going to be a 0.15 podspec before 1.0), I'm merging.

**Pull request merged**
