### PR TITLE
Set threads_per_cq=2 for C++ unconstrained scenarios for best throughput and lower variance

### PR DESCRIPTION
**Pull request by jtattermusch**
Alternative to #27849.

While the default threads_per_cq=1 least to the lowest noisiness, it also leads to performance drop.

Empirically, setting threads_per_cq=2 leads to best throughput (better than both threads_per_cq=1 and threads_per_cq=3) and to low variance as well. threads_per_cq=2 also performs the best across all the dimensions I looked at (8core vs 32core, unary vs streaming). 

Since threads_per_cq = 3 was also chosen empirically in the past (see https://github.com/grpc/grpc/pull/12465), IMHO it makes sense to switch to threads_per_cq=2 now.

BEFORE (threads_per_cq=3)
average qps 184Kqps
relative st.deviation: 21.38% 

ALTERNATIVE PR (threads_per_cq=1)
average qps 166Kqps
relative st.deviation 3.26%

THIS PR (threads_per_cq=2) - **BEST RESULTS**
average qps 201Kqps
relative st.deviation 4.27%

### CODE REVIEW

**Review by ctiller — APPROVED** [review]

**Review by markdroth — APPROVED** [review]
If Craig's happy with this, I'm fine with it.

Interestingly, note that our [performance best practices](https://grpc.io/docs/guides/performance/) doc suggests using "numcpu’s threads and one completion queue per thread".  It doesn't seem like that maps to the benchmark results we're actually seeing here.

**Comment by ctiller** [comment]
Note I haven't done deep analysis, but the 3 was chosen empirically, and I
expected it to drift over the years.
I'm not sure I care much though, since within a year my expectation is that
the advice will be firmly 'use the callback API, not the CQ API' for
performance.

**Comment by jtattermusch** [comment]
Test failure are unrelated since this PR only changes benchmarking scenarios.

**Comment by jtattermusch** [comment]
> If Craig's happy with this, I'm fine with it.
> 
> Interestingly, note that our [performance best practices](https://grpc.io/docs/guides/performance/) doc suggests using "numcpu’s threads and one completion queue per thread". It doesn't seem like that maps to the benchmark results we're actually seeing here.

Good point, I think this advice in the "performance best practices" doc is originally taken from the internal performance tips, but due to differences in iomgr, it doesn't translate well into the OSS stack.

**Pull request merged**
