### PR TITLE
Temporarily reduce throughput test depth to 1 RPC per channel

### PR DESCRIPTION
**Pull request by vjpai**
due to flake. Need to root-cause the flake.

### CODE REVIEW

**Comment by jtattermusch** [comment]
LGTM.

**Comment by jtattermusch** [comment]
Undo LGTM. 

Looks like the test is still timing out:

`TIMEOUT: qps_json_driver.cpp_single_channel_throughput_secure [pid=9036]`

**Comment by vjpai** [comment]
Yes, just realized that. It's become more urgent to root-cause this, and maybe it wasn't caused by this particular change.

**Comment by vjpai** [comment]
BTW, note that this failed on the perf smoke test, which is a single-machine test. So, it's not about single-machine vs multi-machine.

**Comment by jtattermusch** [comment]
Superseded by#6270

**Pull request closed without merging**
