### PR TITLE
Protect a Noise Comment

### PR DESCRIPTION
**Pull request by ncteisen**
This comment should be protected with a tracer.

Also added some more details. It has been a red herring for stalls in the past

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +192 [None]                                                                                 +1008  +0.0%
  +1.1%     +64 src/core/ext/transport/chttp2/transport/writing.cc                                       +64  +1.1%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
      +1.2%     +64 grpc_chttp2_begin_write                                                                  +64  +1.2%

  +0.0%    +256 TOTAL                                                                                +1.05Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by nicolasnoble** [comment]
I'd use the word "unwanted" instead of "malevolent", as the latter would maybe indicate malicious external intervention.

**Comment by ncteisen** [comment]
Done

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +192 [None]                                                                                 +1008  +0.0%
  +1.1%     +64 src/core/ext/transport/chttp2/transport/writing.cc                                       +64  +1.1%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
      +1.2%     +64 grpc_chttp2_begin_write                                                                  +64  +1.2%

  +0.0%    +256 TOTAL                                                                                +1.05Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
