### PR TITLE
PR AS ISSUE: should we reconnect after disconnection?

### PR DESCRIPTION
**Pull request by AspirinSJL**
After running `grpclb_end2end_test` 2000+ times without failure, I believe we will not reconnect immediately after the connected subchannel disconnects. At least, https://github.com/grpc/grpc/blob/5a6120ac8ca4e087c9eb31d139c0c4219d1cc29d/src/core/ext/filters/client_channel/subchannel.cc#L563 is a noop. When this function is called, the subchannel's watchers have already been cleared when the connectivity was set https://github.com/grpc/grpc/blob/5a6120ac8ca4e087c9eb31d139c0c4219d1cc29d/src/core/lib/transport/connectivity_state.cc#L156. (And the connectivity callback in the LB policy hasn't run, so even if we want to keep watching we hasn't renewed the watch yet.)

I think this is hidden/unimportant before because we combine the connectivity watch subscription and subchannel connection together.

@dgquintas @markdroth So my question is - do we want to reconnect the subchannel if it disconnects but the LB policy wants to continue watching it? If so, this seems a real bug and we should fix it. But I guess we may not want to reconnect immediately because the disconnection might be due to a GOAWAY. Then we should remove this line from `on_connected_subchannel_connectivity_changed()`.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                         FILE SIZE
 ++++++++++++++ GROWING                                           ++++++++++++++
  +0.0%     +40 [None]                                               +160  +0.0%
  +1.3%     +80 src/core/ext/filters/client_channel/subchannel.cc     +80  +1.3%
      [NEW]    +460 maybe_start_connecting_locked                        +460  [NEW]
      +5.3%     +16 on_connected_subchannel_connectivity_changed          +16  +5.3%

  +0.0%    +120 TOTAL                                                +240  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,775      Total (>)      1,976,654

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,775,734      Total (=)     10,775,734

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                            cpu_time    real_time
-------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/32768                         -4%         -4%
BM_PumpStreamServerToClient<InProcessCHTTP2>/32768                   -7%         -7%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768  -4%         -4%
```

**Comment by markdroth** [comment]
If we are going to decouple the connectivity watch from triggering a connection attempt, then I think we need the LB policy to tell us when it wants us to try to connect.  See my comments in #16176 for details.

**Pull request closed without merging**
