### PR TITLE
Big improvements to CMake build

### PR DESCRIPTION
**Pull request by jtattermusch**
Lots of improvements to CMake build.
-- create targets `buildtests_c` `buildtests_cxx` `tools_c` and `tools_cxx` to make building tests with CMake more convenient
-- fixes in C/C++ code to ensure it builds correctly on windows
-- for now, disable tests `bm_fullstack` and `json_run_localhost` because they need more work to become buildable on windows
-- build dependencies in submodules using their own CMake files (instead of generating a "virtual" library instead).

With this PR, all the C/C++ tests build successfully on Windows (we weren't able to build the C++ tests before) - and on Linux as well.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Also includes changes from https://github.com/grpc/grpc/pull/9417.

**Comment by ctiller** [comment]
We should get a test in place for this (for Windows and Linux at least)

**Comment by jtattermusch** [comment]
Yes, that is definitely the plan. The very next thing on my plate.

**Comment by ctiller** [comment]
Also, I'm not sure how useful this is: strategically we're likely better off moving to Bazel to build our tests and having the non-Bazel build systems just building the library itself.

**Comment by matt-kwong** [comment]
Bazel on Windows is still experimental, so it could take a while before we can reliably build tests on Windows. I don't think it's a bad thing to add test building support for CMake, at least for Windows.

**Comment by jtattermusch** [comment]
@ctiller  I'd argue this is pretty useful:
-- as Matt pointed out, bazel on windows is still experimental, so it's unclear how long would it take to implement
-- there is some targets (`grpc_cli` for example that should be buildable as well, but require protoc generation and other changes to be in place to make them build successfully anyway, so why not make other targets buildable as well
-- things are not going to build under bazel on windows unless the code is actually buildable on windows (this PR is a great way to make sure that is the case in advance and make transition to bazel much simpler in the future)
-- we have several user issues regarding the weirdness of how we currently handle the zlib + openssl dependencies, and it seems it's resulting in observable instability of our windows port - we need to fix that ASAP
-- there are targets that we really want to make buildable on windows (qps_worker, interop_client, interop_server, ...). This PR makes them so in a fashion that can be automated. Again, yesterday was too late for this.

**Comment by jtattermusch** [comment]
@matt-kwong   I think I fixed the interop tests (my bad - gpr_time_add only accepts GPR_TIMESPAN as the second argument, fixed in interop_client.cc and interop_server.cc).

I needed to resolve conflicts with master so I rebased and fixed the original commit. PTAL.

**Comment by ctiller** [comment]
Please talk with Nico and ensure there's a plan for being able to get all
the data this needs from the Bazel BUILD files. build.yaml is deprecated,
and the last plan I heard was that tests would NOT be supported from its
replacement for the purposes of the templating engine.

**Comment by jtattermusch** [comment]
@nicolasnoble  can I get your opinions on this PR please?

**Comment by matt-kwong** [comment]
The changes look good, but I'd like @nicolasnoble to approve this, since he did tell me earlier this week he'd like to move test-related building to Bazel. I do think making these changes now and switching to Bazel later is a good option.

**Comment by nicolasnoble** [comment]
As per our chat, the tests will be removed from the cmakefile.

**Comment by jtattermusch** [comment]
Known failures:
- #9499
- #9147

**Pull request merged**
