### PR TITLE
Don't destroy null lb_addr

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
As part of investigating how to test the changes in #14228 for c-ares, I simply ran `resolve_address_test` with c-ares enabled (at current master), and it exploded: 
```$ GRPC_DNS_RESOLVER=ares bins/asan/resolve_address_test
D0130 09:50:57.459232700   12276 test_config.cc:388]         test slowdown factor: sanitizer=3, fixture=1, poller=1, total=3
ASAN:DEADLYSIGNAL
=================================================================
==12276==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000099f8fa bp 0x7ffdbccf0f90 sp 0x7ffdbccf0f00 T0)
    #0 0x99f8f9 in grpc_lb_addresses_destroy(grpc_lb_addresses*) /usr/local/google/home/dgq/grpc/forks/tmp/grpc/src/core/ext/filters/client_channel/lb_policy_factory.cc:116:24
    #1 0x7615f7 in on_dns_lookup_done_cb(void*, grpc_error*) /usr/local/google/home/dgq/grpc/forks/tmp/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc:508:3
    #2 0x4f2e7d in exec_ctx_run(grpc_closure*, grpc_error*) /usr/local/google/home/dgq/grpc/forks/tmp/grpc/src/core/lib/iomgr/exec_ctx.cc:38:3
    #3 0x4f2854 in grpc_core::ExecCtx::Flush() /usr/local/google/home/dgq/grpc/forks/tmp/grpc/src/core/lib/iomgr/exec_ctx.cc:125:9
    #4 0x4e0cfd in test_missing_default_port() /usr/local/google/home/dgq/grpc/forks/tmp/grpc/test/core/iomgr/resolve_address_test.cc:164:3
    #5 0x4e024f in main /usr/local/google/home/dgq/grpc/forks/tmp/grpc/test/core/iomgr/resolve_address_test.cc:250:5
    #6 0x7f0b02fcef44 in __libc_start_main /build/eglibc-ripdx6/eglibc-2.19/csu/libc-start.c:287
    #7 0x41c255 in _start (/usr/local/google/home/dgq/grpc/forks/tmp/grpc/bins/asan/resolve_address_test+0x41c255)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/local/google/home/dgq/grpc/forks/tmp/grpc/src/core/ext/filters/client_channel/lb_policy_factory.cc:116:24 in grpc_lb_addresses_destroy(grpc_lb_addresses*)
==12276==ABORTING
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
