### PR TITLE
Expose gpr_asprintf and gpr_strdup

### PR DESCRIPTION
**Pull request by soltanmm**
Adds a new file `string_util.h` and moves the declarations for `gpr_asprintf` and `gpr_strdup` to it.

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM, waiting on Travis

24% increase in coverage... wow

(methinks the previous coveralls run was broken)

**Comment by jcanizales** [comment]
This change broke [census_rpc_stats.c](https://github.com/grpc/grpc/blob/master/src/core/statistics/census_rpc_stats.c) and [census_tracing.c](https://github.com/grpc/grpc/blob/master/src/core/statistics/census_tracing.c) for me. Both use `gpr_strdup` and weren't made to include the new file.

Am I compiling more than Travis?

**Comment by ctiller** [comment]
You almost certainly are. build.json is the canonical file listing what to
include in a libgrpc build, and if you're compiling a different list than
that you're almost certainly doing it wrong.

Please work with +Nicolas Noble <nnoble@google.com> to generate your build
lists from that file.

**Comment by nicolasnoble** [comment]
@ctiller is correct. You need to start generating your project files from the build.json to keep in sync with the rest of the project.

**Pull request merged**
