### PR TITLE
Fix hang during fork on Python 3.

### PR DESCRIPTION
**Pull request by dcoles**
On Python 3, the Python interpreter calls `PyEval_ReInitThreads` in the
child process during a call to `os.fork`. As a fork only copies the
current thread (typically a handler), the Python runtime is thus free to
garbage collect objects from other threads including the `_Server`
object. This causes a call to `_stop` which hangs the incomplete child
process.

To prevent this, only try and stop `_Server` if the current PID matches
the PID that created the `Server` object. To avoid errors, the forked
thread should only call async-signal-safe functions before making a call
to one of the exec functions.

Fixes: GH-17093

### CODE REVIEW

**Comment by srini100** [comment]
@dcoles, thanks for the PR. Can you please add the reason why this is not an issue in Python 2.7? Does the garbage collector kicks in later?

**Comment by dcoles** [comment]
@srini100 Python 3.4 introduced python/cpython@8408cea0cdc0ccd5900acd99a9a51dd9161ae319 which causes Python to destroy all threads except the current one during `PyEval_ReInitThreads` (https://github.com/python/cpython/blob/3.6/Python/ceval.c#L330) which is called by `PyOS_AfterFork` in the new child.

From the Python 3.4 release notes: 

> Stale thread states are now cleared after fork(). This may cause some system resources to be released that previously were incorrectly kept perpetually alive (for example, database connections kept in thread-local storage). ([bpo-17094](https://bugs.python.org/issue17094).)

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,224      Total (=)      2,020,224

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,228      Total (<)     11,154,230

 No significant differences in binary sizes


```

**Comment by ericgribkoff** [comment]
Thanks very much for the detailed analysis, reproduction steps, and this PR. I was able to replicate similar behavior on Python 3.5.3 as well. It appears that obtaining a lock in a `__del__` method (as we are doing here in the server's destructor via the call to `_stop()`) is a bad idea for a multi-threaded application: it's easy to recreate this behavior without gRPC involved, simply by creating two threads, one which allocates an object with a `__del__` method that grabs a lock, and forking from the second thread. The child process will initiate cleanup of the other thread's state and invoke the `__del__` method of the (now-deceased) thread's instance object, which can hang and never give the forked process a chance to exec. The fix here is valid, but I'm worried about our other deallocation methods and I would like to pursue addressing the root cause directly first.

My initial impression is that we need to revisit how gRPC Python shuts down servers and, more generally, how we rely on garbage collection in our Python and Cython layers. We have just seen a [related issue](https://github.com/grpc/grpc/issues/17258) where a server is not completely shutting down because of how we rely on GC to finish the shutdown process, and this being unreliable in terms of when/if it occurs. I think the full solution here has two parts: (a) remove, as much as possible, all heavy-weight actions from our destructors, including obtaining locks, and (b) modify the existing `server.stop()` method completely handle server shutdown, instead of partially off-loading some work to methods that must later triggered by the garbage collector. (a) alone would solve issue #17288, but by itself would would exacerbate problems like #17258.

We will work on getting this solution put together. I would like to avoid checking pids in every deallocator, but if we would otherwise break users who are currently depending on our shut-down-via-deallocation behavior, it may be tricky to find an alternative.

**Comment by dcoles** [comment]
Closing this PR since this should now be fixed by #17444.

**Pull request closed without merging**
