### PR TITLE
Remove deprecated V8 function call in Node library

### PR DESCRIPTION
**Pull request by murgatroid99**
This should fix the problems reported in #8193 and #8166.

### CODE REVIEW

**Comment by bootstraponline** [comment]
This is blocking using electron with grpc. It'd be great to have this merged.

#6138

**Comment by murgatroid99** [comment]
test this please

**Comment by nicolasnoble** [comment]
Test this please.

**Comment by murgatroid99** [comment]
It looks like the relevant tests passed.

**Pull request merged**
