### PR TITLE
Revert "Allow encoding arbitrary channel args on a per-address basis."

### PR DESCRIPTION
**Pull request by hcaseyal**
Reverts grpc/grpc#17343 because of internal breakage

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  [NEW] +1.35Ki src/core/ext/filters/client_channel/lb_policy_factory.cc                             +1.35Ki  [NEW]
      [NEW]    +383 grpc_lb_addresses_cmp                                                                   +383  [NEW]
      [NEW]    +211 grpc_lb_addresses_set_address                                                           +211  [NEW]
      [NEW]    +164 grpc_lb_addresses_copy                                                                  +164  [NEW]
      [NEW]    +158 grpc_lb_addresses_set_address_from_uri                                                  +158  [NEW]
      [NEW]    +109 grpc_lb_addresses_destroy                                                               +109  [NEW]
      [NEW]     +91 grpc_lb_addresses_contains_balancer_address                                              +91  [NEW]
      [NEW]     +76 grpc_lb_addresses_create_channel_arg                                                     +76  [NEW]
      [NEW]     +72 [Unmapped]                                                                               +72  [NEW]
      [NEW]     +61 grpc_lb_addresses_create                                                                 +61  [NEW]
      [NEW]     +47 grpc_lb_addresses_find_channel_arg                                                       +47  [NEW]
      [NEW]      +5 lb_addresses_cmp                                                                          +5  [NEW]
      [NEW]      +5 lb_addresses_copy                                                                         +5  [NEW]
      [NEW]      +5 lb_addresses_destroy                                                                      +5  [NEW]
  +2.4%     +33 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_channel_secure.cc            +33  +2.4%
      +2.7%     +33 grpc_lb_policy_grpclb_modify_lb_channel_args                                             +33  +2.7%
  +2.7%     +33 src/core/ext/filters/client_channel/lb_policy/xds/xds_channel_secure.cc                  +33  +2.7%
      +2.7%     +33 grpc_lb_policy_xds_modify_lb_channel_args                                                +33  +2.7%

 -------------- SHRINKING                                                                            --------------
 -35.7% -3.34Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc         -3.34Ki -35.7%
     -65.4% -1.65Ki on_hostbyname_done_locked                                                            -1.65Ki -65.4%
      [DEL] -1.43Ki grpc_cares_wrapper_address_sorting_sort                                              -1.43Ki  [DEL]
      [DEL] -1.30Ki grpc_dns_lookup_ares_locked_impl                                                     -1.30Ki  [DEL]
      [DEL]    -250 log_address_sorting_list                                                                -250  [DEL]
     -21.7%    -128 on_dns_lookup_done_locked                                                               -128 -21.7%
      -8.4%     -18 grpc_resolve_address_ares_impl                                                           -18  -8.4%
     -14.9%     -13 [Unmapped]                                                                               -13 -14.9%
 -10.0% -1.77Ki src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                       -1.77Ki -10.0%
      [DEL] -1.76Ki grpc_core::(anonymous namespace)::GrpcLb::CreateRoundRobinPolicyArgsLocked           -1.76Ki  [DEL]
      [DEL] -1.09Ki grpc_core::(anonymous namespace)::GrpcLb::CreateOrUpdateRoundRobinPolicyLocked() [cl -1.09Ki  [DEL]
     -45.5%    -956 grpc_core::(anonymous namespace)::GrpcLb::ProcessChannelArgsLocked                      -956 -45.5%
     -20.2%     -96 grpc_core::(anonymous namespace)::GrpcLb::~GrpcLb                                        -96 -20.2%
      -5.4%     -80 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::OnBalancerMessageReceiv     -80  -5.4%
      -2.4%      -9 [Unmapped]                                                                                -9  -2.4%
      -2.5%      -8 grpc_core::(anonymous namespace)::GrpcLb::PickLocked                                      -8  -2.5%
      -3.0%      -8 grpc_core::(anonymous namespace)::GrpcLb::PendingPickSetMetadataAndContext                -8  -3.0%
     -22.7%      -5 grpc_core::(anonymous namespace)::lb_token_cmp                                            -5 -22.7%
      -0.1%      -1 grpc_core::(anonymous namespace)::GrpcLbFactory::CreateLoadBalancingPolicy(grpc_core      -1  -0.1%
  [DEL] -1.30Ki src/core/ext/filters/client_channel/server_address.cc                                -1.30Ki  [DEL]
      [DEL]    -635 grpc_core::(anonymous namespace)::ServerAddressListCopy                                 -635  [DEL]
      [DEL]    -136 grpc_core::(anonymous namespace)::ServerAddressListCompare                              -136  [DEL]
      [DEL]    -114 grpc_core::(anonymous namespace)::ServerAddressListDestroy                              -114  [DEL]
      [DEL]    -102 grpc_core::ServerAddress::Cmp(grpc_core::ServerAddress const&) const                    -102  [DEL]
      [DEL]     -90 grpc_core::ServerAddress::ServerAddress                                                  -90  [DEL]
      [DEL]     -76 grpc_core::CreateServerAddressListChannelArg                                             -76  [DEL]
      [DEL]     -66 [Unmapped]                                                                               -66  [DEL]
      [DEL]     -47 grpc_core::FindServerAddressListChannelArg                                               -47  [DEL]
      [DEL]     -37 grpc_core::ServerAddress::IsBalancer() const                                             -37  [DEL]
      [DEL]     -24 grpc_core::ServerAddress::ServerAddress                                                  -24  [DEL]
  -6.9% -1.11Ki src/core/ext/filters/client_channel/lb_policy/xds/xds.cc                             -1.11Ki  -6.9%
      [DEL] -1.94Ki grpc_core::(anonymous namespace)::XdsLb::CreateOrUpdateChildPolicyLocked() [clone .p -1.94Ki  [DEL]
     -53.7% -1.30Ki grpc_core::(anonymous namespace)::XdsLb::ProcessChannelArgsLocked                    -1.30Ki -53.7%
      [DEL]    -115 grpc_core::(anonymous namespace)::XdsLb::PendingPickCleanup                             -115  [DEL]
     -20.2%     -96 grpc_core::(anonymous namespace)::XdsLb::~XdsLb                                          -96 -20.2%
      -5.4%     -83 grpc_core::(anonymous namespace)::XdsLb::BalancerCallState::OnBalancerMessageReceive     -83  -5.4%
      -2.5%      -8 grpc_core::(anonymous namespace)::XdsLb::PickLocked                                       -8  -2.5%
 -31.5%    -832 src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc              -832 -31.5%
     -53.4%    -722 grpc_core::(anonymous namespace)::CreateSockaddrResolver                                -722 -53.4%
     -72.5%    -108 grpc_core::(anonymous namespace)::SockaddrResolver::~SockaddrResolver                   -108 -72.5%
      -1.1%      -2 [Unmapped]                                                                                -2  -1.1%
  -5.9%    -800 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  -800  -5.9%
     -20.0%    -780 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                               -780 -20.0%
      [DEL]    -219 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc    -219  [DEL]
      -3.3%     -16 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     -16  -3.3%
      -1.6%      -4 [Unmapped]                                                                                -4  -1.6%
 -17.5%    -560 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc                 -560 -17.5%
     -42.1%    -554 grpc_core::(anonymous namespace)::NativeDnsResolver::OnResolvedLocked                   -554 -42.1%
      [DEL]     -65 grpc_core::(anonymous namespace)::NativeDnsResolver::MaybeFinishNextLocked() [clone      -65  [DEL]
      -5.2%      -6 [Unmapped]                                                                                -6  -5.2%
  -2.9%    -416 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                -416  -2.9%
     -19.5%    -644 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                              -644 -19.5%
      [DEL]    -592 grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelList::StartWatchin    -592  [DEL]
      [DEL]    -219 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu    -219  [DEL]
      -4.5%     -11 [Unmapped]                                                                               -11  -4.5%
  -4.4%    -192 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc            -192  -4.4%
     -52.9%    -117 grpc_core::(anonymous namespace)::AresDnsResolver::~AresDnsResolver                     -117 -52.9%
      [DEL]    -111 grpc_core::(anonymous namespace)::AresDnsResolver::MaybeFinishNextLocked() [clone .p    -111  [DEL]
      -5.3%     -88 grpc_core::(anonymous namespace)::AresDnsResolver::OnResolvedLocked                      -88  -5.3%
      -2.2%      -3 [Unmapped]                                                                                -3  -2.2%
  -0.5%     -48 src/core/ext/filters/client_channel/subchannel.cc                                        -48  -0.5%
      [DEL]     -76 grpc_core::ConnectedSubchannel::ConnectedSubchannel                                      -76  [DEL]
     -19.8%     -16 grpc_core::ConnectedSubchannel::~ConnectedSubchannel                                     -16 -19.8%
      -0.3%      -1 [Unmapped]                                                                                -1  -0.3%
  -0.5%     -32 src/core/ext/filters/client_channel/resolver_result_parsing.cc                           -32  -0.5%
      [DEL]    -260 grpc_core::internal::(anonymous namespace)::ParseDuration(grpc_json*, long*) [clone     -260  [DEL]
      [DEL]    -111 void grpc_core::ServiceConfig::ParseGlobalParams<grpc_core::internal::ProcessedResol    -111  [DEL]
      -7.3%     -31 grpc_core::internal::ProcessedResolverResult::ProcessLbPolicyName                        -31  -7.3%
      -1.8%      -1 [Unmapped]                                                                                -1  -1.8%
  -0.0%     -16 src/core/ext/filters/client_channel/client_channel.cc                                    -16  -0.0%
      [DEL] -3.51Ki on_resolver_result_changed_locked(void*, grpc_error*) [clone .part.83]               -3.51Ki  [DEL]
      [DEL]    -391 add_closure_for_subchannel_batch(grpc_call_element*, grpc_transport_stream_op_batch*    -391  [DEL]
      [DEL]    -192 add_retriable_send_message_op(grpc_call_element*, (anonymous namespace)::subchannel_    -192  [DEL]
      -4.3%     -16 [Unmapped]                                                                               -16  -4.3%
      -3.9%     -16 invoke_recv_message_callback                                                             -16  -3.9%
      -0.6%     -12 run_closures_for_completed_call                                                          -12  -0.6%
      -2.0%      -8 invoke_recv_initial_metadata_callback                                                     -8  -2.0%
  -0.7%     -16 src/core/lib/iomgr/sockaddr_utils.cc                                                     -16  -0.7%
      -6.6%     -16 grpc_sockaddr_to_uri                                                                     -16  -6.6%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  +0.1%    +994 [None]                                                                                -118Ki  -1.1%
      [NEW]     +96 grpc_core::(anonymous namespace)::BuildBalancerChannelArgs(grpc_lb_addresses const*,     +96  [NEW]
      [NEW]     +48 grpc_core::(anonymous namespace)::lb_token_vtable                                        +48  [NEW]
      [NEW]     +24 lb_addresses_arg_vtable                                                                  +24  [NEW]
      [NEW]     +24 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     +24  [NEW]
      [NEW]     +24 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     +24  [NEW]
       +20%      +8 vtable for grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData         +8   +20%
       +20%      +8 vtable for grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData           +8   +20%
       +20%      +8 vtable for grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::R      +8   +20%
       +20%      +8 vtable for grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::Pi      +8   +20%
      [DEL]     -96 grpc_core::(anonymous namespace)::BuildBalancerChannelArgs(grpc_core::InlinedVector<     -96  [DEL]
      [DEL]     -24 grpc_core::(anonymous namespace)::lb_token_arg_vtable                                    -24  [DEL]
      [DEL]     -24 grpc_core::(anonymous namespace)::server_addresses_arg_vtable                            -24  [DEL]
      [DEL]     -24 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSu     -24  [DEL]
      [DEL]     -24 grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc     -24  [DEL]
      [DEL]      -8 grpc_core::(anonymous namespace)::ExtractBalancerAddresses(grpc_core::InlinedVector<      -8  [DEL]

  -0.5% -7.97Ki TOTAL                                                                                 -127Ki  -1.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   730,442       Core (<)        731,628

 2,019,388      Total (<)      2,020,710

***************FRAMEWORKS****************
  New size                      Old size
 3,947,450       Core (<)      3,968,626

11,154,183      Total (<)     11,175,362


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] Performance differences noted:
Benchmark                                     cpu_time    real_time
--------------------------------------------  ----------  -----------
BM_ErrorGetStatus<ErrorWithGrpcStatus>        -10%        -10%
BM_ErrorGetStatus<ErrorWithNestedGrpcStatus>  -11%        -11%
BM_ErrorHttpError<ErrorWithGrpcStatus>        -10%        -10%
BM_ErrorHttpError<ErrorWithNestedGrpcStatus>  -8%         -8%
```

**Comment by hcaseyal** [comment]
Ignoring test failures because this is just a revert

**Pull request merged**
