### PR TITLE
Update upb

### PR DESCRIPTION
**Pull request by veblush**
Synced with the [head](https://github.com/protocolbuffers/upb/commit/ed86d98f53a0421eaa487acd9a39d1c927eba7f3) of upb.

### CODE REVIEW

**Comment by markdroth** [comment]
Out of curiosity, what's the motivation for this?  As it happens, we've been discussing the fact that we're going to need to do another upgrade soon anyway to get a bug fix needed for the RBAC work.

However, I think we should hold off on this until we resolve the ongoing build failure issues that were caused by the last upb upgrade, which @nicolasnoble is still investigating.  If we wind up needing to revert that upgrade, then I'd rather not have a second one on top of it making the revert harder.

Nico, can you give us an ETA on addressing the build failures?

**Comment by veblush** [comment]
This is not necessary right now. I was curious about the difference between our upb snapshot and the HEAD because I was helping upb code work of ALTS and there was an issue how to access map with new API of upb. But it seems that there is no chance between two twos so there is no direct demand other than having up-to-date upb with minor bug fixes.

**Comment by veblush** [comment]
I think this PR can be used when everything for upb settled.

**Comment by veblush** [comment]
Superseded by #23727

**Pull request closed without merging**
