### PR TITLE
Bump zlib version to match master.

### PR DESCRIPTION
**Pull request by ernie**
Older versions of zlib fail to build on Alpine Linux, due to a left
shift of negative value warning in `inflate.c`'s `inflateMark` function
and `-Werror`.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by jtattermusch** [comment]
I'm not sure we want to do this for v1.3.x (btw, this PR has merge conflicts, so is not mergeable anyway).
 v1.4.0 will be released soon, would that be sufficient?

**Comment by ernie** [comment]
@jtattermusch I'm happy to rebase to eliminate the conflicts, if you would like to put it in 1.3.x. Meanwhile, I'm happily using a custom build of 1.3.7 with this change without ill effects, and can wait until 1.4 for official support.

**Comment by ernie** [comment]
To add, I think the conflicts are an unfortunate side-effect of my forgetting, briefly, that this branch was tied to a PR when working on our internal fork.

**Comment by ernie** [comment]
@jtattermusch I eliminated the conflicts, just in case.

**Pull request closed without merging**
