### PR TITLE
Fix code formatting

### PR DESCRIPTION
**Pull request by jtattermusch**
sanity is currently broken

### CODE REVIEW

**Comment by murgatroid99** [comment]
I think you didn't update your submodules.

**Comment by jtattermusch** [comment]
@murgatroid99   I checked and I am pretty sure my submodules are up to date. What's the issue?

Also, I rebased onto upstream/master and pushed.

**Comment by murgatroid99** [comment]
The first change listed removes all of the files from the `LIBGOOGLE_BENCHMARK_SRC` Makefile target. That doesn't seem like a correct change, so I'm guessing that it happens if you don't have the google_benchmark submodule.

**Comment by jtattermusch** [comment]
@murgatroid99 I see now. there was a new submodule added which explains why `git submodule update` didn't pickup anything. Removed the regenerate project commit altogether and only kept code formatting.

**Comment by jtattermusch** [comment]
Superseded by #8728

**Pull request closed without merging**
