### PR TITLE
Delete unused header file string.h

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by vjpai** [comment]
This is ok to test

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by yang-g** [comment]
Should the line be removed instead? I do not see how it is needed as we are using grpc::string anyway..

**Comment by thinkerou** [comment]
@yang-g thanks, fixed.

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by vjpai** [comment]
Sorry. This PR is out-of-date. I couldn't merge it when it was fresh because we were having Jenkins testing issues and now it has other sanity/etc issues. I'll recreate it if it is still relevant. Thanks for the contribution!

**Pull request closed without merging**
