### PR TITLE
Add support for abstract unix domain sockets

### LINKED ISSUE #24638: Support null bytes in URI components
### Is your feature request related to a problem? Please describe.
 https://github.com/grpc/grpc/pull/24500 introduced unix sockets in the abstract namespace. However, abstract sockets may have arbitrary names while this only supports names that can be expressed as c strings (no null characters in the string).

### Describe the solution you'd like
We should support all valid abstract namespace socket names.

### Describe alternatives you've considered
We could not bother, since this probably doesn't limit any applications.

### Additional context
Requested by @markdroth

### PR DESCRIPTION
**Pull request by drfloob**
See `test/core/end2end/fixtures/h2_local_abstract_uds_percent_encoded.cc` for evidence that this works. I paused the tests in the debugger and confirmed that `lsof -U` showed abstract sockets in use. I also modified the `helloworld` examples (not in this PR) to use an abstract UDS `unix-abstract:arst%00.withEmbeddedNulls`, which worked as expected.

```
$  lsof -U
COMMAND       PID USER   FD   TYPE             DEVICE SIZE/OFF     NODE NAME
...
greeter_a 2059513 me      5u  unix 0x0000000000000000      0t0 13885774 @arst@.withEmbeddedNulls type=STREAM
greeter_a 2059513 me      8u  unix 0x0000000000000000      0t0 13885776 @arst@.withEmbeddedNulls type=STREAM
greeter_a 2059523 me      9u  unix 0x0000000000000000      0t0 13877853 type=STREAM
```

Fixes #24638 and #24821

@yashykt

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/27906)

### CODE REVIEW

**Review by veblush — COMMENTED** [review]
LGTM! Thank you for the PR!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27906#-:-MngvFKYDjK7VjPvrXfk:b-fb3a1i)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @markdroth)

**Review by veblush — APPROVED** [review]

**Comment by drfloob** [comment]
"All checks have passed". Headed out to buy a lottery ticket.

**Review by markdroth — COMMENTED** [review]
Sorry for not reviewing earlier.  Overall, this looks great!  Comments are all minor; feel free to address in a follow-up PR.

> Reviewed 23 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27906#-:-MnlfDAP96MV7Md9klQM:b-jx169g)* status: all files reviewed, 7 unresolved discussions

___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 95 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-Mnlc1TPAQHQxxkwdNTJ:-Mnlc1TQ3Nhmd-DgbbC-:b-cx6r3j) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L95)):*
> ```cpp
>   for (absl::string_view ith_path : absl::StrSplit(uri.path(), ',')) {
>     URI ith_uri(uri.scheme(), "",
>                 std::string(ith_path.data(), ith_path.length()), {}, "");
> ```

This change is not necessary.  Converting an `absl::string_view` to `std::string` already takes into account the length.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 861 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-Mnld_7S4ievSWA2xTLQ:-Mnld_7S4ievSWA2xTLR:bffyfk2) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/ext/transport/chttp2/server/chttp2_server.cc#L861)):*
> ```cpp
>   grpc_resolved_addresses* resolved = nullptr;
>   std::vector<grpc_error_handle> error_list;
>   std::string parsed_addr = URI::PercentDecode(absl::NullSafeStringView(addr));
> ```

I don't think `addr` can be null here.  If it was, the `strncmp()` call at the top of the function would cause a segfault.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 867 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-MnldEPzEe2M2cgnVNHt:-MnldEPzEe2M2cgnVNHu:b6mpj3o) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/ext/transport/chttp2/server/chttp2_server.cc#L867)):*
> ```cpp
>     if (absl::StartsWith(parsed_addr, kUnixUriPrefix)) {
>       error = grpc_resolve_unix_domain_address(
>           absl::StripPrefix(parsed_addr, kUnixUriPrefix), &resolved);
> ```

This is less efficient than the original code here, because it means that we're doing the `absl::StartsWith()` check twice.  But when we get here, we already know it has the right prefix, so there's no need to check it again.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 870 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-MnldUkNDIPuihWLJSO_:-MnldUkNDIPuihWLJSOa:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/ext/transport/chttp2/server/chttp2_server.cc#L870)):*
> ```cpp
>     } else if (absl::StartsWith(addr, kUnixAbstractUriPrefix)) {
>       error = grpc_resolve_unix_abstract_domain_address(
>           absl::StripPrefix(parsed_addr, kUnixAbstractUriPrefix), &resolved);
> ```

Same here.
___
*[src/core/lib/iomgr/tcp_posix.cc, line 1730 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-MnldsQ71tzwO-Jm-Q_e:-MnldsQ71tzwO-Jm-Q_f:b85xkpz) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/lib/iomgr/tcp_posix.cc#L1730)):*
> ```cpp
>                                tcp_tx_zerocopy_send_bytes_thresh);
>   tcp->base.vtable = &vtable;
>   tcp->peer_string = std::string(peer_string.data(), peer_string.size());
> ```

This can just be `std::string(peer_string)`.
___
*[src/core/lib/iomgr/tcp_windows.cc, line 524 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-Mnle-SM0rxMFQk2laAG:-Mnle-SM0rxMFQk2laAH:b-4p4ycq) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/lib/iomgr/tcp_windows.cc#L524)):*
> ```cpp
>     tcp->local_address = grpc_sockaddr_to_uri(&resolved_local_addr);
>   }
>   tcp->peer_string = std::string(peer_string.data(), peer_string.size());
> ```

`std::string(peer_string)`
___
*[src/core/lib/iomgr/unix_sockets_posix_noop.cc, line 37 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-MnleHm18XlInH3IF56a:-MnleHm18XlInH3IF56b:bttlros) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/lib/iomgr/unix_sockets_posix_noop.cc#L37)):*
> ```cpp
> 
> grpc_error_handle grpc_resolve_unix_domain_address(
>     /*name=*/absl::string_view, grpc_resolved_addresses** addresses) {
> ```

Nit: The syntax `/*param_name=*/type` makes sense for function calls, not for function declarations.  For declarations, it makes more sense to say `type /*param_name*/`.

**Review by drfloob — COMMENTED** [review]
Review appreciated, thanks for the improvements. I've addressed your comments here https://github.com/grpc/grpc/pull/27954

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27906#-:-MnlrXU5Bx8PHwuJdsLE:b-qdxff1)* status: all files reviewed, 7 unresolved discussions

___
*[src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc, line 95 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-Mnlc1TPAQHQxxkwdNTJ:-MnljwNWEQihGv31YQSD:bp6vo12) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.cc#L95)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This change is not necessary.  Converting an `absl::string_view` to `std::string` already takes into account the length.
</blockquote></details>

Addressing in another PR. Thanks for catching this.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 861 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-Mnld_7S4ievSWA2xTLQ:-MnlkfjkBxxCONZSoBPU:bp1w59e) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/ext/transport/chttp2/server/chttp2_server.cc#L861)):*
Good you pointed that out, because it's actually UB, not necessarily a segfault. From https://en.cppreference.com/w/cpp/string/byte/strncmp

> The behavior is undefined when access occurs past the end of either array lhs or rhs. The behavior is undefined when either lhs or rhs is the null pointer.

It's probably the case that this method has not been called with a nullptr or an addr with length < 9. But I'll add a nullptr check and length check for `addr` above for good measure, and remove the NulSafeStringView conversion.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 867 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-MnldEPzEe2M2cgnVNHt:-Mnlq_YC70r4JI-UxBwj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/ext/transport/chttp2/server/chttp2_server.cc#L867)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is less efficient than the original code here, because it means that we're doing the `absl::StartsWith()` check twice.  But when we get here, we already know it has the right prefix, so there's no need to check it again.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 870 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-MnldUkNDIPuihWLJSO_:-Mnlq_mr0eSS1P2dDDAj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/ext/transport/chttp2/server/chttp2_server.cc#L870)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/tcp_posix.cc, line 1730 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-MnldsQ71tzwO-Jm-Q_e:-MnlpV1j5K1YZhwgf-_r:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/lib/iomgr/tcp_posix.cc#L1730)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can just be `std::string(peer_string)`.
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/tcp_windows.cc, line 524 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-Mnle-SM0rxMFQk2laAG:-MnlpUEE5BTZ0PbnLvL1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/lib/iomgr/tcp_windows.cc#L524)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::string(peer_string)`
</blockquote></details>

Done.
___
*[src/core/lib/iomgr/unix_sockets_posix_noop.cc, line 37 at r2](https://reviewable.io/reviews/grpc/grpc/27906#-MnleHm18XlInH3IF56a:-MnlnxgF7lnalEAxx_FF:b60wi2g) ([raw file](https://github.com/grpc/grpc/blob/6f5f9534d47eb3032c7dbd3627bd4fcc2cbdf0a1/src/core/lib/iomgr/unix_sockets_posix_noop.cc#L37)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Nit: The syntax `/*param_name=*/type` makes sense for function calls, not for function declarations.  For declarations, it makes more sense to say `type /*param_name*/`.
</blockquote></details>

Fixed. I thought it was useful for `bugprone-argument-comment` (which would be nice to enable in our tidy checks), but that comment form doesn't help. I've fixed this, an others I had changed.

**Pull request merged**
