### PR TITLE
Backport #14904 to v1.10.x

### PR DESCRIPTION
**Pull request by ZhouyihaiDing**
It is the backport to #14904, which fix the persistent channel not working under the php-fpm mode.

### CODE REVIEW

**Comment by ZhouyihaiDing** [comment]
Bazel Opt build for C/C++: #13621

**Comment by tmatsuo** [comment]
I tested v1.10.x branch and observed that the persistent channel seems working. As far as I use PHP's builtin web server, I don't see any signs of memory leaks.

**Comment by tmatsuo** [comment]
Only concern is that, with debug-enabled PHP 7.2.4, my PHP program aborts with the following log:

```
php: /home/tmatsuo/.phpbrew/build/php-7.2.4/Zend/zend_hash.c:1162: zend_hash_str_del: Assertion `((ht)->gc.refcount == 1) || ((ht)->u.flags & (1<<6))' failed.
Aborted
```

Although, the situation is the same with gRPC extension 1.10.0, so it's not a new issue with this patch.

**Comment by ZhouyihaiDing** [comment]
Thanks @tmatsuo .
I am trying to install PHP 7.2.4 in an empty VM and see how can I fix it.
Can you please help me to test it with grpc-1.8.0? 
I am wondering is this introduced by memory leak fix or not before I set the environment and make test.

**Comment by tmatsuo** [comment]
Sure, I'll test it with 1.8.0 and let you know the result

**Comment by tmatsuo** [comment]
It's happening with 1.8.0 too.

**Comment by ZhouyihaiDing** [comment]
Hi @tmatsuo . 
I set a GCE VM with php 7.2.4-dev, but I am struggling installing grpc.so by pecl. I observe `php: symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/grpc.so: undefined symbol: pthread_once` and am trying to find out why.
But by building from the source, grpc.so doesn't abort.
Do you have something instructions like Dockerfile I can see if I do something wrong when installing the php binary? Currently I am following this [Dockerfile and change the checkout version](https://github.com/grpc/grpc/blob/5253c8f9a899450397a5e46e4923d01ac9a66a27/tools/dockerfile/interoptest/grpc_interop_php7/Dockerfile#L54) to 7.2.4.
Thank you!

**Comment by tmatsuo** [comment]
@ZhouyihaiDing The abort only happens with debug-enabled PHP binary. You have to compile PHP with --enable-debug.

**Comment by ZhouyihaiDing** [comment]
Thanks! 
I see the abort. I'll look into it.

**Comment by ZhouyihaiDing** [comment]
Seems there are many places have abort/segment fault in php 7.2.4-dev with `--enable-debug`. Not sure what causes it. Below is one of the place I find will abort:

`php -d extension=grpc.so $(which phpunit) -v --debug  --filter testPersistentChannelForceNewOldChannelIdle src/php/tests/unit_tests/ChannelTest.php`

This php code [createChannel with force_new](https://github.com/grpc/grpc/blob/master/src/php/tests/unit_tests/ChannelTest.php#L554), and related C extension abort command [here](https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/channel.c#L258).

`php_grpc_zend_hash_del(array_hash, "force_new", sizeof("force_new"));` will abort with:
```
Starting test 'ChannelTest::testPersistentChannelForceNewOldChannelIdle'.
php: /usr/local/src/php-7.2.4/Zend/zend_hash.c:1162: zend_hash_str_del: Assertion `((ht)->gc.refcount == 1) || ((ht)->u.flags & (1<<6))' failed.
Aborted (core dumped)
```

**Pull request merged**
