### PR TITLE
ASSERT vector size before directly accessing first element

### PR DESCRIPTION
**Pull request by rjshade**

### CODE REVIEW

**Comment by yang-g** [comment]
LGTM

**Comment by rjshade** [comment]
@yang-g is there anything I need to do here?

**Comment by yang-g** [comment]
LGTM

**Comment by yang-g** [comment]
Could you merge with head and push again?

**Comment by rjshade** [comment]
@yang-g done, ptal

**Comment by yang-g** [comment]
LGTM
Waiting for green

**Comment by rjshade** [comment]
@yang-g pretty sure this isn't causing build/test failures - what needs to be done to get it merged?

**Comment by kpayson64** [comment]
test this please

**Pull request merged**
