### PR TITLE
Updated SymbolTable to DefPool (#30247)

### PR DESCRIPTION
**Pull request by nikzayn**
In this PR, I have updated the naming convection of SymbolTable to DefPool.

Please do check if there are any other changes required from my end for this.

### CODE REVIEW

**Comment by markdroth** [comment]
You'll need to fix the CLA on your commit before we can look at this.

**Comment by veblush** [comment]
I think we should do along with a regular upb update and the further update is currently blocked by https://github.com/protocolbuffers/upb/issues/684.

**Comment by yashykt** [comment]
Sounds like this is no longer blocked on upb, but is now blocked on protobuf, since we need to upgrade the two at the same time.

**Comment by yashykt** [comment]
looks like the protobuf update is postponed to jan of next year

**Comment by yashykt** [comment]
Sounds like we want to have this change, but there are a bunch of upgrades that are needed before this goes through, and when those upgrades are made, we'll need to make many more changes. So, given that this PR by itself is not gonna make it through, we are gonna close it.

**Pull request closed without merging**
