### PR TITLE
Improve grpclb trace logging.

### PR DESCRIPTION
**Pull request by markdroth**
Improve grpclb trace logging messages.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.2%     +32 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           +32  +0.2%
      +2.1%     +32 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::OnBalancerMessageReceiv     +32  +2.1%
      +1.4%      +8 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::SendClientLoadReportLoc      +8  +1.4%
      +0.7%      +8 grpc_core::(anonymous namespace)::GrpcLb::CreateOrUpdateRoundRobinPolicyLocked() [cl      +8  +0.7%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  +0.0%    +152 [None]                                                                                   -32  -0.0%

  +0.0%    +184 TOTAL                                                                                      0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,026,958      Total (>)      2,026,850

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,325,183      Total (<)     11,325,195

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: #16497 #17463 #17526

**Pull request merged**
