### PR TITLE
Load default roots.pem in PHP via grpc_set_ssl_roots_override_callback

### PR DESCRIPTION
**Pull request by thinkerou**
Attempts to fixs this #5711.

### CODE REVIEW

**Comment by murgatroid99** [comment]
Can you please send this PR without all of the irrelevant commits? All of the changes for this PR are in the second-to-last commit.

**Comment by thinkerou** [comment]
@murgatroid99 I have cleaned up all of the extra commits.

**Comment by stanley-cheung** [comment]
LGTM @murgatroid99 is the user of `gpr_malloc` appropriate here?

**Comment by murgatroid99** [comment]
I think so. This change is copied pretty much verbatim from the corresponding Node change.

**Pull request merged**
