### PR TITLE
Stop checking for pre-c++11 compilers since these are no longer supported

### PR DESCRIPTION
**Pull request by vjpai**
The previous code made it look like pre-C++11 compilers were still supported at master. They are only supported at 1.0.x , and this change reflects that to avoid user confusion such as #10948 .

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by vjpai** [comment]
Ok, this just got interesting. Now that core accepts C++ , this change that is intended to affect the C++ API takes down the core portability tests which still test gcc-4.4 and 4.6. @ctiller : is the intention that core will also require gcc-4.8+ ? If so, this would be a good time to change the Portability tests dockerfile (which I can do as another commit in this PR)

**Comment by vjpai** [comment]
Test failures : #9542

**Comment by ctiller** [comment]
I think the expectation is that core will start to require gcc-4.8+, yes.

**Comment by vjpai** [comment]
Ok, I think I can strip out those portability tests in a different PR and then wait until that one lands before merging this one - for sane history.

**Comment by vjpai** [comment]
Rebasing master after merger of #11066 . Diff unchanged.

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by vjpai** [comment]
Portability is reporting a failure with "SUCCESS: All tests passed". Infrastructural.

**Pull request merged**
