### PR TITLE
Updated Abseil to LTS 20211102.0

### PR DESCRIPTION
**Pull request by veblush**

### CODE REVIEW

**Comment by veblush** [comment]
[grpc_build_artifacts_multiplatform](https://fusion2.corp.google.com/invocations/3710b54c-7472-4c72-b4f9-b3db45265cc0): running

**Comment by veblush** [comment]
Hmm this is almost green except bazel test on mac. ([log](https://source.cloud.google.com/results/invocations/7ce2d359-01ad-49b7-8d6c-4b1d8a8938f5/targets))

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/cpp/end2end/xds:xds_end2end_test
-----------------------------------------------------------------------------
dyld: malformed mach-o: load commands size (33104) > 32768
```

**Comment by veblush** [comment]
This PR passed the `grpc_build_artifacts_multiplatform` and mac doesn't observe the above `bazel test on mac` issue any more so this is ready to get merged.

**Review by jtattermusch — APPROVED** [review]
LGTM once you're confident this doesn't introduce any regressions.

**Comment by veblush** [comment]
To wake up EasyCLA, I'm going to close and reopen this PR.

**Comment by only-test-linux** [comment]
QMAKE_CXXFLAGS += pkg-config --cflags= protobuf grpc
QMAKE_CXXFLAGS += -std=c++11
QMAKE_LIBS += pkg-config --libs= protobuf grpc++ -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -ldl

**Pull request merged**
