### PR TITLE
[cpp][absl] Include str_cat.h for StrCat

### PR DESCRIPTION
**Pull request by wltu**
Explicitly include str_cat.h for StrCat to make sure there are no build failures.

After building to
https://github.com/abseil/abseil-cpp/commit/9e1789ffea47fdeb3133aa42aa9592f3673fb6ed for abseil-cpp, the grpc repo won't build due to missing StrCat definition. Include the str_cat.h before grpc start building with the updated absl-cpp release.

Tested:
Checked the missing header with
```
files=($(git grep StrCat | awk -F ':' '{print $1}'))

for file in "${files[@]}"
do
  if [[ "${file}" =~ "third_party" ]];
  then
    continue
  fi
  cat "${file}" | grep "str_cat.h"  > /dev/null && continue
  echo "${file}"
done
```

All StrCat usage now include the header.

### CODE REVIEW

**Comment by wltu** [comment]
oh, I don't think I have permission to add `release notes: no` as the label, or maybe I just don't know how to do it.

**Comment by veblush** [comment]
> oh, I don't think I have permission to add `release notes: no` as the label, or maybe I just don't know how to do it.

No worries. I added the label.

**Comment by ctiller** [comment]
I think we're gonna want a `// IWYU pragma: keep` alongside each of these

**Comment by wltu** [comment]
> I think we're gonna want a `// IWYU pragma: keep` alongside each of these

I have updated to include the IWYU comment.

**Comment by yashykt** [comment]
please resolve conflicts

**Comment by wltu** [comment]
> please resolve conflicts

Resolved.

**Comment by yashykt** [comment]
please run `/tools/distrib/sanitize.sh`

**Comment by yashykt** [comment]
oh, the error's actually 
```
src/core/lib/iomgr/tcp_posix.cc:49:1: error: duplicate include [readability-duplicate-include,-warnings-as-errors]
#include "absl/strings/str_cat.h"  // IWYU pragma: keep
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Suppressed 7371 warnings (7322 in non-user code, 49 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
1 warning treated as error
```

**Comment by yashykt** [comment]
I believe we've removed IWYU anyway, so once you resolve conflicts again, we should be able to merge it.

**Comment by wltu** [comment]
> I believe we've removed IWYU anyway, so once you resolve conflicts again, we should be able to merge it. Sorry for the churn.

Sorry for the delay, I have pushed another revision of this. Hopefully I didn't miss anything.

**Pull request closed without merging**
