### PR TITLE
Fix flow control bug [Different attempt]

### PR DESCRIPTION
**Pull request by ncteisen**
WIP

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +16 [None]                                                           +8  +0.0%
  +0.0%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +16  +0.0%
      +1.2%      +8 [Unmapped]                                                       +8  +1.2%
      +0.2%      +8 perform_stream_op_locked                                         +8  +0.2%

  +0.0%     +32 TOTAL                                                           +24  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by srini100** [comment]
Fixes #12383

**Pull request closed without merging**
