### PR TITLE
Switch Server back to lockfree stack

### PR DESCRIPTION
**Pull request by kpayson64**
https://github.com/grpc/grpc/commit/53e6b56e32c79ba401a67cb349519c12991539cc
Was causing hangs for tensorflow.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Sanity isn't really happy - I was kind of expecting this.

**Comment by nicolasnoble** [comment]
Did you regenerate the project files ?

**Comment by nicolasnoble** [comment]
Blah, clang format is the one that fails.

**Comment by kpayson64** [comment]
Ran clang-format.

**Pull request merged**
