### PR TITLE
Update protobuf to v3.19.5 on v1.46.x

### PR DESCRIPTION
**Pull request by gnossen**

### CODE REVIEW

**Review by nicolasnoble — APPROVED** [review]

**Comment by gnossen** [comment]
@nicolasnoble 👋

**Comment by gnossen** [comment]
There appears to be a PHP memory leak [here](Basic Tests PHP Linux ). It seems to be unrelated to the protobuf update, but it's concerning nonetheless, especially since this is our LTS branch.

@stanley-cheung Can you please take a look?

**Comment by gnossen** [comment]
@apolcyn One more I need your sign-off on: https://source.cloud.google.com/results/invocations/cc7e5980-3443-4dde-8def-542a426885ef/log

**Comment by stanley-cheung** [comment]
PHP issue seems to be the same as #28390

**Comment by gnossen** [comment]
##  Python Tests

Same framework-level race condition as in https://github.com/grpc/grpc/pull/31031

## Interop tests

[Same as in 1.48.x](https://github.com/grpc/grpc/pull/31029#issuecomment-1249964300)

## Sample Fuzzers

Failed due to removed internal Kokoro config:

```
com.google.devtools.kokoro.config.ConfigException: Couldn't find build configuration file grpc_sample_fuzzers.cfg or grpc_sample_fuzzers.gcl under /tmp/workspace/workspace/grpc/core/pull_request/linux/grpc_sample_fuzzers/src/github/grpc/tools/internal_ci/linux/pull_request.
	at com.google.devtools.kokoro.config.BuildConfigReader.lambda$read$2(BuildConfigReader.java:54)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.google.devtools.kokoro.config.BuildConfigReader.read(BuildConfigReader.java:51)
	at com.google.devtools.kokoro.jenkins.plugin.kokorojob.store.NodeBuildConfigReader.invoke(NodeBuildConfigReader.java:39)
	at com.google.devtools.kokoro.jenkins.plugin.kokorojob.store.NodeBuildConfigReader.invoke(NodeBuildConfigReader.java:13)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
```

**Pull request merged**
