### PR TITLE
[csharp] Fix csharp_ubuntu2204_x64 docker image

### PR DESCRIPTION
**Pull request by tonydnewell**
Fix the docker image for C# distribution tests - csharp_ubuntu2204_x64 

The package that installed the .NET 7.0 SDK is missing setting up links and thus the `dotnet` command cannot find the SDK. Setting this links has been added to the dockerfile.

**NOTE**: I'm unable to update `tools/dockerfile/distribtest/csharp_ubuntu2204_x64.current_version` as I don't have access to the artifact registry.

### CODE REVIEW

**Comment by tonydnewell** [comment]
@apolcyn I've updated the dockerfile for csharp_ubuntu2204_x64 - but I'm unable to update the version file as I don't have access the the artifact registry

**Comment by apolcyn** [comment]
@tonydnewell sent you https://github.com/tonydnewell/grpc/pull/3

**Comment by apolcyn** [comment]
@tonydnewell sorry can you please format the distrib test targets python script? 

"Sanity checks" is failing:

```
blackSuccessfully installed black-23.3.0 click-8.1.7 importlib-metadata-6.7.0 mypy-extensions-1.0.0 packaging-23.2 pathspec-0.11.2 platformdirs-4.0.0 tomli-2.0.1 typed-ast-1.5.5 typing-extensions-4.7.1 zipp-3.15.0+ black_virtual_environment/bin/python -m black --config=black.toml --check examples src test tools setup.pywould reformat /var/local/git/grpc/tools/run_tests/artifacts/distribtest_targets.pyOh no!   1 file would be reformatted, 595 files would be left unchanged.
--


<mat-paginator _ngcontent-ng-c2083210054="" role="group" class="mat-mdc-paginator gmat-mdc-paginator ng-star-inserted" style="margin: 0px; padding: 0px; box-sizing: border-box; --mat-paginator-container-background-color: var(--page-bg); --mat-paginator-container-text-color: var(--text-default); --mat-paginator-enabled-icon-color: var(--text-secondary); --mat-paginator-disabled-icon-color: var(--text-disabled); display: block; -webkit-font-smoothing: antialiased; color: var(--mat-paginator-container-text-color); background-color: var(--mat-paginator-container-background-color); font-family: var(--mat-paginator-container-text-font); line-height: var(--mat-paginator-container-text-line-height); font-size: var(--mat-paginator-container-text-size); font-weight: 400; letter-spacing: var(--mat-paginator-container-text-tracking); --mat-form-field-container-height: var(--mat-paginator-form-field-container-height); --mat-form-field-container-vertical-padding: var(--mat-paginator-form-field-container-vertical-padding); border-top: 1px solid var(--hairline); bottom: 0px; height: 0px; left: 0px; overflow: hidden; position: fixed; right: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mat-mdc-paginator-outer-container" style="margin: 0px; padding: 0px; box-sizing: border-box; display: flex;"><div class="mat-mdc-paginator-container" style="margin: 0px; padding: 0px 8px; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; flex-wrap: wrap; width: 1667px; min-height: var(--mat-paginator-container-size);"><div class="mat-mdc-paginator-page-size ng-star-inserted" style="margin: 0px 8px 0px 0px; padding: 0px; box-sizing: border-box; display: flex; align-items: baseline;"><br class="Apple-interchange-newline">
```

**Comment by tonydnewell** [comment]
@apolcyn python formatting fixed

**Review by apolcyn — APPROVED** [review]

**Pull request closed without merging**
