### PR TITLE
Add identity to static metadata accept-encodings bitmasks

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by dgquintas** [comment]
Green!

**Comment by ctiller** [comment]
LGTM

**Comment by jtattermusch** [comment]
@dgquintas  If this is critical to be in today's google-internal import, I'm fine with merging before travis tests finish (if we are 100% sure this doesn't break ObjC of course).

**Comment by jtattermusch** [comment]
csharp coverage failure is a known flake.

**Pull request merged**
