### PR TITLE
Cherrypick connectivity fixes into release branch

### PR DESCRIPTION
**Pull request by jcanizales**
These PRs were merged into the master branch, but should have been merged into the release branch instead:

- #5736
- #5720
- #5893
- #5749
- #5722

### CODE REVIEW

**Comment by jcanizales** [comment]
@pquerna , @nicolasnoble I think the GoogleBot wants you guys to comment that you're ok with your commits going into the release branch.

**Comment by pquerna** [comment]
@jcanizales Happy to do so, is there any documentation on what you are supposed to say to GoogleBot to do this?  I couldn't find anything via a google search.

**Comment by jcanizales** [comment]
I have no idea, to be honest! @willnorris: Is commenting "I'm OK with this", or similar, enough to satisfy the GoogleBot here?

**Comment by jcanizales** [comment]
(Maybe just commenting is enough?)

**Comment by jcanizales** [comment]
@makdharma - the test failures were flakes. I already pinged the corresponding BUILDPONY issues. Running the tests again now.

**Comment by willnorris** [comment]
nothing will "satisfy" googlebot to the extent that it will change the CLA status.  (see [go/cla#github-consent](http://go/cla#github-consent))

**Comment by pquerna** [comment]
I have a CLA on file, and previously the googlebot recongized it:
https://github.com/grpc/grpc/pull/5736

Don't see what I can do to change the commit status in this PR though.

**Comment by jcanizales** [comment]
@makdharma I say we merge. CLAs are fine despite what GoogleBot says, and the Jenkins failures are flakes whose fixes we aren't going to backport to the release branch.

**Comment by jcanizales** [comment]
Ping

**Comment by makdharma** [comment]
Merged.

**Pull request merged**
