### PR TITLE
basic tcp_trace support for windows

### PR DESCRIPTION
**Pull request by jtattermusch**
Currently printing read and write payloads only works on unix (implemented in tcp_posix.cc).
Adding this support to windows is useful for debugging and good for consistency.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,410      Total (=)      2,020,410

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,174,080      Total (<)     11,174,081

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
This has been already merged into v1.17.x as https://github.com/grpc/grpc/pull/17378 (and will be upmerged to master later).

**Comment by jtattermusch** [comment]
This was upmerged to master as part of #17423

**Pull request closed without merging**
