### PR TITLE
PF: Check connectivity state before watching

### LINKED ISSUE #15514: Unexpected GOAWAY in Ruby client
### What version of gRPC and what language are you using?

* Server: go with grpc-go 1.7.0
* Client: ruby with grpc 1.10.0

I've seen the same behaviour with a newer server (grpc-go 1.12.0) and any Ruby version >= 1.8.0 up to the latest release (1.12.0).
 
### What operating system (Linux, Windows, …) and version?

* macOS 10.13.4
* Ubuntu 14.04 w/ 4.4.0-124-generic kernel
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

* go 1.10.2
* ruby 2.4.2
 
### What did you do?

We have:
* Multiple exposed gRPC services
* A Go server with a non-infinite [`MaxConnectionIdle`](https://godoc.org/google.golang.org/grpc/keepalive#ServerParameters) time
* A Ruby client that calls multiple of the services, potentially waiting more than the `MaxConnectionIdle` time between requests

### What did you expect to see?
 
Successful requests regardless of how much time lapses between requests from the client (assuming that there are no unrelated failures).
 
### What did you see instead?
 
The client sometimes fails with `GOAWAY received`, e.g.:

```
/Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 13:GOAWAY received (GRPC::Internal)
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:180:in `attach_status_results_and_complete_call'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:372:in `request_response'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from client.rb:21:in `increment'
	from client.rb:42:in `main'
	from client.rb:45:in `<main>'
```
 
### Anything else we should know about your project / environment?

I've made a [demo server/client](https://github.com/iredelmeier/goaway) that demonstrates the failure. (Please let me know if there are any issues running it!)

Some other things:
* I haven't been able to reproduce the error in go, python, or node
* The bug seems to only occur when there are **multiple services**, and the time lapse happens between them - something along the lines of:
  * Request to service A receives a GOAWAY, creates a new connection, and ultimately succeeds
  * Nothing happens for some period of time
  * Request to service B receives a GOAWAY and can't sort itself out
* It seems like the bug was introduced in [#ccfdfb3a41](https://github.com/grpc/grpc/commit/ccfdfb3a41), which looks to us like a pretty surprising culprit!! Preliminary messing around with the change didn't fix it, but we didn't delve too far into the commit.

### PR DESCRIPTION
**Pull request by AspirinSJL**
Fix #15514. This is extracted from the initial attempt https://github.com/grpc/grpc/pull/16176. This PR is much simpler but does fix the problem.

Instead of always starting a subchannel from `IDLE`, we will check the current connectivity state of a subchannel and start watching the connectivity change from that state. With this change, if the current state of a subchannel is `TRANSIENT_FAILURE`, we will try connecting to it first and determine its real state by the connection result.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/16306)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +368 [None]                                                                               +1.44Ki  +0.0%
      +0.0%    +336 [Unmapped]                                                                           +1.41Ki  +0.0%
       +17%      +8 vtable for grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData         +8   +17%
       +17%      +8 vtable for grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData           +8   +17%
       +17%      +8 vtable for grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::R      +8   +17%
       +17%      +8 vtable for grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::Pi      +8   +17%
  +5.0%    +640 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +640  +5.0%
      [NEW]    +897 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +897  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::StartConnectiv    +200  [NEW]
       +13%     +37 [Unmapped]                                                                               +37   +13%
      +2.5%      +8 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc      +8  +2.5%

  +0.1%   +1008 TOTAL                                                                                +2.06Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,951,592      Total (>)      1,950,932

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,617,434       Core (>)      3,615,418

10,671,344      Total (>)     10,669,329


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +352 [None]                                                                               +1.41Ki  +0.0%
      +0.0%    +320 [Unmapped]                                                                           +1.38Ki  +0.0%
       +17%      +8 vtable for grpc_core::(anonymous namespace)::RoundRobin::RoundRobinSubchannelData         +8   +17%
       +17%      +8 vtable for grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData           +8   +17%
       +17%      +8 vtable for grpc_core::SubchannelData<grpc_core::(anonymous namespace)::RoundRobin::R      +8   +17%
       +17%      +8 vtable for grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::Pi      +8   +17%
  +4.3%    +544 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +544  +4.3%
      [NEW]    +812 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +812  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::StartConnectiv    +200  [NEW]
      +9.0%     +26 [Unmapped]                                                                               +26  +9.0%
      +2.5%      +8 grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubc      +8  +2.5%

  +0.1%    +896 TOTAL                                                                                +1.95Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,951,584      Total (>)      1,950,932

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,617,434       Core (>)      3,615,418

10,671,347      Total (>)     10,669,332


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +224 [None]                                                                                  +816  +0.0%
  +3.5%    +448 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +448  +3.5%
      [NEW]    +729 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +729  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::CheckConnectiv    +200  [NEW]
      +7.3%     +21 [Unmapped]                                                                               +21  +7.3%

  +0.0%    +672 TOTAL                                                                                +1.23Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,951,347      Total (>)      1,950,932

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,616,466       Core (>)      3,615,418

10,663,195      Total (>)     10,662,142


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +120 [None]                                                                               +4.88Ki  +0.1%
  +2.8%    +352 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +352  +2.8%
      [NEW]    +636 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +636  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::CheckConnectiv    +200  [NEW]
      +5.6%     +16 [Unmapped]                                                                               +16  +5.6%
      +0.7%      +2 grpc_core::(anonymous namespace)::PickFirst::PickLocked                                   +2  +0.7%

  +0.0%    +472 TOTAL                                                                                +5.23Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,986      Total (>)      1,952,734

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,617,538       Core (>)      3,616,490

10,664,631      Total (>)     10,663,581


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
Ah, thanks for bumping that up. With all the things going on it went down my list. I'll try to get that PR merged, with a test, ASAP.

**Comment by dgquintas** [comment]
I've just updated #16054

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +120 [None]                                                                               +4.88Ki  +0.1%
  +2.8%    +352 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +352  +2.8%
      [NEW]    +636 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +636  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::CheckConnectiv    +200  [NEW]
      +6.3%     +18 [Unmapped]                                                                               +18  +6.3%

  +0.0%    +472 TOTAL                                                                                +5.23Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,998      Total (>)      1,952,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,617,710       Core (>)      3,616,662

10,664,797      Total (>)     10,663,751


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +120 [None]                                                                               +4.88Ki  +0.1%
  +2.8%    +352 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  +352  +2.8%
      [NEW]    +636 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessUnselec    +636  [NEW]
      [NEW]    +200 grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::CheckConnectiv    +200  [NEW]
      +6.3%     +18 [Unmapped]                                                                               +18  +6.3%

  +0.0%    +472 TOTAL                                                                                +5.23Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,998      Total (>)      1,952,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,617,710       Core (>)      3,616,662

10,664,796      Total (>)     10,663,741


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
- Basic Tests MacOS [opt] (internal CI): https://github.com/grpc/grpc/issues/16380
- Bazel ASAN build for C/C++: https://github.com/grpc/grpc/issues/16379
- Bazel TSAN build for C/C++: https://github.com/grpc/grpc/issues/16379

**Pull request merged**
