### PR TITLE
Speedup linux portability build_only tests

### PR DESCRIPTION
**Pull request by jtattermusch**
- remove gcc5.3 portability test (we test among others with gcc4.9 and gcc8.3, which should give us enough coverage)
- remove GRPC_DNS_RESOLVER=ares portability test since it 1. does nothing when running --build_only test 2. ares is the default resolver on linux anyway.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Duration BEFORE  1h 25min  AFTER 1h 10min

**Review by veblush — APPROVED** [review]
LGTMed for removing gcc5.3.

**Comment by jtattermusch** [comment]
@apolcyn  can you confirm that removing GRPC_DNS_RESOLVER=ares test is fine? (AFAICT its useless).

**Comment by jtattermusch** [comment]
Known failures:
- interop tests: b/213229890

**Review by apolcyn — APPROVED** [review]

**Pull request merged**
