### PR TITLE
Ensure `libboringssl.a` is always built for Python

### PR DESCRIPTION
**Pull request by lidizheng**
Issue https://github.com/grpc/grpc/issues/17002

After discussing with @nicolasnoble , it is important to keep the BoringSSL inside the gRPC Python distribution. It is much easier to link inside the Python distribution than linking to the system's library, and may potentially create problems in Windows. So, instead of risking to build upon arbitrary dependencies, it seems more sensible to ensure `libboringssl.a` is always built for gRPC Python.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Seems like macos aftifacts are failing :-)

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,303      Total (=)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,999      Total (>)     11,115,995

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,303      Total (=)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,993      Total (<)     11,115,994

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,303      Total (=)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,993      Total (>)     11,115,986

 No significant differences in binary sizes


```

**Comment by Mottl** [comment]
Go is not installed (Artifact Build MacOS (internal CI)):

```
CMake Error at third_party/boringssl/CMakeLists.txt:38 (message):
304
  Could not find Go
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,649      Total (=)      2,015,649

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,198      Total (>)     11,116,193

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,649      Total (=)      2,015,649

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,196      Total (>)     11,116,189

 No significant differences in binary sizes


```

**Comment by lidizheng** [comment]
Interestingly, this trunk of code specified for macOS was introduced by https://github.com/grpc/grpc/pull/10427.

**Pull request merged**
