### PR TITLE
Add ChannelBase, change ClientBase constructor argument

### PR DESCRIPTION
**Pull request by JamesNK**
* Adds ChannelBase
* As a **breaking change**, ClientBase constructor now takes a ChannelBase value instead of Channel. This is optional. An alternative non-breaking approach would be to update client code gen to add a ChannelBase constructor to generated clients that use LiteClientBase.

Good things about ClientBase using ChannelBase instead of Channel:
* ClientBase can be moved to Grpc.Core.Api (not done yet in this PR)
* LiteClientBase can be removed (not done yet in this PR)
* Client packages like Grpc.Reflection can now depend Grpc.Core.Api. They will work with C-Core client and .NET HttpClient client.

Bad things:
* Binary breaking change. However source code can be recompiled without changes.

Before going further I'd like to get a decision on whether the breaking change is desirable.

@jtattermusch @JunTaoLuo @shirhatti

### CODE REVIEW

**Comment by mgravell** [comment]
> Binary breaking change. However source code can be recompiled without changes.

If this can happen at the same time as the `IAsyncEnumerable<T>` fix, I don't see that as a problem - that's *already* a: necessary, and b: hard breaking

**Comment by jtattermusch** [comment]
I am quite liking this idea of introducing ChannelBase and I think this particular breaking change is worth doing:
- the main benefit is establishing a common concept of a channel in both existing gRPC implementations and I like that it does it in a logical and clean way.
- while breaking change, the change is "recompile only" and we will already require rebuilding because of the System.Interactive.Async change, so there is no extra value to be paid by the users.

Because this is a breaking change though, I think I'm going to come up with a short proposal for the https://github.com/grpc/proposal repository, where I'll summarize the changes and their pros/cons.

**Comment by JamesNK** [comment]
Since we like the ChannelBase change I've finished the PR:
* Move ClientBase to Grpc.Core.Api
* Change codegen to use ChannelBase
* Reference Grpc.Core.Api from Grpc.Reflection and Grpc.HealthCheck

**Comment by jtattermusch** [comment]
Pushed a clang format fix and regenerated the C# protos based on the change to grpc_csharp_plugin

**Pull request merged**
