### PR TITLE
Fix #2275 (Make sure PHP example can be run with Apache)

### LINKED ISSUE #2275: Make sure PHP example can be run with Apache
Test case: Set up Apache server. User hit webserver asking to execute some PHP scripts. Apache invokes PHP (via a fastCGI service). The PHP script initiates a gRPC client, and tries to make connection to a gRPC server.

### PR DESCRIPTION
**Pull request by bjori**
Normal constants are cleaned up during RSHUTDOWN.

We must explicitly mark these as PERSISTENT so they survive multiple requests

### CODE REVIEW

**Comment by bjori** [comment]
I signed it!

**Comment by stanley-cheung** [comment]
I am on this. Thank you very much for your contribution!

The fix appears to be working - I will do more testing and merge accordingly.

**Comment by stanley-cheung** [comment]
I have done these testing:
 * in Debian
 * in Mac OS X
 * as a docker image

All looking good!

**Comment by stanley-cheung** [comment]
Again, Thanks @bjori for your contribution!

**Pull request merged**
