### PR TITLE
adding content-type to the example response

### PR DESCRIPTION
**Pull request by stevej**
This is to bring the Response up to date with the protocol ABNF.

Note: I have not yet contributed a CLA, I am working with my bosses to get a Corporate CLA in place.

### CODE REVIEW

**Comment by stevej** [comment]
Ok, the CLA is signed. It's a corporate CLA and the company name is Buoyant, Inc.

**Comment by ejona86** [comment]
I don't see the CLA yet for Bouyant. Apparently it can take a few days. I can check again on Monday.

Thanks for noticing and the fix!

**Comment by ejona86** [comment]
Still not there. I checked yesterday morning and this morning and still don't see it. I'll give it one more day before starting to talk to people about its status, since it's only been one full business day at this point.

**Comment by stevej** [comment]
One small note, the CLA was filed as 'Buoyant, Inc'

**Pull request merged**
