### PR TITLE
Make lb_calld Orphanable

### PR DESCRIPTION
**Pull request by AspirinSJL**
C++ conversion of `GlbLbCallData`.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/14331)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%    +494 [None]                                                                               +9.51Ki  +0.2%
      +0.1%    +414 [Unmapped]                                                                           +9.43Ki  +0.2%
      [NEW]     +40 vtable for (anonymous namespace)::GlbLbCallData                                          +40  [NEW]
      [NEW]     +40 vtable for grpc_core::InternallyRefCountedWithTracing                                    +40  [NEW]
  +0.2%     +26 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           +26  +0.2%
      [NEW] +1.50Ki rr_handover_locked(glb_lb_policy*) [clone .part.25]                                  +1.50Ki  [NEW]
     +11e2% +1.36Ki query_for_backends_locked                                                            +1.36Ki +11e2%
      [NEW] +1.31Ki (anonymous namespace)::GlbLbCallData::OnBalancerMessageReceivedLocked                +1.31Ki  [NEW]
      [NEW]    +801 build_lb_channel_args(grpc_lb_addresses const*, grpc_fake_resolver_response_generato    +801  [NEW]
      [NEW]    +695 (anonymous namespace)::GlbLbCallData::OnBalancerStatusReceivedLocked                    +695  [NEW]
      [NEW]    +531 (anonymous namespace)::GlbLbCallData::SendClientLoadReportLocked                        +531  [NEW]
      [NEW]    +210 extract_backend_addresses_locked(grpc_lb_addresses const*) [clone .isra.3]              +210  [NEW]
      [NEW]    +170 (anonymous namespace)::GlbLbCallData::~GlbLbCallData                                    +170  [NEW]
      [NEW]    +120 (anonymous namespace)::GlbLbCallData::ScheduleNextClientLoadReportLocked                +120  [NEW]
      [NEW]    +109 (anonymous namespace)::GlbLbCallData::ClientLoadReportDoneLocked                        +109  [NEW]
      [NEW]    +105 (anonymous namespace)::GlbLbCallData::OnInitialRequestSentLocked                        +105  [NEW]
      [NEW]     +88 (anonymous namespace)::GlbLbCallData::Orphan                                             +88  [NEW]
      [NEW]     +87 (anonymous namespace)::GlbLbCallData::MaybeSendClientLoadReportLocked                    +87  [NEW]
      [NEW]     +47 grpc_core::Orphanable::Orphan                                                            +47  [NEW]
      [NEW]     +14 (anonymous namespace)::GlbLbCallData::~GlbLbCallData                                     +14  [NEW]
      [NEW]      +9 grpc_core::InternallyRefCountedWithTracing::~InternallyRefCountedWithTracing              +9  [NEW]
      +2.9%      +8 glb_lb_channel_on_connectivity_changed_cb                                                 +8  +2.9%
      [NEW]      +2 grpc_core::InternallyRefCountedWithTracing::~InternallyRefCountedWithTracing              +2  [NEW]

  +0.0%    +520 TOTAL                                                                                +9.53Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%    +494 [None]                                                                               +9.51Ki  +0.2%
      +0.1%    +414 [Unmapped]                                                                           +9.43Ki  +0.2%
      [NEW]     +40 vtable for (anonymous namespace)::GlbLbCallData                                          +40  [NEW]
      [NEW]     +40 vtable for grpc_core::InternallyRefCountedWithTracing                                    +40  [NEW]
  +0.2%     +26 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                           +26  +0.2%
      [NEW] +1.50Ki rr_handover_locked(glb_lb_policy*) [clone .part.25]                                  +1.50Ki  [NEW]
     +11e2% +1.36Ki query_for_backends_locked                                                            +1.36Ki +11e2%
      [NEW] +1.31Ki (anonymous namespace)::GlbLbCallData::OnBalancerMessageReceivedLocked                +1.31Ki  [NEW]
      [NEW]    +801 build_lb_channel_args(grpc_lb_addresses const*, grpc_fake_resolver_response_generato    +801  [NEW]
      [NEW]    +695 (anonymous namespace)::GlbLbCallData::OnBalancerStatusReceivedLocked                    +695  [NEW]
      [NEW]    +531 (anonymous namespace)::GlbLbCallData::SendClientLoadReportLocked                        +531  [NEW]
      [NEW]    +210 extract_backend_addresses_locked(grpc_lb_addresses const*) [clone .isra.3]              +210  [NEW]
      [NEW]    +170 (anonymous namespace)::GlbLbCallData::~GlbLbCallData                                    +170  [NEW]
      [NEW]    +120 (anonymous namespace)::GlbLbCallData::ScheduleNextClientLoadReportLocked                +120  [NEW]
      [NEW]    +109 (anonymous namespace)::GlbLbCallData::ClientLoadReportDoneLocked                        +109  [NEW]
      [NEW]    +105 (anonymous namespace)::GlbLbCallData::OnInitialRequestSentLocked                        +105  [NEW]
      [NEW]     +88 (anonymous namespace)::GlbLbCallData::Orphan                                             +88  [NEW]
      [NEW]     +87 (anonymous namespace)::GlbLbCallData::MaybeSendClientLoadReportLocked                    +87  [NEW]
      [NEW]     +47 grpc_core::Orphanable::Orphan                                                            +47  [NEW]
      [NEW]     +14 (anonymous namespace)::GlbLbCallData::~GlbLbCallData                                     +14  [NEW]
      [NEW]      +9 grpc_core::InternallyRefCountedWithTracing::~InternallyRefCountedWithTracing              +9  [NEW]
      +2.9%      +8 glb_lb_channel_on_connectivity_changed_cb                                                 +8  +2.9%
      [NEW]      +2 grpc_core::InternallyRefCountedWithTracing::~InternallyRefCountedWithTracing              +2  [NEW]

  +0.0%    +520 TOTAL                                                                                +9.53Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__0.counters.new: 1
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_MinSockPair__0.counters.old: 1


[microbenchmarks] Performance differences noted:
Benchmark                            cpu_time    real_time
-----------------------------------  ----------  -----------
BM_ClosureInitAgainstCombiner        -33%        -33%
BM_ClosureInitAndRun                 +6%         +6%
BM_ErrorGetStatusCode<ErrorNone>     -6%         -6%
BM_ErrorGetStatusCode<SimpleError>   -7%         -7%
BM_ErrorStringRepeatedly<ErrorNone>  -5%         -5%
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_MinSockPair__0.opt.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
This looks pretty good!  My comments are all fairly minor.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 134 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4fz9DQVCVRneO_91EF:-L4fz9DQVCVRneO_91EG:b4ie9zt) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L134)):*
> ```cpp
> 
> namespace {
> class GlbLbCallData;
> ```

Let's keep these structs and classes defined here, rather than moving them below and needing forward declarations here.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 162 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g7Sb9s6XiOJ8vou2N:-L4g7Sb9s6XiOJ8vou2O:bhwmsy7) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L162)):*
> ```cpp
>    * is shutting down, or the LB call has ended). A non-NULL lb_calld always
>    * contains a non-NULL lb_call_. */
>   GlbLbCallData* lb_calld;
> ```

I think we'll need to change this to be an `OrphanablePtr<>` as part of merging the changes from #14221 (which I plan to merge later today).

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 277 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4fyfZjKgaGonZKSHzH:-L4fyfZjKgaGonZKSHzI:b-c6ja9y) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L277)):*
> ```cpp
> };
> 
> class GlbLbCallData final : public grpc_core::InternallyRefCountedWithTracing {
> ```

I don't think `final` actually adds any benefit here, so let's not use it.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 277 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4fzLiIi-edB33lXOW_:-L4fzLiIi-edB33lXOWa:b-6m4nb4) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L277)):*
> ```cpp
> };
> 
> class GlbLbCallData final : public grpc_core::InternallyRefCountedWithTracing {
> ```

Suggest calling this something like `BalancerCallState`.

Also, please add a short comment explaining the purpose of this class.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 280 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g3KpfLfEzDxyJ736a:-L4g3KpfLfEzDxyJ736b:bqxcf9c) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L280)):*
> ```cpp
>  public:
>   explicit GlbLbCallData(glb_lb_policy* glb_policy);
>   void Orphan() override;
> ```

It's probably worth adding a comment here that it's the caller's responsibility to ensure that `Orphan()` is called from inside the combiner.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 283 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g0SB4iQEh9pu5S1CU:-L4g0SB4iQEh9pu5S1CV:b-jlusxs) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L283)):*
> ```cpp
> 
>   void StartQuery();
>   // TODO(juanlishen): should be removed when glb is C++-ized and a fiend class
> ```

Please remove this TODO.  It's better to provide accessor functions than to use `friend`, since the latter breaks proper encapsulation.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 285 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g-iLjujXlK1eJogxc:-L4g-iLjujXlK1eJogxd:bf4pwj8) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L285)):*
> ```cpp
>   // TODO(juanlishen): should be removed when glb is C++-ized and a fiend class
>   // of GlbLbCallData.
>   grpc_grpclb_client_stats* ClientStats();
> ```

Simple accessor methods should be named the same as the underlying variable, as per:

https://google.github.io/styleguide/cppguide.html#Function_Names

Also, short methods like this can be defined in-line instead of declared here and defined below, as per:

https://google.github.io/styleguide/cppguide.html#Inline_Functions

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 312 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g-HvFO9U54ZUDSa-Z:-L4g-HvFO9U54ZUDSa-_:b-aqhbui) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L312)):*
> ```cpp
>    * value may vary if the LB server indicates a redirect) or send client load
>    * report. */
>   grpc_byte_buffer* send_message_payload_;
> ```

Please initialize all pointer fields to nullptr.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 320 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g-KWfkGqTH_F7EiLJ:-L4g-KWfkGqTH_F7EiLK:b-u55kbj) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L320)):*
> ```cpp
>   /** The callback to process the response received from the LB server. */
>   grpc_closure lb_on_balancer_message_received_;
>   bool seen_initial_response_;
> ```

Please initialize all bool fields to false.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 405 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g1thU89EzgtYWqhlg:-L4g1thU89EzgtYWqhlh:b6r8y8u) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L405)):*
> ```cpp
> void GlbLbCallData::Orphan() {
>   GPR_ASSERT(lb_call_ != nullptr);
>   // lb_on_balancer_status_received_ will complete the cancellation and clean
> ```

This comment should point out that there are two possible cases here:

1. We are being called because the LB policy is cancelling the call, in which case `lb_on_balancer_status_received_` will complete the cancellation and clean up.

2. The call is already complete, in which case `grpc_call_cancel()` will be a no-op, and we have already cleaned up.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 411 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g2aX__DaL55NCv_Sj:-L4g2aX__DaL55NCv_Sk:b-dpj7c6) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L411)):*
> ```cpp
>     grpc_timer_cancel(&client_load_report_timer_);
>   }
> }
> ```

Upon initially reading this code, I was going to point out that this method needs to call `Unref()`, or else the object's external ref will never go away, and we'll have a memory leak.  However, upon reading further, I see that the code is structured such that the object's initial ref is not actually held by the caller.  This is consistent with how the code worked prior to this PR, so it's fine, but it is not the typical use for `InterallyRefCounted`.  Given that, it's probably worth a comment explainining this.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 494 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g4w7mGWCnmWqNXOHf:-L4g4w7mGWCnmWqNXOHg:b-vdtsmh) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L494)):*
> ```cpp
> void GlbLbCallData::MaybeSendClientLoadReportLocked(void* arg,
>                                                     grpc_error* error) {
>   GlbLbCallData* lb_calld = (GlbLbCallData*)arg;
> ```

Please use C++-style casts, both here and throughout this new code.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 524 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g5FCYh-ZUHsE88kQO:-L4g5FCYh-ZUHsE88kQP:bjaeh9m) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L524)):*
> ```cpp
> 
> void GlbLbCallData::SendClientLoadReportLocked() {
>   glb_lb_policy* glb_policy = glb_policy_;
> ```

This local variable seems totally unnecessary now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14331#-:-L4g8HtzooJdzNdbICcN:b-dreg0u)*

**Comment by markdroth** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 162 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4g7Sb9s6XiOJ8vou2N:-L4hFsEbm9INOklbnSHi:b-p054my) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L162)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we'll need to change this to be an `OrphanablePtr<>` as part of merging the changes from #14221 (which I plan to merge later today).
</blockquote></details>

Actually, it looks like this is unrelated to the changes from #14221, so don't worry about this now.  I'll take care of it as part of #13870.

---

*[src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc, line 438 at r1](https://reviewable.io:443/reviews/grpc/grpc/14331#-L4hGcVzhyxW0utaOBEZ:-L4hGcVzhyxW0utaOBE_:blfbvjo) ([raw file](https://github.com/grpc/grpc/blob/1dc772e5683ff1ed49d4f0057617480c43815fdc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L438)):*
> ```cpp
>   op->reserved = nullptr;
>   op++;
>   Ref(DEBUG_LOCATION, "OnInitialRequestSentLocked");
> ```

Note that when you merge in the changes from #14221, `Ref()` will now return a `RefCountedPtr<>`, which we will need to `release()`, since we're currently tracking the ref manually.  Please add a TODO about fixing this once the new ClosureRef API is done, since that will allow us to track the ref with the closure.

Same thing everywhere you call `Ref()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14331)*

**Pull request closed without merging**
