### PR TITLE
Php generate protos refactor

### PR DESCRIPTION
**Pull request by jtattermusch**
Followup https://github.com/grpc/grpc/pull/22703 for PHP codegen.

Currently PHP codegen is in a very messy state (some generated proto files are checked in, some are not and the ones that are checked in haven't been regenerated for ~2 years.

- make generate_proto_php.sh use bazel-built binaries
- cleanup the generate_proto_php.sh
- check in all the generated PHP code (already being code by C# and ruby, so it seems fine).

### CODE REVIEW

**Comment by jtattermusch** [comment]
Looks like something is wrong with the php's build_interop.sh (because it seems to be finishing fine with DONE=1, but it still gets reported as an error https://source.cloud.google.com/results/invocations/69440f00-13ab-403d-ade8-1424a89b4189/targets/github%2Fgrpc%2Finterop_docker_build/tests)

```
+ DONE=1
+ [[ 1 == 1 ]]
+ break
+ [[ 1 != 1 ]]
```

https://github.com/grpc/grpc/blob/b8e34c84ed6ec54d8371051dde7e593ee0833113/tools/dockerfile/interoptest/grpc_interop_php/build_interop.sh#L46

My hunch is this is due to the use of `&&` instead of `||`

**Comment by stanley-cheung** [comment]
> ```
> + DONE=1
> + [[ 1 == 1 ]]
> + break
> + [[ 1 != 1 ]]
> ```
> 
> https://github.com/grpc/grpc/blob/b8e34c84ed6ec54d8371051dde7e593ee0833113/tools/dockerfile/interoptest/grpc_interop_php/build_interop.sh#L46
> 
> My hunch is this is due to the use of `&&` instead of `||`

but here's the semantics

```
"A && B" Run B if A succeeded
"A || B" Run B if A failed
```

In this case, left half is false (i.e. 1 != 1), so we don't want to run the right half. If we switch to `||`, we would have run the right half, which we don't want.

**Comment by stanley-cheung** [comment]
I wonder why just another test run around the similar time was successful: https://source.cloud.google.com/results/invocations/a7dc1f64-b5c7-41bc-88dd-a697295ea7b7/targets/github%2Fgrpc%2Finterop_docker_build/tests

The `grpc_interop_php/build_interop.sh` script hasn't been touched in 6 months. That `&&` statement has been in place since then.

I was wondering if the problem actually came from the next statement ....

Oh I got it, since this PR _removes_ the next line https://github.com/grpc/grpc/blob/master/tools/dockerfile/interoptest/grpc_interop_php/build_interop.sh#L48, so the exit status of the entire script becomes the exit status of this line

```
[[ "$DONE" != 1 ]] && echo "Failed to do composer install" && exit 1
```

The exit status used to be the next statement

```
./bin/generate_proto_php.sh
```

So ... perhaps we just put an `exit 0` as the last line now?

**Comment by jtattermusch** [comment]
@stanley-cheung  FYI using  `[[ some_test ]] && exit 1` at the end of a shell script is fundamentally broken and it doesn't do what you expect it to do.
I fixed the error handling logic in this commit https://github.com/grpc/grpc/pull/22712/commits/cfbeb3edd78629bf231a426bba95ee655450eb9c

**Comment by jtattermusch** [comment]
> I wonder why just another test run around the similar time was successful: https://source.cloud.google.com/results/invocations/a7dc1f64-b5c7-41bc-88dd-a697295ea7b7/targets/github%2Fgrpc%2Finterop_docker_build/tests
> 
> The `grpc_interop_php/build_interop.sh` script hasn't been touched in 6 months. That `&&` statement has been in place since then.
> 
> I was wondering if the problem actually came from the next statement ....
> 
> Oh I got it, since this PR _removes_ the next line https://github.com/grpc/grpc/blob/master/tools/dockerfile/interoptest/grpc_interop_php/build_interop.sh#L48, so the exit status of the entire script becomes the exit status of this line
> 
> ```
> [[ "$DONE" != 1 ]] && echo "Failed to do composer install" && exit 1
> ```
> 
> The exit status used to be the next statement
> 
> ```
> ./bin/generate_proto_php.sh
> ```
> 
> So ... perhaps we just put an `exit 0` as the last line now?

Yes you're right. Sorry I didn't see your comment at first so I used a different way to fix it.

**Comment by jtattermusch** [comment]
> > ```
> > + DONE=1
> > + [[ 1 == 1 ]]
> > + break
> > + [[ 1 != 1 ]]
> > ```
> > 
> > 
> > https://github.com/grpc/grpc/blob/b8e34c84ed6ec54d8371051dde7e593ee0833113/tools/dockerfile/interoptest/grpc_interop_php/build_interop.sh#L46
> > 
> > My hunch is this is due to the use of `&&` instead of `||`
> 
> but here's the semantics
> 
> ```
> "A && B" Run B if A succeeded
> "A || B" Run B if A failed
> ```
> 
> In this case, left half is false (i.e. 1 != 1), so we don't want to run the right half. If we switch to `||`, we would have run the right half, which we don't want.

Yes, what I meant that you can use `||` but of course you'd need to negate the condition to keep the semantics.

`[[ DONE != 1 ]] && exit 1` looks like its doing the right thing but it's wrong (because it has exitcode of 1 even when DONE==1).

While the negated condition with a || has the right behavior:
`[[ DONE == 1]] || exit 1`
(the exitcode is guaranteed to be 0 if DONE==1)

**Comment by stanley-cheung** [comment]
Sounds good. Agreed on the root cause being the exit status. Thanks for fixing this!

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/18892

**Pull request merged**
