### PR TITLE
Stop pinging if transport is closed

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by yashykt** [comment]
A similar check should probably also be added to start_bdp_ping_locked

**Comment by yang-g** [comment]
I am not sure that is needed as it is wrapped in send_ping_locked which does the check.

**Comment by yashykt** [comment]
send_ping_locked schedules start_bdp_ping_locked and finish_bdp_ping_locked on error. Looks like start_bdp_ping_locked just ignores that error currently.

**Comment by yang-g** [comment]
I think you are right! Updated.

**Comment by yang-g** [comment]
Test failure: https://github.com/grpc/grpc/issues/18512

**Pull request merged**
