### PR TITLE
PHP: upgrade references to phpunit 8.5.8

### PR DESCRIPTION
**Pull request by HannahShiSFB**
@stanley-cheung

### CODE REVIEW

**Comment by stanley-cheung** [comment]
This is a continuation of #24695. A few more stranglers.

**Comment by Alexander1000** [comment]
in this file you run tests on php 7.0: tools/dockerfile/distribtest/php7_stretch_x64/Dockerfile
in this commit fixed it: https://github.com/grpc/grpc/pull/24525/files#diff-8b0fa6f8a955efc4d572809c29439ef1116a7b08d71ca48e0e6bb66a23a19a4e

**Comment by stanley-cheung** [comment]
> in this file you run tests on php 7.0: tools/dockerfile/distribtest/php7_stretch_x64/Dockerfile
> in this commit fixed it: https://github.com/grpc/grpc/pull/24525/files#diff-8b0fa6f8a955efc4d572809c29439ef1116a7b08d71ca48e0e6bb66a23a19a4e

Yea sorry we missed it the first time around.

**Comment by Alexander1000** [comment]
it would not be bad to change composer.json on minimum required version php

**Comment by stanley-cheung** [comment]
> it would not be bad to change composer.json on minimum required version php

Sounds good. Do you mind making a PR just for that change please? Thanks.

**Comment by Alexander1000** [comment]
No problems! https://github.com/grpc/grpc/pull/24791

**Review by stanley-cheung — APPROVED** [review]

**Comment by stanley-cheung** [comment]
Tests all passed.

**Pull request merged**
