### PR TITLE
Only Print Stats if They Are Collected

### PR DESCRIPTION
**Pull request by ncteisen**
Only print stats if they are collected

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by hcaseyal** [comment]
Does anyone use these? If so, we should probably let them give output under a flag. If not, I'm happy with deleting them :)

**Comment by ncteisen** [comment]
Actually, it is probably a better idea to protect this under the same #define we use to collect stats

**Comment by ncteisen** [comment]
Done

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,961,099      Total (=)      1,961,099

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,883,611      Total (>)     10,883,608

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                         cpu_time    real_time
------------------------------------------------  ----------  -----------
BM_ErrorGetIntFromNoError                         +7%         +7%
BM_HasClearGrpcStatus<ErrorNone>                  +4%         +4%
BM_HasClearGrpcStatus<ErrorWithNestedGrpcStatus>  +5%         +5%
BM_MetadataRefUnrefExternal                       -16%        -16%
BM_MetadataRefUnrefStatic                         -4%         -4%
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,961,099      Total (=)      1,961,099

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,883,611      Total (>)     10,883,608

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark              cpu_time    real_time
---------------------  ----------  -----------
BM_ErrorGetPresentInt  -5%         -5%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,961,099      Total (=)      1,961,099

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,883,616      Total (>)     10,883,609

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                    cpu_time    real_time
---------------------------  ----------  -----------
BM_MetadataRefUnrefExternal  -16%        -16%
BM_MetadataRefUnrefStatic    -4%         -4%
```

**Pull request merged**
