### PR TITLE
We need libmath for FreeBSD.

### PR DESCRIPTION
**Pull request by nicolasnoble**
(Also, regenerating project files, apparently ?)

### CODE REVIEW

**Comment by ctiller** [comment]
Needs a merge

**Comment by nicolasnoble** [comment]
Actually goes in par with the failed previous zlib stuff. Rebuilding the old one first.

**Comment by ctiller** [comment]
Reassigning since I figure it's unlikely to get tickled enough today :)

**Comment by nicolasnoble** [comment]
It probably won't in a little while anyway.

**Comment by vjpai** [comment]
Looks ok, but you got merge conflicts!

**Comment by vjpai** [comment]
Can I get a status update on this?

**Comment by vjpai** [comment]
Hi, revisiting this old PR again. It has been conflicted for more than a month with no update. Can you resolve conflicts, or should this be closed?

**Comment by vjpai** [comment]
I believe this is obsolete. Closing.

**Pull request closed without merging**
