### PR TITLE
Revert recent changes to node interop build script

### LINKED ISSUE #15289: Node interop docker image build fails consistently
Fails consistently on master, failing 100% of test runs.
e.g.
https://source.cloud.google.com/results/invocations/4856fb30-685c-4a7e-b0ca-08b064c85298/log

```
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.o
make: *** No rule to make target 'Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/subchannel_list.o', needed by 'Release/obj.target/libgrpc.a'.  Stop.
make: Leaving directory '/var/local/git/grpc-node/packages/grpc-native-core/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
...
2018-05-06 08:37:38,861 FAILED: build_docker_node [ret=1, pid=9291, time=464.1sec]
```

### PR DESCRIPTION
**Pull request by murgatroid99**
Fix issues with build file changes not propagating to the Node repo in interop tests.

Fixes #15289

### CODE REVIEW

**Comment by kpayson64** [comment]
@jtattermusch 
Do you know how the node unit tests are getting around this problem?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by murgatroid99** [comment]
For the node unit tests, we rerun the build script templating script after updating the submodule.

**Comment by kpayson64** [comment]
Would https://github.com/grpc/grpc/pull/15299 be a satisfactory alternative then?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Merging to unbreak the interop tests. Thanks!

**Comment by murgatroid99** [comment]
@kpayson64 As of grpc/grpc-node#324, we are now testing for these problems in the grpc-node local tests. So I would prefer to remove this section of the script entirely.

**Pull request merged**
