### PR TITLE
Fixes for the GRPC Bazel build

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
This is ok to test.

**Comment by nicolasnoble** [comment]
Errr, actually. Why is this change needed ?

**Comment by nicolasnoble** [comment]
More specifically, aren't you able to use nanopb from third_party instead of relying on the external ?

**Comment by earhart** [comment]
When Bazel pulls down git repositories, it deletes the submodules. The idea
is that it's important that everything in the workspace is on the same
version of all dependencies.

So we want to reference submodules via //external links, and let the
workspace bind those dependencies as needed.

**Comment by earhart** [comment]
... note that zlib and SSL are already bound via //external dependencies.

**Comment by nicolasnoble** [comment]
Alright. We need to address this. But this PR isn't exactly the right solution immediately for us.

**Comment by earhart** [comment]
Agreed, but what's currently checked in doesn't work at all; this doesn't
break anything.

It'd definitely be better to fix the build template and add an actual Bazel
test, but I don't have the time or experience with the template system to
get that right. :-/

We could also just fork GRPC for our own development. I'd rather not do
that, since it's harder to maintain - especially since these changes won't
break anything. :-) But it's your call.

**Comment by nicolasnoble** [comment]
Well, in all cases, your change without changing the corresponding template would be wiped at the next build.yaml change, which tends to happens pretty often.

**Comment by nicolasnoble** [comment]
So, the proper workaround for now is to have a special exception case in the template to detect nanopb and alter the BUILD file generation accordingly. Which is painful. But nanopb creates other similar issues for us at the moment with the Makefile, and we need to come up with a common solution for both (and potentially more).

**Comment by earhart** [comment]
Okay -- I'll look into doing this via template tweaking, and send a pull
request if I can get it to work; otherwise, we'll just fork for now.

**Comment by earhart** [comment]
Okay, how's this?  (I've manually verified that the generated BUILD file works with Bazel.)

**Comment by nicolasnoble** [comment]
Yep! That's looking good. Can you try solving the merge conflicts so this becomes mergeable ? Thanks for that!

**Pull request merged**
