### PR TITLE
Script for running a matrix of run_tests.py instances at once.

### PR DESCRIPTION
**Pull request by jtattermusch**
Adds `tools/run_tests/run_tests_matrix.py` script. The idea is to be able to run all tests for given platform in a single run. On Linux, configurations are run in separate docker containers. On windows and mac, local repo is cloned in a "workspace" from where it is built.

Currently the scripts contains definitions for all configurations being run by gRPC_master and gRPC_portability_master. Selection of configurations to run is done through "filters".

Examples
```
# runs basictests for all langs
tools/run_tests/run_tests_matrix.py -f linux basictests

# runs sanitizers for c++
tools/run_tests/run_tests_matrix.py -f linux sanitizer c++

# run windows portability tests
tools/run_tests/run_tests_matrix.py -f windows portability
```

This is going to be useful for:
-- being able to run tests on a dedicated worker with a single executor (and thus being able start rebooting workers after every build).
-- easier management what configurations should/shouldn't be run.
-- for integration with the internal k****o CI system (no matrix jobs supported).

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @ctiller  @adelez  

@adelez , can you pls CC Matt?

**Comment by adelez** [comment]
CC @matt-kwong

**Comment by jtattermusch** [comment]
@nicolasnoble  friendly ping (or reassign the review to someone else).

@matt-kwong  feel free to express your opinions as well.

**Comment by jtattermusch** [comment]
Ping again, I'd really appreciate some feedback. I do believe this is an approach that's at least worth trying (and solves several Jenkins issues we've been having along the way).

**Pull request merged**
