### PR TITLE
Fix gRPC performance regression

### LINKED ISSUE #12768: Add bm_diff test(s) for stream compression
@ncteisen

### PR DESCRIPTION
**Pull request by muxi**
The stream compression refactor in #12399 routed non-compressed traffic through a truncation of first 5 bytes for deframing the gRPC header. This action is had some impact on performance when stream is not compressed but is actually not necessary in this case. This PR reroutes these data and consider them as decompressed.

Fixes #12768

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++
  +0.1%     +32 src/core/ext/transport/chttp2/transport/chttp2_transport.c     +32  +0.1%
      +4.1%     +36 grpc_chttp2_maybe_complete_recv_message                        +36  +4.1%
  [ = ]       0 [None]                                                         +16  +0.0%

  +0.0%     +32 TOTAL                                                          +48  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++
  +0.1%     +32 src/core/ext/transport/chttp2/transport/chttp2_transport.c     +32  +0.1%
      +4.1%     +36 grpc_chttp2_maybe_complete_recv_message                        +36  +4.1%
  [ = ]       0 [None]                                                         +16  +0.0%

  +0.0%     +32 TOTAL                                                          +48  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Basic Tests C++ Linux [dbg] (internal CI) - #11205 
Basic Tests C++ Linux [opt] (internal CI) - #11205 #12428 
Basic Tests Windows [dbg] (internal CI) - #12819 
Basic Tests Windows [opt] (internal CI) - #11383 
Interop Cloud-to-Prod Tests (internal CI) - #9167
Tsan C++ (internal CI) - #12428

**Pull request merged**
