### PR TITLE
Remove node benchmarks from run performance script.

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/13347.

After doing the next release, we will also need to update 
https://github.com/grpc/grpc/blob/master/tools/jenkins/run_full_performance_released.sh

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_unary_ping_pong.BM_UnaryPingPong_InProcessCHTTP2_NoOpMutator_NoOpMutator__0_32768.counters.old: 1


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
The change doesn't affect any of the PR tests. Merging to fix the performance dashboard for 8core.

**Pull request merged**
