### PR TITLE
Linking against zlib's static version instead of dynamic.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by jtattermusch** [comment]
why exactly do we wanna do this? I thought we didn't want to link in any third party dependencies. 
For C#, compiling this statically would mean dropping the dependency on https://www.nuget.org/packages/grpc.dependencies.zlib/, so this PR is incomplete.

**Comment by jtattermusch** [comment]
Looking at this old abandoned pull request, it looks like the zlib static linkage made it to upstream/master (see #2709) through some backdoor, because I haven't LGTMd it ;-)

**Comment by larsonmpdx** [comment]
it got put in with #2506 in order to get tests to compile, see templates/vsprojects/vcxproj_defs.include.  Do you want it turned off on non-test items?

**Comment by ctiller** [comment]
Is this dead?

**Comment by jtattermusch** [comment]
I think so. Closing.

**Pull request closed without merging**
