### PR TITLE
Add Java v1.40.2 and v1.41.1 to the interop test client matrix.

### PR DESCRIPTION
**Pull request by temawi**
Successful run: https://fusion2.corp.google.com/invocations/a225e937-e3e1-468a-b1b4-f19a6c35aabe/targets

@markdroth

### CODE REVIEW

**Comment by temawi** [comment]
Successful run: https://fusion2.corp.google.com/invocations/dabcac15-99d6-418f-b229-42b4794eda0d/targets

**Comment by temawi** [comment]
@donnadionne - could you please review this one?

**Review by markdroth — APPROVED** [review]

**Comment by markdroth** [comment]
Looks like there's a merge conflict.  Please fix, and then we can merge this.

**Comment by temawi** [comment]
@markdroth Should be updated now, merge away please.

**Pull request merged**
