### PR TITLE
Add v1.47.0 release of grpc-go to interop matrix

### PR DESCRIPTION
**Pull request by dfawley**

### CODE REVIEW

**Comment by dfawley** [comment]
@jtattermusch it seems like the adhoc run failed - what's the protocol here?

**Comment by jtattermusch** [comment]
> Details

It seems that the only test failed in the adhoc run are  python-related, so that seems unrelated to grpc-go 1.47.x release.

**Comment by jtattermusch** [comment]
> It seems that the only test failed in the adhoc run are python-related, so that seems unrelated to grpc-go 1.47.x release.

It seems that the only test failed in the adhoc run are python-related, so that seems unrelated to grpc-go 1.47.x release.

**Comment by jtattermusch** [comment]
> @jtattermusch it seems like the adhoc run failed - what's the protocol here?

It seems that the only test failed in the adhoc run are python-related, so that seems unrelated to grpc-go 1.47.x release.
I'd say this one is safe to merge.

**Review by jtattermusch — APPROVED** [review]

**Pull request merged**
