### PR TITLE
C++: Stop using std::thread

### PR DESCRIPTION
**Pull request by vjpai**
Built on #14459 

Note that this is a smaller and less-comprehensive PR than the previous attempt at this (#13697) since it only eliminates the use of `std::thread` and does not attempt to add new functionality such as explicit resource exhaustion handling. That will be done in a later PR.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.0%    +162 [None]                                                                                +111Ki  +1.7%
      +0.0%    +114 [Unmapped]                                                                            +111Ki  +1.7%
      [NEW]     +48 grpc_core::(anonymous namespace)::g_cv                                                     0  [ = ]
      [NEW]     +48 vtable for grpc_core::(anonymous namespace)::ThreadInternalsPosix                        +48  [NEW]
      [NEW]     +40 grpc_core::(anonymous namespace)::g_mu                                                     0  [ = ]
      +6.7%      +8 g_alts_resource                                                                            0  [ = ]
       +33%      +8 poll_cache                                                                                 0  [ = ]
      [NEW]      +4 grpc_core::(anonymous namespace)::g_thread_count                                           0  [ = ]
      [NEW]      +4 grpc_core::(anonymous namespace)::g_awaiting_threads                                       0  [ = ]
  [NEW] +1.30Ki src/core/lib/gprpp/thd_posix.cc                                                      +1.30Ki  [NEW]
      [NEW]    +616 grpc_core::Thread::Thread                                                               +616  [NEW]
      [NEW]    +275 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char co    +275  [NEW]
      [NEW]    +179 grpc_core::Thread::AwaitAll                                                             +179  [NEW]
      [NEW]     +74 [Unmapped]                                                                               +74  [NEW]
      [NEW]     +53 grpc_core::Thread::Init                                                                  +53  [NEW]
      [NEW]     +48 grpc_core::(anonymous namespace)::ThreadInternalsPosix::Start                            +48  [NEW]
      [NEW]     +38 grpc_core::(anonymous namespace)::ThreadInternalsPosix::~ThreadInternalsPosix            +38  [NEW]
      [NEW]     +34 grpc_core::(anonymous namespace)::ThreadInternalsPosix::~ThreadInternalsPosix            +34  [NEW]
      [NEW]     +11 grpc_core::(anonymous namespace)::ThreadInternalsPosix::Join                             +11  [NEW]
      [NEW]      +5 gpr_thd_currentid                                                                         +5  [NEW]
   +28%    +816 src/core/lib/iomgr/executor.cc                                                          +816   +28%
       +88%    +501 grpc_executor_set_threading                                                             +501   +88%
       +24%    +311 executor_push                                                                           +311   +24%
      +3.4%     +23 executor_thread                                                                          +23  +3.4%
  +6.3%    +771 src/core/lib/iomgr/ev_poll_posix.cc                                                     +771  +6.3%
      [NEW]    +331 cache_harvest_locked                                                                    +331  [NEW]
       +13%    +205 cvfd_poll                                                                               +205   +13%
       +34%    +174 run_poll                                                                                +174   +34%
      [NEW]    +169 init_result(poll_args*) [clone .constprop.19]                                           +169  [NEW]
      [NEW]    +124 unref_by(grpc_fd*, int) [clone .constprop.21]                                           +124  [NEW]
       +17%     +15 cache_insert_locked                                                                      +15   +17%
      [NEW]      +9 grpc_core::internal::ThreadInternalsInterface::~ThreadInternalsInterface                  +9  [NEW]
      +2.3%      +8 grpc_init_poll_cv_posix                                                                   +8  +2.3%
      +2.4%      +5 global_cv_fd_table_shutdown                                                               +5  +2.4%
      +1.5%      +3 cache_poller_locked                                                                       +3  +1.5%
      [NEW]      +2 grpc_core::internal::ThreadInternalsInterface::~ThreadInternalsInterface                  +2  [NEW]
   +13%    +320 src/core/lib/iomgr/timer_manager.cc                                                     +320   +13%
       +67%    +174 start_timer_thread_and_unlock                                                           +174   +67%
      +158%    +163 gc_completed_threads                                                                    +163  +158%
   +96%    +293 src/core/tsi/alts_transport_security.cc                                                 +293   +96%
      +118%    +190 grpc_tsi_alts_shutdown                                                                  +190  +118%
      [NEW]     +56 alts_shared_resource::~alts_shared_resource                                              +56  [NEW]
      [NEW]     +47 _GLOBAL__sub_I_alts_transport_security.cc                                                +47  [NEW]

 -------------- SHRINKING                                                                            --------------
  [DEL]    -988 src/core/lib/gpr/thd_posix.cc                                                           -988  [DEL]
      [DEL]    -540 gpr_thd_new                                                                             -540  [DEL]
      [DEL]    -138 thread_body                                                                             -138  [DEL]
      [DEL]    -108 gpr_await_threads                                                                       -108  [DEL]
      [DEL]     -92 dec_thd_count() [clone .part.0]                                                          -92  [DEL]
      [DEL]     -53 gpr_thd_init                                                                             -53  [DEL]
      [DEL]     -45 [Unmapped]                                                                               -45  [DEL]
      [DEL]      -7 gpr_thd_join                                                                              -7  [DEL]
      [DEL]      -5 gpr_thd_currentid                                                                         -5  [DEL]
  [DEL]    -147 src/core/lib/gpr/thd.cc                                                                 -147  [DEL]
      [DEL]     -54 gpr_thd_options_default                                                                  -54  [DEL]
      [DEL]     -44 [Unmapped]                                                                               -44  [DEL]
      [DEL]     -22 gpr_thd_options_is_detached                                                              -22  [DEL]
      [DEL]     -19 gpr_thd_options_is_joinable                                                              -19  [DEL]
      [DEL]      -4 gpr_thd_options_set_detached                                                              -4  [DEL]
      [DEL]      -4 gpr_thd_options_set_joinable                                                              -4  [DEL]

  +0.2% +2.50Ki TOTAL                                                                                 +114Ki  +1.5%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +1.2%     +58 src/cpp/server/dynamic_thread_pool.cc                                                    +58  +1.2%
      +145%    +103 grpc::DynamicThreadPool::DynamicThread::~DynamicThread                                  +103  +145%
      +6.4%     +13 grpc::DynamicThreadPool::DynamicThread::DynamicThread                                    +13  +6.4%
      [NEW]      +9 grpc_core::internal::ThreadInternalsInterface::~ThreadInternalsInterface                  +9  [NEW]
       +11%      +7 [Unmapped]                                                                                +7   +11%
      [NEW]      +5 grpc::DynamicThreadPool::DynamicThread::DynamicThread(grpc::DynamicThreadPool*)::{la      +5  [NEW]
      [NEW]      +2 grpc_core::internal::ThreadInternalsInterface::~ThreadInternalsInterface                  +2  [NEW]
  +1.8%     +44 src/cpp/thread_manager/thread_manager.cc                                                 +44  +1.8%
       +83%     +79 grpc::ThreadManager::WorkerThread::~WorkerThread                                         +79   +83%
      +8.5%     +29 grpc::ThreadManager::WorkerThread::WorkerThread                                          +29  +8.5%
       +12%     +12 [Unmapped]                                                                               +12   +12%
      [NEW]      +5 grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::{lambda(void*      +5  [NEW]

 -------------- SHRINKING                                                                            --------------
  -1.2% -2.82Ki [None]                                                                               -68.5Ki  -1.3%
      -1.2% -2.49Ki [Unmapped]                                                                           -68.2Ki  -1.3%
      [DEL]    -109 typeinfo name for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc    -109  [DEL]
      [DEL]    -104 typeinfo name for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc    -104  [DEL]
      [DEL]     -40 vtable for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc::Threa     -40  [DEL]
      [DEL]     -40 vtable for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc::Dynam     -40  [DEL]
      [DEL]     -24 typeinfo for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc::Thr     -24  [DEL]
      [DEL]     -24 typeinfo for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc::Dyn     -24  [DEL]

  -0.8% -2.72Ki TOTAL                                                                                -68.4Ki  -1.3%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Closing this in favor of merging into #14459

**Pull request closed without merging**
