### PR TITLE
[v1.42.x] Add xDS k8s_lb tests

### PR DESCRIPTION
**Pull request by lidizheng**
As title. This PR is created by:

```
git co master -- \
  tools/internal_ci/linux/grpc_xds_k8s_lb.sh \
  tools/internal_ci/linux/grpc_xds_k8s_lb.cfg \
  tools/internal_ci/linux/grpc_xds_k8s_lb_python.sh \
  tools/internal_ci/linux/grpc_xds_k8s_lb_python.cfg \
  tools/internal_ci/linux/grpc_xds_url_map.sh \
  tools/internal_ci/linux/grpc_xds_url_map.cfg \
  tools/internal_ci/linux/grpc_xds_url_map_python.sh \
  tools/internal_ci/linux/grpc_xds_url_map_python.cfg
```

### CODE REVIEW

**Comment by lidizheng** [comment]
* [grpc_xds_k8s_lb](http://sponge/fd1dc2e6-7b39-4e50-8e0e-bee88d9d28c3)
* [grpc_xds_k8s_lb_python](http://sponge/9a8735b7-2f00-41ed-a2c6-be09702a28c8)

**Comment by lidizheng** [comment]
* [grpc_xds_k8s_lb](http://sponge/f06a9520-622b-4b28-a5c5-36b49beefe32)
* [grpc_xds_k8s_lb_python](http://sponge/e4cb927c-ebbe-414b-828f-579f2f3e85f7)

**Comment by lidizheng** [comment]
Rerun k8s-lb tests to deflake:

* [grpc_xds_k8s_lb](http://sponge/8eaa941a-ec5f-49d4-9c8c-87e91e7c2454)
* [grpc_xds_k8s_lb_python](http://sponge/d6dcfada-f46b-40bb-afc9-2561b710e8eb)

**Comment by lidizheng** [comment]
Deflake:

* [grpc_xds_k8s_lb_python](http://sponge/1243ac9f-08d1-445a-8e64-5e1891384911)

**Comment by lidizheng** [comment]
Rerun after https://github.com/grpc/grpc/pull/29945

* [grpc_xds_k8s_lb_python](http://sponge/50789c04-e0f8-4f97-9056-a5b6f10569c3)

**Review by ejona86 — APPROVED** [review]

**Pull request merged**
