### PR TITLE
Remove GRPC_NEED_UDP ifdefs

### PR DESCRIPTION
**Pull request by rjshade**
See https://github.com/grpc/grpc/issues/6624.

The exclusion of udp_server from regular build/test cycles has caused numerous problems with bit rot.

I am unclear why these ifdef guards were added in the first place. Thoughts @ctiller @yang-g ?

### CODE REVIEW

**Comment by rjshade** [comment]
test this please

**Comment by ctiller** [comment]
Jenkins: test this please

**Comment by yang-g** [comment]
Could you merge with head?

**Comment by rjshade** [comment]
@yang-g done

**Pull request merged**
