### PR TITLE
Really upload bq test results in batches

### LINKED ISSUE #15724: Test result upload to biqquery is too verbose
The upload script uploads test results one row at a time, which generates a ton of logs that are not useful. 

Will be fixed by https://github.com/grpc/grpc/pull/15723 (and #15705).

### PR DESCRIPTION
**Pull request by jtattermusch**
Same idea as #15705, but this time done right.  I realized I was only batching results over a single test name, not over all tests. 

Fixes #15724

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
@matt-kwong good catch with the `upload_results_to_bq`. Done.

**Comment by jtattermusch** [comment]
Note: I checked the newly uploaded test results (after merging this PR) for both basictests and interop tests and everything seems be working fine.

**Pull request merged**
