### PR TITLE
Revert "Fix a Python spinlock bug"

### PR DESCRIPTION
**Pull request by mehrdada**
This reverts commit 2df509fc0e8628d6d4431139ce953c70796a21eb (PR #13665)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                           FILE SIZE
 ++++++++++++++ GROWING                             ++++++++++++++

 -------------- SHRINKING                           --------------
  -0.0%     -16 [None]                                 -144  -0.0%
  -0.9%    -112 src/core/lib/iomgr/ev_poll_posix.cc    -112  -0.9%
      -2.2%     -64 pollset_work                            -64  -2.2%
      -8.8%     -32 fd_orphan                               -32  -8.8%
      -4.4%     -11 fd_create                               -11  -4.4%
      -1.5%      -5 [Unmapped]                               -5  -1.5%

  -0.0%    -128 TOTAL                                  -256  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
Test failures:
macOS: Infra error--ignored
C++ Linux: https://github.com/grpc/grpc/issues/13330 https://github.com/grpc/grpc/issues/13477
Multilang Linux: https://github.com/grpc/grpc/issues/12189

**Pull request merged**
