### PR TITLE
Fix Python backward compatibility tests

### LINKED ISSUE #15147: interop matrix broken on master.
https://source.cloud.google.com/results/invocations/42e7a546-b421-4f42-ad81-4d4ce64d265e/targets/github%2Fgrpc/tests

`bash: py27/bin/python: No such file or directory`

Probably introduced by https://github.com/grpc/grpc/pull/15115.

### PR DESCRIPTION
**Pull request by adelez**
Fixes #15147

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by adelez** [comment]
Used to be true. I recently changed this behavior.

**Comment by mehrdada** [comment]
Triggered a build https://fusion.corp.google.com/invocation/e57cf341-780a-48e4-8d88-9927f8e25af3

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
