### PR TITLE
Revert "Revert "Fathom tcp changes""

### PR DESCRIPTION
**Pull request by yashykt**
Reverts grpc/grpc#16463
Original PR grpc/grpc#15941

This was reverted because linux/version.h is not necessarily present on systems that have musl as the library present. This ended up breaking Alpine Linux

Manually tested on alpine:3.5 to verify that this does not break alpine linux anymore.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                             FILE SIZE
 ++++++++++++++ GROWING                                                               ++++++++++++++
  +0.2% +1.74Ki [None]                                                                +62.7Ki  +0.7%
      +0.3% +1.71Ki [Unmapped]                                                            +62.7Ki  +0.7%
      +2.3%     +24 [None]                                                                      0  [ = ]
      [NEW]      +8 grpc_core::(anonymous namespace)::timestamps_callback                       0  [ = ]
   +28% +1.84Ki src/core/lib/iomgr/tcp_posix.cc                                       +1.84Ki   +28%
      [NEW]    +875 process_errors                                                           +875  [NEW]
      [NEW]    +732 tcp_write                                                                +732  [NEW]
       +49%    +413 tcp_flush                                                                +413   +49%
      [NEW]    +236 tcp_handle_error                                                         +236  [NEW]
      [NEW]    +141 drop_uncovered((anonymous namespace)::grpc_tcp*) [clone .isra.5]         +141  [NEW]
       +16%    +120 grpc_tcp_create                                                          +120   +16%
      [NEW]     +58 tcp_send                                                                  +58  [NEW]
      +107%     +29 tcp_destroy                                                               +29  +107%
       +21%     +24 grpc_tcp_destroy_and_release_fd                                           +24   +21%
       +12%     +12 tcp_unref                                                                 +12   +12%
      +4.1%      +7 [Unmapped]                                                                 +7  +4.1%
  [NEW]    +472 src/core/lib/iomgr/buffer_list.cc                                        +472  [NEW]
      [NEW]    +195 grpc_core::TracedBuffer::ProcessTimestamp                                +195  [NEW]
      [NEW]    +135 grpc_core::TracedBuffer::AddNewEntry                                     +135  [NEW]
      [NEW]    +103 grpc_core::TracedBuffer::Shutdown                                        +103  [NEW]
      [NEW]     +31 [Unmapped]                                                                +31  [NEW]
      [NEW]      +8 grpc_core::grpc_tcp_set_write_timestamps_callback                          +8  [NEW]
  +2.3%     +48 src/core/lib/iomgr/ev_posix.cc                                            +48  +2.3%
       +39%     +36 grpc_fd_create                                                            +36   +39%
      +5.8%     +12 [Unmapped]                                                                +12  +5.8%
  +2.3%     +16 src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc     +16  +2.3%
      +2.3%     +16 grpc_insecure_channel_create_from_fd                                      +16  +2.3%
  +2.2%     +16 src/core/lib/iomgr/endpoint_pair_posix.cc                                 +16  +2.2%
      +2.2%     +16 grpc_iomgr_create_endpoint_pair                                           +16  +2.2%
  +0.4%     +16 src/core/lib/security/transport/secure_endpoint.cc                        +16  +0.4%
      [NEW] +1.21Ki endpoint_write                                                        +1.21Ki  [NEW]
      +3.0%      +3 [Unmapped]                                                                 +3  +3.0%
  +0.4%     +16 src/core/lib/security/transport/security_handshaker.cc                    +16  +0.4%
      +5.2%      +8 [Unmapped]                                                                 +8  +5.2%
      +1.5%      +8 on_handshake_next_done_locked                                              +8  +1.5%
  +0.4%      +8 src/core/lib/iomgr/tcp_server_utils_posix_common.cc                        +8  +0.4%
      +1.1%      +8 grpc_tcp_server_add_addr                                                   +8  +1.1%
  [NEW]      +6 src/core/lib/iomgr/internal_errqueue.cc                                    +6  [NEW]
      [NEW]      +6 kernel_supports_errqueue                                                   +6  [NEW]

  +0.3% +4.16Ki TOTAL                                                                 +65.1Ki  +0.7%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]      -8  -0.0%

  [ = ]       0 TOTAL       -8  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%    +873 [None]                                                                               +48.7Ki  +0.5%
      +0.1%    +841 [Unmapped]                                                                           +48.7Ki  +0.5%
      +3.1%     +32 [None]                                                                                     0  [ = ]
  +7.2%    +488 src/core/lib/iomgr/tcp_posix.cc                                                         +488  +7.2%
      [NEW]    +732 tcp_write                                                                               +732  [NEW]
      [NEW]    +141 drop_uncovered((anonymous namespace)::grpc_tcp*) [clone .isra.5]                        +141  [NEW]
      [NEW]    +135 tcp_annotate_error(grpc_error*, (anonymous namespace)::grpc_tcp*) [clone .isra.3]       +135  [NEW]
       +16%    +120 grpc_tcp_create                                                                         +120   +16%
      [NEW]     +78 tcp_handle_error                                                                         +78  [NEW]
      [NEW]     +58 tcp_send                                                                                 +58  [NEW]
      +6.5%     +55 tcp_flush                                                                                +55  +6.5%
      +107%     +29 tcp_destroy                                                                              +29  +107%
       +21%     +24 grpc_tcp_destroy_and_release_fd                                                          +24   +21%
       +12%     +12 tcp_unref                                                                                +12   +12%
      +3.5%      +6 [Unmapped]                                                                                +6  +3.5%
  +2.3%     +48 src/core/lib/iomgr/ev_posix.cc                                                           +48  +2.3%
       +39%     +36 grpc_fd_create                                                                           +36   +39%
       +10%     +21 [Unmapped]                                                                               +21   +10%
  [NEW]     +28 src/core/lib/iomgr/buffer_list.cc                                                        +28  [NEW]
      [NEW]     +28 grpc_core::grpc_tcp_set_write_timestamps_callback                                        +28  [NEW]
  +2.3%     +16 src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc                    +16  +2.3%
      +2.3%     +16 grpc_insecure_channel_create_from_fd                                                     +16  +2.3%
  +2.2%     +16 src/core/lib/iomgr/endpoint_pair_posix.cc                                                +16  +2.2%
      +2.2%     +16 grpc_iomgr_create_endpoint_pair                                                          +16  +2.2%
  +0.4%     +16 src/core/lib/security/transport/secure_endpoint.cc                                       +16  +0.4%
      [NEW] +1.21Ki endpoint_write                                                                       +1.21Ki  [NEW]
      +3.0%      +3 [Unmapped]                                                                                +3  +3.0%
  +0.4%     +16 src/core/lib/security/transport/security_handshaker.cc                                   +16  +0.4%
      +5.2%      +8 [Unmapped]                                                                                +8  +5.2%
      +1.5%      +8 on_handshake_next_done_locked                                                             +8  +1.5%
  +0.4%      +8 src/core/lib/iomgr/tcp_server_utils_posix_common.cc                                       +8  +0.4%
      +1.1%      +8 grpc_tcp_server_add_addr                                                                  +8  +1.1%
  [NEW]      +3 src/core/lib/iomgr/internal_errqueue.cc                                                   +3  [NEW]
      [NEW]      +3 kernel_supports_errqueue                                                                  +3  [NEW]

  +0.1% +1.48Ki TOTAL                                                                                +49.3Ki  +0.5%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]      -8  -0.0%

  [ = ]       0 TOTAL       -8  -0.0%



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,028      Total (>)      1,954,464

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,639,702       Core (>)      3,638,286

10,843,752      Total (>)     10,842,342


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,028      Total (>)      1,954,464

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
 3,639,702       Core (>)      3,638,286

10,843,758      Total (>)     10,842,333


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
Known issues #16042, #16472, #15752, #16123, #16473
Since linux/version.h is not being included in this PR. This effectively does not enable timestamping.

**Pull request merged**
