### PR TITLE
Skip running stress_tests on jenkins by run_tests.py

### PR DESCRIPTION
**Pull request by sreecha**
(This fixed the issue addressed by commit: e6cd0e70a9c8, the right way)

### CODE REVIEW

**Comment by ctiller** [comment]
Need to rerun `tools/buildgen/generate_projects.sh`

**Comment by sreecha** [comment]
Looks like this isn't working. Added DNM label.

**Comment by sreecha** [comment]
@ctiller , thanks for reminding me to re-run generate_projects.sh!

**Comment by sreecha** [comment]
Looks good now. Stress_tests are being skipped. The other jenkins failures are unrelated. I removed the Do-not-merge flag.

**Pull request merged**
