### PR TITLE
Make PHP work correctly when receiving a compressed message

### LINKED ISSUE #6743: Make PHP work correctly when receiving a compressed message
See node's fix #6719.

### PR DESCRIPTION
**Pull request by thinkerou**
Fixed #6743.
This change is copied pretty much verbatim from the corresponding Node changed #6719.

### CODE REVIEW

**Comment by stanley-cheung** [comment]
LGTM

**Comment by kpayson64** [comment]
test this please

**Comment by kpayson64** [comment]
ok to test

**Comment by stanley-cheung** [comment]
I believe there's a new conflict because of #7190

**Comment by thinkerou** [comment]
The conflict have fixed.

**Comment by stanley-cheung** [comment]
LGTM

**Pull request merged**
