### PR TITLE
Be a tad more specific requesting error reports

### PR DESCRIPTION
**Pull request by soltanmm-google**
Can error reports end up obscenely long if people don't attach separate files? ... yes. Will it be quicker for all involved to just skim the logs? Probably usually yep.

### CODE REVIEW

**Comment by kpayson64** [comment]
No matter how verbose this message is, there will continue to be "gRPC Broken" reports.  But I think this is a good idea.

**Comment by soltanmm-google** [comment]
Oh huh I forgot about this.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by mehrdada** [comment]
@kpayson64 @nathanielmanistaatgoogle do we still want to merge this?

**Comment by nathanielmanistaatgoogle** [comment]
@mehrdada: yes I think so - may I trouble you to trigger what test runs need to happen?

**Comment by mehrdada** [comment]
@nathanielmanistaatgoogle sure

**Comment by mehrdada** [comment]
Closed in favor of https://github.com/grpc/grpc/pull/8663

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @soltanmm-google isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
