### PR TITLE
testing: add a fake TCP and UDP server to test/core/util (extracted from #27883)

### PR DESCRIPTION
**Pull request by apolcyn**
This is extracted from https://github.com/grpc/grpc/pull/27883, since it's a mostly independent change from the rest of #27883.

This change merges the fake servers implemented separately in `alts_concurrrent_connectivity_test.cc` and the fake UDP server in `test/cpp/naming/dns_test_util.h` into a single fake that lives in test/core/util.

### CODE REVIEW

**Comment by ctiller** [comment]
Given #27595 removed our UDP code, is having a UDP fake still useful?

**Comment by apolcyn** [comment]
> Given #27595 removed our UDP code, is having a UDP fake still useful?

Yeah, the UDP fake is still used in some DNS resolver tests (mainly to act as a non-responsive DNS server).

**Review by markdroth — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @apolcyn)

**Comment by apolcyn** [comment]
python windows: https://github.com/grpc/grpc/issues/25124
macos artifacts: b/209603283

**Pull request merged**
