### PR TITLE
[support] Add detection of QNX platform

### PR DESCRIPTION
**Pull request by Roman-Byshliaha-Bose**

### CODE REVIEW

**Comment by Roman-Byshliaha-Bose** [comment]
A solution for https://github.com/grpc/grpc/issues/34417.

**Comment by Roman-Byshliaha-Bose** [comment]
Hi @eugeneo

I might need to limit the detection to QNX platform only, instead of both QNX and QNXNTO.

Beside that - what are my further steps? Or do I need to just wait for a reviewer/maintainer approval?

**Comment by eugeneo** [comment]
We need to run the presubmits (I triggered them) then let the assigned reviewer do the review.

**Review by eugeneo — APPROVED** [review]

**Comment by luominjie19981026** [comment]
Thank you for your great contribution and may I ask that did you successfully cross compile grpc for QNX using this cmake configuration?

**Pull request merged**
