### PR TITLE
Simplify QPS Metrics collection

### PR DESCRIPTION
**Pull request by sreecha**
Previously, the stress test client calculated the qps every few seconds (as determined by `metrics_collection_interval_secs` command line arg) and set the qps gauge.

Now, I have removed the `metrics_collection_interval_secs` and created a `QpsGauge` (actually rewrote the `Gauge` class to a `QpsGauge` class) which maintains the total number of queries and the total duration and returns (total queries) / (total duration in secs).

### CODE REVIEW

**Comment by vjpai** [comment]
LGTM.

**Comment by sreecha** [comment]
Basic test failures are known flakes

**Comment by vjpai** [comment]
Can you remerge master and rerun the tests? I think that the mdstr PR that Craig put in last night should deflake your remaining problems. I had already given this an LGTM.

**Comment by sreecha** [comment]
all green!!

**Comment by vjpai** [comment]
Yup, LGTM and ready to merge.

**Pull request merged**
