### PR TITLE
Devel monotonic

### PR DESCRIPTION
**Pull request by iancoolidge**
Add monotonic clock for condition waits where possible (Linux),
and some other misc updates found during integration

### CODE REVIEW

**Comment by ctiller** [comment]
Jenkins: this is ok to test

**Comment by iancoolidge** [comment]
These failures don't seem related to my PR

**Comment by dgquintas** [comment]
jenkins test this please

**Comment by dgquintas** [comment]
The change to Makefile seems to be spurious

**Comment by iancoolidge** [comment]
@dgquintas why do you say that?  codegen_init.o really has not many deps.

**Comment by dgquintas** [comment]
We don't manually edit the Makefile, it's a generated file, from build.yaml. In any case, I don't see how the changes to sync_stream.h and sync_posix.c are related to any changes in the Makefile or build.yaml.

**Comment by iancoolidge** [comment]
They aren't related.

I removed that CL. I'll look into editing the yaml file to fix the bug the right way.

**Comment by dgquintas** [comment]
is this PR still relevant?

**Pull request closed without merging**
