### PR TITLE
Security connector replacement

### PR DESCRIPTION
**Pull request by yihuazhang**
The PR moves security_connector.{h, cc} from src/core/lib/security/transport_security to src/core/lib/security/security_connector, which will be consistent with the placement of credentials.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  [NEW] +8.82Ki src/core/lib/security/security_connector/security_connector.cc                       +8.82Ki  [NEW]
      [NEW] +1.92Ki [Other]                                                                              +1.92Ki  [NEW]
      [NEW]    +666 grpc_ssl_channel_security_connector_create                                              +666  [NEW]
      [NEW]    +629 try_fetch_ssl_server_credentials                                                        +629  [NEW]
      [NEW]    +537 fake_check_peer(grpc_security_connector*, tsi_peer, grpc_auth_context**, grpc_closur    +537  [NEW]
      [NEW]    +526 fake_channel_check_peer                                                                 +526  [NEW]
      [NEW]    +518 tsi_shallow_peer_from_ssl_auth_context                                                  +518  [NEW]
      [NEW]    +500 grpc_ssl_server_security_connector_create                                               +500  [NEW]
      [NEW]    +492 [Unmapped]                                                                              +492  [NEW]
      [NEW]    +452 compute_default_pem_root_certs_once                                                     +452  [NEW]
      [NEW]    +409 tsi_ssl_peer_to_auth_context                                                            +409  [NEW]
      [NEW]    +404 ssl_check_peer(grpc_security_connector*, char const*, tsi_peer const*, grpc_auth_con    +404  [NEW]
      [NEW]    +343 fake_check_target                                                                       +343  [NEW]
      [NEW]    +216 grpc_channel_security_connector_cmp                                                     +216  [NEW]
      [NEW]    +202 ssl_channel_check_call_host                                                             +202  [NEW]
      [NEW]    +183 grpc_security_connector_check_peer                                                      +183  [NEW]
      [NEW]    +182 ssl_channel_add_handshakers                                                             +182  [NEW]
      [NEW]    +176 grpc_fake_channel_security_connector_create                                             +176  [NEW]
      [NEW]    +166 grpc_channel_security_connector_check_call_host                                         +166  [NEW]
      [NEW]    +160 ssl_server_add_handshakers                                                              +160  [NEW]
      [NEW]    +154 grpc_server_security_connector_cmp                                                      +154  [NEW]
      [NEW]    +146 ssl_host_matches_name                                                                   +146  [NEW]
  [ = ]       0 [None]                                                                                  +480  +0.0%

 -------------- SHRINKING                                                                            --------------
  [DEL] -8.82Ki src/core/lib/security/transport/security_connector.cc                                -8.82Ki  [DEL]
      [DEL] -1.92Ki [Other]                                                                              -1.92Ki  [DEL]
      [DEL]    -666 grpc_ssl_channel_security_connector_create                                              -666  [DEL]
      [DEL]    -629 try_fetch_ssl_server_credentials                                                        -629  [DEL]
      [DEL]    -537 fake_check_peer(grpc_security_connector*, tsi_peer, grpc_auth_context**, grpc_closur    -537  [DEL]
      [DEL]    -526 fake_channel_check_peer                                                                 -526  [DEL]
      [DEL]    -518 tsi_shallow_peer_from_ssl_auth_context                                                  -518  [DEL]
      [DEL]    -500 grpc_ssl_server_security_connector_create                                               -500  [DEL]
      [DEL]    -492 [Unmapped]                                                                              -492  [DEL]
      [DEL]    -452 compute_default_pem_root_certs_once                                                     -452  [DEL]
      [DEL]    -409 tsi_ssl_peer_to_auth_context                                                            -409  [DEL]
      [DEL]    -404 ssl_check_peer(grpc_security_connector*, char const*, tsi_peer const*, grpc_auth_con    -404  [DEL]
      [DEL]    -343 fake_check_target                                                                       -343  [DEL]
      [DEL]    -216 grpc_channel_security_connector_cmp                                                     -216  [DEL]
      [DEL]    -202 ssl_channel_check_call_host                                                             -202  [DEL]
      [DEL]    -183 grpc_security_connector_check_peer                                                      -183  [DEL]
      [DEL]    -182 ssl_channel_add_handshakers                                                             -182  [DEL]
      [DEL]    -176 grpc_fake_channel_security_connector_create                                             -176  [DEL]
      [DEL]    -166 grpc_channel_security_connector_check_call_host                                         -166  [DEL]
      [DEL]    -160 ssl_server_add_handshakers                                                              -160  [DEL]
      [DEL]    -154 grpc_server_security_connector_cmp                                                      -154  [DEL]
      [DEL]    -146 ssl_host_matches_name                                                                   -146  [DEL]

  [ = ]       0 TOTAL                                                                                   +480  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Looks like there's still a bug in the BUILD file.  You'll need to fix that before this can be merged.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  [NEW] +8.82Ki src/core/lib/security/security_connector/security_connector.cc                       +8.82Ki  [NEW]
      [NEW] +1.92Ki [Other]                                                                              +1.92Ki  [NEW]
      [NEW]    +666 grpc_ssl_channel_security_connector_create                                              +666  [NEW]
      [NEW]    +629 try_fetch_ssl_server_credentials                                                        +629  [NEW]
      [NEW]    +537 fake_check_peer(grpc_security_connector*, tsi_peer, grpc_auth_context**, grpc_closur    +537  [NEW]
      [NEW]    +526 fake_channel_check_peer                                                                 +526  [NEW]
      [NEW]    +518 tsi_shallow_peer_from_ssl_auth_context                                                  +518  [NEW]
      [NEW]    +500 grpc_ssl_server_security_connector_create                                               +500  [NEW]
      [NEW]    +492 [Unmapped]                                                                              +492  [NEW]
      [NEW]    +452 compute_default_pem_root_certs_once                                                     +452  [NEW]
      [NEW]    +409 tsi_ssl_peer_to_auth_context                                                            +409  [NEW]
      [NEW]    +404 ssl_check_peer(grpc_security_connector*, char const*, tsi_peer const*, grpc_auth_con    +404  [NEW]
      [NEW]    +343 fake_check_target                                                                       +343  [NEW]
      [NEW]    +216 grpc_channel_security_connector_cmp                                                     +216  [NEW]
      [NEW]    +202 ssl_channel_check_call_host                                                             +202  [NEW]
      [NEW]    +183 grpc_security_connector_check_peer                                                      +183  [NEW]
      [NEW]    +182 ssl_channel_add_handshakers                                                             +182  [NEW]
      [NEW]    +176 grpc_fake_channel_security_connector_create                                             +176  [NEW]
      [NEW]    +166 grpc_channel_security_connector_check_call_host                                         +166  [NEW]
      [NEW]    +160 ssl_server_add_handshakers                                                              +160  [NEW]
      [NEW]    +154 grpc_server_security_connector_cmp                                                      +154  [NEW]
      [NEW]    +146 ssl_host_matches_name                                                                   +146  [NEW]
  [ = ]       0 [None]                                                                                  +480  +0.0%

 -------------- SHRINKING                                                                            --------------
  [DEL] -8.82Ki src/core/lib/security/transport/security_connector.cc                                -8.82Ki  [DEL]
      [DEL] -1.92Ki [Other]                                                                              -1.92Ki  [DEL]
      [DEL]    -666 grpc_ssl_channel_security_connector_create                                              -666  [DEL]
      [DEL]    -629 try_fetch_ssl_server_credentials                                                        -629  [DEL]
      [DEL]    -537 fake_check_peer(grpc_security_connector*, tsi_peer, grpc_auth_context**, grpc_closur    -537  [DEL]
      [DEL]    -526 fake_channel_check_peer                                                                 -526  [DEL]
      [DEL]    -518 tsi_shallow_peer_from_ssl_auth_context                                                  -518  [DEL]
      [DEL]    -500 grpc_ssl_server_security_connector_create                                               -500  [DEL]
      [DEL]    -492 [Unmapped]                                                                              -492  [DEL]
      [DEL]    -452 compute_default_pem_root_certs_once                                                     -452  [DEL]
      [DEL]    -409 tsi_ssl_peer_to_auth_context                                                            -409  [DEL]
      [DEL]    -404 ssl_check_peer(grpc_security_connector*, char const*, tsi_peer const*, grpc_auth_con    -404  [DEL]
      [DEL]    -343 fake_check_target                                                                       -343  [DEL]
      [DEL]    -216 grpc_channel_security_connector_cmp                                                     -216  [DEL]
      [DEL]    -202 ssl_channel_check_call_host                                                             -202  [DEL]
      [DEL]    -183 grpc_security_connector_check_peer                                                      -183  [DEL]
      [DEL]    -182 ssl_channel_add_handshakers                                                             -182  [DEL]
      [DEL]    -176 grpc_fake_channel_security_connector_create                                             -176  [DEL]
      [DEL]    -166 grpc_channel_security_connector_check_call_host                                         -166  [DEL]
      [DEL]    -160 ssl_server_add_handshakers                                                              -160  [DEL]
      [DEL]    -154 grpc_server_security_connector_cmp                                                      -154  [DEL]
      [DEL]    -146 ssl_host_matches_name                                                                   -146  [DEL]

  [ = ]       0 TOTAL                                                                                   +480  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yihuazhang** [comment]
F.Y.I. All tests passed, and I think it is ready to get merged.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  [NEW] +8.82Ki src/core/lib/security/security_connector/security_connector.cc                       +8.82Ki  [NEW]
      [NEW] +1.92Ki [Other]                                                                              +1.92Ki  [NEW]
      [NEW]    +666 grpc_ssl_channel_security_connector_create                                              +666  [NEW]
      [NEW]    +629 try_fetch_ssl_server_credentials                                                        +629  [NEW]
      [NEW]    +537 fake_check_peer(grpc_security_connector*, tsi_peer, grpc_auth_context**, grpc_closur    +537  [NEW]
      [NEW]    +526 fake_channel_check_peer                                                                 +526  [NEW]
      [NEW]    +518 tsi_shallow_peer_from_ssl_auth_context                                                  +518  [NEW]
      [NEW]    +500 grpc_ssl_server_security_connector_create                                               +500  [NEW]
      [NEW]    +492 [Unmapped]                                                                              +492  [NEW]
      [NEW]    +452 compute_default_pem_root_certs_once                                                     +452  [NEW]
      [NEW]    +409 tsi_ssl_peer_to_auth_context                                                            +409  [NEW]
      [NEW]    +404 ssl_check_peer(grpc_security_connector*, char const*, tsi_peer const*, grpc_auth_con    +404  [NEW]
      [NEW]    +343 fake_check_target                                                                       +343  [NEW]
      [NEW]    +216 grpc_channel_security_connector_cmp                                                     +216  [NEW]
      [NEW]    +202 ssl_channel_check_call_host                                                             +202  [NEW]
      [NEW]    +183 grpc_security_connector_check_peer                                                      +183  [NEW]
      [NEW]    +182 ssl_channel_add_handshakers                                                             +182  [NEW]
      [NEW]    +176 grpc_fake_channel_security_connector_create                                             +176  [NEW]
      [NEW]    +166 grpc_channel_security_connector_check_call_host                                         +166  [NEW]
      [NEW]    +160 ssl_server_add_handshakers                                                              +160  [NEW]
      [NEW]    +154 grpc_server_security_connector_cmp                                                      +154  [NEW]
      [NEW]    +146 ssl_host_matches_name                                                                   +146  [NEW]
  [ = ]       0 [None]                                                                                  +480  +0.0%

 -------------- SHRINKING                                                                            --------------
  [DEL] -8.82Ki src/core/lib/security/transport/security_connector.cc                                -8.82Ki  [DEL]
      [DEL] -1.92Ki [Other]                                                                              -1.92Ki  [DEL]
      [DEL]    -666 grpc_ssl_channel_security_connector_create                                              -666  [DEL]
      [DEL]    -629 try_fetch_ssl_server_credentials                                                        -629  [DEL]
      [DEL]    -537 fake_check_peer(grpc_security_connector*, tsi_peer, grpc_auth_context**, grpc_closur    -537  [DEL]
      [DEL]    -526 fake_channel_check_peer                                                                 -526  [DEL]
      [DEL]    -518 tsi_shallow_peer_from_ssl_auth_context                                                  -518  [DEL]
      [DEL]    -500 grpc_ssl_server_security_connector_create                                               -500  [DEL]
      [DEL]    -492 [Unmapped]                                                                              -492  [DEL]
      [DEL]    -452 compute_default_pem_root_certs_once                                                     -452  [DEL]
      [DEL]    -409 tsi_ssl_peer_to_auth_context                                                            -409  [DEL]
      [DEL]    -404 ssl_check_peer(grpc_security_connector*, char const*, tsi_peer const*, grpc_auth_con    -404  [DEL]
      [DEL]    -343 fake_check_target                                                                       -343  [DEL]
      [DEL]    -216 grpc_channel_security_connector_cmp                                                     -216  [DEL]
      [DEL]    -202 ssl_channel_check_call_host                                                             -202  [DEL]
      [DEL]    -183 grpc_security_connector_check_peer                                                      -183  [DEL]
      [DEL]    -182 ssl_channel_add_handshakers                                                             -182  [DEL]
      [DEL]    -176 grpc_fake_channel_security_connector_create                                             -176  [DEL]
      [DEL]    -166 grpc_channel_security_connector_check_call_host                                         -166  [DEL]
      [DEL]    -160 ssl_server_add_handshakers                                                              -160  [DEL]
      [DEL]    -154 grpc_server_security_connector_cmp                                                      -154  [DEL]
      [DEL]    -146 ssl_host_matches_name                                                                   -146  [DEL]

  [ = ]       0 TOTAL                                                                                   +480  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  [NEW] +8.82Ki src/core/lib/security/security_connector/security_connector.cc                       +8.82Ki  [NEW]
      [NEW] +1.92Ki [Other]                                                                              +1.92Ki  [NEW]
      [NEW]    +666 grpc_ssl_channel_security_connector_create                                              +666  [NEW]
      [NEW]    +629 try_fetch_ssl_server_credentials                                                        +629  [NEW]
      [NEW]    +537 fake_check_peer(grpc_security_connector*, tsi_peer, grpc_auth_context**, grpc_closur    +537  [NEW]
      [NEW]    +526 fake_channel_check_peer                                                                 +526  [NEW]
      [NEW]    +518 tsi_shallow_peer_from_ssl_auth_context                                                  +518  [NEW]
      [NEW]    +500 grpc_ssl_server_security_connector_create                                               +500  [NEW]
      [NEW]    +492 [Unmapped]                                                                              +492  [NEW]
      [NEW]    +452 compute_default_pem_root_certs_once                                                     +452  [NEW]
      [NEW]    +409 tsi_ssl_peer_to_auth_context                                                            +409  [NEW]
      [NEW]    +404 ssl_check_peer(grpc_security_connector*, char const*, tsi_peer const*, grpc_auth_con    +404  [NEW]
      [NEW]    +343 fake_check_target                                                                       +343  [NEW]
      [NEW]    +216 grpc_channel_security_connector_cmp                                                     +216  [NEW]
      [NEW]    +202 ssl_channel_check_call_host                                                             +202  [NEW]
      [NEW]    +183 grpc_security_connector_check_peer                                                      +183  [NEW]
      [NEW]    +182 ssl_channel_add_handshakers                                                             +182  [NEW]
      [NEW]    +176 grpc_fake_channel_security_connector_create                                             +176  [NEW]
      [NEW]    +166 grpc_channel_security_connector_check_call_host                                         +166  [NEW]
      [NEW]    +160 ssl_server_add_handshakers                                                              +160  [NEW]
      [NEW]    +154 grpc_server_security_connector_cmp                                                      +154  [NEW]
      [NEW]    +146 ssl_host_matches_name                                                                   +146  [NEW]
  [ = ]       0 [None]                                                                                  +480  +0.0%

 -------------- SHRINKING                                                                            --------------
  [DEL] -8.82Ki src/core/lib/security/transport/security_connector.cc                                -8.82Ki  [DEL]
      [DEL] -1.92Ki [Other]                                                                              -1.92Ki  [DEL]
      [DEL]    -666 grpc_ssl_channel_security_connector_create                                              -666  [DEL]
      [DEL]    -629 try_fetch_ssl_server_credentials                                                        -629  [DEL]
      [DEL]    -537 fake_check_peer(grpc_security_connector*, tsi_peer, grpc_auth_context**, grpc_closur    -537  [DEL]
      [DEL]    -526 fake_channel_check_peer                                                                 -526  [DEL]
      [DEL]    -518 tsi_shallow_peer_from_ssl_auth_context                                                  -518  [DEL]
      [DEL]    -500 grpc_ssl_server_security_connector_create                                               -500  [DEL]
      [DEL]    -492 [Unmapped]                                                                              -492  [DEL]
      [DEL]    -452 compute_default_pem_root_certs_once                                                     -452  [DEL]
      [DEL]    -409 tsi_ssl_peer_to_auth_context                                                            -409  [DEL]
      [DEL]    -404 ssl_check_peer(grpc_security_connector*, char const*, tsi_peer const*, grpc_auth_con    -404  [DEL]
      [DEL]    -343 fake_check_target                                                                       -343  [DEL]
      [DEL]    -216 grpc_channel_security_connector_cmp                                                     -216  [DEL]
      [DEL]    -202 ssl_channel_check_call_host                                                             -202  [DEL]
      [DEL]    -183 grpc_security_connector_check_peer                                                      -183  [DEL]
      [DEL]    -182 ssl_channel_add_handshakers                                                             -182  [DEL]
      [DEL]    -176 grpc_fake_channel_security_connector_create                                             -176  [DEL]
      [DEL]    -166 grpc_channel_security_connector_check_call_host                                         -166  [DEL]
      [DEL]    -160 ssl_server_add_handshakers                                                              -160  [DEL]
      [DEL]    -154 grpc_server_security_connector_cmp                                                      -154  [DEL]
      [DEL]    -146 ssl_host_matches_name                                                                   -146  [DEL]

  [ = ]       0 TOTAL                                                                                   +480  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
As a follow-up, it would probably be a good idea to move the fake and SSL security connector implementations out of security_connector.{h,cc} and into their own subdirectories.

**Comment by yihuazhang** [comment]
Sure, I will work on refactoring the security connector for fake and SSL from security_connector.{h, cc}.

**Pull request merged**
