### PR TITLE
Make C++ alarm class usable and testable

### PR DESCRIPTION
**Pull request by vjpai**
It was not actually even included in the library or the test suite so it was never actually tested or built. Minor changes required to the code.

### CODE REVIEW

**Comment by dgquintas** [comment]
Sanity: 
target alarm_cpp_test (test/cpp/common/alarm_cpp_test.cc) does not name header grpc++/alarm.h as a dependency
target grpc++ (src/cpp/common/alarm.cc) does not name header grpc++/alarm.h as a dependency
target grpc++_unsecure (src/cpp/common/alarm.cc) does not name header grpc++/alarm.h as a dependency

Also, try running run_tests.py -l sanity --use-docker locally

**Comment by vjpai** [comment]
Thanks. Done.

**Comment by vjpai** [comment]
@dgquintas : Question. For the Alarm class, should we use CompletionQueueTag* instead of void* ? The reason is that this class really directly uses the CompletionQueue and it should be made clear that the argument must be a derived type of CompletionQueueTag. Using void* like on regular Async operations makes it look like it can be anything, but in this case, it really can't.

**Comment by vjpai** [comment]
Talking to myself here, but I now think that we should leave it a void* but allow it to be anything by wrapping it in a CompletionQueueTag, like how it's done in the Async RPCs notifications. Will adjust.

**Comment by ctiller** [comment]
Eek. Let's chat tomorrow briefly. I'd prefer not to have users using
completionqueuetag directly.

**Comment by vjpai** [comment]
Yes, I agree with that, @ctiller. The current setup requires it to be derived from CompletionQueueTag, but I think that's the wrong way to do things in C++.

**Comment by vjpai** [comment]
Given the green-ness, can I have a code review (and merge?). Thanks!

**Pull request merged**
