### PR TITLE
Fix an outdated comment

### PR DESCRIPTION
**Pull request by sreecha**
Fix the outdated comment in ServerCompletionQueue constructor

### CODE REVIEW

**Comment by sreecha** [comment]
Just realized I no longer have write-access :(.. Wanted to assign this to @vjpai for review (as per his comment here: https://github.com/grpc/grpc/pull/16992#discussion_r228033869)

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by vjpai** [comment]
@sreecha I'm glad to proxy for you until we figure out the committer story. ( calling @hsaliak )

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,303      Total (=)      2,015,303

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,115,279      Total (=)     11,115,279

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Pull request merged**
