### PR TITLE
XdsEnd2EndTest : Use a queue to save resource updates

### PR DESCRIPTION
**Pull request by yashykt**
Precursor to fixing #28468

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/28467)

### CODE REVIEW

**Review by markdroth — APPROVED** [review]
Thanks for fixing this!  Looks like I introduced this bug in #28165.

**Comment by markdroth** [comment]
Why does the use of XdsCredentials matter for the RBAC NACK tests?

**Comment by yashykt** [comment]
> Why does the use of XdsCredentials matter for the RBAC NACK tests?

The NACKing infrastructure uses the `WaitForNack()` which uses the default RPC sending infrastructure instead of the one specialized for server testing, which causes inconsistencies in what the clients and the servers expect from each other in terms of credentials. Disabling XdsCredentials means that both clients and servers would use fake credentials.

**Comment by yashykt** [comment]
@markdroth Please take another look. This should fix the bug for RDS updates where the response does not need to include all the resources. Instead of using separate balancers for clients and servers, I simply keep track of whether an individual resource has been ACKed or NACKed. This approach seems to be more flexible.

**Comment by markdroth** [comment]
> I simply keep track of whether an individual resource has been ACKed or NACKed.

I don't think this approach makes sense.  At the protocol level, it is not currently possible for the client to specify which individual resource it is ACKing or NACKing, so the server cannot possibly know how to record which resource has been ACKed or NACKed.  The protocol allows only ACKing or NACKing a complete response, but that does not mean that the client has rejected every single resource in that response; it means only that the client has rejected at least one of the resources in the response, but the server has no way of knowing which of the resources in the response were accepted and which were rejected.  So it's very misleading for the server to provide an API that implies that it does know that.

(As it happens, in the long term, we do actually want to change the protocol such that the client can explicitly indicate which individual resource(s) are being rejected.  And once we do that, this sort of interface might make sense.  But until then, I don't think it makes sense.)

I can think of two possible alternatives here.

**Option 1: Server maintains a queue of client responses**

The server maintains a queue of ACK/NACK responses from the client for each resource type.  It can provide a method like this to access the client responses:

```
// Waits for a client response for the specified resource type.
// If no response is seen by the time the timeout elapses, returns absl::nullopt.
// Otherwise, returns the response.
absl::optional<ResponseState> WaitForClientResponse(absl::string_view resource_type, absl::Duration timeout);
```

The implementation of that method will probably be somewhat similar to [`LrsServiceImpl::WaitForLoadReport()`](https://github.com/grpc/grpc/blob/143d1a7e2cb188f6de9c37e39fe04576197b41cd/test/cpp/end2end/xds/xds_server.cc#L241).

Then you can change the `WaitForNack()` methods to be a simple loop that repeatedly calls `WaitForClientResponse()` until it sees either a NACK or a timeout.  That way, if the server sees an ACK from another client, we'll just ignore that response and keep waiting for the NACK that we're expecting.

The down-side of this approach is that it will ignore spurious ACKs, so the test would still pass if the client incorrectly sent an ACK and then a NACK.  But the odds of that happening aren't that high, and ultimately the current ACK/NACK semantics are fuzzy enough that that would probably be okay behavior anyway.

**Option 2: Use a different xDS server for the client and server**

Now that #27938 has been merged, you can change the tests to just use a different xDS server for the client and server.

This isn't as general of a solution as option 1; instead of fixing the `WaitForNack()` infrastructure to handle this problem for all callers, it would require that we explicitly change all affected callers to use a separate xDS server for the client and server.  However, there aren't a huge number of tests that both call `WaitForNack()` and have both xDS-enabled client and server, so the cost of being less general isn't that high.  And this option would avoid the problem of incorrectly accepting spurious ACKs that we'd have with option 1.

I think I could live with either option, so feel free to pick between them (or suggest another alternative).

**Comment by yashykt** [comment]
Updated to save a vector of updates for each resource type.

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks pretty good!  Comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28467#-:-Mt4uNd875f5iIEzn2nx:bcckk1n)* status: all files reviewed, 8 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_client.cc, line 1935 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4u1IY1Wg1HyMAVFI0:-Mt4u1IY1Wg1HyMAVFI1:bc0xjxp) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/src/core/ext/xds/xds_client.cc#L1935)):*
> ```cpp
>   // Clean up empty map entries, if any.
>   if (resource_state.watchers.empty()) {
>     authority_state.channel_state->UnsubscribeLocked(type, *resource_name,
> ```

At this point, this change seems unrelated to the rest of this PR.  I think we should split this out into a separate PR.

We should also add a test that exercises this bug.  The test can have two channels that both subscribe to the same resource.  Then we destroy one of the channels and send an xDS update for the resource, and we make sure that the remaining channel still sees the update.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1304 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4rllm8LcqZbQ8Ucfi:-Mt4rllm8LcqZbQ8Ucfj:b-a5zzab) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_end2end_test.cc#L1304)):*
> ```cpp
>                               }
>                               auto state_queue = get_state();
>                               return !(get_nack_response_state().has_value());
> ```

If you change `AdsServiceImpl::GetResponseState()` to return just the most recent value in the queue, as I suggested in xds_server.h, then this can be a lot simpler.  First, declare a local variable before calling `CheckRpcSendFailure()`:

```
absl::optional<AdsServiceImpl::ResponseState> response_state;
```

Then, inside the lambda, do this:

```
response_state = get_state();  // Set local variable captured from outside lambda.
return response_state.has_value() &&
       response_state->state == AdsServiceImpl::ResponseState::NACKED;
```

Then you can just return `response_state` at the end of the function.
___
*[test/cpp/end2end/xds/xds_server.h, line 72 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4qoFb28uI5SN8vvB3:-Mt4qoFb28uI5SN8vvB4:b-w03r9s) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L72)):*
> ```objc
>   struct ResponseState {
>     enum State {
>       NOT_SENT,  // No response sent yet.
> ```

We probably no longer need the `NOT_SENT` and `SENT` states.
___
*[test/cpp/end2end/xds/xds_server.h, line 147 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4oQcq8rFsJTS1l81q:-Mt4oQcq8rFsJTS1l81r:bvazubb) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L147)):*
> ```objc
> 
>   // Get the list of response state for each resource type.
>   std::vector<ResponseState> GetResponseState(const std::string& type_url) {
> ```

Instead of having this return a vector, let's just have it return the next item from the queue, if any.  The return type can be `absl::optional<ResponseState>`.

I think this will avoid the need for callers to deal with the queue, which will simplify things a bit.
___
*[test/cpp/end2end/xds/xds_server.h, line 387 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4ocLU6DFPt7hyOcZP:-Mt4ocLU6DFPt7hyOcZQ:bp77gdr) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L387)):*
> ```objc
>       // (This will be absent on the first request on a stream.)
>       if (request.response_nonce().empty()) {
>         gpr_log(GPR_ERROR, "HERE");
> ```

Please remove before merging.
___
*[test/cpp/end2end/xds/xds_server.h, line 390 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4pFc--uxjNLgvhz7O:-Mt4pFc--uxjNLgvhz7P:b6g50tc) ([raw file](https://github.com/grpc/grpc/blob/7759632a2d85aeb30caef990b01abb9e878401da/test/cpp/end2end/xds/xds_server.h#L390)):*
> ```objc
>         int client_nonce;
>         GPR_ASSERT(absl::SimpleAtoi(request.response_nonce(), &client_nonce));
>         // Ignore requests with stale nonces.
> ```

We still need to ignore requests from the client with stale nonces, since that's part of the xDS spec:

https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#resource-updates
___
*[test/cpp/end2end/xds/xds_server.h, line 397 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4od_JAHu2h43kstqF:-Mt4od_JAHu2h43kstqG:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L397)):*
> ```objc
>             << "resource_type: " << v3_resource_type;
>       } else {
>         gpr_log(GPR_ERROR, "HERE");
> ```

Same here.
___
*[test/cpp/end2end/xds/xds_server.h, line 648 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4qX3n0nlvY6PxwebG:-Mt4qX3n0nlvY6PxwebH:b-kbzcl8) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L648)):*
> ```objc
>   grpc_core::Mutex ads_mu_;
>   bool ads_done_ ABSL_GUARDED_BY(ads_mu_) = false;
>   std::map<std::string /* type_url */, std::vector<ResponseState>>
> ```

Suggest using `std::deque<>` instead of `std::vector<>` here, since that data structure is better suited to represent a queue.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28467)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1304 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4rllm8LcqZbQ8Ucfi:-Mt5DbkW9mV_DFSpg7OX:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_end2end_test.cc#L1304)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If you change `AdsServiceImpl::GetResponseState()` to return just the most recent value in the queue, as I suggested in xds_server.h, then this can be a lot simpler.  First, declare a local variable before calling `CheckRpcSendFailure()`:

```
absl::optional<AdsServiceImpl::ResponseState> response_state;
```

Then, inside the lambda, do this:

```
response_state = get_state();  // Set local variable captured from outside lambda.
return response_state.has_value() &&
       response_state->state == AdsServiceImpl::ResponseState::NACKED;
```

Then you can just return `response_state` at the end of the function.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_server.h, line 72 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4qoFb28uI5SN8vvB3:-Mt5DeLdBRSIl_2PH0UA:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L72)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We probably no longer need the `NOT_SENT` and `SENT` states.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_server.h, line 147 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4oQcq8rFsJTS1l81q:-Mt5DfwD9RJA-UODVu6P:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L147)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of having this return a vector, let's just have it return the next item from the queue, if any.  The return type can be `absl::optional<ResponseState>`.

I think this will avoid the need for callers to deal with the queue, which will simplify things a bit.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_server.h, line 387 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4ocLU6DFPt7hyOcZP:-Mt5DhKQ-DxcnEZmg7od:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L387)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove before merging.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_server.h, line 390 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4pFc--uxjNLgvhz7O:-Mt529usAFbi10iJycWG:blxuxpx) ([raw file](https://github.com/grpc/grpc/blob/7759632a2d85aeb30caef990b01abb9e878401da/test/cpp/end2end/xds/xds_server.h#L390)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We still need to ignore requests from the client with stale nonces, since that's part of the xDS spec:

https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#resource-updates
</blockquote></details>

You are right, but I believe it needs to be done after checking for ACK/NACK, so that we don't miss anything.



_Code quote:_
```objc
        // Ignore requests with stale nonces.
        if (client_nonce < sent_state->nonce) return;
```
___
*[test/cpp/end2end/xds/xds_server.h, line 397 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4od_JAHu2h43kstqF:-Mt5DhpA-fQPCXy8dsiJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L397)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_server.h, line 648 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4qX3n0nlvY6PxwebG:-Mt5Dj5U5P3kYMwpO6Kw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/test/cpp/end2end/xds/xds_server.h#L648)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest using `std::deque<>` instead of `std::vector<>` here, since that data structure is better suited to represent a queue.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_client.cc, line 1935 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4u1IY1Wg1HyMAVFI0:-Mt5DkzI8CVchjobKSQs:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a7d82be65961e1c646a2c47a5318aac8c5184e3a/src/core/ext/xds/xds_client.cc#L1935)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

At this point, this change seems unrelated to the rest of this PR.  I think we should split this out into a separate PR.

We should also add a test that exercises this bug.  The test can have two channels that both subscribe to the same resource.  Then we destroy one of the channels and send an xDS update for the resource, and we make sure that the remaining channel still sees the update.
</blockquote></details>

Done.

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks really good!  Remaining comments are all minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28467#-:-Mt97yfs5mTmx7tMnq50:b-lhudij)* status: all files reviewed, 6 unresolved discussions (waiting on @yashykt)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1295 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt92KC_BdWdAGOFTIM-:-Mt92KC_BdWdAGOFTIM0:bfrhcry) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L1295)):*
> ```cpp
>                               }
>                               response_state = get_state();
>                               return !(
> ```

Suggest writing this as:

```
!response_state.has_value() ||
response_state->state !=
    AdsServiceImpl::ResponseState::NACKED
```

That way, there's no need for the outer parens.

Same thing for all of the similar conditions here.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2483 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt95j7dClMAwWJTWe4E:-Mt95j7dClMAwWJTWe4F:b631oog) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2483)):*
> ```cpp
>     grpc::Status status = stub2->Echo(&context, request, &response);
>     EXPECT_FALSE(status.ok());
>     // Wait for second NACK to be reported to xDS server.
> ```

Can this be changed to use `WaitForNack()` instead of duplicating a lot of its code?
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2497 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt91c22-jFcN1obgLMZ:-Mt91c22-jFcN1obgLM_:b-odr9z) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2497)):*
> ```cpp
>                    response_state->state ==
>                        AdsServiceImpl::ResponseState::NACKED &&
>                    (::testing::Matches(::testing::ContainsRegex(absl::StrCat(
> ```

This sub-expression can be written with less duplication:

```
::testing::ContainsRegex(absl::StrCat(
    kServerName,
    ": validation error.*"
    "Listener has neither address nor ApiListener")) &&
::testing::ContainsRegex(absl::StrCat(
    kServerName2,
    ": validation error.*"
    "Listener has neither address nor ApiListener"))
```
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2544 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt95P5B6Y9_jhIOlzWL:-Mt95P5B6Y9_jhIOlzWM:b-dg2pgn) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2544)):*
> ```cpp
>   listener.clear_api_listener();
>   balancer_->ads_service()->SetLdsResource(listener);
>   // Wait for xDS server to see NACK.
> ```

Can this just use `WaitForLdsNack()` instead of reimplementing the same functionality?
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2967 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt97PDe3qfRPDOO6y9d:-Mt97PDe3qfRPDOO6y9e:b-n7c0sn) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2967)):*
> ```cpp
>   const auto response_state = WaitForLdsNack();
>   ASSERT_TRUE(response_state.has_value()) << "timed out waiting for NACK";
> ```

Please remove unnecessary blank line.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 6498 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt96a7r2JLymXPYpWZf:-Mt96a7r2JLymXPYpWZg:bdeokfn) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L6498)):*
> ```cpp
>   balancer_->ads_service()->SetCdsResource(cluster);
>   absl::optional<AdsServiceImpl::ResponseState> response_state;
>   // Wait for xDS server to see NACK.
> ```

Can this use `WaitForCdsNack()`?
___
*[test/cpp/end2end/xds/xds_server.h, line 390 at r3](https://reviewable.io/reviews/grpc/grpc/28467#-Mt4pFc--uxjNLgvhz7O:-Mt90rgACg0qLcO-h_u5:bix23r) ([raw file](https://github.com/grpc/grpc/blob/7759632a2d85aeb30caef990b01abb9e878401da/test/cpp/end2end/xds/xds_server.h#L390)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

You are right, but I believe it needs to be done after checking for ACK/NACK, so that we don't miss anything.
</blockquote></details>

Yeah, probably a good idea to do it there.  It's kind of a grey area in the spec.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28467)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1295 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt92KC_BdWdAGOFTIM-:-Mt9VDAuEMEVd-ECrt0X:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L1295)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest writing this as:

```
!response_state.has_value() ||
response_state->state !=
    AdsServiceImpl::ResponseState::NACKED
```

That way, there's no need for the outer parens.

Same thing for all of the similar conditions here.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2483 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt95j7dClMAwWJTWe4E:-Mt9VE8j5uL2C2nh3SHf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2483)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can this be changed to use `WaitForNack()` instead of duplicating a lot of its code?
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2497 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt91c22-jFcN1obgLMZ:-Mt9Hmaa0BY1KL3UQtee:b-i2f9f1) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2497)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This sub-expression can be written with less duplication:

```
::testing::ContainsRegex(absl::StrCat(
    kServerName,
    ": validation error.*"
    "Listener has neither address nor ApiListener")) &&
::testing::ContainsRegex(absl::StrCat(
    kServerName2,
    ": validation error.*"
    "Listener has neither address nor ApiListener"))
```
</blockquote></details>

:) Done!
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2544 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt95P5B6Y9_jhIOlzWL:-Mt9O6_-3bTBMTCZENPf:bdo34qg) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2544)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can this just use `WaitForLdsNack()` instead of reimplementing the same functionality?
</blockquote></details>

We can probably change `WaitForNack()` to accept an OK status... which actually sounds useful
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 6498 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt96a7r2JLymXPYpWZf:-Mt9VBi8Ev-Lja3S_ATw:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L6498)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can this use `WaitForCdsNack()`?
</blockquote></details>

Done.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28467)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2967 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt97PDe3qfRPDOO6y9d:-Mt9VQHnBheoTlirWyj6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2967)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove unnecessary blank line.
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
This looks really good!  Remaining comments are minor, so feel free to merge after addressing.

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28467#-:-Mt9dWmE-wIsWRWhKZbr:bodj02i)* status: all files reviewed, 5 unresolved discussions (waiting on @yashykt)

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2544 at r6](https://reviewable.io/reviews/grpc/grpc/28467#-Mt95P5B6Y9_jhIOlzWL:-Mt9b7h88dmHiuBdNVuB:b-ovwawk) ([raw file](https://github.com/grpc/grpc/blob/0197c5e71d219b30207e341c94bd367af03fb17b/test/cpp/end2end/xds/xds_end2end_test.cc#L2544)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We can probably change `WaitForNack()` to accept an OK status... which actually sounds useful
</blockquote></details>

Good idea!
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1299 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9_3C30sksnzL05Fn4:-Mt9_3C30sksnzL05Fn5:bjgxj63) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L1299)):*
> ```cpp
>     do {
>       const Status status = SendRpc();
>       EXPECT_EQ(expected_status, status.error_code());
> ```

Suggest adding `<< "code=" << status.error_code() << " message=" << status.error_message()`, so that when this expectation fails, the error message is more useful.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2476 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9_d3e-hzRDgQXJATp:-Mt9_d3e-hzRDgQXJATq:bvnnhxd) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L2476)):*
> ```cpp
>   const auto response_state = WaitForLdsNack();
>   ASSERT_TRUE(response_state.has_value()) << "timed out waiting for NACK";
>   EXPECT_EQ(response_state->state, AdsServiceImpl::ResponseState::NACKED);
> ```

This check is redundant; `WaitForLdsNack()` will never return any other value.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2495 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9aJvvAId6VEWKsKvp:-Mt9aJvw8duci-pjv55e:b652zoi) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L2495)):*
> ```cpp
>     const auto response_state = WaitForLdsNack();
>     ASSERT_TRUE(response_state.has_value()) << "timed out waiting for NACK";
>     EXPECT_EQ(response_state->state, AdsServiceImpl::ResponseState::NACKED);
> ```

This check is redundant.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2537 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9aexOEViYmiLtYL7h:-Mt9aexOEViYmiLtYL7i:b652zoi) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L2537)):*
> ```cpp
>   const auto response_state = WaitForLdsNack(StatusCode::OK);
>   ASSERT_TRUE(response_state.has_value()) << "timed out waiting for NACK";
>   EXPECT_EQ(response_state->state, AdsServiceImpl::ResponseState::NACKED);
> ```

This check is redundant.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 6481 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9avZ25fyScVyt6GPs:-Mt9avZ25fyScVyt6GPt:b652zoi) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L6481)):*
> ```cpp
>   const auto response_state = WaitForCdsNack(StatusCode::OK);
>   ASSERT_TRUE(response_state.has_value()) << "timed out waiting for NACK";
>   EXPECT_EQ(response_state->state, AdsServiceImpl::ResponseState::NACKED);
> ```

This check is redundant.

**Comment by yashykt** [comment]
Thanks for reviewing!

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28467)* status: 2 of 3 files reviewed, 5 unresolved discussions

___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 1299 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9_3C30sksnzL05Fn4:-MtANG-07w4s61_35hje:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L1299)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest adding `<< "code=" << status.error_code() << " message=" << status.error_message()`, so that when this expectation fails, the error message is more useful.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2476 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9_d3e-hzRDgQXJATp:-MtANGuXCk6M7WTVoDSy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L2476)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check is redundant; `WaitForLdsNack()` will never return any other value.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2495 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9aJvvAId6VEWKsKvp:-MtANHv2AoSBoIiWC-cd:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L2495)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check is redundant.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 2537 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9aexOEViYmiLtYL7h:-MtANJSXApUlkI3oUckv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L2537)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check is redundant.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 6481 at r8](https://reviewable.io/reviews/grpc/grpc/28467#-Mt9avZ25fyScVyt6GPs:-MtANMzH2ptgYWawWKyC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c99c448b7247714bc328067362bd89512f6536c5/test/cpp/end2end/xds/xds_end2end_test.cc#L6481)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check is redundant.
</blockquote></details>

Done.

**Pull request merged**
