### PR TITLE
Convert status_error to an atomic because it can be accessed from dif…

### LINKED ISSUE #16592: TSAN C++ flake: data race in call_start_batch
Happening in several test cases:
bins/tsan/client_channel_stress_test
bins/tsan/server_request_call_test --gtest_filter=ServerRequestCallTest.ShortDeadlineDoesNotCauseOkayFalse
bins/tsan/streaming_throughput_test --gtest_filter=End2endTest.StreamingThroughput

basically it says:

`SUMMARY: ThreadSanitizer: data race /var/local/git/grpc/src/core/lib/surface/call.cc:1670:28 in call_start_batch(grpc_call*, grpc_op const*, unsigned long, void*, int)`

https://source.cloud.google.com/results/invocations/5dc27523-f923-4984-9452-de1da80aa827/targets/github%2Fgrpc%2Fcpp_linux_tsan_native_x64_clang7.0/tests
https://source.cloud.google.com/results/invocations/5dc27523-f923-4984-9452-de1da80aa827/targets/github%2Fgrpc%2Fcpp_linux_tsan_native_x64_clang7.0/tests
https://source.cloud.google.com/results/invocations/5b007e5a-b441-4223-8e1c-c2a44b064fc0/targets/github%2Fgrpc%2Fcpp_linux_tsan_native_x64_clang7.0/tests

```
==================
WARNING: ThreadSanitizer: data race (pid=3260)
  Write of size 8 at 0x7b9c0006d250 by thread T9:
    #0 call_start_batch(grpc_call*, grpc_op const*, unsigned long, void*, int) /var/local/git/grpc/src/core/lib/surface/call.cc:1670:28 (client_channel_stress_test+0x819ee8)
    #1 grpc_call_start_batch /var/local/git/grpc/src/core/lib/surface/call.cc:1864:11 (client_channel_stress_test+0x8187bc)
    #2 grpc::Server::PerformOpsOnCall(grpc::internal::CallOpSetInterface*, grpc::internal::Call*) /var/local/git/grpc/src/cpp/server/server_cc.cc:671:17 (client_channel_stress_test+0x7c84b4)
    #3 grpc::internal::Call::PerformOps(grpc::internal::CallOpSetInterface*) /var/local/git/grpc/include/grpcpp/impl/codegen/call.h:671:17 (client_channel_stress_test+0x6af597)
    #4 grpc::internal::RpcMethodHandler<grpc::testing::EchoTestService::Service, grpc::testing::EchoRequest, grpc::testing::EchoResponse>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&) /var/local/git/grpc/include/grpcpp/impl/codegen/method_handler_impl.h:85:17 (client_channel_stress_test+0x7108f3)
    #5 grpc::Server::SyncRequest::CallData::Run(std::shared_ptr<grpc::Server::GlobalCallbacks> const&, bool) /var/local/git/grpc/src/cpp/server/server_cc.cc:237:16 (client_channel_stress_test+0x7cf97f)
    #6 grpc::Server::SyncRequestThreadManager::DoWork(void*, bool, bool) /var/local/git/grpc/src/cpp/server/server_cc.cc:330:10 (client_channel_stress_test+0x7ce13e)
    #7 grpc::ThreadManager::MainWorkLoop() /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:200:9 (client_channel_stress_test+0x7de215)
    #8 grpc::ThreadManager::WorkerThread::Run() /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:42:13 (client_channel_stress_test+0x7dde18)
    #9 grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::$_0::operator()(void*) const /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:36:69 (client_channel_stress_test+0x7df0c4)
    #10 grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::$_0::__invoke(void*) /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:36:7 (client_channel_stress_test+0x7df068)
    #11 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:100:27 (client_channel_stress_test+0x7eafac)
    #12 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:74:25 (client_channel_stress_test+0x7eae48)
  Previous read of size 8 at 0x7b9c0006d250 by thread T1:
    #0 set_final_status(grpc_call*, grpc_error*) /var/local/git/grpc/src/core/lib/surface/call.cc:711:43 (client_channel_stress_test+0x8200de)
    #1 recv_trailing_filter(void*, grpc_metadata_batch*, grpc_error*) /var/local/git/grpc/src/core/lib/surface/call.cc:1019:5 (client_channel_stress_test+0x81fc7b)
    #2 receiving_trailing_metadata_ready(void*, grpc_error*) /var/local/git/grpc/src/core/lib/surface/call.cc:1430:3 (client_channel_stress_test+0x81c9f0)
    #3 exec_ctx_run(grpc_closure*, grpc_error*) /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:40:3 (client_channel_stress_test+0x741879)
    #4 grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /var/local/git/grpc/./src/core/lib/iomgr/closure.h:258:5 (client_channel_stress_test+0x74d1ad)
    #5 server_recv_trailing_metadata_ready(void*, grpc_error*) /var/local/git/grpc/src/core/lib/surface/server.cc:741:3 (client_channel_stress_test+0x833c4f)
    #6 exec_ctx_run(grpc_closure*, grpc_error*) /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:40:3 (client_channel_stress_test+0x741879)
    #7 grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /var/local/git/grpc/./src/core/lib/iomgr/closure.h:258:5 (client_channel_stress_test+0x74d1ad)
    #8 recv_trailing_metadata_ready(void*, grpc_error*) /var/local/git/grpc/src/core/ext/filters/message_size/message_size_filter.cc:161:3 (client_channel_stress_test+0x9168ef)
    #9 exec_ctx_run(grpc_closure*, grpc_error*) /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:40:3 (client_channel_stress_test+0x741879)
    #10 grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /var/local/git/grpc/./src/core/lib/iomgr/closure.h:258:5 (client_channel_stress_test+0x74d1ad)
    #11 recv_trailing_metadata_ready(void*, grpc_error*) /var/local/git/grpc/src/core/ext/filters/deadline/deadline_filter.cc:136:3 (client_channel_stress_test+0x876f15)
    #12 exec_ctx_run(grpc_closure*, grpc_error*) /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:40:3 (client_channel_stress_test+0x741879)
    #13 grpc_closure_run(char const*, int, grpc_closure*, grpc_error*) /var/local/git/grpc/./src/core/lib/iomgr/closure.h:258:5 (client_channel_stress_test+0x74d1ad)
    #14 hs_recv_trailing_metadata_ready(void*, grpc_error*) /var/local/git/grpc/src/core/ext/filters/http/server/http_server_filter.cc:327:3 (client_channel_stress_test+0x8d72ef)
    #15 exec_ctx_run(grpc_closure*, grpc_error*) /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:40:3 (client_channel_stress_test+0x741879)
    #16 grpc_core::ExecCtx::Flush() /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:134:9 (client_channel_stress_test+0x741603)
    #17 GrpcExecutor::RunClosures(char const*, grpc_closure_list) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:79:32 (client_channel_stress_test+0x7427de)
    #18 GrpcExecutor::ThreadMain(void*) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:191:22 (client_channel_stress_test+0x742ed8)
    #19 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:100:27 (client_channel_stress_test+0x7eafac)
    #20 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:74:25 (client_channel_stress_test+0x7eae48)
  Location is heap block of size 12647 at 0x7b9c0006c800 allocated by thread T1:
    #0 malloc /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:666:5 (client_channel_stress_test+0x61f9c7)
    #1 gpr_malloc /var/local/git/grpc/src/core/lib/gpr/alloc.cc:57:7 (client_channel_stress_test+0x7e2a48)
    #2 gpr_malloc_aligned /var/local/git/grpc/src/core/lib/gpr/alloc.cc:93:13 (client_channel_stress_test+0x7e2caf)
    #3 zalloc_aligned(unsigned long) /var/local/git/grpc/src/core/lib/gpr/arena.cc:94:15 (client_channel_stress_test+0x88146f)
    #4 gpr_arena_create(unsigned long) /var/local/git/grpc/src/core/lib/gpr/arena.cc:101:42 (client_channel_stress_test+0x8813b9)
    #5 grpc_call_create(grpc_call_create_args const*, grpc_call**) /var/local/git/grpc/src/core/lib/surface/call.cc:299:22 (client_channel_stress_test+0x815256)
    #6 accept_stream(void*, grpc_transport*, void const*) /var/local/git/grpc/src/core/lib/surface/server.cc:800:23 (client_channel_stress_test+0x8303f9)
    #7 grpc_chttp2_parsing_accept_stream(grpc_chttp2_transport*, unsigned int) /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:801:3 (client_channel_stress_test+0x8922a4)
    #8 init_header_frame_parser(grpc_chttp2_transport*, int) /var/local/git/grpc/src/core/ext/transport/chttp2/transport/parsing.cc:595:9 (client_channel_stress_test+0x8c8b14)
    #9 init_frame_parser(grpc_chttp2_transport*) /var/local/git/grpc/src/core/ext/transport/chttp2/transport/parsing.cc:292:14 (client_channel_stress_test+0x8c7b88)
    #10 grpc_chttp2_perform_read(grpc_chttp2_transport*, grpc_slice) /var/local/git/grpc/src/core/ext/transport/chttp2/transport/parsing.cc:177:13 (client_channel_stress_test+0x8c6ab6)
    #11 read_action_locked(void*, grpc_error*) /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2501:19 (client_channel_stress_test+0x8a7f99)
    #12 grpc_combiner_continue_exec_ctx() /var/local/git/grpc/src/core/lib/iomgr/combiner.cc:260:5 (client_channel_stress_test+0x73a941)
    #13 grpc_core::ExecCtx::Flush() /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:137:17 (client_channel_stress_test+0x74161a)
    #14 GrpcExecutor::RunClosures(char const*, grpc_closure_list) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:79:32 (client_channel_stress_test+0x7427de)
    #15 GrpcExecutor::ThreadMain(void*) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:191:22 (client_channel_stress_test+0x742ed8)
    #16 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:100:27 (client_channel_stress_test+0x7eafac)
    #17 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:74:25 (client_channel_stress_test+0x7eae48)
  Thread T9 'grpcpp_sync_ser' (tid=3293, running) created by thread T8 at:
    #0 pthread_create /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:992:3 (client_channel_stress_test+0x621495)
    #1 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:73:10 (client_channel_stress_test+0x7eab56)
    #2 grpc_core::(anonymous namespace)::ThreadInternalsPosix* grpc_core::New<grpc_core::(anonymous namespace)::ThreadInternalsPosix, char const*&, void (*&)(void*), void*&, bool*>(char const*&, void (*&)(void*), void*&, bool*&&) /var/local/git/grpc/./src/core/lib/gprpp/memory.h:52:18 (client_channel_stress_test+0x7ea813)
    #3 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:142:7 (client_channel_stress_test+0x7ea634)
    #4 grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*) /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:34:10 (client_channel_stress_test+0x7ddd0d)
    #5 grpc::ThreadManager::Initialize() /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:142:9 (client_channel_stress_test+0x7defb8)
    #6 grpc::Server::SyncRequestThreadManager::Start() /var/local/git/grpc/src/cpp/server/server_cc.cc:373:7 (client_channel_stress_test+0x7cc2b5)
    #7 grpc::Server::Start(grpc::ServerCompletionQueue**, unsigned long) /var/local/git/grpc/src/cpp/server/server_cc.cc:603:12 (client_channel_stress_test+0x7c7d2d)
    #8 grpc::ServerBuilder::BuildAndStart() /var/local/git/grpc/src/cpp/server/server_builder.cc:345:11 (client_channel_stress_test+0x7b301e)
    #9 grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>::Start(std::string const&, std::mutex*, std::condition_variable*) /var/local/git/grpc/test/cpp/client/client_channel_stress_test.cc:193:25 (client_channel_stress_test+0x6ca6ee)
    #10 void std::_Mem_fn<void (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>::*)(std::string const&, std::mutex*, std::condition_variable*)>::operator()<std::string&, std::mutex*&, std::condition_variable*&, void>(grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>*, std::string&, std::mutex*&, std::condition_variable*&) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (client_channel_stress_test+0x6cce9e)
    #11 void std::_Bind<std::_Mem_fn<void (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>::*)(std::string const&, std::mutex*, std::condition_variable*)> (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>*, std::string, std::mutex*, std::condition_variable*)>::__call<void, , 0ul, 1ul, 2ul, 3ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1263:11 (client_channel_stress_test+0x6cccfb)
    #12 void std::_Bind<std::_Mem_fn<void (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>::*)(std::string const&, std::mutex*, std::condition_variable*)> (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>*, std::string, std::mutex*, std::condition_variable*)>::operator()<, void>() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1321:17 (client_channel_stress_test+0x6ccba9)
    #13 void std::_Bind_simple<std::_Bind<std::_Mem_fn<void (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>::*)(std::string const&, std::mutex*, std::condition_variable*)> (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>*, std::string, std::mutex*, std::condition_variable*)> ()>::_M_invoke<>(std::_Index_tuple<>) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (client_channel_stress_test+0x6ccb08)
    #14 std::_Bind_simple<std::_Bind<std::_Mem_fn<void (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>::*)(std::string const&, std::mutex*, std::condition_variable*)> (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>*, std::string, std::mutex*, std::condition_variable*)> ()>::operator()() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (client_channel_stress_test+0x6ccaa8)
    #15 std::thread::_Impl<std::_Bind_simple<std::_Bind<std::_Mem_fn<void (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>::*)(std::string const&, std::mutex*, std::condition_variable*)> (grpc::testing::(anonymous namespace)::ClientChannelStressTest::ServerThread<grpc::testing::TestServiceImpl>*, std::string, std::mutex*, std::condition_variable*)> ()> >::_M_run() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (client_channel_stress_test+0x6cc5ac)
    #16 <null> <null> (libstdc++.so.6+0xb696f)
  Thread T1 'default-executo' (tid=3271, running) created by main thread at:
    #0 pthread_create /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:992:3 (client_channel_stress_test+0x621495)
    #1 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:73:10 (client_channel_stress_test+0x7eab56)
    #2 grpc_core::(anonymous namespace)::ThreadInternalsPosix* grpc_core::New<grpc_core::(anonymous namespace)::ThreadInternalsPosix, char const*&, void (*&)(void*), void*&, bool*>(char const*&, void (*&)(void*), void*&, bool*&&) /var/local/git/grpc/./src/core/lib/gprpp/memory.h:52:18 (client_channel_stress_test+0x7ea813)
    #3 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:142:7 (client_channel_stress_test+0x7ea634)
    #4 GrpcExecutor::SetThreading(bool) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:115:9 (client_channel_stress_test+0x742040)
    #5 GrpcExecutor::Init() /var/local/git/grpc/src/core/lib/iomgr/executor.cc:58:29 (client_channel_stress_test+0x741b7d)
    #6 grpc_executor_init() /var/local/git/grpc/src/core/lib/iomgr/executor.cc:372:37 (client_channel_stress_test+0x743d3b)
    #7 grpc_iomgr_init() /var/local/git/grpc/src/core/lib/iomgr/iomgr.cc:54:3 (client_channel_stress_test+0x744aa1)
    #8 grpc_init /var/local/git/grpc/src/core/lib/surface/init.cc:133:5 (client_channel_stress_test+0x80b5d3)
    #9 main /var/local/git/grpc/test/cpp/client/client_channel_stress_test.cc:323:3 (client_channel_stress_test+0x6c45b3)
SUMMARY: ThreadSanitizer: data race /var/local/git/grpc/src/core/lib/surface/call.cc:1670:28 in call_start_batch(grpc_call*, grpc_op const*, unsigned long, void*, int)
==================
```

### PR DESCRIPTION
**Pull request by yashykt**
…ferent threads at the same time. should fix #16592

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,961,099      Total (>)      1,961,079

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,883,615      Total (>)     10,883,611

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
Thanks for reviewing! All green and merging

**Pull request merged**
