### PR TITLE
Performance proto polishing

### PR DESCRIPTION
**Pull request by jtattermusch**
Based on #4146.

-- explicitly pass HistogramParams as part of ClientConfig (and make sure the default params are set by qps_driver)
-- allow specifying host to be used by server's AddListeningPort().
-- adding clarification comments to control proto fields.

### CODE REVIEW

**Comment by vjpai** [comment]
LGTM on the C++ code and protos. Have not reviewed any C# here.

**Comment by jtattermusch** [comment]
@murgatroid99  please do the C# review. I think it's basically just the https://github.com/jtattermusch/grpc/commit/18ce9d65ef8ee34f31fb9e5fd82718247061ad2a commit.

**Comment by murgatroid99** [comment]
LGTM

**Comment by vjpai** [comment]
I assume that this is DNM until PR #4146 goes in, correct?

**Comment by murgatroid99** [comment]
I just merged #4146.

**Comment by vjpai** [comment]
Ok, I've LGTMed my side so please feel free to merge when you are ready.

**Comment by jtattermusch** [comment]
Test failures on mac are unrelated: https://github.com/grpc/grpc/issues/4160

**Pull request merged**
