### PR TITLE
Update protobuf to 3.21.2

### PR DESCRIPTION
**Pull request by yashykt**
Automatic script to update protobuf did not work, so performed the update manually.

Changes -
1. Updated protobuf submodule to 3.21.2
2. Updated bazel dependencies
3. Updated check_submodules.sh
4. Modified protobuf.patch to use "4.21.2" because of the python protobuf breaking change
5. Modified bazel files to use ":well_known_type_protos" instead of ":well_known_protos" since the latter has been deprecated and removed in 3.21.2.
6. Regenerated code
7. Regenerated UPB files

### CODE REVIEW

**Comment by yashykt** [comment]
I suspect that the automatic script did not work due to the two breaking changes -
- Python proto breaking change leading to version change from 3.19.4 to 4.21.2
- Removal of ":well_known_types" target

**Comment by yashykt** [comment]
Protobuf v3.21.2 seems broken for Python. The target `'@com_google_protobuf//:protobuf_python'` is not publicly visible.

**Comment by jtattermusch** [comment]
> Automatic script to update protobuf did not work, so performed the update manually.

What didn't work? Let's fix the automation - we're going to need to fix it anyway so we might as well do it right now.

**Comment by yashykt** [comment]
> What didn't work? Let's fix the automation - we're going to need to fix it anyway so we might as well do it right now.

The errors weren't verbose enough. I'm thinking of skipping this protobuf version upgrade for the release given the issues.

**Pull request closed without merging**
