### PR TITLE
Build python artifact on Mac

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by jtattermusch** [comment]
turns out we need bdist_wheel on mac

**Comment by jtattermusch** [comment]
Ok, problem shoud be fixed. Fine to review.

**Comment by soltanmm** [comment]
Was `pip install wheel` ran on all mac builders?

**Comment by jtattermusch** [comment]
@soltanmm  not yet - other stuff needs to be installed as well.

**Comment by jtattermusch** [comment]
I installed all prerequisites on both mac workers and the artifacts got successfully built on Jenkins.
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/105/architecture=x64,language=python,platform=macos/

**Pull request merged**
