### PR TITLE
Added aggregate C files for public core libraries

### PR DESCRIPTION
**Pull request by murgatroid99**
This will be useful for bundling the C core with wrapped languages, and Ruby in particular.

### CODE REVIEW

**Comment by soltanmm** [comment]
Why can't this be done in the same way that `node_modules` was handled (plumb through `build.yaml`)?

**Comment by murgatroid99** [comment]
Ruby extensions only allow for a single glob pattern to list the files, and expects those files to be in a directory called `ext/[name]`. The simplest way to include the entirety of the C core is to put it in that directory, one way or another, and this is the best way to do that.

Plus, this is plumbing through `build.yaml`, just indirectly.

**Comment by ctiller** [comment]
We may want to use this for C++ at some point also.... it allows some better optimization opportunities for compilers.

**Comment by ctiller** [comment]
Have you tried compiling this?

**Comment by murgatroid99** [comment]
OK, I tried compiling it. This may not actually work because of static symbols with name collisions.

**Comment by ctiller** [comment]
It's possible that we could fix that. It's possible it's not worth the effort either (versus generating a .c with a single `#include` per core source file).

**Comment by ctiller** [comment]
I might prefer generating a .c file per core .c file ultimately.
We're going to have to make whatever approach we choose work with boringssl
also.

**Comment by jtattermusch** [comment]
Another reason why this is dangerous it that some of the .c files  add "local" #defines that might collide between the .c files. Along with the static functions problem I don't think this is really worth it.

**Pull request closed without merging**
