### PR TITLE
Remove redundant memset() after zalloc() a batch control

### PR DESCRIPTION
**Pull request by AspirinSJL**
All the zones in an arena are zalloc()ed. 
https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/arena.cc#L99
https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/arena.cc#L127

So, we don't need to memset() a `batch_control` to zero right after allocating it from the arena.

This change should at most reduce 6 memset() invocations (each 368B). It doesn't seem to be a big difference. But since memset() is costly, we may want to be frugal.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +88  +0.0%

  [ = ]       0 TOTAL      +88  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
Basic Tests Multi-language Linux (internal CI):  #15470
Bazel Debug build for C/C++: #14240, #15427
Bazel Opt build for C/C++: #14240, #15427

**Pull request merged**
