### PR TITLE
Census test printf fix

### PR DESCRIPTION
**Pull request by maxwell-demon**

### CODE REVIEW

**Comment by ctiller** [comment]
This will need to be merged with master and re-pushed before merging - to ensure travis tests pass.

**Comment by ctiller** [comment]
Is this dead?

**Comment by ctiller** [comment]
Closing as there's been no activity for months.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @tbetbetbe isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/
* User @a-veitch isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
