### PR TITLE
[PSM Interop] Fix Python 3.11 dependencies issues

### PR DESCRIPTION
**Pull request by sergiitk**
Updated dependencies:
- pyasn1 `0.5.0` -> `0.4.8`: https://pyasn1.readthedocs.io/en/latest/changelog.html
- pyasn1-modules `0.2.8` -> `0.3.0`: https://github.com/pyasn1/pyasn1-modules/blob/main/CHANGES.txt
- grpcio* `1.48.2` -> `1.57.0`: https://pypi.org/project/grpcio-status/
- protobuf `3.20.3` -> `4.24.1`: BREAKING: https://protobuf.dev/news/2022-05-06/
- xds-protos `0.0.11` -> `1.58.0rc1`: BREAKING - proto descriptors for `Any` messages need to be imported separately

### CODE REVIEW

**Comment by sergiitk** [comment]
- [ ] [grpc/core/v1.55.x/branch/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/)
- [ ] [grpc/core/v1.55.x/branch/linux/psm-security](https://source.cloud.google.com/results/invocations/)
- [ ] [grpc/core/v1.55.x/branch/linux/grpc_xds_url_map](https://source.cloud.google.com/results/invocations/)

**Comment by sergiitk** [comment]
csds needs to be updated.

```py
Traceback (most recent call last):
  File "/Users/sergiitk/Development/grpc/tools/run_tests/xds_k8s_test_driver/tests/url_map/csds_test.py", line 20, in <module>
    from framework import xds_url_map_testcase
  File "/Users/sergiitk/Development/grpc/tools/run_tests/xds_k8s_test_driver/framework/xds_url_map_testcase.py", line 33, in <module>
    from framework import xds_k8s_testcase
  File "/Users/sergiitk/Development/grpc/tools/run_tests/xds_k8s_test_driver/framework/xds_k8s_testcase.py", line 43, in <module>
    from framework.rpc import grpc_csds
  File "/Users/sergiitk/Development/grpc/tools/run_tests/xds_k8s_test_driver/framework/rpc/grpc_csds.py", line 25, in <module>
    from envoy.extensions.filters.common.fault.v3 import fault_pb2 as _
  File "/Users/sergiitk/Development/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.9/site-packages/envoy/extensions/filters/common/fault/v3/fault_pb2.py", line 14, in <module>
    from envoy.type.v3 import percent_pb2 as envoy_dot_type_dot_v3_dot_percent__pb2
  File "/Users/sergiitk/Development/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.9/site-packages/envoy/type/v3/percent_pb2.py", line 14, in <module>
    from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
  File "/Users/sergiitk/Development/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.9/site-packages/udpa/annotations/status_pb2.py", line 35, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Users/sergiitk/Development/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by sergiitk** [comment]
cc @gnossen @eugeneo

**Comment by sergiitk** [comment]
- [ ] [grpc/java/v1.57.x/branch/xds_k8s_lb](https://source.cloud.google.com/results/invocations/98ecc20d-e2e5-40c5-a595-09ad5bb98db7)
- [ ] [grpc/java/v1.57.x/branch/psm-security](https://source.cloud.google.com/results/invocations/27b3a519-2d3a-4bc9-9ff4-653d43926047)
- [ ] [grpc/java/v1.57.x/branch/xds_url_map](https://source.cloud.google.com/results/invocations/8f77f5c8-398e-471d-906c-0ecc97ada7b3)

**Comment by sergiitk** [comment]
Getting csds-related errors:

```
Traceback (most recent call last):
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 408, in _CreateMessageFromTypeUrl
    message_descriptor = pool.FindMessageTypeByName(type_name)
KeyError: "Couldn't find message envoy.config.listener.v3.Listener"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/tests/round_robin_test.py", line 61, in test_round_robin
    self.assertXdsConfigExists(test_client)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/framework/xds_k8s_testcase.py", line 513, in assertXdsConfigExists
    json_format.MessageToJson(config, indent=2),
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 132, in MessageToJson
    return printer.ToJsonString(message, indent, sort_keys, ensure_ascii)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 199, in ToJsonString
    js = self._MessageToJsonObject(message)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 212, in _MessageToJsonObject
    return self._RegularMessageToJsonObject(message, js)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 241, in _RegularMessageToJsonObject
    js[name] = [self._FieldToJsonObject(field, k)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 241, in <listcomp>
    js[name] = [self._FieldToJsonObject(field, k)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 281, in _FieldToJsonObject
    return self._MessageToJsonObject(value)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 212, in _MessageToJsonObject
    return self._RegularMessageToJsonObject(message, js)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 247, in _RegularMessageToJsonObject
    js[name] = self._FieldToJsonObject(field, value)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 281, in _FieldToJsonObject
    return self._MessageToJsonObject(value)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 210, in _MessageToJsonObject
    return methodcaller(_WKTJSONMETHODS[full_name][0], message)(self)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 330, in _AnyMessageToJsonObject
    sub_message = _CreateMessageFromTypeUrl(type_url, self.descriptor_pool)
  File "/tmp/tmp.MHgUHUKyGZ/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/google/protobuf/json_format.py", line 410, in _CreateMessageFromTypeUrl
    raise TypeError(
TypeError: Can not find message descriptor by type_url: [type.googleapis.com/envoy.config.listener.v3.Listener](https://www.google.com/url?q=http://type.googleapis.com/envoy.config.listener.v3.Listener&sa=D)
```

**Comment by sergiitk** [comment]
- [ ] [grpc/java/v1.57.x/branch/xds_k8s_lb](https://source.cloud.google.com/results/invocations/aaa1b5c8-0970-4f2f-b19c-8a12f755f5d7)
- [ ] [grpc/java/v1.57.x/branch/psm-security](https://source.cloud.google.com/results/invocations/a2181378-2377-4dcd-9225-0ee07426d566)
- [ ] [grpc/java/v1.57.x/branch/xds_url_map](https://source.cloud.google.com/results/invocations/20017399-1759-48e7-a41b-5a8a209b03d9)

**Review by gnossen — APPROVED** [review]

**Comment by sergiitk** [comment]
Related: https://github.com/grpc/grpc/pull/34171

**Pull request merged**
