### PR TITLE
give run_performance_tests a main method

### PR DESCRIPTION
**Pull request by pongad**
In this way, external users can add perf tests for other languages
by adding to scenario_config.LANGUAGES then calling
run_performance_tests.main.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by pongad** [comment]
@fengli79 @shinfan Can you guys take a look?

One question I wasn't able to resolve: currently all languages are [built](https://github.com/grpc/grpc/blob/61c913531c1b36a810b39785ae88e1c549ef2939/tools/run_tests/run_performance_tests.py#L237) with `build_performance.sh`. An external user wouldn't be able to provide their own build script. I thought about something like this:

We could give each language (in scenario_config) a method `build_cmdline` that returns the command used to build the language. But then builds of different languages will run in parallel and all [compile C++ code](https://github.com/grpc/grpc/blob/61c913531c1b36a810b39785ae88e1c549ef2939/tools/run_tests/performance/build_performance.sh#L31) leading to a race.

Does gRPC team have an opinion on how to best resolve this? Maybe compile C++ in a separate jobset?

**Comment by fengli79** [comment]
@pongad ,
My understanding is C/C++ always get compiled first, and then all wrapper languages should use the built artifacts. As veneer supports multiple languages, you can add additional commands to build them, but all of them should depends on previous C/C++ outputs, I don't see a race there.

**Comment by fengli79** [comment]
@adelez why change like this doesn't trigger any test?

**Comment by adelez** [comment]
@matt-kwong , AFAIK, since we switched to Kokoro, outside contributors' PRs need to have label kokoro:run for running the tests.

**Comment by fengli79** [comment]
@adelez 
There are some tests either failed or keep hanging:
1. Basic Tests Windows (internal CI)
2. Interop Cloud-to-Prod Tests (internal CI) 
3. Basic Tests C & C++ Linux [dbg] (internal CI)
4. Basic Tests C & C++ Linux [opt] (internal CI)
5. Basic Tests Multi-language Linux (internal CI)
Is it expected?

**Comment by pongad** [comment]
A bunch of these tests are also failing in other PRs, so I don't think it's related to this change. Not sure about "expected" though.

**Comment by matt-kwong** [comment]
The hanging issues were fixed yesterday, after these tests were run. The interop failure looks like a flake. 

The tests we run on PRs shouldn't cover the changes. Performance tests take a long time, so we trigger those manually. Feng/Adele, please make sure someone builds https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_adhoc/ before merging this.

**Comment by adelez** [comment]
All the tests finished. The failures are all test failures, except the first one that says "infrastructure error". You can ignore this one for now. For the test failures. the normal workflow is either file a bug or find an existing bug and list them here. Please also post the sponge link if you are filing a bug.

**Comment by pongad** [comment]
@adelez The multi-language test failed by #10142. The rest are also connection failures, similar to other PRs like #12244. A bunch of these are internal CIs, are we OK posting links?

**Comment by adelez** [comment]
Yes, it's ok to post. Please use Sponge links rather than CI build links though.

**Comment by pongad** [comment]
@adelez I posted issue for test flake at #12279. Just a reminder: I don't have write access to this repo :)

**Comment by adelez** [comment]
Please wait for @jtattermusch's approval for merge. I never worked on this script.

**Comment by jtattermusch** [comment]
So I don't see much value in "external users can add perf tests for other languages
by adding to scenario_config.LANGUAGES then calling
run_performance_tests.main." (because anyone can just modify the scenario_config.py script to achieve the same result), but I think there's some value in refactoring the code of run_performance_tests.py.

The changes look fair to me, but we'll need to test the changes first (how did you test?) - the problem is we are no longer running tests using this script on pull requests, so we need some out of band indication that this change is actualy safe.

**Comment by pongad** [comment]
@jtattermusch I ran the script locally on a few languages :)

I guess I was trying to avoid forking grpc. In that way, I don't need to deal with merge conflicts. I guess it's possible that scenario_config will change in ways that break the external script. I guess experience will tell :)

**Comment by pongad** [comment]
@jtattermusch Ping, if this looks good to you can you merge this? I don't have write access to this repo.

**Comment by jtattermusch** [comment]
None of the tests on the PR is affected by changes in run_performance_tests.py, so I will merge this (based on the fact that it has been tested manually). After merging, we need to watch to perf dashboard https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584 to double check the change didn't break anything.

**Comment by pongad** [comment]
Looking at the test dashboard, everything seems to be working OK. I'll keep an eye on it for a while longer though.

**Pull request merged**
