### PR TITLE
Add a dummy function to grpc cfstream library

### PR DESCRIPTION
**Pull request by yashykt**
Add a dummy function to grpc cfstream library

### CODE REVIEW

**Comment by muxi** [comment]
did it solve the problem?

**Comment by yashykt** [comment]
we would need to submit this PR to verify whether it works

**Comment by muxi** [comment]
ok

**Comment by yashykt** [comment]
Thanks @muxi! I'll merge this as soon as the tests are done running, and check whether it works.

**Comment by yashykt** [comment]
This seems to have solved the issue for windows kokoro builds

**Comment by nicolasnoble** [comment]
Called it.

**Comment by muxi** [comment]
lol

**Comment by srini100** [comment]
Please backport to v1.20.x too.

**Pull request merged**
