### PR TITLE
Fix Flatbuffer compatibility issues

### PR DESCRIPTION
**Pull request by per-gron**
According to @aardappel in https://github.com/google/flatbuffers/pull/4305, `cpp_generator.cc`, `cpp_generator.h` and `schema_interface.h` are supposed to be able to be used as-is copied from here to flatbuffers.git. This was the case before, but it is no longer true.

In this PR I have attempted to restore this, making as few changes as possible to this code. For more details about the reasoning about the changes I have made, have a look at the individual commit messages.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by aardappel** [comment]
Thanks! The filenames have `.pb` in them though, which is protobuf specific?

**Comment by per-gron** [comment]
@aardappel `.pb.` is part of the filenames that are generated by the main (non Flatbuffer) gRPC code. I can't just remove that, so what I did was to move it out to `config.h`, which I assumed is there to be able to configure certain format-specific parameters. That file already has protobuf-y stuff in it, which seems okay to me.

After this PR, Flatbuffers will be able to use `cpp_generator.cpp`, `cpp_generator.h` and `schema_interface.h` as-is, but it will have to provide a Flatbuffer-specific config.h

**Comment by aardappel** [comment]
@per-gron Ok, sounds good.

**Comment by yang-g** [comment]
jenkins: this is ok to test

**Comment by per-gron** [comment]
@yang-g: I fixed the clang-format issues. The other ones seem like flaky tests to me, or am I missing something?

**Comment by yang-g** [comment]
Test flakes:  #11105 #11116  #9542

**Pull request merged**
