### PR TITLE
Better slice management for windows reads (for v1.17.x)

### PR DESCRIPTION
**Pull request by jtattermusch**
Backports #17377 into v1.17.x

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,496      Total (=)      2,020,496

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,619      Total (<)     11,175,625

 No significant differences in binary sizes


```

**Comment by jtattermusch** [comment]
ad the "RELEASE BLOCKER" label: it's totally fine not to block the v1.17.0 release, but this fix seems important enough that v1.17.1 should be started right after releasing v1.17.0. Leaving the decision upon @muxi

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/17138

**Comment by jtattermusch** [comment]
@nicolasnoble  @muxi  let's approve this PR and get it merged instead of #17377 (and do upmerge v1.17.x -> master afterwards instead).

**Comment by jtattermusch** [comment]
@nicolasnoble  already approved #17377 which is exactly the same code.

**Comment by jtattermusch** [comment]
Setting "release notes:no" to prevent this PR from showing up in v1.18 release notes (it's already in v1.17 release notes).

**Pull request merged**
