### PR TITLE
Upmerge 1.2.4 into master

### PR DESCRIPTION
**Pull request by murgatroid99**

### CODE REVIEW

**Comment by apolcyn** [comment]
I think the added project.json probably need to be removed, they shouldn't be in master (they were taken out by #10480), though might not cause build failures

**Comment by murgatroid99** [comment]
OK, I redid the merge without those project.json files.

**Comment by murgatroid99** [comment]
The sanity tests failed, so I tried the merge again. And I definitely ran `generate_projects` this time.

**Comment by dgquintas** [comment]
I'm done waiting.

Issues: #9185 #9542

**Comment by murgatroid99** [comment]
There was also #10567 and #10640.

**Pull request merged**
