### PR TITLE
Add Cygwin platform definitions. Allows compiling with both g++ and clang 3.8.

### PR DESCRIPTION
**Pull request by kskalski**
Refreshed version of https://github.com/grpc/grpc/pull/9218#issuecomment-270782951

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by yang-g** [comment]
Seems obsolete, closing.

**Pull request closed without merging**
