### PR TITLE
Removed unnecessary assert on size check of address in tcp_server_uti…

### PR DESCRIPTION
**Pull request by andrewheard**
…ls_posix_common.cc after conversion to socklen_t.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                           FILE SIZE
 ++++++++++++++ GROWING                                             ++++++++++++++

 -------------- SHRINKING                                           --------------
  -2.7%     -48 src/core/lib/iomgr/tcp_server_utils_posix_common.cc     -48  -2.7%
      -6.7%     -52 grpc_tcp_server_prepare_socket                          -52  -6.7%

 -+-+-+-+-+-+-+ MIXED                                               +-+-+-+-+-+-+-
  +0.0%     +16 [None]                                                  -80  -0.0%

  -0.0%     -32 TOTAL                                                  -128  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by yashykt** [comment]
I've initiated the tests. Can you also please squash the commits?

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
No longer needed

**Pull request closed without merging**
