### PR TITLE
Fix resource_quota bug

### LINKED ISSUE #13999: h2_census_test resource_quota_server flaky on macos since 2018-01-10
See https://screenshot.googleplex.com/PB6WVs5BkWK

Example: https://sponge.corp.google.com/target?id=e7357717-490c-45ea-a279-3536834ba801&target=github/grpc/c_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

### PR DESCRIPTION
**Pull request by ncteisen**
Attempt to fix #13999

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%     +16 [None]                                                                               +16  +0.0%
  +0.0%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                          +16  +0.0%
      +5.5%     +16 removal_error(grpc_error*, grpc_chttp2_stream*, char const*) [clone .isra.2]         +16  +5.5%

  +0.0%     +32 TOTAL                                                                                +32  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by jtattermusch** [comment]
@ncteisen  I did several thousand runs on my machine and so far it's looking good - I'm unable to reproduce anymore.  Thanks!

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
So this was not the correct way to fix this. Many tests rely on the error status being propagated up past "stream removed". Clobbering it with UNAVAILABLE is not the right move.

Instead I have narrowed the problem to
https://github.com/grpc/grpc/blob/306503861733e0210e25d4bb31907914f9d5b24e/src/core/lib/surface/call.cc#L1099

In which the call reads the metadata and sees that 2 has been set. Now I will track back and figure out why that metadata was there in the first place

**Comment by ncteisen** [comment]
@jtattermusch I think I have the right fix this time. The issue being in poll makes sense that it is only flaky on Mac.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                           FILE SIZE
 ++++++++++++++ GROWING                             ++++++++++++++
  +0.0%     +24 [None]                                 +328  +0.0%
  +0.7%     +80 src/core/lib/iomgr/ev_poll_posix.cc     +80  +0.7%
       +39%     +46 fd_shutdown_error                       +46   +39%
      +9.0%     +32 notify_on_locked                        +32  +9.0%
      +0.6%      +2 [Unmapped]                               +2  +0.6%

  +0.0%    +104 TOTAL                                  +408  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Failures: #14291

**Comment by jtattermusch** [comment]
@ncteisen   thanks for the fix, you're a star!

I tested the fix locally and I can confirm it mitigates the problem (so I have no reservations from that perspective) but I'd rather delegate the review to someone with better knowledge of C core codebase - my approval would be based mostly on faith.

**Pull request merged**
