### PR TITLE
xds client bootstrap file

### PR DESCRIPTION
**Pull request by markdroth**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/20380)

### CODE REVIEW

**Comment by markdroth** [comment]
It looks like I need to revamp the error-handling here a bit.  Please hold off on reviewing for now.

**Comment by markdroth** [comment]
This is once again ready for review.

**Comment by markdroth** [comment]
The changes were pushed in commit eea5c40.  Maybe try reloading?

**Comment by markdroth** [comment]
Known issues: #20545 #18840 #20519 #20502

**Comment by nanahpang** [comment]
Hi, Mark
Could you try to sync to head and then rebuild your PR? Jan has modified the build file before you merged. It is possible that you run the tests before Jan's change got merged, so you didn't see the 
 tests are broken. If that is the case, sync and rebuild will solve this problem.

**Pull request merged**
