### PR TITLE
SerializationTraits: Remove unnecessary 2nd template parameter

### PR DESCRIPTION
**Pull request by yashykt**
Internal reference b/67717285

### CODE REVIEW

**Comment by yashykt** [comment]
@vjpai I'll let you write it :P

**Comment by vjpai** [comment]
I was just about to approve

**Review by vjpai — APPROVED** [review]
Even though I might have wanted to commit this PR for "sentimental" reasons, it makes a lot more sense for y'all to do it since I'll have to set up clang-format etc on my system.

Actually @AspirinSJL really helped identify this issue and deserves the credit for pointing us toward a compiler bug. Send her a PB if you can. (I'd be happy to get a lunch invite the next time I'm in the SVL area in exchange for this approval. Or just let me know when you'd like a lunch invite to SSF in exchange for discussing gRPC.)

**Review by ctiller — APPROVED** [review]

**Comment by vjpai** [comment]
I hope the meeting for that 5-year-old calendar invite went something like this:

Animated gif of people celebrating

**Pull request merged**
