### PR TITLE
Fix c-ares tests under gcc musl

### PR DESCRIPTION
**Pull request by apolcyn**
fixes https://github.com/grpc/grpc/issues/14928 - the DNS server was [failing to import the yaml package](https://github.com/grpc/grpc/blob/master/test/cpp/naming/utils/dns_server.py#L20)

also starts `cat`'ing the DNS server's log if it failed to start

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by jtattermusch** [comment]
I ran the tests locally and it seems to be fixing the problem.

I also ran `tools/dockerfile/push_testing_images.sh` on your branch to make sure the updated docker image is available when running the test on kokoro.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
