### PR TITLE
Split port_platform.h into public and private headers for maintainability

### PR DESCRIPTION
**Pull request by murgatroid99**
For the first part of this, I created `grpc_inet_ntop` to ensure that every reference to network-related `GPR_*` constants is in `scr/core/lib/iomgr/`.

### CODE REVIEW

**Comment by murgatroid99** [comment]
OK, all of the basic test failures so far are "Agent went offline during build"

**Comment by murgatroid99** [comment]
@ctiller Can you take a look at this?

**Comment by ctiller** [comment]
@yang-g is taking a look in my stead, as he's working on related stuff.

**Comment by murgatroid99** [comment]
Ping @yang-g

**Comment by murgatroid99** [comment]
This has been folded into #8125, and has not been maintained.

**Pull request closed without merging**
