### PR TITLE
Python source distribtests

### PR DESCRIPTION
**Pull request by mehrdada**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by mehrdada** [comment]
Kokoro build triggered here: https://fusion.corp.google.com/invocation/bdd63f05-8619-43f8-9666-4e68f4e829d4/detail?search_pattern=artifact&include_inactive_projects=false

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
https://fusion.corp.google.com/runanalysis/test/prod%3Agrpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform/prod%3Agrpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform/KOKORO/bdd63f05-8619-43f8-9666-4e68f4e829d4/1524780424092/prod%3Agrpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform%20Build%20%23179/Target%20Transitions?target=grpc/core/experimental/grpc_build_artifacts_multiplatform

@matt-kwong For some reason the artifact build did not trigger the package build step. Retrying...

**Comment by matt-kwong** [comment]
https://source.cloud.google.com/results/invocations/54faa296-ee3d-4909-96b9-0a2d14ea5e9b/targets/github%2Fgrpc/tests

What's the distinction between `python`and `python_dev` distribtests?

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
Distribtests passed in https://fusion.corp.google.com/invocation/024de03e-f567-49a5-a4b1-3648346a5104/buildlogs

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
