### PR TITLE
Remove unnecessary invocations of make_grpcio_tools.py

### PR DESCRIPTION
**Pull request by mehrdada**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by jtattermusch** [comment]
Rationale:
- make_grpcio_tools.py has a confusing name, this script only regenerates the file lists for actually building grpcio_tools (which is why I guess we didn't spot this earlier).

- the lines being removed were actually useless, because none of the docker images running the scripts updated in this PR doesn't contain bazel - so make_grpcio_tools.py was just silently failing.
https://github.com/grpc/grpc/blob/515908ba3196d057a8465a146f667b9e6c2ad9f2/tools/distrib/python/make_grpcio_tools.py#L163

**Comment by mehrdada** [comment]
I like how "Red LGTM" above is similar to what the script does. 

I will clean up the .py file and the exception handler garbage in a followon PR to ensure step-wise correctness of the procedure and that we don't break something.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by mehrdada** [comment]
@jtattermusch It seems `make_grpcio_tools` has a dual-purpose of doing a raw directory copy of protobuf into the grpcio-tools directory and also do the bazel query for updating the dependency file list. That needs to be separated in my opinion.

However, I think this fix is best done as I move Python to its own repo, which I plan to do very soon. Let's not worry about it for now.

**Pull request closed without merging**
