### PR TITLE
Make census_tag_set the only field of census_context

### PR DESCRIPTION
**Pull request by maxwell-demon**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
+1

**Comment by ctiller** [comment]
Can you explain the reasoning here?

**Comment by maxwell-demon** [comment]
We are working on to unify tracing and census - trace_id and op_id etc.
will be represented by census tags.

All the information we need from a census context is in census_tag_set.

**Comment by bogdandrutu** [comment]
The goal is to have all the tracing ids as census tags so there is no point in having a separation between census tags and tracing ids. This is a bit different than what dapper was but will simplify the logic and the code.

**Comment by a-veitch** [comment]
LGTM. Merging...

**Pull request merged**
