### PR TITLE
Fix http server filter comment

### PR DESCRIPTION
**Pull request by hcaseyal**
Looks like a copy and paste typo

### CODE REVIEW

**Comment by hcaseyal** [comment]
Branched off the wrong branch, closing this for now

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```


Missing files (indicates new benchmark): 
    bm_call_create.BM_IsolatedFilter_CompressFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_ClientDeadlineFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ServerDeadlineFilter_SendEmptyMetadata_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_NoFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_HttpServerFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_MessageSizeFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_HttpServerFilter_SendEmptyMetadata_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_DummyFilter_SendEmptyMetadata_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_HttpClientFilter_SendEmptyMetadata_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_ServerDeadlineFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_ServerDeadlineFilter_SendEmptyMetadata_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_CompressFilter_SendEmptyMetadata_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_HttpServerFilter_SendEmptyMetadata_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientDeadlineFilter_SendEmptyMetadata_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_DummyFilter_SendEmptyMetadata_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_MessageSizeFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_MessageSizeFilter_SendEmptyMetadata_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientDeadlineFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_HttpClientFilter_SendEmptyMetadata_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_HttpClientFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_CompressFilter_SendEmptyMetadata_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_NoFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_MessageSizeFilter_SendEmptyMetadata_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_DummyFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_ServerDeadlineFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_LoadReportingFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_LoadReportingFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_LoadReportingFilter_SendEmptyMetadata_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_LoadReportingFilter_SendEmptyMetadata_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_CompressFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_HttpClientFilter_NoOp_.opt.new: 10
    bm_call_create.BM_IsolatedFilter_HttpServerFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_DummyFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientDeadlineFilter_SendEmptyMetadata_.counters.new: 10


[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
