### PR TITLE
PHP: implement custom_metadata interop, status_code_and_message, unimplemented_method tests

### LINKED ISSUE #6579: Implement custom_metadata interop test in PHP
Turns out PHP doesn't expose the trailing metadata in the API, so this interop test is currently unimplementable in PHP. Implementing that interop test is a good check that we actually expose the right API.

### PR DESCRIPTION
**Pull request by stanley-cheung**
Implement `custom_metadata` interop test for PHP. Fixes #6579

### CODE REVIEW

**Comment by stanley-cheung** [comment]
This needs #6632 to be merged first

**Comment by stanley-cheung** [comment]
Friendly ping

**Comment by stanley-cheung** [comment]
Another ping: this is just the custom_metadata interop test for PHP now

**Comment by murgatroid99** [comment]
LGTM

**Comment by murgatroid99** [comment]
test this please

**Comment by stanley-cheung** [comment]
re-based and PHP tests passed

**Comment by jtattermusch** [comment]
Let's un-blacklist the custom_metadata interop test for PHP, otherwise this change is pointless.

https://github.com/grpc/grpc/blob/master/tools/run_tests/run_interop_tests.py#L255

**Comment by stanley-cheung** [comment]
@murgatroid99 Please review this again, thanks!

So I end up implementing all of `custom_metadata`, `status_code_and_message`, `unimplemented_method` interop tests so that I can remove the `_SKIP_ADVANCED` blacklist.

Two things:
1. Since PHP is still on proto2, I need to copy over some missing fields for `messages.proto`.
2. For the `unimplemented_method` interop test, I cheated a little bit - if the method is truly undefined even in the proto, the method won't be in the generated stub, and if I try to call that, PHP will throw a Fatal Error. So I make an unimplemented method in the proto so that I can call it, which correspond to an unimplemented method on the server, and I get the desired response code.

**Comment by murgatroid99** [comment]
The existing `test.proto` file already has an `UnimplementedService` definition. You should copy that to your proto file instead of making a different one.

**Comment by stanley-cheung** [comment]
@murgatroid99  Thanks for the pointer. Fixed by copying and using `UnimplementedService`.

**Comment by murgatroid99** [comment]
LGTM

**Pull request merged**
