### PR TITLE
Set siblings for server clones properly.

### PR DESCRIPTION
**Pull request by daniel-j-born**

### CODE REVIEW

**Comment by ctiller** [comment]
CLA problems... but I'd also like to know what problem this is solving?

Maybe some explanatory text in the code to say how the siblings are supposed to be arranged?

**Comment by ctiller** [comment]
LGTM

**Comment by daniel-j-born** [comment]
I need a core gRPC team member to merge this.

**Comment by nicolasnoble** [comment]
For Jenkins: test this please

**Pull request merged**
