### PR TITLE
Adding clang packages for msan/tsan/asan testing.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
We'll need that to add asan/tsan/msan to Jenkins btw.

**Comment by nicolasnoble** [comment]
Hold on... the clang package is way too old in that image.

**Comment by nicolasnoble** [comment]
Switching the image to jessie instead of wheezy bring a proper version of clang. Let's see how Jenkins likes this.

**Comment by jtattermusch** [comment]
test this please

**Pull request merged**
