### PR TITLE
Nuking the poll-cv polling engine

### PR DESCRIPTION
**Pull request by yashykt**
Nuking the poll-cv polling engine

Supporting this polling engine does not make sense anymore, since no one seems to be using it.

### CODE REVIEW

**Comment by vjpai** [comment]
Cc: @ctiller @sreecha

**Comment by vjpai** [comment]
Looks like bazel tests are still expecting poll-cv

**Comment by vjpai** [comment]
You should do a recursive grep for poll-cv though ; it still exists for example at https://github.com/grpc/grpc/blob/620d80d8172995706da6e9f7284008ffb56869ce/test/cpp/end2end/BUILD

**Comment by jtattermusch** [comment]
I've been told in the past that poll-cv is really good for catching bugs, but because all the owners seem to be happy with removal, I'm happy too.

Btw, removing poll-cv will result in significant reduction of our test load, as poll-cv is very slow compared to other pollers. According to https://github.com/grpc/grpc/issues/14332 we spend 42% test time time running poll-cv tests.

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/18292

**Comment by jtattermusch** [comment]
I did a sweep on test flake issues mentioning poll-cv and I've closed the ones that seems to have been poll-cv specific (most of them seemed to be associated with the problem discovered by @yashykt)

**Comment by vjpai** [comment]
@jtattermusch : I think it was once helpful at catching bugs but now we have MSAN C++ which we didn't use to have, and that's helped a lot. I can't remember the last time we used poll-cv to identify a bug outside of poll-cv itself.

**Comment by yashykt** [comment]
I forgot to mention that internal tests were being run overnight to make sure that nothing breaks. The good news is that the tests completed and nothing looks suspicious.

**Pull request merged**
