### PR TITLE
Add needed include for udp_server_test

### PR DESCRIPTION
**Pull request by vjpai**
Needs to include grpc/grpc.h for grpc_init . Broken build otherwise.

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM

**Comment by vjpai** [comment]
Nope, needs some header guard cleanups.

**Comment by vjpai** [comment]
Can I get a re-review of the code since I made a possibly suspect change to a header file? The tests are green except for PHP Opt which didn't run (shakes fist in air at Jenkins)

**Comment by ctiller** [comment]
Lgtm

**Comment by nicolasnoble** [comment]
The PHP failure is Jenkins unable to clone it - so I'm force-merging that one.

**Pull request merged**
