### PR TITLE
Fix grpc_timer_list_init signature in timer_uv.cc

### LINKED ISSUE #12875: All node tests are failing in interop tests
https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/master/job/grpc_interop_tocloud/

Tests start to fail since build 470: 
https://sponge.corp.google.com/target?id=e404c081-00e5-4033-af41-0130df6297f1&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS
All tests timed out.

In this one: https://sponge.corp.google.com/target?id=6191a52e-051b-43db-aa2f-fe3320ca998d&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS
Error becomes:
Failure
node: symbol lookup error: /var/local/git/grpc/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_timer_list_init

### PR DESCRIPTION
**Pull request by murgatroid99**
This fixes #12875.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
Fixed UV issues as part of #12885

**Pull request closed without merging**
