### PR TITLE
Test BUILD file assortment

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by dgquintas** [comment]
After @nicolasnoble and I discussed it, I removed the cpp/codegen/golden_file_test because 1) problematic to get it running with bazel and 2) it's useless: it's only testing that the grpc proto compiler hasn't changed. When it did, whoever would just go and update the golden file. No actual testing of codegen is happening.

**Comment by ctiller** [comment]
Please don't remove it.

It forces the generated code to be included in the code review, which
forces that code to also be reviewed: having it there catches real problems.

**Comment by vjpai** [comment]
I agree with keeping it. In fact, we should extend it to all languages, not
just cpp. As much as I hated having to deal with it when I was working on
codegen, it does serve a real purpose with regard to compatibility and
other issues.

**Comment by dgquintas** [comment]
Ok. Actually I think I have an idea to make it work. I'll update the pr
momentarily.

**Comment by dgquintas** [comment]
jenkins test this please

**Comment by dgquintas** [comment]
Issues: #9150 #9668 #9891 #9797 #9762

**Pull request merged**
