### PR TITLE
update and add new generate_protos script in csharp examples

### PR DESCRIPTION
**Pull request by apolcyn**
This update the generate_protos.bat script to the latest Grpc.Tools version.

It also adds a copy of the script for use in the hello-world-from-cli example, in order to generate code with the script for both examples.

### CODE REVIEW

**Comment by murgatroid99** [comment]
Do these scripts do anything different? If not, can you put the output in a common directory, or if that doesn't work, can you have one script that generates both?

**Comment by apolcyn** [comment]
I think these could be changed to use a common directory, without having to have the packages restored in each one (using different tools to restore packages in each one).


By the way this is tied to the documentation change in https://github.com/grpc/grpc.github.io/pull/322/files/a329f4c42c6843da3e78fa8c9f4be643efecfaf1#r75013511

**Comment by apolcyn** [comment]
The quickstart also no longer references the bat script, and I'm now thinking that it's not worth it to have the generate_protos_script in the dotnet cli example as well, especially since that will often be used on OS X or linux. 

I think the original one should still have its tools version updated though.

**Comment by murgatroid99** [comment]
LGTM

**Comment by apolcyn** [comment]
test this please

**Pull request merged**
