### PR TITLE
[Deps] Upgrade abseil podsepc to 1.20240116.1

### PR DESCRIPTION
**Pull request by veblush**

### CODE REVIEW

**Comment by veblush** [comment]
@sampajano Would you mind taking a look at https://github.com/CocoaPods/Specs/blob/master/Specs/3/8/6/abseil/1.20240116.1/abseil.podspec.json to make sure this new abseil version has all requirements?

**Comment by HannahShiSFB** [comment]
> @sampajano Would you mind taking a look at https://github.com/CocoaPods/Specs/blob/master/Specs/3/8/6/abseil/1.20240116.1/abseil.podspec.json to make sure this new abseil version has all requirements?

Yes, it's everything we need for now. Thank you Esun @veblush 
And I will backport it to v1.49 and v1.61 as well @sampajano

**Comment by sampajano** [comment]
@veblush Thanks very much for helping here!! As @HannahShiSFB has mentioned this would be all we need at the moment!! Thanks!! 😊

**Comment by veblush** [comment]
Thanks for verification. Once this is merged, and I'm going to release old versions of Abseil podspec as well. (I only released `1.20240116.1`)

**Review by sampajano — APPROVED** [review]
@veblush Thanks so much for the help! 😃

**Pull request closed without merging**
