### PR TITLE
get rid of connectivity state watchers right after timeout

### PR DESCRIPTION
**Pull request by apolcyn**
<s>WIP as I'm not sure yet if https://github.com/grpc/grpc/compare/master...apolcyn:fix_conn_watch_mem_accum?expand=1#diff-a7c672b62938053ba5a0007a5089a1b6R1501 is correct.</s>

A recent ruby release that used constant `state watches` with short timeouts showed a constant build up of memory over time (as long there's a channel that hasn't been garbage collected).

`valgrind memcheck` showed:

```
 85.93% (15,653,862B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
 469 ->41.03% (7,473,548B) 0x7FE9066: gpr_malloc (alloc.c:71)
 470 | ->27.56% (5,020,016B) 0x7FDF019: grpc_channel_watch_connectivity_state (channel_connectivity.c:188)
 471 | | ->27.56% (5,020,016B) 0x7F9B7F1: grpc_rb_channel_try_register_connection_polling (rb_channel.c:455)
...
```

with eventually about all allocs being from `channel_connectivity.c:188`

Prompted by https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1421 and should allow  re-releasing https://github.com/grpc/grpc/pull/9986.

### CODE REVIEW

**Comment by apolcyn** [comment]
PTAL I think this is ready for a look now

**Comment by apolcyn** [comment]
I put the release blocker tag on this, though its mainly needed for just ruby. cc @dgquintas

**Comment by dgquintas** [comment]
There's a lot of failure due to, what it seems, an outdated version of run_tests.py. Could you merge with HEAD?

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by apolcyn** [comment]
rebased on top of https://github.com/grpc/grpc/pull/10871

**Comment by apolcyn** [comment]
jenkins: test this please

**Comment by ctiller** [comment]
Just a note that you could watch the connection state for (say) 30 days at
a time and avoid the leak also... Or at least reduce it to a handful of
bytes per month.

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                                                         cpu_time    real_time
------------------------------------------------------------------------------  ----------  -----------
BM_HpackEncoderEncodeHeader<RepresentativeServerTrailingMetadata>/1/16k             -11.50       -11.50
BM_HpackEncoderEncodeHeader<SingleInternedBinaryElem<100, true>>/0/16k              -12.00       -12.00
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<1, false>>/0/16k            -25.00       -25.00
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<1, true>>/0/16k             -23.00       -23.00
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<10, false>>/0/16k           -46.00       -46.00
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<10, true>>/0/16k            -25.00       -25.00
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<3, false>>/0/16k            -29.00       -29.00
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<3, true>>/0/16k             -23.00       -23.00
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<31, false>>/0/16k           -54.00       -54.00
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<31, true>>/0/16k            -20.50       -20.50
BM_HpackEncoderEncodeHeader<SingleNonInternedElem>/0/16k                            -26.00       -26.00
BM_HpackParserParseHeader<AddIndexedSingleStaticElem>                               -26.50       -26.50
BM_HpackParserParseHeader<IndexedSingleInternedElem>                                 -6.50        -6.50
BM_HpackParserParseHeader<NonIndexedBinaryElem<100, true>>                          -48.50       -48.50
BM_HpackParserParseHeader<NonIndexedBinaryElem<31, true>>                           -44.50       -44.50
BM_HpackParserParseHeader<NonIndexedElem>                                           -31.00       -31.00
BM_HpackParserParseHeader<RepresentativeClientInitialMetadata>                      -27.00       -27.00
BM_HpackParserParseHeader<RepresentativeServerTrailingMetadata>                     -10.00       -10.00
BM_StreamCreateDestroy                                                              -21.00       -21.00
BM_StreamCreateSendInitialMetadataDestroy<RepresentativeClientInitialMetadata>     -307.50      -307.50
BM_TransportStreamSend/8                                                            -55.50       -55.50
```

**Comment by matt-kwong** [comment]
Tests won't run since #10847 is overridden by f5521c33f9094f2f1e416764c4d2020237d65bc6. Since f5521c33f9094f2f1e416764c4d2020237d65bc6 was already merged into v1.3.x, you can rebase this PR back to the head of v1.3.x and only include 15b27bdacc2d4a29b1a2d95b9a89ec10f2d2f4d4 in this PR to get tests running.

**Comment by apolcyn** [comment]
@ctiller I'm not completely sure yet but I think just ruby can change without this going in

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                        cpu_time    real_time
---------------------------------------------  ----------  -----------
BM_IsolatedFilter<ServerDeadlineFilter, NoOp>       +6.00        +6.00
```

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                                         cpu_time    real_time
--------------------------------------------------------------  ----------  -----------
BM_HpackEncoderInitDestroy                                         +167.50      +167.50
BM_HpackParserParseHeader<RepresentativeClientInitialMetadata>      -27.50       -27.50
```

**Comment by dgquintas** [comment]
@apolcyn can you confirm you are OK with 1.3 going out without this?

**Comment by apolcyn** [comment]
A heads up that AFAICS changing ruby to not use timeouts here is a somewhat-significant change. (It needs an algorithm change to https://github.com/grpc/grpc/pull/9986. Currently, the short timeouts are needed in order for timely GC of channels and cleanup on interrupts). 

WIP on it, I think it's doable to change around ruby but there's some issues that still need to be fixed.

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                cpu_time    real_time
-------------------------------------  ----------  -----------
BM_CallCreateDestroy<InsecureChannel>     +208.50      +208.50
BM_CallCreateDestroy<LameChannel>         +191.00      +191.00
BM_IsolatedCall_NoOp                      +206.00      +206.00
BM_IsolatedCall_Unary                     +284.50      +284.50
BM_LameChannelCallCreateCpp               +953.50      +953.50
```

**Comment by apolcyn** [comment]
jenkins: test this please

**Comment by apolcyn** [comment]
FTR `tools/run_tests/run_tests.py -l c -r concurrent_connectivity_test -c asan` is flaking about 1/30 on this PR, though I'm not sure why yet, so holding this back

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                                                   cpu_time    real_time
------------------------------------------------------------------------  ----------  -----------
BM_ClosureSched3OnCombiner                                                    +14.50       +14.50
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<10, true>>/0/16k      +28.00       +28.00
BM_HpackParserParseHeader<NonIndexedBinaryElem<1, true>>                      +28.00       +28.00
BM_HpackParserParseHeader<NonIndexedBinaryElem<10, true>>                     +31.50       +31.50
BM_HpackParserParseHeader<NonIndexedBinaryElem<100, false>>                  +447.50      +447.00
BM_HpackParserParseHeader<NonIndexedBinaryElem<3, true>>                      +28.50       +28.50
BM_HpackParserParseHeader<NonIndexedElem>                                     +31.50       +31.50
BM_LameChannelCallCreateCpp                                                  +644.50      +644.50
BM_TransportStreamRecv/2M                                                   +5192.50     +5192.50
```

**Comment by apolcyn** [comment]
FTR, there does seem to be a real bug here:

WIP but seems its getting a bit more complicated

The phenomenon that seems to occur when tests fail is:
1. we start a watch with a timeout, which enqueues a closure to register a "watcher"
2. the timeout goes off and it runs it's watcher-cancelling-callback before that "watcher" has registered, but there's nothing to cancel, and things stop proceeding...

**Comment by apolcyn** [comment]
`tools/run_tests/run_tests.py -l c -r concurrent_connectivity_test -c asan -n inf -a 20` is the test that would previously fail, but it now seems to run forever, as head does.

**Comment by apolcyn** [comment]
heads up still not completely ready here though

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                                                   cpu_time    real_time
------------------------------------------------------------------------  ----------  -----------
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<1, false>>/0/16k      -25.00       -25.00
BM_HpackParserParseHeader<NonIndexedBinaryElem<1, true>>                      +32.50       +32.50
BM_HpackParserParseHeader<NonIndexedBinaryElem<31, false>>                   -123.50      -123.50
BM_HpackParserParseHeader<NonIndexedBinaryElem<31, true>>                     -46.00       -46.00
BM_HpackParserParseHeader<RepresentativeServerInitialMetadata>                 -8.00        -8.00
BM_HpackParserParseHeader<RepresentativeServerTrailingMetadata>                -8.50        -8.50
BM_IsolatedFilter<ClientDeadlineFilter, SendEmptyMetadata>                    -10.00       -10.00
BM_IsolatedFilter<HttpClientFilter, NoOp>                                      -7.00        -7.00
BM_IsolatedFilter<ServerDeadlineFilter, NoOp>                                  +6.00        +6.00
```

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                                                         cpu_time    real_time
------------------------------------------------------------------------------  ----------  -----------
BM_ClosureSched3OnExecCtx                                                            -8.50        -8.50
BM_CreateDestroyCore                                                                -52.50       -52.50
BM_EmptyCore                                                                        -91.00       -91.00
BM_ErrorHttpError<ErrorWithNestedGrpcStatus>                                         +5.50        +5.50
BM_HpackEncoderEncodeHeader<SingleNonInternedBinaryElem<31, false>>/0/16k           +96.50       +96.50
BM_HpackParserParseHeader<NonIndexedBinaryElem<1, true>>                            +66.00       +66.00
BM_HpackParserParseHeader<NonIndexedBinaryElem<3, true>>                            +64.50       +64.50
BM_IsolatedCall_NoOp                                                               -173.00      -173.00
BM_IsolatedCall_Unary                                                              -124.00      -124.00
BM_IsolatedFilter<ClientDeadlineFilter, SendEmptyMetadata>                          +17.50       +17.50
BM_IsolatedFilter<LoadReportingFilter, SendEmptyMetadata>                           -15.00       -15.00
BM_IsolatedFilter<MessageSizeFilter, NoOp>                                           +6.00        +6.00
BM_MetadataFromStaticMetadataStrings                                                 +7.50        +7.50
BM_MetadataFromStaticMetadataStringsNotIndexed                                      +32.00       +32.00
BM_Pluck1Core                                                                       -25.50       -25.50
BM_StreamCreateSendInitialMetadataDestroy<RepresentativeClientInitialMetadata>     +471.50      +471.50
BM_TransportEmptyOp                                                                 +20.50       +20.50
BM_TransportStreamRecv/0                                                           +157.00      +157.00
BM_TransportStreamSend/16M                                                       +34262.50    +34262.50
```

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                              cpu_time    real_time
---------------------------------------------------  ----------  -----------
BM_ErrorCreateAndSetIntAndStr                            +54.00       +54.00
BM_ErrorCreateAndSetStatus                               +56.50       +56.50
BM_ErrorCreateFromCopied                                 +83.50       +83.50
BM_ErrorCreateFromStatic                                 +62.00       +62.00
BM_ErrorStringOnNewError<ErrorWithGrpcStatus>           +515.00      +515.00
BM_ErrorStringOnNewError<ErrorWithHttpError>            +542.50      +542.50
BM_ErrorStringOnNewError<ErrorWithNestedGrpcStatus>     +777.50      +777.50
BM_ErrorStringOnNewError<SimpleError>                   +435.00      +435.00
```

**Comment by apolcyn** [comment]
PTAL I think this is ready for a look now

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                        cpu_time    real_time
---------------------------------------------  ----------  -----------
BM_IsolatedFilter<ServerDeadlineFilter, NoOp>       +5.50        +5.50
```

**Comment by apolcyn** [comment]
test failures:
- linux PR: https://github.com/grpc/grpc/issues/11008
- mac PR: https://github.com/grpc/grpc/issues/11213, https://github.com/grpc/grpc/issues/11226
- ubsan didn't run only because it's not enabled for this 1.3.x branch

**Comment by apolcyn** [comment]
after squashing, test failures were:
* linux PR: https://github.com/grpc/grpc/issues/11008
* mac PR: https://github.com/grpc/grpc/issues/11226, https://github.com/grpc/grpc/issues/11231

**Pull request merged**
