### PR TITLE
Remove vestigial sed for /etc/apt/sources.list in Dockerfiles

### PR DESCRIPTION
**Pull request by ejona86**
Jessie has a line that looks like this, now-a-days, so the regex is no
longer matching:
deb http://security.debian.org/debian-security jessie/updates main

But because that line was changed, downloads are also working correctly
out-of-the-box. The sed was originally added in #18530.

-----

I removed it from the template, and then regenerated. Please double-check that I didn't miss some step in that process.

CC @nicolasnoble, @jtattermusch

### CODE REVIEW

**Comment by nicolasnoble** [comment]
This is not vestigial at all. Debian started pulling anything Jessie related out without changing their base image. This fixes that.

**Comment by ejona86** [comment]
I checked the base image; that's what I was talking about.

```
$ docker run -it --rm debian:jessie cat /etc/apt/sources.list
# deb http://snapshot.debian.org/archive/debian/20190326T120000Z jessie main
deb http://deb.debian.org/debian jessie main
# deb http://snapshot.debian.org/archive/debian-security/20190326T120000Z jessie/updates main
deb http://security.debian.org/debian-security jessie/updates main
```

**Comment by nicolasnoble** [comment]
They may have fixed that in the meantime. This broke us for a while.

**Comment by ejona86** [comment]
@nicolasnoble, I was claiming it was no longer useful. I don't debate it served a purpose at some point.

**Comment by nicolasnoble** [comment]
And I was debating the word "vestigial", really :-) This is as recent as
last week.

**Comment by jtattermusch** [comment]
Tests are failing because docker images haven't been rebuilt and pushed 
(see https://github.com/grpc/grpc/blob/master/tools/dockerfile/push_testing_images.sh)

I tried rebuilding them and got this error:
```
+ DOCKER_IMAGE_NAME=node_jessie_x64_7913858dd6a38b123dd2e09d93fd5031314cf5ae
+ curl --silent -f -lSL https://registry.hub.docker.com/v2/repositories/grpctesting/node_jessie_x64_7913858dd6a38b123dd2e09d93fd5031314cf5ae/tags/latest
curl: (22) The requested URL returned error: 404 NOT FOUND
+ docker build -t grpctesting/node_jessie_x64_7913858dd6a38b123dd2e09d93fd5031314cf5ae tools/dockerfile/test/node_jessie_x64
Sending build context to Docker daemon  4.608kB
Step 1/22 : FROM debian:jessie
 ---> 39db55273026
Step 2/22 : RUN apt-get update && apt-get install -y   autoconf   autotools-dev   build-essential   bzip2   ccache   curl   dnsutils   gcc   gcc-multilib   git   golang   gyp   lcov   libc6   libc6-dbg   libc6-dev   libgtest-dev   libtool   make   perl   strace   python-dev   python-setuptools   python-yaml   telnet   unzip   wget   zip && apt-get clean
 ---> Using cache
 ---> 7f9881f4483c
Step 3/22 : RUN apt-get update && apt-get install -y time && apt-get clean
 ---> Using cache
 ---> 2aca1c43a89f
Step 4/22 : RUN apt-get update && apt-get install -y python-pip && apt-get clean
 ---> Using cache
 ---> 78d9e70dfc10
Step 5/22 : RUN pip install --upgrade google-api-python-client oauth2client
 ---> Using cache
 ---> 8d4011f79988
Step 6/22 : RUN apt-get update && apt-get install -y   libasound2   libgconf-2-4   libgtk2.0-0   libnss3   libxss1   libxtst6   xvfb
 ---> Running in 0b4d119e69fb
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [7340 B]
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [825 kB]
Get:4 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 9975 kB in 35s (282 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y   libasound2   libgconf-2-4   libgtk2.0-0   libnss3   libxss1   libxtst6   xvfb' returned a non-zero code: 100
```

**Comment by ejona86** [comment]
@jtattermusch, I needed to wait for #18651 to be merged to rebuild, since it also modified a Dockerfile. But then it seemed like there was denial that the sed was no longer useful and rebuilding the images takes forever, so I was waiting for some hint that this might be approved.

I've rebuilt the images and pushed a merge commit. Your build likely failed because you have an old jessie, especially since step 2+ was completed from the cache. A `docker pull debian:jessie` would have resolved it.

**Comment by ejona86** [comment]
By looking at the interop test results, it should be clear at this point that the sed line is not needed. Could I get a review?

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/18637

**Comment by jtattermusch** [comment]
I was able to rebuild after nuking the cache. Sorry for the delay.

**Comment by jtattermusch** [comment]
I'm wondering if the jessie-backports changes are also not needed anymore:
https://github.com/grpc/grpc/pull/18530/files#diff-6053bff72b48eab8b94465af56a05117

**Comment by ejona86** [comment]
@jtattermusch, it looks like the old URL (the "ftp" domain name) is still not correct. Since the servers did change, I expect that part of the change is still valid. Dunno about the rest; it wasn't in the Java Dockerfile so I hadn't looked at it.

**Pull request merged**
