### PR TITLE
Fix Windows Compile

### LINKED ISSUE #13748: Cant build on Windows grpc_chttp2_huffsyms issue
### What version of gRPC and what language are you using?
clean master branch 
 
### What operating system (Linux, Windows, …) and version?
 Windows 10/Windows 7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 2017/ 2015
 
### What did you do?
Try to build grpc.
 
### What did you expect to see?
Projects built 
 
### What did you see instead?
 "D:\Projekty\GRPC\.build\ALL_BUILD.vcxproj" (domyślny element docelowy) (1)->
"D:\Projekty\GRPC\.build\gen_hpack_tables.vcxproj" (domyślny element docelowy) (106)->
(element docelowy Link) ->
  gen_hpack_tables.obj : error LNK2001: unresolved external symbol _grpc_chttp2_huffsyms [D:\Projekty\GRPC\.build\gen_h
pack_tables.vcxproj]
  D:\Projekty\GRPC\.build\Debug\gen_hpack_tables.exe : fatal error LNK1120: 1 unresolved externals [D:\Projekty\GRPC\.b
uild\gen_hpack_tables.vcxproj]

 
### Anything else we should know about your project / environment?

I'm using Visual Studio Express. Tested on two different PC-s one with Windows 7 and Visual Studio 2015 other one with Windows 10 and Visual Studio 2017, also tryied to build with Ninja and it throws the same error.

### PR DESCRIPTION
**Pull request by ncteisen**
Some files were missed in c to c++ sweep

Fixes #13748

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Opt: #13643 
Dbg: #13430

**Pull request merged**
