### PR TITLE
Avoid C# GC when deserializing large messages

### PR DESCRIPTION
**Pull request by jtattermusch**
Progress towards fixing https://github.com/grpc/grpc/issues/13236.

- add new SegmentDeserializer field into marshaller (that takes ArraySegment instead of byte[]). the backward compatibility is maintained as the new deserializer fallbacks to older byte[] (with some overhead though) based serializer if not defined explicitly
- when deserializing messages, don't always allocate a new byte array, but instead reuse a thread-local byte array that is allocated for that purpose. That byte array is always-growing, but it's a weak reference, so the runtime can free the memory if it grows too big and memory is needed (the expectation is users shouldn't really use messages larger >X MB or so at that makes little practical sense - they could always use streaming).
- new ParseFrom(buffer, offset, count) API from Protobuf 3.5+ is used to allow parsing messages from byte array that is potentially larger than the message size.  Users would need to regenerate their .proto generate code to benefit from this optimization.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
CC @azyobuzin

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by azyobuzin** [comment]
It looks great as to deserializing mesages and shows me the expected GC timings (with https://github.com/grpc/grpc/pull/13440#discussion_r155264141 ). Thank you.

**Comment by apolcyn** [comment]
@jtattermusch is this waiting on review?

**Comment by jtattermusch** [comment]
@apolcyn  I temporarily interrupted work on this PR to take care of other things (cmake & test flakiness). I'll get back to it when I'm back from vacation.

**Comment by jtattermusch** [comment]
Superseded by https://github.com/grpc/grpc/pull/18865 which provides a better solution.

**Pull request closed without merging**
