### PR TITLE
Add src/compiler to clang-formatting pass

### PR DESCRIPTION
**Pull request by soltanmm**
I won't mark this as DNM, but it'd be easier if #6479 goes in first to keep the conflicts easy to manage.

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM

**Comment by jtattermusch** [comment]
needs resolving

**Comment by jtattermusch** [comment]
Please assign me again once the conflict is resolved and it's ready to merge.

**Comment by nathanielmanistaatgoogle** [comment]
Bumping priority - I'm about to check in a C++ change full of tab characters that my editor inserted into the code against my will. :-P

**Comment by soltanmm** [comment]
rebased

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum.

**Comment by nathanielmanistaatgoogle** [comment]
Wooo!

**Pull request merged**
