### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by gnossen**
This PR addresses both https://github.com/grpc/grpc/issues/17017 and https://github.com/grpc/grpc/issues/16572. In https://github.com/grpc/grpc/pull/16378, we add calls to `logging.basicConfig()` in various modules, which added a handler to the root logger.

One potential solution to the problem is to by default configure each module-level logger with a [`NullHandler`](https://docs.python.org/2/library/logging.handlers.html#nullhandler). This does two things:
 - avoids the pesky "No handlers could be found" message
 - doesn't mess with the user's own logging

Without explicit configuration of a handler for the root logger in application code, this change will result in no logging output from `grpcio`. To address this issue for tests, I have added a call to `logging.basicConfig()` in all unit tests and test utilities I could identify. It's entirely possible I've missed some places.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @gnossen isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by gnossen** [comment]
Agreed

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,649      Total (=)      2,015,649

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,193      Total (<)     11,116,194

 No significant differences in binary sizes


```

**Comment by gnossen** [comment]
@srini100 No, I don't believe so. Handlers are added to particular loggers. So if the user configured a particular grpc module to have a handler (which I doubt would happen very often), then `logging.getLogger(__name__).addHandler(logging.NullHandler)` is still okay. We'll simply be adding another handler, which from the experience of the user is a no-op.

As for the additional test, sure! Sounds like a good idea.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,649      Total (=)      2,015,649

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,197      Total (>)     11,116,196

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,649      Total (=)      2,015,649

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,198      Total (<)     11,116,201

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,649      Total (=)      2,015,649

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,194      Total (<)     11,116,195

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,649      Total (=)      2,015,649

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,195      Total (>)     11,116,193

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,649      Total (=)      2,015,649

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,187      Total (<)     11,116,197

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,578      Total (=)      2,015,578

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,200      Total (>)     11,116,196

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,015,578      Total (=)      2,015,578

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,116,194      Total (>)     11,116,192

 No significant differences in binary sizes


```

**Pull request merged**
