### PR TITLE
Enable xds retry test for cpp

### PR DESCRIPTION
**Pull request by dapengzhang0**
@lidizheng

### CODE REVIEW

**Review by lidizheng — COMMENTED** [review]
Looks good. Do you have a sponge link that proves this runs okay on Kokoro?

**Comment by dapengzhang0** [comment]
> Do you have a sponge link that proves this runs okay on Kokoro?

Yes, see in https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_xds_url_map Build# 533

**Review by lidizheng — APPROVED** [review]
LGTM.

**Comment by lidizheng** [comment]
@dapengzhang0 Do you plan to add this test case to Python as well? It will be really useful for Python users. I can help, if needed.

**Comment by dapengzhang0** [comment]
> Do you plan to add this test case to Python as well?
Is continuous URL map tests running for python already? 

>  It will be really useful for Python users.

Yeah we have users asking for the feature.

> I can help, if needed.

That'll be great! Otherwise I will do it later.

**Comment by lidizheng** [comment]
> Is continuous URL map test running for python already?

Yes, it's up at https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_xds_url_map_python

**Comment by dapengzhang0** [comment]
Thanks @lidizheng !

**Pull request merged**
