### PR TITLE
Check the length of unix socket path name 

### PR DESCRIPTION
**Pull request by y-zeng**
The path name should not have more than 107 characters, as `sun_path` in `struct sockaddr_un` is a char array of length 108.

---
Tests are failing with known issues:
Basic Tests Linux: #9124, #9150
Bazel Full Build & Tests: #9386

### CODE REVIEW

**Comment by y-zeng** [comment]
Fixed by using `GPR_ARRAY_SIZE(un->sun_path)`. Thanks a lot for the review!

**Comment by ctiller** [comment]
Can you add a test that demonstrates this?

(i.e. passing in a megabyte path length)?

**Comment by y-zeng** [comment]
Added `test_unix_socket` and `test_unix_socket_path_name_too_long`.

**Comment by ctiller** [comment]
Can you update and ping me?

**Comment by y-zeng** [comment]
@ctiller Updated with new changes.
Tests are failing with known issues:
Basic Tests Linux: #9124, #9150
Bazel Full Build & Tests: #9386

**Comment by y-zeng** [comment]
@ctiller Ping :grin:

**Comment by stanley-cheung** [comment]
Looks like `CMakeLists.txt` is out of sync after this is merged into `master`

**Pull request merged**
