### PR TITLE
Correct the default DNS resolver to ares

### PR DESCRIPTION
**Pull request by lidizheng**
The default value for `GRPC_DNS_RESOLVER` is changed since https://github.com/grpc/grpc/pull/17723 which released in `v1.19.0`. So, this part of doc should be corrected.

### CODE REVIEW

**Comment by markdroth** [comment]
@apolcyn, isn't the default per-platform these days?  Or is that just internally?

**Comment by apolcyn** [comment]
> @apolcyn, isn't the default per-platform these days? Or is that just internally?

**Comment by apolcyn** [comment]
^ yeah it's per-platform.

It's probably good to mention something like:

"ares is the default on most platforms, but not on iOS, Android, or Node"

**Comment by lidizheng** [comment]
The description about per-platform default value is added.

**Pull request merged**
