### PR TITLE
Init OpenSSL callbacks if it has not been initialized.

### PR DESCRIPTION
**Pull request by jiangtaoli2016**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%    +112 [None]                                                                              +136  +0.0%
  +0.4%     +48 src/core/tsi/ssl_transport_security.cc                                               +48  +0.4%
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.9]             +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.7]         +47  [NEW]
       +15%     +36 init_openssl                                                                         +36   +15%
      +3.1%     +12 [Unmapped]                                                                           +12  +3.1%

  +0.0%    +160 TOTAL                                                                               +184  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%    +112 [None]                                                                              +136  +0.0%
  +0.4%     +48 src/core/tsi/ssl_transport_security.cc                                               +48  +0.4%
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.9]             +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.7]         +47  [NEW]
       +15%     +36 init_openssl                                                                         +36   +15%
      +3.1%     +12 [Unmapped]                                                                           +12  +3.1%

  +0.0%    +160 TOTAL                                                                               +184  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%    +112 [None]                                                                              +144  +0.0%
  +0.4%     +48 src/core/tsi/ssl_transport_security.cc                                               +48  +0.4%
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.9]             +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.7]         +47  [NEW]
       +15%     +36 init_openssl                                                                         +36   +15%
      +3.1%     +12 [Unmapped]                                                                           +12  +3.1%

  +0.0%    +160 TOTAL                                                                               +192  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%    +144 [None]                                                                              +176  +0.0%
  +0.6%     +80 src/core/tsi/ssl_transport_security.cc                                               +80  +0.6%
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.9]             +76  [NEW]
       +28%     +68 init_openssl                                                                         +68   +28%
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.7]         +47  [NEW]
      +3.1%     +12 [Unmapped]                                                                           +12  +3.1%

  +0.0%    +224 TOTAL                                                                               +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%    +144 [None]                                                                              +176  +0.0%
  +0.6%     +80 src/core/tsi/ssl_transport_security.cc                                               +80  +0.6%
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.9]             +76  [NEW]
       +28%     +68 init_openssl                                                                         +68   +28%
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.7]         +47  [NEW]
      +3.1%     +12 [Unmapped]                                                                           +12  +3.1%

  +0.0%    +224 TOTAL                                                                               +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%    +144 [None]                                                                              +176  +0.0%
  +0.6%     +80 src/core/tsi/ssl_transport_security.cc                                               +80  +0.6%
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.9]             +76  [NEW]
       +28%     +68 init_openssl                                                                         +68   +28%
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.7]         +47  [NEW]
      +3.1%     +12 [Unmapped]                                                                           +12  +3.1%

  +0.0%    +224 TOTAL                                                                               +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by abaldeva** [comment]
Ping. If this can release with next grpc release, that'd be great.

Thanks.

**Comment by jiangtaoli2016** [comment]
Let me merge this one. It is not perfect, but at least improve.

**Pull request merged**
