### PR TITLE
Second attempt: Implement Watch method in health check service.

### PR DESCRIPTION
**Pull request by markdroth**
The first commit reverts the revert of #16351.  The second commit is the changes from #16499.

The internal breakage that required the revert is being fixed by internal changes.  I will not merge this until the internal changes are all submitted.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
   +12% +27.0Ki [None]                                                                                +762Ki   +15%
       +12% +24.9Ki [Unmapped]                                                                            +760Ki   +15%
      [NEW]    +655 [Other]                                                                                 +655  [NEW]
      [NEW]    +175 typeinfo name for std::_Bind<std::_Mem_fn<void (grpc::DefaultHealthCheckService::Hea    +175  [NEW]
      [NEW]    +175 typeinfo name for std::_Bind<std::_Mem_fn<void (grpc::DefaultHealthCheckService::Hea    +175  [NEW]
      [NEW]    +157 typeinfo name for std::_Maybe_get_result_type<std::_Mem_fn<void (grpc::DefaultHealth    +157  [NEW]
      [NEW]    +157 typeinfo name for std::_Maybe_get_result_type<std::_Mem_fn<void (grpc::DefaultHealth    +157  [NEW]
      [NEW]    +156 typeinfo name for std::_Weak_result_type_impl<std::_Mem_fn<void (grpc::DefaultHealth    +156  [NEW]
      [NEW]    +156 typeinfo name for std::_Weak_result_type_impl<std::_Mem_fn<void (grpc::DefaultHealth    +156  [NEW]
      [NEW]    +151 typeinfo name for std::_Weak_result_type<std::_Mem_fn<void (grpc::DefaultHealthCheck    +151  [NEW]
      [NEW]    +151 typeinfo name for std::_Weak_result_type<std::_Mem_fn<void (grpc::DefaultHealthCheck    +151  [NEW]
      [NEW]    +142 typeinfo name for std::_Sp_counted_ptr_inplace<grpc::DefaultHealthCheckService::Heal    +142  [NEW]
      [NEW]    +142 typeinfo name for std::_Sp_counted_ptr_inplace<grpc::DefaultHealthCheckService::Heal    +142  [NEW]
      [NEW]    +128 vtable for grpc::ServerAsyncWriter<grpc::ByteBuffer>                                    +128  [NEW]
      [NEW]     +77 typeinfo name for grpc::DefaultHealthCheckService::HealthCheckServiceImpl::CheckCall     +77  [NEW]
      [NEW]     +77 typeinfo name for grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCall     +77  [NEW]
      [NEW]     +72 typeinfo name for grpc::DefaultHealthCheckService::HealthCheckServiceImpl::CallHandl     +72  [NEW]
      [NEW]     +64 typeinfo name for grpc::ServerInterface::PayloadAsyncRequest<grpc::ByteBuffer>           +64  [NEW]
      [NEW]     +56 typeinfo for grpc::ServerAsyncWriterInterface<grpc::ByteBuffer>                          +56  [NEW]
      [NEW]     +56 vtable for std::_Sp_counted_ptr_inplace<grpc::DefaultHealthCheckService::HealthCheck     +56  [NEW]
      [NEW]     +56 vtable for std::_Sp_counted_ptr_inplace<grpc::DefaultHealthCheckService::HealthCheck     +56  [NEW]
      [NEW]     +54 typeinfo name for grpc::ServerAsyncWriterInterface<grpc::ByteBuffer>                     +54  [NEW]
  +343% +41.5Ki src/cpp/server/health/default_health_check_service.cc                                +41.5Ki  +343%
     +21e2% +11.0Ki [Other]                                                                              +11.0Ki +21e2%
      [NEW] +8.79Ki grpc::DefaultHealthCheckService::HealthCheckServiceImpl::CheckCallHandler::OnCallRec +8.79Ki  [NEW]
      [NEW] +5.84Ki grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCallHandler::SendHealt +5.84Ki  [NEW]
      [NEW] +3.83Ki grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCallHandler::OnCallRec +3.83Ki  [NEW]
      [NEW] +3.12Ki grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCallHandler::Shutdown  +3.12Ki  [NEW]
      [NEW] +2.76Ki grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCallHandler::CreateAnd +2.76Ki  [NEW]
      [NEW] +2.14Ki grpc::ServerAsyncWriter<grpc::ByteBuffer>::WriteAndFinish                            +2.14Ki  [NEW]
      [NEW] +1.90Ki grpc::ServerAsyncWriter<grpc::ByteBuffer>::Finish                                    +1.90Ki  [NEW]
      [NEW] +1.67Ki grpc::DefaultHealthCheckService::HealthCheckServiceImpl::CheckCallHandler::CreateAnd +1.67Ki  [NEW]
      [NEW] +1.05Ki grpc::ServerAsyncWriter<grpc::ByteBuffer>::Write                                     +1.05Ki  [NEW]
      [NEW] +1.01Ki grpc::ServerAsyncWriter<grpc::ByteBuffer>::Write                                     +1.01Ki  [NEW]
      [NEW]    +901 grpc::DefaultHealthCheckService::RegisterCallHandler                                    +901  [NEW]
      [NEW]    +857 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCallHandler::WatchCall    +857  [NEW]
      [NEW]    +830 grpc::ServerAsyncWriter<grpc::ByteBuffer>::SendInitialMetadata                          +830  [NEW]
      [NEW]    +830 grpc::ServerAsyncResponseWriter<grpc::ByteBuffer>::SendInitialMetadata                  +830  [NEW]
      [NEW]    +826 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::DecodeRequest                  +826  [NEW]
      [NEW]    +772 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCallHandler::~WatchCal    +772  [NEW]
      [NEW]    +764 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::WatchCallHandler::~WatchCal    +764  [NEW]
      [NEW]    +724 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocato    +724  [NEW]
      [NEW]    +702 grpc::DefaultHealthCheckService::UnregisterCallHandler                                  +702  [NEW]
      [NEW]    +682 grpc::ServerInterface::PayloadAsyncRequest<grpc::ByteBuffer>::FinalizeResult            +682  [NEW]
  +0.3%    +127 src/cpp/server/server_cc.cc                                                             +127  +0.3%
       +53% +1.04Ki grpc::Server::Start                                                                  +1.04Ki   +53%
      [NEW]     +12 [ELF Headers]                                                                            +12  [NEW]

   +19% +68.6Ki TOTAL                                                                                 +804Ki   +15%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,968      Total (=)      1,955,968

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,891      Total (>)     10,843,886

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,968      Total (=)      1,955,968

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,887      Total (>)     10,843,884

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known failures: #15835 #14268 #16471 #16577

**Pull request merged**
