### PR TITLE
Adding basic sanity test.

### PR DESCRIPTION
**Pull request by nicolasnoble**
This adds a basic script to test if we didn't forget to run the templates renderer. We can add more to that as we proceed to add more sanity checks.

### CODE REVIEW

**Comment by ctiller** [comment]
I will merge this once it's updated :)

**Comment by nicolasnoble** [comment]
Updated.

**Comment by ctiller** [comment]
Looks like it fails?

**Comment by nicolasnoble** [comment]
I don't know what you're talking about :-P

**Comment by ctiller** [comment]
One more merge?

**Comment by nicolasnoble** [comment]
*grunts*

**Pull request merged**
