### PR TITLE
handle empty slice explicitly

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                            FILE SIZE
 ++++++++++++++ GROWING                                              ++++++++++++++
  +0.4%     +60 src/cpp/client/generic_stub.cc                           +60  +0.4%
      +3.0%     +60 grpc::internal::CallOpClientRecvStatus::FinishOp         +60  +3.0%

 -------------- SHRINKING                                            --------------
  -0.0%     -28 [None]                                                  -572  -0.0%

  +0.0%     +32 TOTAL                                                   -512  -0.0%



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
@yang-g   is this ready to be reviewed?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                            FILE SIZE
 ++++++++++++++ GROWING                                              ++++++++++++++
  +0.4%     +60 src/cpp/client/generic_stub.cc                           +60  +0.4%
      +3.0%     +60 grpc::internal::CallOpClientRecvStatus::FinishOp         +60  +3.0%

 -------------- SHRINKING                                            --------------
  -0.0%     -28 [None]                                                  -580  -0.0%

  +0.0%     +32 TOTAL                                                   -520  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                            FILE SIZE
 ++++++++++++++ GROWING                                              ++++++++++++++
  +0.4%     +60 src/cpp/client/generic_stub.cc                           +60  +0.4%
      +3.0%     +60 grpc::internal::CallOpClientRecvStatus::FinishOp         +60  +3.0%

 -+-+-+-+-+-+-+ MIXED                                                +-+-+-+-+-+-+-
  +0.0%      +4 [None]                                                  -556  -0.0%

  +0.0%     +64 TOTAL                                                   -496  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                            FILE SIZE
 ++++++++++++++ GROWING                                              ++++++++++++++
  +0.4%     +60 src/cpp/client/generic_stub.cc                           +60  +0.4%
      +3.0%     +60 grpc::internal::CallOpClientRecvStatus::FinishOp         +60  +3.0%

 -+-+-+-+-+-+-+ MIXED                                                +-+-+-+-+-+-+-
  +0.0%      +4 [None]                                                  -556  -0.0%

  +0.0%     +64 TOTAL                                                   -496  -0.0%



```

**Comment by yang-g** [comment]
rebased and added a test.
Waiting for the tests.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                            FILE SIZE
 ++++++++++++++ GROWING                                              ++++++++++++++
  +0.4%     +60 src/cpp/client/generic_stub.cc                           +60  +0.4%
      +3.0%     +60 grpc::internal::CallOpClientRecvStatus::FinishOp         +60  +3.0%

 -+-+-+-+-+-+-+ MIXED                                                +-+-+-+-+-+-+-
  +0.0%      +4 [None]                                                  -556  -0.0%

  +0.0%     +64 TOTAL                                                   -496  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                              cpu_time    real_time
-------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamServerToClient<InProcess>/262144                                          +7%         +7%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/2                     -4%         -4%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/32768/1                      -7%         -7%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/262144                   -5%         -5%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/1  -8%         -8%
```

**Comment by yang-g** [comment]
Test failures: #15611 #15693

**Pull request merged**
