### PR TITLE
Add libuv core tests to portability test suite

### PR DESCRIPTION
**Pull request by murgatroid99**
Currently there are a few tests failing with errors about network endpoints not shutting down. It looks like some server-side TCP connections are not getting destroyed, but I don't know what might cause that.

### CODE REVIEW

**Comment by murgatroid99** [comment]
Well, the libuv portability tests appear to have passed in this PR.

**Comment by ctiller** [comment]
Jenkins: test this please

**Comment by murgatroid99** [comment]
test this please

**Comment by murgatroid99** [comment]
Superseded by #9766.

**Pull request closed without merging**
