### PR TITLE
Bump version to 1.14.2

### PR DESCRIPTION
**Pull request by srini100**
Bump version to 1.14.2 and regenerate projects.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++

 -------------- SHRINKING                    --------------
 -11.5%     -11 src/cpp/common/version_cc.cc     -11 -11.5%
     -22.0%     -11 grpc::Version[abi:cxx11]         -11 -22.0%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  +0.0%     +11 [None]                          -109  -0.0%

  [ = ]       0 TOTAL                           -120  -0.0%



```

**Comment by AspirinSJL** [comment]
We are supposed to have closed this branch, right?

**Comment by mehrdada** [comment]
@AspirinSJL We close the branch so nothing gets accidentally committed. It does not prevent some people with additional permissions to click on the merge button. We occasionally push things to closed branches for various reasons (security bug fix backports). This PR is fine as it is intentional, but yes, we should close the branch so that only a few people can click on the merge button.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++

 -------------- SHRINKING                    --------------
 -11.5%     -11 src/cpp/common/version_cc.cc     -11 -11.5%
     -22.0%     -11 grpc::Version[abi:cxx11]         -11 -22.0%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  +0.0%     +11 [None]                          -109  -0.0%

  [ = ]       0 TOTAL                           -120  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                              cpu_time    real_time
-------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/262144                                          -7%         -7%
BM_PumpStreamClientToServer<InProcess>/32768                                           -4%         -4%
BM_PumpStreamClientToServer<InProcessCHTTP2>/32768                                     -4%         -4%
BM_PumpStreamServerToClient<InProcess>/32768                                           -5%         -5%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/2                     -7%         -7%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                    -6%         -6%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/262144                -7%         -7%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32768                 -5%         -5%
BM_StreamingPingPongMsgs<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>/32768           -6%         -6%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/1/0  -7%         -7%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/0  -7%         -7%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/2097152                     -6%         -6%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/32768/32768                   -4%         -4%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++

 -------------- SHRINKING                    --------------
 -11.5%     -11 src/cpp/common/version_cc.cc     -11 -11.5%
     -22.0%     -11 grpc::Version[abi:cxx11]         -11 -22.0%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  +0.0%     +11 [None]                          -109  -0.0%

  [ = ]       0 TOTAL                           -120  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
