### PR TITLE
Clean up some warnings in the ruby wrapping code

### LINKED ISSUE #2457: ruby installation failing with compilation error
https://github.com/grpc/homebrew-grpc/issues/49

@tbetbetbe for visibility
```
✗ curl -fsSL https://goo.gl/getgrpc | bash -s ruby
Warning: Already tapped!
zlib is already installed
openssl is already installed
Warning: Already tapped!
google-protobuf is already installed
grpc is already installed
installing grpc ruby
Fetching: grpc-0.10.0.gem (100%)
Building native extensions with: '--with-grpc-dir=/usr/local'
This could take a while...
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.

    /Users/$user/.rbenv/versions/2.1.5/bin/ruby -r ./siteconf20150715-86487-wtwbpd.rb extconf.rb --with-grpc-dir=/usr/local
checking for dlopen() in -ldl... yes
checking for inflate() in -lz... yes
checking for gpr_now() in -lgpr... yes
checking for grpc_channel_destroy() in -lgrpc... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rb_byte_buffer.c
compiling rb_call.c
rb_call.c:134:66: error: missing field 'reserved' initializer [-Werror,-Wmissing-field-initializers]
    {GRPC_RB_GC_NOT_MARKED, GRPC_RB_GC_DONT_FREE, md_ary_datasize},
                                                                 ^
rb_call.c:142:78: error: missing field 'reserved' initializer [-Werror,-Wmissing-field-initializers]
    {GRPC_RB_GC_NOT_MARKED, grpc_rb_call_destroy, GRPC_RB_MEMSIZE_UNAVAILABLE},
                                                                             ^
rb_call.c:274:50: error: unused parameter 'key' [-Werror,-Wunused-parameter]
static int grpc_rb_md_ary_capacity_hash_cb(VALUE key, VALUE val,
                                                 ^
rb_call.c:349:64: error: unused parameter 'val' [-Werror,-Wunused-parameter]
static int grpc_rb_call_check_op_keys_hash_cb(VALUE key, VALUE val,
                                                               ^
4 errors generated.
make: *** [rb_call.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/$user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/grpc-0.10.0 for inspection.
Results logged to /Users/$user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/grpc-0.10.0/gem_make.out
```

### PR DESCRIPTION
**Pull request by murgatroid99**
This fixes #2457 and grpc/homebrew-grpc#49 (actually the same issue).

### CODE REVIEW

**Comment by johnwahba** [comment]
@murgatroid99 looks like the build is failing.

**Comment by murgatroid99** [comment]
They're passing now, or at least the relevant ones are.

**Comment by johnwahba** [comment]
@murgatroid99, still failing?

**Comment by johnwahba** [comment]
@nicolasnoble can this get merged into 0.10? 0.10 is still broken.

**Comment by marcinwyszynski** [comment]
This is still failing at HEAD:

```
marcinw@bruno:~/Downloads/grpc/src/ruby$ gem build grpc.gemspec
WARNING:  bin/math.rb is missing #! line
WARNING:  bin/math_services.rb is missing #! line
WARNING:  prerelease dependency on google-protobuf (~> 3.0.0alpha.1.1) is not recommended
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: grpc
  Version: 0.10.0
  File: grpc-0.10.0.gem
marcinw@bruno:~/Downloads/grpc/src/ruby$ gem install grpc-0.10.0.gem
Building native extensions.  This could take a while...
ERROR:  Error installing grpc-0.10.0.gem:
        ERROR: Failed to build gem native extension.

    /Users/marcinw/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150723-84018-1gw0ck1.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rb_byte_buffer.c
compiling rb_call.c
rb_call.c:247:20: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
    array_length = RARRAY_LEN(val);
                 ~ ^~~~~~~~~~~~~~~
/Users/marcinw/.rvm/rubies/ruby-2.2.0/include/ruby-2.2.0/ruby/ruby.h:900:6: note: expanded from macro 'RARRAY_LEN'
     (long)((RBASIC(a)->flags >> RARRAY_EMBED_LEN_SHIFT) & \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rb_call.c:247:20: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
    array_length = RARRAY_LEN(val);
                 ~ ^~~~~~~~~~~~~~~
/Users/marcinw/.rvm/rubies/ruby-2.2.0/include/ruby-2.2.0/ruby/ruby.h:902:25: note: expanded from macro 'RARRAY_LEN'
     RARRAY(a)->as.heap.len)
     ~~~~~~~~~~~~~~~~~~~^~~
2 errors generated.
make: *** [rb_call.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/marcinw/.rvm/gems/ruby-2.2.0/gems/grpc-0.10.0 for inspection.
Results logged to /Users/marcinw/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/grpc-0.10.0/gem_make.out
```

**Comment by marcinwyszynski** [comment]
Please kindly see https://github.com/grpc/grpc/pull/2632 for fixes.

**Pull request merged**
