### PR TITLE
Update (and fix) C# distribtests

### PR DESCRIPTION
**Pull request by jtattermusch**
- fixes https://github.com/grpc/grpc/issues/15327 (the dotnet cli version being used currently is too old)
- update the DistribTest project for dotnet CLI from `project.json` project format to the new .csproj format.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Tested locally.

**Comment by jtattermusch** [comment]
@matt-kwong   I'll need owners approval.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Pull request merged**
