### PR TITLE
RBAC Authorization Engine

### PR DESCRIPTION
**Pull request by ashithasantosh**
Implementation for gRPC RBAC-based Authorization Engine.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25948)

### CODE REVIEW

**Comment by ashithasantosh** [comment]
@markdroth @ZhenLian @jiangtaoli2016 PTAL, Thank you!

**Review by ZhenLian — CHANGES_REQUESTED** [review]
Thanks Ashitha for the pull request! I left some comments. Feel free to let me know any questions/concerns. Thanks!

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25948#-:-MYuyrZx73kX3YBI2GdM:bs8wubl)* status: all files reviewed, 7 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @markdroth)

___
*[src/core/lib/security/authorization/authorization_engine.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYsMhfq6nupmXrFdEP6:-MYsMhfr86hVPlkY8v43:b-5wpdup) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/authorization_engine.h#L32)):*
> ```objc
>     enum class DecisionType {
>       kAllow,
>       kDeny,
> ```

clarification question: so now we have only two decisions, either deny or allow. Do we consider to add `unknown` in the future? because I think  `unknown` is typical for a normal authz engine...
___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYumNTBECfPqVdG2_9L:-MYumNTBECfPqVdG2_9M:b-yard1t) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.h#L39)):*
> ```objc
>   explicit GrpcAuthorizationEngine(Rbac policy);
>   // Used only for testing purposes.
>   GrpcAuthorizationEngine(
> ```

nit: for testing-only functions, I usually prefer to name it something like `GrpcAuthorizationEngineForTesting`.
___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYuwfXV8UM4U_-hWdOp:-MYuwfXV8UM4U_-hWdOq:bqicya0) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.h#L42)):*
> ```objc
>       Rbac::Action action,
>       std::map<std::string, std::unique_ptr<AuthorizationMatcher>> policies)
>       : action_(action), policies_(std::move(policies)) {}
> ```

I thought sometimes in core, we had to use testing-only functions, because those being tested classes are not very-well organized as "interface-inheritance" hierarchy(maybe due to historical reasons), which makes things like mocking ctor input very difficult. In those cases, testing-only functions can still help us test part of the class logic, but I guess is not very ideal.
In your case, since I think our classes are very well written, have we considered the possibility to directly mock `Rbac::Action action`(maybe this one is harder) or `Rbac policy`? That way, we could also test the ctor of `GrpcAuthorizationEngine`, which I think is another good thing to have in unit tests.
___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 50 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYunTrd8nwQz4XK0ff-:-MYunTrd8nwQz4XK0ff0:b-gsnx5q) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.h#L50)):*
> ```objc
>  private:
>   Rbac::Action action_;
>   std::map<std::string, std::unique_ptr<AuthorizationMatcher>> policies_;
> ```

Do we really need a map here? It seems we will only do iterations on all the matchers, instead of retrieving some specific ones by names. Maybe a vector would be more suitable for our case here?
___
*[src/core/lib/security/authorization/grpc_authorization_engine.cc, line 45 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYup4FJ7nkTLpnjCtx9:-MYup4FJ7nkTLpnjCtxA:b7h9ak8) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.cc#L45)):*
> ```cpp
>   } else {
>     decision.type = matches ? Decision::DecisionType::kAllow
>                             : Decision::DecisionType::kDeny;
> ```

We could probably change this to `decision.type = (matches == (action_ == Rbac::Action::Allow)) ? kAllow : kDeny;` to save some lines.
This can be interpreted as "if `matches` and `action_ == Rbac::Action::Allow` are going in the opposite direction, we will deny it, since either no match for the valid record, or match for the invalid record; otherwise we will allow it"
___
*[test/core/security/grpc_authorization_engine_test.cc, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYuvnfqCAqGncLAi9cC:-MYuvnfqCAqGncLAi9cD:bnvucp8) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/test/core/security/grpc_authorization_engine_test.cc#L42)):*
> ```cpp
>     std::map<std::string, std::unique_ptr<AuthorizationMatcher>> matchers;
>     matchers[kPolicy1] = std::move(matcher1_);
>     matchers[kPolicy2] = std::move(matcher2_);
> ```

If I were you, I would probably just create `matcher1` and `matcher2` as local variables, and make the function static, since it is simpler, and it makes sense for a function like MakeXXX to be static. But I am also fine with the current way. I will leave you to decide whether to make this change:)
___
*[test/core/security/grpc_authorization_engine_test.cc, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYuvgic02T7YkvatSPj:-MYuvgic02T7YkvatSPk:b-rxmw0o) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/test/core/security/grpc_authorization_engine_test.cc#L46)):*
> ```cpp
>   }
> 
>   GrpcAuthorizationEngine MakeEmptyAuthorizationEngine(Rbac::Action action) {
> ```

This can probably also be `static`.

**Review by markdroth — CHANGES_REQUESTED** [review]
It's really nice to see this coming together so simply and effectively!

I have only one really significant comment, which is that we should create real Rbac policies in the test instead of trying to use mocks.  That will make the tests more readable and more realistic, and it will avoid the need to expose a separate method for overriding the contents of the real object in the production code.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 11 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25948#-:-MZ-5YCsBRf3Bn26c5mw:b-m7i4ca)* status: all files reviewed, 11 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/authorization_engine.h, line 30 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MYzq_gH9tfCYjoL219x:-MYzq_gH9tfCYjoL219y:bui6kbd) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/src/core/lib/security/authorization/authorization_engine.h#L30)):*
> ```objc
>  public:
>   struct Decision {
>     enum class DecisionType {
> ```

Suggest just calling this `Type`.  It's nested inside of the `Decision` struct, so making `Decision` part of this name is redundant.
___
*[src/core/lib/security/authorization/evaluate_args.h, line 46 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MYzqzRI-ysrkC4eyRdQ:-MYzqzRI-ysrkC4eyRdR:bdk7ku9) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/src/core/lib/security/authorization/evaluate_args.h#L46)):*
> ```objc
>   };
> 
>   EvaluateArgs() = default;
> ```

Why is this needed?
___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYuwfXV8UM4U_-hWdOp:-MYzrQAjC1axsIZ8aV5n:bi7gcye) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.h#L42)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

I thought sometimes in core, we had to use testing-only functions, because those being tested classes are not very-well organized as "interface-inheritance" hierarchy(maybe due to historical reasons), which makes things like mocking ctor input very difficult. In those cases, testing-only functions can still help us test part of the class logic, but I guess is not very ideal.
In your case, since I think our classes are very well written, have we considered the possibility to directly mock `Rbac::Action action`(maybe this one is harder) or `Rbac policy`? That way, we could also test the ctor of `GrpcAuthorizationEngine`, which I think is another good thing to have in unit tests.
</blockquote></details>

I agree.  I don't see why it's easier to construct this map than it is to just construct the RBAC policy.  I don't think we need this method.

See also my comments in the test about not using mocks here.
___
*[test/core/security/grpc_authorization_engine_test.cc, line 25 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MYzsoxX5RSXs4zt4Cgb:-MYzsoxX5RSXs4zt4Cgc:b9sa1q9) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/test/core/security/grpc_authorization_engine_test.cc#L25)):*
> ```cpp
> namespace grpc_core {
> 
> class MockMatcher : public AuthorizationMatcher {
> ```

Using a mock doesn't really make sense here.  Mocks are for situations where the object does a bunch of heavyweight work or brings in a bunch of external dependencies that are undesirable.  But in this case, all we really need is the Rbac policy, which is a self-contained structure with no external dependencies.  I think the tests will be more readable if we use a real policy rather than using a mock here.

For example, in the `AllowEngineWithMatchingPolicy` test, you have one policy that fails and another one that matches.  It's easy enough to craft a real Rbac policy that does that.   A simple matching policy is a `kAny` permission and a `kAny` principal.  And a simple non-matching policy is the same thing, but with `not_rule` set to true.
___
*[test/core/security/grpc_authorization_engine_test.cc, line 109 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MZ-41Li2rdT2OI1g9JV:-MZ-41Li2rdT2OI1g9JW:b53zka0) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/test/core/security/grpc_authorization_engine_test.cc#L109)):*
> ```cpp
>               .value()),
>       Rbac::Principal(Rbac::Principal::RuleType::kAny));
>   std::map<std::string, Rbac::Policy> policies;
> ```

This can be written as:

```
std::map<std::string, Rbac::Policy> policies = {
  {"policy1", std::move(policy)},
};
```

**Review by ashithasantosh — COMMENTED** [review]
Thanks for the review! I have resolved all comments. PTAL.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25948#-:-MZ-Q4aFDhAQp576-cbO:b-kjbz0)* status: 6 of 11 files reviewed, 10 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/authorization_engine.h, line 32 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYsMhfq6nupmXrFdEP6:-MYvTdQ94PdZ_LVqCmbg:bhbmtmx) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/authorization_engine.h#L32)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

clarification question: so now we have only two decisions, either deny or allow. Do we consider to add `unknown` in the future? because I think  `unknown` is typical for a normal authz engine...
</blockquote></details>

We will only have allow and deny decisions.  This is to support both xDS and non-xDS case. In xDS case, we could have single or multiple RBAC policies. For ex. in a single policy if we don't find a match, we want to say allow/deny depending on the engine type (instead of unknown).  Even Envoy behaves similarly.

Hence in an xDS use-case, we will check authorization decision from each engine, if we encounter a DENY we reject the RPC, and if all is allow we accept the RPC.  Similarly for non-xDS with the difference that we have exactly two engines.
___
*[src/core/lib/security/authorization/authorization_engine.h, line 30 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MYzq_gH9tfCYjoL219x:-MZ-M0ahD7m9XToe4i-f:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/src/core/lib/security/authorization/authorization_engine.h#L30)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest just calling this `Type`.  It's nested inside of the `Decision` struct, so making `Decision` part of this name is redundant.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/evaluate_args.h, line 46 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MYzqzRI-ysrkC4eyRdQ:-MZ-KDpjCR95zloiwqr4:b-tkzqqk) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/src/core/lib/security/authorization/evaluate_args.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

I had added that to avoid using EvaluateArgs(nullptr, nullptr) in tests, since anyway they get default initialized. Removed it in the latest commit.
___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYuwfXV8UM4U_-hWdOp:-MYvwNA789YyKRDu7nE3:bgsnwuo) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.h#L42)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I agree.  I don't see why it's easier to construct this map than it is to just construct the RBAC policy.  I don't think we need this method.

See also my comments in the test about not using mocks here.
</blockquote></details>

Sure, Updated the tests to use RBAC policy. The reason I didn't do it was to keep the test limited to engine (as we will have to set evaluate arguments too in this case., similar to matchers testing). But using just Any rule type avoids that too.PTAL.
___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 50 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYunTrd8nwQz4XK0ff-:-MYv_W6T7cx8xr1_y1Br:b-7jbl57) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.h#L50)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Do we really need a map here? It seems we will only do iterations on all the matchers, instead of retrieving some specific ones by names. Maybe a vector would be more suitable for our case here?
</blockquote></details>

The key here is the policy name, which is included in the AuthorizationDecision as the matching_policy_name when we find a match.
___
*[src/core/lib/security/authorization/grpc_authorization_engine.cc, line 45 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYup4FJ7nkTLpnjCtx9:-MYvc-Bc6lweGK1R5XwY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.cc#L45)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

We could probably change this to `decision.type = (matches == (action_ == Rbac::Action::Allow)) ? kAllow : kDeny;` to save some lines.
This can be interpreted as "if `matches` and `action_ == Rbac::Action::Allow` are going in the opposite direction, we will deny it, since either no match for the valid record, or match for the invalid record; otherwise we will allow it"
</blockquote></details>

Done.
___
*[test/core/security/grpc_authorization_engine_test.cc, line 42 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYuvnfqCAqGncLAi9cC:-MZ-QHzW1aVR-WnSzoLG:bqlqsys) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/test/core/security/grpc_authorization_engine_test.cc#L42)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

If I were you, I would probably just create `matcher1` and `matcher2` as local variables, and make the function static, since it is simpler, and it makes sense for a function like MakeXXX to be static. But I am also fine with the current way. I will leave you to decide whether to make this change:)
</blockquote></details>

Not using mock matchers anymore.
___
*[test/core/security/grpc_authorization_engine_test.cc, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYuvgic02T7YkvatSPj:-MZ-QBTR7UG7vajbf3v5:b-i77ae0) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/test/core/security/grpc_authorization_engine_test.cc#L46)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

This can probably also be `static`.
</blockquote></details>

I removed the test fixture.
___
*[test/core/security/grpc_authorization_engine_test.cc, line 25 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MYzsoxX5RSXs4zt4Cgb:-MZ-LKoi5UXK3KFPNesY:b-htx7fg) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/test/core/security/grpc_authorization_engine_test.cc#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Using a mock doesn't really make sense here.  Mocks are for situations where the object does a bunch of heavyweight work or brings in a bunch of external dependencies that are undesirable.  But in this case, all we really need is the Rbac policy, which is a self-contained structure with no external dependencies.  I think the tests will be more readable if we use a real policy rather than using a mock here.

For example, in the `AllowEngineWithMatchingPolicy` test, you have one policy that fails and another one that matches.  It's easy enough to craft a real Rbac policy that does that.   A simple matching policy is a `kAny` permission and a `kAny` principal.  And a simple non-matching policy is the same thing, but with `not_rule` set to true.
</blockquote></details>

SG! I had considered doing this, but felt it increased the scope of engine unit test. I have taken your suggestion and using only any rule type, to avoid EvaluateArgs. Let me know if you would like me to include other rule types here. 
___
*[test/core/security/grpc_authorization_engine_test.cc, line 109 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MZ-41Li2rdT2OI1g9JV:-MZ-JoKO17UL8w9DbtLo:b-ct82rj) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/test/core/security/grpc_authorization_engine_test.cc#L109)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be written as:

```
std::map<std::string, Rbac::Policy> policies = {
  {"policy1", std::move(policy)},
};
```
</blockquote></details>

Rbac::Policy is move-only type. So we won't be able to use initializer list here.

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks really good!  Just a few minor comments remaining.

Please let me know if you have any questions.  Thanks!

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25948#-:-MZ06Wd18HxABh0v6CTH:b-mb4u0z)* status: all files reviewed, 7 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 72 at r3](https://reviewable.io/reviews/grpc/grpc/25948#-MZ04Cgk04EzAHb9ROau:-MZ04CglBWhTVdR8ERHz:b-seyhe) ([raw file](https://github.com/grpc/grpc/blob/fc5a52709424bde618f2c7887862ee3b5320f326/src/core/lib/security/authorization/evaluate_args.h#L72)):*
> ```objc
> 
>  private:
>   grpc_metadata_batch* metadata_ = nullptr;
> ```

We actually don't need to initialize these to null here, since they will get set unconditionally by the ctor.
___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 50 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYunTrd8nwQz4XK0ff-:-MZ04TlbDbSMJvMAs79J:b-g2oz0c) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.h#L50)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

The key here is the policy name, which is included in the AuthorizationDecision as the matching_policy_name when we find a match.
</blockquote></details>

I think Zhen's question here was not about whether we need to store the policy name, but just about whether we need to store it as a map.  Instead, we could do something like this:

```
struct Policy {
  std::string name;
  std::unique_ptr<AuthorizationMatcher> matcher;
};
std::vector<Policy> policies_;
```

That would be a somewhat more compact representation.  The map isn't really needed, since we're never doing a random-access lookup for any particular key.
___
*[test/core/security/grpc_authorization_engine_test.cc, line 25 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MYzsoxX5RSXs4zt4Cgb:-MZ05S0Z0YPdGRY4asro:b686car) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/test/core/security/grpc_authorization_engine_test.cc#L25)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

SG! I had considered doing this, but felt it increased the scope of engine unit test. I have taken your suggestion and using only any rule type, to avoid EvaluateArgs. Let me know if you would like me to include other rule types here. 
</blockquote></details>

I think it's very easy to use `EvaluateArgs` here via `EvaluateArgsTestUtil`, so I don't see that as something we should avoid doing.  But I also don't think it's necessary to test any of the more complex matcher types, since we already have tests that the matchers work properly, and the `GrpcAuthorizationEngine` impl that we're testing here cares only about the result of the match.  So this looks fine.

**Review by ashithasantosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25948)* status: all files reviewed, 7 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/evaluate_args.h, line 72 at r3](https://reviewable.io/reviews/grpc/grpc/25948#-MZ04Cgk04EzAHb9ROau:-MZ0B0Kb7UGTBB9L5pWj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/fc5a52709424bde618f2c7887862ee3b5320f326/src/core/lib/security/authorization/evaluate_args.h#L72)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We actually don't need to initialize these to null here, since they will get set unconditionally by the ctor.
</blockquote></details>

Done.
___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 50 at r1](https://reviewable.io/reviews/grpc/grpc/25948#-MYunTrd8nwQz4XK0ff-:-MZ0B12p1hklFOF1erQD:bpgm9m4) ([raw file](https://github.com/grpc/grpc/blob/01c609e6136068be3ac73335a83764ad93e0261f/src/core/lib/security/authorization/grpc_authorization_engine.h#L50)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think Zhen's question here was not about whether we need to store the policy name, but just about whether we need to store it as a map.  Instead, we could do something like this:

```
struct Policy {
  std::string name;
  std::unique_ptr<AuthorizationMatcher> matcher;
};
std::vector<Policy> policies_;
```

That would be a somewhat more compact representation.  The map isn't really needed, since we're never doing a random-access lookup for any particular key.
</blockquote></details>

Oh! That is a very good suggestion. Updated code. Thanks!
___
*[test/core/security/grpc_authorization_engine_test.cc, line 25 at r2](https://reviewable.io/reviews/grpc/grpc/25948#-MYzsoxX5RSXs4zt4Cgb:-MZ0Arq19u6D1jFZvBWj:bvsw4j6) ([raw file](https://github.com/grpc/grpc/blob/1732978d2e912f9dd4bcfcfe94be72f3c20c68c3/test/core/security/grpc_authorization_engine_test.cc#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think it's very easy to use `EvaluateArgs` here via `EvaluateArgsTestUtil`, so I don't see that as something we should avoid doing.  But I also don't think it's necessary to test any of the more complex matcher types, since we already have tests that the matchers work properly, and the `GrpcAuthorizationEngine` impl that we're testing here cares only about the result of the match.  So this looks fine.
</blockquote></details>

Sounds Good. Thanks!

**Review by markdroth — APPROVED** [review]
This looks great!  Feel free to merge after addressing my one remaining comment.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25948#-:-MZJcANj4ncTIwbOPzYX:bkw4c1b)* status: all files reviewed, 7 unresolved discussions (waiting on @ashithasantosh, @jiangtaoli2016, and @ZhenLian)

___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 45 at r4](https://reviewable.io/reviews/grpc/grpc/25948#-MZJbnCcEjrTZZtBSodi:-MZJbnCcEjrTZZtBSodj:buptql9) ([raw file](https://github.com/grpc/grpc/blob/50a3f607c56689cfd45f0353d0697944a07070d2/src/core/lib/security/authorization/grpc_authorization_engine.h#L45)):*
> ```objc
>  private:
>   Rbac::Action action_;
>   struct Policy {
> ```

Structs should come before data members, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order

**Review by ashithasantosh — COMMENTED** [review]
Thanks for the review, Mark!:)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25948#-:-MZK9Auo3Q2zXxpkqL3M:b9c2l33)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @jiangtaoli2016, @markdroth, and @ZhenLian)

___
*[src/core/lib/security/authorization/grpc_authorization_engine.h, line 45 at r4](https://reviewable.io/reviews/grpc/grpc/25948#-MZJbnCcEjrTZZtBSodi:-MZK9HT-0nuamxPm5FLj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/50a3f607c56689cfd45f0353d0697944a07070d2/src/core/lib/security/authorization/grpc_authorization_engine.h#L45)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Structs should come before data members, as per:

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

Done.

**Review by ZhenLian — APPROVED** [review]
Thanks for making all the changes! This looks really great!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25948#-:-MZM95bF95KxvHNfWm-U:b-x98b31)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @jiangtaoli2016 and @markdroth)

**Comment by ashithasantosh** [comment]
Thanks for the review, Zhen!:)

**Pull request merged**
