### PR TITLE
xds tests: pin grpcio and grpc-tools to 1.31.0 

### PR DESCRIPTION
**Pull request by ericgribkoff**

### CODE REVIEW

**Review by menghanl — APPROVED** [review]
What changed? Why did this work before?

**Comment by menghanl** [comment]
And which version of python is this using? https://github.com/grpc/grpc/blob/1370ea77bd442896e5dffad3fb8436579c17f4fe/tools/internal_ci/linux/grpc_xds_bazel_test_in_docker.sh#L40-L48

**Comment by ericgribkoff** [comment]
It looks like the grpc_tools in the v1.32.0 release is either incompatible with Python 3.4, or incompatible with some step of the setup we are using here. @gnossen is checking if this is an issue with the release or WAI. Regardless, this change doesn't work as-is (https://g3c.corp.google.com/results/invocations/61767e8c-83fa-460b-87b7-76209cdcd947/targets/grpc%2Fjava%2Fmaster%2Fbranch%2Fxds/log) as it appears Python 3.6 is not installed on the Kokoro image we are using. Currently waiting for approval to the group that has access to these images so I can figure out a workaround here; it doesn't seem like it will be as simple as 'apt-get install python3.6+' as its using a fairly old ubuntu release and does not have access to later Python versions in the default package manager.

All tests that run in this repository (C++, PHP, Python, Ruby, C#) run inside of a docker container and are using Python 2.7. See logs, e.g., https://g3c.corp.google.com/results/invocations/40c76b73-53f8-4cda-8ddb-3cf2924301a3/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_xds/log.

**Comment by gnossen** [comment]
There's [a fix](https://github.com/grpc/grpc/pull/24099) up for this. We'll be releasing a patch to 1.32 soon.

**Comment by ericgribkoff** [comment]
Richard pointed out that just checking in the generated Python proto code would workaround this issue, but I'm trying just pinning the install to grpcio and grpc-tools 1.31.0 (running over on https://github.com/grpc/grpc-java/pull/7406)

**Comment by ericgribkoff** [comment]
Ok, pinning to 1.31.0 worked: https://g3c.corp.google.com/results/invocations/37d2997b-0216-4c04-9a8e-6027d1d6d513

**Pull request merged**
