### PR TITLE
Fix streaming_response_error end2end test in epoll1

### PR DESCRIPTION
**Pull request by sreecha**
1) Added a `force_use_poller` flag in  run_tests.py
2) Fixes streaming_response_error test:
Fixing the `streaming_response_error` test in case of `h2_*_proxy` fixtures (i.e `h2_proxy` and `h2_ssl_proxy`).

    There were cases where the server STATUS was reaching the client before server message (even thought the server sent the message before sending Status).  This is because of the test-proxy in the middle. The proxy does not try to keep any state (and as a result, was sending server status to client before sending the message). 

    Once the client receives the status, it ignores reading any message  (this is by-design). The fix is to ensure that the server does not send status until the client read the message.

### CODE REVIEW

**Comment by y-zeng** [comment]
Should we also add the changes in `pollset_init` here.

**Comment by sreecha** [comment]
@y-zeng , thanks for pointing that out. Yes, I just did now.

**Comment by y-zeng** [comment]
Maybe we can enable the tests first, and fix the remaining issues in another PR.

**Comment by sreecha** [comment]
I agree with @y-zeng . I updated this PR. epoll1 is only enabled in tests and not enabled by default (unless explicitly requested via GRPC_POLL_STRATEGY var)

**Comment by sreecha** [comment]
Windows failure is known: https://github.com/grpc/grpc/issues/10643

**Pull request merged**
