### PR TITLE
Protect timeout feature under a flag and added testing.

### PR DESCRIPTION
**Pull request by donnadionne**
---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24683)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
Thanks for doing this!

Please let me know if you have any questions.  Thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24683#-:-MLTbQAL9mFkDwymlDTk:b-pevjuw)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/24683#-MLTZfQqB9__V4tDZ38h:-MLTZfQqB9__V4tDZ38i:b-6nc4g9) ([raw file](https://github.com/grpc/grpc/blob/6b38a821d4615e0f690c143b3c1bbc7567e5e886/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L44)):*
> ```cpp
> 
> // TODO (donnadionne): Check to see if timeout is enabled, this will be
> // removed once circuit breaking feature is fully integrated and enabled by
> ```

s/circuit breaking/timeout/
s/integrated/intergration-tested/
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/24683#-MLTZqgI7U4uv9xfygfd:-MLTZqgI7U4uv9xfygfe:b-2gu0yl) ([raw file](https://github.com/grpc/grpc/blob/6b38a821d4615e0f690c143b3c1bbc7567e5e886/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L46)):*
> ```cpp
> // removed once circuit breaking feature is fully integrated and enabled by
> // default.
> bool XdsTimeoutEnabled() {
> ```

I think we should actually do this in the XdsApi code instead of doing it here.  If we never parse the timeout configs to begin with, then the code here will never see them.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 542 at r1](https://reviewable.io/reviews/grpc/grpc/24683#-MLT_n09ByBnGqw15lUK:-MLT_n09ByBnGqw15lUL:bag4zde) ([raw file](https://github.com/grpc/grpc/blob/6b38a821d4615e0f690c143b3c1bbc7567e5e886/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L542)):*
> ```cpp
>     ClusterState* cluster_state = it->second->Ref().release();
>     CallConfig call_config;
>     if (xds_timeout_enabled_ && entry.method_config != nullptr) {
> ```

This is not the right place to disable this, because we will soon be adding additional things to the method config, such as fault injection.  We don't want to not use the method config; we just don't want to configure the timeout.

If we do this in the xds resolver code, then I think the right place to do it is in `CreateMethodConfig()`, where we decide whether to add the "timeout" field to the method config.

However, as I mention above, I think a much better approach would be to do this in the XdsApi code, so that we never get the timeout configs here to begin with.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4397 at r1](https://reviewable.io/reviews/grpc/grpc/24683#-MLTb2n6BQBM9HcYazha:-MLTb2n79ZQSsk2K9jYs:b-77c068) ([raw file](https://github.com/grpc/grpc/blob/6b38a821d4615e0f690c143b3c1bbc7567e5e886/test/cpp/end2end/xds_end2end_test.cc#L4397)):*
> ```cpp
> }
> 
> TEST_P(LdsRdsTest, XdsRoutingXdsTimeoutDisabled) {
> ```

We probably don't need to test every individual field in this test; it's enough to check just one case to make sure that the max stream duration message from the xDS server is being ignored.  However, we should test that we are properly ignoring both the field in the HttpConnectionManager config *and* the field in the individual route.  So we may want to break this into two different test cases.

**Review by donnadionne — COMMENTED** [review]
fixed; PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24683#-:-MLjRRLYEieCUGIdIjyF:b277qrw)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 44 at r1](https://reviewable.io/reviews/grpc/grpc/24683#-MLTZfQqB9__V4tDZ38h:-MLjRJixDcj-FThHc6ZI:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b38a821d4615e0f690c143b3c1bbc7567e5e886/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L44)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/circuit breaking/timeout/
s/integrated/intergration-tested/
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 46 at r1](https://reviewable.io/reviews/grpc/grpc/24683#-MLTZqgI7U4uv9xfygfd:-MLjRKAj43T-bwfOtbby:b-7mmp82) ([raw file](https://github.com/grpc/grpc/blob/6b38a821d4615e0f690c143b3c1bbc7567e5e886/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we should actually do this in the XdsApi code instead of doing it here.  If we never parse the timeout configs to begin with, then the code here will never see them.
</blockquote></details>

moved
___
*[src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc, line 542 at r1](https://reviewable.io/reviews/grpc/grpc/24683#-MLT_n09ByBnGqw15lUK:-MLjRLvY5vPU_tORj5OE:b-xq9r8h) ([raw file](https://github.com/grpc/grpc/blob/6b38a821d4615e0f690c143b3c1bbc7567e5e886/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L542)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is not the right place to disable this, because we will soon be adding additional things to the method config, such as fault injection.  We don't want to not use the method config; we just don't want to configure the timeout.

If we do this in the xds resolver code, then I think the right place to do it is in `CreateMethodConfig()`, where we decide whether to add the "timeout" field to the method config.

However, as I mention above, I think a much better approach would be to do this in the XdsApi code, so that we never get the timeout configs here to begin with.
</blockquote></details>

moved to xds_api.cc
___
*[test/cpp/end2end/xds_end2end_test.cc, line 4397 at r1](https://reviewable.io/reviews/grpc/grpc/24683#-MLTb2n6BQBM9HcYazha:-MLjRO-QBvas9XK6B9fL:b-xvbj6r) ([raw file](https://github.com/grpc/grpc/blob/6b38a821d4615e0f690c143b3c1bbc7567e5e886/test/cpp/end2end/xds_end2end_test.cc#L4397)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We probably don't need to test every individual field in this test; it's enough to check just one case to make sure that the max stream duration message from the xDS server is being ignored.  However, we should test that we are properly ignoring both the field in the HttpConnectionManager config *and* the field in the individual route.  So we may want to break this into two different test cases.
</blockquote></details>

simplified and separated into 2

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks good overall!  There's one problem remaining in the test.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24683#-:-MLn2c-A-Xpr0qKOa6Iy:b-poltj8)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 4409 at r2](https://reviewable.io/reviews/grpc/grpc/24683#-MLn21Wl6NO23kqCVI7d:-MLn21Wl6NO23kqCVI7e:blj5jt6) ([raw file](https://github.com/grpc/grpc/blob/a9fd660a47adb4d69dbd0f9815fdafac7ddfd194/test/cpp/end2end/xds_end2end_test.cc#L4409)):*
> ```cpp
>   });
>   balancers_[0]->ads_service()->SetEdsResource(BuildEdsResource(args));
>   RouteConfiguration new_route_config =
> ```

You're creating this resource proto but not actually setting it in the xDS server, so we're not actually testing the right thing here.

**Review by donnadionne — COMMENTED** [review]
fixed; PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24683#-:-MLnR-4FDB_vFu-3NWyP:b277qrw)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 4409 at r2](https://reviewable.io/reviews/grpc/grpc/24683#-MLn21Wl6NO23kqCVI7d:-MLnR2-g8W0V2MFns-Aa:b43e4sq) ([raw file](https://github.com/grpc/grpc/blob/a9fd660a47adb4d69dbd0f9815fdafac7ddfd194/test/cpp/end2end/xds_end2end_test.cc#L4409)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

You're creating this resource proto but not actually setting it in the xDS server, so we're not actually testing the right thing here.
</blockquote></details>

thanks for catching that!

**Review by markdroth — APPROVED** [review]
Looks great!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24683#-:-MLnYErG5c8hSJMY_BOx:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
