### PR TITLE
Rename repo consistency checks to "consistency"

### PR DESCRIPTION
**Pull request by vjpai**
This will improve precision of language and reduce the use of "sanity," whose current definition has deviated from its etymological meaning of "cleanliness."

### CODE REVIEW

**Comment by vjpai** [comment]
Note that the CI is still labeled as "Sanity Checks". I think this needs a change as well. There are additional Ruby and Python codes with the issue but I'll send those as separate PRs.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,960,729      Total (=)      1,960,729

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,878,845      Total (>)     10,878,844

 No significant differences in binary sizes


```

**Comment by vjpai** [comment]
I realize that this repo-level change can't be made atomically since the "Sanity Checks" themselves are configured externally. I will create copies of the "_consistency.cfg" files using the old names and perhaps add a consistency check for that itself. Then the _sanity.cfg files can be removed once the CI is updated.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,960,729      Total (=)      1,960,729

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,878,844      Total (<)     10,878,845

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,960,729      Total (=)      1,960,729

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,878,851      Total (>)     10,878,849

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,960,729      Total (=)      1,960,729

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,878,846      Total (>)     10,878,838

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,960,729      Total (=)      1,960,729

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,878,841      Total (>)     10,878,839

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Independent of whether or not this is a good idea, it can't move forward in any case until an authorized owner of the grpctesting DOCKERHUB runs the commands at `tools/dockerfile/push_testing_images.sh` (afaict)

**Comment by vjpai** [comment]
Closing due to logistical concerns

**Pull request closed without merging**
