### PR TITLE
Remove GPR TLS API

### PR DESCRIPTION
**Pull request by tamird**
Use c++11 thread_local everywhere. Use proper types everywhere.

An alternative to #26942.

@veblush

### CODE REVIEW

**Comment by veblush** [comment]
I believe it's not ready to replace all TLS variants with c++11 thread_local yet. (ref: #24572)

**Comment by tamird** [comment]
Yep, see discussion in https://github.com/grpc/grpc/pull/26942#issuecomment-896056588.

Is there test coverage for that simulator version? It seems that #26912 introduced "naked" `thread_local` usage but still passed tests.

**Comment by veblush** [comment]
I believe there is but not sure CI tests for the PR cover it. (There are more tests running on master branch only)

**Comment by tamird** [comment]
Where can I see the results of those tests?

**Comment by tamird** [comment]
Oh, I didn't realize #26912 hasn't landed yet.

**Comment by ctiller** [comment]
#26912 isn't landed... would like to sort this out beforehand :)

**Comment by tamird** [comment]
Indeed, no dice.

```
Tue Aug 10 10:29:55 PDT 2021 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/core/lib/iomgr/exec_ctx.h:249:10: error: thread-local storage is not supported for the current target
Tue Aug 10 10:29:55 PDT 2021 -   static thread_local ExecCtx* exec_ctx_;
Tue Aug 10 10:29:55 PDT 2021 -          ^
Tue Aug 10 10:29:55 PDT 2021 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/core/lib/iomgr/exec_ctx.h:370:10: error: thread-local storage is not supported for the current target
Tue Aug 10 10:29:55 PDT 2021 -   static thread_local ApplicationCallbackExecCtx* callback_exec_ctx_;
```

**Pull request closed without merging**
