### PR TITLE
Cleanup: remove .travis.yml since it is unused

### PR DESCRIPTION
**Pull request by jtattermusch**
AFAICT, travis hasn't been disabled for the grpc/grpc repository a long time ago.
https://travis-ci.org/github/grpc/grpc
https://travis-ci.com/github/grpc/grpc

I'm happy to be proven wrong if travis is still being used, but if not, we should delete the travis config to avoid confusing people (I've seen some recently open PRs attempting to make modification to this file).

### CODE REVIEW

**Comment by jtattermusch** [comment]
Since we were only using travis to test grpc-objc, @HannahShiSFB  and @sampajano to confirm that travis.yml is no longer needed.

**Review by sampajano — APPROVED** [review]
Thanks!!

> travis hasn't been disabled for the grpc/grpc repository a long time ago

You meant travis *has been disabled, right?

**Comment by HannahShiSFB** [comment]
I'm not sure with this one, it's beyond my knowledge. I think it's only CI related, and I trust your judgement as a CI expert:) 
@jtattermusch

**Comment by jtattermusch** [comment]
> Thanks!!
> 
> > travis hasn't been disabled for the grpc/grpc repository a long time ago
> 
> You meant travis *has been disabled, right?

Yes, typo.

**Pull request merged**
