### PR TITLE
Upgrade C# to proto3

### LINKED ISSUE #2378: Use csharp_names.h routines in C# protoc plugin
there's a TODO for it in csharp_generator.cc

### LINKED ISSUE #2409: Migrate gRPC C# to proto3
C# doesn't support proto3 yet. Once proto3 C# gets released, we need to migrate all the proto files used by C# to proto3. 
Same things needs to be done for Greeter and Routeguide example.

### LINKED ISSUE #2719: C#: Expose ServiceDescriptor in generated code for service.

### PR DESCRIPTION
**Pull request by jtattermusch**
Upgrades third_party/protobuf to the latest release and migrates C# to proto3.

Fixes #2409 
Fixes #2719 
Fixes #2378

### CODE REVIEW

**Comment by jtattermusch** [comment]
@murgatroid99  can you please check if node/linux/dbg error is related to protobuf upgrade?
Also, do we have a way to verify objective-c won't get broken by this PR?

**Comment by murgatroid99** [comment]
The node error is just a connection error when installing dependencies. Unfortunately, this **does** in fact break the Objective C build.

**Comment by jtattermusch** [comment]
grpc plugins on linux need more work.

```
In file included from third_party/protobuf/src/google/protobuf/descriptor.pb.h:27:0,
                 from ./src/compiler/config.h:42,
                 from ./src/compiler/cpp_generator.h:37,
                 from src/compiler/cpp_generator.cc:36:
third_party/protobuf/src/google/protobuf/repeated_field.h: In instantiation of 'void google::protobuf::RepeatedField<T>::Reserve(int) [with Element = int]':
third_party/protobuf/src/google/protobuf/repeated_field.h:1060:60:   required from 'void google::protobuf::RepeatedField<T>::Add(const Element&) [with Element = int]'
third_party/protobuf/src/google/protobuf/descriptor.pb.h:3596:31:   required from here
third_party/protobuf/src/google/protobuf/repeated_field.h:1226:18: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   GOOGLE_CHECK_LE(new_size,

```

**Comment by jtattermusch** [comment]
gens/test/cpp/qps/qpstest.pb.cc: In member function 'void grpc::testing::LoadParams::clear_load()':
gens/test/cpp/qps/qpstest.pb.cc:3249:22: error: typedef 'T' locally defined but not used [-Werror=unused-local-typedefs]
   typedef LoadParams T;
                      ^
gens/test/cpp/qps/qpstest.pb.cc: In member function 'void grpc::testing::ClientArgs::clear_argtype()':
gens/test/cpp/qps/qpstest.pb.cc:4875:22: error: typedef 'T' locally defined but not used [-Werror=unused-local-typedefs]
   typedef ClientArgs T;
                      ^
gens/test/cpp/qps/qpstest.pb.cc: In member function 'void grpc::testing::ServerArgs::clear_argtype()':
gens/test/cpp/qps/qpstest.pb.cc:6375:22: error: typedef 'T' locally defined but not used [-Werror=unused-local-typedefs]
   typedef ServerArgs T;
                      ^
cc1plus: all warnings being treated as errors
Makefile:3685: recipe for target 'objs/dbg/./gens/test/cpp/qps/qpstest.pb.o' failed
make: *** [objs/dbg/./gens/test/cpp/qps/qpstest.pb.o] Error 1

**Comment by xfxyjwf** [comment]
Just sent out https://github.com/google/protobuf/pull/748 to fix the typedef issue.

**Comment by jtattermusch** [comment]
FYI @nathanielmanistaatgoogle @ctiller @stanley-cheung @murgatroid99 @tbetbetbe @jcanizales  this is going to be merged soon.

**Comment by nathanielmanistaatgoogle** [comment]
The history here goes back quite a bit and contains a lot of discarded or superseded intermediate progress - is there any hope of cleaning that up with a rebase? Or is there other draft work branched off of this that would get complicated?

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle  this need to atomically migrate C# from proto2 to proto3, so that's one of the reasons why there's so many commits. That said, I will try to do a rebase to clean up a bit once I get LGTM.

**Pull request merged**
