### PR TITLE
Better win32 orphans and event support.

### PR DESCRIPTION
**Pull request by nicolasnoble**
That should help with #1473, and a few "hung when shutting down" issues.

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM

**Comment by jtattermusch** [comment]
It looks like C# server can now handle client connecting and disconnecting many times and can later shutdown without hanging, so there's definitely been an improvement.

In some of my tests, I still get #1474 (virtually always) and in the rare cases when it doesn't crash I still seem to get stuck in do_iocp_work upon shutdown.

**Comment by nicolasnoble** [comment]
I didn't manage to get #1474 yet myself, but I haven't run all the tests. We'll see if I can get a reproduction with one of the tests.

**Comment by jtattermusch** [comment]
I'm happy to show you #1474 in debugger on my machine.

**Comment by nicolasnoble** [comment]
Well I'll need to heavily modify the code to get to understand what's going on, so I don't really think it'll be useful to just see it :-)

**Pull request merged**
