### PR TITLE
Remove /vsprojects pre-generated projects in favor of cmake

### PR DESCRIPTION
**Pull request by jtattermusch**
Removing pre-generated .vcxproj files (from /vsprojects), because they were partially broken and cmake provides a better alternative.

-- switch remaining builds to cmake (protoc artifacts builds)
-- build windows tests using cmake
-- adjust run_tests_matrix.py builds on windows
-- update documentation
-- remove contents of /vsprojects directory (as a large separate commit to make reviewing possible).
  
Quoting the rationale from the PR:
  **Pre-generated MS Visual Studio projects used to be the recommended way to build on Windows, but there were some limitations:**
  - **hard to build dependencies, expecially boringssl (deps usually support cmake quite well)**
  - **the nuget-based openssl & zlib dependencies are hard to maintain and update. We've received issues indicating that they are flawed.**
  - **.proto codegen is hard to support in Visual Studio directly (but we have a pretty decent support in cmake)**
  - **It's a LOT of generated files. We prefer not to have too much generated code in our github repo.**

### CODE REVIEW

**Comment by jtattermusch** [comment]
FYI @mehrdada @ctiller @makdharma

**Comment by jtattermusch** [comment]
protoc artifacts built sucessfully using cmake here: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/347/platform=windows/

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
+ @mehrdada  to review

**Comment by jtattermusch** [comment]
Unfortunately, the deprecation notice didn't make it into the v1.4.x branch, so it might make sense to merge this PR once v1.5.x branch has been cut (so v1.5.x will be released with the deprecation notice and v1.6.x won't have vsproject generated projects anymore)

**Comment by mehrdada** [comment]
Sounds like a valid point.

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/12261
https://github.com/grpc/grpc/issues/11179
https://github.com/grpc/grpc/issues/12262

**Comment by jtattermusch** [comment]
Ad basic tests windows failures:
Both failures - cmake/build/Debug/large_metadata_bad_client_test.exe and cmake/build/Release/concurrent_connectivity_test.exe are known flakes on master, but they were previously named vsprojects/Debug/large_metadata_bad_client_test.exe and vsprojects/Release/concurrent_connectivity_test.exe  - once they run on master under a new name, they'll be marked as flaky and won't appear red on PRs.

**Comment by ctiller** [comment]
Please revert.

Needing to hit six different websites before I can open a project to debug a problem is unacceptable.

**Comment by jtattermusch** [comment]
@ctiller, I do have several issues with reverting:
- there were good reasons we got rid of the vsprojects (they are reasonably well described in the PR description)
- in case we bring them back, who's going to be responsible for maintaining them? (they definitely needed more love and we never dedicated resources to proper maintenance).
- "six different websites" seems to be an exaggeration. There's always room for improvement, but the prerequisites are listed in https://github.com/grpc/grpc/blob/master/INSTALL.md#building-using-cmake-recommended  (and you really only need to install cmake and chocolatey, the rest you can do with 3 commands - not that different from what you need to do on Linux). Cmake is something you'd expect on a windows developer's box  and chocolatey is also pretty common. 

That said, I'm happy to work on  improving the documentation if you found it insufficient but I'm against reverting. Let's talk offline if you insist.

**Pull request merged**
