### PR TITLE
Fix C# artifacts compatibility

### PR DESCRIPTION
**Pull request by jtattermusch**
-- fix C# distribtest on debian wheezy
-- use macos compat flag for compilation on mac

### CODE REVIEW

**Comment by jtattermusch** [comment]
All C# distribtests are passing:
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/191/

**Comment by jtattermusch** [comment]
It would be good to get this one in before the fixit starts.

**Comment by jtattermusch** [comment]
@murgatroid99   can you please review this one?

**Comment by murgatroid99** [comment]
LGTM

**Pull request merged**
