### PR TITLE
Fix for changed parseFromData: signature (now parseFromData:error:)

### PR DESCRIPTION
**Pull request by jcanizales**
This was changed in the Protobufs repo, which is still in flux.

CC: @murgatroid99

### CODE REVIEW

**Comment by jcanizales** [comment]
@marcwan maybe you have to reply here too?

Marc is a Googler, but GitHub might be slow in discovering his corporate email.

**Comment by marcwan** [comment]
I signed it!

**Comment by nicolasnoble** [comment]
Do we want to wait until protobuf is released to make sure nothing else changes, or are we certain this is going to stay ?

**Comment by nicolasnoble** [comment]
Alright, protobuf-alpha-3 has been released. Merging that in. @jcanizales you also need to do the same PR for master.

**Comment by jcanizales** [comment]
It was already in master; thanks for merging!

**Pull request merged**
