### PR TITLE
Replace work serializer with a mutex in c-ares resolver

### PR DESCRIPTION
**Pull request by apolcyn**
In order to add cancellation support to `grpc_httpcli_get`, we need to first add cancellation support to non-client-channel resolver APIs.

This change makes cancellation support in the non-client-channel c-ares resolver case simpler since we don't need to first jump into a work serializer in to initiate cancellation.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/27858)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks reasonable overall.  I do agree that not depending on the `WorkSerializer` in this code is a good idea, since we eventually want to move it out of the client channel anyway.

My main concern is about adding lock annotations so that the compiler can enforce correctness.

As a side note, is there any chance you can get #25108 rolled forward?  I think it would make the kind of changes we're dealing with now a lot easier to understand.

Please let me know if you have any questions.  Thanks!

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27858#-:-MnmAG5r93Wu4R6gEowZ:b-3udh2s)* status: all files reviewed, 6 unresolved discussions (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm8DyWB1v9eIWtdoJQ:-Mnm8DyWB1v9eIWtdoJR:br88qqs) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L62)):*
> ```objc
>   virtual GrpcPolledFd* NewGrpcPolledFdLocked(
>       ares_socket_t as, grpc_pollset_set* driver_pollset_set,
>       grpc_core::Mutex* mu) = 0;
> ```

Doesn't look like this parameter is needed.  Neither implementation of this interface actually uses it.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc, line 102 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm7jPn4PrOSEMMEeHA:-Mnm7jPn4PrOSEMMEeHB:btjfs1l) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc#L102)):*
> ```cpp
>   };
> 
>   GrpcPolledFdWindows(ares_socket_t as, grpc_core::Mutex* mu,
> ```

No need for `grpc_core::` prefix, since we're already in that namespace.

Same thing throughout.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc, line 153 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm6lVpC7HlDlkio-yc:-Mnm6lVpC7HlDlkio-yd:bncjki0) ([raw file](https://github.com/grpc/grpc/blob/2530c73d449961fd7ab61d6f3d38c8dddd36e517/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc#L153)):*
> ```cpp
>     read_buf_ = GRPC_SLICE_MALLOC(4192);
>     if (connect_done_) {
>       work_serializer_->Run([this]() { ContinueRegisterForOnReadableLocked(); },
> ```

It looks like there are a bunch of places where the code was previously hopping into the `WorkSerializer` and is now not doing any synchronization.  Don't we need to acquire the mutex in all of these places instead?  If not, is it because we're already holding the mutex?  In that case, why were we hopping into the `WorkSerializer` in these places to begin with; shouldn't we have already been running in the `WorkSerializer`?

More generally, please add lock annotations so the compiler can enforce code correctness here and humans can see what's expected.  In particular, please add `ABSL_GUARDED_BY()` annotations on all data members guarded by the lock, and please add `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` annotations on all methods that must be called while already holding the lock.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm8TVv80QmJcYsGuS5:-Mnm8TVv80QmJcYsGuS6:bn90mwr) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L48)):*
> ```objc
> 
> struct grpc_ares_request {
>   /** synchronizes access to this request, and also to associated
> ```

Please add `ABSL_GUARDED_BY()` annotations on all data members protected by this mutex.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 245 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm9D7m2cbyUkSLju_R:-Mnm9D7m2cbyUkSLju_S:b-cucvyq) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L245)):*
> ```cpp
> }
> 
> static void on_timeout_locked(grpc_ares_ev_driver* driver,
> ```

I'm not sure if lock annotations work on standalone C-style functions, but if possible, please add `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` annotations on all functions that require that the lock be held while they are called.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 1138 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm9dQVBp1ktfoB5GD3:-Mnm9dQVBp1ktfoB5GD4:bsyc3ld) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L1138)):*
> ```cpp
>     }
>   }
>   (void)GRPC_ERROR_REF(error);
> ```

This can just go in-line in the following line:

```
grpc_core::ExecCtx::Run(DEBUG_LOCATION, r->on_resolve_address_done, GRPC_ERROR_REF(error));
```

**Review by apolcyn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27858)* status: 1 of 10 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h, line 62 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm8DyWB1v9eIWtdoJQ:-MqMNj6t4TczrIqhFXb_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.h#L62)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this parameter is needed.  Neither implementation of this interface actually uses it.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc, line 102 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm7jPn4PrOSEMMEeHA:-MqMNkEZEpTGGP4lY-32:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc#L102)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `grpc_core::` prefix, since we're already in that namespace.

Same thing throughout.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc, line 153 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm6lVpC7HlDlkio-yc:-MqMNl1O72DtUOEsIAD6:b-sdbzaz) ([raw file](https://github.com/grpc/grpc/blob/2530c73d449961fd7ab61d6f3d38c8dddd36e517/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_windows.cc#L153)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like there are a bunch of places where the code was previously hopping into the `WorkSerializer` and is now not doing any synchronization.  Don't we need to acquire the mutex in all of these places instead?  If not, is it because we're already holding the mutex?  In that case, why were we hopping into the `WorkSerializer` in these places to begin with; shouldn't we have already been running in the `WorkSerializer`?

More generally, please add lock annotations so the compiler can enforce code correctness here and humans can see what's expected.  In particular, please add `ABSL_GUARDED_BY()` annotations on all data members guarded by the lock, and please add `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` annotations on all methods that must be called while already holding the lock.
</blockquote></details>

These sites were using the work serializer redundantly.

This was addressed by https://github.com/grpc/grpc/pull/28016
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h, line 48 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm8TVv80QmJcYsGuS5:-MqMO0rO5X4SZv4fjji4:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.h#L48)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add `ABSL_GUARDED_BY()` annotations on all data members protected by this mutex.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 245 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm9D7m2cbyUkSLju_R:-MqMO20e04l-GnFPQxCA:b8quep9) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L245)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'm not sure if lock annotations work on standalone C-style functions, but if possible, please add `ABSL_EXCLUSIVE_LOCKS_REQUIRED()` annotations on all functions that require that the lock be held while they are called.
</blockquote></details>

Done - added lock annotations throughout.

The only thing I didn't do is add lock annotations to the windows code. AFAICT it looks like we don't actually [use them](https://github.com/grpc/grpc/pull/28016) on Windows, so I left them out.
___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 1138 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm9dQVBp1ktfoB5GD3:-MqMO3T_1-8YwNllkjsb:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L1138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can just go in-line in the following line:

```
grpc_core::ExecCtx::Run(DEBUG_LOCATION, r->on_resolve_address_done, GRPC_ERROR_REF(error));
```
</blockquote></details>

Done.

**Comment by apolcyn** [comment]
Sorry for the delay, I believe I've addressed comments though. PTAL

**Review by markdroth — APPROVED** [review]
This looks great!

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27858#-:-MqQupip3qYSVCWfiSQ3:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 245 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm9D7m2cbyUkSLju_R:-MqQtZqb9uzNoda9zJ8F:b-dg39ju) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L245)):*
<details><summary><i>Previously, apolcyn wrote…</i></summary><blockquote>

Done - added lock annotations throughout.

The only thing I didn't do is add lock annotations to the windows code. AFAICT it looks like we don't actually [use them](https://github.com/grpc/grpc/pull/28016) on Windows, so I left them out.
</blockquote></details>

Did you link to the right place there?  I don't see anything in that PR that says that we don't use lock annotations on Windows.

If you're sure that we really don't use them on any compiler that we might use on Windows, then I guess it's fine to omit them.

**Review by apolcyn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27858)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @apolcyn)

___
*[src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc, line 245 at r1](https://reviewable.io/reviews/grpc/grpc/27858#-Mnm9D7m2cbyUkSLju_R:-MqQvxoV054JqeL8mH73:b-ipmcba) ([raw file](https://github.com/grpc/grpc/blob/0427e5514cee4441ad93cc2f18bc95b36521f4b4/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L245)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Did you link to the right place there?  I don't see anything in that PR that says that we don't use lock annotations on Windows.

If you're sure that we really don't use them on any compiler that we might use on Windows, then I guess it's fine to omit them.
</blockquote></details>

Sorry wrong link, I meant to point out that -Wthread-safety-analysis is only considered an error when the our bazel [use_strict_warning](https://github.com/grpc/grpc/blob/3c28d6e65c4cfac7edde4943f84e17b97826b2f5/bazel/copts.bzl#L58) config is used. Meanwhile, [use_strict_warning](https://github.com/grpc/grpc/blob/3c28d6e65c4cfac7edde4943f84e17b97826b2f5/bazel/copts.bzl#L58) is only used on [mac](https://github.com/grpc/grpc/blob/fd3bd70939fb4239639fbd26143ec416366e4157/tools/remote_build/mac.bazelrc#L38) and [linux](https://github.com/grpc/grpc/blob/746eaf6c48e8099929af8a0bad512cd726a02adf/tools/internal_ci/linux/grpc_bazel_build_in_docker.sh#L32).

I've confirmed this with @veblush

**Comment by apolcyn** [comment]
cloud to prod failure is https://github.com/grpc/grpc/issues/19834

artifacts and distrib failures are ruby CBF: b/209603283

**Pull request merged**
