### PR TITLE
Adding Dns Resolver to LogicalDNSDiscoveryMechanism in xds_cluster_resolver

### PR DESCRIPTION
**Pull request by donnadionne**
---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25031)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks really good!  Just a few minor comments.

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25031#-:-MOnN9WI0RYAaxyxR5dd:b-4884ml)* status: all files reviewed, 4 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 463 at r1](https://reviewable.io/reviews/grpc/grpc/25031#-MOnM5vW4eOmSuZ1fCYX:-MOnM5vW4eOmSuZ1fCYY:b-prxc9w) ([raw file](https://github.com/grpc/grpc/blob/ceaa2b6f31df6725c12873830373b98f308735f1/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L463)):*
> ```cpp
> // XdsClusterResolverLb::LogicalDNSDiscoveryMechanism
> //
> XdsClusterResolverLb::LogicalDNSDiscoveryMechanism::
> ```

Please add a blank line above this.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 473 at r1](https://reviewable.io/reviews/grpc/grpc/25031#-MOnLvdmEqG6-JE85RSB:-MOnLvdmEqG6-JE85RSC:b-wxcotd) ([raw file](https://github.com/grpc/grpc/blob/ceaa2b6f31df6725c12873830373b98f308735f1/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L473)):*
> ```cpp
>       absl::make_unique<ResolverResultHandler>(
>           Ref(DEBUG_LOCATION, "LogicalDNSDiscoveryMechanism")));
>   GPR_ASSERT(resolver_ != nullptr);
> ```

Instead of asserting here, we can have the discovery mechanism call the parent's `OnResourceDoesNotExist()`.

Note that there may be a bit of a chicken-and-egg problem here, because the code in `XdsClusterResolverLb::UpdateLocked()` will not yet have added the mechanism to `discovery_mechanisms_` until after this ctor returns, but calling `OnResourceDoesNotExist()` will expect the relevant mechanism to already be present in the list.  To solve this, we may need to use two-phase initialization: Add a `Start()` method to the `DiscoveryMechanism` interface, and that's where we can actually create the resolver.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 513 at r1](https://reviewable.io/reviews/grpc/grpc/25031#-MOnMKSG7bWQNxoxJORK:-MOnMKSG7bWQNxoxJORL:bn6io2k) ([raw file](https://github.com/grpc/grpc/blob/ceaa2b6f31df6725c12873830373b98f308735f1/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L513)):*
> ```cpp
> 
> void XdsClusterResolverLb::LogicalDNSDiscoveryMechanism::ResolverResultHandler::
>     ReturnError(grpc_error* error) {}
> ```

In this case, we should call the parent's `OnError()`.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 615 at r1](https://reviewable.io/reviews/grpc/grpc/25031#-MOnMQLJ-5JnkYMJrHCJ:-MOnMQLJ-5JnkYMJrHCK:bgi7au7) ([raw file](https://github.com/grpc/grpc/blob/ceaa2b6f31df6725c12873830373b98f308735f1/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L615)):*
> ```cpp
>   if (is_initial_update) {
>     for (auto config : config_->discovery_mechanisms()) {
>       // TODO(donnadionne): need to add new types of
> ```

This TODO can go away now.

**Review by donnadionne — COMMENTED** [review]
Thank you! PTAL !

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25031#-:-MP5q7CWClmDzMmlkKhR:bjq0cdv)* status: all files reviewed, 4 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 463 at r1](https://reviewable.io/reviews/grpc/grpc/25031#-MOnM5vW4eOmSuZ1fCYX:-MP5nYmUEG1zbFrNHdrM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ceaa2b6f31df6725c12873830373b98f308735f1/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L463)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a blank line above this.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 473 at r1](https://reviewable.io/reviews/grpc/grpc/25031#-MOnLvdmEqG6-JE85RSB:-MP5n_DRBitxFOqITLvZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ceaa2b6f31df6725c12873830373b98f308735f1/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L473)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of asserting here, we can have the discovery mechanism call the parent's `OnResourceDoesNotExist()`.

Note that there may be a bit of a chicken-and-egg problem here, because the code in `XdsClusterResolverLb::UpdateLocked()` will not yet have added the mechanism to `discovery_mechanisms_` until after this ctor returns, but calling `OnResourceDoesNotExist()` will expect the relevant mechanism to already be present in the list.  To solve this, we may need to use two-phase initialization: Add a `Start()` method to the `DiscoveryMechanism` interface, and that's where we can actually create the resolver.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 513 at r1](https://reviewable.io/reviews/grpc/grpc/25031#-MOnMKSG7bWQNxoxJORK:-MP5o-I598i2tFDCQs8a:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ceaa2b6f31df6725c12873830373b98f308735f1/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L513)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

In this case, we should call the parent's `OnError()`.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 615 at r1](https://reviewable.io/reviews/grpc/grpc/25031#-MOnMQLJ-5JnkYMJrHCJ:-MP5q4hm-DkVup1iw-dx:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ceaa2b6f31df6725c12873830373b98f308735f1/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L615)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This TODO can go away now.
</blockquote></details>

Done.

**Review by markdroth — CHANGES_REQUESTED** [review]
Just a couple of minor comments remaining!

Please let me know if you have any questions.  Thanks!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25031#-:-MP5sw_n3UvKt9na5oPL:b-tluxr8)* status: all files reviewed, 3 unresolved discussions (waiting on @donnadionne)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 133 at r2](https://reviewable.io/reviews/grpc/grpc/25031#-MP5rYM68mFbeW4ksHJ_:-MP5rYM68mFbeW4ksHJa:b-fa3dy9) ([raw file](https://github.com/grpc/grpc/blob/c4d0896da904e16e4eaa02072a0b07fb784c7a42/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L133)):*
> ```cpp
>         size_t index)
>         : parent_(std::move(xds_cluster_resolver_lb)), index_(index) {}
>     virtual void Start(){};
> ```

This should be a pure virtual function.  In the EDS implementation, we should start the EDS watch in this method instead of in the ctor.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 474 at r2](https://reviewable.io/reviews/grpc/grpc/25031#-MP5s-0-0jf0kOeuLweu:-MP5s-0-0jf0kOeuLwev:b8ohno6) ([raw file](https://github.com/grpc/grpc/blob/c4d0896da904e16e4eaa02072a0b07fb784c7a42/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L474)):*
> ```cpp
>           Ref(DEBUG_LOCATION, "LogicalDNSDiscoveryMechanism")));
>   if (resolver_ == nullptr) {
>     parent()->OnResourceDoesNotExist(index());
> ```

Suggest returning after this, so that we don't need the `else` for the rest of this method.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 633 at r2](https://reviewable.io/reviews/grpc/grpc/25031#-MP5sD_e1aIfE2CRD5aX:-MP5sD_e1aIfE2CRD5aY:b-q6yh7r) ([raw file](https://github.com/grpc/grpc/blob/c4d0896da904e16e4eaa02072a0b07fb784c7a42/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L633)):*
> ```cpp
>                 Ref(DEBUG_LOCATION, "LogicalDNSDiscoveryMechanism"),
>                 discovery_mechanisms_.size());
>         // Need to call Start() because that is where the DNS resolver is
> ```

I think we should pull this out into a separate loop, so that we first construct all of the discovery mechanisms and then start them all.  This is because the code in `XdsClusterResolverLb::OnEndpointUpdate()` wants to check all existing discovery mechanisms, and there may be edge cases where strange things will happen if we enter that code before creating all of the mechanisms.

**Review by donnadionne — COMMENTED** [review]
PTAL thank you

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25031#-:-MP6g1I94OY2FuHXThv2:bxtaph9)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 133 at r2](https://reviewable.io/reviews/grpc/grpc/25031#-MP5rYM68mFbeW4ksHJ_:-MP6fzjo1_yOfWETrz8q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c4d0896da904e16e4eaa02072a0b07fb784c7a42/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L133)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be a pure virtual function.  In the EDS implementation, we should start the EDS watch in this method instead of in the ctor.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 474 at r2](https://reviewable.io/reviews/grpc/grpc/25031#-MP5s-0-0jf0kOeuLweu:-MP6g-NjCgxPU1r6_Go5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c4d0896da904e16e4eaa02072a0b07fb784c7a42/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L474)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest returning after this, so that we don't need the `else` for the rest of this method.
</blockquote></details>

Done.
___
*[src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc, line 633 at r2](https://reviewable.io/reviews/grpc/grpc/25031#-MP5sD_e1aIfE2CRD5aX:-MP6g0RmCzHFGChdNEId:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c4d0896da904e16e4eaa02072a0b07fb784c7a42/src/core/ext/filters/client_channel/lb_policy/xds/xds_cluster_resolver.cc#L633)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we should pull this out into a separate loop, so that we first construct all of the discovery mechanisms and then start them all.  This is because the code in `XdsClusterResolverLb::OnEndpointUpdate()` wants to check all existing discovery mechanisms, and there may be edge cases where strange things will happen if we enter that code before creating all of the mechanisms.
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
This looks great!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25031#-:-MPAGZawEjyLYd_PS4YF:b-j45s0z)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
