### PR TITLE
Fixed MinGW 7.3.0 shared library compile and link issues

### PR DESCRIPTION
**Pull request by githubuser0xFFFF**
added definition WIN32_WINNT=0x600
added missing libraries wsock32 ws2_32 crypt32

@yashykt

### CODE REVIEW

**Comment by yashykt** [comment]
This file CMakelists.txt is autogenerated, so this probably wouldn't work. I'm unclear as to which problem you are trying to solve though

**Comment by githubuser0xFFFF** [comment]
What do you mean with *CMakelists.txt is autogenerated*? The file grpc/CMakeLists is under version control - so I would not expect that it is autoegenerated.

When compiling grpc with MinGW, the following compiler error occurs:

```
Scanning dependencies of target gpr
[  1%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gpr/alloc.cc.obj
In file included from C:/CodingXP/grpc/include/grpc/support/port_platform.h:22:0,
                 from C:\CodingXP\grpc\src\core\lib\gpr\alloc.cc:19:
C:/CodingXP/grpc/include/grpc/impl/codegen/port_platform.h:43:2: error: #error "Please compile grpc with _WIN32_WINNT of at least 0x600 (aka Windows Vista)"
 #error \
  ^~~~~
make[2]: *** [CMakeFiles\gpr.dir\build.make:63: CMakeFiles/gpr.dir/src/core/lib/gpr/alloc.cc.obj] Error 1
make[1]: *** [CMakeFiles\Makefile2:306: CMakeFiles/gpr.dir/all] Error 2
make: *** [Makefile:129: all] Error 2
```
That means, for MinGW build _WIN32_WINNT is not properly defined. For MSVC this is defined. Therefore I added the following code:

```cmake
if (MINGW)
  add_definitions(-D_WIN32_WINNT=0x600)
endif()
```

With this change, the build at least starts. The next error that I see is the following linker error:

```
[  4%] Linking C shared library libaddress_sorting.dll
CMakeFiles\address_sorting.dir/objects.a(address_sorting.c.obj):address_sorting.c:(.text+0x13e): undefined reference to `_imp__htonl@4'
CMakeFiles\address_sorting.dir/objects.a(address_sorting.c.obj):address_sorting.c:(.text+0x18e): undefined reference to `_imp__htonl@4'
CMakeFiles\address_sorting.dir/objects.a(address_sorting.c.obj):address_sorting.c:(.text+0x1f6): undefined reference to `_imp__htonl@4'
CMakeFiles\address_sorting.dir/objects.a(address_sorting_windows.c.obj):address_sorting_windows.c:(.text+0x2b): undefined reference to `_imp__socket@12'
CMakeFiles\address_sorting.dir/objects.a(address_sorting_windows.c.obj):address_sorting_windows.c:(.text+0x5c): undefined reference to `_imp__connect@12'
CMakeFiles\address_sorting.dir/objects.a(address_sorting_windows.c.obj):address_sorting_windows.c:(.text+0xac): undefined reference to `_imp__getsockname@12'
CMakeFiles\address_sorting.dir/objects.a(address_sorting_windows.c.obj):address_sorting_windows.c:(.text+0xdc): undefined reference to `_imp__closesocket@4'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles\address_sorting.dir\build.make:118: libaddress_sorting.dll] Error 1
```

This is caused, by some missing libraries that are not linked. Therfore I changed the code:

```cmake
if(WIN32 AND MSVC)
  set(_gRPC_BASELIB_LIBRARIES wsock32 ws2_32)
endif()
```
to

```cmake
if(WIN32)
  set(_gRPC_BASELIB_LIBRARIES wsock32 ws2_32)
endif()
```

to ensure that the required libraries are not only linked for Visual Studio builds but also for MinGW builds. With these changes the MinGW build succeeds.

**Comment by jtattermusch** [comment]
See here: https://github.com/grpc/grpc/blob/d4e5e535c48b2bd4656d48ebcec20d2e7a166e15/CMakeLists.txt#L3

https://github.com/grpc/grpc/blob/master/templates/README.md

(you'd need to edit https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template)

Also note that mingw isn't officially supported so it's support is only on best-effort basis (and things might be broken in the future).

**Comment by githubuser0xFFFF** [comment]
Ahh, thank you - now I see. 

I updated the pull request to change the template file instead of the generated CMakeLists.txt file.

**Comment by kou** [comment]
I think that we need to update `templates/CMakeLists.txt.template` and then run `tools/buildgen/generate_projects.sh` to update `CMakeLists.txt` too. And we commit both `templates/CMakeLists.txt.template` and `CMakeLists.txt`.

**Comment by githubuser0xFFFF** [comment]
I just got the info "This issue/PR has been automatically marked as stale". I'm a little bit lost, what to do know. Is there something wrong with my patch? Ist there something I can do to to fix the checks?

Any help would be great.

**Comment by jtattermusch** [comment]
@veblush  can I have second-googler LGTM?

**Comment by veblush** [comment]
Although it was merged but approved by me as well just in case.

**Pull request merged**
