### PR TITLE
[ObjC] Support use frameworks!

### PR DESCRIPTION
**Pull request by HannahShiSFB**
1. add swift example configured with `use_frameworks!`.

2. fix [unable to find C++ headers](https://source.cloud.google.com/results/invocations/2100300a-0b61-4e56-8a77-113e362f2c63/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_objc_examples/log) by renaming `.m` files to `.mm`.
`/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_objc_macos_opt_native/src/objective-c/examples/SwiftUseFrameworks/Build/Build/Build/Products/Debug-iphoneos/gRPC-Core/grpc.framework/Headers/grpc_audit_logging.h:24:10: fatal error: 'memory' file not found #include <memory>`

3. fix [cyclic dependency errors](https://source.cloud.google.com/results/invocations/90972079-eade-4c07-a5c4-20f139c64d4e/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fios-buildtest-example-switftsample/tests) by making `openssl/time.h` private.
`/Applications/Xcode_14.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.sdk/usr/include/dispatch/dispatch.h:25:10: error: cyclic dependency in module 'Darwin': Darwin -> openssl_grpc -> UIKit -> Foundation -> CoreFoundation -> Dispatch -> Darwin`

"Basic Tests ObjC Examples" succeeds with this PR:
https://source.cloud.google.com/results/invocations/cff74ec0-43ca-43b9-a2ff-12edabc02896/targets

### CODE REVIEW

**Review by sampajano — APPROVED** [review]
WOW! Thanks so much for the fix, Hannah! Glad to see it fixed!!

I'm curious how did you fix the cyclic dependency issue (3)?

**Comment by sampajano** [comment]
@wu-hui FYI :)

**Comment by wu-hui** [comment]
> @wu-hui FYI :)

Wonderful!

**Comment by HannahShiSFB** [comment]
> I'm curious how did you fix the cyclic dependency issue (3)?

Basically with use_frameworks!, headers can be found with both #include <openssl/time.h> (openssl_grpc/time.h actually) and #include <time.h> due to how cocoapods put those files and generate compiler flags.
I tried several ways but it turned out the most simple solution is just make the time.h file private as it's not used anyways outside of boringssl itself.

**Comment by sampajano** [comment]
> Basically with use_frameworks!, headers can be found with both #include <openssl/time.h> (openssl_grpc/time.h actually) and #include <time.h> due to how cocoapods put those files and generate compiler flags. I tried several ways but it turned out the most simple solution is just make the time.h file private as it's not used anyways outside of boringssl itself.

aha nice! Good to note! Thanks for explaining!

**Comment by wu-hui** [comment]
When do we plan to release this?

**Comment by sampajano** [comment]
> When do we plan to release this?

The github workflow has changed!

@wu-hui Now we have to review and merge this PR on google3 first! I'm working on it now and will keep you updated!

@HannahShiSFB FYI!

**Review by sampajano — APPROVED** [review]
Thanks for the change!

**Pull request closed without merging**
