### PR TITLE
Use Debug Assert to Save Bit Operations

### PR DESCRIPTION
**Pull request by ncteisen**
From VTune data

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                FILE SIZE
 ++++++++++++++ GROWING                                                  ++++++++++++++

 -------------- SHRINKING                                                --------------
  -0.0%     -32 [None]                                                      -152  -0.0%
  -0.8%     -64 src/core/ext/transport/chttp2/transport/hpack_encoder.cc     -64  -0.8%
      -4.7%     -70 hpack_enc                                                    -70  -4.7%

  -0.0%     -96 TOTAL                                                       -216  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
No impact

**Pull request closed without merging**
