### PR TITLE
Upmerge 1.8.x into master to prevent future merge conflict after version bump

### PR DESCRIPTION
**Pull request by mehrdada**
Prevents future conflicts by creating a shared ancestor for future commits on 1.8.x on master

### CODE REVIEW

**Comment by mehrdada** [comment]
@nicolasnoble Updated the branch after the merge re-do. PTAL.

**Comment by mehrdada** [comment]
@markdroth Please take a look and sanity check if I have done the merge correctly and all your changes are there intact in the merge commit.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
