### PR TITLE
EXPERIMENT/NOT FOR REVIEW: Bring back some absl just to see what happens

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9%    +263 src/core/ext/filters/client_channel/client_channel.cc                                   +263  +0.9%
      [NEW]    +181 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    +181  [NEW]
      +5.2%    +160 start_retriable_subchannel_batches                                                      +160  +5.2%
       +11%    +135 bool grpc_core::ServiceConfig::ParseJsonMethodConfig<grpc_core::internal::ClientChan    +135   +11%
      +0.5%     +15 on_complete                                                                              +15  +0.5%
      +0.2%      +1 [Unmapped]                                                                                +1  +0.2%
  +3.8%    +192 src/core/ext/filters/message_size/message_size_filter.cc                                +192  +3.8%
      +6.8%    +187 init_channel_elem                                                                       +187  +6.8%
      +4.1%      +5 [Unmapped]                                                                                +5  +4.1%
  +2.4%    +128 src/core/lib/iomgr/udp_server.cc                                                        +128  +2.4%
       +19%    +223 add_socket_to_server                                                                    +223   +19%
  +5.4%     +66 src/core/ext/filters/client_channel/lb_policy_registry.cc                                +66  +5.4%
       +27%    +145 grpc_core::LoadBalancingPolicyRegistry::Builder::RegisterLoadBalancingPolicyFactory     +145   +27%
       +37%      +7 [Unmapped]                                                                                +7   +37%

 -------------- SHRINKING                                                                            --------------
  -2.6%     -94 src/core/ext/filters/client_channel/resolver_registry.cc                                 -94  -2.6%
      -9.1%     -71 grpc_core::ResolverRegistry::CreateResolver                                              -71  -9.1%
      -7.8%     -57 grpc_core::ResolverRegistry::GetDefaultAuthority                                         -57  -7.8%
      [DEL]     -47 grpc_core::(anonymous namespace)::RegistryState::FindResolverFactory(char const*, gr     -47  [DEL]
     -33.7%     -34 grpc_core::ResolverRegistry::Builder::InitRegistry                                       -34 -33.7%
      -4.5%     -30 grpc_core::ResolverRegistry::AddDefaultPrefixIfNeeded                                    -30  -4.5%
     -12.0%     -27 grpc_core::ResolverRegistry::LookupResolverFactory                                       -27 -12.0%
      -8.8%     -25 grpc_core::ResolverRegistry::Builder::ShutdownRegistry                                   -25  -8.8%
      -4.8%      -8 grpc_core::ResolverRegistry::Builder::SetDefaultPrefix                                    -8  -4.8%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -19 [None]                                                                                +174Ki  +2.1%

  +0.0%    +536 TOTAL                                                                                 +174Ki  +1.9%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                 call_initial_size-median    cpu_time    real_time
----------------------------------------------------------------------------------------  --------------------------  ----------  -----------
BM_PumpStreamServerToClient<InProcess>/32768                                                                          +4%         +4%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/0/2                                   -7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/1/2                                   -7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/32768/2                               -7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/4096/2                                -7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/512/2                                 -7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/64/2                                  -7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/8/2                                   -7%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/262144                                               -5%         -5%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/1                                 -7%         -7%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/1/0                              -6%         -6%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9%    +263 src/core/ext/filters/client_channel/client_channel.cc                                   +263  +0.9%
      [NEW]    +181 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    +181  [NEW]
      +5.2%    +160 start_retriable_subchannel_batches                                                      +160  +5.2%
       +11%    +135 bool grpc_core::ServiceConfig::ParseJsonMethodConfig<grpc_core::internal::ClientChan    +135   +11%
      +0.5%     +15 on_complete                                                                              +15  +0.5%
      +0.2%      +1 [Unmapped]                                                                                +1  +0.2%
  +3.8%    +192 src/core/ext/filters/message_size/message_size_filter.cc                                +192  +3.8%
      +6.8%    +187 init_channel_elem                                                                       +187  +6.8%
      +4.1%      +5 [Unmapped]                                                                                +5  +4.1%
  +2.4%    +128 src/core/lib/iomgr/udp_server.cc                                                        +128  +2.4%
       +19%    +223 add_socket_to_server                                                                    +223   +19%
  +5.4%     +66 src/core/ext/filters/client_channel/lb_policy_registry.cc                                +66  +5.4%
       +27%    +145 grpc_core::LoadBalancingPolicyRegistry::Builder::RegisterLoadBalancingPolicyFactory     +145   +27%
       +37%      +7 [Unmapped]                                                                                +7   +37%

 -------------- SHRINKING                                                                            --------------
  -2.6%     -94 src/core/ext/filters/client_channel/resolver_registry.cc                                 -94  -2.6%
      -9.1%     -71 grpc_core::ResolverRegistry::CreateResolver                                              -71  -9.1%
      -7.8%     -57 grpc_core::ResolverRegistry::GetDefaultAuthority                                         -57  -7.8%
      [DEL]     -47 grpc_core::(anonymous namespace)::RegistryState::FindResolverFactory(char const*, gr     -47  [DEL]
     -33.7%     -34 grpc_core::ResolverRegistry::Builder::InitRegistry                                       -34 -33.7%
      -4.5%     -30 grpc_core::ResolverRegistry::AddDefaultPrefixIfNeeded                                    -30  -4.5%
     -12.0%     -27 grpc_core::ResolverRegistry::LookupResolverFactory                                       -27 -12.0%
      -8.8%     -25 grpc_core::ResolverRegistry::Builder::ShutdownRegistry                                   -25  -8.8%
      -4.8%      -8 grpc_core::ResolverRegistry::Builder::SetDefaultPrefix                                    -8  -4.8%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -19 [None]                                                                                +175Ki  +2.1%

  +0.0%    +536 TOTAL                                                                                 +176Ki  +1.9%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9%    +263 src/core/ext/filters/client_channel/client_channel.cc                                   +263  +0.9%
      [NEW]    +181 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    +181  [NEW]
      +5.2%    +160 start_retriable_subchannel_batches                                                      +160  +5.2%
       +11%    +135 bool grpc_core::ServiceConfig::ParseJsonMethodConfig<grpc_core::internal::ClientChan    +135   +11%
      +0.5%     +15 on_complete                                                                              +15  +0.5%
      +0.2%      +1 [Unmapped]                                                                                +1  +0.2%
  +3.8%    +192 src/core/ext/filters/message_size/message_size_filter.cc                                +192  +3.8%
      +6.8%    +187 init_channel_elem                                                                       +187  +6.8%
      +4.1%      +5 [Unmapped]                                                                                +5  +4.1%
  +2.4%    +128 src/core/lib/iomgr/udp_server.cc                                                        +128  +2.4%
       +19%    +223 add_socket_to_server                                                                    +223   +19%
  +5.4%     +66 src/core/ext/filters/client_channel/lb_policy_registry.cc                                +66  +5.4%
       +27%    +145 grpc_core::LoadBalancingPolicyRegistry::Builder::RegisterLoadBalancingPolicyFactory     +145   +27%
       +37%      +7 [Unmapped]                                                                                +7   +37%

 -------------- SHRINKING                                                                            --------------
  -2.6%     -94 src/core/ext/filters/client_channel/resolver_registry.cc                                 -94  -2.6%
      -9.1%     -71 grpc_core::ResolverRegistry::CreateResolver                                              -71  -9.1%
      -7.8%     -57 grpc_core::ResolverRegistry::GetDefaultAuthority                                         -57  -7.8%
      [DEL]     -47 grpc_core::(anonymous namespace)::RegistryState::FindResolverFactory(char const*, gr     -47  [DEL]
     -33.7%     -34 grpc_core::ResolverRegistry::Builder::InitRegistry                                       -34 -33.7%
      -4.5%     -30 grpc_core::ResolverRegistry::AddDefaultPrefixIfNeeded                                    -30  -4.5%
     -12.0%     -27 grpc_core::ResolverRegistry::LookupResolverFactory                                       -27 -12.0%
      -8.8%     -25 grpc_core::ResolverRegistry::Builder::ShutdownRegistry                                   -25  -8.8%
      -4.8%      -8 grpc_core::ResolverRegistry::Builder::SetDefaultPrefix                                    -8  -4.8%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -19 [None]                                                                                +175Ki  +2.1%

  +0.0%    +536 TOTAL                                                                                 +176Ki  +1.9%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by markdroth** [comment]
See also #13254.

**Comment by vjpai** [comment]
Note that this is not an attempt to get absl working for now. It is just an experiment to report the latest set of failures. It is intended to keep going as a series. I wish that this were a way of telling reviewers that this is just pretend and that they should not really review it.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.9%    +263 src/core/ext/filters/client_channel/client_channel.cc                                   +263  +0.9%
      [NEW]    +181 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    +181  [NEW]
      +5.2%    +160 start_retriable_subchannel_batches                                                      +160  +5.2%
       +11%    +135 bool grpc_core::ServiceConfig::ParseJsonMethodConfig<grpc_core::internal::ClientChan    +135   +11%
      +0.5%     +15 on_complete                                                                              +15  +0.5%
      +0.2%      +1 [Unmapped]                                                                                +1  +0.2%
  +3.8%    +192 src/core/ext/filters/message_size/message_size_filter.cc                                +192  +3.8%
      +6.8%    +187 init_channel_elem                                                                       +187  +6.8%
      +4.1%      +5 [Unmapped]                                                                                +5  +4.1%
  +2.4%    +128 src/core/lib/iomgr/udp_server.cc                                                        +128  +2.4%
       +19%    +223 add_socket_to_server                                                                    +223   +19%
  +5.4%     +66 src/core/ext/filters/client_channel/lb_policy_registry.cc                                +66  +5.4%
       +27%    +145 grpc_core::LoadBalancingPolicyRegistry::Builder::RegisterLoadBalancingPolicyFactory     +145   +27%
       +37%      +7 [Unmapped]                                                                                +7   +37%

 -------------- SHRINKING                                                                            --------------
  -2.6%     -94 src/core/ext/filters/client_channel/resolver_registry.cc                                 -94  -2.6%
      -9.1%     -71 grpc_core::ResolverRegistry::CreateResolver                                              -71  -9.1%
      -7.8%     -57 grpc_core::ResolverRegistry::GetDefaultAuthority                                         -57  -7.8%
      [DEL]     -47 grpc_core::(anonymous namespace)::RegistryState::FindResolverFactory(char const*, gr     -47  [DEL]
     -33.7%     -34 grpc_core::ResolverRegistry::Builder::InitRegistry                                       -34 -33.7%
      -4.5%     -30 grpc_core::ResolverRegistry::AddDefaultPrefixIfNeeded                                    -30  -4.5%
     -12.0%     -27 grpc_core::ResolverRegistry::LookupResolverFactory                                       -27 -12.0%
      -8.8%     -25 grpc_core::ResolverRegistry::Builder::ShutdownRegistry                                   -25  -8.8%
      -4.8%      -8 grpc_core::ResolverRegistry::Builder::SetDefaultPrefix                                    -8  -4.8%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -19 [None]                                                                                +175Ki  +2.1%

  +0.0%    +536 TOTAL                                                                                 +176Ki  +1.9%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
is this PR still useful?

**Comment by vjpai** [comment]
It was probably never useful

**Pull request closed without merging**
