### PR TITLE
Added interop tests v2.

### PR DESCRIPTION
**Pull request by adelez**
@jtattermusch . The test won't run until we add --cloud_to_prod_v2 and --cloud_to_prod_auth_v2 in the main script.

### CODE REVIEW

**Comment by adelez** [comment]
Ping?

**Comment by jtattermusch** [comment]
For discussion: why is --cloud_to_prod_v2 and --cloud_to_prod_auth_v2    better than just having
--cloud_to_prod and --cloud_to_prod_auth and introducing a new --prod_backend="grpc-test12345.sandbox.google.com" argument?  For clarity, we could display the backend that was used HTML report, so that it's clear to everyone against what backend the tests were run.

Also, if we find ourselves needing to run against multiple prod backends at a time (do we really need to?), we can allow the --prod_backend argument to take multiple values and then run prod tests againts all the backends listed.

--prod_backend is just an example name of the argument I have in mind, I don't insist on that specific name, only using it to illustrate the idea.

**Comment by jtattermusch** [comment]
Unless I hear good arguments why duplicating the --cloud_to_prod argument is a good idea, I think I am against it.

**Comment by jtattermusch** [comment]
this is ok to test

**Comment by adelez** [comment]
There are several ways to do it, I just picked the one I thought was most clear about what this test is to do. But sure I can combine them too.

**Comment by adelez** [comment]
The advantage of separating the two is that right now some of the tests for the new service fail due to valid bugs. So if you put them together the overall cloud-to-prod tests look broken. By separating them, cloud-to-prod is more likely to be green.

**Comment by adelez** [comment]
I propose leaving them separate for now until the bugs are fixed.

**Comment by jtattermusch** [comment]
Ok, I definitely see an explosion of --cloud_to_prod_ABC  arguments coming (this PR is the first instance and the next instance is #5047 and this is not the last time we see this), which also requires changing the script in several places when those new arguments are introduced.

So we should stop for a moment and solve this problem right. As of now, the --prod_backend argument that accepts a list of backends and displays the backend names in the report seems like the way to go here.

**Comment by adelez** [comment]
#5047 doesn't introduce a new flag. It's how you suggested here. :) These two PR demonstrates my reasoning: #5047 is a test suite ready to be run with the existing tests right away, so no flag is needed, no change to the users. This PR needs a new flag because the tests are still under debugging. It's just laying ground work.

**Comment by jtattermusch** [comment]
This is solvable, we can introduce a whitelist of tests that are allowed to
fail, in a similar fashion as we did it for unimplemented test cases.

**Comment by adelez** [comment]
Sorry I missed the conversation on #5047.

**Comment by jtattermusch** [comment]
Ok, I misread the code, sorry.
Anyway, it looks like we are implementing one feature (ability to talk to different prod backends) in two different ways - here we are introducing a new flag and in #5047 we are solving basically the same problem in a different way.

**Pull request closed without merging**
