### PR TITLE
Add v1.34.0 release of grpc-go to interop matrix

### PR DESCRIPTION
**Pull request by dfawley**

### CODE REVIEW

**Comment by jtattermusch** [comment]
I started the interop matrix adhoc build, but this PR will be tricky to merge as long as b/174126929 is open (because interop_matrix on master is currently failing).

**Review by jtattermusch — APPROVED** [review]
LGTM once the adhoc interop matrix test is green.

**Comment by dfawley** [comment]
> LGTM once the adhoc interop matrix test is green.

Looks like it failed.  One looks bewildering ("all python tests passed" followed by "FAILED=1"), the other seems like it might be related to the recent changes to the Go test script:
```
../../credentials/credentials.go:31:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/go/src/github.com/golang/protobuf/proto (from $GOPATH)
../../internal/binarylog/method_logger.go:28:2: cannot find package "github.com/golang/protobuf/ptypes" in any of:
	/usr/local/go/src/github.com/golang/protobuf/ptypes (from $GOROOT)
	/go/src/github.com/golang/protobuf/ptypes (from $GOPATH)
../../balancer/grpclb/grpclb.go:42:2: cannot find package "github.com/golang/protobuf/ptypes/duration" in any of:
...
```

That is, unfortunately, about all I'm able to see in the logs.  Is `GO111MODULE=on` not being set in the script that this is using, perhaps?  That was the problem that led to these messages in the continuous interop failures.

**Comment by jtattermusch** [comment]
Yes, the issue is likely the missing GO111MODULE=on when invoking the go interop matrix tests

The file from where the commands to run are taken is:
https://github.com/grpc/grpc/blob/master/tools/interop_matrix/testcases/go__master. 

The challenge is that that file is generated (as specified in the comment), making sure GO111MODULE=on is not trivial.

Btw these things should have been considered when/before adding the GO111MODULE change to the grpc-go build system (and potential interop_matrix issues is also something I pointed out when requesting revert of the PR that broke the interop test build recently).

**Comment by dfawley** [comment]
> Btw these things should have been considered when/before adding the GO111MODULE change to the grpc-go build system (and potential interop_matrix issues is also something I pointed out when requesting revert of the PR that broke the interop test build recently).

Either way, progress needs to be made here, and needs to be possible.  We're using an unsupported, 2+ year old version of Go here.  We should have a low-effort process for upgrading so forward progress is not blocked by the testing infrastructure.

**Comment by jtattermusch** [comment]
> > Btw these things should have been considered when/before adding the GO111MODULE change to the grpc-go build system (and potential interop_matrix issues is also something I pointed out when requesting revert of the PR that broke the interop test build recently).
> 
> Either way, progress needs to be made here, and needs to be possible. We're using an unsupported, 2+ year old version of Go here. We should have a low-effort process for upgrading so forward progress is not blocked by the testing infrastructure.

It turns out just running `LANG=go ./create_testcases.sh` (as documented here: https://github.com/grpc/grpc/tree/master/tools/interop_matrix#instructions-for-creating-new-test-cases) was enough to refresh the testcases file to and reflect the GO111MODULE change - so not that high-effort as you are implying.

If you have ideas how to improve the current infrastructure (and can dedicate some time to improving things) that's of course welcome but it's somewhat unrelated to what I was saying - I just said that if grpc-go is upgrading their build process, making sure that doing that doesn't break the interop tests for everyone else should be part of the plan (as well as considering what this will mean upon the next release).

**Comment by jtattermusch** [comment]
I pushed a commit that hopefully will fix the adhoc interop matrix tests (and once that's green, we can merge).

**Comment by dfawley** [comment]
Looks like it's green now, thanks for the fix.  We will try to spend some time in Q1 on this during our fixit week.

**Comment by jtattermusch** [comment]
> Looks like it's green now, thanks for the fix. We will try to spend some time in Q1 on this during our fixit week.

Btw it should be relatively easy to setup a presubmit job for go interop tests (a "quick" subset of them - e.g. just go against go_server, or go against java_server or at least go to prod backends) - I think that's something that would prevent these kinds of breakages in the future. I don't have the bandwidth to do this myself but I can certainly help out when needed.
FTR I think setting up interop tests job with github actions (should also be feasible (normally we use kokoro, so some minor adjustments might be needed, but it should still work, especially if you only use languages that are fast to build - such as go and java).

**Comment by jtattermusch** [comment]
ObjC flakes are unrelated.

**Pull request merged**
