### PR TITLE
fix retry handling of callbacks for pending batches

### PR DESCRIPTION
**Pull request by markdroth**
This fixes two bugs:
1. When there was more than one pending batch containing send ops, we were failing to return the on_complete callback for all but the last one.
2. When all three recv ops are in the same batch, which is seen after we start our own internal recv_trailing_metadata batch, and the completion of that internal batch commits us to a failing call, we failed to return the recv_initial_metadata_ready and recv_message_ready callbacks.

### CODE REVIEW

**Comment by markdroth** [comment]
Known issues: #19834 #26595

The "Basic Tests PHP MacOS" failure is an infrastructure timeout.

**Comment by yashykt** [comment]
> When there was more than one pending batch containing send ops, we were failing to return the on_complete callback for all but the last one.

Is that even legal?

**Comment by markdroth** [comment]
> > When there was more than one pending batch containing send ops, we were failing to return the on_complete callback for all but the last one.
> 
> Is that even legal?

Yes.  You can't have more than one send_message op pending at once, but you can start one batch with send_initial_metadata, a second batch with send_message, and a third batch with send_trailing_metadata.  See the test for an example.

**Review by yashykt — APPROVED** [review]

**Comment by markdroth** [comment]
Known issues: #26595 

The "Basic Tests ObjC iOS" test is an infrastructure failure.

**Pull request merged**
