### PR TITLE
Revert a change in BoringSSL 8.1 podspec

### PR DESCRIPTION
**Pull request by muxi**
BoringSSL 8.1 podspec included an inappropriate fix for interop tests in (#10631). This will cause build failing when building for iOS devices. This PR partly reverts BoringSSL 8.1 podspec upgrade to fix this problem. Better fix for the original problem follows in another PR.

### CODE REVIEW

**Comment by jcanizales** [comment]
Please link to the original pull request, for easier context.

Also, consider trying to catch this problem in the automated tests by [archiving from the command line](http://stackoverflow.com/questions/2664885/xcode-build-and-archive-from-command-line).

**Comment by jcanizales** [comment]
Why is the umbrella header not reverted too?

**Comment by muxi** [comment]
Good point... missed that

**Comment by muxi** [comment]
Test failures:
gRPC_performance_pull_requests - #10714 
gRPC_interop_pull_requests - #10576

**Comment by jcanizales** [comment]
Do you want to open an issue for testing this automatically?

**Pull request merged**
