### PR TITLE
Upgrade bazel version to 0.27.1

### PR DESCRIPTION
**Pull request by jtattermusch**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Confirming that for now bazel 0.27 is failing on Kokoro's workers:

```
+ tools/bazel version
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 0.27.0 will be used instead of system-wide bazel installation.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   615    0   615    0     0   2615      0 --:--:-- --:--:-- --:--:--  2639
  0 44.8M    0 68139    0     0   154k      0  0:04:57 --:--:--  0:04:57  154k
100 44.8M  100 44.8M    0     0  45.7M      0 --:--:-- --:--:-- --:--:-- 81.4M
/tmpfs/src/github/grpc/tools/bazel-0.27.0-linux-x86_64: relocation error: /tmpfs/src/github/grpc/tools/bazel-0.27.0-linux-x86_64: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

**Comment by jtattermusch** [comment]
Looks like bazel 0.27.1 will restore compatibility with ubuntu Ubuntu 14.04 so we can just wait for that release.

**Comment by nicolasnoble** [comment]
Looks like there's still broken things.

**Comment by jtattermusch** [comment]
Looks like upgrading to bazel 0.27.1 breaks the `//test/cpp/naming:resolver_component_tests_runner_invoker_unsecure` test on bazel RBE

This is the culprit
```
/b/f/w/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Health check: attempt to connect to DNS server over TCP.
/b/f/w/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Failed to reach DNS server over TCP and/or UDP. Exitting without running tests.
/b/f/w/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: ======= DNS server stdout (merged stdout and stderr) =============
/b/f/w/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epoll1.runfiles/com_github_grpc_grpc/test/cpp/naming/utils/dns_server.py", line 20, in <module>
    import yaml
  File "/b/f/w/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epoll1.runfiles/com_github_yaml_pyyaml/lib/yaml/__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'
```

https://source.cloud.google.com/results/invocations/851e8909-629c-4973-b3a5-fe02484ccf3e/targets

CC @apolcyn  @gnossen

**Comment by jtattermusch** [comment]
Bazel RBE windows build also seems problematic (but this is less of an issue)
https://source.cloud.google.com/results/invocations/1e15715f-704f-46d5-9050-811aa3f3db84/log

**Comment by jtattermusch** [comment]
The python bazel problem might be
*Python rules now find the Python runtime using toolchains, rather than the --python_top and --python_path flags, which are deprecated. See the migration issue for more information on declaring Python toolchains and migrating your code.* as mentioned in the release notes https://blog.bazel.build/2019/06/17/bazel-0.27.0.html
https://github.com/bazelbuild/bazel/issues/7899

**Comment by jtattermusch** [comment]
@gnossen , can you help with the python bazel build issue mentioned here: https://github.com/grpc/grpc/pull/19462#issuecomment-508543500

**Comment by gnossen** [comment]
@jtattermusch To give you an update on this, I don't see a quick workaround for this problem. It seems that the way python interpreter version is specified has fundamentally changed. I'm working on a toolchain-based selection mechanism.

**Comment by jtattermusch** [comment]
The bazel RBE problem:
https://source.cloud.google.com/results/invocations/9c50241f-e011-46bd-9c08-ae9606f084d8/log

```
...
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2:discovery:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2/core:health_check:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2/core:address:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2/core:config_source:
external/com_google_protobuf: warning: directory does not exist.
[1,377 / 1,399] Generating Descriptor Set proto_library @envoy_api//envoy/api/v2/cluster:circuit_breaker; 17s remote ... (5 actions running)
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2/endpoint:load_report:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2/cluster:circuit_breaker:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2/auth:cert:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/service/load_stats/v2:lrs:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2/endpoint:endpoint:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2:eds:
external/com_google_protobuf: warning: directory does not exist.
INFO: From Generating Descriptor Set proto_library @envoy_api//envoy/api/v2:cds:
external/com_google_protobuf: warning: directory does not exist.
[1,396 / 1,399] [Prepa] Generating upb protos for :cds
INFO: Elapsed time: 262.196s, Critical Path: 185.08s
INFO: 1303 processes: 1229 remote cache hit, 74 remote.
INFO: Build completed successfully, 1399 total actions
ERROR: The Build Event Protocol upload failed: INTERNAL: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
INFO: Build completed successfully, 1399 total actions
T:\src\github\grpc>set BAZEL_EXITCODE=38
```

**Comment by jtattermusch** [comment]
Bazel RBE C/C++ are now mostly passing, but test result uploading seems broken:
https://source.cloud.google.com/results/invocations/69d7cf07-cf25-422f-86c2-14929a03fe51/log

```
//test/cpp/util:time_test@poller=epollex                                 PASSED in 2.5s
//test/cpp/util:time_test@poller=poll                                    PASSED in 3.1s
//test/cpp/naming:resolver_component_tests_runner_invoker@poller=epoll1  FAILED in 17.4s
  /tmpfs/tmp/bazel/execroot/com_github_grpc_grpc/bazel-out/k8-opt/testlogs/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epoll1/test.log
//test/cpp/naming:resolver_component_tests_runner_invoker@poller=epollex FAILED in 16.5s
  /tmpfs/tmp/bazel/execroot/com_github_grpc_grpc/bazel-out/k8-opt/testlogs/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epollex/test.log
//test/cpp/naming:resolver_component_tests_runner_invoker@poller=poll    FAILED in 15.5s
  /tmpfs/tmp/bazel/execroot/com_github_grpc_grpc/bazel-out/k8-opt/testlogs/test/cpp/naming/resolver_component_tests_runner_invoker@poller=poll/test.log
//test/cpp/naming:resolver_component_tests_runner_invoker_unsecure@poller=epoll1 FAILED in 15.5s
  /tmpfs/tmp/bazel/execroot/com_github_grpc_grpc/bazel-out/k8-opt/testlogs/test/cpp/naming/resolver_component_tests_runner_invoker_unsecure@poller=epoll1/test.log
//test/cpp/naming:resolver_component_tests_runner_invoker_unsecure@poller=epollex FAILED in 17.3s
  /tmpfs/tmp/bazel/execroot/com_github_grpc_grpc/bazel-out/k8-opt/testlogs/test/cpp/naming/resolver_component_tests_runner_invoker_unsecure@poller=epollex/test.log
//test/cpp/naming:resolver_component_tests_runner_invoker_unsecure@poller=poll FAILED in 15.0s
  /tmpfs/tmp/bazel/execroot/com_github_grpc_grpc/bazel-out/k8-opt/testlogs/test/cpp/naming/resolver_component_tests_runner_invoker_unsecure@poller=poll/test.log
Executed 8281 out of 8281 tests: 8275 tests pass and 6 fail remotely.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build completed, 6 tests FAILED, 38561 total actions
ERROR: The Build Event Protocol upload failed: UNAVAILABLE: Network is unreachable
INFO: Build completed, 6 tests FAILED, 38561 total actions
```

**Comment by jtattermusch** [comment]
Another problem:
```
/b/f/w/bazel-out/k8-opt/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=poll.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Failed to reach DNS server over TCP and/or UDP. Exitting without running tests.
/b/f/w/bazel-out/k8-opt/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=poll.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: ======= DNS server stdout (merged stdout and stderr) =============
/b/f/w/bazel-out/k8-opt/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=poll.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=poll.runfiles/com_github_grpc_grpc/test/cpp/naming/utils/dns_server.py", line 20, in <module>
    import yaml
  File "/b/f/w/bazel-out/k8-opt/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=poll.runfiles/com_github_yaml_pyyaml/lib/yaml/__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'
/b/f/w/bazel-out/k8-opt/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=poll.runfiles/com_github_grpc_grpc/test/cpp/naming/resolver_component_tests_runner.py: ======= end DNS server output=========
I0826 15:22:28.683130456      17 resolver_component_tests_runner_invoker.cc:133] Resolver component test test-runner exited with code 1
Aborted (core dumped)
================================================================================
[33,449 / 33,649] 6717 / 8281 tests, 6 failed; Testing //test/cpp/end2end:xds_end2end_test@poller=epollex; 104s remote ... (200 actions, 199 running)
[38,053 / 38,253] 7995 / 8281 tests, 6 failed; Testing //test/cpp/end2end:xds_end2end_test@poller=epollex; 145s remote ... (200 actions running)
[38,560 / 38,561] 8280 / 8281 tests, 6 failed; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 50s remote
[38,560 / 38,561] 8280 / 8281 tests, 6 failed; Testing //test/cpp/end2end:xds_end2end_test@poller=poll; 105s remote
INFO: Elapsed time: 476.924s, Critical Path: 165.87s
INFO: 20556 processes: 4343 remote cache hit, 16213 remote.
INFO: Build completed, 6 tests FAILED, 38561 total actions
```

**Comment by jtattermusch** [comment]
Two problems remaining:
- `resolver_component_tests_runner.py` fails to start dns_server.py because of a missing import:
https://source.cloud.google.com/results/invocations/076294c7-ea79-45ad-85c2-d7a4933527af/targets/%2F%2Ftest%2Fcpp%2Fnaming:resolver_component_tests_runner_invoker@poller%3Depollex/log
- python bazel test run:  https://source.cloud.google.com/results/invocations/369a5a23-8007-4d8b-b938-df9084cf98f9/log : there seem to be some problems with imports too

**Comment by jtattermusch** [comment]
Superseded by #20097 (which has the right bazel build fixes to make all the tests pass).
Thanks @gnossen  for help!

**Pull request closed without merging**
