### PR TITLE
Backport #20761 and #20764

### PR DESCRIPTION
**Pull request by veblush**
This is required to build ruby artifacts and pass distribtests for ruby. (Backport of #20761 and #20764)

### CODE REVIEW

**Comment by jtattermusch** [comment]
I'm confused. You're saying "backport" but all of these PRs are against master.

**Comment by nicolasnoble** [comment]
I'm with Jan here :) That's the wrong branch. #20761 and #20764 were against master, and so is this PR.

**Comment by nicolasnoble** [comment]
Looks like I managed to update the base branch without anything breaking.

**Comment by veblush** [comment]
Oops! It's my bad to make this onto master. It should be on v1.25.x branch! Thanks Nico!

**Pull request merged**
