### PR TITLE
Revert "Revert "Revert "Add Python Reflection Client"""

### PR DESCRIPTION
**Pull request by drfloob**
Reverts grpc/grpc#28879

This breaks portability and ARM tests.

### CODE REVIEW

**Review by lidizheng — APPROVED** [review]

**Review by gnossen — APPROVED** [review]

**Comment by lidizheng** [comment]
The breaking tests:

* https://source.cloud.google.com/results/invocations/4884c82b-9a41-45bc-b86d-81076d5f53e5/targets/github%2Fgrpc%2Frun_tests%2Fpython_linux_dbg_native_default_python_alpine%2Fpy38.native.reflection._reflection_client_test.ReflectionClientTest/tests
* https://source.cloud.google.com/results/invocations/2c54aa59-d164-487d-b91b-8ec934f35a98/targets

**Comment by tomerv** [comment]
@drfloob - can you please clarify where the portability break? Is it the tests that @lidizheng linked?
TBH, I don't understand how it could fail. The tests pass on my machine and they passed in the original pull request (but now the check is missing from there?!) - how can I reproduce this? I don't see any reason for this failure. On the other hand, I can't argue with the results...

This is what fails:
```
_INVALID_SYMBOL_NAME = "IDoNotExist"
# ...
        with self.assertRaises(KeyError):
            service_desc.FindMethodByName(_INVALID_SYMBOL_NAME)
```

**Comment by drfloob** [comment]
The tests that @lidizheng linked show failures in testFindMethodError:

```
...
SUCCESS       reflection._reflection_client_test.ReflectionClientTest.testFindMessageError
FAILURE       reflection._reflection_client_test.ReflectionClientTest.testFindMethodError
SUCCESS       reflection._reflection_client_test.ReflectionClientTest.testFindServiceError
...
```

This set of tests is run before cutting a release, and I rolled it back so we could move forward for the release. Lidi can help you run them again when you've figured out the issue. 

I'm not a regular on the Python team, but from first glance, I think it might be a poor assumption that FindMethodByName raises an error when not found. From https://googleapis.dev/python/protobuf/latest/google/protobuf/descriptor.html#google.protobuf.descriptor.ServiceDescriptor.FindMethodByName

image

**Comment by tomerv** [comment]
Interesting, this seems to be a bug in protobuf. I opened an issue: https://github.com/protocolbuffers/protobuf/issues/9592

I'll remove this test (or make it compatible with both behaviors) and resubmit a patch.

**Pull request merged**
