### PR TITLE
Remove lambda expression from grpc C++ library and make a fake nullptr

### PR DESCRIPTION
**Pull request by vjpai**
To support older compilers (specifically gcc 4.4-4.5), we need to eliminate lambda expressions and nullptr.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Will wait from travis, but basically LGTM. I wonder if there isn't a better way to detect the presence of nullptr tho...

**Comment by vjpai** [comment]
I think that the best way to detect nullptr would be to actually have a
test run at configure time to see if the nullptr inherently exists and has
normal behavior.

**Comment by yang-g** [comment]
Is it possible to add a test to build with some legacy compiler?

**Comment by vjpai** [comment]
That would be great; maybe there is a way to do it in Travis? I'm using an outside account that has an old compiler on it for now.

**Comment by nicolasnoble** [comment]
I'm trying something - travis has that ability, but we can't compile and run the tests, since they're still containing things gcc-4.4 wouldn't like.

**Comment by vjpai** [comment]
That's correct, we can only run a limited selection of the C++ tests under
4.4

**Comment by nicolasnoble** [comment]
Check vjpai/grpc#1 - I've done a pull request on top of that pull request :-)

**Comment by vjpai** [comment]
I confirm that all your commits are belong to me

**Comment by nicolasnoble** [comment]
Yeah, yeah, I consent :-)

**Comment by vjpai** [comment]
FYI, clang has a test to check if nullptr is supported using __has_features . For gcc, we can test based on the version # . So, I should add a test in for the clang case also.

**Pull request merged**
