### PR TITLE
Initialize last sent ping time

### LINKED ISSUE #13504: py35.test.interop._secure_intraop_test.SecureIntraopTest timing out (on Windows)
Timing out with rather high rate (~20%), mostly on Windows opt.

https://sponge.corp.google.com/target?id=9995e90c-b26b-4bfa-b364-dadfd238a7ff&target=github/grpc/python_windows_opt_native&searchFor=&show=FAILED&sortBy=STATUS

```
Timeout
++ dirname 'T:\src\github\grpc\workspace_python_windows_opt_native\tools\run_tests\helper_scripts\run_python.sh'
+ cd 'T:\src\github\grpc\workspace_python_windows_opt_native\tools\run_tests\helper_scripts/../../..'
++ realpath 'py35\Scripts/python.exe'
+ PYTHON=/t/src/github/grpc/workspace_python_windows_opt_native/py35/Scripts/python.exe
++ pwd
+ ROOT=/t/src/github/grpc/workspace_python_windows_opt_native
+ /t/src/github/grpc/workspace_python_windows_opt_native/py35/Scripts/python.exe /t/src/github/grpc/workspace_python_windows_opt_native/src/python/grpcio_tests/setup.py test_lite
running test_lite
Running       interop._secure_intraop_test.SecureIntraopTest.testCancelAfterBegin
[95mTesting gRPC Python...
[0m[92mSUCCESS       interop._secure_intraop_test.SecureIntraopTest.testCancelAfterBegin
[0mRunning       interop._secure_intraop_test.SecureIntraopTest.testCancelAfterFirstResponse
[92mSUCCESS       interop._secure_intraop_test.SecureIntraopTest.testCancelAfterFirstResponse
[0mRunning       interop._secure_intraop_test.SecureIntraopTest.testClientStreaming
[92mSUCCESS       interop._secure_intraop_test.SecureIntraopTest.testClientStreaming
[0mRunning       interop._secure_intraop_test.SecureIntraopTest.testEmptyUnary
[92mSUCCESS       interop._secure_intraop_test.SecureIntraopTest.testEmptyUnary
[0mRunning       interop._secure_intraop_test.SecureIntraopTest.testLargeUnary
```

### PR DESCRIPTION
**Pull request by kpayson64**
Fixes #13504

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.8%     +48 src/core/ext/transport/chttp2/transport/writing.cc              +48  +0.8%
      +0.7%     +40 grpc_chttp2_begin_write                                         +40  +0.7%
       +73%      +8 [Unmapped]                                                       +8   +73%
  +0.0%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +16  +0.0%
      +0.5%     +16 grpc_create_chttp2_transport                                    +16  +0.5%

 -+-+-+-+-+-+-+ MIXED                                                       +-+-+-+-+-+-+-
  +0.0%     +32 [None]                                                          -80  -0.0%

  +0.0%     +96 TOTAL                                                           -16  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by kpayson64** [comment]
#12510
#12913

**Pull request merged**
