### PR TITLE
1.1.x to master again

### PR DESCRIPTION
**Pull request by dgquintas**
This should be the last one prior to jumping to 1.2.x.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Marked as "release blocker" as this contains changes that also need to go to 1.2.x branch (after merging this to master)

**Comment by dgquintas** [comment]
@murgatroid99 can you confirm this is ok for your contributions?

**Comment by dgquintas** [comment]
@apolcyn can you confirm this is ok for your contributions?

**Comment by murgatroid99** [comment]
It's OK with me

**Comment by dgquintas** [comment]
Issues: #10031 #9956

**Pull request merged**
