### PR TITLE
Removed expiration_interval from LB proto

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by dgquintas** [comment]
jenkins test this please

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                 FILE SIZE
 ++++++++++++++ GROWING                                                                   ++++++++++++++

 -------------- SHRINKING                                                                 --------------
  -0.0%     -56 [None]                                                                       -544  -0.0%
      -0.0%     -42 [Unmapped]                                                                   -530  -0.0%
     -33.3%     -14 grpc_lb_v1_ServerList_fields                                                  -14 -33.3%
  -2.6%     -80 src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc     -80  -2.6%
      -7.6%     -40 grpc_grpclb_response_parse_serverlist                                         -40  -7.6%
      -9.8%     -24 grpc_grpclb_serverlist_copy                                                   -24  -9.8%
     -15.6%     -21 grpc_grpclb_serverlist_equals                                                 -21 -15.6%

  -0.0%    -136 TOTAL                                                                        -624  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                 FILE SIZE
 ++++++++++++++ GROWING                                                                   ++++++++++++++

 -------------- SHRINKING                                                                 --------------
  -0.0%     -88 [None]                                                                       -544  -0.0%
      -0.0%     -74 [Unmapped]                                                                   -530  -0.0%
     -33.3%     -14 grpc_lb_v1_ServerList_fields                                                  -14 -33.3%
  -2.6%     -80 src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc     -80  -2.6%
      -7.6%     -40 grpc_grpclb_response_parse_serverlist                                         -40  -7.6%
      -9.8%     -24 grpc_grpclb_serverlist_copy                                                   -24  -9.8%
     -15.6%     -21 grpc_grpclb_serverlist_equals                                                 -21 -15.6%

  -0.0%    -168 TOTAL                                                                        -624  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                cpu_time    real_time
---------------------------------------------------------------------------------------  ----------  -----------
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/32768/2/1  -5%         -5%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/262144                        -4%         -4%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                 FILE SIZE
 ++++++++++++++ GROWING                                                                   ++++++++++++++

 -------------- SHRINKING                                                                 --------------
  -0.0%    -152 [None]                                                                       -600  -0.0%
      -0.0%    -106 [Unmapped]                                                                   -586  -0.0%
      -2.6%     -32 [None]                                                                          0  [ = ]
     -33.3%     -14 grpc_lb_v1_ServerList_fields                                                  -14 -33.3%
  -2.6%     -80 src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc     -80  -2.6%
      -7.6%     -40 grpc_grpclb_response_parse_serverlist                                         -40  -7.6%
      -9.8%     -24 grpc_grpclb_serverlist_copy                                                   -24  -9.8%
     -15.6%     -21 grpc_grpclb_serverlist_equals                                                 -21 -15.6%

  -0.0%    -232 TOTAL                                                                        -680  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                 FILE SIZE
 ++++++++++++++ GROWING                                                                   ++++++++++++++

 -------------- SHRINKING                                                                 --------------
  -0.0%    -152 [None]                                                                       -600  -0.0%
      -0.0%    -106 [Unmapped]                                                                   -586  -0.0%
      -2.6%     -32 [None]                                                                          0  [ = ]
     -33.3%     -14 grpc_lb_v1_ServerList_fields                                                  -14 -33.3%
  -2.6%     -80 src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc     -80  -2.6%
      -7.6%     -40 grpc_grpclb_response_parse_serverlist                                         -40  -7.6%
      -9.8%     -24 grpc_grpclb_serverlist_copy                                                   -24  -9.8%
     -15.6%     -21 grpc_grpclb_serverlist_equals                                                 -21 -15.6%

  -0.0%    -232 TOTAL                                                                        -680  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
Issues: #13149 #13669

**Pull request merged**
