### PR TITLE
Compiling protobuf twice to enable msan in C++, and let cross compilation be a thing.

### PR DESCRIPTION
**Pull request by nicolasnoble**
This still won't allow us to get msan for C++ just yet, but it gets us one step closer.

This builds the protobuf submodule twice. Once to build protoc without msan, and once to build the rest (libprotoc and libprotobuf) with msan, and while overriding the protoc with the one we just compiled before.

Now failures lies within the plugins themselves, as they get compiled and linked with msan options.

@tengyifei

### CODE REVIEW

**Comment by murgatroid99** [comment]
LGTM

**Comment by nicolasnoble** [comment]
test this please

**Comment by murgatroid99** [comment]
Sanity is failing

**Comment by nicolasnoble** [comment]
Refreshed stuff by pulling from master. The failed test was... weird.

**Comment by murgatroid99** [comment]
That same test is still failing

**Comment by nicolasnoble** [comment]
I don't... understand...

**Comment by murgatroid99** [comment]
test this please

**Comment by vjpai** [comment]
Is this PR near ready to merge at some point?

**Comment by ctiller** [comment]
test this please

**Comment by nicolasnoble** [comment]
We'll switch to just Bazel, so, no.

**Pull request closed without merging**
