### PR TITLE
Fix NSDictionary <-> metadata codec

### PR DESCRIPTION
**Pull request by jcanizales**
This was making the C library to silently drop all our request headers. Which prevented auth :)

* Assign `metadata->value_length`, to prevent all request headers from being dropped :)
* Add the `"-bin"` suffix to the key of binary metadata (and strip it when it's received).
* Initialize NSStrings from metadata with ASCII encoding instead of Unicode.

### CODE REVIEW

**Comment by jcanizales** [comment]
@marcwan This is the fix to the auth issue.

**Comment by murgatroid99** [comment]
I'm unsure about this automatic handling of binary fields. What if two incoming (from the server) metadata items have the same key, one with `-bin` and one without? What if our user gives us a string with the key `key-bin` and a `NSData` object with the key `key`? It seems like they'll effectively be coalesced at the other end.

**Comment by jcanizales** [comment]
> What if two incoming (from the server) metadata items have the same key, one with -bin and one without?

You end up with `@{@"key": @[<NSString value>, <NSData value>]}`.

> What if our user gives us a string with the key key-bin

Ah, right, we have to prevent that, or it'll fool the C library into encoding and decoding the value as base-64.

> and a NSData object with the key key?

For this we _need_ to add the `"-bin"` suffix, per the contract of the C library.

I don't know of a better way to do it without inflicting on the user the pain of turning `NSString`s into `NSData`s and adding suffixes. The most common case by far will be non-repeated header names, none of which end in `"-bin"`.

**Comment by jcanizales** [comment]
This now raises an exception when the user tries to make a call with a header `@{@"something-bin": <NSString value>}`. If they really really need such a header, they can dump the string into a NSData and set `@{@"something-bin": <NSData equivalent value>}`. The server would see the same in both cases.

**Pull request merged**
