### PR TITLE
Fix Makefile incorrect shared lib major version for install

### LINKED ISSUE #10299: Mismatched soname for libgrpc++
A symlink to libgrpc++.so.1.2.0 is [created in the Makefile](https://github.com/grpc/grpc/blob/eeb3b24f7ed2d2a560d94d7c87a5d99fb19d6e35/Makefile#L4141) with the name libgrpc++.so.1. However, the soname of this library is set to libgrpc++.so.3 on the line above. This causes programs linked with libgrpc++ to fail with the error
`./tests: error while loading shared libraries: libgrpc++.so.3: cannot open shared object file: No such file or directory`

Creating the symlink manually fixes the problem (but I haven't checked if grpc actually works). I'm using OpenSUSE Leap 42.2, with source from the 'v1.2.0' git tag.

Note: I know very little about sonames, so this could be completely wrong. :-)

### PR DESCRIPTION
**Pull request by sgleizes**
Trivial change to parameterize the soname used when installing libraries.

Fixes #10299 #10942 #11868 #12764

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits was unable to be associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by sgleizes** [comment]
Email issue should be fixed

**Comment by sgleizes** [comment]
Email/CLA issue should be fixed

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by sgleizes** [comment]
I see there are two CI checks failing, but I cannot access the report.
Let me know if there's something to fix.

**Comment by iMichka** [comment]
Any progress on this? We have this issue when packaging grpc for Linux in the Linuxbrew package manager: https://github.com/Linuxbrew/homebrew-core/pull/8136

I could hack around the issue but I would prefer a proper solution is found upstream first.

**Comment by sawlogs** [comment]
@sgleizes It seems the Makefile is automatically generated, so you need to patch the build source.
See the header: 
> \# GRPC global makefile
> \# This currently builds C and C++ code.
> \# This file has been automatically generated from a template file.
> \# Please look at the templates directory instead.
> \# This file can be regenerated from the template by running
> \# tools/buildgen/generate_projects.sh

**Comment by jtattermusch** [comment]
Superseded by https://github.com/grpc/grpc/pull/16832

**Pull request closed without merging**
