### PR TITLE
Backport 16659: Update function signature in grpc_security

### PR DESCRIPTION
**Pull request by muxi**
Backport #16659

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,061      Total (=)      1,955,061

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,023      Total (>)     10,843,022

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Bazel test failures - #16687
Interop tests failures - #16531

**Pull request merged**
