### PR TITLE
Revert "Stop using std::thread in C++ library since it can trigger exceptions"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#13697

Even though the tests on the original PR look green, I've noticed about 20 end2end flakes started failing when this was merged.

The failures started with this c++ tsan build https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/sanitizer/job/grpc_cpp_tsan/409/

failures (failed in all builds since build 409 and didn't fail for many builds before that).
end2end_test --gtest_filter=ProxyEnd2end/ProxyEnd2endTest.RpcDeadlineExpires
end2end_test --gtest_filter=End2end/End2endTest.CancelRpcBeforeStart
end2end_test --gtest_filter=End2end/End2endTest.BidiStreamWithEverythingCoalesced
end2end_test --gtest_filter=ProxyEnd2end/ProxyEnd2endTest.EchoDeadline
end2end_test --gtest_filter=End2end/End2endTest.ReconnectChannel

around 10 other end2end test also got much flakier.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -2.1%    -739 src/cpp/server/server_cc.cc                                                             -739  -2.1%
      [DEL] -2.54Ki grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>::RunHandler                 -2.54Ki  [DEL]
      [DEL] -2.54Ki grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>::RunHandler                  -2.54Ki  [DEL]
      [DEL] -2.06Ki grpc::Server::Server                                                                 -2.06Ki  [DEL]
      [DEL] -1.41Ki grpc::Server::SyncRequestThreadManager::DoWork(void*, bool, bool) [clone .part.61]   -1.41Ki  [DEL]
      [DEL]    -194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    -194  [DEL]
      -7.1%     -80 grpc::Server::~Server                                                                    -80  -7.1%
      [DEL]     -63 grpc::Server::SyncRequestThreadManager::DoWork                                           -63  [DEL]
      -1.7%     -32 grpc::Server::Start                                                                      -32  -1.7%
      [DEL]      -5 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>::~ErrorMethodHandler             -5  [DEL]
      [DEL]      -5 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>::~ErrorMethodHandler              -5  [DEL]
      [DEL]      -2 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>::~ErrorMethodHandler             -2  [DEL]
      [DEL]      -2 grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>::~ErrorMethodHandler              -2  [DEL]
 -11.5%    -532 src/cpp/server/dynamic_thread_pool.cc                                                   -532 -11.5%
      [DEL] -1.22Ki grpc::DynamicThreadPool::DynamicThreadPool                                           -1.22Ki  [DEL]
      [DEL]    -299 grpc::DynamicThreadPool::DynamicThread::DynamicThread                                   -299  [DEL]
     -62.6%    -119 grpc::DynamicThreadPool::DynamicThread::~DynamicThread                                  -119 -62.6%
     -19.6%     -69 grpc::DynamicThreadPool::Add                                                             -69 -19.6%
     -10.2%     -56 grpc::DynamicThreadPool::~DynamicThreadPool                                              -56 -10.2%
     -11.7%      -7 [Unmapped]                                                                                -7 -11.7%
      [DEL]      -5 grpc::DynamicThreadPool::DynamicThread::DynamicThread(grpc::DynamicThreadPool*, bool      -5  [DEL]
 -15.7%    -444 src/cpp/thread_manager/thread_manager.cc                                                -444 -15.7%
      [DEL]    -335 grpc::ThreadManager::ThreadManager                                                      -335  [DEL]
      [DEL]    -296 grpc::ThreadManager::WorkerThread::WorkerThread                                         -296  [DEL]
     -19.3%    -107 grpc::ThreadManager::MainWorkLoop                                                       -107 -19.3%
     -46.0%    -104 grpc::ThreadManager::Initialize                                                         -104 -46.0%
     -50.0%     -95 grpc::ThreadManager::WorkerThread::~WorkerThread                                         -95 -50.0%
     -20.6%     -52 grpc::ThreadManager::~ThreadManager                                                      -52 -20.6%
     -11.4%     -12 [Unmapped]                                                                               -12 -11.4%
      [DEL]      -5 grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*, bool*)::{lambd      -5  [DEL]
  -3.9%    -383 src/cpp/server/server_builder.cc                                                        -383  -3.9%
      -8.1%    -239 grpc::ServerBuilder::BuildAndStart                                                      -239  -8.1%
      [DEL]    -194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    -194  [DEL]
     -17.6%     -96 grpc::ServerBuilder::ServerBuilder                                                       -96 -17.6%
      -7.1%     -48 grpc::ServerBuilder::~ServerBuilder                                                      -48  -7.1%
 -77.8%    -308 src/cpp/server/create_default_thread_pool.cc                                            -308 -77.8%
     -75.9%    -176 grpc::(anonymous namespace)::CreateDefaultThreadPoolImpl                                -176 -75.9%
      [DEL]     -46 std::_Function_base::_Base_manager<int (*)(unsigned long*, char const*, void (*)(voi     -46  [DEL]
      [DEL]     -46 std::_Function_base::_Base_manager<void (*)(unsigned long)>::_M_manager                  -46  [DEL]
      [DEL]     -32 std::_Function_handler<int (unsigned long*, char const*, void (*)(void*), void*, gpr     -32  [DEL]
      [DEL]      -8 std::_Function_handler<void (unsigned long), void (*)(unsigned long)>::_M_invoke          -8  [DEL]
  -0.8%     -64 src/cpp/client/secure_credentials.cc                                                     -64  -0.8%
     -10.5%     -64 grpc::MetadataCredentialsPluginWrapper::GetMetadata                                      -64 -10.5%
  -0.7%     -32 src/cpp/server/secure_server_credentials.cc                                              -32  -0.7%
      -8.5%     -32 grpc::AuthMetadataProcessorAyncWrapper::Process                                          -32  -8.5%

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.2%    -498 [None]                                                                               +27.1Ki  +0.6%
      [NEW]    +109 typeinfo name for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc    +109  [NEW]
      [NEW]    +104 typeinfo name for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc    +104  [NEW]
      [NEW]     +40 vtable for grpc::internal::UnknownMethodHandler                                          +40  [NEW]
      [NEW]     +40 vtable for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc::Threa     +40  [NEW]
      [NEW]     +40 vtable for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc::Dynam     +40  [NEW]
      [NEW]     +39 typeinfo name for grpc::internal::UnknownMethodHandler                                   +39  [NEW]
      [NEW]     +24 typeinfo for grpc::internal::UnknownMethodHandler                                        +24  [NEW]
      [NEW]     +24 typeinfo for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc::Thr     +24  [NEW]
      [NEW]     +24 typeinfo for std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (grpc::Dyn     +24  [NEW]
      [DEL]     -59 typeinfo name for grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>               -59  [DEL]
      [DEL]     -58 typeinfo name for grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>                -58  [DEL]
      [DEL]     -40 vtable for grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>                      -40  [DEL]
      [DEL]     -40 vtable for grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>                       -40  [DEL]
      [DEL]     -38 typeinfo name for int (*)                                                                -38  [DEL]
      [DEL]     -37 typeinfo name for int                                                                    -37  [DEL]
      [DEL]     -32 typeinfo for int (*)                                                                     -32  [DEL]
      [DEL]     -32 typeinfo for void (*)                                                                    -32  [DEL]
      [DEL]     -24 typeinfo for grpc::internal::ErrorMethodHandler<(grpc::StatusCode)12>                    -24  [DEL]
      [DEL]     -24 typeinfo for grpc::internal::ErrorMethodHandler<(grpc::StatusCode)8>                     -24  [DEL]
      [DEL]     -16 typeinfo for int                                                                         -16  [DEL]
      [DEL]     -16 typeinfo for void                                                                        -16  [DEL]
      [DEL]      -6 typeinfo name for void (*)                                                                -6  [DEL]
      [DEL]      -5 typeinfo name for void                                                                    -5  [DEL]

  -0.9% -2.93Ki TOTAL                                                                                +24.7Ki  +0.5%



```

**Comment by jtattermusch** [comment]
The failures:
https://sponge.corp.google.com/target?id=d8e1e60b-a746-463c-9cf4-7e545a8beb04&target=github/grpc/c%2B%2B_linux_tsan_native&searchFor=&show=ALL&sortBy=STATUS

```
SUMMARY: ThreadSanitizer: data race on vptr (ctor/dtor vs virtual call) /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:72:33 in grpc::ThreadManager::~ThreadManager()
```

```
SUMMARY: ThreadSanitizer: data race /llvm/projects/compiler-rt/lib/tsan/rtl/tsan_new_delete.cc:77 in operator delete(void*)
```

and similar

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Ok, let's revert this and try again.

**Pull request merged**
