### PR TITLE
Record backwards comp results to BQ and add more details to test names in Sponge URL

### PR DESCRIPTION
**Pull request by adelez**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.old: 1


[microbenchmarks] No significant performance differences
```

**Comment by adelez** [comment]
Interop Cloud-to-Prod Tests https://github.com/grpc/grpc-java/issues/3562#issuecomment-335873934
Interop Cloud-to-Cloud Tests https://github.com/grpc/grpc-go/issues/1572
Msan C (internal CI infra failure)
Tsan C #12892
Tsan C++ #12983
UBsan C #12982

**Pull request merged**
