### PR TITLE
[Aio] An alternative way of making sync & async compatible

### PR DESCRIPTION
**Pull request by lidizheng**
Originated by Richard, that instead of spawning a background thread, we can only call sync objects in other threads. It seems working pretty well with relatively small amount of changes.

However, it does expose some issue with our custom IO manager. That I'm still debugging.

Let's see if tests are happy.

### CODE REVIEW

**Comment by lidizheng** [comment]
I'm observing performance boost with this PR??? This is unexpected (asyncio-to-asyncio):

```
I0302 18:45:39.665086592  164816 report.cc:82]               QPS: 25905.8
I0302 18:45:39.665138240  164816 report.cc:127]              Latencies (50/90/95/99/99.9%-ile): 4340.4/5765.7/11241.8/11883.8/13883.0 us
```

**Comment by lidizheng** [comment]
The only explanation might be that `asyncio.run_coroutine_threadsafe` is a lot faster than `create_task`.

**Comment by pfreixes** [comment]
Hi @lidizheng and @gnossen ... if we have that freedom of prescribing the users that if they want to use synchronous stack on top of the asynchronous one needs be done by using a separated thread, definitely this would make easier having compatibility between both stacks since we do not have to spawn a dedicated thread.

But I have some concerns/comments.

Eventually, we would need to check that whole sync stack, or at least a substantial part of it can be executed on top of `Aio`, following something similar to what was done here [1]. 

My concern is that, once we start testing the whole sync stack on top of Aio deadlocks might start appearing  - this needs to be double-checked since sync stack does not use CQ Callblack - because of `run_coroutine_threadsafe` usage. More info about why these deadlocks could appear in this comment [2].

Also, for making the integration good enough - so having a decent performance - you would need to implement the synchronization between the Asyncio thread and the synchronous thread. Otherwise, the `poll` [3] method would behave like a busy loop.

Regarding the boost performance, is this happening with Asyncio? Allow me to be a bit skeptic. I wouldn't attribute this to the usage of the  `run_coroutine_threadsafe` - unless I'm missing something - since this function would be used only for scheduling _coros_ from other threads, which in the use case of pure `Aio` environment should not happen. am I wrong? The only thing that Ive observed - again, I could be missing some details - that could be different is the attribute lookup for getting the loop [4] which in your proposal replaces the implementation by using a global variable that might be circumventing the usage of the Cython _getattr_ primitives that is applied to all `object` fields.


[1] https://github.com/grpc/grpc/pull/22076/files#diff-f4932b2c9567e7075b28bc8ddf591120R264
[2] https://github.com/grpc/grpc/pull/22076#issuecomment-593909082
[3] https://github.com/grpc/grpc/pull/22076/files#diff-a7e3f1791cea46394233f53c3a3f1972R211
[4] https://github.com/grpc/grpc/pull/22216/files#diff-0fe140df36d45de59f70c52194cc8d6aR64

**Comment by lidizheng** [comment]
Firstly, I apologize about the false performance improvement. Turns out my work station CPU core is way better than VM's, which contributed the entire 25% boost.

As predicted by @pfreixes, this approach proved to be no better than https://github.com/grpc/grpc/pull/22076. The sync-over-async stack crumbles in non-helloworld applications. The test I setup is creating multiple combinations of async / sync of servers and channels. During the process of debugging, I have learnt:

1. The challenge is Core's donated-thread model. Core invokes us through `run_loop`, however, it is difficult to get it work since we are crossing cpp / python and sync / asyncio world. The best known solution should be Pau's #22076 that releases GIL whenever we should.
2. Server shutdown path has a bug (https://github.com/grpc/grpc/pull/22234/commits/9bb61d396ff8369e08fcb059762e175800dae8d9).
3. Timer's implementation has a small issue under multi-threading environment.
4. Python's `logging` module has a global `RLock` that might livelock / deadlock.

I will close this PR.

**Pull request closed without merging**
