### PR TITLE
Add Findc-ares.cmake module

### PR DESCRIPTION
**Pull request by KyleFromKitware**
This is a CMake find-module, which attempts to find c-ares without
a CMake package file being available. If such a file is available,
it uses that. Otherwise, it searches for the library and include
directory manually.

Fixes: #14839

@jtattermusch

### CODE REVIEW

**Comment by jtattermusch** [comment]
How to we test this works correctly?

**Comment by KyleFromKitware** [comment]
> How to we test this works correctly?

Build and install a copy of c-ares with the `configure` script rather than CMake. This will not generate the needed CMake package files, thus ensuring that the find-module is working correctly.

**Comment by KyleFromKitware** [comment]
@zackgalbreath

**Comment by zackgalbreath** [comment]
@jtattermusch Would you like to see another distribtest to cover this method of finding c-ares?

**Comment by jtattermusch** [comment]
> @jtattermusch Would you like to see another distribtest to cover this method of finding c-ares?

I don't think we need to test this continuously as this is quite a niche use-case,

But it would be good to verify that if we remote the c-ares cmake installation here: https://github.com/grpc/grpc/blob/a02d6b9be81cbadb60eed88b3b44498ba27bcba9/test/distrib/cpp/run_distrib_test_cmake.sh#L26, things still pass.
We could also add a comment that  replacing the lines with sth. like `apt-get install c-ares`  should also work.

Also, this PR has conflicts. Can you please rebase?

**Comment by KyleFromKitware** [comment]
Rebased.

**Comment by KyleFromKitware** [comment]
Attempting to run `grpc/test/distrib/cpp/run_distrib_test_cmake.sh` (with the c-ares installation removed) on Debian Jessie fails since the version of c-ares on Jessie is not new enough (1.10). We should figure out the minimum version needed for gRPC and specify that in `find_package()`.

**Comment by jtattermusch** [comment]
Yes, the version is jessie is definitely too old.
Currently the c-ares submodule third-party/cares/cares is at 1.15.0, but it seems that we bumped from 1.13.0 mostly to overcome some build warnings (might not be a problem if we use pre-build package).

So I'd try to set the minimum c-ares version to 1.13.0.
Btw, debian buster (current stable) is at c-ares 1.14.0 so that would allow us to test nicely.

**Comment by KyleFromKitware** [comment]
> we bumped from 1.13.0 mostly to overcome some build warnings

OK, I will set it to 1.13.0 then.

**Comment by KyleFromKitware** [comment]
I just made some tweaks to `gRPCConfig.cmake` to use the new `Findc-ares.cmake` module. Local testing of the distrib test in Buster works with this setup, and local testing in Jessie fails early due to the outdated c-ares installation. (Note: the version of CMake shipped with Jessie is also too old for gRPC, but the distrib test looks like it's still written for Jessie. Perhaps it should be updated, but that is beyond the scope of this PR.)

I think this change is ready.

**Comment by jtattermusch** [comment]
distribtest error:
```
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find c-ares (missing: c-ares_INCLUDE_DIR c-ares_LIBRARY)
  (Required is at least version "1.13.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/Findc-ares.cmake:19 (find_package_handle_standard_args)
  cmake/cares.cmake:36 (find_package)
  CMakeLists.txt:150 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by KyleFromKitware** [comment]
@jtattermusch The distrib test failure is because c-ares' package export file is not providing version information. See c-ares/c-ares#296. I've added manual version checking to `Findc-ares.cmake` to support this until my PR gets merged.

**Comment by KyleFromKitware** [comment]
Local testing on the failed distrib test with the new version checking works.

**Comment by jtattermusch** [comment]
@apolcyn need another googler's LGTM.

**Comment by KyleFromKitware** [comment]
c-ares/c-ares#296 has now been merged.

**Pull request merged**
