### PR TITLE
cherry-pick #21641 #21277

### PR DESCRIPTION
**Pull request by JimmyCYJ**
Cherry-pick two STS bug fixes into 1.25
https://github.com/grpc/grpc/pull/21277
https://github.com/grpc/grpc/pull/21641

@donnadionne

### CODE REVIEW

**Comment by jtattermusch** [comment]
@JimmyCYJ 
Some findings about windows portability tests build only timeout:
- the test timeout is not happening on master, but this PR is against v1.25.x, which is relatively old (there is 1.26.x and 1.27.x now)
- I found that this PR https://github.com/grpc/grpc/pull/20900 has increased the timeout for windows C++ portability build, but the fix is not available in v1.25.x (it's only available in 1.26+)

So two possible solutions:
- it seems safe to mark this particular failure as "known flake on v1.25.x" and ignore it
- we could backport https://github.com/grpc/grpc/pull/20900 into v1.25.x

**Comment by jtattermusch** [comment]
A few more comments on the other test failures:
- the bazel C/C++ MacOS tests I wouldn't expect to work as support for bazel for mac was added after 1.25 release (so safe to ignore the failures)

- the interop test build failure seems to be due to java interop docker build failing, so probably safe to ignore (https://github.com/grpc/grpc/issues/21675)

- the artifact build failure (`fatal error: openssl/cmac.h: No such file or directory` on python manylinux1) I don't have much context, but it's worth doublechecking what's going on.

**Comment by jiangtaoli2016** [comment]
@jtattermusch Thanks much for looking into the test failures. Right now, merging is blocked on portability tests windows. 

@JimmyCYJ can backport #20900 in this PR if it can unblock merging.

**Comment by JimmyCYJ** [comment]
"I signed it"

**Comment by JimmyCYJ** [comment]
I signed it

**Comment by srini100** [comment]
What is the need to patch 1.25.x branch? We only patch last two releases which are 1.26.x and 1.27.x.

**Comment by srini100** [comment]
Checked that this change is needed for Envoy dependency. Based on above comments, tests failures are not due to this PR. Merging.

**Pull request merged**
