### PR TITLE
Add Node 1.11.3 and 1.12.4 to interop matrix

### PR DESCRIPTION
**Pull request by murgatroid99**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by murgatroid99** [comment]
Issues: #16041, #16042, #16043, #15752, and #16004.

**Pull request merged**
