### PR TITLE
Fix some instances of -Wunreachable-code-aggressive.

### PR DESCRIPTION
**Pull request by pkasting**
Bug: chromium:1066980

@nicolasnoble

### CODE REVIEW

**Comment by pkasting** [comment]
@nicolasnoble I see you're busy... is there another reviewer that can take this?  Alternatively, do you have time to stamp?  This should be trivial.  It would be nice to land it so we can roll it into Chromium downstream, though, as I'm trying to enable this warning there.

**Review by drfloob — APPROVED** [review]
LGTM, thanks for the cleanup! There is also a macro `GPR_UNREACHABLE_CODE`, which might be useful in situations that aren't as clear at this, where the compiler needs to see a return statement that we know is unreachable.

**Comment by pkasting** [comment]
Is there more I need to do in order for this to be committed?

**Comment by ctiller** [comment]
Can we add this warning to our build, to avoid continuously breaking chrome
folks in the future?

**Comment by drfloob** [comment]
I've just kicked our CI, it has had some challenges this week and didn't pick this PR up.

@ctiller I'll look into adding that warning next week if nobody beats me to it. Would you mind merging this when CI finishes?

**Comment by ctiller** [comment]
Just following up... @pkasting I'm getting curious about the kinds of bugs this warning is preventing

**Pull request merged**
