### PR TITLE
Make pretty interop test output graphs

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
+CC @jtattermusch

### CODE REVIEW

**Comment by dgquintas** [comment]
It there an example of the output handy? Also, it needs a remerge.

**Comment by carl-mastrangelo** [comment]
@dgquintas I rebased.

**Comment by carl-mastrangelo** [comment]
I updated the code to reraise the exception

**Comment by dgquintas** [comment]
Sigh... I've been rebuilding and jenkins always seems to fail for some reason. Giving it another go.

**Pull request merged**
