### PR TITLE
Move internals of many C++ Async classes to ref-counted struct

### PR DESCRIPTION
**Pull request by vjpai**
The purpose of this is to reduce the likelihood of races caused in the async code without changing the API. The current situation was that an async operation queued multiple entries on the core completion_queue, only some of which get delivered up to C++. If the entries are processed by different threads, a regular (as opposed to Sneaky) CallOpSet could successfully return control to the application thread from CompletionQueue::Next and thus allow the application to delete the Async class that it belongs to; meanwhile, one of the other (sneaky or regular) CallOpSets might still have work to do on a different thread and could have its object destructed before it is invoked.

### CODE REVIEW

**Comment by ctiller** [comment]
Would it be saner to restrict this refactoring to just those stream objects that also contain SneakyOps?

Justification:
- it's a much smaller diff
- it's going to be easier to refine that smaller diff to elide the allocation in the future
- we don't think it's necessary to take the extra allocation without a sneaky op?

**Comment by vjpai** [comment]
So, I was working with the idea that we should protect against any
situation where multiple CallOpSet's could be processed in parallel by
different threads. But I guess you are saying that in that situation (when
it's not Sneaky), the user already sees the CQ events for each of those
CallOpSet's and has to act on them. Is that correct?

**Comment by ctiller** [comment]
That's correct. And they're obliged to deal with them. I think this is only a problem when we don't show the user what's going on (to simplify API).

**Comment by vjpai** [comment]
ok, did that....

**Comment by ctiller** [comment]
Shouldn't `CallOpSet::FinalizeResult` call `SetCollection(nullptr)` to clear the reference cycle once the op is done?

**Comment by vjpai** [comment]
You're right. I was thinking that most of our accesses had "delete this" on them, but that's not for these struct's at all. Yes, we need to drop the ref ourselves.

**Comment by vjpai** [comment]
I believe that this is ready to review

**Comment by vjpai** [comment]
... and I believe that all affected test (C++) pass.

**Comment by ctiller** [comment]
LGTM

**Comment by nicolasnoble** [comment]
Green enough to merge ?

**Pull request merged**
