### PR TITLE
Perform secure naming checks in grpclb_end2end_test

### PR DESCRIPTION
**Pull request by dgquintas**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/14507)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by markdroth** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/lib/security/security_connector/security_connector.cc, line 467 at r1](https://reviewable.io:443/reviews/grpc/grpc/14507#-L62ikyJyxWuzYiVXmMw:-L62ikyJyxWuzYiVXmMx:b-8xn5ou) ([raw file](https://github.com/grpc/grpc/blob/c2377961383704c3c66ef9a00d94522f253ce219/src/core/lib/security/security_connector/security_connector.cc#L467)):*
> ```cpp
>       reinterpret_cast<grpc_fake_channel_security_connector*>(sc);
>   if (c->is_lb_channel) {
>     // TODO(dgq): verify that the host (ie, authority header) matches that of
> ```

We should probably verify that the authority header is set correctly in both the balancer and backend cases.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 61 at r1](https://reviewable.io:443/reviews/grpc/grpc/14507#-L62jgNeWeN6eeQnk9aC:-L62jgNeWeN6eeQnk9aD:b-3n5t9n) ([raw file](https://github.com/grpc/grpc/blob/a90d718cb89414bfe5f6cfaa69a1b3716ed55d5f/test/cpp/end2end/grpclb_end2end_test.cc#L61)):*
> ```cpp
> //   serverlist with non-existent backends after having initially returned a
> //   valid one.
> // - test using secure credentials and make sure we don't send call
> ```

I don't see where we're actually checking that we aren't sending the call credentials to the balancer.  Don't we need the credentials to add some metadata to the call and then somehow check that that metadata is present on the backend call but not on the balancer call?

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 391 at r1](https://reviewable.io:443/reviews/grpc/grpc/14507#-L62lrpg07rc80nN-Jtj:-L62lrpg07rc80nN-Jtk:b-hm7puz) ([raw file](https://github.com/grpc/grpc/blob/c2377961383704c3c66ef9a00d94522f253ce219/test/cpp/end2end/grpclb_end2end_test.cc#L391)):*
> ```cpp
>                     response_generator_.get());
>     if (!expected_targets.empty()) {
>       args.SetString(GRPC_ARG_FAKE_SECURITY_EXPECTED_TARGETS, expected_targets);
> ```

Don't the fake credentials require this to be set?  If so, why aren't all of the existing tests failing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14507)*

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/lib/security/security_connector/security_connector.cc, line 467 at r1](https://reviewable.io:443/reviews/grpc/grpc/14507#-L62ikyJyxWuzYiVXmMw:-L62oFerw-b9at3HTjsG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c2377961383704c3c66ef9a00d94522f253ce219/src/core/lib/security/security_connector/security_connector.cc#L467)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should probably verify that the authority header is set correctly in both the balancer and backend cases.
</blockquote></details>

Done.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 61 at r1](https://reviewable.io:443/reviews/grpc/grpc/14507#-L62jgNeWeN6eeQnk9aC:-L63dVT2GwkhLBGFTzA8:b-ovhgbu) ([raw file](https://github.com/grpc/grpc/blob/a90d718cb89414bfe5f6cfaa69a1b3716ed55d5f/test/cpp/end2end/grpclb_end2end_test.cc#L61)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't see where we're actually checking that we aren't sending the call credentials to the balancer.  Don't we need the credentials to add some metadata to the call and then somehow check that that metadata is present on the backend call but not on the balancer call?
</blockquote></details>

True, that has never been tested. After trying for a while, I've restored the TODO. I don't have cycles to do this right now, and lack of familiarity with this part of the code prevents me from doing it quickly enough while having other more pressing tasks in the pipeline.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 391 at r1](https://reviewable.io:443/reviews/grpc/grpc/14507#-L62lrpg07rc80nN-Jtj:-L62neIsCzGOn8oyzmgb:b-cieca7) ([raw file](https://github.com/grpc/grpc/blob/c2377961383704c3c66ef9a00d94522f253ce219/test/cpp/end2end/grpclb_end2end_test.cc#L391)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't the fake credentials require this to be set?  If so, why aren't all of the existing tests failing?
</blockquote></details>

If it's not set, the check is not performed: https://github.com/grpc/grpc/blob/9b32d9c4f38a8a81bbbff8f9217d3032573c4ce5/src/core/lib/security/security_connector/security_connector.cc#L341

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14507)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 650 at r2](https://beta.reviewable.io/reviews/grpc/grpc/14507#-L6Jnhli4hJxa_OE1ZpQ:-L6Jnhli4hJxa_OE1ZpR:b-rbgtj8) ([raw file](https://github.com/grpc/grpc/blob/80a77a74b21301b45095d47e6dfd8a4ef1b60836/test/cpp/end2end/grpclb_end2end_test.cc#L650)):*
> ```cpp
> }
> 
> TEST_F(SingleBalancerTest, SecureNaming) {
> ```

To make sure the secure naming check is working, we should add a test that will fail the check?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/grpc/grpc/14507)*

**Comment by AspirinSJL** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/grpc/grpc/14507)*

**Comment by dgquintas** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 650 at r2](https://beta.reviewable.io/reviews/grpc/grpc/14507#-L6Jnhli4hJxa_OE1ZpQ:-L6NDCmsCD3SgFcBwChq:ba7l43h) ([raw file](https://github.com/grpc/grpc/blob/80a77a74b21301b45095d47e6dfd8a4ef1b60836/test/cpp/end2end/grpclb_end2end_test.cc#L650)):*
<details><summary><i>Previously, AspirinSJL (Juanli Shen) wrote…</i></summary><blockquote>

To make sure the secure naming check is working, we should add a test that will fail the check?
</blockquote></details>

I tried doing a [death test](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#death-tests) but given the complicated way in which do things, the gtest framework is unable to properly capture the `abort()` that happens when the secure naming check fails.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/grpc/grpc/14507)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by dgquintas** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 650 at r2](https://reviewable.io:443/reviews/grpc/grpc/14507#-L6Jnhli4hJxa_OE1ZpQ:-L6NIm_JfKnhmQ2OevRz:bl0t64p) ([raw file](https://github.com/grpc/grpc/blob/80a77a74b21301b45095d47e6dfd8a4ef1b60836/test/cpp/end2end/grpclb_end2end_test.cc#L650)):*
<details><summary><i>Previously, dgquintas (David G. Quintas) wrote…</i></summary><blockquote>

I tried doing a [death test](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#death-tests) but given the complicated way in which do things, the gtest framework is unable to properly capture the `abort()` that happens when the secure naming check fails.
</blockquote></details>

ACTUALLY, I take that back :) I found a way and added the death test. Good idea! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14507)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by AspirinSJL** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 650 at r2](https://beta.reviewable.io/reviews/grpc/grpc/14507#-L6Jnhli4hJxa_OE1ZpQ:-L6NMW8aCEqlQbeigsYV:bccpe83) ([raw file](https://github.com/grpc/grpc/blob/80a77a74b21301b45095d47e6dfd8a4ef1b60836/test/cpp/end2end/grpclb_end2end_test.cc#L650)):*
<details><summary><i>Previously, dgquintas (David G. Quintas) wrote…</i></summary><blockquote>

ACTUALLY, I take that back :) I found a way and added the death test. Good idea! 
</blockquote></details>

Awesome!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/grpc/grpc/14507)*

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
