### PR TITLE
Fix oss-fuzz/961

### PR DESCRIPTION
**Pull request by dgquintas**
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=961

### CODE REVIEW

**Comment by kcc** [comment]
please consider adding a test, or adding the buggy input to the fuzzer corpus, or both.

**Comment by dgquintas** [comment]
@kcc ugh yes. I remembered right after the push but the amended commit didn't go...

**Comment by dgquintas** [comment]
@makdharma would you mind adding a more explicit (human readable) test to exercise this path?

**Comment by dgquintas** [comment]
@yang-g yes, thanks. Done.

**Comment by yang-g** [comment]
LGTM
squash?

**Comment by dgquintas** [comment]
Failures: https://github.com/grpc/grpc/issues/10199

**Pull request merged**
