### PR TITLE
Refactor verify_peer_callback to support asynchronous return.

### PR DESCRIPTION
**Pull request by JackOfMostTrades**
@markdroth Following up on the PR comments from [here](https://github.com/grpc/grpc/pull/12656#discussion_r206392973), refactoring the c-core API for verify_peer_callback to support an asynchronous callback.

This pretty closely models off of the existing get_metadata plugin code, so I don't think there's too many surprises. @markdroth did mention that we should aim to properly support cancellation from the get-go, but it wasn't really clear to me what this should look like here (there doesn't look to be any code here that anticipates needing to cancel the `ssl_channel_check_peer` call).

### CODE REVIEW

**Comment by markdroth** [comment]
I haven't yet had a chance to look at this code, but I do have a few high-level comments.

First, it turns out that we actually have a policy of requiring a gRFC for core API changes:

https://github.com/grpc/proposal/blob/master/P3-grfcs-for-core-api-changes.md

I wasn't aware of this until recently, or I would have pointed it out before you made the original verify_peer API change.  So we should probably go ahead and put together a gRFC here, not just for the change in this PR but also for the verify_peer API as a whole (i.e., including both this change and the original one).

Second, please sync with @yihuazhang, who is currently working on a design for SPIFFE credentials that introduces a couple of cancellable application call-outs similar to this one.  I believe he is proposing to introduce some helper code to handle the semantics of the application call-out use case correctly, and we should try to reuse that code here.

Third, responding to this comment:

> @markdroth did mention that we should aim to properly support cancellation from the get-go, but it wasn't really clear to me what this should look like here (there doesn't look to be any code here that anticipates needing to cancel the `ssl_channel_check_peer` call).

I suspect this is another case similar to the metadata plugin credentials where we simply failed to think about the need for cancellation when we originally designed the APIs.  The `check_peer` call should in principle be cancelled whenever the security handshaker shuts down.  As part of this PR, we should fix the security handshaker to cancel the call when the handshaker is shut down.

**Comment by yihuazhang** [comment]
I am currently working on the design of supporting SPIFFE in gRPC auth stack which contains a general mechanism to support application call-out use case, and I think it will be ready for gRFC review by the end of this week. 

Does your use case require HTTPS or SPIFFE-based SSL implementation? if it is SPIFFE-based, my current SPIFFE design may also be useful in your use case.

**Comment by JackOfMostTrades** [comment]
@yihuazhang Our use-case is similar to SPIFFE but predates it just slightly and is a bit different in the details (similarly we have a non-DNS notion of identity we want to verify, but ours is based on a set of custom X509 extensions rather than a URI SAN). But I suspect that some of what you're putting together could be used for this general verification callback. I don't think I'll be able to do more work on this PR this week anyway, so I'll check out what you're putting together for SPIFFE once you have it ready.

**Comment by jiangtaoli2016** [comment]
@JackOfMostTrades If I understand correctly, your use case is workload-to-workload mTLS authentication. We are going to refactor grpc SSL credentials into two types: https SSL credentials and SPIFFE credentials (not strictly SPIFFE, but should also support your use case and similar other mTLS use cases). @yihuazhang is driving that effort. More details coming soon.

**Comment by JackOfMostTrades** [comment]
> If I understand correctly, your use case is workload-to-workload mTLS authentication.
Yes, that's exactly correct.
> not strictly SPIFFE, but should also support your use case and similar other mTLS use cases
That sounds great! I'll stay tuned!

**Comment by yihuazhang** [comment]
@JackOfMostTrades 

I drafted a gRFC (https://github.com/grpc/proposal/pull/98) that has all the details we discussed before. Could you please take a look (i.e., server_authorization_check) and see if the API is implementable to meet your needs?

**Pull request closed without merging**
