### PR TITLE
Expose Trailers-Only responses via C core API.

### PR DESCRIPTION
**Pull request by markdroth**
I ran into one problem here, which is that the existing `trailing_metadata_available` field in `grpc_transport_stream_op_batch` was `bool`, but we can't use `bool` in the C core API due to the C89 restriction.  I didn't want to add unnecessary memory usage in surface/call.cc by saving the original pointer in the call and setting it based on the result from the call stack.  And I don't think casting is safe due to strict aliasing issues.  So, to work around this, I changed the type in `grpc_transport_stream_op_batch` to `uint8_t`, which is what I'm using in the C core API.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]    -128  -0.0%

  [ = ]       0 TOTAL     -128  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +120  +0.0%

  [ = ]       0 TOTAL     +120  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by markdroth** [comment]
As we discussed, it won't actually be set to 1 in the streaming case, because it only comes back as part of the recv_initial_metadata op.  But I've added a test that it is not set in a case where there is not a Trailers-Only response.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]    -128  -0.0%

  [ = ]       0 TOTAL     -128  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +120  +0.0%

  [ = ]       0 TOTAL     +120  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__8.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__2097152.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinUDS__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__512.counters.new: 5
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__32768.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__32768.counters.new: 5
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_TCP_NoOpMutator_NoOpMutator__0_0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__16777216.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__262144.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinSockPair__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__64.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__134217728.opt.new: 3
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__1.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__16777216.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__32768.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__64.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinUDS__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__134217728.opt.new: 8
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__512.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__64.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__1.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinTCP__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__4096.counters.new: 5
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__8.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__8.counters.new: 10
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__0_0.opt.new: 6
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__262144.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__4096.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__1.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__2097152.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__262144.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__4096.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__32768.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__262144.counters.new: 5
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__32768.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__1.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__512.counters.new: 5
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_MinTCP_NoOpMutator_NoOpMutator__0_0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__8.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__512.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__134217728.opt.new: 3
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__64.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__512.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__2097152.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__1.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__4096.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__262144.opt.new: 10
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_InProcessCHTTP2_NoOpMutator_NoOpMutator__0_0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__8.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__64.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__262144.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__64.counters.new: 2
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__16777216.opt.new: 9
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__4096.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__1.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinTCP__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinSockPair__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__512.counters.new: 1
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__8.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__4096.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__32768.counters.new: 3


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__8.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__4096.counters.new: 2
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinUDS__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__512.counters.new: 3
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__32768.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__64.counters.new: 1
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__16777216.opt.new: 10
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_TCP_NoOpMutator_NoOpMutator__0_0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__16777216.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__262144.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinSockPair__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__32768.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__262144.counters.new: 5
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__1.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__16777216.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__32768.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__2097152.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__64.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinUDS__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__134217728.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__512.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__64.counters.new: 3
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__1.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinTCP__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__8.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__8.counters.new: 10
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__0_0.opt.new: 8
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__262144.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__4096.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__1.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__2097152.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__262144.counters.new: 3
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__4096.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__32768.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__1.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__512.counters.new: 3
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_MinTCP_NoOpMutator_NoOpMutator__0_0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__8.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__512.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__134217728.opt.new: 6
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__64.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__512.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__2097152.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__1.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__4096.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__262144.opt.new: 10
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPong_InProcessCHTTP2_NoOpMutator_NoOpMutator__0_0.opt.new: 9
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__8.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__64.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__262144.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__64.counters.new: 1
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_UDS__32768.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__4096.counters.new: 3
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__1.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinTCP__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_MinSockPair__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__512.counters.new: 2
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__8.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__0.counters.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_TCP__0.opt.new: 10
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__4096.counters.new: 3
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__32768.counters.new: 4
    bm_fullstack_streaming_pump.BM_PumpStreamClientToServer_SockPair__134217728.opt.new: 3


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++
  +0.8%     +96 src/core/ext/transport/inproc/inproc_transport.cc      +96  +0.8%
      +1.3%     +39 op_state_machine                                       +39  +1.3%
      +2.3%     +32 fail_helper_locked                                     +32  +2.3%
      +0.7%     +16 perform_stream_op                                      +16  +0.7%
      +4.3%      +9 [Unmapped]                                              +9  +4.3%
  +0.2%     +16 src/core/ext/transport/chttp2/transport/parsing.cc     +16  +0.2%
       +12%      +8 [Unmapped]                                              +8   +12%
      +0.6%      +8 init_header_frame_parser                                +8  +0.6%
  +0.1%     +16 src/core/lib/surface/call.cc                           +16  +0.1%
      +0.5%     +16 call_start_batch                                       +16  +0.5%

 -------------- SHRINKING                                          --------------
  [ = ]       0 [None]                                                -520  -0.0%

  +0.0%    +128 TOTAL                                                 -392  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +120  +0.0%

  [ = ]       0 TOTAL     +120  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++
  +0.8%     +96 src/core/ext/transport/inproc/inproc_transport.cc      +96  +0.8%
      +1.6%     +47 op_state_machine                                       +47  +1.6%
      +2.3%     +32 fail_helper_locked                                     +32  +2.3%
      +0.7%     +16 perform_stream_op                                      +16  +0.7%
      +0.5%      +1 [Unmapped]                                              +1  +0.5%
  +0.2%     +16 src/core/ext/transport/chttp2/transport/parsing.cc     +16  +0.2%
      +1.2%     +16 init_header_frame_parser                               +16  +1.2%
  +0.1%     +16 src/core/lib/surface/call.cc                           +16  +0.1%
      +0.5%     +16 call_start_batch                                       +16  +0.5%

 -------------- SHRINKING                                          --------------
  [ = ]       0 [None]                                                -392  -0.0%

  +0.0%    +128 TOTAL                                                 -264  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +120  +0.0%

  [ = ]       0 TOTAL     +120  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++
  +0.8%     +96 src/core/ext/transport/inproc/inproc_transport.cc      +96  +0.8%
      +1.6%     +47 op_state_machine                                       +47  +1.6%
      +2.3%     +32 fail_helper_locked                                     +32  +2.3%
      +0.7%     +16 perform_stream_op                                      +16  +0.7%
      +0.5%      +1 [Unmapped]                                              +1  +0.5%
  +0.2%     +16 src/core/ext/transport/chttp2/transport/parsing.cc     +16  +0.2%
      +1.2%     +16 init_header_frame_parser                               +16  +1.2%
  +0.1%     +16 src/core/lib/surface/call.cc                           +16  +0.1%
      +0.5%     +16 call_start_batch                                       +16  +0.5%

 -------------- SHRINKING                                          --------------
  [ = ]       0 [None]                                                -496  -0.0%

  +0.0%    +128 TOTAL                                                 -368  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -80  -0.0%

  [ = ]       0 TOTAL      -80  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++
  +0.8%     +96 src/core/ext/transport/inproc/inproc_transport.cc      +96  +0.8%
      +1.6%     +47 op_state_machine                                       +47  +1.6%
      +2.3%     +32 fail_helper_locked                                     +32  +2.3%
      +0.7%     +16 perform_stream_op                                      +16  +0.7%
      +0.5%      +1 [Unmapped]                                              +1  +0.5%
  +0.2%     +16 src/core/ext/transport/chttp2/transport/parsing.cc     +16  +0.2%
      +1.2%     +16 init_header_frame_parser                               +16  +1.2%
  +0.1%     +16 src/core/lib/surface/call.cc                           +16  +0.1%
      +0.5%     +16 call_start_batch                                       +16  +0.5%

 -------------- SHRINKING                                          --------------
  [ = ]       0 [None]                                                -496  -0.0%

  +0.0%    +128 TOTAL                                                 -368  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.2%     +32 src/cpp/client/generic_stub.cc                                                           +32  +0.2%
      +3.4%      +8 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +8  +3.4%
      +5.1%      +8 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +8  +5.1%
      +4.4%      +8 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +8  +4.4%
      +8.0%      +8 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +8  +8.0%

 -------------- SHRINKING                                                                            --------------
  [ = ]       0 [None]                                                                                   -96  -0.0%

  +0.0%     +32 TOTAL                                                                                    -64  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++
  +0.8%     +96 src/core/ext/transport/inproc/inproc_transport.cc      +96  +0.8%
      +1.6%     +47 op_state_machine                                       +47  +1.6%
      +2.3%     +32 fail_helper_locked                                     +32  +2.3%
      +0.7%     +16 perform_stream_op                                      +16  +0.7%
      +0.5%      +1 [Unmapped]                                              +1  +0.5%
  +0.2%     +16 src/core/ext/transport/chttp2/transport/parsing.cc     +16  +0.2%
      +1.2%     +16 init_header_frame_parser                               +16  +1.2%
  +0.1%     +16 src/core/lib/surface/call.cc                           +16  +0.1%
      +0.5%     +16 call_start_batch                                       +16  +0.5%

 -------------- SHRINKING                                          --------------
  [ = ]       0 [None]                                                -496  -0.0%

  +0.0%    +128 TOTAL                                                 -368  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.2%     +32 src/cpp/client/generic_stub.cc                                                           +32  +0.2%
      +3.4%      +8 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +8  +3.4%
      +5.1%      +8 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +8  +5.1%
      +4.4%      +8 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +8  +4.4%
      +8.0%      +8 grpc::internal::CallOpSet<grpc::internal::CallOpRecvInitialMetadata, grpc::internal:      +8  +8.0%

 -------------- SHRINKING                                                                            --------------
  [ = ]       0 [None]                                                                                   -96  -0.0%

  +0.0%     +32 TOTAL                                                                                    -64  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Setting this aside for now, as per discussion with @ctiller.  We will instead do some experiments to see if it's sufficient to have the transport treat an initial headers frame followed immediately by a trailing headers frame the same as a Trailers-Only response.

**Pull request closed without merging**
