### PR TITLE
WIP: Add a gcc-8.1 portability test for c and make it pass

### PR DESCRIPTION
**Pull request by apolcyn**
Fixes https://github.com/grpc/grpc/issues/15520 and https://github.com/grpc/grpc/issues/15534, but leaves some TODO's

The c-ares compilation in the issue is the first error that appears when compiling with gcc 8, but there's also one in borginssl, and several in core. This PR just suppresses those warnings so that the added test here passes so that:

```
tools/run_tests/run_tests.py -l c --build_only --compiler gcc8.1
```

passes off of this PR.

We might want to fix some of the warnings in source, but this shows the issues, as a starting point.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
I see lots of test error.

**Comment by apolcyn** [comment]
Sorry, I should have put a WIP on this (the change to test matrix isn't correct yet and the docker image isn't uploaded).

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by eugeny-stoyka** [comment]
i add in makefile `-Wno-class-memaccess` , `-Wno-ignored-qualifiers`and `-Wno-stringop-truncation` in CPPFLAGS for suppressing this issues while build.

**Comment by kaelzhang** [comment]
Any updates?

I encountered an issue of protobuf.js and I want to upgrade the module to the latest and rebuild grpc for myself.

And the master could not be built.

```sh
$ cc --version

Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
```

**Comment by DexHunter** [comment]
Hi! Any updates on this PR? I was wondering if changing `grpc.gyp` and add CPPFLAGS there would be enough for a successful build? Thanks.

```
$ cc --version
cc (GCC) 8.2.1 20180831
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Sexual** [comment]
Any updates regarding this? Can't use GRPC and Alpine 3.9.

**Comment by jtattermusch** [comment]
@apolcyn  can we revive this? We still need gcc8.1 build to work.

**Pull request closed without merging**
