### PR TITLE
Fix header file import for latest ProtoBuf in grpcio-tools

### PR DESCRIPTION
**Pull request by lidizheng**
Fixes https://github.com/grpc/grpc/issues/29338.

### CODE REVIEW

**Comment by lidizheng** [comment]
Triggered prod:grpc/core/master/linux/grpc_build_protobuf_at_head
* http://sponge/64ab4e1f-68c9-4acf-8ecc-099b0440e224

**Comment by jtattermusch** [comment]
Well, as is, this would break build against the current version of third_party/protobuf submodule.
```
grpc_tools/main.cc:27:10: fatal error: google/protobuf/compiler/python/generator.h: No such file or directory
```

Actually, the situation is quite bad, since it seems that protobuf has recently renamed lots of their public headers.
E.g. see https://github.com/protocolbuffers/protobuf/pull/9669/files#diff-0dd62c8d5a58dc167544764d463de9e6129568f09bbe20145f6ab7d4632f6608R111

And it's not just about python, other languages would likely suffer from a similar problem:
https://github.com/protocolbuffers/protobuf/pull/9669/files#diff-deef97e4c58bafd49f04825aa86dcc91ee390d5d23d041c3d7ccb9d4529ee72b

**Comment by lidizheng** [comment]
I'm planning to update the ProtoBuf submodule again, and try to fix breakages. I see ProtoBuf pushed packages to various package management plaforms (like PyPI), it might be harder to yank all that.

The ProtoBuf build at head job is failing constantly for at least 2 weeks (around the mentioned commit). We might want to dig into why this didn't raise an alarm for both teams. https://screenshot.googleplex.com/Ahybmk6DF5WkTtG

**Comment by lidizheng** [comment]
Updating ProtoBuf is blocked by another issue: https://github.com/grpc/grpc/issues/29297.

**Comment by lidizheng** [comment]
We probably need to figure out who should fix the issue first.

**Pull request closed without merging**
