### PR TITLE
Backport bazel changes from #13468 to 1.8.x

### PR DESCRIPTION
**Pull request by apolcyn**
This can allow consuming grpc with bazel on 1.8.x with the new simpler setup that was initially proposed in https://github.com/grpc/grpc/pull/13468

There were a couple of manual merge conflicts unnoticed by git that are addressed in the most recent commit here (needed to remove references to a couple of things that only exist in master branch, like bazel toolchains).

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
Not merging right now, I think the fix for #13862 needs to be backported as well

**Comment by apolcyn** [comment]
will merge now that https://github.com/grpc/grpc/pull/13863 has been merged

**Comment by apolcyn** [comment]
* basic tests c++: https://github.com/grpc/grpc/issues/13080 (fixed on master)
* basic tests multi-lang linux: https://github.com/grpc/grpc/issues/13272 (fixed on master), https://github.com/grpc/grpc/issues/13848
* basic tests windows: https://github.com/grpc/grpc/issues/12748, https://github.com/grpc/grpc/issues/13845
tsan c: https://github.com/grpc/grpc/issues/13124 (fixed on master)

tsan c++: https://github.com/grpc/grpc/issues/13148., https://github.com/grpc/grpc/issues/12510, https://github.com/grpc/grpc/issues/13381

**Pull request merged**
