### PR TITLE
Completion Queue creation API changes (C-Core and C++ only)

### PR DESCRIPTION
**Pull request by sreecha**
This is the initial pull request for `grpc_completion_queue_create` changes as listed in the gRFC https://github.com/grpc/proposal/pull/6 . These were the minimum set of changes I could make to get this to compile and for tests (C/C++) to pass :) [Note: This has all the API changes needed. Its just that I resisted the temptation to implement a bit more functionality]

**Changes in this PR**
- Breaking change to the `grpc_completion_queue_create` API in C-Core
- Added _asserts_ in `grpc_completion_queue_next` and `grpc_completion_queue_pluck` to make sure they are called on the completion queues with correct `grpc_cq_completion_type`
- Did *not* make any other functionality changes in core (like for example not creating a pollset if `grpc_cq_polling_type` is `NON_POLLING`). This will happen in a separate PR 

- No changes to the C++ user-facing API. These will happen in later PRs (when I work on hybrid servers). The main change in C++ was to make sure that completion queues created for `Call`s were of `GRPC_CQ_PLUCK` type and all other completion queues were of `GRPC_CQ_NEXT` type (the polling type for all these queues is `DEFAULT_POLLING`). Will make more changes later.

**Changes in other wrapped languages**
- Python: https://github.com/sreecha/grpc/pull/4
- Node, Ruby and Objective-C: https://github.com/sreecha/grpc/pull/5
- PHP: https://github.com/sreecha/grpc/pull/6
- C#: https://github.com/sreecha/grpc/pull/7

----
**UPDATE**
Update on 3/22/2017: Pulled in the changes from https://github.com/grpc/grpc/pull/10245 as well.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/9972)

### CODE REVIEW

**Comment by ctiller** [comment]
I like the idea of prefixing the enum names.

**Comment by sreecha** [comment]
@murgatroid99 and @muxi: Can you please take a look at this PR ?  https://github.com/sreecha/grpc/pull/4 
(Muxi for objective C changes and Michael for Ruby and Node)
If everything looks good, I'll merge that with this current PR

@kpayson64 , can you please take a look at Python changes here: https://github.com/sreecha/grpc/pull/5

**Comment by sreecha** [comment]
@stanley-cheung : Can you please take a look at the PR here: https://github.com/sreecha/grpc/pull/6 ?

**Comment by sreecha** [comment]
@ctiller : This PR is now updated to use `grpc_completion_queue_factory` to create completion queues.
I also changed all languages. PTAL

**Comment by sreecha** [comment]
Fixed the ASAN failure.

**Comment by sreecha** [comment]
Fixed C-asan errors too (after latest merge).

**Comment by sreecha** [comment]
Known failures:
**Basic Tests mac** : https://github.com/grpc/grpc/issues/10202
**The Bazel full Build & Tests**: We are ignoring these failures for now (until all the targets fully move to bazel)

**Comment by ctiller** [comment]
Note: if the PR isn't assigned to me, I'm unlikely to see it on my daily rounds.

**Comment by sreecha** [comment]
Interop failures and bazel failures are known

**Pull request merged**
