### PR TITLE
AWSCredentials: fix interaction with metadata server

### PR DESCRIPTION
**Pull request by clundin25**
* No need to call metadata server if environment variables are set.
* AWS_SESSION_TOKEN is optional.

### CODE REVIEW

**Comment by clundin25** [comment]
cc: @lsirac

**Review by markdroth — APPROVED** [review]
Looks good.  I've triggered the tests, let's see how they look.

**Comment by markdroth** [comment]
The ASAN failure looks unrelated, but please address the clang-tidy and clang-format failures.

**Comment by clundin25** [comment]
Thanks for the review @markdroth ! I've addressed the tidy & format errors.

I was unable to run the clang tidy script locally, so will wait to see if it passes in the CI.

**Comment by markdroth** [comment]
I'll trigger the tests again.

For future reference, please don't force-push once a review has started, since that makes it impossible for the reviewer to see what's changed since their last review pass.  Thanks!

**Comment by markdroth** [comment]
Looks like there are some memory leaks in the test.

**Comment by clundin25** [comment]
@markdroth ACK. Trying to setup this check locally.

**Comment by clundin25** [comment]
@markdroth I've fixed the sanitizer complaints locally, so hopefully this should now pass CI.

I did notice an error in the logic, so fixed that as well.

Thanks for the review!

**Comment by markdroth** [comment]
I've triggered the tests again.  Let's see how they look.

**Pull request merged**
