### PR TITLE
[TSI] Print cert verification status on handshake failure

### PR DESCRIPTION
**Pull request by csapuntz**
Certificate verification can fail for more than 50 different reasons. Simplify troubleshooting by including the reason in the error message.

### CODE REVIEW

**Comment by erm-g** [comment]
Hello @csapuntz and thank you for the PR! Could you add tests covering this new code?

**Comment by csapuntz** [comment]
> Hello @csapuntz and thank you for the PR! Could you add tests covering this new code?

Appreciate the welcome and the thank you! Thank you for gRPC and all of the hard work that went into it.

The following test case should covers this code path:

```
ssl_transport_security_test.cc:TEST_P(SslTransportSecurityTest, DoHandshakeWithBadServerCert) {
```

The test passes with the changes in this PR.

To make sure, I added an `exit(1)` to the inside of the if statement I added and ran `bazel test //test/core/tsi:ssl_transport_security_test` and testing failed at DoHandshakeWithBadServerCert.

Do you think adding an addition test is still required given the existing coverage?

**Comment by csapuntz** [comment]
Another friendly ping. I believe the existing test coverage covers this new code. Please see comment above.

**Review by matthewstevenson88 — APPROVED** [review]
Thanks for the PR! This is a great change.

**Comment by matthewstevenson88** [comment]
@csapuntz It looks like there are a few test failures, could you address these and just tag me when ready and I can re-trigger the presubmits?

**Comment by csapuntz** [comment]
@matthewstevenson88 I did a couple things (updated my branch, rebased, pushed) and now can't find the test results from the run.

I fixed a couple issues but I'm not sure I addressed all of them nor do I know how to kick off a new round of testing. Grateful for any guidance.

**Comment by matthewstevenson88** [comment]
Basic Tests ObjC Examples, Basic Tests PHP MacOS, and Bazel RBE Windows Opt C/C++ look like an unrelated flakes. I'll retrigger the tests to confirm.

To resolve the Sanity Checks failure, you can run `tools/distrib/clang_format_code.sh` from the top-level directory.

**Comment by csapuntz** [comment]
@matthewstevenson88 I believe I have resolved the sanity test issue.

**Review by matthewstevenson88 — APPROVED** [review]

**Review by eugeneo — APPROVED** [review]

**Pull request closed without merging**
