### PR TITLE
Check for tracing variables before logging info statements

### PR DESCRIPTION
**Pull request by yashykt**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,980,683      Total (>)      1,980,675

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,811,759      Total (<)     10,811,761

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,980,695      Total (>)      1,980,675

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,811,772      Total (>)     10,811,764

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
This message was intended to be logged for all clients, not just when the client_channel tracer is enabled.  It reflects a possible misconfiguration and is something users may want to know about.

**Comment by yashykt** [comment]
@markdroth should that be switched to GPR_ERROR then?

**Comment by markdroth** [comment]
I don't think it needs to be.  It's a possible misconfiguration, not a definite one.

**Comment by AspirinSJL** [comment]
@markdroth Why is that a possible one?

**Comment by markdroth** [comment]
Because some environments may intentionally configure something like round_robin via the service config with the intention that it will be used only when the resolver does not return any balancer addresses.

**Comment by AspirinSJL** [comment]
Makes sense. Closing the PR.

**Pull request closed without merging**
