### PR TITLE
C++11: Support compat with 1.0.x generated PB files

### LINKED ISSUE #8772: Move to C++11 and outdated protoc plugins
So issue #8754 (which I've closed since that reporter is now ok) brings up the issue that people with protoc plugins installed before #8602 but more recent gRPC headers are in a pickle - namely that the current headers no longer recognize GRPC_OVERRIDE and GRPC_FINAL generated by the old plugins. The solution is to fully reinstall gRPC, which will automatically reset the plugins. Is there any desire to allow users to keep their outdated protoc plugins? If so, we should add those macros back to our headers but keep in mind that they are deprecated so that we never generate any new code that uses them. In my view, we should not do this as it leaves scope for error, and the better option is to just tell users to reinstall the plugins if they update gRPC. We should either fix this for 1.1 or decide that the current behavior is WAI and leave it alone. I vote for the latter, but let's see what the electoral college decides.

### PR DESCRIPTION
**Pull request by vjpai**
Add back a few macros that were used in old generated PB files pre-#8602.
Fixes #8772

### CODE REVIEW

**Comment by vjpai** [comment]
Fixes #8772

**Comment by vjpai** [comment]
Jenkins, test this please.

**Comment by ctiller** [comment]
List of failing tests?

**Comment by vjpai** [comment]
# Currently failing tests:
## From Bazel Build&Test
//test/core/bad_ssl:bad_ssl_alpn_server                                  FAILED in 0.3s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/grpc/bazel-out/local-fastbuild/testlogs/test/core/bad_ssl/bad_ssl_alpn_server/test.log
//test/core/bad_ssl:bad_ssl_cert_server                                  FAILED in 0.3s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/grpc/bazel-out/local-fastbuild/testlogs/test/core/bad_ssl/bad_ssl_cert_server/test.log
//test/core/end2end:h2_fd_test@ping                                      FAILED in 0.1s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/grpc/bazel-out/local-fastbuild/testlogs/test/core/end2end/h2_fd_test@ping/test.log
//test/core/end2end:h2_proxy_test@compressed_payload                     FAILED in 0.1s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/grpc/bazel-out/local-fastbuild/testlogs/test/core/end2end/h2_proxy_test@compressed_payload/test.log
//test/core/end2end:h2_sockpair_1byte_test@ping                          FAILED in 0.1s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/grpc/bazel-out/local-fastbuild/testlogs/test/core/end2end/h2_sockpair_1byte_test@ping/test.log
//test/core/end2end:h2_sockpair_test@ping                                FAILED in 0.1s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/grpc/bazel-out/local-fastbuild/testlogs/test/core/end2end/h2_sockpair_test@ping/test.log
//test/core/end2end:h2_ssl_proxy_test@compressed_payload                 FAILED in 0.1s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/grpc/bazel-out/local-fastbuild/testlogs/test/core/end2end/h2_ssl_proxy_test@compressed_payload/test.log
//test/core/end2end:h2_ssl_proxy_test@connectivity                       FAILED in 0.2s
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/grpc/bazel-out/local-fastbuild/testlogs/test/core/end2end/h2_ssl_proxy_test@connectivity/test.log

Executed 5037 out of 5037 tests: 5029 tests pass and 8 fail locally.
**My opinion:** these cannot have been affected by this PR because this PR is in include/grpc++ and these failures are in test/core

## From Basic Tests Linux
c++_linux_dbg.bins/dbg/json_run_localhost --scenarios_json '{"scenarios": [{"name": "cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure", "warmup_seconds": 0, "benchmark_seconds": 1, "num_servers": 1, "server_config": {"async_server_threads": 0, "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "server_type": "SYNC_SERVER"}, "num_clients": 0, "client_config": {"client_type": "ASYNC_CLIENT", "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 0, "req_size": 0}}, "client_channels": 64, "async_client_threads": 0, "outstanding_rpcs_per_channel": 100, "rpc_type": "STREAMING", "load_params": {"closed_loop": {}}, "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}}]}' GRPC_POLL_STRATEGY=poll-cv

**My opinion:** This is a pre-existing flake. It is not possible to have been affected by this PR since these #defines are not used in the code at all.

**Comment by ctiller** [comment]
Also we are not looking at that project for flakes right?

**Comment by vjpai** [comment]
I have removed references to Bazel Full Build & Test from the comment documenting failures.

**Pull request merged**
