### PR TITLE
Auto-update Python documentation

### PR DESCRIPTION
**Pull request by soltanmm**
This indirectly depends on an automatic docgen+push script in [soltanmm:coverage](https://github.com/soltanmm/grpc/tree/coverage). That branch is still a WIP with respect to a whole bunch of modifications to setup.py and such to enable coverage reporting (and the work will probably need to be split up into multiple commits), but the auto-genned documentation should still be reviewable as acceptable or not.

cc @nicolasnoble

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
The commit log message should help me navigate my way around all the files changed in your commit. Which are generated? What's the reason for checking generated resources into source control, which is usually a mistake? Is the documentation checked into the same source tree as the source from which it's generated? Can that be avoided?

You describe this as a work in progress - what are the next steps you have in mind?

**Comment by soltanmm** [comment]
*Everything* in this commit is auto-generated. We're checking this into source control because that's the mechanism we decided on to have our documentation hosted (note the name of the branch I'm PR'ing against). The only thing that's 'in progress' is the support script - technically the documentation is ready-to-merge, it's just that we wouldn't be able to regenerate it easily (so the WIP nature is a matter of workflow rather than artifact-readiness).

**Comment by soltanmm** [comment]
This depends on #2697 for the intended update-workflow.

**Comment by ctiller** [comment]
Can we target reference documentation into doc/ref/python?

A directory off root isn't the place for this.

**Comment by soltanmm** [comment]
What are `core` and `cpp` currently doing off root, then? Or is that changing as well?

**Comment by ctiller** [comment]
Ah I just saw this was against the gh-docs branch.

@nicolasnoble - question here - the branch with a different directory
layout is kind of weird to me. Do we run into problems serving stuff out of
master? What's the versioning strategy for docs?

**Comment by nathanielmanistaatgoogle** [comment]
How would you recommend I browse the documentation? Just in the GitHub browser, or is there someplace I can see it rendered?

**Comment by soltanmm** [comment]
The only easy way I'm aware of is for you to clone the branch and browse it locally. I could try hosting it somewhere, but that seems a tad silly unless you have any straightforward means in mind.

**Comment by nathanielmanistaatgoogle** [comment]
LGTM after cloning and browsing locally. Since it's @nicolasnoble's branch I'll leave the merge to him.

**Comment by soltanmm** [comment]
@ctiller (to leave a thread-record w.r.t. the layout of `gh-pages`): https://help.github.com/articles/creating-project-pages-manually/

**Comment by nicolasnoble** [comment]
D'oh, just saw the question here. But yes, @soltanmm is right, this is due to github's pages layout. This is basically the website that is served from http://www.grpc.io/grpc.

**Pull request merged**
