### PR TITLE
Do not start timer if transport is closed.

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +16 [None]                                                         +152  +0.0%
  +0.1%     +16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +16  +0.1%
       +25%     +16 start_keepalive_ping_locked                                     +16   +25%

  +0.0%     +32 TOTAL                                                          +168  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
Test failure: #15981

**Pull request merged**
