### PR TITLE
Adding NPN support if ALPN support is not available.

### PR DESCRIPTION
**Pull request by jboeuf**
- ALPN may not be available:
  - because OpenSSL does not support it.
  - because one of the peers does not support it.
- Tested manually end to end by forcing TSI_OPENSSL_ALPN_SUPPORT to 0.
  Also tested if only one of the peers supports ALPN.

### CODE REVIEW

**Comment by jboeuf** [comment]
@nicolasnoble, @ctiller, This `TSI_OPENSSL_ALPN_SUPPORT` macro is kind of yucky. I'm open to suggestions...

**Comment by nicolasnoble** [comment]
It's a bit of a shame, but I don't think we can do otherwise. Keep in mind this is "temporary" until ALPN is widely supported (aka, ~2 years).

**Comment by ctiller** [comment]
This is up to you, but I could imagine a small wrapper module that we selectively compile in.

The 'with alpn' version would do the alpn calls we currently do.
The 'without alpn' version would produce whatever result the with alpn would otherwise produce for its failure case.

It'd prevent ifdef sprawl over the next few years at least.

**Comment by nicolasnoble** [comment]
Well... I'd agree with you, but I feel this would obfuscate an otherwise pretty straightforward flow. Maybe.

**Comment by ctiller** [comment]
I don't disagree... it's a judgement call as to whether we can keep this as
being an argument for inserting just one more #ifdef later on (and ending
up with a cancer on the codebase) or whether we think this sort of thing is
strictly isolated.

Having typed that out, I think I prefer splitting this into a module.

**Comment by jboeuf** [comment]
Are you guys OK if I just add a comment that this is yucky and a TODO to
split that in a module? I have a lot of stuff on my list for EOQ.

**Comment by ctiller** [comment]
sgtm

**Comment by jboeuf** [comment]
adding comments as discussed.

**Comment by jboeuf** [comment]
The travis csharp failure looks completely unrelated:
`Unable to read package from path 'grpc.dependencies.openssl.redist.1.0.2.2.nupkg'.`.

@jtattermusch can you have a look?

**Comment by jtattermusch** [comment]
I don't see the travis failure of C# anywhere. The error sounds like there was a  problem downloading a dependency (maybe nuget unavailable for a while? can happen).

**Pull request merged**
