### PR TITLE
Remove exec_ctx_fwd.h from surface public headers

### PR DESCRIPTION
**Pull request by vjpai**
Was there a reason why this was made a surface header? No part of the surface API uses it. It also wasn't needed in either of the places that include it.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -24  -0.0%

  [ = ]       0 TOTAL      -24  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]    -192  -0.0%

  [ = ]       0 TOTAL     -192  -0.0%



```

**Comment by yashykt** [comment]
It was probably needed but wasn't needed any longer after the ExecCtx change. I remember it needing a bit of cleanup in google3 too, so I was planning to get to it after, but I never did.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
I'm chalking this one up to the fact that our boundaries were not always as clear as they are today, keeping in mind previous instances of misplaced content like [`gpr_histogram`](https://github.com/grpc/grpc/pull/13575) .

**Pull request merged**
