### PR TITLE
Update Python documentation

### PR DESCRIPTION
**Pull request by lidizheng**
Reorganized the section titles to make it more consistent, and added `Tutorial` and `Example` section to point to [grpc.io](https://grpc.io) and GitHub example folder.

### CODE REVIEW

**Comment by lidizheng** [comment]
This changes are implemented to facilitate publish of new documentation for gRPC Python v1.16.0.
Related PR https://github.com/grpc/grpc/pull/17190

**Comment by mehrdada** [comment]
Documentation on the grpc.io website is still stale... FYI, it does not get automatically updated. Someone needs to manually run the new script and upload it to `gh-pages` branch of this repo.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,028      Total (=)      2,019,028

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,179,732      Total (>)     11,179,731

 No significant differences in binary sizes


```

**Comment by lidizheng** [comment]
@mehrdada Thanks for giving that information. I was doing update for generator and document in two separate PR. Now the document is live XD

**Comment by mehrdada** [comment]
@lidizheng Thanks! the docs look good now. I created a new issue for automatically updating the docs.

**Pull request merged**
