### PR TITLE
Revert "Update the kokoro build version in gcloud command"

### PR DESCRIPTION
**Pull request by AspirinSJL**
Reverts grpc/grpc#15219

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
As explained here, I think this PR has nothing to do with the breakage: https://github.com/grpc/grpc/pull/15219#issuecomment-385490207  Let's find the real rootcause (my guess would be a recent change in grpc-go repo?) and close this PR.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
@jtattermusch Thanks for the info! Closing this PR.

**Pull request closed without merging**
