### PR TITLE
Add support for clang3.5, clang3.7 and gcc4.6  in run_tests.py

### PR DESCRIPTION
**Pull request by jtattermusch**
For #1928 and #1929.

### CODE REVIEW

**Comment by vjpai** [comment]
If clang-3.6 is the default, I think the compiler should just be called clang, right? The portability test says there's no clang-3.6

**Comment by jtattermusch** [comment]
Ok, the clang-3.6 missing is really odd, it think it might be that that symlink was added to the ubuntu1604 distro after the docker image was created (it is cached), because locally I do have clang3.6 available in that image.

**Comment by jtattermusch** [comment]
(I am not trying to call clang  just clang  even when it is the default, because by calling it `clang-3.6` explicitly it would be easier to spot a problem if we by mistake break our configuration one day).

**Comment by jtattermusch** [comment]
clang3.6 portability test is passing now.

**Comment by jtattermusch** [comment]
PTAL.

**Comment by vjpai** [comment]
LGTM.

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
test this please

**Comment by vjpai** [comment]
FWIW, I believe that clang 3.5, 3.6, 3.7, and gcc 4.6, 4.9, 5.3 are all ready to go for C++ . clang 3.4 for C++ produces compilation errors. Will look into those once the gcc 4.4 issues are resolved.

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
test were already green, needed to rebase to give Jenkins a kick to rerun interop tests (Required for merge).
Will merge once required statuses are green.

**Pull request merged**
