### PR TITLE
Make mobile log per-host

### PR DESCRIPTION
**Pull request by muxi**
Allow per-host configuration of mobile log. 

Rename the config as context.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Basic Tests C Linux - #13727 
Basic Tests MacOS - #14182 
Interop Cloud-to-Cloud Tests - #15464 
Interop Cloud-to-Prod Tests - #15540

**Pull request merged**
