### PR TITLE
Bump 1.31.x to 1.31.1

### PR DESCRIPTION
**Pull request by apolcyn**
To release https://github.com/grpc/grpc/pull/23826

### CODE REVIEW

**Comment by jtattermusch** [comment]
Looks like there's one more fix for the 1.31.x branch: https://github.com/grpc/grpc/pull/23830

**Comment by stanley-cheung** [comment]
There's also #23830.

**Comment by apolcyn** [comment]
> Looks like we will only need a ruby release?

Yes, I'll kick off builds after this is merge and will aim to do the release on monday

**Comment by jtattermusch** [comment]
Both https://github.com/grpc/grpc/pull/23826 and https://github.com/grpc/grpc/pull/23830 have been merged.

**Comment by jtattermusch** [comment]
After merging I started the package builds on v1.31.x branch:
https://g3c.corp.google.com/results/invocations/0cd1ef09-574e-47f6-af9b-c8a42049883e/targets
https://g3c.corp.google.com/results/invocations/bb9e2ad2-d82f-4bef-a358-1baa3e415151/targets

**Comment by apolcyn** [comment]
Thanks, Jan! Those builds look green so I'll do the release from them today.

**Pull request merged**
