### PR TITLE
Explain this directory's existence

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by markdroth** [comment]
Should we put this same file in `include/grpc/impl/codegen` as well?

**Comment by vjpai** [comment]
@markdroth That feels less clear to me since user code isn't supposed to include _anything_ in `include/grpc` . wdyt?

**Comment by markdroth** [comment]
It's a fair point that users are not supposed to include anything from that directory anyway.  But the content in this README file about the fact that we can eventually get rid of the directory entirely applies to both directories.  IIUC, once the proto_library rules go away, so does the need for both directories.

**Comment by vjpai** [comment]
@markdroth Sounds good, I'll add a finessed version in that directory.

**Pull request merged**
