### PR TITLE
Avoid low severity log message construction

### PR DESCRIPTION
**Pull request by ara-ayvazyan**
The change improves the performance of `gpr_log` by avoiding unnecessary message allocation and formatting.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                     FILE SIZE
 ++++++++++++++ GROWING                       ++++++++++++++
  +0.0%    +152 [None]                           +272  +0.0%
  +9.5%     +48 src/core/lib/gpr/log.cc           +48  +9.5%
      [NEW]     +19 gpr_should_log                    +19  [NEW]
       +17%     +17 gpr_log_message                   +17   +17%
       +29%     +12 [Unmapped]                        +12   +29%
  +4.6%     +32 src/core/lib/gpr/log_linux.cc     +32  +4.6%
       +12%     +30 gpr_log                           +30   +12%
       +17%      +2 [Unmapped]                         +2   +17%

  +0.0%    +232 TOTAL                            +352  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -80  -0.0%

  [ = ]       0 TOTAL      -80  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Odd sanity check failure:
```
245a246
>   printf("%lx", (unsigned long) gpr_should_log);
Traceback (most recent call last):
  File "tools/buildgen/generate_projects.py", line 100, in <module>
    assert 0 == os.system('diff %s %s' % (s, g)), s
AssertionError: ./test/core/surface/public_headers_must_be_c89.c
2018-04-05 05:29:35,924 FAILED: tools/buildgen/generate_projects.sh [ret=1, pid=1915, time=56.5sec]
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                     FILE SIZE
 ++++++++++++++ GROWING                       ++++++++++++++
  +0.0%    +152 [None]                           +272  +0.0%
  +9.5%     +48 src/core/lib/gpr/log.cc           +48  +9.5%
      [NEW]     +19 gpr_should_log                    +19  [NEW]
       +17%     +17 gpr_log_message                   +17   +17%
       +29%     +12 [Unmapped]                        +12   +29%
  +4.6%     +32 src/core/lib/gpr/log_linux.cc     +32  +4.6%
       +12%     +30 gpr_log                           +30   +12%
       +17%      +2 [Unmapped]                         +2   +17%

  +0.0%    +232 TOTAL                            +352  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -80  -0.0%

  [ = ]       0 TOTAL      -80  -0.0%



```

**Comment by jtattermusch** [comment]
@ara-ayvazyan The problem with sanity was that you need to run tools/buildgen/generate_projects.sh after adding a public header. I did that and pushed a commit that fixes the sanity test to this PR.

@ncteisen  do we need a special approval for adding a new method to the public API?

It would be interesting to know if this change leads to improvements in our public end to end benchmarks.
CC @sreecha

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                     FILE SIZE
 ++++++++++++++ GROWING                       ++++++++++++++
  +0.0%    +152 [None]                           +272  +0.0%
  +9.5%     +48 src/core/lib/gpr/log.cc           +48  +9.5%
      [NEW]     +19 gpr_should_log                    +19  [NEW]
       +17%     +17 gpr_log_message                   +17   +17%
       +29%     +12 [Unmapped]                        +12   +29%
  +4.6%     +32 src/core/lib/gpr/log_linux.cc     +32  +4.6%
       +12%     +30 gpr_log                           +30   +12%
       +17%      +2 [Unmapped]                         +2   +17%

  +0.0%    +232 TOTAL                            +352  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -80  -0.0%

  [ = ]       0 TOTAL      -80  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
C Core API changes generally should be looked at quite closely, but there is no official practice for a more rigorous approval. Since this is purely additive (and quite small), I think it is fine. This will need to go into release notes though.

As far as performance, we will know the answer after this gets imported. Performance team has looked at a lot of flamegraphs, and I have never seen gpr_log show up, so I am a little doubtful this will improve perf on linux. Perhaps Windows `vsnprintf_s` is slower than the Linux `vasprintf`, which would make sense. I would love to be proven wrong here.

Regardless, it is great to have people looking into Windows perf. That is an area that we have not dedicated much time to, and I am sure there is a lot of low hanging fruit

**Comment by ncteisen** [comment]
Actually, to get a quick take, could you run `tools/profiling/microbenchmarks/bm_diff/bm_main.py -d master` from your windows machine?

It _should_ just work out of the box, no promises though :)

That will take 30 min or so, and will run our suite of microbenchmarks against your branch and master, then compare the results

**Comment by ncteisen** [comment]
Actually, on second though, it probably won't work immediately for Windows... since it relies on calling make commands. Making it windows friendly shouldn't be too hard, and might be worthwhile for future perf work.

**Comment by ara-ayvazyan** [comment]
@jtattermusch, thanks for the fix.

The `gpr_log` started showing up in [`report_stall`](https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/writing.cc#L140) function after I've enabled [`SIO_LOOPBACK_FAST_PATH`](#14905).

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                     FILE SIZE
 ++++++++++++++ GROWING                       ++++++++++++++
  +0.0%    +152 [None]                           +272  +0.0%
  +9.5%     +48 src/core/lib/gpr/log.cc           +48  +9.5%
      [NEW]     +19 gpr_should_log                    +19  [NEW]
       +17%     +17 gpr_log_message                   +17   +17%
       +29%     +12 [Unmapped]                        +12   +29%
  +4.6%     +32 src/core/lib/gpr/log_linux.cc     +32  +4.6%
       +12%     +30 gpr_log                           +30   +12%
       +17%      +2 [Unmapped]                         +2   +17%

  +0.0%    +232 TOTAL                            +352  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -80  -0.0%

  [ = ]       0 TOTAL      -80  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
