### PR TITLE
Correct the test request/response size, to be consistent with the tes…

### PR DESCRIPTION
**Pull request by madongfly**
…t spec:https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md

@yang-g , please take a look, thanks!

### CODE REVIEW

**Comment by yang-g** [comment]
LGTM

**Comment by yang-g** [comment]
Usually we wait until the travis tests return success before the reviewer does the merge. But this one is kind-of trivial, so it could be ok. Please do not do it again :)

**Comment by madongfly** [comment]
I did merge after confirmed travis tests returned success, are you saying the "merge" should be done by reviewer?

**Comment by yang-g** [comment]
Yes.

**Comment by madongfly** [comment]
Oh, ok, didn't know that, thanks for the info.

**Pull request merged**
