### PR TITLE
Add missing security field to channelz Socket

### PR DESCRIPTION
**Pull request by yashykt**
As per https://github.com/grpc/grpc/blob/fcd43e90304862a823316b224ee733d17a8cfd90/src/proto/grpc/channelz/channelz.proto#L240, `Sockets` should expose security information.

Currently, we are able to get the remote's peer certificate from `grpc_auth_context` once the security handshake is done, but we don't have any other information. This PR exposes the remote's peer certificates as part of the channelz's Socket information.

cc @markdroth @ZhenLian

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25593)

### CODE REVIEW

**Review by veblush — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25593)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 366 at r1](https://reviewable.io/reviews/grpc/grpc/25593#-MUuumMD4fozNGsZ4k4K:-MUuumME7B9xBD4wBIT_:b-iixtg4) ([raw file](https://github.com/grpc/grpc/blob/bf26a113cc6abc73fdaf8bbe360da3a6799305d9/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L366)):*
> ```cpp
>   }
>   if (channelz_enabled) {
>     auto sec = grpc_core::channelz::SocketNode::Security::GetFromChannelArgs(
> ```

is sec used here?

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25593)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @veblush)

___
*[src/core/ext/transport/chttp2/transport/chttp2_transport.cc, line 366 at r1](https://reviewable.io/reviews/grpc/grpc/25593#-MUuumMD4fozNGsZ4k4K:-MUv0h-K4c7prdQLDgEs:b-4qh4bt) ([raw file](https://github.com/grpc/grpc/blob/bf26a113cc6abc73fdaf8bbe360da3a6799305d9/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L366)):*
<details><summary><i>Previously, veblush (Esun Kim) wrote…</i></summary><blockquote>

is sec used here?
</blockquote></details>

Removed. Thanks for catching that! Looks like it got left over from testing.

**Review by markdroth — COMMENTED** [review]
Thanks for doing this!  Just a couple of minor comments.

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25593#-:-MUyuX8MALrO3b1oh42U:bd8038k)* status: all files reviewed, 3 unresolved discussions (waiting on @veblush and @yashykt)

___
*[src/core/lib/channel/channelz.cc, line 376 at r2](https://reviewable.io/reviews/grpc/grpc/25593#-MUysyyv1PE8-caZoPuU:-MUysyyv1PE8-caZoPuV:b-vjlrsj) ([raw file](https://github.com/grpc/grpc/blob/5ddcf515b52be4c060dabe60124dc834ae252756/src/core/lib/channel/channelz.cc#L376)):*
> ```cpp
>     case ModelType::kOther:
>       if (other) {
>         data["other"] = tls->RenderJson();
> ```

Shouldn't this use `*other` instead of `tls->RenderJson()`?
___
*[test/cpp/end2end/channelz_service_test.cc, line 145 at r2](https://reviewable.io/reviews/grpc/grpc/25593#-MUyu2ux0f5ZIjEIUQjp:-MUyu2ux0f5ZIjEIUQjq:b-ja4vqw) ([raw file](https://github.com/grpc/grpc/blob/5ddcf515b52be4c060dabe60124dc834ae252756/test/cpp/end2end/channelz_service_test.cc#L145)):*
> ```cpp
>   }
>   args->SetSslTargetNameOverride("foo.test.google.fr");
>   // TODO(yashykt): Switch to using C++ API once b/173823806 is fixed.
> ```

Is that bug a problem here?  We're not using the custom verification config here, unless I'm missing something.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25593)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth and @veblush)

___
*[src/core/lib/channel/channelz.cc, line 376 at r2](https://reviewable.io/reviews/grpc/grpc/25593#-MUysyyv1PE8-caZoPuU:-MUzCdIB0nzz_bGV2Nf3:b-x6j106) ([raw file](https://github.com/grpc/grpc/blob/5ddcf515b52be4c060dabe60124dc834ae252756/src/core/lib/channel/channelz.cc#L376)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Shouldn't this use `*other` instead of `tls->RenderJson()`?
</blockquote></details>

Thanks for catching this. Making this change in #25624
___
*[test/cpp/end2end/channelz_service_test.cc, line 145 at r2](https://reviewable.io/reviews/grpc/grpc/25593#-MUyu2ux0f5ZIjEIUQjp:-MUzCkmc3DeEsBg8QsJN:b-qdy53) ([raw file](https://github.com/grpc/grpc/blob/5ddcf515b52be4c060dabe60124dc834ae252756/test/cpp/end2end/channelz_service_test.cc#L145)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Is that bug a problem here?  We're not using the custom verification config here, unless I'm missing something.
</blockquote></details>

You are right. I just copied over the code from existing tests but this should not be needed here. Making the change in #25624

**Pull request merged**
