### PR TITLE
Update jessie-backports URL

### PR DESCRIPTION
**Pull request by murgatroid99**
Update jessie-backports URL as described in [this post](https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository).

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Hopefully this will fix the issues we've seen in #18477. CC @jtattermusch and @jiangtaoli2016.

**Comment by murgatroid99** [comment]
I had to change a lot more files to get all of the updated docker files to actually build, so it would be good to check them again.

**Comment by jtattermusch** [comment]
LGTM again. I checked the test failures and they seem to be mostly:

https://github.com/grpc/grpc/issues/17794

**Comment by srini100** [comment]
Does this need to be backported to v1.19.x to fix https://github.com/grpc/grpc/issues/18646?

**Pull request merged**
