### PR TITLE
Minimal Bazel BUILD files for grpcio Python

### PR DESCRIPTION
**Pull request by ghostwriternr**
Follow-up on the additions in #15992. Pad the grpcio Python package with necessary BUILD files along with 2 simple tests.

cc: @nathanielmanistaatgoogle  @mehrdada

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,654      Total (=)      1,976,654

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,775,728      Total (<)     10,775,731

 No significant differences in binary sizes


```

**Comment by nathanielmanistaatgoogle** [comment]
What would you think about naming these files `BUILD.bazel`? @nicolasnoble pointed out to me that if these files were simply named `BUILD`, they'd break the way this code is used internally at Google. We can work around the problem on the internal side if you like, but a quick and easy solution (as I understand it) would be for the open source Bazel-using files to just have `.bazel` suffixes. What do you think?

**Comment by ghostwriternr** [comment]
Hey! Renaming the files to BUILD.bazel was a good suggestion. I checked to see and BUILD.bazel is indeed the recommended naming scheme for build files (to the extent that [if there are two files `BUILD` and `BUILD.bazel`, the latter is used](https://github.com/bazelbuild/bazel/issues/4517#issuecomment-360213750)). 

I went ahead and made the change to all the files here.

**Comment by nathanielmanistaatgoogle** [comment]
@nicolasnoble: I think this is ready for owners approval; do you agree?

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,980,479      Total (=)      1,980,479

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,810,802      Total (>)     10,810,791

 No significant differences in binary sizes


```

**Pull request merged**
