### PR TITLE
Replace atm with grpc_error_handle in call

### PR DESCRIPTION
**Pull request by veblush**
`grpc_call` stores `grpc_error_handle` in a type of `gpr_atm` and uses atomic operation when loading and storing value. But it doesn't support `absl::Status` so this PR adds a new `AtomicError` type to be considered as `atomic<grpc_error_handle>` and updates call to use this.

One side effect is having `reset_batch_errors` in a safer way. It doesn't used to be not handling a race condition. Current code isn't clear as to how to handle race condition. As an instance, following function isn't capable of handling it although it uses atomic functions. When `reset_batch_errors` is called by two threads at once, it's possible to call GRPC_ERROR_UNREF twice against the same error instance.

```
static void reset_batch_errors(batch_control* bctl) {
  GRPC_ERROR_UNREF(bctl->batch_error);
  bctl->batch_error = GRPC_ERROR_NONE;
}
```

But a new `AtomicError` simply solves this by using a lock.

### CODE REVIEW

**Comment by veblush** [comment]
Oh https://github.com/grpc/grpc/pull/16594 looks relevant

**Comment by yashykt** [comment]
The race around `reset_batch_errors` is avoided by using different batch_control slots for different types of ops.

**Review by yashykt — APPROVED** [review]
Approved with a question- Why can't we just use Atomic<grpc_error_handle>?

**Comment by veblush** [comment]
> Approved with a question- Why can't we just use Atomic<grpc_error_handle>?

To use `std::atomic`, T should meet a few traits listed in [doc](https://en.cppreference.com/w/cpp/atomic/atomic). Notably `absl::Status` isn't `std::is_trivially_copyable` so it cannot use it unless it has a specialized template for it. Similarly, shared_ptr cannot be used `std::atomic` but it seems that C++20 adds a specialized class for it.

**Pull request merged**
