### PR TITLE
Replace distutils.sysconfig with sysconfig

### PR DESCRIPTION
**Pull request by jjyao**
This is essentially https://github.com/tensorflow/tensorflow/issues/51776 since `python_configure.bzl` is modified from tensorflow.

I basically copied two PRs from there: https://github.com/tensorflow/tensorflow/pull/51782 and https://github.com/tensorflow/tensorflow/pull/51865.

@donnadionne

### CODE REVIEW

**Comment by jjyao** [comment]
Tag @lidizheng @gnossen as well.

**Comment by lidizheng** [comment]
Docker Hub is down now, I will retrigger the tests when it's back-up.

**Comment by jjyao** [comment]
@lidizheng I think docker hub is back-up now :)

**Comment by lidizheng** [comment]
```
INFO: Repository local_config_python instantiated at:
  /var/local/git/grpc/WORKSPACE:5:10: in <toplevel>
  /var/local/git/grpc/bazel/grpc_deps.bzl:448:21: in grpc_deps
  /var/local/git/grpc/bazel/grpc_python_deps.bzl:61:21: in grpc_python_deps
Repository rule python_configure defined at:
  /var/local/git/grpc/third_party/py/python_configure.bzl:365:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 347, column 35, in _python_autoconf_impl
		_create_single_version_package(
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 304, column 45, in _create_single_version_package
		python_include = _get_python_include(repository_ctx, python_bin)
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 253, column 13, in _get_python_include
		_execute(
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 62, column 14, in _execute
		_fail("\n".join([
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 35, column 9, in _fail
		fail("%sPython Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Python Configuration Error: Unable to find Python headers for /usr/bin/python2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: /usr/local/include/python2.7/Python.h does not exist.
Are Python headers installed? Try installing python-dev or python3-dev on Debian-based systems. Try python-devel or python3-devel on Redhat-based systems.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 347, column 35, in _python_autoconf_impl
		_create_single_version_package(
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 304, column 45, in _create_single_version_package
		python_include = _get_python_include(repository_ctx, python_bin)
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 253, column 13, in _get_python_include
		_execute(
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 62, column 14, in _execute
		_fail("\n".join([
	File "/var/local/git/grpc/third_party/py/python_configure.bzl", line 35, column 9, in _fail
		fail("%sPython Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Python Configuration Error: Unable to find Python headers for /usr/bin/python2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: /usr/local/include/python2.7/Python.h does not exist.
Are Python headers installed? Try installing python-dev or python3-dev on Debian-based systems. Try python-devel or python3-devel on Redhat-based systems.
INFO: Repository com_google_libprotobuf_mutator instantiated at:
  /var/local/git/grpc/WORKSPACE:7:20: in <toplevel>
  /var/local/git/grpc/bazel/grpc_deps.bzl:528:21: in grpc_test_only_deps
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /var/local/git/grpc/src/python/grpcio/grpc/_cython/BUILD.bazel:25:12: //src/python/grpcio/grpc/_cython:cygrpc.so depends on @local_config_python//:python_headers in repository @local_config_python which failed to fetch. no such package '@local_config_python//': Python Configuration Error: Unable to find Python headers for /usr/bin/python2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: /usr/local/include/python2.7/Python.h does not exist.
Are Python headers installed? Try installing python-dev or python3-dev on Debian-based systems. Try python-devel or python3-devel on Redhat-based systems.
ERROR: Analysis of target '//examples/python/multiprocessing:prime_proto_pb2_grpc' failed; build aborted: Analysis failed
INFO: Elapsed time: 28.827s
```

There might be some Python 2 residual causing tests to fail (there is also an ongoing `setuptools` issue). If you are comfortable with Bazel, do you think you can take a peak at it?

**Comment by acxz** [comment]
@jjyao can you fix the corresponding error msg?

```
            python_bin + ".) " + "Is distutils installed? " +
            _HEADERS_HELP
```
to
```
            python_bin + ".) " + _HEADERS_HELP
```

as seen in my PR.

This is just for consistency since distutils does not need to be installed as sysconfig is part of the default python installation now.

However it is not for python2 I believe. Thus for the tests are failing regarding python2 we may need to have a conditional that runs the old code with distutils.

**Comment by jjyao** [comment]
Oh, does grpc support python2? I thought it's >= 3.6 based on https://github.com/grpc/grpc/tree/master/src/python/grpcio.

**Comment by lidizheng** [comment]
Nah, this looks like a script used by C/C++ build. I can take a look later.

**Comment by jjyao** [comment]
> Nah, this looks like a script used by C/C++ build. I can take a look later.

Thanks. I'm not familiar with the grpc build system so it would be great if you can provide some help here.

**Comment by lidizheng** [comment]
Link to an existing issue: https://github.com/grpc/grpc/issues/28026

**Comment by acxz** [comment]
@lidizheng can you clarify on what is needed for this PR to be merged?

Is getting the CI to pass a hard requirement? Just want to know since quite a few downstream projects are stuck at this issue and would like to know when this can be rolled out.

**Comment by lidizheng** [comment]
During last weekend, upstream `setuptools` broke the Python build, I'm working on two fixes https://github.com/grpc/grpc/pull/28393 and https://github.com/grpc/grpc/pull/28397.

Yes, getting the CI pass is a hard requirement.

@acxz  I understand this is a headache for Bazel + 3.10.  For code rollout, do we need a patch release?

**Comment by acxz** [comment]
> Yes, getting the CI pass is a hard requirement.

Got it. If I get some bandwidth I'll see if I can help with #28026 and eliminating all python 2 code.

The way we use grpc in our Bazel, a fix at head is just what we need.

**Comment by lidizheng** [comment]
@jjyao Build related issues have been fixed, the Python 2 issue in Bazel is also fixed. Can you rebase this PR?

**Comment by jjyao** [comment]
@lidizheng Rebased.

**Review by lidizheng — APPROVED** [review]
Thanks for making this update!

**Comment by lidizheng** [comment]
@gnossen PTAL.

**Review by gnossen — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
