### PR TITLE
Support swift package manager for grpc-core and grpc-cpp.

### PR DESCRIPTION
**Pull request by yulin-liang**
Support swift package manager for grpc-core and grpc-cpp. I will have another PR to remove unsafe flags.

### CODE REVIEW

**Comment by yulin-liang** [comment]
cc: @paulb777

**Review by paulb777 — COMMENTED** [review]
Thanks! Do you plan to add SPM support for the abseil and BoringSSL dependencies?

Adding CI would be helpful - something like https://github.com/nanopb/nanopb/blob/maintenance_0.3/.github/workflows/spm.yml

**Comment by yulin-liang** [comment]
> Thanks! Do you plan to add SPM support for the abseil and BoringSSL dependencies?
> 
> Adding CI would be helpful - something like https://github.com/nanopb/nanopb/blob/maintenance_0.3/.github/workflows/spm.yml

Thanks for reviewing it, I'll have a separate RP to add CI. For adding SPM support for the abseil and BoringSSL dependencies, I may need to discuss with Wenbo first.

**Comment by paulb777** [comment]
OK, one of the open questions from the prototype implementation I did is that I did not find a way to do symbol renaming for the BoringSSL symbols. This will cause problems for any client apps that link another ssl implementation.

**Comment by yulin-liang** [comment]
I'll look into it later. If I understand correctly, `CNIOBoringSSL` is incompatible with `BoringSSL`, so I can reproduce the symbol collision issue by adding these two dependencies into a project, is that right?

**Comment by paulb777** [comment]
Not sure - but I wasn't able to find a way to port the CocoaPods transformations like https://github.com/CocoaPods/Specs/blob/master/Specs/c/8/7/gRPC-C++/1.33.1/gRPC-C++.podspec.json#L43 to Swift Package Manager

**Comment by yulin-liang** [comment]
I see, I'll do some searches and let you know if I can figure out how to do symbol renaming.

**Review by stanley-cheung — APPROVED** [review]

**Pull request merged**
