### PR TITLE
Make RIDs for the native dependencies in Grpc.Core arch specific

### LINKED ISSUE #18106: Exclude libgrpc_csharp_ext.x86.so from publish when targetting linux-64
### What version of gRPC and what language are you using?
 
C# , gRPC 1.17.0
 
### What operating system (Linux, Windows, …) and version?
 
Linux 64 bit

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
dotnet core 2.2

### What did you do?

Build a dotnet core project for linux-64 only.
`dotnet publish -c Release -o build -r linux-x64 --self-contained false .`
 
### What did you expect to see?
 
Only have libgrpc_csharp_ext.x64.so in my build directory.

### What did you see instead?

Both libgrpc_csharp_ext.x64.so and libgrpc_csharp_ext.x86.so are copied to the build directory and get mentioned as a dependency in myapp.deps.json .

I can't do `PackageReference ExcludeAssets native` in my csproj because I do need libgrpc_csharp_ext.x64.so .
How can I only exclude the x86 binaries ?

### PR DESCRIPTION
**Pull request by jtattermusch**
This is basically https://github.com/grpc/grpc/pull/24233, with a few adjustments and fixes.

This should fix #18106.

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @EraYaN

**Comment by jtattermusch** [comment]
Adhoc distribtests: https://g3c.corp.google.com/results/invocations/5cb6604b-539f-4044-a73e-5eacd8b2f132/targets

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/24764

**Comment by EraYaN** [comment]
>the problem is that the NativeExtension would need to be able to find the file that's copied to the output folder on net45 (but you just changed its logic to look for grpc_csharp_ext.dll only.

This is how native libs are supposed to work at least for .NET Core and .NET 5. It either ships the full runtimes folder with all OSes and architectures, on you publish for a specific arch and so you ship only one files with a fixed name. So there should I thik never be a conflict.

>At the same time, there are 2 <Content> items: one for x86 and one for x64.
you cannot copy them both into a single grpc_csharp_ext.dll (I think this is the original reason why we have the x64.dll and x86.dll suffix - to avoid a name clash in net45.

This should work because during publish MSbuild or dotnet CLI SHOULD only ship one for the correct arch. (Or it ships the full runtimes folder if one uses Any CPU.

For example, look how libSkiaSharp ships their native libraries: https://github.com/mono/SkiaSharp/blob/master/nuget/SkiaSharp.nuspec#L108-L140

That is what I tried to recreate.

**Comment by jtattermusch** [comment]
Distribtests are passing: https://g3c.corp.google.com/results/invocations/8df522b5-9fec-465b-931f-6e71a645f708/targets/grpc%2Fcore%2Fexperimental%2Fgrpc_distribtests_multiplatform/log

**Comment by jtattermusch** [comment]
> > the problem is that the NativeExtension would need to be able to find the file that's copied to the output folder on net45 (but you just changed its logic to look for grpc_csharp_ext.dll only.
> 
> This is how native libs are supposed to work at least for .NET Core and .NET 5 I believe. It either ships the full runtimes folder with all OSes and architectures, on you publish for a specific arch and so you ship only one files with a fixed name. So there should I think never be a conflict.

Yes, on .NET core and .NET 5 there is no problem as both actually support the runtime ids and native dependencies, so they automatically do the right thing. It's the net45 target that's problematic (since we have to emulate that logic by providing a Grpc.Core.targets file).

> 
> > At the same time, there are 2  items: one for x86 and one for x64.
> > you cannot copy them both into a single grpc_csharp_ext.dll (I think this is the original reason why we have the x64.dll and x86.dll suffix - to avoid a name clash in net45.
> 
> This should work because during publish MSbuild or dotnet CLI SHOULD only ship one for the correct arch. (Or it ships the full runtimes folder if one uses Any CPU).

I don't think that's true for the `net45` targets. For `net45` the way the native libraries get copied to the output folder is by the Grpc.Core.targets file we ship as MSBuild has no clue what "native libraries" are. An because MSBuild also knows nothing about the target architecture (at least when we're building under AnyCPU config), it wouldn't know whether it should copy grpc_csharp_ext.x86.dll or grpc_csharp_ext.x64.dll - so it currently always copies both (which would lead to a conflict if the file was named just grpc_csharp_ext.dll - as I pointed out earlier).

> 
> For example, look how libSkiaSharp ships their native libraries: https://github.com/mono/SkiaSharp/blob/master/nuget/SkiaSharp.nuspec#L108-L140
> 
> That is what I tried to recreate.

**Review by apolcyn — APPROVED** [review]

**Pull request merged**
