### PR TITLE
Moved the report template under tools/run_tests.

### PR DESCRIPTION
**Pull request by adelez**

### CODE REVIEW

**Comment by adelez** [comment]
Fixes #4264.

**Comment by jtattermusch** [comment]
LGTM. "Jenkins" tests are behaving oddly though, so let's wait for the build.

**Comment by adelez** [comment]
Interop test passed: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_interop_pull_requests/757/HTML_Report/

**Comment by adelez** [comment]
I think the regular pull request tests are chaotic for other reasons.

**Pull request merged**
