### PR TITLE
fix IOCP error handling and remove a redundant system-call

### PR DESCRIPTION
**Pull request by zeliard**
Please check this:
https://github.com/grpc/grpc/blob/master/src/core/iomgr/tcp_windows.c#L193-L204

IMHO, these lines are unnecessary because leaving the I/O to OS (kernel mode) gives better efficiency (low CPU utilization and low user-kernel transition) in case of the proactor style I/O (such as IOCP).

What's your opinion about this PR and comments?

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Please have a look at #1522 which does the same things, and more.

**Comment by nicolasnoble** [comment]
Also, about the first system call, this is to avoid a thread switch. I've yet to run actual benchmarks on this however. But basically I'm trying to avoid thread switching as much as possible, as they typically are more expensive than anything else you'd encounter. So running a first sync read will try that.

**Comment by zeliard** [comment]
@nicolasnoble  I couldn't recognize that you'd already solved that problem at #1522 :+1: 

About the first system call, basically you are right but, I think it is better that let the IOCP do I/O because IOCP mechanism surpresses the thread-switching by using stack-based thread pooling.

**Comment by zeliard** [comment]
when #1522 is merged, you'd better close this issue :)

**Comment by nicolasnoble** [comment]
Once the tests are stable, I'll definitely run some benchmark to see which is better. Right now that is just a gut intuition this is better, but I can be proven wrong by actual numbers, of course.

**Comment by nicolasnoble** [comment]
#1522 has been merged, closing this one.

**Pull request closed without merging**
