### PR TITLE
Generate separate sponge target for each test suite for more readable test results.

### PR DESCRIPTION
**Pull request by jtattermusch**
The idea is that when there's error reported by a test suite, one needs to first click on a test suite to see what are the actual test cases failing. This PR changes the sponge_log.xml files so that each test becomes a separate test target. 

Advantages:
- one can immediately see list of failing test cases by clicking on the "Details" link. (saves one click)
- internally the sponge targets are easier to query that their subelements (the test cases) which hopefully will make it easy to use internal queries to detect test flakiness
- This makes the test layout more similar to Bazel RBE tests (which have a lot of test target, each with only a few test cases) as opposed to the current situation (where kokoro tests only have a few targets where each has a large number of "test cases"). The UIs we use are more optimized to support a large number of targets than a large number of test cases split into only a few targets.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Example before and after test results for comparison
C# before:
https://source.cloud.google.com/results/invocations/2c866270-e7c7-497f-881a-6493aa52c34d/targets

C# after:
https://source.cloud.google.com/results/invocations/7e940420-a3ab-4b96-b5cc-c97435974050/targets

An example how the test results look if there are failures:
https://source.cloud.google.com/results/invocations/71fd6555-41b8-45b3-b7b8-3830903cb938/targets (in this case one can immediately see there's a problem with yapf code formatting - in contrast to only knowing there's something wrong with sanity tests).

**Comment by jtattermusch** [comment]
FYI @hcaseyal  @nicolasnoble  @gnossen

**Comment by jtattermusch** [comment]
> Really nice! This is an improvement I've wanted for a while.

It's still WIP, I wanted to verify a few things first and also decide on the exact format of the target names.

**Comment by hcaseyal** [comment]
@jtattermusch This is really nice. Thank you so much for doing this!

**Comment by jtattermusch** [comment]
A few more remarks:
- I've introduced a `--report_multi_target` argument for run_tests.py that allows to optionally switch to the new more readable report layout.
- I've enabled the new report for run_tests.py in all languages, except C and C++. The reason is that C/C++ have a very large number of test cases (5000+) and such number of .xml test logs could clog kokoro quite easily (problem is on kokoro side). Because the linux C/C++ test are already using bazel RBE, this shouldn't matter much, at least not on PRs.
- I've tried to make it obvious that tests are being run by run_tests.py (useful for build cops to easily see that) and to clearly name the "umbrella" targets for top-level run_tests.py invocations.

**Comment by jtattermusch** [comment]
Feel free to provide additional feedback in terms of how test results could be more readable - we can make adjustments as a followup.

**Pull request merged**
