### PR TITLE
Backport #13604 to v1.8.x

### PR DESCRIPTION
**Pull request by jtattermusch**
See https://github.com/grpc/grpc/pull/13604.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/13122

**Comment by jtattermusch** [comment]
@mehrdada  please let me know once it's ok to merge backports to v1.8.x

**Pull request merged**
