### PR TITLE
Improving the C# auth API

### PR DESCRIPTION
**Pull request by jtattermusch**
Follow up for https://github.com/grpc/grpc/pull/3468

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @jskeet

**Comment by jboeuf** [comment]
Thanks for the PR. I commented again on the doc about the MetadataCredentials vs. CallCredentials. 

Also, since these helpers are using Google specific libraries for authenticating to Google, I think that it would be better to rename this file to something less generic (current GrpcCredentials). How about GrpcGoogleCredentials? And then you could rename CreateGoogleCredentials to just CreateDefault and so on.

**Comment by jtattermusch** [comment]
Ok, so I think I addressed the API comments and I am quite happy with the API now.

-- I've renamed GrpcCredentials helper class to GoogleGrpcCredentials with factory methods GetApplicationDefaultAsync(), FromAccessToken() and extension methods ToCallCredentials() and ToChannelCredentials().

-- I've hidden the class MetadataCredentials entirely and exposed just CallCredentials.FromInterceptor() factory method instead.

PTAL.

Btw, I am still considering these changes (I might do them in a followup PR, because they are fairly orthogonal to changes made here):
-- hiding the SslCredentials class and exposing just factory methods on ChannelCredentials instead (same for SslServerCredentials)
-- figuring out a better way how to accommodate credentials composition using instance/extension methods.

**Comment by jskeet** [comment]
Added a few comments - looks generally fine to me, but a) I don't really know this area of the API well; b) I'm jetlagged... best to wait for +jboeuf as well, I'd suggest.

**Comment by jboeuf** [comment]
Thanks much for the changes. That looks really good to me and is definitely aligned with what we discussed.

> -- hiding the SslCredentials class and exposing just factory methods on ChannelCredentials instead (same for SslServerCredentials)

+1

**Comment by jtattermusch** [comment]
Got an LGTM offline, merging.

**Pull request merged**
