### PR TITLE
Allow Streaming RPCs to take iterables.

### PR DESCRIPTION
**Pull request by robertwb**
This avoids unpythonic (and hard to track down) errors like

```
    result = stub.StreamingRequest([msg])
    ...
    Exception iterating requests!
```

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @robertwb isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by robertwb** [comment]
release note: no

**Comment by robertwb** [comment]
I'm going to try and rebase this.

**Comment by robertwb** [comment]
Ping?

**Comment by robertwb** [comment]
Thanks. Merge conflict resolved.

**Comment by gnossen** [comment]
Odd. Not all of the tests have been triggered. Closing and reopening the PR to see if they'll get kicked off.

**Comment by robertwb** [comment]
This was approved. Any chance of it going in?

**Comment by robertwb** [comment]
What would it take to actually get this change merged ?

**Pull request closed without merging**
