### PR TITLE
Re-add cfstream_test

### PR DESCRIPTION
**Pull request by rmstar**
2nd attempt at adding cfstream_test after fixing internal build failures caused by first attempt.

### CODE REVIEW

**Comment by jtattermusch** [comment]
I don't have much context about what lead to the revert (https://github.com/grpc/grpc/pull/18069), so I'll leave the review to others.

**Comment by g-easy** [comment]
This breaks the opencensus build on darwin: https://travis-ci.org/census-instrumentation/opencensus-cpp/jobs/496305764#L2223

```
ERROR: /Users/travis/build/census-instrumentation/opencensus-cpp/examples/grpc/BUILD:43:1: Couldn't build file examples/grpc/hello_client: Linking of rule '//examples/grpc:hello_client' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -lc++ -fobjc-link-runtime -Wl,-S -o bazel-out/darwin-fastbuild/bin/examples/grpc/hello_client ... (remaining 180 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
[1,660 / 1,662] 2 actions running
    Linking examples/grpc/hello_client; 2s darwin-sandbox ...
bols for architecture x86_64:
  "grpc_set_default_iomgr_platform()", referenced from:
      grpc_determine_iomgr_platform() in libgrpc_base_c.a(iomgr_internal.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Pinning grpc to the previous commit (b03e014ad82c39b7c91d794bc775c0d4ec187e1b) makes the build work again. Please help. :)

**Comment by rmstar** [comment]
#18118 should fix the build failure.

**Comment by g-easy** [comment]
Thanks! Can confirm this fixes the build for me.

**Comment by yashykt** [comment]
This PR is causing breakages in tensorflow's windows kokoro builds

**Pull request merged**
