### PR TITLE
Removed obsolete lb_policies_test

### PR DESCRIPTION
**Pull request by dgquintas**
This code has been disabled for about a year (https://github.com/grpc/grpc/pull/9765). The is superseded by [client_lb_end2end_test](https://github.com/grpc/grpc/blob/master/test/cpp/end2end/client_lb_end2end_test.cc), which cover a wider set of scenarios. Ping testing is already performed in [tests/ping.cc](https://github.com/grpc/grpc/blob/master/test/core/end2end/tests/ping.cc). In addition, the test uses the low level core APIs directly, which makes it harder to maintain.

Fixes https://github.com/grpc/grpc/issues/9764

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
For future reference, here's the breakdown of the test case equivalences:

- `verify_vanilla_round_robin`: Covered by `ClientLbEnd2endTest::RoundRobin`
- `verify_total_carnage_round_robin`: Covered by `ClientLbEnd2endTest::RoundRobinReresolve`
- `verify_vanishing_floor_round_robin` and `verify_rebirth_round_robin`: Covered by `ClientLbEnd2endTest::RoundRobinSingleReconnect`

**Comment by dgquintas** [comment]
Issues: #14043 #13727

**Pull request merged**
