### PR TITLE
Properly release dynamically allocated memory

### PR DESCRIPTION
**Pull request by rikelme**

### CODE REVIEW

**Comment by rikelme** [comment]
I signed it!

**Comment by nicolasnoble** [comment]
@murgatroid99 can you comment on that one ? It may need to be adapted since it can't be merged as is.

**Comment by murgatroid99** [comment]
It looks like this change would still be correct. It's not immediately apparent where the merge conflict is.

**Comment by murgatroid99** [comment]
Thank you for your contribution. It turns out that this was already fixed in another PR.

**Pull request closed without merging**
