### PR TITLE
Fix SocketMutator channel args.

### PR DESCRIPTION
**Pull request by daniel-j-born**
Fix SocketMutator channel args.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                    FILE SIZE
 ++++++++++++++ GROWING                                      ++++++++++++++
  +0.0%     +24 [None]                                       +4.76Ki  +0.1%
  +4.5%    +272 src/cpp/common/channel_arguments.cc             +272  +4.5%
       +33%    +278 grpc::ChannelArguments::SetSocketMutator        +278   +33%

  +0.1%    +296 TOTAL                                        +5.02Ki  +0.1%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
cc @yang-g

**Comment by yashykt** [comment]
looks like this was done in #17573

**Pull request closed without merging**
