### PR TITLE
Convert grpc_server to idiomatic C++.

### PR DESCRIPTION
**Pull request by markdroth**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/23581)

### CODE REVIEW

**Comment by vjpai** [comment]
There are leaks in the server construction, can you check those out and lmk when this is reviewable? Thanks!

**Comment by markdroth** [comment]
Known issues: #19834

**Comment by markdroth** [comment]
Known issues: #23028

**Comment by jtattermusch** [comment]
This PR makes  //test/cpp/end2end:client_lb_end2end_test flaky on UBSAN   b/159146482

**Pull request merged**
