### PR TITLE
Updating build package C# scripts.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Triggered build from that PR: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/1500/

**Comment by nicolasnoble** [comment]
There was a failure, triggered a rebuild here: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/1503/

**Comment by nicolasnoble** [comment]
Updated packages should hopefully happen in https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/1480/

**Comment by apolcyn** [comment]
LGTM. 
Thanks for the help here! It looks like the CSharp packages include the recent updates now.

**Comment by nicolasnoble** [comment]
Yay :-)

**Pull request merged**
