### PR TITLE
Removed early adopter code

### PR DESCRIPTION
**Pull request by kpayson64**
This is #7328 cut against the GA branch.  I've also added a commit to remove some early adopter test modules.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
One commit, please.

**Comment by kpayson64** [comment]
Done

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum.

**Comment by kpayson64** [comment]
@nathanielmanistaatgoogle 
I had to make some changes to get the tests passing, specifically:
rm src/python/grpcio_tests/tests/unit/framework/interfaces/links/*

And removing an unused import from
src/python/grpcio/grpc/beta/implementations.py

**Comment by nathanielmanistaatgoogle** [comment]
That's not surprising.

How about including `stream_testing`, all of `tests/unit/framework/interfaces/base`, `_receiver`, and all of `foundation` except for `abandonment`, `callable_util`, `future`, and `logging_pool`? Anything else?

**Comment by kpayson64** [comment]
I've added the suggested files to the purge:
```
#	deleted:    src/python/grpcio/grpc/framework/foundation/_timer_future.py
#	deleted:    src/python/grpcio/grpc/framework/foundation/activated.py
#	deleted:    src/python/grpcio/grpc/framework/foundation/later.py
#	deleted:    src/python/grpcio/grpc/framework/foundation/relay.py
#	deleted:    src/python/grpcio/grpc/framework/foundation/stream.py
#	deleted:    src/python/grpcio/grpc/framework/foundation/stream_util.py
#	deleted:    src/python/grpcio_tests/tests/unit/framework/interfaces/base/__init__.py
#	deleted:    src/python/grpcio_tests/tests/unit/framework/interfaces/base/_control.py
#	deleted:    src/python/grpcio_tests/tests/unit/framework/interfaces/base/_sequence.py
#	deleted:    src/python/grpcio_tests/tests/unit/framework/interfaces/base/_state.py
#	deleted:    src/python/grpcio_tests/tests/unit/framework/interfaces/base/test_cases.py
#	deleted:    src/python/grpcio_tests/tests/unit/framework/interfaces/base/test_interfaces.py
#	deleted:    src/python/grpcio_tests/tests/unit/framework/interfaces/face/_receiver.py
```

**Comment by nathanielmanistaatgoogle** [comment]
`stream_testing.py`?

**Comment by kpayson64** [comment]
Turns out ``framework.foundation.stream.py`` is referenced by ```src/python/grpcio/grpc/framework/interfaces/face/face.py```

I'm leaving in stream_testing and bringing back stream as well.

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum.

**Comment by nathanielmanistaatgoogle** [comment]
... [and if you really want, the dee in "Removed" can be dropped](http://chris.beams.io/posts/git-commit/#seven-rules). :-P

**Pull request merged**
