### PR TITLE
Ruby performance testing worker

### LINKED ISSUE #4177: Implement QpsWorker for Ruby
go/grpc-performance-testing-setup

### PR DESCRIPTION
**Pull request by vjpai**
This is the Ruby performance benchmark test for both clients and servers.
This does not currently support generic servers (TBD), but this should be enough
to capture a large number of performance testing scenarios.

Fixes #4177

### CODE REVIEW

**Comment by vjpai** [comment]
Actually, please hold off on the review as I am close to finishing the client and let's just get it all done at once

**Comment by vjpai** [comment]
Known issue: security performance benchmarking is not yet working.

**Comment by vjpai** [comment]
Security benchmarking is now working. This is now ready to review.

**Comment by murgatroid99** [comment]
I don't see any clear problems. If you can run your script with this in place of the C++ worker, and it works, that's good enough for me.

**Comment by vjpai** [comment]
I forgot to implement one important option here - I didn't have support for multiple outstanding RPCs per channel.

This is now a suitable substitute for C++ in scenarios 2c, 3 (changed to proto), 5, 6, 10 (changed to proto), and 13

I would like to start using this in testing if you're ok with it.

**Comment by murgatroid99** [comment]
LGTM

**Pull request merged**
