### PR TITLE
Revert to the official manylinux1 image

### LINKED ISSUE #15770: Return to official manylinux1 docker image when Python 3.7 ships
We had to roll our own docker image base to build Python3.7 binary wheels for `manylinux1` platform. This is supposed to be temporary and this work item tracks going back to the official docker image after it distributes python3.7.

[grpc_artifact_python_manylinux_x64/Dockerfile](https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_artifact_python_manylinux_x64/Dockerfile#L17)

[grpc_artifact_python_manylinux_x86/Dockerfile](https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_artifact_python_manylinux_x86/Dockerfile#L17)

### PR DESCRIPTION
**Pull request by mehrdada**
Fixes #15770

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by mehrdada** [comment]
@matt-kwong I already checked that their travis infrastructure has uploaded from source. One way is to just drop into a shell in our docker image and check the version to double check. I'll do it now.

**Comment by mehrdada** [comment]
Confirmed~

```
bash-3.2# /opt/python/cp37-cp37m/bin/python --version
Python 3.7.0
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
