### PR TITLE
make iterators python3-compatible

### PR DESCRIPTION
**Pull request by leifurhauks**
re: #5648 , #282

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
This is OK to test.

**Comment by nathanielmanistaatgoogle** [comment]
From the sanity test failure output:
```
src/python/grpcio/grpc/_adapter/_types.py modified 2016 but copyright only extends to 2015
src/python/grpcio/grpc/framework/alpha/interfaces.py modified 2016 but copyright only extends to 2015
src/python/grpcio/grpc/framework/crust/_control.py modified 2016 but copyright only extends to 2015
src/python/grpcio/grpc/framework/face/_control.py modified 2016 but copyright only extends to 2015
src/python/grpcio/grpc/framework/face/interfaces.py modified 2016 but copyright only extends to 2015
src/python/grpcio/grpc/framework/foundation/stream_util.py modified 2016 but copyright only extends to 2015
src/python/grpcio/tests/interop/methods.py modified 2016 but copyright only extends to 2015
src/python/grpcio/tests/unit/beta/_beta_features_test.py modified 2016 but copyright only extends to 2015
src/python/grpcio/tests/unit/framework/face/testing/future_invocation_asynchronous_event_service_test_case.py modified 2016 but copyright only
```

Please address by adding `-2016` in the relevant places.

**Comment by jtattermusch** [comment]
Tests haven't finished, removing the label.

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: LGTM

**Pull request merged**
