### PR TITLE
Quick compilation fix.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by mehrdada** [comment]
I'm curious which C99 compiler fails on this? Name and shame!

**Comment by ctiller** [comment]
Want proof.

**Comment by markdroth** [comment]
Yeah, we declare loop variables inside the loop all over the place in our codebase.  This should work with any C99 compiler.  And if it doesn't, we have a lot more code to fix than just this one instance.

**Comment by nicolasnoble** [comment]
It's less about the compiler and more about build environments which fails at propagating the C99 compilation flag.

**Pull request merged**
