### PR TITLE
Update PHP composer.json files

### PR DESCRIPTION
**Pull request by stanley-cheung**
Addresses #5562 for `master`

### CODE REVIEW

**Comment by stanley-cheung** [comment]
PHP tests passed

**Comment by jtattermusch** [comment]
Putting this on hold while we are in fixit mode.

**Comment by jtattermusch** [comment]
LGTM, will merge based on keeping it green spreadsheet.

**Comment by jtattermusch** [comment]
Git checkout error for C# https://grpc-testing.appspot.com/job/gRPC_pull_requests/6877/config=dbg,language=csharp,platform=windows/ is unrelated.

**Pull request merged**
