### PR TITLE
Add `void` arguments to two function declarations.

### PR DESCRIPTION
**Pull request by MrMage**
This fixes the following warnings when compiling https://github.com/grpc/grpc-swift:

```
gRPC-Core/grpc.framework/Headers/grpc_security.h:635:74: this function declaration is not a prototype [-Wstrict-prototypes]
GRPCAPI grpc_tls_credentials_options* grpc_tls_credentials_options_create();
gRPC-Core/grpc.framework/Headers/grpc_security.h:677:76: this function declaration is not a prototype [-Wstrict-prototypes]
GRPCAPI grpc_tls_key_materials_config* grpc_tls_key_materials_config_create();
```

### CODE REVIEW

**Comment by vjpai** [comment]
Thanks for the patch! I've added a commit to resolve the formatting and project generation checks. I'll merge when tests pass.

**Comment by MrMage** [comment]
Looks like one test is still failing :-/

**Comment by vjpai** [comment]
Some of our formatting checks were broken by some recent bad pushes but I think that this would go away if you rebase your branch against master. Can you try that?

**Comment by MrMage** [comment]
> Some of our formatting checks were broken by some recent bad pushes but I think that this would go away if you rebase your branch against master. Can you try that?

Done, thanks for the info! Here's hope it will pass now.

**Comment by vjpai** [comment]
The remaining failures seem infrastructural.

**Pull request merged**
