### PR TITLE
Revert "Merge pull request #13932 from dgquintas/conn_subchannel"

### PR DESCRIPTION
**Pull request by nicolasnoble**
This reverts commit a8891634d32ad9556921faed2707fb304304c900, reversing
changes made to 47fe8507a1905c20a86df09f97c3f972d643dda5.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++

 -------------- SHRINKING                                                                        --------------
  -0.1%    -765 [None]                                                                           -31.7Ki  -0.5%
      -0.1%    -701 [Unmapped]                                                                       -31.7Ki  -0.5%
      [DEL]     -32 vtable for grpc_core::ConnectedSubchannel                                            -32  [DEL]
      [DEL]     -32 vtable for grpc_core::RefCountedWithTracing                                          -32  [DEL]
 -11.3%    -720 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc            -720 -11.3%
     -13.9%    -273 rr_connectivity_changed_locked                                                      -273 -13.9%
     -23.4%    -119 rr_ping_one_locked                                                                  -119 -23.4%
     -22.6%    -106 rr_pick_locked                                                                      -106 -22.6%
     -24.1%     -87 rr_cancel_pick_locked                                                                -87 -24.1%
     -21.6%     -82 rr_cancel_picks_locked                                                               -82 -21.6%
     -12.2%     -67 rr_shutdown_locked                                                                   -67 -12.2%
  -6.3%    -384 src/core/ext/filters/client_channel/subchannel.cc                                   -384  -6.3%
      [DEL]    -822 on_subchannel_connected                                                             -822  [DEL]
      [DEL]    -322 grpc_core::ConnectedSubchannel::CreateCall                                          -322  [DEL]
      [DEL]    -290 on_connected_subchannel_connectivity_changed                                        -290  [DEL]
      [DEL]     -76 grpc_core::ConnectedSubchannel::NotifyOnStateChange                                  -76  [DEL]
      [DEL]     -74 grpc_core::ConnectedSubchannel::ConnectedSubchannel                                  -74  [DEL]
      [DEL]     -73 grpc_core::ConnectedSubchannel::Ping                                                 -73  [DEL]
     -89.9%     -71 grpc_subchannel_get_connected_subchannel                                             -71 -89.9%
     -11.1%     -36 grpc_subchannel_unref                                                                -36 -11.1%
     -29.6%     -32 subchannel_call_destroy                                                              -32 -29.6%
      [DEL]     -23 grpc_core::ConnectedSubchannel::~ConnectedSubchannel                                 -23  [DEL]
      [DEL]     -14 grpc_core::ConnectedSubchannel::~ConnectedSubchannel                                 -14  [DEL]
      -3.0%      -8 [Unmapped]                                                                            -8  -3.0%
  -6.4%    -336 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc              -336  -6.4%
      -8.8%     -94 pf_update_locked                                                                     -94  -8.8%
      [DEL]     -89 destroy_unselected_subchannels_locked(pick_first_lb_policy*) [clone .isra.2]         -89  [DEL]
     -24.1%     -87 pf_cancel_pick_locked                                                                -87 -24.1%
     -12.2%     -67 pf_shutdown_locked                                                                   -67 -12.2%
     -38.3%     -64 pf_pick_locked                                                                       -64 -38.3%
      -1.9%     -29 pf_connectivity_changed_locked                                                       -29  -1.9%
  -1.1%    -160 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                      -160  -1.1%
      [DEL] -1.50Ki rr_handover_locked(glb_lb_policy*) [clone .part.11]                              -1.50Ki  [DEL]
      [DEL] -1.36Ki query_for_backends_locked(glb_lb_policy*) [clone .part.13]                       -1.36Ki  [DEL]
     -12.7%    -105 glb_shutdown_locked                                                                 -105 -12.7%
     -16.5%     -62 glb_cancel_pick_locked                                                               -62 -16.5%
  -0.5%     -75 src/core/ext/filters/client_channel/client_channel.cc                                -75  -0.5%
     -18.0%     -68 cc_destroy_call_elem                                                                 -68 -18.0%
      [DEL]      -9 grpc_core::RefCountedWithTracing::~RefCountedWithTracing                              -9  [DEL]
      [DEL]      -2 grpc_core::RefCountedWithTracing::~RefCountedWithTracing                              -2  [DEL]
  -2.8%     -64 src/core/ext/filters/client_channel/lb_policy/subchannel_list.cc                     -64  -2.8%
     -25.0%     -72 grpc_lb_subchannel_data_unref_subchannel                                             -72 -25.0%

  -0.2% -2.45Ki TOTAL                                                                            -33.4Ki  -0.5%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++

 -------------- SHRINKING                                                                        --------------
  -0.1%    -765 [None]                                                                           -31.7Ki  -0.5%
      -0.1%    -701 [Unmapped]                                                                       -31.7Ki  -0.5%
      [DEL]     -32 vtable for grpc_core::ConnectedSubchannel                                            -32  [DEL]
      [DEL]     -32 vtable for grpc_core::RefCountedWithTracing                                          -32  [DEL]
 -11.3%    -720 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc            -720 -11.3%
     -13.9%    -273 rr_connectivity_changed_locked                                                      -273 -13.9%
     -23.4%    -119 rr_ping_one_locked                                                                  -119 -23.4%
     -22.6%    -106 rr_pick_locked                                                                      -106 -22.6%
     -24.1%     -87 rr_cancel_pick_locked                                                                -87 -24.1%
     -21.6%     -82 rr_cancel_picks_locked                                                               -82 -21.6%
     -12.2%     -67 rr_shutdown_locked                                                                   -67 -12.2%
  -6.3%    -384 src/core/ext/filters/client_channel/subchannel.cc                                   -384  -6.3%
      [DEL]    -822 on_subchannel_connected                                                             -822  [DEL]
      [DEL]    -322 grpc_core::ConnectedSubchannel::CreateCall                                          -322  [DEL]
      [DEL]    -290 on_connected_subchannel_connectivity_changed                                        -290  [DEL]
      [DEL]     -76 grpc_core::ConnectedSubchannel::NotifyOnStateChange                                  -76  [DEL]
      [DEL]     -74 grpc_core::ConnectedSubchannel::ConnectedSubchannel                                  -74  [DEL]
      [DEL]     -73 grpc_core::ConnectedSubchannel::Ping                                                 -73  [DEL]
     -89.9%     -71 grpc_subchannel_get_connected_subchannel                                             -71 -89.9%
     -11.1%     -36 grpc_subchannel_unref                                                                -36 -11.1%
     -29.6%     -32 subchannel_call_destroy                                                              -32 -29.6%
      [DEL]     -23 grpc_core::ConnectedSubchannel::~ConnectedSubchannel                                 -23  [DEL]
      [DEL]     -14 grpc_core::ConnectedSubchannel::~ConnectedSubchannel                                 -14  [DEL]
      -3.0%      -8 [Unmapped]                                                                            -8  -3.0%
  -6.4%    -336 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc              -336  -6.4%
      -8.8%     -94 pf_update_locked                                                                     -94  -8.8%
      [DEL]     -89 destroy_unselected_subchannels_locked(pick_first_lb_policy*) [clone .isra.2]         -89  [DEL]
     -24.1%     -87 pf_cancel_pick_locked                                                                -87 -24.1%
     -12.2%     -67 pf_shutdown_locked                                                                   -67 -12.2%
     -38.3%     -64 pf_pick_locked                                                                       -64 -38.3%
      -1.9%     -29 pf_connectivity_changed_locked                                                       -29  -1.9%
  -1.1%    -160 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                      -160  -1.1%
      [DEL] -1.50Ki rr_handover_locked(glb_lb_policy*) [clone .part.11]                              -1.50Ki  [DEL]
      [DEL] -1.36Ki query_for_backends_locked(glb_lb_policy*) [clone .part.13]                       -1.36Ki  [DEL]
     -12.7%    -105 glb_shutdown_locked                                                                 -105 -12.7%
     -16.5%     -62 glb_cancel_pick_locked                                                               -62 -16.5%
  -0.5%     -75 src/core/ext/filters/client_channel/client_channel.cc                                -75  -0.5%
     -18.0%     -68 cc_destroy_call_elem                                                                 -68 -18.0%
      [DEL]      -9 grpc_core::RefCountedWithTracing::~RefCountedWithTracing                              -9  [DEL]
      [DEL]      -2 grpc_core::RefCountedWithTracing::~RefCountedWithTracing                              -2  [DEL]
  -2.8%     -64 src/core/ext/filters/client_channel/lb_policy/subchannel_list.cc                     -64  -2.8%
     -25.0%     -72 grpc_lb_subchannel_data_unref_subchannel                                             -72 -25.0%

  -0.2% -2.45Ki TOTAL                                                                            -33.4Ki  -0.5%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
issues: #13546 #13445 #13477

**Pull request merged**
