### PR TITLE
Show Xcode versions

### PR DESCRIPTION
**Pull request by matt-kwong**

### CODE REVIEW

**Comment by matt-kwong** [comment]
cc @muxi

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by matt-kwong** [comment]
@muxi 
```
++ ls /Applications/Xcode.app /Applications/Xcode_7.2.app /Applications/Xcode_7.3.1.app /Applications/Xcode_8.1.app /Applications/Xcode_8.2.1.app /Applications/Xcode_8.2.app /Applications/Xcode_8.app
/Applications/Xcode.app:
Contents

/Applications/Xcode_7.2.app:
Contents

/Applications/Xcode_7.3.1.app:
Contents

/Applications/Xcode_8.1.app:
Contents

/Applications/Xcode_8.2.1.app:
Contents

/Applications/Xcode_8.2.app:
Contents

/Applications/Xcode_8.app:
Contents
```
It looks like 8.2.1 is the latest version and we would need to upgrade the OS before upgrading Xcode. This doesn't explain why ObjC tests started failing though.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__512.opt.old: 1


[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
