### PR TITLE
Add synchronization to a read of current writer state.

### PR DESCRIPTION
**Pull request by var-const**
Fixes the data race in #15368.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @var-const isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by var-const** [comment]
CLA.

**Comment by var-const** [comment]
This is a sample fix intended to demonstrate the issue.

Note: I've had (a lot of) trouble trying to run Objective-C tests locally. I gave up upon encountering:
```
=== BUILD TARGET RemoteTest OF PROJECT Pods WITH CONFIGURATION Test ===
Check dependencies
/Users/varconst/grpc-2/grpc/src/objective-c/tests/RemoteTestClient/Test.pbrpc.m:8:9: error: non-portable path to file '<protobuf/Empty.pbobjc.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
#import <Protobuf/Empty.pbobjc.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
        <protobuf/Empty.pbobjc.h>
1 error generated.
/Users/varconst/grpc-2/grpc/src/objective-c/tests/RemoteTestClient/Test.pbobjc.m:17:10: error: non-portable path to file '<protobuf/Empty.pbobjc.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-pat
h]
 #import <Protobuf/Empty.pbobjc.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
         <protobuf/Empty.pbobjc.h>
/Users/varconst/grpc-2/grpc/src/objective-c/tests/RemoteTestClient/Test.pbrpc.m:8:9: error: non-portable path to file '<protobuf/Empty.pbobjc.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
#import <Protobuf/Empty.pbobjc.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
        <protobuf/Empty.pbobjc.h>
1 error generated.
```
Hopefully Travis checks will take care of this.

**Comment by muxi** [comment]
This has been covered in #17578.

**Pull request closed without merging**
