### PR TITLE
Make should generate pkg-config file for gpr as well

### PR DESCRIPTION
**Pull request by jtattermusch**
tentative fix for https://github.com/grpc/grpc/issues/15166.

### CODE REVIEW

**Comment by jtattermusch** [comment]
@coryan  can you help testing this?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by coryan** [comment]
Thanks for the quick turnaround, I know you folks are busy.  This seems to fix most problems, however, I think you also need to change the `grpc.pc` file to work in the case of static libraries.  This is the script I used to test this:

```Dockerfile
FROM ubuntu:16.04
MAINTAINER "Carlos O'Ryan <coryan@google.com>"

ARG NCPU=8

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  gcc \
  g++ \
  golang \
  git \
  cmake \
  libssl-dev \
  libtool \
  lsb-release \
  make \
  tar \
  wget \
  zlib1g-dev

RUN apt-get update && apt-get install -y curl unzip automake
WORKDIR /var/tmp/build-dependencies
RUN wget -q https://github.com/google/protobuf/archive/v3.5.2.tar.gz
RUN tar -xf v3.5.2.tar.gz
WORKDIR /var/tmp/build-dependencies/protobuf-3.5.2
RUN ./autogen.sh && ./configure && make -j ${NCPU} && make install
RUN ldconfig

WORKDIR /var/tmp/build-dependencies
RUN apt-get remove -y libc-ares-dev libc-ares2
RUN wget -q https://github.com/c-ares/c-ares/archive/cares-1_14_0.tar.gz
RUN tar -xf cares-1_14_0.tar.gz
WORKDIR /var/tmp/build-dependencies/c-ares-cares-1_14_0
RUN ./buildconf && ./configure && make -j ${NCPU} && make install
RUN ldconfig

ARG SHA=4563cf04886fd71ea7ffb89b1095ab6293a5fe59
WORKDIR /var/tmp/build-dependencies
RUN wget -q https://github.com/jtattermusch/grpc/archive/${SHA}.tar.gz
RUN tar -xf ${SHA}.tar.gz
WORKDIR /var/tmp/build-dependencies/grpc-${SHA}
RUN make -j ${NCPU} && make install

RUN ls -l /usr/local/lib/pkgconfig
RUN if [ ! -f /usr/local/lib/pkgconfig/gpr.pc ]; then echo "Did not install gpr.pc"; exit 1; fi

RUN pkg-config gpr --libs
RUN pkg-config gpr --version
RUN pkg-config grpc++ --libs --static | grep -q "gpr"
```

**Comment by coryan** [comment]
Ping.

**Comment by jtattermusch** [comment]
@coryan   I updated the PR, now I get:
```
$ PKG_CONFIG_PATH=$(pwd) pkg-config grpc++ --libs --static
-L/usr/local/google/home/jtattermusch/github/grpc/testinstall/lib -lgrpc++ -lgrpc -lgpr -lz -lssl -lcrypto -ldl -pthread
```

```
$ PKG_CONFIG_PATH=$(pwd) pkg-config grpc++_unsecure --libs --static
-L/usr/local/google/home/jtattermusch/github/grpc/testinstall/lib -lgrpc++ -lgrpc -lgpr -lz
```

Does that look alright to you?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by jtattermusch** [comment]
@murgatroid99  can you please review?

**Comment by jtattermusch** [comment]
@coryan if you are happy with the changes, I'll merge as soon as the tests pass.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,951,097      Total (=)      1,951,097

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,661,414      Total (>)     10,661,410

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by coryan** [comment]
@jtattermusch the changes look good in that they solve the problem with `libgpr`. Did you see my additional question in #15166 about `libaddress_sorting`?

**Comment by jtattermusch** [comment]
@coryan  I'll address the `libaddress_sorting` problem in a separate PR.

**Pull request merged**
