### PR TITLE
cleanup gens/ directory after nanopb check

### PR DESCRIPTION
**Pull request by dgquintas**
This should take care of the `warning: failed to remove gens/src/proto/grpc/lb/v0/load_balancer.pb.c` messages on jenkins

### CODE REVIEW

**Comment by dgquintas** [comment]
@ctiller / @nicolasnoble   as @vjpai isn't currently available.

**Comment by nicolasnoble** [comment]
So, the clean way is to actually generate the files in a temporary folder instead. If your script gets interrupted for any reason, it won't reach the rm, and the files will still be ligering around.

Please use the `BUILDDIR` variable instead, as shown here: 

https://github.com/grpc/grpc/blob/release-0_13_0/Rakefile#L84

Or

https://github.com/grpc/grpc/blob/release-0_13_0/src/ruby/ext/grpc/extconf.rb#L85

**Comment by ctiller** [comment]
The gens/ trick was needed when we needed clang format on the generated
files. Now that we don't it's likely safe to use /tmp again.

**Comment by dgquintas** [comment]
Updated. PTAL.

**Comment by vjpai** [comment]
Sanity is still broken: 
stderr: warning: failed to remove gens/src/proto/grpc/lb/v0/load_balancer.pb.c
warning: failed to remove gens/src/proto/grpc/lb/v0/load_balancer.pb.h

Everything else is broken too, but why?

**Comment by dgquintas** [comment]
I'm regenerating the workers to fix that

**Comment by dgquintas** [comment]
The workers will keep on breaking until the changes in the PR go in.

**Pull request merged**
