### PR TITLE
Change metadata names used by the instrumentation.

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by ctiller** [comment]
You'll need to run tools/distrib/clang-format-code.sh

**Comment by bogdandrutu** [comment]
Done. PTAL.

**Comment by bogdandrutu** [comment]
Done.

**Comment by bogdandrutu** [comment]
Any chance we can get this merged?

**Comment by dgquintas** [comment]
I'm now keeping an eye on this and will merge ASAP.

**Comment by dgquintas** [comment]
Merging on mobile. Will comment on failures later

**Comment by dgquintas** [comment]
Issues: #9542 #10640 #10576

**Pull request merged**
