### PR TITLE
[3PI Support] Add aws-sourced external account credentials

### PR DESCRIPTION
**Pull request by renkelvin**
### Structure of 3PI Support
The implementation of 3PI support is organized as follows:
1. Base external account credentials class [#24208]
2. Subclasses to base external account credentials
    a. url-sourced credentials [#24411]
    b. file-sourced credentials [#24526]
    c-prerequisites. utility to sign Aws requests [#24618]
    **c. aws-sourced credentials [This PR]**
3. Internal and public apis

### Description of this PR
There are 3 main steps to retrieve the subject token for aws-sourced credentials:
1. Retrieve aws region and credentials from environment variables or http calls.
2. Sign an http request using the `AwsRequestSigner` with the variables from Step 1.
3. Build the subject token with the signed request headers from Step2.

@markdroth Please take a look and let me know if you have any questions. Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24733)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks like a reasonable start.

Please let me know if you have any questions.  Thanks!

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24733#-:-MMHrfWPAjSLrp6bhBQv:bctipna)* status: all files reviewed, 13 unresolved discussions (waiting on @renkelvin)

___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.h, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHcy4f3PGyLpkzVRXq:-MMHcy4g1Pxu1qc29RG2:b-rrq3jp) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.h#L71)):*
> ```objc
>   std::string token_;
> 
>   AwsRequestSigner* signer_ = nullptr;
> ```

Suggest making this a `std::unique_ptr<>` so that you don't need to manually delete it in the dtor.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHc29v4mSznZGndRQ9:-MMHc29w4MYJamj2RRPJ:b-sd23l7) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L38)):*
> ```cpp
> 
> std::string UrlEncode(const absl::string_view& s) {
>   std::string hex("0123456789ABCDEF");
> ```

This can be `const char*`.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHcC3a2oatPeMpcxUM:-MMHcC3a2oatPeMpcxUN:bmj0unm) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L39)):*
> ```cpp
> std::string UrlEncode(const absl::string_view& s) {
>   std::string hex("0123456789ABCDEF");
>   std::vector<std::string> result_vector;
> ```

This is horribly inefficient.  It's basically allocating a separate `std::string` for almost every character in the string.

Instead, I suggest just declaring a single `std::string` for the output, calling its `reserve()` method to pre-allocate the size of the input string (which is a lower bound), and then just adding one character to the string at a time.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 145 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHekk74fvd-srKTBYC:-MMHekk74fvd-srKTBYD:b-iwsnah) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L145)):*
> ```cpp
> 
> void AwsExternalAccountCredentials::RetrieveRegion() {
>   char* region_from_env = gpr_getenv(kRegionEnvVar);
> ```

The result of `gpr_getenv()` is a newly allocated string that the caller is responsible for freeing.

I suggest storing this as a `UniquePtr<char>` instead of a `char*`.  That will automatically free the string when it goes out of scope.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 197 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHh_smEbWM0l85iNI4:-MMHh_smEbWM0l85iNI5:bnzfvjv) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L197)):*
> ```cpp
>   // Remove the last letter of availability zone to get pure region
>   region_ =
>       std::string(ctx_->response.body).substr(0, strlen(ctx_->response.body));
> ```

No need to call `strlen()`, since the length of the body is already available in `ctx_->response.body_length`.

Calling `.substr(0, length)` is a no-op, because it basically just gives you back the original string.  The comment says you're removing the last letter, but it doesn't look like this is actually doing that.  Did you mean to use `length - 1`  here?

Converting the body to a `std::string` and then immediately calling `substr()` to allocate another string is inefficient.  Instead, I suggest writing this using something like this (assuming that you actually did intend to ignore the last character of the body):

```
absl::string_view response_body(ctx_->response.body,
                                ctx_->response.body_length);
region_ = std::string(response_body.substr(0, response_body.size() - 1));
```
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 198 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHhR2Y4nM6yQ7vyUCg:-MMHhR2Y4nM6yQ7vyUCh:bh1w4w3) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L198)):*
> ```cpp
>   region_ =
>       std::string(ctx_->response.body).substr(0, strlen(ctx_->response.body));
> ```

Please remove blank line.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 251 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHkIiU8UfPH5C4yv1z:-MMHkIiU8UfPH5C4yv2-:bcat8wh) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L251)):*
> ```cpp
> 
> void AwsExternalAccountCredentials::RetrieveSigningKeys() {
>   char* access_key_id_from_env = gpr_getenv(kAccessKeyIdEnvVar);
> ```

Same comments as above: These strings need to be freed.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 268 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHnIXf-dMlwGNpQL00:-MMHnIXf-dMlwGNpQL01:b6b27dq) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L268)):*
> ```cpp
>     return;
>   }
>   std::string url_with_role_name = url_ + "/" + role_name_;
> ```

Please use `absl::StrCat()` instead of `+` here.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 363 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHpDEqD4Zf__raJbj5:-MMHpDEqD4Zf__raJbj6:b-l9p11n) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L363)):*
> ```cpp
>   std::string url = absl::StrReplaceAll(regional_cred_verification_url_,
>                                         {{"{region}", region_}});
>   signer_ = new AwsRequestSigner(access_key_id_, secret_access_key_, token_,
> ```

If `signer_` is not null in `RetrieveSubjectToken()`, we will call this function and immediately recreate the signer.  This means that we're recreating the signer for each individual request, which means that we're not getting any benefit from the caching in the signer.  I think we should reuse the signer that we already have in this case.

Also, the way you have this code right now, this is a memory leak, because you're not freeing the previous object before you allocate this new one and change `signer_` to point to it.  But if you change `signer_` to be a `unique_ptr<>` as I suggest elsewhere, that problem will go away.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 383 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHnutM-PEfsupPcI3R:-MMHnutM-PEfsupPcI3S:b-cubpct) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L383)):*
> ```cpp
>   }
>   // Construct subject token
>   std::vector<Json> headers_vector;
> ```

Please use `Json::Array` here.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 389 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHnxqZ0x1xsVBOT0oD:-MMHnxqZ0x1xsVBOT0oE:bh55rgh) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L389)):*
> ```cpp
>   headers_vector.push_back(
>       Json({{"key", "x-amz-date"}, {"value", headers["x-amz-date"]}}));
>   std::map<std::string, Json> object{{"url", Json(url)},
> ```

Please use `Json::Object` here.
___
*[test/core/security/credentials_test.cc, line 2079 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHr3il3aTuzIDgfvkt:-MMHr3il3aTuzIDgfvku:bh1w4w3) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/test/core/security/credentials_test.cc#L2079)):*
> ```cpp
>                     "https://www.googleapis.com/auth/cloud-platform") == 0);
>   grpc_uri_destroy(uri);
> ```

Please remove blank line.
___
*[test/core/security/credentials_test.cc, line 2601 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHrSSlBbYwvS7G3jj_:-MMHrSSlBbYwvS7G3jja:b-vhjoe1) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/test/core/security/credentials_test.cc#L2601)):*
> ```cpp
> }
> 
> static void test_aws_external_account_creds_success(void) {
> ```

It looks like there are a lot more test cases to be added here.  We need one for every different combination of paths through the code and one for each possible error.

**Review by renkelvin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24733)* status: all files reviewed, 13 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.h, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHcy4f3PGyLpkzVRXq:-MMHw-R06ydrqqVs9HP0:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.h#L71)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest making this a `std::unique_ptr<>` so that you don't need to manually delete it in the dtor.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHc29v4mSznZGndRQ9:-MMHw8ay3-htsHXv0l6o:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This can be `const char*`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHcC3a2oatPeMpcxUM:-MMHxOgmC9-5jamU1Xwb:b-tr293q) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is horribly inefficient.  It's basically allocating a separate `std::string` for almost every character in the string.

Instead, I suggest just declaring a single `std::string` for the output, calling its `reserve()` method to pre-allocate the size of the input string (which is a lower bound), and then just adding one character to the string at a time.
</blockquote></details>

Done.

Note that "+=" is used when a char is parsed to "%XY".
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 145 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHekk74fvd-srKTBYC:-MMHyWNP-5m8fIaRLSQK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L145)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The result of `gpr_getenv()` is a newly allocated string that the caller is responsible for freeing.

I suggest storing this as a `UniquePtr<char>` instead of a `char*`.  That will automatically free the string when it goes out of scope.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 197 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHh_smEbWM0l85iNI4:-MMI-0615ZiKGU8_ny8p:bg0wann) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L197)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need to call `strlen()`, since the length of the body is already available in `ctx_->response.body_length`.

Calling `.substr(0, length)` is a no-op, because it basically just gives you back the original string.  The comment says you're removing the last letter, but it doesn't look like this is actually doing that.  Did you mean to use `length - 1`  here?

Converting the body to a `std::string` and then immediately calling `substr()` to allocate another string is inefficient.  Instead, I suggest writing this using something like this (assuming that you actually did intend to ignore the last character of the body):

```
absl::string_view response_body(ctx_->response.body,
                                ctx_->response.body_length);
region_ = std::string(response_body.substr(0, response_body.size() - 1));
```
</blockquote></details>

Done.

Yeah, meant `length - 1`.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 198 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHhR2Y4nM6yQ7vyUCg:-MMI-58q2bhzhFZcoya6:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L198)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 251 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHkIiU8UfPH5C4yv1z:-MMI-7fABSpI67G9XaxZ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L251)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same comments as above: These strings need to be freed.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 268 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHnIXf-dMlwGNpQL00:-MMI2-RqCe63l9jGs8Om:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L268)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `absl::StrCat()` instead of `+` here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 363 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHpDEqD4Zf__raJbj5:-MMI2Iff2zuz9mECHbuH:bli8e1k) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L363)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If `signer_` is not null in `RetrieveSubjectToken()`, we will call this function and immediately recreate the signer.  This means that we're recreating the signer for each individual request, which means that we're not getting any benefit from the caching in the signer.  I think we should reuse the signer that we already have in this case.

Also, the way you have this code right now, this is a memory leak, because you're not freeing the previous object before you allocate this new one and change `signer_` to point to it.  But if you change `signer_` to be a `unique_ptr<>` as I suggest elsewhere, that problem will go away.
</blockquote></details>

Done.

Yeah, should have checked if `signer_` exists before  creating.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 383 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHnutM-PEfsupPcI3R:-MMI3dTTDH-ubnUiV3S-:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L383)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `Json::Array` here.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 389 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHnxqZ0x1xsVBOT0oD:-MMI4Hv0AXvsa1qzdDJa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L389)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please use `Json::Object` here.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2079 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHr3il3aTuzIDgfvkt:-MMI4_sH3Eo6Lsor845q:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/test/core/security/credentials_test.cc#L2079)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please remove blank line.
</blockquote></details>

Done.
___
*[test/core/security/credentials_test.cc, line 2601 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHrSSlBbYwvS7G3jj_:-MMIS5Gt3R8WB-t4mcsa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/test/core/security/credentials_test.cc#L2601)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It looks like there are a lot more test cases to be added here.  We need one for every different combination of paths through the code and one for each possible error.
</blockquote></details>

Done.

**Review by markdroth — CHANGES_REQUESTED** [review]
This is moving in the right direction.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24733#-:-MMRtkgA6-Ax3kUKtMgC:b-qjvg5x)* status: all files reviewed, 5 unresolved discussions (waiting on @renkelvin)

___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.h, line 70 at r2](https://reviewable.io/reviews/grpc/grpc/24733#-MMRagu9A3xhxUF9mrZu:-MMRagu9A3xhxUF9mrZv:bp6e5o6) ([raw file](https://github.com/grpc/grpc/blob/13569e416f803d515e3dd5c4c954a6a02ebc8497/src/core/lib/security/credentials/external/aws_external_account_credentials.h#L70)):*
> ```objc
>   std::string token_;
> 
>   std::unique_ptr<AwsRequestSigner> signer_ = nullptr;
> ```

No need for `= nullptr`.  That's the default for a `unique_ptr`.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 39 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHcC3a2oatPeMpcxUM:-MMRatb-63bXHkHzczdo:b-uem7zk) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L39)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.

Note that "+=" is used when a char is parsed to "%XY".
</blockquote></details>

Don't use `+=` there.  Instead, please call `push_back()` for each of the 3 characters individually.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 268 at r1](https://reviewable.io/reviews/grpc/grpc/24733#-MMHnIXf-dMlwGNpQL00:-MMRbioE-SnsXITvSuVy:bmlcju6) ([raw file](https://github.com/grpc/grpc/blob/0c9666e7e4bf73c7b35545cddfd67de148adabcd/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L268)):*
<details><summary><i>Previously, renkelvin (Chuan Ren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can pass as many params as you want to `absl::StrCat()`, so you can just say `absl::StrCat(url_, "/", role_name_)`.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 141 at r2](https://reviewable.io/reviews/grpc/grpc/24733#-MMRbMthD8E1iFSbiXaz:-MMRbMtiEPL96atgklRE:b3v3s27) ([raw file](https://github.com/grpc/grpc/blob/13569e416f803d515e3dd5c4c954a6a02ebc8497/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L141)):*
> ```cpp
> 
> void AwsExternalAccountCredentials::RetrieveRegion() {
>   UniquePtr<char> region_from_env = UniquePtr<char>(gpr_getenv(kRegionEnvVar));
> ```

Instead of saying `type foo = type(...)`, please say `type foo(...)`.

Please fix throughout.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 361 at r2](https://reviewable.io/reviews/grpc/grpc/24733#-MMRc6Q84o8Ty4Tlz6FP:-MMRc6Q84o8Ty4Tlz6FQ:bilnfb4) ([raw file](https://github.com/grpc/grpc/blob/13569e416f803d515e3dd5c4c954a6a02ebc8497/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L361)):*
> ```cpp
> void AwsExternalAccountCredentials::BuildSubjectToken() {
>   grpc_error* error = GRPC_ERROR_NONE;
>   std::string url = absl::StrReplaceAll(regional_cred_verification_url_,
> ```

Once the signer is created, isn't this value going to be the same for all calls?  If so, it should be cached as well.

**Review by renkelvin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24733)* status: all files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.h, line 70 at r2](https://reviewable.io/reviews/grpc/grpc/24733#-MMRagu9A3xhxUF9mrZu:-MMRxfyh48GmU0zQrzxO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/13569e416f803d515e3dd5c4c954a6a02ebc8497/src/core/lib/security/credentials/external/aws_external_account_credentials.h#L70)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for `= nullptr`.  That's the default for a `unique_ptr`.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 141 at r2](https://reviewable.io/reviews/grpc/grpc/24733#-MMRbMthD8E1iFSbiXaz:-MMRyvrBAnIOmMu28FSc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/13569e416f803d515e3dd5c4c954a6a02ebc8497/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L141)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of saying `type foo = type(...)`, please say `type foo(...)`.

Please fix throughout.
</blockquote></details>

Done.
___
*[src/core/lib/security/credentials/external/aws_external_account_credentials.cc, line 361 at r2](https://reviewable.io/reviews/grpc/grpc/24733#-MMRc6Q84o8Ty4Tlz6FP:-MMRzO_S-43b2Jwqj_MV:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/13569e416f803d515e3dd5c4c954a6a02ebc8497/src/core/lib/security/credentials/external/aws_external_account_credentials.cc#L361)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Once the signer is created, isn't this value going to be the same for all calls?  If so, it should be cached as well.
</blockquote></details>

Done.

**Comment by markdroth** [comment]
This looks good. I've triggered the tests.

**Comment by renkelvin** [comment]
Fixed 2 styling issue that CI complains. Please re-trigger the tests. Thanks!

**Comment by markdroth** [comment]
Re-triggered the tests.

**Comment by renkelvin** [comment]
Seems there is something wrong with the tooling.

**Comment by markdroth** [comment]
There was a problem with our cloud project in which the tests run.  I've re-triggered the tests, so let's see if the problem is cleared up now.

**Comment by renkelvin** [comment]
Seems one of the checks failed https://source.cloud.google.com/results/invocations/dd77d0c0-df0b-4629-8879-a6061c4b030f/targets
Commits squashed.

**Comment by markdroth** [comment]
That failure looks like an infrastructure timeout.

I've re-triggered the tests.

**Comment by renkelvin** [comment]
The CI is green now, please help merge the pr. Thanks!

**Review by markdroth — APPROVED** [review]

**Pull request merged**
