### PR TITLE
Backport: Don't resolve if there is a resolution timer

### PR DESCRIPTION
**Pull request by jtattermusch**
Backports #15156 to v1.11.x

### CODE REVIEW

**Comment by jtattermusch** [comment]
@mehrdada  can we cut and release v1.11.x after this is merged?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.3% +2.03Ki [None]                                                                               +5.42Ki  +0.1%
      +0.3% +1.97Ki [Unmapped]                                                                           +5.39Ki  +0.1%
      [NEW]     +24 grpc_handshaker_trace                                                                      0  [ = ]
       +33%      +8 fail_handshaker_vtable                                                                    +8   +33%
       +33%      +8 security_handshaker_vtable                                                                +8   +33%
       +33%      +8 http_connect_handshaker_vtable                                                            +8   +33%
      +0.4%      +5 [None]                                                                                     0  [ = ]
      [NEW]      +4 g_support_so_reuseport                                                                     0  [ = ]
      [NEW]      +4 g_probe_so_reuesport_once                                                                  0  [ = ]
  +0.9% +2.19Ki [Other]                                                                              +2.19Ki  +0.9%
  +2.7%    +817 src/core/ext/filters/client_channel/client_channel.cc                                   +817  +2.7%
      [NEW]    +471 execute_closures_in_call_combiner(grpc_call_element*, char const*, closure_to_execut    +471  [NEW]
      [NEW]    +181 add_retriable_send_message_op(grpc_call_element*, subchannel_call_retry_state*, subc    +181  [NEW]
      [NEW]    +163 add_closure_for_subchannel_batch(client_channel_call_data*, grpc_transport_stream_op    +163  [NEW]
      +1.9%    +133 [Other]                                                                                 +133  +1.9%
      [NEW]    +110 free_cached_send_message                                                                +110  [NEW]
      [NEW]     +67 free_cached_send_initial_metadata                                                        +67  [NEW]
      [NEW]     +67 free_cached_send_trailing_metadata                                                       +67  [NEW]
       +11%     +61 grpc_core::SliceHashTable<grpc_core::RefCountedPtr<grpc_core::internal::ClientChanne     +61   +11%
      +9.2%     +55 grpc_core::RefCountedPtr<grpc_core::SliceHashTable<grpc_core::RefCountedPtr<grpc_cor     +55  +9.2%
      +5.7%     +53 pick_callback_start_locked                                                               +53  +5.7%
       +29%     +52 grpc_core::SliceHashTable<grpc_core::RefCountedPtr<grpc_core::internal::ClientChanne     +52   +29%
       +32%     +49 request_reresolution_locked                                                              +49   +32%
       +12%     +47 [Unmapped]                                                                               +47   +12%
      +8.9%     +46 cc_destroy_call_elem                                                                     +46  +8.9%
       +17%     +43 cc_init_call_elem                                                                        +43   +17%
      +7.3%     +39 pending_batches_fail                                                                     +39  +7.3%
      [NEW]     +37 grpc_core::internal::ClientChannelMethodParams::~ClientChannelMethodParams               +37  [NEW]
      +2.7%     +36 cc_start_transport_stream_op_batch                                                       +36  +2.7%
      [NEW]     +34 grpc_core::internal::ClientChannelMethodParams::~ClientChannelMethodParams               +34  [NEW]
      +0.9%     +33 on_resolver_result_changed_locked                                                        +33  +0.9%
      +1.8%     +28 maybe_retry                                                                              +28  +1.8%
   +36%    +607 src/core/lib/channel/handshaker.cc                                                      +607   +36%
      +230%    +444 call_next_handshaker_locked                                                             +444  +230%
       +63%     +83 grpc_handshake_manager_add                                                               +83   +63%
      [NEW]     +48 _GLOBAL__sub_I_handshaker.cc                                                             +48  [NEW]
      +3.5%     +15 grpc_handshake_manager_do_handshake                                                      +15  +3.5%
      +8.4%     +12 grpc_handshake_manager_pending_list_add                                                  +12  +8.4%
      [NEW]      +8 grpc_handshaker_name                                                                      +8  [NEW]
      +6.7%      +7 grpc_handshake_manager_pending_list_remove                                                +7  +6.7%
  +1.7%    +576 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +576  +1.7%
      +107%    +288 init_keepalive_ping_locked                                                              +288  +107%
      +5.9%     +49 destroy_stream_locked                                                                    +49  +5.9%
      +1.1%     +40 perform_stream_op_locked                                                                 +40  +1.1%
      +5.7%     +37 [Unmapped]                                                                               +37  +5.7%
      +2.2%     +23 grpc_chttp2_maybe_complete_recv_message                                                  +23  +2.2%
      +3.9%     +22 grpc_chttp2_unref_transport                                                              +22  +3.9%
      +0.8%     +18 grpc_chttp2_cancel_stream                                                                +18  +0.8%
      +4.6%     +15 perform_stream_op                                                                        +15  +4.6%
      +5.9%     +15 start_bdp_ping_locked                                                                    +15  +5.9%
      +2.1%     +14 maybe_start_some_streams                                                                 +14  +2.1%
      +2.2%     +13 grpc_core::Chttp2IncomingByteStream::NextLocked                                          +13  +2.2%
      +3.1%      +9 finish_bdp_ping_locked                                                                    +9  +3.1%
      +0.8%      +8 grpc_chttp2_mark_stream_closed                                                            +8  +0.8%
      +4.3%      +8 schedule_bdp_ping_locked                                                                  +8  +4.3%
      +3.2%      +6 grpc_core::Chttp2IncomingByteStream::PublishError                                         +6  +3.2%
      +3.0%      +5 grpc_chttp2_parsing_accept_stream                                                         +5  +3.0%
      +0.7%      +5 write_action_begin_locked                                                                 +5  +0.7%
      +3.6%      +3 [Other]                                                                                   +3  +3.6%
      +3.2%      +3 connectivity_state_set                                                                    +3  +3.2%
      +0.8%      +3 benign_reclaimer_locked                                                                   +3  +0.8%
      +0.9%      +3 destructive_reclaimer_locked                                                              +3  +0.9%
  +8.1%    +432 src/core/lib/iomgr/udp_server.cc                                                        +432  +8.1%
      [NEW] +1.16Ki grpc_udp_server_add_port                                                             +1.16Ki  [NEW]
       +11%    +122 add_socket_to_server                                                                    +122   +11%
       +15%     +29 grpc_udp_server_create                                                                   +29   +15%
      +2.0%      +6 GrpcUdpListener::GrpcUdpListener                                                          +6  +2.0%
      +2.0%      +4 GrpcUdpListener::do_write                                                                 +4  +2.0%
      +1.8%      +3 GrpcUdpListener::do_read                                                                  +3  +1.8%
  +3.3%    +353 src/core/lib/iomgr/ev_epollex_linux.cc                                                  +353  +3.3%
       +43%    +199 pollable_process_events                                                                 +199   +43%
      +2.1%     +41 pollset_work                                                                             +41  +2.1%
      +6.5%     +18 pollable_add_fd                                                                          +18  +6.5%
      +1.9%     +16 pollset_set_add_pollset                                                                  +16  +1.9%
      +1.4%     +11 pollset_set_add_pollset_set                                                              +11  +1.4%
      +6.2%     +10 unref_by(grpc_fd*, int) [clone .constprop.15]                                            +10  +6.2%
      +1.8%      +9 pollset_transition_pollable_from_empty_to_fd_locked                                       +9  +1.8%
       +11%      +8 pollset_init                                                                              +8   +11%
      +6.2%      +8 pollset_maybe_finish_shutdown                                                             +8  +6.2%
      +2.7%      +8 pollset_transition_pollable_from_fd_to_multi_locked                                       +8  +2.7%
      +3.5%      +7 fd_orphan                                                                                 +7  +3.5%
      +3.9%      +4 pollset_shutdown                                                                          +4  +3.9%
      +0.7%      +3 pollset_kick                                                                              +3  +0.7%
      +0.5%      +3 kick_one_worker                                                                           +3  +0.5%
      +1.2%      +3 pollset_set_del_fd                                                                        +3  +1.2%
      +1.1%      +3 pollset_set_del_pollset                                                                   +3  +1.1%
      +0.6%      +2 [Unmapped]                                                                                +2  +0.6%
  +9.2%    +342 src/core/lib/channel/channel_args.cc                                                    +342  +9.2%
      [NEW]    +316 grpc_channel_args_string                                                                +316  [NEW]
      +8.8%     +15 [Unmapped]                                                                               +15  +8.8%
      +4.7%      +6 grpc_channel_args_set_compression_algorithm                                               +6  +4.7%
      +1.1%      +5 grpc_channel_args_compression_algorithm_set_state                                         +5  +1.1%
  +6.5%    +225 src/core/lib/iomgr/socket_utils_common_posix.cc                                         +225  +6.5%
      [NEW]    +105 probe_so_reuseport_once                                                                 +105  [NEW]
      [NEW]     +39 grpc_is_socket_reuse_port_supported                                                      +39  [NEW]
       +29%     +38 [Unmapped]                                                                               +38   +29%
      +7.0%      +9 grpc_set_socket_rcvbuf                                                                    +9  +7.0%
      +7.0%      +9 grpc_set_socket_sndbuf                                                                    +9  +7.0%
      +3.5%      +6 grpc_set_socket_with_mutator                                                              +6  +3.5%
      +1.9%      +4 grpc_set_socket_cloexec                                                                   +4  +1.9%
      +1.9%      +4 grpc_set_socket_nonblocking                                                               +4  +1.9%
      +2.5%      +4 grpc_set_socket_ip_pktinfo_if_possible                                                    +4  +2.5%
      +2.4%      +4 grpc_set_socket_ipv6_recvpktinfo_if_possible                                              +4  +2.4%
      +1.0%      +2 error_for_fd(int, grpc_resolved_address const*) [clone .part.1]                           +2  +1.0%
      +1.6%      +1 grpc_inet_ntop                                                                            +1  +1.6%
  +1.3%    +193 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                          +193  +1.3%
      +5.9%     +92 grpc_core::(anonymous namespace)::GrpcLb::StartBalancerCallLocked                        +92  +5.9%
       +22%     +46 grpc_core::(anonymous namespace)::GrpcLb::OnRoundRobinRequestReresolutionLocked          +46   +22%
      +1.8%     +34 grpc_core::(anonymous namespace)::GrpcLb::CreateOrUpdateRoundRobinPolicyLocked() [cl     +34  +1.8%
      +4.9%     +17 [Unmapped]                                                                               +17  +4.9%
      +6.8%     +14 grpc_core::(anonymous namespace)::GrpcLb::PendingPickSetMetadataAndContext               +14  +6.8%
      +3.5%     +14 grpc_core::(anonymous namespace)::GrpcLb::~GrpcLb                                        +14  +3.5%
      +1.8%     +12 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::OnBalancerStatusReceive     +12  +1.8%
      +1.9%      +8 grpc_core::(anonymous namespace)::GrpcLb::PickFromRoundRobinPolicyLocked                  +8  +1.9%
      +1.4%      +7 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::SendClientLoadReportLoc      +7  +1.4%
      +2.2%      +7 grpc_core::(anonymous namespace)::GrpcLb::OnBalancerChannelConnectivityChangedLocked      +7  +2.2%
      +2.8%      +6 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::~BalancerCallState           +6  +2.8%
      +0.4%      +5 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::OnBalancerMessageReceiv      +5  +0.4%
      +1.3%      +4 grpc_core::(anonymous namespace)::GrpcLb::UpdateConnectivityStateFromRoundRobinPolic      +4  +1.3%
      +0.7%      +3 grpc_core::(anonymous namespace)::GrpcLb::PickLocked                                      +3  +0.7%
      +1.3%      +3 grpc_core::(anonymous namespace)::GrpcLb::UpdateLocked                                    +3  +1.3%
      +3.4%      +3 grpc_core::(anonymous namespace)::GrpcLb::BalancerCallState::Orphan                       +3  +3.4%
   +13%    +134 src/core/lib/gpr/sync_posix.cc                                                          +134   +13%
      +167%     +65 [Unmapped]                                                                               +65  +167%
      +5.5%     +13 gpr_cv_init                                                                              +13  +5.5%
      +3.0%      +7 gpr_cv_wait                                                                               +7  +3.0%
      +9.8%      +6 gpr_cv_broadcast                                                                          +6  +9.8%
      +9.8%      +6 gpr_cv_destroy                                                                            +6  +9.8%
      +9.8%      +6 gpr_cv_signal                                                                             +6  +9.8%
      +9.8%      +6 gpr_mu_destroy                                                                            +6  +9.8%
      +9.8%      +6 gpr_mu_lock                                                                               +6  +9.8%
      +9.8%      +6 gpr_mu_unlock                                                                             +6  +9.8%
      +9.8%      +6 gpr_once_init                                                                             +6  +9.8%
      +6.3%      +4 gpr_mu_init                                                                               +4  +6.3%
      +4.2%      +3 gpr_mu_trylock                                                                            +3  +4.2%
  +1.0%    +128 src/core/ext/transport/inproc/inproc_transport.cc                                       +128  +1.0%
      +1.4%     +41 op_state_machine                                                                         +41  +1.4%
      +2.1%     +19 init_stream                                                                              +19  +2.1%
      +0.9%     +19 perform_stream_op                                                                        +19  +0.9%
      +1.3%     +18 fail_helper_locked                                                                       +18  +1.3%
      +2.5%     +15 message_transfer_locked                                                                  +15  +2.5%
      +0.5%      +3 grpc_inproc_channel_create                                                                +3  +0.5%
      +4.7%      +3 ref_stream                                                                                +3  +4.7%
      +4.7%      +3 unref_stream                                                                              +3  +4.7%
      +5.2%      +3 ref_transport                                                                             +3  +5.2%
      +1.6%      +3 unref_transport                                                                           +3  +1.6%
      +3.3%      +3 destroy_transport                                                                         +3  +3.3%
      +1.3%      +3 perform_transport_op                                                                      +3  +1.3%
      +0.9%      +3 close_transport_locked                                                                    +3  +0.9%
  +1.7%    +119 src/core/lib/iomgr/tcp_posix.cc                                                         +119  +1.7%
      +4.6%     +25 notify_on_write                                                                          +25  +4.6%
      +4.0%     +25 tcp_handle_read                                                                          +25  +4.0%
      +5.2%     +19 tcp_drop_uncovered_then_handle_write                                                     +19  +5.2%
      +2.3%     +14 tcp_write                                                                                +14  +2.3%
      +2.0%     +11 run_poller                                                                               +11  +2.0%
      +6.5%      +7 grpc_tcp_destroy_and_release_fd                                                           +7  +6.5%
      +5.2%      +7 drop_uncovered((anonymous namespace)::grpc_tcp*) [clone .isra.4]                          +7  +5.2%
      +3.5%      +6 tcp_read                                                                                  +6  +3.5%
      +0.4%      +4 tcp_do_read                                                                               +4  +0.4%
      +4.4%      +3 grpc_tcp_fd                                                                               +3  +4.4%
      +4.5%      +3 done_poller                                                                               +3  +4.5%
      +0.8%      +3 call_read_cb                                                                              +3  +0.8%
      +2.9%      +3 notify_on_read                                                                            +3  +2.9%
      +2.0%      +3 tcp_read_allocation_done                                                                  +3  +2.0%
  +1.4%    +117 src/core/ext/transport/chttp2/transport/hpack_encoder.cc                                +117  +1.4%
      [NEW]    +165 emit_indexed(grpc_chttp2_hpack_compressor*, unsigned int, framer_state*) [clone .isr    +165  [NEW]
      +4.8%     +33 emit_lithdr_noidx_v                                                                      +33  +4.8%
      +4.8%     +33 emit_lithdr_incidx_v                                                                     +33  +4.8%
      [NEW]     +31 add_wire_value(framer_state*, wire_value) [clone .isra.4]                                +31  [NEW]
       +11%     +22 evict_entry                                                                              +22   +11%
      +1.0%     +15 hpack_enc                                                                                +15  +1.0%
      +2.1%     +10 emit_lithdr_incidx                                                                       +10  +2.1%
      +4.0%      +8 grpc_chttp2_hpack_compressor_set_max_table_size                                           +8  +4.0%
      +3.9%      +8 rebuild_elems                                                                             +8  +3.9%
      +2.9%      +6 finish_frame                                                                              +6  +2.9%
      +0.8%      +5 grpc_chttp2_encode_header                                                                 +5  +0.8%
      +1.1%      +5 add_elem                                                                                  +5  +1.1%
      +0.4%      +2 emit_lithdr_noidx                                                                         +2  +0.4%
  +0.9%    +112 src/core/lib/iomgr/ev_poll_posix.cc                                                     +112  +0.9%
      [NEW]    +169 init_result(poll_args*) [clone .constprop.21]                                           +169  [NEW]
      +4.4%     +77 cvfd_poll                                                                                +77  +4.4%
      +0.5%     +13 pollset_work                                                                             +13  +0.5%
      +5.6%      +7 unref_by(grpc_fd*, int) [clone .constprop.20]                                             +7  +5.6%
      +6.5%      +6 decref_poll_result                                                                        +6  +6.5%
      +3.7%      +5 pollset_destroy                                                                           +5  +3.7%
      +0.8%      +5 pollset_kick_ext                                                                          +5  +0.8%
      +0.9%      +2 global_cv_fd_table_shutdown                                                               +2  +0.9%
      +0.8%      +1 pollset_shutdown                                                                          +1  +0.8%
      +0.9%      +1 pollset_kick_locked(grpc_fd_watcher*) [clone .isra.11]                                    +1  +0.9%
  +0.9%    +109 src/core/tsi/ssl_transport_security.cc                                                  +109  +0.9%
      +2.7%     +37 peer_from_x509                                                                           +37  +2.7%
      +3.0%     +26 populate_ssl_context                                                                     +26  +3.0%
      +4.6%     +24 x509_store_load_certs                                                                    +24  +4.6%
      +6.4%     +23 [Unmapped]                                                                               +23  +6.4%
       +11%     +12 tsi_ssl_handshaker_factory_swap_vtable                                                   +12   +11%
      +2.4%     +11 ssl_protector_protect                                                                    +11  +2.4%
      +3.0%     +11 ssl_protector_protect_flush                                                              +11  +3.0%
      +4.3%      +8 do_ssl_write                                                                              +8  +4.3%
      +1.7%      +7 do_ssl_read                                                                               +7  +1.7%
      +8.2%      +6 server_handshaker_factory_npn_advertised_callback                                         +6  +8.2%
      +0.4%      +5 tsi_create_ssl_server_handshaker_factory_with_options                                     +5  +0.4%
  +2.3%     +98 src/core/lib/slice/slice_buffer.cc                                                       +98  +2.3%
       +14%     +29 grpc_slice_buffer_destroy                                                                +29   +14%
       +14%     +29 grpc_slice_buffer_reset_and_unref                                                        +29   +14%
       +12%     +17 [Unmapped]                                                                               +17   +12%
      +1.8%     +14 slice_buffer_move_first_maybe_ref                                                        +14  +1.8%
      +2.4%      +6 maybe_embiggen                                                                            +6  +2.4%
      +0.5%      +2 grpc_slice_buffer_move_first_into_buffer                                                  +2  +0.5%
      +0.7%      +1 grpc_slice_buffer_take_first                                                              +1  +0.7%
  +2.4%     +96 src/core/lib/security/transport/security_handshaker.cc                                   +96  +2.4%
       +23%    +103 on_handshake_next_done_locked                                                           +103   +23%
  +2.3%     +96 src/core/lib/slice/slice.cc                                                              +96  +2.3%
       +22%     +52 grpc_slice_unref                                                                         +52   +22%
      +9.4%     +23 grpc_slice_sub_no_ref                                                                    +23  +9.4%
      +3.3%     +13 grpc_slice_split_head                                                                    +13  +3.3%
      +1.8%      +7 grpc_slice_split_tail_maybe_ref                                                           +7  +1.8%
      +0.3%      +1 [Unmapped]                                                                                +1  +0.3%
  +4.5%     +80 src/core/ext/transport/chttp2/transport/stream_lists.cc                                  +80  +4.5%
       +15%     +46 stream_list_remove                                                                       +46   +15%
      +7.5%     +18 stream_list_add_tail                                                                     +18  +7.5%
      +7.1%      +6 grpc_chttp2_list_add_writable_stream                                                      +6  +7.1%
      +2.3%      +3 [Unmapped]                                                                                +3  +2.3%
      +1.0%      +3 stream_list_pop                                                                           +3  +1.0%
      +1.7%      +2 grpc_chttp2_list_add_stalled_by_stream                                                    +2  +1.7%
      +1.7%      +2 grpc_chttp2_list_add_stalled_by_transport                                                 +2  +1.7%
  +0.8%     +80 src/core/lib/iomgr/ev_epoll1_linux.cc                                                    +80  +0.8%
      +1.7%     +40 pollset_kick                                                                             +40  +1.7%
      +0.6%     +21 pollset_work                                                                             +21  +0.6%
      +2.3%     +12 pollset_shutdown                                                                         +12  +2.3%
      +1.5%      +4 [Unmapped]                                                                                +4  +1.5%
      +0.5%      +3 check_neighborhood_for_available_poller(pollset_neighborhood*) [clone .isra.7]            +3  +0.5%

 -------------- SHRINKING                                                                            --------------
 -12.5%    -453 src/core/ext/filters/client_channel/resolver_registry.cc                                -453 -12.5%
     -41.7%    -118 grpc_core::ResolverRegistry::Builder::ShutdownRegistry                                  -118 -41.7%
     -14.3%    -112 grpc_core::ResolverRegistry::CreateResolver                                             -112 -14.3%
      -8.2%     -60 grpc_core::ResolverRegistry::GetDefaultAuthority                                         -60  -8.2%
      -8.1%     -54 grpc_core::ResolverRegistry::AddDefaultPrefixIfNeeded                                    -54  -8.1%
      [DEL]     -47 grpc_core::(anonymous namespace)::RegistryState::FindResolverFactory(char const*, gr     -47  [DEL]
      -6.7%     -36 grpc_core::ResolverRegistry::Builder::RegisterResolverFactory                            -36  -6.7%
      -9.8%     -22 grpc_core::ResolverRegistry::LookupResolverFactory                                       -22  -9.8%
     -18.9%     -10 [Unmapped]                                                                               -10 -18.9%
  -7.4%    -368 src/core/ext/filters/message_size/message_size_filter.cc                                -368  -7.4%
     -12.9%    -356 init_channel_elem                                                                       -356 -12.9%
      -3.1%     -16 init_call_elem                                                                           -16  -3.1%
      -4.7%      -8 grpc_core::SliceHashTable<grpc_core::RefCountedPtr<grpc_core::(anonymous namespace):      -8  -4.7%
 -14.3%    -175 src/core/ext/filters/client_channel/lb_policy_registry.cc                               -175 -14.3%
     -44.2%    -118 grpc_core::LoadBalancingPolicyRegistry::Builder::ShutdownRegistry                       -118 -44.2%
      -6.7%     -36 grpc_core::LoadBalancingPolicyRegistry::Builder::RegisterLoadBalancingPolicyFactory      -36  -6.7%
     -10.2%     -31 grpc_core::LoadBalancingPolicyRegistry::CreateLoadBalancingPolicy                        -31 -10.2%
  -2.6%    -144 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                  -144  -2.6%
      -3.4%     -58 grpc_core::(anonymous namespace)::PickFirst::OnConnectivityChangedLocked                 -58  -3.4%
      -2.7%     -30 grpc_core::(anonymous namespace)::PickFirst::UpdateLocked                                -30  -2.7%
      -6.1%     -29 grpc_core::(anonymous namespace)::PickFirst::ShutdownLocked                              -29  -6.1%
     -14.4%     -24 grpc_core::(anonymous namespace)::PickFirst::PickLocked                                  -24 -14.4%
      -6.4%     -23 grpc_core::(anonymous namespace)::PickFirst::CancelPickLocked                            -23  -6.4%
      -2.8%      -4 [Unmapped]                                                                                -4  -2.8%
  -2.4%    -128 src/core/lib/iomgr/tcp_server_posix.cc                                                  -128  -2.4%
      [DEL]    -105 init                                                                                    -105  [DEL]
      -3.7%     -50 tcp_server_start                                                                         -50  -3.7%
      -2.2%      -2 [Unmapped]                                                                                -2  -2.2%
      -0.2%      -2 tcp_server_add_port                                                                       -2  -0.2%
  -1.2%     -80 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                 -80  -1.2%
      -8.9%     -34 grpc_core::(anonymous namespace)::RoundRobin::CancelMatchingPicksLocked                  -34  -8.9%
      -6.1%     -29 grpc_core::(anonymous namespace)::RoundRobin::ShutdownLocked                             -29  -6.1%
      -6.0%     -27 grpc_core::(anonymous namespace)::RoundRobin::PickLocked                                 -27  -6.0%
      -6.4%     -23 grpc_core::(anonymous namespace)::RoundRobin::CancelPickLocked                           -23  -6.4%
      -0.7%     -16 grpc_core::(anonymous namespace)::RoundRobin::OnConnectivityChangedLocked                -16  -0.7%
  -0.5%     -32 src/core/ext/transport/chttp2/transport/writing.cc                                       -32  -0.5%
      -0.4%     -22 grpc_chttp2_begin_write                                                                  -22  -0.4%
     -28.6%     -10 [Unmapped]                                                                               -10 -28.6%
  -0.6%     -32 src/core/lib/surface/channel.cc                                                          -32  -0.6%
      -3.2%     -33 grpc_channel_create_with_builder                                                         -33  -3.2%
      -8.0%     -14 destroy_channel                                                                          -14  -8.0%
      -1.2%      -7 grpc_channel_create_call                                                                  -7  -1.2%
  -1.7%     -29 src/core/ext/filters/client_channel/method_params.cc                                     -29  -1.7%
      [DEL]     -37 grpc_core::internal::ClientChannelMethodParams::~ClientChannelMethodParams               -37  [DEL]
      [DEL]     -34 grpc_core::internal::ClientChannelMethodParams::~ClientChannelMethodParams               -34  [DEL]
  -4.4%     -27 src/core/lib/security/transport/target_authority_table.cc                                -27  -4.4%
     -25.5%     -14 grpc_core::(anonymous namespace)::target_authority_table_destroy                         -14 -25.5%
      [DEL]      -9 grpc_core::RefCounted<grpc_core::SliceHashTable<std::unique_ptr<char, grpc_core::Def      -9  [DEL]
      -5.1%      -2 [Unmapped]                                                                                -2  -5.1%
      [DEL]      -2 grpc_core::RefCounted<grpc_core::SliceHashTable<std::unique_ptr<char, grpc_core::Def      -2  [DEL]
  -0.3%     -16 src/core/ext/filters/http/client/http_client_filter.cc                                   -16  -0.3%
     -13.9%     -14 [Unmapped]                                                                               -14 -13.9%
      -0.1%      -2 init_channel_elem                                                                         -2  -0.1%
  -0.3%     -16 src/core/lib/http/parser.cc                                                              -16  -0.3%
      -0.7%     -11 grpc_http_parser_parse                                                                   -11  -0.7%
     -11.1%      -5 [Unmapped]                                                                                -5 -11.1%
  -2.2%     -16 src/core/lib/iomgr/wakeup_fd_pipe.cc                                                     -16  -2.2%
      -5.1%     -10 pipe_consume                                                                             -10  -5.1%
     -13.0%      -6 [Unmapped]                                                                                -6 -13.0%
  -4.2%     -16 src/core/lib/security/credentials/alts/grpc_alts_credentials_client_options.cc           -16  -4.2%
      [DEL]    -110 grpc_alts_credentials_client_options_add_target_service_account                         -110  [DEL]
      [DEL]     -29 grpc_alts_credentials_client_options_create                                              -29  [DEL]
     -11.1%      -1 [Unmapped]                                                                                -1 -11.1%
  -0.6%     -16 src/core/lib/slice/slice_intern.cc                                                       -16  -0.6%
      -3.8%     -44 grpc_slice_intern                                                                        -44  -3.8%
  -0.4%      -9 src/core/ext/transport/chttp2/server/chttp2_server.cc                                     -9  -0.4%
      -2.5%     -25 grpc_chttp2_server_add_port                                                              -25  -2.5%
  -0.3%      -3 src/core/ext/transport/chttp2/client/insecure/channel_create.cc                           -3  -0.3%
      -0.6%      -3 grpc_insecure_channel_create                                                              -3  -0.6%

  +0.5% +7.30Ki TOTAL                                                                                +10.7Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
   +25%    +409 src/cpp/util/byte_buffer_cc.cc                                                          +409   +25%
       +57%    +254 void std::vector<grpc::Slice, std::allocator<grpc::Slice> >::_M_emplace_back_aux<grp    +254   +57%
       +37%    +235 grpc::ByteBuffer::Dump(std::vector<grpc::Slice, std::allocator<grpc::Slice> >*) cons    +235   +37%
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
  +3.8%    +341 src/cpp/client/secure_credentials.cc                                                    +341  +3.8%
      [NEW]    +335 grpc::experimental::AltsCredentials                                                     +335  [NEW]
      [NEW]    +194 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +194  [NEW]
      +0.9%      +5 grpc::MetadataCredentialsPluginWrapper::GetMetadata                                       +5  +0.9%
      +0.7%      +1 [Unmapped]                                                                                +1  +0.7%
  +3.7%    +192 src/cpp/server/secure_server_credentials.cc                                             +192  +3.7%
      [NEW]    +184 grpc::experimental::AltsServerCredentials                                               +184  [NEW]
       +22%      +8 [Unmapped]                                                                                +8   +22%
  +7.0%     +96 src/cpp/common/core_codegen.cc                                                           +96  +7.0%
      [NEW]     +68 grpc::CoreCodegen::grpc_slice_new_with_len                                               +68  [NEW]
      +5.6%     +20 [Unmapped]                                                                               +20  +5.6%
      [NEW]      +8 grpc::CoreCodegen::grpc_byte_buffer_length                                                +8  [NEW]
  +0.7%     +80 src/cpp/server/health/default_health_check_service.cc                                    +80  +0.7%
      +3.2%     +68 grpc::DefaultHealthCheckService::HealthCheckServiceImpl::Check                           +68  +3.2%
      +5.2%      +7 grpc::DefaultHealthCheckService::GetHealthCheckService                                    +7  +5.2%
       +12%      +5 [Unmapped]                                                                                +5   +12%
  +0.2%     +77 src/cpp/server/server_cc.cc                                                              +77  +0.2%
      +1.6%     +31 grpc::Server::Start                                                                      +31  +1.6%
      +5.2%     +18 grpc::ServerInterface::GenericAsyncRequest::GenericAsyncRequest                          +18  +5.2%
      +0.8%     +13 grpc::Server::SyncRequestThreadManager::DoWork                                           +13  +0.8%
      +2.5%      +8 grpc::Server::SetGlobalCallbacks                                                          +8  +2.5%
      +3.3%      +7 grpc::ServerInterface::RegisteredAsyncRequest::IssueRequest                               +7  +3.3%
       +11%      +7 grpc::Server::RegisterAsyncGenericService                                                 +7   +11%
  +1.4%     +64 src/cpp/client/client_context.cc                                                         +64  +1.4%
      +5.6%     +32 grpc::ClientContext::set_call                                                            +32  +5.6%
      +9.4%     +16 grpc::ClientContext::SetGlobalCallbacks                                                  +16  +9.4%
       +23%     +13 [Unmapped]                                                                               +13   +23%
      +0.8%      +3 grpc::ClientContext::set_compression_algorithm                                            +3  +0.8%
  +0.6%     +32 src/cpp/server/server_context.cc                                                         +32  +0.6%
       +23%     +23 [Unmapped]                                                                               +23   +23%
      +2.9%      +6 grpc::ServerContext::BeginCompletionOp                                                    +6  +2.9%
      +0.8%      +3 grpc::ServerContext::set_compression_algorithm                                            +3  +0.8%
  +0.4%     +16 src/cpp/client/channel_cc.cc                                                             +16  +0.4%
      +2.0%     +13 grpc::Channel::WaitForStateChangeImpl                                                    +13  +2.0%
      +3.4%      +6 grpc::Channel::PerformOpsOnCall                                                           +6  +3.4%
  +0.3%     +16 src/cpp/server/dynamic_thread_pool.cc                                                    +16  +0.3%
      +4.6%     +10 grpc::DynamicThreadPool::DynamicThread::DynamicThread                                    +10  +4.6%
      +5.4%      +4 [Unmapped]                                                                                +4  +5.4%
      +1.7%      +2 grpc::DynamicThreadPool::DynamicThread::~DynamicThread                                    +2  +1.7%
  +0.6%     +16 src/cpp/thread_manager/thread_manager.cc                                                 +16  +0.6%
      +5.9%     +22 grpc::ThreadManager::WorkerThread::WorkerThread                                          +22  +5.9%
      +1.7%      +2 grpc::ThreadManager::WorkerThread::~WorkerThread                                          +2  +1.7%
  +8.2%      +7 src/cpp/common/version_cc.cc                                                              +7  +8.2%
       +18%      +7 grpc::Version[abi:cxx11]                                                                  +7   +18%

 -------------- SHRINKING                                                                            --------------
  -0.5% -1.16Ki [None]                                                                               -14.0Ki  -0.3%
      -0.6% -1.18Ki [Unmapped]                                                                           -14.1Ki  -0.3%
      -3.4%      -1 std::__ioinit                                                                              0  [ = ]
  [DEL]    -808 src/cpp/util/slice_cc.cc                                                                -808  [DEL]
      [DEL]    -126 [Unmapped]                                                                              -126  [DEL]
      [DEL]     -74 grpc::Slice::c_slice() const                                                             -74  [DEL]
      [DEL]     -71 grpc::Slice::Slice                                                                       -71  [DEL]
      [DEL]     -66 grpc::Slice::Slice                                                                       -66  [DEL]
      [DEL]     -58 grpc::Slice::Slice                                                                       -58  [DEL]
      [DEL]     -51 grpc::Slice::Slice                                                                       -51  [DEL]
      [DEL]     -51 grpc::Slice::Slice                                                                       -51  [DEL]
      [DEL]     -51 grpc::Slice::Slice                                                                       -51  [DEL]
      [DEL]     -51 grpc::Slice::Slice                                                                       -51  [DEL]
      [DEL]     -51 grpc::Slice::Slice                                                                       -51  [DEL]
      [DEL]     -51 grpc::Slice::Slice                                                                       -51  [DEL]
      [DEL]     -46 _GLOBAL__sub_I_slice_cc.cc                                                               -46  [DEL]
      [DEL]     -36 grpc::Slice::Slice                                                                       -36  [DEL]
      [DEL]     -25 grpc::Slice::~Slice                                                                      -25  [DEL]

  -0.2%    -651 TOTAL                                                                                -13.5Ki  -0.3%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by mehrdada** [comment]
@jtattermusch ok

**Comment by jtattermusch** [comment]
@markdroth  can we get owners approval?

**Comment by jtattermusch** [comment]
Merging  as this is only a backport of #15156.

**Pull request merged**
