### PR TITLE
Roll foward "Strip Python wheel binary"

### PR DESCRIPTION
**Pull request by lidizheng**
Try to install the command explicitly, and invoke as a Python module instead of Linux command.
@jtattermusch PTAL.

### CODE REVIEW

**Comment by lidizheng** [comment]
Original PR https://github.com/grpc/grpc/pull/18241

**Comment by lidizheng** [comment]
A fun discovery that explains why the installation has been successful, but `wheel` module keep being unfound:
```
# During preparation phase, Kokoro use Python in virtual environment
+++ which python
++ echo /home/kbuilder/.pyenv/shims/python
/home/kbuilder/.pyenv/shims/python

# During the actual script running phase, Kokoro use system Python
++ which python
+ echo /usr/bin/python
/usr/bin/python
```

**Comment by lidizheng** [comment]
The `wheel` command is installed successfully.
https://source.cloud.google.com/results/invocations/c7491a8e-f092-4613-b95e-99cfac408ae8/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_build_packages/log

If the build triggered normally, the artifacts will be generated under the designated folder. And the CI build should pass.

**Comment by jtattermusch** [comment]
Started an adhoc run of artifact - packages - distribtest flow to test this change: https://sponge.corp.google.com/target?id=13c35ab2-d2b3-4c08-ba9e-602d4185e840&target=grpc/core/experimental/grpc_build_artifacts_multiplatform

**Comment by jtattermusch** [comment]
The adhoc run I started actually reveal that this will probably break the grpc_build_packages build on linux again:
https://sponge.corp.google.com/target?id=082a165b-cc5d-4c7e-9466-aea9a258414b&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

Please doublecheck and revert.

**Comment by lidizheng** [comment]
@jtattermusch Sorry, I was running the Child Job instead of the full-fledged Kokoro job.
Reverting the PR.

**Pull request merged**
