### PR TITLE
Pre 0.13.1 downmerge

### PR DESCRIPTION
**Pull request by nicolasnoble**
I'm still toying with #5678 to make it look green, so don't merge that before I have a change to tackle it.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
We should be good to merge now :-) (upon green tests).

**Comment by jtattermusch** [comment]
Let's include the python fix #5704 and then merge this.

**Comment by jtattermusch** [comment]
`Version key "version" value "0.13.1-pre1" should have a -dev tag`
https://grpc-testing.appspot.com/job/gRPC_pull_requests/6869/config=opt,language=sanity,platform=linux/testReport/junit/(root)/tests/tools_run_tests_sanity_check_version_py/

**Comment by jtattermusch** [comment]
Also, objc has failed:

```
Failures:
  0) -[GRPCClientTests testUserAgentPrefix] (InteropTestsLocalCleartext.xctest)
```
https://travis-ci.org/grpc/grpc/jobs/115187739

**Comment by nicolasnoble** [comment]
So this now contains #5704.

**Comment by jtattermusch** [comment]
@makdharma    can you please check what's up with the objc test?

**Comment by jtattermusch** [comment]
@nicolasnoble   what about the sanity test?

**Comment by nicolasnoble** [comment]
Only typical python issues there.

**Pull request merged**
