### PR TITLE
Merge release-0.12 into master

### LINKED ISSUE #4295: Failure to download openssl-1.0.2d.tar.gz breaks iOS build on Travis.
https://openssl.org/source/openssl-1.0.2d.tar.gz does not exist which breaks the travis build of iOS.

https://travis-ci.org/grpc/grpc/jobs/95380279

```
> Http download
   $ /usr/bin/curl -f -L -o
   /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/d20151207-10705-v07flj/file.tgz
   https://openssl.org/source/openssl-1.0.2d.tar.gz --create-dirs
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
[!] Error installing OpenSSL
[!] /usr/bin/curl -f -L -o /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/d20151207-10705-v07flj/file.tgz https://openssl.org/source/openssl-1.0.2d.tar.gz --create-dirs
```

### PR DESCRIPTION
**Pull request by jcanizales**
Fixes #4295, and keeps things consistent overall.

Manually solved conflicts for:
* `client_uchannel.c` (stays as in master)
* Node's [`call.c`](https://github.com/grpc/grpc/pull/4306/files#diff-affd89200e5b52355e081883dcb3bee0)
* `server_auth_filter.c` (stays as in master)
* [`run_interop_tests.py`](https://github.com/grpc/grpc/pull/4306/files#diff-267afa22a65534e2688adc5fce0f3f47)

Let's wait for the test runs to make sure I didn't mess them up :)

CC @murgatroid99  and @w4-sjcho. This supersedes PR #4301

### CODE REVIEW

**Comment by jtattermusch** [comment]
LGTM, but let's wait for all the tests to finish.

**Comment by jtattermusch** [comment]
This branch needs resolving.

**Comment by jtattermusch** [comment]
Looks like the "tox" tool is not available in the python interop image:

```
+ cd /var/local/git/grpc/src/python/grpcio
+ tox --notest
./tools/run_tests/build_python.sh: line 47: tox: command not found
```

@soltanmm, @nathanielmanistaatgoogle looks like this has been introduced by by #4281, and that interop tests failure on that PR was ignored. Please fix.

**Comment by jcanizales** [comment]
Yeah that's Issue #4317 :)

**Comment by jcanizales** [comment]
The Jenkins failures are just git exceptions, so I'm just going to rerun them.

**Comment by jcanizales** [comment]
Please review my manual merge of [`NativeMetadataCredentialsPlugin.cs`, line 100](https://github.com/grpc/grpc/commit/b91c7068200895d7d0b9752a5e9520b2df6c04bd#diff-c5298b7bb3a2f490d932de598a4fa12c).

**Comment by jtattermusch** [comment]
Changes of NativeMetadataCredentialsPlugin.cs, look good.

**Comment by jtattermusch** [comment]
LGTM, feel free to merge once interop tests & Jenkins are green.

**Comment by jtattermusch** [comment]
Merging as Jenkins looks good and this should fix iOS on travis.

**Pull request merged**
