### PR TITLE
pass URI string to resolver impls

### PR DESCRIPTION
**Pull request by markdroth**
We were already passing the parsed URI, but now we pass along the URI string as well.

### CODE REVIEW

**Review by donnadionne — APPROVED** [review]
I see, this is how we should obtain the URI string.

**Comment by ctiller** [comment]
Would this make it possible to remove the uri parameter entirely?

**Comment by markdroth** [comment]
Craig, are you asking whether we can pass only the raw URI string instead of the parsed URI?  I don't think that makes sense, since basically every resolver needs the parsed URI anyway.  If we didn't pass it in, then every resolver impl would need to do the parsing itself.  And the registry needs to do the parsing anyway in order to find the URI scheme, so that would amount to parsing it twice.

**Comment by ctiller** [comment]
Right... I was trying to think through what happens when this becomes a
public API... We should chat separately, but right now making resolver
public likely means making our uri parsing and our json parsing public, and
it's not clear to me that this is desirable.

**Comment by markdroth** [comment]
Good point.  I agree that it seems undesirable to expose our URI parsing library, but on the other hand, we know that basically all resolver impls will need this functionality, and in the absence of some standard OSS URI-parsing library, resolver impls are likely to try to roll their own (and get it wrong) if we don't provide something.

Anyway, as you say, let's chat further about this separately.

**Comment by markdroth** [comment]
The "Basic Tests Python Windows" failure is an infrastructure timeout.

**Pull request merged**
