### PR TITLE
Move to new URL for interop tests

### PR DESCRIPTION
**Pull request by jcanizales**

### CODE REVIEW

**Comment by adelez** [comment]
This is already fixed in PR #4790

**Comment by jcanizales** [comment]
Thanks for the pointer Adele!

That change went to the master branch. Shouldn't we fix it on the release branch too?

**Comment by adelez** [comment]
Hmm, I didn't know about release branch, thinking merging to master is all I need. I'll ask you tmr when I'm in CL2.

**Comment by cv** [comment]
Looks like this PR was forgotten. Can we close?

**Comment by jcanizales** [comment]
Yeah, this was for release 0.12 anyway. Closing.

**Pull request closed without merging**
