### PR TITLE
Allow gRPC ObjC user to set keepalive options

### LINKED ISSUE #8328: Keep Alive Support for Objective-C
Add keep alive and ping support for Objetive-C clients. See https://github.com/grpc/grpc-java/issues/1648

### PR DESCRIPTION
**Pull request by muxi**
Fixes #8328. The new test will only pass after #14780 is merged.

cc: @srini100

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%     +96 [None]                                                         +352  +0.0%
  +0.2%     +64 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     +64  +0.2%
       +14%     +32 keepalive_watchdog_fired_locked                                 +32   +14%
       +30%     +19 start_keepalive_ping_locked                                     +19   +30%
      +2.0%     +13 [Unmapped]                                                      +13  +2.0%

  +0.0%    +160 TOTAL                                                          +416  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%    +184 [None]                                                         +688  +0.0%
  +0.4%    +144 src/core/ext/transport/chttp2/transport/chttp2_transport.cc    +144  +0.4%
       +49%    +108 keepalive_watchdog_fired_locked                                +108   +49%
       +30%     +19 start_keepalive_ping_locked                                     +19   +30%
      +2.6%     +17 [Unmapped]                                                      +17  +2.6%

  +0.0%    +328 TOTAL                                                          +832  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++
  +0.0%    +280 [None]                                                         +896  +0.0%
  +0.6%    +192 src/core/ext/transport/chttp2/transport/chttp2_transport.cc    +192  +0.6%
       +49%    +108 keepalive_watchdog_fired_locked                                +108   +49%
       +42%     +49 finish_keepalive_ping_locked                                    +49   +42%
       +30%     +19 start_keepalive_ping_locked                                     +19   +30%
      +2.5%     +16 [Unmapped]                                                      +16  +2.5%

  +0.0%    +472 TOTAL                                                       +1.06Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Artifact Build Windows - succeeded but not reported to github.

**Pull request merged**
