### PR TITLE
Add src/core/lib/iomgr/nameser.h

### PR DESCRIPTION
**Pull request by y-zeng**

### CODE REVIEW

**Comment by dgquintas** [comment]
Why is the file called "nameser" instead of "nameserver"? Are we supporting ms-dos now? :)

**Comment by y-zeng** [comment]
@dgquintas This file is supposed to serve as arpa/nameser.h on platforms that do not have that file. It'd be less confusing to let them have the same name.

**Comment by y-zeng** [comment]
Known issues:
Basic Tests Windows: #11188, #11109
gRPC_interop_pull_requests: #11967

**Comment by y-zeng** [comment]
@ax3l has agreed to submit 3180dfa in #11903

**Comment by ax3l** [comment]
@y-zeng just a quick question: is this still going into the upcoming 1.5.0 release? :)

**Comment by y-zeng** [comment]
@ax3l I think so. We haven't cut the 1.5.0 release.

**Pull request merged**
