### PR TITLE
[BinderTransport] Make `CreateBinderChannel` parameter names consistent

### PR DESCRIPTION
**Pull request by rock1246**
* Rename `jni_env` to `jni_env_void`
* Rename `application` to `context`

### CODE REVIEW

**Comment by sifmelcara** [comment]
We will also want to update parameter names in https://github.com/grpc/grpc/blob/master/src/core/ext/transport/binder/client/channel_create.cc

If you have time, can you also look into why checks like https://clang.llvm.org/extra/clang-tidy/checks/readability/inconsistent-declaration-parameter-name.html didn't get triggered in this case? Maybe it is because clang-tidy didn't process things in `include/` folder, maybe it is because the check is not turned on at all

**Comment by sifmelcara** [comment]
Just in case you don't know, you can run https://github.com/grpc/grpc/blob/master/tools/distrib/sanitize.sh to sanitize the code (this is similar to the concept of pre-commit hook that you are familiar with)

**Review by LittleCVR — APPROVED** [review]

**Comment by rock1246** [comment]
> We will also want to update parameter names in https://github.com/grpc/grpc/blob/master/src/core/ext/transport/binder/client/channel_create.cc
> 

IIUC, I already changed the file.

> If you have time, can you also look into why checks like https://clang.llvm.org/extra/clang-tidy/checks/readability/inconsistent-declaration-parameter-name.html didn't get triggered in this case? Maybe it is because clang-tidy didn't process things in `include/` folder, maybe it is because the check is not turned on at all

Thanks for the info! I didn't know that.

**Comment by sifmelcara** [comment]
(For reference, here is a relevant old PR: #28036 )

**Comment by sifmelcara** [comment]
> > We will also want to update parameter names in https://github.com/grpc/grpc/blob/master/src/core/ext/transport/binder/client/channel_create.cc
> 
> IIUC, I already changed the file.

You are right, for some reason I didn't see the change

**Review by sifmelcara — APPROVED** [review]

**Pull request merged**
