### PR TITLE
Fix threading problem in gRPC ObjC

### PR DESCRIPTION
**Pull request by muxi**
GRPCCall.state is non-atomic. To access it, the code should be protected by synchronization.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @muxi isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by muxi** [comment]
cla?

**Comment by makdharma** [comment]
How was this found?

**Comment by muxi** [comment]
Fix #15368

**Pull request merged**
