### PR TITLE
Change refcount representation to mean 1 when the atomic is zero

### PR DESCRIPTION
**Pull request by mehrdada**
Helps with zero-initialization being able to initialize it properly

### CODE REVIEW

**Comment by soheilhy** [comment]
While I understand the usecase here, I generally dislike `memset(0)` on a C++ class. 

I'd defer to @markdroth

**Comment by mehrdada** [comment]
@soheilhy @markdroth  Of course the idea is not to `memset` in C++ -- it is to enable compiler optimizations to be able to skip constructing the object/eliminate logic.

**Comment by soheilhy** [comment]
@mehrdada do you have an example?  Except in some specific situation for static and array storage, the C++ compiler never skips initialization.

**Comment by mehrdada** [comment]
Yeap, and there's a difference between initialization of a big block to zero as opposed to a 1 in the middle of a bunch of zeros. But I guess the difference is not significant enough and I don't want to fix the tests, so whatever :)

**Pull request closed without merging**
