### PR TITLE
Fix to undefined reference to gpr_log

### PR DESCRIPTION
**Pull request by chedeti**

### CODE REVIEW

**Comment by dgquintas** [comment]
LGTM.

@chedeti , you don't have to do anything else. I'm assigning the "ready to merge" label to this PR. Someone else (usually @jtattermusch ) will eventually merge it.

**Comment by thinkerou** [comment]
Why the `Makefile` of `examples/cpp/route_guide` is right but it have not `grpc` in `pkg-config` line?

**Comment by y-zeng** [comment]
@thinkerou The problem was caused by the use of `GPR_ASSERT`. This macro uses `gpr_log()`, which is implemented in the library `grpc`. But `grpc` is hidden from the application in `grpc++.pc`. We have to explicitly add `grpc` to `pkg-config` when the application needs to use its interfaces. `route_guide` does not use any interfaces from `grpc`.

**Comment by thinkerou** [comment]
@y-zeng Thanks, I got it.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
