### PR TITLE
PHP: change the php ssl server credentials API so that a server can have multiple key/cert pairs

### PR DESCRIPTION
**Pull request by thinkerou**
This fixs #1122.

### CODE REVIEW

**Comment by thinkerou** [comment]
Hi, @stanley-cheung the PR needs to recommit when support PHP7 later? Thanks!

**Comment by stanley-cheung** [comment]
Yes this will need to be done on top of the latest code.

**Comment by thinkerou** [comment]
OK...

**Comment by thinkerou** [comment]
#7566 fixed.

**Pull request closed without merging**
