### PR TITLE
Remove unused exec_ctx argument from grpc_timer_init

### PR DESCRIPTION
**Pull request by rjshade**

### CODE REVIEW

**Comment by ctiller** [comment]
We're in the midst of a stabilization fixit right now: ok if we hold this until next week?

**Comment by rjshade** [comment]
ctiller: No problem, this is just a tidyup.

**Comment by ctiller** [comment]
I'm wondering if we actually want that exec_ctx present: seems like we could do something like 'if deadline < now, enqueue result immediately' - and avoid going through the timer machinery.

**Comment by ctiller** [comment]
We do actually use this in grpc_timer_init now. Closing.

**Pull request closed without merging**
