### PR TITLE
Test Travis fail fast

### PR DESCRIPTION
**Pull request by jcanizales**
Tests #7414.

### CODE REVIEW

**Comment by muxi** [comment]
Travis is not running for some reason

**Comment by jcanizales** [comment]
It is scheduled alright: https://travis-ci.org/grpc/grpc/pull_requests , I don't know if it's waiting to start running to show in the box (bad), or if it won't show anyway (also bad).

**Comment by muxi** [comment]
I see. Is that a success? In my understanding I thought when #11257.1 failed, some of the newer jobs will be halted...

**Comment by jcanizales** [comment]
Yeah they kept going even after the failure......

**Comment by muxi** [comment]
This should probably be closed since we are no longer using Travis

**Pull request closed without merging**
