### PR TITLE
xds-k8s: Allow multiple instance of the driver to run concurrently

### PR DESCRIPTION
**Pull request by sergiitk**
- replace `--namespace` with `--resource_prefix` and `--resource_suffix`
- make resource names unique by randomizing `--resource prefix`
- add option to use randomly allocated xds port
- add a check for port to be taken. the check is unreliable, but practically the clash is unlikely. There's a room for improvement here, see TODOs
- updates to README.md

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/26542)

### CODE REVIEW

**Review by lidizheng — COMMENTED** [review]
Overall looks pretty good. I think separate the naming into prefix and suffix is a good design. I saw a few conflict changes with https://github.com/grpc/grpc/pull/26367, but they should be simple to fix.

The most important discussion is about the content of suffix. I think we should put something helpful for debugging into it. Many TD components are using timestamp as version number.

> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542#-:-McvG8kJ8t0QCZcqccFk:b-4kzw0r)* status: 2 of 14 files reviewed, 3 unresolved discussions (waiting on @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvBUPv8ms9WBeK2MhY:-McvBUPv8ms9WBeK2MhZ:b-avngdj) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py#L65)):*
> ```Python
> flags.adopt_module_key_flags(xds_k8s_flags)
> # Running outside of a test suite, so require explicit resource_suffix.
> flags.mark_flag_as_required("resource_suffix")
> ```

Can we mark some other flags as non-required? E.g. client-image, server-image for this script.
___
*[tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py, line 91 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvDjGV3P_Uf3G6n2Mg:-McvDjGV3P_Uf3G6n2Mh:b-qmw6d8) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py#L91)):*
> ```Python
>     server_xds_port = xds_flags.SERVER_XDS_PORT.value
>     server_namespace = KubernetesServerRunner.make_namespace_name(
>         resource_prefix, resource_suffix)
> ```

Just a thought. Creating/deleting namespaces are time consuming. Is it possible to run multiple instances at Deployment level?
___
*[tools/run_tests/xds_k8s_test_driver/framework/helpers/rand.py, line 33 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvD1SF2B_DTAX1doSy:-McvD1SF2B_DTAX1doSz:boffhcm) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/framework/helpers/rand.py#L33)):*
> ```Python
>     """
>     alphabet = ALPHANUM_LOWERCASE if lowercase else ALPHANUM
>     return ''.join(random.choices(population=alphabet, k=length))
> ```

I would recommend to just use nano timestamp. It's increasing chronologically, might help debugging.

**Review by sergiitk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542)* status: 2 of 14 files reviewed, 3 unresolved discussions (waiting on @lidizheng and @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvBUPv8ms9WBeK2MhY:-Md4CbMR4FrPzWc-iTix:bibr9e7) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py#L65)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Can we mark some other flags as non-required? E.g. client-image, server-image for this script.
</blockquote></details>

Good idea, I'll look into that.
___
*[tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py, line 91 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvDjGV3P_Uf3G6n2Mg:-Md4CfWO-KRGWXBi5iJz:b5qunm5) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py#L91)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Just a thought. Creating/deleting namespaces are time consuming. Is it possible to run multiple instances at Deployment level?
</blockquote></details>

This is a good point. Deleting namespaces is time consuming, but on the upside it ensures all resources are deleted. This is definitely something to consider, but, at this time, this would change too many things conceptually. I wouldn't do it without serious thought.
And, extra time per test case might not even be a factor if we can parallelize runs.
___
*[tools/run_tests/xds_k8s_test_driver/framework/helpers/rand.py, line 33 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvD1SF2B_DTAX1doSy:-Md4DfNqBHhOUHkg17fU:b-gu2sw4) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/framework/helpers/rand.py#L33)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

I would recommend to just use nano timestamp. It's increasing chronologically, might help debugging.
</blockquote></details>

This is a good suggestion. I went with a simpler approach for now because I didn't want to run a limit on resource name chars.
If resource names have reasonable length limit , I'd probably even one-up your suggestion, and make the date readable, f.e. `2021-06-25-1859-{rand_string()}`

**Review by lidizheng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542)* status: 2 of 14 files reviewed, 3 unresolved discussions (waiting on @lidizheng and @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py, line 91 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvDjGV3P_Uf3G6n2Mg:-Md4RlJw-_5qrsqA4v_8:bo1k9or) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py#L91)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

This is a good point. Deleting namespaces is time consuming, but on the upside it ensures all resources are deleted. This is definitely something to consider, but, at this time, this would change too many things conceptually. I wouldn't do it without serious thought.
And, extra time per test case might not even be a factor if we can parallelize runs.
</blockquote></details>

Sure. Current version works and we can make incremental changes afterward.
___
*[tools/run_tests/xds_k8s_test_driver/framework/helpers/rand.py, line 33 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvD1SF2B_DTAX1doSy:-Md4Rw7O21ZKzyfWYyIC:bex7x79) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/framework/helpers/rand.py#L33)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

This is a good suggestion. I went with a simpler approach for now because I didn't want to run a limit on resource name chars.
If resource names have reasonable length limit , I'd probably even one-up your suggestion, and make the date readable, f.e. `2021-06-25-1859-{rand_string()}`
</blockquote></details>

Up to you. The only resource name limit I hit during the development of the new framework is the path matcher name, which is at most 62. I think we should be fine to allocate 20 characters to the generated suffix.

**Comment by lidizheng** [comment]
If you are sure about the change, and it won't break existing test suite. Feel free to merge first, and improve in next quarter. It's not really an unbreakable contract.

**Review by sergiitk — COMMENTED** [review]
Randomizing xds server port (for the forwarding rule), and at the same time guaranteeing is not taken turned out to be more difficult than expected. 

Ideal approach would be to attempt creating a forwarding rule, and retry if the creation is rejected due to port conflict. However, this introduces chicken-and-the-egg problem: to create a forwarding rule we need a URL map, and to create a URL map, we need to know that forwarding rule port is not taken.

I think practically what I did should work in most cases due to the temporary nature of our resources, and relatively large port range 1-65535 to choose a random one. 

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542#-:-Md8utVn6UAZHQrvJwlM:b-7pxy1x)* status: 2 of 19 files reviewed, 3 unresolved discussions (waiting on @lidizheng)

___
*[tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py, line 65 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvBUPv8ms9WBeK2MhY:-Md8w5az-2NJ1QUvqrIs:b-j4fj32) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py#L65)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

Good idea, I'll look into that.
</blockquote></details>

Didn't find an easy way to do this. There's no API to undo `mark_flag_as_required()` :(
___
*[tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py, line 91 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvDjGV3P_Uf3G6n2Mg:-Md8wLza8ZFKA1p9Vx-x:b-60meb2) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/bin/run_td_setup.py#L91)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Sure. Current version works and we can make incremental changes afterward.
</blockquote></details>

Closing this thread.
___
*[tools/run_tests/xds_k8s_test_driver/framework/helpers/rand.py, line 33 at r1](https://reviewable.io/reviews/grpc/grpc/26542#-McvD1SF2B_DTAX1doSy:-Md8wULjDZIx4zkliSAS:bzac75t) ([raw file](https://github.com/grpc/grpc/blob/b33e0f3cf64f92a614a0904ba5fd11191e1726b3/tools/run_tests/xds_k8s_test_driver/framework/helpers/rand.py#L33)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Up to you. The only resource name limit I hit during the development of the new framework is the path matcher name, which is at most 62. I think we should be fine to allocate 20 characters to the generated suffix.
</blockquote></details>

Done. Ended up with going over the limit in for endpoint-config-selector, but the API was conveniently renamed to endpoint-policy, with endpoint-config-selector getting deprecated.

**Review by lidizheng — COMMENTED** [review]
Potentially, we can ask GCP to give the list of forwarding rules. This won't prevent race, but should be able to greatly reduce the collision chance. As for port range, it's better to choose within the "ephemeral ports" (49152–65535): https://en.wikipedia.org/wiki/Ephemeral_port

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542#-:-MdIi6Qv65qbLtU4nJBg:b3fdgo8)* status: 2 of 19 files reviewed, all discussions resolved (waiting on @lidizheng)

**Review by sergiitk — COMMENTED** [review]
1) Added some minor fixes
2) Tested on Kokoro: https://source.cloud.google.com/results/invocations/e3bf062a-be24-430c-8173-9d6f8b3ee611
3) Re: "ask GCP to give the list of forwarding rules" this could be an improvement for the worst case when most ports are busy. For normal operations, I think choosing a random port and retrying if there's a forwarding rule assigned to it (current behavior) should be ok. I think long-term we should look into something similar to making whole creation procedure a transaction, with a rollback-retry in case a forwarding rule creation fails due to a port taken
4) "it's better to choose within the "ephemeral ports" (49152–65535)" could you clarify why it's better? AFAIK the port we're choosing is a virtual xds port (same as the virtual xds ip 0.0.0.0), and it's nothing more than an app identifier.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542#-:-MeRFacnBNgleqqJLlH7:b-wmuscm)* status: 2 of 20 files reviewed, all discussions resolved (waiting on @lidizheng)

**Review by lidizheng — COMMENTED** [review]
For item 3, I agree that as long as we have retry, it should be okay. A transaction might be overkill, since our test concurrency at this point is low.

For item 4, it's just a conventional port semantics, same idea that we don't want the testing framework to pick 22, 80, 443. Yes, it's virtual, and the xDS port only makes sense to the proxy, which is us. But if we use ephemeral ports, there will be less confusion that we are talking to an ephemeral service.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542#-:-MeRIEANCO1Lda0k1u97:b-lbfwfi)* status: 2 of 20 files reviewed, 1 unresolved discussion (waiting on @lidizheng and @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/framework/xds_flags.py, line 94 at r4](https://reviewable.io/reviews/grpc/grpc/26542#-MeRJQm3Cj2X9DOQCtYT:-MeRJQm3Cj2X9DOQCtYU:b9hwjqo) ([raw file](https://github.com/grpc/grpc/blob/657b912c48e49636d7bca0c2a717f3bb5f9b0fc6/tools/run_tests/xds_k8s_test_driver/framework/xds_flags.py#L94)):*
> ```Python
>     "server_xds_port",
>     default=8080,
>     lower_bound=0,
> ```

I known this is only impacting the naming of our Listeners. 

We still might not want to collide with well-known ports. We should set lower_bound to at least 1024.
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Review by sergiitk — COMMENTED** [review]
To shorten things a bit more, also limited suffix unique_hash len to 5

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542#-:-MeRSO989drEJ8Xu5ZPk:bi06ci2)* status: 2 of 20 files reviewed, 1 unresolved discussion (waiting on @lidizheng)

___
*[tools/run_tests/xds_k8s_test_driver/framework/xds_flags.py, line 94 at r4](https://reviewable.io/reviews/grpc/grpc/26542#-MeRJQm3Cj2X9DOQCtYT:-MeRQZ7rAPCm7JL1wBPn:bfgv78a) ([raw file](https://github.com/grpc/grpc/blob/657b912c48e49636d7bca0c2a717f3bb5f9b0fc6/tools/run_tests/xds_k8s_test_driver/framework/xds_flags.py#L94)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

I known this is only impacting the naming of our Listeners. 

We still might not want to collide with well-known ports. We should set lower_bound to at least 1024.
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
</blockquote></details>

1) This will make the logic of setting port `0` (which enables random port selection) more complicated, and will require a custom absl flag validator. 
2) This flag allows framework user to set any xds port, so it leaves the decision whether they want to run on ports below 1024 to them. Which is arguably useful. What if we need to run a framework on port 80 to test something for a customer? Or we want to add a special test case for the well known ports?

TBH, I think the benefits of leaving this decision to the user outweigh the downsides.

**Review by lidizheng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542)* status: 2 of 20 files reviewed, 2 unresolved discussions (waiting on @lidizheng and @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/framework/xds_flags.py, line 94 at r4](https://reviewable.io/reviews/grpc/grpc/26542#-MeRJQm3Cj2X9DOQCtYT:-MeRURzmDr4dxoa__40B:b-t616ax) ([raw file](https://github.com/grpc/grpc/blob/657b912c48e49636d7bca0c2a717f3bb5f9b0fc6/tools/run_tests/xds_k8s_test_driver/framework/xds_flags.py#L94)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

1) This will make the logic of setting port `0` (which enables random port selection) more complicated, and will require a custom absl flag validator. 
2) This flag allows framework user to set any xds port, so it leaves the decision whether they want to run on ports below 1024 to them. Which is arguably useful. What if we need to run a framework on port 80 to test something for a customer? Or we want to add a special test case for the well known ports?

TBH, I think the benefits of leaving this decision to the user outweigh the downsides.
</blockquote></details>

Sorry, I mistaken it as `service_port_range` in our existing framework https://github.com/grpc/grpc/blob/master/tools/run_tests/run_xds_tests.py#L222.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/traffic_director.py, line 358 at r5](https://reviewable.io/reviews/grpc/grpc/26542#-MeRUtpL0UCmsoYdh6Fn:-MeRUtpL0UCmsoYdh6Fo:b-jsicx0) ([raw file](https://github.com/grpc/grpc/blob/0e75da92eab279877fbe927de2a31b38994f775c/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/traffic_director.py#L358)):*
> ```Python
> 
>     def find_unused_forwarding_rule_port(self,
>                                          lo: int = 1,
> ```

The port range lower bound I'm looking for is here.

**Review by sergiitk — COMMENTED** [review]
All done!

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26542#-:-MeRX3Jp8-Dq2Zw3n7Pf:b-cw6y1x)* status: 2 of 20 files reviewed, 2 unresolved discussions (waiting on @lidizheng)

___
*[tools/run_tests/xds_k8s_test_driver/framework/xds_flags.py, line 94 at r4](https://reviewable.io/reviews/grpc/grpc/26542#-MeRJQm3Cj2X9DOQCtYT:-MeRX0-87WI_q79zyY_Y:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/657b912c48e49636d7bca0c2a717f3bb5f9b0fc6/tools/run_tests/xds_k8s_test_driver/framework/xds_flags.py#L94)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Sorry, I mistaken it as `service_port_range` in our existing framework https://github.com/grpc/grpc/blob/master/tools/run_tests/run_xds_tests.py#L222.
</blockquote></details>

Done.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/traffic_director.py, line 358 at r5](https://reviewable.io/reviews/grpc/grpc/26542#-MeRUtpL0UCmsoYdh6Fn:-MeRX1_u47LZaFboRp0r:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/0e75da92eab279877fbe927de2a31b38994f775c/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/traffic_director.py#L358)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

The port range lower bound I'm looking for is here.
</blockquote></details>

Done.

**Pull request merged**
