### PR TITLE
[PSM Interop] Enable GRPC_EXPERIMENTAL_XDS_ENABLE_OVERRIDE_HOST

### PR DESCRIPTION
**Pull request by eugeneo**

### CODE REVIEW

**Comment by sergiitk** [comment]
- [ ] [grpc/core/master/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/9fbf61c4-add2-4ec8-b732-0aae752398ed)
- [ ] [grpc/core/master/linux/grpc_xds_url_map](https://source.cloud.google.com/results/invocations/5ffcdbe1-805c-47fb-900e-4d338f5e7cba)
- [ ] [grpc/core/master/linux/psm-security](https://source.cloud.google.com/results/invocations/36099ff1-7156-4d9a-be99-59c90f7a6612)
- [ ] [grpc/core/master/linux/psm-gamma](https://source.cloud.google.com/results/invocations/25d1f133-c369-47e1-ab4e-ec90c547a857)

**Review by sergiitk — COMMENTED** [review]
LGTM, running the tests

**Comment by sergiitk** [comment]
Hm. Gamma test failed:

```
framework.helpers.retryers.RetryError: Retry error calling framework.infrastructure.k8s.KubernetesNamespace.get_service: timeout 0:01:00 (h:mm:ss) exceeded. Check result callback returned False.

Reason: A k8s service wasn't assigned a NEG (Network Endpoint Group).
################################################################################
# IMPORTANT: This is not a root cause. This is an indication that
# _something_ -- literally _anything_ -- has gone wrong in the xDS flow.
# It is _your_ responsibility to look through the interop client and/or
# server logs to determine what exactly went wrong.
################################################################################
# Please inspect the information below:
Timeout 0:01:00 (h:mm:ss) waiting for service psm-grpc-server to report NEG status. Last service status:
psm-grpc-server:
---
conditions: null
load_balancer:
  ingress: null
...
```

**Comment by eugeneo** [comment]
Test is flake. It did not use any updated manifests. Error is:

```
I0831 22:00:00.889662 140703409885184 k8s_base_runner.py:540] Deployment psm-grpc-client deletion failed: Kubernetes API returned 404 Not Found: deployments.apps "psm-grpc-client" not found
```

**Comment by sergiitk** [comment]
Appears to be an unrelated flake. Re-running:
- [ ] [grpc/core/master/linux/psm-gamma](https://source.cloud.google.com/results/invocations/aadf7bec-907e-4192-8ecc-300bffb5645a)

**Comment by sergiitk** [comment]
> Test is flake. It did not use any updated manifests. Error is:
> 
> ```
> I0831 22:00:00.889662 140703409885184 k8s_base_runner.py:540] Deployment psm-grpc-client deletion failed: Kubernetes API returned 404 Not Found: deployments.apps "psm-grpc-client" not found
> ```

That's not the error btw. That's just a normal teardown note. The `psm-grpc-client` deployment hasn't been deleted because it doesn't exit - the driver didn't create it as it's failed before that step.

**Review by sergiitk — APPROVED** [review]

**Pull request merged**
