### PR TITLE
Making sure that gpr_free is a no-op for NULL input.

### PR DESCRIPTION
**Pull request by jboeuf**

### CODE REVIEW

**Comment by markdroth** [comment]
I personally don't think this is necessary.  I would consider any implementation of free() that does not ignore NULL to be broken.

That having been said, if Craig has no objection, then I'm okay with it too.

**Comment by jboeuf** [comment]
If my understanding is correct, the free function can be user supplied (custom allocators). If this function, over which we have zero control over, does not do this check, grpc will crash badly in some unexpected manner. 
Adding this check gives me that warm and fuzzy feeling...

**Comment by ctiller** [comment]
I don't think it's necessary, and I noted that earlier, but I also don't object.

**Comment by vjpai** [comment]
Part of the `free` contract is that NULL is a valid argument with no value. If that's also part of the `free_fn` contract, then this could instead be tested in `alloc_test.c` and leave the library alone instead, right?

**Comment by jboeuf** [comment]
I'm not sure how we can test that in alloc_test.c since I can't think of a
way to run these tests after the user of the API has called
gpr_set_allocation_functions.
Now, I'm OK removing this check in gpr_free and having a more precise
documentation for gpr_set_allocation_functions(...).

**Comment by jboeuf** [comment]
Please see new diff and let me know if that works for you.

**Pull request merged**
