### PR TITLE
python: close channels in _server_ssl_cert_config_test

### PR DESCRIPTION
**Pull request by ericgribkoff**
Appears to fix the flake in https://github.com/grpc/grpc/issues/17138

We are diagnosing the root cause, but @lidizheng found that the test became flaky with commit https://github.com/grpc/grpc/pull/15132/commits/ca7ba4d0ac3ab452c5db60befc8be37fd6e2339b, which includes this in the commit notes:

> Noteworthy here is that we drop the cygrpc.Channel.\_\_dealloc__ method.
It is not the same as \_\_del__ (which is not something that can be added
to cygrpc.Channel) and there is no guarantee that \_\_dealloc__ will be
called at all or that it will be called while the cygrpc.Channel
instance's Python attributes are intact (in testing, I saw both in
different environments). This commit does not knowingly break any
garbage-collection-based memory management working (or "happening to
appear to work in some circumstances"), though if it does, **the proper
remedy is to call grpc.Channel.close**... which is the objective towards
which this commit builds.

The `_do_one_shot_client_rpc` method in this test was previously explicitly using `del` to clean up its stub. Since https://github.com/grpc/grpc/pull/15132/commits/ca7ba4d0ac3ab452c5db60befc8be37fd6e2339b this is now (AFAIK) a no-op, and replacing it with an explicit `channel.close()` seems to clean up the flake, I believe the test is back to working-as-intended. Still need to understand the test behavior better to know why it becomes flaky if the channel is not explicitly closed.

### CODE REVIEW

**Comment by ericgribkoff** [comment]
@lidizheng I changed `_do_one_shot_client_rpc` to use the `with ... as channel:` construct. The `persistent_channel_A` and `persistent_channel_B` channels are created and used throughout the test case, so I left those with an explicit close. Creating all the of the channels in setUp and destroying them in tearDown would be slightly different behavior than the current test, so prefer to leave as-is for this PR.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,630      Total (>)     11,175,622

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,624      Total (<)     11,175,629

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,630      Total (>)     11,175,625

 No significant differences in binary sizes


```

**Comment by ericgribkoff** [comment]
I believe we found the root cause of the failing test in #17138: the test includes client channels that reject the server's TLS configuration. This is a connection failure, which means that core will attempt to re-establish the client connection automatically. Each attempt will trigger a call to the dynamic certificate fetcher: the test assumes that, after it attempts one RPC on a channel, no more calls to the server's certificate fetcher will occur. This assumption is false, due to the reconnection attempts. Explicitly closing the channels fixes this (there *could* still be a flake if the reconnection attempt happens before the channel close, but this seems less likely, and will not be made worse by the changes in this PR).

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,626      Total (>)     11,175,625

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,624      Total (<)     11,175,629

 No significant differences in binary sizes


```

**Pull request merged**
