### PR TITLE
Query for TXT service configs with _gprc_config prefix

### PR DESCRIPTION
**Pull request by apolcyn**
Follow up for https://github.com/grpc/proposal/pull/44

Updated test records and added `_grpc_config` as prefix of TXT query. 

Waiting for tests against GCE in https://grpc-testing.appspot.com/job/gRPC_naming_Adhoc/210/

------

looks like tests against GCE DNS are successful

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                    FILE SIZE
 ++++++++++++++ GROWING                                                                      ++++++++++++++
  +0.7%     +32 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc     +32  +0.7%
      +2.2%     +32 grpc_dns_lookup_ares_impl                                                        +32  +2.2%

 -+-+-+-+-+-+-+ MIXED                                                                        +-+-+-+-+-+-+-
  +0.0%     +16 [None]                                                                           -80  -0.0%

  +0.0%     +48 TOTAL                                                                            -48  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
test failures:
* https://github.com/grpc/grpc/issues/13270, mac dbg
* https://github.com/grpc/grpc/issues/13085, mac opt
* https://github.com/grpc/grpc/issues/12932, basic tests multilang
* https://github.com/grpc/grpc/issues/13404, basic tests multilang
* https://github.com/grpc/grpc-node/issues/89, interop cloud to prod
* https://github.com/grpc/grpc-node/issues/89, interop cloud to cloud
* https://github.com/grpc/grpc/issues/13178, tsan c++
* https://github.com/grpc/grpc/issues/12892, ubsan c

**Pull request merged**
