### PR TITLE
Revert "Sanity check that tests declared non-polling actually don't poll"

### PR DESCRIPTION
**Pull request by vjpai**
Reverts grpc/grpc#12953

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                   FILE SIZE
 ++++++++++++++ GROWING                                     ++++++++++++++

 -------------- SHRINKING                                   --------------
  -0.1%    -336 [None]                                         -848  -0.0%
      -0.1%    -288 [Unmapped]                                     -832  -0.0%
      -4.1%     -32 [None]                                            0  [ = ]
     -16.7%     -16 g_factories                                     -16 -16.7%
  -8.4%    -112 src/core/lib/iomgr/ev_posix.cc                 -112  -8.4%
      [DEL]     -78 dummypoll                                       -78  [DEL]
      [DEL]     -35 (anonymous namespace)::init_non_polling         -35  [DEL]
      -4.8%      -9 [Unmapped]                                       -9  -4.8%

  -0.0%    -448 TOTAL                                          -960  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_2_0.opt.new: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.old: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_2_0.counters.old: 1


[microbenchmarks] Performance differences noted:
Benchmark                  cpu_time    real_time
-------------------------  ----------  -----------
BM_MetadataRefUnrefStatic  -12%        -12%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                   FILE SIZE
 ++++++++++++++ GROWING                                     ++++++++++++++

 -------------- SHRINKING                                   --------------
  -0.1%    -368 [None]                                         -848  -0.0%
      -0.1%    -320 [Unmapped]                                     -832  -0.0%
      -4.1%     -32 [None]                                            0  [ = ]
     -16.7%     -16 g_factories                                     -16 -16.7%
  -8.4%    -112 src/core/lib/iomgr/ev_posix.cc                 -112  -8.4%
      [DEL]     -78 dummypoll                                       -78  [DEL]
      [DEL]     -35 (anonymous namespace)::init_non_polling         -35  [DEL]
      -4.8%      -9 [Unmapped]                                       -9  -4.8%

  -0.0%    -480 TOTAL                                          -960  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.new: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.old: 1


[microbenchmarks] Performance differences noted:
Benchmark                                   cpu_time    real_time
------------------------------------------  ----------  -----------
BM_ClosureSched3OnExecCtx                   -5%         -5%
BM_ErrorGetIntFromNoError                   +6%         +6%
BM_ErrorGetStatusCode<ErrorCancelled>       +4%         +4%
BM_ErrorGetStatusCode<ErrorWithGrpcStatus>  +4%         +4%
BM_ErrorHttpError<ErrorCancelled>           +11%        +11%
BM_ErrorHttpError<ErrorNone>                +8%         +8%
BM_ErrorHttpError<SimpleError>              +9%         +9%
```

**Comment by vjpai** [comment]
Superceded by #12965

**Pull request closed without merging**
