### PR TITLE
Add watchOS target

### PR DESCRIPTION
**Pull request by hohteri**
Add watchOS target to support effort to have Firebase Firestore on watchOS. See https://github.com/grpc/grpc/issues/21566

@yashykt

### CODE REVIEW

**Comment by hohteri** [comment]
CLA

**Comment by markdroth** [comment]
The CLA needs to be signed before we can look at this.

**Comment by hohteri** [comment]
Hey, I have signed the CLA but I don’t know how to trigger a new check (this the CLA comment).

**Comment by muxi** [comment]
Ah I was wrong. It is already in `gRPC-Core.podspec`. Yea I think it is fine.

**Comment by markdroth** [comment]
@hohteri The EasyCLA check is still failing.  I don't think you signed it right, or at least not in a way that it recognized.  You'll need to get that resolved before we can look at this.

(Muxi, note that technically, we should not have even looked at the changes until the CLA was signed.)

**Comment by hohteri** [comment]
Hmm... if I open EasyCLA link "Please click here to be authorized." it just redirects me back here as I've already completed the CLA authorisation... Please let me know if I need to do something differently.

**Comment by markdroth** [comment]
@hohteri The check is still failing.  If it's not working for you, try opening a ticket using the link in the CLA message above.

**Comment by hohteri** [comment]
To be exact, it opens a link where I can click "Individual" and then "OPEN CLA", and then it redirects back here. I'm using Safari on a Mac if that is of any help.

**Comment by markdroth** [comment]
We (gRPC) don't own the CLA check; it's run by CNCF.  To get help resolving this, you'll need to open a ticket with them via the link above.

**Comment by hohteri** [comment]
Fixed CLA

**Pull request closed without merging**
