### PR TITLE
Reworked python health checking and added tests

### PR DESCRIPTION
**Pull request by kpayson64**
Health Checking should now be able to be packaged and has unit tests.  

I expect unit tests to fail because there is a dependency on #6437 being pushed to PYPI (Currently we are unable to have grpcio as a dependency).  However, I was able to build against a local repository with the change in #6437 and the unit tests passed.

### CODE REVIEW

**Comment by kpayson64** [comment]
@soltanmm 
running 
```/workspace/grpc2/src/python/grpcio_health_checking/tmp/bin/python setup.py install``` on the generated sdist failse with 
```error: The 'grpcio>=0.13.1' distribution was not found and is required by grpcio-health-checking```

(tmp is a fresh virtualenv)


This is more the result I expected given that it failed as a build dependency as well.  I still believe this to be an artifact of the generated egg missing version info, and #6437 is the easy way to fix that, but am open to alternate solutions.

**Comment by soltanmm** [comment]
You `python setup.py install`'d from the sdist...? One is typically not supposed to do that with an sdist. What does `pip install <sdist here>` have to say?

**Comment by kpayson64** [comment]
pip works fine.  I think the issue is with setuptools, ```easy_install <sdist here>``` also fails.  I think the issue is with the egg installation.  If we don't want to support that, then I think we are all set.

**Comment by soltanmm** [comment]
Also, out of curiosity, do you on your work machine also see a difference between `sudo which pip` and `which pip`? I've not yet thought through how that particular indication may affect this but given what I've seen thus far our work machines seem to have broken Python environments by default. Having mused that, I'll take another look soon-ish.

**Comment by soltanmm** [comment]
Oh, yes, eggs are deprecated.

**Comment by kpayson64** [comment]
If we are not concerned about egg installation, I think this is all set.

I've tested (with a fresh virtual env each time)

```python setup.py sdist```
```pip install <sdist_tgz>```
```import grpc_health.health.v1.health; import grpc_health.health.v1.health_pb2```

```python setup.py bdist_wheel --universal```
```pip install <bdist_whl>```
```import grpc_health.health.v1.health; import grpc_health.health.v1.health_pb2```

**Comment by soltanmm** [comment]
Sorry this slipped again. LGTM.

**Pull request merged**
