### PR TITLE
Upgrading protobuf.

### PR DESCRIPTION
**Pull request by nicolasnoble**
That currently won't work. Python seems to have an issue with that.

Let's treat that Pull Request as an issue, where we can follow its progress through Travis's status.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
[Direct link to the Python issue on Travis](https://travis-ci.org/grpc/grpc/jobs/61011301).

**Comment by nathanielmanistaatgoogle** [comment]
@haberman: does the exception "TypeError: __init__() got an unexpected keyword argument 'syntax'" call to mind any common, simple, obvious mistakes we may be making in this case?

@soltanmm: since this is happening only in python_plugin_test and what's happening is failure when import of the generated _pb2 module is attempted, it's worth looking at for at least twenty or thirty minutes. I can't imagine what we'd be doing wrong, but it's worth learning more details - possibly from looking at the text of the generated code?

**Comment by haberman** [comment]
> does the exception "TypeError: init() got an unexpected keyword argument 'syntax'" call to mind any common, simple, obvious mistakes we may be making in this case?

The `syntax` field was added since the last release to both descriptor.proto and the Descriptor classes in Python. This error suggests to me that you are using generated code from the new version of protobuf, but using either a runtime or a generated descriptor_pb2.py from an earlier version.

What version are you upgrading from, and what version are you upgrading to?

**Comment by nicolasnoble** [comment]
from alpha-1 to alpha-2.

**Comment by nathanielmanistaatgoogle** [comment]
I wonder if the work to be done here is as simple as changing "protobuf==3.0.0-alpha-1" to "protobuf==3.0.0-alpha-2" in src/python/requirements.txt? @nicolasnoble, did you try that in an earlier draft of this pull request?

**Comment by nicolasnoble** [comment]
Let's give it a go.

**Comment by nicolasnoble** [comment]
Nope, same thing: https://travis-ci.org/grpc/grpc/jobs/61660220

**Comment by fta1** [comment]
after building grpc (and protobuf 3.0.0a2) from sources, I stumbled upon that same unexpected keyword argument 'syntax'. I checked and grpc was not using my protobuf (egg) build, it was using alpha1 from pypi instead.
I tried to simply tweak my easy-install.pth to make it point to my alpha2 build, and it worked (the examples in the grpc-common repo).
I ended up just rebuilding with:
sed -i -e 's/3.0.0-alpha-1/3.0.0-alpha-2/' src/python/src/setup.py
It was enough to make it work for me (but there are other hardcoded strict dependencies on alpha-1 in the tree)

**Comment by soltanmm** [comment]
On it, but, an aside: shouldn't [this](https://github.com/grpc/grpc/blob/master/tools/run_tests/run_sanity.sh#L48) file also be changed?

**Comment by nicolasnoble** [comment]
Yes. I will do that last when everything else works.

**Comment by soltanmm** [comment]
It is an upstream issue: https://github.com/google/protobuf/issues/333

**Comment by jtattermusch** [comment]
For gRPC C#, this is basically a release blocker, as it prevents me from upgrading to the version of protobufs that supports C# (which was merged into master just today).

**Comment by jcanizales** [comment]
Same thing with Objective-C. The protoc plugin needs the newer version of the protoc libraries, and alpha release needs the plugin.

**Comment by nicolasnoble** [comment]
Everything seems now working, with the latest protobuf pip package.

**Comment by nicolasnoble** [comment]
Ping.

**Comment by nathanielmanistaatgoogle** [comment]
Please squash commits? Change content looks good.

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle , would you be fine merging this?  Nico is sick today and I depend on this being merged. 
As an alternative, I can recreate this PR with commits squashed so we can merge this today.

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: yes, please recreate the content with commits squashed.

**Comment by jtattermusch** [comment]
@nathanielmanistaatgoogle, I recreated the PR. Thanks for pushing hard towards quality!

**Pull request closed without merging**
