### PR TITLE
Properly compiling distributable native gems.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Pending https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/129/

**Comment by jtattermusch** [comment]
this is ok to test

**Comment by jtattermusch** [comment]
LGTM, merge when green.

**Comment by nicolasnoble** [comment]
Artifact build failed.

**Comment by nicolasnoble** [comment]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/131/

**Comment by nicolasnoble** [comment]
Failed too for another stupid reason. 

https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/132/

**Comment by nicolasnoble** [comment]
image
image

**Comment by nicolasnoble** [comment]
This worked, and I verified the gems are working properly. I'll merge this one.

**Pull request merged**
