### PR TITLE
Add kokoro AWS integration and corresponding test jobs.

### PR DESCRIPTION
**Pull request by jtattermusch**
Implemented by @amidlash and @jtattermusch. The code in the source branch has already been reviewed (by @amidlash or @jtattermusch) and now I'm importing the implementation into upstream/master.

The PR adds test jobs for bazel C/C++, ruby, php, csharp and python that run on real ARM64 hardware.

See go/kokoro-on-aws for internal docs.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Easy CLA is ok since all authors are googlers.

**Comment by jtattermusch** [comment]
@amidlash can you please try to resolve the EasyCLA check failures (I think you need to associate @google.com email with your github account so that EasyCLA can tell you're a googler).

**Review by veblush — APPROVED** [review]

**Comment by jtattermusch** [comment]
adding a comment to bump the easyCLA bot.

**Comment by amidlash** [comment]
@googlebot please rescan

**Comment by jtattermusch** [comment]
I tried to rebase but EasyCLA is still reporting a problem.

**Pull request merged**
