### PR TITLE
Grpc ruby rpc server simple signal handling

### LINKED ISSUE #122: Improving server signal handling
- ruby can only receive signals on the main interpreter thread, and can't receive signals when the ruby GIL is dropped
- by default rpc_server currently runs on the current thread, which will sometimes be the main thread
- update rpc_server so that it runs on a separate thread by default, and has a class method that should be called by the main thread that installs signal handler and waits for interrupts

### PR DESCRIPTION
**Pull request by tbetbetbe**
Fixes #122

### CODE REVIEW

**Comment by jtattermusch** [comment]
Looks like there are conflicts. Otherwise LGTM, so please resolve and then I'll merge.

**Comment by tbetbetbe** [comment]
Done

**Comment by tbetbetbe** [comment]
Done

**Comment by jtattermusch** [comment]
Looks like ruby tests are failing with the latest commit.

**Comment by tbetbetbe** [comment]
To be precise, on the last commit travis failed to build openssl, so the ruby extension did not build.

I.e, should be OK to merge this PR without additional work because:
- as we know, our travis build is a bit flaky
- in general, when it's clear that a commit did not cause the travis-reported failure and earlier commits of the same PR passed, it's should be OK to merge the PR.

Does that make sense ?

E.g, here, the conflicts that you reported before were in the gemspec that defines the ruby extension, which had been checked in on another branch + another change where an incorrect variable reference in ruby is corrected.  Neither of these can cause the reported travis error.

**Pull request merged**
