### PR TITLE
Fix bazel copyright notices

### PR DESCRIPTION
**Pull request by gnossen**
It seems many Bazel files were not being properly tracked by the copyright checker. This PR adds the check and adds a copyright notice to many files that did not previously have them.

### CODE REVIEW

**Review by lidizheng — APPROVED** [review]
Thanks for doing this so quickly!

**Comment by lidizheng** [comment]
FYI, we need to re-generate the project.

**Comment by gnossen** [comment]
Thanks for pointing this out. I didn't realize that some of these were non-template generated files. Fixed.

**Review by jtattermusch — APPROVED** [review]
LGTM once the tests are green

**Pull request merged**
