### PR TITLE
PHP: update param description of function

### PR DESCRIPTION
**Pull request by thinkerou**
- Add some descriptions of function

- Unify to use `$var_name` style

- Update some `$param` to `$return`

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Can you rebase this off the latest master please?

**Comment by thinkerou** [comment]
OK, done.

**Comment by stanley-cheung** [comment]
Sorry can you rebase this once more off the latest master please? Thanks.

**Comment by thinkerou** [comment]
Hi, @stanley-cheung  right now?

**Comment by stanley-cheung** [comment]
Yea thanks. I am hoping the tests will be green now. Let's wait and see

**Comment by thinkerou** [comment]
OK, thanks!

**Pull request merged**
