### PR TITLE
Assert lack of thread contention on queues

### PR DESCRIPTION
**Pull request by soltanmm**
Also remove tests that correspondingly tested improper behavior.

### CODE REVIEW

**Comment by ctiller** [comment]
Why do you do CQ logic in a critical section?

**Comment by soltanmm** [comment]
Because of the invariant in the documentation comments that queues ought to only have one outstanding call to a `poll` or `pluck`.

**Comment by soltanmm** [comment]
Misunderstanding of the doc-comments made apparent out-of-band. Fixin'.

**Comment by soltanmm** [comment]
Just gonna make a new pull request for this.

**Pull request closed without merging**
