### PR TITLE
Move C++ mu_guard class out of C-core public headers and fix style.

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None] -5.42Ki  -0.1%

  [ = ]       0 TOTAL  -5.42Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None] -1.32Ki  -0.0%

  [ = ]       0 TOTAL  -1.32Ki  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,730      Total (=)      1,952,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,663,754      Total (>)     10,663,753

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,730      Total (=)      1,952,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,663,761      Total (>)     10,663,748

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: #15434

**Pull request merged**
