### PR TITLE
Update third_party/protobuf to v3.15.2

### PR DESCRIPTION
**Pull request by karthikravis**
@donnadionne

### CODE REVIEW

**Comment by srini100** [comment]
Let's wait for @jtattermusch's approval and passing tests before merging. LGTM from my side.

**Comment by jtattermusch** [comment]
for some reason the `src/objective-c/BoringSSL-GRPC.podspec` was being updated as well (dirty boringssl version locally?) so I pushed a commit to revert that change.

**Review by jtattermusch — APPROVED** [review]
LGTM, thanks for taking care of this.

**Comment by karthikravis** [comment]
> for some reason the `src/objective-c/BoringSSL-GRPC.podspec` was being updated as well (dirty boringssl version locally?) so I pushed a commit to revert that change.

Apologies, I was updating boringssl and changes from that branch seeped in here. Thanks for fixing this, Jan!

**Comment by karthikravis** [comment]
iOS Binary Size Diff (internal CI) — https://source.cloud.google.com/results/invocations/c73d3cf4-3a8f-4f0a-a43b-277372c8271f/log -  No significant differences in binary sizes, but some infra errors.

Basic Tests Python MacOS — https://source.cloud.google.com/results/invocations/c1ae0202-dac2-43a6-ad71-c5d52c36a576/log - test timeout, unrelated to this PR.

**Pull request merged**
