### PR TITLE
Security connector refactoring

### PR DESCRIPTION
**Pull request by jboeuf**
The security connector is now the object responsible to do the handshake.

I noticed some flakiness in asan due to timing (time out, no memory leaks) in the proxy tests. I don't really understand why. @ctiller do you know what would cause this? When I debug and CTRL-C in the debugger, the thread looks stuck here:

Program received signal SIGINT, Interrupt.
__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135     ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) where
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff76b8657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff76b8480 in __GI___pthread_mutex_lock (mutex=0x61200000ae80) at ../nptl/pthread_mutex_lock.c:79
#3  0x0000000000a089bb in gpr_mu_lock (mu=<optimized out>) at src/core/support/sync_posix.c:48
#4  0x000000000056bf12 in basic_do_promote (args=<optimized out>, success=<optimized out>) at src/core/iomgr/pollset_posix.c:298
#5  0x00000000005180bc in grpc_maybe_call_delayed_callbacks (drop_mu=<optimized out>, success=<optimized out>) at src/core/iomgr/iomgr.c:267
#6  0x0000000000565830 in grpc_pollset_work (pollset=<optimized out>, worker=<optimized out>, deadline=...) at src/core/iomgr/pollset_posix.c:183
#7  0x00000000004e6592 in grpc_completion_queue_next (cc=<optimized out>, deadline=..., reserved=<optimized out>) at src/core/surface/completion_queue.c:199
#8  0x000000000049658a in cq_verify (v=<optimized out>) at test/core/end2end/cq_verifier.c:229
#9  0x0000000000492f7c in request_response_with_payload_and_call_creds (test_name=<optimized out>, config=..., mode=<optimized out>) at test/core/end2end/tests/request_response_with_payload_and_call_creds.c:258
#10 0x000000000048c97e in test_request_response_with_payload_and_call_creds (config=...) at test/core/end2end/tests/request_response_with_payload_and_call_creds.c:377
#11 0x000000000048c2cc in grpc_end2end_tests (config=...) at test/core/end2end/tests/request_response_with_payload_and_call_creds.c:494
#12 0x0000000000488c34 in main (argc=<optimized out>, argv=<optimized out>) at test/core/end2end/fixtures/chttp2_simple_ssl_fullstack_with_proxy.c:207

### CODE REVIEW

**Comment by jboeuf** [comment]
@daniel-j-born may want to have a look.

**Comment by jboeuf** [comment]
This is definitely post-beta.

**Comment by ctiller** [comment]
This definitely needs an update :)

**Comment by jboeuf** [comment]
Yup. On my TODO.

**Comment by jboeuf** [comment]
Merging from master... Oh my... what happened? Oh yes... the endpoint API refactoring! 

I'll try to finish the merge tonight but I don't guarantee anything...

**Comment by jboeuf** [comment]
Merged (it was not that bad after all). 

asan proxy test still timing out (`bins/asan/h2_ssl_proxy_simple_request_test` in particular).

**Comment by jboeuf** [comment]
Anything blocking this PR? I'd prefer to not have to do another kaboom merge if possible :).

**Pull request merged**
