### PR TITLE
Plumbs SAN fields to tsi_peer.

### PR DESCRIPTION
**Pull request by ashithasantosh**
This PR does the following -
1. Plumbs DNS, email and ip address SAN fields to tsi_peer
2. Adds above fields to grpc_auth_context

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25874)

### CODE REVIEW

**Review by ZhenLian — CHANGES_REQUESTED** [review]
Thanks for the effort, Ashitha! I've left some comments. Please let me know if you have any concerns :)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25874#-:-MXkBFkI11No28GsHVlR:buc9p9z)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @ashithasantosh and @jiangtaoli2016)

___
*[src/core/tsi/ssl_transport_security.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk7HNGBFza-eG5C4-1:-MXk7HNGBFza-eG5C4-2:b-ej6i1h) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/src/core/tsi/ssl_transport_security.h#L47)):*
> ```objc
> #define TSI_SSL_ALPN_SELECTED_PROTOCOL "ssl_alpn_selected_protocol"
> 
> #define TSI_X509_DNS_PEER_PROPERTY "x509_dns"
> ```

Since you already added the DNS field, can you please also add the other fields as well(if you have time)? The logic should be quite similar...
We can have two more macros, one for the `ip address`, and the rest goes into a category probably named "unknown" or "other_fields". That way, at least all the names and their types are plumbed. Changing `tsi_peer` is a non-trivial effort, and we might live with it for a while. This way of plumbing is not optimal, but it solves the problems for not having each names and their types exposed.
This can go into another PR, or you can add it to this PR. Thank you so much! 
___
*[src/core/tsi/ssl_transport_security.cc, line 448 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk3DTr0R2LnFuXdZ1Y:-MXk3DTsE7dr1DyIun_H:bafa60a) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/src/core/tsi/ssl_transport_security.cc#L448)):*
> ```cpp
>         sk_GENERAL_NAME_value(subject_alt_names, TSI_SIZE_AS_SIZE(i));
>     if (subject_alt_name->type == GEN_URI ||
>         subject_alt_name->type == GEN_DNS) {
> ```

nit: I should do this earlier, but can you please document then reason why we have to add the property count for URI and DNS here? And also maybe add a TODO for me to clean this up later...
___
*[test/core/security/security_connector_test.cc, line 472 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk5hnp8sejUeSqjdgk:-MXk5hnp8sejUeSqjdgl:b-gtowro) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/test/core/security/security_connector_test.cc#L472)):*
> ```cpp
> static void test_dns_peer_to_auth_context(void) {
>   tsi_peer peer;
>   const char* expected_dns[] = {"dns1", "dns2", "dns3"};
> ```

Let's use C++ style std::vector for this.
___
*[test/core/security/security_connector_test.cc, line 474 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXkAmZGCoZ8YrixaaX1:-MXkAmZGCoZ8YrixaaX2:b-aqxh41) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/test/core/security/security_connector_test.cc#L474)):*
> ```cpp
>   const char* expected_dns[] = {"dns1", "dns2", "dns3"};
>   GPR_ASSERT(tsi_construct_peer(GPR_ARRAY_SIZE(expected_dns), &peer) == TSI_OK);
>   for (size_t i = 0; i < GPR_ARRAY_SIZE(expected_dns); i++) {
> ```

nit: prefer `++i` per C++ style guide: https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement
`Use prefix increment/decrement, unless the code explicitly needs the result of the postfix increment/decrement expression.`
same throughout.
___
*[test/core/tsi/ssl_transport_security_test.cc, line 944 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk6dKF2QktI6ZGUZGS:-MXk6dKF2QktI6ZGUZGT:bmt6wyc) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/test/core/tsi/ssl_transport_security_test.cc#L944)):*
> ```cpp
>   GPR_ASSERT(check_subject_alt_name(&peer, "bar.test.domain.com") == 1);
>   GPR_ASSERT(check_dns(&peer, "foo.test.domain.com") == 1);
>   GPR_ASSERT(check_dns(&peer, "bar.test.domain.com") == 1);
> ```

It seems this is an existing certificate...so I guess it already contained these two DNS fields?

**Review by jiangtaoli2016 — APPROVED** [review]

**Review by ashithasantosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25874)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @ZhenLian)

___
*[src/core/tsi/ssl_transport_security.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk7HNGBFza-eG5C4-1:-MXnMyM3CuVbIVIvz_iE:b-ksivho) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/src/core/tsi/ssl_transport_security.h#L47)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Since you already added the DNS field, can you please also add the other fields as well(if you have time)? The logic should be quite similar...
We can have two more macros, one for the `ip address`, and the rest goes into a category probably named "unknown" or "other_fields". That way, at least all the names and their types are plumbed. Changing `tsi_peer` is a non-trivial effort, and we might live with it for a while. This way of plumbing is not optimal, but it solves the problems for not having each names and their types exposed.
This can go into another PR, or you can add it to this PR. Thank you so much! 
</blockquote></details>

Sure, only the "ip address", or do you want me to add "email" field as well? There are others too, but I don't think it is used much, so like you said we could just have "other_fields" for those.

I couldn't find an existing certificate that has IP address. Do you think there is one I could use for testing purposes? Or should I create a new one, or maybe add ip address SAN to "multi-domain" cert. Is there any doc/reference that I can take a look at for creating/modifying certs?
___
*[src/core/tsi/ssl_transport_security.cc, line 448 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk3DTr0R2LnFuXdZ1Y:-MXnH7j_2tvuQyBwwOQI:bkmtwyb) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/src/core/tsi/ssl_transport_security.cc#L448)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

nit: I should do this earlier, but can you please document then reason why we have to add the property count for URI and DNS here? And also maybe add a TODO for me to clean this up later...
</blockquote></details>

Sure. Added comment. Let me know if this looks good to you.
___
*[test/core/security/security_connector_test.cc, line 472 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk5hnp8sejUeSqjdgk:-MXnKa7h5LBA-5vzNQIq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/test/core/security/security_connector_test.cc#L472)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Let's use C++ style std::vector for this.
</blockquote></details>

Done.
___
*[test/core/tsi/ssl_transport_security_test.cc, line 944 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk6dKF2QktI6ZGUZGS:-MXnLnUM-Mk9QXxXuV6X:bfyfrpm) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/test/core/tsi/ssl_transport_security_test.cc#L944)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

It seems this is an existing certificate...so I guess it already contained these two DNS fields?
</blockquote></details>

This is an existing certificate. My understanding is that the "multi-domain" cert contains 7 SAN fields - 3 URI, 2 DNS and 2 email. Please do verify this if needed, as I am not familiar with test certificates.

**Review by ZhenLian — CHANGES_REQUESTED** [review]
Thanks for the quick fix! I can approve this now, or wait until your new changes come in(whichever way you prefer).
Feel free to let me know how you want to proceed:)

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25874#-:-MXowDR43afKumytzzTC:b-rx3jq6)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ashithasantosh)

___
*[src/core/tsi/ssl_transport_security.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk7HNGBFza-eG5C4-1:-MXorpCJ4arfVGMIp4Vf:b-4s1nba) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/src/core/tsi/ssl_transport_security.h#L47)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

Sure, only the "ip address", or do you want me to add "email" field as well? There are others too, but I don't think it is used much, so like you said we could just have "other_fields" for those.

I couldn't find an existing certificate that has IP address. Do you think there is one I could use for testing purposes? Or should I create a new one, or maybe add ip address SAN to "multi-domain" cert. Is there any doc/reference that I can take a look at for creating/modifying certs?
</blockquote></details>

Great, thank you so much! Yeah having another "email" field would be even better.
I don't think we have a cert with IP address. I could create one for you, or you could also refer to https://github.com/grpc/grpc/blob/master/src/core/tsi/test_creds/README for how to create a test cert using OpenSSL. It could be a cert containing all the fields we need, and will replace the "multi-domain" cert. Feel free to let me know how you want to proceed :)
___
*[test/core/tsi/ssl_transport_security_test.cc, line 944 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk6dKF2QktI6ZGUZGS:-MXotj9V1ovYYZfeoVVD:blcqzmh) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/test/core/tsi/ssl_transport_security_test.cc#L944)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

This is an existing certificate. My understanding is that the "multi-domain" cert contains 7 SAN fields - 3 URI, 2 DNS and 2 email. Please do verify this if needed, as I am not familiar with test certificates.
</blockquote></details>

Yeah, those 7 fields are all the SAN fields in the cert(you can use OpenSSL command to parse the cert content, or even easier copy-paste the content to an online certificate parser website, since it is a test cert).
We might want to replace it with a cert which has additional one "ip address" field and one "other_name" field.

**Comment by jiangtaoli2016** [comment]
@yihuazhang generated the multi-domain certificate. The config is [here](https://github.com/grpc/grpc/blob/master/src/core/tsi/test_creds/multi-domain-openssl.cnf). Adding a few more fields should be easy.

**Review by ashithasantosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25874)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ashithasantosh and @ZhenLian)

___
*[src/core/tsi/ssl_transport_security.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk7HNGBFza-eG5C4-1:-MXx0vBK6eKWiyeBnjUO:b-l7jwjt) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/src/core/tsi/ssl_transport_security.h#L47)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Great, thank you so much! Yeah having another "email" field would be even better.
I don't think we have a cert with IP address. I could create one for you, or you could also refer to https://github.com/grpc/grpc/blob/master/src/core/tsi/test_creds/README for how to create a test cert using OpenSSL. It could be a cert containing all the fields we need, and will replace the "multi-domain" cert. Feel free to let me know how you want to proceed :)
</blockquote></details>

Thanks Zhen, for the guidance and tips!:)  I submitted the modified certificate.

The PR is not ready for review yet.  I wanted to discuss about "other_fields" san with you, before making the changes.

Currently in TSI_X509_SUBJECT_ALTERNATIVE_NAME_PEER_PROPERTY, apart from uri, dns, email and ip, the other field values are not extracted, it is just stored as "other types of san".
https://github.com/grpc/grpc/blob/2b0f8b631372938af214c1ce1705298911f7afdd/src/core/tsi/ssl_transport_security.cc#L413-L415
Do we still want to add "other_fields" additionally? It might be better to add it later, when we remove the duplicate entries (by removing TSI_X509_SUBJECT_ALTERNATIVE_NAME_PEER_PROPERTY). Wdyt?

Also,  I tried looking into extracting the other field values, it is not straightforward, as they have different types. If these values are not used, we could continue adding them with dummy values "other types of san" for now.

**Review by ZhenLian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25874)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ashithasantosh)

___
*[src/core/tsi/ssl_transport_security.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk7HNGBFza-eG5C4-1:-MYGRubrBsJg__CE5I6K:b-gcwbpt) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/src/core/tsi/ssl_transport_security.h#L47)):*
<details><summary><i>Previously, ashithasantosh (Ashitha Santhosh) wrote…</i></summary><blockquote>

Thanks Zhen, for the guidance and tips!:)  I submitted the modified certificate.

The PR is not ready for review yet.  I wanted to discuss about "other_fields" san with you, before making the changes.

Currently in TSI_X509_SUBJECT_ALTERNATIVE_NAME_PEER_PROPERTY, apart from uri, dns, email and ip, the other field values are not extracted, it is just stored as "other types of san".
https://github.com/grpc/grpc/blob/2b0f8b631372938af214c1ce1705298911f7afdd/src/core/tsi/ssl_transport_security.cc#L413-L415
Do we still want to add "other_fields" additionally? It might be better to add it later, when we remove the duplicate entries (by removing TSI_X509_SUBJECT_ALTERNATIVE_NAME_PEER_PROPERTY). Wdyt?

Also,  I tried looking into extracting the other field values, it is not straightforward, as they have different types. If these values are not used, we could continue adding them with dummy values "other types of san" for now.
</blockquote></details>

Sure, then I think we can probably ignore "other_fields" here, since I don't see any potential projects claiming to use it at this moment.
We can always add it later when we have to. 
Thanks for the investigation!

**Comment by ashithasantosh** [comment]
Thanks for the review, @jiangtaoli2016 and @ZhenLian!:)

**Review by ashithasantosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25874)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ZhenLian)

___
*[src/core/tsi/ssl_transport_security.h, line 47 at r1](https://reviewable.io/reviews/grpc/grpc/25874#-MXk7HNGBFza-eG5C4-1:-MYLfBxoD4n_0kgl5yK6:b-c26fnt) ([raw file](https://github.com/grpc/grpc/blob/3efe09d218c1f4c7b72e743fd778660f53b792a6/src/core/tsi/ssl_transport_security.h#L47)):*
<details><summary><i>Previously, ZhenLian wrote…</i></summary><blockquote>

Sure, then I think we can probably ignore "other_fields" here, since I don't see any potential projects claiming to use it at this moment.
We can always add it later when we have to. 
Thanks for the investigation!
</blockquote></details>

SG. Thanks! I added email and ip san. For now, we will ignore other_fields.

**Pull request merged**
