### PR TITLE
Fix a missing initialization

### PR DESCRIPTION
**Pull request by dklempner**
Fix a missing initialization of TestServerBuilderPlugin::register_service_

### CODE REVIEW

**Comment by y-zeng** [comment]
LGTM. Thank for fixing it!

**Comment by ctiller** [comment]
Does someone want to get MSAN C++ testing up and running?

**Comment by dklempner** [comment]
Right, msan would definitely catch this.

This came out of an asan run internally, which noticed a load of a bad bool (not 0 or 1); I'm assuming our asan runs don't include that check.

**Comment by ctiller** [comment]
It shouldn't be awful to do either.

I stopped because protoc fails (which means we fail to build).
Alternatives:
1. fix protoc, get huge thanks from the proto team
2. fix Makefile, build protoc as opt, and everything else as msan
3 = 2 + 1

**Comment by dklempner** [comment]
I believe failures are unrelated: the msan failure is a timeout.

**Comment by jtattermusch** [comment]
test this please

**Pull request merged**
