### PR TITLE
Fix C build in Visual Studio (internal_ci)

### PR DESCRIPTION
**Pull request by jtattermusch**
- switch default C and C++ build from VS2013 to VS2015 (this would probably happen anyway sooner or later, current cmake build is using VS2015)
- download nuget.exe to be able to restore vsprojects/grpc.sln (C build)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by jtattermusch** [comment]
Seems like this is failing windows builds on Jenkins. Will investigate.

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by jtattermusch** [comment]
Looks like this PR won't be necesssary, the v6prod windows image has nuget available and VS2013 installed.

**Pull request closed without merging**
