### PR TITLE
Release 0.11 to master upmerge.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Everything is in 0.11, this can now be merged.

**Comment by dgquintas** [comment]
Ack. Waiting for Jenkins

**Comment by murgatroid99** [comment]
Can we merge this soon?

**Comment by dgquintas** [comment]
Yes, as soon as people stop adding commits and jenkins is green enough.

**Comment by nicolasnoble** [comment]
:clap:

**Comment by dgquintas** [comment]
:v:

**Comment by jcanizales** [comment]
\o/

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @tbetbetbe isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* User @soltanmm isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
