### PR TITLE
Update QPS test to proto3

### LINKED ISSUE #1677: Update QPS proto
I recently updated the QPS proto to be in conformance with the proto3 styleguide: https://github.com/grpc/grpc-java/blob/master/benchmarks/src/main/proto/qpstest.proto.

We should make the same change to this repo's version.

### PR DESCRIPTION
**Pull request by vjpai**
Switch to proto3 syntax
Fixes #1677 
Do not merge until after completing PR #1948

### CODE REVIEW

**Comment by vjpai** [comment]
Nathan, are you ok with what  I've done to qpstest.proto here? Does this address #1677 in your opinion? It's still not the same as Java because we have additional open-loop parameters, but I think that it takes care of the Proto3 syntax issue. I've still marked this DNM until #1948 gets in.

**Comment by vjpai** [comment]
Removed the DNM. Please take a look.

**Comment by vjpai** [comment]
Putting the DNM back on.

**Comment by vjpai** [comment]
Removed the DNM since #1984 went in.

**Comment by vjpai** [comment]
... and it's green!

**Comment by nmittler** [comment]
LGTM

**Pull request merged**
