### PR TITLE
DO NOT MERGE: Test upgrade to protobuf 4.0.0-rc1

### PR DESCRIPTION
**Pull request by stanley-cheung**
Protobuf just released version [`4.0.0-rc1`](https://github.com/protocolbuffers/protobuf/releases). This PR is to attempt to run our tests early to identify potential issues.

There is no language package uploaded for this release candidate yet.

This is a Draft PR - DO NOT MERGE please.

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Looks like some of these tests (esp those involving ObjC cocoapods) won't work without the 4.0.0-rc1 packages being uploaded first. Protobuf team said that they will - just being held up by some other issues. Will check again.

**Comment by stanley-cheung** [comment]
`4.0.0-rc1` packages for Ruby gems have been uploaded, but not for Cocoapods yet. Will keep monitoring.

**Comment by stanley-cheung** [comment]
`4.0.0-rc1` packages for Ruby, C# and Obj-C have been uploaded. Running a new set of tests...

**Comment by stanley-cheung** [comment]
Looks like one big category of error is this one, involving gems dependency:

```
+ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "google-protobuf":
  In Gemfile:
    grpc was resolved to 1.31.0.dev, which depends on
googleapis-common-protos-types (~> 1.0) was resolved to 1.0.4, which
depends on
        google-protobuf (~> 3.0)

    grpc was resolved to 1.31.0.dev, which depends on
      google-protobuf (>= 4.0.0.rc.1)
```

Looks like we might need to submit a PR to get this line fixed first: https://github.com/googleapis/common-protos-ruby/blob/master/googleapis-common-protos-types/googleapis-common-protos-types.gemspec#L38

**Comment by acozzette** [comment]
@stanley-cheung We ended up deciding that we are not going to increase the major version yet, and instead we are going to release 3.13.0 next. We're still releasing from the same branch cut, though. Would it be worthwhile to create another pull request like this one to test the 3.13.0-rc3 release?

**Comment by stanley-cheung** [comment]
@acozzette Yes I will do that today. Thanks for letting us know.

**Pull request closed without merging**
