### PR TITLE
Reverts #16179

### PR DESCRIPTION
**Pull request by ncteisen**
cc @jtattermusch @srini100

### CODE REVIEW

**Comment by ncteisen** [comment]
Duplicate of #16243

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++

 -------------- SHRINKING                                                   --------------
  -0.1%     -16 src/core/ext/transport/chttp2/transport/chttp2_transport.cc     -16  -0.1%
      -2.5%     -16 grpc_chttp2_complete_closure_step                               -16  -2.5%

 -+-+-+-+-+-+-+ MIXED                                                       +-+-+-+-+-+-+-
  +0.0%     +16 [None]                                                          -32  -0.0%

  [ = ]       0 TOTAL                                                           -48  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,980,675      Total (<)      1,980,683

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,811,769      Total (>)     10,811,757

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                       cpu_time    real_time
----------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/2097152  +6%         +6%
```

**Pull request closed without merging**
