### PR TITLE
update third_party/xxhash

### PR DESCRIPTION
**Pull request by HannahShiSFB**
update third_party/xxhash to reflect the fix of xxhash [issue#590](https://github.com/Cyan4973/xxHash/issues/590), mentioned in [PR#27609](https://github.com/grpc/grpc/pull/27609)

@drfloob
@dennycd

### CODE REVIEW

**Review by dennycd — COMMENTED** [review]
@HannahShiSFB  should we patch this by updating gRPC's dependency to point to a new xxhash revision/ release tag ?

**Comment by drfloob** [comment]
@donnadionne xxhash was tracked as a subtree originally, but we manually deleted a lot of unnecessary files. Is there an update process? I'm not sure if `git subtree pull ...` will re-acquire those deleted files.

**Comment by drfloob** [comment]
Also, thanks @HannahShiSFB for the fix! How did you generate the patch?

@donnadionne `git subtree pull` appears to be broken. I think we could instead do something like adding the xxhash remote, pulling to a branch, then squash-merging to master. But whatever it is, we should document the process if it isn't already.

**Comment by donnadionne** [comment]
I remember having some trouble importing xxhash properly; it was originally attempted to be added as header only, but then we ended up adding it as a subtree but pretty much only using the xxhash.h file.  How is git subtree pull broken?  I can try it out and document any workaround may be needed.

Including @nicolasnoble in this to see if he has good solutions

**Comment by donnadionne** [comment]
For this PR, i triggered adhoc 👍 
https://fusion2.corp.google.com/invocations/720c867c-a687-441e-8559-f03a57ea7d82/targets

let's make sure that is clean

**Comment by donnadionne** [comment]
Here is the result to adhoc: https://fusion2.corp.google.com/invocations/7da31b89-4818-45d6-85ef-ae45939808d1/details

**Comment by HannahShiSFB** [comment]
I followed the instruction in 
https://github.com/grpc/grpc/tree/master/third_party#updating-third_partyxxhash
to update the xxhash.

**Review by drfloob — APPROVED** [review]
> I followed the instruction in
> https://github.com/grpc/grpc/tree/master/third_party#updating-third_partyxxhash
> to update the xxhash.

Oh excellent! I didn't realize it was documented there. The ad hoc run looks good, and the test failures are unrelated (a bug may need to be filed for the one labeled "kokoro", that test looks broken). Thanks Hannah!

**Review by dennycd — APPROVED** [review]

**Pull request merged**
