### PR TITLE
Make sure to accept expected tags exactly once

### LINKED ISSUE #12873: FLAKE: AsyncEnd2end/AsyncEnd2endTest.SimpleBidiStreamingWithCoalescingApiWAF/15
https://sponge.corp.google.com/target?id=afa712d5-339b-414e-85c8-7ae668cf408b&target=github/grpc/c%2B%2B_linux_dbg_native&searchFor=&show=ALL&sortBy=STATUS

Note: Google Test filter = AsyncEnd2end/AsyncEnd2endTest.SimpleBidiStreamingWithCoalescingApiWAF/15
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from AsyncEnd2end/AsyncEnd2endTest
[ RUN      ] AsyncEnd2end/AsyncEnd2endTest.SimpleBidiStreamingWithCoalescingApiWAF/15
D1006 19:31:53.566215031     758 async_end2end_test.cc:273]  TestScenario{disable_blocking=false, inproc=false, credentials='INSECURE_CREDENTIALS, health_check_service=false', message_size=1048576}
I1006 19:31:53.566352462     758 ev_epoll1_linux.cc:93]      grpc epoll fd: 3
D1006 19:31:53.566369552     758 ev_posix.cc:107]            Using polling engine: epoll1
D1006 19:31:53.566384022     758 dns_resolver.cc:306]        Using native dns resolver
I1006 19:31:53.568922466     758 ev_epoll1_linux.cc:93]      grpc epoll fd: 3
D1006 19:31:53.568945992     758 ev_posix.cc:107]            Using polling engine: epoll1
D1006 19:31:53.568959804     758 dns_resolver.cc:306]        Using native dns resolver
E1006 19:31:53.577235061     758 async_end2end_test.cc:206]  Unexpected tag: 0x40f709

### PR DESCRIPTION
**Pull request by vjpai**
Fixes #12873

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by vjpai** [comment]
Test failures: #12917 #11737

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.new: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.old: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_2_0.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Pull request merged**
