### PR TITLE
Fix bm_diff

### PR DESCRIPTION
**Pull request by ncteisen**
Take 1

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Sanity check passed, AKA the bot ran and posted results. Let's merge this in and see if the noise is reduced?

**Comment by matt-kwong** [comment]
I didn't know `bm_main.py` used `jobset.py`. Something you could actually do is set the cpu_estimated in a test high enough that it either runs exclusively or with less tests in parallel. 

Overall, randomizing the test order might reduce noise, but I'm doubtful it'll get us back to where we were a couple months ago.

**Comment by ncteisen** [comment]
That risks increasing runtime. But I guess slow, reliable bm_diff is preferable to quick, nonsense bm_diff. I increased to 2 cores. Most of the benchmarks, only need one thread, but the fullstack_* might spin up a few in the executor.... I;ll actually look later

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Sanity passes

**Comment by ncteisen** [comment]
Merging now. Let's "live" test this on PRs as they come in and improve as we go. That seems like the fastest way for now

**Comment by ncteisen** [comment]
This is the first effort towards #12614

**Pull request merged**
