### PR TITLE
V1.0.x merge into master

### PR DESCRIPTION
**Pull request by murgatroid99**
CC @nathanielmanistaatgoogle @soltanmm 
I had to guess what the correct conflict resolution was for tools/distrib/python/grpcio_tools/setup.py. Can you check that the merged version here is correct?

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Also cc @kpayson64.

**Comment by murgatroid99** [comment]
I think I may not have merged correctly.

**Comment by soltanmm** [comment]
For `grpcio-tools`' `tools/distrib/python/grpcio_tools/setup.py`:
```python
141 <<<<<<< HEAD
142 def extension_modules():
143   if BUILD_WITH_CYTHON:
144     plugin_sources = ['grpc/tools/_protoc_compiler.pyx']
145   else:
146     plugin_sources = ['grpc/tools/_protoc_compiler.cpp']
147   plugin_sources += [
148       'grpc/tools/main.cc',
149       'grpc_root/src/compiler/python_generator.cc'] + [
150       os.path.join(protoc_lib_deps.CC_INCLUDE, cc_file)
151       for cc_file in protoc_lib_deps.CC_FILES]
152   plugin_ext = extension.Extension(
153       name='grpc.tools._protoc_compiler',
154       sources=plugin_sources,
155 =======
156 def protoc_ext_module():
157   plugin_sources = [
158       os.path.join('grpc', 'tools', 'main.cc'),
159       os.path.join('grpc_root', 'src', 'compiler', 'python_generator.cc')] + [
160       os.path.join(CC_INCLUDE, cc_file)
161       for cc_file in CC_FILES]
162   plugin_ext = extension.Extension(
163       name='grpc.tools._protoc_compiler',
164       sources=(
165           [os.path.join('grpc', 'tools', '_protoc_compiler.pyx')] +
166           plugin_sources),
167 >>>>>>> v1.0.x
```

becomes

```python
def extension_modules():
  if BUILD_WITH_CYTHON:
    plugin_sources = [os.path.join('grpc', 'tools', '_protoc_compiler.pyx')]
  else:
    plugin_sources = [os.path.join('grpc', 'tools', '_protoc_compiler.cpp')]
    plugin_sources += [
      os.path.join('grpc', 'tools', 'main.cc'),
      os.path.join('grpc_root', 'src', 'compiler', 'python_generator.cc')] + [
      os.path.join(CC_INCLUDE, cc_file)
      for cc_file in CC_FILES]
  plugin_ext = extension.Extension(
      name='grpc.tools._protoc_compiler',
      sources=plugin_sources,
```

**Comment by murgatroid99** [comment]
@soltanmm Can you also look at `src/python/grpcio/_unixccompiler_patch.py`?

**Comment by soltanmm** [comment]
@murgatroid99 `_unixccompiler_patch.py` file looks good.

**Comment by murgatroid99** [comment]
The interop test build appears to be failing with a Python protoc related error. Do you know what's going on there?

**Comment by nicolasnoble** [comment]
```
ImportError: /var/local/git/grpc/py27/lib/python2.7/site-packages/grpc/tools/_protoc_compiler.so: undefined symbol: _Z11protoc_mainiPPc
```

@soltanmm ? @kpayson64 ? @nathanielmanistaatgoogle ? Anyone ? Bueller ?

**Comment by nathanielmanistaatgoogle** [comment]
I don't know off the top of my head what's going on but am looking.

What's with the sanity test failure?

Earlier in the log of the failing interop test I see
```
+ cd /var/local/git/grpc
+ /var/local/git/grpc/py27/bin/python /var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py
/var/local/git/grpc/tools/distrib/python/bazel_deps.sh: line 39: bazel: command not found
Got non-fatal error:
Traceback (most recent call last):
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 217, in main
    protoc_lib_deps_content = get_deps()
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 118, in get_deps
    cc_files_output = bazel_query(BAZEL_DEPS_PROTOC_LIB_QUERY)
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 112, in bazel_query
    output = subprocess.check_output([BAZEL_DEPS, query])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/var/local/git/grpc/tools/distrib/python/bazel_deps.sh', '//:protoc_lib']' returned non-zero exit status 127
```
; is that a known or understood thing?

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle That's a known, understood, non-fatal error (the message says non-fatal anyway and I recall writing it as being a non-fatal error). It's just saying that it can't regenerate certain files which require bazel (or indirectly require docker) and some build systems don't have either so we just keep up-to-date files in the repository.

**Comment by soltanmm** [comment]
Sorry @murgatroid99 ; gave you the wrong patch. Here it is, corrected:

```python
def extension_modules():
  if BUILD_WITH_CYTHON:
    plugin_sources = [os.path.join('grpc', 'tools', '_protoc_compiler.pyx')]
  else:
    plugin_sources = [os.path.join('grpc', 'tools', '_protoc_compiler.cpp')]
  plugin_sources += [
    os.path.join('grpc', 'tools', 'main.cc'),
    os.path.join('grpc_root', 'src', 'compiler', 'python_generator.cc')] + [
    os.path.join(CC_INCLUDE, cc_file)
    for cc_file in CC_FILES]
  plugin_ext = extension.Extension(
      name='grpc.tools._protoc_compiler',
      sources=plugin_sources,
```

**Comment by murgatroid99** [comment]
This looks basically green, besides a couple of flakes.

**Comment by murgatroid99** [comment]
I would squash the commits I made in this PR, but I can't figure out how to squash commits into a merge commit.

**Comment by nicolasnoble** [comment]
Merge commits should never be squashed, otherwise you would no longer be able to properly merge afterward, which defeats the purpose of such PR.

I'm slightly interested in the Travis build, just to see if we don't break ObjC.

**Pull request merged**
