### PR TITLE
remove notification observer to avoid iOS 8 crash

### LINKED ISSUE #18567: iphone5 ios8 Change NetWork is Crash
### What version of gRPC and what language are you using?
 
Objective-c
 
### What operating system (Linux, Windows,...) and version?
 
iOS 8.0    Iphone5
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?

Crash Log

2019-03-29 15:13:25.319 teacher[1266:92727] -[UIImageView connectivityChanged:]: unrecognized selector sent to instance 0x14ff1130
2019-03-29 15:13:59.490 teacher[1266:92727] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImageView connectivityChanged:]: unrecognized selector sent to instance 0x14ff1130'
*** First throw call stack:
(0x2a99de3f 0x3804bc8b 0x2a9a3189 0x2a9a10a7 0x2a8d3208 0x2a9564a1 0x2a8b293d 0x2b5e29b9 0x2b5e751f 0x21fcb7b 0x2dde49c7 0x2a96458f 0x2a96399f 0x2a962005 0x2a8b0621 0x2a8b0433 0x31c5e0a9 0x2de9a809 0xc752b 0x385cbaaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

### PR DESCRIPTION
**Pull request by HarrisonXi**
fix #18567

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @HarrisonXi isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by muxi** [comment]
@HarrisonXi  Thank you for the change. Could you sign the CLA in order to get your commit merged?

**Comment by HarrisonXi** [comment]
signed the CLA

**Comment by HarrisonXi** [comment]
I signed it

**Comment by HarrisonXi** [comment]
I signed it

**Comment by HarrisonXi** [comment]
I signed it

**Comment by muxi** [comment]
Basic Tests ObjC MacOS - #18195
Interop Cloud-to-Cloud Tests - #18967
Interop Cloud-to-Prod Tests - #18967

**Pull request merged**
