### PR TITLE
Upgrading unaligned reads to aligned reads.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Just to see what microbenchmarks are going to say about this one.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                               FILE SIZE
 ++++++++++++++ GROWING                                                 ++++++++++++++
  +5.0% +34.6Ki [None]                                                  +35.8Ki  +0.4%
      +300% +23.3Ki emit_sub_tbl                                            +23.3Ki  +300%
      +300% +4.50Ki next_sub_tbl                                            +4.50Ki  +300%
      +700% +1.75Ki first_byte_lut                                          +1.75Ki  +700%
      +700% +1.75Ki inverse_base64                                          +1.75Ki  +700%
      +700% +1.75Ki next_tbl                                                +1.75Ki  +700%
      +300% +1.50Ki emit_tbl                                                +1.50Ki  +300%
      +0.0%     +16 [Unmapped]                                              +1.24Ki  +0.0%
  +0.1%     +16 src/core/ext/transport/chttp2/transport/hpack_parser.cc     +16  +0.1%
      +1.6%     +16 append_string                                               +16  +1.6%
      +4.8%      +8 huff_nibble                                                  +8  +4.8%

  +2.5% +34.6Ki TOTAL                                                   +35.9Ki  +0.4%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                              cpu_time    real_time
-------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/32768                                           -4%         -4%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/1/1  -4%         -4%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/262144                         -4%         -4%
```

**Comment by nicolasnoble** [comment]
-4% for +35kB ? I can live with this.

**Comment by ncteisen** [comment]
The fact that it is only these three benchmarks leads me to believe this is just noise from GCE shift. Let's rerun

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by nicolasnoble** [comment]
Yeah, this is weird these 3 tests are showing improvement with no other results. Meh. We knew that without any actual hotspot information, this was kind of a shot in the dark. We really need hotspot marking :-)

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
