### PR TITLE
C# "-dev" nugets should have a timestamped suffix.

### PR DESCRIPTION
**Pull request by jtattermusch**
This should address https://github.com/grpc/grpc/issues/17886.

- some packages were still being built from .nuspec. Switch them to .csproj so that a unified way of patching the nuget version can be used.
- cleanup of the batch script to build nuget packages (version is not needed in that script anymore, so it can stop being generated from a template)
- add a simple scripts that modifies the props file that contains the C# nugets' version number (if there's -dev suffix, add timestamp).

### CODE REVIEW

**Comment by jtattermusch** [comment]
I'll post a link to a package build experiment once available.

**Comment by jtattermusch** [comment]
@dawidfowl @JunTaoLuo  @JamesNK

**Comment by JamesNK** [comment]
@davidfowl 🐴

**Comment by jtattermusch** [comment]
I am going to merge as is because I want the nightly packages generated ASAP, but I might add a followup PR to do a bit more cleanup around the nugets.

**Comment by jtattermusch** [comment]
Daily packages with this change are already available:
https://packages.grpc.io/archive/2019/02/f7ef20b5104bb62aa438aacfe7d8e46058f517b1-13da6a86-a39e-4edf-ae92-9ac26f04a995/index.xml

**Pull request merged**
