### PR TITLE
Add sys/epoll.h header to relevant files

### PR DESCRIPTION
**Pull request by kwasimensah**
EPOLL_CLOEXEC should come from this header and wasn't explicitly included before

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by nicolasnoble** [comment]
Everything seems to be building as intended. Passing it over to @sreecha for 2nd approval and merging.

**Comment by kwasimensah** [comment]
Friendly ping.

**Pull request merged**
