### PR TITLE
Obj c duplicate

### PR DESCRIPTION
**Pull request by gnossen**
CC @jtattermusch

### CODE REVIEW

**Comment by jtattermusch** [comment]
Still an error, but probably just an oversight
https://source.cloud.google.com/results/invocations/1d2574be-ac4d-4630-817a-ae95527eeae8/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_bazel_build/log

**Comment by jtattermusch** [comment]
I fixed the build error with https://github.com/grpc/grpc/pull/23902/commits/57161a7a947ad10afe34ff930e08c41b3ab37d61

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/23902 has been merged.

**Comment by jtattermusch** [comment]
@gnossen  thanks for the help!

**Comment by gnossen** [comment]
Oh whoops. Yeah, I forgot to push up my change to `examples/proto/BUILD`. Sorry about that!

**Pull request closed without merging**
