### PR TITLE
Enable vsock as a transport for gRPC

### PR DESCRIPTION
**Pull request by egranata**
This patch is based on https://android-review.googlesource.com/c/platform/external/grpc-grpc/+/1205919 where we enabled vsock support in the AOSP gRPC tree

We would like to bring this support back to the mainline tree

Any and all help in getting this reviewed and merged would be greatly appreciated.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
@ejona86 is this sort of naming scheme something we want to keep promoting? This is adding `vsock:` as a naming scheme here.

**Comment by nicolasnoble** [comment]
Also as a general code style, we try as much as possible to avoid the paradigms of:

```C
void doSomething() {
#ifdef X
doSomethingWithX();
#else
doAFallback();
#endif
}
```

And rather have whole files dedicated to features being enabled / disabled. In this case, this would mean having a `vsock.cc` file that contains all the vsock-enabled function, with a global `#ifdef` / `#endif` around it, and a `novsock.cc` file that contains all the opposites.

**Comment by ejona86** [comment]
`vsock:` prefix is fine. Although because that is an address, it would be most similar to `ip:`, `inprocess:`, `unix:`, which are something a bit more akin to convenience.

Now the format appears to be `vsock:cid:port`. I don't know if that is the format we want. But using the scheme vsock seems fine. (FWIW, Java today doesn't support _any_ of the schemes I've mentioned here. I think Go only supports `unix:`. Java would like to support inprocess and unix, though.)

**Comment by egranata** [comment]
> `vsock:` prefix is fine. Although because that is an address, it would be most similar to `ip:`, `inprocess:`, `unix:`, which are something a bit more akin to convenience.
> 
> Now the format appears to be `vsock:cid:port`. I don't know if that is the format we want. But using the scheme vsock seems fine. (FWIW, Java today doesn't support _any_ of the schemes I've mentioned here. I think Go only supports `unix:`. Java would like to support inprocess and unix, though.)

I think we are definitely open to suggestions on the format of the name. What do you think would work better than `vsock:cid:port` here?

**Comment by egranata** [comment]
> Also as a general code style, we try as much as possible to avoid the paradigms of:
> 
> ```c
> void doSomething() {
> #ifdef X
>   doSomethingWithX();
> #else
>   doAFallback();
> #endif
> }
> ```
> 
> And rather have whole files dedicated to features being enabled / disabled. In this case, this would mean having a `vsock.cc` file that contains all the vsock-enabled function, with a global `#ifdef` / `#endif` around it, and a `novsock.cc` file that contains all the opposites.

Got it. I can certainly work on that.

**Comment by egranata** [comment]
I have taken the feedback into account and moved several of the `#ifdef` blocks into separate files. There's a few smaller sections of conditional code that I left as-is, just because they are one or two lines each.

Please do take a look when you get a chance.

Thanks all for the feedback so far.

**Comment by markdroth** [comment]
We can't look at this until you sign the CLA.

**Comment by egranata** [comment]
> We can't look at this until you sign the CLA.

Do Google FTEs need to sign this CLA as well?

**Comment by ejona86** [comment]
@egranata, yes, but no. It is already signed but you need to help the bot know you are a corporate user by logging in to it with your `@google.com` account.

**Comment by egranata** [comment]
> @egranata, yes, but no. It is already signed but you need to help the bot know you are a corporate user by logging in to it with your `@google.com` account.

Aha, done. I was signed in, but I had never allowed the EasyCLA OAuth agent. Now it looks like it's green. Thanks for the heads up!

**Comment by karthikravis** [comment]
Needs language label to pass "Mergeable" check

**Comment by egranata** [comment]
> Needs language label to pass "Mergeable" check

How do I add it? I see a Labels sidebar, but I don't think I can edit it

**Comment by egranata** [comment]
> I've added the necessary labels and triggered the tests to run. It looks like there are a lot of failures, so please take a look at them.
> 

I looked at some of the build failures, looks like I had a few compile errors that my local build didn't catch. I think I addressed them, but happy to get new results & keep iterating. Unfortunately, I don't have access to anything but a Linux host.

> Please also update the PR description into a form that will be appropriate for the gRPC release notes.

What's a good PR to look at for this?

> > Reviewed 28 of 28 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/grpc/grpc/21745#-:-LzryBeq-97VZXIz-1XV:b-iz94uh)_ status: all files reviewed, 8 unresolved discussions (waiting on @egranata)
> 
> _[BUILD, line 753 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-LzrnFpXApUutvQZ_vIM:-LzrnFpXApUutvQZ_vIN:b-6vvn03) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/BUILD#L753)):_
> 
> > ```python
> >         "src/core/lib/iomgr/lockfree_event.cc",
> >         "src/core/lib/iomgr/logical_thread.cc",
> >         "src/core/lib/iomgr/novsock.cc",
> > ```
> 
> To match our existing naming convention, please call these two files `resolve_vsock_linux.cc` and `resolve_vsock_fallback.cc`, respectively.
> 

Done

> _[BUILD, line 1060 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-LzrxwB42IZXtbXh738w:-LzrxwB42IZXtbXh738x:bzgrzq2) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/BUILD#L1060)):_
> 
> > ```python
> >         "src/core/ext/filters/client_channel/local_subchannel_pool.cc",
> >         "src/core/ext/filters/client_channel/parse_address.cc",
> >         "src/core/ext/filters/client_channel/parse_address_novsock.cc",
> > ```
> 
> Now that we're needing more conditional compilation here, we should probably bite the bullet and move the parse_address library from the client_channel tree into the iomgr tree, since we're not really supposed to have any ifdefs outside of that tree.

I can give it a shot, but I don't know if I am familiar enough with gRPC to do a good job at it.

> _[src/core/lib/iomgr/resolve_address_posix.cc, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-LzruWIs53qL3natraAI:-LzruWIs53qL3natraAJ:b-k13d6q) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/src/core/lib/iomgr/resolve_address_posix.cc#L60)):_
> 
> > ```c++
> >   }
> > 
> >   if (name[0] == 'v' && name[1] == 's' && name[2] == 'o' && name[3] == 'c' &&
> > ```
> 
> Please remove this. The code we have above this for "unix:" URIs is a really ugly hack that I've been meaning to get rid of. And even though I haven't yet gotten around to doing that, I don't want to repeat the existing mistake here.
> 
> The iomgr name resolution code is used both on the client and on the server, but the ability for it to understand "unix:" or "vsock:" names is only needed on the server side, because the client side only uses this code when it already knows it's a DNS name -- if you specify a "unix:" or "vsock:" URI on the client side, it selects a different resolver that does not call the iomgr name resolution code in the first place.
> 
> So instead of adding this hack here, we should instead move this check into the server code, which is the only place where it's actually needed.
> 
> For bonus points, feel free to move the existing "unix:" code at the same time.

Same as above

> _[src/core/lib/iomgr/sockaddr_utils.cc, line 253 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-Lzrw9k87CQVGhT3q2it:-Lzrw9k9BCUgdKocsZwZ:blz90uz) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/src/core/lib/iomgr/sockaddr_utils.cc#L253)):_
> 
> > ```c++
> >     case GRPC_AF_UNIX:
> >       return "unix";
> > #ifdef GRPC_AF_VSOCK
> > ```
> 
> Why do we need an ifdef for vsock here but we don't need it for unix? It would be better to be consistent.

Because AF_UNIX as a symbol is pretty much defined anywhere (including on Windows, much to my surprise!) but AF_VSOCK is not. So we have to guard its usage. One thing I could do of course is

```
#ifdef HAVE_VSOCK
#define GRPC_AF_VSOCK AF_VSOCK
#else
#define GRPC_AF_VSOCK (-1)
#endif
```

just to have the symbol resolve and avoid the ifdef. Would that work better?

> _[src/core/lib/iomgr/sockaddr_utils.cc, line 275 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-LzrwPtbAWmcbmb6Bx5f:-LzrwPtbAWmcbmb6Bx5g:b5vxgo4) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/src/core/lib/iomgr/sockaddr_utils.cc#L275)):_
> 
> > ```c++
> >     case GRPC_AF_INET6:
> >       return grpc_ntohs(((grpc_sockaddr_in6*)addr)->sin6_port);
> > #ifdef GRPC_AF_VSOCK
> > ```
> 
> As above, this ifdef should not be needed.
> 

See above

> _[src/core/lib/iomgr/sockaddr_utils.cc, line 277 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-LzrwWEq368L4jf7W0WR:-LzrwWEr5JjdTC8Y0GVN:b-35gvte) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/src/core/lib/iomgr/sockaddr_utils.cc#L277)):_
> 
> > ```c++
> > #ifdef GRPC_AF_VSOCK
> >     case GRPC_AF_VSOCK:
> > #ifdef GRPC_HAVE_LINUX_VSOCK
> > ```
> 
> This ifdef probably is needed, but it would be better not to bury it inside of this file. Instead, I suggest defining a function called something like `grpc_vsock_addr_get_port()` with a real definition in vsock.cc and a no-op definition in novsock.cc, and then unconditionally call that function here.


You'd still need the #ifdef GRPC_AF_VSOCK (but see above, or happy to take suggestions). Otherwise, I can make that change yes.

> _[src/core/lib/iomgr/sockaddr_utils.cc, line 310 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-LzrwpkT5jQy0eulypLH:-LzrwpkT5jQy0eulypLI:b6pzzlt) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/src/core/lib/iomgr/sockaddr_utils.cc#L310)):_
> 
> > ```c++
> >           grpc_htons(static_cast<uint16_t>(port));
> >       return 1;
> > #ifdef GRPC_AF_VSOCK
> > ```
> 
> This ifdef should not be needed.
> 
> _[src/core/lib/iomgr/sockaddr_utils.cc, line 312 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-LzrwsRwDLAmXMZaJxvw:-LzrwsRwDLAmXMZaJxvx:b-x3br9a) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/src/core/lib/iomgr/sockaddr_utils.cc#L312)):_
> 
> > ```c++
> > #ifdef GRPC_AF_VSOCK
> >     case GRPC_AF_VSOCK:
> > #ifdef GRPC_HAVE_LINUX_VSOCK
> > ```
> 
> Same comment as on line 277 above.

See above. It seems like a lot of the feedback is about how to avoid the `#ifdef GRPC_AF_VSOCK` sprinkled around. I am happy to figure out a good path for that and go with it. What do you think?

**Comment by egranata** [comment]
Friendly ping

**Review by markdroth — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/21745)* status: all files reviewed, 7 unresolved discussions (waiting on @egranata and @markdroth)

___
*[BUILD, line 1060 at r1](https://reviewable.io/reviews/grpc/grpc/21745#-LzrxwB42IZXtbXh738w:-MGniA4R7Bnj7-778ENh:ba53w2f) ([raw file](https://github.com/grpc/grpc/blob/b4fd52930fc7122269f5fed2aeaf7b1b63359ba9/BUILD#L1060)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All I am suggesting is to move the files from src/core/ext/filters/client_channel to src/core/lib/iomgr.  You'll need to update a bunch of include paths and the include guard in the .h file, but otherwise nothing else should need to be changed.
</blockquote></details>

I recently took care of moving the parse_address library to iomgr in #23820, so if you merge in the changes from master, this part should be done for you.

**Comment by egranata** [comment]
Ah, @markdroth thanks for getting back to me; I will attempt to update the pull request soon & get back to you w/ an update

Apologies for the delay as well; this did fall off my radar w/ WFH & all

**Pull request closed without merging**
