### PR TITLE
Make handlers optional at server construction

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
This fixes [issue 7062](https://github.com/grpc/grpc/issues/7062) and is the master version of what was merged into `release-0_15` in [pull request 7148](https://github.com/grpc/grpc/pull/7148). (Two different commits because `_compression_test.py` was in conflict between the branches.)

### CODE REVIEW

**Comment by kpayson64** [comment]
lgtm

**Comment by jtattermusch** [comment]
Needs resolving.

**Comment by nathanielmanistaatgoogle** [comment]
Actually let's wait to merge this until after [pull request 6791](https://github.com/grpc/grpc/pull/6791).

**Comment by nathanielmanistaatgoogle** [comment]
retest this please

**Comment by nathanielmanistaatgoogle** [comment]
retest this please

**Comment by kpayson64** [comment]
test this please

**Comment by kpayson64** [comment]
test this please

**Pull request merged**
