### PR TITLE
Improve server-side ending for QPS tests

### PR DESCRIPTION
**Pull request by vjpai**
This is not as precarious as the client-side since there are not as many outstanding threads and the system is structured very differently, but just as a matter of course, we should end the threads before calling the destructor to avoid any races if the thread processing function tries to call some member function or access some member variable. This is the server-side analogy of #7652

### CODE REVIEW

**Comment by dgquintas** [comment]
LGTM

**Comment by dgquintas** [comment]
test this please

**Comment by vjpai** [comment]
test this please

**Comment by vjpai** [comment]
test this please

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by vjpai** [comment]
This PR is unnecessary. The class at hand is a final class (though not officially declared as such), so there is no problem with having a destructor that joins its  member threads.

**Pull request closed without merging**
