### PR TITLE
Upgrade third_party/protobuf to v3.14.0 (for v1.35.x)

### PR DESCRIPTION
**Pull request by jtattermusch**
Same as https://github.com/grpc/grpc/pull/24855, but for the already-cut v1.35.x branch (and including third_party/protobuf commit that hopefully fixes the build problem encountered in https://github.com/grpc/grpc/pull/24855)

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @stanley-cheung

**Comment by jtattermusch** [comment]
Lets wait for the tests to see if all problems encountered in https://github.com/grpc/grpc/pull/24855 have been fixed.

**Comment by jtattermusch** [comment]
Still seeing problems:

Python artifact build on Windows
https://source.cloud.google.com/results/invocations/82b67290-2e1a-4882-b3b0-bd026e6c8814/targets/github%2Fgrpc/tests;group=tasks;test=build_artifact.python_windows_x86_Python27_32bit;row=2
```
third_party\protobuf\src/google/protobuf/stubs/mutex.h:119:13: error: explicitly defaulted function 'constexpr google::protobuf::internal::WrappedMutex::WrappedMutex()' cannot be declared as constexpr because the implicit declaration is not constexpr:
   constexpr WrappedMutex() = default;
             ^~~~~~~~~~~~
```


Python basic bazel tests
https://source.cloud.google.com/results/invocations/fa5b00dd-ab16-47bd-ae0b-328bbaaef574/log
```
FAIL: //src/python/grpcio_tests/tests_aio/interop:local_interop_test (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests_aio/interop/local_interop_test/test.log)
INFO: From Testing //src/python/grpcio_tests/tests_aio/interop:local_interop_test:
==================== Test output for //src/python/grpcio_tests/tests_aio/interop:local_interop_test:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2698/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/interop/local_interop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/interop/local_interop_test.py", line 24, in <module>
    from tests_aio.interop import methods
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2698/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/interop/local_interop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/interop/methods.py", line 29, in <module>
    from google import auth as google_auth
ImportError: cannot import name 'auth'
================================================================================
[3,626 / 3,642] 71 / 138 tests, 1 failed; Testing //src/python/grpcio_tests/tests/unit/_cython:_channel_test.python2; 13s processwrapper-sandbox ... (16 actions running)
FAIL: //src/python/grpcio_tests/tests_aio/status:grpc_status_test (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests_aio/status/grpc_status_test/test.log)
INFO: From Testing //src/python/grpcio_tests/tests_aio/status:grpc_status_test:
==================== Test output for //src/python/grpcio_tests/tests_aio/status:grpc_status_test:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2873/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/status/grpc_status_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/status/grpc_status_test.py", line 22, in <module>
    from google.rpc import code_pb2, error_details_pb2, status_pb2
ModuleNotFoundError: No module named 'google.rpc'
================================================================================
[3,913 / 3,915] 136 / 138 tests, 2 failed; Testing //src/python/grpcio_tests/tests/unit/_cython:_channel_test.python3; 30s processwrapper-sandbox ... (2 actions running)
```

**Comment by jtattermusch** [comment]
@gnossen  @acozzette  looks like the backport https://github.com/protocolbuffers/protobuf/pull/8115 doesn't work 100%:

windows python artifact build:
```
third_party\protobuf\src/google/protobuf/stubs/mutex.h:119:13: error: explicitly defaulted function 'constexpr google::protobuf::internal::WrappedMutex::WrappedMutex()' cannot be declared as constexpr because the implicit declaration is not constexpr:
   constexpr WrappedMutex() = default;
             ^~~~~~~~~~~~
In file included from C:/tools/msys64_win7/mingw32/include/c++/6.3.0/mutex:44:0,
                 from third_party\protobuf\src/google/protobuf/stubs/mutex.h:33,
                 from third_party\protobuf\src/google/protobuf/descriptor.h:65,
                 from third_party\protobuf\src/google/protobuf/compiler/scc.h:38,
                 from third_party\protobuf\src/google/protobuf/compiler/js/js_generator.h:41,
                 from third_party\protobuf\src\google\protobuf\compiler\js\js_generator.cc:31:
C:/tools/msys64_win7/mingw32/include/c++/6.3.0/bits/std_mutex.h:94:5: note: defaulted constructor calls non-constexpr 'std::mutex::mutex()'
     mutex() noexcept = default;
     ^~~~~
```

**Comment by jtattermusch** [comment]
@gnossen @lidizheng   how can we fix the other issue?


Python basic bazel tests
https://source.cloud.google.com/results/invocations/fa5b00dd-ab16-47bd-ae0b-328bbaaef574/log
```
FAIL: //src/python/grpcio_tests/tests_aio/interop:local_interop_test (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests_aio/interop/local_interop_test/test.log)
INFO: From Testing //src/python/grpcio_tests/tests_aio/interop:local_interop_test:
==================== Test output for //src/python/grpcio_tests/tests_aio/interop:local_interop_test:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2698/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/interop/local_interop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/interop/local_interop_test.py", line 24, in <module>
    from tests_aio.interop import methods
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2698/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/interop/local_interop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/interop/methods.py", line 29, in <module>
    from google import auth as google_auth
ImportError: cannot import name 'auth'
================================================================================
[3,626 / 3,642] 71 / 138 tests, 1 failed; Testing //src/python/grpcio_tests/tests/unit/_cython:_channel_test.python2; 13s processwrapper-sandbox ... (16 actions running)
FAIL: //src/python/grpcio_tests/tests_aio/status:grpc_status_test (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests_aio/status/grpc_status_test/test.log)
INFO: From Testing //src/python/grpcio_tests/tests_aio/status:grpc_status_test:
==================== Test output for //src/python/grpcio_tests/tests_aio/status:grpc_status_test:
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2873/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/status/grpc_status_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/status/grpc_status_test.py", line 22, in <module>
    from google.rpc import code_pb2, error_details_pb2, status_pb2
ModuleNotFoundError: No module named 'google.rpc'
================================================================================
[3,913 / 3,915] 136 / 138 tests, 2 failed; Testing //src/python/grpcio_tests/tests/unit/_cython:_channel_test.python3; 30s processwrapper-sandbox ... (2 actions running)
```

**Comment by acozzette** [comment]
I think this pull [request](https://github.com/protocolbuffers/protobuf/pull/8098) might fix the WrappedMutex error.

**Comment by jtattermusch** [comment]
> @gnossen @lidizheng how can we fix the other issue?
> 
> Python basic bazel tests
> https://source.cloud.google.com/results/invocations/fa5b00dd-ab16-47bd-ae0b-328bbaaef574/log
> 
> ```
> FAIL: //src/python/grpcio_tests/tests_aio/interop:local_interop_test (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests_aio/interop/local_interop_test/test.log)
> INFO: From Testing //src/python/grpcio_tests/tests_aio/interop:local_interop_test:
> ==================== Test output for //src/python/grpcio_tests/tests_aio/interop:local_interop_test:
> Traceback (most recent call last):
>   File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2698/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/interop/local_interop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/interop/local_interop_test.py", line 24, in <module>
>     from tests_aio.interop import methods
>   File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2698/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/interop/local_interop_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/interop/methods.py", line 29, in <module>
>     from google import auth as google_auth
> ImportError: cannot import name 'auth'
> ================================================================================
> [3,626 / 3,642] 71 / 138 tests, 1 failed; Testing //src/python/grpcio_tests/tests/unit/_cython:_channel_test.python2; 13s processwrapper-sandbox ... (16 actions running)
> FAIL: //src/python/grpcio_tests/tests_aio/status:grpc_status_test (see /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/testlogs/src/python/grpcio_tests/tests_aio/status/grpc_status_test/test.log)
> INFO: From Testing //src/python/grpcio_tests/tests_aio/status:grpc_status_test:
> ==================== Test output for //src/python/grpcio_tests/tests_aio/status:grpc_status_test:
> Traceback (most recent call last):
>   File "/root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/sandbox/processwrapper-sandbox/2873/execroot/com_github_grpc_grpc/bazel-out/k8-fastbuild/bin/src/python/grpcio_tests/tests_aio/status/grpc_status_test.runfiles/com_github_grpc_grpc/src/python/grpcio_tests/tests_aio/status/grpc_status_test.py", line 22, in <module>
>     from google.rpc import code_pb2, error_details_pb2, status_pb2
> ModuleNotFoundError: No module named 'google.rpc'
> ================================================================================
> [3,913 / 3,915] 136 / 138 tests, 2 failed; Testing //src/python/grpcio_tests/tests/unit/_cython:_channel_test.python3; 30s processwrapper-sandbox ... (2 actions running)
> ```

@gnossen  @lidizheng  it looks like this is the last issue that's preventing us from upgrading third_party/protobuf.
I tried to fix it by upgrading rules_python to 0.1.0 but that seems to lead to other test failures (see https://github.com/grpc/grpc/pull/25143). Can you take a look and suggest how to fix this issue (a hotfix is fine)?
Since we're trying to backport this into 1.35.x branch, we don't want to any major changes, so I'd prefer to fix this in some simple way and then perform the rules_python upgrade properly on the master branch.

**Comment by lidizheng** [comment]
@jtattermusch Sorry, I missed the last notification. Richard and I discussed this problem, and it can be resolved by an existing workaround in our repo: https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/bazel_namespace_package_hack.py.

**Comment by gnossen** [comment]
And it looks like it was caused by [this PR](https://github.com/protocolbuffers/protobuf/pull/7902). I'm still investigating to determine the best way to resolve the issue.

**Comment by gnossen** [comment]
So it turns out that the Envoy project [dealt with this problem](https://github.com/envoyproxy/envoy/pull/14253#discussion_r536912177) before us. The Protobuf team has intentionally removed their namespace package declarations from the `__init__.py` file, instead declaring them in their `setup.py` file, which we do not consume at all. It seems that this solution is only necessary until all other packages using the `google` namespace package (`google-auth`) do the same. I've implemented that solution in our repo [here](https://github.com/grpc/grpc/pull/25171/commits/99d20dfab3d5e399fa0d05420be2aece63445bc7).

**Comment by jtattermusch** [comment]
I cherry-picked the patch from https://github.com/grpc/grpc/pull/25171/. After that, all tests should be green.

**Comment by jtattermusch** [comment]
The interop toprod tests are also failing on master: https://source.cloud.google.com/results/invocations/09ff4cb1-e4af-4841-a86e-3e48b2c99952/targets/github%2Fgrpc%2Finterop_test/tests

**Comment by jtattermusch** [comment]
@gnossen  @veblush @stanley-cheung I checked all the test results and they are looking good, and this PR is now ready to merge. Please review so I can merge.

After this is merged, I'll create a PR to upport this change to the master branch.

**Review by stanley-cheung — APPROVED** [review]
LGTM. I was also following this and came to the same conclusion. Tests are looking good. Thanks for taking care of this!

**Comment by jtattermusch** [comment]
> LGTM. I was also following this and came to the same conclusion. Tests are looking good. Thanks for taking care of this!

That was quick! Happy presidents day!

**Pull request merged**
