### PR TITLE
Enable epoll on Python manylinux1

### PR DESCRIPTION
**Pull request by mehrdada**
The Python packages built for Linux and uploaded to PyPI are required to
target a standardized platform dubbed `manylinux1`, which is essentially
an old legacy Linux distribution with an old `glibc` that does not have
`epoll_create1`, but provides the `epoll_create` system call.  While
there are race condition risks in using the latter and setting the
`O_CLOEXEC` flag immediately afterward on the file descriptor returned by
`epoll_create`, the return is well worth the risks for our Python users,
who end up falling back on `poll` polling engine when downloading our Linux
binary packages.

Fixes https://github.com/grpc/grpc/issues/13949.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +112  +0.0%

  [ = ]       0 TOTAL     +112  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +216  +0.0%

  [ = ]       0 TOTAL     +216  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +216  +0.0%

  [ = ]       0 TOTAL     +216  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
Test failure: https://github.com/grpc/grpc/issues/13445

**Pull request merged**
