### PR TITLE
Make the error domain and codes public and documented.

### LINKED ISSUE #2107: Make NSError+GRPC.h public and document the error codes
Also move [`kGRPCStatusMetadataKey`](https://github.com/grpc/grpc/blob/master/src/objective-c/GRPCClient/GRPCCall.h#L54) into that file.

### PR DESCRIPTION
**Pull request by jcanizales**
Fixes #2107.

### CODE REVIEW

**Comment by murgatroid99** [comment]
I'm not sure it's a good idea to duplicate the documentation in `grpc/status.h` here.

**Comment by jcanizales** [comment]
We need to, for it to be part of the generated documentation. I also modified it to make it specific to RPCs, and the client use case, which the one in `grpc/status.h` isn't.

**Comment by murgatroid99** [comment]
OK, that's a good enough reason for me. Also, there's a merge conflict.

**Comment by jcanizales** [comment]
Solved conflict.

**Pull request merged**
