### PR TITLE
Revert Python Bazel PRs

### PR DESCRIPTION
**Pull request by mehrdada**
Reverts #16831 and #16813 that break internal build.

+ Also reverts false fix #16859.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,922      Total (=)      1,965,922

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,000      Total (<)     10,909,005

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
@nathanielmanistaatgoogle We tried merging the rename PR, but it still failed import by @markdroth and we rolled back to have it figured out later. I'd rather keep the internal error outside the public tracker, but you can probably see the errors by running the import script pointed at the parent commit of this PR.

**Comment by nathanielmanistaatgoogle** [comment]
@ghostwriternr: I dug into this a little bit this evening and I think I've drafted the right change to our internal processes, but I'll perhaps need @nicolasnoble's help in getting it reviewed and integrated into the internal process. But... some sort of progress. 🙂

**Pull request merged**
