### PR TITLE
Add windows config_setting for cares

### PR DESCRIPTION
**Pull request by sgreenstein**
Don't define HAVE_CONFIG_H on Windows.

### CODE REVIEW

**Comment by sgreenstein** [comment]
Friendly ping, this is a simple change with no effect on non-Windows platforms

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @sgreenstein isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by sgreenstein** [comment]
Comment to re-verify CLA

**Comment by sgreenstein** [comment]
This fixes #13202

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by sgreenstein** [comment]
Obsoleted by #15624

**Pull request closed without merging**
