### PR TITLE
Replace grpc_shutdown_blocking with grpc_shutdown in Cython

### PR DESCRIPTION
**Pull request by lidizheng**
Maybe fixes b/169596172

### CODE REVIEW

**Review by veblush — APPROVED** [review]
If this goes well in Google, let's do the same thing for all wrapped langues.

**Comment by lidizheng** [comment]
@veblush Changing to `grpc_shutdown` seems caused a deadlock during interpreter exit.

https://source.cloud.google.com/results/invocations/9b351ba6-3545-454f-af7e-e50707d19423/targets/github%2Fgrpc%2Frun_tests%2Fpython_linux_opt_native%2Fpy37_native.test.unit._signal_handling_test.SignalHandlingTest/tests

**Comment by veblush** [comment]
@lidizheng Thanks and it's weird to have a deadlock here hmm. Can you manage to have a callstack related to a deadlock?

**Comment by lidizheng** [comment]
I will work on this task maybe later next week. Debugging subprocess in run_tests.py could be toil.

**Comment by veblush** [comment]
@lidizheng Sure! Thanks :)

**Comment by kmjung** [comment]
Hi folks, any updates here?

**Comment by lidizheng** [comment]
Haven't got time to dig deep into the failed test yet. Feel free to take over if this is urgent. I still have some work in PSM I hope to get them done first.

**Comment by lidizheng** [comment]
I'm unable to reproduce the error locally with Python 2.7 and 3.7 on Linux and macOS. It might be an unfortunate flake?

**Comment by kmjung** [comment]
@lidizheng are you referring to the errors in which showed up in your CI environment during the first iteration of this pull request, or to the underlying issue of a deadlock during process exit?

**Comment by lidizheng** [comment]
Sorry. I meant the CI error during the first iteration. It was the right test case to fail if there was a deadlock in interceptor clean-up. That test case spawns subprocesses, and try to shut them down with signals.

**Pull request merged**
