### PR TITLE
Ruby garbage collection fixes

### PR DESCRIPTION
**Pull request by murgatroid99**
This fixes the Ruby garbage collections problems described in #5742 by doing the following:

 - Remove any unused `mark` values in C wrapper objects, and ensure that the documentation for the ones that are used is consistent.

 - Remove the Ruby object `CompletionQueue`. Any object that needs to use a completion queue has a reference to one at the C level. Each server and call needs its own queue anyway, so this prevents some API usage errors, simplifies the Ruby code, and removes the need for certain Ruby objects to be destroyed in a particular order. This also makes it possible to have a simple server destruction function.

 - Remove all `init_copy` methods. It doesn't make sense to copy one of the C wrapping functions, the existing implementations did the wrong thing, and they (apparently) weren't used anyway.

### CODE REVIEW

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
I see lots of ruby failures?   (interop tests and basic tests)

**Comment by murgatroid99** [comment]
I am working on investigating the failures.

**Comment by murgatroid99** [comment]
Note: I believe that changing this API now is better than forcing backwards compatibility. This removes the CompletionQueue parameter from a couple of public-facing constructors. In at least one case, the parameter was a required argument in the middle of the list of required arguments. Keeping that backward compatible would mean requiring users to pass a dummy object for that argument every time they call that constructor. It is better to remove it now than to have that requirement after GA.

CC @jayantkolhe

**Comment by murgatroid99** [comment]
@nathanielmanistaatgoogle @soltanmm Some change I made in this PR is causing the Ruby client/Python server combination to fail the `timeout_on_sleeping_server` interop test. Specifically, I'm getting this status response:

```
2:Exception iterating responses: list index out of range
```

It looks like that comes from `src/python/grpcio/grpc/_server.py`, in the `_take_response_from_response_iterator` function, but I'm not sure how to follow that back to the source.

Do you have any idea what might be causing this problem in that test scenario? All the ruby server does is make a bidi call with a one-second timeout, send a message, wait two seconds, then half-close from the client side.

**Comment by nathanielmanistaatgoogle** [comment]
@murgatroid99: is there any chance you're not including more than zero response parameters in your request, causing [this line](https://github.com/grpc/grpc/blob/09bf5f458a6be15e4d7737aa232ad33ecdf6891a/src/python/grpcio/tests/interop/methods.py#L85) to make an out-of-range list access? If so, is the Python code on the server out of spec for assuming at least one response parameter will be included or is the Ruby code out of spec for not including at least one response parameter?

**Comment by murgatroid99** [comment]
We do in fact send zero response parameters, as specified in the [test case specification](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#timeout_on_sleeping_server). 

The [specification for that server feature](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#fullduplexcall) says

> Server implements FullDuplexCall by replying, in order, with one StreamingOutputCallResponses **for each ResponseParameters** in each StreamingOutputCallRequest. So I'd say that it's the Python server that's out of spec.

**Comment by nathanielmanistaatgoogle** [comment]
I agree and will get working on a fix to the Python code.

**Comment by jtattermusch** [comment]
Reassigning to @stanley-cheung  as I'll OOO soon.

**Comment by murgatroid99** [comment]
@ctiller I discussed this change with Jayant, and we would like a third opinion on making this breaking change now.

This change removes the CompletionQueue type from the public API and removes any parameters with that type from all functions. Specifically, the client stub initializer takes a CompletionQueue as a required parameter, so changing that is breaking.

**Comment by ctiller** [comment]
Getting CQ's out of the public API seems worth it.

**Comment by murgatroid99** [comment]
@stanley-cheung Can you take a look at this?

**Comment by stanley-cheung** [comment]
LGTM, I think it makes sense to remove completion_queue from the public API

**Pull request merged**
