### PR TITLE
Free result of grpc_dump_slice

### LINKED ISSUE #16619: memory leak in grpclb.cc: gpr_dump output not freed.
the output of gpr_dump need to be freed with  `gpr_free()`

https://github.com/grpc/grpc/blob/20345b21bb00c626ef346c26dbb3903c96c21c52/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc#L858

### PR DESCRIPTION
**Pull request by dgquintas**
Fixes #16619

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +160  +0.0%

  [ = ]       0 TOTAL     +160  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
Issues: https://github.com/grpc/grpc/issues/16692

**Pull request merged**
