### PR TITLE
[ssl] Add support for client side certificate reloading

### PR DESCRIPTION
**Pull request by euroelessar**
grpc-core part of #15735

### CODE REVIEW

**Comment by euroelessar** [comment]
@jiangtaoli2016 @mehrdada Please have a look, I'm not that certain about the provided API and comments are definitely welcome.

**Comment by jiangtaoli2016** [comment]
@euroelessar You may be interested in this gRFC https://github.com/grpc/proposal/pull/98. @yihuazhang from my team is working new grpc TLS credential API that supports both SPIFFE and HTTPS semantics, supports credential reloading for both client/server, support server authorization, and so on. 

We are hoping to migrate to this new API rather than adding burden to old SSL credential API which is hard to maintain.

**Comment by euroelessar** [comment]
@jiangtaoli2016 The proposal looks promising, but what is an expected timeline for it to be approved and implemented?

**Comment by jiangtaoli2016** [comment]
@euroelessar We expect to finish the implementation (grpc core code) by end of Oct.

**Comment by euroelessar** [comment]
The proposed timeline looks reasonable, thanks. I'll postpone/abandon the PR in the meantime.

**Comment by jiangtaoli2016** [comment]
Thank you @euroelessar for your patience.

**Comment by BACtaki** [comment]
@jiangtaoli2016 Is there an update on the new API changes?

**Comment by yihuazhang** [comment]
@BACtaki https://github.com/grpc/grpc/pull/16614 is currently under review, that achieves the purpose.

**Pull request closed without merging**
