### PR TITLE
Keepalive watchdog firing should return status UNAVAILABLE

### PR DESCRIPTION
**Pull request by yashykt**
It used to return INTERNAL earlier which seems to be a mistake.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,792      Total (=)      1,964,792

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,887,063      Total (<)     10,887,068

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,892      Total (=)      1,964,892

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,887,717      Total (<)     10,887,720

 No significant differences in binary sizes


```

**Comment by ncteisen** [comment]
What's the status here, can this be merged?

**Comment by yashykt** [comment]
ah, I almost forgot about this. Looks like obj c keepalive interop also needed to be updated.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,108      Total (=)      1,965,108

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,887,893      Total (<)     10,887,894

 No significant differences in binary sizes


```

**Comment by yashykt** [comment]
MacOS tests are failing because of insufficient available space.

**Comment by yashykt** [comment]
Thanks for reviewing!

**Pull request merged**
