### PR TITLE
Fix compile error "argument to ‘sizeof’ in ‘strncpy’ call is the same" by updating cares to 1.15.0

### PR DESCRIPTION
**Pull request by fho**
This fixes the issue: https://github.com/grpc/grpc/issues/16688

Which causes that grpc can not be build because of the following
compiler error:
```
  third_party/cares/cares/ares_init.c: In function ‘ares_dup’:
  third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer- memaccess] sizeof(src->local_dev_name));
```

### CODE REVIEW

**Comment by fho** [comment]
@nicolasnoble could you add the `kokoro:run` label to trigger the CI checks again?
I might have fixed the CI issues with https://github.com/grpc/grpc/pull/18016/commits/5c9573667321c26648b307e0e7043041d7222cde.
Thanks!

**Comment by fho** [comment]
next try :-)
I'm probably not supposed to add the new header and c-file to `tools/run_tests/generated/sources_and_headers.json` manually in a commit?
What is the correct way to add it?

Is it possible that I can trigger the CI test myself to check if I fixed the issue?

**Comment by fho** [comment]
Can we run the CI checks again?

**Comment by fho** [comment]
Bazel is now failing with:
```
[0 / 17] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: missing input file '@com_github_cares_cares//:ares_strsplit.h'
ERROR: /tmpfs/tmp/bazel/external/com_github_cares_cares/BUILD.bazel:65:1: @com_github_cares_cares//:ares: missing input file '@com_github_cares_cares//:ares_strsplit.h'
ERROR: missing input file '@com_github_cares_cares//:ares_strsplit.c'
```
Somebody has an idea what is wrong?

**Comment by fho** [comment]
@nicolasnoble @mhaidrygoog might it be that the problem is not in the PR and the GRPC-Repository but in the external CI scripts + bazel files?

**Comment by nicolasnoble** [comment]
Updating submodules isn't that easy. Bazel doesn't in fact care about submodules. There are more files to update and keep in sync when updating submodules.

Check for the old sha1 in the repository, you'll find the other occurrences to update.

**Comment by nicolasnoble** [comment]
See https://github.com/grpc/grpc/search?q=3be1924221e1326df520f8498d704a5c4c8d0cce&unscoped_q=3be1924221e1326df520f8498d704a5c4c8d0cce

**Comment by fho** [comment]
Thanks a lot for the hint.
I updated the remaining sha and tag references for cares.

**Comment by nicolasnoble** [comment]
@apolcyn: please review and merge if acceptable.

**Comment by apolcyn** [comment]
Ack. There are a couple of non-CI tests I want to check. Will review by monday

**Comment by apolcyn** [comment]
nit: just for consistency in keeping up to date with upstream during this upgrade, can we add the following patch:

```
 /* Define to 1 if you have the ws2tcpip.h header file. */
 /* #undef HAVE_WS2TCPIP_H */
 
+/* Define to 1 if you have the __system_property_get function */
+/* #undef HAVE___SYSTEM_PROPERTY_GET */
+
 /* Define to 1 if you need the malloc.h header file even with stdlib.h */
 /* #undef NEED_MALLOC_H */
 
```

to:
`third_party/cares/config_linux/ares_config.h`
`third_party/cares/config_darwin/ares_config.h`
`third_party/cares/config_android/ares_config.h`
`third_party/cares/config_freebsd/ares_config.h`
`third_party/cares/config_openbsd/ares_config.h`
`third_party/cares/config_android/ares_windows.h`


(I ran cmake from c-ares git root on mac, windows, and linux to regenerate that file, and found that that small patch will be the only change).

**Comment by fho** [comment]
@apolcyn I changed the cares config header files accordingly

**Comment by apolcyn** [comment]
Sorry, a C# test which is relevant to c-ares on Windows failed in the last re-run. I'll need to investigate (there's a chance it's a pre-existing flake).

https://source.cloud.google.com/results/invocations/1c1b0710-291e-479f-a06c-0b35e504e9d4/targets/github%2Fgrpc%2Fcsharp_windows_opt_native/tests

```
NUnitLite 3.10.1 (.NET Framework 4.5)
Copyright (c) 2018 Charlie Poole, Rob Prouse
Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601.65536
  CLR Version: 4.0.30319.42000
Test Files
    T:/src/github/grpc/workspace_csharp_windows_opt_native/src/csharp/Grpc.IntegrationTesting/bin/Release/net45/Grpc.IntegrationTesting.exe
Test Filters
    Test: Grpc.IntegrationTesting.ExternalDnsClientServerTest
=> Grpc.IntegrationTesting.ExternalDnsClientServerTest
D0312 12:10:21.142578 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "T:\src\github\grpc\workspace_csharp_windows_opt_native\src\csharp\Grpc.IntegrationTesting\bin\Release\net45\grpc_csharp_ext.x64.dll"
D0312 12:10:21.236328 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
=> Grpc.IntegrationTesting.ExternalDnsClientServerTest.EmptyUnary
running empty_unary
Errors, Failures and Warnings
1) Error : Grpc.IntegrationTesting.ExternalDnsClientServerTest.EmptyUnary
Grpc.Core.RpcException : Status(StatusCode=Unavailable, Detail="Resolver transient failure")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Testing.TestService.TestServiceClient.EmptyCall(Empty request, CallOptions options)
   at Grpc.Testing.TestService.TestServiceClient.EmptyCall(Empty request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Grpc.IntegrationTesting.InteropClient.RunEmptyUnary(TestServiceClient client)
Run Settings
    Number of Test Workers: 1
    Work Directory: T:\src\github\grpc\workspace_csharp_windows_opt_native
    Internal Trace: Off
Test Run Summary
  Overall result: Failed
  Test Count: 1, Passed: 0, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2019-03-12 19:10:21Z
    End time: 2019-03-12 19:10:31Z
    Duration: 10.435 seconds
```

**Comment by apolcyn** [comment]
I haven't been able to be too conclusive with the flake seen here, since it's not easy to reproduce. 1000's of manual test runs on Windows can be made without triggering a flake. At the same time, I have seen this test flake a couple of times on master branch. So, I think that the flake seen here might not be related to this change.

@fho can you please update this PR to fix the merge conflict in the Makefile? Probably need to regenerate projects

**Comment by apolcyn** [comment]
@fho I believe that the test failures seen here were pre-existing flakes.

Please fix merge conflicts and update this PR so we can merge, thanks.

**Comment by fho** [comment]
@apolcyn I rebased the branch on master and fixed the conflict.

**Comment by fho** [comment]
was merged as part of PR https://github.com/grpc/grpc/pull/18519

**Pull request closed without merging**
