### PR TITLE
Fix DNS resolvers to reset the backoff in a better place.

### PR DESCRIPTION
**Pull request by markdroth**
No functional changes here; just a small code cleanup.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                    FILE SIZE
 ++++++++++++++ GROWING                                                                      ++++++++++++++

 -------------- SHRINKING                                                                    --------------
  -0.0%     -32 [None]                                                                          -832  -0.0%
  -0.9%     -32 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc     -32  -0.9%
     -48.8%     -20 dns_ares_channel_saw_error_locked                                                -20 -48.8%
      -9.2%     -15 dns_ares_next_locked                                                             -15  -9.2%
  -1.5%     -32 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc          -32  -1.5%
     -17.9%     -20 dns_next_locked                                                                  -20 -17.9%
     -48.8%     -20 dns_channel_saw_error_locked                                                     -20 -48.8%

  -0.0%     -96 TOTAL                                                                           -896  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known issues: grpc/grpc-node#168

**Pull request merged**
