### PR TITLE
Revert "Provide protocol for initializer of generated messages"

### PR DESCRIPTION
**Pull request by muxi**
Reverts grpc/grpc#15193. Broke some internal tests

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Basic Tests MacOS - #14673 
Interop Cloud-to-Cloud Tests - #15199 
Interop Cloud-to-Prod Tests - #15199

**Pull request merged**
