### PR TITLE
unimplemented error on parse failure confused me

### PR DESCRIPTION
**Pull request by cove**
This response confused me due to https://github.com/dotnet/aspnetcore/issues/39317 where the body of a response went missing, but I got back an unimplemented error.

### CODE REVIEW

**Comment by yashykt** [comment]
Note that is C++ and the linked issue is .NET

**Comment by markdroth** [comment]
I don't have all of the context on the C# problem here, but I don't think it makes sense to add a comment in a C++ header file about a C# issue.

**Comment by cove** [comment]
Sorry let me explain the C# connection here for context better: 

- I have a server that's written in C# and is using MSFT's gRPC impl
- My client is using this gRPC impl in C++
- I ran into this issue cited in to the TODO on the C++ side _and_ a bug on the C# server side at the same time, which resulted in an unimplemented error from the C++ gRPC client when it was implemented on the server side. So took some time to track down what was going on, a better error message from the gRPC client would have helped.

**Comment by markdroth** [comment]
Okay, thanks, that's useful info.  We should definitely have a bug to track improving the error message in this case, but I don't think we need a comment pointing to the C# issue.

@yashykt, do we have an existing bug tracking this?  If not, let's create one.

**Pull request closed without merging**
