### PR TITLE
Remove include from end2end data files and add extern C to each defin…

### PR DESCRIPTION
**Pull request by yashykt**
Remove include from end2end data files and add extern C to each definition instead

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Out of curiosity, what's the motivation behind this change?

**Comment by yashykt** [comment]
This is needed to land the import for test/core c++ization :)

**Comment by yashykt** [comment]
Known Issues #13302, #12510, #13148, #13124, #13178

**Pull request merged**
