### PR TITLE
gRPC CLI batch mode

### PR DESCRIPTION
**Pull request by y-zeng**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_2_0.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by y-zeng** [comment]
Basic Tests C++ Linux [dbg] (internal CI): #12510
Basic Tests C++ Linux [opt] (internal CI): #12428
Interop Cloud-to-Prod Tests (internal CI): #12261

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
