### PR TITLE
Fix Windows subprocess flake

### PR DESCRIPTION
**Pull request by gnossen**
```
python workspace_csharp_windows_dbg_native/tools/run_tests/run_tests.py -t -j 8 -x ../run_tests/csharp_windows_dbg_native/sponge_log.xml --report_suite_name csharp_windows_dbg_native -l csharp -c dbg --iomgr_platform native --bq_result_table aggregate_results --measure_cpu_costs --report_multi_target
...
2021-11-09 08:50:42,517 WARNING: Failed to start cmake/build/Debug/bin_encoder_test.exe GRPC_POLL_STRATEGY=none, retrying in 2.400000 seconds

Traceback (most recent call last):

  File "workspace_c_windows_dbg_native/tools/run_tests/run_tests.py", line 1897, in <module>

  File "workspace_c_windows_dbg_native/tools/run_tests/run_tests.py", line 1823, in _build_and_run

  File "T:\src\github\grpc\workspace_c_windows_dbg_native\tools\run_tests\python_utils\jobset.py", line 594, in run

    if not js.start(cmdline):

  File "T:\src\github\grpc\workspace_c_windows_dbg_native\tools\run_tests\python_utils\jobset.py", line 479, in start

    self._quiet_success)

  File "T:\src\github\grpc\workspace_c_windows_dbg_native\tools\run_tests\python_utils\jobset.py", line 268, in __init__

    self.start()

  File "T:\src\github\grpc\workspace_c_windows_dbg_native\tools\run_tests\python_utils\jobset.py", line 317, in start

    self._process = try_start()

  File "T:\src\github\grpc\workspace_c_windows_dbg_native\tools\run_tests\python_utils\jobset.py", line 304, in <lambda>

    env=env)

  File "C:\Python37\lib\subprocess.py", line 645, in __init__

    _cleanup()

  File "C:\Python37\lib\subprocess.py", line 215, in _cleanup

    res = inst._internal_poll(_deadstate=sys.maxsize)

  File "C:\Python37\lib\subprocess.py", line 1193, in _internal_poll

    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:

OSError: [WinError 6] The handle is invalid
```

[Manual run](https://sponge2.corp.google.com/1dace392-a063-4623-a3ae-6bb1669d076e) (ongoing)

### CODE REVIEW

**Review by jtattermusch — APPROVED** [review]
LGTM once the fix is confirmed.

**Comment by gnossen** [comment]
So this initial approach did not work. I now believe that https://github.com/grpc/grpc/pull/27971 is the cause of the issue (I was not previously aware that the failures started at this commit) and the Python stdlib for Windows just does a terrible job of explaining things when a subprocess dies immediately on startup. I'm now investigating what the actual failure might be.

**Comment by jtattermusch** [comment]
Superseded by #28005?

**Comment by gnossen** [comment]
Yes.

**Pull request closed without merging**
