### PR TITLE
Updating roots from Mozilla.

### PR DESCRIPTION
**Pull request by jboeuf**

### CODE REVIEW

**Comment by jboeuf** [comment]
There are a bunch of tests failing with nothing to do with this PR. Should I merge anyway? Thanks!

**Comment by dgquintas** [comment]
Known issues: #10555 #10554 #10552 #10553 #10548

**Comment by dgquintas** [comment]
@jboeuf not a good day for testing... you can merge.

**Comment by jboeuf** [comment]
Thanks!

**Pull request merged**
