### PR TITLE
Bump version to 1.16.1

### PR DESCRIPTION
**Pull request by srini100**
Bump version to 1.16.1

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++

 -------------- SHRINKING                    --------------
  -0.0%     -21 [None]                          -109  -0.0%
 -11.5%     -11 src/cpp/common/version_cc.cc     -11 -11.5%
     -22.0%     -11 grpc::Version[abi:cxx11]         -11 -22.0%

  -0.0%     -32 TOTAL                           -120  -0.0%



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,967,222      Total (<)      1,967,227

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,889,382      Total (<)     10,889,385

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by srini100** [comment]
Objective C tests failed due to a config file on master not present on this branch. Other tests are failing due to npm error. This PR is just version bump. Tests passed fine on previous PR https://github.com/grpc/grpc/pull/17130

**Pull request merged**
