### PR TITLE
[ruby]: add pre-compiled binaries for ruby 3.2; drop them for ruby 2.6

### PR DESCRIPTION
**Pull request by apolcyn**
Ruby 3.2 came out at the end of 2022, and rake-compiler-dock just added support in 1.3.0. Ruby 2.6 is now EOL, so stop building pre-compiled targets for it.

Note:

- Test coverage is primarily being added in https://github.com/grpc/grpc/pull/31991. Besides that, we'll need to follow this up with new distrib tests as well.
- I did some cleanup to the `Rakefile` by removing the `if RUBY_PLATFORM =~ /darwin/` - we no longer build packages on macos hosts so there's no need for it.
- A hack is made to `extconf.rb` to work around https://github.com/rake-compiler/rake-compiler/issues/210

### CODE REVIEW

**Comment by apolcyn** [comment]
Currently macos unit tests are failing (where the ruby extension is built natively on the macos host i.e. not cross-compiled):

```
<internal:/Users/kbuilder/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc/grpc_c.bundle, 0x0009): tried: '/Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc/grpc_c.bundle' (not a mach-o file) - /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc/grpc_c.bundle (LoadError)
	from <internal:/Users/kbuilder/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc/grpc.rb:22:in `<top (required)>'
	from /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc.rb:19:in `require_relative'
	from /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc.rb:19:in `<top (required)>'
	from <internal:/Users/kbuilder/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/kbuilder/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Volumes/BuildData/tmpfs/altsrc/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/end2end/end2end_common.rb:24:in `<top (required)>'
	from src/ruby/end2end/client_memory_usage_test.rb:17:in `require_relative'
	from src/ruby/end2end/client_memory_usage_test.rb:17:in `<main>'
```

**Comment by apolcyn** [comment]
Distrib tests also failing, in a different way:

```
+ bundle exec ./distribtest.rb
Success!
+ [[ binary == \s\o\u\r\c\e ]]
++ gem env
++ grep '\- INSTALLATION DIRECTORY'
++ awk '{ print $4 }'
+ INSTALLATION_DIR=/usr/local/rvm/gems/ruby-2.7.0
++ find /usr/local/rvm/gems/ruby-2.7.0 -name grpc_c.so
++ wc -l
+ [[ 5 == 0 ]]
++ find /usr/local/rvm/gems/ruby-2.7.0 -name grpc_c.so -exec ldd '{}' ';'
++ grep -c libruby
A grpc_c.so file in this binary gRPC package is dynamically linked to libruby.
+ LIBRUBY_DEPENDENCY_EXISTS=1
+ [[ 1 != 0 ]]
+ echo 'A grpc_c.so file in this binary gRPC package is dynamically linked to libruby.'
++ find /usr/local/rvm/gems/ruby-2.7.0 -name grpc_c.so -exec ldd '{}' ';'
++ grep -c 'not found'
+ DEPENDENCY_NOT_FOUND=1
+ [[ 1 != 0 ]]
+ echo 'A grpc_c.so file in this binary gRPC package has an non-portable dependency.'
+ '[' 1 '!=' 0 ']'
+ exit 1
A grpc_c.so file in this binary gRPC package has an non-portable dependency.
+ DOCKER_EXIT_CODE=1
+ '[' /tmpfs/src/github/grpc '!=' '' ']'
+ mkdir -p /tmpfs/src/github/grpc
+ cp -r /tmp/tmp.NOZGpssgMg/reports /tmpfs/src/github/grpc
+ '[' '' '!=' '' ']'
+ exit 1

2023-01-17 18:01:57,590 FAILED: distribtest.ruby_linux_x64_stretch_version_ruby_2_7_package_type_binary [ret=1, pid=242254, time=30.8sec]
```

**Comment by apolcyn** [comment]
Experimentally, potential workaround macos dbg unit test failure is to also strip with the dbg build: https://github.com/grpc/grpc/blob/47871b1e4846c87c0f3a3c9664ba4009b4e36ffc/src/ruby/ext/grpc/extconf.rb#L177

**Comment by johnnyshields** [comment]
It would be great if we can get this merged and out on a pre-release as per https://github.com/grpc/grpc/issues/32046

**Comment by apolcyn** [comment]
> It would be great if we can get this merged and out on a pre-release as per https://github.com/grpc/grpc/issues/32046

I'd love to get this out in a pre-release soon. I need to fix the macos test issue, though (not a mach-o file)

**Comment by apolcyn** [comment]
Potentially relevant: https://github.com/ruby/ruby/pull/7086

**Review by stanley-cheung — APPROVED** [review]

**Comment by apolcyn** [comment]
@johnnyshields FYI this is available in 1.52.pre2 now

**Pull request merged**
