### PR TITLE
Add copyrights to .bat files (and update the checker to report missing ones)

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/5479.

### CODE REVIEW

**Comment by kpayson64** [comment]
It looks like there are some more bat files (Ignoring /third_party)
```/workspace/grpc$ find . -type f -name "*.bat"
./tools/run_tests/build_artifact_protoc.bat
./tools/run_tests/pre_build_node.bat
./tools/run_tests/run_node.bat
./tools/run_tests/build_artifact_csharp.bat
./tools/run_tests/pre_build_csharp.bat
./tools/run_tests/build_artifact_python.bat
./tools/run_tests/post_tests_csharp.bat
./tools/run_tests/pre_build_c.bat
./tools/run_tests/build_artifact_node.bat
./tools/run_tests/build_node.bat
./vsprojects/build_vs2010.bat
./vsprojects/build_vs2013.bat
./vsprojects/build_vs2015.bat
./vsprojects/coapp/zlib/buildall.bat
./vsprojects/coapp/openssl/buildall.bat
./vsprojects/build_plugins.bat
./examples/csharp/route_guide/generate_protos.bat
./examples/csharp/helloworld/generate_protos.bat
./test/distrib/csharp/run_distrib_test.bat
./test/distrib/csharp/build_vs2015.bat
./src/csharp/build_packages.bat
./src/csharp/buildall.bat
```

**Comment by jtattermusch** [comment]
Some of the .bat files already had the copyright headers.

To me it seems  tools/distrib/check_copyright.py  is now passing (and before it reported the list of files that needed to be fixed after I added the functionality to check .bat files)

**Comment by kpayson64** [comment]
LGTM.

**Comment by jtattermusch** [comment]
Sanity is failing because I forgot to update the templates for .bat files.

**Pull request merged**
