### PR TITLE
Build C# nugets on linux instead of windows for simplicity

### PR DESCRIPTION
**Pull request by jtattermusch**
Currently C# nugets (and unitypackage) are built in the "build_packages" jobs, but unlike all the other languages, they are built on windows. Building on linux is simpler both in terms of scripting (.bat files are terrible) and also in terms of unification with other languages.

Historically, building nugets on Windows was necessary because of the legacy nuget + msbuild stack, but these days, building nuget on linux with "dotnet pack" seems completely alright.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Adhoc distribtests: https://g3c.corp.google.com/results/invocations/9a871ec2-46a1-4074-aa58-ad73a80d16ac/targets

**Comment by jtattermusch** [comment]
Windows package build now complains "Nothing to build." (which is to be expected), but all the distribtests are passing:
sponge/a2b2b942-2b13-45a3-a501-c49a47cbd8f5

**Comment by jtattermusch** [comment]
Another adhoc run to check the result of build_packages job: https://g3c.corp.google.com/results/invocations/f6f682c8-f330-439c-ad20-89eb63aea0d8

**Comment by jtattermusch** [comment]
@apolcyn  this is now ready for review.

**Review by apolcyn — APPROVED** [review]

**Comment by jtattermusch** [comment]
Some followup items:
- update the release doc
- make sure that uploading of nightly packages still works fine

**Pull request merged**
