### PR TITLE
Add logging.basicConfig() for example servers

### PR DESCRIPTION
**Pull request by lidizheng**
A fix for #17321

### CODE REVIEW

**Comment by srini100** [comment]
@lidizheng, do we want to complicate greeter example? We intentionally keep it simple as this is the bare minimum to get started with gRPC. We can probably add a separate version of this example that show how to handle errors and exceptions.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,224      Total (=)      2,020,224

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,227      Total (<)     11,154,234

 No significant differences in binary sizes


```

**Comment by gnossen** [comment]
@srini100 I think the point here is to make debugging of user issues easier. Very often, people will modify these examples to produce a minimal example of a use case. Without this configuration added, any log statements produced by grpc -- including errors -- will simply surface as "no handlers found".

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,410      Total (=)      2,020,410

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,174,077      Total (<)     11,174,080

 No significant differences in binary sizes


```

**Comment by lidizheng** [comment]
Added `logging.basicConfig()` to all the example files.

**Comment by lidizheng** [comment]
@srini100 The Python logger logs following stuff for entire gRPC Python:
* Channel exception while consuming request iterator
* Server certificate fetcher raised an exception
* Server certificate fetcher fetched something that is not a certificate
* Cython prefork failed to shutdown gRPC Python threads
* Cython postfork failed to shutdown gRPC Core
* Cython string decode failure
* AuthMetadataPluginCallback raised an exception (Won't log for other plugins)
* Server abort with StatusCode.OK
* Server method handler raised an exception
* Server response iterator raised an exception
* Server interceptor raised an exception

There are critical debug information being logged by developers, adding the `basicConfig()` here will express our recommendation of utilizing Python logging mechanism. And as @gnossen said, it may help developers who copy/paste from the examples.

PS: Finding solution for `No handlers could be found for logger` is not hard. Google "Python no handlers" and bunch of posts will suggest calling `logging.basicConfig()`. But developers who might not familiar with Python logging mechanism (I was one of them) will panic first time saw it.

**Comment by lidizheng** [comment]
@ericgribkoff PTaL

**Pull request merged**
