### PR TITLE
Upmerge 1.16.x to master

### PR DESCRIPTION
**Pull request by muxi**
For v1.17 release.

### CODE REVIEW

**Comment by srini100** [comment]
@gnossen, please check if this upmerge is fine. I though this should be a no-op for your logging related changes as master should have everything already.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,622      Total (<)     11,175,626

 No significant differences in binary sizes


```

**Comment by muxi** [comment]
Closing this PR since it turns out we do not need to upmerge anything.

**Comment by srini100** [comment]
I think you should still do this merge even though it is no-op. Otherwise, the next merge will cause the same issue.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,623      Total (<)     11,175,630

 No significant differences in binary sizes


```

**Pull request merged**
