### PR TITLE
Enable auth interop tests on grpc-dotnet client

### PR DESCRIPTION
**Pull request by JamesNK**
Testing to see what works and what is broken.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Some insights on the failures as listed here https://source.cloud.google.com/results/invocations/31c4a403-7d6a-49d8-9ae0-abbcddb2cc33/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_prod_auth:aspnetcore:default:compute_engine_creds:tls;row=1

You might be able to get the interop tests passing for managed client by using the newly implemented CallCredentials functionality and converting GoogleCredentials from the dotnet auth library to an instance of CallCredentials:
https://github.com/grpc/grpc/blob/df998f70239ec80af7d9af7133f9c0757e952f39/src/csharp/Grpc.Auth/GoogleGrpcCredentials.cs#L66

`Google.Apis.Auth` nuget package provides "GoogleCredentials" that implement ITokenAccess, which can be used by as AuthInterceptor to generate the right metadata entries to add to your calls.

Potential issues:
- Grpc.Auth depends on Grpc.Core (which made sense until we came up with the managed impl).
- you can't use the most straigtforward method https://github.com/grpc/grpc/blob/df998f70239ec80af7d9af7133f9c0757e952f39/src/csharp/Grpc.Auth/GoogleGrpcCredentials.cs#L41 as managed client doesn't have a concept of ChannelCredentials.

**Comment by jtattermusch** [comment]
Btw, the name of the PR is not accurate as the  `_AUTH_TEST_CASES` will never run against an AspNetCore server (they use gRPC client to talk to a Google Cloud API backend and basically verify if authentication against google services works as expected - they talk to one of our testing APIs)

**Comment by jtattermusch** [comment]
@jskeet  once the auth interop tests enabled in this PR work, that also means the GCP client libraries should be able to authenticate with google backends when using the managed grpc-dotnet client (the glue code to use Google.Apis.Auth is the same).

**Comment by JamesNK** [comment]
@jtattermusch For the tests to pass the interop client needs to be updated to pass the auth libraries call credential's via CallOptions. Currently the auth tests use ChannelCredentials which won't do anything with the grpc-dotnet client.

**Comment by jtattermusch** [comment]
> @jtattermusch For the tests to pass the interop client needs to be updated to pass the auth libraries call credential's via CallOptions. Currently the auth tests use ChannelCredentials which won't do anything with the grpc-dotnet client.

Good point, but not all of them do. `oauth2_auth_token` and `per_rpc_creds` use call credentials so we could implement them pretty easily.

**Comment by JamesNK** [comment]
Ok. In that case I’m not sure why they’re not already passing since grpc-dotnet now supports call credentials.

**Comment by jtattermusch** [comment]
> Ok. In that case I’m not sure why they’re not already passing since grpc-dotnet now supports call credentials.

I took a look and found the problem(s): https://github.com/grpc/grpc/pull/19648

**Comment by jtattermusch** [comment]
The per-rpc auth interop tests are now passing, the next step is enabling 
`compute_engine_creds` and `jwt_token_creds`. 
https://github.com/grpc/grpc/blob/d56e4eb0fdd182276eaed0e4eec02ef28c021fb9/tools/run_tests/run_interop_tests.py#L211

It is true that the test cases in InteropClient.cs use ChannelCredentials (which we don't support), but that's not required by the interop test spec, it's more an implementation detail. Also the ChannelCredentials being used are a composite of default SslCredentials and CallCredentials, so we could make these tests pass by applying CallCredentials to individual calls.
https://github.com/grpc/grpc/blob/d56e4eb0fdd182276eaed0e4eec02ef28c021fb9/src/csharp/Grpc.IntegrationTesting/InteropClient.cs#L123

That said, it would be useful to be able to specify CallCredentials to use for all calls from a given channel (= basically a replacement for the composite channelCredentials that take CallCredentials as the second argument), but that something that should be doable relatively easily.

**Pull request closed without merging**
