### PR TITLE
Enable use of short-stream optimizations in qps tests

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by vjpai** [comment]
Unrelated failures in 1-core QPS tests being addressed in #11009

**Comment by vjpai** [comment]
Revisiting this PR after some time in suspension.

**Comment by vjpai** [comment]
Putting this on hold pending #11557 since the failures on this are now present for sync streaming only, afaik

**Pull request closed without merging**
