### PR TITLE
Migrate SSL_transport_security TSI to new TSI handshaker API

### PR DESCRIPTION
**Pull request by jiangtaoli2016**
On SSL TSI, deprecate get_bytes_to_send_to_peer, process_bytes_from_peer, get_result, extract_peer. Implement tsi_handshaker_next natively for SSL transport security.

Also delete transport_security_adapter.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/15313)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%     +72 [None]                                                                           +7.50Ki  +0.1%
      +0.0%     +32 [Unmapped]                                                                       +7.46Ki  +0.1%
      +100%     +40 handshaker_result_vtable                                                             +40  +100%
  +4.3%    +560 src/core/tsi/ssl_transport_security.cc                                              +560  +4.3%
      [NEW]    +631 ssl_handshaker_next                                                                 +631  [NEW]
      [NEW]    +434 ssl_handshaker_result_extract_peer                                                  +434  [NEW]
      [NEW]    +370 ssl_handshaker_process_bytes_from_peer                                              +370  [NEW]
      [NEW]    +245 ssl_handshaker_result_create_frame_protector                                        +245  [NEW]
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.10]            +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.8]         +47  [NEW]
      +6.1%     +41 create_tsi_ssl_handshaker                                                            +41  +6.1%
      [NEW]     +40 ssl_handshaker_result_destroy                                                        +40  [NEW]
      +8.8%     +35 [Unmapped]                                                                           +35  +8.8%
      [NEW]     +17 ssl_handshaker_result_get_unused_bytes                                               +17  [NEW]
       +22%      +9 ssl_handshaker_destroy                                                                +9   +22%

 -------------- SHRINKING                                                                        --------------
  -1.3%     -16 src/core/lib/http/httpcli_security_connector.cc                                      -16  -1.3%
      -9.1%     -16 httpcli_ssl_add_handshakers                                                          -16  -9.1%
  -0.2%     -16 src/core/lib/security/security_connector/security_connector.cc                       -16  -0.2%
      -6.0%     -11 ssl_channel_add_handshakers                                                          -11  -6.0%
      -0.9%      -5 [Unmapped]                                                                            -5  -0.9%

  +0.0%    +600 TOTAL                                                                            +8.02Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +4.3%    +560 src/core/tsi/ssl_transport_security.cc                                              +560  +4.3%
      [NEW]    +631 ssl_handshaker_next                                                                 +631  [NEW]
      [NEW]    +434 ssl_handshaker_result_extract_peer                                                  +434  [NEW]
      [NEW]    +370 ssl_handshaker_process_bytes_from_peer                                              +370  [NEW]
      [NEW]    +245 ssl_handshaker_result_create_frame_protector                                        +245  [NEW]
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.10]            +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.8]         +47  [NEW]
      +6.1%     +41 create_tsi_ssl_handshaker                                                            +41  +6.1%
      [NEW]     +40 ssl_handshaker_result_destroy                                                        +40  [NEW]
      +8.8%     +35 [Unmapped]                                                                           +35  +8.8%
      [NEW]     +17 ssl_handshaker_result_get_unused_bytes                                               +17  [NEW]
       +22%      +9 ssl_handshaker_destroy                                                                +9   +22%

 -------------- SHRINKING                                                                        --------------
  -0.2% -1.37Ki [None]                                                                           -9.75Ki  -0.1%
      -0.2% -1.28Ki [Unmapped]                                                                       -9.69Ki  -0.1%
     -25.0%     -56 handshaker_vtable                                                                    -56 -25.0%
     -50.0%     -40 result_vtable                                                                        -40 -50.0%
      -2.6%     -32 [None]                                                                                 0  [ = ]
  [DEL] -1.08Ki src/core/tsi/transport_security_adapter.cc                                       -1.08Ki  [DEL]
      [DEL]    -621 adapter_next                                                                        -621  [DEL]
      [DEL]    -123 tsi_create_adapter_handshaker                                                       -123  [DEL]
      [DEL]     -96 [Unmapped]                                                                           -96  [DEL]
      [DEL]     -37 adapter_create_frame_protector                                                       -37  [DEL]
      [DEL]     -37 adapter_process_bytes_from_peer                                                      -37  [DEL]
      [DEL]     -37 adapter_get_bytes_to_send_to_peer                                                    -37  [DEL]
      [DEL]     -31 adapter_destroy                                                                      -31  [DEL]
      [DEL]     -31 adapter_result_destroy                                                               -31  [DEL]
      [DEL]     -21 adapter_get_result                                                                   -21  [DEL]
      [DEL]     -21 adapter_extract_peer                                                                 -21  [DEL]
      [DEL]     -19 tsi_adapter_handshaker_get_wrapped                                                   -19  [DEL]
      [DEL]     -17 adapter_result_get_unused_bytes                                                      -17  [DEL]
      [DEL]      -9 adapter_result_extract_peer                                                           -9  [DEL]
      [DEL]      -9 adapter_result_create_frame_protector                                                 -9  [DEL]
  -1.3%     -16 src/core/lib/http/httpcli_security_connector.cc                                      -16  -1.3%
      -9.1%     -16 httpcli_ssl_add_handshakers                                                          -16  -9.1%
  -0.2%     -16 src/core/lib/security/security_connector/security_connector.cc                       -16  -0.2%
      -6.0%     -11 ssl_channel_add_handshakers                                                          -11  -6.0%
      -0.9%      -5 [Unmapped]                                                                            -5  -0.9%

  -0.1% -1.94Ki TOTAL                                                                            -10.3Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jiangtaoli2016** [comment]
@markdroth Can you please review?

**Comment by markdroth** [comment]
This looks good overall.  Just a couple of comments.

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/core/tsi/transport_security.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/15313#-LC4rQL2Apki5tOi4Cg7:-LC4rQL2Apki5tOi4Cg8:b-d5o58h) ([raw file](https://github.com/grpc/grpc/blob/68db94e975b664b5c7b067b35cd362a698e0a7b6/src/core/tsi/transport_security.h#L58)):*
> ```objc
>    See transport_security_interface.h for documentation. */
> typedef struct {
>   tsi_result (*get_bytes_to_send_to_peer)(tsi_handshaker* self,
> ```

Any reason not to remove these deprecated methods in this PR?

---

*[src/core/tsi/transport_security.h, line 98 at r1](https://reviewable.io/reviews/grpc/grpc/15313#-LC4qbYT1PHaF24kyrFF:-LC4qbYT1PHaF24kyrFG:b-jn0297) ([raw file](https://github.com/grpc/grpc/blob/aef957950aa3390e3516531ca2d783de8fc9333b/src/core/tsi/transport_security.h#L98)):*
> ```objc
>       size_t* max_output_protected_frame_size,
>       tsi_zero_copy_grpc_protector** protector);
>   tsi_result (*create_frame_protector)(const tsi_handshaker_result* self,
> ```

It seems odd to make this a non-const method when the other methods are all const.  Possible alternatives, in order of decreasing preference:

- Keep this as const and don't bother resetting the fields in the result object.  Instead, just document that the caller must only create the frame protector once from a given result object.

- Keep this as const and use a const_cast<> to reset the fields in the result object.  This is a bit ugly, but it is consistent with the idea that this doesn't actually modify the result object from the caller's perspective.

- Change all of these methods to be non-const.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15313#-:-LC4sxkk0WmvUhbvrgbZ:bicqb5l)*

**Comment by jiangtaoli2016** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/core/tsi/transport_security.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/15313#-LC4rQL2Apki5tOi4Cg7:-LC4uW0K0YNFleJv5JWk:bvomziq) ([raw file](https://github.com/grpc/grpc/blob/68db94e975b664b5c7b067b35cd362a698e0a7b6/src/core/tsi/transport_security.h#L58)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Any reason not to remove these deprecated methods in this PR?
</blockquote></details>

GFE is still calling TSI using old API. We cannot get rid of the old deprecated methods yet. 

---

*[src/core/tsi/transport_security.h, line 98 at r1](https://reviewable.io/reviews/grpc/grpc/15313#-LC4qbYT1PHaF24kyrFF:-LC4v8MN5XMhTxk70YcO:b6a0hpb) ([raw file](https://github.com/grpc/grpc/blob/aef957950aa3390e3516531ca2d783de8fc9333b/src/core/tsi/transport_security.h#L98)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

It seems odd to make this a non-const method when the other methods are all const.  Possible alternatives, in order of decreasing preference:

- Keep this as const and don't bother resetting the fields in the result object.  Instead, just document that the caller must only create the frame protector once from a given result object.

- Keep this as const and use a const_cast<> to reset the fields in the result object.  This is a bit ugly, but it is consistent with the idea that this doesn't actually modify the result object from the caller's perspective.

- Change all of these methods to be non-const.
</blockquote></details>

In fact, I tried (1) before creating this PR. It will crash due to following:
during create ssl frame protector, ssl and network_io pointers are copied to frame protector. Say we do not reset nullptr of these value in handshaker_result.
during destroy of handshaker result, it will destroy ssl and network_io.
when frame protector tries to use it, it will crash.

It is safer to set ssl and network_io to nullptr after frame protector is created. Let me do (2) then

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15313)*

**Comment by jiangtaoli2016** [comment]
@markdroth Code revised.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +4.3%    +560 src/core/tsi/ssl_transport_security.cc                                              +560  +4.3%
      [NEW]    +631 ssl_handshaker_next                                                                 +631  [NEW]
      [NEW]    +434 ssl_handshaker_result_extract_peer                                                  +434  [NEW]
      [NEW]    +370 ssl_handshaker_process_bytes_from_peer                                              +370  [NEW]
      [NEW]    +245 ssl_handshaker_result_create_frame_protector                                        +245  [NEW]
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.10]            +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.8]         +47  [NEW]
      +6.1%     +41 create_tsi_ssl_handshaker                                                            +41  +6.1%
      [NEW]     +40 ssl_handshaker_result_destroy                                                        +40  [NEW]
      +8.8%     +35 [Unmapped]                                                                           +35  +8.8%
      [NEW]     +17 ssl_handshaker_result_get_unused_bytes                                               +17  [NEW]
       +22%      +9 ssl_handshaker_destroy                                                                +9   +22%

 -------------- SHRINKING                                                                        --------------
  -0.2% -1.34Ki [None]                                                                           -9.75Ki  -0.1%
      -0.2% -1.25Ki [Unmapped]                                                                       -9.69Ki  -0.1%
     -25.0%     -56 handshaker_vtable                                                                    -56 -25.0%
     -50.0%     -40 result_vtable                                                                        -40 -50.0%
      -2.6%     -32 [None]                                                                                 0  [ = ]
  [DEL] -1.08Ki src/core/tsi/transport_security_adapter.cc                                       -1.08Ki  [DEL]
      [DEL]    -621 adapter_next                                                                        -621  [DEL]
      [DEL]    -123 tsi_create_adapter_handshaker                                                       -123  [DEL]
      [DEL]     -96 [Unmapped]                                                                           -96  [DEL]
      [DEL]     -37 adapter_create_frame_protector                                                       -37  [DEL]
      [DEL]     -37 adapter_process_bytes_from_peer                                                      -37  [DEL]
      [DEL]     -37 adapter_get_bytes_to_send_to_peer                                                    -37  [DEL]
      [DEL]     -31 adapter_destroy                                                                      -31  [DEL]
      [DEL]     -31 adapter_result_destroy                                                               -31  [DEL]
      [DEL]     -21 adapter_get_result                                                                   -21  [DEL]
      [DEL]     -21 adapter_extract_peer                                                                 -21  [DEL]
      [DEL]     -19 tsi_adapter_handshaker_get_wrapped                                                   -19  [DEL]
      [DEL]     -17 adapter_result_get_unused_bytes                                                      -17  [DEL]
      [DEL]      -9 adapter_result_extract_peer                                                           -9  [DEL]
      [DEL]      -9 adapter_result_create_frame_protector                                                 -9  [DEL]
  -1.3%     -16 src/core/lib/http/httpcli_security_connector.cc                                      -16  -1.3%
      -9.1%     -16 httpcli_ssl_add_handshakers                                                          -16  -9.1%
  -0.2%     -16 src/core/lib/security/security_connector/security_connector.cc                       -16  -0.2%
      -6.0%     -11 ssl_channel_add_handshakers                                                          -11  -6.0%
      -0.9%      -5 [Unmapped]                                                                            -5  -0.9%

  -0.1% -1.91Ki TOTAL                                                                            -10.3Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by markdroth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/core/tsi/transport_security.h, line 58 at r1](https://reviewable.io/reviews/grpc/grpc/15313#-LC4rQL2Apki5tOi4Cg7:-LC56XA40sMBt0FQUq2l:b62yh52) ([raw file](https://github.com/grpc/grpc/blob/68db94e975b664b5c7b067b35cd362a698e0a7b6/src/core/tsi/transport_security.h#L58)):*
<details><summary><i>Previously, jiangtaoli2016 (Jiangtao Li) wrote…</i></summary><blockquote>

GFE is still calling TSI using old API. We cannot get rid of the old deprecated methods yet. 
</blockquote></details>

Okay.  Then please add a TODO about removing these methods in a future PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15313)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +4.3%    +560 src/core/tsi/ssl_transport_security.cc                                              +560  +4.3%
      [NEW]    +631 ssl_handshaker_next                                                                 +631  [NEW]
      [NEW]    +434 ssl_handshaker_result_extract_peer                                                  +434  [NEW]
      [NEW]    +370 ssl_handshaker_process_bytes_from_peer                                              +370  [NEW]
      [NEW]    +245 ssl_handshaker_result_create_frame_protector                                        +245  [NEW]
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.10]            +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.8]         +47  [NEW]
      +6.1%     +41 create_tsi_ssl_handshaker                                                            +41  +6.1%
      [NEW]     +40 ssl_handshaker_result_destroy                                                        +40  [NEW]
      +8.8%     +35 [Unmapped]                                                                           +35  +8.8%
      [NEW]     +17 ssl_handshaker_result_get_unused_bytes                                               +17  [NEW]
       +22%      +9 ssl_handshaker_destroy                                                                +9   +22%

 -------------- SHRINKING                                                                        --------------
  -0.2% -1.34Ki [None]                                                                           -9.75Ki  -0.1%
      -0.2% -1.25Ki [Unmapped]                                                                       -9.69Ki  -0.1%
     -25.0%     -56 handshaker_vtable                                                                    -56 -25.0%
     -50.0%     -40 result_vtable                                                                        -40 -50.0%
      -2.6%     -32 [None]                                                                                 0  [ = ]
  [DEL] -1.08Ki src/core/tsi/transport_security_adapter.cc                                       -1.08Ki  [DEL]
      [DEL]    -621 adapter_next                                                                        -621  [DEL]
      [DEL]    -123 tsi_create_adapter_handshaker                                                       -123  [DEL]
      [DEL]     -96 [Unmapped]                                                                           -96  [DEL]
      [DEL]     -37 adapter_create_frame_protector                                                       -37  [DEL]
      [DEL]     -37 adapter_process_bytes_from_peer                                                      -37  [DEL]
      [DEL]     -37 adapter_get_bytes_to_send_to_peer                                                    -37  [DEL]
      [DEL]     -31 adapter_destroy                                                                      -31  [DEL]
      [DEL]     -31 adapter_result_destroy                                                               -31  [DEL]
      [DEL]     -21 adapter_get_result                                                                   -21  [DEL]
      [DEL]     -21 adapter_extract_peer                                                                 -21  [DEL]
      [DEL]     -19 tsi_adapter_handshaker_get_wrapped                                                   -19  [DEL]
      [DEL]     -17 adapter_result_get_unused_bytes                                                      -17  [DEL]
      [DEL]      -9 adapter_result_extract_peer                                                           -9  [DEL]
      [DEL]      -9 adapter_result_create_frame_protector                                                 -9  [DEL]
  -1.3%     -16 src/core/lib/http/httpcli_security_connector.cc                                      -16  -1.3%
      -9.1%     -16 httpcli_ssl_add_handshakers                                                          -16  -9.1%
  -0.2%     -16 src/core/lib/security/security_connector/security_connector.cc                       -16  -0.2%
      -6.0%     -11 ssl_channel_add_handshakers                                                          -11  -6.0%
      -0.9%      -5 [Unmapped]                                                                            -5  -0.9%

  -0.1% -1.91Ki TOTAL                                                                            -10.3Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
LGTM

---

Reviewed 2 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15313#-:-LC5XebD2ZVPrLtoJjRa:bb6ywmx)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +4.3%    +560 src/core/tsi/ssl_transport_security.cc                                              +560  +4.3%
      [NEW]    +631 ssl_handshaker_next                                                                 +631  [NEW]
      [NEW]    +434 ssl_handshaker_result_extract_peer                                                  +434  [NEW]
      [NEW]    +370 ssl_handshaker_process_bytes_from_peer                                              +370  [NEW]
      [NEW]    +245 ssl_handshaker_result_create_frame_protector                                        +245  [NEW]
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.10]            +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.8]         +47  [NEW]
      +6.1%     +41 create_tsi_ssl_handshaker                                                            +41  +6.1%
      [NEW]     +40 ssl_handshaker_result_destroy                                                        +40  [NEW]
      +8.8%     +35 [Unmapped]                                                                           +35  +8.8%
      [NEW]     +17 ssl_handshaker_result_get_unused_bytes                                               +17  [NEW]
       +22%      +9 ssl_handshaker_destroy                                                                +9   +22%

 -------------- SHRINKING                                                                        --------------
  -0.2% -1.42Ki [None]                                                                           -14.1Ki  -0.2%
      -0.2% -1.35Ki [Unmapped]                                                                       -14.0Ki  -0.2%
     -25.0%     -64 handshaker_vtable                                                                    -64 -25.0%
     -50.0%     -40 result_vtable                                                                        -40 -50.0%
  [DEL] -1.10Ki src/core/tsi/transport_security_adapter.cc                                       -1.10Ki  [DEL]
      [DEL]    -621 adapter_next                                                                        -621  [DEL]
      [DEL]    -123 tsi_create_adapter_handshaker                                                       -123  [DEL]
      [DEL]    -103 [Unmapped]                                                                          -103  [DEL]
      [DEL]     -37 adapter_create_frame_protector                                                       -37  [DEL]
      [DEL]     -37 adapter_process_bytes_from_peer                                                      -37  [DEL]
      [DEL]     -37 adapter_get_bytes_to_send_to_peer                                                    -37  [DEL]
      [DEL]     -31 adapter_destroy                                                                      -31  [DEL]
      [DEL]     -31 adapter_result_destroy                                                               -31  [DEL]
      [DEL]     -21 adapter_get_result                                                                   -21  [DEL]
      [DEL]     -21 adapter_extract_peer                                                                 -21  [DEL]
      [DEL]     -19 tsi_adapter_handshaker_get_wrapped                                                   -19  [DEL]
      [DEL]     -17 adapter_result_get_unused_bytes                                                      -17  [DEL]
      [DEL]      -9 adapter_shutdown                                                                      -9  [DEL]
      [DEL]      -9 adapter_result_extract_peer                                                           -9  [DEL]
      [DEL]      -9 adapter_result_create_frame_protector                                                 -9  [DEL]
  -1.3%     -16 src/core/lib/http/httpcli_security_connector.cc                                      -16  -1.3%
      -9.1%     -16 httpcli_ssl_add_handshakers                                                          -16  -9.1%
  -0.2%     -16 src/core/lib/security/security_connector/security_connector.cc                       -16  -0.2%
      -6.0%     -11 ssl_channel_add_handshakers                                                          -11  -6.0%
      -0.9%      -5 [Unmapped]                                                                            -5  -0.9%

  -0.1% -2.00Ki TOTAL                                                                            -14.7Ki  -0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by jiangtaoli2016** [comment]
Conflict resolved on PR#15265
@markdroth approval?

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +4.3%    +560 src/core/tsi/ssl_transport_security.cc                                              +560  +4.3%
      [NEW]    +631 ssl_handshaker_next                                                                 +631  [NEW]
      [NEW]    +434 ssl_handshaker_result_extract_peer                                                  +434  [NEW]
      [NEW]    +370 ssl_handshaker_process_bytes_from_peer                                              +370  [NEW]
      [NEW]    +245 ssl_handshaker_result_create_frame_protector                                        +245  [NEW]
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.10]            +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.8]         +47  [NEW]
      +6.1%     +41 create_tsi_ssl_handshaker                                                            +41  +6.1%
      [NEW]     +40 ssl_handshaker_result_destroy                                                        +40  [NEW]
      +8.8%     +35 [Unmapped]                                                                           +35  +8.8%
      [NEW]     +17 ssl_handshaker_result_get_unused_bytes                                               +17  [NEW]
       +22%      +9 ssl_handshaker_destroy                                                                +9   +22%

 -------------- SHRINKING                                                                        --------------
  -0.2% -1.42Ki [None]                                                                           -14.1Ki  -0.2%
      -0.2% -1.35Ki [Unmapped]                                                                       -14.0Ki  -0.2%
     -25.0%     -64 handshaker_vtable                                                                    -64 -25.0%
     -50.0%     -40 result_vtable                                                                        -40 -50.0%
  [DEL] -1.10Ki src/core/tsi/transport_security_adapter.cc                                       -1.10Ki  [DEL]
      [DEL]    -621 adapter_next                                                                        -621  [DEL]
      [DEL]    -123 tsi_create_adapter_handshaker                                                       -123  [DEL]
      [DEL]    -103 [Unmapped]                                                                          -103  [DEL]
      [DEL]     -37 adapter_create_frame_protector                                                       -37  [DEL]
      [DEL]     -37 adapter_process_bytes_from_peer                                                      -37  [DEL]
      [DEL]     -37 adapter_get_bytes_to_send_to_peer                                                    -37  [DEL]
      [DEL]     -31 adapter_destroy                                                                      -31  [DEL]
      [DEL]     -31 adapter_result_destroy                                                               -31  [DEL]
      [DEL]     -21 adapter_get_result                                                                   -21  [DEL]
      [DEL]     -21 adapter_extract_peer                                                                 -21  [DEL]
      [DEL]     -19 tsi_adapter_handshaker_get_wrapped                                                   -19  [DEL]
      [DEL]     -17 adapter_result_get_unused_bytes                                                      -17  [DEL]
      [DEL]      -9 adapter_shutdown                                                                      -9  [DEL]
      [DEL]      -9 adapter_result_extract_peer                                                           -9  [DEL]
      [DEL]      -9 adapter_result_create_frame_protector                                                 -9  [DEL]
  -1.3%     -16 src/core/lib/http/httpcli_security_connector.cc                                      -16  -1.3%
      -9.1%     -16 httpcli_ssl_add_handshakers                                                          -16  -9.1%
  -0.2%     -16 src/core/lib/security/security_connector/security_connector.cc                       -16  -0.2%
      -6.0%     -11 ssl_channel_add_handshakers                                                          -11  -6.0%
      -0.9%      -5 [Unmapped]                                                                            -5  -0.9%

  -0.1% -2.00Ki TOTAL                                                                            -14.7Ki  -0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +4.3%    +560 src/core/tsi/ssl_transport_security.cc                                              +560  +4.3%
      [NEW]    +631 ssl_handshaker_next                                                                 +631  [NEW]
      [NEW]    +434 ssl_handshaker_result_extract_peer                                                  +434  [NEW]
      [NEW]    +370 ssl_handshaker_process_bytes_from_peer                                              +370  [NEW]
      [NEW]    +245 ssl_handshaker_result_create_frame_protector                                        +245  [NEW]
      [NEW]     +76 ssl_log_where_info(ssl_st const*, int, int, char const*) [clone .part.10]            +76  [NEW]
      [NEW]     +47 tsi_ssl_handshaker_factory_init(tsi_ssl_handshaker_factory*) [clone .part.8]         +47  [NEW]
      +6.1%     +41 create_tsi_ssl_handshaker                                                            +41  +6.1%
      [NEW]     +40 ssl_handshaker_result_destroy                                                        +40  [NEW]
      +8.8%     +35 [Unmapped]                                                                           +35  +8.8%
      [NEW]     +17 ssl_handshaker_result_get_unused_bytes                                               +17  [NEW]
       +22%      +9 ssl_handshaker_destroy                                                                +9   +22%

 -------------- SHRINKING                                                                        --------------
  -0.2% -1.42Ki [None]                                                                           -14.1Ki  -0.2%
      -0.2% -1.35Ki [Unmapped]                                                                       -14.0Ki  -0.2%
     -25.0%     -64 handshaker_vtable                                                                    -64 -25.0%
     -50.0%     -40 result_vtable                                                                        -40 -50.0%
  [DEL] -1.10Ki src/core/tsi/transport_security_adapter.cc                                       -1.10Ki  [DEL]
      [DEL]    -621 adapter_next                                                                        -621  [DEL]
      [DEL]    -123 tsi_create_adapter_handshaker                                                       -123  [DEL]
      [DEL]    -103 [Unmapped]                                                                          -103  [DEL]
      [DEL]     -37 adapter_create_frame_protector                                                       -37  [DEL]
      [DEL]     -37 adapter_process_bytes_from_peer                                                      -37  [DEL]
      [DEL]     -37 adapter_get_bytes_to_send_to_peer                                                    -37  [DEL]
      [DEL]     -31 adapter_destroy                                                                      -31  [DEL]
      [DEL]     -31 adapter_result_destroy                                                               -31  [DEL]
      [DEL]     -21 adapter_get_result                                                                   -21  [DEL]
      [DEL]     -21 adapter_extract_peer                                                                 -21  [DEL]
      [DEL]     -19 tsi_adapter_handshaker_get_wrapped                                                   -19  [DEL]
      [DEL]     -17 adapter_result_get_unused_bytes                                                      -17  [DEL]
      [DEL]      -9 adapter_shutdown                                                                      -9  [DEL]
      [DEL]      -9 adapter_result_extract_peer                                                           -9  [DEL]
      [DEL]      -9 adapter_result_create_frame_protector                                                 -9  [DEL]
  -1.3%     -16 src/core/lib/http/httpcli_security_connector.cc                                      -16  -1.3%
      -9.1%     -16 httpcli_ssl_add_handshakers                                                          -16  -9.1%
  -0.2%     -16 src/core/lib/security/security_connector/security_connector.cc                       -16  -0.2%
      -6.0%     -11 ssl_channel_add_handshakers                                                          -11  -6.0%
      -0.9%      -5 [Unmapped]                                                                            -5  -0.9%

  -0.1% -2.00Ki TOTAL                                                                            -14.7Ki  -0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jiangtaoli2016** [comment]
Failing Basic Tests MacOS tests are unrelated. Let me merge

**Pull request merged**
