### PR TITLE
fix non-virtual-dtor

### PR DESCRIPTION
**Pull request by toanju**
compiling with -Wnon-virtual-dtor works with this patch

### CODE REVIEW

**Comment by toanju** [comment]
seems like I have to check the code in more detail... adding the destructors leads to segfaults.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.1%    -344 [None]                                                                               -2.38Ki  -0.0%
  -1.8%    -256 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                          -256  -1.8%
      [DEL] -1.50Ki rr_handover_locked(glb_lb_policy*) [clone .part.19]                                  -1.50Ki  [DEL]
      [DEL]    -801 build_lb_channel_args(grpc_lb_addresses const*, grpc_fake_resolver_response_generato    -801  [DEL]
      [DEL]    -531 send_client_load_report_locked                                                          -531  [DEL]
      [DEL]    -284 glb_lb_call_data_unref                                                                  -284  [DEL]
     -36.2%    -234 lb_on_server_status_received_locked                                                     -234 -36.2%
      [DEL]    -145 lb_call_data_shutdown(glb_lb_policy*) [clone .isra.4]                                   -145  [DEL]
      [DEL]    -119 schedule_next_client_load_report                                                        -119  [DEL]
      [DEL]     -92 glb_lb_call_data_ref                                                                     -92  [DEL]
     -16.9%     -73 [Unmapped]                                                                               -73 -16.9%
      -6.2%     -64 glb_create                                                                               -64  -6.2%
      -4.3%     -58 lb_on_response_received_locked                                                           -58  -4.3%
      [DEL]     -58 maybe_send_client_load_report_locked                                                     -58  [DEL]
     -42.0%     -55 query_for_backends_locked                                                                -55 -42.0%
     -56.8%     -46 lb_on_sent_initial_request_locked                                                        -46 -56.8%

  -0.0%    -600 TOTAL                                                                                -2.62Ki  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.4%    +859 [None]                                                                               +23.4Ki  +0.5%
      +0.4%    +795 [Unmapped]                                                                           +23.4Ki  +0.5%
       +29%     +16 grpc::internal::g_core_codegen                                                           +16   +29%
       +29%     +16 grpc::internal::g_gli                                                                    +16   +29%
      +4.0%     +16 vtable for grpc::CoreCodegen                                                             +16  +4.0%
       +50%     +16 vtable for grpc::internal::GrpcLibrary                                                   +16   +50%
  +1.7%    +151 src/cpp/client/secure_credentials.cc                                                    +151  +1.7%
       +56%     +54 [Unmapped]                                                                               +54   +56%
       +54%     +52 _GLOBAL__sub_I_secure_credentials.cc                                                     +52   +54%
      +2.8%      +9 grpc::SslCredentials                                                                      +9  +2.8%
      +3.4%      +9 grpc::GoogleDefaultCredentials                                                            +9  +3.4%
      [NEW]      +5 grpc::CoreCodegen::~CoreCodegen                                                           +5  [NEW]
      [NEW]      +5 grpc::internal::GrpcLibrary::~GrpcLibrary                                                 +5  [NEW]
      [NEW]      +2 grpc::CoreCodegen::~CoreCodegen                                                           +2  [NEW]
      [NEW]      +2 grpc::internal::GrpcLibrary::~GrpcLibrary                                                 +2  [NEW]
      +0.3%      +1 [Other]                                                                                   +1  +0.3%
      +0.7%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen                                             +1  +0.7%
      +0.8%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen                                             +1  +0.8%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.3%      +1 grpc::GoogleIAMCredentials                                                                +1  +0.3%
      +0.4%      +1 grpc::AccessTokenCredentials                                                              +1  +0.4%
      +0.4%      +1 grpc::GoogleRefreshTokenCredentials                                                       +1  +0.4%
      +0.2%      +1 grpc::MetadataCredentialsFromPlugin                                                       +1  +0.2%
      +0.4%      +1 grpc::GoogleComputeEngineCredentials                                                      +1  +0.4%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::Destroy                                           +1  +0.5%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::MetadataCredentialsPluginWrapper                  +1  +0.5%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::~MetadataCredentialsPluginWrapper                 +1  +0.5%
      +0.6%      +1 grpc::MetadataCredentialsPluginWrapper::~MetadataCredentialsPluginWrapper                 +1  +0.6%
   +12%     +84 src/cpp/client/credentials_cc.cc                                                         +84   +12%
       +54%     +52 _GLOBAL__sub_I_credentials_cc.cc                                                         +52   +54%
      +175%     +28 [Unmapped]                                                                               +28  +175%
      +0.7%      +1 grpc::CallCredentials::CallCredentials                                                    +1  +0.7%
      +0.8%      +1 grpc::CallCredentials::~CallCredentials                                                   +1  +0.8%
      +0.7%      +1 grpc::ChannelCredentials::ChannelCredentials                                              +1  +0.7%
      +0.8%      +1 grpc::ChannelCredentials::~ChannelCredentials                                             +1  +0.8%
  +1.6%     +71 src/cpp/client/channel_cc.cc                                                             +71  +1.6%
       +54%     +52 _GLOBAL__sub_I_channel_cc.cc                                                             +52   +54%
      +7.1%     +13 [Unmapped]                                                                               +13  +7.1%
      +0.6%      +1 grpc::CompletionQueue::~CompletionQueue                                                   +1  +0.6%
      +0.6%      +1 grpc::CompletionQueue::~CompletionQueue                                                   +1  +0.6%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.2%      +1 grpc::Channel::WaitForStateChangeImpl                                                     +1  +0.2%
      +0.3%      +1 grpc::Channel::Channel                                                                    +1  +0.3%
      +0.4%      +1 grpc::Channel::~Channel                                                                   +1  +0.4%
  +0.2%     +55 src/cpp/server/server_cc.cc                                                              +55  +0.2%
       +36%     +52 _GLOBAL__sub_I_server_cc.cc                                                              +52   +36%
      +0.2%      +2 grpc::Server::ShutdownInternal                                                            +2  +0.2%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.5%      +1 grpc::Server::SyncRequest::CallData::~CallData                                            +1  +0.5%
      +0.1%      +1 grpc::Server::SyncRequestThreadManager::DoWork                                            +1  +0.1%
      +0.1%      +1 grpc::Server::Server                                                                      +1  +0.1%
      +0.1%      +1 grpc::Server::~Server                                                                     +1  +0.1%
  +1.2%     +52 src/cpp/client/client_context.cc                                                         +52  +1.2%
       +43%     +52 _GLOBAL__sub_I_client_context.cc                                                         +52   +43%
  +8.0%     +52 src/cpp/client/create_channel.cc                                                         +52  +8.0%
      +113%     +52 _GLOBAL__sub_I_create_channel.cc                                                         +52  +113%
      +0.4%      +2 grpc::CreateCustomChannel                                                                 +2  +0.4%
  +8.7%     +52 src/cpp/client/create_channel_posix.cc                                                   +52  +8.7%
      [NEW]    +174 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +174  [NEW]
      +113%     +52 _GLOBAL__sub_I_create_channel_posix.cc                                                   +52  +113%
   +10%     +52 src/cpp/common/completion_queue_cc.cc                                                    +52   +10%
       +54%     +52 _GLOBAL__sub_I_completion_queue_cc.cc                                                    +52   +54%
  +3.3%     +52 src/cpp/util/byte_buffer_cc.cc                                                           +52  +3.3%
       +54%     +52 _GLOBAL__sub_I_byte_buffer_cc.cc                                                         +52   +54%
  +0.0%      +5 src/cpp/client/generic_stub.cc                                                            +5  +0.0%
      +0.1%      +1 grpc::GenericStub::PrepareUnaryCall                                                       +1  +0.1%
      +0.9%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::ReadInitialMetada      +1  +0.9%
      +0.3%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::Write                  +1  +0.3%
      +0.3%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::Write                  +1  +0.3%
      +0.9%      +1 grpc::ClientAsyncResponseReader<grpc::ByteBuffer>::ReadInitialMetadata                    +1  +0.9%
  +0.0%      +3 src/cpp/server/server_builder.cc                                                          +3  +0.0%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.6%      +1 grpc::ServerCompletionQueue::~ServerCompletionQueue                                       +1  +0.6%
      +0.7%      +1 grpc::ServerCompletionQueue::~ServerCompletionQueue                                       +1  +0.7%

  +0.4% +1.45Ki TOTAL                                                                                +24.1Ki  +0.5%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by toanju** [comment]
seems like I had a wrong configuration locally that led to the segfaults

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.3%    +807 [None]                                                                               +20.5Ki  +0.4%
      +0.3%    +743 [Unmapped]                                                                           +20.4Ki  +0.4%
       +25%     +16 grpc::internal::g_core_codegen                                                           +16   +25%
       +25%     +16 grpc::internal::g_gli                                                                    +16   +25%
      +4.0%     +16 vtable for grpc::CoreCodegen                                                             +16  +4.0%
       +50%     +16 vtable for grpc::internal::GrpcLibrary                                                   +16   +50%
  +1.7%    +151 src/cpp/client/secure_credentials.cc                                                    +151  +1.7%
       +56%     +54 [Unmapped]                                                                               +54   +56%
       +54%     +52 _GLOBAL__sub_I_secure_credentials.cc                                                     +52   +54%
      +2.8%      +9 grpc::SslCredentials                                                                      +9  +2.8%
      +3.4%      +9 grpc::GoogleDefaultCredentials                                                            +9  +3.4%
      [NEW]      +5 grpc::CoreCodegen::~CoreCodegen                                                           +5  [NEW]
      [NEW]      +5 grpc::internal::GrpcLibrary::~GrpcLibrary                                                 +5  [NEW]
      [NEW]      +2 grpc::CoreCodegen::~CoreCodegen                                                           +2  [NEW]
      [NEW]      +2 grpc::internal::GrpcLibrary::~GrpcLibrary                                                 +2  [NEW]
      +0.3%      +1 [Other]                                                                                   +1  +0.3%
      +0.7%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen                                             +1  +0.7%
      +0.8%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen                                             +1  +0.8%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.3%      +1 grpc::GoogleIAMCredentials                                                                +1  +0.3%
      +0.4%      +1 grpc::AccessTokenCredentials                                                              +1  +0.4%
      +0.4%      +1 grpc::GoogleRefreshTokenCredentials                                                       +1  +0.4%
      +0.2%      +1 grpc::MetadataCredentialsFromPlugin                                                       +1  +0.2%
      +0.4%      +1 grpc::GoogleComputeEngineCredentials                                                      +1  +0.4%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::Destroy                                           +1  +0.5%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::MetadataCredentialsPluginWrapper                  +1  +0.5%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::~MetadataCredentialsPluginWrapper                 +1  +0.5%
      +0.6%      +1 grpc::MetadataCredentialsPluginWrapper::~MetadataCredentialsPluginWrapper                 +1  +0.6%
   +12%     +84 src/cpp/client/credentials_cc.cc                                                         +84   +12%
       +54%     +52 _GLOBAL__sub_I_credentials_cc.cc                                                         +52   +54%
      +175%     +28 [Unmapped]                                                                               +28  +175%
      +0.7%      +1 grpc::CallCredentials::CallCredentials                                                    +1  +0.7%
      +0.8%      +1 grpc::CallCredentials::~CallCredentials                                                   +1  +0.8%
      +0.7%      +1 grpc::ChannelCredentials::ChannelCredentials                                              +1  +0.7%
      +0.8%      +1 grpc::ChannelCredentials::~ChannelCredentials                                             +1  +0.8%
  +1.6%     +71 src/cpp/client/channel_cc.cc                                                             +71  +1.6%
       +54%     +52 _GLOBAL__sub_I_channel_cc.cc                                                             +52   +54%
      +7.1%     +13 [Unmapped]                                                                               +13  +7.1%
      +0.6%      +1 grpc::CompletionQueue::~CompletionQueue                                                   +1  +0.6%
      +0.6%      +1 grpc::CompletionQueue::~CompletionQueue                                                   +1  +0.6%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.2%      +1 grpc::Channel::WaitForStateChangeImpl                                                     +1  +0.2%
      +0.3%      +1 grpc::Channel::Channel                                                                    +1  +0.3%
      +0.4%      +1 grpc::Channel::~Channel                                                                   +1  +0.4%
  +0.2%     +55 src/cpp/server/server_cc.cc                                                              +55  +0.2%
       +36%     +52 _GLOBAL__sub_I_server_cc.cc                                                              +52   +36%
      +0.2%      +2 grpc::Server::ShutdownInternal                                                            +2  +0.2%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.5%      +1 grpc::Server::SyncRequest::CallData::~CallData                                            +1  +0.5%
      +0.1%      +1 grpc::Server::SyncRequestThreadManager::DoWork                                            +1  +0.1%
      +0.1%      +1 grpc::Server::Server                                                                      +1  +0.1%
      +0.1%      +1 grpc::Server::~Server                                                                     +1  +0.1%
  +1.2%     +52 src/cpp/client/client_context.cc                                                         +52  +1.2%
       +43%     +52 _GLOBAL__sub_I_client_context.cc                                                         +52   +43%
  +8.0%     +52 src/cpp/client/create_channel.cc                                                         +52  +8.0%
      +113%     +52 _GLOBAL__sub_I_create_channel.cc                                                         +52  +113%
      +0.4%      +2 grpc::CreateCustomChannel                                                                 +2  +0.4%
  +8.7%     +52 src/cpp/client/create_channel_posix.cc                                                   +52  +8.7%
      [NEW]    +174 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +174  [NEW]
      +113%     +52 _GLOBAL__sub_I_create_channel_posix.cc                                                   +52  +113%
  +1.8%     +52 src/cpp/common/alarm.cc                                                                  +52  +1.8%
       +54%     +52 _GLOBAL__sub_I_alarm.cc                                                                  +52   +54%
      +0.6%      +2 grpc::Alarm::Alarm                                                                        +2  +0.6%
      +0.1%      +1 grpc::Alarm::~Alarm                                                                       +1  +0.1%
   +10%     +52 src/cpp/common/completion_queue_cc.cc                                                    +52   +10%
       +54%     +52 _GLOBAL__sub_I_completion_queue_cc.cc                                                    +52   +54%
  +3.3%     +52 src/cpp/util/byte_buffer_cc.cc                                                           +52  +3.3%
       +54%     +52 _GLOBAL__sub_I_byte_buffer_cc.cc                                                         +52   +54%
  +0.0%      +5 src/cpp/client/generic_stub.cc                                                            +5  +0.0%
      +0.1%      +1 grpc::GenericStub::PrepareUnaryCall                                                       +1  +0.1%
      +0.9%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::ReadInitialMetada      +1  +0.9%
      +0.3%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::Write                  +1  +0.3%
      +0.3%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::Write                  +1  +0.3%
      +0.9%      +1 grpc::ClientAsyncResponseReader<grpc::ByteBuffer>::ReadInitialMetadata                    +1  +0.9%
  +0.0%      +3 src/cpp/server/server_builder.cc                                                          +3  +0.0%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.6%      +1 grpc::ServerCompletionQueue::~ServerCompletionQueue                                       +1  +0.6%
      +0.7%      +1 grpc::ServerCompletionQueue::~ServerCompletionQueue                                       +1  +0.7%

  +0.4% +1.45Ki TOTAL                                                                                +21.1Ki  +0.4%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by toanju** [comment]
rebased to master due to merge conflicts (0e00c430827)

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.3%    +807 [None]                                                                               +20.4Ki  +0.4%
      +0.3%    +743 [Unmapped]                                                                           +20.3Ki  +0.4%
       +25%     +16 grpc::internal::g_core_codegen                                                           +16   +25%
       +25%     +16 grpc::internal::g_gli                                                                    +16   +25%
      +4.0%     +16 vtable for grpc::CoreCodegen                                                             +16  +4.0%
       +50%     +16 vtable for grpc::internal::GrpcLibrary                                                   +16   +50%
  +1.7%    +151 src/cpp/client/secure_credentials.cc                                                    +151  +1.7%
       +56%     +54 [Unmapped]                                                                               +54   +56%
       +54%     +52 _GLOBAL__sub_I_secure_credentials.cc                                                     +52   +54%
      +2.8%      +9 grpc::SslCredentials                                                                      +9  +2.8%
      +3.4%      +9 grpc::GoogleDefaultCredentials                                                            +9  +3.4%
      [NEW]      +5 grpc::CoreCodegen::~CoreCodegen                                                           +5  [NEW]
      [NEW]      +5 grpc::internal::GrpcLibrary::~GrpcLibrary                                                 +5  [NEW]
      [NEW]      +2 grpc::CoreCodegen::~CoreCodegen                                                           +2  [NEW]
      [NEW]      +2 grpc::internal::GrpcLibrary::~GrpcLibrary                                                 +2  [NEW]
      +0.3%      +1 [Other]                                                                                   +1  +0.3%
      +0.7%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen                                             +1  +0.7%
      +0.8%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen                                             +1  +0.8%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.3%      +1 grpc::GoogleIAMCredentials                                                                +1  +0.3%
      +0.4%      +1 grpc::AccessTokenCredentials                                                              +1  +0.4%
      +0.4%      +1 grpc::GoogleRefreshTokenCredentials                                                       +1  +0.4%
      +0.2%      +1 grpc::MetadataCredentialsFromPlugin                                                       +1  +0.2%
      +0.4%      +1 grpc::GoogleComputeEngineCredentials                                                      +1  +0.4%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::Destroy                                           +1  +0.5%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::MetadataCredentialsPluginWrapper                  +1  +0.5%
      +0.5%      +1 grpc::MetadataCredentialsPluginWrapper::~MetadataCredentialsPluginWrapper                 +1  +0.5%
      +0.6%      +1 grpc::MetadataCredentialsPluginWrapper::~MetadataCredentialsPluginWrapper                 +1  +0.6%
   +12%     +84 src/cpp/client/credentials_cc.cc                                                         +84   +12%
       +54%     +52 _GLOBAL__sub_I_credentials_cc.cc                                                         +52   +54%
      +175%     +28 [Unmapped]                                                                               +28  +175%
      +0.7%      +1 grpc::CallCredentials::CallCredentials                                                    +1  +0.7%
      +0.8%      +1 grpc::CallCredentials::~CallCredentials                                                   +1  +0.8%
      +0.7%      +1 grpc::ChannelCredentials::ChannelCredentials                                              +1  +0.7%
      +0.8%      +1 grpc::ChannelCredentials::~ChannelCredentials                                             +1  +0.8%
  +1.6%     +71 src/cpp/client/channel_cc.cc                                                             +71  +1.6%
       +54%     +52 _GLOBAL__sub_I_channel_cc.cc                                                             +52   +54%
      +7.1%     +13 [Unmapped]                                                                               +13  +7.1%
      +0.6%      +1 grpc::CompletionQueue::~CompletionQueue                                                   +1  +0.6%
      +0.6%      +1 grpc::CompletionQueue::~CompletionQueue                                                   +1  +0.6%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.2%      +1 grpc::Channel::WaitForStateChangeImpl                                                     +1  +0.2%
      +0.3%      +1 grpc::Channel::Channel                                                                    +1  +0.3%
      +0.4%      +1 grpc::Channel::~Channel                                                                   +1  +0.4%
  +0.2%     +55 src/cpp/server/server_cc.cc                                                              +55  +0.2%
       +36%     +52 _GLOBAL__sub_I_server_cc.cc                                                              +52   +36%
      +0.2%      +2 grpc::Server::ShutdownInternal                                                            +2  +0.2%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.5%      +1 grpc::Server::SyncRequest::CallData::~CallData                                            +1  +0.5%
      +0.1%      +1 grpc::Server::SyncRequestThreadManager::DoWork                                            +1  +0.1%
      +0.1%      +1 grpc::Server::Server                                                                      +1  +0.1%
      +0.1%      +1 grpc::Server::~Server                                                                     +1  +0.1%
  +1.2%     +52 src/cpp/client/client_context.cc                                                         +52  +1.2%
       +43%     +52 _GLOBAL__sub_I_client_context.cc                                                         +52   +43%
  +8.0%     +52 src/cpp/client/create_channel.cc                                                         +52  +8.0%
      +113%     +52 _GLOBAL__sub_I_create_channel.cc                                                         +52  +113%
      +0.4%      +2 grpc::CreateCustomChannel                                                                 +2  +0.4%
  +8.7%     +52 src/cpp/client/create_channel_posix.cc                                                   +52  +8.7%
      [NEW]    +174 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >    +174  [NEW]
      +113%     +52 _GLOBAL__sub_I_create_channel_posix.cc                                                   +52  +113%
  +1.8%     +52 src/cpp/common/alarm.cc                                                                  +52  +1.8%
       +54%     +52 _GLOBAL__sub_I_alarm.cc                                                                  +52   +54%
      +0.6%      +2 grpc::Alarm::Alarm                                                                        +2  +0.6%
      +0.1%      +1 grpc::Alarm::~Alarm                                                                       +1  +0.1%
   +10%     +52 src/cpp/common/completion_queue_cc.cc                                                    +52   +10%
       +54%     +52 _GLOBAL__sub_I_completion_queue_cc.cc                                                    +52   +54%
  +3.3%     +52 src/cpp/util/byte_buffer_cc.cc                                                           +52  +3.3%
       +54%     +52 _GLOBAL__sub_I_byte_buffer_cc.cc                                                         +52   +54%
  +0.0%      +5 src/cpp/client/generic_stub.cc                                                            +5  +0.0%
      +0.1%      +1 grpc::GenericStub::PrepareUnaryCall                                                       +1  +0.1%
      +0.9%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::ReadInitialMetada      +1  +0.9%
      +0.3%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::Write                  +1  +0.3%
      +0.3%      +1 grpc::ClientAsyncReaderWriter<grpc::ByteBuffer, grpc::ByteBuffer>::Write                  +1  +0.3%
      +0.9%      +1 grpc::ClientAsyncResponseReader<grpc::ByteBuffer>::ReadInitialMetadata                    +1  +0.9%
  +0.0%      +3 src/cpp/server/server_builder.cc                                                          +3  +0.0%
      +1.6%      +1 grpc::GrpcLibraryCodegen::~GrpcLibraryCodegen() [clone .part.0]                           +1  +1.6%
      +0.6%      +1 grpc::ServerCompletionQueue::~ServerCompletionQueue                                       +1  +0.6%
      +0.7%      +1 grpc::ServerCompletionQueue::~ServerCompletionQueue                                       +1  +0.7%

  +0.4% +1.45Ki TOTAL                                                                                +21.1Ki  +0.4%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark      cpu_time    real_time
-------------  ----------  -----------
BM_Zalloc/512  -7%         -7%
```

**Pull request merged**
