### PR TITLE
[v1.41.x] Add xDS k8s_lb tests

### PR DESCRIPTION
**Pull request by lidizheng**
As title. This PR is created by:

```
git co master -- \
  tools/internal_ci/linux/grpc_xds_k8s_lb.sh \
  tools/internal_ci/linux/grpc_xds_k8s_lb.cfg \
  tools/internal_ci/linux/grpc_xds_k8s_lb_python.sh \
  tools/internal_ci/linux/grpc_xds_k8s_lb_python.cfg \
  tools/internal_ci/linux/grpc_xds_url_map.sh \
  tools/internal_ci/linux/grpc_xds_url_map.cfg \
  tools/internal_ci/linux/grpc_xds_url_map_python.sh \
  tools/internal_ci/linux/grpc_xds_url_map_python.cfg
```

### CODE REVIEW

**Comment by lidizheng** [comment]
* [grpc_xds_k8s_lb](http://sponge/06c1ac86-b521-408d-b621-43ed3ac0918f)
* [grpc_xds_k8s_lb_python](http://sponge/cc99ac56-9f02-408d-b436-6482b17f2357)

**Comment by lidizheng** [comment]
Deflake:

* [grpc_xds_k8s_lb](http://sponge/0224343a-73b9-4811-809a-b7c7341bccc9)
* [grpc_xds_k8s_lb_python](http://sponge/021108ba-4d79-4680-822b-c02c6ef65ad7)

**Comment by lidizheng** [comment]
Deflake:

* [grpc_xds_k8s_lb_python](http://sponge/04d92f78-cccc-40ea-9f10-1cd637346234)

**Comment by lidizheng** [comment]
Rerun after https://github.com/grpc/grpc/pull/29945

* [grpc_xds_k8s_lb_python](http://sponge/aafc1c34-e98a-40e3-8e44-e67a407b3335)

**Review by ejona86 — APPROVED** [review]

**Pull request merged**
