### PR TITLE
Put a 900-sec timeout on the perf test.

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by jtattermusch** [comment]
this is ok to test

**Comment by jtattermusch** [comment]
LGTM, fine to merge once performance tests are green.

One observation I'd like to note is that it looks like the shell script will get out of hand fairly quickly and we might need to switch to something a bit more manageable in the future (e.g. some python script to drive this)

**Comment by pgrosu** [comment]
It passes, but 900sec is 15min which could be a while for later tests.  For instance, if we look at the pattern of build times over time, with the following script:

```Bash
$ cat perf-tests.sh
#!/bin/bash
testtimes=" "
for ((t=500;t<=700;t++));
do
  testtime=$(curl --silent https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/$t/ | grep Took | cut -f2 -d"<" | cut -f2 -d">")
  if [ $(expr "$testtime" : '.*') -gt 1 ]; then
    echo "BUILD "$t" -> "$testtime
  fi
done
$
$ ./perf-tests.sh
BUILD 600 -> 2 min 36 sec
BUILD 601 -> 2 min 37 sec
BUILD 602 -> 2 min 38 sec
...
```

If I look at the average, it's 2 min 22 sec.  If I plot the trend, it seems to expand quite dramatically lately by almost 4x than the average.

build_time_vs_build

It might be good to keep this in mind, and maybe optimize around it so that it doesn't become a bottleneck later on.

~p

**Comment by pgrosu** [comment]
I guess that's what Jan was suggesting too :)

**Pull request merged**
