### PR TITLE
Add verbosity back to Python `run_tests.py` output

### PR DESCRIPTION
**Pull request by soltanmm**
We used to have verbosity back when we were manually running the tests via `run_tests.py`. This puts it back in now that we use `py.test`. Should help us address such issues as #3585.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Change content looks fine but test output looks not just verbose but also crazypants - some stack traces involve gRPC Python code and some appear to be tool defects (`INTERNALERROR> ValueError: signal only works in main thread`). How remediable are these?

**Comment by soltanmm** [comment]
And if we enable API tracing like we ostensibly should, it'll get even crazier. I'm considering more tooling to filter through debug output...

As for the INTERNALERROR things... [Crap. Crap crap crap crap crap.](https://github.com/Yelp/pip-faster/issues/42#issuecomment-74910985)

**Comment by soltanmm** [comment]
Cleaned up. For an example of output on flaky-timeout and/or an introduced artificial failure (in `test_operation`), see [here](https://grpc-testing.appspot.com/job/gRPC_pull_requests/3555/).

**Comment by nathanielmanistaatgoogle** [comment]
`suite_child_of_mine`: :+1:

Merging as Python is green.

**Pull request merged**
