### PR TITLE
Add missing FLAGS for pecl

### PR DESCRIPTION
**Pull request by axot**
Fix this issue, https://github.com/grpc/grpc/issues/14767

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @axot isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @axot isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by ZhouyihaiDing** [comment]
Thank you!
Can you also run tools/buildgen/generate_projects.sh. It will update config.m4.
Our tests can make sure the new pear package works in different systems.

**Comment by ZhouyihaiDing** [comment]
Sorry for causing you inconvenience. The new commit seems strange.
Only `config.m4.template` and `config.m4` should be changed. Can you rebase to the current master, then change the `config.m4.template` and do `tools/buildgen/generate_projects.sh`.

**Comment by axot** [comment]
Thank you for detail explanation. I did rebase master and then update config.m4.template and config.m4.

**Comment by ZhouyihaiDing** [comment]
Sorry again. Can you please sign the CLA, so the PR will pass the `cla/linuxfoundation` check and then start the tests? 
Thanks!

**Comment by axot** [comment]
@ZhouyihaiDing I think CLA was already signed yesterday. No idea why test did not start.

**Comment by axot** [comment]
Hello @mehrdada, It seems the CI did not start correctly, `cla/linuxfoundation` check was passed, Did I do something wrong?

**Comment by axot** [comment]
Oops, failed by a timeout to pull an image...

> error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/ab/ab47c68ac806a59d07e84e70392d31586da681fe27478c36809e017d897cfeb4/data?Expires=1521737133&Signature=Uk4JbNaSmy6wIf5WIFoQ6-o~MZ9uJgSI83Cb-mI7mCOmdq6qOKxyjYWKzmZsFumrfNSHS-XgIZiB7-IssEiAaByzJOQxc8Jk~sLWCoYQ9yLofATi63cKLp8XgO~ZFJQ2o-PZBSXtMvzdRrkaYLiDELV3U4OT~msidooi-2SNhU0_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.230.80.45:443: i/o timeout

**Comment by axot** [comment]
@ZhouyihaiDing Cloud you review this PR, thank you.

**Comment by ZhouyihaiDing** [comment]
Sorry for the delay. I was trying to fix the test error #14798 in order to make sure the pecl installation works on macOS.
I am starting to verify the speed boost works on different system then this PR is ready to merge. Just to make sure, are you observing the speed boost on Ubuntu? Seems on Debian, there is not much speed boost. I will test it on macOS to make sure there is at least no speed regression there.

**Comment by axot** [comment]
Here is the same warmup test under Debian 9.

## env
```
$ php -v
PHP 7.2.3-1+0~20180306120016.19+stretch~1.gbp81bf3b (cli) (built: Mar  6 2018 12:00:19) ( NTS )

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

$ ls -agh /usr/lib/php/20170718/grpc.so.*
-rwxr-xr-x 1 root 3.6M Mar 24 00:35 /usr/lib/php/20170718/grpc.so.1.10.0.original
-rwxr-xr-x 1 root  16M Mar 24 00:50 /usr/lib/php/20170718/grpc.so.1.10.0.patched
```

## 1.10.0 original
```
php test.php
pid: 3717
GRPC Version: 1.10.0
Warmup: 1,106.190 milliseconds
```

## 1.10.0 with this patch
```
php test.php
pid: 15947
GRPC Version: 1.10.0
Warmup: 802.936 milliseconds
```

So there is 200 ~ 300ms boost with this patch.

**Comment by ZhouyihaiDing** [comment]
Thank you! I write [a simple script](https://github.com/ZhouyihaiDing/grpc/pull/14/files) to test the local QPS. It seems it does improve the performance a lot. Nice job!
Here are some results:

| ping-pong for 30s  | old  | new(this patch)  | 
|---|---|---|
| Debian  | 217627  | 316971  | 
| Mac  | 102620  | 147969  | 
| Ubuntu  | 160890  | 249004  |

Since our dashboard is using the php extension installed by building from the source, you may not observe the performance changes there.

**Comment by axot** [comment]
@ZhouyihaiDing How can I check CLA if it works?

**Pull request merged**
