### PR TITLE
Update Node library dependencies and change deprecated function calls

### PR DESCRIPTION
**Pull request by murgatroid99**
Also fix a couple of minor issues.

### CODE REVIEW

**Comment by apolcyn** [comment]
error with the lodash dependency? Seeing "No compatible version found: lodash@'>=4.15.0 <5.0.0'" in the performance test

**Comment by murgatroid99** [comment]
Jenkins: test this please

**Comment by apolcyn** [comment]
The failure on the sanity tests related to not finding the zip for gmock. 

LGTM.

**Comment by murgatroid99** [comment]
test this please

**Comment by murgatroid99** [comment]
test this please

**Comment by murgatroid99** [comment]
this this please

**Comment by murgatroid99** [comment]
test this please

**Comment by murgatroid99** [comment]
test this please

**Comment by murgatroid99** [comment]
The relevant tests passed. The Windows Node tests are also failing on master, which is a problem, but not the fault of this PR. @apolcyn Can you formally approve this?

**Pull request merged**
