### PR TITLE
Python packages fixes

### PR DESCRIPTION
**Pull request by jtattermusch**
-- Change protoc invocation from `python -m grpc.protoc.compiler` to `python -m grpc.tools.protoc`.

-- fixed docker-on-overlayFS related issue in python distribtests.

### CODE REVIEW

**Comment by jtattermusch** [comment]
@nicolasnoble  FYI

**Comment by jtattermusch** [comment]
Started a build here: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/739/

**Comment by soltanmm** [comment]
lgtm

**Comment by soltanmm** [comment]
[Distrib tests](https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/670/) almost all succeeded on x64. While the docker issue doesn't appear to be entirely fixed, I don't believe that is a blocker on this PR.

**Comment by jtattermusch** [comment]
test failures on mac unrelated.

**Pull request merged**
