### PR TITLE
Delete tests of dead pre-GA code

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
How about we have our test runs complete faster?

### CODE REVIEW

**Comment by kpayson64** [comment]
While we are at it, I think there is a lot more test cruft we can remove.  Here's what I came up with.

src/python/grpcio/tests/unit/_adapter/.gitignore
src/python/grpcio/tests/unit/_adapter/__init__.py
src/python/grpcio/tests/unit/_adapter/_intermediary_low_test.py
src/python/grpcio/tests/unit/_adapter/_low_test.py
src/python/grpcio/tests/unit/_adapter/_proto_scenarios.py
src/python/grpcio/tests/unit/_core_over_links_base_interface_test.py
src/python/grpcio/tests/unit/_crust_over_core_over_links_face_interface_test.py
src/python/grpcio/tests/unit/_junkdrawer/math_pb2.py
src/python/grpcio/tests/unit/_links/__init__.py
src/python/grpcio/tests/unit/_links/_lonely_invocation_link_test.py
src/python/grpcio/tests/unit/_links/_proto_scenarios.py
src/python/grpcio/tests/unit/_links/_transmission_test.py
src/python/grpcio/tests/unit/framework/_crust_over_core_face_interface_test.py
src/python/grpcio/tests/unit/framework/core/__init__.py
src/python/grpcio/tests/unit/framework/core/_base_interface_test.py
src/python/grpcio/tests/unit/framework/foundation/_later_test.py
src/python/grpcio/tests/unit/framework/foundation/stream_testing.py
src/python/grpcio/tests/unit/framework/interfaces/links/__init__.py
src/python/grpcio/tests/unit/framework/interfaces/links/test_cases.py
src/python/grpcio/tests/unit/framework/interfaces/links/test_utilities.py

**Comment by nathanielmanistaatgoogle** [comment]
I agree and intend to do the rest in upcoming commits.

**Comment by kpayson64** [comment]
What is here LGTM.  Any reason we need to split the removal of dead test code across multiple commits?

**Comment by nathanielmanistaatgoogle** [comment]
Habit on my part, perhaps with a simple abundance of caution mixed in?

**Pull request merged**
