### PR TITLE
Remove CleanupThread

### PR DESCRIPTION
**Pull request by kpayson64**
This is no longer needed with the addition of a close() API that allows
clean shutdown.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Does this need to wait until after the resolution of #12531?

**Comment by kpayson64** [comment]
I don't think it needs to be ordered after #12531, but is justified because a resolution to #12531 is coming.

Making these threads daemons should avoid any of the shutdown-hanging issues we saw before introducing CleanupThreads, so there shouldn't be any impact.

**Comment by nathanielmanistaatgoogle** [comment]
Resolve conflicts?

**Comment by kpayson64** [comment]
Fixed

**Pull request merged**
