### PR TITLE
Node: made call credentials properly use UV async events. Also deleted some log lines

### PR DESCRIPTION
**Pull request by murgatroid99**
This fixes an occasional timeout in Node tests.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
```src/node/ext/call_credentials.h modified 2016 but copyright only extends to 2015```

**Comment by murgatroid99** [comment]
Oops, fixed.

**Comment by nicolasnoble** [comment]
The interop tests seem pretty upset about node... https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/2894/

**Comment by murgatroid99** [comment]
OK, it looks like everything passed except for a couple of C tests on Windows. Are those known flakes?

**Pull request merged**
