### PR TITLE
Verify protobuf 3.9.1 with GRPC

### PR DESCRIPTION
**Pull request by anandolee**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @anandolee isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by anandolee** [comment]
I have signed

**Comment by anandolee** [comment]
> Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.
> 
> After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.
> 
> * User @anandolee isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf
> 
> _Regards, CLA GitHub bot_

**Comment by anandolee** [comment]
I have signed

**Comment by jtattermusch** [comment]
Including the PR that bumped to 3.8 for comparison:
https://github.com/grpc/grpc/pull/19182/files

**Comment by anandolee** [comment]
Updated tools/distrib/python/grpcio_tools/protoc_lib_deps.py

**Comment by jtattermusch** [comment]
There are some bazel build issues, e.g.:
```
ERROR: /var/local/git/grpc/src/python/grpcio_reflection/grpc_reflection/v1alpha/BUILD.bazel:17:1: error loading package '@com_google_protobuf//': Unable to find package for @rules_proto//proto:defs.bzl: The repository '@rules_proto' could not be resolved. and referenced by '//src/python/grpcio_reflection/grpc_reflection/v1alpha:grpc_reflection'
ERROR: Analysis of target '//src/python/grpcio_reflection/grpc_reflection/v1alpha:grpc_reflection' failed; build aborted: error loading package '@com_google_protobuf//': Unable to find package for @rules_proto//proto:defs.bzl: The repository '@rules_proto' could not be resolved.
```
@gnossen  might know more.

**Comment by jtattermusch** [comment]
There's also a problem with indentation of dependencies.props  vs dependencies.props.template (they don't match)
```
5c5
<     <GoogleProtobufVersion>3.9.1</GoogleProtobufVersion>
---
>   <GoogleProtobufVersion>3.9.1</GoogleProtobufVersion>
Traceback (most recent call last):
  File "tools/buildgen/generate_projects.py", line 100, in <module>
    assert 0 == os.system('diff %s %s' % (s, g)), s
AssertionError: ./src/csharp/build/dependencies.props
```

**Comment by jtattermusch** [comment]
ObjC podspec  might need to get regenerated too

https://source.cloud.google.com/results/invocations/100cd5ba-81b3-414b-8317-2768d028f64a/targets/github%2Fgrpc%2Fsanity_linux_dbg_native/tests;group=sanity_linux_dbg_native;test=tools%2Fdistrib%2Fcheck_protobuf_pod_version.sh;row=2

**Comment by anandolee** [comment]
Updated dependencies.props.template and ObjC podspec files

**Comment by jtattermusch** [comment]
@rafi-kamal  we haven't finished this one the last time protobuf was released let's finish this off or close?

**Comment by rafi-kamal** [comment]
I talked to @anandolee offline, let's close this issue and focus on integrating 3.10.0 instead.

**Pull request closed without merging**
