### PR TITLE
Bring Cython tests back online

### PR DESCRIPTION
**Pull request by soltanmm**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Looks good; watching the Jenkins run.

**Comment by ctiller** [comment]
Suggest providing a docker image with the correct version of Cython
installed so that anyone can build this.

**Comment by nathanielmanistaatgoogle** [comment]
@ctiller in this pull request or another?

**Comment by ctiller** [comment]
I'd prefer it in this pull request: I'm fairly convinced that maintenance problems previously were due to conflicting Cython versions.

**Comment by nathanielmanistaatgoogle** [comment]
LGTM; @ctiller will you also be taking a look before this is merged?

**Comment by nathanielmanistaatgoogle** [comment]
Test results are absurd; tests restarted.

**Comment by nathanielmanistaatgoogle** [comment]
Please take a look at the Python linux opt test failure? Is there an interesting story of what's going on there?

**Comment by soltanmm** [comment]
Yuck. Build timeout...

**Comment by soltanmm** [comment]
I believe that was just Jenkins tripping over itself, but to reduce the possible headaches I've increased the build time allowance to ten minutes from five. Note that due to the way we're distributing generated code rather than Cython code on PyPI, end-users/devs will never see this extended build time. It may be possible to get around this build time in the future by modifying the Jenkins Docker image and allowing the `build_python` script to detect whether or not there's a system install of Cython at the desired version (as opposed to us always making a fresh install of Cython for our virtualenv).

**Comment by ctiller** [comment]
It's worth noting that you can launch docker instances (on Linux at least)
from the test scripts, if that helps.

**Comment by nathanielmanistaatgoogle** [comment]
Looks like you increased the build timeout for everyone/everything, not just Python. @ctiller, do you consent to that change in this pull request?

**Comment by soltanmm** [comment]
Was informed by @nathanielmanistaatgoogle this could be merged; will wait for a green in the Python tests then do so.

**Comment by nathanielmanistaatgoogle** [comment]
Yeah, still LGTM.

**Pull request merged**
