### PR TITLE
C# protoc plugin: generate *Grpc.cs even if there are no services.

### PR DESCRIPTION
**Pull request by jtattermusch**
Currently, if there are no services defined in a .proto file, a `FooBarGrpc.cs` won't be generated.
That is perhaps cleaner for manual handling of generated files, but it presents a problem for automatic tooling (which has no way of knowing if given .proto file should have generated a `*Grpc.cs` or not).

Context: This has come up in https://github.com/grpc/grpc/pull/13207.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by jtattermusch** [comment]
Btw, C++ and Python already have this behavior, some other languages don't (e.g. Ruby, PHP, Node)

**Comment by jtattermusch** [comment]
CC @kkm000  @jskeet

**Comment by jskeet** [comment]
This feels to me like it should probably be an option rather than a change to the default. With this change, my current build scripts will end up generating far more files, most of which will be empty. I don't think we should be making msbuild work at the expense of existing build scripts.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by kkm000** [comment]
@jtattermusch, @jskeet Since I am writing a task, and using the dependency file from protoc which lists actual generated files, it is easier to handle a situation when a file is not produced (I'll just touch an empty file for dependency check only, and won't include it in compilation). With this approach, this is not a blocking issue.

On the other hand, overall, it is not as easy to handle protoc/gRPC in an automated build because it "too smart" about the files it produces, and their locations. Compare to gcc, for example: it just puts the output file wherever you tell it to (-o), and all other outputs, if any, are also exactly controlled. From my, as a user, point of view, this sometimes tends to violate the Least Surprise Principle, especially given that behavior is so different between C++ and C# generators (not only file naming, but also output paths: in C++ codegen are inferred from the root provided by -I, while the C# codegen puts all into the output directory with no subpaths). To me, the easier a tool to do what you want it to do, the better.

Having said that, there is already an option for the user to control generating gRPC services (you either pass --plugin and friends to protoc or not). From the tool user's standpoint, the fewer corner cases are there, the better. If you compile and empty (of services) input, get an empty output. Maybe print a warning message. So I still think that producing an empty (or a minimal compilable by the target language) file is the right thing to do when there are no services. I think gcc gets it right in this case by producing an output from empty input:
```
$ touch foo.cc
$ gcc -c foo.cc
$ ls -l foo.o
-rw-rw-r-- 1 kkm kkm 944 Nov 24 23:31 foo.o
```
And whichever way you decide at the end, it would still be better if the behavior was consistent across codegens.

**Comment by jskeet** [comment]
> To me, the easier a tool to do what you want it to do, the better.

Sure - but I don't want it to produce files that have no use. I can see how predictability at the expense of tidiness is useful for a Make-based tool, but *I* prefer to end up with only files that will be useful, in the most idiomatic place. That's why the C# plugin also lets you specify the `base_namespace` - it *doesn't* always just put all the output files in a single directory; if you specify a `base_namespace` option, it will treat the specified output directory as the directory representing that namespace, and create subdirectories from there. We can't really infer what that base namespace should be from other options, and in many cases just specifying a flat output directory is simpler anyway.

> From my, as a user, point of view, this sometimes tends to violate the Least Surprise Principle

Whereas to me, if an update from 1.7.x to 1.8.x suddenly started creating one C# file per proto regardless of services when it didn't before, *that* would be a *huge* violation of the principle of least surprise.

> I think gcc gets it right in this case by producing an output from empty input

The output of gcc is transient though. That's the big difference here. It doesn't matter if you produce a few more .o files than you need - no-one's ever going to look at them. For protos, I take a different approach, checking the C# files into source control. That makes it easier for debugging purposes, as well as anyone wanting to look at what the source code was at a particular revision. It also makes it easier to compare changes due to proto or generator changes. Now obviously you're coming at it from a different perspective, wanting to treat the generated C# code as transient - but I'd like you to bear in mind that that's not the only perspective.

**Comment by kkm000** [comment]
Sure, although it is certain that your perspective, as the tool's developer, is very different. I would not be at all surprised if gcc developers were looking at .o files all the time. or kept them somehow versioned for regression tests. They are Greek to me though. It would not probably far off the bat to say that most of the rest of the world would never look at the generated files. I used to check them in; that was only a mess in the source control history. When I finally scripted the build to keep them as transient, that was a big relief.

So, to me as the user of the tool it only creates hurdles, and as a writer of make, msbuild or any type of  scripts doubly so. I am just trying to convey a perspective from the other side.

**Comment by jskeet** [comment]
> Sure, although it is certain that your perspective, as the tool's developer, is very different.

But that's not what I do for most of my job. I'm not in the protobuf team - I wrote the generator a while ago and still help out occasionally. But day to day, I work on projects that *use* protobuf all the time. I spend far more time as a user than as a tool developer on that front.

What I've proposed is that it's an option so that it's still entirely feasible for your new use case to work as you want it, but without disrupting everyone that expects a minor version change to only have minimal codegen changes.

**Comment by kkm000** [comment]
I see. It seems I underestimate certain use cases.

As far as C# build integration goes, it currently looks like I can work with the tool as is. Adding the option would solve only one problem of at least two. So this issue is not blocking, assuming MSBuild task.

**Comment by jtattermusch** [comment]
Closing this based on the above discussion. We can reopen later if needed.

**Comment by kkm000** [comment]
@jtattermusch Thanks, I believe this is correct. My understanding we pretty much decided on leaving the codegen as it.

I am working on the task and scripts, time allowing. I'll need your help locating C++ plugin binaries in the build tree for packaging.

**Pull request closed without merging**
