### PR TITLE
Throw exception if not lower case Metadata.Entry.Key.

### PR DESCRIPTION
**Pull request by dalebrubaker**
Currently the user is allowed to add an upper-case key, then an exception is thrown server-side if he tries to find it as uppercase, e.g. with             
var value = context.RequestHeaders.FirstOrDefault((entry) => entry.Key == "ABC").Value;

It seems better to fail early, client-side, when the key is first created.

BTW, the exception thrown is "Cannot access string value of a binary metadata entry", which doesn't help much.

### CODE REVIEW

**Comment by dalebrubaker** [comment]
Did I do something wrong with this pull request? The fix is minor, and of course you are welcome to reject it. Thanks.

**Comment by jtattermusch** [comment]
Hey, thanks for your pull request.

Problems:
-- HTTP2 only allows lowercase metadata keys
-- HTTP1 allows uppercase characters as well.
-- Some libraries (like the auth library we are using) generate the HTTP1 style headers and we need to support that.

To comply with the HTTP2 spec (which is the protocol that gRPC is is using internally), please use only lowercase metadata headers.

**Comment by jtattermusch** [comment]
I don't think i'll be accept the change unfortunately for the reasons described above.  

Btw, the reason you are getting the exception "Cannot access string value of a binary metadata entry". Is that you are using FirstOrDefault and the entry doesn't exist, so you get a default instance of Metadata.Entry (which is a struct)   that happens to throw the exception you are describing.

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/issues/6713

**Pull request closed without merging**
