### PR TITLE
Removes unused SIGNAL_CHECK_PERIOD constant

### PR DESCRIPTION
**Pull request by Parad0X**
Code that was using this constant is long gone.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @Parad0X isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by Parad0X** [comment]
CLA

**Comment by Parad0X** [comment]
cla

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,792      Total (=)      1,964,792

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,887,069      Total (<)     10,887,070

 No significant differences in binary sizes


```

**Comment by vjpai** [comment]
@apolcyn : can you review if this is still relevant?

**Comment by apolcyn** [comment]
cc @stanley-cheung can you please give this a second review?

**Pull request closed without merging**
