### PR TITLE
Cleanup: remove Jenkins references from build_packages scripts

### PR DESCRIPTION
**Pull request by jtattermusch**
- Jenkins has been shutdown several month ago, we no longer need the code for handling jenkins paths in build_packages

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by jtattermusch** [comment]
@mehrdada  we delete quite a few Jenkins scripts in the past. We can do more cleanup if you know about some scripts that are no longer useful.

**Comment by mehrdada** [comment]
Ha, I did not realize they were already gone. :)
Cool.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,654      Total (=)      1,976,654

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,775,731      Total (>)     10,775,730

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/16203

**Pull request merged**
