### PR TITLE
Build Python distributions for Python 3

### PR DESCRIPTION
**Pull request by soltanmm**
Don't wanna do it manually, I guess.

Build to follow: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/1276/

### CODE REVIEW

**Comment by kpayson64** [comment]
Looks like we both had the same idea:
https://github.com/kpayson64/grpc/tree/python_3_artifacts
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/1278/

I'll let you finish this one.

**Comment by soltanmm** [comment]
Aye 'kay. Quick note: there're some weird missing symbol issues with 64-bit Python 3 builds on Windows (I can't even see the symbols in the official `.lib` files through `nm` via MSYS2). So, this PR might go some weird last-minute places over the weekend. Did not expect this class of problems to still be relevant...

**Comment by soltanmm** [comment]
Quick note to myself so I don't forget while I pore over Py3 linkage: because we're not using a proper build system `make_grpcio_tools.py` needs to become a `pre_build_step` else one build might trash the other nondeterministically.

**Comment by soltanmm** [comment]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/1299/

**Comment by soltanmm** [comment]
n.b. #7424 will be needed to correct the Python 3 distribution tags for Mac OS X (bringing the `10.6`s up to `10.7` and `10.9` for `grpcio` and `grpcio-tools` respectively).

**Comment by soltanmm** [comment]
cc #7423

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum, though there's a lot going on here. If possible please wait for @kpayson64 to also review.

**Comment by soltanmm** [comment]
Quick explanation: long-paths handling is done otherwise Windows refuses to move files around on our artifact builders (chucking `WindowsError`s left and right on `os.rename`). Changing the directory when building `grpcio-tools` *may* be unnecessary, but doesn't hurt.  The `spawn` patch was cherry-picked because... of reasons that *may* no longer be valid, but, hey, why leave it off until `1.1` when one can have it in `1.0`. `distutils` command idiosyncracies in the spawn patch was just to correct detection of `ccache xyz` when it's specified as a single string (not that `ccache` works well on Windows MinGW *anyway*, but, y'know, we try...). Normalizing path separators is a weird one because I'd expect Python on Windows to handle all path normalization correctly but then I ended up seeing include directories being passed to `gcc.exe` in both Unix and Windows style (so, Python wasn't normalizing) and that just made me feel uncomfortable. Using whack-a-mole against the filesystem was to ensure that multiple simultaneous invocations of `make_grpcio_tools.py` (which cannot be avoided by our build system without either joining Python 2 and Python 3 targets at the hip or adding a new kind of build step) don't interact negatively among themselves or with other tasks involving the copied source files.

**Comment by nathanielmanistaatgoogle** [comment]
Okay! :-)

**Comment by kpayson64** [comment]
LGTM

**Comment by soltanmm** [comment]
@kpayson64 re edit: aye, noted.

**Comment by soltanmm** [comment]
Kicking portability tests after some manual clean-up...

> ```
Total Disk Space Available is: 0Gb
 Node Name: grpc-jenkins-linux1
```

**Comment by soltanmm** [comment]
All checks are green! Quick, we must merge before a sudden catastrophic failure of the electroweak force!

**Pull request merged**
