### PR TITLE
Fix internal BUILD

### PR DESCRIPTION
**Pull request by ncteisen**
Needed for internal build check

### CODE REVIEW

**Comment by AspirinSJL** [comment]
Logically LGTM. 

But the tests are failing.

**Comment by ncteisen** [comment]
Looks like the annotation will not work with legacy build stuff. Can we swtich the targets back to libraries? Or are they needed elsewhere as binaries

**Comment by ncteisen** [comment]
All failures are infra. Merging to unblock import

**Comment by AspirinSJL** [comment]
Actually I am not the author of the OSS memory test. But I think changing the targets to libraries is OK.

**Pull request merged**
