### PR TITLE
Expose interop tests and add --tls_key_file flag for interop_server

### PR DESCRIPTION
**Pull request by qiwzhang**
[ESP](https://github.com/cloudendpoints/esp) was using grpc-go interop tests for its e2e tests and stress tests.  ESP is c++ code using bazel,  the mixing of go with bazel causes a lot of troubles.  Beside, it has to use a very old grpc-go version result in very difficult to upgrade bazel.

In order for ESP to use grpc-cpp interop, folllowing changes are needed:
* change test/cpp/interop default package visibility to public 
* export some more proto files in src/proto/grpc/testing
* build metrics_client 
* add two flags --tls_cert_file and --tls_key_file flags (just like golang interop_server) to provide custom cert for interop_server.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @qiwzhang isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by qiwzhang** [comment]
Signed it

**Comment by qiwzhang** [comment]
@zhangkun83 could you help to review it?

**Comment by zhangkun83** [comment]
@yang-g, could you take a look or find the proper reviewer?

**Comment by yang-g** [comment]
LGTM
Please format the code according to:
```
+ tools/dockerfile/grpc_clang_format/clang_format_all_the_things.sh
--- /var/local/git/grpc/test/cpp/util/test_credentials_provider.cc	2019-05-28 22:13:42.175595702 +0000
+++ /tmp/tmp.z9CzSaQBnP	2019-05-28 22:15:53.343595702 +0000
@@ -119,8 +119,8 @@
       SslServerCredentialsOptions ssl_opts;
       ssl_opts.pem_root_certs = "";
       if (!custom_server_key_.empty() && !custom_server_cert_.empty()) {
-        SslServerCredentialsOptions::PemKeyCertPair pkcp = {custom_server_key_,
-                                                            custom_server_cert_};
+        SslServerCredentialsOptions::PemKeyCertPair pkcp = {
+            custom_server_key_, custom_server_cert_};
         ssl_opts.pem_key_cert_pairs.push_back(pkcp);
       } else {
         SslServerCredentialsOptions::PemKeyCertPair pkcp = {test_server1_key,
```

**Comment by qiwzhang** [comment]
Thanks for the review.  Fixed the format.

**Pull request merged**
