### PR TITLE
Fake resolver: Added ability to specify response upon error

### PR DESCRIPTION
**Pull request by dgquintas**
Extracted from @AspirinSJL 's PR https://github.com/grpc/grpc/pull/13671

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.0%    +296 [None]                                                             +1.94Ki  +0.0%
   +24%    +288 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +288   +24%
      [NEW]    +142 grpc_fake_resolver_response_generator_set_response_upon_error         +142  [NEW]
       +41%     +56 grpc_fake_resolver_response_generator_set_response                     +56   +41%
       +90%     +46 fake_resolver_channel_saw_error_locked                                 +46   +90%
       +15%     +16 fake_resolver_maybe_finish_next_locked                                 +16   +15%
      +6.4%     +14 [Unmapped]                                                             +14  +6.4%
       +22%      +9 fake_resolver_destroy                                                   +9   +22%
      +5.6%      +5 set_response_closure_fn                                                 +5  +5.6%

  +0.0%    +584 TOTAL                                                              +2.22Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by markdroth** [comment]
Note that there's still one comment I made about this code in Juanli's PR that has not yet been addressed:

https://reviewable.io/reviews/grpc/grpc/13671#-L2LUfU7kxszaytAWLDf:-L2_v-dt1HELOshckWWJ:bprregw

I'd like to see that addressed before this gets merged.

**Comment by AspirinSJL** [comment]
This reminds me that I still have one more change to apply to the fake_resolver. Will finish it soon.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by AspirinSJL** [comment]
#13671 has been updated. @dgquintas Do you want to sync the change on your side or let me open a new PR?

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
You can create a new PR, that way you can rightly take the credit too :)

**Comment by dgquintas** [comment]
Closing, @AspirinSJL will create a separate one.

**Pull request closed without merging**
