### PR TITLE
typo: probobuf -> protobuf

### PR DESCRIPTION
**Pull request by boivie**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @boivie isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jtattermusch** [comment]
@boivie , please sign the CLA, otherwise I cannot merge your contribution.

**Comment by jtattermusch** [comment]
@boivie, please ignore my comment, the bot just picked up.

**Comment by y-zeng** [comment]
Thanks for the fix!

**Pull request merged**
