### PR TITLE
add a python test that tests both the C-core and python bindings changes for server SSL credentials reload

### PR DESCRIPTION
**Pull request by cauthu**
depends on PR #12689

can be run like:
```
tools/run_tests/run_tests.py -l python [--compiler python2.7] \
    --force_default_poller -r ServerSSLCredentialsReloadTest
```

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by cauthu** [comment]
@justinburke @nathanielmanistaatgoogle the test

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by cauthu** [comment]
closing... will include the test along with the feature change in PR #12689

**Pull request closed without merging**
