### PR TITLE
Channelz Part 6: Basic Socket Support

### PR DESCRIPTION
**Pull request by ncteisen**
Minimal socket support

Tracking bug: #15340

Coming in future changes: Address, Security, flow control windows

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/16649)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.2% +1.63Ki [None]                                                             +11.2Ki  +0.1%
      +0.2% +1.62Ki [Unmapped]                                                         +11.1Ki  +0.1%
      [NEW]     +40 vtable for grpc_core::channelz::SocketNode                             +40  [NEW]
   +65%   +1000 src/core/lib/channel/channelz.cc                                     +1000   +65%
      [NEW]    +726 grpc_core::channelz::SocketNode::RenderJson                           +726  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageSent                     +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageRecieved                 +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromLocal          +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromRemote         +40  [NEW]
       +30%     +35 [Unmapped]                                                             +35   +30%
       +17%     +32 grpc_core::channelz::CallCountingHelper::PopulateCallCounts            +32   +17%
      [NEW]     +28 grpc_core::channelz::SocketNode::~SocketNode                           +28  [NEW]
      [NEW]     +19 grpc_core::channelz::SocketNode::~SocketNode                           +19  [NEW]
  +1.2%    +368 src/core/ext/transport/chttp2/transport/chttp2_transport.cc           +368  +1.2%
      +6.3%    +215 grpc_create_chttp2_transport                                          +215  +6.3%
      +7.2%     +64 destroy_stream_locked                                                  +64  +7.2%
      +2.1%     +64 perform_stream_op_locked                                               +64  +2.1%
       +23%     +18 start_keepalive_ping_locked                                            +18   +23%
      +1.0%      +7 [Unmapped]                                                              +7  +1.0%
  +6.0%    +144 src/core/lib/channel/channelz_registry.cc                             +144  +6.0%
      [NEW]    +130 grpc_channelz_get_socket                                              +130  [NEW]
       +10%     +14 [Unmapped]                                                             +14   +10%
  +0.6%     +48 src/core/ext/transport/chttp2/transport/parsing.cc                     +48  +0.6%
      +3.7%     +47 init_header_frame_parser                                               +47  +3.7%
      +1.3%      +1 [Unmapped]                                                              +1  +1.3%
  +0.3%     +16 src/core/ext/transport/chttp2/transport/writing.cc                     +16  +0.3%
      +0.3%     +16 grpc_chttp2_begin_write                                                +16  +0.3%

  +0.2% +3.17Ki TOTAL                                                              +12.7Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -24  -0.0%

  [ = ]       0 TOTAL      -24  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.2% +1.63Ki [None]                                                             +11.2Ki  +0.1%
      +0.2% +1.62Ki [Unmapped]                                                         +11.1Ki  +0.1%
      [NEW]     +40 vtable for grpc_core::channelz::SocketNode                             +40  [NEW]
   +65%   +1000 src/core/lib/channel/channelz.cc                                     +1000   +65%
      [NEW]    +726 grpc_core::channelz::SocketNode::RenderJson                           +726  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageSent                     +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageRecieved                 +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromLocal          +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromRemote         +40  [NEW]
       +30%     +35 [Unmapped]                                                             +35   +30%
       +17%     +32 grpc_core::channelz::CallCountingHelper::PopulateCallCounts            +32   +17%
      [NEW]     +28 grpc_core::channelz::SocketNode::~SocketNode                           +28  [NEW]
      [NEW]     +19 grpc_core::channelz::SocketNode::~SocketNode                           +19  [NEW]
  +1.2%    +368 src/core/ext/transport/chttp2/transport/chttp2_transport.cc           +368  +1.2%
      +6.3%    +215 grpc_create_chttp2_transport                                          +215  +6.3%
      +7.2%     +64 destroy_stream_locked                                                  +64  +7.2%
      +2.1%     +64 perform_stream_op_locked                                               +64  +2.1%
       +23%     +18 start_keepalive_ping_locked                                            +18   +23%
      +1.0%      +7 [Unmapped]                                                              +7  +1.0%
  +6.0%    +144 src/core/lib/channel/channelz_registry.cc                             +144  +6.0%
      [NEW]    +130 grpc_channelz_get_socket                                              +130  [NEW]
       +10%     +14 [Unmapped]                                                             +14   +10%
  +0.6%     +48 src/core/ext/transport/chttp2/transport/parsing.cc                     +48  +0.6%
      +3.7%     +47 init_header_frame_parser                                               +47  +3.7%
      +1.3%      +1 [Unmapped]                                                              +1  +1.3%
  +0.3%     +16 src/core/ext/transport/chttp2/transport/writing.cc                     +16  +0.3%
      +0.3%     +16 grpc_chttp2_begin_write                                                +16  +0.3%

  +0.2% +3.17Ki TOTAL                                                              +12.7Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -24  -0.0%

  [ = ]       0 TOTAL      -24  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.3% +1.97Ki [None]                                                                               +30.7Ki  +0.3%
      +0.3% +1.93Ki [Unmapped]                                                                           +30.6Ki  +0.3%
      [NEW]     +40 vtable for grpc_core::channelz::SocketNode                                               +40  [NEW]
   +71% +1.06Ki src/core/lib/channel/channelz.cc                                                     +1.06Ki   +71%
      [NEW]    +683 grpc_core::channelz::SocketNode::RenderJson                                             +683  [NEW]
      [NEW]    +118 grpc_core::channelz::SocketNode::SocketNode                                             +118  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::RecordMessagesSent                                      +41  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::~SocketNode                                             +41  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageReceived                                   +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromLocal                            +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromRemote                           +40  [NEW]
       +34%     +39 [Unmapped]                                                                               +39   +34%
       +17%     +32 grpc_core::channelz::CallCountingHelper::PopulateCallCounts                              +32   +17%
      [NEW]     +14 grpc_core::channelz::SocketNode::~SocketNode                                             +14  [NEW]
  +0.7%    +224 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +224  +0.7%
      +2.9%     +98 grpc_create_chttp2_transport                                                             +98  +2.9%
      +7.2%     +64 destroy_stream_locked                                                                    +64  +7.2%
      +1.0%     +32 perform_stream_op_locked                                                                 +32  +1.0%
       +23%     +18 start_keepalive_ping_locked                                                              +18   +23%
      +1.8%     +12 [Unmapped]                                                                               +12  +1.8%
  +6.0%    +144 src/core/lib/channel/channelz_registry.cc                                               +144  +6.0%
      [NEW]    +130 grpc_channelz_get_socket                                                                +130  [NEW]
       +10%     +14 [Unmapped]                                                                               +14   +10%
  +1.9%     +64 src/core/ext/transport/chttp2/transport/frame_data.cc                                    +64  +1.9%
      +3.0%     +64 grpc_deframe_unprocessed_incoming_frames                                                 +64  +3.0%
      +3.7%      +8 grpc_chttp2_data_parser_begin_frame                                                       +8  +3.7%
  +0.6%     +48 src/core/ext/transport/chttp2/transport/parsing.cc                                       +48  +0.6%
      +3.7%     +47 init_header_frame_parser                                                                 +47  +3.7%
      +1.2%      +1 [Unmapped]                                                                                +1  +1.2%
  +0.8%     +48 src/core/ext/transport/chttp2/transport/writing.cc                                       +48  +0.8%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +16%     +32 grpc_chttp2_end_write                                                                    +32   +16%
      +0.3%     +16 grpc_chttp2_begin_write                                                                  +16  +0.3%

  +0.2% +3.55Ki TOTAL                                                                                +32.2Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.3% +1.97Ki [None]                                                                               +30.7Ki  +0.3%
      +0.3% +1.93Ki [Unmapped]                                                                           +30.6Ki  +0.3%
      [NEW]     +40 vtable for grpc_core::channelz::SocketNode                                               +40  [NEW]
   +71% +1.06Ki src/core/lib/channel/channelz.cc                                                     +1.06Ki   +71%
      [NEW]    +683 grpc_core::channelz::SocketNode::RenderJson                                             +683  [NEW]
      [NEW]    +118 grpc_core::channelz::SocketNode::SocketNode                                             +118  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::RecordMessagesSent                                      +41  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::~SocketNode                                             +41  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageReceived                                   +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromLocal                            +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromRemote                           +40  [NEW]
       +34%     +39 [Unmapped]                                                                               +39   +34%
       +17%     +32 grpc_core::channelz::CallCountingHelper::PopulateCallCounts                              +32   +17%
      [NEW]     +14 grpc_core::channelz::SocketNode::~SocketNode                                             +14  [NEW]
  +0.7%    +224 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +224  +0.7%
      +2.9%     +98 grpc_create_chttp2_transport                                                             +98  +2.9%
      +7.2%     +64 destroy_stream_locked                                                                    +64  +7.2%
      +1.0%     +32 perform_stream_op_locked                                                                 +32  +1.0%
       +23%     +18 start_keepalive_ping_locked                                                              +18   +23%
      +1.8%     +12 [Unmapped]                                                                               +12  +1.8%
  +6.0%    +144 src/core/lib/channel/channelz_registry.cc                                               +144  +6.0%
      [NEW]    +130 grpc_channelz_get_socket                                                                +130  [NEW]
       +10%     +14 [Unmapped]                                                                               +14   +10%
  +1.9%     +64 src/core/ext/transport/chttp2/transport/frame_data.cc                                    +64  +1.9%
      +3.0%     +64 grpc_deframe_unprocessed_incoming_frames                                                 +64  +3.0%
      +3.7%      +8 grpc_chttp2_data_parser_begin_frame                                                       +8  +3.7%
  +0.6%     +48 src/core/ext/transport/chttp2/transport/parsing.cc                                       +48  +0.6%
      +3.7%     +47 init_header_frame_parser                                                                 +47  +3.7%
      +1.2%      +1 [Unmapped]                                                                                +1  +1.2%
  +0.8%     +48 src/core/ext/transport/chttp2/transport/writing.cc                                       +48  +0.8%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +16%     +32 grpc_chttp2_end_write                                                                    +32   +16%
      +0.3%     +16 grpc_chttp2_begin_write                                                                  +16  +0.3%

  +0.2% +3.55Ki TOTAL                                                                                +32.2Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   678,820       Core (>)        676,945

 1,964,595      Total (>)      1,962,660

***************FRAMEWORKS****************
  New size                      Old size
 3,681,286       Core (>)      3,678,182

10,886,805      Total (>)     10,883,700


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.3% +1.97Ki [None]                                                                               +31.2Ki  +0.3%
      +0.3% +1.93Ki [Unmapped]                                                                           +31.2Ki  +0.3%
      [NEW]     +40 vtable for grpc_core::channelz::SocketNode                                               +40  [NEW]
   +71% +1.06Ki src/core/lib/channel/channelz.cc                                                     +1.06Ki   +71%
      [NEW]    +683 grpc_core::channelz::SocketNode::RenderJson                                             +683  [NEW]
      [NEW]    +118 grpc_core::channelz::SocketNode::SocketNode                                             +118  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::RecordMessagesSent                                      +41  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::~SocketNode                                             +41  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageReceived                                   +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromLocal                            +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromRemote                           +40  [NEW]
       +34%     +39 [Unmapped]                                                                               +39   +34%
       +17%     +32 grpc_core::channelz::CallCountingHelper::PopulateCallCounts                              +32   +17%
      [NEW]     +14 grpc_core::channelz::SocketNode::~SocketNode                                             +14  [NEW]
  +0.9%    +288 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +288  +0.9%
      +2.9%     +98 grpc_create_chttp2_transport                                                             +98  +2.9%
       +11%     +64 grpc_chttp2_unref_transport                                                              +64   +11%
      +7.2%     +64 destroy_stream_locked                                                                    +64  +7.2%
      +1.0%     +32 perform_stream_op_locked                                                                 +32  +1.0%
       +23%     +18 start_keepalive_ping_locked                                                              +18   +23%
      +1.8%     +12 [Unmapped]                                                                               +12  +1.8%
  +6.0%    +144 src/core/lib/channel/channelz_registry.cc                                               +144  +6.0%
      [NEW]    +130 grpc_channelz_get_socket                                                                +130  [NEW]
       +10%     +14 [Unmapped]                                                                               +14   +10%
  +1.9%     +64 src/core/ext/transport/chttp2/transport/frame_data.cc                                    +64  +1.9%
      +3.0%     +64 grpc_deframe_unprocessed_incoming_frames                                                 +64  +3.0%
      +3.7%      +8 grpc_chttp2_data_parser_begin_frame                                                       +8  +3.7%
  +0.6%     +48 src/core/ext/transport/chttp2/transport/parsing.cc                                       +48  +0.6%
      +3.7%     +47 init_header_frame_parser                                                                 +47  +3.7%
      +1.2%      +1 [Unmapped]                                                                                +1  +1.2%
  +0.8%     +48 src/core/ext/transport/chttp2/transport/writing.cc                                       +48  +0.8%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +16%     +32 grpc_chttp2_end_write                                                                    +32   +16%
      +0.3%     +16 grpc_chttp2_begin_write                                                                  +16  +0.3%

  +0.2% +3.61Ki TOTAL                                                                                +32.8Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   678,848       Core (>)        676,957

 1,964,623      Total (>)      1,962,672

***************FRAMEWORKS****************
  New size                      Old size
 3,681,286       Core (>)      3,678,182

10,886,803      Total (>)     10,883,699


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.3% +1.94Ki [None]                                                                               +31.1Ki  +0.3%
      +0.3% +1.90Ki [Unmapped]                                                                           +31.1Ki  +0.3%
      [NEW]     +40 vtable for grpc_core::channelz::SocketNode                                               +40  [NEW]
   +68% +1.02Ki src/core/lib/channel/channelz.cc                                                     +1.02Ki   +68%
      [NEW]    +638 grpc_core::channelz::SocketNode::RenderJson                                             +638  [NEW]
      [NEW]    +118 grpc_core::channelz::SocketNode::SocketNode                                             +118  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::RecordMessagesSent                                      +41  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::~SocketNode                                             +41  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageReceived                                   +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromLocal                            +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromRemote                           +40  [NEW]
       +31%     +36 [Unmapped]                                                                               +36   +31%
       +17%     +32 grpc_core::channelz::CallCountingHelper::PopulateCallCounts                              +32   +17%
      [NEW]     +14 grpc_core::channelz::SocketNode::~SocketNode                                             +14  [NEW]
  +0.9%    +288 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +288  +0.9%
      +2.9%     +98 grpc_create_chttp2_transport                                                             +98  +2.9%
       +11%     +64 grpc_chttp2_unref_transport                                                              +64   +11%
      +7.2%     +64 destroy_stream_locked                                                                    +64  +7.2%
      +1.0%     +32 perform_stream_op_locked                                                                 +32  +1.0%
       +23%     +18 start_keepalive_ping_locked                                                              +18   +23%
      +1.8%     +12 [Unmapped]                                                                               +12  +1.8%
  +6.0%    +144 src/core/lib/channel/channelz_registry.cc                                               +144  +6.0%
      [NEW]    +130 grpc_channelz_get_socket                                                                +130  [NEW]
       +10%     +14 [Unmapped]                                                                               +14   +10%
  +1.9%     +64 src/core/ext/transport/chttp2/transport/frame_data.cc                                    +64  +1.9%
      +3.0%     +64 grpc_deframe_unprocessed_incoming_frames                                                 +64  +3.0%
      +3.7%      +8 grpc_chttp2_data_parser_begin_frame                                                       +8  +3.7%
  +0.6%     +48 src/core/ext/transport/chttp2/transport/parsing.cc                                       +48  +0.6%
      +3.7%     +47 init_header_frame_parser                                                                 +47  +3.7%
      +1.2%      +1 [Unmapped]                                                                                +1  +1.2%
  +0.8%     +48 src/core/ext/transport/chttp2/transport/writing.cc                                       +48  +0.8%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +16%     +32 grpc_chttp2_end_write                                                                    +32   +16%
      +0.3%     +16 grpc_chttp2_begin_write                                                                  +16  +0.3%

  +0.2% +3.53Ki TOTAL                                                                                +32.7Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.3% +1.94Ki [None]                                                                               +31.1Ki  +0.3%
      +0.3% +1.90Ki [Unmapped]                                                                           +31.1Ki  +0.3%
      [NEW]     +40 vtable for grpc_core::channelz::SocketNode                                               +40  [NEW]
   +68% +1.02Ki src/core/lib/channel/channelz.cc                                                     +1.02Ki   +68%
      [NEW]    +638 grpc_core::channelz::SocketNode::RenderJson                                             +638  [NEW]
      [NEW]    +118 grpc_core::channelz::SocketNode::SocketNode                                             +118  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::RecordMessagesSent                                      +41  [NEW]
      [NEW]     +41 grpc_core::channelz::SocketNode::~SocketNode                                             +41  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordMessageReceived                                   +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromLocal                            +40  [NEW]
      [NEW]     +40 grpc_core::channelz::SocketNode::RecordStreamStartedFromRemote                           +40  [NEW]
       +31%     +36 [Unmapped]                                                                               +36   +31%
       +17%     +32 grpc_core::channelz::CallCountingHelper::PopulateCallCounts                              +32   +17%
      [NEW]     +14 grpc_core::channelz::SocketNode::~SocketNode                                             +14  [NEW]
  +0.9%    +288 src/core/ext/transport/chttp2/transport/chttp2_transport.cc                             +288  +0.9%
      +2.9%     +98 grpc_create_chttp2_transport                                                             +98  +2.9%
       +11%     +64 grpc_chttp2_unref_transport                                                              +64   +11%
      +7.2%     +64 destroy_stream_locked                                                                    +64  +7.2%
      +1.0%     +32 perform_stream_op_locked                                                                 +32  +1.0%
       +23%     +18 start_keepalive_ping_locked                                                              +18   +23%
      +1.8%     +12 [Unmapped]                                                                               +12  +1.8%
  +6.0%    +144 src/core/lib/channel/channelz_registry.cc                                               +144  +6.0%
      [NEW]    +130 grpc_channelz_get_socket                                                                +130  [NEW]
       +10%     +14 [Unmapped]                                                                               +14   +10%
  +1.9%     +64 src/core/ext/transport/chttp2/transport/frame_data.cc                                    +64  +1.9%
      +3.0%     +64 grpc_deframe_unprocessed_incoming_frames                                                 +64  +3.0%
      +3.7%      +8 grpc_chttp2_data_parser_begin_frame                                                       +8  +3.7%
  +0.6%     +48 src/core/ext/transport/chttp2/transport/parsing.cc                                       +48  +0.6%
      +3.7%     +47 init_header_frame_parser                                                                 +47  +3.7%
      +1.2%      +1 [Unmapped]                                                                                +1  +1.2%
  +0.8%     +48 src/core/ext/transport/chttp2/transport/writing.cc                                       +48  +0.8%
      [NEW]    +117 report_stall(grpc_chttp2_transport*, grpc_chttp2_stream*, char const*) [clone .part.    +117  [NEW]
       +16%     +32 grpc_chttp2_end_write                                                                    +32   +16%
      +0.3%     +16 grpc_chttp2_begin_write                                                                  +16  +0.3%

  +0.2% +3.53Ki TOTAL                                                                                +32.7Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   678,840       Core (>)        676,957

 1,964,615      Total (>)      1,962,672

***************FRAMEWORKS****************
  New size                      Old size
 3,681,286       Core (>)      3,678,182

10,886,805      Total (>)     10,883,708


```

**Comment by ncteisen** [comment]
Failures: #16692

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
