### PR TITLE
Fix grpc_byte_buffer_copy to copy compression algorithm

### PR DESCRIPTION
**Pull request by lizan**

### CODE REVIEW

**Comment by lizan** [comment]
Ping.

**Comment by dgquintas** [comment]
LGTM. Nice catch, @lizan

**Comment by dgquintas** [comment]
jenkins test this please

**Comment by dgquintas** [comment]
@lizan can you please run clang-format over your changes? The test that verifies code changes are formatted with clang-format 3.6 is failing. Alternatively I can replicate your PR myself, let me know.

**Comment by lizan** [comment]
@dgquintas Done

**Pull request merged**
