### PR TITLE
Minor fix on example script

### PR DESCRIPTION
**Pull request by tamihiro**

### CODE REVIEW

**Comment by tamihiro** [comment]
I've signed a CLA!

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the fix! Please squash commits and conform to [these guidelines](http://chris.beams.io/posts/git-commit/#seven-rules) with your commit log message.

**Comment by nathanielmanistaatgoogle** [comment]
This looks good! Thank you for the contribution.

We're having a code freeze this week to address issues with our testing but I intend to merge this in its current form after the freeze is lifted.

**Comment by jtattermusch** [comment]
no merge with failed tests.

**Comment by jtattermusch** [comment]
this is ok to test

**Comment by nathanielmanistaatgoogle** [comment]
Apologies for asking for extra work in such a simple change, but... this needs conflict resolution. I'm not quite sure I see how or why, but it does.

**Comment by jtattermusch** [comment]
test this please

**Comment by nathanielmanistaatgoogle** [comment]
This is okay to test.

**Pull request merged**
