### PR TITLE
Check Python ByteBuffer reader init status

### LINKED ISSUE #7205: Check the return value of grpc_byte_buffer_reader_init
as part of `class ByteBuffer` in records.pyx.pxi

`grpc_byte_buffer_reader_init` returns status since #7190.

### PR DESCRIPTION
**Pull request by soltanmm**
Fixes #7205

### CODE REVIEW

**Comment by soltanmm** [comment]
Also obvs depends on #7190.

**Comment by soltanmm** [comment]
@dgquintas If you flip whatever bits you didn't set to disallow PRs against your branches on GitHub, I can just put this against your `bb_reader_error` branch instead. 😄

**Comment by dgquintas** [comment]
I'd the happy to do so... if I knew how. I looked around and I don't see
where that switch is :?

**Comment by dgquintas** [comment]
Nevermind, I've manually merged it into #7190. See https://github.com/grpc/grpc/pull/7190/commits/fce332a4c46435537487fb1609b381bb8ea6e585

Thanks!

**Pull request closed without merging**
