### PR TITLE
sockaddr resolver: skip empty addresses in target URI

### PR DESCRIPTION
**Pull request by Vignesh2208**
Fixes b/212831051 which was caused due to repeated channel_args copying instigated by a grpc_channel_check_connectivity_state api call after creation of a channel containing a large number of targets in a Unix URI

@ctiller

### CODE REVIEW

**Comment by markdroth** [comment]
I'm not sure this fix actually makes sense.  There's no limit on the number of addresses that can be returned by any resolver, so putting a limit in the sockaddr resolver doesn't prevent any other resolver from returning a huge number of addresses.

If the amount of memory used for a large number of addresses is a problem, then maybe we should find ways to reduce the memory usage instead of imposing arbitrary limits.

Also, note that this problem doesn't really have anything specifically to do with `grpc_channel_check_connectivity_state()`; that call can trigger the channel to start trying to connect, but so can just sending an RPC on the channel.

**Comment by Vignesh2208** [comment]
> 

I see, makes sense. The problem is due to copying of channel args for each target specified in a comma separated "target uri" string provided to the channel at channel construction time. If the target uri string is very long as is the case here, then its leading to OOMs (since this string is copied for each target address) when the channel starts to connect. 

In this particular case, the issue goes away if we just prune addresses which are empty (target uri is split into addresses at each comma) but I though we may have to impose hard limits on the number of addresses for the general case

**Comment by markdroth** [comment]
So it sounds like the concern here is that (a) the target URI could be very long and (b) there could be a large number of addresses, and because the target URI is copied once for each address, this leads to increased memory usage.

The problem is that nothing requires any resolver to have a finite limit for either the length of the target URI or for the number of addresses, and it's not clear to me that it makes sense to add such a limit, because we can't possibly choose an artificial limit that works for every machine that anyone might use gRPC on.  Obviously, if someone is trying to use a configuration that requires more memory than their machine has, that won't work, but if we imposed a limit that kept us from OOMing on that particular machine, then we'd just be adding an arbitrary limitation that prevents someone with a bigger machine from using that kind of configuration.

The one change I could see making here that might improve scalability a bit would be to have a single copy of the target URI string that is shared across all addresses, rather than creating a new copy for each address.  However, this would require introducing a special ref-counted object, and it's honestly not clear to me that it's worth the complexity of doing that, since I doubt that anyone will actually run into this limitation in practice.

My inclination is to just say that the behavior you're seeing is working as intended.  We can't stop people from doing things that OOM their machines, and I don't think that's a bug.

**Comment by Vignesh2208** [comment]
> So it sounds like the concern here is that (a) the target URI could be very long and (b) there could be a large number of addresses, and because the target URI is copied once for each address, this leads to increased memory usage.
> 
> The problem is that nothing requires any resolver to have a finite limit for either the length of the target URI or for the number of addresses, and it's not clear to me that it makes sense to add such a limit, because we can't possibly choose an artificial limit that works for every machine that anyone might use gRPC on. Obviously, if someone is trying to use a configuration that requires more memory than their machine has, that won't work, but if we imposed a limit that kept us from OOMing on that particular machine, then we'd just be adding an arbitrary limitation that prevents someone with a bigger machine from using that kind of configuration.
> 
> The one change I could see making here that might improve scalability a bit would be to have a single copy of the target URI string that is shared across all addresses, rather than creating a new copy for each address. However, this would require introducing a special ref-counted object, and it's honestly not clear to me that it's worth the complexity of doing that, since I doubt that anyone will actually run into this limitation in practice.
> 
> My inclination is to just say that the behavior you're seeing is working as intended. We can't stop people from doing things that OOM their machines, and I don't think that's a bug.

Sounds good. In the latest I removed the hard limit on number of allowed addresses. But I did retain a check to skip addresses which are empty. Turns out this is sufficient to make this bug go away. I can close this PR if you think this check also shouldn't be done ?

**Review by markdroth — APPROVED** [review]

**Pull request merged**
