### PR TITLE
Add debug support for checking tls_init is called

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by yang-g** [comment]
Fixes #5392

**Comment by vjpai** [comment]
The code looks good, but there was just a docker failure on the C++ asan test. Will rebuild and call it ready to merge when it's green.

**Comment by vjpai** [comment]
LGTM on the code.

**Comment by ctiller** [comment]
LGTM

**Comment by jtattermusch** [comment]
I can't merge with red tests. Can we pls rebase and get a fresh test run?

**Comment by yang-g** [comment]
Done.

**Comment by jtattermusch** [comment]
I see 3 python flakes that I thought were fixed (or reduced to very low flakiness rate). Are we certain that this is rebased on top of lastest master?

**Comment by yang-g** [comment]
I did a rebase again this morning. Still sees a failing python test.

**Comment by jtattermusch** [comment]
C# gcov failure is this one: https://github.com/grpc/grpc/issues/5811.

**Pull request merged**
