### PR TITLE
Revert "Revert "Add an implementation firewall against pollset_set""

### PR DESCRIPTION
**Pull request by ctiller**
Reverts grpc/grpc#5426

### CODE REVIEW

**Comment by ctiller** [comment]
Unreverting. It's beyond my gitfu to recover the one before this also. Let's look at what's broken and fix it from there.

**Comment by nicolasnoble** [comment]
Here's the proper gitfu to avoid that PR here:

```
$ git checkout master
$ git pullall upstream/master
$ git checkout hide-the-pollset-set
$ git merge master
$ git revert 2596d8f7e786b22be2fba95c8ced4ec0ad017739 -m 1
$ git push
$ git checkout cleaner-posix2
$ git merge hide-the-pollset-set
$ git push
```

**Comment by nicolasnoble** [comment]
And then you can re-create another PR out of `hide-the-pollset-set`, and #5419 should become mergeable again.

**Comment by nicolasnoble** [comment]
https://xkcd.com/1597/

**Comment by pgrosu** [comment]
@nicolasnoble :)

**Pull request closed without merging**
