### PR TITLE
Revert "Account the memory usage of channel and call by resource quota"

### PR DESCRIPTION
**Pull request by AspirinSJL**
Reverts grpc/grpc#16823

This breaks internal test.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                   FILE SIZE
 ++++++++++++++ GROWING                                                     ++++++++++++++

 -------------- SHRINKING                                                   --------------
  -6.6%    -542 src/core/lib/iomgr/resource_quota.cc                           -542  -6.6%
      [DEL]    -293 resource_user_alloc_locked                                     -293  [DEL]
      [DEL]    -171 grpc_resource_quota_from_channel_args                          -171  [DEL]
     -83.6%    -158 grpc_resource_user_alloc_slices                                -158 -83.6%
      [DEL]    -156 grpc_resource_user_safe_alloc                                  -156  [DEL]
      -6.4%     -92 rq_step                                                         -92  -6.4%
     -22.1%     -59 grpc_resource_user_free                                         -59 -22.1%
      -5.0%     -17 [Unmapped]                                                      -17  -5.0%
      -2.8%      -8 grpc_resource_quota_create                                       -8  -2.8%
  -0.6%    -192 src/core/ext/transport/chttp2/transport/chttp2_transport.cc    -192  -0.6%
      [DEL] -3.42Ki grpc_create_chttp2_transport                                -3.42Ki  [DEL]
     -47.8%    -155 grpc_chttp2_parsing_accept_stream                              -155 -47.8%
      -1.5%     -16 destroy_stream_locked                                           -16  -1.5%
      -0.7%      -5 [Unmapped]                                                       -5  -0.7%
  -5.5%    -160 src/core/ext/transport/chttp2/server/chttp2_server.cc          -160  -5.5%
     -15.7%     -91 on_handshake_done                                               -91 -15.7%
     -14.2%     -61 on_accept                                                       -61 -14.2%
     -12.3%      -8 [Unmapped]                                                       -8 -12.3%
  -0.6%     -96 src/core/lib/surface/server.cc                                  -96  -0.6%
      [DEL] -1.12Ki grpc_server_setup_transport                                 -1.12Ki  [DEL]
      -6.4%     -48 grpc_server_create                                              -48  -6.4%
      -4.2%     -40 grpc_server_shutdown_and_notify                                 -40  -4.2%
      [DEL]      -5 grpc_server_get_default_resource_user                            -5  [DEL]
      -0.9%      -3 [Unmapped]                                                       -3  -0.9%
  -4.8%     -80 src/core/lib/channel/channel_stack_builder.cc                   -80  -4.8%
      [DEL]     -63 grpc_channel_stack_builder_set_resource_user                    -63  [DEL]
      -7.6%     -12 [Unmapped]                                                      -12  -7.6%
      [DEL]      -5 grpc_channel_stack_builder_get_resource_user                     -5  [DEL]
  -0.8%     -48 src/core/lib/surface/channel.cc                                 -48  -0.8%
      [DEL]    -533 grpc_channel_create                                            -533  [DEL]
      -4.4%     -16 destroy_channel                                                 -16  -4.4%
      -2.3%      -3 [Unmapped]                                                       -3  -2.3%
  -0.9%     -16 src/core/ext/transport/chttp2/transport/stream_lists.cc         -16  -0.9%
      -5.8%      -8 [Unmapped]                                                       -8  -5.8%
      -2.3%      -8 stream_list_remove                                               -8  -2.3%
  -0.5%      -8 src/core/lib/surface/lame_client.cc                              -8  -0.5%
      -1.7%      -8 grpc_lame_client_channel_create                                  -8  -1.7%

 -+-+-+-+-+-+-+ MIXED                                                       +-+-+-+-+-+-+-
  -0.2% -1.51Ki [None]                                                      +1.98Ki  +0.0%

  -0.2% -2.62Ki TOTAL                                                          +888  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]    -248  -0.0%

  [ = ]       0 TOTAL     -248  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   725,212       Core (<)        726,346

 2,014,177      Total (<)      2,015,303

***************FRAMEWORKS****************
  New size                      Old size
 3,907,114       Core (<)      3,908,686

11,113,846      Total (<)     11,115,425


```

**Comment by AspirinSJL** [comment]
Superseded by https://github.com/grpc/grpc/pull/17025.

**Pull request closed without merging**
