### PR TITLE
Rewrite udp server linked list

### PR DESCRIPTION
**Pull request by rjshade**
This rewrites udp_server to use a linked list of server_ports, bringing it in line with https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/tcp_server_posix.c

### CODE REVIEW

**Comment by rjshade** [comment]
@ctiller can you take a look at this? It's an attempt to make udp_server.c more similar to the updated tcp_server_posix.c

**Comment by ctiller** [comment]
LGTM

**Comment by rjshade** [comment]
Please test this.

**Comment by rjshade** [comment]
@ctiller can you take a look? I think this still needs to be approved.

**Pull request merged**
