### PR TITLE
Remove grpc_use_signal from API, as no longer relevant

### PR DESCRIPTION
**Pull request by vjpai**
This is a core API removal and discussed in grpc/proposal#106. I will also send in a PR for the stopgap to close the core API breakage that we currently have (I believe it is theoretical only as I cannot find any use of it, but I made a mistake in deleting its implementation).

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,588      Total (=)      1,964,588

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,886,810      Total (>)     10,886,809

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                      FILE SIZE
 ++++++++++++++ GROWING                        ++++++++++++++

 -------------- SHRINKING                      --------------
  -0.0%    -123 [None]                            -171  -0.0%
  -0.2%      -5 src/core/lib/iomgr/ev_posix.cc      -5  -0.2%
      -1.4%      -3 [Unmapped]                          -3  -1.4%
      [DEL]      -2 grpc_use_signal                     -2  [DEL]

  -0.0%    -128 TOTAL                             -176  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                      FILE SIZE
 ++++++++++++++ GROWING                        ++++++++++++++

 -------------- SHRINKING                      --------------
  -0.0%    -123 [None]                            -171  -0.0%
  -0.2%      -5 src/core/lib/iomgr/ev_posix.cc      -5  -0.2%
      -1.4%      -3 [Unmapped]                          -3  -1.4%
      [DEL]      -2 grpc_use_signal                     -2  [DEL]

  -0.0%    -128 TOTAL                             -176  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,588      Total (=)      1,964,588

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,886,802      Total (<)     10,886,957

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,588      Total (=)      1,964,588

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,886,806      Total (<)     10,886,955

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Thanks for the review. I will not merge this until October 10 at the earliest, following the gRFC process.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                      FILE SIZE
 ++++++++++++++ GROWING                        ++++++++++++++

 -------------- SHRINKING                      --------------
  -0.0%     -91 [None]                            -163  -0.0%
  -0.2%      -5 src/core/lib/iomgr/ev_posix.cc      -5  -0.2%
      -1.3%      -3 [Unmapped]                          -3  -1.3%
      [DEL]      -2 grpc_use_signal                     -2  [DEL]

  -0.0%     -96 TOTAL                             -168  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
