### PR TITLE
Update License under third_party/address_sorting

### PR DESCRIPTION
**Pull request by dmaclach**
As far as I can tell, the license file here was completely wrong and was adding 300+ K of unnecessary bloat to every app that included grpc.

### CODE REVIEW

**Comment by apolcyn** [comment]
I want to double-check on this internally before merging

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by mehrdada** [comment]
Yup, SGTM.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
