### PR TITLE
Add Node distrib tests and fixed some issues with the packaging script

### PR DESCRIPTION
**Pull request by murgatroid99**
The Dockerfiles in here match the ones for C#.

### CODE REVIEW

**Comment by murgatroid99** [comment]
Currently, the tests are reporting that `nvm` is not available. I'm not sure why.

**Comment by jtattermusch** [comment]
LGTM.

**Comment by jtattermusch** [comment]
Is the nvm problem related to the fact that you are not using login shell? (you solved that before somewhere by sourcing .profile or sth).

**Comment by murgatroid99** [comment]
That was specifically an issue on Mac, because we were using SSH.

**Pull request merged**
