### PR TITLE
Fix ssl_transport_security_test.cc when built against OpenSSL 1.0.2.

### PR DESCRIPTION
**Pull request by matthewstevenson88**
This PR fixes some of the errors found by PR #25770, namely it enables `ssl_transport_security_test.cc` to build and have its test pass when built against OpenSSL 1.0.2.

Note that there are still some tests that fail when built against OpenSSL 1.0.2.

Relevant issue: #24960

### CODE REVIEW

**Review by veblush — APPROVED** [review]
Thank you for the fix!

**Comment by veblush** [comment]
As a side note, `//test/core/tsi:ssl_transport_security_test` has been flaky for a while [log](https://source.cloud.google.com/results/invocations/adfddb05-99d7-4b6d-9589-7567b8358f8d/targets). I don't think this PR changes it but can you take a quick look on that, too? (This has been flaky for months)

**Comment by matthewstevenson88** [comment]
> As a side note, `//test/core/tsi:ssl_transport_security_test` has been flaky for a while [log](https://source.cloud.google.com/results/invocations/adfddb05-99d7-4b6d-9589-7567b8358f8d/targets). I don't think this PR changes it but can you take a quick look on that, too? (This has been flaky for months)

Sure, I'll take a look before submitting this PR. Is it always a timeout, like in the case of the Bazel RBE TSAN C/C++ failure?

**Comment by matthewstevenson88** [comment]
Update: the [ssl_tsi_test_do_round_trip_odd_buffer_size](https://github.com/grpc/grpc/blob/9eb5cdcb8f725e45fb90be75ba966a00612ac811/test/core/tsi/ssl_transport_security_test.cc#L700) test is super slow (because it runs many many times), so we need to decrease the number of test runs when using TSAN. Otherwise, this test will timeout.

**Pull request merged**
