### PR TITLE
Add ruby 3.0 support for mac binary packages

### PR DESCRIPTION
**Pull request by apolcyn**
Fixes https://github.com/grpc/grpc/issues/25222

Kicked off an artifact run in: https://fusion2.corp.google.com/invocations/0e763400-0be8-47b6-b4ff-12b2434d989e/targets

### CODE REVIEW

**Comment by dazuma** [comment]
@apolcyn Is something holding this up?

**Comment by apolcyn** [comment]
@dazuma sorry progress on this has been slow, but I do plan to get this into the upcoming release. Currently, this PR is stuck on the following error:

```
cd -
mkdir -p /Users/kbuilder/.rake-compiler/sources/ruby-2.7.0
cd /Users/kbuilder/.rake-compiler/sources
tar xf ruby-2.7.0.tar.bz2
cd -
cd /Users/kbuilder/.rake-compiler/builds/x86_64-darwin11/ruby-2.7.0
/Users/kbuilder/.rake-compiler/sources/ruby-2.7.0/configure --host=x86_64-darwin11 --target=x86_64-darwin11 --build=x86_64-apple-darwin18.7.0 --enable-static --disable-shared --disable-install-doc --without-gmp --with-ext= LDFLAGS=-pipe -s --prefix=/Users/kbuilder/.rake-compiler/ruby/x86_64-darwin11/ruby-2.7.0
checking for ruby... /Users/kbuilder/.rvm/rubies/ruby-2.7.0/bin/ruby
tool/config.guess already exists
tool/config.sub already exists
checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-pc-darwin11
checking target system type... x86_64-pc-darwin11
checking for x86_64-darwin11-clang... no
checking for x86_64-darwin11-gcc... no
checking for x86_64-darwin11-cc... no
checking for clang... clang
configure: WARNING: using cross tools not prefixed with host triplet
checking for x86_64-darwin11-gcc... clang
checking for x86_64-darwin11-gcc... (cached) clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for clang option to accept ISO C99... none needed
checking for x86_64-darwin11-clang++... no
checking for clang++... clang++
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C preprocessor... clang -E
checking if minimum required OS X version is supported... yes
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether clang++ accepts -g... (cached) yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether clang needs -traditional... no
checking for x86_64-darwin11-ld... no
checking for ld... ld
checking whether the linker is GNU ld... no
checking whether clang -E accepts -o... yes
checking for x86_64-darwin11-clang-ranlib... no
checking for x86_64-darwin11-ranlib... no
checking for clang-ranlib... (cached) :
checking for x86_64-darwin11-clang-ar... no
checking for x86_64-darwin11-ar... no
checking for clang-ar... (cached) libtool -static
checking for libtool -static flags... (cached) -no_warning_for_no_symbols -o
checking for x86_64-darwin11-as... no
checking for as... as
checking for x86_64-darwin11-objdump... no
checking for x86_64-darwin11-gobjdump... no
checking for objdump... objdump
checking for x86_64-darwin11-objcopy... no
checking for x86_64-darwin11-gobjcopy... no
checking for objcopy... no
checking for gobjcopy... no
checking for x86_64-darwin11-clang-nm... no
checking for x86_64-darwin11-nm... no
checking for clang-nm... no
checking for nm... nm
checking whether ln -s works... yes
checking whether make -j8 sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for x86_64-darwin11-dtrace... no
checking for dot... no
checking for doxygen... no
checking for pkg-config... pkg-config
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for cd using physical directory... cd -P
checking whether CFLAGS is valid... yes
checking whether LDFLAGS is valid... no
configure: error: something wrong with LDFLAGS="-pipe -s"
rake aborted!
Command failed with status (1): [/Users/kbuilder/.rake-compiler/sources/rub...]
/Volumes/BuildData/tmpfs/src/github/grpc/tmpfile.74o8Xi3S:128:in `block (2 levels) in <top (required)>'
/Volumes/BuildData/tmpfs/src/github/grpc/tmpfile.74o8Xi3S:125:in `block in <top (required)>'
Tasks: TOP => cross-ruby => install => /Users/kbuilder/.rake-compiler/ruby/x86_64-darwin11/ruby-2.7.0/bin/ruby.exe => /Users/kbuilder/.rake-compiler/builds/x86_64-darwin11/ruby-2.7.0/ruby.exe => /Users/kbuilder/.rake-compiler/builds/x86_64-darwin11/ruby-2.7.0/Makefile
(See full trace by running task with --trace)
```

**Comment by apolcyn** [comment]
Kicked off a full package build in https://fusion2.corp.google.com/invocations/1be85d06-f857-44bc-b631-52f400778b11/targets since the macos artifact smoke test passed

**Comment by apolcyn** [comment]
passing package build: https://fusion2.corp.google.com/invocations/69a3c64e-de5b-472e-9441-f2b45aa3c0e8/targets/grpc%2Fcore%2Fexperimental%2Fgrpc_build_artifacts_multiplatform/log

**Review by stanley-cheung — APPROVED** [review]

**Pull request merged**
