### PR TITLE
Fixed Ruby build on Mac

### LINKED ISSUE #3626: Ruby build failing
I am unable to build the ruby gem. Here is the homebrew install:

```
$ curl -fsSL https://goo.gl/getgrpc | bash -s ruby
zlib is already installed
openssl is already installed
google-protobuf is already installed
grpc is already installed
installing grpc ruby
Building native extensions with: '--with-grpc-dir=/usr/local'
This could take a while...
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.

    /Users/blowmage/.rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151005-44201-1btzn1u.rb extconf.rb --with-grpc-dir=/usr/local
checking for dlopen() in -ldl... yes
checking for inflate() in -lz... yes
checking for gpr_now() in -lgpr... yes
checking for grpc_channel_destroy() in -lgrpc... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rb_byte_buffer.c
compiling rb_call.c
rb_call.c:177:32: error: too many arguments to function call, expected single argument 'call', have 2 arguments
  err = grpc_call_cancel(call, NULL);
        ~~~~~~~~~~~~~~~~       ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/stddef.h:105:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
/usr/local/include/grpc/grpc.h:448:1: note: 'grpc_call_cancel' declared here
grpc_call_error grpc_call_cancel(grpc_call *call);
^
rb_call.c:192:10: error: implicit declaration of function 'grpc_call_get_peer' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  peer = grpc_call_get_peer(call);
         ^
rb_call.c:192:10: note: did you mean 'grpc_rb_call_get_peer'?
rb_call.c:187:14: note: 'grpc_rb_call_get_peer' declared here
static VALUE grpc_rb_call_get_peer(VALUE self) {
             ^
rb_call.c:192:8: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Werror,-Wint-conversion]
  peer = grpc_call_get_peer(call);
       ^ ~~~~~~~~~~~~~~~~~~~~~~~~
rb_call.c:560:25: error: no member named 'reserved' in 'struct grpc_op'
    st->ops[st->op_num].reserved = NULL;
    ~~~~~~~~~~~~~~~~~~~ ^
rb_call.c:655:70: error: too many arguments to function call, expected 4, have 5
  err = grpc_call_start_batch(call, st.ops, st.op_num, ROBJECT(tag), NULL);
        ~~~~~~~~~~~~~~~~~~~~~                                        ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/stddef.h:105:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
/usr/local/include/grpc/grpc.h:420:1: note: 'grpc_call_start_batch' declared here
grpc_call_error grpc_call_start_batch(grpc_call *call, const grpc_op *ops,
^
5 errors generated.
make: *** [rb_call.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/blowmage/.gem/repos/grpc-travis/gems/grpc-0.11.0 for inspection.
Results logged to /Users/blowmage/.gem/repos/grpc-travis/extensions/x86_64-darwin-14/2.2.0-static/grpc-0.11.0/gem_make.out
```

And here is a `bundle install`:

```
$ bundle install
Fetching gem metadata from http://rubygems.org/..........
Fetching version metadata from http://rubygems.org/..
Resolving dependencies...
Using addressable 2.3.8
Using extlib 0.9.16
Using multipart-post 2.0.0
Using faraday 0.9.1
Using google-protobuf 3.0.0.alpha.4.0
Using jwt 1.5.1
Using little-plugger 1.1.4
Using multi_json 1.11.2
Using logging 2.0.0
Using memoist 0.12.0
Using signet 0.6.1
Using googleauth 0.4.2
Installing grpc 0.11.0 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/blowmage/.rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151005-44363-wztxjm.rb extconf.rb
checking for dlopen() in -ldl... yes
checking for inflate() in -lz... yes
checking for gpr_now() in -lgpr... yes
checking for grpc_channel_destroy() in -lgrpc... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rb_byte_buffer.c
compiling rb_call.c
rb_call.c:177:32: error: too many arguments to function call, expected single argument 'call', have 2 arguments
  err = grpc_call_cancel(call, NULL);
        ~~~~~~~~~~~~~~~~       ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/stddef.h:105:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
/usr/local/include/grpc/grpc.h:448:1: note: 'grpc_call_cancel' declared here
grpc_call_error grpc_call_cancel(grpc_call *call);
^
rb_call.c:192:10: error: implicit declaration of function 'grpc_call_get_peer' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  peer = grpc_call_get_peer(call);
         ^
rb_call.c:192:10: note: did you mean 'grpc_rb_call_get_peer'?
rb_call.c:187:14: note: 'grpc_rb_call_get_peer' declared here
static VALUE grpc_rb_call_get_peer(VALUE self) {
             ^
rb_call.c:192:8: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Werror,-Wint-conversion]
  peer = grpc_call_get_peer(call);
       ^ ~~~~~~~~~~~~~~~~~~~~~~~~
rb_call.c:560:25: error: no member named 'reserved' in 'struct grpc_op'
    st->ops[st->op_num].reserved = NULL;
    ~~~~~~~~~~~~~~~~~~~ ^
rb_call.c:655:70: error: too many arguments to function call, expected 4, have 5
  err = grpc_call_start_batch(call, st.ops, st.op_num, ROBJECT(tag), NULL);
        ~~~~~~~~~~~~~~~~~~~~~                                        ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/stddef.h:105:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
/usr/local/include/grpc/grpc.h:420:1: note: 'grpc_call_start_batch' declared here
grpc_call_error grpc_call_start_batch(grpc_call *call, const grpc_op *ops,
^
5 errors generated.
make: *** [rb_call.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/blowmage/.gem/repos/grpc-travis/gems/grpc-0.11.0 for inspection.
Results logged to /Users/blowmage/.gem/repos/grpc-travis/extensions/x86_64-darwin-14/2.2.0-static/grpc-0.11.0/gem_make.out
An error occurred while installing grpc (0.11.0), and Bundler cannot continue.
Make sure that `gem install grpc -v '0.11.0'` succeeds before bundling.
```

Another report was made at grpc/grpc-common#283.

### PR DESCRIPTION
**Pull request by murgatroid99**
Fixes #3626. This is on the release branch because I want it to be in a point release if we publish one.

### CODE REVIEW

**Comment by avongluck-r1soft** [comment]
Just confirmed this applied to master/head resolves the same gem build issue on Ubuntu 15.10

**Comment by murgatroid99** [comment]
@avongluck-r1soft Great, thank you for checking that.

**Comment by jtattermusch** [comment]
LGTM, fine to merge once green.

**Comment by murgatroid99** [comment]
A bunch of tests failed, but they're all tsan and msan. And the interop test failures are all known cloud-to-prod issues. I think it's OK to merge.

**Pull request merged**
