### PR TITLE
Update nuget packages

### PR DESCRIPTION
**Pull request by jtattermusch**
-- bump grpc.native.csharp_ext version
-- add debugging symbol support for nuget packages
-- make doc comments part of nuget package

### CODE REVIEW

**Comment by tbetbetbe** [comment]
The travis failure was another instance of #1573

**Comment by gazialankus** [comment]
I would like to step into C# grpc code but I can't. 

I'm using grpc via NuGet in Visual Studio and it can't find Grpc.Core.pdb for 1.00.1.0. I configured to use symbolsource.org but it seems the latest pdb it has is for 0.7.1. I'm not a NuGet expert, how can I step into grpc code? 

image

**Comment by jtattermusch** [comment]
@gazialankus, if stepping into the code doesn't work for you, please create a separate issue for that (this PR has been merged long time ago and is not relevant anymore).

**Comment by gazialankus** [comment]
Sorry about that, [here is the issue](https://github.com/grpc/grpc/issues/9521) for future reference.

**Pull request merged**
