### PR TITLE
UCX first implementation approach example

### PR DESCRIPTION
**Pull request by shssf**
This PR is a first step. It is not planned to be merged. It is for feedback collection and implementation proposals.
The UCX is http://www.openucx.org/
UCX Quick start: https://github.com/openucx/ucx/wiki

To try this patch you can build gRPC with -DGRPC_USE_UCX=1 and do simple tests (UCX will be used instead TCP as low level endpoint).

### CODE REVIEW

**Comment by shssf** [comment]
I signed it!

**Comment by ctiller** [comment]
Thanks for your contribution!

Some quick initial feedback:
1. Copyright will need to be assigned to gRPC and all files should take the normal gRPC copyright banner
2. However this ends up getting implemented... it should not require changes to epoll/tcp related files, especially not changes that call out ucx explicitly - our usual style is to factor platform specific code into `_$platform.{c,h}` files
3. We will need a way of testing this without special hardware with our run_tests infrastructure
4. transport is a word that means something very different in the grpc codebase than what ucx is providing

If the intent is to replace grpc_tcp with ucx, then I'd suggest an approach whereby we have a tcp_ucx.c implementation that gets enabled/disabled with a `#define`.

**Comment by shssf** [comment]
@ctiller Thank you for the feedback. I will take care about proposed changes.
I would like to implement automatic endpoint selection instead hard-coded `#define`. I see it in the following way (please correct me):
1. add an auxiliary field in chttp2 handshake procedure and use it as UCX HW address (~400 bytes)
2. If the server gets incoming connection (in regular way) it looks for this field. If it is not zero (end server support UCX) it creates and dispatch  closure which will establish UCX connection with the client.
2. If the client support UCX it packed UCX HW address into chttp2 field and send it to server. If positive answer received - it dispatch closure to establish UCX based connection with the server.

Could you recommend me some example field I could use (as an example) to create UCX address filed in chttp2 handshake mechanism?

**Comment by miked-mellanox** [comment]
@ctiller - re \#3 from your list - UCX supports shared memory transport so it will be no issue to call it from run_test infra.

**Comment by ctiller** [comment]
@murgatroid99 has a proposal for how to deal with custom endpoint creation: hoping he can share it here.

**Comment by murgatroid99** [comment]
I've written that proposal up in issue #8639.

**Comment by shssf** [comment]
@ctiller @murgatroid99 
Thank you very much for the proposal.
Just to clarify things: Does it mean you reject alternative endpoint implementations in gRPC by providing external interface for this?
I completely agree that external interface for endpoints is a very good idea. This could solve particular user need if non-tcp stack used. From another perspective, it prevents other users to get the same functionality "from the box" in gRPC.

**Comment by miked-mellanox** [comment]
@ctiller @murgatroid99 - could you please update on status and ETA of new infra ( #8639) so we can plan to rebase this PR and its availability?
Thanks

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Pull request closed without merging**
