### PR TITLE
Add grpc-java 1.45.2 to client_matrix.py

### PR DESCRIPTION
**Pull request by sergiitk**

### CODE REVIEW

**Comment by sergiitk** [comment]
Adhoc run: https://source.cloud.google.com/results/invocations/d4847f37-cb97-4946-ac53-e05a1eaa4015

**Comment by ejona86** [comment]
This now has conflicts because of https://github.com/grpc/grpc/pull/31273 . Let's close this in favor of https://github.com/grpc/grpc/pull/31291

**Comment by sergiitk** [comment]
Got it, thanks.

**Comment by sergiitk** [comment]
BTW, the test failed with tool failure. Kokoro.

**Pull request closed without merging**
