### PR TITLE
Remove beta module dependency from the Python Bazel package

### PR DESCRIPTION
**Pull request by mehrdada**
gRPC Python Beta code elements is deprecated and should go away. Considering Bazel users are unlikely to have ever depended on such old API, we should not let them to dig themselves into a hole. Let's make those code elements unavailable from the Python Bazel-built package.

### CODE REVIEW

**Comment by mehrdada** [comment]
cc @lidizheng

**Comment by mehrdada** [comment]
@lidizheng PTAL.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,630      Total (>)     11,175,626

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,021,646      Total (=)      2,021,646

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,937      Total (>)     11,177,935

 No significant differences in binary sizes


```

**Comment by mehrdada** [comment]
@lidizheng thanks for merging. Yes, also note that ".frameworks" is also part of the beta story, and should be deprecated. There are some tiny internal dependencies that needs to be fixed up (just `callable_util` and `logging_pool` in a couple places) and we should be good to go with removing that, but wanted to do that later.

**Pull request merged**
