### PR TITLE
Removed references to public APIs from codegen/

### LINKED ISSUE #6023: Move all core API's out of codegen/
Reasoning: any API call will require pulling in the library, and we can't pull in the library. Therefore, no API declaration can live in the codegen/ directory.

### PR DESCRIPTION
**Pull request by dgquintas**
Fixes #6023 

This PR looks scary but there's (almost) no new code, simply lines moving around. The exception to the no-new-code is the addition of some methods to the CoreInterface API (see `core_codegen_interface.h` and `core_codegen.{h,cc}`).

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM. objc failure seems scary though - @jcanizales PTAL.

**Comment by dgquintas** [comment]
It seems to have been failing for a while
https://grpc-testing.appspot.com/job/gRPC_pull_requests/12543/config=dbg,language=objc,platform=macos/testReport/(root)/tests/objc_examples_build/history/

**Comment by jcanizales** [comment]
@makdharma and @muxi for ObjC Jenkins. I see a timeout - Craig, is that the one you mean, or am I looking at the wrong place?

**Comment by muxi** [comment]
The timeout of objc-examples-build happens when the macos machines get busy. However, logs of other previous PRs showed that macos node 1's cocoapods repo is not up to date. Expected to happen since node 1 was offline for a while last few weeks, due to which we stopped automatic update of cocoapods repo. I am updating it right now and should be no problem.

Can we try a retest?

**Comment by dgquintas** [comment]
Test this please

**Comment by dgquintas** [comment]
Yes, the objc failure is gone, thanks!

**Comment by dgquintas** [comment]
@kpayson64 can this be merged forcefully? The interop tests are still failing across the board and for unrelated reasons it seems.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
