### PR TITLE
ruby: Use fully-qualified type name when necessary

### PR DESCRIPTION
**Pull request by jmuk**
- Use full_name() instead of name(), otherwise package names
  are omitted.
- Fix a minor bug on RubyTypeOf(), to replace dotted protobuf
  package name by ruby's module names correctly.

### CODE REVIEW

**Comment by murgatroid99** [comment]
This is ok to test

**Comment by jmuk** [comment]
What is the best way to test this?

I'm looking src/ruby/spec/pb, probably adding a new test case in parallel to health.proto?

**Comment by murgatroid99** [comment]
I think that would be a good way to handle it.

**Comment by jmuk** [comment]
Added a test case. PTAL.

**Comment by murgatroid99** [comment]
If the goal here is just to test cross-package imports, you should use the existing file `src/proto/grpc/testing/duplicate/echo_duplicate.proto`, which appears to be present specifically for that purpose.

**Comment by jmuk** [comment]
Oh, I see. Updated to reuse echo_duplicate.proto. Thanks, and please take another look!

**Comment by murgatroid99** [comment]
LGTM. The C# failure is a known flake that this change did not affect.

**Pull request merged**
