### PR TITLE
Improve perf smoke test stability

### PR DESCRIPTION
**Pull request by vjpai**
Right now, perf smoke tests are broken (even though the perf tests integrated into basic tests are running), and this may be because we have issues related to keeping the workers alive from test to test. This stability problem needs a longer-term solution, but for now we need to be able to have green smoke tests.

### CODE REVIEW

**Comment by ctiller** [comment]
Ugly, but it works.

**Comment by vjpai** [comment]
This change did not work. 
https://grpc-testing.appspot.com/job/gRPC_performance_master/2086/console

Given that it did not work, I believe that it should be reverted.

**Comment by ctiller** [comment]
agree

**Comment by ctiller** [comment]
Do pull requests go through a different list?

**Comment by vjpai** [comment]
List? It's the same script, but on a different Jenkins task. I think it
runs on the same box, though.

**Pull request merged**
