### PR TITLE
Backport pick_first fix to v1.19.x

### PR DESCRIPTION
**Pull request by AspirinSJL**
The original fix (#18598) is modified to fit into v1.19.x.

I have verified that the test fails before the fix and passes after the fix.

### CODE REVIEW

**Comment by AspirinSJL** [comment]
@srini100 Please merge this patch, thanks!

**Comment by srini100** [comment]
@lidizheng, this will require a new RC since pick first is default policy.

**Comment by AspirinSJL** [comment]
Distribution Tests Linux (standalone subset): https://github.com/grpc/grpc/issues/18548

**Comment by AspirinSJL** [comment]
I think we need a patch release for v1.19.

It's not in v1.20.x yet. Backporting it via https://github.com/grpc/grpc/pull/18629.

**Pull request merged**
