### PR TITLE
LB policies: convert to new JSON API

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by ctiller** [comment]
looking at the bloat numbers it seems like we're pouring too much code into AutoLoader<> and not enough into shared backends in the cc file

**Comment by ctiller** [comment]
Just a drive by... there's a lot of systemic bloat here, anything prefixed with `grpc_core::json_detail`:
```
    +292% +2.75Ki  +292% +2.75Ki    grpc_core::json_detail::AutoLoader<>::Insert()
```
That's probably fine to take on because, being systemic we can systemically reduce it.

There's also some PostLoad & new std::map usage bloat that we should survey and see if there's anything we can do, for example:
```
    [NEW] +4.54Ki  [NEW] +4.54Ki    grpc_core::(anonymous namespace)::RlsLbConfig::RouteLookupConfig::JsonPostLoad()
    [NEW] +3.34Ki  [NEW] +3.34Ki    grpc_core::(anonymous namespace)::XdsClusterImplLbConfig::JsonPostLoad()
    [NEW] +2.38Ki  [NEW] +2.38Ki    grpc_core::(anonymous namespace)::GrpcLbConfig::JsonPostLoad()
    [NEW] +2.18Ki  [NEW] +2.18Ki    grpc_core::(anonymous namespace)::GrpcKeyBuilder::JsonPostLoad()
    +2.5% +2.11Ki  +2.5% +2.11Ki    std::_Rb_tree<>::_M_erase()
    [NEW] +2.02Ki  [NEW] +2.02Ki    grpc_core::(anonymous namespace)::RlsLbConfig::JsonPostLoad()
    [NEW] +1.49Ki  [NEW] +1.49Ki    grpc_core::(anonymous namespace)::XdsClusterResolverLbConfig::DiscoveryMechanism::JsonPostLoad()
    [NEW] +1.22Ki  [NEW] +1.22Ki    grpc_core::(anonymous namespace)::XdsClusterResolverLbConfig::JsonPostLoad()
 ```

**Comment by markdroth** [comment]
I've added a variant of `LoadFromJson()` that handles the case where the object is `RefCounted<>`, which eliminates the need for all of the LB configs to be movable.  We'll see if that reduces some of the bloat here.

I think it's expected for this PR to be adding code in `JsonPostLoad()` functions, because those are the cases where we need custom parsing or validation for various fields; that code basically already existed prior to this PR, but it was in a different place.  The only place I can see where we might be able to cut this down some duplication is the case that we discussed a while back, where we have multiple places where we are basically doing the same parsing of a child policy config.  If you can suggest a way to create a JsonLoader for a `RefCountedPtr<LoadBalancingPolicy::Config>` without having the json_object_loader library depend on the LB policy API, then we can probably eliminate some more duplication there.

**Comment by markdroth** [comment]
FWIW, note that the additions in the various `JsonLoader()` and `JsonPostLoad()` functions are actually smaller than the original code removed, which is what I would expect.  Here are the additions, which total about 25.4K:

```
    [NEW] +4.61Ki  [NEW] +4.61Ki    grpc_core::(anonymous namespace)::RlsLbConfig::RouteLookupConfig::JsonPostLoad()
    [NEW] +3.34Ki  [NEW] +3.34Ki    grpc_core::(anonymous namespace)::XdsClusterImplLbConfig::JsonPostLoad()
    [NEW] +2.52Ki  [NEW] +2.52Ki    grpc_core::(anonymous namespace)::RlsLbConfig::JsonPostLoad()
    [NEW] +2.42Ki  [NEW] +2.42Ki    grpc_core::(anonymous namespace)::GrpcLbConfig::JsonPostLoad()
    [NEW] +2.18Ki  [NEW] +2.18Ki    grpc_core::(anonymous namespace)::GrpcKeyBuilder::JsonPostLoad()
    [NEW] +1.49Ki  [NEW] +1.49Ki    grpc_core::(anonymous namespace)::XdsClusterResolverLbConfig::DiscoveryMechanism::JsonPostLoad()
    [NEW] +1.22Ki  [NEW] +1.22Ki    grpc_core::(anonymous namespace)::XdsClusterResolverLbConfig::JsonPostLoad()
    [NEW] +1.09Ki  [NEW] +1.09Ki    grpc_core::(anonymous namespace)::PriorityLbConfig::JsonPostLoad()
    [NEW]    +986  [NEW]    +986    grpc_core::OutlierDetectionConfig::JsonLoader()
    [NEW]    +880  [NEW]    +880    grpc_core::(anonymous namespace)::RlsLbConfig::RouteLookupConfig::JsonLoader()
    [NEW]    +725  [NEW]    +725    grpc_core::OutlierDetectionConfig::FailurePercentageEjection::JsonLoader()
    [NEW]    +719  [NEW]    +719    grpc_core::OutlierDetectionConfig::SuccessRateEjection::JsonLoader()
    +4.1%    +632  +4.1%    +632    grpc_core::(anonymous namespace)::XdsClusterResolverLb::CreateChildPolicyConfigLocked()
    [NEW]    +624  [NEW]    +624    grpc_core::(anonymous namespace)::GrpcKeyBuilder::JsonLoader()
    [NEW]    +502  [NEW]    +502    grpc_core::RingHashConfig::JsonPostLoad()
    [NEW]    +468  [NEW]    +468    grpc_core::(anonymous namespace)::GrpcKeyBuilder::JsonPostLoad()::{lambda()#1}::operator()()
    [NEW]    +410  [NEW]    +410    grpc_core::OutlierDetectionConfig::JsonPostLoad()
    [NEW]    +374  [NEW]    +374    grpc_core::RingHashConfig::JsonLoader()
    [NEW]     +92  [NEW]     +92    grpc_core::(anonymous namespace)::XdsClusterResolverLbFactory::ParseLoadBalancingConfig()::XdsJsonArgs::IsEnabled()
    [NEW]     +88  [NEW]     +88    grpc_core::(anonymous namespace)::XdsClusterResolverLbFactory::ParseLoadBalancingConfig()::XdsJsonArgs::~XdsJsonArgs()
```

And here's the code that got removed, totalling about 57.3K:

```
   -46.7%    -854 -46.7%    -854    grpc_core::(anonymous namespace)::CdsLbFactory::ParseLoadBalancingConfig()
    [DEL] -1.62Ki  [DEL] -1.62Ki    grpc_core::ParseRingHashLbConfig()
   -51.8% -1.73Ki -51.8% -1.73Ki    grpc_core::(anonymous namespace)::OutlierDetectionLbFactory::ParseLoadBalancingConfig()
   -79.0% -2.86Ki -79.0% -2.86Ki    grpc_core::(anonymous namespace)::GrpcLbFactory::ParseLoadBalancingConfig()
   -75.8% -3.03Ki -75.8% -3.03Ki    grpc_core::(anonymous namespace)::XdsClusterManagerLbFactory::ParseLoadBalancingConfig()
   -81.2% -4.11Ki -81.2% -4.11Ki    grpc_core::(anonymous namespace)::PriorityLbFactory::ParseLoadBalancingConfig()
   -81.3% -4.21Ki -81.3% -4.21Ki    grpc_core::(anonymous namespace)::WeightedTargetLbFactory::ParseLoadBalancingConfig()
   -92.0% -9.29Ki -92.0% -9.29Ki    grpc_core::(anonymous namespace)::XdsClusterImplLbFactory::ParseLoadBalancingConfig()
    [DEL] -9.70Ki  [DEL] -9.70Ki    grpc_core::(anonymous namespace)::ParseGrpcKeybuilder()
   -96.0% -9.75Ki -96.0% -9.75Ki    grpc_core::(anonymous namespace)::XdsClusterResolverLbFactory::ParseLoadBalancingConfig()
   -92.7% -10.1Ki -92.7% -10.1Ki    grpc_core::(anonymous namespace)::RlsLbFactory::ParseLoadBalancingConfig()
```

So it's not really clear to me what's causing the additional bloat here.

**Review by ctiller — APPROVED** [review]

**Pull request merged**
