### PR TITLE
Switch RBE build_url from Sponge to ResultStore Bazel invocation

### LINKED ISSUE #15627: "jenkins_test_results.rbe_test_results" dataset contains resultstore links without structured test results.
There's distinction between the "ResultStore" and "Bazel" links:

https://source.cloud.google.com/results/invocations/f90fe70c-f09e-436a-8fd7-b267bf7de9a7
vs 
https://source.cloud.google.com/results/invocations/912eaf41-0f8d-4363-b5db-ef58cf2debfb

For rbe_test_results, the BQ data should contain the latter link which has more details and clickable structured test results.

### PR DESCRIPTION
**Pull request by matt-kwong**
Fixes #15627

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by matt-kwong** [comment]
Bazel failures: #15610

**Pull request merged**
