### PR TITLE
C++ Documentation Audit Fixes 

### PR DESCRIPTION
**Pull request by mehrdada**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by markdroth** [comment]
Haven't reviewed this yet, but please see my comments in #10992 for some of what I think is missing.  I will try to take a look at this in the next day or two.

**Comment by mehrdada** [comment]
We have done independent audits, so there could be some overlap, but there are difference. I will try to merge and rebase it against @apolcyn's PR—have you already reviewed that and is it ready to merge? If so, it's easier for me to wait for y'all to merge it first and then I'll rebase against that future master?

**Comment by apolcyn** [comment]
I'm still making a some changes that I'll be trying to get wrapped up within today

**Comment by mehrdada** [comment]
@apolcyn Cool! Please ping here once you merged that other PR and I'll rebase & merge this PR promptly

**Comment by mehrdada** [comment]
@yang-g rebased this against master. PTAL for additional edits on top of Alex's PR.

**Pull request merged**
