### PR TITLE
Enable check for use-after-dtor

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                    FILE SIZE
 ++++++++++++++ GROWING                                      ++++++++++++++

 -------------- SHRINKING                                    --------------
  -0.7%     -64 src/core/lib/iomgr/ev_epoll1_linux.cc            -64  -0.7%
     -16.2%     -61 fd_create                                        -61 -16.2%
      -1.2%      -3 [Unmapped]                                        -3  -1.2%
  -0.7%     -64 src/core/lib/iomgr/ev_epollsig_linux.cc          -64  -0.7%
     -18.9%     -66 fd_create                                        -66 -18.9%
  -0.4%     -48 src/core/lib/iomgr/ev_epollex_linux.cc           -48  -0.4%
     -17.4%     -58 fd_create                                        -58 -17.4%
  -1.1%     -16 src/core/lib/iomgr/lockfree_event.cc             -16  -1.1%
      [DEL]    -179 grpc_core::LockfreeEvent::DestroyEvent          -179  [DEL]
     -21.2%     -11 [Unmapped]                                       -11 -21.2%
      [DEL]      -8 grpc_core::LockfreeEvent::InitEvent               -8  [DEL]

 -+-+-+-+-+-+-+ MIXED                                        +-+-+-+-+-+-+-
  -0.0%    -112 [None]                                          +328  +0.0%

  -0.0%    -304 TOTAL                                           +136  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by yang-g** [comment]
Verified this would have caught the problem fixed by #13454

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
Test flakes:
Asan C++: #13445
Basic Tests MacOS(dbg opt): #13446 #13426
Basic Tests Windows (dbg opt): #13426 
Tsan C++: #13478

**Pull request merged**
