### PR TITLE
Simple optimizations in TCP read

### PR DESCRIPTION
**Pull request by soheilhy**
This PR has two commits. One fixes a bug IMO, and one is a performance enhancement.

These are both precursors to TCP_INQ.

## Patch 1
Update TCP read estimates as soon as we read the whole buffer.

If we have a continous stream of bytes on the socket, we will
never grow the buffer, because we will never get EAGAIN, and
call finish. This is a serious performance issue, which can
be misued.

As soon as we have a full buffer, update the estimate.

## Patch 2
Do not wait for allocation if buffer is less than half the target.

We overallocate by 2x for target. Unless buffer is more than half
full, we should not delay read for more allocation.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                       FILE SIZE
 ++++++++++++++ GROWING                         ++++++++++++++
  [ = ]       0 [None]                             +144  +0.0%
  +1.3%     +96 src/core/lib/iomgr/tcp_posix.cc     +96  +1.3%
      +9.5%     +83 tcp_do_read                         +83  +9.5%
      +2.8%     +16 tcp_handle_read                     +16  +2.8%

  +0.0%     +96 TOTAL                              +240  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                             allocs_per_iteration    locks_per_iteration
--------------------------------------------------------------------  ----------------------  ---------------------
BM_PumpStreamClientToServer<TCP>/16777216                             -6%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/16777216/1     -6%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/16777216/2     -4%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/2097152/2      -5%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/16777216/1        -18%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/16777216   -10%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/16777216         -7%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/16777216/16777216  -14%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/16777216/16777216     -6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/2097152/2097152                               -5%
```

**Comment by yashykt** [comment]
Cool!

**Comment by soheilhy** [comment]
Thank you for approval guys!

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                       FILE SIZE
 ++++++++++++++ GROWING                         ++++++++++++++
  [ = ]       0 [None]                             +144  +0.0%
  +1.3%     +96 src/core/lib/iomgr/tcp_posix.cc     +96  +1.3%
      +9.5%     +83 tcp_do_read                         +83  +9.5%
      +2.8%     +16 tcp_handle_read                     +16  +2.8%

  +0.0%     +96 TOTAL                              +240  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,914      Total (>)      1,965,822

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,001      Total (<)     10,909,003

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                          allocs_per_iteration    atm_add_per_iteration
-----------------------------------------------------------------  ----------------------  -----------------------
BM_PumpStreamClientToServer<TCP>/134217728                         -9%
BM_PumpStreamServerToClient<TCP>/16777216                          -9%
BM_PumpStreamServerToClient<TCP>/8                                 +11%                    +4%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/16777216/1  -18%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/134217728/2    -38%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/16777216/1     -25%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/16777216/2     -13%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/16777216   -11%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/16777216      -12%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/16777216         -10%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                       FILE SIZE
 ++++++++++++++ GROWING                         ++++++++++++++
  [ = ]       0 [None]                             +144  +0.0%
  +1.3%     +96 src/core/lib/iomgr/tcp_posix.cc     +96  +1.3%
      +9.5%     +83 tcp_do_read                         +83  +9.5%
      +2.8%     +16 tcp_handle_read                     +16  +2.8%

  +0.0%     +96 TOTAL                              +240  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,914      Total (>)      1,965,822

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,004      Total (<)     10,909,007

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                            allocs_per_iteration    atm_add_per_iteration    atm_cas_per_iteration    locks_per_iteration
-------------------------------------------------------------------  ----------------------  -----------------------  -----------------------  ---------------------
BM_PumpStreamClientToServer<TCP>/16777216                            -11%
BM_PumpStreamServerToClient<TCP>/16777216                            -9%
BM_PumpStreamServerToClient<TCP>/8                                   +22%                    +8%                      +11%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/16777216/1    -28%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/16777216/2    -15%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/2097152/1                                                                               -5%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/134217728/1      -50%                    -35%                     -43%                     -39%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/16777216/1       -30%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/16777216/2       -17%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/16777216  -28%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/16777216     -28%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/134217728       -6%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/16777216        -6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/2097152/2097152                                                                                -9%
```

**Comment by soheilhy** [comment]
Tool failure is because of #16846

**Pull request merged**
