### PR TITLE
Don't Use Benchmark Counters

### PR DESCRIPTION
**Pull request by ncteisen**
Follows from #15188.

Using this feature prohibits us from linking our OSS benchmarks to internal code. 

Will this break #12870? call_initial_size-median and call_initial_size-99p still get printed

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by kpayson64** [comment]
I suspect so.  I used counters to avoid having to parse the output later IIRC.

FWIW I'm fine removing call size from the BM diff.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by ncteisen** [comment]
Done

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                            cpu_time    real_time
-------------------------------------------------------------------  ----------  -----------
BM_ErrorGetIntFromNoError                                            +8%         +8%
BM_HasClearGrpcStatus<ErrorCancelled>                                -5%         -5%
BM_MetadataRefUnrefStatic                                            +12%        +12%
BM_PumpStreamServerToClient<InProcess>/262144                        +4%         +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768  +4%         +4%
```

**Pull request merged**
