### PR TITLE
Fix and parsing utils for compression in C++

### PR DESCRIPTION
**Pull request by dgquintas**
Plus addition of C++ utility functions for the parsing of compression levels and algorithms

### CODE REVIEW

**Comment by dgquintas** [comment]
@yang-g PTAL

**Comment by dgquintas** [comment]
jenkins test this please

**Comment by dgquintas** [comment]
jenkins test this please

**Comment by atomextranova** [comment]
Are there already any helloworld example for compressing data referred by #6297? @dgquintas Perhaps I am just too dumb to find any in the project.

**Pull request closed without merging**
