### PR TITLE
Fix stream_compression_payload flake

### LINKED ISSUE #12892: Failed: bins/msan/h2_ssl_proxy_test stream_compression_payload
```
2017-10-07 00:43:04,120 FAILED: Some tests failed
  adding: reports/ (stored 0%)
  adding: reports/index.html (deflated 22%)
  adding: c_linux_ubsan_native/sponge_log.xml (deflated 87%)
+ DOCKER_EXIT_CODE=2
++ mktemp
+ TEMP_REPORTS_ZIP=/tmp/tmp.V5MdPp8zdq
+ docker cp run_tests_ee82fa35-9f64-4d5c-8264-4b6f17e0c2d5:/var/local/git/grpc/reports.zip /tmp/tmp.V5MdPp8zdq
+ unzip -o /tmp/tmp.V5MdPp8zdq -d /tmpfs/src/github/grpc
Archive:  /tmp/tmp.V5MdPp8zdq
  inflating: /tmpfs/src/github/grpc/reports/index.html  
  inflating: /tmpfs/src/github/grpc/c_linux_ubsan_native/sponge_log.xml  
+ rm -f /tmp/tmp.V5MdPp8zdq
+ docker rm -f run_tests_ee82fa35-9f64-4d5c-8264-4b6f17e0c2d5
run_tests_ee82fa35-9f64-4d5c-8264-4b6f17e0c2d5
+ exit 2
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1448, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 2
```
The same as `h2_ssl_proxy_test`
https://sponge.corp.google.com/invocation?id=f8531aeb-cfdd-46f3-b207-901aa682e762&searchFor=

### PR DESCRIPTION
**Pull request by muxi**
Fixes #12892

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +48  +0.0%

  [ = ]       0 TOTAL      +48  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +208  +0.0%

  [ = ]       0 TOTAL     +208  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_unary_ping_pong.BM_UnaryPingPong_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__512_512.opt.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Basic Tests C++ Linux [opt] - #13695 
Basic Tests Multi-language Linux - #13757 
Basic Tests Windows [dbg] - #13149

**Pull request merged**
