### PR TITLE
Try fixing python artifact build on Windows

### PR DESCRIPTION
**Pull request by jtattermusch**
Tentative fix for https://github.com/grpc/grpc/issues/11111

### CODE REVIEW

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/3427/

**Comment by jtattermusch** [comment]
Artifact is still broken, not sure what's the best way to fix.

**Comment by jtattermusch** [comment]
This version of PR is actually not fixing the problem. Any ideas how to actually fix it?

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/30/

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/11178
https://github.com/grpc/grpc/issues/11179
https://github.com/grpc/grpc/issues/11116
https://github.com/grpc/grpc/issues/9153
https://github.com/grpc/grpc/issues/11180
https://github.com/grpc/grpc/issues/11117

**Pull request merged**
