### PR TITLE
Introduced "lb_enabled" to grpc_lb_policy_args.

### PR DESCRIPTION
**Pull request by dgquintas**
As well as a way to specify its value in a sockaddr_resolver URI (for testing
purposes mostly).

### CODE REVIEW

**Comment by dgquintas** [comment]
@ctiller FYI

**Comment by dgquintas** [comment]
Note that the new code will be fully tested and put to full use in the upcoming lb implementation

**Comment by ctiller** [comment]
I think I need some explanation on what this is useful for

**Comment by dgquintas** [comment]
For the propagation of the LB nature of a name resolution.

**Comment by ctiller** [comment]
But why does the LB policy need to know?
Couldn't this be wholly contained in the resolver?

**Comment by dgquintas** [comment]
True... I was working under the assumption that the LB behavior when a resolution is not for a set of load balancers would live inside the LB policy, but it doesn't need to: the discrimination can indeed happen wholly in the resolver. Closing.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
