### PR TITLE
Fix issue #9597

### PR DESCRIPTION
**Pull request by ppietrasa**
Generate consistently named PDBs for libraries across generators and install those PDBs if present.

### CODE REVIEW

**Comment by jtattermusch** [comment]
you also need to run tools/buildgen/generate_projects.sh  to   update content of CMakeLists.txt (and not just the template).

**Comment by ppietrasa** [comment]
@jtattermusch I know. I did run it locally. The CMakeListst.txt was successfully generated and I tested that it works.

I intentionally did not include the re-generated file in the pull request to minimize the risk that it conflicts with changes coming from other pull requests. I thought you might want to regenerate the file yourself after you go over and approve the pull requests. Note, I myself authored another request (#9615) which impacts the generated CMakeLists.txt.

**Comment by jtattermusch** [comment]
@ppietrasa please just add the generated CMakeLists.txt to this PR, because without it I can't really run the CI tests (which is what I'd like to check first).

**Comment by ppietrasa** [comment]
@jtattermusch done

**Comment by jtattermusch** [comment]
test this please

**Comment by jtattermusch** [comment]
Known failures: 
- https://github.com/grpc/grpc/issues/9620
- https://github.com/grpc/grpc/issues/9668
- https://github.com/grpc/grpc/issues/9669

**Pull request merged**
