### PR TITLE
Prepare to remove insecure credentials from grpc++

### PR DESCRIPTION
**Pull request by jiangtaoli2016**
First step of limit internal use of insecure channel

### CODE REVIEW

**Comment by jiangtaoli2016** [comment]
Only changed BUILD file. Did not change Make and cmake.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by vjpai** [comment]
This will break API, won't it? If this is intended for internal users, can we just prevent internal users from using these creds rather than making a change at OSS? (Perhaps by an internal presubmit check or by disabling this feature in the internal build system.)

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,588      Total (=)      1,964,588

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,886,802      Total (<)     10,886,808

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,588      Total (=)      1,964,588

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,886,802      Total (<)     10,886,805

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jiangtaoli2016** [comment]
@vjpai How can we enforce visibility control if we don't separate insecure credentials from grpc++. Ideally, if user wants to use insecure channel, she/he use grpc++_unsecure, if user wants to use secure, she/he grpc++. That is one step forward to adding enforcement.

**Pull request closed without merging**
