### PR TITLE
Check content type on the client response path

### LINKED ISSUE #4711: Check content type on the client response path
Currently http_client_filter ignores the content type. We should check it (as per http_server_filter)

### PR DESCRIPTION
**Pull request by dgquintas**
Fixes #4711

### CODE REVIEW

**Comment by dgquintas** [comment]
Ping :)

**Comment by sreecha** [comment]
LGTM.

**Comment by dgquintas** [comment]
Failures are flakes due to executions under very high load.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
