### PR TITLE
grpc: support static linked c-ares on win32

### PR DESCRIPTION
**Pull request by franksinankaya**
When c-ares is static linked, all applications using c-ares need to pass a preprocessor definition during compilation. This CFLAGS is only present in the pkgconfig. Prefer pkgconfig over cmake find_package.

@donnadionne

### CODE REVIEW

**Comment by franksinankaya** [comment]
Any feedback?

**Comment by franksinankaya** [comment]
any comments? Why is the build not running?

**Comment by jtattermusch** [comment]
> any comments? Why is the build not running?

A maintainer needs to mark the contribution as "safe to run" before it gets executed on our infrastructure.

**Comment by franksinankaya** [comment]
Can I have another build run please?

**Comment by franksinankaya** [comment]
> Can I have another build run please?

@jtattermusch : ping?

**Comment by franksinankaya** [comment]
can I have a build run / review please?

**Comment by franksinankaya** [comment]
Please don't close.

I'm still waiting for someone's attention to have a code review.

**Comment by franksinankaya** [comment]
Anyone?

**Comment by yashykt** [comment]
@apolcyn ping :)

**Comment by apolcyn** [comment]
@franksinankaya I'm re-running tests. The last run seems to have failed but it may have been from a while ago.

Since this PR edits files under `templates`, an you please make sure that you've ran `tools/buildgen/generate_projects.sh` on the latest commit.

**Comment by franksinankaya** [comment]
Sorry, one year turnaround time is a very long time to keep any context around.
I no longer have a repro environment.
I'm unable to follow up on this anymore.

**Pull request closed without merging**
