### PR TITLE
Update root pem certs

### PR DESCRIPTION
**Pull request by yihuazhang**

### CODE REVIEW

**Review by nicolasnoble — APPROVED** [review]

**Comment by yihuazhang** [comment]
Hi @nicolasnoble, I further removed the certificate for DST Root CA X3 which is expired a couple of hours ago (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/), and it seems the source of truth - https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt has yet been updated.

**Comment by cdelguercio** [comment]
Will this make its way to the python package? I would assume not since I think python uses the certifi certs.

**Comment by yihuazhang** [comment]
The internal failed test is flaky and MacOS failures are unrelated to this PR.

**Comment by jdlourenco** [comment]
Is this going to be released? I've bumped into this and I've come up with a workaround but it would be nice to start using this fix.

Thanks

**Comment by yihuazhang** [comment]
Per https://github.com/grpc/grpc/releases schedule, the next release (pre-release) will happen in a week or so. I will also try cherry-picking #27539 into v.1.41.0 later this week.

**Pull request merged**
