### PR TITLE
Add a results_upon_error setter to fake resolver

### PR DESCRIPTION
**Pull request by AspirinSJL**
Extracted from #13671 to unblock #14170.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/14281)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.0%    +296 [None]                                                             +1.92Ki  +0.0%
   +27%    +320 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +320   +27%
      [NEW]    +150 grpc_fake_resolver_response_generator_set_response_upon_error         +150  [NEW]
       +41%     +56 grpc_fake_resolver_response_generator_set_response                     +56   +41%
       +90%     +46 fake_resolver_channel_saw_error_locked                                 +46   +90%
       +15%     +32 [Unmapped]                                                             +32   +15%
       +30%     +27 set_response_closure_fn                                                +27   +30%
       +22%      +9 fake_resolver_destroy                                                   +9   +22%

  +0.1%    +616 TOTAL                                                              +2.23Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Looks good!  I have a couple of cosmetic comments, but I'll go ahead and approve, so you can merge as soon as those are addressed.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc, line 64 at r1](https://reviewable.io:443/reviews/grpc/grpc/14281#-L4M2fX_c2-OMLIDjrLp:-L4M2fX_c2-OMLIDjrLq:b-1q9ate) ([raw file](https://github.com/grpc/grpc/blob/63f8f95b7be2799f841a870c28119d812d1d533d/src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc#L64)):*
> ```cpp
>   grpc_channel_args* results_upon_error;
> 
>   // A copy of the most-recently used resolution results.
> ```

Please add a TODO that this can go away once pick_first is changed to not throw away its subchannels, since that will eliminate its dependence on`channel_saw_error_locked()` causing an immediate resolver return.

---

*[src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc, line 167 at r1](https://reviewable.io:443/reviews/grpc/grpc/14281#-L4M3I9B_iFJOO-7HEQB:-L4M3I9B_iFJOO-7HEQC:b44ayyl) ([raw file](https://github.com/grpc/grpc/blob/63f8f95b7be2799f841a870c28119d812d1d533d/src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc#L167)):*
> ```cpp
> } set_response_closure_arg;
> 
> static void set_response_closure_fn(void* arg, grpc_error* error) {
> ```

As long as we're in here, please rename this to `set_response_locked()`, to make it clear that this runs inside the combiner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14281#-:-L4M4FML6QYn1WUrSJ2M:bh8c645)*

**Comment by markdroth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/core/client_channel/resolvers/fake_resolver_test.cc, line 85 at r1](https://reviewable.io:443/reviews/grpc/grpc/14281#-L4M4c6xIGY25VhhvxHo:-L4M4c6xIGY25VhhvxHp:b-yd2yk6) ([raw file](https://github.com/grpc/grpc/blob/63f8f95b7be2799f841a870c28119d812d1d533d/test/core/client_channel/resolvers/fake_resolver_test.cc#L85)):*
> ```cpp
>       grpc_lb_addresses_create(num_addresses, nullptr);
>   for (size_t i = 0; i < num_addresses; ++i) {
>     gpr_asprintf(&uri_string, "ipv4:127.0.0.1:100%lu",
> ```

Note that `%lu` is not portable.  You'll need to use `PRIuPTR` instead.

---

*[test/core/client_channel/resolvers/fake_resolver_test.cc, line 88 at r1](https://reviewable.io:443/reviews/grpc/grpc/14281#-L4M4iqahRwjG2RBCaW5:-L4M4iqahRwjG2RBCaW6:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/63f8f95b7be2799f841a870c28119d812d1d533d/test/core/client_channel/resolvers/fake_resolver_test.cc#L88)):*
> ```cpp
>                  test_counter * num_addresses + i);
>     grpc_uri* uri = grpc_uri_parse(uri_string, true);
>     gpr_asprintf(&balancer_name, "balancer%lu",
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14281)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.0%    +296 [None]                                                             +1.92Ki  +0.0%
   +27%    +320 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +320   +27%
      [NEW]    +150 grpc_fake_resolver_response_generator_set_response_upon_error         +150  [NEW]
       +41%     +56 grpc_fake_resolver_response_generator_set_response                     +56   +41%
       +90%     +46 fake_resolver_channel_saw_error_locked                                 +46   +90%
       +15%     +32 [Unmapped]                                                             +32   +15%
       +30%     +27 set_response_closure_fn                                                +27   +30%
       +22%      +9 fake_resolver_destroy                                                   +9   +22%

  +0.1%    +616 TOTAL                                                              +2.23Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by AspirinSJL** [comment]
Thanks!

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc, line 64 at r1](https://reviewable.io:443/reviews/grpc/grpc/14281#-L4M2fX_c2-OMLIDjrLp:-L4MWRmPPM_pIcqa_kH5:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63f8f95b7be2799f841a870c28119d812d1d533d/src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc#L64)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO that this can go away once pick_first is changed to not throw away its subchannels, since that will eliminate its dependence on`channel_saw_error_locked()` causing an immediate resolver return.
</blockquote></details>

Done.

---

*[src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc, line 167 at r1](https://reviewable.io:443/reviews/grpc/grpc/14281#-L4M3I9B_iFJOO-7HEQB:-L4MWT00RF77BUVlxvoo:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63f8f95b7be2799f841a870c28119d812d1d533d/src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc#L167)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As long as we're in here, please rename this to `set_response_locked()`, to make it clear that this runs inside the combiner.
</blockquote></details>

Done.

---

*[test/core/client_channel/resolvers/fake_resolver_test.cc, line 85 at r1](https://reviewable.io:443/reviews/grpc/grpc/14281#-L4M4c6xIGY25VhhvxHo:-L4MWVYOthzcp2_HubJK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63f8f95b7be2799f841a870c28119d812d1d533d/test/core/client_channel/resolvers/fake_resolver_test.cc#L85)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that `%lu` is not portable.  You'll need to use `PRIuPTR` instead.
</blockquote></details>

Done.

---

*[test/core/client_channel/resolvers/fake_resolver_test.cc, line 88 at r1](https://reviewable.io:443/reviews/grpc/grpc/14281#-L4M4iqahRwjG2RBCaW5:-L4MWWsbborWW4R07xR1:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/63f8f95b7be2799f841a870c28119d812d1d533d/test/core/client_channel/resolvers/fake_resolver_test.cc#L88)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14281#-:-L4MWPBhkhtGb_ekl5G3:b-ucfknh)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.0%    +296 [None]                                                             +1.93Ki  +0.0%
   +27%    +320 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +320   +27%
      [NEW]    +150 grpc_fake_resolver_response_generator_set_response_upon_error         +150  [NEW]
      [NEW]    +117 set_response_closure_locked                                           +117  [NEW]
       +41%     +56 grpc_fake_resolver_response_generator_set_response                     +56   +41%
       +90%     +46 fake_resolver_channel_saw_error_locked                                 +46   +90%
       +15%     +32 [Unmapped]                                                             +32   +15%
       +22%      +9 fake_resolver_destroy                                                   +9   +22%

  +0.1%    +616 TOTAL                                                              +2.24Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.0%    +296 [None]                                                             +1.93Ki  +0.0%
   +27%    +320 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +320   +27%
      [NEW]    +150 grpc_fake_resolver_response_generator_set_response_upon_error         +150  [NEW]
      [NEW]    +117 set_response_closure_locked                                           +117  [NEW]
       +41%     +56 grpc_fake_resolver_response_generator_set_response                     +56   +41%
       +90%     +46 fake_resolver_channel_saw_error_locked                                 +46   +90%
       +15%     +32 [Unmapped]                                                             +32   +15%
       +22%      +9 fake_resolver_destroy                                                   +9   +22%

  +0.1%    +616 TOTAL                                                              +2.24Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                          FILE SIZE
 ++++++++++++++ GROWING                                                            ++++++++++++++
  +0.0%    +296 [None]                                                             +1.93Ki  +0.0%
   +27%    +320 src/core/ext/filters/client_channel/resolver/fake/fake_resolver.cc    +320   +27%
      [NEW]    +150 grpc_fake_resolver_response_generator_set_response_upon_error         +150  [NEW]
      [NEW]    +117 set_response_closure_locked                                           +117  [NEW]
       +41%     +56 grpc_fake_resolver_response_generator_set_response                     +56   +41%
       +90%     +46 fake_resolver_channel_saw_error_locked                                 +46   +90%
       +15%     +32 [Unmapped]                                                             +32   +15%
       +22%      +9 fake_resolver_destroy                                                   +9   +22%

  +0.1%    +616 TOTAL                                                              +2.24Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by markdroth** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/14281)*

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
Basic Tests MacOS [dbg] (internal CI): #14291
Basic Tests MacOS [opt] (internal CI): #14291

**Pull request merged**
