### PR TITLE
specify metaclasses in a py3-compatible way

### PR DESCRIPTION
**Pull request by leifurhauks**
re: #5648 , #282

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
This is OK to test.

**Comment by nathanielmanistaatgoogle** [comment]
I would never have guessed that that's how many interfaces are in the codebase...

**Comment by jtattermusch** [comment]
Please add an explicit LGTM and then i'll be able to merge.

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: LGTM

**Pull request merged**
