### PR TITLE
Parse FilterChainMatch from LDS response

### PR DESCRIPTION
**Pull request by yashykt**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25530)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks like a great start!

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25530#-:-MUKWRyA3ieqN2psu-bF:b9kv8rc)* status: all files reviewed, 12 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.h, line 244 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUGIkoQAsr47RfCNYts:-MUGIkoQAsr47RfCNYtt:bjppm3n) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L244)):*
> ```objc
>     std::vector<HttpFilter> http_filters;
> 
>     struct FilterChain {
> ```

This also needs an actual list of filters.  Although the only filter we're going to support right now is the `HttpConnectionManager` filter, so we don't need any registry or anything; we can just hard-code the HCM config.

I suggest a structure like the following:

```
struct LdsUpdate {
  enum class ListenerType {
    kTcpListener = 0,
    kHttpApiListener,
  } type;

  struct HttpConnectionManager {
    std::string route_config_name;
    Duration max_stream_duration;
    absl::optional<RdsUpdate> rds_update;
    struct HttpFilter {
      // ...
    };
    std::vector<HttpFilter> http_filters;
  };

  struct FilterChain {
    struct FilterChainMatch {
      // ...
    } filter_chain_match;

    DownstreamTlsContext downstream_tls_context;

    // This is in principle the filter list.
    // We currently require exactly one filter, which is the HCM.
    HttpConnectionManager http_connection_manager;
  };

  // Populated for type=kHttpApiListener.
  HttpConnectionManager http_connection_manager;

  // Populated for type=kTcpListener.
  std::vector<FilterChain> filter_chains;
  absl::optional<FilterChain> default_filter_chain;
};
```
___
*[src/core/ext/xds/xds_api.h, line 246 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKR7aZ4tf690aT81vv:-MUKR7aZ4tf690aT81vw:b-dv5sx3) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L246)):*
> ```objc
>     struct FilterChain {
>       struct FilterChainMatch {
>         uint32_t destination_port = 0;
> ```

Since we know that any value here will cause us to fail the match, I think we can not include this field here.  Instead, when we are parsing the proto, we can just skip any entry that has this set (i.e., not return it as part of the `LdsUpdate` at all), since we know it will never be used.
___
*[src/core/ext/xds/xds_api.h, line 270 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKRM6e-RRVekINdhT4:-MUKRM6e-RRVekINdhT5:bmnddx4) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L270)):*
> ```objc
>         std::vector<CidrRange> source_prefix_ranges;
>         std::vector<uint32_t> source_ports;
>         std::vector<std::string> server_names;
> ```

Same here -- we don't need this field, because we don't need to return entries with this field set at all.
___
*[src/core/ext/xds/xds_api.h, line 271 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKRRytBkc0BoGFhK_t:-MUKRRytBkc0BoGFhK_u:b8rep1o) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L271)):*
> ```objc
>         std::vector<uint32_t> source_ports;
>         std::vector<std::string> server_names;
>         std::string transport_protocol;
> ```

Same here -- if we see a value other than `raw_buffer` for this, we can just not return the entry at all.
___
*[src/core/ext/xds/xds_api.h, line 272 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKRWtv7IECtq2shjbR:-MUKRWtv7IECtq2shjbS:b-8n8m9c) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L272)):*
> ```objc
>         std::vector<std::string> server_names;
>         std::string transport_protocol;
>         std::vector<std::string> application_protocols;
> ```

Same here -- any value in this field means that we don't need to return the entry.
___
*[src/core/ext/xds/xds_api.cc, line 469 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKLDVyEsAxmCH-4faz:-MUKLDVyEsAxmCH-4fb-:b-1n9itb) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L469)):*
> ```cpp
>     contents.push_back(absl::StrCat("destination_port=", destination_port));
>   }
>   std::vector<std::string> prefix_ranges_content;
> ```

Maybe execute these next few lines only if `!prefix_ranges.empty()`?
___
*[src/core/ext/xds/xds_api.cc, line 482 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKLKqx1uQMXg2gi7tq:-MUKLKqx1uQMXg2gi7tr:b-ld8bv4) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L482)):*
> ```cpp
>     contents.push_back("source_type=EXTERNAL");
>   }
>   std::vector<std::string> source_prefix_ranges_content;
> ```

Similar comment here -- do this only if `!source_prefix_ranges.empty())`.
___
*[src/core/ext/xds/xds_api.cc, line 513 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKLVUMDvBwu3CFHuIa:-MUKLVUN3jqy3riOPaT5:b-cm1lfk) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L513)):*
> ```cpp
> 
> std::string XdsApi::LdsUpdate::FilterChain::ToString() const {
>   return absl::StrFormat("{filter_chain_match=%s, downstream_tls_context=%s}",
> ```

This will also need to log the HCM filter config.
___
*[src/core/ext/xds/xds_api.cc, line 1774 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKTfqP8YZ-PxuSF9Dt:-MUKTfqP8YZ-PxuSF9Du:br636r5) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L1774)):*
> ```cpp
>           filter_chain_match_proto);
>   if (destination_port != nullptr) {
>     filter_chain_match.destination_port =
> ```

See comments in the .h file about skipping entries with fields that we know will cause us to never match the entry.
___
*[src/core/ext/xds/xds_api.cc, line 1869 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKTpuCBLFrDNWcwAc2:-MUKTpuD8c_9w7pWjrZN:b-hciyo6) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L1869)):*
> ```cpp
> }
> 
> XdsApi::LdsUpdate::FilterChain FilterChainParse(
> ```

This will also need to parse the filter list itself, which must contain only the HCM filter.

To do this, we'll also need to make the changes we talked about a couple of weeks ago:
- Refactor the HCM config parsing logic out of `LdsResponseParseClient()`, so that it can be called both from there and from here.
- Add two new methods to `XdsHttpFilterImpl` that return a bool to indicate whether the filter is supported on the client and server side, respectively.
- Add a parameter to the refactored function for parsing the HCM config to indicate whether it's being called on the server side or the client side.  The code can use that parameter to check whether any given filter is supported on the side it's being called from.
___
*[src/core/ext/xds/xds_api.cc, line 1902 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKVvcZ6FuZ4F8y-qJq:-MUKVvcZ6FuZ4F8y-qJr:bdbpgqf) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L1902)):*
> ```cpp
>   auto* filter_chains =
>       envoy_config_listener_v3_Listener_filter_chains(listener, &size);
>   // TODO(yashykt): Remove following if block when FilterChainMatch
> ```

Any reason not to do this as part of this PR?  Seems a little odd to add the parsing without actually using it for anything. :)
___
*[src/core/ext/xds/xds_api.cc, line 1906 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKVpHL-5Y_nGlS3GDf:-MUKVpHL-5Y_nGlS3GDg:byjfp9b) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L1906)):*
> ```cpp
>   if (size == 0) {
>     return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
>         "Atleast one filter chain needed.");
> ```

"At least" is two words, not one.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25530)* status: 2 of 3 files reviewed, 12 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.h, line 244 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUGIkoQAsr47RfCNYts:-MUUVFfj4Ni5J8nRbLtn:bssnvv) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L244)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This also needs an actual list of filters.  Although the only filter we're going to support right now is the `HttpConnectionManager` filter, so we don't need any registry or anything; we can just hard-code the HCM config.

I suggest a structure like the following:

```
struct LdsUpdate {
  enum class ListenerType {
    kTcpListener = 0,
    kHttpApiListener,
  } type;

  struct HttpConnectionManager {
    std::string route_config_name;
    Duration max_stream_duration;
    absl::optional<RdsUpdate> rds_update;
    struct HttpFilter {
      // ...
    };
    std::vector<HttpFilter> http_filters;
  };

  struct FilterChain {
    struct FilterChainMatch {
      // ...
    } filter_chain_match;

    DownstreamTlsContext downstream_tls_context;

    // This is in principle the filter list.
    // We currently require exactly one filter, which is the HCM.
    HttpConnectionManager http_connection_manager;
  };

  // Populated for type=kHttpApiListener.
  HttpConnectionManager http_connection_manager;

  // Populated for type=kTcpListener.
  std::vector<FilterChain> filter_chains;
  absl::optional<FilterChain> default_filter_chain;
};
```
</blockquote></details>

I have some questions on how the filters need to be parsed. Also, I'd prefer doing that in a subsequent PR
___
*[src/core/ext/xds/xds_api.h, line 246 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKR7aZ4tf690aT81vv:-MUUVVRO1H95bolrDVDn:b99ni4r) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L246)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Since we know that any value here will cause us to fail the match, I think we can not include this field here.  Instead, when we are parsing the proto, we can just skip any entry that has this set (i.e., not return it as part of the `LdsUpdate` at all), since we know it will never be used.
</blockquote></details>

As discussed, we cannot skip entries because the match algorithm does not allow us to.
___
*[src/core/ext/xds/xds_api.h, line 270 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKRM6e-RRVekINdhT4:-MUUVc-c7tzKOBTVAYH9:b99ni4r) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L270)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here -- we don't need this field, because we don't need to return entries with this field set at all.
</blockquote></details>

As discussed, we cannot skip entries because the match algorithm does not allow us to.
___
*[src/core/ext/xds/xds_api.h, line 271 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKRRytBkc0BoGFhK_t:-MUUVclDBEQuWaSdLPn9:b99ni4r) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L271)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here -- if we see a value other than `raw_buffer` for this, we can just not return the entry at all.
</blockquote></details>

As discussed, we cannot skip entries because the match algorithm does not allow us to.
___
*[src/core/ext/xds/xds_api.h, line 272 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKRWtv7IECtq2shjbR:-MUUVdJa-OzwsKwih1Ai:b99ni4r) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.h#L272)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here -- any value in this field means that we don't need to return the entry.
</blockquote></details>

As discussed, we cannot skip entries because the match algorithm does not allow us to.
___
*[src/core/ext/xds/xds_api.cc, line 469 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKLDVyEsAxmCH-4faz:-MUUVfsD0Vdglvq3OHkU:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L469)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Maybe execute these next few lines only if `!prefix_ranges.empty()`?
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 482 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKLKqx1uQMXg2gi7tq:-MUUVgSv6_n-soKxSwgE:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L482)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Similar comment here -- do this only if `!source_prefix_ranges.empty())`.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 513 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKLVUMDvBwu3CFHuIa:-MUUVhPf0Yrf1bYKn0w1:b-hi1ruz) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L513)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This will also need to log the HCM filter config.
</blockquote></details>

I'd prefer to add the HCM filter config in a subsequent PR.
___
*[src/core/ext/xds/xds_api.cc, line 1774 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKTfqP8YZ-PxuSF9Dt:-MUUVm-HD9UocrZub-6N:b99ni4r) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L1774)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

See comments in the .h file about skipping entries with fields that we know will cause us to never match the entry.
</blockquote></details>

As discussed, we cannot skip entries because the match algorithm does not allow us to.
___
*[src/core/ext/xds/xds_api.cc, line 1869 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKTpuCBLFrDNWcwAc2:-MUUVn77E7g-9ZcF1QMl:bjxau5w) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L1869)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This will also need to parse the filter list itself, which must contain only the HCM filter.

To do this, we'll also need to make the changes we talked about a couple of weeks ago:
- Refactor the HCM config parsing logic out of `LdsResponseParseClient()`, so that it can be called both from there and from here.
- Add two new methods to `XdsHttpFilterImpl` that return a bool to indicate whether the filter is supported on the client and server side, respectively.
- Add a parameter to the refactored function for parsing the HCM config to indicate whether it's being called on the server side or the client side.  The code can use that parameter to check whether any given filter is supported on the side it's being called from.
</blockquote></details>

I'd prefer to do this in a subsequent PR
___
*[src/core/ext/xds/xds_api.cc, line 1902 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKVvcZ6FuZ4F8y-qJq:-MUUVqpT-pucw5GIfRWz:bd1d9gy) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L1902)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Any reason not to do this as part of this PR?  Seems a little odd to add the parsing without actually using it for anything. :)
</blockquote></details>

The FilterChainMatch algorithm itself is pretty interesting. I want it as a separate PR.
___
*[src/core/ext/xds/xds_api.cc, line 1906 at r1](https://reviewable.io/reviews/grpc/grpc/25530#-MUKVpHL-5Y_nGlS3GDf:-MUUVzSS--xIu3i-vUeO:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d0922c823dab1a11cb7d07ae36c7a6b50c2caf02/src/core/ext/xds/xds_api.cc#L1906)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

"At least" is two words, not one.
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
This looks good!   I'm looking forward to seeing the follow-up PRs for implementing filter chain matching and refactoring HCM config parsing to use on server side.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25530#-:-MUnwjfm-gJwd3U8on_x:blb18gf)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by yashykt** [comment]
Thanks for reviewing!

**Pull request merged**
