### PR TITLE
Change strview.data() to string(strview) (porting to v1.33.x)

### PR DESCRIPTION
**Pull request by donnadionne**

### CODE REVIEW

**Review by stanley-cheung — APPROVED** [review]

**Review by markdroth — APPROVED** [review]

**Comment by donnadionne** [comment]
There are some failures; however they are unrelated to the fix. The failures are one of the two categories:

MacOs tools updated
Windows tools updated

**Comment by donnadionne** [comment]
Bazel RBE MSAN C/C++ failure is unrelated to the fix

**Comment by donnadionne** [comment]
All required tests pass, just need permission to merge this fix into the release

**Comment by srini100** [comment]
Force merging as the failing tests are not related to this PR.

**Pull request merged**
