### PR TITLE
Fixes leak in test_cancel_after_client_done & cancel_after_accept

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM

**Comment by ctiller** [comment]
Looks like this triggers some new failures - but the approach looks right.

**Comment by dgquintas** [comment]
@ctiller PTAL. Failures are flakes. I've filed the corresponding issues: https://github.com/grpc/grpc/issues/6669, https://github.com/grpc/grpc/issues/6668

**Comment by sreecha** [comment]
LGTM.

**Comment by ctiller** [comment]
LGTM

**Comment by dgquintas** [comment]
Merging right away, sorry @jtattermusch :)

**Pull request merged**
