### PR TITLE
remove core_stats.h from installed headers

### PR DESCRIPTION
**Pull request by toanju**
core_stats.h is installed in a non standard directory and originates
from the source directory. Hence this PR removes it from beeing
installed.

### CODE REVIEW

**Comment by vjpai** [comment]
Thanks for pointing this out. This needs to be done a little differently, and I can take it over.

**Comment by vjpai** [comment]
Reopening so that you can get credit for the commit. I'll send another commit to this branch.

**Comment by vjpai** [comment]
@dgquintas : can you provide a secondary review on this PR? Thanks!

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by dgquintas** [comment]
I assume "generate_projects" was run as usual, correct?

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Yes, I ran that.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Thanks again for your contribution!

**Comment by toanju** [comment]
Thanks to you, I wasn't really aware of the Makefile generation. Seems I was reading the header too briefly to spot the remark. So it's rather thanks to you since you did most of the job :)

**Pull request merged**
