### PR TITLE
Add PHP to jenkins

### PR DESCRIPTION
**Pull request by stanley-cheung**
* For issue #1920 
 * Tested by building the docker image via this command: `tools/jenkins/grpc_jenkins_slave$ sudo docker build -t grpc/grpc_jenkins_slave .`
 * And running the script: `sudo platform=linux language=php GIT_URL=https://github.com/grpc/grpc.git ./run_jenkins.sh`

### CODE REVIEW

**Comment by stanley-cheung** [comment]
Some logs as proof:

```
Using /usr/local/rvm/gems/ruby-2.1.5
START: make
PASSED: make [time=71.5sec]
START: tools/run_tests/build_php.sh
PASSED: tools/run_tests/build_php.sh [time=4.4sec]
START: src/php/bin/run_tests.sh
PASSED: src/php/bin/run_tests.sh [time=2.9sec]
SUCCESS: All tests passed
++ cat docker.cid
+ DOCKER_CID=7b584498ac376235812026f57790957a095d7c38616e5fd12dfbad4d59fd88b8
+ '[' '' == '' ']'
+ echo 'Docker finished successfully, deleting the container 7b584498ac376235812026f57790957a095d7c38616e5fd12dfbad4d59fd88b8'
Docker finished successfully, deleting the container 7b584498ac376235812026f57790957a095d7c38616e5fd12dfbad4d59fd88b8
+ docker rm 7b584498ac376235812026f57790957a095d7c38616e5fd12dfbad4d59fd88b8
7b584498ac376235812026f57790957a095d7c38616e5fd12dfbad4d59fd88b8
```

**Comment by jtattermusch** [comment]
run ci

**Comment by jtattermusch** [comment]
[run ci]

**Comment by jtattermusch** [comment]
[0G[2K[1;30mSTART[0m: make
[0G[2K[0;32mPASSED[0m: make [time=157.0sec]
[0G[2K[1;30mSTART[0m: tools/run_tests/build_php.sh
[0G[2K[0;32mPASSED[0m: tools/run_tests/build_php.sh [time=13.7sec]
[0G[2K[1;30mSTART[0m: src/php/bin/run_tests.sh
[0G[2K
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
PHPUnit 3.6.10 by Sebastian Bergmann.


Starting test 'CallTest::testAddEmptyMetadata'.
I0616 04:08:05.390008452    7372 call.c:1201] grpc_call_start_batch(call=0x1573f90, ops=0x7ffcf22275d0, nops=1, tag=0x1573f90)
I0616 04:08:05.390053796    7372 call.c:1201] ops[0]: SEND_INITIAL_METADATA
I0616 04:08:05.419153583    7372 completion_queue.c:285] RETURN_EVENT[0x157d450]: OP_COMPLETE: tag:0x1573f90 OK
.
Starting test 'CallTest::testAddSingleMetadata'.
I0616 04:08:05.421130895    7372 call.c:1201] grpc_call_start_batch(call=0x1619920, ops=0x7ffcf22275d0, nops=1, tag=0x1619920)
I0616 04:08:05.421168672    7372 call.c:1201] ops[0]: SEND_INITIAL_METADATA
key=key value=76 61 6c 75 65 'value'
I0616 04:08:05.519036766    7372 completion_queue.c:285] RETURN_EVENT[0x157d450]: OP_COMPLETE: tag:0x1619920 OK
.
Starting test 'CallTest::testAddMultiValueMetadata'.
I0616 04:08:05.520563036    7372 call.c:1201] grpc_call_start_batch(call=0x1622140, ops=0x7ffcf22275d0, nops=1, tag=0x1622140)
I0616 04:08:05.520582618    7372 call.c:1201] ops[0]: SEND_INITIAL_METADATA
key=key value=76 61 6c 75 65 31 'value1'
key=key value=76 61 6c 75 65 32 'value2'
I0616 04:08:05.618961413    7372 completion_queue.c:285] RETURN_EVENT[0x157d450]: OP_COMPLETE: tag:0x1622140 OK
.
Starting test 'CallTest::testAddSingleAndMultiValueMetadata'.
I0616 04:08:05.620491667    7372 call.c:1201] grpc_call_start_batch(call=0x162ad30, ops=0x7ffcf22275d0, nops=1, tag=0x162ad30)
I0616 04:08:05.620518496    7372 call.c:1201] ops[0]: SEND_INITIAL_METADATA
key=key1 value=76 61 6c 75 65 31 'value1'
key=key2 value=76 61 6c 75 65 32 'value2'
key=key2 value=76 61 6c 75 65 33 'value3'
I0616 04:08:05.718957788    7372 completion_queue.c:285] RETURN_EVENT[0x157d450]: OP_COMPLETE: tag:0x162ad30 OK
.
Starting test 'EndToEndTest::testSimpleRequestBody'.
I0616 04:08:05.720720936    7372 call.c:1201] grpc_call_start_batch(call=0x16342c0, ops=0x7ffcf22275d0, nops=2, tag=0x16342c0)
I0616 04:08:05.720740247    7372 call.c:1201] ops[0]: SEND_INITIAL_METADATA
I0616 04:08:05.720749849    7372 call.c:1201] ops[1]: SEND_CLOSE_FROM_CLIENT
Segmentation fault
[0;31mFAILED[0m: src/php/bin/run_tests.sh [ret=139, pid=7357]

**Comment by stanley-cheung** [comment]
hm, some kind of flake? I tried to run a few times in a gce instance but they all worked. Let's investigate this tomorrow.

**Comment by jtattermusch** [comment]
I'll merge this, but I am only including this under "unstable" in jenkins for now.
https://grpc-testing.appspot.com/job/gRPC%20unstable/

If we see php passing most of the time in "unstable", I can add it to the main test matrix on jenkins.

**Pull request merged**
