### PR TITLE
Export function gpr_log_severity_string for grpc_csharp_ext

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by dgquintas** [comment]
What motivates this change?

**Comment by KindDragon** [comment]
Errors that occurs when you trying to build grpc as DLL

**Comment by jtattermusch** [comment]
On Mon, May 22, 2017 at 11:15 AM, Arkady Shapkin <notifications@github.com>
wrote:

> Errors that occurs when you trying to build grpc as DLL
>
Please also post more details about that error. Our windows build seems to
be working just fine.

**Comment by KindDragon** [comment]
Issue #11261

**Pull request merged**
