### PR TITLE
Use thread pool from concurrent-ruby on ruby server

### PR DESCRIPTION
**Pull request by apolcyn**
This changes the server to use a thread pool from the concurrent-ruby gem, which can grow and shrink, and keep a queue.

### CODE REVIEW

**Comment by murgatroid99** [comment]
You have to update `templates/grpc.gemspec.template` and rerun `tools/buildgen/genereate_projects.sh`. Other than that, LGTM. It's nice seeing a lot of red in the diff.

**Comment by kpayson64** [comment]
@apolcyn @murgatroid99 I see several ruby test failures.  The ruby tests are usually pretty well behaved, so I'm hesitant to re-run the basic tests until we get a success because these might be real race conditions.

If you guys think they are just flakes, feel free to re-run the tests.

**Comment by apolcyn** [comment]
@kpayson64 it looks to me like these failures might actually be existing bugs. I'm able to make these same errors occur with this PR, but also with both the current master and v1.0.x branches. 

I'm not sure what we want to do about this PR, but I think this error is unrelated to this change, creating a separate issue for it https://github.com/grpc/grpc/issues/7972.

**Comment by kpayson64** [comment]
@apolcyn Thanks for verifying! I'll go ahead with the merge.

**Pull request merged**
