### PR TITLE
Add certificate provider registry implementation

### PR DESCRIPTION
**Pull request by yashykt**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24080)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
Just one minor suggestion.  Otherwise, looks great!

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24080#-:-MGnxKGe8L-XDjtXQFpY:b-oi1b2m)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[src/core/ext/xds/certificate_provider_registry.cc, line 57 at r1](https://reviewable.io/reviews/grpc/grpc/24080#-MGnw_Mc72jx0RHcGGaq:-MGnw_Mc72jx0RHcGGar:b-qo9v3k) ([raw file](https://github.com/grpc/grpc/blob/cdda406115252be5dbb6a8b32d31bc680d2c8024/src/core/ext/xds/certificate_provider_registry.cc#L57)):*
> ```cpp
>   // hurting performance (which is unlikely, since these allocations
>   // only occur at gRPC initialization time).
>   absl::InlinedVector<std::unique_ptr<CertificateProviderFactory>, 3>
> ```

Why not just use `std::map<>` here?  That would make lookups more efficient at run-time.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24080)* status: all files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[src/core/ext/xds/certificate_provider_registry.cc, line 57 at r1](https://reviewable.io/reviews/grpc/grpc/24080#-MGnw_Mc72jx0RHcGGaq:-MGo3Sez9MndA7qAh2Yb:b-iiaacm) ([raw file](https://github.com/grpc/grpc/blob/cdda406115252be5dbb6a8b32d31bc680d2c8024/src/core/ext/xds/certificate_provider_registry.cc#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why not just use `std::map<>` here?  That would make lookups more efficient at run-time.
</blockquote></details>

I don't have data for this, but from sounds like for a small number of elements vectors are faster than std::map.

**Review by markdroth — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24080)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/core/ext/xds/certificate_provider_registry.cc, line 57 at r1](https://reviewable.io/reviews/grpc/grpc/24080#-MGnw_Mc72jx0RHcGGaq:-MGoSFlhCNdhe_-SP_Z_:byi78fn) ([raw file](https://github.com/grpc/grpc/blob/cdda406115252be5dbb6a8b32d31bc680d2c8024/src/core/ext/xds/certificate_provider_registry.cc#L57)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I don't have data for this, but from sounds like for a small number of elements vectors are faster than std::map.
</blockquote></details>

A map seems more natural to me, but I guess it doesn't really matter.  This is fine for now.

**Comment by yashykt** [comment]
Issues: #24092, #24093

**Comment by yashykt** [comment]
Thanks for reviewing!

**Pull request merged**
