### PR TITLE
[Test] Add the callback support in scenario_config.py

### LINKED ISSUE #33216: Scenario_config.py does not support "callback".
The current version of scenario_config.py only supports the "sync" and "async". However, we plan to prioritize the "callback" in the future. Therefore, is it necessary to add support for "callback" to scenario_config.py?

### PR DESCRIPTION
**Pull request by LeiW000**
Fix #33216.

### CODE REVIEW

**Review by paulosjca — APPROVED** [review]

**Comment by LeiW000** [comment]
Can the PR be merged? Or, is there any other comment?

**Comment by paulosjca** [comment]
> Can the PR be merged? Or, is there any other comment?

It has formatting issues right now. I would suggest syncing to the latest and then running `./tools/distrib/black_code.sh`.

If the issue is resolved it should be fine to merge.

**Comment by LeiW000** [comment]
Yesterday, I updated the PR to address the conflict.

**Comment by sergiitk** [comment]
Yea, the we changed code style to black. Sorry for any inconvenience it caused. 
Looks like the conflict was resolved correctly wrt code style change:

```
2023-06-12 17:02:12,273 START: tools/distrib/black_code.sh
2023-06-12 17:02:31,331 PASSED: tools/distrib/black_code.sh [time=19.1sec, retries=0:0]
```

The test fails because for another reason: 

> `qps benchmark scenarios have been updated, please commit test/cpp/qps/qps_json_driver_scenarios.bzl and/or test/cpp/qps/json_run_localhost_scenarios.bzl`  
> — https://source.cloud.google.com/results/invocations/1bc2ea3e-72c5-4120-9bac-52dd08913eb2/targets/github%2Fgrpc%2Frun_tests%2Fsanity_linux_dbg_native%2Ftools%2Frun_tests%2Fsanity%2Fcheck_qps_scenario_changes.py/tests

AFAIK this is fixed by running `./test/cpp/qps/json_run_localhost_scenario_gen.py`, as  @ctiller pointed out.

**Review by sergiitk — APPROVED** [review]
LGTM as long as PR checks pass.

**Comment by LeiW000** [comment]
@sergiitk @paulosjca , Thanks for your help on it. I just updated the PR again. Please take a look at it again.

**Comment by paulosjca** [comment]
I see more errors in the tests. Could you please run the following and upload again?

```shell
./tools/distrib/gen_experiments_and_format.sh
```

**Comment by LeiW000** [comment]
I run "./tools/distrib/gen_experiments_and_format.sh". But there is nothing happening. No code change in my workspace after running it.

**Comment by paulosjca** [comment]
> I run "./tools/distrib/gen_experiments_and_format.sh". But there is nothing happening. No code change in my workspace after running it.

Thanks there are more issues such as **Bazel RBE ASAN C/C++** tests. I am reassigning this to @sergiitk.

**Comment by sergiitk** [comment]
This doesn't seem to be related to any of the python code style changes. I'll re-assign this to @ctiller - he's one of the most recent folks who reviewed `test/cpp/qps/json_run_localhost_scenarios.bzl`.

**Comment by sergiitk** [comment]
Hey @jtattermusch - maybe you could help?

**Comment by LeiW000** [comment]
I rebased the code base and re-submitted the PR. Could you help to trigger the tests? I would like to see if they can pass with the latest code.

**Comment by paulosjca** [comment]
> I rebased the code base and re-submitted the PR. Could you help to trigger the tests? I would like to see if they can pass with the latest code.

Looks like the Bazel RBE tests still fail.

**Comment by jtattermusch** [comment]
CC @drfloob

**Comment by LeiW000** [comment]
We plan to prioritize the "callback". That is why I'm adding the "callback" support in scenario_config.py.

**Comment by drfloob** [comment]
We do want to enable some callback API benchmarks, soon. I've started an internal thread about benchmark framework resources. If necessary, we may be able to find some middle ground where a subset of the callback API tests are run to begin with.

**Comment by drfloob** [comment]
@jtattermusch , for some added context

> we'd have to have a good reason to add more of these tests 

Plans are to start making the callback API faster this year. We're still laying the ground work for it, but we'll need baseline benchmarks to compare against before long (months).

> I'm not even sure if the "callback" API is supported in gRPC C++ externally at this point

It is supported, and we have recommended it. Performance-sensitive customers may not want to adopt it yet, but we're working towards a future where it is the most performant option.

**Comment by drfloob** [comment]
Completed in https://github.com/grpc/grpc/pull/36055

**Pull request closed without merging**
