### PR TITLE
Fix C core build breakage

### PR DESCRIPTION
**Pull request by jcanizales**
Oh Jenkins :(

### CODE REVIEW

**Comment by murgatroid99** [comment]
Argh. I fixed this in #3100, but it looks like the change disappeared. On a related note, you might want to fix the include line without deleting it entirely.

**Comment by a-veitch** [comment]
#3194 also fixes this, without deleting the include line.

**Comment by murgatroid99** [comment]
@a-veitch That change is exactly the same as this one, and it does delete the include line.

**Comment by a-veitch** [comment]
My bad - misreading something else. I agree with keeping the include. Will comment on other one as well.

**Comment by jcanizales** [comment]
As Hongyu explained, the include is already there, if you expand the diff a bit down.

**Pull request merged**
