### PR TITLE
Ensure Lib is Initialize for ByteBuffer Use

### PR DESCRIPTION
**Pull request by ncteisen**
I did not mean to take this out in #14541

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                            FILE SIZE
 ++++++++++++++ GROWING                              ++++++++++++++
  +0.0%     +21 [None]                                  +373  +0.0%
  +2.6%     +51 src/cpp/util/byte_buffer_cc.cc           +51  +2.6%
       +52%     +51 _GLOBAL__sub_I_byte_buffer_cc.cc         +51   +52%

  +0.0%     +72 TOTAL                                   +424  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
This needs to be in the next import

**Pull request merged**
