### PR TITLE
[support PHP7] control code by version of PHP macro

### PR DESCRIPTION
**Pull request by thinkerou**
@stanley-cheung Please review this PR

I have not use the follow code style:

    #if PHP_MAJOR_VERSION < 7
       // all supports php5 codes
    #else
       // all supports php7 codes
    #endif

But use the follow code style:
    
    function()
    {
    #if PHP_MAJOR_VERSION < 7
       // all supports php5 codes in function
    #else
       // all supports php7 codes in function
    }

So, ~~I only commit `timeval` code~~, I committed all codes now, we should agree on code style.

If we use second method, it will prepare to use php7_wrapper in the future.

What do you think?

### CODE REVIEW

**Comment by stanley-cheung** [comment]
LGTM. Please proceed with the rest. Thanks

**Comment by stanley-cheung** [comment]
Fixes #4337

**Comment by thinkerou** [comment]
Now unit test is OK on php5 and php7, please review this PR @stanley-cheung thanks!

**Comment by thinkerou** [comment]
Hi, @stanley-cheung I have squashed all commits to one commit to be good for review.

About the PR:

1. Supported `PHP5.*`, `PHP7.0` and `7.1.0alpha1` by marco

2. Run right for all unit test cases on all PHP version(>=5.5)

3. Added some unit test cases

4. Added some TODO(like: crash, unit test)

5. Fixed all PHP files format by `run_php_cs_fixer.sh`

And then we should do this.... https://github.com/thinkerou/grpc-php7/issues/4

**Comment by stanley-cheung** [comment]
@murgatroid99 Can you please see if you have any major objection? 

@thinkerou Thanks for the great work here. Let's hold the PR in this state for now for the review. Let's hold off on making more changes for now. Thanks!

**Comment by murgatroid99** [comment]
I skimmed through it, and I don't see anything particularly out of place. I do hope that in the future, we can decrease the code duplication and us a compatibility library (like php7_wrapper appears to be).

**Comment by stanley-cheung** [comment]
LGTM. Let me wait for the tests to finish. Can you also make a similar PR for the `v1.0.x` branch please? Thanks.

**Comment by thinkerou** [comment]
Yeth, OK.

**Comment by stanley-cheung** [comment]
I believe at this time `master` and `v1.0.x` for PHP is at the exact same footing. So just apply the same change to the `v1.0.x` branch should be fine.

**Comment by thinkerou** [comment]
@stanley-cheung Done, please review #7487

**Comment by stanley-cheung** [comment]
Verified this compiles and installs properly on both php5 and php7 and both manually and as a pecl package. Also passed unit tests and generated code tests on both platform

**Pull request merged**
