### PR TITLE
Add an end-to-end test that includes a client-side fork.

### PR DESCRIPTION
**Pull request by bdhess**
@veblush - I tried to boil down the issue I was describing to you into a reproducible test case, and it turns out everything works fine at head, we just had an order-of-operations issue.  This test case covers our usage.

### CODE REVIEW

**Review by veblush — APPROVED** [review]
Sorry for the late review!

**Comment by veblush** [comment]
To get this merged, two things needs to be done;

 1. run tools/buildgen/generate_projects.sh
 2. address `test/cpp/end2end/client_fork_test.cc:18:#include <pthread.h>` from `tools/run_tests/sanity/cpp_banned_constructs.sh`. you may want to add a new exception there.

**Comment by veblush** [comment]
and xSAN tests failed so those errors need to be fixed.

**Comment by drfloob** [comment]
I've continued this work in #31035

**Pull request closed without merging**
