### PR TITLE
Build experimental nugets with dotnet CLI

### PR DESCRIPTION
**Pull request by jtattermusch**
Adds a set of experimental NuGet packages created by `dotnet pack` command. These experimental nugets target both net45 and netstandard1.5.
The production nugets are already getting built on Windows and that's not changing until we verify that the new nugets work properly on all supported platforms and support older version of tooling as well (VS2013, monodevelop, mono, xamarin studio).

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @jskeet  (you might care about the lines that install dotnet cli in a debian-based dockerfile).

**Comment by jskeet** [comment]
Ta. Had been using the Ubuntu version in my PR, but good to hear this works. Will give that a try next :)

**Comment by jtattermusch** [comment]
Ubuntu 14.04 has worked for me as well, using the instructions from https://www.microsoft.com/net/core#ubuntu

**Comment by jtattermusch** [comment]
@apolcyn  let's get this PR in early.

**Comment by apolcyn** [comment]
LGTM

**Comment by jtattermusch** [comment]
test failures are unrelated.

**Pull request merged**
