### PR TITLE
[C++] Add admin and reflection to xds interop binaries

### PR DESCRIPTION
**Pull request by lidizheng**
This is based on @menghanl 's https://github.com/grpc/grpc/pull/25851. Let's see if tests are happy now.

Also, this PR needs to be cherry-picked.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25964)

### CODE REVIEW

**Comment by lidizheng** [comment]
@gnossen @yashykt PTAL. This PR adds the admin services and reflection services to xDS interop client and server. This should allow the test driver to fetch xDS configs for C++ tests.

The hack about "_xds" suffix can be found: [cl/364351425](http://cl/364351425). Basically, it hides Envoy protos in google3, so it won't be counted as Core component dependency violation.

**Review by gnossen — APPROVED** [review]

**Review by yashykt — APPROVED** [review]

**Comment by lidizheng** [comment]
@yashykt There was a conflict between this PR and https://github.com/grpc/grpc/pull/25939. The admin services will add Channelz services just like your PR. It should work the same in OSS (or our xDS staging tests).

**Comment by yashykt** [comment]
I've got a broader question on `AddAdminServices`. Why wasn't this structured as a `ServerBuilderOption` instead?

**Comment by yashykt** [comment]
Also, note that `channelz::experimental::InitChannelzService()` is called by default internally on init.

**Comment by lidizheng** [comment]
Can we register certain services on a specific builder via `ServerBuilderOption`? If we can do it cleanly, I'm happy to change the logic.

The idea is that internally, we have pretty good security to protect our data. But in OSS, we don't want users to register sensitive services along with their primary business serving port.

**Comment by yashykt** [comment]
It seems like we can do it with a ServerBuilderPlugin but for some reason that API is not public. It's not clear to me as to why that's the case, but I guess we don't have a better way then.

**Comment by lidizheng** [comment]
Thanks to https://github.com/grpc/grpc/pull/25980, we no longer needs to cherry-pick this PR. Merging.

**Pull request merged**
