### PR TITLE
Performance tuning discussions

### PR DESCRIPTION
**Pull request by vjpai**

### CODE REVIEW

**Comment by vjpai** [comment]
This is just a PR to make sure that random performance experiments don't kill everything, but yeah, I'm glad to know about this.

**Comment by ctiller** [comment]
NP... it's a concerning lock nevertheless :)

**Comment by vjpai** [comment]
I'll be glad to pick up that discussion with @jboeuf and we can figure this one out.

**Comment by jboeuf** [comment]
@vjpai, do you want to setup a quick meeting with @ctiller, @yang-g and me on this? I will need to refresh my cache on this one...

**Comment by vjpai** [comment]
Idle a long time and likely obsolete

**Pull request closed without merging**
