### PR TITLE
Update function signature in grpc_security

### PR DESCRIPTION
**Pull request by muxi**
Follow-up of #16659. Fix the function definitions.

cc: @nicolasnoble

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,961,233      Total (=)      1,961,233

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,884,242      Total (<)     10,884,245

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Wait, why is this needed? The src files are C++ and this is actually contrary to C++ rules.

**Comment by vjpai** [comment]
I approved this, but should not have done so. Has anyone complained about this? It seems contradictory, since the source files are written in C++ (not C89), and passing a void argument in C++ has specific meaning.

**Comment by muxi** [comment]
In C++ is it not that `func()` and `func(void)` are equivalent?

In fact I'm curious why the linker has been able to link the C declaration to its C++ definition.

**Comment by vjpai** [comment]
Ok, so there is a clause hidden deep in the C++ standard that says that "an unnamed parameter of type void as the only item in the [parameter] list specifies that the function has no parameters" . So technically either form is equivalent if there are no other arguments and the void has no name; this was probably put in the standard just to avoid breaking old C code being built using C++ compilers. That said, it should be viewed as a deprecated special case and not encouraged (IMO); none of our readability examples use this form.

As to how the compilers match them: the compilers match using their IR, not a simple text form (this also handles cases like default parameter values or unnamed parameters in declarations or even typedefs), and the IR for C indicating a function with C linkage and an explicit `(void)` in the parameter list would be the same as that in C++ for a function with C linkage and an empty parameter list.

**Comment by vjpai** [comment]
So with all that said, I would suggest closing this PR unless anyone has specifically complained of a breakage.

**Comment by muxi** [comment]
> it can't participate in any overloads, so the compiler would compile it with C linkage even though those specific words aren't repeated in the source file

That's an indication that they are actually C functions and I say we follow the C style here. Note that for most (funny it's not all) other functions in the same situation we have `(void)` in their definition.

**Comment by vjpai** [comment]
Since we are using this style for most functions, I'll relent and approve.

**Comment by muxi** [comment]
Basic Tests MacOS [opt] - #16672

**Pull request merged**
