### PR TITLE
Upmerge v1.8.x branch (at v1.8.3) into master 

### PR DESCRIPTION
**Pull request by mehrdada**

### CODE REVIEW

**Comment by mehrdada** [comment]
@apolcyn I have resolved the merge to bazel changes basically by picking the master copy and discarding your changes on 1.8.x. I assume that was the intent, i.e. the changes to 1.8.x version were specific to that branch. Please take a look and confirm that none of your changes on 1.8.x that are actually supposed to get to master are lost.

**Comment by apolcyn** [comment]
bazel-related merge lgtm, thanks; looks like nothing affecting the bazel build is modified here, as intended (the bazel build, and other builds, do appear caught on a c-core compilation issue though).

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                           FILE SIZE
 ++++++++++++++ GROWING                             ++++++++++++++
  +0.0%     +16 [None]                                 +144  +0.0%
  +0.9%    +112 src/core/lib/iomgr/ev_poll_posix.cc    +112  +0.9%
      +2.2%     +64 pollset_work                            +64  +2.2%
      +9.6%     +32 fd_orphan                               +32  +9.6%
      +4.6%     +11 fd_create                               +11  +4.6%
      +1.6%      +5 [Unmapped]                               +5  +1.6%

  +0.0%    +128 TOTAL                                  +256  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by mehrdada** [comment]
@apolcyn Yup, fixed the C compile issue. I think the issue I was alluding to was #13468 which was "backported" to 1.8.x, but was never merged to master. I think we're fine then. :)

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by dgquintas** [comment]
There were several new failures introduced in this PR. For example, https://sponge.corp.google.com/target?id=aca73bf4-e13e-4706-9c20-2ba9979f388d&target=github/grpc/c_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Pull request merged**
