### PR TITLE
[Release] Upmerge v1.54.x branch into master

### PR DESCRIPTION
**Pull request by yashykt**
Change was created by the release automation script. See go/grpc-release

### CODE REVIEW

**Review by eugeneo — APPROVED** [review]

**Comment by yashykt** [comment]
The EasyCLA check seems to be broken for co-authors but the authors of the commit https://github.com/grpc/grpc/commit/15d19432aab2772a8d04e61153b2f4b755361980 are @yijiem and @drfloob who have both signed the CLA. Force-merging this PR

**Pull request merged**
