### PR TITLE
Update max-allowed-version of googleauth ruby dependency

### PR DESCRIPTION
**Pull request by apolcyn**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @apolcyn isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by apolcyn** [comment]
I signed it!

**Comment by apolcyn** [comment]
interop test failures: `python:node server` cloud-to-cloud timeout

**Comment by apolcyn** [comment]
I signed it!

**Comment by apolcyn** [comment]
I signed it!

**Pull request merged**
