### PR TITLE
Revert "Treat nanopb as a regular external dep"

### PR DESCRIPTION
**Pull request by AspirinSJL**
Reverts grpc/grpc#15595

Due to internal breakage.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                              ++++++++++++++
  +1.1%     +48 src/core/tsi/alts/handshaker/alts_handshaker_service_api.cc              +48  +1.1%
      +5.6%     +16 grpc_gcp_handshaker_req_param_add_record_protocol                        +16  +5.6%
      +4.8%     +16 grpc_gcp_handshaker_req_param_add_local_identity_hostname                +16  +4.8%
      +4.8%     +16 grpc_gcp_handshaker_req_param_add_local_identity_service_account         +16  +4.8%

 -+-+-+-+-+-+-+ MIXED                                                                +-+-+-+-+-+-+-
  -0.1%    -944 [None]                                                                  +152  +0.0%
     -34.5%    -100 grpc_gcp_StartClientHandshakeReq_fields                                 -100 -34.5%
     -34.5%     -90 [Other]                                                                  -90 -34.5%
     -34.5%     -80 grpc_gcp_HandshakerResult_fields                                         -80 -34.5%
     -34.5%     -70 grpc_gcp_AltsContext_fields                                              -70 -34.5%
     -34.5%     -70 grpc_gcp_StartServerHandshakeReq_fields                                  -70 -34.5%
     -34.5%     -70 grpc_lb_v1_ClientStats_fields                                            -70 -34.5%
     -34.5%     -50 grpc_gcp_HandshakerResp_fields                                           -50 -34.5%
     -34.5%     -50 grpc_lb_v1_Server_fields                                                 -50 -34.5%
     -34.5%     -40 grpc_gcp_Endpoint_fields                                                 -40 -34.5%
     -34.5%     -40 grpc_gcp_HandshakerReq_fields                                            -40 -34.5%
     -34.5%     -30 grpc_gcp_HandshakerStatus_fields                                         -30 -34.5%
     -34.5%     -30 grpc_gcp_Identity_fields                                                 -30 -34.5%
     -34.5%     -30 grpc_gcp_RpcProtocolVersions_Version_fields                              -30 -34.5%
     -34.5%     -30 grpc_gcp_RpcProtocolVersions_fields                                      -30 -34.5%
     -34.5%     -30 grpc_gcp_ServerHandshakeParameters_fields                                -30 -34.5%
     -34.5%     -30 grpc_gcp_StartServerHandshakeReq_HandshakeParametersEntry_fields         -30 -34.5%
     -34.5%     -30 grpc_lb_v1_ClientStatsPerToken_fields                                    -30 -34.5%
     -34.5%     -30 grpc_lb_v1_Duration_fields                                               -30 -34.5%
     -34.5%     -30 grpc_lb_v1_InitialLoadBalanceResponse_fields                             -30 -34.5%
     -34.5%     -30 grpc_lb_v1_LoadBalanceRequest_fields                                     -30 -34.5%
     -34.5%     -30 grpc_lb_v1_LoadBalanceResponse_fields                                    -30 -34.5%

  -0.1%    -896 TOTAL                                                                   +200  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                              cpu_time    real_time
-------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/32768                                           +4%         +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                    -4%         -4%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/1/1  -4%         -4%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/0  -6%         -6%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/1  -6%         -6%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/2097152                        +4%         +4%
```

**Comment by dgquintas** [comment]
Let's not merge this just yet. It may be better to fix stuff.

**Comment by dgquintas** [comment]
Superseded by https://github.com/grpc/grpc/pull/15788

**Pull request closed without merging**
