### PR TITLE
Backport 15262: Provide protocol for initializer of generated messages

### PR DESCRIPTION
**Pull request by muxi**
Backport #15262 to v1.12.x which fixes an issue in #15193.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
@muxi please merge ASAP so I can trigger the build

**Comment by muxi** [comment]
Interop tests failing are #15199. Bazel is unrelated.

**Pull request merged**
