### PR TITLE
Add back artifact builder dockerfiles

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts removal of artifact build dockerfiles that were removed by mistake in https://github.com/grpc/grpc/pull/13145.

Should fix https://github.com/grpc/grpc/issues/13302.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Confirmed that this fixed the artifact build on Linux.

**Comment by jtattermusch** [comment]
Fixes linux artifacts, merging early.

**Pull request merged**
