### PR TITLE
Bumping protobuf submodule to beta-3-pre1.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Fixing #6516.

**Comment by nicolasnoble** [comment]
Ran an artificat build from that PR: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_distribtest/723/

**Comment by jtattermusch** [comment]
LGTM, but not sure what's up with the node x86 distribtest.
@murgatroid99

**Comment by murgatroid99** [comment]
I don't know what's happening there, but it works on x64, and the problems on the x86 test seem to be unrelated to anything we're doing.

**Pull request merged**
