### PR TITLE
Include linux/version.h in port_platform.h

### PR DESCRIPTION
**Pull request by yashykt**
Include <linux/version.h> only if __GLIBC__ is not defined.. i.e. this is not a system with musl library.

Tested manually on alpine 3.5

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
ping @nicolasnoble

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%    +873 [None]                                                                               +15.5Ki  +0.2%
      +0.1%    +905 [Unmapped]                                                                           +15.5Ki  +0.2%
      [NEW]      +8 grpc_core::(anonymous namespace)::timestamps_callback                                      0  [ = ]
   +19% +1.36Ki src/core/lib/iomgr/tcp_posix.cc                                                      +1.36Ki   +19%
      [NEW]    +875 process_errors                                                                          +875  [NEW]
       +40%    +358 tcp_flush                                                                               +358   +40%
      +203%    +158 tcp_handle_error                                                                        +158  +203%
      [NEW]    +135 tcp_annotate_error(grpc_error*, (anonymous namespace)::grpc_tcp*) [clone .isra.2]       +135  [NEW]
      +0.6%      +1 [Unmapped]                                                                                +1  +0.6%
 +16e2%    +444 src/core/lib/iomgr/buffer_list.cc                                                       +444 +16e2%
      [NEW]    +195 grpc_core::TracedBuffer::ProcessTimestamp                                               +195  [NEW]
      [NEW]    +135 grpc_core::TracedBuffer::AddNewEntry                                                    +135  [NEW]
      [NEW]    +103 grpc_core::TracedBuffer::Shutdown                                                       +103  [NEW]
      [NEW]     +31 [Unmapped]                                                                               +31  [NEW]
  +100%      +3 src/core/lib/iomgr/internal_errqueue.cc                                                   +3  +100%
      +100%      +3 kernel_supports_errqueue                                                                  +3  +100%

  +0.2% +2.65Ki TOTAL                                                                                +17.3Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,960,914      Total (=)      1,960,914

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,883,158      Total (>)     10,883,157

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1% +1.09Ki [None]                                                                               +12.9Ki  +0.1%
      +0.2% +1.08Ki [Unmapped]                                                                           +12.9Ki  +0.1%
      [NEW]      +8 grpc_core::(anonymous namespace)::timestamps_callback                                      0  [ = ]
      [NEW]      +4 g_default_client_tcp_user_timeout_ms                                                      +4  [NEW]
      [NEW]      +4 g_default_server_tcp_user_timeout_ms                                                      +4  [NEW]
      [NEW]      +1 g_default_client_tcp_user_timeout_enabled                                                  0  [ = ]
      [NEW]      +1 g_default_server_tcp_user_timeout_enabled                                                 +1  [NEW]
   +19% +1.36Ki src/core/lib/iomgr/tcp_posix.cc                                                      +1.36Ki   +19%
      [NEW]    +875 process_errors                                                                          +875  [NEW]
       +40%    +358 tcp_flush                                                                               +358   +40%
      +203%    +158 tcp_handle_error                                                                        +158  +203%
      [NEW]    +135 tcp_annotate_error(grpc_error*, (anonymous namespace)::grpc_tcp*) [clone .isra.2]       +135  [NEW]
      +0.6%      +1 [Unmapped]                                                                                +1  +0.6%
   +20%    +768 src/core/lib/iomgr/socket_utils_common_posix.cc                                         +768   +20%
     +17e2%    +714 grpc_set_socket_tcp_user_timeout                                                        +714 +17e2%
      [NEW]    +206 error_for_fd(int, grpc_resolved_address const*) [clone .part.2]                         +206  [NEW]
     +24e2%     +49 config_default_tcp_user_timeout                                                          +49 +24e2%
      [NEW]      +7 grpc_ntohs(unsigned short) [clone .localalias.4]                                          +7  [NEW]
      +2.4%      +5 [Unmapped]                                                                                +5  +2.4%
 +16e2%    +444 src/core/lib/iomgr/buffer_list.cc                                                       +444 +16e2%
      [NEW]    +195 grpc_core::TracedBuffer::ProcessTimestamp                                               +195  [NEW]
      [NEW]    +135 grpc_core::TracedBuffer::AddNewEntry                                                    +135  [NEW]
      [NEW]    +103 grpc_core::TracedBuffer::Shutdown                                                       +103  [NEW]
      [NEW]     +31 [Unmapped]                                                                               +31  [NEW]
  +100%      +3 src/core/lib/iomgr/internal_errqueue.cc                                                   +3  +100%
      +100%      +3 kernel_supports_errqueue                                                                  +3  +100%

  +0.2% +3.63Ki TOTAL                                                                                +15.4Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yashykt** [comment]
Thanks for reviewing! and a beautiful green tick for all checks passing

**Pull request merged**
