### PR TITLE
Fixing invalid usage of getProtobufServiceAttrs() function.

### PR DESCRIPTION
**Pull request by dmitriykovalev**
getProtobufServiceAttrs(service, options) must be called with 2 arguments.

### CODE REVIEW

**Comment by dmitriykovalev** [comment]
@murgatroid99 , I'm trying to merge a simple fix for nodejs code, the build has failed with:

ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from http://github.com/grpc/grpc.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1066)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

Should I just resubmit the pull request or it is somehow possible to run the build again?

**Comment by murgatroid99** [comment]
this is ok to test

**Comment by murgatroid99** [comment]
LGTM

**Comment by murgatroid99** [comment]
OK, it looks like all of the test failures are unrelated

**Pull request merged**
