### PR TITLE
Improvements to Debian packaging targeting unstable

### PR DESCRIPTION
**Pull request by andrewpollock**
Contributions from Laszlo Boszormenyi, who is the other Debian Developer who was independently working packaging gRPC.

Some cleanup, make rebuildable.

This is for #662

### CODE REVIEW

**Comment by nicolasnoble** [comment]
@googlebot everything is okay, don't worry.

**Comment by gcsideal** [comment]
Just to be extra sure, I've already signed the CLA, please verify.

**Comment by tbetbetbe** [comment]
Just one minor admin comment.  Could you possibly split this into two PRs ?
- One that just updates the branch from master
- and a follow-up that contains your changes.

**Comment by nicolasnoble** [comment]
Sorry, I didn't spot that I was assigned to this one. And thinking about it, wouldn't it be better to base that from the release-0_9 branch so to truly have a 0.9.1 release ?

**Comment by andrewpollock** [comment]
> And thinking about it, wouldn't it be better to base that from the release-0_9 branch so to truly have a 0.9.1 release

Okay so bear with me, I'm new to doing collaborative development in Git and using Github. 

So are you asking me to merge the release-0_9 into my debian/sid branch and then send a PR from my debian/sid branch into the one on grpc/grpc?

And I presume that means I abandon this PR?

**Comment by nicolasnoble** [comment]
I'm going to close this one since it's abandoned.

**Pull request closed without merging**
