### PR TITLE
Add project overview for gsoc submission

### PR DESCRIPTION
**Pull request by thunderboltsid**
@nathanielmanistaatgoogle Please go through the content and give some feedback. Also please add the necessary labels. 

P.S. This needs to get merged as soon as the final amendments are done so I can use the link for submission..

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
I think it looks great. Let's merge it now (since we want a link to it to work now) and we can always make changes later.

@kpayson64, @nicolasnoble: please merge this documentation-only change this evening or first thing tomorrow morning?

**Comment by nathanielmanistaatgoogle** [comment]
@thunderboltsid: if you felt like making a change: the directory could be named "2016", since the "gsoc" is redundant with it being under "summerofcode".

**Comment by thunderboltsid** [comment]
@nathanielmanistaatgoogle made the change to directory name. I'd really prefer having it merged today as tomorrow morning in SF can easily be post deadline UTC.

**Comment by kpayson64** [comment]
I can merge this once the portability tests/interop tests pass.  The "Merge pull request" box is grayed out.  I'll make sure it happens tonight.

**Pull request merged**
