### PR TITLE
Update Python for Protobuf 4.21

### PR DESCRIPTION
**Pull request by gnossen**
This PR needs to be added atomically to the protobuf update. It does the following:

- Drops support for Python 3.6.
- Updates test infrastructure to install protobuf 4.X wheels (a major version bump)
- Fixes a latent bug in the test runner where individual modules were loaded multiple times
  - Previously, this bug was benign since protobuf module loading was idempotent
  - `AddSerializedFile` now returns `None` on subsequent invocations
- Regenerates generated code in `examples/python/`

### CODE REVIEW

**Comment by gnossen** [comment]
@yashykt Heads up. I've got this _almost_ working. There's [one last issue to be worked out with type checking](https://source.cloud.google.com/results/invocations/d6209b55-af27-4299-9104-9e5ad75eb802/log) for the new generated code. I think I should be able to have this resolved by COB Monday.

**Comment by gnossen** [comment]
@yashykt I think all Python-related issues are now resolved. Feel free to merge this PR into yours.

**Comment by jtattermusch** [comment]
Looks like this can be closed (the update was already done here: https://github.com/grpc/grpc/pull/30377/commits/6886c0f197a6ae7ecd9f8bb727c6051009e99759)

**Comment by gnossen** [comment]
Right. This contents of this PR were merged into Yash's protobuf update PR. Going ahead and closing this one.

**Pull request closed without merging**
