### PR TITLE
Fix undefined behavior introduced in #16167.

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                             FILE SIZE
 ++++++++++++++ GROWING                                               ++++++++++++++
  +0.1%     +48 src/core/ext/filters/client_channel/client_channel.cc     +48  +0.1%
      +3.7%     +48 start_transport_op_locked                                 +48  +3.7%

 -+-+-+-+-+-+-+ MIXED                                                 +-+-+-+-+-+-+-
  -0.0%     -16 [None]                                                    +88  +0.0%

  +0.0%     +32 TOTAL                                                    +136  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,975,943      Total (>)      1,975,935

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,774,674      Total (<)     10,774,676

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Known failures: #14240

**Pull request merged**
