### PR TITLE
Teach the release notes script to find GitHub Squash and Merge PRs

### PR DESCRIPTION
**Pull request by drfloob**
In preparation for enabling GitHub Squash and Merge for Pull Requests.

Running this script on the drfloob/grpc_clone_for_pr repo results in a draft file that contains both the merge commit and the GitHub-flavored "squash and merge" commit:

```

...
PRs with missing release notes label - please fix in Github
---

- drfloob@ -  Ahead multi commits. ([#1](https://github.com/drfloob/grpc_clone_for_pr/pull/1))
- drfloob@ -  GitHub merge multi commits. ([#2](https://github.com/drfloob/grpc_clone_for_pr/pull/2))
...

```

### CODE REVIEW

**Review by markdroth — COMMENTED** [review]
This looks reasonable to me, but I'm not so familiar with this code, so I think @srini100 should review.

**Comment by srini100** [comment]
Why do we want both commits to show in the draft release notes? Isn't the PR commit sufficient as before even if you are doing squash and merge?

**Comment by drfloob** [comment]
I accidentally re-requested a review from you @markdroth . Please disregard.

I'd appreciate the review, Srini!

**Comment by markdroth** [comment]
Srini, this doesn't show duplicate commits; it just adds handling for both types of commits (merges and squashes).

**Review by srini100 — APPROVED** [review]
Got it. LGTM, assuming it uncommon to see (#NUMBER) in commit messages.

**Comment by drfloob** [comment]
Thanks @srini100. Our release notes import drafts may have false positive commits with `(#NUMBER)` in the messages, but 1) we do review the draft manually before we send out release notes, and 2) we can eliminate that problem if we only allow squash & merge (decision TBD).

**Comment by drfloob** [comment]
Known issue for InsecureIntraopTest #23934

**Pull request merged**
