### PR TITLE
C++ windows tests linking

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Tests are now compiling, linking, and running using run_tests, both in debug and release. Some are still not passing, but merging that will help us finding what's going on by sharing the love.

**Comment by pgrosu** [comment]
@nicolasnoble By the Law of Thelema? :smile:

**Comment by ctiller** [comment]
LGTM. Merge on green (and thankyou!)

**Comment by nicolasnoble** [comment]
*sigh* turns out I broke C#. I'll revisit this by doing it on the GA branch.

**Pull request closed without merging**
