### PR TITLE
Unreferenced buffer pointer for ruby grpc.

### PR DESCRIPTION
**Pull request by alienchow**
Attempted fix for issue #5476

### CODE REVIEW

**Comment by ctiller** [comment]
This is ok to test

**Comment by murgatroid99** [comment]
LGTM

**Comment by alienchow** [comment]
The python tests failed for a ruby ext change. I'm confused. Will need to check why.

**Comment by murgatroid99** [comment]
The Python tests are failing for everything right now. If that's the only failure, then this is fine.

**Comment by jtattermusch** [comment]
Ruby tests are failing

```
make: Leaving directory '/var/local/git/grpc'
Generating Makefile for grpc/grpc_c
creating Makefile
cd -
cd tmp/x86_64-linux/grpc_c/2.1.5
/usr/bin/make
compiling ../../../../src/ruby/ext/grpc/rb_call_credentials.c
compiling ../../../../src/ruby/ext/grpc/rb_server.c
compiling ../../../../src/ruby/ext/grpc/rb_byte_buffer.c
../../../../src/ruby/ext/grpc/rb_byte_buffer.c: In function 'grpc_rb_byte_buffer_to_s':
../../../../src/ruby/ext/grpc/rb_byte_buffer.c:56:28: error: initialization makes integer from pointer without a cast [-Werror]
   VALUE output_rb_string = NULL;
                            ^
cc1: all warnings being treated as errors
Makefile:224: recipe for target 'rb_byte_buffer.o' failed
make: *** [rb_byte_buffer.o] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-compiler-0.9.6/lib/rake/extensiontask.rb:152:in `block (2 levels) in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-compiler-0.9.6/lib/rake/extensiontask.rb:151:in `block in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => compile => compile:x86_64-linux => compile:grpc_c:x86_64-linux => copy:grpc_c:x86_64-linux:2.1.5 => tmp/x86_64-linux/grpc_c/2.1.5/grpc_c.so
(See full trace by running task with --trace)
Command exited with non-zero status 1
real 25.24
user 52.98
sys 14.67
```

**Comment by murgatroid99** [comment]
A VALUE should be initialized with `Qnil` instead of `NULL`. VALUE is not a pointer type.

**Comment by murgatroid99** [comment]
This has been superseded by #6004.

**Pull request closed without merging**
