### PR TITLE
Channel idleness

### PR DESCRIPTION
**Pull request by bigfacebear**
Add an idle filter to client channel. Switch the channel state to IDLE after a period of time not using it.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/19634)

### CODE REVIEW

**Comment by bigfacebear** [comment]
Thanks for reviewing!
I have not solved comments about atomic operations yet. As Soheil said, they could be very tricky and still need to be discussed.
As the simpler solution Mark mentioned, I will create a new branch to implement it after this PR works correctly and then compare the performance of these two approaches.

**Comment by bigfacebear** [comment]
I made all operations on `call_count_` RELAXED because I think `call_count_` does not guard any other variable but is just an atomic counter. When a thread finds itself increases the `call_count_` from 0 to 1, it checks and write the atomic variable `state_` without looking at others. There is no way to guarantee that the expected `state_` value has been set by `DecreaseCallCount()` who previously decreases the `call_count_` from 1 to 0, even if we change the memory order on `call_count_` to ACQ_REL. That's why I used a loop to wait for the `state_` being properly set.
BTW, as mentioned in [c++ reference](https://en.cppreference.com/w/cpp/atomic/memory_order#Relaxed_ordering), in the implementation of `std::shared_ptr`, increment operation is conducted as RELAXED and decrement operation is conducted as ACQ_REL, because the counter guards the access to data pointer. However, we don't have any data need to be guarded by the counter, so I think we can make both increment and decrement RELAXED.

As for `state_` atomic variable, it does guard the shared access of a non-atomic variable, which is `last_leisure_start_time_`, so we need to RELEASE-store `state_` in cases where there are some other threads care about the updated value of `last_leisure_start_time_` when they see the updated value of `state_`. This case happens when we set `state_` to `LEISURE_FROM_BUSY`, then the `IdleTimerCallback()` will access the updated value of `last_leisure_start_time_` when it sees the `state_` is `LEISURE_FROM_BUSY`. Therefore, I applied release-acquire semantic in this case.

Please let me know if I made any mistake.

**Comment by markdroth** [comment]
Since we've removed the atomics from this PR, I don't think it's necessary to wait for approvals from Soheil or David.

**Comment by bigfacebear** [comment]
#19614 #19422 #19170 #19726

**Pull request merged**
