### PR TITLE
Deduplication of health.proto and math.proto

### PR DESCRIPTION
**Pull request by jtattermusch**
Addresses most of  #3850  (except of python's health.proto and PHP that need to stay on proto2 version of the file).

### CODE REVIEW

**Comment by ctiller** [comment]
Any chance we could flatten src/proto (so... no subdirectories) in the process?

It would make cmake rules sooooooooooooooo much easier to write.

**Comment by jtattermusch** [comment]
I think we could flatten the src/proto dir, but the general guideline to put protos into directories based on their package?

**Comment by jtattermusch** [comment]
The united test failures seem unrelated. Can we decide on flattening the src/proto directory quickly and proceed to merging?

**Comment by jtattermusch** [comment]
If we flatten the protos directory, we won't be able to have multiple versions of health.proto  (currently it's v1alpha). But because it'd expect to have some more versions in the future (v1beta, v1, v2), I think I am against flattening at this point.

**Comment by ctiller** [comment]
Can we do some experimentation. I had problems getting cmake to accept
anything from our project. We'd really like a cmake build file.

Let's try putting this with #4124 and seeing if we can figure it out.

**Comment by ctiller** [comment]
I did some experimentation. I can get the cmake story working with a directory hierarchy given the following constraint:
- C++ projects can only refer to one protobuf file of a given name, regardless of directory hierarchy

@nicolasnoble, @vjpai, @yang-g - thoughts?

**Comment by nicolasnoble** [comment]
I don't think this limitation would be a big issue. We're not overflowing with proto files anyway, and I don't think we will, so we should be fairly safe.

Moreover, two different proto files with the same exact filename in the same C/C++ project is but a source of confusion and mistakes :-)

**Comment by yang-g** [comment]
I think it is ok. Maybe I should change v1alpha1 to v1 since we are not
making changes to it. In the future if we have a v2, then v1 will live with
a previous release and grpc repo only has one health.proto at any given
release. Does it make sense?

**Comment by jtattermusch** [comment]
@yang-g yeah, I think it makes sense. Let's make it in a followup PR?

**Comment by yang-g** [comment]
@jtattermusch OK

**Comment by jtattermusch** [comment]
@murgatroid99 , the travis errors are unrelated. Let's proceed with this PR?

**Pull request merged**
