### PR TITLE
Make gRPC C# nuget work with new project.json style projects

### LINKED ISSUE #4872: C# nuget package doesn't work with DNX-based JSON projects.
```
System.IO.FileNotFoundException: Error loading native library. File does not exist.
File name: 'C:\Users\Jon\.dnx\packages\Grpc.Core\0.13.0\lib\net45\nativelibs\windows_x86\grpc_csharp_ext.dll'
```

If I copy the contents of the grpc.native.csharp package into the right place for that to be found, it works.

It's not clear to me where it's getting that path from to try to load it from... I'd have expected it to try to load it from

```
C:\Users\Jon\.dnx\packages\grpc.native.csharp\0.13.0\build\native\bin\windows_x86
```
(or the x64 equivalent).

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes #4872.

The idea is that when using project.json style projects, assemblies imported from nuget packages (Grpc.Core.dll) don't get copied to the build output directory alongside the compiled assemblies, but they are referenced to directly in the directory where the restored nuget package gets extracted.
So when looking for the native extension library, we also try that alternative.

To make things simpler, this PR also gets rid of the grpc.native.csharp package entirely and moves all the precompiled native libraries to Grpc.Core nuget package (which makes them easier to discover).

### CODE REVIEW

**Comment by jtattermusch** [comment]
FYI @chrisdunelm  @jskeet  as this might be of interest for you.

I actually have more changes coming to add support for CoreCLR support (I have a prototype, but more work is still needed).

**Comment by jskeet** [comment]
Yay - I was wondering just today why we didn't include the native dependencies directly in Grpc.Core. Good to see it happening :)

**Comment by jtattermusch** [comment]
Friendly ping.

**Comment by murgatroid99** [comment]
LGTM

**Pull request merged**
