### PR TITLE
Quickfix for linting in docstring

### LINKED ISSUE #22970: Python generated missing docstrings not according to docstrings standard
### What version of gRPC and what language are you using?
1.28.1 / python

### What operating system (Linux, Windows,...) and version?
Linux.

### What runtime / compiler are you using (e.g. python version or version of gcc)
python3.8

### What did you do?
Create a proto with out comments.

### What did you expect to see?
_pb2_grpc creates docstrings with:
"""Missing associated documentation comment in .proto file."""

### What did you see instead?
"""Missing associated documentation comment in .proto file"""

It is missing a doc which makes linting error from docstring in most style guides:
First line should end with a period, question mark, or exclamation point.

### Anything else we should know about your project / environment?
-

### PR DESCRIPTION
**Pull request by staticdev**
Closes #22970 

This is for Python generator. I couldn't add a label.
Are there unit tests for generated code?

@nicolasnoble this is my first contribution, I intend to do more complex ones as soon as I understand the process.

### CODE REVIEW

**Comment by gnossen** [comment]
The tests associated with the generated code are located [here](https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/protoc_plugin/_python_plugin_test.py).

**Comment by staticdev** [comment]
@gnossen I didn't understand how this Kokoro errors are related to the change I did. I also did not see a test related to the docstring [here](https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/protoc_plugin/_python_plugin_test.py).

**Comment by gnossen** [comment]
@staticdev All of these failures look unrelated:
 - https://github.com/grpc/grpc/issues/22979
 - https://github.com/grpc/grpc/issues/22978

**Comment by gnossen** [comment]
Thans again for the change! 😃

**Pull request merged**
