### PR TITLE
Use 32 bit nanopb fields

### LINKED ISSUE #17145: Firestore broken by nanopb version mismatch
Firestore got broken recently on a nanopb version mismatch problem (see #https://github.com/firebase/firebase-ios-sdk/pull/2046). There's a workaround in place for now but we should probably check if gRPC should has an internal namespaced version of nanopb (at least on iOS, like what we did for BoringSSL)

### PR DESCRIPTION
**Pull request by muxi**
... by replacing all PB_FIELD_16BIT with PB_FIELD_32BIT in gRPC core and ObjC.

Fixes #17145.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by yihuazhang** [comment]
Thanks for the PR. In general, there is no need to modify nanopb output files (i.e., `*pb.c`). I think that's the reason for the sanity check failure.

**Comment by muxi** [comment]
But if I leave it it seems the generated information would be incorrect, something like:
```
YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES
```

**Comment by muxi** [comment]
Actually seems like variable names, which probably is fine.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,021,250      Total (>)      2,020,870

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,177,133      Total (>)     11,177,124

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
@yihuazhang is the current state look good to you?

**Comment by yihuazhang** [comment]
LGTM.

**Pull request merged**
