### PR TITLE
use nullptr instead of NULL

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by vjpai** [comment]
This is ok to test

**Comment by thinkerou** [comment]
Thank you @vjpai for reviewing, I have fix code style and the test run right.

**Comment by jtattermusch** [comment]
@vjpai   please handle or close.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by thinkerou** [comment]
@vjpai please review, thanks!

**Comment by thinkerou** [comment]
all `NULL` have replaced.

**Pull request closed without merging**
