### PR TITLE
gRPC: Add grpc_authorization_provider to CMake

### PR DESCRIPTION
**Pull request by jebr224**
The CMake is missing a build library, and this patch adds it. This library exist in the bazel.

Signed-off-by: John Edward Broadbent <jebr@google.com>

### CODE REVIEW

**Comment by jebr224** [comment]
Request testing labels.

**Comment by jebr224** [comment]
Request testing labels.

**Comment by jtattermusch** [comment]
I skimmed over the changes and the changes to add the `grpc_authorization_provider` library seem fair, as long as that's actually a library that is supposed to be public and to be distributed/installed along with the grpc C++.

@veblush  should know the answers to these questions.

also let's doublecheck the test results, since lots of them seem to be failing.

**Comment by veblush** [comment]
This [window test](https://source.cloud.google.com/results/invocations/3e1461f7-5f36-4cf1-b267-f44ca648032b/log) might be relevant to this PR?

```
  t:\altsrc\github\grpc\workspace_cpp_windows_x86_cmake_as_externalproject\src\core\lib\matchers\matchers.h(28): fatal error C1083: Cannot open include file: 're2/re2.h': No such file or directory (compiling source file 
```

**Comment by veblush** [comment]
`grpc_authorization_provider` cmake target seems to miss `${_gRPC_RE2_LIBRARIES}`. Since it's a bit hard to tweak `CMakeLists.txt.template`, you can consider working on `CMakeLists.txt` first without modifying its template file. This will break sanity test but it'd be much easier to fix it once you get a working CMakeLists.txt with other tests.

**Comment by veblush** [comment]
Closing in favor of https://github.com/grpc/grpc/pull/31308

**Pull request closed without merging**
