### PR TITLE
Attempt to complete TODO: unify these two searches

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by ctiller** [comment]
Thanks for the PR! However, I think this is not quite what I was thinking about here: we need to keep this part of the code as simple as possible, and playing loop tricks, while it does get rid of the duplication in spirit, ends up making the logic harder to follow.

Would you consider breaking out the common parts into a function instead?

**Comment by thinkerou** [comment]
I had considered use the common function, but I think the method will call this new function many a time in for loop. Now I consider to write a function that it includes for loop, I try it.

**Comment by thinkerou** [comment]
If breaks out the common parts into a function instead, the method also need one var which indicated that it use host or not. So the code like this:

    static bool search_by_host_or_not(channel_data *chand, call_data *calld, grpc_server *server,
                   channel_registered_method *rm, bool host) {
      uint32_t hash;
      hash = GRPC_MDSTR_KV_HASH(host ? calld->host->hash : 0, calld->path->hash);

      for (i = 0; i <= chand->registered_method_max_probes; i++) {
        rm = &chand->registered_methods[(hash + i) %
                                    chand->registered_method_slots];
        if (!rm) return false;
        if (host && (rm->host != calld->host)) continue;
        if (!host && (rm->host != NULL)) continue;
        if (rm->method != calld->path) continue;
        if ((rm->flags & GRPC_INITIAL_METADATA_IDEMPOTENT_REQUEST) &&
            !calld->recv_idempotent_request)
          continue;
        finish_start_new_rpc(exec_ctx, server, elem,
                         &rm->server_registered_method->request_matcher,
                         rm->server_registered_method->payload_handling);
        return true;
      }
    }

**Comment by nicolasnoble** [comment]
@ctiller does this work better for you ?

**Comment by jtattermusch** [comment]
No activity here, closing.

**Pull request closed without merging**
