### PR TITLE
csharp: hide the native libraries in Visual Studio project explorer

### LINKED ISSUE #12247: [csharp] native libraries shown in project root layout
### What version of gRPC and what language are you using?

1.4.1 but I think this applies to any project using the new csproj targetting a framework greater or equal than net45. 
 
### What operating system (Linux, Windows, …) and version?
 
Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Doesn't apply.
 
### What did you do?

Include Grpc.Core in a newly formatted csproj.
 
### What did you expect to see?
 
Linked `Content` elements not to be shown by default, I would expect this:

screen shot 2017-08-22 at 07 36 04
 
### What did you see instead?
 
I got this instead:

screen shot 2017-08-22 at 07 44 06
 
### Anything else we should know about your project / environment?

I'm using the new csproj approach which by default inspects all the tree down (*.targets included) and make every file/extension pertaining to its whitelist shown by default.

I tried to modify Visibility status through this:

```
<ItemGroup>
    <Content Update="grpc_csharp_ext.x86.dll" Visible="false" />
</ItemGroup>
```

But it doesn't seem to work.

I think people would like to avoid seeing grpc native libraries in its project root layout

### PR DESCRIPTION
**Pull request by glerchundi**
Closes #12247

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by glerchundi** [comment]
I don't know whats happening but I think the bot got crazy.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Pull request merged**
