### PR TITLE
[C-API] client

### PR DESCRIPTION
**Pull request by tengyifei**
This PR implements all blocking APIs and a async unary call. It has tests for the basic API wrapping layer and for generated code. It supersedes https://github.com/grpc/grpc/pull/7386.

To reviewers:
- `include/grpc_c` contains the public headers that the final user could see.
- `include/grpc_c/codgen` contains the private headers that must be visible to generated code, but shall not be referenced directly in user code.
- `src/c` contains the implementations of those methods defined in `include`.
- `src/compiler/c_generator.cpp` contains the bulk of `grpc_c_plugin` code generator.
- `test/c/end2end` contains end-to-end tests for the APIs.
- `examples/c` contains the `helloworld` and `routeguide` example ported to C demonstrating the usage of the API.

The tests are written in C++, since it depends on a server implementation which the C runtime does not provide yet. As a result they are subsumed under C++ tests and can be run by specifying `-l c++` in the test script.

Since this is a huge PR, I hope to split it into different functional components and have multiple reviewers each going over a section:
- Unary blocking call: `src/c/unary_blocking_call.c`
- Client streaming block call: `src/c/client_streaming_blocking_call.c`
- Server streaming block call: `src/c/server_streaming_blocking_call.c`
- Bidi streaming block call: `src/c/bidi_streaming_blocking_call.c`
- Unary async call: `src/c/unary_async_call.c`

Some useful files:
- `src/c/completion_queue.c` handles unwrapping of tags. A `call_op_set` is always used as tag during async operations. The user tag is stored in the set and is what `completion_queue_next` returns.
- `src/c/call_ops.c` handles filling a `grpc_op` array using operations specified in `call_op_set`. The library can declaratively indicate the actions to be performed in a `call_start_batch`, much like C++.

### CODE REVIEW

**Comment by tengyifei** [comment]
@nicolasnoble Do you have Google CLA?

**Comment by nicolasnoble** [comment]
That thing gets confused if you pull someone else's PR in yours. Yes, I have Google's CLA as I am a Google employee :-)

**Comment by tengyifei** [comment]
Yeah but how do I unconfuse it? ;)

**Comment by pgrosu** [comment]
Just label is "cla: yes" and remove "cla: no" like here:

https://github.com/google/protobuf/pull/361#issuecomment-109549084

**Comment by jtattermusch** [comment]
no action here for >1 year. Closing as code is probably way out of date.

CC @vjpai  @srini100

**Pull request closed without merging**
