### PR TITLE
Upgrade protobuf to 3.15.0-rc2

### PR DESCRIPTION
**Pull request by acozzette**
This pull request should just be merged but is just for testing.

### CODE REVIEW

**Comment by acozzette** [comment]
@jtattermusch Would you mind adding the necessary tags to kick off the tests?

**Comment by gnossen** [comment]
@acozzette There's now some automation around bumping this version. Update [this line](https://github.com/grpc/grpc/blob/a72c72f6e353ffeba7d3a268e7daa8916d48dac0/build_handwritten.yaml#L18) and then run `tools/buildgen/generate_projects.sh`.

**Comment by gnossen** [comment]
You'll have to resolve the merge conflicts before the tests will run.

**Comment by acozzette** [comment]
Thanks, @gnossen. I've now fixed the merge conflicts.

**Comment by acozzette** [comment]
Oh sorry I missed your earlier comment, let me try that script.

**Comment by jtattermusch** [comment]
C++ build error:
```
In file included from /var/local/git/grpc/third_party/protobuf/src/google/protobuf/any.pb.cc:4:
In file included from /var/local/git/grpc/third_party/protobuf/src/google/protobuf/any.pb.h:30:
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/message.h:234:13: error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]
  constexpr Message() {}
            ^
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/message.h:234:13: note: non-literal type 'google::protobuf::MessageLite' cannot be used in a constant expression
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/any.pb.cc:20:16: error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]
constexpr Any::Any(
               ^
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/any.pb.cc:20:16: note: non-literal type '::google::protobuf::Message' cannot be used in a constant expression
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/any.pb.cc:26:13: error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]
  constexpr AnyDefaultTypeInternal()
            ^
/var/local/git/grpc/third_party/protobuf/src/google/protobuf/any.pb.cc:27:7: note: non-literal type 'google::protobuf::Any' cannot be used in a constant expression
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
      ^
[ 12%] Building C object third_party/boringssl-with-bazel/CMakeFiles/crypto.dir/src/crypto/x509/a_digest.c.o
3 errors generated.
third_party/protobuf/CMakeFiles/libprotobuf.dir/build.make:782: recipe for target 'third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/any.pb.cc.o' failed
make[3]: *** [third_party/protobuf/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/any.pb.cc.o] Error 1
CMakeFiles/Makefile2:32528: recipe for target 'third_party/protobuf/CMakeFiles/libprotobuf.dir/all' failed
make[2]: *** [third_party/protobuf/CMakeFiles/libprotobuf.dir/all] Error 2
```
https://source.cloud.google.com/results/invocations/224fef9b-389d-4d35-8834-13b7f8f827a8/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_c%2B%2B_linux_dbg_native_x64_clang3.6_buildonly/tests

-----------------

Ruby failure:

https://source.cloud.google.com/results/invocations/4a8f9191-98be-4b49-811c-9fe786e4e8d6/targets/github%2Fgrpc%2Frun_tests%2Fruby_macos_dbg_native%2Ftools%2Frun_tests%2Fhelper_scripts%2Frun_ruby.sh/tests
```
got echo response: grpc-ruby/1.37.0.dev grpc-c/15.0.0 (osx; chttp2)
  user agent header does not grow when the same channel args hash is used across multiple stubs

Failures:

  1) GRPC::BadStatus to_rpc_status does not raise when decoding a bad proto
     Failure/Error: expect(log_contents).to include "WARN  GRPC : #{error_desc}"

       expected " WARN  GRPC : parse error: to_rpc_status failed\n WARN  GRPC : <Google::Protobuf::ParseError> Error ...n `invoke'\n\t/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'\n" to include "WARN  GRPC : <Google::Protobuf::ParseError> Error occurred during parsing: Invalid wire type"
       Diff:
       @@ -1,34 +1,67 @@
       -WARN  GRPC : <Google::Protobuf::ParseError> Error occurred during parsing: Invalid wire type
       + WARN  GRPC : parse error: to_rpc_status failed
       + WARN  GRPC : <Google::Protobuf::ParseError> Error occurred during parsing
       +	/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc/google_rpc_status_utils.rb:37:in `decode'
       +	/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc/google_rpc_status_utils.rb:37:in `extract_google_rpc_status'
       +	/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/lib/grpc/errors.rb:70:in `to_rpc_status'
       +	/Volumes/BuildData/tmpfs/src/github/grpc/workspace_ruby_macos_dbg_native/src/ruby/spec/errors_spec.rb:130:in `block (3 levels) in <top (required)>'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
       +	/Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-support-3.10.2/lib/rspec/support.rb:102:in `block in <module:Support>'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-support-3.10.2/lib/rspec/support.rb:111:in `notify_failure'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./src/ruby/spec/errors_spec.rb:139:in `block (3 levels) in <top (required)>'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/kbuilder/.rvm/gems/ruby-2.5.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'

Finished in 2.08 seconds (files took 0.49395 seconds to load)
```


python on windows:
```
C:\tools\msys64_win7\mingw64\bin\gcc.exe -mdll -O -Wall -DWIN32_LEAN_AND_MEAN=1 -DMS_WIN64=1 -I. -Igrpc_root -Igrpc_root\include -Ithird_party\protobuf\src -IC:\Python27\include -IC:\Python27\PC -c third_party\protobuf\src\google\protobuf\compiler\java\java_extension_lite.cc -o build\temp.win-amd64-2.7\Release\third_party\protobuf\src\google\protobuf\compiler\java\java_extension_lite.o -std=c++11 -D_ftime=_ftime64 -D_timeb=__timeb64 -D_hypot=hypot
In file included from third_party\protobuf\src/google/protobuf/descriptor.pb.h:23:0,
                 from third_party\protobuf\src\google\protobuf\compiler\js\js_generator.cc:36:
third_party\protobuf\src/google/protobuf/io/coded_stream.h:137:37: fatal error: endian.h: No such file or directory
 #include <endian.h>  // __BYTE_ORDER
                                     ^
compilation terminated.
```


objc:
```
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/test/cpp/ios/Pods/Target\ Support\ Files/RemoteTestCpp/RemoteTestCpp-prefix.pch -MMD -MT dependencies -MF /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fzhnkppkkmzsbwgphcrtztwjhxny/Build/Intermediates.noindex/Pods.build/Cronet-iphonesimulator/RemoteTestCpp.build/Objects-normal/x86_64/simple_messages.grpc.pb.d --serialize-diagnostics /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fzhnkppkkmzsbwgphcrtztwjhxny/Build/Intermediates.noindex/Pods.build/Cronet-iphonesimulator/RemoteTestCpp.build/Objects-normal/x86_64/simple_messages.grpc.pb.dia -c /Volumes/BuildData/tmpfs/src/github/grpTesting failed:
	This file was generated by a newer version of protoc which is
	Incompatible with your Protocol Buffer headers. Please update
	Your headers.
	Unknown type name 'PROTOBUF_PRAGMA_INIT_SEG'
	Expected unqualified-id
	No matching constructor for initialization of '::google::protobuf::internal::ArenaStringPtr'
	Constexpr constructor must initialize all members
	No matching constructor for initialization of 'grpc::testing::StringValue'
	Constexpr constructor must initialize all members
	No matching constructor for initialization of 'grpc::testing::StringValueDefaultTypeInternal'
	Cannot initialize a member subobject of type 'const char *' with an rvalue of type 'int'
	Cannot initialize a member subobject of type 'int' with an lvalue of type 'const char [45]'
	Cannot initialize a member subobject of type 'int' with an lvalue of type 'const ::google::protobuf::internal::MigrationSchema [3]'
	Cannot initialize a member subobject of type 'const google::protobuf::internal::MigrationSchema *' with an lvalue of type 'const ::google::protobuf::Message *const []'
	Cannot initialize a member subobject of type 'const google::protobuf::Message *const *' with an lvalue of type 'const ::google::protobuf::uint32 [16]'
	Cannot initialize a member subobject of type 'const google::protobuf::uint32 *' (aka 'const unsigned int *') with an lvalue of type '::google::protobuf::Metadata [3]'
	Cannot initialize a member subobject of type 'google::protobuf::Metadata *' with an lvalue of type 'const ::google::protobuf::EnumDescriptor **const'
	Cannot initialize a member subobject of type 'int' with an lvalue of type 'const ::google::protobuf::ServiceDescriptor **const'
	Use of undeclared identifier 'PROTOBUF_ATTRIBUTE_WEAK'
	Too many errors emitted, stopping now
	Testing cancelled because the build failed.

** TEST FAILED **
```

**Comment by jtattermusch** [comment]
@lidizheng  since you're the release manager for this grpc release cycle, can you please work with @acozzette  to look into the issues exposed by this PR? The goal is to be able to upgrade to protobuf 3.15 release without any issues once it becomes available.

**Comment by lidizheng** [comment]
@acozzette Thanks for writing this PR up! Jan's comment summarized the failed build and logs, when you got a second, can you go through them to see if anything is trivially fixable. For harder issues, I can also help, and I'm available online/offline.

**Comment by lidizheng** [comment]
For the C++ build failure (`constexpr` constrcutors with parent class) on old compilers, based on Godbolt, it builds for `clang` 4.0.0+, with `-std=c++11`. I can't find which change in 4.0.0 release note fixed it (https://releases.llvm.org/4.0.1/tools/clang/ReleaseNotes.html). But we can bump up our minimum supported clang.

**Comment by acozzette** [comment]
@lidizheng If we can end support for Clang 3.x then that would be great since that would solve the problem. Otherwise we might have to have some complicated ifdefs to handle older Clang versions.

**Comment by jtattermusch** [comment]
Ad clang 3.6 and clang3.7 failures:   clang 3.x is pretty old by now. If it's older than 5 years, I think we can drop support for it (we normally support compiler versions released up to 5 years ago and newer),  but for that we would need to  update our portability test suite:
https://github.com/grpc/grpc/blob/711d1d7fe2da56896957e00fea12c84b6d1fa1e1/tools/run_tests/run_tests_matrix.py#L268 and setup clang tests for newer versions of clang).

https://github.com/grpc/grpc/blob/711d1d7fe2da56896957e00fea12c84b6d1fa1e1/tools/run_tests/run_tests.py#L490

**Comment by acozzette** [comment]
@jtattermusch Clang 3.9.1 was released in December 2016, so it's not quite 5 years old yet. Is that OK or does that mean gRPC has to keep support for it until December 2021?

**Comment by jtattermusch** [comment]
> @jtattermusch Clang 3.9.1 was released in December 2016, so it's not quite 5 years old yet. Is that OK or does that mean gRPC has to keep support for it until December 2021?

I would be leaning toward dropping the support if that avoids dirty hacks. But it there is a reasonably easy to do proper fix, let's do that instead. Dropping clang 3.x support would ideally be done separately, not because we are pressured to that in order to be able to upgrade protobuf. Btw, what's the compiler support policy for protobuf - shouldn't clang 3.x be still supported?

**Comment by acozzette** [comment]
I don't think we have an official compiler support policy, and in practice we have just been constrained by needing to support whatever gRPC supports. Unfortunately it sounds like there's not really an easy workaround but @sbenzaquen can probably say more.

**Comment by sbenzaquen** [comment]
We could use conditional compilation to add `constexpr` only when the compiler will support it.
The system will work if these constructors are not `constexpr`, but it will be less efficient (in binary size and startup cost).
We already have this case for versions of MSVC that don't do constant initialization, even though the spec says it should.
It does complicate the code. It would not be a dirty hack, it would be more like using a macro instead of spelling it `constexpr` directly.
I am not sure if this kind of conditional compilation would lead to ODR violations if different compilers are used for different parts of a binary. It most likely would. ie, if the proto library is prebuilt with/without constexpr and user code is built the other way.

**Comment by jtattermusch** [comment]
I just merged https://github.com/grpc/grpc/pull/25443 and I'm going to restart the tests.  Now the clang3.x problem should go away, but other issues still need to be fixed.

**Comment by acozzette** [comment]
Thanks, @jtattermusch. I am working on rc2 now and this should fix the Windows Python error. The Objective-C error looks like a mismatch between protoc and the protobuf runtime, so I think that might be a problem with the test setup. I haven't looked carefully at the Ruby failure yet but I think it might be easy to fix--it looks like the code is returning an error as expected but just doesn't have the exact error message the test expects. @haberman might know more about the Ruby test failure.

**Comment by yulin-liang** [comment]
@acozzette It looks like you forgot to change [Protobuf-C++.podspec](https://github.com/grpc/grpc/blob/master/src/cpp/Protobuf-C%2B%2B.podspec#L3), I think it's the root cause of the mismatch between protoc and the protobuf runtime.

**Comment by acozzette** [comment]
@yulin-liang Oh thanks, I just pushed another commit to update the version there.

**Comment by yulin-liang** [comment]
@acozzette `Basic Tests C++ iOS` still fails, here the error message:
```
Wed Feb 17 11:42:02 PST 2021 - [!] Error installing Protobuf-C++
Wed Feb 17 11:42:02 PST 2021 - [!] /usr/local/bin/git clone https://github.com/google/protobuf.git /var/folders/wv/_5q8c8j155g873yylt68nd4c0000gn/T/d20210217-5120-89p3hr --template= --single-branch --depth 1 --branch v3.15.0-rc1
Wed Feb 17 11:42:02 PST 2021 -
Wed Feb 17 11:42:02 PST 2021 - Cloning into '/var/folders/wv/_5q8c8j155g873yylt68nd4c0000gn/T/d20210217-5120-89p3hr'...
Wed Feb 17 11:42:02 PST 2021 - warning: Could not find remote branch v3.15.0-rc1 to clone.
Wed Feb 17 11:42:02 PST 2021 - fatal: Remote branch v3.15.0-rc1 not found in upstream origin
```

Looks like the tag name should be `v3.15.0-rc1` instead of `3.15.0-rc1`.

Screen Shot 2021-02-17 at 12 24 23 PM

**Comment by acozzette** [comment]
@yulin-liang Good catch, thanks! I added a `v3.15.0-rc1` tag.

**Comment by jtattermusch** [comment]
Remaining issues:

Sanity failures (both should be quite easy to fix)
https://source.cloud.google.com/results/invocations/bca59558-1c29-4b17-aa33-2e95791180c4/targets

Build issue on mac:
https://source.cloud.google.com/results/invocations/92317c37-6006-48bd-b83f-29c532424e44/log

Ruby tests seem broken:
https://source.cloud.google.com/results/invocations/7183090b-3072-4bed-9372-a10e7710baab/targets/github%2Fgrpc%2Frun_tests%2Fruby_macos_dbg_native%2Ftools%2Frun_tests%2Fhelper_scripts%2Frun_ruby.sh/tests

**Comment by acozzette** [comment]
Would anyone on the gRPC team mind kicking off the tests again? I think most or all of the remaining issues should be fixed now.

**Comment by lidizheng** [comment]
@acozzette Can you take a look at the Sanity Checks? It needs a version update in podspec. The Ruby build failure looks like missing some Core files. Maybe re-run the `tools/buildgen/generate_projects.sh` script could fix the problem.

**Comment by lidizheng** [comment]
BTW, there is an update to fix the Ruby test https://github.com/grpc/grpc/pull/25507. When update this PR next time, we should probably sync with HEAD.

**Comment by jtattermusch** [comment]
Looks like protobuf 3.15.2 has been released. @lidizheng  can you please create a PR to upgrade to that version? (and close this PR)

**Comment by jtattermusch** [comment]
Thanks everyone for the investigating the problems. This PR can now be closed in favor of https://github.com/grpc/grpc/pull/25565

**Pull request closed without merging**
