### PR TITLE
Simplify running of cloud_to_cloud interop tests.

### PR DESCRIPTION
**Pull request by jtattermusch**
This supersedes pull requests #3355 and #3359.

Enables running most of cloud_to_prod and cloud_to_cloud tests quickly.  After building docker image that contains interop servers and clients for (almost) all languages, two containers are spawn. One of them runs the interop server and the other one run clients from run_interop_test.py.

Building the docker image takes ~5mins.
Running all the cloud_to_prod and cloud_to_cloud tests takes ~1min (not bad for ~160 tests).

Usage examples:
```
# csharp against node under docker
run_interop_tests.py --use_docker  -l csharp --server node

# cloud to prod locally
run_interop_tests.py -l all --cloud_to_prod

# run against manually spawn server
run_interop_tests.py -l ruby --override_server=node=localhost:1234

# all servers, all clients and cloud_to_prod
run_interop_tests.py --use_docker -l all --server all --cloud_to_prod
```

### CODE REVIEW

**Comment by jtattermusch** [comment]
@ctiller FYI

**Comment by jtattermusch** [comment]
On jenkins, the "interop c++" configuration is green. The tests run by it are cloud_to_prod and cloud_to_cloud interop tests where c++ is client.

**Comment by jtattermusch** [comment]
I will be probably rebasing this on top of #3388 as I want that one merged first.

**Comment by jtattermusch** [comment]
This should be ready for review and Jenkins is sufficiently green.

**Comment by jtattermusch** [comment]
ping?

**Comment by jtattermusch** [comment]
It would be great if this could get reviewed soon.

**Comment by ctiller** [comment]
Can you merge, and add an allow_flakes argument to the python script?

**Comment by jtattermusch** [comment]
I am not sure if the --allow_flakes option is compatible with future changes to interop test scripts, so for now, I just rebased this PR and I am not propagating $@ to  tools/run_tests/run_interop_tests.py in  run_jenkins.sh

**Comment by ctiller** [comment]
What future change are you worried about with the interop test scripts?

**Comment by jtattermusch** [comment]
We haven't quite figured out what the jenkins job setup for interop tests will look like (likely they will disappear from the current matrix and will become part of some other job). Also, I don't think we want to commit to having exactly the same cmdline args for run_tests.py and run_interop_tests.py now (and passing $@ basically implies that).
So, adding --allow_flakes support to run_interop_tests.py right now seems like unnecessary work.

**Pull request merged**
