### PR TITLE
Revert "Revert "Merge pull request #15797 from apolcyn/windows_compile_and_sort""

### PR DESCRIPTION
**Pull request by apolcyn**
This reverts commit d9e8f86675cf923714b3ead4b06087e14a88c08c, reversing
changes made to 04847aeb1e62bc528d88fa3c47daa24a4cf629b3.

The internal fix for the previous build breakage is pending now, so getting this PR ready again

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +0.0%    +269 [None]                                                                           +16.8Ki  +0.2%
  +2.0%     +32 third_party/address_sorting/address_sorting.c                                        +32  +2.0%
      [NEW]     +24 address_sorting_get_source_addr_for_testing                                          +24  [NEW]
      +9.6%      +8 [Unmapped]                                                                            +8  +9.6%
  [NEW]     +19 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper_posix.     +19  [NEW]
      [NEW]     +19 grpc_ares_query_ipv6                                                                 +19  [NEW]

  +0.0%    +320 TOTAL                                                                            +16.9Ki  +0.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,976,610      Total (=)      1,976,610

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,771,524      Total (=)     10,771,524

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
macos objc failures: https://github.com/grpc/grpc/issues/16156

**Pull request merged**
