### PR TITLE
Add support for max metadata size.

### LINKED ISSUE #1802: Add hooks for limiting metadata size
We currently don't have any way of enforcing limits on metadata received

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #1802.

This is my initial attempt, but I'm pretty sure it still needs some work.  Currently, the code does not seem to be properly causing the RPC to fail when the max size is exceeded (see the FIXME comment in the diff).  I'm not sure why.  Is there something I need to do in the parsing code other than setting stream_parsing->seen_error = 1 to cause an error to be returned?

### CODE REVIEW

**Comment by markdroth** [comment]
As we discussed, I've changed the code to use cancel_from_api() to return an error.  I picked GRPC_STATUS_RESOURCE_EXHAUSTED as the status code that seemed to most closely match this situation, but I can easily use a different one if you prefer.

There are still a couple of proxy tests failing, and I'm still trying to figure out why.

Please let me know what you think.  Thanks!

**Comment by markdroth** [comment]
I've changed the code to use the HTTP/2 MAX_HEADER_LIST_SIZE setting, and to honor that value on both the sending and receiving sides.

As per our discussion, I've changed the large_metadata test back to covering only the case where both the client and server support large metadata.  I still need to write new tests in the bad_client suite that cover the cases where the sending and receiving sides see values larger than they should.

I also still need to figure out the problem with the proxy tests.  I suspect it may involve a race condition, but I haven't had time to dig into it yet.

**Comment by markdroth** [comment]
Okay, I think this PR is finally ready for review.  I think I've added all of the tests we need for this new functionality, and all of the existing tests should now be passing.

Please let me know what you think.  Thanks!

**Comment by ctiller** [comment]
This looks right I think... clang-format wants to be happier though (tools/distrib/clang_format_code.sh)

**Comment by markdroth** [comment]
The clang-format stuff should be fixed now.

**Comment by markdroth** [comment]
Hmm, looks like there are still a few test failures.

@nicolasnoble, a couple of the failures are windows tests, which I have no idea how to deal with.  Can you take a look and help me figure out what's broken?  Thanks!

The other failures are the large_metadata_bad_client test in both asan and tsan configs.  I'm looking into those, with help from Craig as needed.

**Comment by markdroth** [comment]
I fixed the asan test failure.

This time, the tsan test did not fail, so I suspect that the previous failure was flakiness.  Also, this time, there are more failures reported that were not reported in the last run, which also smells like flakiness.

I suspect that this is okay to merge at this point, but I'll let someone with more experience with this code make that call.  Please let me know if you need anything else from my end.

**Comment by ctiller** [comment]
Lgtm

**Comment by jtattermusch** [comment]
Tests too red (most likely unrelated, but there's too many failures for me to check), trying to rerun.

**Pull request merged**
