### PR TITLE
Test message size of 100MB

### PR DESCRIPTION
**Pull request by AspirinSJL**
A followup of https://github.com/grpc/grpc/pull/16259.

We want to be able to say "we can handle 100MB request". But we don't have any promise about message that's beyond that size.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,077      Total (=)      1,955,077

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,025      Total (>)     10,843,022

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,002      Total (=)      1,955,002

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,752      Total (>)     10,843,749

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
The Bazel tests are all failing, but the finished cmake tests are all passing.. Don't know why.

**Comment by AspirinSJL** [comment]
The failing tests are due to too long execution time. We should change the test timeout.

**Comment by nicolasnoble** [comment]
This is actually because we're running out of memory. Msan & tsan are the two categories of test eating a lot of memory, and the processes most likely got killed due to OOM.

@jtattermusch - we might need to bump the available memory on this pool; maybe create a specific pool of workers for msan / tsan.

**Comment by jtattermusch** [comment]
I'd be in favor of skipping the tests that require an extreme amount of memory for msan and tsan (or using a lower max message size if the code is compiled with msan or tsan enabled). There's very little value in testing on tsan with 100MB vs testing with smaller messages. 
Increasing the available resources shouldn't be a universal answer to this kind of problems - we should be clever about how we utilize our testing resources and design our tests accordingly (instead of running a combinatorial explosion of all the possible params).

**Comment by AspirinSJL** [comment]
@yang-g Please take another look. Thanks!

**Comment by AspirinSJL** [comment]
https://github.com/grpc/grpc/issues/20118

**Comment by vjpai** [comment]
Rolling back due to internal timeouts. Please see if you need to adjust the test size or something to compensate for the larger messages....

**Comment by AspirinSJL** [comment]
This should be covered by the stress test @yashykt works on, so I'm not rolling forward it.

**Pull request merged**
