### PR TITLE
Create Markdown table for structure and dev status

### PR DESCRIPTION
**Pull request by thebearjew**
Cleanly display the Language, Source Code, and Release Status in one Table for easy viewing and updating.

:rocket: :cookie:

### CODE REVIEW

**Comment by thebearjew** [comment]
I signed it!

**Comment by jcanizales** [comment]
:+1:

**Comment by thebearjew** [comment]
Some clarification: I am not currently up to date with with the API stabilities of the project (as I am not actively contributing). 

But the Markdown table might be a worthwhile investment in having easily checkable, up-to-date, and compact API stability reference.

**Comment by soltanmm** [comment]
@thebearjew Nonono - that wasn't a comment meant to be directed toward this PR at all. I like the table. That stability note was there before you and I'm concerned with how we've been planning for a while now to change the Python API's top-level packages when we move to GA, so I'm concerned with what the *meaning* of stability is, here, not necessarily with its use.

table = pretty

**Comment by thebearjew** [comment]
@soltanmm Oh got it! Sorry I guess I totally misunderstood, my mistake. Alright, well glad the table is looking useful (just about the most I can contribute at the moment haha).

**Comment by jcanizales** [comment]
Mugur might not visit GitHub much, so if nobody has an objection, I'll merge this by the end of Monday.

**Comment by thebearjew** [comment]
:tada:

**Comment by jcanizales** [comment]
Sorry that it slipped my mind ^^ and thanks a lot for taking the time to do it!

**Comment by thebearjew** [comment]
No worries, happy to contribute something small!

**Pull request merged**
