### PR TITLE
fix performance benchmarks on windows

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/16334

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,951,564      Total (=)      1,951,564

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,662,111      Total (>)     10,662,102

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
In the ad-hoc performance run, some scenarios have failed, but those failures look unrelated. The windows scenarios have succeeded though, which was the goal in this PR.
https://source.cloud.google.com/results/invocations/6799a47d-4947-4b42-a324-0d69e4daf4b4/targets/github%2Fgrpc%2Freports%2Fwindows/tests

I'm going to fix code formattin and then I'll merge.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,951,564      Total (=)      1,951,564

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,662,106      Total (<)     10,662,111

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/16352

**Pull request merged**
