### PR TITLE
Remove unused ChannelCredentials.c_credentials

### PR DESCRIPTION
**Pull request by mehrdada**
remnant of the past not used anywhere

cc @lidizheng.

### CODE REVIEW

**Comment by lidizheng** [comment]
@mehrdada LOAS2 is using the channel credentials, so we can't easily remove this API in OSS.

**Comment by mehrdada** [comment]
@lidizheng Doesn't it inherit from the credentials object?

**Comment by lidizheng** [comment]
@mehrdada The major part of change is internal. If we are going to remove this field, then the internal change have to be merged first to prevent the import from failing.

**Comment by mehrdada** [comment]
@lidizheng I understand. Unless we had been doing something seriously wrong, it should be straightforward. Patch is low priority obviously, so I leave it to you to prioritize accordingly, but it might be worth cleaning up some of mess in the credentials space. It's a good start.

**Comment by lidizheng** [comment]
@mehrdada Thanks for submitting the PR. Once the internal change is submitted I will merge this PR.

**Pull request merged**
