### PR TITLE
Upmerge v1.3.x branch to master

### PR DESCRIPTION
**Pull request by apolcyn**

### CODE REVIEW

**Comment by apolcyn** [comment]
manual merge conflicts:

* `src/core/ext/filters/client_channel/client_channel.c` (See https://github.com/grpc/grpc/pull/11268/files#diff-a7c672b62938053ba5a0007a5089a1b6R1569)

* `rb_event_thread.c` and `rb_channel.c` (format only conflicts).

* `build.yaml` and `BUILD` versions

* also https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Version.csproj.include#L5

**Comment by dgquintas** [comment]
There's a bunch of sanity failures: https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/5677/#showFailuresLink

Otherwise LGTM

**Comment by apolcyn** [comment]
@dgquintas it looks like sanity tests are failing at head of master.

I opened https://github.com/grpc/grpc/pull/11313 to fix the sanity failures, not sure if this should wait

**Comment by apolcyn** [comment]
re-running after sanity fixed.

jenkins: test this please

**Comment by markdroth** [comment]
Is this superseded by #11309?

**Comment by apolcyn** [comment]
I'm not sure; I'd note the change to `src/core/ext/filters/client_channel/client_channel.c` in here is slightly different than in #11309. 

Is #11309 preferred? cc @murgatroid99

**Comment by apolcyn** [comment]
closing this in favor of https://github.com/grpc/grpc/pull/11309

**Pull request closed without merging**
