### PR TITLE
Revert "Revert "Revert "Revert "Remove redundant includes from string.h and tmpfile.h""""

### PR DESCRIPTION
**Pull request by markdroth**
Reverts grpc/grpc#9063.  Yet another attempt to get #8922 to stick.

Trying this one more time.

NOTE: DO NOT MERGE UNTIL AFTER BUILD CHANGE MORATORIUM IS OVER!

### CODE REVIEW

**Comment by dgquintas** [comment]
This PR seems to be out of date: there are mentions of gpr_slice and reintroduction of slice.h, etc.

**Comment by sreecha** [comment]
@dgquintas , this is not outdated. It was deliberately added to maintain backward compatibility with any third party sources (like tensorflow) that take a dependency on grpc release snapshots.

This can be released once we cut another grpc release

**Comment by dgquintas** [comment]
ah, got it, thanks @sreecha !

**Comment by markdroth** [comment]
I will drive this forward, but there's nothing that can really be done with it until the moratorium on build changes is lifted.

**Comment by markdroth** [comment]
Known failures: #8996.

**Pull request merged**
