### PR TITLE
Set cq_ on servercontext

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by vjpai** [comment]
Ok, I can see that this was the intended code path. So far, looks good to me. Please go ahead and add in tests at your convenience.

**Comment by vjpai** [comment]
Hi, a reverse friendly ping. Wondering what's still remaining on this one? I wouldn't mind merging it except that it still has DO NOT MERGE (I guess the tests?)

**Comment by yang-g** [comment]
I will get some tests added today and then ping you. Thanks.

**Comment by yang-g** [comment]
Ping~

**Pull request merged**
