### PR TITLE
Fix for cmake test failures

### PR DESCRIPTION
**Pull request by MakMukhi**

### CODE REVIEW

**Comment by MakMukhi** [comment]
asan c failure due to know issue #10169

**Comment by yang-g** [comment]
5aa4158 does not look like your commit, can you get rid of it?

**Comment by MakMukhi** [comment]
This fix is for a failure in portability test linux aggregate_tests.run_tests_c++_linux_dbg_native_default_cmake 
No issue was created for this.

The asan failure in this PR is due to another known issue #10169

**Comment by MakMukhi** [comment]
Opened another PR since this had incorrect commit messages.

**Comment by dgquintas** [comment]
@MakMukhi and what PR is that?

**Comment by jtattermusch** [comment]
@MakMukhi, nit:  you could have done `git rebase -i upstream/master` and force push to this branch to reuse this PR. 

What is the number of the new PR?

**Comment by ctiller** [comment]
Guessing https://github.com/grpc/grpc/pull/10869

If it's not solved can we figure out how to rollback?

**Pull request closed without merging**
