### PR TITLE
Revert "Buffer HPACK parsing until the end of a header boundary"

### PR DESCRIPTION
**Pull request by ctiller**
Reverts grpc/grpc#26700

This PR introduces a dangerous overbuffering condition that's unsolvable with this approach.

### CODE REVIEW

**Review by ejona86 — APPROVED** [review]
As I just commented (https://github.com/grpc/grpc/pull/26787#issuecomment-889275285) you can allow some overbuffering, but not "excessive" overbuffering (tehe) with this approach. I think I did an audit of the implementations and something like that was predominant. That said, I would recommend still streaming but at a coarser granularity.

Approving to let you revert quickly. If you want to patch-up instead of revert by limiting the buffering size, that is still an option.

**Comment by ctiller** [comment]
I'd rather not destroy the connection on a badly formed header... I think I can rework the simplification to parse one element at a time, and that's probably preferable

**Comment by ejona86** [comment]
SGTM. That's my preference as well.

**Comment by ctiller** [comment]
Turning on auto-merge... I'm likely to be distracted later, and the sooner this is expunged from the build the better.

**Pull request merged**
