### PR TITLE
Add v1.27.1 release of grpc-go to interop matrix

### PR DESCRIPTION
**Pull request by dfawley**
See also #21880 which this will surely conflict with, unfortunately.

### CODE REVIEW

**Comment by jtattermusch** [comment]
It seems that just adding v1.27.1 should be enough and https://github.com/grpc/grpc/pull/21880 can be closed?

**Comment by dfawley** [comment]
Sounds good.  I didn't notice that only the latest patch release for any minor release is still in `client_matrix.py`.  I've never removed an older version in the past; should we always do so going forward?  If so I will update our release instructions.

**Comment by jtattermusch** [comment]
> Sounds good. I didn't notice that only the latest patch release for any minor release is still in `client_matrix.py`. I've never removed an older version in the past; should we always do so going forward? If so I will update our release instructions.

I think what we've been doing for other languages is to update the existing v1.X.Y entry  with v1.X.Y+1 when a new patch was released on given release branch.

**Comment by dfawley** [comment]
> I think what we've been doing for other languages is to update the existing v1.X.Y entry with v1.X.Y+1 when a new patch was released on given release branch.

It seems we have been doing this in Go as well.  Apparently I haven't made a patch release in a long time.  The release instructions do mention it, but only in one place; I've updated the instructions to emphasize this in the main checklist as well.

**Pull request merged**
