### PR TITLE
Change rpc server to not reuse server instance

### PR DESCRIPTION
**Pull request by shahoxo**
This PR fixes bug(maybe) rpc server handlers.

Since existing implementations reuse method instances, all variables are initialized by previous rpc call.
After this patch applied, method instances that used by rpc call will be instantiated every time.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @shahoxo isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by apolcyn** [comment]
thanks for the pull request.

My only issue with this is that it's a potentially breaking behavior change; I could imagine that some people might be relying on the fact that instance state can be shared between different RPC's. (the [route guide server](https://github.com/grpc/grpc/blob/master/examples/ruby/route_guide/route_guide_server.rb#L150) is one contrived example).

Rather than <i>change</i> the current behavior, can we extend it to support the <i>old</i> way and this <i>new</i> way? 

One simple example: we could add a new method called, e.g., `RpcServer#handle_with_new_instance_per_rpc(service)`, which uses this new behavior from this PR.

**Comment by shahoxo** [comment]
Fixed!

**Comment by apolcyn** [comment]
jenkins: this is ok to test

**Comment by apolcyn** [comment]
@shahoxo I'm not sure if you can see the test results, e.g., in https://sponge.corp.google.com/target?id=f9ebce33-9e5c-42d1-9ab9-6c097f1ef514&target=github/grpc/ruby_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS, but there appears to be some rubocop style checker errors here.

Can you please fix the style check error here? Note you can run the (most of) the ruby unit tests locally by running either `bundle exec rake` from the repo root, or by running `toosl/run_tests/run_tests.py -l ruby (--use_docker)`

**Comment by vjpai** [comment]
@apolcyn : if this PR is actually a good idea (and I contend that it is _not_), it needs to go through the gRFC process. This is a new (and strange, IMO) promise.

**Comment by apolcyn** [comment]
@shahoxo though this PR is not too invasive, I do agree with @vjpai, and I am worried that the API extension here could be confusing for the benefit it provides.

If you'd like to move forward with this, can you please create a gRPF proposal? Here are some examples: https://github.com/grpc/proposal/pulls. A gRPF proposal could be useful because 1) the API here adds some complexity and it would be helpful to check the motivations first, and 2) this idea could potentially apply to all grpc servers and not just ruby.

**Comment by vjpai** [comment]
I would go one step further than my previous comment and say that this PR should just be closed. If the writer of a service wants this effect, the service should just be written to use local variables in the handler method rather than class variables in the service implementation. There's no point adding to the API to achieve something that can be easily done with what's already supported. I'm closing it for now.

**Pull request closed without merging**
