### PR TITLE
Add proto comments to generated _pb2.py files

### PR DESCRIPTION
**Pull request by yang-g**
The examples files are regenerated and can be used as examples.

### CODE REVIEW

**Comment by yang-g** [comment]
Fixes #6343.

**Comment by soltanmm** [comment]
LGTM, thanks!

**Comment by soltanmm** [comment]
Python is green and the given source code only affects Python, so, `READY TO MERGE`ing...

(Kicked off another basic test build anyway; old results [here](https://grpc-testing.appspot.com/job/gRPC_pull_requests/8490/))

**Comment by jtattermusch** [comment]
Thanks @yang-g  for handling this!

**Pull request merged**
