### PR TITLE
Update third_party/protobuf to v3.11.2 

### PR DESCRIPTION
**Pull request by jtattermusch**
We're currently at protobuf 3.8 (didn't manage to upgrade to protobuf 3.9 and 3.10 due to some issues).

### CODE REVIEW

**Comment by jtattermusch** [comment]
Python Bazel Build
https://source.cloud.google.com/results/invocations/da1975c4-f708-49f1-b090-5e86b8c4ccfd/log
```
DEBUG: /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:226:13: rbe_msan not using checked in configs; Bazel version 1.0.0 was picked/selected with '["9.0.0", "10.0.0"]' compatible configs but none match the 'env = {"ABI_LIBC_VERSION": "glibc_2.19", "ABI_VERSION": "clang", "BAZEL_COMPILER": "clang", "BAZEL_HOST_SYSTEM": "i686-unknown-linux-gnu", "BAZEL_TARGET_CPU": "k8", "BAZEL_TARGET_LIBC": "glibc_2.19", "BAZEL_TARGET_SYSTEM": "x86_64-unknown-linux-gnu", "CC": "clang", "CC_TOOLCHAIN_NAME": "linux_gnu_x86", "BAZEL_LINKOPTS": "-lc++:-lc++abi:-lm"}', 'config_repos = None',and/or 'create_cc_configs = True' passed as attrs
Analyzing: 214 targets (36 packages loaded, 0 targets configured)
INFO: Call stack for the definition of repository 'go_sdk' which is a _go_download_sdk (rule definition at /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/io_bazel_rules_go/go/private/sdk.bzl:53:20):
 - /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/io_bazel_rules_go/go/private/sdk.bzl:65:5
 - /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:13
 - /var/local/git/grpc/bazel/grpc_extra_deps.bzl:36:5
 - /var/local/git/grpc/WORKSPACE:11:1
ERROR: /root/.cache/bazel/_bazel_root/d2dc70c3d9da3fab488ba0dcbbd35051/external/com_google_protobuf/BUILD:874:1: no such package '@six//': The repository '@six' could not be resolved and referenced by '@com_google_protobuf//:protobuf_python'
ERROR: Analysis of target '//src/python/grpcio_reflection/grpc_reflection/v1alpha:reflection_py_pb2' failed; build aborted: no such package '@six//': The repository '@six' could not be resolved
```

**Comment by jtattermusch** [comment]
A bunch of Macos bazel tests terminating with an odd, likely protobuf related error:

https://source.cloud.google.com/results/invocations/9a21fcab-5195-4f6d-88e4-1780fe99d5a0/targets
```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:120] File already exists in database: google/protobuf/any.proto
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
```

**Comment by jtattermusch** [comment]
ASAN problems:
https://source.cloud.google.com/results/invocations/cfad3c7d-e44b-4853-974a-3b2e8cbb649a/targets
```
+ export GRPC_POLL_STRATEGY=epoll1
+ shift
+ test/core/channel/channelz_test
=================================================================
==18==ERROR: AddressSanitizer: odr-violation (0x7f3ef8ff53a0):
  [1] size=32 'google::protobuf::_DoubleValue_default_instance_' bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/wrappers_proto/google/protobuf/wrappers.pb.cc:21:3
  [2] size=32 'google::protobuf::_DoubleValue_default_instance_' external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:21:3
These globals were registered at these points:
  [1]:
    #0 0x45f0dd in __asan_register_globals /tmp/clang-build/src/compiler-rt/lib/asan/asan_globals.cpp:362:3
    #1 0x7f3ef8fdb0db in asan.module_ctor (/b/f/w/bazel-out/k8-fastbuild/bin/test/core/channel/channelz_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/core/channel/../../../_solib_k8/libexternal_Scom_Ugoogle_Uprotobuf_Slibwrappers_Uproto.so+0x2b0db)

  [2]:
    #0 0x45f0dd in __asan_register_globals /tmp/clang-build/src/compiler-rt/lib/asan/asan_globals.cpp:362:3
    #1 0x7f3ef8dff48b in asan.module_ctor (/b/f/w/bazel-out/k8-fastbuild/bin/test/core/channel/channelz_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/core/channel/../../../_solib_k8/libexternal_Scom_Ugoogle_Uprotobuf_Slibprotobuf.so+0x9af48b)

==18==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'google::protobuf::_DoubleValue_default_instance_' at bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/wrappers_proto/google/protobuf/wrappers.pb.cc:21:3
```

**Comment by jtattermusch** [comment]
@rafi-kamal  looks like there's several problems upgrading gRPC to protobuf 3.11.2 - can you look at them and help us resolve?

**Comment by jtattermusch** [comment]
> ASAN problems:
> https://source.cloud.google.com/results/invocations/cfad3c7d-e44b-4853-974a-3b2e8cbb649a/targets
> 
> ```
> + export GRPC_POLL_STRATEGY=epoll1
> + shift
> + test/core/channel/channelz_test
> =================================================================
> ==18==ERROR: AddressSanitizer: odr-violation (0x7f3ef8ff53a0):
>   [1] size=32 'google::protobuf::_DoubleValue_default_instance_' bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/wrappers_proto/google/protobuf/wrappers.pb.cc:21:3
>   [2] size=32 'google::protobuf::_DoubleValue_default_instance_' external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:21:3
> These globals were registered at these points:
>   [1]:
>     #0 0x45f0dd in __asan_register_globals /tmp/clang-build/src/compiler-rt/lib/asan/asan_globals.cpp:362:3
>     #1 0x7f3ef8fdb0db in asan.module_ctor (/b/f/w/bazel-out/k8-fastbuild/bin/test/core/channel/channelz_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/core/channel/../../../_solib_k8/libexternal_Scom_Ugoogle_Uprotobuf_Slibwrappers_Uproto.so+0x2b0db)
> 
>   [2]:
>     #0 0x45f0dd in __asan_register_globals /tmp/clang-build/src/compiler-rt/lib/asan/asan_globals.cpp:362:3
>     #1 0x7f3ef8dff48b in asan.module_ctor (/b/f/w/bazel-out/k8-fastbuild/bin/test/core/channel/channelz_test@poller=epoll1.runfiles/com_github_grpc_grpc/test/core/channel/../../../_solib_k8/libexternal_Scom_Ugoogle_Uprotobuf_Slibprotobuf.so+0x9af48b)
> 
> ==18==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
> SUMMARY: AddressSanitizer: odr-violation: global 'google::protobuf::_DoubleValue_default_instance_' at bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/wrappers_proto/google/protobuf/wrappers.pb.cc:21:3
> ```

Oh, looks like this is due to https://github.com/grpc/grpc/pull/20224#issuecomment-537732931
 @rafi-kamal  what is the next step here to fix?

**Comment by gnossen** [comment]
The failure in the Python build is addressed by https://github.com/grpc/grpc/pull/20783. We were hesitant to pull it in because it constitutes a breaking change, but I think at this point, we'd better.

**Comment by rafi-kamal** [comment]
There are two potential solutions mentioned in https://github.com/grpc/grpc/pull/20224#issuecomment-537732931, but I'm not familiar enough with Protobuf or gRPC C++ to determine which one is better or what exactly the next steps would be in either of these two solutions. @veblush would be able to help here? 

I'm happy to help if any changes are needed from the Protobuf side,

**Comment by jtattermusch** [comment]
ObjC regression
https://source.cloud.google.com/results/invocations/b889017f-279c-43ff-9d12-317f0ec660fe/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fios-cpp-test-cronet/tests
```
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/test/cpp/ios/Pods/Headers/Private/RemoteTestCpp/src/proto/grpc/testing/echo_messages.pb.h:576:111: error: only virtual member functions can be marked 'final'
Tue Jan  7 01:55:51 PST 2020 -       ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
Tue Jan  7 01:55:51 PST 2020 -                                                                                                               ^~~~~
Tue Jan  7 01:55:51 PST 2020 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/test/cpp/ios/Pods/Headers/Private/RemoteTestCpp/src/proto/grpc/testing/echo_messages.pb.h:548:42: error: no member named 'GenericSwap' in namespace 'google::protobuf::internal'
Tue Jan  7 01:55:51 PST 2020 -       ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
Tue Jan  7 01:55:51 PST 2020 -       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Tue Jan  7 01:55:51 PST 2020 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/test/cpp/ios/Pods/Headers/Private/RemoteTestCpp/src/proto/grpc/testing/echo_messages.pb.h:978:101: error: only virtual member functions can be marked 'final'
Tue Jan  7 01:55:51 PST 2020 -   const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
Tue Jan  7 01:55:51 PST 2020 -                                                                                                     ^~~~~
Tue Jan  7 01:55:51 PST 2020 - fatal error: too many errors emitted, stopping now [-ferror-limit=]
Tue Jan  7 01:55:51 PST 2020 -
```

**Comment by muxi** [comment]
I see `Protobuf-C++ 3.8.0` got installed.

**Comment by muxi** [comment]
The file is [here](https://github.com/grpc/grpc/blob/master/src/cpp/Protobuf-C++.podspec). I'm not sure why it is maintained in gRPC repo though (since I remember discussion with teboring on integrating its release in Protobuf's release process).

**Comment by jtattermusch** [comment]
> The file is [here](https://github.com/grpc/grpc/blob/master/src/cpp/Protobuf-C++.podspec). I'm not sure why it is maintained in gRPC repo though (since I remember discussion with teboring on integrating its release in Protobuf's release process).

This is the history of that file:
https://github.com/grpc/grpc/commits/master/src/cpp/Protobuf-C%2B%2B.podspec
(and it also looks that is only affects ios-cpp-test-cronet tests as other objC test are passing?)

**Comment by muxi** [comment]
If Protobuf has a copy of this file it's probably right to get rid of our copy. Let me check why our copy exist first.

**Comment by rafi-kamal** [comment]
The protobuf version of the podspec doesn't work. Previous internal discussion: https://groups.google.com/a/google.com/g/protobuf-team/c/7kqwEta6q_A/m/8doAs-OlCwAJ

**Comment by jtattermusch** [comment]
@gnossen, looks like `well_known_protos` conflict problem described here https://github.com/grpc/grpc/pull/21590#issuecomment-571240528 is related to a PR that you reviewed in the past
https://github.com/grpc/grpc/pull/18955/files. Can you please take a look and suggest a fix?

**Comment by jtattermusch** [comment]
> If Protobuf has a copy of this file it's probably right to get rid of our copy. Let me check why our copy exist first.

Thanks! Btw, Protobuf-C++.podspec being in our repo under `src/cpp` (why there?) makes no sense to me at all. We should get rid of it.

**Comment by jtattermusch** [comment]
@muxi https://github.com/grpc/grpc/blob/b07d7f14857d09f05b58ccd0e5f15a6992618f3a/test/cpp/ios/Podfile#L15

**Comment by muxi** [comment]
@rafi-kamal - Sorry I did not notice that thread in Sep. Those two files are exactly the same. It's probably an error that happens during Cocoapods lint but not with gRPC test. I'm taking a look.

**Comment by jtattermusch** [comment]
@muxi  @rafi-kamal  for now I'll try to go with updating our local copy of Protobuf-C++.podspec (https://github.com/grpc/grpc/pull/21590/commits/406cb5d5ca4dd65ccdb8d7027f5761116c687819) to see if that helps fix the failing test

**Comment by muxi** [comment]
@rafi-kamal - I found the reason for the error. Short version: pushing the podspec with additional flags `--use-libraries --allow-warnings` should make the linter pass.

Protobuf C++ code are using the include style `#include <google/protobuf/...>`. The style is not compatible with Apple's Frameworks include style, so the podspec cannot be used as frameworks and thus cannot be lint that way either. `--use-libraries` lints the library as static library.

**Comment by muxi** [comment]
> for now I'll try to go with updating our local copy of Protobuf-C++.podspec (406cb5d) to see if that helps fix the failing test

Thanks Jan. I think it'll work.

**Comment by rafi-kamal** [comment]
> @rafi-kamal - I found the reason for the error. Short version: pushing the podspec with additional flags `--use-libraries --allow-warnings` should make the linter pass.
> 

Thanks! Let me know if you want me to push it to pod.

> Protobuf C++ code are using the include style `#include <google/protobuf/...>`. The style is not compatible with Apple's Frameworks include style, so the podspec cannot be used as frameworks and thus cannot be lint that way either. `--use-libraries` lints the library as static library.

**Comment by muxi** [comment]
> Let me know if you want me to push it to pod.

Yes that's okay to push. Whether and which version to push follows Protobuf's release schedule.

**Comment by gnossen** [comment]
@jtattermusch I managed to track down the root cause of the duplicate symbol issue. It turns out to be a bug in Bazel itself. See the [issue on the protobuf repo](https://github.com/protocolbuffers/protobuf/issues/7046) and [on the bazel repo](https://github.com/bazelbuild/bazel/issues/10484). @Yannic has [a pending PR](https://github.com/bazelbuild/bazel/pull/10493) that fixes this. I built the PR and verified that it solves our duplicate symbol issue.

So our options are:
 - Wait for https://github.com/bazelbuild/bazel/pull/10493 to be merged and make it into a release. Then, upgrade our bazel version.
 - Convince the protobuf team to revert https://github.com/protocolbuffers/protobuf/commit/7b28278c7d4f4175e70aef2f89d304696eb85ae3 and https://github.com/protocolbuffers/protobuf/commit/7b28278c7d4f4175e70aef2f89d304696eb85ae3 as suggested in https://github.com/protocolbuffers/protobuf/issues/7046
 - Temporarily disable ODR violation detection with `ASAN_OPTIONS=detect_odr_violation=0`. (not a fan of this option)

**Comment by jtattermusch** [comment]
> @jtattermusch I managed to track down the root cause of the duplicate symbol issue. It turns out to be a bug in Bazel itself. Lyft has been having a [fair bit](https://github.com/lyft/envoy-mobile/issues/617) of [trouble](https://github.com/lyft/envoy-mobile/pull/618) with it. See the [issue on the protobuf repo](https://github.com/protocolbuffers/protobuf/issues/7046) and [on the bazel repo](https://github.com/bazelbuild/bazel/issues/10484). @Yannic has [a pending PR](https://github.com/bazelbuild/bazel/pull/10493) that fixes this. I built the PR and verified that it solves our duplicate symbol issue.
> 
> So our options are:
> 
> * Wait for [bazelbuild/bazel#10493](https://github.com/bazelbuild/bazel/pull/10493) to be merged and make it into a release. Then, upgrade our bazel version.
> * Convince the protobuf team to revert [protocolbuffers/protobuf@7b28278](https://github.com/protocolbuffers/protobuf/commit/7b28278c7d4f4175e70aef2f89d304696eb85ae3) and [protocolbuffers/protobuf@7b28278](https://github.com/protocolbuffers/protobuf/commit/7b28278c7d4f4175e70aef2f89d304696eb85ae3) as suggested in [protocolbuffers/protobuf#7046](https://github.com/protocolbuffers/protobuf/issues/7046). I've verified that this change also solves the problem. Alternatively, we could just patch their repo when we pull it in, but this could be seen as somewhat antagonistic.
> * Temporarily disable ODR violation detection with `ASAN_OPTIONS=detect_odr_violation=0`. (not a fan of this option)

@rafi-kamal  I believe protobuf should revert the commits mentioned above. It seems to have caused a fair bit of trouble in several projects (grpc, envoy, ..) and it doesn't make sense for every protobuf user to fix it on their own. Also, waiting for bazel to get patched and until everyone upgrades to the patched version of bazel is just not realistic.
https://github.com/protocolbuffers/protobuf/issues/7046
Can we revert the two commits and release 3.11.3?

**Comment by rafi-kamal** [comment]
@jtattermusch I don't fully understand the implication of reverting those two commits. https://github.com/protocolbuffers/protobuf/commit/7b28278c7d4f4175e70aef2f89d304696eb85ae3 says  "Legacy support for using .proto files will be removed in a future version of Bazel", I'm wondering if this is something we need to worry about in the future if we revert the commit.

Can you please send a PR reverting the commits along with the justification?

**Comment by gnossen** [comment]
@rafi-kamal Yes, we will have to worry about this again in the future. Bazel *is* changing the way protos are dealt with. Unfortunately, the support for the new method is broken in Bazel itself (see https://github.com/bazelbuild/bazel/issues/10484). Once Bazel fixes things on their end, the protobuf repo will want to unrevert the two commits Jan and I have pointed out. However, without reverting, Protobuf's support for Bazel is *fundamentally broken.* A test should be added to the protobuf repo along with the revert that pulls in both a protocol buffer *and* `libprotobuf.so`.

For reference, [here is the build graph for one of our protos before these two commits](https://user-images.githubusercontent.com/1644595/72007568-d4d2d180-3206-11ea-9996-670c43bec0b7.png) and [here is the build graph after](https://user-images.githubusercontent.com/1644595/72007571-d8665880-3206-11ea-9697-a5081811c7e9.png). The fundamental difference is that the older version depended on a set of well-known protos generated via a copy operation, while the new version depends on them directly.

I can put together a reversion PR if you agree that this is the proper path to take.

**Comment by Yannic** [comment]
You don't need to revert https://github.com/protocolbuffers/protobuf/commit/a03d332aca5d33c5d4b2cd25037c9e37d57eff02, it's a noop for Bazel >= 1.0 (https://github.com/bazelbuild/bazel/issues/9215), and required many ugly workarounds in earlier versions. The WKPs have been previously copied to remove the `src/` prefix, but that manual step is no longer needed with `strip_import_prefix = "src"`.

The issue your seeing here is caused by Bazel internally distinguishing between the "original" sources (which are the files in the workspace referenced in `proto_library` [1]) and the direct/transitive proto-sources that are used, e.g. by `cc_proto_library`, to generate C++ code [2]. For backward compatibility with `blacklisted = ["a.proto", "b.proto"]`, the blacklist uses the original sources [3], which breaks when the blacklisted `proto_library` sets `import_prefix`, `strip_import_prefix`, or references generated files.

[1] https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/proto/ProtoInfo.java;l=115?q=ProtoInfo
[2] https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/skylarkbuildapi/ProtoInfoApi.java;l=59?q=ProtoInfo
[3] https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/proto/CcProtoAspect.java;l=279

**Comment by gnossen** [comment]
@Yannic Then what do you suggest we do?

**Comment by Yannic** [comment]
Submitted https://github.com/protocolbuffers/protobuf/pull/7065 as a (somewhat) forward-compatible change that fixes the duplicate-symbol issue without a fix in Bazel.

**Comment by jtattermusch** [comment]
@rafi-kamal   can we get https://github.com/protocolbuffers/protobuf/pull/7065 merged and backported into v3.11.x branch? That should unlock this PR.

**Comment by rafi-kamal** [comment]
Created https://github.com/protocolbuffers/protobuf/pull/7069 to backport the PR to 3.11.x, will merge it once the tests pass.

Do you need it to be released?

**Comment by jtattermusch** [comment]
> Created [protocolbuffers/protobuf#7069](https://github.com/protocolbuffers/protobuf/pull/7069) to backport the PR to 3.11.x, will merge it once the tests pass.
> 
> Do you need it to be released?

I applied the backported patch in https://github.com/grpc/grpc/pull/21590/commits/8d916aba11e9ccc8e9b81ca1cf591f1c6b5ab624, but unfortunately it does not seem to be helping - which is odd because @gnossen  has confirmed that the revert was helping and this backport was supposed to have a similar effect.

@Yannic  any ideas why https://github.com/protocolbuffers/protobuf/pull/7065 is not helping?

Test are still reporting the same problem:
https://source.cloud.google.com/results/invocations/407c3834-1517-412e-a1a0-2f4fe2a64010/targets/%2F%2Ftest%2Fcore%2Fchannel:channel_trace_test@poller%3Depoll1/log

**Comment by Yannic** [comment]
(Sorry, I added a `not` that shouldn't be there :/ https://github.com/protocolbuffers/protobuf/blob/master/BUILD#L992).

I tried to fix it and add a test here: https://github.com/Yannic/protobuf/tree/patch-1, but all that test does is showing weird differences between running them locally vs. running them as external workspace.

```
$ bazel test @com_google_protobuf//:cc_proto_blacklist_test //:cc_proto_blacklist_test
INFO: Invocation ID: 99c81582-931b-4b25-a4da-ea523e235133
DEBUG: /private/var/tmp/_bazel_yannic/fff811adc2189b8ffeb88f8dd10a8167/external/bazel_skylib/lib/unittest.bzl:336:5: In test _cc_proto_blacklist_test_impl from //:cc_proto_blacklist_test.bzl: Expected "0", but got "48"
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 test targets...
FAIL: //:cc_proto_blacklist_test (see /private/var/tmp/_bazel_yannic/fff811adc2189b8ffeb88f8dd10a8167/execroot/com_google_protobuf/bazel-out/darwin-fastbuild/testlogs/cc_proto_blacklist_test/test.log)
INFO: Elapsed time: 0.573s, Critical Path: 0.25s
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
@com_google_protobuf//:cc_proto_blacklist_test                           PASSED in 0.1s
//:cc_proto_blacklist_test                                               FAILED in 0.1s
  /private/var/tmp/_bazel_yannic/fff811adc2189b8ffeb88f8dd10a8167/execroot/com_google_protobuf/bazel-out/darwin-fastbuild/testlogs/cc_proto_blacklist_test/test.log

Executed 1 out of 2 tests: 1 test passes and 1 fails locally.
INFO: Build completed, 1 test FAILED, 2 total actions
```

Then, I reverted my change from yesterday, which resulted in both tests failing (as expected). After that, I tried to revert https://github.com/protocolbuffers/protobuf/commit/a03d332aca5d33c5d4b2cd25037c9e37d57eff02 and https://github.com/protocolbuffers/protobuf/commit/7b28278c7d4f4175e70aef2f89d304696eb85ae3 (as suggested in https://github.com/protocolbuffers/protobuf/issues/7046), but that also only works for one of the tests.

I have no idea what's causing this :(.

**Comment by jtattermusch** [comment]
@rafi-kamal  it seems that we are stuck upgrading to protobuf 3.11.2 and we don't have a resolution (besides reverting protocolbuffers/protobuf@7b28278 and protocolbuffers/protobuf@7b28278).

At the same time:
- we haven't updated third_party/protobuf since 3.8 release so finally getting the upgrade done seems very important (we have some features and issues depending on that)
- gRPC release branch is scheduled to be cut very very soon, so it would be highly desirable to solve the problem before we cut the release branch.

In another words, it's highly to solve this problem and to solve it ASAP. Would reverting the commits that caused the problem be feasible (it's the only solution I know of).

@Yannic @gnossen  WDYT?

**Comment by Yannic** [comment]
Would you mind testing grpc against https://github.com/protocolbuffers/protobuf/pull/7096? If that doesn't work, reverting indeed sounds like the only remaining option until a compatible Bazel version is released (hopefully Bazel 2.2).

**Comment by gnossen** [comment]
@Yannic I pulled down https://github.com/protocolbuffers/protobuf/pull/7096 localy and can confirm that it fixes the ODR violation issue. Thanks for the help!

```
rbellevi@rbell:~/Dev/tmp/grpcs/grpc001$ bazel test --config=asan //test/cpp/end2end:xds_end2end_test@poller=poll
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 1.0.0 will be used instead of system-wide bazel installation.
INFO: Writing tracer profile to '/usr/local/google/home/rbellevi/.cache/bazel/_bazel_rbellevi/04546161b9be61d72cb5cf2d432011ac/command.profile.gz'
DEBUG: /usr/local/google/home/rbellevi/.cache/bazel/_bazel_rbellevi/04546161b9be61d72cb5cf2d432011ac/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:226:13: rbe_msan not using checked in configs; Bazel version 1.0.0 was picked/selected with '["9.0.0", "10.0.0"]' compatible configs but none match the 'env = {"ABI_LIBC_VERSION": "glibc_2.19", "ABI_VERSION": "clang", "BAZEL_COMPILER": "clang", "BAZEL_HOST_SYSTEM": "i686-unknown-linux-gnu", "BAZEL_TARGET_CPU": "k8", "BAZEL_TARGET_LIBC": "glibc_2.19", "BAZEL_TARGET_SYSTEM": "x86_64-unknown-linux-gnu", "CC": "clang", "CC_TOOLCHAIN_NAME": "linux_gnu_x86", "BAZEL_LINKOPTS": "-lc++:-lc++abi:-lm"}', 'config_repos = None',and/or 'create_cc_configs = True' passed as attrs
INFO: Analyzed target //test/cpp/end2end:xds_end2end_test@poller=poll (55 packages loaded, 3127 targets configured).
INFO: Found 1 test target...
Target //test/cpp/end2end:xds_end2end_test@poller=poll up-to-date:
  bazel-bin/test/cpp/end2end/xds_end2end_test@poller=poll
INFO: Elapsed time: 339.065s, Critical Path: 284.48s
INFO: 1281 processes: 1281 linux-sandbox.
INFO: Build completed successfully, 1488 total actions
//test/cpp/end2end:xds_end2end_test@poller=poll                          PASSED in 265.1s
  Stats over 10 runs: max = 265.1s, min = 15.4s, avg = 116.6s, dev = 102.6s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 1488 total actions

```

**Comment by rafi-kamal** [comment]
Nice! I'm happy to merge https://github.com/protocolbuffers/protobuf/pull/7096 when it's ready.

**Comment by jtattermusch** [comment]
I also tested with protocolbuffers/protobuf#7096 locally and it seems to work. As another confirmation, I added a "DO NOT MERGE" commit to this PR that tests protobuf with @Yannic 's changes included https://github.com/grpc/grpc/pull/21590/commits/a16e793d5d20a1fa53b5c024b4ad567db2a45828 - let's see what the tests say.

@Yannic any idea when will you be able to finalize the PR? We are in bit of a hurry because we want to cut the release branch for gRPC 1.27.x (with upgraded protobuf) as soon as possible.

**Comment by Yannic** [comment]
The Protobuf PRs are ready not (I only submitted it as a draft so it doesn't get accidentally merged).

**Comment by jtattermusch** [comment]
> I also tested with [protocolbuffers/protobuf#7096](https://github.com/protocolbuffers/protobuf/pull/7096) locally and it seems to work. As another confirmation, I added a "DO NOT MERGE" commit to this PR that tests protobuf with @Yannic 's changes included [a16e793](https://github.com/grpc/grpc/commit/a16e793d5d20a1fa53b5c024b4ad567db2a45828) - let's see what the tests say.

Test failures seem unrelated so I'd say let's proceed with merging protocolbuffers/protobuf#7096
> 
> @Yannic any idea when will you be able to finalize the PR? We are in bit of a hurry because we want to cut the release branch for gRPC 1.27.x (with upgraded protobuf) as soon as possible.

**Comment by rafi-kamal** [comment]
Merged https://github.com/protocolbuffers/protobuf/pull/7096.

**Comment by jtattermusch** [comment]
I updated the PR to include changes from protocolbuffers/protobuf#7096 (that have just been merged to protobuf's 3.11.x). I only upgraded the grpc_deps.bzl ((see https://github.com/grpc/grpc/pull/21590/commits/bf1b849f9a103f08a911a141481efa4b40708916)), which should be enough to fix our bazel problems, the third_party/protobuf stays exactly at the 3.11.2 release 

Once the tests finish, this PR will be ready to merge. Thanks everyone for the help!

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/21627
https://github.com/grpc/grpc/issues/21674

Two failures I'm puzzled about is the the MacOS artifact build:
https://source.cloud.google.com/results/invocations/0456a690-de68-46ee-8baf-e74ade7d7df1/targets/github%2Fgrpc/tests

and the android build
https://source.cloud.google.com/results/invocations/029bcc7f-0b34-467f-a43b-545d7819a1df/log

AFAIR the two failures weren't there on the last build or this PR, which is strange because the only change in https://github.com/grpc/grpc/pull/21590/commits/bf1b849f9a103f08a911a141481efa4b40708916 is upgrading the bazel protobuf dependency (which should have nothing to do with those tests).

**Comment by jtattermusch** [comment]
Another run of adhoc artifact/package/distribtest build: https://sponge.corp.google.com/invocation?tab=Build+Log&id=43bd076b-7395-4fe5-8a56-74d6177a8fba&searchFor=

**Pull request merged**
