### PR TITLE
remove erroneously redefined function from run_tests.py

### PR DESCRIPTION
**Pull request by thunderboltsid**
Tried finding the source where it reappeared and turns out it always has been there. I guess my brain just loves playing with my memories.

### CODE REVIEW

**Comment by thunderboltsid** [comment]
@nathanielmanistaatgoogle Please take a look and add necessary tags.

**Comment by nathanielmanistaatgoogle** [comment]
Commit content looks great.

In your commit message:

* these are functions, not methods,
* it's not redundant, it's erroneously redefined,
* drop "commit hash"; "824c234de8cc0b9a7e4cfd6618060e4158ecf8e3" is a perfectly fine name for a commit,
* [Missing a period at the end of your non-subject-line sentence](http://chris.beams.io/posts/git-commit/#seven-rules).

**Comment by thunderboltsid** [comment]
test this please.

**Comment by nathanielmanistaatgoogle** [comment]
In your commit message:

* It's a function, not a method.
* It was erroneously _redefined_, not erroneously defined.

**Comment by thunderboltsid** [comment]
Fixed.

**Comment by nathanielmanistaatgoogle** [comment]
Luhguhtum.

**Comment by nathanielmanistaatgoogle** [comment]
@nicolasnoble: I think this is now mergeable, though I would have preferred for the test results to have gotten even greener...

**Pull request merged**
