### PR TITLE
Fix URL in README for Python language

### PR DESCRIPTION
**Pull request by vsel**
I don't understand what i need to do(

@veblush

### CODE REVIEW

**Comment by vsel** [comment]
Help me please. What I need to do to merge this request?

**Comment by gnossen** [comment]
Thanks for the fix! You'll have to follow the instructions above to sign a CLA before we can accept your contribution.

**Comment by vsel** [comment]
Thank you! I have sign a CLA.

**Comment by veblush** [comment]
Currently the link appears to correspond to "Quick start" python doc. Does this need to change to Language/Python page? If so, conflict needs to be resolved to get this merged.

**Pull request closed without merging**
