### PR TITLE
Update Google Benchmark to get CMake < 3.6 fix

### PR DESCRIPTION
**Pull request by chwarr**
Google Benchmark v1.4.1 uses a CMake feature that is only in version >=
3.6. This was an inadvertent change in Google Benchmark (too high of a
version) that has been [fixed upsteam][1].

That being said, on 2019-05-01 in [commit 13b8bdc2][2], Google Benchmark
started requiring CMake >= 3.5.1.

Since gRPC still only requires >= CMake 2.8, this commit upgrades the Google
Benchmark submodule to commit 94115f44 (13b8bdc2~1).

Fixes https://github.com/grpc/grpc/issues/18559

[1]: https://github.com/google/benchmark/commit/505be96ab23056580a3a2315abba048f4428b04e
[2]: https://github.com/google/benchmark/commit/13b8bdc2b51805c3ccd666a511ae092784b1c20e

### CODE REVIEW

**Comment by chwarr** [comment]
@jtattermusch: I've created this PR against the 1.22.x branch that has you upb changes. I can move this to master if you want.

**Comment by chwarr** [comment]
I can switch to v1.5.0. That will pull gRPC's CMake minimum version up to 3.5.1. You ok with that?

I'm watching #19504 and will move this when that lands.

**Comment by jtattermusch** [comment]
Let's try switching to v1.5.0.

@nicolasnoble  WDYT?

**Comment by chwarr** [comment]
I've rebased this PR atop a recent master and started [a new PR targeting master](https://github.com/grpc/grpc/pull/19535).

**Pull request closed without merging**
