### PR TITLE
Remove template for extconf.rb and get the version from lib/grpc/version.rb

### PR DESCRIPTION
**Pull request by eregon**
* Having the entire logic of extconf.rb duplicated in 2 files is
  extremely inconvenient, also because the Ruby logic in the YAML template
  does not get any syntax highlighting or IDE features.

### CODE REVIEW

**Comment by eregon** [comment]
@apolcyn Could you review this PR? This makes it so much easier for everyone to modify/maintain the extconf.rb.

**Comment by dennycd** [comment]
cc @HannahShiSFB  can you also help take a look at it ? thanks

**Review by apolcyn — APPROVED** [review]
LGTM

**Comment by eregon** [comment]
Thank you for the review.
The CI seems to pass, the only 2 failures seem preexisting and unrelated.

**Review by dennycd — APPROVED** [review]

**Comment by apolcyn** [comment]
MSAN C++ failures unrelated

**Pull request merged**
