### PR TITLE
Added experimental tvOS and watchOS support

### PR DESCRIPTION
**Pull request by Tony1023**

### CODE REVIEW

**Comment by Tony1023** [comment]
@muxi I guess it was because watch apps must be coupled with iOS apps so together they take longer. Also could you help rerun the sanity checks?

**Comment by Tony1023** [comment]
I removed the example builds for tv and watch with frameworks, so now Basic Tests ObjC Examples  takes about 65 minutes.

**Comment by Tony1023** [comment]
@muxi What about the remote Podspec for `!ProtoCompiler` and `Boring-SSL`? Do we update those to include watchos at some point? Currently we are modifying locally and tell the podfile to use the local copy.

**Comment by muxi** [comment]
Are you talking about `src/objective-c/Podfile`? `BoringSSL-GRPC` has to be remote I think because it is not in the BoringSSL directory. ProtoCompiler is also downloading from online, not local. So these two are ok to be remote podspecs.

**Comment by muxi** [comment]
#19819, #19669

**Comment by Tony1023** [comment]
> Are you talking about `src/objective-c/Podfile`? `BoringSSL-GRPC` has to be remote I think because it is not in the BoringSSL directory. ProtoCompiler is also downloading from online, not local. So these two are ok to be remote podspecs.

I mean adding watchos.deployment_target to the remote podspecs for the next release.

**Pull request merged**
