### PR TITLE
Update version to v1.8.4

### PR DESCRIPTION
**Pull request by murgatroid99**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by y-zeng** [comment]
Can we merge this PR? There are new fixes we need to backport to v1.8.x.

**Comment by nunofgs** [comment]
This PR is sorely needed due to the `GOAWAY received` [error](https://github.com/grpc/grpc-node/issues/138) 😄

**Pull request merged**
