### PR TITLE
Move tests to Cocoapods 1.0.0

### PR DESCRIPTION
**Pull request by jcanizales**
This is a followup of PR #5591, with the fix that was needed for Travis to behave.

Solves https://github.com/grpc/grpc/issues/5602.

### CODE REVIEW

**Comment by jcanizales** [comment]
Dear Googlebot: @pquerna generously intended for his commits to be contributed, as evidenced by his pull request.
Best wishes,
Jorge

**Comment by pquerna** [comment]
Okay with commits

**Comment by jcanizales** [comment]
Test this please.

**Comment by jcanizales** [comment]
The portability test is a problem with Jenkins (although not a flake). Opened https://github.com/grpc/grpc/issues/6677 for it.

**Comment by jcanizales** [comment]
Opened issues for the two unrelated flakes. Ready to merge?

**Comment by jcanizales** [comment]
@makdharma Ping; this blocks my other PRs.

**Comment by jcanizales** [comment]
Ping.

**Comment by jcanizales** [comment]
Pretty please?

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @pquerna isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request merged**
