### PR TITLE
[PSM Interop] Ignore DeprecationWarning: HTTPResponse.getheaders()

### PR DESCRIPTION
**Pull request by sergiitk**
Disables the warning produced by kubernetes/client/rest.py calling the deprecated `urllib3.response.HTTPResponse.getheaders`, `urllib3.response.HTTPResponse.getheader` methods:

```
venv-test/lib/python3.9/site-packages/kubernetes/client/rest.py:44: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.
  return self.urllib3_response.getheaders()
```

This issue introduced by openapi-generator, and solved in `v6.4.0`. To fix the issue properly, kubernetes/python folks need to regenerate the library using newer openapi-generator. The most recent release `v27.2.0` still used openapi-generator [`v4.3.0`](https://github.com/kubernetes-client/python/blob/v27.2.0/kubernetes/.openapi-generator/VERSION).
Since they release two times a year, and the 2 major version difference of openapi-generator, the fix may take a while.

Created an issue in their repo: https://github.com/kubernetes-client/python/issues/2101.

### CODE REVIEW

**Comment by sergiitk** [comment]
- [ ] [grpc/java/v1.57.x/branch/xds_k8s_lb](https://source.cloud.google.com/results/invocations/8211f624-08af-4e2c-ad4e-12be772f73d2)
- [ ] [grpc/java/v1.57.x/branch/psm-security](https://source.cloud.google.com/results/invocations/963d8eb3-330a-4250-a16c-df73cf6e8567)
- [ ] [grpc/java/v1.57.x/branch/xds_url_map](https://source.cloud.google.com/results/invocations/b0c258c8-8433-4159-bb3c-836c6d14c3b8)

**Comment by sergiitk** [comment]
Apparently there's another place where this is happening:

```
/tmp/tmp.Htth7yh8wI/grpc/tools/run_tests/xds_k8s_test_driver/venv/lib/python3.10/site-packages/kubernetes/client/exceptions.py:91: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.
  self.headers = http_resp.getheaders()
```

**Comment by sergiitk** [comment]
- [ ] [grpc/java/v1.57.x/branch/xds_k8s_lb](https://source.cloud.google.com/results/invocations/43d4d137-993f-4b29-89a4-9a2c16629b5f)
- [ ] [grpc/java/v1.57.x/branch/psm-security](https://source.cloud.google.com/results/invocations/ec919177-5376-4056-8e65-40b61b086ab0)
- [ ] [grpc/java/v1.57.x/branch/xds_url_map](https://source.cloud.google.com/results/invocations/ccc2160c-ffc6-4bb1-8a56-3733fb03e98d)

**Comment by sergiitk** [comment]
All looks good now.

**Review by gnossen — APPROVED** [review]

**Pull request merged**
