### PR TITLE
Remove and Prohibit C Style Casts

### PR DESCRIPTION
**Pull request by ncteisen**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +432  +0.0%

  [ = ]       0 TOTAL     +432  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +432  +0.0%

  [ = ]       0 TOTAL     +432  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.1%    -344 [None]                                                                               -1.95Ki  -0.0%
  -1.8%    -256 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                          -256  -1.8%
      [DEL] -1.50Ki rr_handover_locked(glb_lb_policy*) [clone .part.19]                                  -1.50Ki  [DEL]
      [DEL]    -801 build_lb_channel_args(grpc_lb_addresses const*, grpc_fake_resolver_response_generato    -801  [DEL]
      [DEL]    -531 send_client_load_report_locked                                                          -531  [DEL]
      [DEL]    -284 glb_lb_call_data_unref                                                                  -284  [DEL]
     -36.2%    -234 lb_on_server_status_received_locked                                                     -234 -36.2%
      [DEL]    -145 lb_call_data_shutdown(glb_lb_policy*) [clone .isra.4]                                   -145  [DEL]
      [DEL]    -119 schedule_next_client_load_report                                                        -119  [DEL]
      [DEL]     -92 glb_lb_call_data_ref                                                                     -92  [DEL]
     -16.9%     -73 [Unmapped]                                                                               -73 -16.9%
      -6.2%     -64 glb_create                                                                               -64  -6.2%
      -4.3%     -58 lb_on_response_received_locked                                                           -58  -4.3%
      [DEL]     -58 maybe_send_client_load_report_locked                                                     -58  [DEL]
     -42.0%     -55 query_for_backends_locked                                                                -55 -42.0%
     -56.8%     -46 lb_on_sent_initial_request_locked                                                        -46 -56.8%

  -0.0%    -600 TOTAL                                                                                -2.20Ki  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +416  +0.0%

  [ = ]       0 TOTAL     +416  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +416  +0.0%

  [ = ]       0 TOTAL     +416  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +416  +0.0%

  [ = ]       0 TOTAL     +416  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +416  +0.0%

  [ = ]       0 TOTAL     +416  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +416  +0.0%

  [ = ]       0 TOTAL     +416  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +416  +0.0%

  [ = ]       0 TOTAL     +416  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by dgquintas** [comment]
Github refuses to show the full list of changes... But if a change like this, which I presume was done via some script, compiles and tests are happy, I am happy.

And on that note, [some tests](https://sponge.corp.google.com/target?id=a08c3cff-e8c4-4602-ae49-b06cb6f058fd&target=grpc/ubuntu/pull_request/grpc_portability_build_only&searchFor=&show=FAILED&sortBy=STATUS) aren't happy:
```
test/core/iomgr/tcp_server_posix_test.cc: In function 'void test_connect(size_t, const grpc_channel_args*, test_addrs*, bool)':
test/core/iomgr/tcp_server_posix_test.cc:313:69: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'unsigned int' [-Werror=format=]
           dst_addrs != nullptr ? "<specific>" : "::", test_dst_addrs);

```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +416  +0.0%

  [ = ]       0 TOTAL     +416  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Pull request merged**
