### PR TITLE
Fix bazel incompatible changes

### PR DESCRIPTION
**Pull request by keith**
When building grpc with the upcoming `--incompatible_depset_is_not_iterable` flag, these violations were found

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @keith isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by keith** [comment]
cc @laurentlb

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @keith isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by keith** [comment]
@thelinuxfoundation signed!

**Comment by keith** [comment]
These CI failures look unrelated to my change, and like a `make` build is failing. Any ideas?

**Comment by gnossen** [comment]
Known failures:
 - https://github.com/grpc/grpc/issues/18967
 - https://github.com/grpc/grpc/issues/18416

These issues explain the two interops tests and "Basic C++ Tests Linux". Rerunning the others to check if they're flakes. Hopefully the [Github webhook outage](https://www.githubstatus.com/incidents/nf4gcjtcsqdb) won't affect this too much.

**Comment by gnossen** [comment]
@nicolasnoble Can you please stamp this with code owner approval?

**Comment by keith** [comment]
Thanks!

**Pull request merged**
