### PR TITLE
Re-enable GoogleDefaultCreds C++ cloud to prod auth tests

### PR DESCRIPTION
**Pull request by apolcyn**
Reverts https://github.com/grpc/grpc/pull/16880 after fixing the underlying issue of https://github.com/grpc/grpc/issues/16879

This change brings back #16841 but does two things differently:
1) When the test is an auth test that needs a service account key file (e.g. `jwt_token_creds`) and we're using GoogleDefaultCredentials, then regardless of where we're running, set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to a valid service account key file, allowing these tests to run outside of GCP.
2) When running outside of GCP, and the test is <i>not</i> an auth test (e.g. `empty_stream`) but we are using GoogleDefaultCredentials, set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to a valid service account key file, so that the channel can still operate.
3) Skip `per_rpc_creds` and `oauth2_auth_token` tests when GoogleDefaultCredentials is in use, because these test cases are designed to test features that are irrelevant to GoogleDefaultCredentials

PTAL

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,922      Total (=)      1,965,922

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,001      Total (=)     10,909,001

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,242      Total (=)      1,965,242

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,022      Total (<)     10,909,033

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,242      Total (=)      1,965,242

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,020      Total (>)     10,909,019

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
sorry, after an offline chat, I've decided to shelf this PR, and will add a new standalone interop test that's designed for testing GoogleDefaultCredentials

**Comment by jtattermusch** [comment]
@apolcyn  +1 because I was a bit confused by the PR and was thinking (without much success) about how to make it "the right way"

**Pull request closed without merging**
