### PR TITLE
Change XdsClient to use its own mutex instead of the channel's WorkSerializer.

### PR DESCRIPTION
**Pull request by markdroth**
This paves the way for sharing the XdsClient between channels.  Each channel has its own WorkSerializer, so we will need to have the XdsClient handle its own synchronization to share data between channels.

### CODE REVIEW

**Comment by markdroth** [comment]
Looks like there are some asan and msan failures, so please hold off on reviewing this while I fix those.

**Comment by markdroth** [comment]
This is ready for review now.

**Review by donnadionne — APPROVED** [review]

**Comment by markdroth** [comment]
Known issues: #23933

The two Windows failures are infrastructure timeouts.

**Comment by voidzcy** [comment]
Assuming the threading model is the same for C-core and Java. Shouldn't each watcher's callback be invoked by *the thread of client Channel that owns the watcher* (or at least some thread owned per client Channel)? Here each watcher's callback is invoked by *XdsClient's channel thread*, although it is synchronized with each client Channel by using each's WorkSerializer. Wouldn't this cause the XdsClient lock to be held for unnecessarily long? Also, the worse thing is that the XdsClient's lock is mixed with client Channel's WorkSerializer. The XdsClient lock may still be held when running other tasks in the client Channel's WorkSerializer.

**Comment by markdroth** [comment]
I'm not sure what you mean by "the thread of client Channel that owns the watcher".  In C-core, channels do not own threads.  All threads are borrowed from the application, and any action can occur in any thread.

But in answer to your main question about the XdsClient lock semantics, this code avoids those problems by having the watcher callback be scheduled on the `ExecCtx` instead of being executed in-line, which means that the real watcher callback doesn't actually get invoked until after the XdsClient lock is released.  This indirection is actually done by the watcher impls themselves instead of by the XdsClient, which is admittedly a bit sub-optimal -- it would be cleaner for the XdsClient itself to enforce that, but that would require making the watchers ref-counted, which would add more complexity.  And given that this is a purely internal API, I was willing to live with the requirement that each watcher impl does that indirection.

**Pull request merged**
