### PR TITLE
Python OWNERship

### PR DESCRIPTION
**Pull request by mehrdada**

### CODE REVIEW

**Comment by ctiller** [comment]
Now that there's three folks here, can I suggest adding a 'set noparent' to the top of this file?

**Comment by mehrdada** [comment]
@ctiller  Sure. Is there a way to include files?

**Comment by ctiller** [comment]
There's no inclusion mechanism (although there's an implicit include of parent directories unless 'set noparent' is in the OWNERS file)

**Comment by ctiller** [comment]
(see #11812)

**Comment by mehrdada** [comment]
Done

**Pull request merged**
