### PR TITLE
fix docker -p flag for interop tests

### PR DESCRIPTION
**Pull request by ericgribkoff**
Fixes https://github.com/grpc/grpc/issues/10374.

This undoes a change from https://github.com/grpc/grpc/commit/996a6734235ac21cb6a6222425fadc93706c93c3. The `-p port:port` flag tells Docker to map the container port to a specific host port. This constrains exactly one container to listen on the port, so when any server container runs after another server container has already started, it fails to bind.

### CODE REVIEW

**Comment by ericgribkoff** [comment]
Status update on this: Changes in the most recent `h2` package on pip also broke the http2 test server and its health check mechanism. Setting the dockerfile to install `h2` at version 2.6.1 gets the tests passing locally; still waiting for Jenkins to see if any other issues pop up. It's probably also a good idea to hardcode the versions of twisted and h2 that are installed to avoid this type of issue in the future, but will consider that in a separate PR.

**Comment by ericgribkoff** [comment]
Interop tests are passing. Will merge after the other tests complete.

**Comment by makdharma** [comment]
@ericgribkoff Thanks for fixing this. How did you find this issue? My PR did not trigger anything that wasn't already failing.

**Comment by ericgribkoff** [comment]
@makdharma When the Go interop docker image was failing to build, the interop tests were all being aborted before anything ran. https://grpc-testing.appspot.com/job/gRPC_interop_master/ hasn't had a successful build in 6 days, with the first failure being the Go docker problem, but that allowed other issues to pop up in the meantime (including `h2` releasing version `3.0.0` five days ago)

**Comment by ericgribkoff** [comment]
Known failures: https://github.com/grpc/grpc/issues/10199

Basic Tests Mac is heavily backlogged or stalled. Merging without waiting for it - nothing here should impact Mac tests, and want to get interop green again.

**Pull request merged**
