### PR TITLE
Add an option to rebuild core configuration in tests.

### PR DESCRIPTION
**Pull request by yousukseung**

### CODE REVIEW

**Comment by ctiller** [comment]
This seems likely to introduce cases whereby we leak configuration between tests and inadvertently create ordering issues.

**Comment by yousukseung** [comment]
> 

Actually I'm adding this to fix an order-dependent test (b/238890770).
I updated a bit to add a function to rebuild, let me know if this one looks OK.

To provide some context, I think there's no way to restore core configuration back after calling BuildSpecialConfiguration(), and after my recent CL we now have a test file with tests that both require the original config and that use BuildSpecialConfiguration(), which is order-dependent.

**Comment by ctiller** [comment]
We use CoreConfiguration::RunWithSpecialConfiguration to handle this
scenario in a few places.

**Comment by yousukseung** [comment]
> RunWithSpecialConfiguration

Yes, I'm aware but not sure if that can help here, the test I am fixing already does what RunWithSpecialConfiguration() does (reset-build-test-reset).

In the above test file, there are tests that require builders that we register to ResolverRegistry during initialization, and other tests that override. It only passes if the latter ones run after the former in the same process, but this is not always guaranteed.

**Comment by yousukseung** [comment]
Craig, I am instead adding a function that rebuilds with registered builders. Also removed CallRegisteredBuilders() that was declared but never defined, but if what I'm adding is what this was going to do I can rename the new function to this. Let me know.

**Comment by yousukseung** [comment]
I found a fix that does not require this fix, closing.

**Pull request closed without merging**
