### PR TITLE
C++ Compression Level set properly

### LINKED ISSUE #6998: Missing function export in grpc_dll
I found out grpc++.lib calls the function grpc_call_compression_for_level which is not exported in the grpc.def list containing the exports from grpc_dll.

Just adding grpc_call_compression_for_level to grpc.def fixes.

I found the problem on release-0_14_1

Can you please add this export?

### PR DESCRIPTION
**Pull request by dgquintas**
That is, through the send initial metadata op.

Fixes #6998

### CODE REVIEW

**Comment by ctiller** [comment]
Worth checking qps impact before submission

**Comment by dgquintas** [comment]
Done.

Some scenarios:

At master:
```
RUNNING SCENARIO: cpp_generic_async_streaming_ping_pong_secure
I0722 13:20:14.305978771   30996 report.cc:75]               QPS: 11495.2
I0722 13:20:14.307985246   30996 report.cc:79]               QPS: 11495.2 (11495.2/server core)
I0722 13:20:14.308015055   30996 report.cc:84]               Latencies (50/90/95/99/99.9%-ile): 87.6/90.0/91.7/103.0/136.5 us
```
At branch:
```
RUNNING SCENARIO: cpp_generic_async_streaming_ping_pong_secure
I0722 12:48:01.812688886   12232 report.cc:75]               QPS: 11685.9
I0722 12:48:01.814797951   12232 report.cc:79]               QPS: 11685.9 (11685.9/server core)
I0722 12:48:01.814828993   12232 report.cc:84]               Latencies (50/90/95/99/99.9%-ile): 85.2/89.2/91.3/103.2/140.6 us
```
 
At master:
```
RUNNING SCENARIO: cpp_generic_async_streaming_qps_one_server_core_insecure
I0722 13:23:26.412124839   31498 report.cc:75]               QPS: 202993.0
I0722 13:23:26.412972121   31498 report.cc:79]               QPS: 202993.0 (202993.0/server core)
I0722 13:23:26.412985945   31498 report.cc:84]               Latencies (50/90/95/99/99.9%-ile): 31265.1/32659.3/33487.3/36995.6/73239.1 us

```

At branch:
```
RUNNING SCENARIO: cpp_generic_async_streaming_qps_one_server_core_insecure
I0722 12:51:13.932141166   12574 report.cc:75]               QPS: 200969.1
I0722 12:51:13.934612692   12574 report.cc:79]               QPS: 200969.1 (200969.1/server core)
I0722 12:51:13.934674187   12574 report.cc:84]               Latencies (50/90/95/99/99.9%-ile): 31407.6/33185.2/34475.6/45716.1/73245.0 us
```

Other scenarios are similarly equivalent in terms of QPS/Lacencies.

**Comment by sreecha** [comment]
LGTM.

**Comment by dgquintas** [comment]
test this please

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
