### PR TITLE
Use go1.19 for go interop tests and for future interop_matrix tests

### PR DESCRIPTION
**Pull request by dfawley**
Attempting to recreate #26124, but for 1.19 so that Go tests will be green again.

I ran `LOCAL_ONLY_MODE=true tools/dockerfile/push_testing_images.sh` (it seems inappropriate to push these since they haven't been reviewed), as described in the README, but it looks like it was actually trying to upload the image it built at the end(?!):

```
The push refers to repository [us-docker.pkg.dev/grpc-testing/testing-images-public/grpc_interop_go1.19]
c158f0568ed9: Preparing 
42bde5dd8372: Preparing 
a440f7febf21: Preparing 
ad53d709b97c: Preparing 
99e8acd709fa: Preparing 
6201ebf6567d: Waiting 
de3f6c83fe06: Waiting 
6a7921805df0: Waiting 
89c3244a87b2: Waiting 
80231db1194c: Waiting 
f1c1f2298584: Waiting 
ccba29d69370: Waiting 
denied: Permission "artifactregistry.repositories.uploadArtifacts" denied on resource "projects/grpc-testing/locations/us/repositories/testing-images-public" (or it may not exist)
```

From `push_testing_images.sh` this seems backwards?:

```
  if [ "${SKIP_UPLOAD}" == "" ] && [ "${LOCAL_ONLY_MODE}" != "" ]
  then
    docker push ${ARTIFACT_REGISTRY_PREFIX}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
  fi
```

### CODE REVIEW

**Comment by ejona86** [comment]
> it seems inappropriate to push these since they haven't been reviewed

Uploading is actually mostly fine, because they are tagged with the hash of their contents (essentially content-addressable storage). So nothing will use it unless it is the right thing to use it. It would "just" waste storage.

**Review by ejona86 — APPROVED** [review]
This looks good, but we need to publish the images first (and should be able to see the tests pass? Dunno if those are still run per-PR now; I think they might not.).

**Comment by Japan50079** [comment]
Eric Anderson ***@***.***>于2022年11月23日 周三03:31写道：

**Comment by jtattermusch** [comment]
> Attempting to recreate #26124, but for 1.19 so that Go tests will be green again.
> 
> I ran `LOCAL_ONLY_MODE=true tools/dockerfile/push_testing_images.sh` (it seems inappropriate to push these since they haven't been reviewed), as described in the README, but it looks like it was actually trying to upload the image it built at the end(?!):
> 
> ```
> The push refers to repository [us-docker.pkg.dev/grpc-testing/testing-images-public/grpc_interop_go1.19]
> c158f0568ed9: Preparing 
> 42bde5dd8372: Preparing 
> a440f7febf21: Preparing 
> ad53d709b97c: Preparing 
> 99e8acd709fa: Preparing 
> 6201ebf6567d: Waiting 
> de3f6c83fe06: Waiting 
> 6a7921805df0: Waiting 
> 89c3244a87b2: Waiting 
> 80231db1194c: Waiting 
> f1c1f2298584: Waiting 
> ccba29d69370: Waiting 
> denied: Permission "artifactregistry.repositories.uploadArtifacts" denied on resource "projects/grpc-testing/locations/us/repositories/testing-images-public" (or it may not exist)
> ```
> 
> From `push_testing_images.sh` this seems backwards?:
> 
> ```
>   if [ "${SKIP_UPLOAD}" == "" ] && [ "${LOCAL_ONLY_MODE}" != "" ]
>   then
>     docker push ${ARTIFACT_REGISTRY_PREFIX}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
>   fi
> ```

You're absolutely right, I already had a PR to fix this, but it hasn't been merged yet: https://github.com/grpc/grpc/pull/31689

**Comment by jtattermusch** [comment]
> Sanity tests are failing with `grep: tools/dockerfile/interoptest/grpc_interop_go1.19.current_version: No such file or directory`. I have no clue what is up with that.
> 
> @jtattermusch, @drfloob, @sergiitk, what is this newfangled stuff?

See the description of https://github.com/grpc/grpc/pull/31591 for context.

**Pull request merged**
