### PR TITLE
Workarounding bazelbuild/bazel#6831

### PR DESCRIPTION
**Pull request by nicolasnoble**
This will take care of the bazel crash until we have a proper fix upstream.

bazelbuild/bazel#6831

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,410      Total (=)      2,020,410

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,174,084      Total (>)     11,174,078

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
can you post a link with the crash?

**Comment by nicolasnoble** [comment]
It's actually in the title. Github didn't create a link from it however. bazelbuild/bazel#6831

**Pull request merged**
