### PR TITLE
mitigate gcc8 -Wstringop-truncation and -Wignored-qualifiers

### PR DESCRIPTION
**Pull request by toanju**
this PR deals with the warnings of gcc8

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by toanju** [comment]
any updates on this? Is it worth to invest some time to rebase and resolve the conflicts?

**Comment by toanju** [comment]
amended fixes for -Werror=class-memaccess (as well appearing with gcc8)

**Comment by toanju** [comment]
since some distros now ship gcc8, did anybody have a look at this, yet?

**Comment by toanju** [comment]
I am still willing to update this - though I would need some feedback in case there is something off. #15443 has another solution to this issue. Could anyone comment please @dgquintas @nicolasnoble

**Comment by toanju** [comment]
updated to master

**Comment by toanju** [comment]
can anybody please comment how to proceed with this one @dgquintas @nicolasnoble @vjpai ?

**Comment by matoro** [comment]
Does this PR address `-Wno-invalid-source-encoding`?

**Comment by toanju** [comment]
no it does not, which compiler and version do you use?

**Comment by toanju** [comment]
since I just updated this branch, I am using `gcc (GCC) 8.2.1 20181105 (Red Hat 8.2.1-5)` and currently the errors dealt with are:

```
-Werror=tautological-compare
-Werror=stringop-truncation
-Werror=ignored-qualifiers
-Werror=class-memaccess
```

(each in a separate commit)

**Comment by matoro** [comment]
@toanju This is a build issue more than a compile one.  I am on `gcc (Gentoo Hardened 8.2.0-r5 p1.6) 8.2.0` so it may be a change between 8.2.1 -> 8.2.0.  Here's what it spits out in the `c-ares` build:

```

This could be fixable by patching the makefile, but I don't know how to do that when `gem` is invoked from `bundle`.
[C]       Compiling third_party/cares/cares/ares_library_init.c
mkdir -p `dirname /var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_library_init.o`                                                                                                                            
armv7a-unknown-linux-gnueabihf-gcc -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/boringssl/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/address_sorting/include -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -Werror -Wno-long-long
-Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -Wno-deprecated-declarations -Ithird_party/nanopb -DPB_FIELD_32BIT -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/gens -DNDEBUG                
-DINSTALL_PREFIX=\"/usr/local\"   -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -fvisibility=hidden -D_GNU_SOURCE   -Ithird_party/cares/config_linux  -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DHAVE_CONFIG_H -O3 -pipe -march=native -funroll-loops -flto=8 -floop-block               
-floop-interchange -floop-strip-mine -ftree-loop-distribution -std=c99 -Wsign-conversion -Wconversion     -Wno-sign-conversion  -Wno-invalid-source-encoding -MMD -MF                                                                                                                                                   
/var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_library_init.dep -c -o                                                                                                                                       
/var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_library_init.o third_party/cares/cares/ares_library_init.c                                                                                                   
third_party/cares/cares/ares_init.c: In function ‘ares_dup’:
third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
           sizeof(src->local_dev_name));
                 ^
[C]       Compiling third_party/cares/cares/ares_llist.c
mkdir -p `dirname /var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_llist.o`
armv7a-unknown-linux-gnueabihf-gcc -Ithird_party/googletest/googletest/include -Ithird_party/googletest/googlemock/include -Ithird_party/boringssl/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/address_sorting/include -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -Werror -Wno-long-long
-Wno-unused-parameter -DOSATOMIC_USE_INLINED=1 -Wno-deprecated-declarations -Ithird_party/nanopb -DPB_FIELD_32BIT -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/gens -DNDEBUG
-DINSTALL_PREFIX=\"/usr/local\"   -Ithird_party/zlib -Ithird_party/cares -Ithird_party/cares/cares -fvisibility=hidden -D_GNU_SOURCE   -Ithird_party/cares/config_linux  -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DHAVE_CONFIG_H -O3 -pipe -march=native -funroll-loops -flto=8 -floop-block
-floop-interchange -floop-strip-mine -ftree-loop-distribution -std=c99 -Wsign-conversion -Wconversion     -Wno-sign-conversion  -Wno-invalid-source-encoding -MMD -MF
/var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_llist.dep -c -o
/var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_llist.o third_party/cares/cares/ares_llist.c
third_party/cares/cares/ares_init.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [Makefile:2896: /var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares_init.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)24

extconf failed, exit code 1

Gem files will remain installed in /var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/gems/grpc-1.15.0 for inspection.
Results logged to /var/tmp/portage/dev-vcs/gitlab-gitaly-0.129.0/work/ruby/vendor/bundle/ruby/2.4.0/extensions/armv7a-linux/2.4.0/grpc-1.15.0/gem_make.out

An error occurred while installing grpc (1.15.0), and Bundler cannot continue.
Make sure that `gem install grpc -v '1.15.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  gitaly-proto was resolved to 0.123.0, which depends on
    grpc
make[1]: *** [Makefile:32: ../.ruby-bundle] Error 5
```

**Comment by matoro** [comment]
Same error as this guy:  https://github.com/grpc/grpc/issues/15520 so it is not specific to Gentoo or to gcc 8.2.0.  Gentoo has a number of gcc8-related patches: https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/grpc/files but because this is pulled from rubygems these would not be applied.  This is also on a significantly newer ruby version (2.4) and grpc (1.15.0)

**Comment by matoro** [comment]
The problem is that this flag is added somewhere downstream, not in the vanilla c-ares build.  Looking at line 10252 of the grpc makefile, I would think that it would only be added if a mingw environment is detected, but I cannot find anywhere else in the build stream that this flag is mentioned.

**Comment by toanju** [comment]
Rebased to master. Even if it's almost a year I am looking for feedback.

**Comment by AspirinSJL** [comment]
@nicolasnoble Friendly reminder.

**Pull request closed without merging**
