### PR TITLE
Fixing 32 bits version of the memcpy wrapper.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
For @ctiller: otherwise we're just recursively looping ;-)

**Comment by nicolasnoble** [comment]
Actually, no, that'll fail if we do NOT use the -Wl thingy. Altering the PR slightly.

**Comment by jtattermusch** [comment]
Fixes #5022

**Comment by jtattermusch** [comment]
32bit compilation fails:
```
src/core/support/wrap_memcpy.c: In function '__wrap_memcpy':
src/core/support/wrap_memcpy.c:55:3: error: implicit declaration of function '__real_memcpy' [-Werror=implicit-function-declaration]
   return __real_memcpy(destination, source, num);
```

**Comment by nicolasnoble** [comment]
Of course it does.

*sigh*

**Comment by jtattermusch** [comment]
I just tested that this change solves #5022, but I already merged #5036 with an alternative fix.

Let's leave this PR around for future polishing.

**Comment by jtattermusch** [comment]
Closing for now, but we can revive this later.

**Pull request closed without merging**
