### PR TITLE
Add write with options interface to AsyncWriterInterface

### PR DESCRIPTION
**Pull request by lizan**

### CODE REVIEW

**Comment by lizan** [comment]
Ping.

**Comment by vjpai** [comment]
Jenkins, this is ok to test

**Comment by vjpai** [comment]
Jenkins, test this please

**Comment by vjpai** [comment]
This code needs to be clang-formatted before it can be merged. Please run 
```
tools/distrib/clang_format_code.sh
```

You'll need docker installed.

**Pull request closed without merging**
