### PR TITLE
Manual upmerge from 1.0.x to master.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Trivial conflict in build.yaml due to the movements we've been doing in there.

### CODE REVIEW

**Comment by murgatroid99** [comment]
LGTM

**Comment by murgatroid99** [comment]
test this please

**Comment by nicolasnoble** [comment]
*groan*

**Comment by nicolasnoble** [comment]
Strange, sanity isn't happy.

**Comment by murgatroid99** [comment]
I've been seeing the `check_nanopb_output` failure a lot, but the rest are actual failures.

**Comment by nicolasnoble** [comment]
Yep, ok, something is broken with that merge. I'll fix it.

**Comment by nicolasnoble** [comment]
Except for a few unrelated tests, everything's green now. Merging this.

**Pull request merged**
