### PR TITLE
Have a dedicated server security connector.

### PR DESCRIPTION
**Pull request by jboeuf**
That was overdue and the handshake is now slightly different for clients
(channels) and servers.

### CODE REVIEW

**Comment by jboeuf** [comment]
@daniel-j-born may want to have a look as well.

**Comment by daniel-j-born** [comment]
The main change I noticed is the server security connector now takes an acceptor. LGTM.

**Comment by yang-g** [comment]
LGTM Seems sanity is failing, merge with head?

**Comment by jboeuf** [comment]
Looks somewhat green now.

**Pull request merged**
