### PR TITLE
Fix CMake for windows (VS2015)

### PR DESCRIPTION
**Pull request by KindDragon**
This fix all issues except referred boringssl @ c880e42 commit doesn't compile with VS2013 because of several warnings and boringssl/master only support VS2015 (it's easy to fix, but they do not want this)

### CODE REVIEW

**Comment by nicolasnoble** [comment]
So unfortunately, for maintainability, you'd need to modify the file `templates/CMakeLists.txt.template` to keep everything in sync. Could you do that please ?

**Comment by KindDragon** [comment]
Done

**Comment by nicolasnoble** [comment]
You actually have a few whitespaces discrepancies between the template and the generated file, and it makes the test sad :-) I've fixed this for you since running the template system might be a bit bothersome in KindDragon/grpc#1 - if you merge that PR, yours here will be automatically updated and its tests should pass.

**Comment by KindDragon** [comment]
> You actually have a few whitespaces discrepancies between the template and the generated file, and it makes the test sad :-) I've fixed this for you since running the template system might be a bit bothersome in KindDragon/grpc#1 - if you merge that PR, yours here will be automatically updated and its tests should pass.

Thank you

**Comment by KindDragon** [comment]
I don't know what to do with boringssl, current commit doesn't compile because some warnings treated as errors. Master fix this, but they doesn't support VS2013 anymore.

**Comment by nicolasnoble** [comment]
I'm not sure we should do anything about BoringSSL, really. Can't we capture an external build of OpenSSL in the CMakefile ? If the user installed https://slproweb.com/products/Win32OpenSSL.html for example.

**Comment by KindDragon** [comment]
If OpenSSL as good as BoringSSL for us, we can do that. But this task for separate PR.

**Comment by KindDragon** [comment]
We also can download OpenSSL from [Conan.io](https://www.conan.io/search?q=ssl).

**Comment by nicolasnoble** [comment]
BoringSSL is shown as a submodule because it's easier for us to distribute, since it's a Google product. But OpenSSL 1.0.2+ works too.

**Comment by topillar** [comment]
why not libressl?

**Pull request merged**
