### PR TITLE
Add missing extern C

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by markdroth** [comment]
Would it make sense to put the `extern "C"` blocks inside of the header files being included, so that if we have other C++ callers in the future, they don't need to do it themselves?

**Comment by yang-g** [comment]
The style guide says to include that in public headers and I think it is better to add is in here as it is a C++ file and maybe there will be new internal C headers will be added in the future.

**Comment by yang-g** [comment]
jenkins: test this please

**Comment by yang-g** [comment]
#12262 #11737

**Pull request merged**
