### PR TITLE
cmake: choose the right protoc executable with gRPC_PROTOBUF_PROVIDER=package

### LINKED ISSUE #12230: CMake: Error evaluating generator expression for protoc package
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
master(2017-08-20)
 
### What operating system (Linux, Windows, …) and version?
Windows 7, Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2013 (Win7), Visual Studio 2015 (Win10)
 
### What did you do?
```
cmake -G "Visual Studio 12" -D CMAKE_INSTALL_PREFIX:PATH=D:\Build\gRPC\install -D CMAKE_DEBUG_POSTFIX:STRING=d -D gRPC_SSL_PROVIDER:STRING=package -D OPENSSL_ROOT_DIR:PATH=D:\Build\gRPC\deps\OpenSSL\install -D OPENSSL_USE_STATIC_LIBS:BOOL=ON -D gRPC_PROTOBUF_PROVIDER:STRING=package -D Protobuf_INCLUDE_DIR:PATH=D:\Build\gRPC\deps\protobuf\install\include -D Protobuf_LIBRARY_DEBUG:FILEPATH=D:\Build\gRPC\deps\protobuf\install\lib\libprotobufd.lib -D Protobuf_LIBRARY_RELEASE:FILEPATH=D:\Build\gRPC\deps\protobuf\install\lib\libprotobuf.lib -D Protobuf_LITE_LIBRARY_DEBUG:FILEPATH=D:\Build\gRPC\deps\protobuf\install\lib\libprotobuf-lited.lib -D Protobuf_LITE_LIBRARY_RELEASE:FILEPATH=D:\Build\gRPC\deps\protobuf\install\lib\libprotobuf-lite.lib -D Protobuf_PROTOC_EXECUTABLE:FILEPATH=D:\Build\gRPC\deps\protobuf\install\bin\protoc.exe -D Protobuf_PROTOC_LIBRARY_DEBUG:FILEPATH=D:\Build\gRPC\deps\protobuf\install\lib\libprotocd.lib -D Protobuf_PROTOC_LIBRARY_RELEASE:FILEPATH=D:\Build\gRPC\deps\protobuf\install\lib\libprotoc.lib -D Protobuf_SRC_ROOT_FOLDER:PATH=D:\Build\gRPC\deps\protobuf\install -D gRPC_ZLIB_PROVIDER:STRING=package -D ZLIB_INCLUDE_DIR:PATH=D:\Build\gRPC\deps\zlib\install\include -D ZLIB_LIBRARY_DEBUG:FILEPATH=D:\Build\gRPC\deps\zlib\install\lib\zlibstaticd.lib -D ZLIB_LIBRARY_RELEASE:FILEPATH=D:\Build\gRPC\deps\zlib\install\lib\zlibstatic.lib -D gRPC_CARES_PROVIDER:STRING=package -D c-ares_DIR:PATH=D:\Build\gRPC\deps\c-ares\install -D GIT_EXECUTABLE:FILEPATH=D:\Build\GIT\bin\git.exe D:\Build\gRPC\src
```
 
### What did you expect to see?
```
-- Build files have been written to: D:/Build/gRPC/build
```
 
### What did you see instead?
```
CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3202 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3202 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3202 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3202 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3332 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3332 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3332 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3332 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3202 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3202 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3202 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3202 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3332 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3332 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3332 (protobuf_generate_grpc_cpp)


CMake Error at CMakeLists.txt:336 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:D:/Build/gRPC/deps/protobuf/install/bin/protoc.exe>

  Expression syntax not recognized.
Call Stack (most recent call first):
  CMakeLists.txt:3332 (protobuf_generate_grpc_cpp)
```
 
### Anything else we should know about your project / environment?
This solved my issue: #11891

### PR DESCRIPTION
**Pull request by jtattermusch**
- also move cmake config files from `tools/cmake` to `cmake` directory

Fixes #12230

Supersedes PRs #11891 and #11794.

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @kskalski  @hesmar  this should solve the issues pointed out in your PRs and I feel this way is more readable. Sorry for the delay, it took me a while to come up with this PR as it was originally part of a larger effort to improve our CMakeFile.txt and add some tests to continue it keeps working well.

The first prerequisite is to finish up  https://github.com/grpc/grpc/pull/12305 and get it merged (and I have some followup changes on top of it).

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/issues/12461
https://github.com/grpc/grpc/issues/12428
https://github.com/grpc/grpc/issues/12475
https://github.com/grpc/grpc/issues/12138
https://github.com/grpc/grpc/issues/12476
https://github.com/grpc/grpc/issues/12261

**Comment by BusyJay** [comment]
Will v1.6.1 contain this changes?

**Comment by jtattermusch** [comment]
@BusyJay  most likely not, it's going to be in v1.7.0

**Pull request merged**
