### PR TITLE
[channel_posix] Don't hardcode the :authority header.

### LINKED ISSUE #12401: grpc_insecure_channel_create_from_fd() hardcodes the default authority to 'test.authority'
gRPC 1.7.0-dev, Linux 4.4 (Ubuntu 14.04)

For reasons unknown to me, the `grpc_insecure_channel_create_from_fd()` function adds a channel argument setting the default `:authority` HTTP/2 header to `test.authority`. This means that any HTTP/2 requests sent by gRPC on a channel created with this function will set the `:authority` field to `test.authority`. If a proxy along the path to the gRPC server relies on the `:authority` field, it may break as a result.

Normally, it's possible to override the default authority by supplying an argument to `grpc_channel_create_call()`. However, the Python bindings provide no way to do such a thing--cf. #12400.

### PR DESCRIPTION
**Pull request by ced5**
Fixes #12401.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @ced5 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by ced5** [comment]
Done.

**Comment by ncteisen** [comment]
@vjpai @yang-g @sreecha, anyone know why this was hardcoded in the first place?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                             FILE SIZE
 ++++++++++++++ GROWING                                                               ++++++++++++++

 -------------- SHRINKING                                                             --------------
  -0.0%     -16 [None]                                                                   -184  -0.0%
  -8.5%     -56 src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc     -56  -8.5%
      -8.5%     -56 grpc_insecure_channel_create_from_fd                                      -56  -8.5%

  -0.0%     -72 TOTAL                                                                    -240  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                             FILE SIZE
 ++++++++++++++ GROWING                                                               ++++++++++++++

 -------------- SHRINKING                                                             --------------
  -8.5%     -56 src/core/ext/transport/chttp2/client/insecure/channel_create_posix.cc     -56  -8.5%
      -8.5%     -56 grpc_insecure_channel_create_from_fd                                      -56  -8.5%

 -+-+-+-+-+-+-+ MIXED                                                                 +-+-+-+-+-+-+-
  +0.0%     +16 [None]                                                                   -192  -0.0%

  -0.0%     -40 TOTAL                                                                    -248  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
