### PR TITLE
Grpc ruby enable propagation between calls

### LINKED ISSUE #2517: Ensure census context can be passed from incoming requests to outgoing requests in Ruby

### PR DESCRIPTION
**Pull request by tbetbetbe**
Fixes #2517

This should be merged only after #2888 has been merged, it depends on a change in that PR.

### CODE REVIEW

**Comment by tbetbetbe** [comment]
PTAL

**Comment by tbetbetbe** [comment]
Please wait for a bit

**Comment by tbetbetbe** [comment]
@murgatroid99 PTAL

**Comment by murgatroid99** [comment]
LGTM, waiting on tests

**Comment by tbetbetbe** [comment]
@murgatroid99: just looked at the test failures and they are all non-ruby macos X issues unrelated to this change

**Pull request merged**
