### PR TITLE
Disable work_serializer_test on internal tests

### PR DESCRIPTION
**Pull request by yashykt**

### CODE REVIEW

**Comment by jtattermusch** [comment]
Why do we need this test set as "enormous"?
From https://github.com/grpc/grpc/blob/master/test/core/iomgr/work_serializer_test.cc it doesn't look like the test is doing much besides many iterations of the same thing? Such tests usually add little signal but they increase stress on the testing infrastructure and worsen the developer experience (increased test latency, longer PR turnaround, ...)

**Comment by yashykt** [comment]
@jtattermusch We need this for our internal testing. Normally, this test should finish within a minute but it seems to be taking a bit too much time internally.

**Comment by yashykt** [comment]
Alternatively, I can disable this for TAP

**Comment by jtattermusch** [comment]
@yashykt  I'll let you make the call, but there doesn't seem to be a good reason for this test to take long internally or externally.
Btw, "enormous" has a default timeout of 3600s (=crazy high). That doesn't seem reasonable for a test whose duration can be controlled with what seems to be arbitrarily chosen parameters.

bwt, note that foundry currently has trouble with test that take very long time: b/143515898

**Comment by yashykt** [comment]
@jtattermusch I'm disabling this test internally for now while I figure out why it's taking so long

**Pull request merged**
