### PR TITLE
Allow protobufjs objects to be used for client calls

### PR DESCRIPTION
**Pull request by zzo**
Allows clients to use protobufjs objects when making rpc calls.

### CODE REVIEW

**Comment by zzo** [comment]
I don't have to sign it!

**Comment by murgatroid99** [comment]
Why, exactly, don't you need to sign the CLA?

**Comment by zzo** [comment]
https://cla.developers.google.com/clas:

*Googlers do not need to sign a CLA.* If you are having trouble
contributing to a Google open source project, see go/cla#googlers
<https://goto.google.com/cla#googlers> or email signcla-users@
<signcla-users@google.com>

**Comment by murgatroid99** [comment]
Please follow the instructions found at that link.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
