### PR TITLE
[health checking] connected subchannel may be null on READY notification

### PR DESCRIPTION
**Pull request by markdroth**
b/360085586

### CODE REVIEW

**Comment by lee-qiu** [comment]
is there any cases for this fix? thanks for your reply.

**Comment by markdroth** [comment]
There wasn't an easy repro for this bug, but it would have triggered when the subchannel gets connected and then very rapidly disconnects.

**Comment by lee-qiu** [comment]
my program crashed in grpc_core::HealthProducer::HealthChecker::StartHealthStreamLocked() for the connected_subchannel_ is null, so I guess this pr can fix it, but the reason why the connection disconnected rapidly is uncertain. I have around 3800 connections with keepalive interval = 10s to the server, I wonder may this cause the server close connection rapidly? thanks again.

**Comment by markdroth** [comment]
It's hard to say why the connection would be closed so rapidly without seeing a log with various tracers enabled.

**Comment by lee-qiu** [comment]
another question: how do subchannel observe that conn has closed?

when I close transport after sent the setting frame in server, the transport in client can't update the subchannel's state to GRPC_CHANNEL_IDLE until next tcp write is triggered, although tcp read has already miss error before this.
Unfortunately, the next tcp write is to send the health check request.

I wonder how to  set subchannel's state to idle before it call the state ready callback?

**Comment by markdroth** [comment]
The transport doesn't report IDLE; it reports either TRANSIENT_FAILURE or SHUTDOWN.  The subchannel handles that case here:

https://github.com/grpc/grpc/blob/fe8bd94c924f98ae4292ec8dfc969dbd802ec886/src/core/client_channel/subchannel.cc#L409

**Comment by lee-qiu** [comment]
yeah, I know it. The transport  report TRANSIENT_FAILURE or SHUTDOWN to subchannel, and it will reset the connected_subchannel, update the state to GRPC_CHANNEL_IDLE and execute all callbacks in work_serializer_ which may include a callback to build the health check client(I guess it was registered in OnConnectingFinished() function and didn't execute asap for some reason). then grpc lib will crash without this fix. but I can't reproduce this case, and I am not clear when will the transport  report TRANSIENT_FAILURE or SHUTDOWN to subchannel(I am trying read more code about this)

>352733 tcp_posix.cc:831]                     READ 0x7f7999141a80 (peer=xxxx) error=INTERNAL:Socket closed {target_address:"xxxx", grpc_status:14, fd:41}
352733 subchannel.cc:797]                    subchannel 0x7f7999089400 {xxxx}: new connected subchannel at 0x7f7985a06240
352733 health_check_client.cc:506]           creating HealthWatcher ....
352733 tcp_posix.cc:1875]                    write: UNKNOWN:Broken pipe {created_time:"xxxx", errno:32, os_error:"Broken pipe", syscall:"sendmsg", fd:41, grpc_status:14, target_address:"xxxx"}
352733 connectivity_state.cc:158]            ConnectivityStateTracker client_channel[0x7f79991426e0]: CONNECTING -> TRANSIENT_FAILURE (helper, UNAVAILABLE: connections to all backends failing; last error: xxxx: health check call failed; will retry after backoff)
352733 tcp_posix.cc:1827]                    WRITE 0x7f7999141a80 (peer=xxxx)
352733 tcp_posix.cc:1831]                    WRITE DATA: 00 00 04 03 00 00 00 00 01 00 00 00 07 '.............'
352733 tcp_posix.cc:1875]                    write: UNKNOWN:Broken pipe {created_time:"xxxx", errno:32, os_error:"Broken pipe", syscall:"sendmsg", fd:41, grpc_status:14, target_address:"xxxx"}
352733 connectivity_state.cc:158]            ConnectivityStateTracker client_transport[0x7f7985a09400]: READY -> SHUTDOWN (close_transport, OK)
352733 connectivity_state.cc:166]            ConnectivityStateTracker client_transport[0x7f7985a09400]: notifying watcher 0x7f7985a06510: READY -> SHUTDOWN
352733 connectivity_state.cc:78]             watcher 0x7f7985a06510: delivering async notification for SHUTDOWN (OK)
352733 subchannel.cc:360]                    subchannel 0x7f7999089400 {xxxx}: Connected subchannel 0x7f7985a06240 reports SHUTDOWN: OK

**Comment by markdroth** [comment]
I think the relevant log line is this one:

> 352733 tcp_posix.cc:1875] write: UNKNOWN:Broken pipe {created_time:"xxxx", errno:32, os_error:"Broken pipe", syscall:"sendmsg", fd:41, grpc_status:14, target_address:"xxxx"}

It looks like the TCP connection is getting closed out from under the transport.  That causes the transport to report SHUTDOWN to the subchannel.

**Pull request closed without merging**
