### PR TITLE
Enable CFStream by default on  iOS

### PR DESCRIPTION
**Pull request by rmstar**
Enable CFStream on iOS for all wrapped languages.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Can you add a more detailed description?
Questions that come to my mind:
- do we want to enable on Mac in general (for all languages in all setups?)
- your PR doesn't enable cfstream for some build systems (e.g. cmake, bazel) is that intended?

**Comment by rmstar** [comment]
@jtattermusch thanks for your comment. After discussing with Muxi we decided to enable CFStream only on iOS. CFStream will be enabled for all languages and all build systems on iOS. I'm working on updating the PR.

Bazel builds already have support for cfstream. The `cc_library` has a [use_cfstream param](https://github.com/grpc/grpc/blob/master/bazel/grpc_build_system.bzl#L83). `grpc_base_c` sets [use_cfstream = True](https://github.com/grpc/grpc/blob/master/BUILD#L1040).

I'm having some trouble with figuring out how to modify build.yaml to link against CoreFoundation library on iOS. I want to do the following: On iOS, libgrpc needs to link against `-framework CoreFoundation`. I'm assuming if I modify build.yaml correctly, both Makefile and CMakeLists.txt will be updated to link against CoreFoundation after running generate_projects.sh. Is that correct?
Any idea what needs to be changed in build.yaml to make libgrpc link against CoreFoundation? Thanks!

**Comment by jtattermusch** [comment]
The build.yaml  compilation flags are only reflected by Makefile,  setting options for cmake needs to be done separately (somewhere in https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template).

if we only want to use cfstream on iOS, I'm not sure if we have a cmake use case there (we might), so this is something to check.   Btw, C# is using "make" to build iOS binaries: https://github.com/grpc/grpc/blob/master/src/csharp/experimental/build_native_ext_for_ios.sh

**Comment by rmstar** [comment]
Thanks @jtattermusch. We don't have a cmake  usecase internally, but there might be other gRPC iOS users who use cmake. I have updated Makefile.template and CmakeLists.txt.template to link CoreFoundation lib. PTAL.

**Comment by jtattermusch** [comment]
Started an adhoc artifact - packages - distribtest run https://sponge.corp.google.com/invocation?id=9d0aa1ec-a4b7-4abb-baa0-652101833b79&searchFor=

**Comment by rmstar** [comment]
@jtattermusch  CFStream is enabled if:
1. `#if defined(GRPC_CFSTREAM)`, and
2. environment variable `grpc_cfstream` is set to 1.

So, a compile time check is not sufficient.

On Mac OS:
- `GRPC_CFSTREAM` is defined
- environment variable `grpc_cftstream` is not set to 1 by default

On iOS:
- `GRPC_CFSTREAM` is defined
- environnment variable `grpc_cfstream` is set to 1 by default.

Note that applications can override the default behavior by setting the `grpc_cfstream` environment variable. For example [cfstream_test](https://github.com/grpc/grpc/blob/master/test/cpp/end2end/cfstream_test.cc#L472) explicitly enables CFStream on Mac OS.

CFStream enables gRPC to detect network connectivity changes while the app is in the background (POSIX sockets don't support this). All wrapped languages can benefit from this on iOS.

**Comment by jtattermusch** [comment]
> @jtattermusch CFStream is enabled if:
> 
> 1. `#if defined(GRPC_CFSTREAM)`, and
> 2. environment variable `grpc_cfstream` is set to 1.
> 
> So, a compile time check is not sufficient.
> 
> On Mac OS:
> 
> * `GRPC_CFSTREAM` is defined
> * environment variable `grpc_cftstream` is not set to 1 by default
> 
> On iOS:
> 
> * `GRPC_CFSTREAM` is defined
> * environnment variable `grpc_cfstream` is set to 1 by default.
> 
> Note that applications can override the default behavior by setting the `grpc_cfstream` environment variable. For example [cfstream_test](https://github.com/grpc/grpc/blob/master/test/cpp/end2end/cfstream_test.cc#L472) explicitly enables CFStream on Mac OS.
> 
> CFStream enables gRPC to detect network connectivity changes while the app is in the background (POSIX sockets don't support this). All wrapped languages can benefit from this on iOS.

Ok that's fair, thanks for the explanation.

is there a debug log message that will tell me when cfstream is enabled?

**Comment by muxi** [comment]
@rmstar - Now that we are confident with CFStream, can we change `grpc_cfstream` to a negative option `grpc_disable_cfstream`?

**Comment by rmstar** [comment]
@jtattermusch if you turn on tcp tracing and DEBUG level logging you will see log lines containing the string `CFStream`. For example:
```
D0628 12:10:06.496004000 123145361362944 tcp_client_cfstream.cc:85]    CLIENT_CONNECT :0x7fe0a3f6d710 OnAlarm, error:0x4
D0628 12:10:06.496123000 123145361362944 endpoint_cfstream.cc:257]     CFStream endpoint:0x7fe083c06cf0 read (0x7fe085802a10, 0x7fe0858029c0) length:0
D0628 12:10:06.503668000 123145361362944 cfstream_handle.cc:63]        CFStream ReadCallback (0x7fe0a3f6aa30, 0x7fe0a3f6ed50, 2, 0x7fe0a3f6aa30)
```

**Comment by rmstar** [comment]
@muxi I can look into changing `grpc_cfstream` to `grpc_disable_cfstream` in a followon PR.

On iOS, we would disable CFStream using `setenv("grpc_disable_cfstream", "1");`. That looks good.

However, to enable CFStream on Mac OS, we would need to do: `setenv("grpc_disable_cfstream", "0");`. IMO that looks a bit awkward because of the double negation. We don't that issue when the environment variable is named `grpc_cfstream`. WDYT?

**Comment by rmstar** [comment]
I see that your adhoc artifact - packages - distribtest run failed due to tool failure. I'm not familiar with this test - is the failure unrelated to my change?

**Comment by muxi** [comment]
No you don't do it that way :)  `grpc_disable_cfstream=0` will be default and only if the user want to disable CFStream will they use `grpc_disable_cfstream=1`. So on both platforms and all languages CFStream will be enabled by default; only be disabled on demand.

**Comment by jtattermusch** [comment]
New adhoc build: https://sponge.corp.google.com/invocation?id=6ca50109-6201-49f2-b82a-dea9553e961c&searchFor=

**Pull request merged**
