### PR TITLE
Change virtualenv path for interop tests for Python 1.10.1

### LINKED ISSUE #15551: Python 1.10.1 fails in backwards compatibility tests since 5/24 due to missing "py27_native/bin/python"
https://fusion.corp.google.com/runanalysis/test/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_matrix/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_matrix/KOKORO/83b04a28-6bbf-4600-a49a-b0101254ed99/1527162781716/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_matrix%20Build%20%2349/Target%20Transitions?target=github/grpc

Error says bash: py27_native/bin/python: No such file or directory

### PR DESCRIPTION
**Pull request by mehrdada**
Fixes #15551

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mehrdada** [comment]
Test failures: 
- blaze infra failure (ignored)
- C# interop failure

**Pull request merged**
