### PR TITLE
Test that http2 settings frames with small max frame sizes are treated as errors

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
The test will need to be enabled for the auto run interop suite once #4233 is fixed.

Longer term, this will need to be a dashboard, rather than a full pass fail kind of test.

### CODE REVIEW

**Comment by jtattermusch** [comment]
The interop tests have failed. Also, can you please squash the commits (the commit message "blah" is not very useful)?

**Comment by carl-mastrangelo** [comment]
Squashing before submitting is SOP no?

**Comment by jtattermusch** [comment]
I believe it's SOP for grpc-java for grpc repo we don't enforce that.

**Comment by jtattermusch** [comment]
I restarted the tests.

**Comment by jtattermusch** [comment]
LGTM, thanks!

**Pull request merged**
