### PR TITLE
Add PR test filters

### PR DESCRIPTION
**Pull request by matt-kwong**
Backport PR #8295 and #8401

### CODE REVIEW

**Comment by jtattermusch** [comment]
Test failures seem to be unrelated. Merging this to fix other PRs for v1.0.x branch.

**Comment by muxi** [comment]
Why did the version of BoringSSL revert to 6.0?

**Comment by matt-kwong** [comment]
I ran tools/buildgen/generate_projects.sh, since sanity tests were failing. If BoringSSL should be 7.0 on v1.0.x branch, then the change can be reverted. I don't usually work on the v1.0.x, so I'm not sure if it's alright for the sanity test to be failing.

**Comment by muxi** [comment]
So the sanity check passes after BoringSSL is reverted to 6.0? If that is the case we probably need to fix the sanity test then :)

**Pull request merged**
