### PR TITLE
Removing the using std::string in the python plugin code.

### PR DESCRIPTION
**Pull request by nicolasnoble**
It's causing some lesser-capable environments to choke on it.

### CODE REVIEW

**Comment by soltanmm** [comment]
Would you mind if we backtick-quoted the `using std::string` in the commit message? I wrote the code, and I still had to do a triple take when reading it.

**Comment by nicolasnoble** [comment]
No worries at all. I'll amend the commit message when I get back home.

**Comment by nicolasnoble** [comment]
Ping.

**Comment by nathanielmanistaatgoogle** [comment]
I'll merge this, but what's the motivation for it? I don't happen to be familiar with the underlying issue.

**Comment by nicolasnoble** [comment]
I can fill you in with more details in person, but long story short, there exists other implementation of protobuf out there, and they have conflicting definitions for std::string. This change is similar in scope to #1032.

**Pull request merged**
