### PR TITLE
Fix jwt verifier

### PR DESCRIPTION
**Pull request by jboeuf**
- Initializes grpc correctly in the JWT utils.
- Make the email mapping work with the new service accounts produced by Google IAM.

### CODE REVIEW

**Comment by jboeuf** [comment]
@yang-g can we merge these changes now? thanks!

**Comment by yang-g** [comment]
jenkins Test this please

**Comment by jboeuf** [comment]
@yang-g I fixed the failing tests. The failing gRPC_interop_pull_request is unrelated.

**Comment by yang-g** [comment]
Test failures:
#9099 
#8989

**Comment by yang-g** [comment]
Could you squash the commits?

**Pull request merged**
