### PR TITLE
Move grpc_census_call_*_context calls into public header

### PR DESCRIPTION
**Pull request by a-veitch**
Issue #2710 fix.

### CODE REVIEW

**Comment by murgatroid99** [comment]
The sanity tests failed. It looks like some project files were not correctly regenerated.

**Comment by a-veitch** [comment]
I see the error in the log, but can't figure out why it is so. I regenerated everything with tools/buildgen/generate_projects.sh before submitting, is there anything else I need to do?

I also looked for mentions of grpc_context.h remaining in any file in my repository, and couldn't see anything. Suggestions?

**Comment by murgatroid99** [comment]
I don't know. There's no clear reason that I can see.

**Comment by a-veitch** [comment]
I'm probably a week behind the mainline with this; I'll try and do merge with current upstream, and see if that helps.

**Comment by a-veitch** [comment]
BTW, not sure I'll get to this today, and I'm out tomorrow, so it may be weekend or Monday.

**Comment by a-veitch** [comment]
Think I found the cause, it was do do with another merge on a common file that still contained the reference to the removed header.

**Comment by murgatroid99** [comment]
OK, the test failures don't look related to this change.

**Pull request merged**
