### PR TITLE
Revert "C++-ify the ChannelzRegistry, Adds Generic Object Support"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#15341

The PR breaks ASAN C++ (100% runs failing on master).
This is actually despite ASAN being green on the PR - we do have a 1 hour run time limit for PR tests in place so this time we probably got unlucky and the test didn't run on presubmit.

The broken test is
```
cpp_linux_asan_native keyboard_arrow_right bins/asan/channelz_registry_test --gtest_filter=ChannelzRegistryTest.CustomObjectTest

=================================================================
[1m[31m==24278==ERROR: LeakSanitizer: detected memory leaks
[1m[0m
[1m[34mDirect leak of 4 byte(s) in 1 object(s) allocated from:
[1m[0m    #0 0x4caa68 in __interceptor_malloc /llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x512222 in gpr_malloc /var/local/git/grpc/src/core/lib/gpr/alloc.cc:57:7
    #2 0x4ffdb6 in grpc_core::testing::(anonymous namespace)::Foo* grpc_core::New<grpc_core::testing::(anonymous namespace)::Foo>() /var/local/git/grpc/./src/core/lib/gprpp/memory.h:51:19
    #3 0x4ffb2e in grpc_core::testing::ChannelzRegistryTest_CustomObjectTest_Test::TestBody() /var/local/git/grpc/test/core/channel/channelz_registry_test.cc:92:14
    #4 0xed1eeb in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2402:10
    #5 0xe9d4c0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #6 0xe67ae9 in testing::Test::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2474:5
    #7 0xe6994c in testing::TestInfo::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2656:5
    #8 0xe6aae1 in testing::TestCase::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2774:5
    #9 0xe7a36c in testing::internal::UnitTestImpl::RunAllTests() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4649:11
    #10 0xedb726 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2402:10
    #11 0xea2b50 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:2438:14
    #12 0xe79961 in testing::UnitTest::Run() /var/local/git/grpc/third_party/googletest/googletest/src/gtest.cc:4257:10
    #13 0x502b53 in RUN_ALL_TESTS() /var/local/git/grpc/third_party/googletest/googletest/include/gtest/gtest.h:2233:10
    #14 0x50080d in main /var/local/git/grpc/test/core/channel/channelz_registry_test.cc:117:13
    #15 0x7f7adff17b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
Objects leaked above:
0x60200000e710 (4 bytes)
SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
Command exited with non-zero status 1
```

https://source.cloud.google.com/results/invocations/6c3be33a-4a0a-4239-b248-ea6327fd0cab/targets
https://source.cloud.google.com/results/invocations/89a69b32-6e94-435b-a1e8-a40302e1771d/targets

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++
  [NEW]    +444 src/core/lib/channel/channel_trace_registry.cc                +444  [NEW]
      [NEW]     +99 grpc_channel_trace_registry_register_channel_trace             +99  [NEW]
      [NEW]     +98 [Unmapped]                                                     +98  [NEW]
      [NEW]     +67 grpc_channel_trace_registry_unregister_channel_trace           +67  [NEW]
      [NEW]     +60 grpc_channel_trace_registry_get_channel_trace                  +60  [NEW]
      [NEW]     +47 grpc_channel_trace_registry_init                               +47  [NEW]
      [NEW]     +41 grpc_channel_trace_registry_shutdown                           +41  [NEW]
      [NEW]     +20 compare_intptr                                                 +20  [NEW]
      [NEW]      +4 copy_intptr                                                     +4  [NEW]
      [NEW]      +4 copy_channel_trace                                              +4  [NEW]
      [NEW]      +2 destroy_intptr                                                  +2  [NEW]
      [NEW]      +2 destroy_channel_trace                                           +2  [NEW]

 -------------- SHRINKING                                                  --------------
  -0.0%    -235 [None]                                                     -3.50Ki  -0.0%
      -0.1%    -331 [Unmapped]                                                 -3.50Ki  -0.0%
      [DEL]     -40 grpc_core::(anonymous namespace)::avl_vtable                   -40  [DEL]
      [DEL]      -8 grpc_core::(anonymous namespace)::g_channelz_registry            0  [ = ]
  [DEL]    -329 src/core/lib/channel/channelz_registry.cc                     -329  [DEL]
      [DEL]    -104 [Unmapped]                                                    -104  [DEL]
      [DEL]     -57 grpc_core::ChannelzRegistry::InternalUnregister                -57  [DEL]
      [DEL]     -39 grpc_core::ChannelzRegistry::ChannelzRegistry                  -39  [DEL]
      [DEL]     -36 grpc_core::ChannelzRegistry::Init                              -36  [DEL]
      [DEL]     -28 grpc_core::ChannelzRegistry::~ChannelzRegistry                 -28  [DEL]
      [DEL]     -25 grpc_core::ChannelzRegistry::Shutdown                          -25  [DEL]
      [DEL]     -20 grpc_core::(anonymous namespace)::compare_intptr               -20  [DEL]
      [DEL]      -8 grpc_core::ChannelzRegistry::Default                            -8  [DEL]
      [DEL]      -4 grpc_core::(anonymous namespace)::copy_intptr                   -4  [DEL]
      [DEL]      -4 grpc_core::(anonymous namespace)::copy_channelz_obj             -4  [DEL]
      [DEL]      -2 grpc_core::(anonymous namespace)::destroy_intptr                -2  [DEL]
      [DEL]      -2 grpc_core::(anonymous namespace)::destroy_channelz_obj          -2  [DEL]
  -2.5%     -64 src/core/lib/channel/channel_trace.cc                          -64  -2.5%
     -23.4%     -54 grpc_core::ChannelTrace::ChannelTrace                          -54 -23.4%
     -14.0%     -16 grpc_core::ChannelTrace::~ChannelTrace                         -16 -14.0%

  -0.0%    -184 TOTAL                                                      -3.45Ki  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Fixed in #15447

**Pull request closed without merging**
