### PR TITLE
Add gRPC Java 1.37.0 to interop matrix

### PR DESCRIPTION
**Pull request by sergiitk**
@karthikravis

### CODE REVIEW

**Comment by sergiitk** [comment]
Local tests passed:

```
❯ sudo docker_image=gcr.io/grpc-testing/grpc_interop_java:v$MAJOR.$MINOR.$PATCH tools/interop_matrix/testcases/java__master
Testing gcr.io/grpc-testing/grpc_interop_java:v1.37.0
Running test large_unary
Test completed.
Running test empty_unary
Test completed.
Running test ping_pong
Test completed.
Running test empty_stream
Test completed.
Running test client_streaming
Test completed.
Running test server_streaming
Test completed.
Running test cancel_after_begin
Test completed.
Running test cancel_after_first_response
Test completed.
Running test timeout_on_sleeping_server
Test completed.
Running test large_unary
Test completed.
Running test empty_unary
Test completed.
Running test ping_pong
Test completed.
Running test empty_stream
Test completed.
Running test client_streaming
Test completed.
Running test server_streaming
Test completed.
Running test cancel_after_begin
Test completed.
Running test cancel_after_first_response
Test completed.
Running test timeout_on_sleeping_server
Test completed.
```

**Review by karthikravis — APPROVED** [review]

**Comment by sergiitk** [comment]
Note: pushed the same commit because EasyCLA wasn't reporting the status.

**Comment by jtattermusch** [comment]
Note that you should always trigger an adhoc run of interop matrix tests when updating the interop matrix:
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_matrix

**Comment by sergiitk** [comment]
@jtattermusch Thank you. We should add it to https://github.com/grpc/grpc/blob/master/tools/interop_matrix/README.md#step-by-step-instructions-for-adding-a-gcr-image-for-a-new-release-for-compatibility-test

**Pull request merged**
