### PR TITLE
Make copyright check slightly more flexible

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Checks that the `Authors` can capitalize, and allows for a trailing period.   More closely matches https://www.apache.org/licenses/LICENSE-2.0#apply

cc: @nicolasnoble @jtattermusch

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by mehrdada** [comment]
@carl-mastrangelo Can you also allow for the presence of "The" preceding "gRPC Authors" please?

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by carl-mastrangelo** [comment]
@mehrdada done, PTAL

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Pull request merged**
