### PR TITLE
Revert breaking API in #12708

### PR DESCRIPTION
**Pull request by muxi**
Parallel with #14229. This is partial revert of #12708 which only reverts the breaking API change.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                    FILE SIZE
 ++++++++++++++ GROWING                                      ++++++++++++++

 -------------- SHRINKING                                    --------------
  -0.1%    -871 [None]                                       -7.22Ki  -0.1%
      -0.1%    -684 [Unmapped]                                   -7.10Ki  -0.1%
      -1.9%     -64 static_metadata_hash                               0  [ = ]
      -1.9%     -64 grpc_static_slice_table                          -64  -1.9%
      -1.9%     -32 grpc_static_metadata_refcounts                   -32  -1.9%
      -2.4%     -27 g_bytes                                          -27  -2.4%
      -1.9%      -8 static_metadata_hash_values                        0  [ = ]
      -2.0%      -2 elems_r                                           -2  -2.0%
      -1.8%      -2 elem_idxs                                         -2  -1.8%
  [DEL]    -553 src/core/lib/compression/compression_ruby.cc    -553  [DEL]
      [DEL]    -330 grpc_compression_algorithm_parse_ruby           -330  [DEL]
      [DEL]    -217 grpc_compression_algorithm_name_ruby            -217  [DEL]
      [DEL]      -6 [Unmapped]                                        -6  [DEL]

  -0.1% -1.39Ki TOTAL                                        -7.76Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -24  -0.0%

  [ = ]       0 TOTAL      -24  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                    FILE SIZE
 ++++++++++++++ GROWING                                      ++++++++++++++

 -------------- SHRINKING                                    --------------
  -0.1%    -871 [None]                                       -7.22Ki  -0.1%
      -0.1%    -684 [Unmapped]                                   -7.10Ki  -0.1%
      -1.9%     -64 static_metadata_hash                               0  [ = ]
      -1.9%     -64 grpc_static_slice_table                          -64  -1.9%
      -1.9%     -32 grpc_static_metadata_refcounts                   -32  -1.9%
      -2.4%     -27 g_bytes                                          -27  -2.4%
      -1.9%      -8 static_metadata_hash_values                        0  [ = ]
      -2.0%      -2 elems_r                                           -2  -2.0%
      -1.8%      -2 elem_idxs                                         -2  -1.8%
  [DEL]    -553 src/core/lib/compression/compression_ruby.cc    -553  [DEL]
      [DEL]    -330 grpc_compression_algorithm_parse_ruby           -330  [DEL]
      [DEL]    -217 grpc_compression_algorithm_name_ruby            -217  [DEL]
      [DEL]      -6 [Unmapped]                                        -6  [DEL]

  -0.1% -1.39Ki TOTAL                                        -7.76Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -24  -0.0%

  [ = ]       0 TOTAL      -24  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__1.counters.old: 1
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__64.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Failure is #14128

**Pull request merged**
