### PR TITLE
Fixing init-test timeout.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by sreecha** [comment]
oh..I too have a PR for this https://github.com/grpc/grpc/pull/12920
but I guess reducing the number of iterations from 100000 to 1000 is better :)

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by nicolasnoble** [comment]
Not all the things are happy. I'll fix it.

```
src/core/lib/iomgr/iocp_windows.cc(53): error C2371: 'timeout': redefinition; different basic types
src/core/lib/iomgr/iocp_windows.cc(47): note: see declaration of 'timeout'
src/core/lib/iomgr/iocp_windows.cc(54): error C2446: '>': no conversion from 'std::numeric_limits<unsigned long>::_Ty' to 'gpr_timespec'
src/core/lib/iomgr/iocp_windows.cc(54): note: No constructor could take the source type, or constructor overload resolution was ambiguous
src/core/lib/iomgr/iocp_windows.cc(55): warning C4244: 'return': conversion from 'grpc_millis' to 'DWORD', possible loss of data
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.opt.old: 1


[microbenchmarks] No significant performance differences
```

**Pull request merged**
