### PR TITLE
C++ benchmark: build C++ with assembly optimizations

### PR DESCRIPTION
**Pull request by jtattermusch**
Based on #16957.

Right now we are building C++ qps_worker in e2e benchmarks with make, which disables boringssl assembly optimizations. We should see much better numbers for secure channel when building with cmake.

https://github.com/grpc/grpc/blob/master/doc/ssl-performance.md

### CODE REVIEW

**Comment by jtattermusch** [comment]
@ncteisen   no this will not influence the tests run by run_tests.py - the "benchmarks" that are run by run_tests.py are basically used as if they were unit tests (which IMHO is not a great idea) and the performance numbers generated by those test don't matter (and I don't think we are tracking them at all).

Ad microbenchmarks:
they are still built by make (and thus assembly optimizations are likely disabled). Not sure if that has any impact on your measurements as I don't know much about C++ microbenchmarks (but that's out of scope for this PR anyway).

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,997,294      Total (=)      1,997,294

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,021,764      Total (>)     11,021,762

 No significant differences in binary sizes


```

**Comment by jtattermusch** [comment]
Test failures:
https://github.com/grpc/grpc/issues/15599

**Pull request merged**
