### PR TITLE
Remove dependency on pubref/rules_proto.

### LINKED ISSUE #18256: bazel build :all fails due to https://github.com/pubref/rules_protobuf
```
❯ bazel build :all                                                                             
ERROR: /usr/local/google/home/xxx/envs/grpc/grpc/worktree-h2/WORKSPACE:62:1: Traceback (most recent call last):
        File "/usr/local/google/home/xxx/envs/grpc/grpc/worktree-h2/WORKSPACE", line 62
                py_proto_repositories()
        File "/usr/local/google/home/xxx/.cache/bazel/_bazel_xxx/6ad28553f473ab366b04b5ff87b51d96/external/org_pubref_rules_protobuf/python/rules.bzl", line 13, in py_proto_repositories
                cpp_proto_repositories(**kwargs)
        File "/usr/local/google/home/xxx/.cache/bazel/_bazel_xxxl/6ad28553f473ab366b04b5ff87b51d96/external/org_pubref_rules_protobuf/cpp/rules.bzl", line 29, in cpp_proto_repositories
                fail(("Unknown loading rule %s for %s...)))
Unknown loading rule http_archive for {"url": "https://github.com/google/googletest/archive/7c6353d29a147cad1c904bf2957fd4ca2befe135.zip", "sha256": "f87029f647276734ef076785f76652347993b6d13ac1cbb2d2e976e16d2f8137", "strip_prefix": "googletest-7c6353d29a147cad1c904bf2957fd4ca2befe135", "name": "com_google_googletest"}
ERROR: Error evaluating WORKSPACE file
ERROR: Skipping ':all': while parsing ':all': error loading package 'external': Package 'external' contains errors
WARNING: Target pattern parsing failed.
ERROR: while parsing ':all': error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.042s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Update from @jtattermusch: it seems that this is happening for bazel 0.23+ (build works fine for bazel 0.20, 0.21, 0.22 based on my testing)

### LINKED ISSUE #18331: External dependence for py_proto_dependencies will never be upstreamed
### What version of gRPC and what language are you using?

master, C++ 
 
### What operating system (Linux, Windows,...) and version?
 
N/A
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
bazel
 
### What did you do?

Tried to upgrade googletest build dependence

### What did you expect to see?
 
Should have been able to upgrade without problem

### What did you see instead?
 
py_proto_dependencies is a problem .  It in turn invokes cpp_proto_dependencies, which then includes a build dependence on a version of googletest that is neither the one that we currently use nor the one that I want to start using.

https://github.com/grpc/grpc/blob/8bed44b2c47577fe255eb5b9fe754a2756cefed7/WORKSPACE#L53-L58 refers to code that should get upstreamed in https://github.com/pubref/rules_protobuf/pull/196 , but that PR has been closed without merging, the repo deprecated, and its contents moved to another repo altogether in another org.

As a general rule, we should reduce these kinds of dependences on outside code that affect our build process. Can this dependence be removed?

### PR DESCRIPTION
**Pull request by gnossen**
This commit resolves #18331.
This commit resolves #18256.
This commit resolves... another TODO that apparently didn't have an
associated github issue.

We swap out pubref's implementation of py_proto_library with our own,
which more closely mirrors the interface of the internal
py_proto_library, taking the descriptor file output of a proto_library
rule as input.

One minor change in behavior was introduced for simplicity. When a
py_proto_library depends on a proto_library with a source proto file in
a subdirectory of the bazel package, the import module of the resultant
python library will reflect the package, *not* the full directory of the
proto file, including both the bazel package and the subdirectories, as
pubref did previously. This behavior also more closely mirrors google
internal behavior.

This commit also introduces a slightly more stringent bazel format
script. Buildifier on its own will not take care of long lines, but by
running yapf first, we end up with a more legible file. At the moment,
there is no sanity check associated with this formatter.

### CODE REVIEW

**Comment by jtattermusch** [comment]
can we double check that the  "Bazel Basic Tests for Python" are actually running? I don't see much of an output from the bazel build in https://source.cloud.google.com/results/invocations/95ea3d05-5081-4147-97ab-4e4c81feb858/log

**Comment by jtattermusch** [comment]
Does this also fix the bazel 0.24.1 build as captured in https://github.com/grpc/grpc/issues/18642? (It's fine if not, but it would be good to check and address as a followup).

**Comment by gnossen** [comment]
Looking into "Bazel Basic Tests for Python". I see what you mean.

Also, it looks like this does indeed fix #18642, at least for `bazel build //test/...`.

**Comment by nicolasnoble** [comment]
This looks good to me overall, but there's two things that we might want to check:

- Does an import still make the internal build happy?
- Can our dependents still build properly with us as a dependency? (like Tensorflow)

**Comment by gnossen** [comment]
@nicolasnoble Testing with an import was a good call. I now have an internal patch that will need to be added in with a cherrypick.

**Comment by jtattermusch** [comment]
@gnossen  can we merge today or are there still other things to check?

**Comment by gnossen** [comment]
@jtattermusch I'll be going for a cherrypick today.

**Comment by gnossen** [comment]
Known failures:
 - https://github.com/grpc/grpc/issues/18637

**Pull request merged**
