### PR TITLE
Rename tcp->finished_edge

### PR DESCRIPTION
**Pull request by sreecha**
Renamed the confusing `finished_edge` member from tcp endpoint struct and added more documentation.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                       FILE SIZE
 ++++++++++++++ GROWING                         ++++++++++++++

 -------------- SHRINKING                       --------------
  -0.0%     -48 [None]                          -4.48Ki  -0.1%
  -2.1%    -144 src/core/lib/iomgr/tcp_posix.cc    -144  -2.1%
     -12.5%     -81 tcp_handle_read                     -81 -12.5%
      -6.3%     -59 tcp_do_read                         -59  -6.3%
      -2.1%      -4 [Unmapped]                           -4  -2.1%

  -0.0%    -192 TOTAL                           -4.62Ki  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by sreecha** [comment]
known failure: https://github.com/grpc/grpc/issues/15610

**Comment by yashykt** [comment]
LGTM.. but it might be a battle worth fighting in the future

**Pull request merged**
