### PR TITLE
Report build results too in the JUnit XML.

### PR DESCRIPTION
**Pull request by jcanizales**
The diff algorithm here isn't very smart :-/

Essentially create the XML root at the top, and split the `try/finally` block in two because now we might want to write the XML file when the antagonists haven't started yet.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
So this isn't exactly "legal" in regards to what JUnit actually does. If you use JUnit in Java and the build fails, there will be no JUnit output being generated. And it doesn't contain any build information. I think I'd rather keep the consistency with what is expected of a typical JUnit report, to avoid confusing Jenkins' parsers.

@ejona86 any feedback ?

**Comment by ejona86** [comment]
JUnit actually _can't_ produce output, since JUnit determines what the tests are at runtime by looking at the compiled code.

I wouldn't be strongly opposed to this at a high level, but consistency does make some sense. However, does this produce a different list of tests in the "JUnit output," based on if the build failed? If so, then I would be opposed to that, as it seems it would just be asking for trouble.

**Comment by jcanizales** [comment]
> However, does this produce a different list of tests in the "JUnit output," based on if the build failed?

Currently, if building any of the tests-to-be-run fails, no output file is produced. When building succeeds, the output file has a `testcase` XML element for every test job run.

With this change, the output file is always produced, and always has a `testcase` XML element for each of the build jobs. If those succeed, the tests jobs are run, and the output will also have a `testcase` element for each of those.

**Comment by jtattermusch** [comment]
This PR is way out of date. Closing.

**Pull request closed without merging**
