### PR TITLE
Add v1.38.0 release of grpc-ruby to interop matrix

### PR DESCRIPTION
**Pull request by tnir**
#26316 for Go, #26291 for Java etc.

@veblush

### CODE REVIEW

**Comment by veblush** [comment]
@yashykt Could you take a look at this?

**Comment by markdroth** [comment]
@apolcyn might also know what's going on with this.

**Comment by apolcyn** [comment]
It looks like we just haven't yet added 1.38 to the interop matrix for any of the wrapped languages, not just ruby. I don't know of any issues with ruby on 1.38 so I assume this will be added along with the rest of the wrapped languages.

cc @yashykt

**Comment by yashykt** [comment]
This is being done as part of https://github.com/grpc/grpc/pull/26411

**Pull request closed without merging**
