### PR TITLE
Fix Ruby sample codes to make them work

### PR DESCRIPTION
**Pull request by eagletmt**

### CODE REVIEW

**Comment by eagletmt** [comment]
I signed it!

**Comment by murgatroid99** [comment]
Jenkins: test this please

**Comment by murgatroid99** [comment]
LGTM. The ruby tests are passing

**Comment by murgatroid99** [comment]
Jenkins: test this please

**Comment by jtattermusch** [comment]
Let's either get this done or close this.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by apolcyn** [comment]
jenkins: this is ok to test

**Comment by apolcyn** [comment]
jenkins: test this please

**Comment by apolcyn** [comment]
tests are still stale.

jenkins: test this please

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by apolcyn** [comment]
jenkins: this is ok to test

**Comment by apolcyn** [comment]
Test runs still stale

Jenkins: test this please

**Comment by jtattermusch** [comment]
@apolcyn  is this PR still useful?  We'd need to rebase to get a fresh test run.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @eagletmt isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by apolcyn** [comment]
@jtattermusch this PR does make corrections to these examples. @eagletmt I know it's been a long time on this PR; if you'd like to continue, can you please rebase?

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @eagletmt isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request closed without merging**
