### PR TITLE
Update Stats Generator

### PR DESCRIPTION
**Pull request by ncteisen**
Ran into some problems generating some ad hoc stats for perf numbers.

The script went stale after a few sweeping changes (removing extern c, support to gpr, and port_platforms).

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
This is a python generator func, no test coverage

**Pull request merged**
