### PR TITLE
Abstract epoll_create and epoll_create1

### PR DESCRIPTION
**Pull request by mehrdada**
Add a function that calls epoll_create1(FD_CLOEXEC) when supported
by glibc and falls back to epoll_create followed by fcntl to set
the CLOEXEC flag.  This is necessary to enable epoll-based polling
engines on Python manylinux1 binaries.

This commit also effectively enables other epoll-based engines
like epollex to be compiled in the manylinux1 builds.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++

 -------------- SHRINKING                               --------------
  -0.0%      -8 [None]                                     -232  -0.0%
  -0.3%     -32 src/core/lib/iomgr/ev_epoll1_linux.cc       -32  -0.3%
      -4.6%     -32 grpc_init_epoll1_linux                      -32  -4.6%
  -0.3%     -24 src/core/lib/iomgr/ev_epollsig_linux.cc     -24  -0.3%
      -2.1%      -8 [Unmapped]                                   -8  -2.1%
      -1.8%      -8 grpc_init_epollsig_linux                     -8  -1.8%
      -2.8%      -8 polling_island_create                        -8  -2.8%

  -0.0%     -64 TOTAL                                      -288  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++
  +0.0%    +142 [None]                                  +2.61Ki  +0.0%
  [NEW]     +10 src/core/lib/iomgr/ev_epoll_linux.cc        +10  [NEW]
      [NEW]     +10 epoll_create_and_cloexec                    +10  [NEW]

 -------------- SHRINKING                               --------------
  -0.3%     -32 src/core/lib/iomgr/ev_epoll1_linux.cc       -32  -0.3%
      -4.6%     -32 grpc_init_epoll1_linux                      -32  -4.6%
  -0.3%     -24 src/core/lib/iomgr/ev_epollsig_linux.cc     -24  -0.3%
      -2.1%      -8 [Unmapped]                                   -8  -2.1%
      -1.8%      -8 grpc_init_epollsig_linux                     -8  -1.8%
      -2.8%      -8 polling_island_create                        -8  -2.8%

  +0.0%     +96 TOTAL                                   +2.56Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                             FILE SIZE
 ++++++++++++++ GROWING                               ++++++++++++++
  +0.0%    +182 [None]                                +2.62Ki  +0.0%
  [NEW]     +10 src/core/lib/iomgr/ev_epoll_linux.cc      +10  [NEW]
      [NEW]     +10 epoll_create_and_cloexec                  +10  [NEW]

 -------------- SHRINKING                             --------------
  -0.3%     -32 src/core/lib/iomgr/ev_epoll1_linux.cc     -32  -0.3%
      -4.6%     -32 grpc_init_epoll1_linux                    -32  -4.6%

  +0.0%    +160 TOTAL                                 +2.60Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by mehrdada** [comment]
Closing: Current implementation of epollsig relies on epoll_pwait and epollex relies on eventfd, none of which are available in manylinux1. Expanding epoll_create support for manylinux1 outside epoll1 therefore would not make sense.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                              cpu_time    real_time
-------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/262144                                          +8%         +8%
BM_PumpStreamServerToClient<InProcess>/32768                                           +4%         +4%
BM_StreamingPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/2                     +9%         +9%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/1                  +4%         +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                    +6%         +6%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32768                 +6%         +6%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/0  +6%         +6%
```

**Pull request closed without merging**
