### PR TITLE
CDS LB policy

### PR DESCRIPTION
**Pull request by markdroth**
Built on #20526.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/20544)

### CODE REVIEW

**Comment by markdroth** [comment]
This is now ready for review.

Only the second commit is new; the first commit is the changes from #20526.

**Comment by markdroth** [comment]
This PR now contains only its own changes.

**Comment by AspirinSJL** [comment]
Sorry for the delay! I will finish reviewing (and cleaning https://github.com/grpc/grpc/pull/20638) today.

**Comment by markdroth** [comment]
Known issues: #20711 #20436 #20308

**Pull request merged**
