### PR TITLE
Fix status_code_and_message interop test for C++.  Change run_interop_tests.py to run this test for C++ and Go.

### PR DESCRIPTION
**Pull request by markdroth**
This depends on grpc/grpc-go#747 and helps address grpc/grpc-go#742.

### CODE REVIEW

**Comment by markdroth** [comment]
It looks like this test was actually implemented in C++ (see #2808), but it was only exercising the UnaryCall part, not the FullDuplexCall part (see https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#status_code_and_message for details).  I have fixed the C++ test and changed run_interop_tests.py to run it, which means that this now helps address #1416.

@a11r to make sure I've done this right.

**Comment by a11r** [comment]
LGTM

**Comment by markdroth** [comment]
Qi, now that the grpc-go change has been merged, this PR is also ready to merge.  I just need an approval from you.  Thanks!

**Comment by iamqizhao** [comment]
LGTM to the py script.

**Comment by markdroth** [comment]
@stanley-cheung, it looks like the PHP client is failing the status_code_and_message interop test when run against a Go server.  Go and C++ work fine with each other (in both directions), and PHP works fine against a C++ server, so I'm not sure what the problem is.  Any idea what's wrong here?  Thanks!

**Pull request merged**
