### PR TITLE
Fix interop HTML report

### PR DESCRIPTION
**Pull request by adelez**

### CODE REVIEW

**Comment by adelez** [comment]
Please test this.

**Comment by adelez** [comment]
@makdharma

**Comment by adelez** [comment]
Test this please.

**Comment by jtattermusch** [comment]
Overall I think the change looks good, but I see lots of tests of X:http2_server failing (X is a client language).

**Comment by adelez** [comment]
What's why I put WIP in the title. It seems all clients will automatically run all tests to all servers so many unsupported cases were run. I'll keep investigating. Let me know if you have suggestions. Thanks!

**Comment by jtattermusch** [comment]
@adelez   one way not to run the HTTP2 test cases that are not supported is to add 
_HTTP2_BADSERVER_TEST_CASES   to   unimplemented_test_cases() or   unimplemented_test_cases_server() for each of the languages.

**Comment by jtattermusch** [comment]
@adelez  scratch that, I think you can just add some conditions to the loop under `if args.http2_badserver_interop:`

**Comment by adelez** [comment]
Test this please.

**Comment by adelez** [comment]
Fixed the previous issue. PTAL.

**Comment by adelez** [comment]
Tests are failing with known issues:
Tsan C - #9680
gRPC_performance_pull_requests - #9681

**Comment by adelez** [comment]
PTAL.

**Comment by jtattermusch** [comment]
ah, sorry, I missed this. I'll review tomorrow.

**Pull request merged**
