### PR TITLE
New version of grpclb end2end test

### PR DESCRIPTION
**Pull request by dgquintas**
Work in progress: The code will be kept "mergeable" at all times but expect new tests being added atomically.

Includes fix for a memory leak in grpclb: empty serverlists weren't being destroyed.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/10360)

### CODE REVIEW

**Comment by markdroth** [comment]
Thanks for doing this!

Are we going to delete test/cpp/grpclb/grpclb_test.cc, now that we've got a new test?  Or is there still code in the original that isn't covered by the new one?

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 124 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZsSUkBCWik1jAVUKY:-KgZrfcprPZc8dVIumAJ:b-78tjjl) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L124)):*
> ```cpp
>   }
> 
>   int request_count() override {
> ```

Suggest moving these two methods into the `CountedService` class, since they're used by both subclasses.

We could also add utility functions for incrementing the counts, which would simplify the code in the subclasses.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 151 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZqqPzGVq6GyaPGfUj:-KgZqqPzGVq6GyaPGfUk:blnzkgt) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L151)):*
> ```cpp
>       : request_count_(0), response_count_(0), shutdown_(false) {}
> 
>   using Stream = ServerReaderWriter<LoadBalanceResponse, LoadBalanceRequest>;
> ```

Please put all typedefs ahead of methods (including the ctor), as per the style guide.

https://google.github.io/styleguide/cppguide.html#Declaration_Order

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 161 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZq_PFu0OnV3344Acr:-KgZq_PFu0OnV3344Acs:b-mvxdoz) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L161)):*
> ```cpp
>     gpr_log(GPR_INFO, "LB: recv msg '%s'", request.DebugString().c_str());
> 
>     decltype(responses_and_delays_) responses_and_delays;
> ```

I generally dislike using `decltype()`.  Suggest using a typedef instead.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 185 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZqlCNwV1LI7tegJJ0:-KgZqlCNwV1LI7tegJJ1:bvde4ia) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L185)):*
> ```cpp
> 
>   void add_response(const LoadBalanceResponse& response, int send_after_ms) {
>     {
> ```

No need for the inner scope here.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 192 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZqmr1cZi9vu1F6GAE:-KgZqmr1cZi9vu1F6GAF:bvde4ia) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L192)):*
> ```cpp
> 
>   void Shutdown() {
>     {
> ```

No need for the inner scope here.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 221 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZsUT2tTU-e4RjkjH9:-KgZsUT2tTU-e4RjkjHA:b-yebe5g) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L221)):*
> ```cpp
>       std::unique_lock<std::mutex> lock(mu_);
>       ++response_count_;
>       if (shutdown_) return;
> ```

This probably isn't needed, since we're at the end of the function anyway -- i.e., we'll return regardless of the value of `shutdown_`.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 255 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZtjwvcu9oVWEXxyxs:-KgZtjwwFTaXlcDYuesg:b-awtw85) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L255)):*
> ```cpp
> 
>     ChannelArguments args;
>     args.SetLoadBalancingPolicyName("grpclb");
> ```

I think this shouldn't be needed, because the resolver will be returning balancer addresses, so we'll select grpclb anyway.  And as per the changes described in #10258, grpclb shouldn't be a valid choice here anyway.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 305 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZvGZOygbtqYZIZ5fM:-KgZvGZOygbtqYZIZ5fN:b-mvyeuv) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L305)):*
>       ClientContext context;
>       context.set_deadline(deadline);

Could just declare this once, outside the loop, since we're going to use the same value for every RPC.  (Or is it not okay to reuse a `ClientContext` object for multiple RPCs?)

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 358 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZveOBcjFTB3MYIbAI:-KgZveOBcjFTB3MYIbAJ:b-cms8jq) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L358)):*
>   const size_t num_backends_;
>   const size_t num_balancers_;

I don't think these are needed.  Instead, we can use `backends_.size()` and `balancers_.size()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/10360#-:-KgZwkIH4QpAqJCUAe6U:bngnw7p)*

**Comment by markdroth** [comment]
This looks pretty good.  All of my remaining comments are minor.

Would still like an answer to my earlier question about whether or not this is intended to replace test/cpp/grpclb/grpclb_test.cc.

Thanks!

---

Reviewed 9 of 11 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 151 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZqqPzGVq6GyaPGfUj:-KiWrwAY5aYlp0z9fViW:b34yy9a) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L151)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please put all typedefs ahead of methods (including the ctor), as per the style guide.

https://google.github.io/styleguide/cppguide.html#Declaration_Order
</blockquote></details>

The typedefs should still be in the class, just listed ahead of the ctor.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 305 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZvGZOygbtqYZIZ5fM:-KiWtalpHw_pBDXAyYLP:b3f9jih) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L305)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

>       ClientContext context;
>       context.set_deadline(deadline);

Could just declare this once, outside the loop, since we're going to use the same value for every RPC.  (Or is it not okay to reuse a `ClientContext` object for multiple RPCs?)
</blockquote></details>

Doesn't look like this was addressed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 358 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZveOBcjFTB3MYIbAI:-KiWtfkeoPVcI2bvBxgz:b3f9jih) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L358)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

>   const size_t num_backends_;
>   const size_t num_balancers_;

I don't think these are needed.  Instead, we can use `backends_.size()` and `balancers_.size()`.
</blockquote></details>

Doesn't look like this was addressed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 272 at r3](https://reviewable.io:443/reviews/grpc/grpc/10360#-KiWsz4C9SHFqr6ClIVH:-KiWsz4C9SHFqr6ClIVI:b-511h94) ([raw file](https://github.com/grpc/grpc/blob/cc503765d9ce0b3720cee6d83ae18805857bc196/test/cpp/end2end/grpclb_end2end_test.cc#L272)):*
> ```cpp
>     grpc_exec_ctx exec_ctx = GRPC_EXEC_CTX_INIT;
>     grpc_lb_addresses* addresses =
>         grpc_lb_addresses_create(address_data.size(), NULL);
> ```

All of the `NULL`s in this file should probably be `nullptr`s instead.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 286 at r3](https://reviewable.io:443/reviews/grpc/grpc/10360#-KiWtPQ7ZeUJ_TUnsvP1:-KiWtPQ7ZeUJ_TUnsvP2:b-khadc) ([raw file](https://github.com/grpc/grpc/blob/cc503765d9ce0b3720cee6d83ae18805857bc196/test/cpp/end2end/grpclb_end2end_test.cc#L286)):*
>     grpc_channel_args* fake_result =
>         grpc_channel_args_copy_and_add(NULL, &fake_addresses, 1);

In this case, you can just say the following:

```
grpc_channel_args fake_result = {&fake_addresses, 1};
```

That way, there's no need to destroy it a few lines below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/10360#-:-KiWu4iDVrCxPO3ZyHXT:bht01ra)*

**Comment by dgquintas** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 124 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZsSUkBCWik1jAVUKY:-KifNIlieND3A03uj0-G:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L124)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest moving these two methods into the `CountedService` class, since they're used by both subclasses.

We could also add utility functions for incrementing the counts, which would simplify the code in the subclasses.
</blockquote></details>

Done.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 151 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZqqPzGVq6GyaPGfUj:-KifNGwaxswwKKWnYkoK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L151)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The typedefs should still be in the class, just listed ahead of the ctor.
</blockquote></details>

Done.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 161 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZq_PFu0OnV3344Acr:-KifNKAEEIYLvUCL_Z9A:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L161)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I generally dislike using `decltype()`.  Suggest using a typedef instead.
</blockquote></details>

Done.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 185 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZqlCNwV1LI7tegJJ0:-KifNLgApZZLPfle2Rvf:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L185)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the inner scope here.
</blockquote></details>

Done.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 192 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZqmr1cZi9vu1F6GAE:-KifNMFq59b87KgGGgCK:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L192)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for the inner scope here.
</blockquote></details>

Done.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 221 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZsUT2tTU-e4RjkjH9:-KifNO_CFRb3GKcHu1jG:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L221)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This probably isn't needed, since we're at the end of the function anyway -- i.e., we'll return regardless of the value of `shutdown_`.
</blockquote></details>

Done.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 305 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZvGZOygbtqYZIZ5fM:-KifNlnvOPENHwwK0gEY:bvan7gp) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L305)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this was addressed.
</blockquote></details>

It shouldn't be reused.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 358 at r1](https://reviewable.io:443/reviews/grpc/grpc/10360#-KgZveOBcjFTB3MYIbAI:-KifPEgSvhYNY6uCHdW2:b-htiv9p) ([raw file](https://github.com/grpc/grpc/blob/a2f879adf45914efd1c4a39712bb4adca4011f28/test/cpp/end2end/grpclb_end2end_test.cc#L358)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this was addressed.
</blockquote></details>

We need these: they are set in the constructor and consumed in SetUp(). Once we have them, we may as well use them.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 272 at r3](https://reviewable.io:443/reviews/grpc/grpc/10360#-KiWsz4C9SHFqr6ClIVH:-KifNY6XJ-PdMpEJImaB:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cc503765d9ce0b3720cee6d83ae18805857bc196/test/cpp/end2end/grpclb_end2end_test.cc#L272)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

All of the `NULL`s in this file should probably be `nullptr`s instead.
</blockquote></details>

Done.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 286 at r3](https://reviewable.io:443/reviews/grpc/grpc/10360#-KiWtPQ7ZeUJ_TUnsvP1:-KifNkPuFEtK-D5byd2a:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/cc503765d9ce0b3720cee6d83ae18805857bc196/test/cpp/end2end/grpclb_end2end_test.cc#L286)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

>     grpc_channel_args* fake_result =
>         grpc_channel_args_copy_and_add(NULL, &fake_addresses, 1);

In this case, you can just say the following:

```
grpc_channel_args fake_result = {&fake_addresses, 1};
```

That way, there's no need to destroy it a few lines below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/10360)*

**Comment by markdroth** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/10360)*

**Comment by markdroth** [comment]
If this fully replaces the old grpclb_test.cc, should we remove it in this PR?

**Comment by dgquintas** [comment]
Actually, grpclb_test covers update scenarios the new tests doesn't have yet. Porting this test is ~half a day job tops, but seems better to not delay merging this PR until that time can be allocated.

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by markdroth** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 34 at r4](https://reviewable.io:443/reviews/grpc/grpc/10360#-Kiq1uD_1eSVLtuejBRv:-Kiq1uD_1eSVLtuejBRw:bi374jn) ([raw file](https://github.com/grpc/grpc/blob/4c1462dbc899013e151ade351bc2f6d6918dfc87/test/cpp/end2end/grpclb_end2end_test.cc#L34)):*
> ```cpp
>  */
> 
> #include <arpa/inet.h>
> ```

I think this needs to be replaced with the following, in order to build on Windows:

```
#include "src/core/lib/iomgr/sockaddr.h"
```

---

*[test/cpp/end2end/grpclb_end2end_test.cc, line 372 at r4](https://reviewable.io:443/reviews/grpc/grpc/10360#-Kiq21Q_U_0J9psC-Euk:-Kiq21Q_U_0J9psC-Eul:b-97mr8q) ([raw file](https://github.com/grpc/grpc/blob/4c1462dbc899013e151ade351bc2f6d6918dfc87/test/cpp/end2end/grpclb_end2end_test.cc#L372)):*
> ```cpp
>   const size_t num_backends_;
>   const size_t num_balancers_;
>   CompletionQueue cli_cq_;
> ```

Doesn't look like this is actually used anywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/grpc/grpc/10360)*

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by dgquintas** [comment]
Will add issues later. Merging from mobile.

**Pull request merged**
