### PR TITLE
profile cpp overhead for call create

### PR DESCRIPTION
**Pull request by lyuxuan**
```
Benchmark                             Time           CPU Iterations
-------------------------------------------------------------------
BM_LameChannelCallCreateCpp        2728 ns       2724 ns     257698
BM_LameChannelCallCreateCore       1830 ns       1828 ns     381045
```

### CODE REVIEW

**Comment by lyuxuan** [comment]
Run on (12 X 3501 MHz CPU s)
2017-04-12 18:05:33
Benchmark                             Time           CPU Iterations
-------------------------------------------------------------------
BM_LameChannelCallCreateCpp        2728 ns       2724 ns     257698
BM_LameChannelCallCreateCore       1830 ns       1828 ns     381045

**Comment by ctiller** [comment]
I haven't had a chance to look at the code yet, but the numbers look much
too different (I expect by a factor of 5 or do). We should cross check
they're exercising core equivalently.

**Comment by lyuxuan** [comment]
```
Benchmark                                          Time           CPU Iterations
--------------------------------------------------------------------------------
BM_LameChannelCallCreateCpp                     2867 ns       2867 ns     247218
BM_LameChannelCallCreateCore                    1764 ns       1764 ns     393540
BM_LameChannelCallCreateCoreSeparateBatch       2377 ns       2377 ns     293493
```

**Comment by ctiller** [comment]
This looks right. Will code review after lunch.

**Pull request merged**
