### PR TITLE
Fix ios flaky tests

### LINKED ISSUE #24739: FAILURE: macos/grpc_basictests_objc_ios & grpc_basictests_objc_mac
[grpc_basictests_objc_ios](https://source.cloud.google.com/results/invocations/85c1a140-e172-49e6-b870-7c4dd09922eb) & [grpc_basictests_objc_mac](https://source.cloud.google.com/results/invocations/a0b9b714-7d04-4e39-b08a-f4968fb543cf/targets)

Following tests are failing.
```
-[CallAPIv2Tests testMetadata]
-[CallAPIv2Tests testMetadata]
-[CallAPIv2Tests testUserAgentPrefix]
-[InteropTestsLocalCleartext testUnaryResponseHandler]
-[InteropTestsLocalSSL testUnaryResponseHandler]
-[InteropTestsRemote test4MBResponsesAreAccepted]
-[InteropTestsRemote testGlobalInterceptor]
-[InteropTestsRemote testHijackingInterceptor]
-[InteropTestsRemote testInterceptorAndGlobalInterceptor]
-[InteropTestsRemote testLargeUnaryRPCWithV2API]
-[InteropTestsRemote testLoggingInterceptor]
```

This could be related with Mojave upgrade.

### PR DESCRIPTION
**Pull request by yulin-liang**
Fix #24739

### CODE REVIEW

**Review by veblush — APPROVED** [review]

**Comment by yulin-liang** [comment]
Looks like `InteropTests` is still failed, which seems like a different bug. I'll take a look at that one.

**Comment by veblush** [comment]
`Basic Tests ObjC iOS ` and `Basic Tests ObjC MacOS ` passed in this PR so it's okay to get this in?

**Comment by yulin-liang** [comment]
Revert #24719 because it breaks mac and ios tests. Will revisit the PR after fixing these flaky tests.

**Comment by yulin-liang** [comment]
@veblush Yep, I'll merge it after the two pending tests are done.

**Pull request merged**
