### PR TITLE
Various RBE bazelrc improvements

### PR DESCRIPTION
**Pull request by jtattermusch**
- make sure we are using the right toolchain for ubsan (it works with the current one, but according to RBE team it's not correct).
- remove some TODOs
- fine tune some bazel options

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Test failures:
https://github.com/grpc/grpc/issues/16585
https://github.com/grpc/grpc/issues/13650

**Pull request merged**
