### PR TITLE
Allow use of alternative credential types.

### PR DESCRIPTION
**Pull request by daniel-j-born**

### CODE REVIEW

**Comment by ctiller** [comment]
Please hold until next week

**Comment by daniel-j-born** [comment]
I'm pretty sure I signed (or don't need?) the CLA.

Ready to merge PRs again?

**Comment by yang-g** [comment]
LGTM

**Comment by jtattermusch** [comment]
Please note that this PR has bypassed our "keeping it green" merge queue.

@ctiller , @nicolasnoble   I don't think it's necessary to revert in this case but feel free to raise objections (and then I can revert).

**Comment by daniel-j-born** [comment]
Sorry, folks. I think I need to defer to core gRPC team members to do merges from now on. I get an LGTM, assume it's OK to merge, and then find out it's really not, because I'm not familiar with the procedures.

**Comment by jtattermusch** [comment]
@daniel-j-born  no need to apologize, there's no way you could have known this. To explain: gRPC team is currently running a fixit effort to unflake all our tests. So far we've been very successful in doing so and temporarily we've introduced some measures to make sure no new flakes are added as we are exiting the fixit mode.

And yes, I think it would be good to defer merging to gRPC team members in future. It's just one click for someone on the team and it can prevent occasional misunderstandings.

Thanks for the contribution btw!

**Comment by yang-g** [comment]
I added this PR to our merging queue and added LGTM because that is
required for a merge. But I forgot to tell you about the procedure, so it
is not your fault.
In general, we let the reviewer merge PRs.

**Pull request merged**
