### PR TITLE
Adding flaky attribute for tests.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by nicolasnoble** [comment]
Looks like we broke travis...

**Comment by ctiller** [comment]
Damn...

**Comment by ctiller** [comment]
http://www.traviscistatus.com/

**Comment by ctiller** [comment]
"Degraded performance"... I'll say

**Comment by nicolasnoble** [comment]
Or something in my CL is interactive and breaking it.

**Comment by nicolasnoble** [comment]
Or its network is down in the dump. It took 10 minutes to run apt-get
update -qq.

**Comment by nicolasnoble** [comment]
Green!

**Pull request merged**
