### PR TITLE
[Build] Update distrib test to build DLL

### PR DESCRIPTION
**Pull request by dawidcha**

### CODE REVIEW

**Comment by dawidcha** [comment]
@veblush is this what you were expecting? Will this test now run as part of the PR checks?

**Comment by veblush** [comment]
Yep, this is what I wanted. Thanks!

**Review by veblush — APPROVED** [review]

**Comment by veblush** [comment]
@yashykt One more review please!

**Comment by dawidcha** [comment]
@yashykt Are you able to review?

**Review by yashykt — APPROVED** [review]

**Pull request merged**
