### PR TITLE
build GCR image for grpc-java 1.48.0 release

### PR DESCRIPTION
**Pull request by YifeiZhuang**

### CODE REVIEW

**Review by temawi — APPROVED** [review]

**Review by YifeiZhuang — COMMENTED** [review]
> At least 1 approving review is required by reviewers with write access. 

@ejona86 could you help merge it?

**Comment by ejona86** [comment]
Have you run the one-off CI run, mentioned in the documentation?

**Comment by YifeiZhuang** [comment]
> Have you run the one-off CI run, mentioned in the documentation?

No.  Running...

**Comment by YifeiZhuang** [comment]
> > Have you run the one-off CI run, mentioned in the documentation?
> 
> No. Running...
run successful: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fexperimental%2Flinux%2Fgrpc_interop_matrix_adhoc
@ejona86

**Comment by ejona86** [comment]
Result:
https://source.cloud.google.com/results/invocations/141428e9-1c7c-45ad-b1bf-c553ea734c59

**Review by ejona86 — APPROVED** [review]

**Pull request merged**
