### PR TITLE
Support GRPC++ compilation as windows dynamic library (DLL)

### PR DESCRIPTION
**Pull request by ivan-kishchenko**
# Support *grpc++* compilation as windows dynamic library (DLL) using cmake.

#### Description
Using one instance of grpc library between other windows dynamic libraries in application.

#### Example
My application (*client.exe*) use two my dynamic libraries (*a.dll* and *b.dll*). Both dynamic libraries (*a.dll* and *b.dll*) contain different implementation of different grpc clients (generated by *protoc.exe*). Every my dynamic library compiled with static grpc library (*grpc++.lib*), and as result - every dynamic library (*a.dll* and *b.dll*) contain implementation of *grpc++* static library. This is an issue for me, because my application after this contains duplicated implementation of *grpc++* static library.

Compilation GRPC as dynamic library (*DLL*) resolves this problem and in application loaded only once instance of *grpc++* library.

## How it fixed
Added new option *gRPC_BUILD_SHARED* (OFF by default) to CMakeLists.txt.
Added *dllexport* and *dllimport* directives to grpc++ code for export symbols and compile *grpc++* project as windows dynamic library (Only for windows and if gRPC_BUILD_SHARED=ON)

## How it works
- Configure and build project using *cmake* with *gRPC_BUILD_SHARED* option:
```
cmake . -G "Visual Studio 14 2015 Win64" -DgRPC_BUILD_SHARED=ON
cmake --build .
```

- Copy *grpc++.dll*, *grpc++.lib* and *libprotobuf.dll*, *libprotobuf.lib* to your project. grpc++ already contains grpc and gpr implementation inside.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @abcdea isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ivan-kishchenko** [comment]
I close pull request because build for linux is broken. After fix build for linux and pass all tests locally I reopen pull request.
Sorry for this issue.

**Pull request closed without merging**
