### PR TITLE
xDS Security: Use new way to fetch certificate provider plugin instance config

### PR DESCRIPTION
**Pull request by yashykt**
The new method is documented at https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md and based on https://github.com/envoyproxy/envoy/pull/17201

Note that the older fields are still used as a fallback mechanism since our current infrastructure still depends on those fields. 

All existing tests have been modified to use the newer fields and some basic tests have been added to test the old fields.

Also performing a quick check on all the cases mentioned in the gRFC for NACKing behavior. Cases NACKed-

1. Unrecognized certificate provider instance names
2. Bad `StringMatcher` for `match_subject_alt_names`
3. `CertificateValidationContext`:`verify_certificate_spki` (unsupported)
4. `CertificateValidationContext`:`verify_certificate_hash` (unsupported)
5. `CertificateValidationContext`:`require_signed_certificate_timestamp` (unsupported)
6. `CertificateValidationContext`:`crl` (unsupported)
7. `CertificateValidationContext`:`custom_validator_config` (unsupported)
8. `CommonTlsContext`:`validation_context_sds_secret_config` (unsupported)
9. `CommonTlsContext`:`tls_certificates` (Only NACKed if TLS certificate provider not provided in the supported fields)
10. `CommonTlsContext`:`tls_certificate_sds_secret_configs` (Only NACKed if TLS certificate provider not provided in the supported fields)
11. `CommonTlsContext`:`tls_params` (unsupported)
12. `CommonTlsContext`:`custom_handshaker` (unsupported)
11. `DownstreamTlsContext`/`UpstreamTlsContext`:Unrecognized transport socket
12. `DownstreamTlsContext`:`require_sni` (unsupported)
13. `DownstreamTlsContext`:unsupported `ocsp_staple_policy` (only LENIENT_STAPLING supported)
14. `DownstreamTlsContext`:TLS configuration without configuration to fetch TLS certs
15. `DownstreamTlsContext`:Tls configuration requires client certs but no validation certs configuration provided.
16. `DownstreamTlsContext`:`match_subject_alt_names` (unsupported on servers)
17. `UpstreamTlsContext`:TLS configuration provided without validation certs configuration

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/27264)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks pretty good!  My comments are mostly minor, except for the one about updating the tests.  I think it's important that our tests cover the fields actually described in the gRFC.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27264#-:-Mj5B_oX7lX82M2KkvAQ:b-frtxcq)* status: all files reviewed, 8 unresolved discussions (waiting on @donnadionne and @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 1912 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj55gFyEJimuzs-HVP5:-Mj55gFyEJimuzs-HVP6:bluo1kj) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L1912)):*
> ```cpp
> }
> 
> // CertificateProviderInstance is deprecated but we are still supporting it for
> ```

Please add a TODO to remove this as soon as TD is updated to populate the new fields.
___
*[src/core/ext/xds/xds_api.cc, line 2083 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj58jZj9Ip74ikVr9E3:-Mj58jZj9Ip74ikVr9E4:b-z9uk8i) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L2083)):*
> ```cpp
>       envoy_extensions_transport_sockets_tls_v3_CommonTlsContext_combined_validation_context(
>           common_tls_context_proto);
>   // The validation context is derived from the oneof in
> ```

Please move this comment up above the preceding statement.
___
*[src/core/ext/xds/xds_api.cc, line 2101 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj58MIj9AJbdhr03v8r:-Mj58MIj9AJbdhr03v8s:b-pu4eb7) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L2101)):*
> ```cpp
>     // 'validation_context_certificate_provider_instance' inside
>     // 'combined_validation_context'. Note that this way of fetching root
>     // certificates is deprecated and might be removed in the future.
> ```

s/might/will/.  Please make this a TODO.
___
*[src/core/ext/xds/xds_api.cc, line 2140 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj56ou3ALLGgnCbQ_5u:-Mj56ou3ALLGgnCbQ_5v:b-pu4eb7) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L2140)):*
> ```cpp
>   } else {
>     // Fall back onto 'tls_certificate_certificate_provider_instance'. Note that
>     // this way of fetching identity certificates is deprecated and might be
> ```

s/might/will/.  Please make this a TODO.
___
*[src/core/ext/xds/xds_api.cc, line 2408 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj586ugBUBSRKHlAdUJ:-Mj586ugBUBSRKHlAdUK:b7pr7qc) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L2408)):*
> ```cpp
>         "provider instance specified for validation."));
>   }
>   return GRPC_ERROR_CREATE_FROM_VECTOR("Error parsing DownstreamTlsContext",
> ```

If we're not going to support `match_subject_alt_names` on the server side, then we need an additional check here to add an error if that field is set.

Please thoroughly check the gRFC to make sure that there are no other edge cases we're missing here.
___
*[src/proto/grpc/testing/xds/v3/tls.proto, line 156 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj5ABX0EvWatorcftA9:-Mj5ABX0EvWatorcftAA:bx7cpth) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/proto/grpc/testing/xds/v3/tls.proto#L156)):*
> ```protobuf
> }
> 
> message SdsSecretConfig {}
> ```

Doesn't look like this is needed here, since you've added it inside of `CommonTlsContext` below.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8138 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj5AvxW6KEabjZ9m7gf:-Mj5AvxW6KEabjZ9m7gg:bcneick) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/test/cpp/end2end/xds_end2end_test.cc#L8138)):*
> ```cpp
>       transport_socket->set_name("envoy.transport_sockets.tls");
>       UpstreamTlsContext upstream_tls_context;
>       // TODO(yashykt): Modify this to use the new security fields once the
> ```

I think we should go ahead and do this now, and just add a separate test or two that use the old fields.  That way, when we remove the legacy code, we can just remove those separate tests and everything else will already be correct.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9200 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj5BL3D4HNQgq97jd5U:-Mj5BL3D4HNQgq97jd5V:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/test/cpp/end2end/xds_end2end_test.cc#L9200)):*
> ```cpp
>     filter_chain->add_filters()->mutable_typed_config()->PackFrom(
>         HttpConnectionManager());
>     // TODO(yashykt): Modify this to use the new security fields once the actual
> ```

Same here.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27264)* status: all files reviewed, 8 unresolved discussions (waiting on @donnadionne, @markdroth, and @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 2408 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj586ugBUBSRKHlAdUJ:-Mj5hJkO9gYQKtRHfK7U:bxdu4ym) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L2408)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're not going to support `match_subject_alt_names` on the server side, then we need an additional check here to add an error if that field is set.

Please thoroughly check the gRFC to make sure that there are no other edge cases we're missing here.
</blockquote></details>

`On the server side an implementation may support this field and its semantics, or NACK the update it if it doesn't.` Ah, I missed this earlier

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27264)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @donnadionne and @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 1912 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj55gFyEJimuzs-HVP5:-Mj6Meym8fj-ljEXd9Kn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L1912)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please add a TODO to remove this as soon as TD is updated to populate the new fields.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2083 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj58jZj9Ip74ikVr9E3:-Mj6MkbvEtR1crJaRejj:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L2083)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this comment up above the preceding statement.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2101 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj58MIj9AJbdhr03v8r:-Mj6Mqj_7hLqyC72_yl7:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L2101)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/might/will/.  Please make this a TODO.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 2140 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj56ou3ALLGgnCbQ_5u:-Mj6MrRj7DK7p4cZISep:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/core/ext/xds/xds_api.cc#L2140)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

s/might/will/.  Please make this a TODO.
</blockquote></details>

Done.
___
*[src/proto/grpc/testing/xds/v3/tls.proto, line 156 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj5ABX0EvWatorcftA9:-Mj6Ms5l25z-m33OHz-Z:b-ulao6q) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/src/proto/grpc/testing/xds/v3/tls.proto#L156)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Doesn't look like this is needed here, since you've added it inside of `CommonTlsContext` below.
</blockquote></details>

Good eye!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8138 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj5AvxW6KEabjZ9m7gf:-Mj6MZvS8-xlSvDogIAJ:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/test/cpp/end2end/xds_end2end_test.cc#L8138)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think we should go ahead and do this now, and just add a separate test or two that use the old fields.  That way, when we remove the legacy code, we can just remove those separate tests and everything else will already be correct.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 9200 at r1](https://reviewable.io/reviews/grpc/grpc/27264#-Mj5BL3D4HNQgq97jd5U:-Mj6MbKwEP5jMf57-qbh:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/25c160a89214af47f29a072cf88329a8c99c37d4/test/cpp/end2end/xds_end2end_test.cc#L9200)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Comment by yashykt** [comment]
Still need to add NACKing for `tls_params` and `custom_handshaker`

**Comment by yashykt** [comment]
Added NACKing for `tls_params` and `custom_handshaker`. @markdroth PTALA

**Review by markdroth — CHANGES_REQUESTED** [review]
Overall, this looks really good.  There's just one problem with the tests to address.

Please let me know if you have any questions.  Thanks!

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27264#-:-MjADtRP6PVzIJdGOXgx:bqrtomn)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne and @yashykt)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 9646 at r4](https://reviewable.io/reviews/grpc/grpc/27264#-MjAD-Et80jifZN8Iflf:-MjAD-Et80jifZN8Iflg:b-uus67m) ([raw file](https://github.com/grpc/grpc/blob/803f6d4e57dceb5ea6de4e8f3c04d0967706b62f/test/cpp/end2end/xds_end2end_test.cc#L9646)):*
> ```cpp
> }
> 
> TEST_P(XdsServerSecurityTest, NacksFieldTlsCertificates) {
> ```

These two tests seem wrong.

On the server side, the TLS cert provider is required, so if it's not present, we should be getting an error that says that the cert provider is not present, and it does not matter whether the tls_certificates or tls_certificate_sds_secret_configs fields are specified.  (Technically, we don't even need to check these fields on the server side.  It's okay if we do, and it's okay if that error gets added to the NACK message, but what we really care about on the server side is that we get an error message that says that the TLS cert provider is not specified, not whether it also includes errors about these two irrelevant fields.)

Conversely, I think we do need these tests on the client side, because there the TLS cert provider is optional, so the checks for these two fields are relevant.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27264)* status: all files reviewed, 1 unresolved discussion (waiting on @donnadionne and @markdroth)

___
*[test/cpp/end2end/xds_end2end_test.cc, line 9646 at r4](https://reviewable.io/reviews/grpc/grpc/27264#-MjAD-Et80jifZN8Iflf:-MjAiVnV6thMriEGI20C:bso4ay2) ([raw file](https://github.com/grpc/grpc/blob/803f6d4e57dceb5ea6de4e8f3c04d0967706b62f/test/cpp/end2end/xds_end2end_test.cc#L9646)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

These two tests seem wrong.

On the server side, the TLS cert provider is required, so if it's not present, we should be getting an error that says that the cert provider is not present, and it does not matter whether the tls_certificates or tls_certificate_sds_secret_configs fields are specified.  (Technically, we don't even need to check these fields on the server side.  It's okay if we do, and it's okay if that error gets added to the NACK message, but what we really care about on the server side is that we get an error message that says that the TLS cert provider is not specified, not whether it also includes errors about these two irrelevant fields.)

Conversely, I think we do need these tests on the client side, because there the TLS cert provider is optional, so the checks for these two fields are relevant.
</blockquote></details>

Moved to the client side

**Review by markdroth — APPROVED** [review]
Looks great!

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/27264#-:-MjAjK0S-DNgojhfXfbZ:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donnadionne)

**Comment by yashykt** [comment]
Thanks for reviewing!

**Pull request merged**
