### PR TITLE
Stop including inttypes.h in gRPC core public header

### LINKED ISSUE #14456: Cannot import `grpc` module in Swift files when using CocoaPods
I am trying to use gRPC-Core 1.9.1 in a vanilla macOS Swift project with CocoaPods.

The pod module compiles just fine, but when I add `import grpc` to one of my Swift files, I get the following error:

    <module-includes>:8:9: note: in file included from <module-includes>:8:
    #import "Headers/support/log.h"
            ^
    /Users/daniel/Library/Developer/Xcode/DerivedData/grpc-import-test-btagazabopubmzbtzlbubflbuxqo/Build/Products/Debug/gRPC-Core/grpc.framework/Headers/support/log.h:22:10: error: include of non-modular header inside framework module 'grpc':     '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/clang/include/inttypes.h'
    #include <inttypes.h>
             ^
    /Users/daniel/Documents/Xcode/Mac/grpc-import-test/grpc-import-test/AppDelegate.swift:10:8: error: could not build Objective-C module 'grpc'
    import grpc
           ^

It appears that this error is specific to `inttypes.h`, as removing that one `include` line fixes the error. I suspect that the problem is that Clang for some reason resolves this to its internal header (which includes an `#include_next` directive), but does not recognize that as a header that does not to be part of the module. Would it be possible to remove the `#include <inttypes.h>` from that file?

FYI, this is my Podfile:

    target 'grpc-import-test' do
      use_frameworks!
    
      pod 'gRPC-Core', '~> 1.9'
      pod 'BoringSSL', '~> 9.1'
    end

The project is a brand-new, otherwise empty Swift project.

### PR DESCRIPTION
**Pull request by muxi**
`inttypes.h` cannot be included in a public header `support/log.h` in Apple platforms (iOS, macos) when gRPC core is built as framework. The macros imported are not being used in this file either. This change fixes this problem and the resulted build issues on Apple platforms.

Fixes #14456

### CODE REVIEW

**Comment by vjpai** [comment]
Great observation; in the spirit of IWYU, can we just remove it from log.h altogether, rather than conditioning it on !APPLE ?

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +120  +0.0%

  [ = ]       0 TOTAL     +120  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -40  -0.0%

  [ = ]       0 TOTAL      -40  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +120  +0.0%

  [ = ]       0 TOTAL     +120  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -40  -0.0%

  [ = ]       0 TOTAL      -40  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
