### PR TITLE
Timer error in max_age_filter on 32-bit platforms

### PR DESCRIPTION
**Pull request by mhaidrygoog**
On 32-bit platforms, trying to use GRPC_MILLIS_INF_PAST (INT64_MIN) in a
gpr_atm type causes implicit conversion to 0 (see attached bug).

Using GPR_ATM_MIN on a gpr_atm type seems more correct and avoids the implicit conversion.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,025      Total (=)      1,955,025

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,758      Total (>)     10,843,754

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by mhaidrygoog** [comment]
Opened issue https://github.com/grpc/grpc/issues/16497 and re-running Basic Tests MacOS [opt]

**Comment by mhaidrygoog** [comment]
So received a successful build on rerunning the MacOS Basic Tests OPT job and it was successful. Issue mentioned in the above comment is still open to address its flakiness.

**Pull request merged**
