### PR TITLE
Utilize the GitHub Check Feature

### PR DESCRIPTION
**Pull request by lidizheng**
Current infrastructure post some test results through comments on GitHub pull requests. It may post 4-5 comments on each commit, as a result, the technical discussion will be **immersed** by the ocean of test results.

Thanks for @nicolasnoble 's guidance,  there is a GitHub feature that is perfectly suitable to solve this problem, the [GitHub check](https://developer.github.com/v3/checks/). The check is similar to a test that associated with a specific commit, but in the check page only the latest check will show up. Each check allows to output a summary or detail in Markdown to briefly describe the test result. If there is something requires action, the check be labeled as `failure` or `timeout`. In this way, we can reduce the distraction in each PR and helps contributors of gRPC read the content of PR (the less noise is, the faster information spreads).

**NEED HELP**: Only GitHub app can manipulate the check state. To use it, we need to put the private key to our testing cluster. Also, we need to install a [GitHub app](https://developer.github.com/v3/apps/) for grpc/grpc.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
That's great. If it doesn't work out of the box, it probably means that the service account we're using doesn't have access to the checks API. Let's sync up tomorrow.

**Comment by jtattermusch** [comment]
I experimented with checks API in the past with no success and then gave up. FTR seee https://github.com/grpc/grpc/issues/17114

**Comment by lidizheng** [comment]
@jtattermusch I encountered that limitation as well. And I attempt to proceed with creating a GitHub App. To authenticate as a GitHub App, the script needs to access three value: 1) The private key; 2) The GitHub App ID; 3) The Installation ID. With the help from @nicolasnoble , he managed to deploy the private key to Kokoro workers. Therefore, it enables us to use script to authenticate as a GitHub App, then call checks API.

**Comment by lidizheng** [comment]
Spent 3 hours to find out that the default Python distribution on Linux Kokoro workers is `pypy`. Now, the private key is accessible, and the request is sent out. But seems there is still missing one piece in the integration. Here is the result of creating/updating check on PR:
```json
{
  "documentation_url": "https://developer.github.com/v3/checks/runs/#create-a-check-run",
  "message": "Resource not accessible by integration"
}
```

**Comment by nicolasnoble** [comment]
Very nice.

**Pull request merged**
