### PR TITLE
Revert "run_interop_matrix.py speedup"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#15629

Looks like this PR introduces a breakage in interop_matrix suite - https://source.cloud.google.com/results/invocations/314e699c-c083-495f-ab09-4c286fb53845/targets

I have a hard time understanding why things are suddenly broken - the PR only changes the way the docker images are downloaded, it doesn't change anything about the way the tests are run.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by adelez** [comment]
Maybe because too many jobs running at the same time? How about increasing individual docker job timeout?

**Pull request merged**
