### PR TITLE
Do not generate _grpc.py if the given proto file doesn't contains any gRPC service.

### PR DESCRIPTION
**Pull request by fengli79**
Do not generate _grpc.py if the given proto file doesn't contains any gRPC service.

### CODE REVIEW

**Comment by kpayson64** [comment]
I'll defer to @nathanielmanistaatgoogle on this one, I'm fine with removing empty pb2_grpc.py files, but it sounded like he may have had some reservations.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by fengli79** [comment]
No problem. It's trivial.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
