### PR TITLE
[ObjC] run cpp ios cronet test with bazel

### PR DESCRIPTION
**Pull request by HannahShiSFB**
Cleanup and remove ios cpp test cronet

To test manually:
./tools/bazel test //src/objective-c/tests:CppCronetTests

@sampajano

### CODE REVIEW

**Review by sampajano — APPROVED** [review]
Fantastic! Thanks!!

**Comment by sampajano** [comment]
I believe this should be mergeable after tests are fixed now?

**Comment by sampajano** [comment]
@yashykt Hey Yash! Do you mind reviewing the `cpp/client/` changes? Thanks!

**Comment by sampajano** [comment]
> @yashykt Hey Yash! Do you mind reviewing the `cpp/client/` changes? Thanks!
> 
> (btw other changes LGTM!)

@yashykt Hey Yash, a friendly reminder! 😃

**Comment by HannahShiSFB** [comment]
Rebased and fixed CI, ready to merge.

**Review by yashykt — APPROVED** [review]

**Pull request merged**
