### PR TITLE
[Aio] Fix a segfault in check connectivity state

### PR DESCRIPTION
**Pull request by lidizheng**
I assumed `grpc_channel_check_connectivity_state` can be invoked safely on closed channels. However, it is in OSS, but not internally. This PR is a workaround for it.

### CODE REVIEW

**Comment by mehrdada** [comment]
Mmm... why not fix the internal version?

**Comment by lidizheng** [comment]
@mehrdada Well, then I need to figure out what's the magic (import) process has done from Core to Python. This fix is still valid by itself.

**Comment by mehrdada** [comment]
@lidizheng yeah, ..., thinking twice, it seems it is valid for `connectivity_state` API spec to crash if you have called `channel_destroy` explicitly previously.

**Comment by lidizheng** [comment]
Known failures: https://github.com/grpc/grpc/issues/15027

**Pull request merged**
