### PR TITLE
Upgrade boringssl-with-bazel submodule to latest chromium-stable-with-bazel

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/15055

### CODE REVIEW

**Comment by jtattermusch** [comment]
@nicolasnoble  do we need to upgrade to master-with-bazel or is chromium-stable-with-bazel enough? (that would be more aligned with chromium-stable branch we are using for third_party/boringssl).

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Which issue do you mean? I don't think bazel is building ObjC at current but I can definitely recheck if there's a related issue.

**Comment by matt-kwong** [comment]
Ah, I responded to the wrong PR. Can you check #15296, which updates the non-Bazel BoringSSL? @muxi, I remember you had to push some changes to CocoaPods the last time I updated BoringSSL, and wanted to check to see if you needed to do it again.

**Comment by muxi** [comment]
I see. The podspec got some building issue with Cocoapods. Troubleshooting that.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Pull request merged**
