### PR TITLE
Perf Bot Backport

### PR DESCRIPTION
**Pull request by ncteisen**
Backports #11034, #11467, #11504, #11505, #11510, #11444 to v1.4.x.

### CODE REVIEW

**Comment by matt-kwong** [comment]
QPS Diff and Trickle Diff are both failing. It looks like there's a missing PR that also needs to be backported..

**Comment by ncteisen** [comment]
Yep, one of the cherry picks got confused. Hopefully fixed now. The QPS one will still fail because it involved a change to qps_worker.cc. In order for that to work I would have to backport that first

**Comment by matt-kwong** [comment]
Side note: performance jobs are really starting to clog the Jenkins queue. Are there any benchmarks that can be disabled to alleviate the queue? If they all provide good signal for performance, then it's fine to not disable any.

**Comment by ncteisen** [comment]
You can turn QPS diff off I think. That one has been less useful, needs more tuning, and can be accomplished by dashboarding.

And I expect that trickle can go away in a month or two. But let's keep that one for now

**Pull request merged**
