### PR TITLE
fix for issue 6344. added printing of .proto file comments in generat…

### PR DESCRIPTION
**Pull request by makdharma**
…ed code.

### CODE REVIEW

**Comment by jcanizales** [comment]
Fixes #6344

**Comment by jcanizales** [comment]
Can you run the tests and paste here a sample of what the generated `Test.pbrpc.h` file under `src/objective-c/tests/RemoteTestClient` looks like with your addition?

**Comment by makdharma** [comment]
[Test.pbrpc.h.txt](https://github.com/grpc/grpc/files/307646/Test.pbrpc.h.txt)

**Comment by jcanizales** [comment]
Awesome, looks great!

**Pull request merged**
