### PR TITLE
NOT YET READY FOR REVIEW: C-ares on Windows

### PR DESCRIPTION
**Pull request by apolcyn**
Works off of https://github.com/grpc/grpc/pull/12416 (this is functionally the same as #12416, but it involves a c->c++ refactor and adds windows to the c-ares test suite).

Waiting to run all tests.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                  cpu_time    real_time
-------------------------  ----------  -----------
BM_MetadataRefUnrefStatic  +12%        +12%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                        FILE SIZE
 ++++++++++++++ GROWING                                                                          ++++++++++++++
  +1.6% +11.2Ki [None]                                                                            +107Ki  +1.3%
      +1.7% +10.9Ki [Unmapped]                                                                        +107Ki  +1.3%
      [NEW]     +80 vtable for grpc_core::FdNodePosix                                                    +80  [NEW]
      [NEW]     +80 vtable for grpc_core::FdNode                                                         +80  [NEW]
      [NEW]     +48 vtable for grpc_core::AresEvDriver                                                   +48  [NEW]
      [NEW]     +48 vtable for grpc_core::AresEvDriverPosix                                              +48  [NEW]
      [NEW]     +40 vtable for grpc_core::InternallyRefCounted<grpc_core::AresEvDriver>                  +40  [NEW]
      [NEW]     +40 vtable for grpc_core::InternallyRefCounted<grpc_core::FdNode>                        +40  [NEW]
  [NEW] +4.83Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver.cc   +4.83Ki  [NEW]
      [NEW] +1.51Ki grpc_core::AresEvDriver::NotifyOnEventLocked                                     +1.51Ki  [NEW]
      [NEW]    +697 grpc_core::FdNode::MaybeRegisterForReadsAndWrites                                   +697  [NEW]
      [NEW]    +274 grpc_core::AresEvDriver::AresEvDriver                                               +274  [NEW]
      [NEW]    +246 grpc_core::AresEvDriver::CreateAndInitialize                                        +246  [NEW]
      [NEW]    +244 [Other]                                                                             +244  [NEW]
      [NEW]    +243 grpc_core::AresEvDriver::~AresEvDriver                                              +243  [NEW]
      [NEW]    +231 grpc_core::FdNode::OnReadableInner                                                  +231  [NEW]
      [NEW]    +203 grpc_core::FdNode::~FdNode                                                          +203  [NEW]
      [NEW]    +196 grpc_core::FdNode::OnWriteableInner                                                 +196  [NEW]
      [NEW]    +155 [Unmapped]                                                                          +155  [NEW]
      [NEW]    +148 grpc_core::FdNode::OnReadable                                                       +148  [NEW]
      [NEW]    +148 grpc_core::FdNode::OnWriteable                                                      +148  [NEW]
      [NEW]    +112 grpc_core::AresEvDriver::LookupFdNodeIndex                                          +112  [NEW]
      [NEW]    +101 grpc_core::AresEvDriver::Shutdown                                                   +101  [NEW]
      [NEW]     +79 grpc_core::AresEvDriver::Destroy                                                     +79  [NEW]
      [NEW]     +79 grpc_core::FdNode::FdNode                                                            +79  [NEW]
      [NEW]     +54 grpc_core::FdNode::Shutdown                                                          +54  [NEW]
      [NEW]     +53 grpc_core::AresEvDriver::Start                                                       +53  [NEW]
      [NEW]     +47 grpc_core::AresEvDriver::CreateFdNode                                                +47  [NEW]
      [NEW]     +47 grpc_core::FdNode::GetInnerEndpoint                                                  +47  [NEW]
      [NEW]     +47 grpc_core::FdNode::RegisterForOnReadable                                             +47  [NEW]
  +0.7%     +28 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc         +28  +0.7%
      +6.0%     +15 grpc_resolver_dns_ares_init                                                          +15  +6.0%
       +20%     +12 grpc_resolver_dns_ares_shutdown                                                      +12   +20%
      +0.8%      +1 [Unmapped]                                                                            +1  +0.8%
  +3.3%      +9 third_party/address_sorting/address_sorting_posix.c                                   +9  +3.3%
      [NEW]      +6 address_sorting_enabled_for_current_platform                                          +6  [NEW]
       +12%      +3 [Unmapped]                                                                            +3   +12%

 -------------- SHRINKING                                                                        --------------
 -74.6% -1.93Ki src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_ev_driver_posi -1.93Ki -74.6%
      [DEL]   -1016 grpc_ares_notify_on_event_locked                                                   -1016  [DEL]
      [DEL]    -327 on_readable_cb                                                                      -327  [DEL]
      [DEL]    -285 grpc_ares_ev_driver_create                                                          -285  [DEL]
      [DEL]    -227 on_writable_cb                                                                      -227  [DEL]
      [DEL]    -203 fd_node_destroy                                                                     -203  [DEL]
      [DEL]    -179 grpc_ares_ev_driver_shutdown                                                        -179  [DEL]
      [DEL]    -171 grpc_ares_ev_driver_unref                                                           -171  [DEL]
      [DEL]     -84 [Unmapped]                                                                           -84  [DEL]
      [DEL]     -53 grpc_ares_ev_driver_start                                                            -53  [DEL]
      [DEL]     -49 grpc_ares_ev_driver_ref                                                              -49  [DEL]
      [DEL]     -47 grpc_ares_ev_driver_destroy                                                          -47  [DEL]
      [DEL]      -4 grpc_ares_ev_driver_get_channel                                                       -4  [DEL]
  -4.0%    -224 src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc        -224  -4.0%
     -27.7%    -202 on_srv_query_done_cb                                                                -202 -27.7%
      -2.2%     -32 grpc_dns_lookup_ares_impl                                                            -32  -2.2%
      -5.7%      -6 [Unmapped]                                                                            -6  -5.7%

  +1.0% +14.0Ki TOTAL                                                                             +110Ki  +1.2%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                            cpu_time    real_time
-----------------------------------  ----------  -----------
BM_ErrorStringOnNewError<ErrorNone>  +12%        +12%
BM_MetadataRefUnrefStatic            +6%         +6%
```

**Comment by apolcyn** [comment]
splitting this into https://github.com/grpc/grpc/pull/15176 https://github.com/grpc/grpc/pull/15179, and leaving a TODO to get it running automatically on windows (as part of larger C++ windows test effort).

**Pull request closed without merging**
