### PR TITLE
Fix mac/win breakage on limit_cores change

### PR DESCRIPTION
**Pull request by vjpai**
I was trigger-happy in merging #5547 . Fixing a breakage.

### CODE REVIEW

**Comment by ctiller** [comment]
Can't we just roll it back?

**Comment by ctiller** [comment]
Actually: let me be clearer.

The correct thing to do when we merge something that's broken is to roll it
back immediately.
Then we look to fixing it.

Particularly this week: is the change fixing something that's preventing us
going green?

**Comment by ctiller** [comment]
#5597

**Comment by vjpai** [comment]
This should be done differently anyway. Closing.

**Pull request closed without merging**
