### PR TITLE
extract_metadata_from_bazel.py: add automatic grpc_upb_proto_library expansion 

### PR DESCRIPTION
**Pull request by jtattermusch**
Improved version of https://github.com/grpc/grpc/pull/24642.

Add `grpc_upb_proto_library` in bazel build, and update extract_metadata_from_bazel_xml.py so that there is no noticeable change to the generated build systems (cmake, make, etc..)

### CODE REVIEW

**Comment by markdroth** [comment]
This looks great!  Will it require internal changes in order to import it?

**Comment by jtattermusch** [comment]
> This looks great! Will it require internal changes in order to import it?

I haven't tried, but hopefully not - it should be strictly better than your original PR https://github.com/grpc/grpc/pull/24642 (since it changes fewer files).

**Comment by markdroth** [comment]
Can you try it out and verify that that's the case?  I think we need to find out before we merge rather than later. :)  Thanks!

**Comment by jtattermusch** [comment]
> Can you try it out and verify that that's the case? I think we need to find out before we merge rather than later. :) Thanks!

I can try once a have a little bit of free time - if you're blocked by this and you want a result fast, feel free to try it out yourself and post back the result.

**Pull request closed without merging**
