### PR TITLE
xds-k8s: grant roles/iam.workloadIdentityUser automatically

### PR DESCRIPTION
**Pull request by sergiitk**
1. Automatically grant `roles/iam.workloadIdentityUser` to workload identity member `serviceAccount:PROJECT_ID.svc.id.goog[K8S_NAMESPACE/KSA_NAME]` so kubernetes pods can use GCP service account
2. Implement support for Service Account policy bindings via [GCP IAM API](https://cloud.google.com/iam/docs/reference/rest), with features analogous to `gcloud iam service-accounts add-iam-policy-binding` and `gcloud iam service-accounts remove-iam-policy-binding`
2. Describe how to setup dedicated GCP workload service account with [minimal required privileges](https://en.wikipedia.org/wiki/Principle_of_least_privilege) to run xds test client and server.
3. Describe how to setup CI to allow test framework to grant `roles/iam.workloadIdentityUser` automatically (normally this requires project owner)

This is needed to run multiple instances of the driver, each restricted to its own kubernetes namespace. b/177354746

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/26487)

### CODE REVIEW

**Review by lidizheng — COMMENTED** [review]
Thanks for doing this! Great work on adding a new mechanism to interact with the GCP IAM service.

Do you have a Kokoro run link for this PR?

> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487#-:-McGwyNB5RtCvyVTYlvC:b-otou0k)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/README.md, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGsmgu0pNZOtbFQZT0:-McGsmgu0pNZOtbFQZT1:bsosxg4) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/README.md#L53)):*
> ```Markdown
> export ZONE="us-central1-a" 
> # Dedicated GCP Service Account to use with workload identity.
> export WORKLOAD_SERVICE_ACCOUNT="xds-k8s-interop-tests@${PROJECT_ID}.iam.gserviceaccount.com"
> ```

I like previous version which allows people to pick their K8s namespace name. Is there a reason we want a fixed SA name?
___
*[tools/run_tests/xds_k8s_test_driver/README.md, line 108 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGtWa_2Hvlq-9jmto9:-McGtWa_2Hvlq-9jmtoA:b-vhe3fl) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/README.md#L108)):*
> ```Markdown
> project, **you can skip this step**.  
> If you're configuring the test framework to run on a CI: use `roles/owner`
> account once to allow test framework to grant `roles/iam.workloadIdentityUser`.
> ```

Optional: we might also want to mention scope for VMs or GKE clusters. During my experiments, I once blocked by a VM unable to access most GCP API due to bad scope setting.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGvkDg62W5wqBPw1EN:-McGvkDg62W5wqBPw1EO:b-2uisg9) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L71)):*
> ```Python
> 
>     @classmethod
>     def from_response(cls, response):
> ```

Type annotation for response?
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 98 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGvnyN646pVy1wLIka:-McGvnyN646pVy1wLIkb:b-2uisg9) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L98)):*
> ```Python
> 
>     @classmethod
>     def from_response(cls, response):
> ```

Type annotation for response?
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 105 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGvr3h7dgmFZnPtTK2:-McGvr3h7dgmFZnPtTK3:bzdvvnp) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L105)):*
> ```Python
> 
> 
> @dataclasses.dataclass(eq=False, frozen=True)
> ```

Just curious, why do we need `eq=False`?
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 188 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGw6F4CdPG82xx-GRL:-McGw6F4CdPG82xx-GRM:b94g2tu) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L188)):*
> ```Python
>         super().__init__(api_manager.iam('v1'), project)
>         # Shortcut to projects/*/serviceAccounts/ endpoints
>         self._service_accounts = self.api.projects().serviceAccounts()
> ```

Do we need to worry about this line to hang or take unexpectedly long time?
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 300 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGwQDYC1sx5R4ZjqIA:-McGwQDYC1sx5R4ZjqIB:b4fgkf8) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L300)):*
> ```Python
> 
>     @staticmethod
>     def _replace_binding(policy, binding, new_binding):
> ```

nit: This can be a private function in this module. It's better to simplify the class logic, since they tend to grow in complexity naturally.
___
*[tools/run_tests/xds_k8s_test_driver/framework/test_app/client_app.py, line 320 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGuIEhDcpggGG3_Gm_:-McGuIEi0F19cxVFFoSL:b-o79e5c) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/test_app/client_app.py#L320)):*
> ```Python
>                 gcp_iam=self.gcp_iam,
>                 gcp_service_account=self.gcp_service_account,
>                 service_account_name=self.service_account_name)
> ```

Is it possible to share a service account across multiple namespaces? In that way, we can save a few seconds granting and revoking identity users.

**Review by sergiitk — COMMENTED** [review]
Thanks for useful feedback! Kokoro run link isn't ready yet, I had to setup new SA on prod first. Will post it as soon as it passes.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487#-:-McQWApIA7TnyZSJIEqw:b-985f0j)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @lidizheng and @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/README.md, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGsmgu0pNZOtbFQZT0:-McLihrv1LkF-az9QEOu:br1v7dw) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/README.md#L53)):*
> I like previous version which allows people to pick their K8s namespace name.

`K8S_NAMESPACE` was only used for `gcloud compute firewall-rules create "${K8S_NAMESPACE}-allow-health-checks"`, which has no relation to `$K8S_NAMESPACE`. Don't remember why I even used it.

> Is there a reason we want a fixed SA name?

I'll break it into

```sh
export WORKLOAD_SA_NAME="xds-k8s-interop-tests"
export WORKLOAD_SA_EMAIL="${WORKLOAD_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
```

Apparently `gcloud iam service-accounts create` can't accept full workload name (AKA email format).
___
*[tools/run_tests/xds_k8s_test_driver/README.md, line 108 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGtWa_2Hvlq-9jmto9:-McLizg_Cqt9QHxkf2mV:b-xophf) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/README.md#L108)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Optional: we might also want to mention scope for VMs or GKE clusters. During my experiments, I once blocked by a VM unable to access most GCP API due to bad scope setting.
</blockquote></details>

AFAIK `--scopes=cloud-platform` only needed when Workload Identity is off.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 105 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGvr3h7dgmFZnPtTK2:-McLn5bQ6FIRhbMsf__X:b-k2begy) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L105)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Just curious, why do we need `eq=False`?
</blockquote></details>

Good catch! It used to contain unhashable field (`members` was a list), and I forgot that I swapped it for a frozen set.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 188 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGw6F4CdPG82xx-GRL:-McQR09C1eFPTzYoyorV:b-3hr2ic) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L188)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Do we need to worry about this line to hang or take unexpectedly long time?
</blockquote></details>

Not on this line, at this point it's basically building object from a loaded spec.
However, the line above could:

```
super().__init__(api_manager.iam('v1'), project)
```
`api_manager.iam('v1')` performs a network call to a discovery URL, to load the spec. I don't think we should fix it in this PR, but it's a valid concern. I'll take a note for my GCP API refactoring.
___
*[tools/run_tests/xds_k8s_test_driver/framework/test_app/client_app.py, line 320 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGuIEhDcpggGG3_Gm_:-McQJ5-b7Aom1Lnewloq:bl1z8ya) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/test_app/client_app.py#L320)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Is it possible to share a service account across multiple namespaces? In that way, we can save a few seconds granting and revoking identity users.
</blockquote></details>

It's possible, but here's why we're not doing it

1. Namespace is a part of [Workload Identity member name](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#concepts): `serviceAccount:PROJECT_ID.svc.id.goog[K8S_NAMESPACE/KSA_NAME]`, so we'll still need to do grant/revoke at least once per different namespace
2. It's better to treat test client and test server as completely separate apps. Real world example would be something like a web server talking to a payment server, and each one will separate service account (with different set of permissions). This is reflected in PSM Security setup, where kubernetes service account is [a part of spiffe identity](https://cloud.google.com/traffic-director/docs/security-proxyless-setup#create-service): `spiffe://WORKLOAD_POOL/ns/NAMESPACE/sa/KUBERNETES_SERVICE_ACCOUNT`, which becomes app identifier in the certificates (see https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE-ID.md#22-path). And we want to test that different apps (with different owners) can talk to each other

**Review by sergiitk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487)* status: 3 of 11 files reviewed, 7 unresolved discussions (waiting on @lidizheng)

___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 71 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGvkDg62W5wqBPw1EN:-McQZfV56d9r7xgmsxwa:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L71)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Type annotation for response?
</blockquote></details>

Done.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 98 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGvnyN646pVy1wLIka:-McQZgmy7HgzZpeDLwWP:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L98)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Type annotation for response?
</blockquote></details>

Done.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 105 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGvr3h7dgmFZnPtTK2:-McQ_3Vt3Yhvgrk86Hco:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L105)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

Good catch! It used to contain unhashable field (`members` was a list), and I forgot that I swapped it for a frozen set.
</blockquote></details>

Done.

**Review by lidizheng — COMMENTED** [review]
This PR looks great. Thanks for the changes. I will approve once we confirmed that Kokoro would be happy with this PR.

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487#-:-McQhauQELvhicXi-Ymf:b-nohph4)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @lidizheng and @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/README.md, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGsmgu0pNZOtbFQZT0:-McQg9qP46N3vBGUvdQC:b-nwd8pi) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/README.md#L53)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

> I like previous version which allows people to pick their K8s namespace name.

`K8S_NAMESPACE` was only used for `gcloud compute firewall-rules create "${K8S_NAMESPACE}-allow-health-checks"`, which has no relation to `$K8S_NAMESPACE`. Don't remember why I even used it.

> Is there a reason we want a fixed SA name?

I'll break it into

```sh
export WORKLOAD_SA_NAME="xds-k8s-interop-tests"
export WORKLOAD_SA_EMAIL="${WORKLOAD_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
```

Apparently `gcloud iam service-accounts create` can't accept full workload name (AKA email format).
</blockquote></details>

Yep. I mean we could set:

```
export WORKLOAD_SA_NAME="${K8S_NAMESPACE}-workload-sa"
```
___
*[tools/run_tests/xds_k8s_test_driver/config/grpc-testing.cfg, line 4 at r2](https://reviewable.io/reviews/grpc/grpc/26487#-McQgPA88MizJGoPbWOw:-McQgPA88MizJGoPbWOx:b-46so7e) ([raw file](https://github.com/grpc/grpc/blob/6b37340f1904b6525e872185136879585ae4997a/tools/run_tests/xds_k8s_test_driver/config/grpc-testing.cfg#L4)):*
> ```INI
> --project=grpc-testing
> --network=default-vpc
> --gcp_service_account=xds-k8s-interop-tests@grpc-testing.iam.gserviceaccount.com
> ```

Are the IAM policy bindings already set up for this SA?
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py, line 143 at r2](https://reviewable.io/reviews/grpc/grpc/26487#-McQgZpd4IHQjFLIhXNZ:-McQgZpd4IHQjFLIhXN_:bdb32gb) ([raw file](https://github.com/grpc/grpc/blob/6b37340f1904b6525e872185136879585ae4997a/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py#L143)):*
> ```Python
> 
>     @functools.lru_cache(None)
>     def iam(self, version):
> ```

Type annotations.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 188 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGw6F4CdPG82xx-GRL:-McQgmtkCvw9kQqT4Pkl:b1xjjft) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L188)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

Not on this line, at this point it's basically building object from a loaded spec.
However, the line above could:

```
super().__init__(api_manager.iam('v1'), project)
```
`api_manager.iam('v1')` performs a network call to a discovery URL, to load the spec. I don't think we should fix it in this PR, but it's a valid concern. I'll take a note for my GCP API refactoring.

</blockquote></details>

Then... should we worry about the `api_manager.iam('v1')` taking unexpectedly long time? I'm not sure when the pulling of IAM resources happens. But we may want to either fast-fast or retry with a reasonable deadline.
___
*[tools/run_tests/xds_k8s_test_driver/framework/test_app/client_app.py, line 320 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGuIEhDcpggGG3_Gm_:-McQhA0Q4FEfi0G5gqp_:brxp9sq) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/test_app/client_app.py#L320)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

It's possible, but here's why we're not doing it

1. Namespace is a part of [Workload Identity member name](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#concepts): `serviceAccount:PROJECT_ID.svc.id.goog[K8S_NAMESPACE/KSA_NAME]`, so we'll still need to do grant/revoke at least once per different namespace
2. It's better to treat test client and test server as completely separate apps. Real world example would be something like a web server talking to a payment server, and each one will separate service account (with different set of permissions). This is reflected in PSM Security setup, where kubernetes service account is [a part of spiffe identity](https://cloud.google.com/traffic-director/docs/security-proxyless-setup#create-service): `spiffe://WORKLOAD_POOL/ns/NAMESPACE/sa/KUBERNETES_SERVICE_ACCOUNT`, which becomes app identifier in the certificates (see https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE-ID.md#22-path). And we want to test that different apps (with different owners) can talk to each other
</blockquote></details>

Sounds good.

**Review by sergiitk — COMMENTED** [review]
Tests passed! https://fusion2.corp.google.com/invocations/92ff9b67-0205-4f1f-a832-2f8b0963c0df

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487#-:-McQwlLcEOIEuXYZYoJk:b-50sevn)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @lidizheng)

___
*[tools/run_tests/xds_k8s_test_driver/README.md, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGsmgu0pNZOtbFQZT0:-McQozHO1WNRmjPuWfn_:beeh91o) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/README.md#L53)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Yep. I mean we could set:

```
export WORKLOAD_SA_NAME="${K8S_NAMESPACE}-workload-sa"
```
</blockquote></details>

Potentially, but I don't see how `$K8S_NAMESPACE` related to `$WORKLOAD_SA_NAME`.

Especially that we'll generate k8s namespace name on the flight soon, with including unique test run id.  In that PR i'm planning to introduce `--resource-prefix` to disambiguate with `--namespace` (used both for prefixes and k8s namespaces).

Maybe adding `$RESOURCE_PREFIX` would make more sense? Something like

```sh
export RESOURCE_PREFIX="xds-k8s-interop-tests"
export CLUSTER_NAME="${RESOURCE_PREFIX}-cluster"
# ...
export WORKLOAD_SA_NAME="${RESOURCE_PREFIX}"
# ...
gcloud compute firewall-rules create "${RESOURCE_PREFIX}-allow-health-checks"

```
___
*[tools/run_tests/xds_k8s_test_driver/config/grpc-testing.cfg, line 4 at r2](https://reviewable.io/reviews/grpc/grpc/26487#-McQgPA88MizJGoPbWOw:-McQqiPE5-O6KQIQg6KA:bgu76fr) ([raw file](https://github.com/grpc/grpc/blob/6b37340f1904b6525e872185136879585ae4997a/tools/run_tests/xds_k8s_test_driver/config/grpc-testing.cfg#L4)):*
Yes, already running kokoro using it


> `I0617 13:35:44.306092 140060747343616 base_runner.py:152] Granting roles/iam.workloadIdentityUser to serviceAccount:grpc-testing.svc.id.goog[sergii-xds-k8s-pr26487/psm-grpc-server] for GCP Service Account xds-k8s-interop-tests@grpc-testing.iam.gserviceaccount.com`
> `I0617 13:35:44.749932 140060747343616 iam.py:280] Role roles/iam.workloadIdentityUser granted to member serviceAccount:grpc-testing.svc.id.goog[sergii-xds-k8s-pr26487/psm-grpc-server] for Service Account xds-k8s-interop-tests@grpc-testing.iam.gserviceaccount.com`
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py, line 143 at r2](https://reviewable.io/reviews/grpc/grpc/26487#-McQgZpd4IHQjFLIhXNZ:-McQr1A9ByuSopHYTGjE:bf1lp01) ([raw file](https://github.com/grpc/grpc/blob/6b37340f1904b6525e872185136879585ae4997a/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py#L143)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Type annotations.
</blockquote></details>

Thanks. We probably should revive that mypy PR.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 188 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGw6F4CdPG82xx-GRL:-McQt-UO1StnJV140IKD:b1jauws) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L188)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Then... should we worry about the `api_manager.iam('v1')` taking unexpectedly long time? I'm not sure when the pulling of IAM resources happens. But we may want to either fast-fast or retry with a reasonable deadline.
</blockquote></details>

This doesn't pull IAM resources, just discovery doc (aka API spec). Looking at google-api-python-client, for this operation the defaults are [1 retry](https://github.com/googleapis/google-api-python-client/blob/9e4e06048cb6940b70591d6179986db0d81d8fba/googleapiclient/discovery.py#L363) and [timeout 60s](https://github.com/googleapis/google-api-python-client/blob/9e4e06048cb6940b70591d6179986db0d81d8fba/googleapiclient/http.py#L77).
So far it wasn't causing issues. Do you think moving this out of `__init__`, and lazy-loading on demand would be a good solution?

**Review by sergiitk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @lidizheng)

___
*[tools/run_tests/xds_k8s_test_driver/config/grpc-testing.cfg, line 4 at r2](https://reviewable.io/reviews/grpc/grpc/26487#-McQgPA88MizJGoPbWOw:-McQxbbjCKNeR6vuj5D8:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b37340f1904b6525e872185136879585ae4997a/tools/run_tests/xds_k8s_test_driver/config/grpc-testing.cfg#L4)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

Yes, already running kokoro using it


> `I0617 13:35:44.306092 140060747343616 base_runner.py:152] Granting roles/iam.workloadIdentityUser to serviceAccount:grpc-testing.svc.id.goog[sergii-xds-k8s-pr26487/psm-grpc-server] for GCP Service Account xds-k8s-interop-tests@grpc-testing.iam.gserviceaccount.com`
> `I0617 13:35:44.749932 140060747343616 iam.py:280] Role roles/iam.workloadIdentityUser granted to member serviceAccount:grpc-testing.svc.id.goog[sergii-xds-k8s-pr26487/psm-grpc-server] for Service Account xds-k8s-interop-tests@grpc-testing.iam.gserviceaccount.com`

</blockquote></details>

Done.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py, line 143 at r2](https://reviewable.io/reviews/grpc/grpc/26487#-McQgZpd4IHQjFLIhXNZ:-McQxYyaCVks2ygIf3mm:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6b37340f1904b6525e872185136879585ae4997a/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py#L143)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

Thanks. We probably should revive that mypy PR.
</blockquote></details>

Done.

**Review by lidizheng — APPROVED** [review]
LGTM. Great work! Don't forget to remove the DO-NOT-MERGE contents.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487#-:-McRJYcK9PhxyB0hAdHq:b-3rdjw5)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @lidizheng and @sergiitk)

___
*[tools/run_tests/xds_k8s_test_driver/README.md, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGsmgu0pNZOtbFQZT0:-McRIOYLDut9m9zD_hkY:b-6so51j) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/README.md#L53)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

Potentially, but I don't see how `$K8S_NAMESPACE` related to `$WORKLOAD_SA_NAME`.

Especially that we'll generate k8s namespace name on the flight soon, with including unique test run id.  In that PR i'm planning to introduce `--resource-prefix` to disambiguate with `--namespace` (used both for prefixes and k8s namespaces).

Maybe adding `$RESOURCE_PREFIX` would make more sense? Something like

```sh
export RESOURCE_PREFIX="xds-k8s-interop-tests"
export CLUSTER_NAME="${RESOURCE_PREFIX}-cluster"
# ...
export WORKLOAD_SA_NAME="${RESOURCE_PREFIX}"
# ...
gcloud compute firewall-rules create "${RESOURCE_PREFIX}-allow-health-checks"

```
</blockquote></details>

Yep. The new variable sounds great.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py, line 143 at r2](https://reviewable.io/reviews/grpc/grpc/26487#-McQgZpd4IHQjFLIhXNZ:-McRIaMO3t_M6YWOylaF:bk8tfn3) ([raw file](https://github.com/grpc/grpc/blob/6b37340f1904b6525e872185136879585ae4997a/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py#L143)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yeah, it would help this situation. I can work on that when I got some free cycles.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 188 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGw6F4CdPG82xx-GRL:-McRJ9su7kdbm_ErhFKR:b-mcch48) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L188)):*
<details><summary><i>Previously, sergiitk (Sergii Tkachenko) wrote…</i></summary><blockquote>

This doesn't pull IAM resources, just discovery doc (aka API spec). Looking at google-api-python-client, for this operation the defaults are [1 retry](https://github.com/googleapis/google-api-python-client/blob/9e4e06048cb6940b70591d6179986db0d81d8fba/googleapiclient/discovery.py#L363) and [timeout 60s](https://github.com/googleapis/google-api-python-client/blob/9e4e06048cb6940b70591d6179986db0d81d8fba/googleapiclient/http.py#L77).
So far it wasn't causing issues. Do you think moving this out of `__init__`, and lazy-loading on demand would be a good solution?

</blockquote></details>

If there are retries already in place, I'm good.

**Review by sergiitk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @lidizheng)

___
*[tools/run_tests/xds_k8s_test_driver/README.md, line 53 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGsmgu0pNZOtbFQZT0:-McRKHgE5jRwx9LiKX7r:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/README.md#L53)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Yep. The new variable sounds great.
</blockquote></details>

Done.
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py, line 143 at r2](https://reviewable.io/reviews/grpc/grpc/26487#-McQgZpd4IHQjFLIhXNZ:-McRKFOvAcsx26F4Xost:b-9755fn) ([raw file](https://github.com/grpc/grpc/blob/6b37340f1904b6525e872185136879585ae4997a/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/api.py#L143)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Yeah, it would help this situation. I can work on that when I got some free cycles.
</blockquote></details>

Thank you!
___
*[tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py, line 188 at r1](https://reviewable.io/reviews/grpc/grpc/26487#-McGw6F4CdPG82xx-GRL:-McRKJvV2P2pjfkpYyZv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/05503775a908cc0bf03532702fb89ecbae9ce5a9/tools/run_tests/xds_k8s_test_driver/framework/infrastructure/gcp/iam.py#L188)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

If there are retries already in place, I'm good.
</blockquote></details>

Done.

**Review by sergiitk — COMMENTED** [review]
Thank for the review! Already reverted them in 9b4c3d3.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26487#-:-McRKUSk-yFrBOhQZfoK:bqlllvc)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @lidizheng)

**Pull request merged**
