### PR TITLE
Fix portability

### PR DESCRIPTION
**Pull request by jtattermusch**
Based on https://github.com/grpc/grpc/pull/28273,

hopefully adds the few remaining fixes.

Should fix: b/209014236

adhoc grpc_portability run: http://sponge/8f6f21c3-ce57-49ea-aa04-e547a5e2d7ab (green)

### CODE REVIEW

**Comment by apolcyn** [comment]
All bazel RBE tests are still failing: 

```
Traceback (most recent call last):
  File "test/core/../../test/core/http/test_server.py", line 22, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by jtattermusch** [comment]
Simple local repro of the failure
```
tools/bazel --bazelrc=tools/remote_build/manual.bazelrc test --config=opt //test/core/http:httpcli_test@poller=poll --cache_test_results=no --test_output=streamed
```
Looks like we'll have to get away without using `six` (since installing six into RBE image is going to be problematic).

**Comment by jtattermusch** [comment]
Adhoc portability tests run: http://sponge/47569a57-80da-4547-82f6-ca349a928aa8

**Review by apolcyn — APPROVED** [review]

**Comment by jtattermusch** [comment]
Known failures:
- ruby failures are b/209603283
- macos C failure seems to be a flake: https://source.cloud.google.com/results/invocations/d912094a-5bf1-4c21-8e86-1bcf99c70b61/targets/github%2Fgrpc%2Frun_tests%2Fc_macos_dbg_native/tests

**Pull request merged**
