### PR TITLE
Bump v1.7.x branch to 1.7.1

### PR DESCRIPTION
**Pull request by apolcyn**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @apolcyn isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by apolcyn** [comment]
I signed it!

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by apolcyn** [comment]
test failures:
* basic tests c++ (opt, dbg): https://github.com/grpc/grpc/issues/12510, https://github.com/grpc/grpc/issues/12313
* macos dbg/opt: https://github.com/grpc/grpc/issues/13073
* basic tests multi-lang linux: #13073  
* basic tests windows dbg: https://github.com/grpc/grpc/issues/12858
* basic tests windows opt: https://github.com/grpc/grpc/issues/11109
* cloud to cloud/cloud to prod didn't run because of kokoro config exception

**Comment by nicolasnoble** [comment]
We'll make the tag retro-actively.

**Pull request merged**
