### PR TITLE
Convince the compiler that the lock is held

### PR DESCRIPTION
**Pull request by tamird**
See commit message.

### CODE REVIEW

**Comment by tamird** [comment]
Hang on, this isn't correct.

**Comment by tamird** [comment]
OK, this is correct now (in that with this change I am able to compile in Fuchsia).

**Comment by veblush** [comment]
@tamird Thank you for the PR. But can you elaborate this more?

**Comment by tamird** [comment]
My feeling is that the compiler is simply not smart enough to know that the lambda passed to it is being called in a context in which the lock is held. There's a more elaborate explanation linked from the commit message.

```
        // Convince the compiler that the lock is held here. This is safe
        // because the lock is held over the call to zxio_do_vector and
        // zxio_do_vector is synchronous, so it cannot extend the life of this
        // lambda.
        //
        // This is required because the compiler does its analysis
        // function-by-function. In this function, it can't see that the lock is
        // held by the calling scope. If We annotate this function with
        // TA_REQUIRES, then this function compiles, but its call in
        // zxio_do_vector doesn't, because the compiler can't tell that the lock
        // is held in that function.
```

It might be possible to make `WaitUntil` `inline` instead? I can try that if you like.

**Comment by tamird** [comment]
Just kidding -- making it `inline` didn't help, the compiler still emits the same warning.

**Comment by tamird** [comment]
@veblush does grpc continuous integration actually check these annotations? It seems like no (I intentionally introduced an incorrect usage and ran `python tools/run_tests/run_tests.py -l c++ --build_only` and it exited successfully).

**Comment by tamird** [comment]
Closing in favor of #26866.

**Pull request closed without merging**
