### PR TITLE
[PSM Interop] Enable custom_lb_test for CXX

### PR DESCRIPTION
**Pull request by eugeneo**

### CODE REVIEW

**Comment by sergiitk** [comment]
Manual test run:
- [grpc/core/master/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/cc9654eb-fa0c-4f94-958c-28d1191e56fb)

**Comment by sergiitk** [comment]
@eugeneo FYI custom_lb test test failed:

```
Traceback (most recent call last):
  File "/tmpfs/tmp/tmp.hM6p0ES1S8/grpc/tools/run_tests/xds_k8s_test_driver/tests/custom_lb_test.py", line 98, in test_custom_lb_config
    method='UNARY_CALL')
  File "/tmpfs/tmp/tmp.hM6p0ES1S8/grpc/tools/run_tests/xds_k8s_test_driver/framework/xds_k8s_testcase.py", line 292, in assertRpcStatusCodes
    self.fail(f"Expected only status {status} but found status "
AssertionError: Expected only status 15 but found status 0 for method UNARY_CALL:
stats_per_method {
  key: "UNARY_CALL"
  value {
    result {
      key: 0
      value: 201
    }
  }
}
```

**Review by sergiitk — CHANGES_REQUESTED** [review]
The test failed. Looks like this happened because the `error-code-` behavior has been reverted: https://github.com/grpc/grpc/pull/32769.

**Comment by eugeneo** [comment]
Test run: [grpc/core/master/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/ea6c0d53-f56f-47b2-8b45-2da270d99747)

**Review by sergiitk — APPROVED** [review]

**Pull request merged**
