### PR TITLE
Enable Abseil crash handler on Windows

### PR DESCRIPTION
**Pull request by veblush**
Let's move forward by having a workaround for a mysterious SymInitialize failure on Windows (#24178).

Workaround: Renaming following targets so that they don't have a name which is 89 or 90 long. 

```
//test/core/client_channel/resolvers:dns_resolver_connectivity_using_native_resolver_test
//test/cpp/qps:qps_json_driver_test_cpp_generic_async_streaming_qps_unconstrained_insecure
//test/cpp/qps:qps_json_driver_test_cpp_protobuf_async_streaming_from_client_1channel_1MB
//test/cpp/qps:qps_json_driver_test_cpp_protobuf_sync_streaming_qps_unconstrained_insecure
```

### CODE REVIEW

**Comment by veblush** [comment]
It's ready for the review.

**Comment by jtattermusch** [comment]
Can you please confirm that you checked manually that the bazel test s(when build locally) do give stack trace correctly when they fail? (we know that on windows RBE that won't work).

**Review by jtattermusch — COMMENTED** [review]
I think we'd need to fix some better explanation for https://github.com/grpc/grpc/issues/24178 before we merge this.
Like this we'd just be getting the SymInitialize randomly and if a test with wrong name length is added, this issue would exhibit itself, which sounds like maintenance hell.

I agree that unifying on using the Absl symbolizer would be nice, but it seems that currently nothings forcing us to do so (we only use the symbolizer in tests, right?), so introducing the SymInitialize problem (for which we don't know the root cause) seems to be too much unnecessary risk?

**Comment by veblush** [comment]
@jtattermusch Yeah, it worked locally on Windows machines.

For the `SymInitialize` error (#24178), Bazel RBE team and I made a conclusion it's a bazel's problem (I suspect that it's a simple edge case of handling long-path file) and I filed the issue there. (They haven't responded yet, though) 

One thing to be clear is that both our current code and abseil have this problem because both use `SymInitialize`. The difference is that ours just simply ignores it when it returns error but Abseil aborts. So ours won't get symbolized stack-trace for 4 tests I modified.

Benefit of using Abseil crash handler & stack-tracer is

- Recently I made ours tests to dump a stack-trace when printing error logs like how internal Google logging does. For example ([log](https://source.cloud.google.com/results/invocations/2b65e14b-ee4f-445f-a96b-31edc213359d/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fbazel_rbe%2Fgrpc_bazel_rbe_opt/log))

```
E1104 05:35:48.628627750      18 cq_verifier.cc:277]         cq returned unexpected event: OP_COMPLETE: tag:0x1 OK
Stack trace:
    @           0x6afa3b         64  _ZN9grpc_core20GetCurrentStackTraceB5cxx11Ev
    @           0x6b1a12        320  gpr_default_log()
    @           0x6b1b92         48  gpr_log_message
    @           0x6b1875        256  gpr_log
    @           0x4420e5        128  cq_verify()
    @           0x435dc3        896  do_request_and_shutdown_server()
    @           0x435b0e        112  disappearing_server()
    @           0x40a1c9        112  grpc_end2end_tests()
    @           0x4086f1         96  main
    @     0x7f641cb70830  (unknown)  __libc_start_main
    @ 0x7f7e258d4c544155  (unknown)  (unknown)
```

- Crash handler is more reliable. For example, our handler on Mac sometimes keeps printing abort log indefinitely without actually exiting. But Abseil's one properly exits in that case.

**Review by jtattermusch — APPROVED** [review]
LGTM.

**Comment by jtattermusch** [comment]
> @jtattermusch Yeah, it worked locally on Windows machines.
> 
> For the `SymInitialize` error (#24178), Bazel RBE team and I made a conclusion it's a bazel's problem (I suspect that it's a simple edge case of handling long-path file) and I filed the issue there. (They haven't responded yet, though)
> 
> One thing to be clear is that both our current code and abseil have this problem because both use `SymInitialize`. The difference is that ours just simply ignores it when it returns error but Abseil aborts. So ours won't get symbolized stack-trace for 4 tests I modified.
> 
> Benefit of using Abseil crash handler & stack-tracer is
> 
> * Recently I made ours tests to dump a stack-trace when printing error logs like how internal Google logging does. For example ([log](https://source.cloud.google.com/results/invocations/2b65e14b-ee4f-445f-a96b-31edc213359d/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fbazel_rbe%2Fgrpc_bazel_rbe_opt/log))
> 
> ```
> E1104 05:35:48.628627750      18 cq_verifier.cc:277]         cq returned unexpected event: OP_COMPLETE: tag:0x1 OK
> Stack trace:
>     @           0x6afa3b         64  _ZN9grpc_core20GetCurrentStackTraceB5cxx11Ev
>     @           0x6b1a12        320  gpr_default_log()
>     @           0x6b1b92         48  gpr_log_message
>     @           0x6b1875        256  gpr_log
>     @           0x4420e5        128  cq_verify()
>     @           0x435dc3        896  do_request_and_shutdown_server()
>     @           0x435b0e        112  disappearing_server()
>     @           0x40a1c9        112  grpc_end2end_tests()
>     @           0x4086f1         96  main
>     @     0x7f641cb70830  (unknown)  __libc_start_main
>     @ 0x7f7e258d4c544155  (unknown)  (unknown)
> ```
> 
> * Crash handler is more reliable. For example, our handler on Mac sometimes keeps printing abort log indefinitely without actually exiting. But Abseil's one properly exits in that case.

**Comment by jtattermusch** [comment]
> @jtattermusch Yeah, it worked locally on Windows machines.
> 
> For the `SymInitialize` error (#24178), Bazel RBE team and I made a conclusion it's a bazel's problem (I suspect that it's a simple edge case of handling long-path file) and I filed the issue there. (They haven't responded yet, though)
> 
> One thing to be clear is that both our current code and abseil have this problem because both use `SymInitialize`. The difference is that ours just simply ignores it when it returns error but Abseil aborts. So ours won't get symbolized stack-trace for 4 tests I modified.
> 
> Benefit of using Abseil crash handler & stack-tracer is
> 
> * Recently I made ours tests to dump a stack-trace when printing error logs like how internal Google logging does. For example ([log](https://source.cloud.google.com/results/invocations/2b65e14b-ee4f-445f-a96b-31edc213359d/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fbazel_rbe%2Fgrpc_bazel_rbe_opt/log))
> 
> ```
> E1104 05:35:48.628627750      18 cq_verifier.cc:277]         cq returned unexpected event: OP_COMPLETE: tag:0x1 OK
> Stack trace:
>     @           0x6afa3b         64  _ZN9grpc_core20GetCurrentStackTraceB5cxx11Ev
>     @           0x6b1a12        320  gpr_default_log()
>     @           0x6b1b92         48  gpr_log_message
>     @           0x6b1875        256  gpr_log
>     @           0x4420e5        128  cq_verify()
>     @           0x435dc3        896  do_request_and_shutdown_server()
>     @           0x435b0e        112  disappearing_server()
>     @           0x40a1c9        112  grpc_end2end_tests()
>     @           0x4086f1         96  main
>     @     0x7f641cb70830  (unknown)  __libc_start_main
>     @ 0x7f7e258d4c544155  (unknown)  (unknown)
> ```
> 
> * Crash handler is more reliable. For example, our handler on Mac sometimes keeps printing abort log indefinitely without actually exiting. But Abseil's one properly exits in that case.

Ok, if the SymInitialize issue is pre-existing, switching to absl which is otherwise better makes sense.

**Pull request merged**
