### PR TITLE
Initiate Pings Earlier

### PR DESCRIPTION
**Pull request by ncteisen**
C++ ify the ping code and start them before flushing writes

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]    -232  -0.0%

  [ = ]       0 TOTAL     -232  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by ncteisen** [comment]
Yash what do you think of this? Tried it a while ago to fix TF. It didn't, but it still might be worth putting the pings on the wire before flushing the data out

**Comment by yashykt** [comment]
I don't think I mind either way, but given that users have been complaining about our pings, I think we should be less aggressive rather than more aggressive

**Pull request closed without merging**
