### PR TITLE
Makes it friendly to import grpc from other bazel projects.

### PR DESCRIPTION
**Pull request by renning22**
Example of how to import grpc in other project's WORKSPACE file:

```
git_repository(
  name = "com_github_grpc_grpc",
  remote = "https://github.com/renning22/grpc.git",
  commit = "14a4c935dd0407cad121d91dd959ce3aae16b002",
)

# Setup grpc's dependencies.
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
```

Then
`bazel build @com_github_grpc_grpc//:grpc` would work.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @renning22 isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
The Linux Foundation CLA GitHub bot_

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by nicolasnoble** [comment]
I am going to merge #13060 first - you'll most likely want to revisit your PR after that.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by renning22** [comment]
Ack, thanks @nicolasnoble .

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by nicolasnoble** [comment]
Also, I'm sorry, but I won't be able to accept your PR if you don't accept the linux foundation CLA. Please visit https://identity.linuxfoundation.org/projects/cncf for this.

**Comment by renning22** [comment]
Thanks @nicolasnoble ,
I have signed linux foundation CLA and the PR is ready to review.

**Comment by nicolasnoble** [comment]
You'll want to update this file so the test pass again:

https://github.com/grpc/grpc/blob/master/tools/run_tests/sanity/check_bazel_workspace.py

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jwpowell055** [comment]
You might consider adopting the pattern used by https://github.com/bazelbuild/rules_go to allow users to optionally overwrite one or more of the dependencies supplied by your Skylark rules. For example,

```if "com_github_bazelbuild_buildtools" not in native.existing_rules():
    native.http_archive(
        name = "com_github_bazelbuild_buildtools",
        url = "https://codeload.github.com/bazelbuild/buildtools/zip/799e530642bac55de7e76728fa0c3161484899f6",
        strip_prefix = "buildtools-799e530642bac55de7e76728fa0c3161484899f6",
        type = "zip",
)```

The conditional will only install the version of Buildtools, e.g., that is supplied by you if the user isn't explicitly binding a rule of the same name somewhere else. See https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl for more examples. A little more discussion can be found at https://groups.google.com/forum/#!topic/bazel-discuss/EBeFucaAg3A.

**Comment by renning22** [comment]
I've fixed "check_bazel_workspace.py" test. It still not passing on my machine because "git submodule" for protobuf is still 80a37e0782d2d702d52234b62dd4b9ec74fd2c95, while the expectation has been updated in https://github.com/grpc/grpc/commit/28661ea6e189fc03fdcf9f6a0f6f15e40c916d08. I guess it should also fail "check_submodules.sh".

@jwpowell055 also adopted your suggestion, thanks!

**Pull request closed without merging**
