### PR TITLE
Adding client changes needed for circuit breaking tests

### PR DESCRIPTION
**Pull request by donnadionne**
- reworking interop client to accpet ClientConfig RPC
- adding new stats RPC

@nicolasnoble

### CODE REVIEW

**Comment by donnadionne** [comment]
Adding Circuit breaking interop test in v1.34.x (backporting from master)

**Comment by voidzcy** [comment]
Is this just the cherry-pick of #24587?

**Review by voidzcy — APPROVED** [review]

**Comment by voidzcy** [comment]
> Is this just the cherry-pick of #24587?

Okay, it looks so.

**Comment by donnadionne** [comment]
NO need to back port since we are not officially supporting CB in 1.34.0.

**Pull request closed without merging**
