### PR TITLE
Added node plugin to grpc-tools npm package, updated build_package_node

### LINKED ISSUE #5982: Simplify development environment for Node.js - package protoc and grpc protoc plugin.
Package and ship protoc and gprc plugin for Node.js.

- Figure out if it will be bundled with the grpc-node package or if it is going to be shipped separately. 
- Figure out for Mac/Linux/Windows.

On resolution of this issue, we should have 1 line install, via packages, for installing protoc, its plugins and the language runtime.

### PR DESCRIPTION
**Pull request by murgatroid99**
This makes the gRPC_build_packages job build the grpc-tools npm package and the corresponding binary artifacts. This fixes #5982.

### CODE REVIEW

**Comment by murgatroid99** [comment]
This is a successful build from this branch: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/621/platform=linux/

**Comment by jtattermusch** [comment]
The changes look fine to me, but I looked at the contents of that platform-specific tarballs (such as  linux-x64.tar.gz) and they seem to contain both  grpc_node_plugin and grpc_node_plugin.exe. Was that really intended?

**Comment by murgatroid99** [comment]
No, that wasn't intended, and I think that last change fixed it.

**Comment by murgatroid99** [comment]
I think I got it right this time: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/626/

**Comment by jtattermusch** [comment]
LGTM.

**Pull request merged**
