### PR TITLE
Generate JS file even if no services are defined in proto file; fix #…

### PR DESCRIPTION
**Pull request by vmax**
…10646

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @vmax isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by vmax** [comment]
@thelinuxfoundation I signed CLA

**Comment by murgatroid99** [comment]
Thank you for the contribution, but the Node service generation code has actually been moved to https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools, so you should make your PR on that repository.

**Comment by vmax** [comment]
@murgatroid99 moved to:
https://github.com/grpc/grpc-node/issues/574
https://github.com/grpc/grpc-node/pull/575

**Pull request closed without merging**
