### PR TITLE
Fix rvm ruby install failure

### LINKED ISSUE #27585: get.rvm.io Failing Consistently
```
++ rvm get stable
Downloading https://get.rvm.io
Could not download rvm-installer, please report to https://github.com/rvm/rvm/issues
```

This is currently affecting the [Artifact Build MacOS](https://source.cloud.google.com/results/invocations/127383bd-a21b-4803-91d5-b112e65422fa/targets) and [Basic Test Ruby MacOS](https://source.cloud.google.com/results/invocations/19a925da-1fb3-499d-9a62-0a44c2209a1b/targets) jobs.

@stanley-cheung Please route if you are no longer the appropriate contact for this.

### PR DESCRIPTION
**Pull request by drfloob**
See https://source.cloud.google.com/results/invocations/9a2a3ca2-72c9-43ef-af8c-fb1c8e7b488d/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_ruby/log

```
++ rvm get stable
Downloading https://get.rvm.io
Could not download rvm-installer, please report to https://github.com/rvm/rvm/issues
```

Fixes #27585

cc @apolcyn

### CODE REVIEW

**Comment by drfloob** [comment]
This may be a transient issue, the debug logs were not terribly helpful.

**Comment by drfloob** [comment]
This is an RVM issue, tracked here: https://github.com/rvm/rvm/issues/5133. I will look into a workaround.

**Comment by drfloob** [comment]
Workaround: since rvm uses curl under the hood, for now we will tell curl to rely on the root certificates that are bundled with gRPC. They were last updated a few days ago to remove the offending `DST Root CA X3` root cert.

**Review by apolcyn — APPROVED** [review]
lgtm, thanks!

**Comment by drfloob** [comment]
Fixes #27585

**Pull request merged**
