### PR TITLE
Backport #14282 to v1.9.x

### PR DESCRIPTION
**Pull request by matt-kwong**
Backport of #14282

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Don't merge yet, see https://github.com/grpc/grpc/pull/14282 for important comment.

**Comment by matt-kwong** [comment]
Issue: #14115 #13845 #13691

**Pull request merged**
