### PR TITLE
Let apt process finish before running another

### PR DESCRIPTION
**Pull request by matt-kwong**
Trying to reproduce this bug
```
+ sudo apt-get install -y jq
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

Reproduced while checking for an `apt` process: https://sponge.corp.google.com/target?id=0c2cdf6b-1c76-43cc-aff4-08b8f88092b9&target=grpc%2Fubuntu%2Fpull_request%2Fgrpc_basictests_cpp_opt&searchFor=
```
+ ps -A
+ grep apt
 3513 ?        00:00:00 apt.systemd.dai
 3525 ?        00:00:00 apt.systemd.dai
+ sudo apt-get install -y jq
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```
Looks like newer versions of Ubunutu have a daemon that updates system packages daily and on boot. This update locks `apt-get` causing `apt-get install` to fail in our builds. 

Possible solution: wait for all `apt` processes to finish before using `apt-get`. Will test this PR a few times to make sure that we can expect the daily apt daemon to finish.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by matt-kwong** [comment]
It looks like this issue is specific to our own images. I'll disable the daemon in our image instead of this PR.

**Comment by matt-kwong** [comment]
I updated the images to disable the daemon and ran 3 rounds of tests. None of them failed with the lock issue. This is likely a resolved issue.

**Pull request closed without merging**
