### PR TITLE
Upmerge from 1.3.0 to master

### PR DESCRIPTION
**Pull request by dgquintas**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by jtattermusch** [comment]
CC @jtattermusch

**Comment by y-zeng** [comment]
CC @markdroth

**Comment by jtattermusch** [comment]
Can we merge this?

**Comment by dgquintas** [comment]
Issues: #9088 #10969

**Pull request merged**
