### PR TITLE
Drop -msse4 compiler flag

### PR DESCRIPTION
**Pull request by stanhu**
Older CPUs that do not have SSE4.1 would crash with the Ruby native gem due to an illegal instruction exception.

The Abseil random library isn't being used at the moment (https://github.com/grpc/grpc/pull/26476), and there's no reason gRPC needs to force SSE4.1 instructions on all platforms at the moment. There are other hardware-specific issues that need to be ironed out for this to work: https://github.com/grpc/grpc/pull/26479

When the `-msse4` compiler flag was enabled, the Abseil code started using the `pinsrb` instruction:

```
$ elfx86exts abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.o
MODE64 (ret)
CMOV (cmovne)
SSE2 (movdqa)
SSE41 (pinsrb)
SSE1 (movaps)
CPU Generation: Penryn
```

This was previously needed because gcc 4.8 wouldn't compile without the `-msse4` and `-maes` flags.

However, per https://github.com/gcc-mirror/gcc/commit/97db2bf7fb10e7eb2e8224e0471b56976f133843 gcc 5.0+ automatically detects whether these options are enabled.

clang still needs `-maes` since including `wmmintrin.h` expects the AES option to be enabled.

Closes https://github.com/grpc/grpc/issues/27095

@markdroth @veblush

### CODE REVIEW

**Comment by mttkay** [comment]
@veblush Just checking if you had a chance to look at this yet? Unfortunately our Ruby 3 migration is blocked by this issue, since we had to revert to an older version of gRPC (from times prior to gRPC receiving Ruby 3 related fixes). The only alternative would be for us to roll our own version of gRPC (or at least abseil-cpp) with these patches applied, which is a lot of effort.

**Comment by stanhu** [comment]
@jtattermusch Would you mind taking a look at this pull request?

**Comment by veblush** [comment]
AFAIK, those flags were necessary to build Abseil. But I could be wrong so let's check the result of CI.

FYI, I'm about to change how to build Abseil (https://github.com/grpc/grpc/pull/27193) so this will be solved once gRPC gets the next Abseil release. (presumably next this year)

**Comment by stanhu** [comment]
@veblush Looking at https://github.com/grpc/grpc/pull/23357, I see `third_party/abseil-cpp/absl/random/internal/randen_hwaes.cc` has this: 

```c
#elif defined(ABSL_ARCH_X86_64) || defined(ABSL_ARCH_X86_32)
// On x86 we rely on the aesni instructions
#include <wmmintrin.h>
```

This sounds like `-maes` **might** be necessary, but `-msse4` could be dropped. What do you think?

**Comment by stanhu** [comment]
I'm not sure what is defining `ABSL_ARCH_X86_64` because it's not being defined in my build. I added some garbage in the `elif` block, and gRPC compiled fine.

**Comment by stanhu** [comment]
Oh, it looks like abseil defines this: https://github.com/abseil/abseil-cpp/blob/997aaf3a28308eba1b9156aa35ab7bca9688e9f6/absl/random/internal/platform.h#L63

**Comment by stanhu** [comment]
It looks gcc 5 and up don't need these compiler flags because they are only enabled when specific flags are in use (https://github.com/gcc-mirror/gcc/commit/97db2bf7fb10e7eb2e8224e0471b56976f133843). For example:

```c
#ifndef _WMMINTRIN_H_INCLUDED
#define _WMMINTRIN_H_INCLUDED

/* We need definitions from the SSE2 header file.  */
#include <emmintrin.h>

/* AES */

#if !defined(__AES__) || !defined(__SSE2__)
#pragma GCC push_options
#pragma GCC target("aes,sse2")
#define __DISABLE_AES__
#endif /* __AES__ */
```

`emmintrin.h` does this as well:

```c
#ifndef _EMMINTRIN_H_INCLUDED
#define _EMMINTRIN_H_INCLUDED

/* We need definitions from the SSE header files*/
#include <xmmintrin.h>

#ifndef __SSE2__
#pragma GCC push_options
#pragma GCC target("sse2")
#define __DISABLE_SSE2__
#endif /* __SSE2__ */
```

**Comment by stanhu** [comment]
clang doesn't have these guards (https://github.com/llvm-mirror/clang/blob/master/lib/Headers/wmmintrin.h). I wonder how these CI builds are working without the options.

Should abeseil be including `immintrin.h` instead? https://github.com/llvm-mirror/clang/blob/aa231e4be75ac4759c236b755c57876f76e3cf05/lib/Headers/immintrin.h#L38-L40

**Comment by stanhu** [comment]
For completeness, I submitted https://github.com/abseil/abseil-cpp/pull/1015.

**Comment by veblush** [comment]
[grpc_build_artifacts_multiplatform](https://fusion2.corp.google.com/invocations/bf76aee5-f85e-4718-8afc-2364c7d93112): running

**Comment by veblush** [comment]
@stanhu thanks you for investigation on this. I'm okay with removing `-msse4` if this can solve the build issue.

**Comment by stanhu** [comment]
@veblush Yeah, I think dropping `-msse4` will work for `clang`. Let me do that then.

**Comment by veblush** [comment]
Thank you for the update. Let me trigger the CI tests.

**Comment by veblush** [comment]
[grpc_build_artifacts_multiplatform](https://fusion2.corp.google.com/invocations/410a5a3f-e52f-4776-9ce6-e2d18d9ff6d3/targets): running

**Review by veblush — APPROVED** [review]
LGTM. Thank you for the PR!

**Comment by veblush** [comment]
@jtattermusch One more LGTM, please.

**Review by jtattermusch — APPROVED** [review]
LGTM once the tests are green.

Note that the test failures on MacOS look suspicious  - @veblush  can you please double check that they are 100% not caused by this PR before merging.

**Comment by stanhu** [comment]
@veblush Could you look this again?

This is even more urgent now that older versions of gRPC ship a stale cacerts that doesn't work with the recent LetsEncrypt root certificate expiration: https://gitlab.com/gitlab-org/gitlab/-/issues/342346

**Comment by jtattermusch** [comment]
The objC failure https://source.cloud.google.com/results/invocations/433116be-2252-4cf5-b810-9f1573fdf51f/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fios-test-interoptests/tests looks unrelated and all the other tests are green.
I'm going to merge.

**Pull request merged**
