### PR TITLE
Even More Clang Tidy: performance-*

### PR DESCRIPTION
**Pull request by ncteisen**
~Built on #15680.~

Working towards #14085.

Enables all `performance-*` checks and makes them pass. Most were done automatically, the second commit was done manually

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

 -+-+-+-+-+-+-+ MIXED                                              +-+-+-+-+-+-+-
  +0.0%     +11 [None]                                             -4.90Ki  -0.1%

  -0.1%    -396 TOTAL                                              -5.30Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                 cpu_time    real_time
----------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/262144                                             -8%         -8%
BM_PumpStreamServerToClient<InProcess>/32768                                              -5%         -5%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/1                     +4%         +4%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/2                     +4%         +4%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                       +7%         +7%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/1     +7%         +7%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/1/0  +4%         +4%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/2/1  +9%         +9%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/262144                            -4%         -4%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/2097152                        -4%         -4%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

 -+-+-+-+-+-+-+ MIXED                                              +-+-+-+-+-+-+-
  +0.0%     +11 [None]                                             -4.90Ki  -0.1%

  -0.1%    -396 TOTAL                                              -5.30Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

 -+-+-+-+-+-+-+ MIXED                                              +-+-+-+-+-+-+-
  +0.0%     +11 [None]                                             -4.90Ki  -0.1%

  -0.1%    -396 TOTAL                                              -5.30Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                              cpu_time    real_time
-------------------------------------------------------------------------------------  ----------  -----------
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/1/1  +6%         +6%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/0  +4%         +4%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/2/1  +4%         +4%
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                                 cpu_time    real_time
----------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamServerToClient<InProcess>/262144                                             -8%         -8%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/262144                   +8%         +8%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/262144/2/1  +6%         +6%
BM_StreamingPingPongWithCoalescingApi<MinInProcess, NoOpMutator, NoOpMutator>/32768/2/1   +4%         +4%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

 -+-+-+-+-+-+-+ MIXED                                              +-+-+-+-+-+-+-
  +0.0%     +11 [None]                                             -4.90Ki  -0.1%

  -0.1%    -396 TOTAL                                              -5.30Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

 -+-+-+-+-+-+-+ MIXED                                              +-+-+-+-+-+-+-
  +0.0%     +11 [None]                                             -4.90Ki  -0.1%

  -0.1%    -396 TOTAL                                              -5.30Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

 -+-+-+-+-+-+-+ MIXED                                              +-+-+-+-+-+-+-
  +0.0%     +11 [None]                                             -4.90Ki  -0.1%

  -0.1%    -396 TOTAL                                              -5.30Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                cpu_time    real_time
-----------------------------------------------------------------------  ----------  -----------
BM_PumpStreamClientToServer<InProcess>/262144                            +5%         +5%
BM_StreamingPingPong<MinInProcess, NoOpMutator, NoOpMutator>/262144/2    -4%         -4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/262144  -4%         -4%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32768   -5%         -5%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/2097152          +4%         +4%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/262144/262144      +5%         +5%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/32768/32768        +4%         +4%
BM_UnaryPingPong<MinInProcess, NoOpMutator, NoOpMutator>/0/2097152       +8%         +8%
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Tests are green, ready for review

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -0.0%     -21 [None]                                             -4.86Ki  -0.1%
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

  -0.1%    -428 TOTAL                                              -5.26Ki  -0.1%



```

**Comment by ncteisen** [comment]
Rebased to merge together manual changes

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -0.0%     -21 [None]                                             -4.86Ki  -0.1%
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

  -0.1%    -428 TOTAL                                              -5.26Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -0.0%     -21 [None]                                             -4.86Ki  -0.1%
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

  -0.1%    -428 TOTAL                                              -5.26Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Failures:
- #15753 
- #15457

**Comment by ncteisen** [comment]
This PRs successor, #15684, has actual failure I am looking into. This one does not. Let's push forward and merge this one to make the investigation of the next one easier

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                                          FILE SIZE
 ++++++++++++++ GROWING                                            ++++++++++++++

 -------------- SHRINKING                                          --------------
  -0.0%     -21 [None]                                             -4.86Ki  -0.1%
  -1.2%    -407 src/cpp/server/server_cc.cc                           -407  -1.2%
     -12.2%    -218 grpc::Server::Server                                  -218 -12.2%
     -11.3%    -183 grpc::Server::SyncRequestThreadManager::DoWork        -183 -11.3%
      -1.5%      -6 [Unmapped]                                              -6  -1.5%

  -0.1%    -428 TOTAL                                              -5.26Ki  -0.1%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                                              cpu_time    real_time
-------------------------------------------------------------------------------------  ----------  -----------
BM_PumpStreamServerToClient<InProcess>/262144                                          -11%        -11%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/262144                   -6%         -6%
BM_StreamingPingPongMsgs<InProcess, NoOpMutator, NoOpMutator>/32768                    -7%         -7%
BM_StreamingPingPongMsgs<MinInProcess, NoOpMutator, NoOpMutator>/32768                 -8%         -8%
BM_StreamingPingPongWithCoalescingApi<InProcess, NoOpMutator, NoOpMutator>/262144/1/1  -6%         -6%
BM_UnaryPingPong<InProcess, NoOpMutator, NoOpMutator>/0/262144                         +5%         +5%
```

**Comment by ncteisen** [comment]
#15029 
#14245

**Pull request merged**
