### PR TITLE
Remove fd dependencies from the local_security_connector

### PR DESCRIPTION
**Pull request by drfloob**
Getting the local address from the raw fd should be unnecessary here. The endpoint's local_address is already set from socket operations on endpoint creation; I checked the iomgr implementations for posix, windows, custom, cfstream, and I spot checked internally. If this works and there are no objections, it may merit a cherry pick import.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/26290)

### CODE REVIEW

**Comment by drfloob** [comment]
The python errors are due to #26322

**Review by markdroth — CHANGES_REQUESTED** [review]
I think the overall approach here is fine, but the implementation isn't quite right.

CC @lidizheng and @yihuazhang, since we have discussed this before.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26290#-:-MaADAEe0ERy9DX-N0c6:b-z4p2o)* status: all files reviewed, 5 unresolved discussions (waiting on @drfloob and @nicolasnoble)

___
*[src/core/lib/address_utils/sockaddr_utils.h, line 82 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaAAmCb1OPm5KFYGJ3Q:-MaAAmCcDeKfQfG5V4Af:bfy3en5) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.h#L82)):*
> ```objc
> /// Strips the URI scheme and port from \a addr, if present.
> ///
> /// This method works with the output of `grpc_sockaddr_to_uri`. If the URI
> ```

This doesn't make sense.  All URIs start with a scheme.  If the string doesn't have a scheme, it isn't a URI.
___
*[src/core/lib/address_utils/sockaddr_utils.h, line 86 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaABnIh0XGeMhxnImdS:-MaABnIh0XGeMhxnImdT:byd93ir) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.h#L86)):*
> ```objc
> /// modified version of \a addr without those URI components. Otherwise, a copy
> /// of \a addr is returned.
> std::string grpc_uri_to_addr_string(absl::string_view addr);
> ```

I don't think this function is needed.  The result of `grpc_endpoint_get_local_address()` should always be a URI, and we can use the existing `grpc_parse_uri()` function to handle it directly in the local credentials code.  We don't need another library function to do this.
___
*[src/core/lib/address_utils/sockaddr_utils.cc, line 259 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaAB3Gu46txzhPN9gMq:-MaAB3Gu46txzhPN9gMr:bbw0mcd) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.cc#L259)):*
> ```cpp
>   auto uri = grpc_core::URI::Parse(addr);
>   if (!uri.ok()) {
>     gpr_log(GPR_ERROR, "Could not parse URI string: %s", addr.data());
> ```

Low-level library functions like this should not log; if necessary, they should have a way to indicate an error to the caller, and the caller can decide whether to log.

Also, it's not safe to treat the result of `string_view::data()` as a null-terminated string, since you have no guarantee that the character following the last one is a null (or is even in memory allocated by this process).
___
*[src/core/lib/address_utils/sockaddr_utils.cc, line 262 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaABX60DoWjjW1lKUBO:-MaABX60DoWjjW1lKUBP:bqw63oh) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.cc#L262)):*
> ```cpp
>     return "";
>   }
>   // Due to the non-standard-compliant URI format used in gRPC-core (see
> ```

This is incorrect.  Our URIs are RFC-3986-compliant, and the address will always be in the path, never in the authority.
___
*[src/core/lib/security/security_connector/local/local_security_connector.cc, line 77 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaACoJz6cbhnuyP2TZ4:-MaACoJz6cbhnuyP2TZ5:b-9365p0) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/security/security_connector/local/local_security_connector.cc#L77)):*
> ```cpp
>   grpc_resolved_address resolved_addr;
>   bool is_endpoint_local = false;
>   std::string local_addr(grpc_endpoint_get_local_address(ep));
> ```

As I mentioned above, I think we should just use the existing `grpc_parse_uri()` function to convert this URI into the `grpc_resolved_address`.

**Review by drfloob — COMMENTED** [review]
Thank you for the review! Changes made, PTAL.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26290#-:-MaASFA6375JhKxLVYAL:b93enmo)* status: all files reviewed, 5 unresolved discussions (waiting on @markdroth and @nicolasnoble)

___
*[src/core/lib/address_utils/sockaddr_utils.h, line 82 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaAAmCb1OPm5KFYGJ3Q:-MaAIr5xCtvPqGJCeZ53:b2nhysk) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.h#L82)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't make sense.  All URIs start with a scheme.  If the string doesn't have a scheme, it isn't a URI.
</blockquote></details>

ack
___
*[src/core/lib/address_utils/sockaddr_utils.h, line 86 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaABnIh0XGeMhxnImdS:-MaAItj-EbJfxzBGzXpT:bsy03by) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.h#L86)):*
> grpc_parse_uri()
Definitely, I forgot we had that. Done.
___
*[src/core/lib/address_utils/sockaddr_utils.cc, line 259 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaAB3Gu46txzhPN9gMq:-MaAIzMIC0zrwmUPzrer:baxpa3s) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.cc#L259)):*
> it's not safe to treat the result of string_view::data() as a null-terminated string, since you have no guarantee that the character following the last one is a null (or is even in memory allocated by this process).

Fixed. I wrestled with this, which you can see in earlier commits in this PR where I took extra steps to be paranoid here. I agree fundamentally that it's not great to trust that it's null-terminated, especially in security code. Ultimately I decided it'd get flagged either way as being too paranoid or not paranoid enough (i.e., it's thought-provoking), so I'm glad to hear you think we should take the extra step. Pragmatically, all current implementations provide a null-terminated string, and I expect something may experience UB before it gets to this point (but of course we can't be sure). The URI Parser, for example, was flagged by asan when I wrote a test to parse a non-null-terminated `char*`.
___
*[src/core/lib/address_utils/sockaddr_utils.cc, line 262 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaABX60DoWjjW1lKUBO:-MaALRfs5UyaEph_jbdq:bwqdg7q) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.cc#L262)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This is incorrect.  Our URIs are RFC-3986-compliant, and the address will always be in the path, never in the authority.
</blockquote></details>

Ack, thanks for the correction.  I do not mean to split hairs with that comment, and in any case you're right that the address here should be in the path. What I meant is that neither ipv4 or ipv6 schemes are listed with IANA https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml, and I didn't find another reference for them. In `ipv6:[::1]:80`, there is no authority specified, and if I understand things correctly, the meaning of a URI with a missing authority is scheme-specific (for example with `http`, a missing authority makes it an invalid URI altogether. With the `file` scheme, it's implicitly localhost).
___
*[src/core/lib/security/security_connector/local/local_security_connector.cc, line 77 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaACoJz6cbhnuyP2TZ4:-MaAPs9DC3WrxrbjNd7V:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/security/security_connector/local/local_security_connector.cc#L77)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

As I mentioned above, I think we should just use the existing `grpc_parse_uri()` function to convert this URI into the `grpc_resolved_address`.
</blockquote></details>

Done.

**Comment by lidizheng** [comment]
Sorry that PR https://github.com/grpc/grpc/pull/22082 fell through my radar. I might took some unnecessary detour there to extend `sockaddr_utils.cc`. This PR is much more simpler. I can add a Python local credential test after this is merged (so it will be tested on Linux/macOS/Windows).

**Review by markdroth — APPROVED** [review]
This looks good to me!  But this is security code, so please don't merge until Yihua approves.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26290#-:-MaAZ5Kc98cFRQ_zPJf-:b9try4w)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nicolasnoble)

___
*[src/core/lib/address_utils/sockaddr_utils.cc, line 259 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaAB3Gu46txzhPN9gMq:-MaAX35755hW-nuoij_b:bkv9ul2) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.cc#L259)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

> it's not safe to treat the result of string_view::data() as a null-terminated string, since you have no guarantee that the character following the last one is a null (or is even in memory allocated by this process).

Fixed. I wrestled with this, which you can see in earlier commits in this PR where I took extra steps to be paranoid here. I agree fundamentally that it's not great to trust that it's null-terminated, especially in security code. Ultimately I decided it'd get flagged either way as being too paranoid or not paranoid enough (i.e., it's thought-provoking), so I'm glad to hear you think we should take the extra step. Pragmatically, all current implementations provide a null-terminated string, and I expect something may experience UB before it gets to this point (but of course we can't be sure). The URI Parser, for example, was flagged by asan when I wrote a test to parse a non-null-terminated `char*`.
</blockquote></details>

Even if every existing implementation guarantees that the result will always be null-terminated, the API itself does not -- i.e., `absl::string_view` inherently has no guarantee that it's safe to access the character immediately following the range encoded in the type.  Therefore, even if it happens to be safe in all of the places where we're currently calling this (which is why none of the sanitizers complained), that does not mean that this is safe to do *as an API*.  If we were going to provide a function that takes an `absl::string_view` as a parameter, callers will not (and should not) make an assumption that the parameter value must have a null in the character following the passed-in string.

In other words, the question here is about what programmers would expect when they see an API that takes an `absl::string_view` parameter, not about the ways in which our code happens to currently call that API.
___
*[src/core/lib/address_utils/sockaddr_utils.cc, line 262 at r1](https://reviewable.io/reviews/grpc/grpc/26290#-MaABX60DoWjjW1lKUBO:-MaAXyDA6zypSmln1G5l:bc9yj12) ([raw file](https://github.com/grpc/grpc/blob/a4b371ed5138ee8adfe0c0fd9de8470a2487523c/src/core/lib/address_utils/sockaddr_utils.cc#L262)):*
<details><summary><i>Previously, drfloob (AJ Heller) wrote…</i></summary><blockquote>

Ack, thanks for the correction.  I do not mean to split hairs with that comment, and in any case you're right that the address here should be in the path. What I meant is that neither ipv4 or ipv6 schemes are listed with IANA https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml, and I didn't find another reference for them. In `ipv6:[::1]:80`, there is no authority specified, and if I understand things correctly, the meaning of a URI with a missing authority is scheme-specific (for example with `http`, a missing authority makes it an invalid URI altogether. With the `file` scheme, it's implicitly localhost).
</blockquote></details>

Okay.  I would have said that as "Because we are using some custom URI schemes", not that our URIs are non-standard-compliant.

It's true that the question of whether authority is optional depends on the scheme.  But that's equally true of path, query params, and fragment -- i.e., the URI scheme actually defines the constraints for *all* of the remaining parts of the URI.  But for all schemes, the overall parsing of the basic parts defined in RFC-3986 are still the same, which is why we can have a URL parser class that doesn't know anything about individual schemes.

**Review by yihuazhang — APPROVED** [review]
Thanks for the change, and LGTM from the security perspective. Let's wait and see if it passes all e2e tests using local credentials.

**Comment by drfloob** [comment]
Thanks! All the e2e tests here are green. I also ran a presubmit internally and all looks good. Merging.

**Pull request merged**
