### PR TITLE
RBE: rely on labels to select the right worker pool (instead of hardcoding GCE machine types)

### PR DESCRIPTION
**Pull request by jtattermusch**
Motivation: we want to switch our RBE worker pools from n1 instances to e2 instances. The problem is that currently our RBE configuration relies on hardcoded machine types (e.g. `n1-standard-8`) to determine on which worker pool should a given test run (there are 2 linux pools, one with 8core "large" machines and one with 2core "small" machines; there is also a windows pool. Tests need to run on the right pools to avoid unexpected failures.

Challenges:
- currently our bazel toolchain we're using is too old to understand the concept of RBE worker pool labels (and we cannot upgrade our toolchain right now for unrelated reason and even if we could, we could not easily backport that to older release branches).
- we need a solution that is non-intrusive enough so we can backport it to older release branches if needed (remember that the older branches have the machine types "n1-standard-8" etc hardcoded in them so if we migrate our existing pools to e2, they will suddenly break).

This PR represents an approach that seems to work and that would allow us to switch our existing worker pools to e2 instances seamlessly without breaking the world (and it can be backported to older branches as needed).

### CODE REVIEW

**Comment by jtattermusch** [comment]
@rubensf feel free to review the workaround I used for setting the RBE worker pool labels. I know it's a bit dirty, but it seems to work just fine and considering the challenges I mentioned in the PR description I think it's actually a pretty clever solution to solve the problem we're having (and to expedite the E2 migration).

**Review by rubensf — COMMENTED** [review]
LGTM - this should work fine! Thanks for looking into this :+1:

**Review by gnossen — APPROVED** [review]
Very clever workaround! :+1:

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/24375

**Pull request merged**
