### PR TITLE
Fake transport security to private

### PR DESCRIPTION
**Pull request by yang-g**
Sending out to see the test results in various languages.

### CODE REVIEW

**Comment by yang-g** [comment]
@stanley-cheung @murgatroid99 @soltanmm Please take a look. I pretty much just deleted the fake credentials related pieces (except node and c++ where I fixed tests).

**Comment by murgatroid99** [comment]
Node changes LGTM. PHP too

**Comment by yang-g** [comment]
@soltanmm @nathanielmanistaatgoogle wants to take a look? I basically removed everything related to fake credentials in python.

**Comment by yang-g** [comment]
Fixes #2591

**Comment by nathanielmanistaatgoogle** [comment]
LGTM but @soltanmm will also review.

**Comment by jboeuf** [comment]
LGTM. Will merge when @soltanmm gives the green light.

**Comment by soltanmm** [comment]
LGTM. Color me pleasantly surprised that the Cython code was kept up to date!

**Pull request merged**
