### PR TITLE
[tls] Add copy constructor for TlsCredentialsOptions

### PR DESCRIPTION
**Pull request by dawidcha**

### CODE REVIEW

**Comment by yashykt** [comment]
cc @veblush

**Comment by matthewstevenson88** [comment]
Thanks for the PR @dawidcha and apologies for the delay in getting this reviewed. The change looks great, will approve once all of the tests are passing. :)

**Comment by veblush** [comment]
Other than clang_format error, others don't look relevant to this PR. Please rebase it into the master and fix the clang-format issue by running `tools/distrib/clang_format_code.sh`

**Comment by dawidcha** [comment]
@veblush @matthewstevenson88 
Rebased onto master and fixed clang format as requested

**Review by matthewstevenson88 — APPROVED** [review]

**Pull request closed without merging**
