### PR TITLE
PHP: attempt to fix bug

### PR DESCRIPTION
**Pull request by thinkerou**
ref #12697

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by stanley-cheung** [comment]
Ok to test

**Comment by ZhouyihaiDing** [comment]
known issue:
gRPC_interop_pull_requests: #10763

**Comment by ZhouyihaiDing** [comment]
gRPC_interop_pull_requests: #10763

**Pull request merged**
