### PR TITLE
Fixing timeout test for tsan and asan:

### PR DESCRIPTION
**Pull request by donnadionne**
A previous fix which changed grpc_cycle_counter_to_millis_round_down/up
was not the correct fix and caused window test issues.

The correct fix is to ensure the test uses the same time apis as the
product code: grp_get_cycle_counter (which is platform dependent) to get
current time.

Tested both in open source and patched into google3 to ensure successful
import:
https://critique-ng.corp.google.com/cl/349981071/analysis

### CODE REVIEW

**Comment by markdroth** [comment]
This fix seems reasonable on its own, but I'd like to understand why the previous approach didn't work.  It seems like this fixes the  problem for this one specific test but does not address the weird behavior that differentiates the two different time APIs, which means that other tests may run into this in the future.  Is there really no way we can fix this in the general case?

**Comment by donnadionne** [comment]
My original change unfortunately didn't really fix any problem: it was not using g_start_time directly but it called an API that used it under the hood.  

Not only that, it seems that the change caused a problem on window platform.  I realized the issue with the original change while investigating the window problem.  So that change should be abondoned.

My current fix is to write the test to use the same API used in exec_ctx and this will ensure tests consistently pass on all platforms.

While I still think it can be a problem to use g_start_time which calls gpr_now(),  I can work on that separately (maybe during fix it?)

**Comment by donnadionne** [comment]
I should mention that the test change is always needed to use the same APIs in exec_ctx and will not be impacted if those APIs later change to avoid using g_start_time

**Review by markdroth — APPROVED** [review]
Okay.  I'm not really comfortable with the fact that we're working around the underlying problem instead of really fixing it, but I don't want the perfect to be the enemy of the good -- this PR is clearly an improvement to the status quo.  So let's get this merged, and please take an AI to find a better solution to the underlying problem, maybe during the fixit.

Thanks!

**Pull request merged**
