### PR TITLE
[PSM Interop] Enable affinity_session_drain_test for cpp

### PR DESCRIPTION
**Pull request by sergiitk**
Add `gamma.affinity_session_drain_test` to `grpc/core/master/linux/psm-csm` test suite.

### CODE REVIEW

**Comment by sergiitk** [comment]
Only drain test:
- [x] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/08c460bb-ff2b-4926-b556-0bfc35b37d5e)

All CSM tests:
- [ ] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/15749352-1ee6-463f-84bd-881c9515077a)

**Comment by sergiitk** [comment]
Should be merged after https://github.com/grpc/psm-interop/pull/34 goes in.

**Comment by sergiitk** [comment]
Only draining:
- [x] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/568a6863-0847-43be-893c-bbfd79975327)

All CSM:
- [x] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/f7ea8785-a95e-4893-9025-bfb4bdfe470a)

Other tests - verify no regressions:
- [x] [grpc/core/v1.62.x/branch/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/0de5a32d-cfc8-4c0b-b82c-15a9f13174d1)
- [x] [grpc/core/v1.62.x/branch/linux/psm-security](https://source.cloud.google.com/results/invocations/7055817a-41c0-4587-9b25-2db2a5ee50c6)
- [x] [grpc/core/v1.62.x/branch/linux/grpc_xds_url_map](https://source.cloud.google.com/results/invocations/dc3eaf67-f320-4c17-9a06-1d8e94543929)

**Comment by sergiitk** [comment]
Ready to be merged.

**Review by gnossen — APPROVED** [review]

**Comment by sergiitk** [comment]
Rebased against latest master to fix the issue with false-negative sanity tests.

**Pull request closed without merging**
