### PR TITLE
[ruby] Fix compilation errors on clang 16

### PR DESCRIPTION
**Pull request by stanhu**
As announced in https://discourse.llvm.org/t/clang-16-notice-of-potentially-breaking-changes/65562, clang 16 defaults `-Wincompatible-function-pointer-types` to be on. This causes a number of hard errors due to implicit conversions between `void *` and `void`, such as:

```
../../../../src/ruby/ext/grpc/rb_channel.c:770:47: error: incompatible function pointer types passing 'VALUE (VALUE)' (aka 'unsigned long (unsigned long)') to parameter of type 'VALUE (*)(void *)' (aka 'unsigned long (*)(void *)') [-Wincompatible-function-pointer-types]
  g_channel_polling_thread = rb_thread_create(run_poll_channels_loop, NULL);
                                              ^~~~~~~~~~~~~~~~~~~~~~
/root/.rbenv/versions/3.1.4/include/ruby-3.1.0/ruby/internal/intern/thread.h:190:32: note: passing argument to parameter 'f' here
VALUE rb_thread_create(VALUE (*f)(void *g), void *g);
                               ^
../../../../src/ruby/ext/grpc/rb_channel.c:780:41: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
void grpc_rb_channel_polling_thread_stop() {
                                        ^
                                         void
../../../../src/ruby/ext/grpc/rb_channel.c:786:30: error: incompatible function pointer types passing 'void (void *)' to parameter of type 'void *(*)(void *)' [-Wincompatible-function-pointer-types]
  rb_thread_call_without_gvl(run_poll_channels_loop_unblocking_func, NULL, NULL,
```

This commit fixes these pointer types using wrapper functions where necessary.

This issue was also raised on the FreeBSD port of the grpc gem: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271540

### CODE REVIEW

**Comment by stanhu** [comment]
@alto-ruby @veblush Homebrew users of `clang` 16 found that `grpc` fails to build without this change. I see that https://github.com/grpc/grpc/pull/32920 adds CI support for `clang` 16.

**Review by alto-ruby — APPROVED** [review]

**Comment by alto-ruby** [comment]
LGTM.
@apolcyn could you take a look as well?
@stanhu thanks for the PR, could you rebase to the latest master?

**Comment by alto-ruby** [comment]
Sanity checks failed with formatting errors: https://source.cloud.google.com/results/invocations/8143196f-0e53-4d33-a1a6-63577c48f97a/targets/github%2Fgrpc%2Frun_tests%2Fsanity_linux_dbg_native%2Ftools%2Fdistrib%2Fclang_format_code.sh/tests

**Comment by alto-ruby** [comment]
ping @apolcyn

**Comment by HannahShiSFB** [comment]
@sampajano Hi Eryu, could you help me check the "import/copybara Pending" status? Thanks a lot!

**Comment by sampajano** [comment]
@HannahShiSFB Thanks for checking! I've approved the internal merge request and will find one more reviewer to approve too (2 is required)!

**Pull request closed without merging**
