### PR TITLE
Initialize variable.

### PR DESCRIPTION
**Pull request by yang-g**
Note we check res != NULL at line 145 and try to destroy it if tested true, while error is not checked.
If there is error in resolve_address, we have a potential memory corruption.

### CODE REVIEW

**Comment by dgquintas** [comment]
LGTM.

**Comment by yang-g** [comment]
Added another one :(

**Comment by dgquintas** [comment]
I'm thinking about running a grep for it with an evil regexp...

**Comment by dgquintas** [comment]
still LGTM

**Comment by jcanizales** [comment]
How can we make these tests, in their state before this PR, fail on Jenkins?

**Comment by dgquintas** [comment]
Some compilers warn about it. Some are smarter than others about it, in
terms of warning only if the variable would be used before being
initialized vs if it's not initialized when declared.

I'm thinking about adding a linter test to check for this. Basically
pointer declarations without a "=" in the declaration line.

**Comment by yang-g** [comment]
I would expect msan or asan can catch these, but somehow they did not.

**Comment by dgquintas** [comment]
tests are like "nope"

**Comment by yang-g** [comment]
test this please

**Comment by yang-g** [comment]
Seems green

**Pull request merged**
