### PR TITLE
Migrate Infrastructure Scripts to Python 3

### PR DESCRIPTION
**Pull request by gnossen**
Flip the switch on Python 3 in infra tooling.

### CODE REVIEW

**Review by veblush — APPROVED** [review]
Thanks for taking care of this!

**Review by jtattermusch — APPROVED** [review]
LGTM, but I think you should wait with the merge until the v1.42.x release branch is cut (since this PR has high potential for breaking stuff that's going to be hard to backport and there is already enough last minute fixes around the release)

CC @markdroth as the release manager.

**Comment by jtattermusch** [comment]
Is there anything that's still preventing this PR from being merged?
If no, let's proceed.

**Comment by jtattermusch** [comment]
The macos Basictests C/++ macos is a test flake, not related to this PR: https://source.cloud.google.com/results/invocations/7b6518af-80fe-4849-bbcf-e87825ed5296/targets/github%2Fgrpc%2Frun_tests%2Fc_macos_dbg_native/tests

Not sure what's up with the iOS Binary size diff (it's a tool failure), but also doesn't look like anything related to this PR.

Can we merge now?

**Comment by gnossen** [comment]
Basic Tests C/C++ MacOS and iOS binary size diff were both non-Python-related failures. Going ahead and merging.

**Pull request merged**
