### PR TITLE
Remove Python alpha code generation

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
Happy New Year to us. :-)

### CODE REVIEW

**Comment by soltanmm** [comment]
Woo! Now to chuck out ye olde runtime.

(C `tsan` failures are unrelated)

**Comment by GuoJing** [comment]
Glad to hear that. :)

**Comment by ctiller** [comment]
Sanity checks are failing at master (out of date copyrights).

**Comment by nathanielmanistaatgoogle** [comment]
Copyright dates updated in #4759.

@soltanmm did you see sanity failures associated with this pull request or only the `tsan` failures you mentioned?

**Comment by soltanmm** [comment]
I don't recall seeing sanity failures associated with this PR. :-/

**Pull request merged**
