### PR TITLE
Add C# distribtest for alpine linux

### PR DESCRIPTION
**Pull request by jtattermusch**
Add alpine 3.9 C# distribtest - a workaround mentioned here https://github.com/grpc/grpc/issues/18428#issuecomment-535041155 is necessary, but at least it things work with it.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,020,494      Total (=)      2,020,494

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,175,630      Total (<)     11,175,633

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Let's leave this open.

**Comment by jtattermusch** [comment]
This is blocked because as of now `protoc` binary cannot run on alpine linux.

**Comment by jtattermusch** [comment]
Added a workaround that makes both protoc and grpc work fine on Alpine 3.9 - it's worth adding a test to avoid further regressions.

**Comment by jtattermusch** [comment]
Adhoc distribtest run: https://sponge.corp.google.com/invocation?id=51a25ff8-e1bb-467a-8efc-4f1e6326f131&searchFor=

**Comment by jtattermusch** [comment]
The C# distribtests are green:
https://source.cloud.google.com/results/invocations/1b7ff29a-d440-4fa8-9b20-b50bb607b9d0/targets/github%2Fgrpc/tests

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/20425
https://github.com/grpc/grpc/issues/20421

**Pull request merged**
