### PR TITLE
Fix stream compression transport duplicate

### PR DESCRIPTION
**Pull request by muxi**
* Add `identity` stream compression module as passthrough.
* Eliminate multiple duplicated code paths in chttp2 trasport.

### CODE REVIEW

**Comment by ctiller** [comment]
Jenkins test this please

**Comment by muxi** [comment]
@ctiller Request review

**Comment by muxi** [comment]
@ctiller ping for review :)

**Comment by muxi** [comment]
Test failures:
Asan C - #12245 
Basic Tests C++ Linux [dbg] (internal CI) - #12510 
Basic Tests C++ Linux [opt] (internal CI) - #12428 
Basic Tests Linux (dbg) - #11205 
Basic Tests Linux (opt) - #11205 
Basic Tests Mac - #12138 
Basic Tests MacOS [dbg] (internal CI) - #12138, #12538 
Basic Tests MacOS [opt] (internal CI) - #12138, #12538 
Basic Tests Windows - #12687
Basic Tests Windows (internal CI) -  #12595 
Portability Tests Linux - #12657 
Portability Tests Linux [Build Only] (internal CI) - #12657 
Tsan C (internal CI) - #12688
gRPC_interop_pull_requests - #12518

**Pull request merged**
