### PR TITLE
Fix-forward "Added portability test with openssl 1.0.2"

### PR DESCRIPTION
**Pull request by veblush**
Fix foward https://github.com/grpc/grpc/pull/25770
Reverts grpc/grpc#25812

Fixes https://github.com/grpc/grpc/issues/24960

### CODE REVIEW

**Comment by matthewstevenson88** [comment]
@veblush I think this still might fail - in #25843 I only fixed the errors for ssl_transport_security_test, but there are still errors for client_ssl_test and server_ssl_test that I'm still trying to sort out.

**Comment by veblush** [comment]
[grpc/core/master/linux/grpc_portability](https://fusion2.corp.google.com/invocations/c6f41043-7c8f-4d88-8219-21ca36b35344/targets): running

**Comment by veblush** [comment]
[grpc/core/master/linux/grpc_portability](https://fusion2.corp.google.com/invocations/6bb80b3a-3d8d-4339-905a-a4a7df743271): running

**Comment by matthewstevenson88** [comment]
Seems like the portability test ran into a `DEADLINE_EXCEEDED` error - could we try re-running it?

While we're at it, could we rerun the presubmit checks to make sure that the `Artifact Build MacOS` and `Basic Tests Python Windows` failures are unrelated flakes? (That seems to be the case from looking at logs.)

**Comment by veblush** [comment]
Yeah, it didn't manage to get a change to run the test due to timeout in the queue. Let's rerun the test.
[linux/grpc_portability](https://fusion2.corp.google.com/invocations/1416c34c-599d-4b1f-8c7a-33b56108f6ee/targets): running

**Comment by matthewstevenson88** [comment]
Looks like the portability test failed in the same way again - should we just keep re-running it until it passes?

**Review by jtattermusch — APPROVED** [review]
LGTM.

**Comment by veblush** [comment]
It seems that it's hard to trigger grpc_portability manually only for this PR. One more try

[prod:grpc/core/master/linux/grpc_portability](https://fusion2.corp.google.com/invocations/3464dbce-c2a5-4c29-9422-d5482f4f2888/targets)

**Review by matthewstevenson88 — APPROVED** [review]
If we're not able to run the portability test without merging the PR, that won't be the end of the world, since we're just adding a new test and not modifying existing ones.

**Comment by veblush** [comment]
Wow finally it passed! It's all set to get merged!

**Pull request merged**
