### PR TITLE
Partial revert of vsprojects removal

### PR DESCRIPTION
**Pull request by jtattermusch**
Partially reverts #11598 
-- bring back the vcxproj generation and sanity check that they are up-to-date to allow friction-less debugging without need to install more dependencies.
-- does not revert changes to building artifacts and the test suites we are running (e.g. kokoro will still test the cmake-built vsprojects) - an alternative would be to add build-only test to portability suite to ensure the vsprojects stay buildable.

Reverting mostly to make sure we don't delay critical development on C core.  The expectations is the pre-generated vsprojects will be removed again at some point.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by jtattermusch** [comment]
I rebased and regenerated and tried building the vcxprojects.

It currently doesn't build as there are bunch of warnings treated as errors in the new C++ code.
Given that things compile under cmake, is it likely that all of these are fixable if we really needed the vcxprojects back.
Closing this PR for now, feel free to reopen if I should give it a try to make it work.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\client_channel\lb_policy\round_robin\round_robin.cc	200	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\client_channel\lb_policy\grpclb\grpclb.cc	676	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\client_channel\client_channel.cc	1122	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\http\message_compress\message_compress_filter.cc	244	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\hpack_parser.cc	1565	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc	450	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\debug\trace.cc	123	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\iomgr\error_internal.h	59	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\transport\bdp_estimator.cc	37	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\iomgr\iocp_windows.cc	53	
Error	C2220	warning treated as error - no 'object' file generated	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\iomgr\error_internal.h	59	
Error	C2220	warning treated as error - no 'object' file generated	grpc++	c:\users\jtattermusch\github\grpc\include\grpc++\impl\codegen\async_stream.h	453	
Error	C2220	warning treated as error - no 'object' file generated	grpc++	c:\users\jtattermusch\github\grpc\src\cpp\client\channel_cc.cc	226	
Warning	C4200	nonstandard extension used: zero-sized array in struct/union	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\iomgr\error_internal.h	59	
Warning	C4200	nonstandard extension used: zero-sized array in struct/union	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\iomgr\error_internal.h	59	
Warning	C4291	'void *operator new(std::size_t,void *) throw()': no matching operator delete found; memory will not be freed if initialization throws an exception	grpc++	c:\users\jtattermusch\github\grpc\include\grpc++\impl\codegen\async_stream.h	453	
Warning	C4291	'void *grpc::ClientAsyncResponseReader<grpc::ByteBuffer>::operator new(std::size_t,void *)': no matching operator delete found; memory will not be freed if initialization throws an exception	grpc++	c:\users\jtattermusch\github\grpc\include\grpc++\impl\codegen\async_unary_call.h	93	
Warning	C4800	'uint8_t': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc	1383	
Warning	C4800	'uint8_t': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc	1387	
Warning	C4800	'uint32_t': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\client_channel\client_channel.cc	1122	
Warning	C4800	'uint32_t': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc	474	
Warning	C4800	'uint32_t': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc	2614	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\client_channel\lb_policy\round_robin\round_robin.cc	200	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\client_channel\lb_policy\grpclb\grpclb.cc	676	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\client_channel\client_channel.cc	1144	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\filters\http\message_compress\message_compress_filter.cc	244	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\hpack_parser.cc	1565	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\hpack_parser.cc	1578	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc	450	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\debug\trace.cc	123	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\debug\trace.cc	130	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\debug\trace.cc	137	
Warning	C4800	'int': forcing value to bool 'true' or 'false' (performance warning)	grpc++	c:\users\jtattermusch\github\grpc\src\cpp\client\channel_cc.cc	226	
Warning	C4018	'>': signed/unsigned mismatch	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\iomgr\iocp_windows.cc	53	
Warning	C4244	'=': conversion from 'double' to 'int', possible loss of data	grpc	c:\users\jtattermusch\github\grpc\src\core\lib\transport\bdp_estimator.cc	37	
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_InProcessCHTTP2_NoOpMutator_NoOpMutator__2M_2_0.opt.new: 1
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongWithCoalescingApi_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__2M_1_0.counters.old: 1


[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
