### PR TITLE
Revert "Simplify LB policy refcounting."

### PR DESCRIPTION
**Pull request by yashykt**
Reverts grpc/grpc#13857
TAP test //net/grpc/testing/interop/lb_integration_tests:grpclb_fallback_test_cpp has been continuously timing out

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                              FILE SIZE
 ++++++++++++++ GROWING                                                                ++++++++++++++
  +0.1%    +688 [None]                                                                 +6.94Ki  +0.1%
  +6.8%    +944 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc            +944  +6.8%
      [NEW] +1.57Ki rr_handover_locked(glb_lb_policy*) [clone .part.8]                     +1.57Ki  [NEW]
      [NEW] +1.36Ki query_for_backends_locked(glb_lb_policy*) [clone .part.11]             +1.36Ki  [NEW]
      [NEW]    +708 glb_pick_locked                                                           +708  [NEW]
      [NEW]    +693 pick_from_internal_rr_locked                                              +693  [NEW]
      [NEW]    +590 glb_shutdown_locked                                                       +590  [NEW]
      [NEW]    +433 wrapped_rr_closure                                                        +433  [NEW]
      [NEW]    +314 glb_cancel_pick_locked                                                    +314  [NEW]
      [NEW]    +150 add_pending_pick                                                          +150  [NEW]
      +124%    +134 glb_ping_one_locked                                                       +134  +124%
      [NEW]    +119 glb_rr_connectivity_changed_locked                                        +119  [NEW]
      [NEW]    +113 initial_metadata_add_lb_token                                             +113  [NEW]
       +13%     +48 [Unmapped]                                                                 +48   +13%
   +29%    +144 src/core/ext/filters/client_channel/lb_policy.cc                          +144   +29%
      [NEW]     +60 grpc_lb_policy_weak_unref                                                  +60  [NEW]
       +76%     +51 grpc_lb_policy_unref                                                       +51   +76%
       +15%     +19 [Unmapped]                                                                 +19   +15%
      [NEW]     +19 shutdown_locked                                                            +19  [NEW]
      [NEW]      +7 grpc_lb_policy_weak_ref                                                     +7  [NEW]
      [NEW]      +6 grpc_lb_policy_pick_locked                                                  +6  [NEW]
      [NEW]      +6 grpc_lb_policy_cancel_pick_locked                                           +6  [NEW]
       +11%      +1 grpc_lb_policy_ref                                                          +1   +11%
  +0.8%    +112 src/core/ext/filters/client_channel/client_channel.cc                     +112  +0.8%
       +86%     +74 pick_callback_done_locked                                                  +74   +86%
      +9.3%     +61 pick_callback_start_locked                                                 +61  +9.3%
       +19%     +59 cc_destroy_call_elem                                                       +59   +19%
      +0.7%      +1 pick_callback_cancel_locked                                                 +1  +0.7%

 -------------- SHRINKING                                                              --------------
  -1.9%     -96 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc     -96  -1.9%
      [DEL]    -481 pf_shutdown_locked                                                        -481  [DEL]
      [DEL]    -274 pf_cancel_pick_locked                                                     -274  [DEL]
      [DEL]    -103 pf_pick_locked                                                            -103  [DEL]
     -24.5%     -34 [Unmapped]                                                                 -34 -24.5%
      -1.0%     -16 pf_connectivity_changed_locked                                             -16  -1.0%
      -1.0%      -3 pf_cancel_picks_locked                                                      -3  -1.0%

  +0.1% +1.75Ki TOTAL                                                                  +8.02Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by dgquintas** [comment]
Please specify the reason for reverts in the description.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark                                                        call_initial_size-median
---------------------------------------------------------------  --------------------------
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/1       -7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/1       -7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/262144/1  -4%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/32768/1   -7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/4096/1    -7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/1     -7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/1      -7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/1       -7%
```

**Pull request merged**
