### PR TITLE
Use test roots.pem in test

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by dgquintas** [comment]
LGTM

**Comment by jcanizales** [comment]
Why wasn't this test failing?

**Comment by yang-g** [comment]
I think because in here we can load the default roots.pem which will also work.

**Comment by jcanizales** [comment]
Does it mean we can't have a test that would have caught it? :(

**Comment by yang-g** [comment]
I was trying to say this PR is not fixing a bug but is simply solving the issue where you cannot load a default roots.pem :)

**Comment by jcanizales** [comment]
> this PR is not fixing a bug

I disagree :) given that we block imports on these tests passing in environments where you cannot load a default roots.pem. This is a bug in the test, from that point of view.

**Comment by dgquintas** [comment]
sanity is failing

**Comment by yang-g** [comment]
green enough?

**Comment by dgquintas** [comment]
Sure.

**Pull request merged**
