### PR TITLE
Update comment

### PR DESCRIPTION
**Pull request by AspirinSJL**
Inspired by this user's [comment](https://github.com/grpc/grpc/issues/8363#issuecomment-360280024).

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by AspirinSJL** [comment]
@yetianx Looks like GitHub can't show your new ID when I search for it. So I'm requesting your review in this comment. Thanks!

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
The authoritative source of this proto in OSS is actually here:

https://github.com/grpc/grpc-proto/blob/master/grpc/lb/v1/load_balancer.proto

Let's update it there.  Then @dgquintas can handle merging the changes in here as part of #15728.

**Comment by AspirinSJL** [comment]
Closing this in favor of [the one in grpc-proto repo](https://github.com/grpc/grpc-proto/pull/27).

**Pull request closed without merging**
