### PR TITLE
Run tests refactoring

### PR DESCRIPTION
**Pull request by jtattermusch**
-- refactor run_tests.py
-- preparation for running run_tests.py with different dockerfiles for each language
-- improve handling of --arch parameter on linux (now autoselects x86 and x64 docker images)
-- move dockerfiles under tools/dockerfile

### CODE REVIEW

**Comment by jtattermusch** [comment]
Green enough.

**Comment by jtattermusch** [comment]
Rebased, but was green before: https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/5575/

**Comment by jtattermusch** [comment]
Copyright test failure is unrelated.

**Comment by jtattermusch** [comment]
Made this mergeable again.

**Comment by ctiller** [comment]
LGTM. Merge on green.

**Comment by jtattermusch** [comment]
Interop tests are broken for other reasons, everything is green (enough).

**Pull request merged**
