### PR TITLE
Fix Leaky Channelz Test

### PR DESCRIPTION
**Pull request by ncteisen**
This is (I think) actually a fix for #16211

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by yashykt** [comment]
Nope, doesn't work currently :)
What's the issue and the intended fix btw?

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,980,683      Total (=)      1,980,683

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,811,771      Total (>)     10,811,767

 No significant differences in binary sizes


```

**Comment by ncteisen** [comment]
I have no idea why this test is causing issues... it is sending a bunch of sync RPCs and that's it. Somehow that is triggering tsan race on Status dtor and sendmsg...

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request closed without merging**
