### PR TITLE
Fix test flake in flaky_network_test

### PR DESCRIPTION
**Pull request by rmstar**
Set channel arg for maximum time between reconnection attempts.

### CODE REVIEW

**Comment by jtattermusch** [comment]
How exactly this should help?

**Comment by rmstar** [comment]
@jtattermusch the failed testcase does the following:
1. Create channel, send an RPC over it.
2. Create iptables rule to drop traffic between client and server. The channel will transition to TRANSIENT_FAILURE state.
3. Wait 10 seconds. 
4. Remove iptables rule.
5. The test expects that the channel will move to READY state within 5 seconds, but the test logs indicate that it took 8 seconds to become READY. So the test failed.

Here's the test log from one of the failures:
```
I0222 23:22:58.694610655    5389 connectivity_state.cc:81]   CONWATCH: 0x2132010 client_channel: get CONNECTING
I0222 23:22:58.694708350    5389 connectivity_state.cc:116]  CONWATCH: 0x2132010 client_channel: from CONNECTING [cur=CONNECTING] notify=0x2129860
I0222 23:23:03.695592567    5423 connectivity_state.cc:113]  CONWATCH: 0x2132010 client_channel: unsubscribe notify=0x2129860
test/cpp/end2end/flaky_network_test.cc:371: Failure
Value of: WaitForChannelReady(channel.get())
  Actual: false
Expected: true
I0222 23:23:03.695928752    5389 connectivity_state.cc:81]   CONWATCH: 0x2132010 client_channel: get CONNECTING
test/cpp/end2end/flaky_network_test.cc:372: Failure
      Expected: channel->GetState(false)
      Which is: 1
To be equal to: GRPC_CHANNEL_READY
      Which is: 2
I0222 23:23:06.874881370    5426 connectivity_state.cc:116]  CONWATCH: 0x7fd47c000c10 server_transport: from IDLE [cur=READY] notify=0x7fd47c002bc8
I0222 23:23:06.874946554    5426 connectivity_state.cc:116]  CONWATCH: 0x7fd47c000c10 server_transport: from READY [cur=READY] notify=0x7fd47c002bc8
I0222 23:23:06.874884067    5427 subchannel.cc:1020]         New connected subchannel at 0x7fd488004b10 for subchannel 0x2171fc0
I0222 23:23:06.874988449    5427 connectivity_state.cc:164]  SET: 0x2172098 subchannel: CONNECTING --> READY [subchannel_connected] error=(nil) "No Error"
```
There are no log lines between 23:22:58 and 23:23:03. That's probably because the client was backing off during that time. Setting the max backoff interval in the channel arguments would ensure that the client reconnects quickly.

Links to some failures:
https://source.cloud.google.com/results/invocations/7ac76164-65b4-4cdf-a3a4-4a66e8823bdf/targets
https://source.cloud.google.com/results/invocations/7a86466a-5708-4d4d-9eaa-69f1f063550f/targets
https://source.cloud.google.com/results/invocations/091acaa8-132b-4b9d-9286-55f378f5f551/targets

**Comment by rmstar** [comment]
There a new test flake in FlakyNetworkTest.FlakyNetwork seen [here](https://source.cloud.google.com/results/invocations/7c5a0d67-391b-4bc3-8bd4-61f134bf33ef/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_flaky_network/log). 
Relevant snippet from the log:
```
D0227 08:15:42.787759519    5386 flaky_network_test.cc:217]  RPC failed: keepalive watchdog timeout
I0227 08:15:42.787776329    5467 connectivity_state.cc:164]  SET: 0x6a1ad8 subchannel: READY --> TRANSIENT_FAILURE [reflect_child] error=0x7f79e40008c0 {"created":"@1551255342.787595751","description":"Delayed close due to in-progress write","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":587,"referenced_errors":[{"created":"@1551255342.787564624","description":"keepalive watchdog timeout","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2781,"grpc_status":14}]}
I0227 08:15:42.787783124    5467 connectivity_state.cc:190]  NOTIFY: 0x6a1ad8 subchannel: 0x6a0a78
I0227 08:15:42.787789771    5467 connectivity_state.cc:164]  SET: 0x6a1af8 subchannel: READY --> TRANSIENT_FAILURE [reflect_child] error=0x7f79e40008c0 {"created":"@1551255342.787595751","description":"Delayed close due to in-progress write","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":587,"referenced_errors":[{"created":"@1551255342.787564624","description":"keepalive watchdog timeout","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2781,"grpc_status":14}]}
I0227 08:15:42.787808350    5467 resolving_lb_policy.cc:102] resolving_lb=0x69cac0: started name re-resolving
test/cpp/end2end/flaky_network_test.cc:424: Failure
Value of: SendRpc(stub)
  Actual: false
Expected: true
```
The testcase simulates packet loss and delays, which results in keepalives timing out. So the RPC fails. This is expected when the network connection is flaky. I have updated the test to not expect RPCs to be successful while the network is flaky.

**Comment by jtattermusch** [comment]
@rmstar I see, thanks for the explanation.

**Comment by rmstar** [comment]
cpp_macos_dbg_native failure: #15027

**Pull request merged**
