### PR TITLE
[xDS interop] Disable api_listener_test for older Python versions

### PR DESCRIPTION
**Pull request by lidizheng**
More context b/235145855.

Disabling the test until we have a more permanent solution.

### CODE REVIEW

**Comment by lidizheng** [comment]
Code version: v1.39.x (https://github.com/grpc/grpc/pull/29773)

Script version: this PR

https://fusion2.corp.google.com/invocations/11ed8e21-43c7-42f4-9d74-66e06f98ae08/targets

**Review by gnossen — APPROVED** [review]

**Comment by lidizheng** [comment]
Thanks for the quick review!

**Review by sergiitk — COMMENTED** [review]
👍

**Comment by YifeiZhuang** [comment]
Thank you. LGTM.

**Pull request merged**
