### PR TITLE
doc: remove outdated documentation on server reflection protocol

### PR DESCRIPTION
**Pull request by ericgribkoff**
Removing out-dated text that may be misleading to end-users. While the discussion contained useful information at a high-level about reflection and the choices faced in its design, the example proto definition and specific examples discussed (such as retrieving a list of all methods) did not end up existing in the `reflection.proto` that is actually being used for gRPC's reflection services, and could lead to confusion.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,980,683      Total (=)      1,980,683

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,811,763      Total (<)     10,811,769

 No significant differences in binary sizes


```

**Comment by jtattermusch** [comment]
Can we make the doc accurate instead of just deleting? We don't have that much publicly available info about server reflection and it seems that some of the statements in the existing doc are correct
(e.g.  reflection.proto uses a streaming RPC to get be able to get a consistent reflection info when the backend is behind a loadbalancer / reverse proxy).

**Comment by ericgribkoff** [comment]
@jtattermusch I took a pass and re-added the "Argument reflection" portions of the original doc, and updated the description of the protocol to match the reflection.proto file that we actually use. I won't have time to work on this again for quite some time due a planned OOO, but I think it's an improvement over the current doc in that some of the outdated/misleading information is removed.

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,025      Total (=)      1,955,025

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,752      Total (<)     10,843,760

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,025      Total (=)      1,955,025

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,753      Total (<)     10,843,758

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,025      Total (=)      1,955,025

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,746      Total (<)     10,843,747

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,025      Total (=)      1,955,025

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,754      Total (<)     10,843,757

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,025      Total (=)      1,955,025

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,755      Total (>)     10,843,751

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,955,025      Total (=)      1,955,025

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,843,753      Total (>)     10,843,751

 No significant differences in binary sizes


```

**Pull request closed without merging**
