### PR TITLE
[Comment fix] Add a verb in front of a bullet point comment

### PR DESCRIPTION
**Pull request by zhenk14**
@yashykt

### CODE REVIEW

**Review by yashykt — APPROVED** [review]

**Comment by yashykt** [comment]
Thanks for the contribution! Please sign the CLA

**Comment by zhenk14** [comment]
Signed. How can I let the CLA bot to pick it up?

**Review by drfloob — APPROVED** [review]

**Comment by yashykt** [comment]
Just re-read the comment `The commit (3839e36) is missing the User's ID`. That's what the CLA issue is

**Comment by yashykt** [comment]
@zhenk14 ping

**Comment by zhenk14** [comment]
Sry I didn't check my github frequently. Will do this now : )

**Comment by zhenk14** [comment]
Sorry yashykt, I tried to remove the first commit(the one without email) but failed... Do you know how to remove it from the PR?

**Comment by drfloob** [comment]
@zhenk14 try squashing your commits. `git rebase -i master` and mark all but the first commit as `fix`. Then push the branch.

**Pull request closed without merging**
