### PR TITLE
Bump v1.8.0-pre2 to v1.8.0

### PR DESCRIPTION
**Pull request by mehrdada**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++

 -------------- SHRINKING                    --------------
 -13.0%     -12 src/cpp/common/version_cc.cc     -12 -13.0%
     -26.1%     -12 grpc::Version[abi:cxx11]         -12 -26.1%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  +0.0%     +12 [None]                           -84  -0.0%

  [ = ]       0 TOTAL                            -96  -0.0%



```

**Comment by jtattermusch** [comment]
I think you need to update versions in BUILD file as well?

**Comment by mehrdada** [comment]
@jtattermusch doesn't generate_projects do it? I simply invoked that.

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++

 -------------- SHRINKING                    --------------
 -13.0%     -12 src/cpp/common/version_cc.cc     -12 -13.0%
     -26.1%     -12 grpc::Version[abi:cxx11]         -12 -26.1%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  +0.0%     +12 [None]                           -84  -0.0%

  [ = ]       0 TOTAL                            -96  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
