### PR TITLE
Some additional fixes to make the C++ codegen not depend on protobuf.

### PR DESCRIPTION
**Pull request by gwvo**
This allows the FlatBuffer code generator to use cpp_generator.cc/.h as-is.

### CODE REVIEW

**Comment by yang-g** [comment]
This is ok to test.

**Comment by gwvo** [comment]
Looking at the failed configuration, I only see:

    PASSED: tools/run_tests/post_tests_c.sh [time=0.0sec; retries=0:0]
    FAILED: Some tests failed

There's no other mention of `FAILED` anywhere else. Is this an actual problem, or an issue with the test setup?
If the latter, is there a better way to make this go green than touching my commit and trying again?

**Comment by gwvo** [comment]
And now it's failing on this, which it didn't fail on before, and doesn't appear to have anything to do with my PR:

    make: *** No rule to make target '/var/local/git/grpc/objs/dbg/third_party/boringssl/crypto/bytestring/asn1_compat.o', needed by '/var/local/git/grpc/libs/dbg/libboringssl.a'.  Stop.

**Comment by ctiller** [comment]
Looks like you changed the version of boringssl that we're pointing to inadvertently.

**Comment by gwvo** [comment]
No idea how that got in there :)

**Comment by ctiller** [comment]
We just moved version... you likely synced without doing a submodule update after.

**Comment by gwvo** [comment]
Different tests fail each time, "connection refused", etc. Seems flakey, but I may be missing something again. I'll keep re-triggering the tests I guess?

**Comment by ctiller** [comment]
There are some flakes currently

**Comment by yang-g** [comment]
LGTM

**Comment by yang-g** [comment]
Restarted tests.

**Pull request merged**
