### PR TITLE
Rename client_config directory to client_channel.

### PR DESCRIPTION
**Pull request by markdroth**
There are no code changes here, just a simple renaming of the directory and updating of the build files and `#include` lines.

### CODE REVIEW

**Comment by ctiller** [comment]
Please hold on this until we've gotten at least #8008 through an import cycle.

**Comment by markdroth** [comment]
Sure, I'm happy to hold off.  There's no rush on this.

**Comment by markdroth** [comment]
#8008 has been merged, so I'd like to move forward with this PR.

**Comment by dgquintas** [comment]
My previous approval still stands.

**Pull request merged**
