### PR TITLE
When seeing an error in interop test, also log the debug error string.

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by ncteisen** [comment]
Woo! first use of new debug_error_string API :)

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
Test failure: #13148

**Pull request merged**
