### PR TITLE
Node distribtest fixes

### PR DESCRIPTION
**Pull request by jtattermusch**
Some node distribtests were still complaining about nvm not being available.

### CODE REVIEW

**Comment by jtattermusch** [comment]
@ctiller FYI

**Comment by jtattermusch** [comment]
```
FAILED: distribtest.node_npm_linux_x86_jessie_4 [ret=1, pid=10758]
PASSED: distribtest.node_npm_linux_x64_wheezy_0.10 [time=18.2sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_wheezy_3 [time=20.1sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_wheezy_0.12 [time=20.3sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_wheezy_4 [time=14.5sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_jessie_0.10 [time=15.0sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_jessie_0.12 [time=20.5sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_jessie_3 [time=18.8sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_wheezy_5 [time=26.4sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_jessie_4 [time=15.9sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1204_0.10 [time=15.6sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1204_0.12 [time=21.7sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_jessie_5 [time=26.6sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1204_3 [time=18.5sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1204_4 [time=15.3sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1404_0.10 [time=14.8sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1404_0.12 [time=20.0sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1204_5 [time=24.9sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1404_3 [time=18.3sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1404_4 [time=15.4sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1504_0.10 [time=17.1sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1504_0.12 [time=18.0sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1504_3 [time=16.5sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1404_5 [time=26.2sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1504_4 [time=14.5sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1510_0.10 [time=15.2sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1504_5 [time=23.7sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1510_0.12 [time=18.2sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1510_3 [time=16.6sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1510_4 [time=17.1sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1604_0.10 [time=16.1sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1510_5 [time=24.6sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1604_0.12 [time=19.4sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1604_3 [time=17.8sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1604_4 [time=15.0sec; retries=0:0]
PASSED: distribtest.node_npm_linux_x64_ubuntu1604_5 [time=23.8sec; retries=0:0]
```

**Comment by jtattermusch** [comment]
node_npm_linux_x86_jessie_4 is still failing because of
```
+ npm install -g node-static
test/distrib/node/run_distrib_test.sh: line 42: npm: command not found
```

**Comment by murgatroid99** [comment]
I'm not sure about that last change. That just means that the `npm` available won't be associated with the version of node we're trying to test.

**Comment by jtattermusch** [comment]
Ok, reverted the npm installation trick for x86. PTAL.

**Pull request merged**
