### PR TITLE
Revert "Metadata handling rewrite"

### PR DESCRIPTION
**Pull request by ctiller**
Reverts grpc/grpc#8842

### CODE REVIEW

**Comment by ctiller** [comment]
Nico: this broke too much, please LGTM and merge

**Comment by ctiller** [comment]
Scratch that. #9430 was merged which probably makes this unsafe.

Jenkins: test this please.

**Comment by muxi** [comment]
I would not mind reverting #9430 too if you want.

**Comment by ctiller** [comment]
Let's check in the morning.

Currently there's a fuzzing detected failure I'm trying to fix in #9432, and a severe concurrency regression that I need to root cause, and whatever is going on with Python (but I'm fairly certain that's not #8842).

@sreecha - in case you get to it first, can you run mutrace against head and see what it shows up?
@nathanielmanistaatgoogle - can you figure out what happened with yapf and any Python flakes
@dgquintas - can you run point and make a call on rolling forward or back?

That should let me figure out the last of the fuzzer-found defects

**Comment by dgquintas** [comment]
I'd say rollback both #8842 (via this PR) PR and #9430. Given that there are known issues with #8842, we don't want to have code committed that depends on it.

I'll bisect the concurrency regression. @ctiller is there any test triggering it?

@muxi Can you go ahead and rollback #9430. Please add me as reviewer.

**Comment by ctiller** [comment]
Also note that this seems to apply cleanly without reverting #9430, so we could just leave that in place

**Comment by dgquintas** [comment]
#9430 looks like a general fix that indeed doesn't depend on #8842. @muxi can you confirm?

**Comment by ctiller** [comment]
I'm going to start looking at concurrency problems (fuzzing failures are fixed in #9432)
I've pushed out a re-forward PR #9444 where I'll be accumulating all the fixes required to get #8842 back in.

**Comment by dgquintas** [comment]
Giving @muxi some time to update, but otherwise I'll be merging this in about an hour, at 9am PST.

**Comment by dgquintas** [comment]
@ctiller can you approve? Probably not, as the author... who else is up. @markdroth ? I'd like to merge this (ie, rollback) asap.

**Comment by ctiller** [comment]
You can approve @dgquintas

**Comment by muxi** [comment]
#9430  is dependent on #8842. If we are not using grpc_slice_to_c_string in the function convert_metadata_to_cronet_headers will not need to free them.

**Comment by dgquintas** [comment]
@ctiller sigh, yes, indeed...

**Comment by dgquintas** [comment]
Waiting on tests for https://github.com/grpc/grpc/pull/9446. It'll then be merged, followed by this one.

**Comment by dgquintas** [comment]
Known issues: #9124 and #9437

**Pull request merged**
