### PR TITLE
Remove unnecessary initialization of fields in PickState.

### PR DESCRIPTION
**Pull request by markdroth**
I think we missed this in #16944.

### CODE REVIEW

**Comment by soheilhy** [comment]
nice!

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                             FILE SIZE
 ++++++++++++++ GROWING                                               ++++++++++++++
  +0.0%     +16 src/core/ext/filters/client_channel/client_channel.cc     +16  +0.0%
      +1.0%     +16 start_transport_op_locked                                 +16  +1.0%

 -------------- SHRINKING                                             --------------
  -0.0%     -16 [None]                                                   -152  -0.0%

  [ = ]       0 TOTAL                                                    -136  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,676      Total (=)      2,019,676

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,188      Total (=)     11,154,188

 No significant differences in binary sizes


```

**Comment by markdroth** [comment]
Known issues: #16585 

The "Basic Tests Windows [opt] (internal CI)" test is still pending, but it looks like there's some sort of backlog in kokoro, so I'm not going wait for it.

**Pull request merged**
