### PR TITLE
Add a maybe-temporary way for apps to clear the channel cache

### PR DESCRIPTION
**Pull request by jcanizales**
This serves two immediate purposes while other longer-term solutions are done:

* Some cases the connectivity monitoring in ObjC cannot detect (like, e.g., a socket was open on the WiFi interface, and now even though the server is still reachable, it is only via the cell interface). With this feature, an app that faces such a problem can set a tight timeout, and force the library to create a new connection after receiving the timeout.

* It lets apps flush the connections cache when going to the background, which is a way to alleviate #3076. (Thanks for debugging, @juxingzhutou!). Until we investigate if the C library can be made aware of sockets killed by the OS while in the background, this lets apps work around the problem manually.

To expedite it, I just created a method for this without iterating on the API, and marked it as experimental to let us evolve it later on (or remove it) if necessary.

FYI: @pranay, @timburks

### CODE REVIEW

**Comment by makdharma** [comment]
How about adding a test to exercise this functionality?

**Comment by jcanizales** [comment]
I've added a test that makes an RPC, closes open connections, and makes a second RPC. It checks that both of them succeed.

**Comment by makdharma** [comment]
@jcanizales Is this relevant anymore? LGTM in any case.

**Comment by makdharma** [comment]
Test this please

**Comment by jcanizales** [comment]
It's been needed by @pranay since end of April, so yeah :)

**Comment by jcanizales** [comment]
I'm going to merge master into it to manually solve the conflicts that have accumulated since.

**Comment by jcanizales** [comment]
Tests pass now (modulo flakes).

**Pull request merged**
