### PR TITLE
Bump Bazel Cython dependency

### PR DESCRIPTION
**Pull request by gnossen**
A breaking C-level API change was made in Python 3.9 which old versions
of Cython cannot handle. Since Bazel prescribes a single version of
dependency instead of ranges, like in setuptools, we must update this to
keep our downstream users working properly.

As a side note, since it was a point of confusion while debugging this,
interpreter versions installed by pyenv must be set *globally* rather
than just locally for Bazel to pick them up, since local pyenv
configuration will not be picked up from within the sandbox.

### CODE REVIEW

**Review by lidizheng — APPROVED** [review]
LGTM. The build failure seems unrelated.

`pyenv` doesn't work well with Bazel. To prevent myself from confusing Python versions between Bazel builds, I completely removed `pyenv` and only keep one `python3`...

**Comment by gnossen** [comment]
@lidizheng Once I switched from `pyenv local` to `pyenv global`, things seemed to work just fine. Have you had problems using `pyenv global`?

Failures:
 - [Bazel Basic Build](https://github.com/grpc/grpc/pull/25228)
 - [Interop ALTS Test](https://github.com/grpc/grpc/issues/25236)

**Comment by lidizheng** [comment]
I didn't encounter issues with `pyenv global` specifically. But switching Python versions could lead to weird Bazel build failures, and requires to run `bazel clean --expunge`.

**Comment by gnossen** [comment]
That's true. But from my perspective, it beats the alternative of trying to reinstall my system-level Python interpreter.

**Comment by gnossen** [comment]
Failures:
 - Basic Tests Python MacOS - Infra Flake (but the test passed before my commit merging master in)
 - Basic Tests Python Windows - Infra Flake (but the test passed before my commit merging master in)
 - [ALTS Interop](https://github.com/grpc/grpc/issues/25242)

**Pull request merged**
