### PR TITLE
NACK xDS updates when certificate provider instace names are unrecognized

### PR DESCRIPTION
**Pull request by yashykt**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/26614)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
Thanks for doing this!

Please let me know if you have any questions.  Thanks!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26614#-:-Me0rcEh4fY1ioGgEypl:b-pevjuw)* status: all files reviewed, 5 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/certificate_provider_store.h, line 61 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0mB9i-Ufb5fmS-kRS:-Me0mB9j3M90jPmIRBNo:b-6eqytv) ([raw file](https://github.com/grpc/grpc/blob/12551bea2dc6707239d655fd9fc6fa3cf21f8974/src/core/ext/xds/certificate_provider_store.h#L61)):*
> ```objc
>   // Returns true if the instance name \a key is present in the map of plugin
>   // configurations, false otherwise.
>   bool CertificateProviderConfigExists(absl::string_view key);
> ```

Suggest calling this `CertificateProviderInstanceExists()`.
___
*[src/core/ext/xds/certificate_provider_store.cc, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0m7os5ngCofy8N_sQ:-Me0m7ot-Al3_jrDWtF8:bxfkgae) ([raw file](https://github.com/grpc/grpc/blob/12551bea2dc6707239d655fd9fc6fa3cf21f8974/src/core/ext/xds/certificate_provider_store.cc#L56)):*
> ```cpp
>     absl::string_view key) {
>   MutexLock lock(&mu_);
>   if (plugin_config_map_.find(std::string(key)) != plugin_config_map_.end()) {
> ```

```
return plugin_config_map_.find(std::string(key)) != plugin_config_map_.end();
```
___
*[src/core/ext/xds/xds_api.cc, line 1820 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0mfn-7zLHapOhA08i:-Me0mfn-7zLHapOhA08j:buh6qfg) ([raw file](https://github.com/grpc/grpc/blob/12551bea2dc6707239d655fd9fc6fa3cf21f8974/src/core/ext/xds/xds_api.cc#L1820)):*
> ```cpp
>           envoy_extensions_transport_sockets_tls_v3_CommonTlsContext_CertificateProviderInstance_certificate_name(
>               certificate_provider_instance_proto))};
>   if (!context.client->certificate_provider_store()
> ```

It seems a little unsafe to access `context.client` this way, since we're not holding a ref to the client.  Today this is actually okay in practice, since the `XdsApi` object is a data member of the `XdsClient` object and will therefore share its lifetime, but it makes me a little nervous, because we could in the future decide to change that and wouldn't necessarily remember to update the code here when that happens, which could lead to crashes.  The `client` field here is really intended as just a pointer address used for logging.  (Feel free to add a comment about this in the `EncodingContext` struct definition.)

Instead, I suggest having the `XdsApi` object store a pointer to the certificate provider map from the `XdsBootstrap` object, the same way that we do for the node info.  As a small bonus, this also avoids the need for synchronization in this check (i.e., acquiring the lock in `CertificateProviderStore::CertificateProviderConfigExists()`).

Also, while looking at this, I noticed that the bootstrap parsing code does not appear to be failing if an unknown cert provider plugin is specified in the bootstrap file.  We should probably fix that as well, and have a test for it.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8074 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0qKMs1ciVfQjLfnJC:-Me0qKMt5HvGw3iL9lc0:b-sc321f) ([raw file](https://github.com/grpc/grpc/blob/0e6c888574fcb0bacc62816fe1089271a03a44b0/test/cpp/end2end/xds_end2end_test.cc#L8074)):*
> ```cpp
>   transport_socket->mutable_typed_config()->PackFrom(upstream_tls_context);
>   balancers_[0]->ads_service()->SetCdsResource(cluster);
>   CheckRpcSendFailure(1, RpcOptions(), StatusCode::UNAVAILABLE);
> ```

Why are we not checking that the error code is UNAVAILABLE anymore?  Seems like we should still test that.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8094 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0qRrW6qzqlI-y1sQM:-Me0qRrW6qzqlI-y1sQN:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/0e6c888574fcb0bacc62816fe1089271a03a44b0/test/cpp/end2end/xds_end2end_test.cc#L8094)):*
> ```cpp
>   transport_socket->mutable_typed_config()->PackFrom(upstream_tls_context);
>   balancers_[0]->ads_service()->SetCdsResource(cluster);
>   CheckRpcSendFailure(1, RpcOptions(), StatusCode::UNAVAILABLE);
> ```

Same here.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26614)* status: all files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/certificate_provider_store.h, line 61 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0mB9i-Ufb5fmS-kRS:-Me23Jl0BJ0KYvb_AO4M:b-xvbsib) ([raw file](https://github.com/grpc/grpc/blob/12551bea2dc6707239d655fd9fc6fa3cf21f8974/src/core/ext/xds/certificate_provider_store.h#L61)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Suggest calling this `CertificateProviderInstanceExists()`.
</blockquote></details>

outdated
___
*[src/core/ext/xds/certificate_provider_store.cc, line 56 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0m7os5ngCofy8N_sQ:-Me23L1pB784ht93UVhg:b-7seu2e) ([raw file](https://github.com/grpc/grpc/blob/12551bea2dc6707239d655fd9fc6fa3cf21f8974/src/core/ext/xds/certificate_provider_store.cc#L56)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

```
return plugin_config_map_.find(std::string(key)) != plugin_config_map_.end();
```
</blockquote></details>

Used in new code
___
*[src/core/ext/xds/xds_api.cc, line 1820 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0mfn-7zLHapOhA08i:-Me23OPW1WQhQMeI8fQv:b-u66mri) ([raw file](https://github.com/grpc/grpc/blob/12551bea2dc6707239d655fd9fc6fa3cf21f8974/src/core/ext/xds/xds_api.cc#L1820)):*
> It seems a little unsafe to access context.client this way, since we're not holding a ref to the client.  Today this is actually okay in practice, since the XdsApi object is a data member of the XdsClient object and will therefore share its lifetime, but it makes me a little nervous, because we could in the future decide to change that and wouldn't necessarily remember to update the code here when that happens, which could lead to crashes.  The client field here is really intended as just a pointer address used for logging.  (Feel free to add a comment about this in the EncodingContext struct definition.)

Ack. Thanks for the suggestion!

> Instead, I suggest having the XdsApi object store a pointer to the certificate provider map from the XdsBootstrap object, the same way that we do for the node info.  As a small bonus, this also avoids the need for synchronization in this check (i.e., acquiring the lock in CertificateProviderStore::CertificateProviderConfigExists()).

Suggestion adopted. Note that we are still tying the lifetime of the XdsApi object and the XdsBootstrap object with this. Also, noticed that the plugin_config_map_ in CertificateProviderStore can be a const.

> Also, while looking at this, I noticed that the bootstrap parsing code does not appear to be failing if an unknown cert provider plugin is specified in the bootstrap file. We should probably fix that as well, and have a test for it.

I think the idea was that we should ignore unknown configurations. But, now that I'm rethinking this, I believe it fits better if we error out instead. PR coming up
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8074 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0qKMs1ciVfQjLfnJC:-Me21tFD1EA9SuUGlmeq:b-b2tz4a) ([raw file](https://github.com/grpc/grpc/blob/0e6c888574fcb0bacc62816fe1089271a03a44b0/test/cpp/end2end/xds_end2end_test.cc#L8074)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why are we not checking that the error code is UNAVAILABLE anymore?  Seems like we should still test that.
</blockquote></details>

We were getting the UNAVAILABLE error earlier because the response was seen by the lb policy resulting in TRANSIENT_FAILURE being propagated. Now, since we NACK the response, the errors are no longer propagated, resulting in a DEADLINE_EXCEEDED failure rather than a TRANSIENT_FAILURE.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8094 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0qRrW6qzqlI-y1sQM:-Me23DQA9axePO7Q2y4h:bykedje) ([raw file](https://github.com/grpc/grpc/blob/0e6c888574fcb0bacc62816fe1089271a03a44b0/test/cpp/end2end/xds_end2end_test.cc#L8094)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

 We were getting the UNAVAILABLE error earlier because the response was seen by the lb policy resulting in TRANSIENT_FAILURE being propagated. Now, since we NACK the response, the errors are no longer propagated, resulting in a DEADLINE_EXCEEDED failure rather than a TRANSIENT_FAILURE.

**Review by markdroth — CHANGES_REQUESTED** [review]
Looks good overall.  Just one remaining suggestion to clean up the code a bit.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26614#-:-Me5hUA_5EjNF6jiTSPs:b-qf5mnp)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 93 at r2](https://reviewable.io/reviews/grpc/grpc/26614#-Me5euuUCZIRm_HNDcj5:-Me5euuUCZIRm_HNDcj6:ba8tqiq) ([raw file](https://github.com/grpc/grpc/blob/aa9a00c3e6858f6afc218cdd4c2f60506b6a7c81/src/core/ext/xds/xds_api.cc#L93)):*
> ```cpp
> 
> #include "src/core/ext/xds/xds_api.h"
> #include "src/core/ext/xds/xds_client.h"
> ```

I don't think this include is needed anymore.
___
*[src/core/ext/xds/xds_api.cc, line 1812 at r2](https://reviewable.io/reviews/grpc/grpc/26614#-Me5eas9B0wRfID-xW3i:-Me5eas9B0wRfID-xW3j:b-ok03hz) ([raw file](https://github.com/grpc/grpc/blob/aa9a00c3e6858f6afc218cdd4c2f60506b6a7c81/src/core/ext/xds/xds_api.cc#L1812)):*
> ```cpp
> grpc_error_handle CertificateProviderInstanceParse(
>     const EncodingContext& context,
>     const CertificateProviderStore::PluginDefinitionMap*
> ```

How about adding this as a new field in `EncodingContext`, so that it's not necessary to pass it down as a separate parameter through all of these functions?
___
*[test/cpp/end2end/xds_end2end_test.cc, line 8074 at r1](https://reviewable.io/reviews/grpc/grpc/26614#-Me0qKMs1ciVfQjLfnJC:-Me5fNAY8q4jwV8utEIb:bl4a05v) ([raw file](https://github.com/grpc/grpc/blob/0e6c888574fcb0bacc62816fe1089271a03a44b0/test/cpp/end2end/xds_end2end_test.cc#L8074)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

We were getting the UNAVAILABLE error earlier because the response was seen by the lb policy resulting in TRANSIENT_FAILURE being propagated. Now, since we NACK the response, the errors are no longer propagated, resulting in a DEADLINE_EXCEEDED failure rather than a TRANSIENT_FAILURE.
</blockquote></details>

Hmm, interesting.  I don't think that's the correct behavior.  If we NACK the xDS resource, it seems like we should fail any non-wait_for_ready RPC with UNAVAILABLE.

It looks like the problem is that the XdsClient is not reporting an error to the watcher when we NACK a resource; instead, it is waiting for the resource timeout.  That seems sub-optimal; I think we should report an error in this case.  But this looks like an unrelated bug, so we can work on fixing that separately.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26614)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 93 at r2](https://reviewable.io/reviews/grpc/grpc/26614#-Me5euuUCZIRm_HNDcj5:-Me7PjRw66VgX96vmwMH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aa9a00c3e6858f6afc218cdd4c2f60506b6a7c81/src/core/ext/xds/xds_api.cc#L93)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I don't think this include is needed anymore.
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1812 at r2](https://reviewable.io/reviews/grpc/grpc/26614#-Me5eas9B0wRfID-xW3i:-Me7PkUw8EvYii5jQ54V:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/aa9a00c3e6858f6afc218cdd4c2f60506b6a7c81/src/core/ext/xds/xds_api.cc#L1812)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about adding this as a new field in `EncodingContext`, so that it's not necessary to pass it down as a separate parameter through all of these functions?
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
Looks great!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/26614#-:-MeAd3VxDsjtQfw3iNfy:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)

**Comment by yashykt** [comment]
Issues: #26595, #26637
Thanks for reviewing!

**Comment by yashykt** [comment]
Issues: #26595, #26637
Thanks for reviewing!

**Pull request merged**
