### PR TITLE
Bump version to v1.14.2-pre1

### PR DESCRIPTION
**Pull request by srini100**
Bump version to v1.14.2-pre1. Stopped adding pre1 to core version.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++
   +13%     +11 src/cpp/common/version_cc.cc     +11   +13%
       +28%     +11 grpc::Version[abi:cxx11]         +11   +28%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  -0.0%     -11 [None]                          +109  +0.0%

  [ = ]       0 TOTAL                           +120  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE                                    FILE SIZE
 ++++++++++++++ GROWING                      ++++++++++++++
   +13%     +11 src/cpp/common/version_cc.cc     +11   +13%
       +28%     +11 grpc::Version[abi:cxx11]         +11   +28%

 -+-+-+-+-+-+-+ MIXED                        +-+-+-+-+-+-+-
  -0.0%     -11 [None]                          +109  +0.0%

  [ = ]       0 TOTAL                           +120  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by srini100** [comment]
Known Tsan C failure https://github.com/grpc/grpc/issues/16352
Python bazel failure seems related to infra.
Known MacOS failures on this branch.

**Pull request merged**
