### PR TITLE
Two trivial comment/doc fixes

### PR DESCRIPTION
**Pull request by jaakristioja**
Please see commit messages for details, if needed.

@karthikravis

### CODE REVIEW

**Comment by jaakristioja** [comment]
Getting a CLA for this might take a while...

**Comment by karthikravis** [comment]
@jaakristioja :  Please sign the CLA so that we can proceed with the review.

**Comment by karthikravis** [comment]
Closing since no response on the PR.

**Comment by jaakristioja** [comment]
I apologize for not responding for so long. But You can leave this PR closed, as I and my employer have no interest in signing the CLA at this moment.

**Pull request closed without merging**
