### PR TITLE
upgrade protobuf to 3.18.1 (automatically generated)

### PR DESCRIPTION
**Pull request by jtattermusch**
Same as https://github.com/grpc/grpc/pull/27712, but generated automatically with the release_open_source.py script.

Let's double check the PRs are identical before merging one of them.

### CODE REVIEW

**Comment by jtattermusch** [comment]
The python bazel build failure seems as a legitimate failure:
https://source.cloud.google.com/results/invocations/af161a15-1c8c-475c-8cfb-4aea52d101c0/log ?

**Comment by lidizheng** [comment]
I'm in favor of getting rid of all Python 2 tests. The only concern I have is the potential impact we might have for GAE users. I have been running TGP for the removal (cl/353911233) every couple months, last time (3 months ago) there were only one target (GAE) left in google3 that still uses Python 2.

**Comment by markdroth** [comment]
@dennycd Can you please take a look at the iOS test failure and help us figure out if this is related to the protobuf upgrade, and if so, advise as to how to fix it?  Thanks!

**Comment by markdroth** [comment]
The iOS C++ test is continuing to fail in exactly the same spot.  Is there some way we can verify whether this is the ongoing Mac test flakiness or a real problem?

**Comment by dennycd** [comment]
protobuf build break should now be gone.  Cronet ios cpp test crash appears non-related to this PR. investigating separately

**Pull request merged**
