### PR TITLE
[grpc-php] php8 compatability

### PR DESCRIPTION
**Pull request by Alexander1000**
fix compatability with php8

@yashykt 

@markdroth

refreshed stale PR: https://github.com/grpc/grpc/pull/20829

### CODE REVIEW

**Comment by Alexander1000** [comment]
build
```docker build -t grpc-php/php-8 -f ./src/php/docker/php-8/Dockerfile .```
run
```docker run -it --rm grpc-php/php-8 > php8.log```
stdout:
```
++ dirname /github/grpc/src/php/bin/run_tests.sh
+ cd /github/grpc/src/php/bin/../../..
++ pwd
+ root=/github/grpc
+ cd src/php/bin
+ source ./determine_extension_dir.sh
++ set -e
+++ php-config --extension-dir
++ default_extension_dir=/usr/local/lib/php/extensions/no-debug-non-zts-20200930
++ '[' '!' -e /usr/local/lib/php/extensions/no-debug-non-zts-20200930/grpc.so ']'
++ extension_dir='-d extension=grpc.so'
+ export DYLD_LIBRARY_PATH=/github/grpc/libs/
+ DYLD_LIBRARY_PATH=/github/grpc/libs/
++ which php
++ which phpunit
+ /usr/local/bin/php -d extension=grpc.so -d max_execution_time=300 /usr/local/bin/phpunit -v --debug --exclude-group persistent_list_bound_tests ../tests/unit_tests
PHPUnit 9.4.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.0RC2

Test 'CallCredentials2Test::testCreateFromPlugin' started
Test 'CallCredentials2Test::testCreateFromPlugin' ended
Test 'CallCredentials2Test::testCallbackWithInvalidKey' started
Test 'CallCredentials2Test::testCallbackWithInvalidKey' ended
Test 'CallCredentials2Test::testCallbackWithInvalidReturnValue' started
Test 'CallCredentials2Test::testCallbackWithInvalidReturnValue' ended
Test 'CallCredentialsTest::testCreateFromPlugin' started
Test 'CallCredentialsTest::testCreateFromPlugin' ended
Test 'CallCredentialsTest::testCreateComposite' started
Test 'CallCredentialsTest::testCreateComposite' ended
Test 'CallCredentialsTest::testCreateFromPluginInvalidParam' started
Test 'CallCredentialsTest::testCreateFromPluginInvalidParam' ended
Test 'CallCredentialsTest::testCreateCompositeInvalidParam' started
Test 'CallCredentialsTest::testCreateCompositeInvalidParam' ended
Test 'CallInvokerTest::testCreateDefaultCallInvoker' started
Test 'CallInvokerTest::testCreateDefaultCallInvoker' ended
Test 'CallInvokerTest::testCreateCallInvoker' started
Test 'CallInvokerTest::testCreateCallInvoker' ended
Test 'CallInvokerTest::testCallInvokerAccessChannel' started
Test 'CallInvokerTest::testCallInvokerAccessChannel' ended
Test 'CallInvokerTest::testClientChangeRequestCallInvoker' started
Test 'CallInvokerTest::testClientChangeRequestCallInvoker' ended
Test 'CallTest::testConstructor' started
Test 'CallTest::testConstructor' ended
Test 'CallTest::testAddEmptyMetadata' started
Test 'CallTest::testAddEmptyMetadata' ended
Test 'CallTest::testAddSingleMetadata' started
Test 'CallTest::testAddSingleMetadata' ended
Test 'CallTest::testAddMultiValueMetadata' started
Test 'CallTest::testAddMultiValueMetadata' ended
Test 'CallTest::testAddSingleAndMultiValueMetadata' started
Test 'CallTest::testAddSingleAndMultiValueMetadata' ended
Test 'CallTest::testAddMultiAndMultiValueMetadata' started
Test 'CallTest::testAddMultiAndMultiValueMetadata' ended
Test 'CallTest::testGetPeer' started
Test 'CallTest::testGetPeer' ended
Test 'CallTest::testCancel' started
Test 'CallTest::testCancel' ended
Test 'CallTest::testInvalidStartBatchKey' started
Test 'CallTest::testInvalidStartBatchKey' ended
Test 'CallTest::testInvalidMetadataStrKey' started
Test 'CallTest::testInvalidMetadataStrKey' ended
Test 'CallTest::testInvalidMetadataIntKey' started
Test 'CallTest::testInvalidMetadataIntKey' ended
Test 'CallTest::testInvalidMetadataInnerValue' started
Test 'CallTest::testInvalidMetadataInnerValue' ended
Test 'CallTest::testInvalidConstuctor' started
Test 'CallTest::testInvalidConstuctor' ended
Test 'CallTest::testInvalidConstuctor2' started
Test 'CallTest::testInvalidConstuctor2' ended
Test 'CallTest::testInvalidSetCredentials' started
Test 'CallTest::testInvalidSetCredentials' ended
Test 'CallTest::testInvalidSetCredentials2' started
Test 'CallTest::testInvalidSetCredentials2' ended
Test 'ChannelCredentialsTest::testCreateSslWith3Null' started
Test 'ChannelCredentialsTest::testCreateSslWith3Null' ended
Test 'ChannelCredentialsTest::testCreateSslWith3NullString' started
Test 'ChannelCredentialsTest::testCreateSslWith3NullString' ended
Test 'ChannelCredentialsTest::testCreateInsecure' started
Test 'ChannelCredentialsTest::testCreateInsecure' ended
Test 'ChannelCredentialsTest::testDefaultRootsPem' started
Test 'ChannelCredentialsTest::testDefaultRootsPem' ended
Test 'ChannelCredentialsTest::testInvalidCreateSsl' started
Test 'ChannelCredentialsTest::testInvalidCreateSsl' ended
Test 'ChannelCredentialsTest::testInvalidCreateComposite' started
Test 'ChannelCredentialsTest::testInvalidCreateComposite' ended
Test 'ChannelTest::testInsecureCredentials' started
Test 'ChannelTest::testInsecureCredentials' ended
Test 'ChannelTest::testConstructorCreateSsl' started
Test 'ChannelTest::testConstructorCreateSsl' ended
Test 'ChannelTest::testGetConnectivityState' started
Test 'ChannelTest::testGetConnectivityState' ended
Test 'ChannelTest::testGetConnectivityStateWithInt' started
Test 'ChannelTest::testGetConnectivityStateWithInt' ended
Test 'ChannelTest::testGetConnectivityStateWithString' started
Test 'ChannelTest::testGetConnectivityStateWithString' ended
Test 'ChannelTest::testGetConnectivityStateWithBool' started
Test 'ChannelTest::testGetConnectivityStateWithBool' ended
Test 'ChannelTest::testGetTarget' started
Test 'ChannelTest::testGetTarget' ended
Test 'ChannelTest::testWatchConnectivityState' started
Test 'ChannelTest::testWatchConnectivityState' ended
Test 'ChannelTest::testClose' started
Test 'ChannelTest::testClose' ended
Test 'ChannelTest::testInvalidConstructorWithNull' started
Test 'ChannelTest::testInvalidConstructorWithNull' ended
Test 'ChannelTest::testInvalidConstructorWith' started
Test 'ChannelTest::testInvalidConstructorWith' ended
Test 'ChannelTest::testInvalidCredentials' started
Test 'ChannelTest::testInvalidCredentials' ended
Test 'ChannelTest::testInvalidOptionsArray' started
Test 'ChannelTest::testInvalidOptionsArray' ended
Test 'ChannelTest::testInvalidGetConnectivityStateWithArray' started
Test 'ChannelTest::testInvalidGetConnectivityStateWithArray' ended
Test 'ChannelTest::testInvalidWatchConnectivityState' started
Test 'ChannelTest::testInvalidWatchConnectivityState' ended
Test 'ChannelTest::testInvalidWatchConnectivityState2' started
Test 'ChannelTest::testInvalidWatchConnectivityState2' ended
Test 'ChannelTest::testPersistentChannelSameHost' started
Test 'ChannelTest::testPersistentChannelSameHost' ended
Test 'ChannelTest::testPersistentChannelDifferentHost' started
Test 'ChannelTest::testPersistentChannelDifferentHost' ended
Test 'ChannelTest::testPersistentChannelSameArgs' started
Test 'ChannelTest::testPersistentChannelSameArgs' ended
Test 'ChannelTest::testPersistentChannelDifferentArgs' started
Test 'ChannelTest::testPersistentChannelDifferentArgs' ended
Test 'ChannelTest::testPersistentChannelSameChannelCredentials' started
E1026 14:55:11.042368400      16 ssl_transport_security.cc:757] Could not load any root certificate.
E1026 14:55:11.042411500      16 ssl_transport_security.cc:961] Could not load root certificates.
E1026 14:55:11.042440900      16 ssl_transport_security.cc:757] Could not load any root certificate.
E1026 14:55:11.042452000      16 ssl_transport_security.cc:1938] Cannot load server root certificates.
E1026 14:55:11.042481500      16 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1026 14:55:11.042515200      16 secure_channel_create.cc:107] Failed to create secure subchannel for secure name 'localhost:50019'
E1026 14:55:11.042525200      16 secure_channel_create.cc:49] Failed to create channel args during subchannel creation.
Test 'ChannelTest::testPersistentChannelSameChannelCredentials' ended
Test 'ChannelTest::testPersistentChannelDifferentChannelCredentials' started
E1026 14:55:11.043308900      16 ssl_transport_security.cc:757] Could not load any root certificate.
E1026 14:55:11.043346300      16 ssl_transport_security.cc:1938] Cannot load server root certificates.
E1026 14:55:11.043357000      16 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1026 14:55:11.043364100      16 secure_channel_create.cc:107] Failed to create secure subchannel for secure name 'localhost:50020'
E1026 14:55:11.043369800      16 secure_channel_create.cc:49] Failed to create channel args during subchannel creation.
Test 'ChannelTest::testPersistentChannelDifferentChannelCredentials' ended
Test 'ChannelTest::testPersistentChannelSameChannelCredentialsRootCerts' started
Test 'ChannelTest::testPersistentChannelSameChannelCredentialsRootCerts' ended
Test 'ChannelTest::testPersistentChannelDifferentSecureChannelCredentials' started
E1026 14:55:11.044544800      16 ssl_transport_security.cc:757] Could not load any root certificate.
E1026 14:55:11.044580200      16 ssl_transport_security.cc:1938] Cannot load server root certificates.
E1026 14:55:11.044593700      16 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1026 14:55:11.044600800      16 secure_channel_create.cc:107] Failed to create secure subchannel for secure name 'localhost:50022'
E1026 14:55:11.044606700      16 secure_channel_create.cc:49] Failed to create channel args during subchannel creation.
Test 'ChannelTest::testPersistentChannelDifferentSecureChannelCredentials' ended
Test 'ChannelTest::testPersistentChannelSharedChannelClose1' started
Test 'ChannelTest::testPersistentChannelSharedChannelClose1' ended
Test 'ChannelTest::testPersistentChannelSharedChannelClose2' started
Test 'ChannelTest::testPersistentChannelSharedChannelClose2' ended
Test 'ChannelTest::testPersistentChannelCreateAfterClose' started
Test 'ChannelTest::testPersistentChannelCreateAfterClose' ended
Test 'ChannelTest::testPersistentChannelSharedMoreThanTwo' started
Test 'ChannelTest::testPersistentChannelSharedMoreThanTwo' ended
Test 'ChannelTest::testPersistentChannelWithCallCredentials' started
E1026 14:55:11.046948300      16 ssl_transport_security.cc:757] Could not load any root certificate.
E1026 14:55:11.046986000      16 ssl_transport_security.cc:1938] Cannot load server root certificates.
E1026 14:55:11.047005300      16 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1026 14:55:11.047010600      16 secure_channel_create.cc:107] Failed to create secure subchannel for secure name 'localhost:50026'
E1026 14:55:11.047020000      16 secure_channel_create.cc:49] Failed to create channel args during subchannel creation.
Test 'ChannelTest::testPersistentChannelWithCallCredentials' ended
Test 'ChannelTest::testPersistentChannelWithDifferentCallCredentials' started
E1026 14:55:11.047980000      16 ssl_transport_security.cc:757] Could not load any root certificate.
E1026 14:55:11.048014900      16 ssl_transport_security.cc:1938] Cannot load server root certificates.
E1026 14:55:11.048030400      16 ssl_security_connector.cc:116] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1026 14:55:11.048064400      16 secure_channel_create.cc:107] Failed to create secure subchannel for secure name 'localhost:50027'
E1026 14:55:11.048079700      16 secure_channel_create.cc:49] Failed to create channel args during subchannel creation.
Test 'ChannelTest::testPersistentChannelWithDifferentCallCredentials' ended
Test 'ChannelTest::testPersistentChannelForceNew' started
Test 'ChannelTest::testPersistentChannelForceNew' ended
Test 'ChannelTest::testPersistentChannelForceNewOldChannelIdle1' started
Test 'ChannelTest::testPersistentChannelForceNewOldChannelIdle1' ended
Test 'ChannelTest::testPersistentChannelForceNewOldChannelIdle2' started
Test 'ChannelTest::testPersistentChannelForceNewOldChannelIdle2' ended
Test 'ChannelTest::testPersistentChannelForceNewOldChannelClose1' started
Test 'ChannelTest::testPersistentChannelForceNewOldChannelClose1' ended
Test 'ChannelTest::testPersistentChannelForceNewOldChannelClose2' started
Test 'ChannelTest::testPersistentChannelForceNewOldChannelClose2' ended
Test 'ChannelTest::testPersistentChannelForceNewNewChannelClose' started
Test 'ChannelTest::testPersistentChannelForceNewNewChannelClose' ended
Test 'EndToEndTest::testSimpleRequestBody' started
Test 'EndToEndTest::testSimpleRequestBody' ended
Test 'EndToEndTest::testMessageWriteFlags' started
Test 'EndToEndTest::testMessageWriteFlags' ended
Test 'EndToEndTest::testClientServerFullRequestResponse' started
Test 'EndToEndTest::testClientServerFullRequestResponse' ended
Test 'EndToEndTest::testInvalidClientMessageArray' started
Test 'EndToEndTest::testInvalidClientMessageArray' ended
Test 'EndToEndTest::testInvalidClientMessageString' started
Test 'EndToEndTest::testInvalidClientMessageString' ended
Test 'EndToEndTest::testInvalidClientMessageFlags' started
Test 'EndToEndTest::testInvalidClientMessageFlags' ended
Test 'EndToEndTest::testInvalidServerStatusMetadata' started
Test 'EndToEndTest::testInvalidServerStatusMetadata' ended
Test 'EndToEndTest::testInvalidServerStatusCode' started
Test 'EndToEndTest::testInvalidServerStatusCode' ended
Test 'EndToEndTest::testMissingServerStatusCode' started
Test 'EndToEndTest::testMissingServerStatusCode' ended
Test 'EndToEndTest::testInvalidServerStatusDetails' started
Test 'EndToEndTest::testInvalidServerStatusDetails' ended
Test 'EndToEndTest::testMissingServerStatusDetails' started
Test 'EndToEndTest::testMissingServerStatusDetails' ended
Test 'EndToEndTest::testInvalidStartBatchKey' started
Test 'EndToEndTest::testInvalidStartBatchKey' ended
Test 'EndToEndTest::testInvalidStartBatch' started
Test 'EndToEndTest::testInvalidStartBatch' ended
Test 'EndToEndTest::testGetTarget' started
Test 'EndToEndTest::testGetTarget' ended
Test 'EndToEndTest::testGetConnectivityState' started
Test 'EndToEndTest::testGetConnectivityState' ended
Test 'EndToEndTest::testWatchConnectivityStateFailed' started
Test 'EndToEndTest::testWatchConnectivityStateFailed' ended
Test 'EndToEndTest::testWatchConnectivityStateSuccess' started
Test 'EndToEndTest::testWatchConnectivityStateSuccess' ended
Test 'EndToEndTest::testWatchConnectivityStateDoNothing' started
Test 'EndToEndTest::testWatchConnectivityStateDoNothing' ended
Test 'EndToEndTest::testGetConnectivityStateInvalidParam' started
Test 'EndToEndTest::testGetConnectivityStateInvalidParam' ended
Test 'EndToEndTest::testWatchConnectivityStateInvalidParam' started
Test 'EndToEndTest::testWatchConnectivityStateInvalidParam' ended
Test 'EndToEndTest::testChannelConstructorInvalidParam' started
Test 'EndToEndTest::testChannelConstructorInvalidParam' ended
Test 'EndToEndTest::testClose' started
Test 'EndToEndTest::testClose' ended
Test 'InterceptorTest::testClientChangeMetadataOneInterceptor' started
Test 'InterceptorTest::testClientChangeMetadataOneInterceptor' ended
Test 'InterceptorTest::testClientChangeMetadataTwoInterceptor' started
Test 'InterceptorTest::testClientChangeMetadataTwoInterceptor' ended
Test 'InterceptorTest::testClientChangeRequestInterceptor' started
Test 'InterceptorTest::testClientChangeRequestInterceptor' ended
Test 'InterceptorTest::testClientChangeStopCallInterceptor' started
Test 'InterceptorTest::testClientChangeStopCallInterceptor' ended
Test 'InterceptorTest::testGetInterceptorChannelConnectivityState' started
Test 'InterceptorTest::testGetInterceptorChannelConnectivityState' ended
Test 'InterceptorTest::testInterceptorChannelWatchConnectivityState' started
Test 'InterceptorTest::testInterceptorChannelWatchConnectivityState' ended
Test 'InterceptorTest::testInterceptorChannelClose' started
Test 'InterceptorTest::testInterceptorChannelClose' ended
Test 'InterceptorTest::testInterceptorChannelGetTarget' started
Test 'InterceptorTest::testInterceptorChannelGetTarget' ended
Test 'SecureEndToEndTest::testSimpleRequestBody' started
Test 'SecureEndToEndTest::testSimpleRequestBody' ended
Test 'SecureEndToEndTest::testMessageWriteFlags' started
Test 'SecureEndToEndTest::testMessageWriteFlags' ended
Test 'SecureEndToEndTest::testClientServerFullRequestResponse' started
Test 'SecureEndToEndTest::testClientServerFullRequestResponse' ended
Test 'ServerTest::testConstructorWithNull' started
Test 'ServerTest::testConstructorWithNull' ended
Test 'ServerTest::testConstructorWithNullArray' started
Test 'ServerTest::testConstructorWithNullArray' ended
Test 'ServerTest::testConstructorWithArray' started
Test 'ServerTest::testConstructorWithArray' ended
Test 'ServerTest::testRequestCall' started
Test 'ServerTest::testRequestCall' ended
Test 'ServerTest::testInvalidConstructor' started
Test 'ServerTest::testInvalidConstructor' ended
Test 'ServerTest::testInvalidConstructorWithNumKeyOfArray' started
Test 'ServerTest::testInvalidConstructorWithNumKeyOfArray' ended
Test 'ServerTest::testInvalidConstructorWithList' started
Test 'ServerTest::testInvalidConstructorWithList' ended
Test 'ServerTest::testInvalidAddHttp2Port' started
Test 'ServerTest::testInvalidAddHttp2Port' ended
Test 'ServerTest::testInvalidAddSecureHttp2Port' started
Test 'ServerTest::testInvalidAddSecureHttp2Port' ended
Test 'ServerTest::testInvalidAddSecureHttp2Port2' started
Test 'ServerTest::testInvalidAddSecureHttp2Port2' ended
Test 'ServerTest::testInvalidAddSecureHttp2Port3' started
Test 'ServerTest::testInvalidAddSecureHttp2Port3' ended
Test 'TimevalTest::testConstructorWithInt' started
Test 'TimevalTest::testConstructorWithInt' ended
Test 'TimevalTest::testConstructorWithNegative' started
Test 'TimevalTest::testConstructorWithNegative' ended
Test 'TimevalTest::testConstructorWithZero' started
Test 'TimevalTest::testConstructorWithZero' ended
Test 'TimevalTest::testConstructorWithOct' started
Test 'TimevalTest::testConstructorWithOct' ended
Test 'TimevalTest::testConstructorWithHex' started
Test 'TimevalTest::testConstructorWithHex' ended
Test 'TimevalTest::testConstructorWithFloat' started
Test 'TimevalTest::testConstructorWithFloat' ended
Test 'TimevalTest::testConstructorWithBigInt' started
Test 'TimevalTest::testConstructorWithBigInt' ended
Test 'TimevalTest::testAddAndSubtractWithBigInt' started
Test 'TimevalTest::testAddAndSubtractWithBigInt' ended
Test 'TimevalTest::testCompareSame' started
Test 'TimevalTest::testCompareSame' ended
Test 'TimevalTest::testPastIsLessThanZero' started
Test 'TimevalTest::testPastIsLessThanZero' ended
Test 'TimevalTest::testFutureIsGreaterThanZero' started
Test 'TimevalTest::testFutureIsGreaterThanZero' ended
Test 'TimevalTest::testNowIsBetweenZeroAndFuture' started
Test 'TimevalTest::testNowIsBetweenZeroAndFuture' ended
Test 'TimevalTest::testNowAndAdd' started
Test 'TimevalTest::testNowAndAdd' ended
Test 'TimevalTest::testNowAndSubtract' started
Test 'TimevalTest::testNowAndSubtract' ended
Test 'TimevalTest::testAddAndSubtract' started
Test 'TimevalTest::testAddAndSubtract' ended
Test 'TimevalTest::testAddAndSubtractBigInt' started
Test 'TimevalTest::testAddAndSubtractBigInt' ended
Test 'TimevalTest::testSimilar' started
Test 'TimevalTest::testSimilar' ended
Test 'TimevalTest::testSleepUntil' started
Test 'TimevalTest::testSleepUntil' ended
Test 'TimevalTest::testConstructorInvalidParam' started
Test 'TimevalTest::testConstructorInvalidParam' ended
Test 'TimevalTest::testAddInvalidParam' started
Test 'TimevalTest::testAddInvalidParam' ended
Test 'TimevalTest::testSubtractInvalidParam' started
Test 'TimevalTest::testSubtractInvalidParam' ended
Test 'TimevalTest::testCompareInvalidParam' started
Test 'TimevalTest::testCompareInvalidParam' ended
Test 'TimevalTest::testSimilarInvalidParam' started
Test 'TimevalTest::testSimilarInvalidParam' ended


Time: 00:00.242, Memory: 20.00 MB

There were 3 risky tests:

1) CallInvokerTest::testCreateDefaultCallInvoker
This test did not perform any assertions

/github/grpc/src/php/tests/unit_tests/CallInvokerTest.php:176

2) CallInvokerTest::testCreateCallInvoker
This test did not perform any assertions

/github/grpc/src/php/tests/unit_tests/CallInvokerTest.php:181

3) ChannelTest::testConstructorCreateSsl
This test did not perform any assertions

/github/grpc/src/php/tests/unit_tests/ChannelTest.php:40

OK, but incomplete, skipped, or risky tests!
Tests: 136, Assertions: 320, Risky: 3.
+ for arg in "$@"
+ [[ --skip-persistent-channel-tests == \-\-\s\k\i\p\-\p\e\r\s\i\s\t\e\n\t\-\c\h\a\n\n\e\l\-\t\e\s\t\s ]]
+ SKIP_PERSISTENT_CHANNEL_TESTS=true
+ for arg in "$@"
+ [[ --ignore-valgrind-undef-errors == \-\-\s\k\i\p\-\p\e\r\s\i\s\t\e\n\t\-\c\h\a\n\n\e\l\-\t\e\s\t\s ]]
+ [[ --ignore-valgrind-undef-errors == \-\-\i\g\n\o\r\e\-\v\a\l\g\r\i\n\d\-\u\n\d\e\f\-\e\r\r\o\r\s ]]
+ VALGRIND_UNDEF_VALUE_ERRORS=--undef-value-errors=no
+ [[ true != \t\r\u\e ]]
+ export ZEND_DONT_UNLOAD_MODULES=1
+ ZEND_DONT_UNLOAD_MODULES=1
+ export USE_ZEND_ALLOC=0
+ USE_ZEND_ALLOC=0
++ command -v valgrind
+ '[' -x /usr/bin/valgrind ']'
++ which valgrind
++ which php
+ /usr/bin/valgrind --error-exitcode=10 --leak-check=yes --undef-value-errors=no /usr/local/bin/php -d extension=grpc.so -d max_execution_time=300 ../tests/MemoryLeakTest/MemoryLeakTest.php
==30== Memcheck, a memory error detector
==30== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==30== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==30== Command: /usr/local/bin/php -d extension=grpc.so -d max_execution_time=300 ../tests/MemoryLeakTest/MemoryLeakTest.php
==30== 
==30== 
==30== HEAP SUMMARY:
==30==     in use at exit: 10,321 bytes in 58 blocks
==30==   total heap usage: 22,256 allocs, 22,198 frees, 3,449,353 bytes allocated
==30== 
==30== LEAK SUMMARY:
==30==    definitely lost: 0 bytes in 0 blocks
==30==    indirectly lost: 0 bytes in 0 blocks
==30==      possibly lost: 0 bytes in 0 blocks
==30==    still reachable: 10,321 bytes in 58 blocks
==30==         suppressed: 0 bytes in 0 blocks
==30== Reachable blocks (those to which a pointer was found) are not shown.
==30== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==30== 
==30== For counts of detected and suppressed errors, rerun with: -v
==30== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by Alexander1000** [comment]
@stanley-cheung, run please koro ci tests

**Comment by stanley-cheung** [comment]
@Alexander1000 Hi Alexander, thanks very much for this contribution. However, there are too many things that are included in this PR - we would prefer to split them up so that they are better reviewed.

I think the first priority here is PHP8 compatibility, right? So I'd like to see these changes included in one small unit PR:
- any changes to the `src/php/ext/grpc` pecl extension to make PHP8 compatible.
- a new docker image in `src/php/docker/php8` to make sure we test that going forward. (Here you will need to create a template file under `templates/src/php/docker/php8`. See other similar docker images as example).

I think that would be a good starting point.

I see your intention to fix the PHP7 syntax in the unit tests. I had wanted to do it at a later stage. As of recently, we just removed PHP5 support so we are concerned about stability. So we'd like to see one small change at a time to make sure we provide some accountability to make sure new changes won't break things.

I also see your changes in `src/php/composer.json` to move the minimum PHP version up to PHP7. That's a good intention and we need to do it sooner or later, but I would like it to be done that line in a separate PR.

And for the PHP7.2 to 7.3 changes in that series of docker images under `src/php/docker`. Yes that would be another change I'd like to separate out. (And make sure you make the changes from the `templates/src/php/docker` directory first - otherwise sanity checks tests will break).

The changes to PHPUnit and adding those PHP7 syntax like `: void` I would like to do it last. 

Actually if you don't mind, we actually have all these in our internal work list that we are rolling it out slowly. So these changes are also somewhat planned already. 

So if you don't mind, can we keep this PR to just add the PHP8 compatibility like I mentioned above? Again thank you very much for your contribution!

**Comment by Alexander1000** [comment]
Thanks for your feedback. I updated PHPUnit because it includes fixes for deprecated expressions.
Without this update, tests will fail with deprecated errors.

**Comment by Alexander1000** [comment]
Thanks for running the tests. I saw that I was missing a couple of places with updating dockerfiles. Fixed it.

**Comment by Alexander1000** [comment]
Can you run autotests?

**Comment by Alexander1000** [comment]
Oh sorry.... build run on php 7.2... I thought I fixed everything...

https://source.cloud.google.com/results/invocations/e3cc5584-0c68-4ab0-bf93-28e91b2304ac/targets/github%2Fgrpc%2Frun_tests%2Fsanity_linux_dbg_native%2Ftools%2Fbuildgen%2Fgenerate_projects.sh/tests;group=sanity_linux_dbg_native_tools%2Fbuildgen%2Fgenerate_projects_sh;test=tools%2Fbuildgen%2Fgenerate_projects.sh;row=1

**Comment by Alexander1000** [comment]
There strange failure: https://source.cloud.google.com/results/invocations/5c93b9c6-3e89-4cd3-8cd3-0362b03691ce/targets
Looks like infrastructure, because docker pull failed...

**Comment by Alexander1000** [comment]
If possible, can I ask you to run it again?

**Comment by Alexander1000** [comment]
I don't understand yet why it falls
I'll try to figure it out later

**Comment by Alexander1000** [comment]
This branch was rebased on fresh master
And patched docker image with fresh image php
I hope that's enough :)

**Comment by Alexander1000** [comment]
How i can see docker build logs?

**Comment by stanley-cheung** [comment]
There are quite a number of PRs related to PHP8 (and subsequently around PHPUnit) that's currently open. I'd like to give a summary of what we know and what we found so far. My plan is to narrow them down in the coming days.

- As far as updating the PECL extension code itself to make sure our `grpc` extension will work in PHP8, I believe the scope there is pretty clear by now. I think #24621 captured all that needs to be done. Some manual testing has been done to make sure this will work on PHP8. I am feeling pretty good about that.

- With the support for PHP8 added, there's a need to upgrade the PHPUnit version we use in our testing docker files. The current thinking is that we should move up to PHPUnit 8 because it supports PHP 7.2 to 7.4. PHPUnit 7 doesn't support PHP 7.4 while PHPUnit 9 doesn't support PHP 7.2. So PHPUnit 8 seems to be the right spot for us in the near future.

- But that creates a dilemma for us because we cannot seem to create a `php8` testing dockerfile that I originally wanted. In order to use PHPUnit 9 (because that's the only version that supports PHP8), there seems to be some extensive code change that's needed to our unit test code that I don't want to get into right now. Testing against PHP 7.2 - 7.4 is our highest priority in the near future, not PHP8 for now. I believe #24695 is tracking those changes to update the PHPUnit version to 8. 

So the combination of above means that _we will add support for PHP8 in our extension but there won't be continuous testing on it in the near future_ and that seems to be an acceptable compromise for now. The alternative of having 2 sets of unit test code that will work for both PHPUnit 8 and 9 are not really acceptable. We have to pick a PHPUnit version to sit on and version 8 seems to be the right choice for now.

**Comment by Alexander1000** [comment]
Well, thanks for your attention. I was glad to help you.

**Comment by stanley-cheung** [comment]
This is merged as part of #24621. But thanks for all the contributions to help us move forward.

**Pull request closed without merging**
