### PR TITLE
Keepalive watchdog timer used a wrong timeout value

### PR DESCRIPTION
**Pull request by muxi**
The watchdog should take the `GRPC_ARG_KEEPALIVE_TIMEOUT_MS` channel arg. Right now it takes `GRPC_ARG_KEEPALIVE_TIME_MS`.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by muxi** [comment]
@yang-g I thought about polishing the [keepalive test](https://github.com/grpc/grpc/blob/master/test/core/end2end/tests/keepalive_timeout.cc). The problem is that the only difference between fixed or not is the timing when the watchdog timer fires. To capture that with a test, you will need to depend on some time reference, which I am not sure if it's a good idea in CI?

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by muxi** [comment]
Updated `keepalive_test` to capture the original bug. When the watchdog used `keepalive_time` for deadline, the call would fail with `DEADLINE_EXCEEDED` since it is much larger than `keepalive_timeout`. With the fix, the test fails with `INTERNAL` which is expected.

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
