### PR TITLE
[Deps] Updated protobuf to v29

### PR DESCRIPTION
**Pull request by veblush**
Upgraded Protobuf from v28 to v29. This PR doesn't have anything special other than regular changes needed.

### CODE REVIEW

**Comment by veblush** [comment]
I just re-realized that gRPC Python tests are configured to use the non RC version of Protobuf. Therefore, the PR using RC version of Protobuf always fails with the mismatched Protobuf versions.

**Comment by veblush** [comment]
@XuanWang-Amos and @gnossen Is there a way to pin the Python Protobuf for the test in this PR? It appears that our Python tests use the latest non RC version.

**Comment by XuanWang-Amos** [comment]
> @XuanWang-Amos and @gnossen Is there a way to pin the Python Protobuf for the test in this PR? It appears that our Python tests use the latest non RC version.

I assume you mean runtime Protobuf? By default, `pip install` will not install release candidate versions, you probably need manually change the version to `pip install protobuf==5.29.0rc2`:
https://github.com/grpc/grpc/blob/e352e896cb854759a2991b9f86389d7b01cf52a1/tools/run_tests/helper_scripts/build_python.sh#L175

**Comment by veblush** [comment]
> > @XuanWang-Amos and @gnossen Is there a way to pin the Python Protobuf for the test in this PR? It appears that our Python tests use the latest non RC version.
> 
> I assume you mean runtime Protobuf? By default, `pip install` will not install release candidate versions, you probably need manually change the version to `pip install protobuf==5.29.0rc2`:
> 
> https://github.com/grpc/grpc/blob/e352e896cb854759a2991b9f86389d7b01cf52a1/tools/run_tests/helper_scripts/build_python.sh#L175

Thanks! I just cooked up something to override it. In a longer run, it'd be helpful for gRPC python tests to follow the protobuf version specified in the `build_handwritten.yaml`

**Review by gnossen — APPROVED** [review]

**Pull request closed without merging**
