### PR TITLE
Cleaned up BUILD file, which fixed a dependency problem with protobuf.

### PR DESCRIPTION
**Pull request by haberman**
Previously the binary was re-listing the source files that were already present in other library rules. But it wasn't properly depending on the libraries #included from those source files.

A simpler solution is just to depend on the existing library rules.

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @haberman isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by ncteisen** [comment]
Can you sign CLA? then I am able to spark off the CI test suite

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,718      Total (=)      1,952,718

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,663,574      Total (<)     10,663,580

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by haberman** [comment]
@thelinuxfoundation Re-check CLA?

**Comment by haberman** [comment]
@ncteisen CLA looks good and the change passes the merge-bot.

**Comment by ncteisen** [comment]
Thanks for the contribution!

**Pull request merged**
