### PR TITLE
Destroy the pollset mutex created in pollset_init

### PR DESCRIPTION
**Pull request by sreecha**
(Manually backporting the fix by Mike Burrows)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +48  +0.0%

  [ = ]       0 TOTAL      +48  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by sreecha** [comment]
The failure in windows is known:
https://github.com/grpc/grpc/issues/13845
https://github.com/grpc/grpc/issues/13149

**Pull request merged**
