### PR TITLE
Bump version to v1.13.1

### PR DESCRIPTION
**Pull request by jtattermusch**
To do a C# patch release with #15975.

CC @srini100

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Known failures (already closed as this is the release branch):
https://github.com/grpc/grpc/issues/15621
https://github.com/grpc/grpc/issues/15405
https://github.com/grpc/grpc/issues/15916

**Pull request merged**
