### PR TITLE
Factor out interface-specific early_adopter code

### PR DESCRIPTION
**Pull request by soltanmm**
Refactors early_adopter such that interface-specific code is located in
the framework module as a submodule `alpha`.

@nathanielmanistaatgoogle Please review and merge!

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
In your commit message you mean "package" and "subpackage". "modules" in Python are individual files.

**Comment by soltanmm** [comment]
Even if I change it, do not merge - something went strangely while rebasing.

**Comment by soltanmm** [comment]
@nathanielmanistaatgoogle Please re-review and merge.

**Comment by nathanielmanistaatgoogle** [comment]
Squash commits, please.

**Comment by soltanmm** [comment]
That was quite the `git` adventure.

**Pull request merged**
