### PR TITLE
Setup rbe_autoconfig for gRPC builds that use RBE

### PR DESCRIPTION
**Pull request by nlopezgi**
This PR enables use of rbe_autoconfig (https://github.com/bazelbuild/bazel-toolchains/blob/master/rules/rbe_repo.bzl) which provides an improved experience for maintaining the toolchain configuration (targets, flags) required to use RBE.

With this PR, all that is necessary to update the toolchain configuration is to update the pin to bazel-toolchains repo. Remote exec flags (specifically crosstool_top) and platform targets no longer need to be updated with new Bazel / container releases.

Note proper use of rbe_autoconfig requires that the external repo is named `@bazel_toolchains` (as opposed to `@com_github_bazelbuild_bazeltoolchains`). 
Note proper execution of rbe_autoconfig requires access to docker binary. Sending pull request to validate CI setup satisfies this requirement.

fyi @jtattermusch @billfeng327 

**Release Note**: No

### CODE REVIEW

**Comment by nlopezgi** [comment]
Hi @jtattermusch 
This PR is now ready to review.
Latest CI run failures do not seem to be related to these changes.
Basic Tests Windows is failing with a timeout:
`TIMEOUT: py35_gevent.test.unit._invocation_defects_test.InvocationDefectsTest [pid=1996, time=300.1sec]`
 Distribution Tests Linux is failing in a cmake build:
` FAILED: distribtest.cpp_linux_x64_jessie_cmake [ret=1, pid=7148, time=95.7sec]`

Rebased onto master to see if errors are solved.

**Comment by nlopezgi** [comment]
thanks for kicking off CI @jtattermusch , it looks like a single TSAN test failed, could this be a flake (i.e., can we restart that tsan run only to see if so?)

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/18511

**Comment by jtattermusch** [comment]
Thanks @nlopezgi  for contributing this!

**Pull request merged**
