### PR TITLE
Fix crash when failing to create an LB policy.

### PR DESCRIPTION
**Pull request by markdroth**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +40  +0.0%

  [ = ]       0 TOTAL      +40  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
The bug was introduced in the PR to convert the LB policy API to C++, but it was only tangentially related to C++.  Prior to that PR, the code used to basically do this:

```
// Step 1: Create a new LB policy if needed.
grpc_lb_policy* new_lb_policy = nullptr;
if (chand->resolver_result != nullptr) {
  // ...
  new_lb_policy = grpc_lb_policy_create(...);
  // ...
}
// Step 2: Update chand->lb_policy.
chand->lb_policy = new_lb_policy;
// Step 3: Check whether new LB policy needs to be initialized.
if (new_lb_policy != nullptr) {
  // ...initialize chand->lb_policy...
}
```

When I convered this code to C++, `new_lb_policy` changed from a simple pointer to an `OrphanablePtr<>`.  This meant that when its value was moved into `chand->lb_policy` in step 2, `new_lb_policy` became null, which meant that I could no longer check whether it was null in step 3.

To work around this, I added a boolean `lb_policy_created` variable and set it to true when we created a new LB policy.  But I forgot that in the original code, `new_lb_policy` could have been null because either we updated an existing LB policy or because we failed to create the new LB policy.  I was setting `lb_policy_created` to true in a place that caught the first case but not the second case.

**Pull request merged**
