### PR TITLE
Drop issue 527 TODOs for UnaryCall interop test specification

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
Issue #527 is long resolved.

### CODE REVIEW

**Comment by ejona86** [comment]
LGTM. Thank you.

Would it be good to include a link to the interop test descriptions? We couldn't do that originally because the document was private. Maybe since it has been public for just shy of six months it's time we reference it? WDYT?

**Comment by nathanielmanistaatgoogle** [comment]
Yes, absolutely, and I'd be in favor of stripping the comments out of `test.proto` as well as they can only ever range from "correct but duplicate and not the place to watch for updates" to "incorrect".

**Comment by ejona86** [comment]
> I'd be in favor of stripping the comments out of test.proto as well

You're not alone in sentiment. However, internally not having the comments causes either warnings or errors... And now it should be obvious why the comments don't add value :) [1]

 1. That combined with the fact that test.proto was originally for benchmarking. And that they were simply copied for the interop work and by the time somebody (me) actually defined the interop tests we already had 3-4 implementations of both clients and servers, so renaming fields and general cleanup was too time consuming.

**Comment by nathanielmanistaatgoogle** [comment]
Is "See (other location) for specification." an acceptable comment that dodges the warning/error issue? I have a large number of such comments in the `src/python/` tree.

**Comment by ejona86** [comment]
I like your thinking. Yeah, that would work for me. Should I do it, or do you want to?

**Pull request merged**
