### PR TITLE
GPR review: Privatize useful.h and avl.h

### PR DESCRIPTION
**Pull request by vjpai**
These should not be public headers

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]     +16  +0.0%

  [ = ]       0 TOTAL      +16  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by vjpai** [comment]
Will not merge until grpc/proposal#56 lands, which is Feb 8 at the earliest

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%    +128 [None]    +448  +0.0%

  +0.0%    +128 TOTAL     +448  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%    +128 [None]    +456  +0.0%

  +0.0%    +128 TOTAL     +456  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  +0.0%    +128 [None]    +456  +0.0%

  +0.0%    +128 TOTAL     +456  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +0.1%    +603 [None]                                                                               +4.71Ki  +0.1%
      +0.1%    +480 [Unmapped]                                                                           +4.59Ki  +0.1%
      +2.0%     +64 static_metadata_hash                                                                       0  [ = ]
      +2.0%     +64 grpc_static_slice_table                                                                  +64  +2.0%
      [NEW]     +32 vtable for grpc_core::RefCountedWithTracing                                              +32  [NEW]
      +2.0%     +32 grpc_static_metadata_refcounts                                                           +32  +2.0%
      +2.5%     +27 g_bytes                                                                                  +27  +2.5%
      +2.0%      +8 static_metadata_hash_values                                                                0  [ = ]
      +2.0%      +2 elems_r                                                                                   +2  +2.0%
      +1.9%      +2 elem_idxs                                                                                 +2  +1.9%
  [NEW]    +553 src/core/lib/compression/compression_ruby.cc                                            +553  [NEW]
      [NEW]    +330 grpc_compression_algorithm_parse_ruby                                                   +330  [NEW]
      [NEW]    +217 grpc_compression_algorithm_name_ruby                                                    +217  [NEW]
      [NEW]      +6 [Unmapped]                                                                                +6  [NEW]

 -------------- SHRINKING                                                                            --------------
 -14.9%    -448 src/core/ext/filters/max_age/max_age_filter.cc                                          -448 -14.9%
      [DEL]    -388 max_idle_timer_cb                                                                       -388  [DEL]
     -66.1%    -160 decrease_call_count                                                                     -160 -66.1%
     -74.1%    -103 increase_call_count                                                                     -103 -74.1%
      -2.0%     -16 init_channel_elem                                                                        -16  -2.0%
      -2.0%      -3 [Unmapped]                                                                                -3  -2.0%
 -61.6%    -188 src/core/tsi/alts_transport_security.cc                                                 -188 -61.6%
     -57.1%     -92 grpc_tsi_alts_shutdown                                                                   -92 -57.1%
      [DEL]     -51 grpc_tsi_alts_signal_for_cq_destroy                                                      -51  [DEL]
     -75.8%     -25 [Unmapped]                                                                               -25 -75.8%
     -38.5%     -20 grpc_tsi_alts_init                                                                       -20 -38.5%
  -2.4%    -160 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc                -160  -2.4%
      -4.2%     -86 rr_connectivity_changed_locked                                                           -86  -4.2%
     -10.2%     -81 rr_update_locked                                                                         -81 -10.2%
  -0.1%     -16 src/core/ext/filters/client_channel/client_channel.cc                                    -16  -0.1%
     -11.3%     -11 pick_callback_done_locked                                                                -11 -11.3%
      [DEL]      -9 grpc_core::RefCountedWithTracing<grpc_core::ConnectedSubchannel>::~RefCountedWithTra      -9  [DEL]
      -1.7%      -5 [Unmapped]                                                                                -5  -1.7%
      [DEL]      -2 grpc_core::RefCountedWithTracing<grpc_core::ConnectedSubchannel>::~RefCountedWithTra      -2  [DEL]
  -0.7%     -16 src/core/ext/filters/client_channel/lb_policy/subchannel_list.cc                         -16  -0.7%
     -14.2%     -20 grpc_lb_subchannel_data_start_connectivity_watch                                         -20 -14.2%
  -0.1%     -16 src/core/lib/surface/call.cc                                                             -16  -0.1%
      -6.4%     -16 publish_app_metadata(grpc_call*, grpc_metadata_batch*, int) [clone .isra.5]              -16  -6.4%

  +0.0%    +312 TOTAL                                                                                +4.43Ki  +0.1%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -40  -0.0%

  [ = ]       0 TOTAL      -40  -0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                               FILE SIZE
 ++++++++++++++ GROWING                 ++++++++++++++
  [NEW] +2.43Ki src/core/lib/avl/avl.cc +2.43Ki  [NEW]
      [NEW]    +943 rebalance                  +943  [NEW]
      [NEW]    +517 remove_key                 +517  [NEW]
      [NEW]    +318 add_key                    +318  [NEW]
      [NEW]    +132 new_node                   +132  [NEW]
      [NEW]    +110 grpc_avl_maybe_get         +110  [NEW]
      [NEW]    +104 grpc_avl_get               +104  [NEW]
      [NEW]    +102 unref_node                 +102  [NEW]
      [NEW]     +89 [Unmapped]                  +89  [NEW]
      [NEW]     +58 grpc_avl_add                +58  [NEW]
      [NEW]     +58 grpc_avl_remove             +58  [NEW]
      [NEW]     +38 grpc_avl_ref                +38  [NEW]
      [NEW]      +9 grpc_avl_is_empty            +9  [NEW]
      [NEW]      +6 grpc_avl_create              +6  [NEW]
      [NEW]      +5 grpc_avl_unref               +5  [NEW]
  +0.0%    +160 [None]                     +536  +0.0%

 -------------- SHRINKING               --------------
  [DEL] -2.43Ki src/core/lib/gpr/avl.cc -2.43Ki  [DEL]
      [DEL]    -943 rebalance                  -943  [DEL]
      [DEL]    -517 remove_key                 -517  [DEL]
      [DEL]    -318 add_key                    -318  [DEL]
      [DEL]    -132 new_node                   -132  [DEL]
      [DEL]    -110 gpr_avl_maybe_get          -110  [DEL]
      [DEL]    -104 gpr_avl_get                -104  [DEL]
      [DEL]    -102 unref_node                 -102  [DEL]
      [DEL]     -89 [Unmapped]                  -89  [DEL]
      [DEL]     -58 gpr_avl_add                 -58  [DEL]
      [DEL]     -58 gpr_avl_remove              -58  [DEL]
      [DEL]     -38 gpr_avl_ref                 -38  [DEL]
      [DEL]      -9 gpr_avl_is_empty             -9  [DEL]
      [DEL]      -6 gpr_avl_create               -6  [DEL]
      [DEL]      -5 gpr_avl_unref                -5  [DEL]

  +0.0%    +160 TOTAL                      +536  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                               FILE SIZE
 ++++++++++++++ GROWING                 ++++++++++++++
  [NEW] +2.43Ki src/core/lib/avl/avl.cc +2.43Ki  [NEW]
      [NEW]    +943 rebalance                  +943  [NEW]
      [NEW]    +517 remove_key                 +517  [NEW]
      [NEW]    +318 add_key                    +318  [NEW]
      [NEW]    +132 new_node                   +132  [NEW]
      [NEW]    +110 grpc_avl_maybe_get         +110  [NEW]
      [NEW]    +104 grpc_avl_get               +104  [NEW]
      [NEW]    +102 unref_node                 +102  [NEW]
      [NEW]     +89 [Unmapped]                  +89  [NEW]
      [NEW]     +58 grpc_avl_add                +58  [NEW]
      [NEW]     +58 grpc_avl_remove             +58  [NEW]
      [NEW]     +38 grpc_avl_ref                +38  [NEW]
      [NEW]      +9 grpc_avl_is_empty            +9  [NEW]
      [NEW]      +6 grpc_avl_create              +6  [NEW]
      [NEW]      +5 grpc_avl_unref               +5  [NEW]
  +0.0%    +160 [None]                     +536  +0.0%

 -------------- SHRINKING               --------------
  [DEL] -2.43Ki src/core/lib/gpr/avl.cc -2.43Ki  [DEL]
      [DEL]    -943 rebalance                  -943  [DEL]
      [DEL]    -517 remove_key                 -517  [DEL]
      [DEL]    -318 add_key                    -318  [DEL]
      [DEL]    -132 new_node                   -132  [DEL]
      [DEL]    -110 gpr_avl_maybe_get          -110  [DEL]
      [DEL]    -104 gpr_avl_get                -104  [DEL]
      [DEL]    -102 unref_node                 -102  [DEL]
      [DEL]     -89 [Unmapped]                  -89  [DEL]
      [DEL]     -58 gpr_avl_add                 -58  [DEL]
      [DEL]     -58 gpr_avl_remove              -58  [DEL]
      [DEL]     -38 gpr_avl_ref                 -38  [DEL]
      [DEL]      -9 gpr_avl_is_empty             -9  [DEL]
      [DEL]      -6 gpr_avl_create               -6  [DEL]
      [DEL]      -5 gpr_avl_unref                -5  [DEL]

  +0.0%    +160 TOTAL                      +536  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                               FILE SIZE
 ++++++++++++++ GROWING                 ++++++++++++++
  [NEW] +2.43Ki src/core/lib/avl/avl.cc +2.43Ki  [NEW]
      [NEW]    +943 rebalance                  +943  [NEW]
      [NEW]    +517 remove_key                 +517  [NEW]
      [NEW]    +318 add_key                    +318  [NEW]
      [NEW]    +132 new_node                   +132  [NEW]
      [NEW]    +110 grpc_avl_maybe_get         +110  [NEW]
      [NEW]    +104 grpc_avl_get               +104  [NEW]
      [NEW]    +102 unref_node                 +102  [NEW]
      [NEW]     +89 [Unmapped]                  +89  [NEW]
      [NEW]     +58 grpc_avl_add                +58  [NEW]
      [NEW]     +58 grpc_avl_remove             +58  [NEW]
      [NEW]     +38 grpc_avl_ref                +38  [NEW]
      [NEW]      +9 grpc_avl_is_empty            +9  [NEW]
      [NEW]      +6 grpc_avl_create              +6  [NEW]
      [NEW]      +5 grpc_avl_unref               +5  [NEW]
  +0.0%    +160 [None]                     +536  +0.0%

 -------------- SHRINKING               --------------
  [DEL] -2.43Ki src/core/lib/gpr/avl.cc -2.43Ki  [DEL]
      [DEL]    -943 rebalance                  -943  [DEL]
      [DEL]    -517 remove_key                 -517  [DEL]
      [DEL]    -318 add_key                    -318  [DEL]
      [DEL]    -132 new_node                   -132  [DEL]
      [DEL]    -110 gpr_avl_maybe_get          -110  [DEL]
      [DEL]    -104 gpr_avl_get                -104  [DEL]
      [DEL]    -102 unref_node                 -102  [DEL]
      [DEL]     -89 [Unmapped]                  -89  [DEL]
      [DEL]     -58 gpr_avl_add                 -58  [DEL]
      [DEL]     -58 gpr_avl_remove              -58  [DEL]
      [DEL]     -38 gpr_avl_ref                 -38  [DEL]
      [DEL]      -9 gpr_avl_is_empty             -9  [DEL]
      [DEL]      -6 gpr_avl_create               -6  [DEL]
      [DEL]      -5 gpr_avl_unref                -5  [DEL]

  +0.0%    +160 TOTAL                      +536  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                               FILE SIZE
 ++++++++++++++ GROWING                 ++++++++++++++
  [NEW] +2.43Ki src/core/lib/avl/avl.cc +2.43Ki  [NEW]
      [NEW]    +943 rebalance                  +943  [NEW]
      [NEW]    +517 remove_key                 +517  [NEW]
      [NEW]    +318 add_key                    +318  [NEW]
      [NEW]    +132 new_node                   +132  [NEW]
      [NEW]    +110 grpc_avl_maybe_get         +110  [NEW]
      [NEW]    +104 grpc_avl_get               +104  [NEW]
      [NEW]    +102 unref_node                 +102  [NEW]
      [NEW]     +89 [Unmapped]                  +89  [NEW]
      [NEW]     +58 grpc_avl_add                +58  [NEW]
      [NEW]     +58 grpc_avl_remove             +58  [NEW]
      [NEW]     +38 grpc_avl_ref                +38  [NEW]
      [NEW]      +9 grpc_avl_is_empty            +9  [NEW]
      [NEW]      +6 grpc_avl_create              +6  [NEW]
      [NEW]      +5 grpc_avl_unref               +5  [NEW]
  +0.0%    +160 [None]                     +536  +0.0%

 -------------- SHRINKING               --------------
  [DEL] -2.43Ki src/core/lib/gpr/avl.cc -2.43Ki  [DEL]
      [DEL]    -943 rebalance                  -943  [DEL]
      [DEL]    -517 remove_key                 -517  [DEL]
      [DEL]    -318 add_key                    -318  [DEL]
      [DEL]    -132 new_node                   -132  [DEL]
      [DEL]    -110 gpr_avl_maybe_get          -110  [DEL]
      [DEL]    -104 gpr_avl_get                -104  [DEL]
      [DEL]    -102 unref_node                 -102  [DEL]
      [DEL]     -89 [Unmapped]                  -89  [DEL]
      [DEL]     -58 gpr_avl_add                 -58  [DEL]
      [DEL]     -58 gpr_avl_remove              -58  [DEL]
      [DEL]     -38 gpr_avl_ref                 -38  [DEL]
      [DEL]      -9 gpr_avl_is_empty             -9  [DEL]
      [DEL]      -6 gpr_avl_create               -6  [DEL]
      [DEL]      -5 gpr_avl_unref                -5  [DEL]

  +0.0%    +160 TOTAL                      +536  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                               FILE SIZE
 ++++++++++++++ GROWING                 ++++++++++++++
  [NEW] +2.43Ki src/core/lib/avl/avl.cc +2.43Ki  [NEW]
      [NEW]    +943 rebalance                  +943  [NEW]
      [NEW]    +517 remove_key                 +517  [NEW]
      [NEW]    +318 add_key                    +318  [NEW]
      [NEW]    +132 new_node                   +132  [NEW]
      [NEW]    +110 grpc_avl_maybe_get         +110  [NEW]
      [NEW]    +104 grpc_avl_get               +104  [NEW]
      [NEW]    +102 unref_node                 +102  [NEW]
      [NEW]     +89 [Unmapped]                  +89  [NEW]
      [NEW]     +58 grpc_avl_add                +58  [NEW]
      [NEW]     +58 grpc_avl_remove             +58  [NEW]
      [NEW]     +38 grpc_avl_ref                +38  [NEW]
      [NEW]      +9 grpc_avl_is_empty            +9  [NEW]
      [NEW]      +6 grpc_avl_create              +6  [NEW]
      [NEW]      +5 grpc_avl_unref               +5  [NEW]
  +0.0%    +160 [None]                     +528  +0.0%

 -------------- SHRINKING               --------------
  [DEL] -2.43Ki src/core/lib/gpr/avl.cc -2.43Ki  [DEL]
      [DEL]    -943 rebalance                  -943  [DEL]
      [DEL]    -517 remove_key                 -517  [DEL]
      [DEL]    -318 add_key                    -318  [DEL]
      [DEL]    -132 new_node                   -132  [DEL]
      [DEL]    -110 gpr_avl_maybe_get          -110  [DEL]
      [DEL]    -104 gpr_avl_get                -104  [DEL]
      [DEL]    -102 unref_node                 -102  [DEL]
      [DEL]     -89 [Unmapped]                  -89  [DEL]
      [DEL]     -58 gpr_avl_add                 -58  [DEL]
      [DEL]     -58 gpr_avl_remove              -58  [DEL]
      [DEL]     -38 gpr_avl_ref                 -38  [DEL]
      [DEL]      -9 gpr_avl_is_empty             -9  [DEL]
      [DEL]      -6 gpr_avl_create               -6  [DEL]
      [DEL]      -5 gpr_avl_unref                -5  [DEL]

  +0.0%    +160 TOTAL                      +528  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                               FILE SIZE
 ++++++++++++++ GROWING                 ++++++++++++++
  [NEW] +2.43Ki src/core/lib/avl/avl.cc +2.43Ki  [NEW]
      [NEW]    +943 rebalance                  +943  [NEW]
      [NEW]    +517 remove_key                 +517  [NEW]
      [NEW]    +318 add_key                    +318  [NEW]
      [NEW]    +132 new_node                   +132  [NEW]
      [NEW]    +110 grpc_avl_maybe_get         +110  [NEW]
      [NEW]    +104 grpc_avl_get               +104  [NEW]
      [NEW]    +102 unref_node                 +102  [NEW]
      [NEW]     +89 [Unmapped]                  +89  [NEW]
      [NEW]     +58 grpc_avl_add                +58  [NEW]
      [NEW]     +58 grpc_avl_remove             +58  [NEW]
      [NEW]     +38 grpc_avl_ref                +38  [NEW]
      [NEW]      +9 grpc_avl_is_empty            +9  [NEW]
      [NEW]      +6 grpc_avl_create              +6  [NEW]
      [NEW]      +5 grpc_avl_unref               +5  [NEW]
  +0.0%    +160 [None]                     +528  +0.0%

 -------------- SHRINKING               --------------
  [DEL] -2.43Ki src/core/lib/gpr/avl.cc -2.43Ki  [DEL]
      [DEL]    -943 rebalance                  -943  [DEL]
      [DEL]    -517 remove_key                 -517  [DEL]
      [DEL]    -318 add_key                    -318  [DEL]
      [DEL]    -132 new_node                   -132  [DEL]
      [DEL]    -110 gpr_avl_maybe_get          -110  [DEL]
      [DEL]    -104 gpr_avl_get                -104  [DEL]
      [DEL]    -102 unref_node                 -102  [DEL]
      [DEL]     -89 [Unmapped]                  -89  [DEL]
      [DEL]     -58 gpr_avl_add                 -58  [DEL]
      [DEL]     -58 gpr_avl_remove              -58  [DEL]
      [DEL]     -38 gpr_avl_ref                 -38  [DEL]
      [DEL]      -9 gpr_avl_is_empty             -9  [DEL]
      [DEL]      -6 gpr_avl_create               -6  [DEL]
      [DEL]      -5 gpr_avl_unref                -5  [DEL]

  +0.0%    +160 TOTAL                      +528  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Pull request merged**
