### PR TITLE
Upgrade bazel to 3.7.1 (repository-wide)

### PR DESCRIPTION
**Pull request by jtattermusch**
Same as #24981, but this time done properly.

### CODE REVIEW

**Review by lidizheng — APPROVED** [review]
Thanks for the update. Just found out these scripts.

All Bazel related tests are passing.

**Comment by gnossen** [comment]
@jtattermusch Shouldn't CI have failed as a result of these values going out of sync?

**Review by gnossen — APPROVED** [review]

**Comment by lidizheng** [comment]
Both 2.2.0 and 3.7.1 compile fine with gRPC hid the problem. E.g., the Sanity test still uses 2.2.0. In other tests, Bazel was reinstalled.

**Comment by jtattermusch** [comment]
> @jtattermusch Shouldn't CI have failed as a result of these values going out of sync?

We don't have a sanity test in place for these (which seems to be an opportunity for improvement).

**Comment by jtattermusch** [comment]
The android failure is unrelated 
https://source.cloud.google.com/results/invocations/f90e284c-eaff-404b-a8cb-825dbd901565/log

**Pull request merged**
