### PR TITLE
enable server compression tests for grpc.aspnetcore.server

### PR DESCRIPTION
**Pull request by jtattermusch**
Followup for https://github.com/grpc/grpc/pull/20076/files

@JamesNK

### CODE REVIEW

**Comment by JamesNK** [comment]
Will it be possible to ever enable google_default_credentials and compute_engine_channel_credentials?

**Comment by jtattermusch** [comment]
> Will it be possible to ever enable google_default_credentials and compute_engine_channel_credentials?

Theoretically yes, but it would be quite a big project. The other auth interop tests already cover the cases for authentication from GCE and using Application Default Credentials. What's special about `google_default_credentials` and `compute_engine_channel_credentials` is the "transport auto-selection" feature:
> Note: the term GoogleDefaultCredentials within the context of this test description refers to an API which encapsulates both "transport credentials" and "call credentials" and which is capable of transport creds auto-selection (including ALTS). Similar APIs involving only auto-selection of OAuth mechanisms might work for this test but aren't the intended subjects.
(see https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#google_default_credentials)

So unless the managed client implements transports like ALTS (and some other advanced features), the two tests cannot really implemented (or they would only be testing what's already tested by other tests and they would be pointless).

**Comment by JamesNK** [comment]
Ok! Will leave those ones out then.

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/20095

**Pull request merged**
