### PR TITLE
Using embedded OpenSSL only if we really don't have a system version.

### LINKED ISSUE #2602: Make OpenSSL embedding strictly opt-in
Our makefile should have users pass a flag, like EMBED_OPENSSL=1 to trigger the embedded OpenSSL, rather than it being the somewhat default, out-of-the-box behavior.

### PR DESCRIPTION
**Pull request by nicolasnoble**
Fixes #2602.

### CODE REVIEW

**Comment by ctiller** [comment]
This looks like it needs more work.

**Comment by nicolasnoble** [comment]
Do I hate stuff that doesn't behave the same way from my machine... :-P

**Comment by jcanizales** [comment]
Don't forget to default to embeded OpenSSL on Mac OS. Mac's installed OpenSSL is deprecated and dangerous.

**Comment by ctiller** [comment]
Please make this mergable?

**Comment by ctiller** [comment]
This would still be good to have

**Pull request closed without merging**
