### PR TITLE
Code clean-up in client_channel.

### PR DESCRIPTION
**Pull request by markdroth**
Replace an enum with a bool and split the code for canceling a pick into its own function.

No functional changes here.

### CODE REVIEW

**Comment by ctiller** [comment]
I'd like to see the bm_diff before approving (pending #10852)

**Comment by ctiller** [comment]
Jenkins: test this please

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Comment by markdroth** [comment]
This should fix #10945.

**Comment by markdroth** [comment]
Jenkins: test this please

**Comment by markdroth** [comment]
Known failures: #9542 #10936 #10839 #10962

**Comment by Zazakas** [comment]
Hi I'm using gcc 4.8.4 and the lates 1.4.x branch got:
src/core/ext/filters/client_channel/client_channel.c: In function ‘lookup_external_connectivity_watcher’:
src/core/ext/filters/client_channel/client_channel.c:1459:40: error: declaration of ‘on_complete’ shadows a global declaration [-Werror=shadow]
src/core/ext/filters/client_channel/client_channel.c:1243:13: error: shadowed declaration is here [-Werror=shadow]

is it a related bug or it has somthing to with my own cofiguration?

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/i686-pc-linux-gnu/4.8.4/lto-wrapper
Target: i686-pc-linux-gnu
Configured with: ../configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 4.8.4 (GCC)

**Comment by markdroth** [comment]
@Zazakas, that looks like it's a code portability problem, not something related to your configuration, although I'm somewhat mystified as to how that could happen, because our portability checks should have prevented it.  @dgquintas may know more.

In any case, I don't think this is related to this PR, so I suggest filing a separate bug about it.

**Pull request merged**
