### PR TITLE
Fix interop_matrix commands for csharp v1.2.5

### PR DESCRIPTION
**Pull request by jtattermusch**
The build destination has changed since v1.2.5, 
commands are the same as csharp__master, but end with bin/Debug instead of bin/Debug/net45

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Only influences interop matrix tests and those are not being tested per PR (and I've tested locally). Merging.

**Pull request merged**
