### PR TITLE
Remove redundant ExecCtx

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                FILE SIZE
 ++++++++++++++ GROWING                                  ++++++++++++++

 -------------- SHRINKING                                --------------
  -0.0%     -24 [None]                                      -352  -0.0%
  -1.9%    -160 src/core/lib/surface/completion_queue.cc    -160  -1.9%
     -37.9%    -167 cq_event_queue_pop                          -167 -37.9%

  -0.0%    -184 TOTAL                                       -512  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] Performance differences noted:
Benchmark     cpu_time    real_time
------------  ----------  -----------
BM_EmptyCore  -5%         -5%
BM_Pass1Cpp   -5%         -5%
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                FILE SIZE
 ++++++++++++++ GROWING                                  ++++++++++++++

 -------------- SHRINKING                                --------------
  -0.0%     -24 [None]                                      -352  -0.0%
  -1.9%    -160 src/core/lib/surface/completion_queue.cc    -160  -1.9%
     -37.9%    -167 cq_event_queue_pop                          -167 -37.9%

  -0.0%    -184 TOTAL                                       -512  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by yang-g** [comment]
Test flakes #15310 #15311

**Pull request merged**
