### PR TITLE
Actually record CPU usage in Python Benchmark worker

### PR DESCRIPTION
**Pull request by gnossen**
The Python benchmark work has been reporting [a phony CPU usage of 200%](https://github.com/grpc/grpc/blob/7c5e3267981b5cdef015438040ad6d5e62ff4044/src/python/grpcio_tests/tests/qps/worker_server.py#L61) for... [7 years](https://github.com/grpc/grpc/commit/0482c1046b837be17c3a056af6569d84b8f52c23)? Hoo boy.

nZ9zVvSWqJcDEj5

This PR actually collects and reports CPU usage.

### CODE REVIEW

**Comment by gnossen** [comment]
[Manually triggered run](https://fusion2.corp.google.com/ci/kokoro/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_e2e_performance_gke_experiment/activity/dadc4c1b-6b34-4d7e-903d-812749c7873d/summary)

**Comment by gnossen** [comment]
[Manual run](https://fusion2.corp.google.com/ci/kokoro/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_e2e_performance_gke_experiment/activity/d2c15d4d-8023-4c4a-92ed-910568a1e30d/summary) based on `3afa5cf`

**Comment by gnossen** [comment]
Results:

```
I1104 20:59:09.877816325       9 report.cc:82]               QPS: 148.5
I1104 20:59:09.878776316       9 report.cc:122]              QPS: 148.5 (18.6/server core)
I1104 20:59:09.878802176       9 report.cc:127]              Latencies (50/90/95/99/99.9%-ile): 6647.2/7525.4/7873.8/8860.0/13707.2 us
I1104 20:59:09.878808590       9 report.cc:137]              Server system time: 36.62%
I1104 20:59:09.878813310       9 report.cc:139]              Server user time:   37.34%
I1104 20:59:09.878819071       9 report.cc:141]              Client system time: 16.66%
I1104 20:59:09.878825039       9 report.cc:143]              Client user time:   27.87%
I1104 20:59:09.878830492       9 report.cc:148]              Server CPU usage: 0.00%
I1104 20:59:09.878834481       9 report.cc:153]              Client Polls per Request: 0.00
I1104 20:59:09.878838815       9 report.cc:155]              Server Polls per Request: 0.00
I1104 20:59:09.878844102       9 report.cc:160]              Server Queries/CPU-sec: 200.76
I1104 20:59:09.878848771       9 report.cc:162]              Client Queries/CPU-sec: 333.52
```

**Comment by gnossen** [comment]
On closer inspection, it looks like `server_cpu_usage` is not driving any of the graphs. I think this is good to go.

**Comment by gnossen** [comment]
The distribtest failure is unrelated: https://github.com/pypa/wheel/issues/485

**Comment by gnossen** [comment]
CC @wanlin31

**Comment by XuanWang-Amos** [comment]
200%? Guess we need borrow some CPU in order to run gRPC lol

**Review by XuanWang-Amos — APPROVED** [review]

**Pull request merged**
