### PR TITLE
Fix asan failure in fake_resolver_test.

### LINKED ISSUE #14581: Bazel test failure: fake_resolver_test fails under asan
https://source.cloud.google.com/results/invocations/64d73663-79a0-4be0-a67c-545146761a49/targets/%2F%2Ftest%2Fcore%2Fclient_channel%2Fresolvers:fake_resolver_test@poller%3Depoll1/log

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #14581.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Both of the test failures look like infrastructure problems in new tests.

**Pull request merged**
