### PR TITLE
Simply LB policy refcounting, again.

### PR DESCRIPTION
**Pull request by markdroth**
Re-attempting #13857 with a bug fix.  The fix is in commit 83d5cd6; the other commit is just the revert of the revert of the previous PR.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++
  +2.0%     +96 src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc                   +96  +2.0%
      [NEW]    +481 pf_shutdown_locked                                                                      +481  [NEW]
      [NEW]    +274 pf_cancel_pick_locked                                                                   +274  [NEW]
      [NEW]    +103 pf_pick_locked                                                                          +103  [NEW]
       +32%     +34 [Unmapped]                                                                               +34   +32%
      +1.1%     +16 pf_connectivity_changed_locked                                                           +16  +1.1%
      +1.0%      +3 pf_cancel_picks_locked                                                                    +3  +1.0%

 -------------- SHRINKING                                                                            --------------
  -0.1%    -704 [None]                                                                               -7.05Ki  -0.1%
  -6.2%    -928 src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.cc                          -928  -6.2%
      [DEL]    -801 build_lb_channel_args(grpc_lb_addresses const*, grpc_fake_resolver_response_generato    -801  [DEL]
      [DEL]    -708 glb_pick_locked                                                                         -708  [DEL]
      [DEL]    -693 pick_from_internal_rr_locked                                                            -693  [DEL]
      [DEL]    -590 glb_shutdown_locked                                                                     -590  [DEL]
      [DEL]    -433 wrapped_rr_closure                                                                      -433  [DEL]
      [DEL]    -314 glb_cancel_pick_locked                                                                  -314  [DEL]
      [DEL]    -150 add_pending_pick                                                                        -150  [DEL]
     -55.4%    -134 glb_ping_one_locked                                                                     -134 -55.4%
      [DEL]    -119 glb_rr_connectivity_changed_locked                                                      -119  [DEL]
      [DEL]    -113 initial_metadata_add_lb_token                                                           -113  [DEL]
      -4.5%     -72 rr_handover_locked(glb_lb_policy*) [clone .part.8]                                       -72  -4.5%
     -10.9%     -45 [Unmapped]                                                                               -45 -10.9%
 -22.5%    -144 src/core/ext/filters/client_channel/lb_policy.cc                                        -144 -22.5%
      [DEL]     -60 grpc_lb_policy_weak_unref                                                                -60  [DEL]
     -43.2%     -51 grpc_lb_policy_unref                                                                     -51 -43.2%
     -13.1%     -19 [Unmapped]                                                                               -19 -13.1%
      [DEL]     -19 shutdown_locked                                                                          -19  [DEL]
      [DEL]      -7 grpc_lb_policy_weak_ref                                                                   -7  [DEL]
      [DEL]      -6 grpc_lb_policy_pick_locked                                                                -6  [DEL]
      [DEL]      -6 grpc_lb_policy_cancel_pick_locked                                                         -6  [DEL]
     -10.0%      -1 grpc_lb_policy_ref                                                                        -1 -10.0%
  -0.8%    -112 src/core/ext/filters/client_channel/client_channel.cc                                   -112  -0.8%
     -46.2%     -74 pick_callback_done_locked                                                                -74 -46.2%
      -8.5%     -61 pick_callback_start_locked                                                               -61  -8.5%
     -16.0%     -59 cc_destroy_call_elem                                                                     -59 -16.0%
      -0.7%      -1 pick_callback_cancel_locked                                                               -1  -0.7%

  -0.1% -1.75Ki TOTAL                                                                                -8.11Ki  -0.1%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_ping_pong.BM_StreamingPingPongMsgs_MinInProcessCHTTP2_NoOpMutator_NoOpMutator__16777216.opt.old: 1


[microbenchmarks] Performance differences noted:
Benchmark                                                       call_initial_size-median
--------------------------------------------------------------  --------------------------
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/1      +7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/1      +8%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/32768/1  +7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/4096/1   +8%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/1    +8%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/1     +7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/1      +8%
```

**Comment by markdroth** [comment]
Known issues: #13477

**Pull request merged**
