### PR TITLE
Adopt OWNERship policy consistent with other CNCF projects

### PR DESCRIPTION
**Pull request by vjpai**
- OWNERS slows code cleanups
- OWNERS adds constraints beyond what we're used to internally
- OWNERS complicates code reverts
- OWNERS is not compatible with taking a vacation
- Github CODEOWNERS is an anti-pattern, the worst possible model for ownership, and not used by _any_ CNCF-graduated projects (or by grpc/grpc-java or grpc/grpc-go)
- OWNERS gotta get guillotined

### CODE REVIEW

**Comment by vjpai** [comment]
- OWNERS is another obstacle to deal with when people change teams (one of the auto-added reviewers for this PR is about to leave the team)

**Comment by vjpai** [comment]
If anyone has even one rational argument in favor of OWNERS, please state it.

**Comment by vjpai** [comment]
Let me anticipate a meta-argument

@vjpai, You claim that "OWNERS adds constraints beyond what we're used to internally," but the gRFC process already does that to us and you've been an advocate for it's expansion. How do you reconcile those arguments?

My response: The gRFC process exists because we and all our users don't exist in a [mono-repo](https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext) in the OSS world. As a result, we can't make changes and test their behavior across all possible targets. This is particularly true for [core](https://github.com/grpc/proposal/blob/444b7030b19f634e650c5d16ffcd421ad585d53c/P3-grfcs-for-core-api-changes.md) where we actually allow ourselves to make breaking changes (since it's a semantically versioned public API meant for implementers, not a stable public API meant for developers). Additionally, the common thread here is product excellence. Facilitating rapid code cleanups and rapid reverts of buggy or destabilizing code improves product excellence. Facilitating rapid API growth and/or breakage degrades product excellence.

**Comment by vjpai** [comment]
This is not a troll PR.

**Comment by vjpai** [comment]
I asked for rational arguments; appeals to recent history are not that.

**Comment by vjpai** [comment]
BTW, the discussion that @markdroth cites in his comment refers to #16534 and its comment section.

**Comment by jtattermusch** [comment]
I know that github's implementation of CODEOWNERS has some (relatively serious) flaws, but I still think there are some directories that are worth protecting (e.g. some of the test infrastructure directories tend to get modified in broken ways unless there's some oversight).

Perhaps the best next move on our side to be actually put together the complaints around complaints of CODEOWNERS implementation, make sure they are files as issues for github.com and try to convince github to fix them.
- the biggest issue from my perspective is  that if I'm already an owner for a subdirectory, I should only need an approval from any other contributor (as opposed to needing another OWNER's approval).

**Comment by vjpai** [comment]
The existence of CODEOWNERS is incompatible with healthy development practices like vacations. Right now we have at least one PR (#17932) that is blocked because the owner who did a review and wrote the words LGTM without clicking the green approval button went on vacation.

**Comment by vjpai** [comment]
CODEOWNERS is a self-inflicted wound. It is perhaps unique among obstacles by delaying both development velocity and revert velocity.

**Comment by vjpai** [comment]
@jtattermusch So right now we're protecting some test infrastructure directories, but we're not protecting the actual unit tests or end2end tests at all. There is nothing in our current setup that would prevent a committer from deleting all of test/core and test/cpp, for example. We're relying on the fact that members of the org are vetted and that reverts are possible (and encouraged) when things go awry. The existence of OWNERS hasn't prevented build and test infrastructure from breaking from time to time. It's just delayed reverts when we realize that things are broken.

**Comment by vjpai** [comment]
#17932 is a good example of why OWNERship makes no sense. It is an overly blunt instrument. Even if you concede that a particular directory should be owned by those who understand its logic (a point that I do not concede), that particular PR had no impact on the logic of the directory. It was a pure code cleanup, yet nevertheless had to go through ownership. The rational basis for the review would have been based on knowledge of concurrency, not knowledge of core logic. But of course, OWNERship complicated both its approval and its unrelated revert.

**Comment by vjpai** [comment]
kubernetes/kubernetes has their own notion of OWNERS. They do not use Github CODEOWNERS. Rather, they use their own bot that assigns 2 reviewers from the OWNER list (even if there are 20 named owners). Once any reviewer has given it an LGTM, the bot assigns an approver from the OWNER list -- unless the PR was created by an approver, in which case it is already approved. The kubernetes policy is still not what I'd ideally seek, but it much better than the default Github CODEOWNERS.

**Comment by vjpai** [comment]
Counterargument to my note above about other CNCF projects. "If all your friends jumped off a bridge, would you do it too?" Response: Unfortunately, grpc/grpc is the bridge jumper in this scenario. We jumped into the Github CODEOWNERS lake even though it was still not really ready for prime time. The other projects were the wiser heads here.

**Comment by vjpai** [comment]
A subscriber suggested that I attach the following: 
image

**Comment by nicolasnoble** [comment]
I believe this is now resolved?

**Pull request closed without merging**
