### PR TITLE
Clean way to enable C and C++ standards in cmake

### PR DESCRIPTION
**Pull request by jtattermusch**
Use a more portable way to use C++11 standard.

Also see https://github.com/google/protobuf/pull/4550.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
see https://github.com/grpc/grpc/issues/14862

**Comment by jtattermusch** [comment]
Let's leave this open.

**Comment by jtattermusch** [comment]
@veblush  I revived this old PR, please review.

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/22019

**Pull request merged**
