### PR TITLE
Update Go interop image to go1.11

### PR DESCRIPTION
**Pull request by jtattermusch**
Fixes https://github.com/grpc/grpc/issues/16604,  

updated the image, regenerated and pushed with `tools/dockerfile/push_testing_images.sh`.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,966,317      Total (=)      1,966,317

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,909,770      Total (<)     10,909,775

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by dfawley** [comment]
Doesn't this make things worse?  I don't claim to understand the test infrastructure, but I *believe* this Dockerfile is used for the ongoing interop tests which build grpc-go from HEAD.  For this purpose, using golang:latest, as it is before this change, seems to make the most sense to me.

My concern in #16604 is that for the compatibility test matrix, we currently enumerate the Go docker images as a matrix of <Go version> x <grpc-go version>.  The go versions supported by that script are 1.7 and 1.8, which will not be supported by new versions of grpc-go.  What we really want is not a matrix, but a flat list of images.  Newly created docker images for new versions of grpc-go should use Go 1.11 (or golang:latest maybe, if that gets captured when the image is created??), and we should be able to enumerate all the existing images in the client_matrix.py script.

**Comment by apolcyn** [comment]
> Doesn't this make things worse? I don't claim to understand the test infrastructure, but I believe this Dockerfile is used for the ongoing interop tests which build grpc-go from HEAD. For this purpose, using golang:latest, as it is before this change, seems to make the most sense to me.

Personally I would go with this PR as I think this it's an improvement.

Note there are two parts to the interop client docker image build:
* the base docker image - this is the part of the docker image that has a grpc interop client's dependencies, but not the actual interop client.
* the full interop image with the actual interop client - on top of a base image with dependencies, we get the relevant grpc client into a container off of the base image, compile it, and commit that that container into a new image which has the actual compiled interop client - https://github.com/grpc/grpc/blob/master/tools/run_tests/dockerize/build_interop_image.sh#L119. This second piece is repeatedly rebuilt during tests to test the clients at HEAD.

The "base docker image" is built once, stored (cached) in dockerhub, and then fetched and reused repeatedly during tests... so there's no defined "re-build" time for this base docker image. If we rely on "latest" in the base docker image, then we could wind up in situation where the base image was built two years ago and includes a now-unsupported go version even though it used to be "latest". Forcing a certain version is IMO more explicit and easier to reason about.

**Comment by apolcyn** [comment]
> Is the Dockerfile stored along with the docker image produced from it? Or does the Dockerfile just specify how to create the image, and we save only the image itself?

Only the docker image is cached in dockerhub. The dockerfile describes how to build the image, but there's no need to store it. Note that name of the docker image as stored in dockerhub includes the sha1 of the dockerfile, so in that way each dockerfile is exactly one-to-one with a cached docker image.

> I'd really prefer for the regularly-running tests that build grpc-go from HEAD to use the latest golang version as well. Otherwise we'll have to increment it at every golang release (or eventually break). If there's any confusion, we should run go version at the start of all the tests so it's obvious what version of Go is stored in the docker image (and ideally name the image accordingly as well).

Ack. But note that using "latest" doesn't fix this because the built image's sha1 will never change and so it will cache hit indefinitely. Running `go version` and checking it against the latest go release could perhaps be done as a part of the [go interop client invocation](https://github.com/grpc/grpc/blob/master/tools/run_tests/run_interop_tests.py#L267), but that check would need some way of knowing what the latest release is. One possible idea to automatically keep the go version up to date with the current year's release: maybe some kind of github bit could file an issue once per year, or perhaps even create a PR to update the go version once per year.

**Comment by dfawley** [comment]
> Only the docker image is cached in dockerhub. The dockerfile describes how to build the image, but there's no need to store it. Note that name of the docker image as stored in dockerhub includes the sha1 of the dockerfile, so in that way each dockerfile is exactly one-to-one with a cached docker image.

Interesting.  So for every Go release, we need to modify this file and build a new image?  Is this hashing part of how dockerhub works, or are we using that convention?

Another option could be to not install Go at all in the image and have it install Go at the start of each test run.  (This is how Travis works, and there's an open source script called `gimme` that makes it easy to install Go: just run `gimme stable`.)

**Comment by jtattermusch** [comment]
@dfawley the change from `golang:latest` to `golang:1.11` doesn't really change the fact that the go version will stay the same in the testing image unless the testing image is rebuilt and pushed - that's the way our testing framework currently works. Changing to 1.11 only triggers that change and makes it explicit that the go version is actually static (so it's an improvement).
This PR is only to upgrade go to 1.11 in interop tests, to mitigate the danger that interop tests will stop working soon (as suggested #16604).

We can discuss how interop testing should be done in the future separately from this PR, but please note that there are some limitations:
- there is a lot of background of why things are setup the way they are (both historical reasons and experience what works and what does not).
- we need to maintain consistency between languages - we can't have special behavior for each language because otherwise maintaining this will become a nightmare.
- overhauling stuff means work and more work to then validate the new solution and fix unexpected problems. we don't currently have any bandwidth for any such work beyond what's absolutely necessary, so we need to be very careful in terms of what we sign up for. Help is welcome ;-). 

Btw, I agree with some of the complaints about the interop backward compatibility matrix  - I will try to dedicate some effort to improving the backward compatibility matrix scripts.

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/16922

**Comment by dfawley** [comment]
@jtattermusch all that sounds good.  Thanks for fixing this.  I'll file a new issue about the backward compatibility scripts since they will not work for our release in 7 weeks.

**Pull request merged**
