### PR TITLE
Fix Internal Fuzzer Error

### PR DESCRIPTION
**Pull request by ncteisen**
This fixes internal bug 100073361

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                               FILE SIZE
 ++++++++++++++ GROWING                                 ++++++++++++++
  +0.0%     +56 [None]                                  +4.08Ki  +0.0%
   +30%     +48 src/core/lib/security/util/json_util.cc     +48   +30%
       +42%     +48 grpc_json_get_string_property               +48   +42%

  +0.0%    +104 TOTAL                                   +4.12Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Bazel: #15610 
MacOS: #14673 
Interop: #15673

**Pull request merged**
