### PR TITLE
Fix LB policy name case handling.

### PR DESCRIPTION
**Pull request by markdroth**
Don't convert JSON LB policy name in LoadBalancingConfig from camelCase to lower_case.
Do convert old LoadBalancingPolicy name to lower-case.

cc @ejona86 @dfawley

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.7%     -48 src/core/ext/filters/client_channel/resolver_result_parsing.cc                           -48  -0.7%
      [DEL]    -260 grpc_core::internal::(anonymous namespace)::ParseDuration(grpc_json*, long*) [clone     -260  [DEL]
     -32.3%    -169 grpc_core::internal::ProcessedResolverResult::ParseLbConfigFromServiceConfig            -169 -32.3%
      [DEL]    -111 void grpc_core::ServiceConfig::ParseGlobalParams<grpc_core::internal::ProcessedResol    -111  [DEL]

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -72 [None]                                                                                  +232  +0.0%

  -0.0%    -120 TOTAL                                                                                   +184  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,734      Total (>)      2,019,718

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,119      Total (<)     11,154,120

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.7%     -48 src/core/ext/filters/client_channel/resolver_result_parsing.cc                           -48  -0.7%
      [DEL]    -260 grpc_core::internal::(anonymous namespace)::ParseDuration(grpc_json*, long*) [clone     -260  [DEL]
     -32.3%    -169 grpc_core::internal::ProcessedResolverResult::ParseLbConfigFromServiceConfig            -169 -32.3%
      [DEL]    -111 void grpc_core::ServiceConfig::ParseGlobalParams<grpc_core::internal::ProcessedResol    -111  [DEL]

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -72 [None]                                                                                  +232  +0.0%

  -0.0%    -120 TOTAL                                                                                   +184  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.7%     -48 src/core/ext/filters/client_channel/resolver_result_parsing.cc                           -48  -0.7%
      [DEL]    -260 grpc_core::internal::(anonymous namespace)::ParseDuration(grpc_json*, long*) [clone     -260  [DEL]
     -32.3%    -169 grpc_core::internal::ProcessedResolverResult::ParseLbConfigFromServiceConfig            -169 -32.3%
      [DEL]    -111 void grpc_core::ServiceConfig::ParseGlobalParams<grpc_core::internal::ProcessedResol    -111  [DEL]

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -72 [None]                                                                                  +232  +0.0%

  -0.0%    -120 TOTAL                                                                                   +184  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                            FILE SIZE
 ++++++++++++++ GROWING                                                                              ++++++++++++++

 -------------- SHRINKING                                                                            --------------
  -0.7%     -48 src/core/ext/filters/client_channel/resolver_result_parsing.cc                           -48  -0.7%
      [DEL]    -260 grpc_core::internal::(anonymous namespace)::ParseDuration(grpc_json*, long*) [clone     -260  [DEL]
     -32.3%    -169 grpc_core::internal::ProcessedResolverResult::ParseLbConfigFromServiceConfig            -169 -32.3%
      [DEL]    -111 void grpc_core::ServiceConfig::ParseGlobalParams<grpc_core::internal::ProcessedResol    -111  [DEL]

 -+-+-+-+-+-+-+ MIXED                                                                                +-+-+-+-+-+-+-
  -0.0%     -72 [None]                                                                                  +232  +0.0%

  -0.0%    -120 TOTAL                                                                                   +184  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,751      Total (>)      2,019,735

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,115      Total (<)     11,154,124

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.new: 10
    bm_call_create.BM_IsolatedFilter_ClientChannelFilter_NoOp_.counters.old: 10


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 2,019,751      Total (>)      2,019,735

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
11,154,121      Total (<)     11,154,123

 No significant differences in binary sizes


```

**Comment by markdroth** [comment]
Known issues: #17375 #17208

**Pull request merged**
