### PR TITLE
xDS: Add graceful shutdown for old connections on listener resource update

### PR DESCRIPTION
**Pull request by yashykt**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/28154)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
Overall, this looks very good.  The only substantive concern is the one about how the grace time option is plumbed through.

Please let me know if you have any questions.  Thanks!

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28154#-:-MpiBtopAFIrP1m266wn:b-21ublq)* status: all files reviewed, 8 unresolved discussions (waiting on @yashykt)

___
*[include/grpc/grpc.h, line 436 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi2uY0BfPM1DG_RpSr:-Mpi2uY10B99hMF98eAK:b-gxkdbs) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/include/grpc/grpc.h#L436)):*
> ```objc
> /** EXPERIMENTAL.  Creates an xDS config fetcher. */
> GRPCAPI grpc_server_config_fetcher* grpc_server_config_fetcher_xds_create(
>     grpc_server_xds_status_notifier notifier, int drain_grace_time_ms,
> ```

Please update gRFC A36 to show this change.
___
*[include/grpcpp/xds_server_builder.h, line 57 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi3QGLBe1OyiMRG4uz:-Mpi3QGM7A32IvDAeIX1:b-k9ismv) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/include/grpcpp/xds_server_builder.h#L57)):*
> ```objc
>         : ServerBuilder::experimental_type(builder), builder_(builder) {}
> 
>     // TODO(review): ServerBuilder uses the mixed naming style
> ```

I think it's fine to use `set_drain_grace_time()` here.  That seems more correct with respect to the style guide.

I don't actually see `SetDefaultGraceTime()` defined anywhere.  What are you looking at?  (Is there an existing option for this that we can maybe use instead of adding a new one?)
___
*[include/grpcpp/xds_server_builder.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi3WSGESYDMqEeqIST:-Mpi3WSGESYDMqEeqISU:b-a9gc2b) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/include/grpcpp/xds_server_builder.h#L60)):*
> ```objc
>     // `SetDefaultGraceTime` but we already ended up using the variable
>     // `set_status_notifier` below.
>     // TODO(review): Maybe use absl::Duration?
> ```

We aren't yet using absl types in our public API.  That's blocked on @veblush writing a proposal for gRPC public API namespacing.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 559 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi9yWQ9xAzYDYcYvxp:-Mpi9yWQ9xAzYDYcYvxq:bmy9s8r) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/ext/transport/chttp2/server/chttp2_server.cc#L559)):*
> ```cpp
>     GRPC_CLOSURE_INIT(&on_drain_grace_time_expiry_, OnDrainGraceTimeExpiry,
>                       this, nullptr);
>     // TODO(yashykt): Fix the API between the server and the transport listener
> ```

Would it make sense to pass the grace time in via a channel arg instead of making it a method on the config fetcher?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 602 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi5jhk72O5sBQySIpJ:-Mpi5jhk72O5sBQySIpK:b-zduu0j) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/ext/transport/chttp2/server/chttp2_server.cc#L602)):*
> ```cpp
>       }
>     }
>     // Cancel the drain_grace_timer_ if needed.
> ```

Don't we also need to do this in `ActiveConnection::Orphan()`?  Hmm, actually, it looks like `Orphan()` kills any in-flight handshaking but does not trigger a GOAWAY on a the connection if it has already finished handshaking.  Is that what we want?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 615 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi75IT0QEQ9SFnXwST:-Mpi75IT0QEQ9SFnXwSU:b-ewm1sj) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/ext/transport/chttp2/server/chttp2_server.cc#L615)):*
> ```cpp
>   // If the drain_grace_timer_ was not cancelled, disconnect the transport
>   // immediately.
>   if (error == GRPC_ERROR_NONE) {
> ```

What happens if `OnClose()` runs between when the timer schedules this callback and when the callback actually runs?  Will the transport op just be a no-op in that case, or do we need to handle this by resetting `drain_grace_timer_expiry_callback_pending_` when we cancel and checking it here?  (This is problem 4 as described in go/grpc-c-core-closure-slides.)
___
*[src/core/lib/surface/server.h, line 498 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-MpiA7-d5P1iWikyvMQH:-MpiA7-d5P1iWikyvMQI:b47lb6w) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/lib/surface/server.h#L498)):*
> ```objc
>   // The drain grace period in ms for older connections when a new
>   // ConnectionManager is received.
>   virtual int drain_grace_time() = 0;
> ```

If this stays here, suggest calling it `drain_grace_time_ms()`.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9293 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-MpiAmHj336BXQYNs6re:-MpiAmHj336BXQYNs6rf:b-ywlhwl) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/test/cpp/end2end/xds/xds_end2end_test.cc#L9293)):*
> ```cpp
>   // After the drain grace time expires, the existing RPCs should all fail.
>   for (int i = 0; i < kNumChannels; i++) {
>     // Wait for the drain grace time to expire
> ```

How about verifying that we wait the expected amount of time before seeing this failure?

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28154)* status: all files reviewed, 8 unresolved discussions (waiting on @markdroth, @veblush, and @yashykt)

___
*[include/grpc/grpc.h, line 436 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi2uY0BfPM1DG_RpSr:-Mpmn7xH2IDypD-TcHs4:b-d7bhn0) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/include/grpc/grpc.h#L436)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please update gRFC A36 to show this change.
</blockquote></details>

will do
___
*[include/grpcpp/xds_server_builder.h, line 57 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi3QGLBe1OyiMRG4uz:-MpmholAA2R2yr0E2v_W:b72pdh9) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/include/grpcpp/xds_server_builder.h#L57)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I think it's fine to use `set_drain_grace_time()` here.  That seems more correct with respect to the style guide.

I don't actually see `SetDefaultGraceTime()` defined anywhere.  What are you looking at?  (Is there an existing option for this that we can maybe use instead of adding a new one?)
</blockquote></details>

The style guide keeps it optional - ```Accessors and mutators (get and set functions) may be named like variables. These often correspond to actual member variables, but this is not required. For example, int count() and void set_count(int count).

```
So, remaining consistent seems more important.

`SetDefaultGraceTime()` is just what the name would like if we choose to use camel case.
 If you look at server_builder.h, the setter methods use camel case, while the getter methods use variable style... 

I'll remove the TODO, since we are agreeing on preferring the variable style for accessors/mutators.
```

___
*[include/grpcpp/xds_server_builder.h, line 60 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi3WSGESYDMqEeqIST:-MpmnE2K1-jlWjshEl5o:b2nhb2c) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/include/grpcpp/xds_server_builder.h#L60)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We aren't yet using absl types in our public API.  That's blocked on @veblush writing a proposal for gRPC public API namespacing.
</blockquote></details>

Ack
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 559 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi9yWQ9xAzYDYcYvxp:-MpmjlfW77q9tokIZhCU:beu7tzd) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/ext/transport/chttp2/server/chttp2_server.cc#L559)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Would it make sense to pass the grace time in via a channel arg instead of making it a method on the config fetcher?
</blockquote></details>

I considered that. There would be one benefit to using channel args in that we won't need to modify the xds_server_config_fetcher Core API, but we would still need to create a new channel arg type, and then we get into the position where users can either set the drain grace time through the xds server builder by calling set_drain_grace_time or by adding in a channel arg. Hence my preference to just change the config fetcher API.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 602 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi5jhk72O5sBQySIpJ:-MpmlJvg3EFSg6rUSnSp:b-m23dov) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/ext/transport/chttp2/server/chttp2_server.cc#L602)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't we also need to do this in `ActiveConnection::Orphan()`?  Hmm, actually, it looks like `Orphan()` kills any in-flight handshaking but does not trigger a GOAWAY on a the connection if it has already finished handshaking.  Is that what we want?
</blockquote></details>

In the normal case and I'm assuming majority of cases, connections would go away normally (maybe through the idle filter timeout or the clients going away), `chttp2_server` does not need to send a GOAWAY. The transport simply invokes the `OnClose` callback and we remove the connection from our list.

We only need to send GOAWAYs when -
1) There was an LDS update and we want to drain existing connections.
2) The listener resource was deleted and so we need to stop serving and drain existing connections.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 615 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi75IT0QEQ9SFnXwST:-MpmhQA866Z6u-Zkz54A:b-2ibuvn) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/ext/transport/chttp2/server/chttp2_server.cc#L615)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

What happens if `OnClose()` runs between when the timer schedules this callback and when the callback actually runs?  Will the transport op just be a no-op in that case, or do we need to handle this by resetting `drain_grace_timer_expiry_callback_pending_` when we cancel and checking it here?  (This is problem 4 as described in go/grpc-c-core-closure-slides.)
</blockquote></details>

Yes, we leave handling of that race to the transport. We just need to make sure that we hold a ref on the transport while this is going on.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28154)* status: 4 of 9 files reviewed, 8 unresolved discussions (waiting on @markdroth, @veblush, and @yashykt)

___
*[src/core/lib/surface/server.h, line 498 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-MpiA7-d5P1iWikyvMQH:-MpmtUYk57paBGLgGxcT:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/lib/surface/server.h#L498)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If this stays here, suggest calling it `drain_grace_time_ms()`.
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9293 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-MpiAmHj336BXQYNs6re:-MpmtXArBj-7ENHppHBH:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/test/cpp/end2end/xds/xds_end2end_test.cc#L9293)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How about verifying that we wait the expected amount of time before seeing this failure?
</blockquote></details>

Done.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28154)* status: 4 of 9 files reviewed, 8 unresolved discussions (waiting on @markdroth and @veblush)

___
*[include/grpc/grpc.h, line 436 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi2uY0BfPM1DG_RpSr:-Mpmvpcb6Acm6D0vvk74:b-sof2al) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/include/grpc/grpc.h#L436)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

will do
</blockquote></details>

https://github.com/grpc/proposal/pull/280 does it

**Review by markdroth — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28154)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 559 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi9yWQ9xAzYDYcYvxp:-MprWuMUDbYhPGgOgDhJ:b-6brjvn) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/ext/transport/chttp2/server/chttp2_server.cc#L559)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I considered that. There would be one benefit to using channel args in that we won't need to modify the xds_server_config_fetcher Core API, but we would still need to create a new channel arg type, and then we get into the position where users can either set the drain grace time through the xds server builder by calling set_drain_grace_time or by adding in a channel arg. Hence my preference to just change the config fetcher API.
</blockquote></details>

I don't think we'd need a new channel arg type; this would just be an integer.  And if we did it as a channel arg, we wouldn't need the `XdsServerBuilder::set_drain_grace_time()` method in the first place.  Or, alternatively, we could keep that method just as a convenience method that sets the channel arg so that callers don't have to set the channel arg manually.

Passing it through the config fetcher doesn't really seem like a good fit to me.  The config fetcher is really for dynamic values that can change over the lifetime of the server, but this is a constant, fixed at instantiation time.  We typically use channel args for that kind of constant parameter, so I'm not sure why we wouldn't do so here.

Also, I'm trying to think through how we're likely to want this to work when we do the refactoring to decouple the server config fetcher code from the transport listener code.  Which side of that divide will we want this on?  It seems like putting this in the config fetcher now means that if we want to change this later, it will require a gRFC.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9298 at r2](https://reviewable.io/reviews/grpc/grpc/28154#-Mpr_5P76KQOJH8sbSEt:-Mpr_5P76KQOJH8sbSEu:b-iog8s8) ([raw file](https://github.com/grpc/grpc/blob/abe06bb665e2a580285eb6b6dc95315d9614e2cc/test/cpp/end2end/xds/xds_end2end_test.cc#L9298)):*
> ```cpp
>     EXPECT_FALSE(streaming_rpcs[i].stream->Read(&response));
>     // Make sure that the drain grace interval is honored.
>     EXPECT_TRUE(NowFromCycleCounter() - kDrainGraceTimeMs >= update_time);
> ```

Please write this as:

```
EXPECT_GE(NowFromCycleTimer() - update_time, kDrainGraceTimeMs);
```

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28154)* status: 3 of 11 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 559 at r1](https://reviewable.io/reviews/grpc/grpc/28154#-Mpi9yWQ9xAzYDYcYvxp:-MpupCRQBDEb7dJ7JENr:b-yrjndr) ([raw file](https://github.com/grpc/grpc/blob/c5d30576a049e08f0ce645fc158ae942e2089ce3/src/core/ext/transport/chttp2/server/chttp2_server.cc#L559)):*
By a new channel arg type, I meant something like `GRPC_ARG_DRAIN_GRACE_TIME_MS`

> Passing it through the config fetcher doesn't really seem like a good fit to me. The config fetcher is really for dynamic values that can change over the lifetime of the server, but this is a constant, fixed at instantiation time. We typically use channel args for that kind of constant parameter, so I'm not sure why we wouldn't do so here.

>Also, I'm trying to think through how we're likely to want this to work when we do the refactoring to decouple the server config fetcher code from the transport listener code. Which side of that divide will we want this on? It seems like putting this in the config fetcher now means that if we want to change this later, it will require a gRFC.

I think I buy this argument. Adopted.
___
*[test/cpp/end2end/xds/xds_end2end_test.cc, line 9298 at r2](https://reviewable.io/reviews/grpc/grpc/28154#-Mpr_5P76KQOJH8sbSEt:-MpupnvnDOnijUXi0OJn:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/abe06bb665e2a580285eb6b6dc95315d9614e2cc/test/cpp/end2end/xds/xds_end2end_test.cc#L9298)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please write this as:

```
EXPECT_GE(NowFromCycleTimer() - update_time, kDrainGraceTimeMs);
```
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
This looks really good!  Just one minor comment about channel arg naming.

Feel free to merge after addressing.  Thanks!

> Reviewed 6 of 8 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/28154#-:-MpwX6Sh7zbnW-YauEmw:bpyyz2d)* status: all files reviewed, 1 unresolved discussion (waiting on @yashykt)

___
*[include/grpc/impl/codegen/grpc_types.h, line 452 at r4](https://reviewable.io/reviews/grpc/grpc/28154#-MpwWC0w2mRHZ1n9BlS1:-MpwWC0w2mRHZ1n9BlS2:bc2va3r) ([raw file](https://github.com/grpc/grpc/blob/053ef311f9c68fb666a103f51e4a29ad8f5dee33/include/grpc/impl/codegen/grpc_types.h#L452)):*
> ```objc
>  * gracefully shut down (i.e., "drained") with a grace period configured by this
>  * channel arg. Int valued, milliseconds. Defaults to 10 minutes.*/
> #define GRPC_ARG_DRAIN_GRACE_TIME_MS "grpc.experimental.drain_grace_time_ms"
> ```

Suggest calling this something like GRPC_ARG_SERVER_CONFIG_CHANGE_GRACE_TIME_MS, to make it clear that it's used only in that context (e.g., it's not used for normal server shutdown).

**Comment by yashykt** [comment]
Issues: #26886
Thanks for reviewing!

**Pull request merged**
