### PR TITLE
Allow optional building in of objc prefix validation.

### PR DESCRIPTION
**Pull request by thomasvl**
@donnadionne
@veblush

### CODE REVIEW

**Review by dennycd — COMMENTED** [review]
looks like need to run tools/distrib/clang_format_code.sh for formatting. Thanks

**Comment by thomasvl** [comment]
> looks like need to run tools/distrib/clang_format_code.sh for formatting. Thanks

I'm not going to install docker to just run a script, and the script it calls also appears to be linux on.  Manually fixed what I think is the issue.

**Comment by dennycd** [comment]
ruby basic test flake https://github.com/grpc/grpc/issues/28404

**Comment by dennycd** [comment]
known python test failure https://github.com/grpc/grpc/issues/28405

**Review by dennycd — APPROVED** [review]
LGTM, thanks for the patch.

**Comment by dennycd** [comment]
> > looks like need to run tools/distrib/clang_format_code.sh for formatting. Thanks
> 
> I'm not going to install docker to just run a script, and the script it calls also appears to be linux on. Manually fixed what I think is the issue.

thanks, you can also manually run clang-format from grpc source root, which should be able to pick up [.clang-format](https://github.com/grpc/grpc/blob/master/.clang-format)  e.g. 

```
clang-format -i src/compiler/objective_c_plugin.cc 
```

**Comment by thomasvl** [comment]
The _feedback/copybara_ failure info seems to be something else also trying to sync in at the same time.

**Pull request merged**
