### PR TITLE
Added "grpc" to pkg-config --libs

### PR DESCRIPTION
**Pull request by Phantal**
* Added "grpc" to the list of pkg-config libraries needed
* Simplified part of the makefile

@markdroth

### CODE REVIEW

**Comment by markdroth** [comment]
You'll need to sign the CLA before we can look at this.

**Comment by Phantal** [comment]
I went in to see the CLA and it only provides one option: "Select this if
you are contributing code as an employee", which is not the case.

-brian

**Comment by WillsonHG** [comment]
@Phantal  Hi I'm Heather with The Linux Foundation. I wasn't able to find an icla on file through the EasyCLA system. For this pull request to be authorized, you'll need to click the link in the communitybridge-easycla bot comment that says "Please click here to be authorized". You'll choose "individual" and then you'll be taken to the document to sign via Docusign. Once that is complete, your pr will be authorized.

**Comment by Phantal** [comment]
@WillsonHG When I go there it only offers an option to sign as a corporate contributor, not as an individual contributor.

**Comment by WillsonHG** [comment]
@Phantal  that sounds like a UI issue that is not allowing you to scroll down to see the individual option beneath the corporate one. Are you able to try in a different browser?

**Comment by Phantal** [comment]
@WillsonHG Looks like that's sort of right.  In chrome I cannot see it at all; on another computer I pulled it up in Edge and the individual option is partially visible, covered by the blue banner at the bottom of the page.  I'll get it sorted.

**Comment by WillsonHG** [comment]
@Phantal I'm glad you were able to get it working. We'll get that layout fixed, thanks!

**Comment by Phantal** [comment]
I forgot to explain why the change was needed.  When trying to link the application it fails with an undefined symbol reference to **gpr_log**, which is satisfied by libgrpc.so

**Comment by markdroth** [comment]
Nico, can you please review to make sure these changes seem sensible?  Thanks!

**Comment by Phantal** [comment]
So where are we with this pull request?

**Pull request closed without merging**
