### PR TITLE
Fixing trailing metadata ops.

### PR DESCRIPTION
**Pull request by Vizerai**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by ncteisen** [comment]
Is this why grpc_opencensus_plugin_test has been failing consistently since #15070?

I assume this raced with #15782

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by Vizerai** [comment]
Please test this.

**Comment by Vizerai** [comment]
Yes, there was a conflict between  #15070 and  #15782.

The metadata changes in client_filter.cc were overwritten, which was causing grpc_opencensus_plugin_test to fail.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
This has probably fixed https://github.com/grpc/grpc/issues/15815.

**Pull request merged**
