### PR TITLE
[PSM Interop] Resume app_net_ssa_test

### PR DESCRIPTION
**Pull request by sergiitk**

### CODE REVIEW

**Comment by sergiitk** [comment]
- [ ] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/9d36fa7b-f331-427d-82be-1f969c522620)

**Review by gnossen — APPROVED** [review]

**Comment by sergiitk** [comment]
- [ ] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/e3448da3-8370-4db6-81fa-da5c6289ca53)

**Comment by sergiitk** [comment]
- [ ] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/b76b8711-fd95-4853-869c-bfebee32250b)

**Comment by sergiitk** [comment]
- [ ] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/46b7c129-28e2-4115-ab83-19bab9e6812b)

**Comment by sergiitk** [comment]
@gnossen FYI we have a pass!

**Comment by gnossen** [comment]
Ship it!

**Pull request merged**
