### PR TITLE
python 2/3 compatible abstract servicers/stubs

### PR DESCRIPTION
**Pull request by leifurhauks**
a possible solution to #5654 that does not require importing external packages in the pb2 files.

### CODE REVIEW

**Comment by leifurhauks** [comment]
revised to use `six.with_metaclass`.

**Comment by nathanielmanistaatgoogle** [comment]
This is OK to test.

**Comment by leifurhauks** [comment]
I definitely haven't changed any C# code. I think I'll try rebasing, maybe this has been fixed already in master.

**Comment by nathanielmanistaatgoogle** [comment]
Did something happen to regress the code in this pull request to an earlier draft?

**Comment by leifurhauks** [comment]
Arrggghhh, I forgot to pull first, and I pushed my last revision from a different machine >.<
Fortunately that machine is a laptop that is currently right next to me! I'll restore that right away.

**Comment by leifurhauks** [comment]
It's back. I wonder if time travelers use git.

**Comment by jtattermusch** [comment]
Tests are not green, see go/grpc-merge-rules

**Comment by nathanielmanistaatgoogle** [comment]
(/me shakes fist at [issue 5509](https://github.com/grpc/grpc/issues/5509))

**Comment by leifurhauks** [comment]
The failure appears to be a nodejs coverage check?

**Comment by nathanielmanistaatgoogle** [comment]
@jtattermusch: LGTM; what can be done about that failed c tsan test?

**Comment by nicolasnoble** [comment]
I'm fine overriding that merge, since this changelist can't affect that C tsan issue. BUT I don't remember seeing that issue before, so let's file it maybe ?

**Comment by nathanielmanistaatgoogle** [comment]
@nicolasnoble: the core tsan failure is now filed as [issue 5906](https://github.com/grpc/grpc/issues/5906).

**Pull request merged**
