### PR TITLE
Move timeout_encoding to core/lib/transport

### PR DESCRIPTION
**Pull request by rjshade**
This is useful general purpose code for any transport implementation. Make it available in core/lib/transport, and rename methods to refer to http2 (not the current implementation specific chttp2).

### CODE REVIEW

**Comment by rjshade** [comment]
@ctiller this is after our chat earlier

**Comment by jcanizales** [comment]
Hi Robbie,

to ease resolving the merge conflict, you will want to revert your changes to `gRPC.podspec`.

**Comment by rjshade** [comment]
@jcanizales thanks, have synced to head.

**Comment by rjshade** [comment]
@jcanizales @ctiller ptal

**Comment by jcanizales** [comment]
If Travis is happy, I'm happy!

**Comment by rjshade** [comment]
Am I able to trigger a re-run of tests, or can you do so if not? The failures seem unrelated to this PR.

**Comment by ctiller** [comment]
Broadly looks good... dgq can look at details

**Comment by dgquintas** [comment]
LGTM. Some tests aren't happy, and it's not immediately clear it's unrelated. Can you re-run them?

**Comment by rjshade** [comment]
@dgquintas I'm having difficulty understanding the failures. It looks like Basic tests and Portability tests are failing. Following the Details link for Basic tests there's 3 red exclamation marks, but clicking on them takes me to a page that doesn't seem to have any useful debug information (e.g. logs):

https://grpc-testing.appspot.com/job/gRPC_pull_requests/11197/config=msan,language=c,platform=linux/

Following the Details link for Portability tests, there are another few red exclamation marks, this time the linked to pages have some logs:

https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests/5123/language=c,scenario=linux_x64_clang3.6_bo/console

with errors like:

ERROR: Something went wrong while deleting Files
ERROR: Step ‘Publish JUnit test result report’ failed: Test reports were found but none of them are new. Did tests run? 
ERROR: [GitHub Commit Status Setter] - Cannot retrieve Git metadata for the build, setting build result to FAILURE


None of the above seems related to this PR - what am I missing?

**Comment by rjshade** [comment]
I also don't think I have the power to trigger another run of Travis tests (running "./tools/run_tests/run_tests.py -l c" locally passes).

**Comment by rjshade** [comment]
@dgquintas ping? Can this be merged? It's been almost 3 weeks since it was opened.

**Comment by dgquintas** [comment]
@rjshade woops sorry. Things look better now. I'm just going to re-run the basic tests one again to get rid of potential flakes. I'm on this.

**Comment by dgquintas** [comment]
Ok, all is well, modulo qps_openloop flaking, which is a known issue. LGTM, and tagging for merge.

For future reference, the way to see the output of a failed test suite, you want to hover to the right of the icon (usually a yellow or red sign). Click on the arrow and from the popup, click on Console Output. Then you may want to click on "full log".

To trigger reruns, the easiest is to write "test this please" as a comment here.

**Comment by kpayson64** [comment]
@dgquintas 
Can you take a look at the sanity tests?  This is the first PR I've seen failures, but its possible that its unrelated.

**Comment by dgquintas** [comment]
@kpayson64 yeah, I think I introduced a flake in grpclb_test. I'll send out a fix shortly.

**Comment by dgquintas** [comment]
Also, regarding sanity, I think it needed to regenerate projects.

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @rjshade isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request merged**
