### PR TITLE
Filters parsing logic for servers

### PR DESCRIPTION
**Pull request by yashykt**
Follows from #25530

1) `HttpConnectionManager` is filtered from `LdsResponseParseClient()` so that it can be called from server side parsing logic too.
2) As part of `FilterChain` we are only supporting `HttpConnectionManager` as a filter right now and it is a mandatory filter.
3) Each XdsHttpFilterImpl now sports two additional methods `IsSupportedOnClients()` and `IsSupportedOnServers()` to check whether that particular filter is supported on clients/servers.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25609)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks great!  My only substantive comment is that we need a few more tests.

Please let me know if you have any questions.  Thanks!

CC @lidizheng 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25609#-:-MUysObP3V_QuKOKpK_Q:b9ihqjn)* status: all files reviewed, 5 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 1650 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUypxRH3JC5mFxI1V1P:-MUypxRH3JC5mFxI1V1Q:bk9szpi) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/src/core/ext/xds/xds_api.cc#L1650)):*
> ```cpp
> }
> 
> template <bool is_client>
> ```

Why make this a template instead of just passing it in as a parameter to the function?  Seems like the generated code size would be a lot smaller that way, and it would be easier to understand for readers.
___
*[src/core/ext/xds/xds_api.cc, line 1713 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUyqHmIADbuae0_C2iz:-MUyqHmIADbuae0_C2j-:blbuv54) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/src/core/ext/xds/xds_api.cc#L1713)):*
> ```cpp
>       if ((is_client && !filter_impl->IsSupportedOnClients()) ||
>           (!is_client && !filter_impl->IsSupportedOnServers())) {
>         return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
> ```

This isn't a static string, so you need to use `GRPC_ERROR_CREATE_FROM_COPIED_STRING()` here.
___
*[src/core/ext/xds/xds_api.cc, line 1983 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUyqsiPEm8VJmuG9rnY:-MUyqsiPEm8VJmuG9rnZ:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/src/core/ext/xds/xds_api.cc#L1983)):*
> ```cpp
>     error = FilterChainParse(context, filter_chains[0], &filter_chain);
>     if (error != GRPC_ERROR_NONE) return error;
>     lds_update->filter_chains.push_back(filter_chain);
> ```

`std::move()`
___
*[src/core/ext/xds/xds_api.cc, line 1991 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUyqyHVBmbHijY38ESv:-MUyqyHVBmbHijY38ESw:b-ddt6re) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/src/core/ext/xds/xds_api.cc#L1991)):*
> ```cpp
>     error = FilterChainParse(context, default_filter_chain, &filter_chain);
>     if (error != GRPC_ERROR_NONE) return error;
>     lds_update->default_filter_chain = filter_chain;
> ```

`std::move()`
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6828 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUyrW86A3VIyUM8Dg9Q:-MUyrW86A3VIyUM8Dg9R:b-uf3wvn) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/test/cpp/end2end/xds_end2end_test.cc#L6828)):*
> ```cpp
> };
> 
> TEST_P(XdsEnabledServerTest, Basic) {
> ```

Please also add the following tests:
- We NACK a config with an L4 filter other than the HCM.
- We NACK a config with an HTTP filter we don't support.
- We NACK a config with an HTTP filter that we we do support but is not supported on the client.
- We NACK a config with an HTTP filter that we we do support but is not supported on the server.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25609)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 1650 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUypxRH3JC5mFxI1V1P:-MVJgK4D8fXGnP-YxB7Q:btlg55d) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/src/core/ext/xds/xds_api.cc#L1650)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why make this a template instead of just passing it in as a parameter to the function?  Seems like the generated code size would be a lot smaller that way, and it would be easier to understand for readers.
</blockquote></details>

I made it a template mainly because at the points where we call `HttpConnectionManagerParse` we already know whether it is a client or a server. 
___
*[src/core/ext/xds/xds_api.cc, line 1713 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUyqHmIADbuae0_C2iz:-MVJgppM2xcFE9aFfUnx:b-t06jdg) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/src/core/ext/xds/xds_api.cc#L1713)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This isn't a static string, so you need to use `GRPC_ERROR_CREATE_FROM_COPIED_STRING()` here.
</blockquote></details>

Oh You are right! Thanks!
___
*[src/core/ext/xds/xds_api.cc, line 1983 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUyqsiPEm8VJmuG9rnY:-MVJgsKR8HXDVRs5whVW:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/src/core/ext/xds/xds_api.cc#L1983)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_api.cc, line 1991 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUyqyHVBmbHijY38ESv:-MVJgsbz-klV4lJlIMVN:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/src/core/ext/xds/xds_api.cc#L1991)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`std::move()`
</blockquote></details>

Done.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6828 at r1](https://reviewable.io/reviews/grpc/grpc/25609#-MUyrW86A3VIyUM8Dg9Q:-MVJhvmv3N9o1wa7JsoM:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/6fb8540a1ace51b1bcd8856329ec2867bfd93a59/test/cpp/end2end/xds_end2end_test.cc#L6828)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please also add the following tests:
- We NACK a config with an L4 filter other than the HCM.
- We NACK a config with an HTTP filter we don't support.
- We NACK a config with an HTTP filter that we we do support but is not supported on the client.
- We NACK a config with an HTTP filter that we we do support but is not supported on the server.
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
This looks great!  Feel free to merge after addressing remaining comments.

> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25609#-:-MVNeSJxC_57ikSEcPnf:b602gs8)* status: all files reviewed, 2 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 1696 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVNZUTj5yTEfHbd9xlj:-MVNZUTj5yTEfHbd9xlk:b-wt6a2z) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/src/core/ext/xds/xds_api.cc#L1696)):*
> ```cpp
>           envoy_extensions_filters_network_http_connection_manager_v3_HttpFilter_typed_config(
>               http_filter);
>       if (any == nullptr) {
> ```

I'm already addressing this in #25651.
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6843 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVN_jKL2oVbqdZL5M5A:-MVN_jKM5a19Pv2kpXdl:bzgb6co) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/test/cpp/end2end/xds_end2end_test.cc#L6843)):*
> ```cpp
> 
> // A No-op HTTP filter used for verifying parsing logic.
> class NoOpHttpFilter : public grpc_core::XdsHttpFilterImpl {
> ```

Please move this up above all the tests, maybe somewhere around line 1501.

**Review by markdroth — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25609)* status: all files reviewed, 3 unresolved discussions (waiting on @yashykt)

___
*[src/core/ext/xds/xds_api.cc, line 1696 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVNZUTj5yTEfHbd9xlj:-MVO3uxY12Cz7A-luFE-:b-twzk46) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/src/core/ext/xds/xds_api.cc#L1696)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I'm already addressing this in #25651.
</blockquote></details>

That PR has been merged, so you'll need to merge the changes in here.
___
*[src/core/ext/xds/xds_http_filters.h, line 106 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVO4-6G0gF2oTYA0swr:-MVO4-6G0gF2oTYA0sws:b-kmmq38) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/src/core/ext/xds/xds_http_filters.h#L106)):*
> ```objc
> 
>   // Returns true if the filter is supported on clients; false otherwise
>   virtual bool IsSupportedOnClients() const = 0;
> ```

The fault injection PR (#24354) has been merged as well, so you'll need to add these methods to that filter as well.

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25609)* status: all files reviewed, 3 unresolved discussions (waiting on @lidizheng and @yashykt)

___
*[src/core/ext/xds/xds_http_filters.h, line 106 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVO4-6G0gF2oTYA0swr:-MVOVE60-7ewmN7NgXuy:b-mpwx28) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/src/core/ext/xds/xds_http_filters.h#L106)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The fault injection PR (#24354) has been merged as well, so you'll need to add these methods to that filter as well.
</blockquote></details>

I'm guessing that since the PR is for client-side only, the filter will also be client-side only. @lidizheng please verify

**Review by lidizheng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25609)* status: all files reviewed, 3 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/xds/xds_http_filters.h, line 106 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVO4-6G0gF2oTYA0swr:-MVOW4Av5gqt3P1ZlxoT:b-f2ysor) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/src/core/ext/xds/xds_http_filters.h#L106)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

I'm guessing that since the PR is for client-side only, the filter will also be client-side only. @lidizheng please verify
</blockquote></details>

Yes. Even though Envoy's HTTPFault filter applies to both client and server, gRPC's fault injection feature currently only tested on client-side. Can you update the `IsSupportedOnServers` method of `XdsHttpFaultFilter` to return `false`?

**Review by yashykt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25609)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @markdroth)

___
*[src/core/ext/xds/xds_api.cc, line 1696 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVNZUTj5yTEfHbd9xlj:-MVSabAP6qw-zeQVYX13:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/src/core/ext/xds/xds_api.cc#L1696)):*
<details><summary><i>Previously, yashykt (Yash Tibrewal) wrote…</i></summary><blockquote>

Will do :)
</blockquote></details>

Done.
___
*[src/core/ext/xds/xds_http_filters.h, line 106 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVO4-6G0gF2oTYA0swr:-MVSacpUBm_LQBMNm78b:b4855oy) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/src/core/ext/xds/xds_http_filters.h#L106)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Note that it's not just that it hasn't been tested on the server; the current implementation actually would not work on the server, because the current implementation triggers its behavior based on the send_initial_metadata op, but on the server side it would need to instead trigger its behavior based on the recv_initial_metadata op.  So if we ever need to support this filter on the server side, we'll need to do some more work.

But anyway, yes, the fault injection filter should be supported only on the client side for now.
</blockquote></details>

Thanks! Done!
___
*[test/cpp/end2end/xds_end2end_test.cc, line 6843 at r4](https://reviewable.io/reviews/grpc/grpc/25609#-MVN_jKL2oVbqdZL5M5A:-MVSaegs7VmxzXXjFBFD:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/56d68f62b44b013e71384b0d3fd0f86d22252055/test/cpp/end2end/xds_end2end_test.cc#L6843)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please move this up above all the tests, maybe somewhere around line 1501.
</blockquote></details>

Done.

**Review by markdroth — APPROVED** [review]
Looks great!

> Reviewed 4 of 6 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25609#-:-MVT9qSvEaP1NlvgaxXy:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)

**Comment by yashykt** [comment]
Thanks for reviewing!

**Pull request merged**
