### PR TITLE
Generated c# docs for v1.15.0

### PR DESCRIPTION
**Pull request by jtattermusch**
By using the new script from https://github.com/grpc/grpc/pull/16783

### CODE REVIEW

**Comment by AspirinSJL** [comment]
Wow, all the tests are failing!

**Comment by jtattermusch** [comment]
@AspirinSJL  that is a known friction item. The "gh-pages" is a separate branch that doesn't contain any of our code, just the generated docs,  so all the test jobs clearly have to fail.

FTR the decision to store our generated docs in "gh-pages" branch was really unfortunate. It's bloating our main repo's git repository and it's really awkward to switch between  code and docs-only branches. And it also brings problems with all the tests seeming to be red unless we blacklist the "gh-pages" branch in kokoro configuration (and I don't like such special casing as it's hard to maintain).  I wish we will change the process at some point and store the generated docs in a more suitable place.  @carl-mastrangelo  WDYT?

**Comment by carl-mastrangelo** [comment]
gh-pages is a limitation of github I thought, but we don't need them in our repo.   Maybe we could make a grpc-docs repo, or possibly put them on grpc/grpc.github.io ?

**Comment by AspirinSJL** [comment]
Before we make any methodology change, I will just merge this PR.

**Pull request merged**
