### PR TITLE
Discard the read buffer on stream error

### LINKED ISSUE #5260: async_end2end_test cancel test flaky
https://grpc-testing.appspot.com/job/gRPC_master/config=opt,language=c++,platform=linux/lastCompletedBuild/testReport/(root)/tests/bins_opt_async_end2end_test/

[ RUN      ] AsyncEnd2endServerTryCancel/AsyncEnd2endServerTryCancelTest.ServerBidiStreamingTryCancelDuring/0
E0216 17:49:50.091436258   14779 tcp_client_posix.c:171]     failed to connect to 'ipv6:[::1]:32767': socket error: connection refused
I0216 17:49:50.097108126   14850 async_end2end_test.cc:796]  Server called TryCancel()
test/cpp/end2end/async_end2end_test.cc:130: Failure
Value of: ok
  Actual: true
Expected: it->second
Which is: false
[  FAILED  ] AsyncEnd2endServerTryCancel/AsyncEnd2endServerTryCancelTest.ServerBidiStreamingTryCancelDuring/0, where GetParam() = false (8 ms)

### PR DESCRIPTION
**Pull request by yang-g**
@ctiller @vjpai 

This fixes #5260

### CODE REVIEW

**Comment by sreecha** [comment]
LGTM.  I will merge once the tests pass..

**Comment by vjpai** [comment]
Can I suggest that this PR be held back until comments are added to this function? It is essentially incomprehensible at this point. This is an issue throughout core, but this would be a good time to deal with it, each time a function is changed.

**Comment by vjpai** [comment]
On second thought, I am not going to insist on holding back this PR, but I strongly suggest that we need an issue filed to comment the transport layer of core. I would also suggest adding this as an issue for me or @sreecha in order to increase the number of eyes on core.

**Comment by sreecha** [comment]
I think thats a good idea to file an issue and assign to me to add some commenting in the transport layer.

**Comment by vjpai** [comment]
Ok, I opened issue #5356 . @sreecha - you can merge this PR when you are ready for it.

**Comment by sreecha** [comment]
@yang-g . A couple of C# interop tests failed. it doesn't seem like they are related to your issue but just to double-check i re-triggered the build.

**Comment by sreecha** [comment]
Interop tests passed now. A few Basic tests failed but the failures are unrelated to this change. Merging.

**Pull request merged**
