### PR TITLE
Use environment variable to enable CFStream

### PR DESCRIPTION
**Pull request by muxi**
This change will allow users to better experiment with CFStream.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                    FILE SIZE
 ++++++++++++++ GROWING                                      ++++++++++++++
  +0.0%     +83 [None]                                           +11  +0.0%
   +22%     +37 src/core/lib/iomgr/iomgr_posix.cc                +37   +22%
       +40%     +37 grpc_set_default_iomgr_platform                  +37   +40%

 -------------- SHRINKING                                    --------------
 -10.9%     -48 src/core/lib/iomgr/polling_entity.cc             -48 -10.9%
     -24.1%     -48 grpc_polling_entity_del_from_pollset_set         -48 -24.1%

  +0.0%     +72 TOTAL                                              0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
   676,555       Core (>)        666,548

 1,991,632      Total (>)      1,980,675

***************FRAMEWORKS****************
  New size                      Old size
 3,674,302       Core (>)      3,612,674

10,873,521      Total (>)     10,811,770


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,981,908      Total (>)      1,981,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,814,153      Total (>)     10,814,015

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,981,908      Total (>)      1,981,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,814,147      Total (>)     10,814,014

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,981,908      Total (>)      1,981,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,814,152      Total (>)     10,814,021

 No significant differences in binary sizes


```

**Comment by ncteisen** [comment]
Please update docs/environment-variables.md too

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,981,908      Total (>)      1,981,730

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,814,147      Total (>)     10,814,015

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by muxi** [comment]
Basic Tests MacOS [opt] - Python failure unrelated

**Comment by muxi** [comment]
Basic Tests MacOS [opt] - #16270

**Pull request merged**
