### PR TITLE
Allow grpc to build when compiled as a Ruby native extension with TruffleRuby (#23069)

### PR DESCRIPTION
**Pull request by norswap**
This allows grpc to build with Truffleruby. Many changes are related to the fact that to build native extensions, TruffleRuby uses the Sulong implementation of the LLVM toolchain (LLVM on top of GraalVM), which behaves differently than Apple's toolchain on mac OS.

The change also disables embedding OpenSSL and ZLib by default, to cut on build times, and because since Sulong is a JIT runtime, it doesn't play that nicely with constant-time crypto functions.

Note that grpc still does not work with TruffleRuby (due to underlying Sulong issues that we are tracking), but now it's possible to build and `require 'grpc'`, which helps install and use gems that have grpc as a non-essential dependency.

Related issue: #23069 

@nicolasnoble

### CODE REVIEW

**Comment by eregon** [comment]
I confirm this PR also works fine on Linux, so:
```
$ ruby -rgrpc -e 'p GRPC'           
GRPC
```
works.

When trying the examples:
```
$ ruby greeter_server.rb
/home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1195:in `__allocate__': TruffleRuby doesn't have a case for the com.oracle.truffle.llvm.runtime.nodes.cast.LLVMToVectorNodeFactory$LLVMSignedCastToI64VectorNodeGen node with values of type com.oracle.truffle.llvm.runtime.vector.LLVMPointerVector (TypeError)
	from com.oracle.truffle.llvm.runtime.nodes.cast.LLVMToVectorNodeFactory$LLVMSignedCastToI64VectorNodeGen.executeAndSpecialize(LLVMToVectorNodeFactory.java:678)
	from com.oracle.truffle.llvm.runtime.nodes.cast.LLVMToVectorNodeFactory$LLVMSignedCastToI64VectorNodeGen.executeGeneric(LLVMToVectorNodeFactory.java:638)
	from com.oracle.truffle.llvm.runtime.nodes.op.LLVMVectorArithmeticNodeGen.executeGeneric(LLVMVectorArithmeticNodeGen.java:60)
	from com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWriteVectorNodeGen.execute(LLVMWriteNodeFactory.java:1074)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.doBlock(LLVMBasicBlockNode.java:176)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNodeFactory$InitializedBlockNodeGen.execute(LLVMBasicBlockNodeFactory.java:48)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.doDispatch(LLVMDispatchBasicBlockNode.java:97)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNodeGen.executeGeneric(LLVMDispatchBasicBlockNodeGen.java:44)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.doRun(LLVMFunctionRootNode.java:85)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNodeGen.executeGeneric(LLVMFunctionRootNodeGen.java:45)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:88)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:557)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/grpc-1.34.0.dev/src/ruby/lib/grpc/generic/rpc_server.rb:234:in `new'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/grpc-1.34.0.dev/src/ruby/lib/grpc/generic/rpc_server.rb:234:in `initialize'
	from greeter_server.rb:39:in `new'
	from greeter_server.rb:39:in `main'
	from greeter_server.rb:48:in `<main>'

$ ruby greeter_client.rb
/home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1195:in `__allocate__': TruffleRuby doesn't have a case for the com.oracle.truffle.llvm.runtime.nodes.cast.LLVMToVectorNodeFactory$LLVMSignedCastToI64VectorNodeGen node with values of type com.oracle.truffle.llvm.runtime.vector.LLVMPointerVector (TypeError)
	from com.oracle.truffle.llvm.runtime.nodes.cast.LLVMToVectorNodeFactory$LLVMSignedCastToI64VectorNodeGen.executeAndSpecialize(LLVMToVectorNodeFactory.java:678)
	from com.oracle.truffle.llvm.runtime.nodes.cast.LLVMToVectorNodeFactory$LLVMSignedCastToI64VectorNodeGen.executeGeneric(LLVMToVectorNodeFactory.java:638)
	from com.oracle.truffle.llvm.runtime.nodes.op.LLVMVectorArithmeticNodeGen.executeGeneric(LLVMVectorArithmeticNodeGen.java:60)
	from com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWriteVectorNodeGen.execute(LLVMWriteNodeFactory.java:1074)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.doBlock(LLVMBasicBlockNode.java:176)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNodeFactory$InitializedBlockNodeGen.execute(LLVMBasicBlockNodeFactory.java:48)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.doDispatch(LLVMDispatchBasicBlockNode.java:97)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNodeGen.executeGeneric(LLVMDispatchBasicBlockNodeGen.java:44)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.doRun(LLVMFunctionRootNode.java:85)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNodeGen.executeGeneric(LLVMFunctionRootNodeGen.java:45)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:88)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:557)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/grpc-1.34.0.dev/src/ruby/lib/grpc/generic/client_stub.rb:47:in `new'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/grpc-1.34.0.dev/src/ruby/lib/grpc/generic/client_stub.rb:47:in `setup_channel'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/grpc-1.34.0.dev/src/ruby/lib/grpc/generic/client_stub.rb:102:in `initialize'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/grpc-1.34.0.dev/src/ruby/lib/grpc/generic/service.rb:158:in `initialize'
	from greeter_client.rb:31:in `new'
	from greeter_client.rb:31:in `main'
	from greeter_client.rb:40:in `<main>'
```
which is the Sulong issue mentioned above and happens on both macOS & Linux.

**Comment by norswap** [comment]
I can't seem to add labels (I might have needed to do that when creating the PR) but this is `lang/ruby` and `release notes: no`.

**Comment by eregon** [comment]
@apolcyn Could you review?

**Comment by apolcyn** [comment]
the macos artifact build timed out https://source.cloud.google.com/results/invocations/02ff47c3-af8a-4322-9f3b-f9aeac5861e3/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_build_artifacts/log --not sure if related to this PR though, I kicked off another run

**Comment by apolcyn** [comment]
retry for macos artifact build also timed out, retrying again

**Comment by norswap** [comment]
Any news? Something needed from my part?

**Comment by deepj** [comment]
@apolcyn Hello, can you take a look at it soon, please? I originally submit the bug in TruffleRuby issue tracker 3/4 year ago. I'd like to test something but the application uses `grpc` and I can't continue without that :) Thank you for your help in advance

**Comment by norswap** [comment]
Rebased on top of master. When running tests (with MRI - this still doesn't work with TruffleRuby, though we're looking at that right now), I'm getting this failure:

```
  1) the secure http client/server behaves like GRPC metadata delivery works OK from server => client sends all the pairs when keys and values are valid
     Got 0 failures and 2 other errors:
     Shared Example Group: "GRPC metadata delivery works OK" called from ./src/ruby/spec/client_server_spec.rb:594

     1.1) Failure/Error: client_batch = call.run_batch(client_ops)

          GRPC::Core::CallError:
            call#run_batch failed somehow
```

(though I swear sometimes it's different)

In the lead up to that, I get a ton of messages, of this style:

```
E0204 19:36:31.829019000 123145413697536 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
E0204 19:36:31.829027000 123145413697536 ev_poll_posix.cc:945]         pollset_work: {"created":"@1612463791.829022000","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
E0204 19:36:31.829043000 123145413697536 completion_queue.cc:1308]     Completion queue pluck failed: {"created":"@1612463791.829022000","description":"Too many open files","errno":24,"file":"src/core/lib/iomgr/wakeup_fd_pipe.cc","file_line":41,"os_error":"Too many open files","syscall":"pipe"}
```

That doesn't seem to be anything related to this change, but I thought I'd report it.

**Comment by eregon** [comment]
@apolcyn or another grpc maintainer:
Could you please review and merge this?
It's been open for more than 6 months now, and multiple users are reporting this issue (https://github.com/oracle/truffleruby/issues/2247) which can only be solved in grpc.

**Comment by eregon** [comment]
Let's take this as an opportunity to open a new PR rebased on latest and hopefully capture the attention of grpc maintainers.

**Pull request closed without merging**
