### PR TITLE
Add logic to work around buggy Android NDKs

### PR DESCRIPTION
**Pull request by nicolasnoble**
Taking #13173 over.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by nicolasnoble** [comment]
This time, sanity passes, @kwasimensah. It's time like these where I just want to nod slowly while smiling, pretending I understand computers.

**Comment by kwasimensah** [comment]
Sweet. thanks!

**Comment by matt-kwong** [comment]
It looks like this PR is having problems building on MacOS:
```
[AR]      Creating /Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x86/libs/opt/libz.a
[LD]      Linking /Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x86/libs/opt/libgpr.dylib
ld: warning: directory not found for option '-L/Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x86/libs/opt/protobuf'
ld: warning: directory not found for option '-L/Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x86/libs/opt/c-ares'
ld: warning: directory not found for option '-L/Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x86/libs/opt/zlib'
Undefined symbols for architecture i386:
  "___cxa_guard_acquire", referenced from:
      _gpr_cpu_current_cpu in cpu_posix.o
  "___cxa_guard_release", referenced from:
      _gpr_cpu_current_cpu in cpu_posix.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x86/libs/opt/libgpr.dylib] Error 1

2017-11-13 12:14:53,570 FAILED: build_artifact.csharp_ext_macos_x86 [ret=2, pid=55424, time=50.2sec]
```

I see the same issue happening with other languages on MacOS. There might be some other issues, but this is the most obvious issue.

**Comment by nicolasnoble** [comment]
@ctiller it looks like we can't use the atomics without using the libstdc++...

**Comment by kwasimensah** [comment]
So this CL depends on using thread safe function local statics which is what I think is added the calls to cxa_guard_acquire.

**Comment by kwasimensah** [comment]
Revert the change and I'll find a way to test this on macs

**Comment by jtattermusch** [comment]
@ericgribkoff   is this still PR stil useful? It hasn't been updated for >1year. Please resolve or close.

**Comment by kwasimensah** [comment]
https://github.com/grpc/grpc/pull/13173 got merged so this pull request can be dropped.

**Pull request closed without merging**
