### PR TITLE
WIP: Microbenchmark for system roots feature

### PR DESCRIPTION
**Pull request by tdbhacks**
This is a work-in-progress PR, please don't assign it / review it yet.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/16278)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,950,932      Total (=)      1,950,932

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,662,141      Total (>)     10,662,140

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,950,932      Total (=)      1,950,932

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,662,146      Total (=)     10,662,146

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
I'm closing this PR since it's kind of old. Please reopen it if appropriate. Thanks!

**Pull request closed without merging**
