### PR TITLE
Remove allocation in server_auth_filter

### PR DESCRIPTION
**Pull request by hcaseyal**

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++

 -------------- SHRINK --------------
  [ = ]       0 [None]     -16  -0.0%

  [ = ]       0 TOTAL      -16  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by hcaseyal** [comment]
@markdroth If `calld->auth_context` is just a reference to `chand->auth_context`, then do we need to store auth_context in calld at all? Can we just refer to `chand->auth_context`?

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                             FILE SIZE
 ++++++++++++++ GROWING                                               ++++++++++++++

 -------------- SHRINKING                                             --------------
  -0.7%     -16 src/core/lib/security/transport/server_auth_filter.cc     -16  -0.7%
     -11.5%     -16 init_call_elem                                            -16 -11.5%
      -1.3%      -9 recv_initial_metadata_ready                                -9  -1.3%

 -+-+-+-+-+-+-+ MIXED                                                 +-+-+-+-+-+-+-
  +0.0%      +8 [None]                                                     -8  -0.0%

  -0.0%      -8 TOTAL                                                     -24  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                             FILE SIZE
 ++++++++++++++ GROWING                                               ++++++++++++++

 -------------- SHRINKING                                             --------------
  -0.7%     -16 src/core/lib/security/transport/server_auth_filter.cc     -16  -0.7%
     -11.5%     -16 init_call_elem                                            -16 -11.5%
      -1.3%      -9 recv_initial_metadata_ready                                -9  -1.3%

 -+-+-+-+-+-+-+ MIXED                                                 +-+-+-+-+-+-+-
  +0.0%      +8 [None]                                                     -8  -0.0%

  -0.0%      -8 TOTAL                                                     -24  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by hcaseyal** [comment]
Interop ALTS Tests: #13379

**Pull request merged**
