### PR TITLE
Fix test failure detection when doing RBE uploads

### PR DESCRIPTION
**Pull request by matt-kwong**
I tested this locally on https://source.cloud.google.com/results/invocations/f8865380-e791-4421-b428-a7add1419e40/targets and it uploaded 12 rows, 2 flakes and 5 tests failing 2/2 times.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by matt-kwong** [comment]
Failures: #15814

**Pull request merged**
