### PR TITLE
cmake: various fixes

### PR DESCRIPTION
**Pull request by jtattermusch**
A few assorted cmake fixes:
Fixes https://github.com/grpc/grpc/issues/8739
Fixes https://github.com/grpc/grpc/issues/8362
Progress toward fixing https://github.com/grpc/grpc/issues/11378 (our cmake file is using CMAKE_INSTALL_{INCLUDEDIR, BINDIR, LIBDIR, CMAKEDIR} definitions brought in by protobuf's cmakefile and that results in putting gRPCConfig.cmake to a wrong destination under protobuf/... directory).

### CODE REVIEW

**Comment by jtattermusch** [comment]
@nicolasnoble  friendly ping.

**Comment by jtattermusch** [comment]
CC @chwarr (this might fix the zlib issue you mentioned).

**Comment by chwarr** [comment]
Thanks. I'll give it a try next week.
It also looks like this resolves some of the `#include` path issues I've been seeing.

**Comment by jtattermusch** [comment]
+mehrdada to review

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/11116
https://github.com/grpc/grpc/issues/10512
https://github.com/grpc/grpc/issues/10686
https://github.com/grpc/grpc/issues/10390

**Comment by chwarr** [comment]
Confirming as of commit 7405347 that the `#include` path problems I mentioned have been fixed. Thanks.

I have yet to verify the zlib changes yet.

**Pull request merged**
