### PR TITLE
Merge 0.14 into master

### PR DESCRIPTION
**Pull request by jcanizales**
Please review the latest commits, which solve merge conflicts.

### CODE REVIEW

**Comment by jcanizales** [comment]
I'll merge master again to solve the conflicts.

**Comment by jcanizales** [comment]
The InteropTest failure is due to Python failing to download and install some package, I suppose due to a connection problem; so I'll rerun it.

**Comment by jcanizales** [comment]
Oh my God, @googlebot ...

**Comment by jcanizales** [comment]
Ping. Release merges have a high tendency to develop merge conflicts as master keeps advancing :) Plus it's GA blocking for us.

**Comment by pgrosu** [comment]
Should we wait for 0.15 to be merged, as now I'm getting errors using this new merge when I compile my client - I can help investigate what the core cause is:

```Bash
$ googleapis/test-compile.sh
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_free'
../libs/opt/libgrpc++.so: undefined reference to `X509_NAME_get_index_by_NID'
../libs/opt/libgrpc++.so: undefined reference to `EC_KEY_free'
../libs/opt/libgrpc++.so: undefined reference to `CRYPTO_set_locking_callback'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_get_cert_store'
../libs/opt/libgrpc++.so: undefined reference to `EVP_DigestVerifyInit'
../libs/opt/libgrpc++.so: undefined reference to `CRYPTO_num_locks'
../libs/opt/libgrpc++.so: undefined reference to `BIO_puts'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_check_private_key'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_use_PrivateKey'
../libs/opt/libgrpc++.so: undefined reference to `SSL_get0_next_proto_negotiated'
../libs/opt/libgrpc++.so: undefined reference to `SSL_get_error'
../libs/opt/libgrpc++.so: undefined reference to `SSL_set_tlsext_host_name'
../libs/opt/libgrpc++.so: undefined reference to `EVP_PKEY_set1_RSA'
../libs/opt/libgrpc++.so: undefined reference to `SSL_state_string_long'
../libs/opt/libgrpc++.so: undefined reference to `sk_value'
../libs/opt/libgrpc++.so: undefined reference to `ASN1_STRING_to_UTF8'
../libs/opt/libgrpc++.so: undefined reference to `sk_new_null'
../libs/opt/libgrpc++.so: undefined reference to `sk_push'
../libs/opt/libgrpc++.so: undefined reference to `RSA_free'
../libs/opt/libgrpc++.so: undefined reference to `SSL_get_servername'
../libs/opt/libgrpc++.so: undefined reference to `SSL_get_peer_certificate'
../libs/opt/libgrpc++.so: undefined reference to `SSL_state_string'
../libs/opt/libgrpc++.so: undefined reference to `BIO_free'
../libs/opt/libgrpc++.so: undefined reference to `SSL_set_SSL_CTX'
../libs/opt/libgrpc++.so: undefined reference to `EVP_PKEY_free'
../libs/opt/libgrpc++.so: undefined reference to `X509_get_ext_d2i'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_tlsext_servername_callback'
../libs/opt/libgrpc++.so: undefined reference to `EVP_sha384'
../libs/opt/libgrpc++.so: undefined reference to `SSL_get0_alpn_selected'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_cipher_list'
../libs/opt/libgrpc++.so: undefined reference to `X509_get_subject_name'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_tmp_ecdh'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_alpn_select_cb'
../libs/opt/libgrpc++.so: undefined reference to `X509_free'
../libs/opt/libgrpc++.so: undefined reference to `PEM_read_bio_PrivateKey'
../libs/opt/libgrpc++.so: undefined reference to `PEM_read_bio_X509'
../libs/opt/libgrpc++.so: undefined reference to `X509_NAME_free'
../libs/opt/libgrpc++.so: undefined reference to `SSL_library_init'
../libs/opt/libgrpc++.so: undefined reference to `BIO_write'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_use_certificate'
../libs/opt/libgrpc++.so: undefined reference to `ERR_error_string_n'
../libs/opt/libgrpc++.so: undefined reference to `EVP_MD_CTX_destroy'
../libs/opt/libgrpc++.so: undefined reference to `SSL_set_bio'
../libs/opt/libgrpc++.so: undefined reference to `sk_pop_free'
../libs/opt/libgrpc++.so: undefined reference to `BN_bin2bn'
../libs/opt/libgrpc++.so: undefined reference to `CRYPTO_set_id_callback'
../libs/opt/libgrpc++.so: undefined reference to `PEM_read_bio_RSAPrivateKey'
../libs/opt/libgrpc++.so: undefined reference to `SSL_read'
../libs/opt/libgrpc++.so: undefined reference to `X509_NAME_dup'
../libs/opt/libgrpc++.so: undefined reference to `X509_NAME_get_entry'
../libs/opt/libgrpc++.so: undefined reference to `X509_NAME_ENTRY_get_data'
../libs/opt/libgrpc++.so: undefined reference to `PEM_write_bio_X509'
../libs/opt/libgrpc++.so: undefined reference to `RSA_new'
../libs/opt/libgrpc++.so: undefined reference to `EVP_PKEY_new'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_add_extra_chain_cert'
../libs/opt/libgrpc++.so: undefined reference to `EVP_DigestVerifyFinal'
../libs/opt/libgrpc++.so: undefined reference to `SSL_is_init_finished'
../libs/opt/libgrpc++.so: undefined reference to `EVP_DigestSignUpdate'
../libs/opt/libgrpc++.so: undefined reference to `BIO_s_mem'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_verify'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_tlsext_servername_arg'
../libs/opt/libgrpc++.so: undefined reference to `BIO_read'
../libs/opt/libgrpc++.so: undefined reference to `EVP_DigestSignFinal'
../libs/opt/libgrpc++.so: undefined reference to `OpenSSL_add_all_algorithms'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_client_CA_list'
../libs/opt/libgrpc++.so: undefined reference to `EVP_DigestSignInit'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_new'
../libs/opt/libgrpc++.so: undefined reference to `TLSv1_2_method'
../libs/opt/libgrpc++.so: undefined reference to `EVP_MD_CTX_create'
../libs/opt/libgrpc++.so: undefined reference to `BIO_pending'
../libs/opt/libgrpc++.so: undefined reference to `sk_num'
../libs/opt/libgrpc++.so: undefined reference to `EVP_DigestVerifyUpdate'
../libs/opt/libgrpc++.so: undefined reference to `BIO_new'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_alpn_protos'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_options'
../libs/opt/libgrpc++.so: undefined reference to `EVP_sha256'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_next_proto_select_cb'
../libs/opt/libgrpc++.so: undefined reference to `PEM_read_bio_X509_AUX'
../libs/opt/libgrpc++.so: undefined reference to `SSL_set_connect_state'
../libs/opt/libgrpc++.so: undefined reference to `ERR_clear_error'
../libs/opt/libgrpc++.so: undefined reference to `BIO_get_mem_data'
../libs/opt/libgrpc++.so: undefined reference to `SSL_load_error_strings'
../libs/opt/libgrpc++.so: undefined reference to `SSL_free'
../libs/opt/libgrpc++.so: undefined reference to `SSL_write'
../libs/opt/libgrpc++.so: undefined reference to `EVP_sha512'
../libs/opt/libgrpc++.so: undefined reference to `BIO_new_mem_buf'
../libs/opt/libgrpc++.so: undefined reference to `X509_STORE_add_cert'
../libs/opt/libgrpc++.so: undefined reference to `GENERAL_NAME_free'
../libs/opt/libgrpc++.so: undefined reference to `SSL_set_accept_state'
../libs/opt/libgrpc++.so: undefined reference to `ERR_get_error'
../libs/opt/libgrpc++.so: undefined reference to `BIO_should_retry'
../libs/opt/libgrpc++.so: undefined reference to `EC_KEY_new_by_curve_name'
../libs/opt/libgrpc++.so: undefined reference to `SSL_new'
../libs/opt/libgrpc++.so: undefined reference to `SSL_do_handshake'
../libs/opt/libgrpc++.so: undefined reference to `SSL_CTX_set_next_protos_advertised_cb'
../libs/opt/libgrpc++.so: undefined reference to `X509_get_pubkey'
../libs/opt/libgrpc++.so: undefined reference to `SSL_set_info_callback'
collect2: error: ld returned 1 exit status
$
```

Thanks,
~p

**Comment by jcanizales** [comment]
Hi Paul, that looks like a version mismatch between BoringSSL/OpenSSL and what the C++ library expects. I'm surprised this PR would affect any of those things (the BoringSSL used by Cocoapods comes from a different place than that used by the C++ library). Can you open an issue for it, to help us tracking, and also confirm that the problem disappears in the commit prior to this merge?

**Comment by pgrosu** [comment]
Hi Jorge,

You got me thinking...  If I specify the boringssl library during my build I get that a symbol is hidden (i.e. can't referenced from another shared library).  The code for the client I use is located at  https://github.com/grpc/grpc/issues/7131#issuecomment-230182747, for which I followed the steps I posted under issue #7131.

The way I compiled above code was as follows, which used to compile without specifying `-lboringssl`:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../libs/opt:../libs/opt/protobuf:/home/pgrosu/apps/protobuf/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/pgrosu/apps/protobuf/lib
export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=/home/pgrosu/apps/grpc/etc/roots.pem
export GOOGLE_APPLICATION_CREDENTIALS=ya...[my access token]...

g++ -std=c++11 -L/usr/lib -L../libs/opt -L/home/pgrosu/apps/protobuf/lib -I./gens -I/home/pgrosu/apps/protobuf/include -I../include -lgrpc++ -lprotobuf  client.cc gens/*.o -o client ; ./client
```

I didn't need to specify the boringssl library before, but if I specify it then the hidden symbol issue comes up:

```
$ g++ -std=c++11 -L/usr/lib -L../libs/opt -L/home/pgrosu/apps/protobuf/lib -I./gens -I/home/pgrosu/apps/protobuf/include -I../include -lgrpc++ -lprotobuf -lboringssl client.cc gens/*.o -o client
/usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/usr/bin/ld: client: hidden symbol `SSL_CTX_free' in ../libs/opt/libboringssl.a(ssl_lib.o) is referenced by DSO
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
$
```
I can create an issue, but I'll continue to dig for a possible solution.

Thanks,
Paul

**Comment by jcanizales** [comment]
Please, definitely open an issue, because someone from the C++ side will be much more helpful than I can be here.

**Comment by pgrosu** [comment]
Hi Jorge,

Ok, I found a fix via the following and will submit an issue:

```
$ cp Makefile Makefile-orig
$ sed s/-fvisibility=hidden//g Makefile > Makefile-not-hidden
$ cp Makefile-not-hidden Makefile
```

Thank you for getting us help with @yang-g on https://github.com/grpc/grpc/issues/7131.

Hope you have a great weekend!
Paul

**Comment by y-zeng** [comment]
@jcanizales The undefined reference error is not caused by this PR. Hopefully #7292 could fix it.

**Comment by pgrosu** [comment]
Hi Jorge and Yuchen,

I submitted issue #7298 with all the steps I performed, including the above fix.  The undefined reference was initially partially fixed by referencing the BoringSSL library during the compilation of the client via `-lboringssl`.  What fixed it was to remove the hidden visibility of the symbols from the [grpc Makefile](https://github.com/grpc/grpc/blob/master/Makefile) through the above [Makefile fix](https://github.com/grpc/grpc/pull/7219#issuecomment-231481517).  Let's test it again after #7292 is merged, but the system that I mostly use is Linux, which could behave differently than a Mac.

I'm sure we will get to a solution that is best for all the users.

Cheers,
Paul

**Pull request merged**
