### PR TITLE
Link grpc_csharp_ext with static runtime.

### PR DESCRIPTION
**Pull request by jtattermusch**
Tentative fix for https://github.com/grpc/grpc/issues/10251.

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @vadimi

**Comment by jtattermusch** [comment]
Artifact build is here: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/3064/

**Comment by vadimi** [comment]
I checked the artifacts, unfortunately it didn't work. They look exactly the same as the NuGet package ones.

**Comment by jtattermusch** [comment]
@vadimi,  just in case, the testing packages built from the artifacts are here:
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/3031/platform=windows/

So you are saying the new artifacts don't actually have the static runtime linked with them?

**Comment by vadimi** [comment]
yes, new dlls don't have the runtime linked with them, just double checked that.

**Comment by vadimi** [comment]
@jtattermusch I think I figured it out. I followed these instructions to setup build environment on my machine: [building-using-cmake-with-boringssl](https://github.com/grpc/grpc/blob/master/INSTALL.md#building-using-cmake-with-boringssl)

I tried to run the following script:
```
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DgRPC_MSVC_STATIC_RUNTIME=ON
cmake --build . --target grpc_csharp_ext --config Release
```
And it didn't statically link the runtime too. So I added two more flags to `msvc_static_runtime.cmake` file: `CMAKE_C_FLAGS_DEBUG` and `CMAKE_C_FLAGS_RELEASE` to replace `/MD` with `/MT`, ran two commands above and everything worked fine.

**Comment by vadimi** [comment]
Could you add `CMAKE_C_FLAGS_DEBUG` and `CMAKE_C_FLAGS_RELEASE` to `msvc_static_runtime.cmake` so we can retest this PR?

**Comment by vadimi** [comment]
@jtattermusch friendly ping

**Comment by jtattermusch** [comment]
@vadimi  thanks for help. I'll look into that ASAP. Also, feel free to create a PR against my branch in the meantime.

**Comment by jtattermusch** [comment]
@vadimi  done and started artifact build here: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/3111/

**Comment by vadimi** [comment]
@jtattermusch that worked perfectly fine. I see the runtime linked. Thanks!

**Comment by jtattermusch** [comment]
Build of testing packages is here: https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/3078/platform=windows/

**Comment by vadimi** [comment]
packages are looking good too, thanks.

**Comment by jtattermusch** [comment]
Known failures:
https://github.com/grpc/grpc/issues/9399
https://github.com/grpc/grpc/issues/10267
https://github.com/grpc/grpc/issues/9804

**Pull request merged**
