### PR TITLE
Use BoringSSL instead of OpenSSL

### LINKED ISSUE #4081: Support bitcode
Cocoapods' OpenSSL isn't compiled using bitcode, which prevents bitcode from being generated for dependent apps. The `prepare_command` of its podspec needs to be updated like in this Gist:

https://gist.github.com/felix-schwarz/c61c0f7d9ab60f53ebb0

- Using clang instead of gcc.
- Passing it `-fembed-bitcode`.
- Passing `no-asm` to `./Configure`.

CC: @thstart because I know you're interested in this support.

### PR DESCRIPTION
**Pull request by jcanizales**
This is a prerequisite for solving #4199 (which is essentially #4121), because a dynamic framework can't be created with precompiled libraries.

It fixes #4081 and any future issue of the sort, because the BoringSSL pod works from sources.

And removes steps 6, 7, 8 and 9 from #3492, because it eliminates the 15 - 20 min of time building OpenSSL the first time one does `pod install` (which times out `run_tests.sh`). By the same token, it should speed up Travis builds considerably.

### CODE REVIEW

**Comment by murgatroid99** [comment]
The travis build failed.

**Comment by jcanizales** [comment]
It's weird, it used XCode 6.1 for those builds, instead of 7...

**Comment by jcanizales** [comment]
Restarting them made them use the correct XCode and pass. The change took 10min off each of the 3 tests. Half of what remains is compiling protoc, and the other half is probably compiling OpenSSL for the test server.

**Comment by jcanizales** [comment]
For the record, this also fixes #4295, which happens every time OpenSSL is released and lasts O(day) until the OpenSSL podspec maintainer updates it.

**Pull request merged**
