### PR TITLE
Optimizing grpc_error Part 2: inline always-present members

### PR DESCRIPTION
**Pull request by ncteisen**
Based off error opt part1 (#9756) and also #9745.

Certain ints and strs will always be present in grpc_error. Rather than store them in an AVL tree, we now hold them directly in the grpc_error struct.

Benchmark snippits:

MacOs:
* BM_ErrorCreate drops from 1309ns to 319ns

Linux:
* BM_ErrorCreate drops from 338ns to 127ns

Also added a small test of basic error functionality to help keep sanity as I made these optimizations. (could be dropped from this PR if it is not worth adding to the repo)

### CODE REVIEW

**Comment by ctiller** [comment]
All tests are worth adding :)

Could I also recommend expanding BM_ErrorGet{Missing,Present}Int to have variants for a value that is inlined and a value that is not inlined.

**Comment by ctiller** [comment]
(and the same for BM_ErrorCreateAndSet*)

**Comment by ctiller** [comment]
(this is excellent progress...)

**Comment by ncteisen** [comment]
Added inlined BM_ErrorCreateAndSet* and inlined BM_ErrorCreateAndSet*Loop and inlined BM_ErrorGetPresentInt. Inlined BM_ErrorGetMissingInt doesn't really make sense because by definition, the inlined members will always be present, since they are set in CREATE

**Comment by ncteisen** [comment]
Closing this. #9963 accomplishes the same optimization in a cleaner fashion.

**Pull request closed without merging**
