### PR TITLE
Don't override GRPC_POLL_STRATEGY in a test

### PR DESCRIPTION
**Pull request by vjpai**
This probably shouldn't be overridden at test granularity

### CODE REVIEW

**Comment by vjpai** [comment]
Interestingly, making this change makes this specific test fail. Any idea why this specific test needs epoll1 ?

**Comment by gnossen** [comment]
Not offhand. @ericgribkoff should know though.

**Comment by ericgribkoff** [comment]
The test requires `epoll1` because epoll1 and poll support fork and epollex does not.

**Comment by vjpai** [comment]
Ahh. So, backing up a level, should this strategy be required for all Python targets as opposed to just this specific test?

**Comment by ericgribkoff** [comment]
I don't think so. gRPC's shipped Python packages only include epoll1, but when building from source - as when the CI runs this fork test - Python will default to epollex.

**Comment by vjpai** [comment]
Ok, so in practice this won't affect any Python users. I suggest that this line of the test deserves a comment. You may have noticed we've been killing polling engines recently (epollsig and poll-cv in the past few months) and epoll1 looks like an attractive target otherwise. Is the process of building a package not included in the repo? Because I didn't find a specific place where epoll1 was included but epollex was excluded. Thanks!

**Comment by gnossen** [comment]
I believe [this](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/port.h#L43) is what you're looking for.

**Comment by mehrdada** [comment]
@vjpai Python depends on `epoll1` because the `manylinux1` specification (which is the only thing we can upload as Linux packages at the moment but might change) specifies an old glibc and it is not feasible to run `epollex` while conforming to that specification.

**Comment by gnossen** [comment]
[`manylinux2010` is on the horizon, but not quite ready yet](https://github.com/grpc/grpc/issues/18210). We're hoping to start distributing wheels for it as soon as it's ready. At which point, we can potentially deprecate `manylinux1`.

**Pull request closed without merging**
