### PR TITLE
Handle the case where completionqueue op completes with a failure

### PR DESCRIPTION
**Pull request by sreecha**

### CODE REVIEW

**Comment by sreecha** [comment]
cc @yang-g

**Comment by ctiller** [comment]
Jenkins seems to be throwing up a huge number of (legitimate) issues:
https://grpc-testing.appspot.com/job/gRPC_pull_requests/5059/

**Comment by sreecha** [comment]
I am looking into this. Most likely the following line is not needed: https://github.com/grpc/grpc/pull/4661/files#diff-7b669dd2948b796b465aa95ec1c42962R186 
(this was not directly related to the issue I was fixing anyway. Just felt like the right thing to do to. I will look into this some more).

Secondly, I think this will also require modifying the 'server_registered_method_bad_client_test' test.

**Comment by sreecha** [comment]
I accidentally pushed some debug statements I added to bad_client.c and server_registered_method.c. 
Do not merge this yet. I will revert the changes once i am done with my debugging.

**Pull request closed without merging**
