### PR TITLE
Add missing dependency on :envoy_annotations_upbdefs

### PR DESCRIPTION
**Pull request by acozzette**
@ctiller

### CODE REVIEW

**Comment by ctiller** [comment]
LGTM

**Comment by ctiller** [comment]
@nicolasnoble am I holding this wrong? How do I get it to merge?

**Comment by acozzette** [comment]
@ctiller I think if you add yourself as a reviewer in the UI then that should give you a way to formally approve the pull request.

**Review by ctiller — APPROVED** [review]

**Comment by acozzette** [comment]
@ctiller Thanks! Now I think we just have to wait for the tests to pass. I'm surprised they're taking this long but maybe that is normal.

**Comment by ctiller** [comment]
Should be O(hours) not O(days), but I don't remember how to poke them.

**Review by ananda1066 — APPROVED** [review]

**Pull request merged**
