### PR TITLE
Revert "Disabled the json_run_localhost:*_low_thread_count family of tests"

### PR DESCRIPTION
**Pull request by jtattermusch**
Reverts grpc/grpc#13813

There is a chance that the rootcause for the original issue #13122 was already fixed (by fixes for other flakes).

So far not ready to merge, but I'm doing some testing now.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__512.opt.new: 1
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__0.counters.new: 1
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__1.opt.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
When running, locally, I got only 1 timeout per 300 test runs (tests are quite slow to run) on TSAN.

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Corrupt JSON data (indicates timeout or crash): 
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_MinSockPair__0.counters.new: 1
    bm_fullstack_streaming_pump.BM_PumpStreamServerToClient_SockPair__512.counters.new: 1


[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Known failures: https://github.com/grpc/grpc/issues/13650

**Comment by jtattermusch** [comment]
@vjpai   @dgquintas   let's reintroduce the tests, otherwise they'll never get fixed. Based on my experiments, the flakiness rate is now much lower than what it used to be.

**Pull request merged**
