### PR TITLE
Remove cruft in interop commands for Go and Java

### PR DESCRIPTION
**Pull request by ejona86**
Stop compiling Go's client.go every invocation; it's already compiled.
The working directory does not need to be set. There's no need for using
bash. There's no need for interactive. server_host_override should _not_
be set, since the server_host is the correct value to use.

CC @dfawley

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,965,918      Total (=)      1,965,918

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,891,797      Total (>)     10,891,794

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by jtattermusch** [comment]
Those are good points, thanks for noticing those. The `go__master` and `java__master` files are just a subset of what actually needs to be edited to fix those (they are actually generated by https://github.com/grpc/grpc/blob/master/tools/interop_matrix/create_testcases.sh, which in turn uses run_interop_tests.py).

I know run_interop_tests.py and expecially run_interop_matrix.py are in need of simplification and cleanup, so I'll try to incorporate the suggested changes once I have get a chance.

Add using `-i` (interactive). I think those are being used because they make it possible to kill the entire run_interop_tests.py run in case you are running the script locally - so I might keep the `-i`. For other changes suggested, I don't have any reservations.

**Comment by ejona86** [comment]
I see. The working directory may be needed for some other languages, but I sort of expect it would be rarely needed. server_host_override is _currently_ necessary for C-based languages, but after some of the stuff is worked out from #16759 it shouldn't be specified for grpc-test.sandbox.googleapis.com and similar. (It should only be specified when we're using the test certificates; so in conjunction with --test_ca)

I've created #16911 to make it clear to others that these scripts are generated.

**Comment by jtattermusch** [comment]
This has been partially addressed by https://github.com/grpc/grpc/pull/17407/files.
I think java__master and go__master should be regenerated (https://github.com/grpc/grpc/tree/master/tools/interop_matrix#instructions-for-creating-new-test-cases) to reflect the changes to run_interop_tests.py

**Comment by ejona86** [comment]
@jtattermusch, I'm confused as to why the files weren't regenerated in #17407 when run_interop_tests.py was changed. I don't understand the process.

**Comment by jtattermusch** [comment]
Sorry for the delay, things are turning out to be more complex than I expected. I've tried to regenerate the test cases in https://github.com/grpc/grpc/pull/18878 according to the instructions (https://github.com/grpc/grpc/tree/master/tools/interop_matrix#instructions-for-creating-new-test-cases), but I'm facing a few more issues - let's discuss on that PR (the PR basically supersedes this one).

**Pull request closed without merging**
