### PR TITLE
Fix  more minor typos

### PR DESCRIPTION
**Pull request by NathanBaulch**
Just thought I'd contribute some more typo fixes I've stumbled upon. This is a followup on #37450.

Use the following command to get a quick and dirty summary of the specific corrections made:
```shell
git diff HEAD^! --word-diff-regex='\w+' -U0 \
  | grep -E '\[\-.*\-\]\{\+.*\+\}' \
  | sed -r 's/.*\[\-(.*)\-\]\{\+(.*)\+\}.*/\1 \2/' \
  | sort | uniq -c | sort -n
```

FWIW, the top typos are:
* compressable (134)
* existant (82)
* unparseable (49)
* occured (24)
* replys (18)
* validing (17)
* writter (16)
* vaidate (9)
* directoty (8)
* convertabl (8)
* atrributes (8)
* indxes (8)
* transfered (7)
* exchage (7)
* descedent (6)
* enpoint (6)
* nonexistant (6)
* matadata (6)
* addtional (5)
* callack (5)
* experenced (5)
* wil (5)

### CODE REVIEW

**Comment by drfloob** [comment]
Thanks for the cleanup, @NathanBaulch ! Would you mind breaking this up into smaller PRs of at most 50 files? Some of our change process is easier to manage with smaller PRs.

**Comment by NathanBaulch** [comment]
Sure thing @drfloob, I'll use this PR for the first 50 files.

**Review by drfloob — COMMENTED** [review]
Thanks @NathanBaulch. Everything looks good to me, but maybe the PHP and Ruby variable name changes.

@stanley-cheung can you check the PHP changes and make sure they don't affect anything (documentation, APIs, etc)

@apolcyn could you do the same for the Ruby changes?

Also @NathanBaulch , you'll need to merge master and re-push, there's a file conflict that'll prevent our tests from passing. And if possible, please don't force-push the branch, it makes reviews easier when there's a commit history attached to review iterations.

**Comment by drfloob** [comment]
@NathanBaulch I still haven't heard back about Ruby, but let's move forward. If there are ruby failures, we can roll this back and fix them.

The sanity tests are failing, due to bad clang-format. Please merge the latest master (not rebase & force-push, please), and run clang-format.

**Comment by NathanBaulch** [comment]
Oops, I should have checked this page before pushing a couple more fixes @drfloob - not sure what the kokoro results were. 😅

**Comment by drfloob** [comment]
> Oops, I should have checked this page before pushing a couple more fixes @drfloob - not sure what the most recent kokoro results were. 😅

You can click the `x` next to the commit hash to see the errors from the previous commit. 
image

None of the failures look related. Unfortunately there's a merge conflict, you'll need to re-merge master and we'll kick off the CI again. This is another reason to keep PRs small: the codebase can move fast, and having fewer files per PR reduces the likelihood of conflicts.

**Review by drfloob — APPROVED** [review]

**Review by yijiem — APPROVED** [review]

**Review by apolcyn — APPROVED** [review]
sorry for the delay, ruby LGTM

**Pull request closed without merging**
