### PR TITLE
Upgrade upb to commit at 2020-12-18

### PR DESCRIPTION
**Pull request by lidizheng**
This PR upgrades the upb subtree to upb's latest commit on 12/18/2020. It should unblock https://github.com/grpc/grpc/pull/24953 and https://github.com/grpc/grpc/pull/25038.

This upgrade touched a lot of files, and it wasn't a simple subtree update due to:

* The split of `*.upb.*` and `*.upbdefs.*` generator;
* The additional `third_party/wyhash/wyhash.h` dependency;
* Files rename or move;
* Changes to the generated upb files.

Unblocked by https://github.com/grpc/grpc/pull/24981

### CODE REVIEW

**Comment by veblush** [comment]
Lidi, can you upgrade the upb version to the recent HEAD? https://github.com/protocolbuffers/upb/commit/60607da72e89ba0c84c84054d2e562d8b6b61177

**Comment by lidizheng** [comment]
@veblush I will prioritize this. I'm still working on the CSDS PR itself... I wasn't sure if we need to upgrade upb again.

**Comment by veblush** [comment]
FYI, I just created https://github.com/grpc/grpc/pull/25037 for the test to see if the change I want is working.

**Comment by lidizheng** [comment]
The C# timeout on macOS is a [known failure](https://github.com/grpc/grpc/issues/25029).

**Comment by veblush** [comment]
Lidi, you can refer https://github.com/grpc/grpc/pull/25037 to fix the existing issues. My feedback are

- gen_upb_api.sh can be simplified more: https://github.com/grpc/grpc/pull/25037/commits/e4014fc2a60e3d9675b2cc00721bd826ce024486
- BUILD files can be kept as they're now when third_party/upb is added to .bazelignore: https://github.com/grpc/grpc/pull/25037/commits/7e38c5ec2ac149acace43dcf0c6c5eed8957579c
- wyhash shouldn't be added to our third_party directory since we don't need it. It can be addressed like https://github.com/grpc/grpc/pull/25037/commits/9f2b5f697bf8e855c1043eb64b0577bd58b2fdb6
- Some new files need to be added to gen_build_yaml.py: https://github.com/grpc/grpc/pull/25037/commits/93070f3ce3bb87a72f8f434090ddac7caf0092c3

**Comment by lidizheng** [comment]
Yield to https://github.com/grpc/grpc/pull/25037, since it has much better progress on fixing CI builds.

**Pull request closed without merging**
