### PR TITLE
Fix round_robin to avoid negative size_t value.

### LINKED ISSUE #16390: RoundRobin should not have last_ready_index_ have an initial value of -1
### What version of gRPC and what language are you using?
 
master, core
 
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
N/A

### What did you do?

Read the source for sign conversion issues

### What did you expect to see?
 
No sign conversion problems
 
### What did you see instead?

https://github.com/grpc/grpc/blob/8ba45636295019b101c1e9579423d4de41c4c59e/src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc#L183
 
A `size_t` is unsigned and should not have the value -1 as an initial value. ~~This is technically undefined.~~ Although this is technically defined in the C++11 standard in the way that you expect, compilers can and do warn about it since it's a bad code smell.

### PR DESCRIPTION
**Pull request by markdroth**
Fixes #16390.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                                FILE SIZE
 ++++++++++++++ GROWING                                                                  ++++++++++++++
  +0.1%     +16 src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc     +16  +0.1%
      +2.6%      +8 [Unmapped]                                                                    +8  +2.6%
      +0.3%      +8 grpc_core::(anonymous namespace)::RoundRobin::UpdateLocked                    +8  +0.3%

 -------------- SHRINKING                                                                --------------
  -0.0%     -16 [None]                                                                       -80  -0.0%

  [ = ]       0 TOTAL                                                                        -64  -0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,952,966      Total (>)      1,952,962

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,664,800      Total (>)     10,664,798

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by AspirinSJL** [comment]
This makes the log https://github.com/grpc/grpc/blob/af89e8c00e796f3398b09b7daed693df2b14da56/src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc#L608 inconsistent with the fact sometimes. That's not a big deal, but it's worth considering using `int` here. 

The style guide says we should "try to avoid unsigned types (except for representing bitfields or modular arithmetic)". https://google.github.io/styleguide/cppguide.html#Integer_Types

But the repo is already using a lot of `size_t`, so I don't have strong opinion on this.

**Comment by markdroth** [comment]
I think it's fine for that tracer log message to indicate the higher value.  The index is really an internal implementation detail, not something end users should know or care about, and the function of the tracer is to expose those internal implementation details for our own use when debugging.  So if the internal implementation changes, the log message should too.

**Comment by AspirinSJL** [comment]
Fair enough.

**Comment by markdroth** [comment]
Known failures: #16429 #16431 #15434

**Pull request merged**
