### PR TITLE
Performance-oriented server refactoring

### PR DESCRIPTION
**Pull request by vjpai**
1. Remove completion queue creation from under the C++ lock
2. Split the C server lock into two: one for global (e.g. channel) state, and one for per-call state

### CODE REVIEW

**Comment by ctiller** [comment]
This change requires #1577 to be merged first.

**Comment by vjpai** [comment]
Depends on #1577 . @ctiller - can you make the CLA-bot happy?

**Comment by vjpai** [comment]
Relates to issue #2017.

**Comment by vjpai** [comment]
The only failures now refer to gcov filling up. I'll wait for it to go green before asking for detailed reviews, but I've removed the DNM. Of course, it should still wait on #1577.

**Comment by vjpai** [comment]
And yes, we're green now!

**Comment by ctiller** [comment]
Didn't I mention LGTM already? I know I thought it :)

**Comment by vjpai** [comment]
ok, let me do a manual merge and push again, and then I'll let you know what's up

**Pull request merged**
