### PR TITLE
Macos system roots implementation

### PR DESCRIPTION
**Pull request by maliksaafir**
This implements the utilization of MacOS system root certificates. It's currently missing the implementation of a feature to remove distrusted certs from the cert pool gathered by the code.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.3% +1.89Ki [None]                                                              +28.0Ki  +0.3%
      +0.3% +1.92Ki [Unmapped]                                                          +28.0Ki  +0.3%
      [NEW]     +16 CSWTCH.83                                                               +16  [NEW]
  [NEW] +1.31Ki src/core/lib/security/security_connector/load_system_roots_linux.cc +1.31Ki  [NEW]
      [NEW]    +773 grpc_core::CreateRootCertsBundle                                       +773  [NEW]
      [NEW]    +225 grpc_core::LoadSystemRootCerts                                         +225  [NEW]
      [NEW]    +170 grpc_core::GetSystemRootCerts                                          +170  [NEW]
      [NEW]     +68 grpc_core::GetAbsoluteFilePath                                          +68  [NEW]
      [NEW]     +40 grpc_core::linux_cert_files_                                            +40  [NEW]
      [NEW]     +40 grpc_core::linux_cert_directories_                                      +40  [NEW]
      [NEW]     +29 [Unmapped]                                                              +29  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc         +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                    +168   +38%

  +0.2% +3.36Ki TOTAL                                                               +29.5Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.2% +1.79Ki [None]                                                              +27.9Ki  +0.3%
      +0.3% +1.71Ki [Unmapped]                                                          +27.8Ki  +0.3%
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertFiles                       +40  [NEW]
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertDirectories                 +40  [NEW]
      [NEW]     +16 CSWTCH.83                                                               +16  [NEW]
  [NEW] +1.43Ki src/core/lib/security/security_connector/load_system_roots_linux.cc +1.43Ki  [NEW]
      [NEW]    +921 grpc_core::CreateRootCertsBundle                                       +921  [NEW]
      [NEW]    +426 grpc_core::LoadSystemRootCerts                                         +426  [NEW]
      [NEW]    +105 grpc_core::GetAbsoluteFilePath                                         +105  [NEW]
      [NEW]     +14 [Unmapped]                                                              +14  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc         +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                    +168   +38%

  +0.2% +3.38Ki TOTAL                                                               +29.5Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                           FILE SIZE
 ++++++++++++++ GROWING                                                             ++++++++++++++
  +0.2% +1.79Ki [None]                                                              +27.9Ki  +0.3%
      +0.3% +1.71Ki [Unmapped]                                                          +27.8Ki  +0.3%
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertFiles                       +40  [NEW]
      [NEW]     +40 grpc_core::(anonymous namespace)::kLinuxCertDirectories                 +40  [NEW]
      [NEW]     +16 CSWTCH.83                                                               +16  [NEW]
  [NEW] +1.43Ki src/core/lib/security/security_connector/load_system_roots_linux.cc +1.43Ki  [NEW]
      [NEW]    +921 grpc_core::CreateRootCertsBundle                                       +921  [NEW]
      [NEW]    +426 grpc_core::LoadSystemRootCerts                                         +426  [NEW]
      [NEW]    +105 grpc_core::GetAbsoluteFilePath                                         +105  [NEW]
      [NEW]     +14 [Unmapped]                                                              +14  [NEW]
  +1.6%    +160 src/core/lib/security/security_connector/security_connector.cc         +160  +1.6%
       +38%    +168 grpc_core::DefaultSslRootStore::ComputePemRootCerts                    +168   +38%

  +0.2% +3.38Ki TOTAL                                                               +29.5Ki  +0.3%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +576  +0.0%

  [ = ]       0 TOTAL     +576  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]    +576  +0.0%

  [ = ]       0 TOTAL     +576  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by yang-g** [comment]
Seems obsolete, closing.

**Comment by equinox1993** [comment]
I wonder why this is closed without merging. Is there still a plan to use system trust store on Mac?

**Comment by nicolasnoble** [comment]
This is mainly a cleanup-close. Code that has been rotting since 8+ months probably needs revisiting.

**Pull request closed without merging**
