### PR TITLE
Cleanup of ObjC test scripts

### PR DESCRIPTION
**Pull request by jtattermusch**
While trying to debug some objc tests (trying to rootcause the CFStream problem), I found out that the test scripts badly need some cleanup.

This PR tries to avoid some of the code duplication (three copies of verbose_time.sh, really?) and make the scripts more consistent and repetitive.
The xcodebuild output filtering is a whole another chapter - it's been duplicated in multiple places with slightly different setup and I think in some cases it must have been broken - specifically if you apply the XCODE_BUILD_FILTER after you added timestamps at the beginning of each line, the filtering won't work anymore.

### CODE REVIEW

**Comment by jtattermusch** [comment]
Nits to fix:
https://source.cloud.google.com/results/invocations/0c6ece6e-8d1a-4441-a432-255123ee7cbc/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fios-buildtest-example-sample-frameworks/tests

https://source.cloud.google.com/results/invocations/84477b10-3f5d-4368-8dcb-1fee22453869/log

**Comment by dennycd** [comment]
cc @HannahShiSFB

**Review by dennycd — APPROVED** [review]
Thanks for the patch Jan.  LGTM.  I wonder if build_and_run_tests.sh & build_tests.sh can be further parameterized to reduce to one copy as the current logic across these 3 test suite are essentially the same except the project naming.

**Comment by jtattermusch** [comment]
> Thanks for the patch Jan. LGTM. I wonder if build_and_run_tests.sh & build_tests.sh can be further parameterized to reduce to one copy as the current logic across these 3 test suite are essentially the same except the project naming.

Agreed that the duplication seems unnecessary. We can look into that as a followup (hopefully we can come up with some way of deduplication without introducing complicated shell script with a lots of param/env variables because that also isn't ideal).

I think overall there are lots of opportunities for simplification and cleanup in the objc tests and I think pursuing them would be very worthwhile.

**Comment by jtattermusch** [comment]
Known failures:
- artifact build MacOS is b/209603283

**Pull request merged**
