### PR TITLE
Re-ordering interdependent proto files.

### PR DESCRIPTION
**Pull request by nicolasnoble**

### CODE REVIEW

**Comment by ctiller** [comment]
What problem does this solve?

Asking mainly because I thought I'd recently nailed all proto dependency problems :)

**Comment by nicolasnoble** [comment]
```
[CXX]     Compiling /home/nnoble/sources/grpc/gens/test/proto/benchmarks/control.pb.cc
In file included from /home/nnoble/sources/grpc/gens/test/proto/benchmarks/control.pb.cc:5:0:
/home/nnoble/sources/grpc/gens/test/proto/benchmarks/control.pb.h:31:47: fatal error: test/proto/benchmarks/payloads.pb.h: No such file or directory
 #include "test/proto/benchmarks/payloads.pb.h"
                                               ^
compilation terminated.
make: *** [/home/nnoble/sources/grpc/objs/opt//home/pixel/sources/grpc/gens/test/proto/benchmarks/control.pb.o] Error 1
```

`control.proto` depends on `payloads.proto`, and `services.proto` depends on `stats.proto`.

**Comment by nicolasnoble** [comment]
Also, green enough.

**Comment by ctiller** [comment]
I missed the 0.12 thing.

**Comment by nicolasnoble** [comment]
Yep, 0.12 fails a simple `make test` because of that, and that would prevent Debian packages. So let's fix it :-)

**Pull request merged**
