### PR TITLE
Adding a build template for generic GYP build.

### PR DESCRIPTION
**Pull request by mdzoba**
This is useful for clients (like DriveFS) who use GYP for cross-platform builds. 
Tested by building on Windows and macOS.

Note that this PR goes against the suggestion to submit changes to templates and generated files at the same time.  This is intentional because 
1) I don't think the suggestion applies for **initial** template check-ins
2) It's useful for reviewers to see the generated file to evaluate correctness of the template.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by nicolasnoble** [comment]
Jenkins: This is ok to test.

**Pull request merged**
