### PR TITLE
Release 0.11 to master

### PR DESCRIPTION
**Pull request by jcanizales**

### CODE REVIEW

**Comment by jcanizales** [comment]
@bjori: The googlebot wants me to notify you that your commit 63256a7 is going to be merged into grpc/master :)

**Comment by jcanizales** [comment]
@nicolasnoble: The merge conflict is on `.gitignore` (easy to solve - just stuff added at the end of the file) and on `gRPC.podspec` (which is solved [this way](https://github.com/jcanizales/grpc/commit/a94184576383861ab229349a4fdd7fcb32d0d986#diff-58d38516b053c0af69d6ef06a7c1ec74)).

**Comment by jcanizales** [comment]
Removing the cla: no label because @bjori has already signed the CLA in #3685.

**Comment by nicolasnoble** [comment]
Did you do a PR to solve the conflict ?

**Comment by jcanizales** [comment]
Sorry, I was preempted - doing it now.

**Comment by nicolasnoble** [comment]
*sigh* that won't be solved automatically, unfortunately...

**Comment by nicolasnoble** [comment]
*AHEUM*

Why did you delete the release branch... ?

**Comment by jcanizales** [comment]
LOL
Habit click for PRs from my fork.

**Pull request merged**
