### PR TITLE
Fix Android + CPP build

### PR DESCRIPTION
**Pull request by perumaalgoog**
This allows building the CPP bindings in Android and avoids the Linux/Posix/Android preprocessor macros conflicts.
Ran the C tests.

### CODE REVIEW

**Comment by sreecha** [comment]
LGTM. @nicolasnoble , can you also take a look?

**Comment by nicolasnoble** [comment]
This is ok to test.

**Comment by nicolasnoble** [comment]
So, I'd rather see something in port_platform.h that does the right thing instead.

**Comment by nicolasnoble** [comment]
Basically, changing https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/port_platform.h#L158 and https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/port_platform.h#L170

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/
* User @perumaalgoog isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Pull request merged**
