### PR TITLE
Let CFStreamHandle be covered by grpc_init/shutdown

### PR DESCRIPTION
**Pull request by yang-g**

### CODE REVIEW

**Comment by rmstar** [comment]
See internal bug 137799633 for context on this issue.

**Comment by muxi** [comment]
When does `GrpcLibraryInitHolder::GrpcLibraryInitHolder()` get called?

**Comment by muxi** [comment]
Oh I see never mind. Not sure why I asked that dumb question

**Comment by yang-g** [comment]
Test failures: #19669 #19802

**Comment by rmstar** [comment]
Fixes #19607

**Pull request merged**
