### PR TITLE
Upgrade protobuf version to 3.16.0-rc1

### PR DESCRIPTION
**Pull request by acozzette**
This pull request should not be merged but is for just testing for any issues with the upcoming protobuf 3.16.0 release.

@markdroth

### CODE REVIEW

**Comment by acozzette** [comment]
@jtattermusch Would you mind adding the necessary labels to run the tests when you have a chance?

**Comment by jtattermusch** [comment]
@yashykt, since you're the release manager for the upcoming grpc 1.38 release, can you please make sure that there's no issues indicated by this PR, so that we can upgrade to protobuf 3.16.0 once the release is out available?
(upgrading third_party/protobuf is part of the release process). Thanks!

**Comment by yashykt** [comment]
Note that the protobuf version was recently updated to 3.15.8 with #26105

**Comment by yashykt** [comment]
From the previous test runs, it looks like `Basic Tests C++ iOS` failed. I see log messages of the form - 
```
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/test/cpp/ios/Pods/Headers/Private/RemoteTestCpp/src/proto/grpc/testing/echo_messages.pb.h:12:2: error: This file was generated by a newer version of protoc which is
Wed Apr 21 10:37:14 PDT 2021 - #error This file was generated by a newer version of protoc which isWed Apr 21 10:37:14 PDT 2021 -  ^
Wed Apr 21 10:37:14 PDT 2021 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/test/cpp/ios/Pods/Headers/Private/RemoteTestCpp/src/proto/grpc/testing/echo_messages.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
Wed Apr 21 10:37:14 PDT 2021 - #error incompatible with your Protocol Buffer headers. Please update
Wed Apr 21 10:37:14 PDT 2021 -  ^
Wed Apr 21 10:37:14 PDT 2021 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/test/cpp/ios/Pods/Headers/Private/RemoteTestCpp/src/proto/grpc/testing/echo_messages.pb.h:14:2: error: your headers.
Wed Apr 21 10:37:14 PDT 2021 - #error your headers.```

It looks like not everything was updated properly in this PR.

**Pull request closed without merging**
