### PR TITLE
Backport PHP PECL extension to main 0.9.1 release

### PR DESCRIPTION
**Pull request by stanley-cheung**
* the PHP PECL extension version 0.5.0 will work on top of the core grpc version 0.9.1
 * Issue: #2083
 * Mainline PR: #2084

### CODE REVIEW

**Comment by stanley-cheung** [comment]
jenkins failed because the release branch does not have the latest run_jenkins script yet.

**Comment by tbetbetbe** [comment]
LGTM.

@nicolasnoble, PTAL

**Comment by nicolasnoble** [comment]
That looks fine, yes.

**Comment by stanley-cheung** [comment]
Thanks!

**Pull request merged**
