### PR TITLE
Revert hotfix; use more permanent fix

### PR DESCRIPTION
**Pull request by brandonpaiz**
Changes `loadtest_template_prebuilt_all_languages.yaml` to call `run_worker.sh` added in grpc/test-infra/pull/231

### CODE REVIEW

**Comment by brandonpaiz** [comment]
Do the changes in `loadtest_template_prebuilt_all_languages.yaml` need to be added to `loadtest_template_basic_all_languages.yaml` as well? What about the templates/samples in grpc-testing?

**Review by paulosjca — APPROVED** [review]
I see the necessary changes to match https://github.com/grpc/test-infra/pull/231 are here – thanks!

**Review by wanlin31 — APPROVED** [review]

**Comment by brandonpaiz** [comment]
This PR can now be merged as grpc/test-infra/pull/231 has been merged

**Comment by jtattermusch** [comment]
Thanks for the fix, let's doublecheck in a day or two that this didn't lead to any java regressions in the dashboard.

**Pull request merged**
