### PR TITLE
add secure hello world example

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Loong <loong.dai@intel.com>

Add a secure example to clarify how to use TLS with gRPC.

Most from https://github.com/grpc/grpc/issues/9593#issuecomment-277946137.

### CODE REVIEW

**Comment by daixiang0** [comment]
@ctiller could you help trigger CI?

**Comment by daixiang0** [comment]
@lidizheng could you help review it?

**Comment by lidizheng** [comment]
Routing to @drfloob

**Comment by daixiang0** [comment]
@drfloob please review, now all CI pass.

**Comment by drfloob** [comment]
Hi @daixiang0. I see this is not configured in the bazel BUILD file, that would need to be done. I recall seeing SSL library errors in the CI output before, which I can't find now due to a force-push on your branch. I'm guessing it's not possible to keep this code under test unless the certificate files are added to the repo.

I believe there are also some SSL credential examples in the `test/cpp/end2end`, which exercise the same code in (hopefully) readable ways, but I haven't had a moment to review them. I'll try to do so today.

**Comment by daixiang0** [comment]
@drfloob thanks for review, I have updated BUILD. As in the example README, it use `make` to build rather than `bazel`, I think build and test are OK. Also there is no CI step for example.

**Comment by drfloob** [comment]
I found this exact same code posted as a comment in https://github.com/grpc/grpc/issues/9593#issuecomment-277946137 in 2017. Is this where you got it from @daixiang0 , and/or are you also @jagranados-dev?

**Comment by daixiang0** [comment]
Yes, I got from it, I have updated commit decription.

**Comment by drfloob** [comment]
This is a bit complicated, unfortunately, please see [CONTRIBUTING.md](https://github.com/grpc/grpc/blob/26ee00db1e6a3cd413bafa3f9ba63b4cd2a77bb4/CONTRIBUTING.md). We would need the original author to sign the CLA and submit the work.

**Comment by daixiang0** [comment]
ping @jagranados-dev

**Comment by jagranados-dev** [comment]
> Hi @jagranados-dev, It is a really good example for the secure case and very helpful for beginners, could you post a PR for it or authorize me to do this thing?

Ok, I'll sign the CLA and post a new PR with the example. Thank you!!

**Comment by daixiang0** [comment]
@jagranados-dev thanks :)

**Comment by daixiang0** [comment]
in favour of #28727

**Pull request closed without merging**
