### PR TITLE
Do not crash if server filter fails at ChannelData::Init

### PR DESCRIPTION
**Pull request by yang-g**
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/24577)

### CODE REVIEW

**Comment by yashykt** [comment]
I thought we discussed in the standup that we did not want to do this?

**Comment by yang-g** [comment]
Adding @markdroth, as I do not recall we discussed this.

**Review by markdroth — CHANGES_REQUESTED** [review]
I don't remember saying that we don't want to do this.  I think I just said that I was interested in seeing what the problem was, and this PR answers that question. :)

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24577#-:-ML9hg6E7gAG0YKK27dF:bbd6f7q)* status: all files reviewed, 6 unresolved discussions (waiting on @yang-g and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 253 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9eqHaCDGPDNSn0WT7:-ML9eqHaCDGPDNSn0WT8:b-ovpqpc) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L253)):*
> ```cpp
>           grpc_timer_init(&self->timer_, self->deadline_, &self->on_timeout_);
>         } else {
>           // Failed to create channel from transport. Clean up.
> ```

Don't we also have to free the read buffer in this case?

I'm pretty sure the transport takes ownership of the endpoint, so that should happen automatically.  What about the channel args and resource user?
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 253 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9et2F-9KBQp1bwgk0:-ML9et2F-9KBQp1bwgk1:b-7tyzcw) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L253)):*
> ```cpp
>           grpc_timer_init(&self->timer_, self->deadline_, &self->on_timeout_);
>         } else {
>           // Failed to create channel from transport. Clean up.
> ```

We should log an error indicating what happened here.
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9gHXX-uhoADGqiyOP:-ML9gHXYDzAXjsHC1I4v:b99ydyr) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L63)):*
> ```cpp
>     grpc_chttp2_transport_start_reading(transport, nullptr, nullptr);
>   } else {
>     grpc_transport_destroy(transport);
> ```

Don't we need to remove the endpoints from the pollsets here that we added above?  Or maybe just not add them to the pollsets until after we know this has succeeded?
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9ghj568HmFJyV2-m8:-ML9ghj568HmFJyV2-m9:b-wog1wc) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L63)):*
> ```cpp
>     grpc_chttp2_transport_start_reading(transport, nullptr, nullptr);
>   } else {
>     grpc_transport_destroy(transport);
> ```

How will this error be propagated back to the application?  Is there any way for the application to know this has failed?
___
*[src/core/lib/surface/server.h, line 118 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9dsOU6XT-70o8m8hN:-ML9dsOU6XT-70o8m8hO:buhlszh) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/lib/surface/server.h#L118)):*
> ```objc
>   // Sets up a transport.  Creates a channel stack and binds the transport to
>   // the server.  Called from the listener when a new connection is accepted.
>   bool SetupTransport(grpc_transport* transport,
> ```

Can we have this return a `grpc_error*` indicating the actual error that the filter returned, so that the caller can log it properly?  It doesn't look like it will be too hard to do this; we just need to return it up through `grpc_channel_stack_builder_finish()` and `grpc_channel_create()`.

If that won't work for some reason, let's at least document the fact that this returns false on error.
___
*[test/cpp/end2end/filter_end2end_test.cc, line 360 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9ckt21qnOFeGkXOXD:-ML9ckt21qnOFeGkXOXE:b-qn3eob) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/test/cpp/end2end/filter_end2end_test.cc#L360)):*
> ```cpp
> };
> 
> TEST_F(ChannelInitErrorTest, InitErrorWorks) {
> ```

Instead of adding this new test here, can you fix the tests in test/core/end2end/tests/filter_call_init_fails.cc to cover this case?

**Comment by yashykt** [comment]
I might have misheard in that case.

**Review by yang-g — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24577)* status: 0 of 18 files reviewed, 6 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 253 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9eqHaCDGPDNSn0WT7:-MLsICmO2hgHnGvW6AUv:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L253)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't we also have to free the read buffer in this case?

I'm pretty sure the transport takes ownership of the endpoint, so that should happen automatically.  What about the channel args and resource user?
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/chttp2_server.cc, line 253 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9et2F-9KBQp1bwgk0:-MLsIDQo3homeNBT9Fyc:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/chttp2_server.cc#L253)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

We should log an error indicating what happened here.
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9gHXX-uhoADGqiyOP:-MLsIGyz-C3h_Bwlhz90:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L63)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Don't we need to remove the endpoints from the pollsets here that we added above?  Or maybe just not add them to the pollsets until after we know this has succeeded?
</blockquote></details>

Done.
___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9ghj568HmFJyV2-m8:-MLsIJFdEArkjVWj5o07:b-xnh2h7) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L63)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

How will this error be propagated back to the application?  Is there any way for the application to know this has failed?
</blockquote></details>

We cannot bubble up the error. The server does not know besides the log line. The client will only see a connect failure.
___
*[src/core/lib/surface/server.h, line 118 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9dsOU6XT-70o8m8hN:-MLsIbYr9bJN3_txbS1z:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/lib/surface/server.h#L118)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can we have this return a `grpc_error*` indicating the actual error that the filter returned, so that the caller can log it properly?  It doesn't look like it will be too hard to do this; we just need to return it up through `grpc_channel_stack_builder_finish()` and `grpc_channel_create()`.

If that won't work for some reason, let's at least document the fact that this returns false on error.
</blockquote></details>

Done.
___
*[test/cpp/end2end/filter_end2end_test.cc, line 360 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9ckt21qnOFeGkXOXD:-MLsIfW31px6SZfYiJs9:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/test/cpp/end2end/filter_end2end_test.cc#L360)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of adding this new test here, can you fix the tests in test/core/end2end/tests/filter_call_init_fails.cc to cover this case?
</blockquote></details>

Done.

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks pretty good!  Remaining comments are relatively minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24577#-:-MLsOTk86-5CO3HNlwbp:b-j4cf44)* status: all files reviewed, 5 unresolved discussions (waiting on @yang-g and @yashykt)

___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9ghj568HmFJyV2-m8:-MLsMfLVE35bQS35qCV7:b-j6temq) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L63)):*
<details><summary><i>Previously, yang-g (Yang Gao) wrote…</i></summary><blockquote>

We cannot bubble up the error. The server does not know besides the log line. The client will only see a connect failure.
</blockquote></details>

But the application needs to know if the channel is valid.  Don't we need to either return null for the channel or maybe return a lame channel here?  Otherwise, the application will try to use a channel that has no transport.  What will happen if it does that?
___
*[test/core/end2end/tests/filter_init_fails.cc, line 173 at r2](https://reviewable.io/reviews/grpc/grpc/24577#-MLsNQJ25dvQsx4oe-Bp:-MLsNQJ25dvQsx4oe-Bq:b-75tzvd) ([raw file](https://github.com/grpc/grpc/blob/64b2a39a623fcae61448ef858d8034d916cfba31/test/core/end2end/tests/filter_init_fails.cc#L173)):*
> ```cpp
> 
>   if (g_channel_filter_init_failure == true) {
>     // Inproc channel returns unknown and other clients return unavailable.
> ```

Why does inproc not return UNAVAILABLE?  It seems like that's the right code here.
___
*[test/core/end2end/tests/filter_init_fails.cc, line 268 at r2](https://reviewable.io/reviews/grpc/grpc/24577#-MLsNXfF7ezk46BtXrmm:-MLsNXfF7ezk46BtXrmn:bf8dfq3) ([raw file](https://github.com/grpc/grpc/blob/64b2a39a623fcae61448ef858d8034d916cfba31/test/core/end2end/tests/filter_init_fails.cc#L268)):*
> ```cpp
> 
>   if (g_channel_filter_init_failure) {
>     gpr_log(GPR_ERROR, "XXX status %d %s", status,
> ```

I assume this was just added for debugging?
___
*[test/core/end2end/tests/filter_init_fails.cc, line 270 at r2](https://reviewable.io/reviews/grpc/grpc/24577#-MLsNofJ210JT5EPyVKf:-MLsNofJ210JT5EPyVKg:b-fspyd1) ([raw file](https://github.com/grpc/grpc/blob/64b2a39a623fcae61448ef858d8034d916cfba31/test/core/end2end/tests/filter_init_fails.cc#L270)):*
> ```cpp
>     gpr_log(GPR_ERROR, "XXX status %d %s", status,
>             GRPC_SLICE_START_PTR(details));
>     GPR_ASSERT(status == GRPC_STATUS_UNKNOWN);
> ```

This should be UNAVAILABLE.
___
*[test/core/end2end/tests/filter_init_fails.cc, line 432 at r2](https://reviewable.io/reviews/grpc/grpc/24577#-MLsNxvS9x4Y7jfgvJis:-MLsNxvS9x4Y7jfgvJit:bpmulkd) ([raw file](https://github.com/grpc/grpc/blob/64b2a39a623fcae61448ef858d8034d916cfba31/test/core/end2end/tests/filter_init_fails.cc#L432)):*
> ```cpp
>                                      grpc_channel_element_args* /*args*/) {
>   if (g_channel_filter_init_failure) {
>     return GRPC_ERROR_CREATE_FROM_STATIC_STRING(
> ```

Please attach a gRPC status to this error, so that we can make sure that the status code from this error is the one returned for calls on the resulting channel.

**Review by yang-g — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24577)* status: 8 of 21 files reviewed, 5 unresolved discussions (waiting on @markdroth and @yashykt)

___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9ghj568HmFJyV2-m8:-MLsuRJUB1ALaWoC01Ai:b-byg5lz) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L63)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

But the application needs to know if the channel is valid.  Don't we need to either return null for the channel or maybe return a lame channel here?  Otherwise, the application will try to use a channel that has no transport.  What will happen if it does that?
</blockquote></details>

Nothing will happen. The server does not really have this channel because the attempt to create the channel failed.

I agree it would be better to notify the user somehow and can see several options.
1. Since this is a less often used call and channel filter init failure is a corner case itself, we can just assert the SetupTransport must succeed.
2. We can change the API to return an grpc_error, but this is a public API.
3. We can open up the reserved pointer to return an error. It does not help the C++ user as there is no way to return that error from `AddInsecureChannelFromFd`
4. Do nothing and rely on the error log and the fact that client RPCs will fail.

Wdyt?
___
*[test/core/end2end/tests/filter_init_fails.cc, line 173 at r2](https://reviewable.io/reviews/grpc/grpc/24577#-MLsNQJ25dvQsx4oe-Bp:-MLtCUUk6HVvAvpm75Uf:boqlp2) ([raw file](https://github.com/grpc/grpc/blob/64b2a39a623fcae61448ef858d8034d916cfba31/test/core/end2end/tests/filter_init_fails.cc#L173)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Why does inproc not return UNAVAILABLE?  It seems like that's the right code here.
</blockquote></details>

For inproc, the lame channel is used, and I believe the lame channel has a bug that it does not cause the rpc to fail with its given code and message...
I sent out #24731 for that  purpose.
___
*[test/core/end2end/tests/filter_init_fails.cc, line 268 at r2](https://reviewable.io/reviews/grpc/grpc/24577#-MLsNXfF7ezk46BtXrmm:-MLsvZ_F8A9J1Htj_OMy:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/64b2a39a623fcae61448ef858d8034d916cfba31/test/core/end2end/tests/filter_init_fails.cc#L268)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

I assume this was just added for debugging?
</blockquote></details>

Done.
___
*[test/core/end2end/tests/filter_init_fails.cc, line 270 at r2](https://reviewable.io/reviews/grpc/grpc/24577#-MLsNofJ210JT5EPyVKf:-MMN5D-XAzWQ-WjmFhu_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/64b2a39a623fcae61448ef858d8034d916cfba31/test/core/end2end/tests/filter_init_fails.cc#L270)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This should be UNAVAILABLE.
</blockquote></details>

Done.
___
*[test/core/end2end/tests/filter_init_fails.cc, line 432 at r2](https://reviewable.io/reviews/grpc/grpc/24577#-MLsNxvS9x4Y7jfgvJis:-MLti2SJ01NdUcxFajrv:bhasov) ([raw file](https://github.com/grpc/grpc/blob/64b2a39a623fcae61448ef858d8034d916cfba31/test/core/end2end/tests/filter_init_fails.cc#L432)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Please attach a gRPC status to this error, so that we can make sure that the status code from this error is the one returned for calls on the resulting channel.
</blockquote></details>

That will require us to actually bubble up the error. Done.

**Review by markdroth — APPROVED** [review]
Thanks for doing this!

> Reviewed 12 of 13 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/24577#-:-MMRPfGYB1ZsdWThHu1P:bxgavm9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yashykt)

___
*[src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc, line 63 at r1](https://reviewable.io/reviews/grpc/grpc/24577#-ML9ghj568HmFJyV2-m8:-MMROPSg0kGQf056svSj:bih6uvk) ([raw file](https://github.com/grpc/grpc/blob/09bc137e1f692679109fb743bee1da418488968b/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc#L63)):*
<details><summary><i>Previously, yang-g (Yang Gao) wrote…</i></summary><blockquote>

Nothing will happen. The server does not really have this channel because the attempt to create the channel failed.

I agree it would be better to notify the user somehow and can see several options.
1. Since this is a less often used call and channel filter init failure is a corner case itself, we can just assert the SetupTransport must succeed.
2. We can change the API to return an grpc_error, but this is a public API.
3. We can open up the reserved pointer to return an error. It does not help the C++ user as there is no way to return that error from `AddInsecureChannelFromFd`
4. Do nothing and rely on the error log and the fact that client RPCs will fail.

Wdyt?
</blockquote></details>

I see your point.  I guess for now, option 4 is the best -- let's just leave this as-is.

I suspect that we will run into this problem at some point, because filter authors are going to assume that it's okay to fail creation, and they're not going to be thinking about this weird edge case that doesn't handle it properly.  But I guess we can cross that bridge when we get to it.

**Comment by yang-g** [comment]
Failure seems from failing to fetch remotejdk11_linux.

**Pull request merged**
