### PR TITLE
Implement C++ Admin Interface API

### PR DESCRIPTION
**Pull request by lidizheng**
Spec: https://github.com/grpc/proposal/blob/master/A38-admin-interface-api.md

Note that server builder does not take ownership of the input services. So, this PR takes a rather brutal-force solution to create global variables to store the service implementations. This should be no worse than existing code, because `server_builder.cc` keeps a global vector `g_plugin_factory_list` to store the factory classes, and it lives in heap forever.

The CI job won't run because CSDS got reverted, but the manual runs are passing.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/25753)

### CODE REVIEW

**Review by markdroth — CHANGES_REQUESTED** [review]
This looks good overall!  Comments are mostly minor.

Please let me know if you have any questions.  Thanks!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25753#-:-MWBjPzy11D4FzhRnCJA:bnzmleu)* status: all files reviewed, 6 unresolved discussions (waiting on @lidizheng)

___
*[include/grpcpp/ext/admin_services.h, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBiHNF6jXqCKVjvh2D:-MWBiHNF6jXqCKVjvh2E:bxoqagp) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/include/grpcpp/ext/admin_services.h#L25)):*
> ```objc
> 
> namespace grpc {
> namespace experimental {
> ```

If we're going to tell people to use this after this release, it should not be in the `experimental` namespace.
___
*[src/cpp/server/admin/admin_services.cc, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBhgdE0zBMc_EpMia2:-MWBhgdE0zBMc_EpMia3:bajtmoj) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/src/cpp/server/admin/admin_services.cc#L28)):*
> ```cpp
> #include <grpcpp/server_builder.h>
> 
> #include "src/cpp/server/channelz/channelz_service.h"
> ```

Hard-coding these dependencies is okay for now, given that we want to get this in before we cut the next release, but it's not really the way I think this should work in the long run.  Please add a TODO here to build a real registration system before we add the next dependency.
___
*[src/cpp/server/admin/admin_services.cc, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBh1qKDwNIj9Qy3GUJ:-MWBh1qKDwNIj9Qy3GUK:bsgpfw7) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/src/cpp/server/admin/admin_services.cc#L38)):*
> ```cpp
> namespace {
> 
> auto g_channelz_service = absl::make_unique<ChannelzService>();
> ```

The style guide prohibits global variables that are not trivially destructible:

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

The end of that section suggests some possible work-arounds.
___
*[test/cpp/end2end/admin_services_end2end_test.cc, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBi53pDU5YMw817eIm:-MWBi53pDU5YMw817eIn:b-814hi9) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/test/cpp/end2end/admin_services_end2end_test.cc#L38)):*
> ```cpp
>   std::ostringstream s;
>   int p = grpc_pick_unused_port_or_die();
>   s << "localhost:" << p;
> ```

`return absl::StrCat("localhost:", p);`
___
*[test/cpp/end2end/admin_services_end2end_test.cc, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBiZkE45SEdYgbCJTo:-MWBiZkE45SEdYgbCJTp:b-i49xe0) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/test/cpp/end2end/admin_services_end2end_test.cc#L74)):*
> ```cpp
>   }
> 
>   std::shared_ptr<Channel> GetChannel() { return channel_; }
> ```

This doesn't appear to be used anywhere.
___
*[test/cpp/end2end/admin_services_end2end_test.cc, line 86 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBijFs-9qs7PkVCToJ:-MWBijFtAY6Cau3FW5BL:b-yeftns) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/test/cpp/end2end/admin_services_end2end_test.cc#L86)):*
> ```cpp
> };
> 
> #ifndef GRPC_NO_XDS
> ```

Can just say:

```
TEST_F(AdminServicesTest, ServicesExported) {
  EXPECT_THAT(GetServiceList(),
              ::testing::UnorderedElementsAre(
#ifndef GRPC_NO_XDS
                  "envoy.service.status.v3.ClientStatusDiscoveryService",
#endif  // !GRPC_NO_XDS
                  "grpc.channelz.v1.Channelz",
                  "grpc.reflection.v1alpha.ServerReflection"));
}
```

**Review by lidizheng — COMMENTED** [review]
Thanks for the quick review! PTALA.

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25753#-:-MWBqAa8--3MSJ_1ckEo:bkxagfy)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @markdroth)

___
*[include/grpcpp/ext/admin_services.h, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBiHNF6jXqCKVjvh2D:-MWBlUkn1K2b4g40rhoY:bq10g5q) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/include/grpcpp/ext/admin_services.h#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

If we're going to tell people to use this after this release, it should not be in the `experimental` namespace.
</blockquote></details>

Removed.

Just curious, what's the gRPC Core/C++'s rule for adding new APIs? For gRPC Python API, we usually add an "experimental" note in new APIs; for Java API, I think they add experimental decorators and create issues to track experimental-graduation progress.
___
*[src/cpp/server/admin/admin_services.cc, line 28 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBhgdE0zBMc_EpMia2:-MWBmSYm4_wH8axlHTPG:b-7p6kwv) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/src/cpp/server/admin/admin_services.cc#L28)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Hard-coding these dependencies is okay for now, given that we want to get this in before we cut the next release, but it's not really the way I think this should work in the long run.  Please add a TODO here to build a real registration system before we add the next dependency.
</blockquote></details>

Added:
```
// TODO(lidiz) build a real registration system that can pull in services
// automatically with minimum amount of code.
```
___
*[src/cpp/server/admin/admin_services.cc, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBh1qKDwNIj9Qy3GUJ:-MWBpoqNEynsAT7IG05t:b-291jyp) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/src/cpp/server/admin/admin_services.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The style guide prohibits global variables that are not trivially destructible:

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

The end of that section suggests some possible work-arounds.
</blockquote></details>

Applied common pattern No.3, "...use a plain pointer to a dynamically allocated object and never delete it...". ASAN/MSAN seems cool with this.
___
*[test/cpp/end2end/admin_services_end2end_test.cc, line 38 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBi53pDU5YMw817eIm:-MWBotQw1as5-shzUibq:btvlxp6) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/test/cpp/end2end/admin_services_end2end_test.cc#L38)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

`return absl::StrCat("localhost:", p);`
</blockquote></details>

Inlined, since StrCat can shorten this 4 LOC to 1 LOC.
___
*[test/cpp/end2end/admin_services_end2end_test.cc, line 74 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBiZkE45SEdYgbCJTo:-MWBp9f45qrugt3UMvPw:bmsbnv3) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/test/cpp/end2end/admin_services_end2end_test.cc#L74)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This doesn't appear to be used anywhere.
</blockquote></details>

Removed, also removed the `channel_` member variable.
___
*[test/cpp/end2end/admin_services_end2end_test.cc, line 86 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBijFs-9qs7PkVCToJ:-MWBpUEd5hRhtKIiQ2uh:b-ydonj4) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/test/cpp/end2end/admin_services_end2end_test.cc#L86)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Can just say:

```
TEST_F(AdminServicesTest, ServicesExported) {
  EXPECT_THAT(GetServiceList(),
              ::testing::UnorderedElementsAre(
#ifndef GRPC_NO_XDS
                  "envoy.service.status.v3.ClientStatusDiscoveryService",
#endif  // !GRPC_NO_XDS
                  "grpc.channelz.v1.Channelz",
                  "grpc.reflection.v1alpha.ServerReflection"));
}
```
</blockquote></details>

Done. Good idea!

**Review by markdroth — APPROVED** [review]
This looks great!  Feel free to merge after addressing my one remaining comment.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25753#-:-MWQ12_v0LkO8thfq_Zz:bkw4c1b)* status: all files reviewed, 1 unresolved discussion (waiting on @lidizheng)

___
*[include/grpcpp/ext/admin_services.h, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBiHNF6jXqCKVjvh2D:-MWPzwpI9BPb3zN3qnPQ:b-moulwd) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/include/grpcpp/ext/admin_services.h#L25)):*
<details><summary><i>Previously, lidizheng (Lidi Zheng) wrote…</i></summary><blockquote>

Removed.

Just curious, what's the gRPC Core/C++'s rule for adding new APIs? For gRPC Python API, we usually add an "experimental" note in new APIs; for Java API, I think they add experimental decorators and create issues to track experimental-graduation progress.
</blockquote></details>

The point of marking an API experimental is to let people know that it is still subject to non-backward-compatible changes, so they can't yet count on it to be stable -- any code they write using it may need to change later.  But if we're actually going to tell people to use this in Google Cloud documentation, then it needs to be stable before we do that.

The only real prerequisite for adding a non-experimental API is a gRFC.  Normally, if we have time and if the API is complex enough, I would prefer to make it experimental and let people use it for a little while before publishing a gRFC and making it non-experimental.  But in this case, we need it quickly, and the API is sufficiently simple that I'm not too worried about there being any hidden design flaws that we haven't yet identified.

All of the above should be true across all languages.
___
*[src/cpp/server/admin/admin_services.cc, line 39 at r2](https://reviewable.io/reviews/grpc/grpc/25753#-MWQ0arj-BfI1T0BxlPk:-MWQ0arkEvD26XNxILnP:b-h71096) ([raw file](https://github.com/grpc/grpc/blob/66bf15f0e40dba397a1fea220739bb19bbc5504a/src/cpp/server/admin/admin_services.cc#L39)):*
> ```cpp
> 
> static auto* g_channelz_service = new ChannelzService();
> static_assert(std::is_trivially_destructible<ChannelzService*>::value, "");
> ```

No need for these assertions.  Raw pointers (of any type) are always trivially destructible.

**Review by lidizheng — COMMENTED** [review]
Thanks for the review! The "ifndef" usage in test cases was reverted to an earlier version, because MSVC fails if we have "ifndef" statement within macros (e.g., `TEST_F` and `EXPECT_THAT`). See log: https://source.cloud.google.com/results/invocations/23b72798-34f1-4209-86e0-571060893144/log

> *[Reviewable](https://reviewable.io/reviews/grpc/grpc/25753#-:-MWQaNLEB4NZNUuOvsQm:b3753us)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @markdroth)

___
*[include/grpcpp/ext/admin_services.h, line 25 at r1](https://reviewable.io/reviews/grpc/grpc/25753#-MWBiHNF6jXqCKVjvh2D:-MWQ23wK9XhKfI22R8Js:bwwhy84) ([raw file](https://github.com/grpc/grpc/blob/d7bdd7a67d1e8aff8d885a15fa572403e0dac4dd/include/grpcpp/ext/admin_services.h#L25)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

The point of marking an API experimental is to let people know that it is still subject to non-backward-compatible changes, so they can't yet count on it to be stable -- any code they write using it may need to change later.  But if we're actually going to tell people to use this in Google Cloud documentation, then it needs to be stable before we do that.

The only real prerequisite for adding a non-experimental API is a gRFC.  Normally, if we have time and if the API is complex enough, I would prefer to make it experimental and let people use it for a little while before publishing a gRFC and making it non-experimental.  But in this case, we need it quickly, and the API is sufficiently simple that I'm not too worried about there being any hidden design flaws that we haven't yet identified.

All of the above should be true across all languages.
</blockquote></details>

Nice to know that we can graduate an API with gRFC. I will follow this usage definition of "experimental" and "stable".
___
*[src/cpp/server/admin/admin_services.cc, line 39 at r2](https://reviewable.io/reviews/grpc/grpc/25753#-MWQ0arj-BfI1T0BxlPk:-MWQ23Vk93fBVZHzEfw_:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/66bf15f0e40dba397a1fea220739bb19bbc5504a/src/cpp/server/admin/admin_services.cc#L39)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

No need for these assertions.  Raw pointers (of any type) are always trivially destructible.
</blockquote></details>

Done.

**Comment by lidizheng** [comment]
Known failures: https://github.com/grpc/grpc/issues/19523

**Pull request merged**
