### PR TITLE
Limit the number of threads doing epoll at any given time

### PR DESCRIPTION
**Pull request by sreecha**
Currently this sets the number of threads to 1 (see `#define GRPC_MAX_POLLERS_PER_ISLAND 1`) which pretty much makes this a turnstile polling

I tired with other values (2 and 3) but did not see any noticeable improvement yet.

### CODE REVIEW

**Comment by ctiller** [comment]
Do we have data on how this performs in the synthetic benchmarks?

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                                        locks_per_iteration
---------------------------------------------------------------  ---------------------
BM_EmptyCore                                                     +100%
BM_PollEmptyPollset                                              +200%
BM_PumpStreamClientToServer<SockPair>/128M                       +102%
BM_PumpStreamClientToServer<SockPair>/16M                        +114%
BM_PumpStreamClientToServer<SockPair>/256k                       +66%
BM_PumpStreamClientToServer<SockPair>/2M                         +107%
BM_PumpStreamClientToServer<SockPair>/32k                        +21%
BM_PumpStreamClientToServer<TCP>/128M                            +16%
BM_PumpStreamClientToServer<TCP>/16M                             +28%
BM_PumpStreamClientToServer<TCP>/256k                            +47%
BM_PumpStreamClientToServer<TCP>/2M                              +51%
BM_PumpStreamClientToServer<TCP>/32k                             +11%
BM_PumpStreamClientToServer<UDS>/128M                            +103%
BM_PumpStreamClientToServer<UDS>/16M                             +30%
BM_PumpStreamClientToServer<UDS>/256k                            +57%
BM_PumpStreamClientToServer<UDS>/2M                              +75%
BM_PumpStreamClientToServer<UDS>/32k                             +13%
BM_PumpStreamServerToClient<SockPair>/128M                       +101%
BM_PumpStreamServerToClient<SockPair>/16M                        +116%
BM_PumpStreamServerToClient<SockPair>/256k                       +67%
BM_PumpStreamServerToClient<SockPair>/2M                         +107%
BM_PumpStreamServerToClient<SockPair>/32k                        +20%
BM_PumpStreamServerToClient<TCP>/128M                            +22%
BM_PumpStreamServerToClient<TCP>/256k                            +45%
BM_PumpStreamServerToClient<TCP>/32k                             +11%
BM_PumpStreamServerToClient<UDS>/128M                            +99%
BM_PumpStreamServerToClient<UDS>/16M                             +113%
BM_PumpStreamServerToClient<UDS>/256k                            +58%
BM_PumpStreamServerToClient<UDS>/2M                              +99%
BM_PumpStreamServerToClient<UDS>/32k                             +16%
BM_SingleThreadPollOneFd                                         +199%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/0       +17%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/1       +21%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/2       +23%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/1       +21%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/2       +23%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/128M/1    +29%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/128M/2    +41%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/16M/2     +7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/1    +35%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/2    +41%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/2M/1      +7%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/2M/2      +9%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/1     +20%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/2     +22%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/1      +20%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/2      +22%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/1     +20%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/2     +22%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/1      +21%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/2      +22%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/1       +21%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/2       +23%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/0/0          +17%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/0/1          +21%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/0/2          +23%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/1/1          +21%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/1/2          +23%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/128M/1       +30%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/128M/2       +43%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/16M/2        +7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/256k/1       +35%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/256k/2       +41%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/2M/1         +7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/32k/1        +20%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/32k/2        +22%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/4k/1         +20%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/4k/2         +22%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/512/1        +20%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/512/2        +22%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/64/1         +21%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/64/2         +22%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/8/1          +21%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/8/2          +23%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/0     +29%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/1     +29%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/128M  +27%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/256k  +55%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/32k   +25%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/4k    +25%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/512   +26%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/64    +27%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/8     +29%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/0        +29%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/1        +29%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/128M     +28%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/256k     +54%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/2M       +4%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/32k      +25%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/4k       +25%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/512      +26%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/64       +27%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/8        +29%
BM_UnaryPingPong<MinSockPair, NoOpMutator, NoOpMutator>/0/0      +22%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/0           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/1           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/256k        +32%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/2M          +8%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/32k         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/4k          +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/512         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/64          +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/8           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/0           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/1           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/0        +32%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/256k     +41%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/2M/0          +9%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/2M/2M         +9%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/0         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/32k       +17%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/0          +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/4k         +17%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/0         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/512       +17%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/0          +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/64         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/0           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/8           +19%
BM_UnaryPingPong<MinUDS, NoOpMutator, NoOpMutator>/0/0           +21%
BM_UnaryPingPong<SockPair, NoOpMutator, NoOpMutator>/0/0         +22%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/0              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/1              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/256k           +32%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/2M             +11%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/32k            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/4k             +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/512            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/64             +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/8              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/1/0              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/1/1              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/256k/0           +32%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/256k/256k        +41%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/2M/0             +4%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/32k/0            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/32k/32k          +17%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/4k/0             +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/4k/4k            +17%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/512/0            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/512/512          +17%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/64/0             +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/64/64            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/8/0              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/8/8              +19%
BM_UnaryPingPong<UDS, NoOpMutator, NoOpMutator>/0/0              +21%
```

**Comment by sreecha** [comment]
[**cpp_protobuf_async_unary_qps_unconstrained_insecure**
](https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_adhoc/306/)```
I0427 16:41:58.042740612   31039 report.cc:84]               QPS: 1727045.9
I0427 16:41:58.044298383   31039 report.cc:94]               QPS: 1727045.9 (53970.2/server core)
I0427 16:41:58.044318011   31039 report.cc:99]               Latencies (50/90/95/99/99.9%-ile): 3597.4/4093.8/4806.5/6351.9/11104.1 us
I0427 16:41:58.044325540   31039 report.cc:109]              Server system time: 114.95%
I0427 16:41:58.044331487   31039 report.cc:111]              Server user time:   2958.57%
I0427 16:41:58.044336805   31039 report.cc:113]              Client system time: 277.63%
I0427 16:41:58.044342293   31039 report.cc:115]              Client user time:   1274.11%
I0427 16:41:58.044348105   31039 report.cc:120]              Server CPU usage: 96.07%
```

[**cpp_protobuf_async_streaming_qps_unconstrained_insecure**
](https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_adhoc/307/)```
I0427 17:06:19.288732422   16234 report.cc:84]               QPS: 4002270.1
I0427 17:06:19.289603861   16234 report.cc:94]               QPS: 4002270.1 (125070.9/server core)
I0427 17:06:19.289616594   16234 report.cc:99]               Latencies (50/90/95/99/99.9%-ile): 1436.0/2195.9/2685.6/3530.4/4618.9 us
I0427 17:06:19.289620859   16234 report.cc:109]              Server system time: 204.34%
I0427 17:06:19.289624278   16234 report.cc:111]              Server user time:   2320.91%
I0427 17:06:19.289627531   16234 report.cc:113]              Client system time: 1184.23%
I0427 17:06:19.289630671   16234 report.cc:115]              Client user time:   1184.46%
I0427 17:06:19.289633872   16234 report.cc:120]              Server CPU usage: 78.61%
```

(about ~30% improvement..)
[**cpp_protobuf_async_client_sync_server_unary_qps_unconstrained_insecure**
](https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_adhoc/308/)```
I0427 17:10:47.801696359     988 report.cc:84]               QPS: 84241.2
I0427 17:10:47.802563843     988 report.cc:94]               QPS: 84241.2 (2632.5/server core)
I0427 17:10:47.802577016     988 report.cc:99]               Latencies (50/90/95/99/99.9%-ile): 38903.9/158642.9/268459.4/706788.2/1456110.8 us
I0427 17:10:47.802581283     988 report.cc:109]              Server system time: 2356.63%
I0427 17:10:47.802584673     988 report.cc:111]              Server user time:   349.37%
I0427 17:10:47.802587840     988 report.cc:113]              Client system time: 15.26%
I0427 17:10:47.802590939     988 report.cc:115]              Client user time:   64.35%
I0427 17:10:47.802594179     988 report.cc:120]              Server CPU usage: 83.04%
```
~60% improvement.
[**cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_insecure**
](https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_adhoc/309/)```
I0427 17:14:42.320255831   18224 report.cc:84]               QPS: 119237.2
I0427 17:14:42.321160539   18224 report.cc:94]               QPS: 119237.2 (3726.2/server core)
I0427 17:14:42.321175598   18224 report.cc:99]               Latencies (50/90/95/99/99.9%-ile): 17690.2/109712.7/195743.1/461392.7/1428660.0 us
I0427 17:14:42.321180192   18224 report.cc:109]              Server system time: 2803.44%
I0427 17:14:42.321183979   18224 report.cc:111]              Server user time:   203.00%
I0427 17:14:42.321187325   18224 report.cc:113]              Client system time: 21.54%
I0427 17:14:42.321190522   18224 report.cc:115]              Client user time:   46.61%
I0427 17:14:42.321193809   18224 report.cc:120]              Server CPU usage: 93.25%
```

**Comment by grpc-testing** [comment]
```
Performance differences noted:
Benchmark                                                        locks_per_iteration
---------------------------------------------------------------  ---------------------
BM_EmptyCore                                                     +100%
BM_PollEmptyPollset                                              +200%
BM_PumpStreamClientToServer<SockPair>/128M                       +102%
BM_PumpStreamClientToServer<SockPair>/16M                        +113%
BM_PumpStreamClientToServer<SockPair>/256k                       +66%
BM_PumpStreamClientToServer<SockPair>/2M                         +108%
BM_PumpStreamClientToServer<SockPair>/32k                        +19%
BM_PumpStreamClientToServer<TCP>/16M                             +8%
BM_PumpStreamClientToServer<TCP>/256k                            +49%
BM_PumpStreamClientToServer<TCP>/2M                              +50%
BM_PumpStreamClientToServer<TCP>/32k                             +11%
BM_PumpStreamClientToServer<UDS>/128M                            +101%
BM_PumpStreamClientToServer<UDS>/16M                             +43%
BM_PumpStreamClientToServer<UDS>/256k                            +57%
BM_PumpStreamClientToServer<UDS>/2M                              +80%
BM_PumpStreamClientToServer<UDS>/32k                             +13%
BM_PumpStreamServerToClient<SockPair>/128M                       +102%
BM_PumpStreamServerToClient<SockPair>/16M                        +112%
BM_PumpStreamServerToClient<SockPair>/256k                       +66%
BM_PumpStreamServerToClient<SockPair>/2M                         +106%
BM_PumpStreamServerToClient<SockPair>/32k                        +18%
BM_PumpStreamServerToClient<TCP>/128M                            +16%
BM_PumpStreamServerToClient<TCP>/256k                            +47%
BM_PumpStreamServerToClient<TCP>/2M                              +15%
BM_PumpStreamServerToClient<TCP>/32k                             +11%
BM_PumpStreamServerToClient<UDS>/128M                            +101%
BM_PumpStreamServerToClient<UDS>/16M                             +109%
BM_PumpStreamServerToClient<UDS>/256k                            +58%
BM_PumpStreamServerToClient<UDS>/2M                              +101%
BM_PumpStreamServerToClient<UDS>/32k                             +17%
BM_SingleThreadPollOneFd                                         +199%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/0       +17%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/1       +21%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/2       +23%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/1       +21%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/2       +23%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/128M/1    +28%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/128M/2    +42%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/1    +35%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/2    +42%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/2M/1      +8%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/1     +20%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/2     +22%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/1      +20%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/2      +22%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/1     +20%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/2     +22%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/1      +21%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/2      +22%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/1       +21%
BM_StreamingPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/2       +23%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/0/0          +17%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/0/1          +21%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/0/2          +23%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/1/1          +21%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/1/2          +23%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/128M/1       +29%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/128M/2       +43%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/16M/2        +7%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/256k/1       +35%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/256k/2       +42%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/2M/1         +18%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/2M/2         +20%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/32k/1        +20%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/32k/2        +22%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/4k/1         +20%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/4k/2         +22%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/512/1        +20%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/512/2        +22%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/64/1         +21%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/64/2         +22%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/8/1          +21%
BM_StreamingPingPong<TCP, NoOpMutator, NoOpMutator>/8/2          +23%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/0     +29%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/1     +29%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/128M  +31%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/256k  +55%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/32k   +25%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/4k    +25%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/512   +26%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/64    +27%
BM_StreamingPingPongMsgs<MinTCP, NoOpMutator, NoOpMutator>/8     +29%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/0        +29%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/1        +29%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/128M     +27%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/256k     +55%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/32k      +25%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/4k       +25%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/512      +26%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/64       +27%
BM_StreamingPingPongMsgs<TCP, NoOpMutator, NoOpMutator>/8        +29%
BM_UnaryPingPong<MinSockPair, NoOpMutator, NoOpMutator>/0/0      +22%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/0           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/1           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/256k        +32%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/2M          +4%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/32k         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/4k          +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/512         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/64          +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/0/8           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/0           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/1/1           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/0        +32%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/256k/256k     +41%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/2M/0          +15%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/0         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/32k/32k       +17%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/0          +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/4k/4k         +17%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/0         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/512/512       +17%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/0          +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/64/64         +18%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/0           +19%
BM_UnaryPingPong<MinTCP, NoOpMutator, NoOpMutator>/8/8           +19%
BM_UnaryPingPong<MinUDS, NoOpMutator, NoOpMutator>/0/0           +21%
BM_UnaryPingPong<SockPair, NoOpMutator, NoOpMutator>/0/0         +22%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/0              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/1              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/256k           +32%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/2M             +5%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/32k            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/4k             +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/512            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/64             +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/0/8              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/1/0              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/1/1              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/256k/0           +32%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/256k/256k        +41%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/2M/0             +7%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/2M/2M            +6%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/32k/0            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/32k/32k          +17%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/4k/0             +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/4k/4k            +17%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/512/0            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/512/512          +17%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/64/0             +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/64/64            +18%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/8/0              +19%
BM_UnaryPingPong<TCP, NoOpMutator, NoOpMutator>/8/8              +19%
BM_UnaryPingPong<UDS, NoOpMutator, NoOpMutator>/0/0              +21%
```

**Comment by ctiller** [comment]
Have you tried preferring to kick a non polling waiter? (Seems like it's
less work to do a timed wait and if we have a choice...)

May only make sense for async with multiple threads per cq however.

**Comment by grpc-testing** [comment]
```
No significant performance differences
```

**Pull request merged**
