### PR TITLE
Fixed unprotected access to call field

### PR DESCRIPTION
**Pull request by dgquintas**
These two functions are only relevant for tests, and are used by the Inspector to sniff call values for those fields. Kudos to @sreecha for figuring out something fishy was up with the interop tests and compression :)

### CODE REVIEW

**Comment by ctiller** [comment]
If these are only for tests can we put test_only in the function names?
Otherwise accessors that take locks scare me a little - they typically hide
threading issues for a long time.

**Comment by dgquintas** [comment]
Done. PTAL.

**Comment by sreecha** [comment]
LGTM!

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
