### PR TITLE
Rename TestService to EchoTestService to prevent name-conflict with 'TestService' in test.proto

### PR DESCRIPTION
**Pull request by sreecha**

### CODE REVIEW

**Comment by yang-g** [comment]
Is this for cosmetic reason or there is a real conflict?

**Comment by yang-g** [comment]
LGTM, Maybe run the copyright fix script to fix sanity.

**Comment by sreecha** [comment]
Just ran the copyright script and found that the following files need updating. It is better to do it in a separate pull request to avoid confusion

```
include/grpc++/generic/async_generic_service.h modified 2016 but copyright only extends to 2015
include/grpc++/support/byte_buffer.h modified 2016 but copyright only extends to 2015
include/grpc++/support/slice.h modified 2016 but copyright only extends to 2015
src/cpp/util/byte_buffer.cc modified 2016 but copyright only extends to 2015
test/cpp/qps/client.h modified 2016 but copyright only extends to 2015
test/cpp/qps/client_async.cc modified 2016 but copyright only extends to 2015
test/cpp/qps/client_sync.cc modified 2016 but copyright only extends to 2015
test/cpp/qps/generic_async_streaming_ping_pong_test.cc modified 2016 but copyright only extends to 2015
test/cpp/qps/qps_driver.cc modified 2016 but copyright only extends to 2015
test/cpp/qps/qps_worker.cc modified 2016 but copyright only extends to 2015
test/cpp/qps/server.h modified 2016 but copyright only extends to 2015
test/cpp/qps/server_async.cc modified 2016 but copyright only extends to 2015
```

**Comment by sreecha** [comment]
All the failed Basic tests had the same failure (except tests.tools/run_tests/run_sanity.sh which gave the copyright warnings that I pasted in my previous comment)

```
FATAL: ThreadSanitizer can not mmap the shadow memory (something is mapped at 0x561e08cfc000 < 0x7cf000000000)
FATAL: Make sure to compile with -fPIE and to link with -pie.
```
This is unrelated to my change and are happenings in other pull requests too (see: https://grpc-testing.appspot.com/job/gRPC_pull_requests/5181/)

I was wondering if we can merge this.

**Pull request merged**
