### PR TITLE
Cut down microbenchmark time

### LINKED ISSUE #13184: grpc_microbenchmark_diff jobs take ~100mins for each run.
Test suites taking that long is incompatible with seeing PR tests results within a reasonable timeframe (#11690).

What can we do to reduce the runtime for microbenchmarks (e.g. so they take <1hr)?

### PR DESCRIPTION
**Pull request by ncteisen**
This should cut runtime down to <60min. If there is a problem with how much noise this introduces, we can roll it back.

Fixes #13184

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
I'll keep a close eye on it today

**Pull request merged**
