### PR TITLE
Qps scenarios

### PR DESCRIPTION
**Pull request by vjpai**
Depends on #4918 . The only relevant file in this commit is qps-sweep.sh , which now spells out useful scenarios for testing

### CODE REVIEW

**Comment by jtattermusch** [comment]
LGTM, please rebase before merging.

**Comment by jtattermusch** [comment]
At some point it would be good to also integrate at least some scenarios with tools/jenkins/run_performance.sh so that we are running more tests on our GCE worker as well.

**Comment by vjpai** [comment]
Rather than rebasing, I'll just make a clean PR with just this file in final form. Coming soon.

**Comment by vjpai** [comment]
This is cleaned up in #4949

**Pull request closed without merging**
