### PR TITLE
Explicitly use built protoc for CMake build.

### PR DESCRIPTION
**Pull request by gkelly**
Setting _gRPC_PROTOBUF_PROTOC to the bare string "protoc" can result in
the host protoc being invoked.  If the protoc target exists, explicitly
use the path to the built artifact.

### CODE REVIEW

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by grpc-testing** [comment]
Thanks for your pull request. The automated tests will run as soon as one of the admins verifies this change is ok for us to run on our infrastructure.

**Comment by ncteisen** [comment]
That file is auto generated. You are going to want to edit templates/CMakeLists.txt.template and then run tools/buildgen/generate_projects.sh

Other than that it looks like a good change. But cc @nicolasnoble or @jtattermusch who have all the build experience and knowledge.

**Comment by gkelly** [comment]
Whoops, I missed that it was generated.  Will update, thanks for looking!

**Comment by gkelly** [comment]
Updated `templates/CMakeLists.txt.template` and ran `./tools/buildgen/generate_projects.sh`. @nnoble, how's this look to you?

**Comment by ncteisen** [comment]
jenkins: test this please

**Comment by jtattermusch** [comment]
Failure: 
```
CMakeFiles/Makefile2:1858: recipe for target 'CMakeFiles/buildtests_cxx.dir/rule' failed
make[1]: *** [CMakeFiles/buildtests_cxx.dir/rule] Error 2
Makefile:606: recipe for target 'buildtests_cxx' failed
make: *** [buildtests_cxx] Error 2

2017-06-07 16:36:08,591 FAILED: make [ret=2, pid=1471]
```

**Comment by jtattermusch** [comment]
This breaks tests as some occurences of the _gRPC_PROTOBUF_PROTOC in the custom command expect a target name, not a file name. Fixed version is in #11422.

**Pull request closed without merging**
