### PR TITLE
Upgrade to YAPF 0.24

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
Large, but no big surprises in the content.

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
Objective-C binary sizes
*****************STATIC******************
  New size                      Old size
 1,964,580      Total (=)      1,964,580

 No significant differences in binary sizes

***************FRAMEWORKS****************
  New size                      Old size
10,886,954      Total (>)     10,886,949

 No significant differences in binary sizes


```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by nathanielmanistaatgoogle** [comment]
@gwelymernans and @caioariede: how gRPC's "sanity test" verifies that code is YAPFed is a bit of a long story, but two things to which I want to call your attention right now are

1. is there anything obviously YAPFy that could be going wrong on lines 565 and 566 of [this test execution](https://source.cloud.google.com/results/invocations/3c5556ea-fd72-4eb3-8436-e41980637d1b/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_sanity/log) to produce
```
+ yapf_virtual_environment/bin/python -m yapf --in-place --recursive --style=setup.cfg --parallel --verbose '--exclude=/tmp/tmp.JN1RuDwLko/*protoc_lib_deps.py' '--exclude=/tmp/tmp.JN1RuDwLko/*_pb2*.py' /tmp/tmp.JN1RuDwLko
Reformatting /tmp/tmp.JN1RuDwLko/interceptors/headers/helloworld_pb2_grpc.py
```
?

2. gRPC is currently stuck on YAPF 0.20. A draft upgrade to 0.20.1 passes our sanity test and a draft upgrade to 0.20.2 demonstrates the above problem when running our sanity test. That chronology seems to strongly implicate [this change](https://github.com/google/yapf/pull/510) as either having a problem or as changing something unsupported that gRPC happened to be accidentally happily using to no longer behaving as gRPC would need it to behave. Any ideas? Anything obvious leaping out? Exclusion patterns like `/tmp/tmp.JN1RuDwLko/*protoc_lib_deps.py` are still supported for YAPF's `--exclude` argument, right?

@mehrdada and @ncteisen: understanding this enough to fix it is way beyond both my nonexistent Bash expertise and beyond my ability to fake having any Bash expertise. Before I reach for friends outside of gRPC who I think might see what's going on, is there anyone on the team who wants a Bash (or at least Bashistic) problem? @nicolasnoble? @jtattermusch? That the problem occurs when invoking `./tools/run_tests/run_tests.py --language=sanity --regex='yapf'` but not when invoking `./tools/distrib/yapf_code.sh` is puzzling and frustrating.

**Comment by nathanielmanistaatgoogle** [comment]
@mehrdada: I also think it looks good and will dig further into the sanity test failure in the next day or so...

**Comment by caioariede** [comment]
Can you try with the following fix against YAPF?

```diff
diff --git a/yapf/yapflib/file_resources.py b/yapf/yapflib/file_resources.py
index 6e7202d..64da2ee 100644
--- a/yapf/yapflib/file_resources.py
+++ b/yapf/yapflib/file_resources.py
diff --git yapf/yapflib/file_resources.py yapf/yapflib/file_resources.py
index 6e7202d..64da2ee 100644
--- yapf/yapflib/file_resources.py
+++ yapf/yapflib/file_resources.py
@@ -148,7 +148,6 @@ def _FindPythonFiles(filenames, recursive, exclude):
 
 def IsIgnored(path, exclude):
   """Return True if filename matches any patterns in exclude."""
-  path = path.lstrip('/')
   while path.startswith('./'):
     path = path[2:]
   return any(fnmatch.fnmatch(path, e.rstrip('/')) for e in exclude)
```

I think this may solve your issue, if so we can propose this fix to YAPF.

**Comment by nathanielmanistaatgoogle** [comment]
@caioariede: yes, that seems to have the desired effect! 🙂 While I was hacking my local environment I added some logging; here are some of the values that were passed for the `exclude` parameter of `_FindPythonFiles` in the successful (not-the-sanity-test) `yapf` execution:
```
WARNING:root:exclude is "['examples/python/*protoc_lib_deps.py', 'examples/python/*_pb2*.py']"!
WARNING:root:exclude is "['src/python/*protoc_lib_deps.py', 'src/python/*_pb2*.py']"!
WARNING:root:exclude is "['tools/*protoc_lib_deps.py', 'tools/*_pb2*.py']"!
```
and here are some of the values that were passed for `exclude` parameter of `_FindPythonFiles` in the unsuccessful (sanity-test) `yapf` execution:
```
WARNING:root:exclude is "['/tmp/tmp.gBJsR8rH4C/*protoc_lib_deps.py', '/tmp/tmp.gBJsR8rH4C/*_pb2*.py']"!
WARNING:root:exclude is "['/tmp/tmp.3X7pSgVIXI/*protoc_lib_deps.py', '/tmp/tmp.3X7pSgVIXI/*_pb2*.py']"!
```
. Thanks for getting that sorted out!

**Comment by caioariede** [comment]
You're welcome. One thing to keep in mind when submitting a fix to YAPF is that that change will likely break other stuff. I think the conflicts are between things like this:

```bash
# absolute path
yapf --exclude=... /tmp/test
```

and

```bash
# relative path
yapf --exclude=... test/
```

**Comment by nathanielmanistaatgoogle** [comment]
@caioariede: I trust you and @gwelymernans to work it out (but please include me on the code review!). 🙂 We'll be happy if YAPF is changed to work with the way we're currently using it, or if it is changed some other way and you help us fix our use. 🙂

**Comment by vjpai** [comment]
Closing since this hasn't been pinged in a long time.

**Pull request closed without merging**
