### PR TITLE
Remove gflags.

### PR DESCRIPTION
**Pull request by Capstan**
With the move to abseil's flags, this removed the now-unnecessary submodule and installation commands.

@veblush

### CODE REVIEW

**Review by veblush — APPROVED** [review]
Thank you for the PR!

**Review by jtattermusch — COMMENTED** [review]
Is there an installation story for absl / absl flags?
I think removing gflags probably makes sense, but with gflags, the advantage is that it's easy to install the gflags dependency on many linux distros (I'm not sure how easy is to install absl).
While statically linking absl flags into our libraries binaries is fine in some cases (e.g. building tests and for internal builds, bazel builds), it's not ok in other cases (installing grpc / grpc++ etc. for use in third party projects) - so I just wanted to make sure we're not degrading our installation story by making this change.

Also, can we get a measurement how much is the binary reduction size? (I think evaluating the binary size impact should be part of all changes that involve adding / removing dependencies).

**Comment by veblush** [comment]
@jtattermusch This doesn't introduce any additional dependency to be installed because Abseil was included previously. So this is more likely just removing gflag which isn't used anymore. Speaking of size, we don't need to worry although it doesn't change much difference because it's only used by tests. gRPC Core and C++ Library shouldn't be affected by this.

**Comment by veblush** [comment]
To make `EasyCLA` get back to normal, I'm going to close and reopen this.

**Comment by Capstan** [comment]
I've looked at the [Artifact Build Linux (internal CI) link](https://source.cloud.google.com/results/invocations/b4aebe9b-a311-40ed-981d-3dea4c4c28ea), but I honestly don't understand the failure there.

**Comment by veblush** [comment]
@Capstan I don't think the failure is relevant to this PR. But I just rerun the test just in case before getting this merged.

**Comment by jtattermusch** [comment]
> @jtattermusch This doesn't introduce any additional dependency to be installed because Abseil was included previously. So this is more likely just removing gflag which isn't used anymore. Speaking of size, we don't need to worry although it doesn't change much difference because it's only used by tests. gRPC Core and C++ Library shouldn't be affected by this.

Sure I understand that this specific PR isn't the one that's adding absl dependency (so my comment might be slightly misplaced), but my question about the installation story for absl is still valid I believe.

**Comment by veblush** [comment]
@jtattermusch I see. Basically all flags are only for the test builds and gflag isn't used anymore, we don't need to worry about this. Let's get this merged and discuss Abseil installation issue on a different channel.

@Capstan Can you rebase it and rerun the `generate_project` script to pass `Sanity Checks`?

**Comment by Capstan** [comment]
@veblush Rebased, regenerated and repushed.

**Pull request merged**
