### PR TITLE
C++-ify the ChannelzRegistry, Adds Generic Object Support

### PR DESCRIPTION
**Pull request by ncteisen**
Built upon #15339.

Needed for implementation of channelz. See #15340.

---
This change is [Reviewable](https://reviewable.io/reviews/grpc/grpc/15341)

### CODE REVIEW

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++
  +0.0%    +267 [None]                                                     +2.92Ki  +0.0%
      +0.0%    +299 [Unmapped]                                                 +2.92Ki  +0.0%
      [NEW]     +40 grpc_core::(anonymous namespace)::avl_vtable                   +40  [NEW]
      +2.0%     +24 [None]                                                           0  [ = ]
      [NEW]      +8 grpc_core::(anonymous namespace)::g_channelz_registry            0  [ = ]
  [NEW]    +329 src/core/lib/channel/channelz_registry.cc                     +329  [NEW]
      [NEW]    +104 [Unmapped]                                                    +104  [NEW]
      [NEW]     +57 grpc_core::ChannelzRegistry::Unregister                        +57  [NEW]
      [NEW]     +39 grpc_core::ChannelzRegistry::ChannelzRegistry                  +39  [NEW]
      [NEW]     +36 grpc_core::ChannelzRegistry::Init                              +36  [NEW]
      [NEW]     +28 grpc_core::ChannelzRegistry::~ChannelzRegistry                 +28  [NEW]
      [NEW]     +25 grpc_core::ChannelzRegistry::Shutdown                          +25  [NEW]
      [NEW]     +20 grpc_core::(anonymous namespace)::compare_intptr               +20  [NEW]
      [NEW]      +8 grpc_core::ChannelzRegistry::Default                            +8  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_intptr                   +4  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_channelz_obj             +4  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_intptr                +2  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_channelz_obj          +2  [NEW]
  +2.5%     +64 src/core/lib/channel/channel_trace.cc                          +64  +2.5%
       +31%     +54 grpc_core::ChannelTrace::ChannelTrace                          +54   +31%
       +16%     +16 grpc_core::ChannelTrace::~ChannelTrace                         +16   +16%

 -------------- SHRINKING                                                  --------------
  [DEL]    -444 src/core/lib/channel/channel_trace_registry.cc                -444  [DEL]
      [DEL]     -99 grpc_channel_trace_registry_register_channel_trace             -99  [DEL]
      [DEL]     -98 [Unmapped]                                                     -98  [DEL]
      [DEL]     -67 grpc_channel_trace_registry_unregister_channel_trace           -67  [DEL]
      [DEL]     -60 grpc_channel_trace_registry_get_channel_trace                  -60  [DEL]
      [DEL]     -47 grpc_channel_trace_registry_init                               -47  [DEL]
      [DEL]     -41 grpc_channel_trace_registry_shutdown                           -41  [DEL]
      [DEL]     -20 compare_intptr                                                 -20  [DEL]
      [DEL]      -4 copy_intptr                                                     -4  [DEL]
      [DEL]      -4 copy_channel_trace                                              -4  [DEL]
      [DEL]      -2 destroy_intptr                                                  -2  [DEL]
      [DEL]      -2 destroy_channel_trace                                           -2  [DEL]

  +0.0%    +216 TOTAL                                                      +2.87Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++
  +0.0%    +267 [None]                                                     +2.92Ki  +0.0%
      +0.0%    +299 [Unmapped]                                                 +2.92Ki  +0.0%
      [NEW]     +40 grpc_core::(anonymous namespace)::avl_vtable                   +40  [NEW]
      +2.0%     +24 [None]                                                           0  [ = ]
      [NEW]      +8 grpc_core::(anonymous namespace)::g_channelz_registry            0  [ = ]
  [NEW]    +329 src/core/lib/channel/channelz_registry.cc                     +329  [NEW]
      [NEW]    +104 [Unmapped]                                                    +104  [NEW]
      [NEW]     +57 grpc_core::ChannelzRegistry::Unregister                        +57  [NEW]
      [NEW]     +39 grpc_core::ChannelzRegistry::ChannelzRegistry                  +39  [NEW]
      [NEW]     +36 grpc_core::ChannelzRegistry::Init                              +36  [NEW]
      [NEW]     +28 grpc_core::ChannelzRegistry::~ChannelzRegistry                 +28  [NEW]
      [NEW]     +25 grpc_core::ChannelzRegistry::Shutdown                          +25  [NEW]
      [NEW]     +20 grpc_core::(anonymous namespace)::compare_intptr               +20  [NEW]
      [NEW]      +8 grpc_core::ChannelzRegistry::Default                            +8  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_intptr                   +4  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_channelz_obj             +4  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_intptr                +2  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_channelz_obj          +2  [NEW]
  +2.5%     +64 src/core/lib/channel/channel_trace.cc                          +64  +2.5%
       +31%     +54 grpc_core::ChannelTrace::ChannelTrace                          +54   +31%
       +16%     +16 grpc_core::ChannelTrace::~ChannelTrace                         +16   +16%

 -------------- SHRINKING                                                  --------------
  [DEL]    -444 src/core/lib/channel/channel_trace_registry.cc                -444  [DEL]
      [DEL]     -99 grpc_channel_trace_registry_register_channel_trace             -99  [DEL]
      [DEL]     -98 [Unmapped]                                                     -98  [DEL]
      [DEL]     -67 grpc_channel_trace_registry_unregister_channel_trace           -67  [DEL]
      [DEL]     -60 grpc_channel_trace_registry_get_channel_trace                  -60  [DEL]
      [DEL]     -47 grpc_channel_trace_registry_init                               -47  [DEL]
      [DEL]     -41 grpc_channel_trace_registry_shutdown                           -41  [DEL]
      [DEL]     -20 compare_intptr                                                 -20  [DEL]
      [DEL]      -4 copy_intptr                                                     -4  [DEL]
      [DEL]      -4 copy_channel_trace                                              -4  [DEL]
      [DEL]      -2 destroy_intptr                                                  -2  [DEL]
      [DEL]      -2 destroy_channel_trace                                           -2  [DEL]

  +0.0%    +216 TOTAL                                                      +2.87Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE              FILE SIZE
 ++++++++++++++ GROWIN ++++++++++++++
  [ = ]       0 [None]      +8  +0.0%

  [ = ]       0 TOTAL       +8  +0.0%



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Windows failure #15352

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++
  +0.0%    +203 [None]                                                     +2.92Ki  +0.0%
      +0.0%    +299 [Unmapped]                                                 +2.92Ki  +0.0%
      [NEW]     +40 grpc_core::(anonymous namespace)::avl_vtable                   +40  [NEW]
      [NEW]      +8 grpc_core::(anonymous namespace)::g_channelz_registry            0  [ = ]
  [NEW]    +329 src/core/lib/channel/channelz_registry.cc                     +329  [NEW]
      [NEW]    +104 [Unmapped]                                                    +104  [NEW]
      [NEW]     +57 grpc_core::ChannelzRegistry::Unregister                        +57  [NEW]
      [NEW]     +39 grpc_core::ChannelzRegistry::ChannelzRegistry                  +39  [NEW]
      [NEW]     +36 grpc_core::ChannelzRegistry::Init                              +36  [NEW]
      [NEW]     +28 grpc_core::ChannelzRegistry::~ChannelzRegistry                 +28  [NEW]
      [NEW]     +25 grpc_core::ChannelzRegistry::Shutdown                          +25  [NEW]
      [NEW]     +20 grpc_core::(anonymous namespace)::compare_intptr               +20  [NEW]
      [NEW]      +8 grpc_core::ChannelzRegistry::Default                            +8  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_intptr                   +4  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_channelz_obj             +4  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_intptr                +2  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_channelz_obj          +2  [NEW]
  +2.5%     +64 src/core/lib/channel/channel_trace.cc                          +64  +2.5%
       +31%     +54 grpc_core::ChannelTrace::ChannelTrace                          +54   +31%
       +16%     +16 grpc_core::ChannelTrace::~ChannelTrace                         +16   +16%

 -------------- SHRINKING                                                  --------------
  [DEL]    -444 src/core/lib/channel/channel_trace_registry.cc                -444  [DEL]
      [DEL]     -99 grpc_channel_trace_registry_register_channel_trace             -99  [DEL]
      [DEL]     -98 [Unmapped]                                                     -98  [DEL]
      [DEL]     -67 grpc_channel_trace_registry_unregister_channel_trace           -67  [DEL]
      [DEL]     -60 grpc_channel_trace_registry_get_channel_trace                  -60  [DEL]
      [DEL]     -47 grpc_channel_trace_registry_init                               -47  [DEL]
      [DEL]     -41 grpc_channel_trace_registry_shutdown                           -41  [DEL]
      [DEL]     -20 compare_intptr                                                 -20  [DEL]
      [DEL]      -4 copy_intptr                                                     -4  [DEL]
      [DEL]      -4 copy_channel_trace                                              -4  [DEL]
      [DEL]      -2 destroy_intptr                                                  -2  [DEL]
      [DEL]      -2 destroy_channel_trace                                           -2  [DEL]

  +0.0%    +152 TOTAL                                                      +2.88Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by markdroth** [comment]
Just a few minor comments remaining.

---

Reviewed 18 of 18 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/core/lib/channel/channelz_registry.h, line 36 at r2](https://reviewable.io/reviews/grpc/grpc/15341#-LCinzLP6Yy2MyguLI2D:-LCjTxDY5QgBwa__2HDC:b-13d20s) ([raw file](https://github.com/grpc/grpc/blob/ac94dcb61da106697a83a262ee057250c348d1f0/src/core/lib/channel/channelz_registry.h#L36)):*
<details><summary><i>Previously, ncteisen (Noah Eisen) wrote…</i></summary><blockquote>

It looks like the Resolver is doing the same thing that I am doing here? As in having an explicit init and shutdown method that set the file static singleton var

I tried a pattern more like:

static Singleton &Singleton::Default() {
  static Singleton s;
  return &s;
}

But ran into a lot of errors 
</blockquote></details>

Ah, okay; I misunderstood what this comment was referring to.

Actually, the pattern you tried violates the style guide:

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

So this probably doesn't require a comment.

---

*[src/core/lib/channel/channelz_registry.h, line 46 at r3](https://reviewable.io/reviews/grpc/grpc/15341#-LCjUSTpBJiainoEWChA:-LCjUSTq18KJKsKZnAPK:brnu87n) ([raw file](https://github.com/grpc/grpc/blob/d4419baa05adc1cb77afdb0a8d61683fdc1a7221/src/core/lib/channel/channelz_registry.h#L46)):*
> ```objc
> 
>   // Returned the singleton instance of ChannelzRegistry;
>   static ChannelzRegistry* Default();
> ```

Instead of requiring all callers to call this to get the object and then invoke a method on that object, I suggest just making the public methods static and having them internally get the default object.  This is what we do in the resolver and LB policy registry code.

---

*[test/core/channel/channelz_registry_test.cc, line 81 at r3](https://reviewable.io/reviews/grpc/grpc/15341#-LCjTjpr8JYDMNNieJST:-LCjTjpr8JYDMNNieJSU:b-becmxe) ([raw file](https://github.com/grpc/grpc/blob/d4419baa05adc1cb77afdb0a8d61683fdc1a7221/test/core/channel/channelz_registry_test.cc#L81)):*
> ```cpp
>   std::string* retrieved_str =
>       ChannelzRegistry::Default()->Get<std::string>(str_uuid);
>   EXPECT_EQ(int_to_register, *retrieved_int);
> ```

This check is not necessary; the one on the following line is a superset.

---

*[test/core/channel/channelz_registry_test.cc, line 83 at r3](https://reviewable.io/reviews/grpc/grpc/15341#-LCjTnQ03asIDkIiR_ic:-LCjTnQ03asIDkIiR_id:brhumzt) ([raw file](https://github.com/grpc/grpc/blob/d4419baa05adc1cb77afdb0a8d61683fdc1a7221/test/core/channel/channelz_registry_test.cc#L83)):*
> ```cpp
>   EXPECT_EQ(int_to_register, *retrieved_int);
>   EXPECT_EQ(&int_to_register, retrieved_int);
>   EXPECT_STREQ(str_to_register.c_str(), (*retrieved_str).c_str());
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15341#-:-LCjUqWjCQnmOrgPwyw1:b7u3aqr)*

**Comment by ncteisen** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/core/lib/channel/channelz_registry.h, line 36 at r2](https://reviewable.io/reviews/grpc/grpc/15341#-LCinzLP6Yy2MyguLI2D:-LCk1Z6A5w-SQJGhB-cC:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/ac94dcb61da106697a83a262ee057250c348d1f0/src/core/lib/channel/channelz_registry.h#L36)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Ah, okay; I misunderstood what this comment was referring to.

Actually, the pattern you tried violates the style guide:

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

So this probably doesn't require a comment.
</blockquote></details>

Done.

---

*[src/core/lib/channel/channelz_registry.h, line 46 at r3](https://reviewable.io/reviews/grpc/grpc/15341#-LCjUSTpBJiainoEWChA:-LCk5H1C1du7VRtboOmY:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d4419baa05adc1cb77afdb0a8d61683fdc1a7221/src/core/lib/channel/channelz_registry.h#L46)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Instead of requiring all callers to call this to get the object and then invoke a method on that object, I suggest just making the public methods static and having them internally get the default object.  This is what we do in the resolver and LB policy registry code.
</blockquote></details>

Done.

---

*[test/core/channel/channelz_registry_test.cc, line 81 at r3](https://reviewable.io/reviews/grpc/grpc/15341#-LCjTjpr8JYDMNNieJST:-LCk3Qxl4Vu4L-sWrEqq:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d4419baa05adc1cb77afdb0a8d61683fdc1a7221/test/core/channel/channelz_registry_test.cc#L81)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

This check is not necessary; the one on the following line is a superset.
</blockquote></details>

Done.

---

*[test/core/channel/channelz_registry_test.cc, line 83 at r3](https://reviewable.io/reviews/grpc/grpc/15341#-LCjTnQ03asIDkIiR_ic:-LCk3RDH1_kE2d-h4CCi:b-896fix) ([raw file](https://github.com/grpc/grpc/blob/d4419baa05adc1cb77afdb0a8d61683fdc1a7221/test/core/channel/channelz_registry_test.cc#L83)):*
<details><summary><i>Previously, markdroth (Mark D. Roth) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15341)*

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++
  +0.0%    +235 [None]                                                     +3.49Ki  +0.0%
      +0.1%    +331 [Unmapped]                                                 +3.49Ki  +0.0%
      [NEW]     +40 grpc_core::(anonymous namespace)::avl_vtable                   +40  [NEW]
      [NEW]      +8 grpc_core::(anonymous namespace)::g_channelz_registry            0  [ = ]
  [NEW]    +329 src/core/lib/channel/channelz_registry.cc                     +329  [NEW]
      [NEW]    +104 [Unmapped]                                                    +104  [NEW]
      [NEW]     +57 grpc_core::ChannelzRegistry::InternalUnregister                +57  [NEW]
      [NEW]     +39 grpc_core::ChannelzRegistry::ChannelzRegistry                  +39  [NEW]
      [NEW]     +36 grpc_core::ChannelzRegistry::Init                              +36  [NEW]
      [NEW]     +28 grpc_core::ChannelzRegistry::~ChannelzRegistry                 +28  [NEW]
      [NEW]     +25 grpc_core::ChannelzRegistry::Shutdown                          +25  [NEW]
      [NEW]     +20 grpc_core::(anonymous namespace)::compare_intptr               +20  [NEW]
      [NEW]      +8 grpc_core::ChannelzRegistry::Default                            +8  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_intptr                   +4  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_channelz_obj             +4  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_intptr                +2  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_channelz_obj          +2  [NEW]
  +2.5%     +64 src/core/lib/channel/channel_trace.cc                          +64  +2.5%
       +31%     +54 grpc_core::ChannelTrace::ChannelTrace                          +54   +31%
       +16%     +16 grpc_core::ChannelTrace::~ChannelTrace                         +16   +16%

 -------------- SHRINKING                                                  --------------
  [DEL]    -444 src/core/lib/channel/channel_trace_registry.cc                -444  [DEL]
      [DEL]     -99 grpc_channel_trace_registry_register_channel_trace             -99  [DEL]
      [DEL]     -98 [Unmapped]                                                     -98  [DEL]
      [DEL]     -67 grpc_channel_trace_registry_unregister_channel_trace           -67  [DEL]
      [DEL]     -60 grpc_channel_trace_registry_get_channel_trace                  -60  [DEL]
      [DEL]     -47 grpc_channel_trace_registry_init                               -47  [DEL]
      [DEL]     -41 grpc_channel_trace_registry_shutdown                           -41  [DEL]
      [DEL]     -20 compare_intptr                                                 -20  [DEL]
      [DEL]      -4 copy_intptr                                                     -4  [DEL]
      [DEL]      -4 copy_channel_trace                                              -4  [DEL]
      [DEL]      -2 destroy_intptr                                                  -2  [DEL]
      [DEL]      -2 destroy_channel_trace                                           -2  [DEL]

  +0.0%    +184 TOTAL                                                      +3.44Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by markdroth** [comment]
Just one style nit remaining.  Otherwise, this looks great!

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/core/lib/channel/channelz_registry.h, line 61 at r4](https://reviewable.io/reviews/grpc/grpc/15341#-LCk6Vhc2sTI2sfRkRJn:-LCk6Vhc2sTI2sfRkRJo:b-1t9vdv) ([raw file](https://github.com/grpc/grpc/blob/3baa90fbea45502070d430ea2fa11c37049597f6/src/core/lib/channel/channelz_registry.h#L61)):*
> ```objc
>   GPRC_ALLOW_CLASS_TO_USE_NON_PUBLIC_DELETE
> 
>   gpr_mu mu_;
> ```

Please follow the declaration order defined by the style guide:

https://google.github.io/styleguide/cppguide.html#Declaration_Order

---


*Comments from [Reviewable](https://reviewable.io/reviews/grpc/grpc/15341#-:-LCk6ov64qFQxrLwpxgJ:b641f5d)*

**Comment by grpc-testing** [comment]
```
[trickle] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
****************************************************************

libgrpc.so

     VM SIZE                                                                  FILE SIZE
 ++++++++++++++ GROWING                                                    ++++++++++++++
  +0.0%    +235 [None]                                                     +3.50Ki  +0.0%
      +0.1%    +331 [Unmapped]                                                 +3.50Ki  +0.0%
      [NEW]     +40 grpc_core::(anonymous namespace)::avl_vtable                   +40  [NEW]
      [NEW]      +8 grpc_core::(anonymous namespace)::g_channelz_registry            0  [ = ]
  [NEW]    +329 src/core/lib/channel/channelz_registry.cc                     +329  [NEW]
      [NEW]    +104 [Unmapped]                                                    +104  [NEW]
      [NEW]     +57 grpc_core::ChannelzRegistry::InternalUnregister                +57  [NEW]
      [NEW]     +39 grpc_core::ChannelzRegistry::ChannelzRegistry                  +39  [NEW]
      [NEW]     +36 grpc_core::ChannelzRegistry::Init                              +36  [NEW]
      [NEW]     +28 grpc_core::ChannelzRegistry::~ChannelzRegistry                 +28  [NEW]
      [NEW]     +25 grpc_core::ChannelzRegistry::Shutdown                          +25  [NEW]
      [NEW]     +20 grpc_core::(anonymous namespace)::compare_intptr               +20  [NEW]
      [NEW]      +8 grpc_core::ChannelzRegistry::Default                            +8  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_intptr                   +4  [NEW]
      [NEW]      +4 grpc_core::(anonymous namespace)::copy_channelz_obj             +4  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_intptr                +2  [NEW]
      [NEW]      +2 grpc_core::(anonymous namespace)::destroy_channelz_obj          +2  [NEW]
  +2.5%     +64 src/core/lib/channel/channel_trace.cc                          +64  +2.5%
       +31%     +54 grpc_core::ChannelTrace::ChannelTrace                          +54   +31%
       +16%     +16 grpc_core::ChannelTrace::~ChannelTrace                         +16   +16%

 -------------- SHRINKING                                                  --------------
  [DEL]    -444 src/core/lib/channel/channel_trace_registry.cc                -444  [DEL]
      [DEL]     -99 grpc_channel_trace_registry_register_channel_trace             -99  [DEL]
      [DEL]     -98 [Unmapped]                                                     -98  [DEL]
      [DEL]     -67 grpc_channel_trace_registry_unregister_channel_trace           -67  [DEL]
      [DEL]     -60 grpc_channel_trace_registry_get_channel_trace                  -60  [DEL]
      [DEL]     -47 grpc_channel_trace_registry_init                               -47  [DEL]
      [DEL]     -41 grpc_channel_trace_registry_shutdown                           -41  [DEL]
      [DEL]     -20 compare_intptr                                                 -20  [DEL]
      [DEL]      -4 copy_intptr                                                     -4  [DEL]
      [DEL]      -4 copy_channel_trace                                              -4  [DEL]
      [DEL]      -2 destroy_intptr                                                  -2  [DEL]
      [DEL]      -2 destroy_channel_trace                                           -2  [DEL]

  +0.0%    +184 TOTAL                                                      +3.45Ki  +0.0%


****************************************************************

libgrpc++.so

     VM SIZE        FILE SIZE
 ++++++++++++++  ++++++++++++++

  [ = ]       0        0  [ = ]



```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by grpc-testing** [comment]
```
[microbenchmarks] No significant performance differences
```

**Comment by ncteisen** [comment]
Mac: #11335
Tsan: #15439 (rerunning it to be sure)

**Pull request merged**
