### PR TITLE
fix some spelling mistakes in document

### PR DESCRIPTION
**Pull request by tanjunchen**
@nicolasnoble

### CODE REVIEW

**Comment by tanjunchen** [comment]
@gnossen

**Comment by markdroth** [comment]
LGTM.  Let's make sure tests pass before merging (although they should, since this is not a code change).

**Comment by tanjunchen** [comment]
@markdroth  Thank You

**Comment by tanjunchen** [comment]
@markdroth  What is up with this CI?

**Comment by markdroth** [comment]
The tests take a while to run.

It looks like you need to run ./tools/distrib/clang_format_code.sh.

**Comment by tanjunchen** [comment]
@markdroth  THX  What command can make CI retest

**Comment by markdroth** [comment]
There's no point in re-triggering the tests until you push changes.  We can do that for you once that happens.

**Comment by tanjunchen** [comment]
OK

**Comment by markdroth** [comment]
@tanjunchen We only require two reviews here, and you've gotten them.  But you need to make the sanity check test pass before we can merge this.  Please run `./tools/distrib/clang_format_code.sh`, commit the resulting changes, squash your commits, and then re-push this branch.

**Comment by tanjunchen** [comment]
@markdroth  OK  I Will Do It

**Comment by AspirinSJL** [comment]
Test failures are unrelated.

**Pull request merged**
